inc/auth.class.php, tests/LDAP/AuthLdap.php
Replaces #10013
If you try to log in with a user account while their LDAP server is unavailable, the process for managing users deleted in the LDAP is triggered. I added a check here to ensure the deletion process only starts if there wasn't a connection made to the LDAP.
To recreate, you can change the port on an LDAP server configured in GLPI and then try logging in to a user that syncs with it.
=> Fix unavailable LDAP causing user deletion

src/CommonDBRelation.php, src/CommonDBTM.php, src/Dropdown.php, src/Html.php, src/Migration.php, src/User.php, templates/components/form/fields_macros.html.twig, tests/functionnal/Ticket.php
The `$itemtype::Dropdown()` method allow to easily display a simple dropdown allowing the user to pick an item from a given itemtype.
This kind of dropdowns sadly doesn't support the "multiple" option of select2 which we can use on others dropdown like `showDropdownFromArray()`.
Creating a field that allow the user to select multiple items of the same itemtype is thus painful as you need to use a "dropdown from array", load the values manually, update data in multiple tables, ...
These changes add the 'multiple' option to the `$itemtype::Dropdown()` method to make this kind of fields easier to create.
There is also a new `getFieldsFromLinkTables` method in `CommonDBTM` that can be used to register such "multiple items" fields to allow GLPI to update them and load their values in the …
=> Support 'multiple' option for item dropdowns

.github/actions/test_update-from-9.5.sh, .github/actions/test_update-from-older-version.sh, src/Console/Database/CheckSchemaIntegrityCommand.php
I figured out that checking tokens related to migration by default on `db:check` may pollute results and mays prevent detection of more important inconsistencies (like missing of a field, for instance). See discussion in #10171, user does not give the full result as it had too many differences.
I propose to use opt-in options instead of opt-out options.
=> Do not check migrations by default on db:check

js/glpi_dialog.js
Don't know why, but modal.hide() (or dispose()) doesn't anymore.
=> fix glpi_close_all_dialogs js function

css/includes/components/_global-menu.scss
There is a 1px gap between the collapsed navigation menu and the panel with the sub-items that show up when hovering. Trying to move the mouse from the collapsed menu over to the sub-items causes the hover to be lost and the menu to close.
By using the before pseudo-element the sub-items panel is stretched over the collapsed menu for the hover to work while keeping it the same visually (gap still shows).
=> Fix lost hover with gap with collapsed left menu

CHANGELOG.md, install/empty_data.php, install/migrations/update_9.5.x_to_10.0.0/configs.php, src/Config.php, src/Transfer.php, tests/functionnal/Config.php
This config is not used anymore (probably replaced by `glpi_entities_transfers_id`).
=> Drop unused transfers_id_auto config

inc/commonitilobject.class.php
With a self service user, this button always leads to an "access denied page".
=> remove link always pointing to "denied access" for self service profile

src/Entity.php
`Entity::getUsedConfig()` will not compute inheritence properly if value is `-1`.
=> Fix inheritence value for transfers_id entity config

css/includes/components/_select2.scss
From https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-bidi
> This keyword makes the elements directionality calculated without considering its parent bidirectional state or the value of the direction property. The directionality is calculated using the P2 and P3 rules of the Unicode Bidirectional Algorithm. This value allows the display of data that is already formatted using a tool following the Unicode Bidirectional Algorithm.
Before:
After:
=> Fix text direction in select2

templates/pages/tools/project/gantt.html.twig
Clicking any of the zoom buttons show an error in the console even though they appear to work properly.
It expects a `gantt_radio` class on radio buttons but that class is missing.
=> Add missing class causing JS errors on zoom

inc/computer_item.class.php
Fix ability to add connections to a computer that exist in a child of the computer's entity when the computer is set to be recursive.
=> Allow adding child-entity connection to Computers

inc/commonglpi.class.php
| Fixed tickets | #10011
This is to prevent issues with closing and re-opening the modal without executing an action.
fixes #10011
replaces #10153
This PR only applies to 9.5 since v10 doesn't use jQuery UI for dialogs. There may be a similar fix needed for the Bootstrap modals in v10.
=> Remove MA modal on close

src/Html.php, src/ObjectLock.php
Only applies to GLPI 10.
First commit fixes invalid option names for JS `glpi_confirm` function that caused the Object Lock unlock dialog to not work.
Second commit fixes an issue with a jQuery animation trying to be applied to an element that doesn't exist yet. It doesn't spam the console with undefined property values if the show call is done within a 100ms timeout, but I don't notice the animation either in v9.5 or v10 so I just removed it. I also simplified the injection of the element instead of adding it, hiding it, moving it, and then showing it.
=> Fix Object Locks UI

src/Group.php
| Fixed tickets | #10044
If you don't anonymize agent names, the group name would be empty. I tested all anonymize options after this change and they seem to work as expected now.
=> Fix group name when not anonymized

src/UserEmail.php
Clicking the `+` button to add new emails to a user gives an `Uncaught SyntaxError: missing ) after argument list` error in the console because of unescaped quotes.
=> Fix form control for adding user emails

src/User.php
| Fixed tickets | #10413
Only show the instance using the default email if a user has more than one email.
fixes #10413
=> Show only one instance of Users in actor dropdown

src/Dashboard/Widget.php
=> use card_id to store/retrieve css cache entry for dashboard widgets

src/SNMPCredential.php, templates/components/form/fields_macros.html.twig, templates/components/form/snmpcredential.html.twig
| Fixed tickets | #10150
- Show only relevant fields based on the selected SNMP version.
- Added required marker to snmpversion field (Checked server-side. Client-side validates OK for empty choice; not a big deal).
- Added check that the username field is set if using v3.
- Added ability to specify additional attributes on form fields. Used in this PR to add a data attribute to each field to specify which SNMP version they are used for.
- Removed redundant card headers for SNMP versions.
=> Improve SNMP credentials form

src/Event.php
Any log entries related to the Root Entity do not show an ID and therefore no item link because it ignores any ID of 0 or less. I added an exception for Entities.
=> Fix missing ID in logs for Root Entity

front/helpdesk.faq.php, front/helpdesk.public.php, front/knowbaseitem.form.php, front/knowbaseitemtranslation.form.php, front/preference.php, front/reminder.form.php, front/reservation.form.php, front/reservation.php, front/reservationitem.php, front/rssfeed.form.php, front/ticket.form.php, front/ticket.php, front/tracking.injector.php, front/updatepassword.php, src/Html.php, templates/layout/parts/menu.html.twig
| Fixed tickets | #10041
Previously `Html::helpHeader` didn't support any context links (buttons link add, search, lists, etc).
I added some basic support for them in the context of Tickets.
As a side-effect, the menu template mistakenly thought that the Tickets menu item had children when it only had those context links. I added an extra check in the template to see if there were any real sub-items.
=> Add context links for Tickets in simplified interface

js/common.js
Not sure how much it affects regular users but I find it awkward switching languages during development. Clicking the language link in the top bar once just loads the dropdown. It requires a second click to then open the dropdown to change the language.
=> Automatically open language switcher

src/Inventory/Request.php
Fix wrong constant usage introduced in #10316
=> Fix wrong WAKEONLAN_TASK constant usage

inc/commondbtm.class.php
| Fixed tickets | #2549
When updating `is_recursive` via massive actions, `$this->canUnrecurs` wasn't checked when it should have been.
=> Verify unRecurs possible with massive actions

src/Search.php
Allow to specify the "forcedisplay" search parameter when calling `Search::showList()`.
=> Expose forcedisplay parameter in Search::showList()

install/migrations/update_9.5.x_to_10.0.0/ticket.php, src/CommonITILObject.php, src/CommonITILValidation.php, src/ITILTemplateMandatoryField.php, src/ITILTemplatePredefinedField.php, src/Ticket.php, templates/components/itilobject/fields/global_validation.html.twig, tests/functionnal/ITILTemplate.php
For now, people which have `VALIDATEREQUEST` or `VALIDATEINCIDENT` rights are able to update the `global_validation` without any restriction. It means that, if many people already add a refusal on a ticket, anyone having this right can bypass this and set the `global_validation` to "Accepted".
1. `VALIDATEREQUEST` and `VALIDATEINCIDENT` should only means that a user is able to receive an approval request.
2. `global_validation` field value should be only computed based on approval requests results, or by business rules, but should not be updatable manually by anyone.
=> Remove global_validation field from ITIL forms

src/Gantt/Item.php
| Fixed tickets | #10436
Fix bad class reference for ReturnTypeWillChange attribute (not in current Glpi\Gantt namespace).
=> Fix Gannt for PHP 8.1

inc/api/apirest.class.php
Since commit c811224616af91b7d9040826dd99bc3a461d754d, `APIRest::parseIncomingParams()` is called prior to sanitizing process (API is using unsanitized data and sanitizes it when it is necessary, see 9246382419e886a90e794226658c98c4ed5f9386).
If a payload containing unicode entities was sent, in a multipart request containing uploaded files, these unicode entities were broken by unnecessary call to `stripcslashes`. Thus, if an input field was containing a `"`, JSON decoding was failing, resulting in a `ERROR_JSON_PAYLOAD_INVALID` error.
Invalid JSON due to removal of backslash preceding a quote:
```diff …
```
=> Fix handling of REST API payload

src/Config.php, src/NotificationTarget.php, src/NotificationTemplate.php, tests/functionnal/NotificationTarget.php
Move `NotificationTarget::getSender()` code to a public static function in `Config`.
This allow plugins (or future new core features) to get the computed "From" configuration without having a `NotificationTarget` object.
This is useful if you need to send emails without the full GLPI notifications system.
=> Move  NotificationTarget::getSender() to Config

src/Application/View/Extension/ConfigExtension.php, src/Entity.php, templates/components/itilobject/timeline/form_task.html.twig, templates/components/itilobject/timeline/timeline.html.twig, templates/components/itilobject/timeline/timeline_item_header_badges.html.twig, templates/components/user/picture.html.twig
Fallback to active entity is dangerous in `Entity::getUsedConfig()` as, most of the time, this method is used in a cron context (active entity = root) and the config should be related to the processed object (e.g, the entity of a ticket). I do not see any usage of this fallback, so I propose to remove it.
This usage was introduced in https://github.com/glpi-project/glpi/pull/7015/files#diff-f2baa5b27a17ff7ea8035b11b6933f05a1ed3aa1ea898344284fd73d6dc4e9cfR1238 , but was almost removed in https://github.com/glpi-project/glpi/pull/7374.
=> Remove fallback to active entity in Entity::getUsedConfig()

css/includes/components/itilobject/_timeline.scss
Seen with Formcreator, which adds a timeline action
To have a consistent height of the button I replaced the HTML I tag with a BUTTON tag. I think this is acceptable to switch to GLPI 10,
=> fix button alignement in legacy timeline actions

templates/components/form/inventory_info.html.twig
Display hook after core
Before
After
=> fix(twig): hook at the end of the display

src/Agent.php, tests/functionnal/Agent.php
The SSL module is not enabled by default on the agent.
GLPI should calculate URLs with HTTP first
=> fix(agent): try http first

front/lostpassword.php, inc/api/api.class.php, inc/config.class.php, inc/user.class.php, tests/APIBaseClass.php, tests/functionnal/User.php, tests/router.php, tests/web/APIRest.php
There may be multiple users in GLPI with the same email (there is no unique email constraint).
If one of these users forget his password, the password recovery process fails with "Email address not found" which is confusing as the email address does in fact exist.
This may lead the user (and his administrator) to lose time trying to understand the real issue.
These changes add a different error message for this edge case.
Suggested by @Pieurre
=> Improve forgotten email edge case

CHANGELOG.md, src/Config.php, src/DBConnection.php, src/NotificationTargetDBConnection.php, src/System/Status/StatusChecker.php
Using master/slave wording has bad connotations in English. I propose replacing the wording with main/replica.
Also, there was already multiple places where main/replica was used in the UI in addition to the other wording so this will also unify it more.
I left the config file name as "config_db_slave" for now.
For the status checker, I left the old properties in place to avoid causing issues with monitoring solutions and added the new properties (Not sure how bad it would be to remove the old ones without deprecation). The plain-text output was left as-is since it is already deprecated.
=> Replace user-facing master/slave DB usage with main/replica

ajax/entitytreesons.php
| Fixed tickets | #10043 
Entity switcher was showing child entities even when using a profile assigned non-recursively because no checks for `is_recursive` were done.
=> Fix entity switcher when using a non-recursive profile

ajax/unlockobject.php, inc/objectlock.class.php
| Fixed tickets | #9555
Unlock request was recently change to be a fetch but the payload for this type of request isn't automatically put into the superglobal `$_POST` so not data is available to automatically unlock items.
Forced unlocks continued to work because they were not done via fetch.
=> Try fixing automatic unlocks

src/Agent.php
In some case, a netword card can be reported without a connection type. When this happens, related instantiation_type is not set in database and related ip won't be use to try to contact the agent when requested.
The case I discovered is in a win10 virtualbox vm which reported its emulated ethernet card with the following json:
```
{
"description": "Intel(R) PRO/1000 MT Desktop Adapter",
"ipaddress": "192.168.122.4",
"ipdhcp": "192.168.122.3",
"ipgateway": "192.168.122.1",
"ipmask": "255.255.255.0",
"ipsubnet": "192.168.122.0",
"mac": "08:00:27:A7:B5:3B",
"pciid": "8086:100E:001E:8086",
"pnpdeviceid": …
```
=> Fix guessed agent addresses when netports.instantiation_type is NULL

src/Search.php, tests/functionnal/Search.php
| Fixed tickets | #1508
Example search on Monitors:
Size CONTAINS 70
Example results:
- 70
- 70.5
- 70.55
- 70.05
Example search on Monitors:
Size CONTAINS 70.5
Example results:
- 70.5
- 70.55
=> Smarter decimal contains search

templates/components/form/inventory_info.html.twig
* use larger timeout as server can try a lot of address to contact agent
* remove fa-spin class in complete function so it is removed also on timeout
This will make the feature more reliable and users will know they won't have anymore information when the icon is no more spinning.
=> Update agent informations ajax requests

css/includes/pages/_search.scss, templates/components/search/table.html.twig
Last point of the previously mentionned meeting on glpi10.
On medium screens (we talked about a 22" with 1680*1050 resolution), the search results could be very big.
So on a 1900px breakpoint, i condensed a little the table.
Before (notice the horizontal scrollbar): 
After:
=> compact a little the display of search results on medium screens

install/empty_data.php, install/migrations/update_9.4.x_to_9.5.0.php, install/migrations/update_9.5.x_to_10.0.0/entity.php, install/mysql/glpi-empty.sql, src/Entity.php, src/User.php, templates/components/user/picture.html.twig
Again, following a meeting about glpi 10 with Nicolas, he says me one of its colleagues initials is a bad idea to display (in France context)  in the timeline.
So here is a config to disable display of initials in timeline.
When set to no, user avatar will display a generic picture (the same used for anonymous heldesk):
=> permits to disable display of initials in timeline

ajax/itillayout.php, css/includes/components/itilobject/_layout.scss, inc/define.php, install/empty_data.php, install/migrations/update_9.5.x_to_10.0.0/configs.php, install/mysql/glpi-empty.sql, templates/components/itilobject/actors/field.html.twig, templates/components/itilobject/actors/main.html.twig, templates/components/itilobject/fields_panel.html.twig, templates/components/itilobject/footer.html.twig, templates/components/itilobject/layout.html.twig, templates/components/itilobject/service_levels.html.twig
|Q             | A
Following an internal conversation with Nicolas about layout of itil objects and his usage of GLPI.
So, here is a list of features provided by this PR:
- right panel can be collapsed
- any click on the collapsed state will expand it
- state of collapsed/full expand right panel and also state of accordion is saved into db by ajax query
- we restore the states when constructing html
- status icon is recalled in first accordion heading when status dropdown is considered as not displayed
=> deep control of itil object layout

tests/functionnal/TicketTask.php
When test is executed on last day of month, if next month have less days, it will fail:
```
begin date: 31/01 + 1 month = 31/02 => 03/03
end date: (31/01 + 2 days = 02/02) + 1 month = 02/03
```
=> Fix edge case on TicketTask tests

install/empty_data.php, install/migrations/update_9.5.x_to_10.0.0/ticket.php, src/ITILFollowupTemplate.php, src/Profile.php
add dedicated right for followup 
instead of global dropdown right
| Fixed tickets | #23298
=> fix(right): add dedicated right for followup template

inc/config.class.php, inc/dropdown.class.php, inc/toolbox.class.php, tests/functionnal/Dropdown.php, tests/units/Toolbox.php
Dropdowns with a decimal step are not displayed correctly since b7457cbbba5d063a828502c099c2cff66068bc15.
After fix:
| Fixed tickets | !23325
=> Fix decimal dropdown

ajax/kanban.php, src/Features/Kanban.php
Tasklists plugin has custom URLs for the different contexts it uses in its Kanban. Currently, the URLs in the switcher are hard coded to the item's form URL with the Kanban tab. Same with the global Kanban for an itemtype.
This adds methods to the Kanban trait which can be overridden by different itemtypes to specify different URLs.
=> Allow custom Kanban URLs

css/includes/components/_select2.scss
Move the "ellipsis" hack into `.select2-selection--single` to ensure it is not applied in multiple selection context.
=> Fix select2 rendering in multiple context; fixes #10470

css/includes/components/itilobject/_timeline.scss, templates/components/itilobject/timeline/form_task.html.twig, templates/components/itilobject/timeline/timeline.html.twig
Prevent this:
By moving state checkbox outside of content:
=> prevent overlap of state switch with ul>li in tasks

templates/pages/assets/cable.html.twig
Remove duplicate dropdown type
Before
After
=> fix(cable): remove duplicate dropdown (type)

inc/system/requirement/selinux.class.php
| Fixed tickets | #10504
In some cases the PHP exec function may be disabled for security reasons and this may not be configurable if using a hosting platform. In this case, there would be an exception thrown in the SeLinux requirement checker and cause the installation or update to fail.
=> Handle exec unavailable

js/modules/Kanban/Kanban.js
Bind Kanban class to its Kanban element. This makes it easier for plugins to interact with the Kanban code when they register listeners from outside the core JS file since the Kanban instance(s) aren't bound to the window global.
Ping @tsmr
=> Add Kanban class to kanban element

src/ComputerAntivirus.php
Fix the following error when trying to create a `ComputerAntivirus` item without specifying an expiration date:
```sql
SQL: INSERT INTO `glpi_computerantiviruses` (`computers_id`, `name`, `is_active`, `manufacturers_id`, `is_uptodate`, `antivirus_version`, `signature_version`, `date_expiration`, `date_creation`, `date_mod`) VALUES ('6', 'grd', '0', '0', '0', '', '', '', '2022-02-02 16:35:50', '2022-02-02 16:35:50')
Error: Incorrect datetime value: '' for column 'date_expiration' at row 1
Backtrace :
src/DBmysql.php:1277                               
src/CommonDBTM.php:653                             DBmysql->insert()
src/CommonDBTM.php:1247                            CommonDBTM->addToDB()
front/computerantivirus.form.php:51                CommonDBTM->add()
```
| Q …
=> Fix antivirus creation

ajax/savedsearch.php, js/modules/Search/GenericView.js, src/SavedSearch.php
| Fixed tickets | #10430
Not sure to do the right thing to fix the mentionned issue but on my understanding, with new ajax view for search, there is some double encoding of the query and before the save a bad order of decoding/unscaping.
I'll try to check also #10009 also
=> try to fix saving of search query in savedsearch; fix #10430

src/CommonITILObject.php, tests/functionnal/Change.php, tests/functionnal/Ticket.php
| New feature?  | yes (change in behavior)
| Fixed tickets | #10299
Before GLPI 10 it seemed like you could change a ticket's status from New directly to Solved or Closed without having anyone assigned to it. The behavior that blocked it was not called at least for tickets, but it is now.
I don't understand the purpose of this forced behavior and don't think it is wanted for Tickets, Changes, or Problems.
If it is wanted, I think it would be best to have this be a configurable behavior somewhere else.
=> Fix Ticket status change

src/GLPINetwork.php, templates/install/step7.html.twig, templates/install/update.html.twig
The donations since the introduction of these links doesn't match the cost of "repution".
So let's remove them.
A push to transifex is required.
=> remove donation links

css/includes/components/itilobject/_timeline.scss
| Fixed tickets | #10546
The original bug reported is due to solutions in timeline have a 1em border with a status color (green = accepted, orange = wainting, etc).
For the new solution form, this border doesn't make any sense.
=> do not display status border for new itilsolution form

templates/components/form/header.html.twig
When changing anything on the root entity main form, the hidden `entities_id` field is set to 0 instead of null. This makes it seem like the root entity is a child of itself and the update will fail.
=> Fix editing root entity main form

src/SavedSearch_Alert.php
"itemptype" instead of "itemtype"
=> fix(savedsearch): typing error

templates/components/itilobject/timeline/approbation_form.html.twig
Usage of icons from tabler and fontawesome for the two buttons results in a different spacing.
So let's standardize they
=> use ti icon for solution approbation

src/Ticket.php
This is to avoid having too many values in the dropdown, as it makes it hard to find the correct one even with text filtering.
| Fixed tickets | !23391
=> Show only ongoing problems for "Link to a problem" massive action

src/Database.php
Fix SO to get ```DatabaseInstance``` from ```Database``` list
| New feature?  | yes/
=> fix(database): fix SO to get DatabaseInstance from Database list

css/legacy/includes/_styles.scss
This icon is supposed to be yellow when viewing a saved search.
Probably broken by some HTML change when switching to tabler.
=> Fix edit saved search icon color

src/CommonDBTM.php
Timeline position for doc is never set or always to left.
| Fixed tickets | !23422
=> fix(UI): get timeline position from parent

src/Agent.php
Triggering the [SNMP inventory issue #52](https://github.com/glpi-project/glpi-inventory-plugin/issues/52) case, I tried to update the status of an agent from the agent page after a just imported a printer. As the agent "Item type" was changed to **Printer**, the guessed addresses was only set to the printer name which was including a space ("MP 3055"). After debugging, I saw the agent guessed address was `https://mr 3055:62354/`. As a space in a hostname is an error, Guzzle triggered the `\GuzzleHttp\Exception\RequestException` which is not handled at the moment and an exception was catched in `php-errors.log`:
``` …
```
=> Catch any Guzzle exception for unknown status

src/CommonDBTM.php
When adding a ticket with a validator user, a PHP warning occurs, while checking a string lenght. Actually, the validator is sent as an array
Found in unit tests of Formcreator, when creating a ticket from a target
https://github.com/pluginsGLPI/formcreator/runs/5138373153?check_suite_focus=true#step:8:953
| Fixed tickets | #10602
=> php warning with users_id_validate

src/DbUtils.php, src/Entity.php
| Fixed tickets | #10590
Fixes specific empty IN case for Entity > Assets tab. Also adds a safety type check to `DBUtils::getAncestorsOf`.
=> Fix empty in error in Entity Assets tab

src/Planning.php
| Fixed tickets | #10139
While this fixes this one instance, there may be others. The `showForm` method has an ID parameter that is largely ignored now.
For example, the default CommonDBTM implementation:
```php
$this->initForm($ID, $options);
TemplateRenderer::getInstance()->display('generic_show_form.html.twig', [
'item'   => $this,
'params' => $options,
]);
return true;
```
The showForm function seems like it is more useful in a static context where it would load a specific item from the DB within the function. Instead, the implementation acts like a class instance method that expects the fields from the database to already be loaded into …
=> Fix editing task from planning

package-lock.json, package.json
Dependabot is using `npm` v7 (see https://github.com/dependabot/dependabot-core/blob/36c45ff2717f77bfab7eb2f71c58e66aec260835/Dockerfile#L101), so we need to allow usage of this version to be able to use this service.
Differences between v7 and v8 are minimal. Usage of a new major version number is related to drop of old node version support (see https://nodesource.com/blog/whats-new-in-npm-8).
=> Allow usage of npm v7

src/Dashboard/Grid.php, src/Ticket.php
"Ticket waiting for your approval", "Ticket" should be plural in this case in English/default translation.
=> Ticket[s] waiting typo

ajax/search.php, css/includes/components/_browser_tree.scss, src/Features/TreeBrowse.php
In browse mode (PR #10163) when updating the search criteria, the result was delayed: you had to click twice.
This PR attempts to fix this.
=> fix(treebrowse): criteria update

src/Entity.php
A comment in #10572 mentions following error:
```
glpiphplog.CRITICAL: *** Uncaught Exception TypeError: Argument 1 passed to Entity::handleConfigStrategyFields() must be of the type array, bool given, called in /var/www/html/glpi10/src/Entity.php on line 324 in /var/www/html/glpicurrent/src/Entity.php at line 360
Backtrace :
src/Entity.php:324 Entity->handleConfigStrategyFields()
src/CommonDBTM.php:1507 Entity->prepareInputForUpdate()
front/dropdown.common.form.php:134 CommonDBTM->update()
front/entity.form.php:50 include()
```
Even if I was not able to reproduce, `parent::prepareInputFor*` may return `false`, and, in …
=> Fix handling of entity update refusal; see #10572

src/CommonTreeDropdown.php, src/Dashboard/Grid.php, src/DbUtils.php, src/GLPINetwork.php, src/Html.php, src/Inventory/Asset/NetworkPort.php, src/Item_Devices.php, src/Marketplace/Api/Plugins.php, src/PCIVendor.php, src/ProfileRight.php, src/USBVendor.php
While searching why some tests are randomly failing, I came to the conclusion that it may be an issue with cache read operations. Indeed following error in `DbUtils::getSonsOf()` can only happen when `$GLPI_CACHE->get($ckey)` returns a null value when `$GLPI_CACHE->has($ckey)` return true.
```
> There are 2 uncompleted methods:
=> tests\units\Glpi\Csv\LogCsvExport::testGetFileName() with exit code 255:
==> output(143) "Uncaught Exception TypeError: array_replace(): Argument #1 ($array) must be of type array, null given in /var/glpi/src/DbUtils.php at line 895"
=> tests\units\Glpi\Csv\LogCsvExport::testGetFileContent() …
```
=> Prevent race condition on cache operations

install/migrations/update_9.5.x_to_10.0.0/dashboard_filters.php
| Fixed tickets | #10577
As the `glpi_dashboards_filters` table creation query is synchronous and `glpi_dashboards_dashboards.users_id` field creation is asynchronous, if migration fails at some point, the `glpi_dashboards_dashboards.users_id` field may not be created, even if migration is replayed. Its creation should not be conditionned to the `glpi_dashboards_filters` table existence.
=> Fix edge case on dashboard filters migration; fixes #10577

src/Group.php
When a new group is created, all visibility flags are set to "yes" except the `is_task` flag (see image below).
With proposed change, this flag will act as all other flags in group creation form.
=> Fix default visibility value in group creation form; see #10582

src/AuthLDAP.php
It should fixes warning such as:
`[2022-02-16 09:18:02] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "mail" in E:\GLPI\src\AuthLDAP.php at line 4327
Backtrace :
src\AuthLDAP.php:2774                              AuthLDAP::getFieldValue()
src\User.php:4965                                  AuthLDAP::ldapImportUserByServerId()
src\MailCollector.php:1026                         User::getOrImportByEmail()
src\MailCollector.php:759                          MailCollector->buildTicket()
src\MailCollector.php:1821                         MailCollector->collect()
src\CronTask.php:1016                              MailCollector::cronMailgate()
front\cron.php:82                                  CronTask::launch()`
When a configured attribute does not exists on an LDAP object.
| Q …
=> Fix "Undefined array key" when attribute does not exist in LDAP

.github/workflows/cancel_workflow_runs.yml, .github/workflows/ci.yml
1. Cancel all but latest
Currently, only previous workflow runs are canceled. It means that if a new workflow is scheduled multiple times without an available worker to trigger it, previous runs will not be cancelled and will all be run. Using the `all_but_latest` option fix this.
2. Handle workflows triggered by PR from fork
As far as I understand, moving the cancel step in a dedicated workflow will permit it to be executed from the fork context, and so it will be able to cancel workflow runs triggered from this fork.
3. Handle coverage workflow
For more information, see …
=> Enhance cancel-workflow action configuration

templates/components/itilobject/answer.html.twig, templates/components/itilobject/timeline/timeline.html.twig
The `template` property for timeline itemtypes is only checked if it is defined and then the `showForm` method is always called on the `item` instead of just directly including the defined template. It seems like the template should be used directly if defined, otherwise it should fall back on `showForm`.
=> Fix unused timeline item templates

front/ticket.php, templates/components/search/display_data.html.twig
The map view currently doesn't support fluid search. A JS error is logged in the console but the view otherwise loads. The first commit removes the error by not initializing the fluid search in this view.
The second commit fixing the handling of the automatic ticket list refresh when in this map view or when the fluid search otherwise fails to initialize. In these cases, it falls back to a page reload like it did in previous versions.
=> Map view fixes for new fluid search

src/Search.php
Fixes following error:
```
glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: class_uses(): Argument #1 ($object_or_class) must be of type object|string, null given in /var/www/glpi/src/Toolbox.php at line 3320
Backtrace :
src/Toolbox.php:3320                               class_uses()
src/Search.php:1750                                Toolbox::hasTrait()
src/Search.php:136                                 Search::displayData()
src/Search.php:100                                 Search::showList()
front/allassets.php:46                             Search::show()
```
=> Fix error on global search view

src/CommonITILObject.php
In #10114, @cedric-anne suggested the following format for ITIL items tabs:
For some reasons the `(179)` part gives me "warning, unread items" vibes like a typical mailbox tab:
Maybe adding a `#` prefix makes it clearer that it's a ticket reference and avoid any confusion ?
=> Add prefix to tickets number

templates/components/itilobject/timeline/form_validation.html.twig
| Fixed tickets | #10509
This field can exist in timeline and in Approvals tab.
Alternate proposal would be to remove the ability to request an approval from the Approval tab. Going further, remove the tab completely and move the global validation settings to the panel in the main tab/timeline.
=> Fix duplicate element ID for validation forms

src/Migration.php
I'm trying to run this very simple migration:
```php
$this->migration->createLinkTable($table, PluginFormcreatorForm::class, $class);
$this->migration->addField($table, 'uuid', 'string');
```
It fails because `migration->addField()` execute its queries directly, thus bypassing the pre/post query system offered by its own class.
It is unexpected as any `addPreQuery` should be ran before any other migrations.
For now I've only changed `migration->createLinkTable()` to avoid this issue but maybe in the future any methods from `migration` should respect pre/post query orders.
=> Use direct query for createLinkTable

src/Html.php
I need this to make an unit test on Formcreator without duplicating the moved code in tests.
https://github.com/pluginsGLPI/formcreator/pull/2613
=> isolate helpdesk menu generation in method

src/AbstractRightsDropdown.php, src/Dashboard/Grid.php
The `AbstractRightsDropdown` class was added in #9348 to makes it easier to create "rights restriction" dropdown containing entities, users, groups, ...
It was only used for the "Share dashboard" feature at the time.
I've now been using it for another development and I needed the two following improvements/fixes to make it works properly:
- The input need to be an array ("input_name[]') or no values will be retrieved in the HTML form (this issue wasn't detected when using the "Share dropdown" feature because it does not submit the form but use instead some custom js/ajax). 
- Move the code responsible for flattening the values into the abstraction layer, no need to have it in multiple places.
| BC breaks? …
=> Fix/Improve AbstractRightsDropdown

js/common.js
| Fixed tickets | #10726
In context of the approval form, whichever validator type you chose first (user or group) would cause the dynamic "__VALUE__" placeholder to get statically set. If you tried changing the validator type this value would be the static itemtype and not "__VALUE__" anymore. This commit puts the resolved parameters into a temporary object instead of modifying the original values.
=> Do not override Ajax element update parameters

ajax/central.php
This was noticed while checking #10654 (Issued reported for 9.5.X but I was testing with GLPI 10). I noticed reminders were not showing at all in GLPI 10 on the central page. This only applies to master. The issue with public reminder visibility would still need checked and presumably fixed for 9.5.X and 10 both as I don't think the back-end code that gets the data for the lists changed.
=> Re-add missing reminders on Central page

src/Console/Application.php, src/Console/System/CheckStatusCommand.php, src/System/Status/StatusChecker.php
If DB is not available, the status check shows a PHP warning before the status check output. For JSON output, this results in an invalid JSON string. It makes sense to suppress these warnings in the console and status check contexts.
=> Fix DB service status check output

inc/itilcategory.class.php
| Fixed tickets | #10484
When you don't have any rights for Problems, the wrong dropdown option was being removed from the ITILCategory itemtype. I fixed that and refactored the logic to make it less likely this could be broken again. Previously it was unset from the array by a static index.
This does not include any additional visibility restrictions as that would be a new behavior. I don't know the reason only the visible for problems dropdown is handled like this but I can add other visibility restrictions in a new PR for GLPI 10.
=> Fix visible for problem dropdown visibility

src/Search.php
| Fixed tickets | see #10680
1. As warnings are now fetched automatically on each query, the `group_concat_max_len` was not anymore increased when first attempt failed.
However, I am not sure it is relevant to increase this value step by step, as, anyways, if this value is too small, it will be increased and the query will be done a second time. Also, unless I miss something, setting this value to its max even when it is not really necessary should not lower performances. So, IMHO, setting this value to its maximum for everyone is the simplier solution.
2. Breaking the 61 joined tables limit triggers an error. Dedicated code was based on …
=> Fix handling of max concat length and max joins in search; see #10680

css/includes/_fonts.scss, package-lock.json, package.json, webpack.config.js
Fetching Inter font from `@fontsource/inter` #10698 was finally not usefull, as is is now bundled in `@tabler/core` since #10646.
=> Use Inter font bundled in @tabler/core

templates/components/itilobject/add_items.html.twig
| Fixed tickets | #10700
Selecting an item from "My elements" was not working. This fixes it.
Note: in case an item is selected from "My elements" and "All elements", the item from "My elements" will be the one used rather than both being used. I believe this was the behavior in previous versions.
=> Fix ticket item selection

src/DbUtils.php, tests/functionnal/DbUtils.php
In some case, in plugins, an itemtype may be retieved from URL (i.e. `ticket.form.php` -> `ticket`). Since introduction of PSR-4 class files naming convention, `getItemForItemtype('ticket')` will return false.
I propose to make this method case insensitive, which corresponds to the GLPI 9.5 behaviour, as there I did not find any other way to get the item class that corresponds to the current URL.
=> Handle PSR4 classes case sensitivity in getItemForItemtype

src/Ticket.php
Fix function name called
```canAssignTome``` instead of ```canAssignToMe```
As 
```php
function canAssignToMe() {
if (isset($this->fields['is_deleted']) && $this->fields['is_deleted'] == 1
|| isset($this->fields['status']) && in_array($this->fields['status'], $this->getClosedStatusArray())
) {
return false;
}
return (Session::haveRight(self::$rightname, self::STEAL)
|| (Session::haveRight(self::$rightname, self::OWN)
&& ($this->countUsers(CommonITILActor::ASSIGN) == 0)));
}
```
=> fix(code): fix function name

templates/dropdown_form.html.twig
| Fixed tickets | #10753
When I changed how `field_params` was handled in #10617 (fixed its scope), I didn't realize this variable was used later in the template for the picture fields.
=> Fix model creation

css/includes/components/itilobject/_timeline.scss
| Fixed tickets | UX issue of #10558
Text content inside a flexbox doesn't treat trailing spaces properly. Solution is to use `inline-block` display, but keep the other "tabler badge fixes". I also increased the negative margin as the gap between the badge and the bottom of the form grew when I changed the display.
=> Fix spacing between text and user link in timeline badge

src/System/Status/StatusChecker.php
Adds new messages for service statuses to be able to provide more information in an external monitoring solution like Nagios.
- DB (Main) will show a connection failed message when there is a problem
- DB (Replicas) will show a replication delay is too high message when there is a problem
- LDAP (Each server) will show a connection failed message when there is a problem
- LDAP (Summary) will always show a summary of the LDAP servers `OK: %d, WARNING: %d, PROBLEM: %d, TOTAL: %d`
- IMAP (Each server) will show a connection failed message when there is a problem
- IMAP (Summary) will always show a summary of the IMAP servers …
=> Add more status checker messages

src/Search.php
| Fixed tickets | #10563 
Navigation through items is not made to be used in a global search context. Indeed, counters and available elements are partitionned by itemtypes, so previous/next/first/last items and items count are always refering to the type of the currently displayed item, whenever other item types are present in the global search results.
Fixing navigation would require lots of refactoring, so I propose to just hide navigation features when an item is shown from a global search context.
=> Hide navigation though items in global search context; closes #10563

src/CartridgeItem.php, src/ConsumableItem.php, src/Contract.php, src/Entity.php, src/Infocom.php
When used in a tree having many levels, `Entity::getUsedConfig()` mays require many DB requests to be able to give a result. Thus, it can be either call many times for a same entity on a page (e.g the `anonymize_support_agents` is fetched for each user name display in Ticket page) or call for many entities on a cron task (see #9137).
First commit fetch the whole values required to compute the inherited value for an entity in a unique request. It may increase the fetched data from the DB, but, unless someone has thousands levels in its entity tree, it should not be an issue.
Second commit add a caching logic, in order to …
=> Enhance performances on Entity::getUsedConfig() usage

tests/GLPITestCase.php, tests/units/Html.php
Exception message is not exactly the same in all PHP versions. Indeed, prior to PHP 8.1, class name and method name were included in exception message, but are not anymore present in PHP 8.1.
I also enhance failure message to be able to easilly detect why logs checks are failing.
=> Fix tests on PHP 7.4 and 8.0

inc/domain.class.php, tests/functionnal/Domain.php
Currently, domain alerts, which are sent for each entity that has alerts activated, contains expired domains from all entities.
=> Fix domains entity filtering on domains alerts

src/Entity.php
1. Display existing/inherited value of `agent_base_url` field (field was blank even if a value was stored in DB).
2. Fix empty checks (`empty($var) == 0` was not a correct check).
3. Display inherited value even on root entity when configuration is `Entity::CONFIG_PARENT`. It should not happens, but could permit to detect data inconsistency.
=> Fix entity config display

src/Dropdown.php
Since enabling SQL warnings, the dropdown search breaks because it always tries to match the search text with the ID column without any type checking. MySQL throws a "'Truncated incorrect DOUBLE value" warning. I added type checking and if the search text is not an integer or integer string, no attempt will be made to use the ID column in the search.
This may fix #10769
=> Fix dropdown search

src/System/Requirement/ExtensionConstant.php, src/System/RequirementsManager.php, tests/units/Glpi/System/Requirement/ExtensionConstant.php
Added new requirements check for existence of the "SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES" constant. The PHP extension only defines this is it exists from the libsodium library (exists in 1.0.12 and newer only) and just directly assigns its value from the one provided by the library.
The compatibility library used does define this constant using a hard-coded value but only for PHP 7.2 and lower it seems.
Also, given that PHP is compiled by default with the sodium extension, it is most likely that users will be running the extension and will be reliant on the libsodium library version.
=> Check required libsodium constant as version check

templates/components/itilobject/timeline/timeline.html.twig
Fix : 
I don't remember why we had `.row` class here
=> fix overflow between avatar and content of timeline-item

CHANGELOG.md, front/dropdown.common.form.php, front/dropdown.common.php, src/CommonDBTM.php, src/CommonDevice.php, src/CommonDropdown.php, src/Entity.php, src/FieldUnicity.php
Fix #10593
`CommonDropdown::displayHeader()` handle breadcrumbs using the item properties: 
Instead of overriding these properties, some item override the `displayHeader` method, for example:
These items should redefine `$first_level_menu`, `second_level_menu` and `$third_level_menu` properly instead of changing this function.  
I've set the function to final to avoid this but it may trigger some fatal error if some plugins are doing the same thing.  
Maybe a depreciation warning instead ? Or is it OK since we are doing a major update from 9 to 10 ?  
| Fixed tickets | #10593
=> Fix displayHeader misuse

src/Change_Item.php, src/Console/Migration/AbstractPluginToCoreCommand.php, src/Console/Migration/DatabasesPluginToCoreCommand.php, src/Console/Migration/DomainsPluginToCoreCommand.php, src/Document_Item.php, src/Domain_Item.php, src/Item_Problem.php, src/Item_Project.php, src/Item_Ticket.php
I transformed the database plugin migration to make it non destructive. It means that it will not erase existing core databases, and that it can be replayed if it fails in the middle of the migration.
I also refactored the domains plugin migration, as lot of code can be shared.
Now, it will be easier to produce plugins migration commands.
=> Make database plugin migration non destructive

inc/commondbtm.class.php, inc/massiveaction.class.php, inc/rule.class.php, inc/user.class.php, tests/functionnal/Appliance.php, tests/functionnal/Certificate.php, tests/functionnal/Computer.php, tests/functionnal/Entity.php, tests/functionnal/Monitor.php, tests/functionnal/NetworkPort.php, tests/functionnal/Project.php, tests/functionnal/Rule.php, tests/functionnal/RuleSoftwareCategory.php, tests/functionnal/Software.php, tests/functionnal/Ticket.php, tests/functionnal/User.php
Cloning an entity fail silently because entity names must be unique.
To fix this, I've improved the cloning system to make sure it always set unique name to new items.
For example, if you clone an item named "Test", the clone will be named "Copy of Test (1)".
If "Copy of Test (1)" already exist then we move on to "Copy of Test (2)" and so on.
This also makes it easier to spot cloned items (and renamed them manually as needed):
| Fixed tickets | !23470
=> Fix clone name uniqueness

src/Console/Migration/TimestampsCommand.php, src/Update.php
When a table structure is changed (i.e. altering any field type), existing "zero dates" (i.e. `0000-00-00 00:00:00`) are trigerring errors as we do not anymore remove the `NO_ZERO_DATE` flag from `sql_mode`:
```
SQL Error "1292": Incorrect datetime value: '0000-00-00 00:00:00' for column 'date_creation' at row 2 in query "ALTER TABLE `glpi_domains`  	 MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL; "
```
To prevent this, I propose:
1. to fix existing "zero dates" in timestamps migration. This is anymay mandatory if we want this migration to not fail in this case;
2. to set the `sql_mode` to empty during …
=> Prevent errors on existing ZERO_DATE values

src/AbstractRightsDropdown.php, tests/units/AbstractRightsDropdown.php
Suggested by @btry in https://github.com/pluginsGLPI/formcreator/pull/2615#discussion_r811924588.
The `AbstractRightDropdown` dropdown will post "flattened" values in the `$_POST` data, like this:
```php
[
'users_id-3'
'users_id-14
'groups_id-2'
'groups_id-78'
'profiles_id-1'
]
```
Each front files handling these values must parse this array to get the matching ids for each expected itemtype.
```php
foreach ($_POST['restrictions'] ?? [] as $restriction_values) {
// Split fkey and ids
$restriction_values = explode("-", $restriction);
$fkey = $restriction_values[0];
$value = $restriction_values[1];
// Parse values
if ($fkey == User::getForeignKeyField()) {
$input['users'][] = $value;
} elseif ($fkey == Group::getForeignKeyField()) {
$input['groups'][] = $value;
} elseif ($fkey == …
```
=> AbstractRightDropdown value parsing in front files

css/includes/_highcontrast.scss, css/includes/components/_fileupload.scss, css/includes/components/_gantt.scss, css/includes/components/_global-menu.scss, css/includes/components/_racks.scss, css/includes/components/itilobject/_timeline.scss
Gantt tooltip `left` style removed completely as it wasn't working with its invalid value and no units make it display correctly. Without the property, the tooltips show OK.
=> Minor CSS Fixes

templates/components/kanban/item_panels/default_panel.html.twig
The default padding for list-group-item is a bit too high for the team member list for Kanban. Adding `p-2` to those elements, reclaims some wasted space while still having enough to separate items.
=> Decrease Kanban team member padding

src/Item_Devices.php
| Fixed tickets | #10778 
When you have a component in the Assets menu and then try adding a component from that page, it opens the Item_Device form. This form doesn't allow you to set the linked item and it doesn't handle an empty itemtype. Adding an Item_Device requires this field to at least be set to an empty string.
=> FIx creating item_device from form

src/Dropdown.php, src/Html.php
The buttons to the right of some dropdowns (info and add) were only clickable over the icon itself. I found that the area the tooltip showed for "info" was also just over the icon.
=> Fix dropdown buttons click area and tooltips

src/KnowbaseItem_Item.php
| Fixed tickets | #10794
Since 8fc5d4f67700de642e63b8845066306c4abca2e3 the date field for KnowbaseItem is now standardized with the others to be `date_creation`.
=> Fix date field name

src/AbstractITILChildTemplate.php, src/CommonITILObject.php, src/CommonITILTask.php, src/ITILFollowup.php, src/ITILSolution.php, tests/functionnal/ITILFollowup.php, tests/functionnal/ITILSolution.php, tests/functionnal/TicketTask.php
Task and followup templates are handled at the ITILObject level on creation or in the UI by changing fields after selecting a template. However, there is no way to programmatically add a task or followup from a template.
This is needed for a plugin. Still a WIP.
=> Handle templates at child-item level

install/empty_data.php, install/migrations/update_9.5.x_to_10.0.0/configs.php, src/Config.php, src/Update.php
Follows #10783.
With this logic, updates GLPI that has been initiated on GLPI 10.0+ will not use the empty `sql_mode`.
It would also permit, in the future, to propose a command that fixes legacy data, and to set this flag to 0 on GLPI that has been initiated in older versions.
=> Do not support legacy data (ZERO_DATE) on future GLPI instances

css/includes/_base.scss, css/includes/_fonts.scss, package-lock.json, package.json, webpack.config.js
Inter font has finally been removed from tabler bundle (see https://github.com/tabler/tabler/pull/1048). I had to revert d4a75ab6b046053ea34544820a50f08c3dd06c5e .
=> Update @tabler/core to 1.0.0-beta9

src/User.php
| Fixed tickets | #10532
If an LDAP user's manager is not in GLPI, the import would fail if this field is mapped.
New behavior skips trying to set the user's supervisor if they don't exist in GLPI. This should get mapped whenever they log in or the user syncs again if the manager is added by that point.
=> Fix user import when manager not in GLPI

templates/layout/parts/profile_selector.html.twig
| Fixed tickets | #10652
Add full name as title/tooltip.
Prepend child entity short name with "... >" to indicate it is not top-level.
=> Show short entity name in switcher

src/Update.php, tests/functionnal/Update.php
Related to #10780 .
This method has been introduced in GLPI 10.0 and is not used in plugins yet. It was public for tests purposes, but should not. Making it private will permit to change its signature in the future without introducing BC breaks.
=> Make Update::getMigrationsToDo() private

src/Dashboard/Grid.php
Error mey occurs from PHP >= 8.0
The ```call_user_func_array()``` function will use they array keys as parameter names, and this can be a breaking-change in certain situations, where the parameter array is an associative array with non-numeric keys. 
see https://php.watch/versions/8.0/named-parameters#named-params-call_user_func_array
| Fixed tickets | #23519
=> fix(dashboard): prevent error from php 8

src/Rule.php, src/RuleAsset.php, src/RuleCollection.php, src/RuleDictionnaryPrinter.php, src/RuleDictionnarySoftware.php, src/RuleImportComputer.php, src/RuleImportEntity.php, src/RuleMailCollector.php, src/RuleRight.php, src/RuleSoftwareCategory.php, src/RuleTicket.php, tests/functionnal/Rule.php, tests/functionnal/RuleDictionnarySoftware.php, tests/functionnal/RuleSoftwareCategory.php, tests/functionnal/RuleTicket.php
Add new global rule action for `Stop rules processing` which will tell the engine to skip all other rules in the collection.
Currently, some rule collections are set to stop after the first match but the default and the case for most is to run all matching rules. With this new option along with the existing ability to change the rule priority/order, this will give the user more control over which rules run and when they run.
This does not stop other collections from running for the same event.
=> Add rule action to skip remaining rules

css/standalone/dashboard.scss
In French for example the arrow was overlapping the text in the word "Assistance".
=> Fix dashboard dropdown being smaller than the text

src/DBmysql.php
`$DB->truncate()` was introduced in GLPI 10.0 and is used only once. Another solution could be to drop this method (or to deprecate it and to remove it from the changelog).
=> Use MySQL delete operation to truncate tables

templates/components/infocom.html.twig
| Fixed tickets | #10832
Best checked without whitespace changes. The form should be inside the `.asset` div and there were missing flex divs.
=> Fix infocom form display

inc/search.class.php
| Fixed tickets | #8637 
I also noticed that when viewing the search list of dropdowns with translations, it uses the default translation only and not the one for the current language. Looking at the Search engine code, this seems intentional and only shows translations for meta criteria?
=> Fix dropdown results with translated field shown

src/CommonITILObject.php, templates/components/itilobject/footer.html.twig, templates/components/itilobject/timeline/sub_documents.html.twig
| Fixed tickets | #10839
Since #10647, the timeline relies on the defined timeline itemtypes for rendering. "Document_Item" was not in this list presumably so it wouldn't be in the menu to add it. However, it is required for files added during the ticket creation and for the Screenshot plugin. I added it to the list of timeline itemtypes but also added a flag that lets you hide certain types from the menu.
=> Fix showing documents in timeline not added by subitem

templates/components/itilobject/layout.html.twig
I was annoyed at the display changes that put the ticket description input at the bottom:
I looked into it and it seems unintentional, a variable is misspelled so the condition that apply the correct flex direction is never true.
After fix:
=> Fix commonitil form display

templates/components/itilobject/mainform_open.html.twig
While testing #9828 to see if there was a bug that would need fixed for GLPI 10, I noticed that I couldn't add tasks from an ITIL template even without missing a mandatory field at first. After re-adding the missing hidden field (was present in 9.5), it worked as expected and I couldn't recreate the issue reported in #9828 at all on v10.
=> Fix adding tasks from ITIL templates

src/Features/Clonable.php, tests/functionnal/Computer.php, tests/functionnal/Software.php
Creating an asset from a template always added "(copy)" to the name even though I was specifying the name. Automatic generation of names should probably not happen if a name is specified in `override_input`.
=> Fix item name created from template

templates/layout/parts/page_header.html.twig
| Fixed tickets | (Related to #10580)
When the menu is expanded enough to cover the screen, the vertical menu wouldn't allow you to scroll past the menu to see the page content while the horizontal menu would.
=> Improve scrolling with vertical menu on small screens

src/Dashboard/Provider.php, src/Toolbox.php, tests/functionnal/Glpi/Dashboard/Provider.php, tests/functionnal/Toolbox.php
| Fixed tickets | #10863
Also added logic to avoid adding empty parameters to the query string. If there were no filters in the dashboard, I noticed that there would be an empty parameter leading to "&&" and breaking the url.
=> Fix dashboard card link for URLs with existing params

templates/components/form/fields_macros.html.twig
In the contracts, the hours (in Support hours) were recorded in the base but not displayed.
| Fixed tickets | !23559
=> fix(contract): display of recorded hours

src/CommonITILObject.php
During tests on #10862 , I may have produced inconsistant data, and result was that my whole dashboard was broken, due to an SQL error.
```
SQL: SELECT COUNT(DISTINCT(`glpi_tickets`.`id`)) AS `cpt` FROM `glpi_tickets` WHERE `glpi_tickets`.`is_deleted` = '0' AND `glpi_tickets`.`status` IN ('1', '2', '3', '4') AND (((IF(`glpi_tickets`.`time_to_resolve` IS NOT NULL
AND `glpi_tickets`.`status` <> 4
AND (`glpi_tickets`.`solvedate` > `glpi_tickets`.`time_to_resolve`
OR (`glpi_tickets`.`solvedate` IS NULL
AND `glpi_tickets`.`time_to_resolve` < NOW())),
1, 0)) OR …
```
=> Fix SQL warnings during TTR/TTO late state computation

src/CommonDBTM.php, src/CommonITILTask.php, src/Config.php, src/ITILFollowup.php, src/ITILSolution.php, tests/functionnal/Computer.php, tests/functionnal/NetworkPort.php
| Fixed tickets | #8980
NetworkPort's prepareInputForUpdate was calling `NetworkPort::splitInputForElements` which was removing all non-fields that didn't start with an underscore. This meant that the `update` input was being removed and later in the update method, it was failing that check which would have cleared the saved input.
This fix I propose sets the `_update` property in `CommonDBTM::update` just before `prepareInputForUpdate` is called while leaving the original `update` property. Then afterwards, the `update` property is removed. This should fix the reported issue without too much risk in causing a break in compatibility.
=> Fix removal of saved NetworkPort input

inc/commondbtm.class.php
| Fixed tickets | #9931
`CommonDBTM::getFromDB()` is loading the object based on the value of its index field (i.e. the field having the name returned by `CommonDBTM::getIndexName()`).
=> Fix satisfaction survey notification; fixes #9931

src/Ticket.php, tests/functionnal/Ticket.php
Found while looking into #9931 but may not be related.
The code looks like it is removing any survey that has the same ID as the current ticket rather than deleting old surveys for this ticket.
=> Fix old survey clean

js/modules/Kanban/Kanban.js
| Fixed tickets | #10900
During a background refresh of the Kanban, any open Add or Bulk Add form is copied outside the DOM and then added back in. During the preservation, the jQuery `clone` method is used but the option to clone events wasn't enabled so after the restore, the Add button in the form acted like a regular submit button instead of using the custom handler.
=> Preserve form events during Kanban refresh

src/IPNetwork.php
Related to #2573. IPNetworks have a "virtual" field `network` used during add and update and it sets the different address and netmask fields from it. When you retrieve an IPNetwork over the API, you see all the address and netmask fields and it may cause confusion when you try using that schema to update one or create a new one.
Currently, you would get "Invalid network address" error if you don't use `network` but that could make you think one of the address fields you set is wrong.
New message should help indicate that there should be a `network` property in CIDR notation.
=> Improve error message when network property missing

install/migrations/update_9.5.x_to_10.0.0/schema_fixes.php, src/Rule.php, src/RuleRight.php
| Fixed tickets | #10903
`showNewRuleForm()` is used only on rules that cannot be assigned to entities. These rules are not using the `entities_id` field.
=> Replace usage of -1 entities_id rules; fixes #10903

src/NotificationEventMailing.php, src/NotificationTarget.php
| Fixed tickets | #10908
`usertype` is automatically computed by `NotificationTarget::addToRecipientsList()` as long as `users_id` is defined and is related to an active user.
=> Fix handling of admin target in notifications; fixes #10908

src/Central.php, src/Config.php, src/Dashboard/Dashboard.php, src/Dashboard/Grid.php, src/Search.php
| Fixed tickets | #10663
Core issue this tries to fix is how the Dashboard dropdowns in the user preferences work. Currently there are two contexts for dashboards (core and mini_core) where everything is thrown into the "core" context except the one default mini dashboard for Tickets. I'm not sure if there is a way to build a custom mini dashboard or not.
The dropdown asking what you want your mini Ticket dashboard to be didn't specify the context and the underlying code didn't support specifying it either.
The Grid class used a static class property to define the context but it was being set in a constructor. This didn't make sense to me. I …
=> Rework dashboard dropdown

src/CommonDBTM.php, src/CommonITILTask.php, src/KnowbaseItem.php, src/Search.php
`RichText::getTextFromHtml()` returns by default a "plain text" that may contains html special chars, like `<` or `>`. It is important, in HTML rendering context, to indicates that expected result has its entities encoded, to prevent any display or security issue.
=> Fix entities encoding of RichText::getTextFromHtml() in HTML rendering context

src/Console/Database/UpdateCommand.php
It does not seems relevant to force usage of `--allow-unstable` option on update command when current version is not a stable version.
=> Prevent requiring --allow-unstable when DB current version is not stable

src/OlaLevel_Ticket.php, src/SlaLevel_Ticket.php
| Fixed tickets | #6010
When trying to apply a SLA/OLA on a solved ticket, no new escalation level is assigned and none is removed. This causes the `replayForTicket` function to loop indefinitely and call `doLevelForTicket` for the same level.
This is an alternative to #9740 where here we only check if it tries applying the same level twice in a row.
I'm not sure how this could be regression tested since the previous behavior was an infinite loop.
=> Fix SLA/OLA replay infinite loop

src/MassiveAction.php
| Fixed tickets | #10939
Fix undefined `status` key error when trying to get whitelisted massive actions for single items when there isn't an item (Not in single item context).
Also, I didn't see any way to use these single Massive Action options in the ITILObject UI anymore.
=> Fix undefined key in Ticket MA

src/CommonGLPI.php
Related to #10292.
Since #10114, a new form option `loaded` was added during the loading of a tab and this caused the saved input of a form to be overridden with this one value before it could be restored.
=> Fix restore of saved input

src/CommonITILObject.php, tests/functionnal/Glpi/ContentTemplates/Parameters/ChangeParameters.php, tests/functionnal/Glpi/ContentTemplates/Parameters/ProblemParameters.php, tests/functionnal/Glpi/ContentTemplates/Parameters/TicketParameters.php, tests/functionnal/Ticket.php
Fix the autofilling of `_users_id_requester`without regarding the user preferences
=> remove autoset of _user_id_request without config, see #10846

src/Marketplace/Controller.php, src/Plugin.php, tests/functionnal/Plugin.php
Not used yet, but will be used soon to give ability to plugins to prevent automaticall executuion of their install function when downloaded from marketplace.
=> Add ability to define plugin options

src/Console/Migration/AppliancesPluginToCoreCommand.php, src/Console/Migration/RacksPluginToCoreCommand.php, tools/deleteorphanlogscommand.class.php
Prior to #10368, these 3 command had a default value to `false` in launch confirmation interaction process. This PR just put back behaviour that was existing in GLPI 9.5.
=> Fix default confirmation values on commands

js/modules/SearchTokenizer/SearchInput.js, package-lock.json, package.json, tests/js/SearchTokenizer/SearchInput.test.js, tests/js/jest-setup.js, tests/js/jest.config.js
I'm working on something that may use the existing JS code used by the new filtering/tagging system used by the Kanban and it would require inheriting several options from the original input.
I added support for adding custom attributes, data attributes, and classes either statically or by copying them directly from the original input element.
JS tests were updates and Kanban filter was manually tested again just be be sure I didn't somehow break it.
=> Allow custom options for SearchInput JS

front/ticket.form.php, src/CommonITILObject.php, src/Ticket.php, tests/functionnal/Ticket.php
| Fixed tickets | #10364
Fix for #10364 done for GLPI 10. I think the only issue in 9.5 was the UPDATE right check in the front file. For GLPI 10, there were other issues due to using `_actors` instead of individual fields for each actor type (_itil_assign`).
=> Allow assigning without UPDATE right

templates/components/infocom.html.twig
Wrong item used with `autoNameField` so value wouldn't show.
Reported on Forum: https://forum.glpi-project.org/viewtopic.php?id=283122
=> Fix Immobilization number infocom field

templates/components/itilobject/timeline/form_validation.html.twig
User and Group options for approval dropdown weren't using localization functions.
=> Fix missing validator type localization

templates/components/itilobject/timeline/timeline_item_header.html.twig
Hide "Promote to Ticket" option for tasks and followups in the timeline if the user doesn't have permission to create Tickets.
=> Hide promote to ticket when cannot create Tickets

ajax/getAbstractRightDropdownValue.php, ajax/getShareDashboardDropdownValue.php, src/AbstractRightsDropdown.php, src/ShareDashboardDropdown.php, tests/bootstrap.php, tests/units/AbstractRightsDropdown.php, tests/units/ShareDashboardDropdown.php
The ajax front file used to load the values of `AbstractRightDropdown` was directly referencing `ShareDashboardDropdown`.
This was not a problem when `ShareDashboardDropdown` was the only implementation of `AbstractRightDropdown` but this is no longer the case since https://github.com/pluginsGLPI/formcreator/pull/2615.
With these changes, each implementation of `AbstractRightDropdown` must have their own ajax front file where they:
* Include the parent ajax file `getAbstractRightDropdownValue.php` which contains the shared logic
* Do their own additional right checks (user who can't access the dropdown shouldn't ajax the ajax endpoint)
* Call `show_rights_dropdown` with the correct class for their specific implementation
| …
=> AbstractRightDropdown front URL

templates/generic_show_form.html.twig, templates/pages/management/certificate.html.twig
- In the form, the field was a 'datetime' but in the database, a 'date' is recorded.
- There was an additional field 'expire' which does not exist in the database.
| Fixed tickets | #10932
=> fix(certificate): date_expiration format

templates/components/itilobject/fields_panel.html.twig
For Ticket : set actiontime create an autogenerated task with the same value.
For Change and Problem, actiontime exists in their sql tables.
Small change also, i inverted the field with global validation due to spacing issue
=> fix actiontime display

CHANGELOG.md, src/Agent/Communication/Headers/Common.php, src/Blacklist.php, src/CommonDBTM.php, src/DBmysqlIterator.php, src/Html.php, src/IPNetwork.php, src/Inventory/Asset/InventoryAsset.php, src/Inventory/Asset/MainAsset.php, src/Inventory/Asset/Monitor.php, src/Inventory/Asset/NetworkEquipment.php, src/Inventory/Inventory.php, src/Item_Rack.php, src/KnowbaseItem.php, src/MailCollector.php, src/MassiveAction.php, src/NetworkPort.php, src/NotificationTarget.php, src/Profile.php, src/RichText/UserMention.php, tests/imap/MailCollector.php
Each commit should be reviewed individually.
See https://php.watch/versions/8.2
1. Usage of dynamic properties is deprecated. It means that using `$this->myvar = '';` when `$myvar` is not declared in class properties will trigger a deprecation error.
To fix this, I used different solutions.
- I replaced class properties by local variables when usage of properties was not relevant.
- I declared properties with a private visibility when they were used only locally.
- I declared properties with a public visibility when they were used by other core or plugin classes.
2. Usage of some "pseudo" encodings are deprecated in …
=> PHP 8.2 fixes

src/Plugin/HookManager.php
`HookManager` was using `isset` to check if a value exist in a table like this one:
```php
return [
self::ADD_CSS,
self::ADD_JAVASCRIPT,
];
```
This was an involuntary mistake, as the array do not contains specific keys, thus it has to be queried with `in_array` instead.
=> Fix HookManager

src/NetworkPort.php
| Fixed tickets | !23271
When network ports are created manually, they have no `ifstatus` value. In this case, I propose to display an "unknown" status, instead of having an empty cell.
=> Handle missing of ifstatus information

install/migrations/update_9.5.x_to_10.0.0/native_inventory.php
One may already have data that does not respect new unicity rule.
With proposed change, only the last entry fore each item/data couple will be preserved, to prevent following error:
=> Fix creation of glpi_printerlogs and glpi_networkportmetrics unicity keys

templates/components/itilobject/timeline/form_validation.html.twig
Approver dropdown in the validation edit form currently shows options for the current approver and then an empty option. I think this is different than previous versions, but I'm not sure it makes sense to change the approver at all without deleting the existing request and creating a new one. It may make sense to disable this field to discourage the behavior in the UI but not necessarily prevent changing the approver in other ways.
=> Prevent changing approver for existing request

js/dashboard.js
`refresh_ticket_list` setting has been named `refresh_views` for a while now so the auto-refresh of the dashboard was always going to be 30 seconds. It isn't possible to set the auto-refresh lower than a minute so it also seemed like a bug that the fallback was 30 seconds and it seemed like it could have been intended to be 30 minutes, so I've made that change too.
There is another bug where user preferences are not available in JS (just system defaults) but that affects much more than Dashboards so it wasn't fixed here.
=> Use correct Dashboard auto-refresh value

src/Change_Problem.php, src/Change_Ticket.php, src/Problem_Ticket.php
| Fixed tickets | #10990
All ITIL Object linking now generates update notifications for both items in the link to match the behavior of Ticket/Ticket links.
This also fixes the bad behavior of the Ticket/Problem links which generated a "new" notification for the Problem instead of an update notification for both.
=> Harmonize ITIL Object link notification behavior

templates/components/itilobject/answer.html.twig, templates/components/itilobject/footer.html.twig, templates/components/itilobject/layout.html.twig, templates/components/itilobject/timeline/form_followup.html.twig, templates/components/itilobject/timeline/form_solution.html.twig, templates/components/itilobject/timeline/form_task.html.twig, templates/components/itilobject/timeline/timeline.html.twig
| Fixed tickets | #10931
The timeline item forms (such as tasks) can feel very cramped unless the browser window is very large. I some cases, the fields are too small to interact with. This is also an issue if, like me, you have the browser's console open often and it is docked on the left or right.
The following changes were made to alleviate these issues:
- Less padding around timeline item forms on non-xxl screens
- Adjusted timeline layout so the left side would have more space on non-xxl screens
- Adjusted col breakpoints in timeline item forms to match xxl and not md screens and added a second break point to slightly reduce the size of …
=> Improve timeline item form layouts for non-xxl screens

src/Html.php
Iframes should be allowed only when `GLPI_ALLOW_IFRAME_IN_RICH_TEXT` is set to true.
In GLPI 9.5, they were not allowed at all, see #10747
=> Do not allow iframes in rich text only by default

front/inventory.php, src/Features/Inventoriable.php, src/RuleImportAssetCollection.php
| Fixed tickets | #10849
Inventory file may be missing from filesystem. There is no need to trigger an error unless an new inventory based on this file is requested.
=> Do not always trigger errors when inventory file is missing; fixes #10849

src/Search.php
While working on #10989 I found that the `$linkid` variable here was a numeric string which `is_int` returns false for. This PR adds a better check to check if it is an integer or integer string and if so, forces it to be converted to an int.
=> Fix int check

src/Update.php
Default sorting algorithm makes GLPI try applying version 10.0.X - 10.1.0 migration before any 9.XX migrations because of the first digit.
Using natural sorting seems to fix this issue.
=> Fix migration file sorting

src/Document.php
This is a proposal to solve !23400
A self service user does not have any access to documents: the right is not available.
There is already a mechanism to access a document linked to a ticket or some other objects. The foreign key and ID of the object are provided in the URL to view the document. They allow to find this object then check if the user can read it.
This PR extends it to any object, including plugins, provided they implement properly the method canView().
The linked item is added by GLPI to the URL when the FK and the ID are provided as a new argument to Document::getDownloadLink(). If no item is given,  then the liked ticket is used, as it was implemented before this PR.
This is needed to allow a self service user to access the document linked to a plugin Formcreator …
=> give access to documents to self service, if allowed to view lined item

install/empty_data.php
=> Add ITILFollowup::ADD_AS_OBSERVER right as default on some profiles

inc/includes.php
See #11022.
In sanitization process, values are preserved when they are matching an existing class, to ensure namespaced itemtypes are not altered. To ensure active plugins itemtypes are preserved, they have to be loaded prior to this sanitization process.
=> Load plugins before sanitizing POST/GET/REQUEST/FILES

src/Ticket.php
`getPredefinedTemplateFields()` method has been removed in #11014.
=> Fix helpdesk form

src/Document.php, src/Document_Item.php, tests/functionnal/Document.php
Noticed while trying to view a Change an error stating it was trying to access `getType` on null. The cause of the issue is that the previous `$params` parameter was optional previously and this method is sometimes called without any arguments. The new behavior defaults the replacement `$linked_item` to null. The code doesn't seem to handle that case.
With this, if the argument is null or a string, the legacy behavior is used. If a string was provided, the link parameters will be the value passed. If null, it defaults to an empty string just to avoid potential issues (which would have been the default value anyways).
=> Fix Document::getDownloadLink

install/empty_data.php
| Fixed tickets | #5992
Currently, a lot of values like rights, user IDs, and profile IDs are hard coded in the `empty_data.php` script and they can be difficult to read. This is mainly true for the rights which use their decimal equivalent instead of separate bit flags.
Work done by commit:
1. Wrap the logic of `empty_data.php` script in an anonymous class and a function so constants can be added and used locally here without them showing up elsewhere in autocomplete data.
2. Replace `mode` and `state` values for CronTasks with their constants from `CronTask`
3. Replace profile IDs with new local constants
4. Replace user IDs with new local …
=> Use constants in empty_data

src/CommonDropdown.php, tests/functionnal/Location.php
| BC breaks?    | maybe - Some fields not imported before may be now
When using `Dropdown::importExternal` and/or `CommonDropdown::importExternal`, you need to provide a value for the `$value` parameter which is always mapped to the `name`. During the import of a tree dropdown value like Location, it tries searching to see if the item already exists and expects there to be an extra `locations_id` field in the input OR have a `completename` value in the input. Neither of these cases is possible since while `importExternal` does accept extra parameters as an array, they are only used for the inputs of the rules processing if that dropdown type …
=> Fix importExternal for tree dropdowns

src/Application/View/Extension/PluginExtension.php, src/Plugin.php
Add a useful `get_plugin_web_dir` function to the `PluginExtension`.
Usage:
```twig
{% set ajax_url = get_plugin_web_dir('my_plugin') ~ '/ajax/my_url.php' %}
```
=> Add getWebDir to twig "Plugin" extension

src/Search.php
| Fixed tickets | #10951
Bug can only be reproduced by either modifing the entity name to `null`, or by having a foreign key that points to an invalid entity ID.
=> Fix handling of invalid entity in search results; fixes #10951

inc/itiltemplate.class.php
When we hide the description field of the ticket template, any change in the ticket causes the value to be truncated if it has special html characters. This PR applies the htmlspecialchars function in the value property to the hidden fields to avoid this problem.
=> Sanitizing value property for hidden fields

templates/components/itilobject/timeline/simple_form.html.twig
| Fixed tickets | #10388
Like in 9.5.x, change of recipient is not permitted at ticket creation
=> permits to edit recipient after ticket creation

src/Ticket.php
| Fixed tickets | #11031
As `<br /><br />` was not encoded, decoding process was considering that content is not encoded, and so was not decoding initial content on rendering.
=> Fix encoding of merged tickets; fixes #11031

src/Alert.php
Will fix following test error:
```
=> tests\units\Domain::testCronDomainsAlert():
In file /var/glpi/tests/functionnal/Domain.php on line 261, array() failed: array(4) is not equal to array(4)
-Expected
+Actual
@@ -2,2 +2 @@
-  ["date"]=>
-  string(19) "2022-03-24 09:56:43"
@@ -9 +9,2 @@
+  ["date"]=>
+  string(19) "2022-03-24 09:56:44"
```
=> Use $_SESSION['glpi_currenttime'] as default alert date

src/LineOperator.php
Fixes issue where the MCC and MNC fields showed as text but the DB schema has them are integers. Without filling these fields, it tried inserting an empty string and failed. Field types and search option data types have been updated to match the actual schema.
=> Fix line operator form

css/includes/components/_racks.scss, src/DCRoom.php, src/Rack.php
| Fixed tickets | #10529
1st step to have the cell size definition at only one place.
May permits override when finish (i'm not sure yet how to do this properly)
the -16 is strange but seems to corresponds to an offset in the height of the grid definition
i'm not 100% sure but we may want to remove both (i don't see any issue when doing it).
@kabassanov this is mostly your suggestions but more generic (usage of variables for width and height instead of raw values). Note the pr targets version 10.
=> fix dcroom grid offset

CHANGELOG.md, src/Domain.php, src/Inventory/Asset/InventoryAsset.php
While working on #11068 , I noticed that Domain form was incorrectly displayed and that some fields were not saved. This is due to the fact that the class inherits from `CommonDropdown`. I guess this inheritance should have been removed in GLPI 9.5.
=> Fix Domain inherited class

src/KnowbaseItem.php
The hidden field used for the `users_id` value was missing. It looks like it was accidentally removed when KB categories were reworked because the hidden field was placed between the Category header and the Category field.
=> Fix missing users_id value for KB item

templates/components/form/fields_macros.html.twig
In `fields` plugin, we need to be able to propose a `number` field that may contains an unpredictable count of decimals. To do so, we have to use the `any` keyword in `step` attribute. In this case, value should not be formatted, as it may be contains more decimals than `$CFG_GLPI["decimal_number"]`.
For instance when a user creates an object with a number field defined to `12.002`, the value will be rendered as `12.00` in object edition form.
=> Handle 'any' step in number fields

templates/components/masonry_grid.html.twig
In some cases, it there is a lot of items on the Central tabs (not including dashboard), the button to return to the top of the screen could overlap some of the content at the bottom of the grids. Adding a margin to the bottom of the grid allows you to scroll down more to prevent this issue.
=> Fix return to top button overlaping with central content

src/NetworkPort.php, src/Socket.php
Few issues fixed here:
- The form showed an Itemtype dropdown but didn't let you select an item afterwards.
- Selecting an itemtype was required, but I'm not sure that is intended. The DB allows a NULL value for the itemtype.
- If no itemtype was selected, a "0" was entered for the itemtype
I also added some checks to prevent errors during the display when there is no item connected.
=> Fix adding Socket from Location

inc/toolbox.class.php, tests/units/Toolbox.php
Following code is generated a warning. It should not.
```php
Dropdown::showNumber(
'fieldname',
[
'value'   => null,
'min'     => 0,
'max'     => 100,
'step'    => 1,
]
);
```
=> Handle empty values in Toolbox::isFloat()

src/MassiveAction.php
Will prevent a deprecation error on PHP 8.2 when using `update` massive action.
=> Replace usage of `CommonDBTM::$search` dynamic property in MassiveAction

src/GLPIUploadHandler.php
| Fixed tickets | #11120
1. Fix deprecations on PHP 8.1.
2. Fix image processing configuration, to disable any image processing. Configuration was not set at correct place, so every image was loaded by gd library, which may cause memory issues when uploading large images.
=> Fix upload handler

src/DeviceMemory.php, src/Search.php, src/Toolbox.php, tests/functionnal/Toolbox.php
Memory sizes are displayed in multiple formats in the search engine:
However, the users are only allowed to search for memory sizes using one format, the raw "mio" value.
It is a bad design for two reasons:
* Formats displayed in the search results should be valid search values, as the user will be tempted to use them.
* It shouldn't be expected for users to know the format conversion, e.g. that they need to write "2048" to search for 2 Gio.
After these changes, the search allow a few different formats :
- Raw Mio values (1024, 2028, 1024 Mio, 1024Mo, ...)
- Gio values (1 Gio, 1GO, 1Gio, ...)
- Tio values (1 Tio, 1to, 1tio, ...)
Note that "Tio" shouldn't be very likely for memory size but I suppose these changes could be applied to other similar fields (hdd size ?).
Search examples:
| Q …
=> Improve searches on Mio

src/Contract.php
| New feature? |  no
The date returned from `Infocom::getWarrantyExpire` may be wrapped in a span element if the test is colored. Whether it is or not, the date is always converted so there is no need to try and convert it again. Doing so when the text is inside a span was causing a PHP error to thrown.
=> Fix date conversion for colored expiration date

front/inventory.php, src/Inventory/Inventory.php
Usage:
```
php front/inventory.php < /path/to/inventory.xml
```
=> Command line inventory

src/DBmysql.php, src/DbUtils.php, src/Search.php, src/Toolbox/Sanitizer.php, tests/functionnal/DbUtils.php, tests/functionnal/PassiveDCEquipment.php, tests/functionnal/Printer.php, tests/units/DB.php, tests/units/Glpi/Toolbox/Sanitizer.php
| Fixed tickets | !23708
To handle namespaced itemtypes, we adapted the sanitization process to not sanitize classames. Main benefit is that, anywhere in the code, an `$itemtype` variable should no longer been sanitized. Previously, it was pretty hard to know if the variable value was containing a sanitized value (value passed through a http query, or manually sanitized), or a raw value.
Problem is that SQL receive a non escaped value, and it does not handle it correctly. For instance, `INSERT INTO `glpi_plugin_myplugin_test` (`name`, `class`) VALUES ('Test', 'GlpiPlugin\Myplugin\Ns\TestClass')` will insert `GlpiPluginMypluginNsTestClass'` in …
=> Fix issues with raw namespaced itemtypes

css/includes/components/_global-menu.scss, css/includes/components/_kanban.scss, css/includes/components/_mini-tabs.scss, css/includes/components/_racks.scss, css/includes/components/itilobject/_dates_timelines.scss, css/legacy/includes/_planning.scss, css/standalone/dashboard.scss
| Fixed tickets | #11123
Readdressing what I started in #11098 since the issue wasn't fully fixed.
This PR fixes all character codes changed between Font Awesome 5 and 6. It also removes the use of `font-family` and `font-weight` and replaces them with the new `font: var(--fa-font-solid);` syntax.
Finally, this PR fixes a small alignment issue with the icons in the timeline statistics view where the icon was not centered in the circle.
=> Fix FA6 compatibility

src/CommonDBConnexity.php, src/CommonDBTM.php, src/Inventory/Inventory.php, src/Session.php, tests/DbTestCase.php, tests/functionnal/Glpi/Inventory/Assets/NetworkCard.php, tests/functionnal/Glpi/Inventory/Assets/NetworkPort.php, tests/functionnal/Glpi/Inventory/Assets/OperatingSystem.php, tests/functionnal/Glpi/Inventory/Assets/Volume.php, tests/functionnal/Glpi/Inventory/Inventory.php
ex update of OS
| Fixed tickets | https://forum.glpi-project.org/viewtopic.php?pid=490556
- update of OS done here https://github.com/glpi-project/glpi/blob/ab8b4df675c0d1b188e5669de484e32f611f1318/src/Inventory/Asset/OperatingSystem.php#L136
- `CommonRelation::prepareInputForUpdate` called with a check on rights : https://github.com/glpi-project/glpi/blob/ab8b4df675c0d1b188e5669de484e32f611f1318/src/CommonDBRelation.php#L766-L770
- as we don't have any rights when doing inventories, false is returned, OS is not updated
Maybe we can up more, by adding return true to `CommonDBTM::can` and `Session::haveRight` when `Session::isIventory` return …
=> don't check right when updating CommonDBRelation on inventory process

ajax/inputtext.php, ajax/textarea.php, install/empty_data.php, install/migrations/update_9.5.x_to_10.0.0/native_inventory.php, src/Agent.php, src/Auth.php, src/Config.php, src/DbUtils.php, src/Html.php, src/Ticket.php, src/Toolbox.php, src/Toolbox/Sanitizer.php, tests/functionnal/RuleTicket.php, tests/functionnal/Ticket.php, tests/functionnal/Toolbox.php, tests/units/Glpi/RichText/RichText.php, tests/units/Glpi/Toolbox/DataExport.php, tests/units/Glpi/Toolbox/Sanitizer.php
While working on plugins, I figured out that new `Sanitizer` API, and associated deprecation messages, were misunderstood. I propose some changes to make things more clear.
Changes:
- expose `encodeHtmlSpecialChars`, `decodeHtmlSpecialChars`, `dbEscape` and `dbUnescape` and ensure they are non destructive;
- add recursive methods to handle encoding/decoding escaping/unescaping of arrays;
- replace usage of `Sanitizer::sanitize($value, false)` by `Sanitizer::encodeHtmlSpecialChars($value)`, to have a more comprehensible code.
=> Enhance Sanitizer API

src/KnowbaseItem_Comment.php, tests/functionnal/KnowbaseItem_Comment.php
Similar to Notes, the KB comments didn't handle when a user image was missing. Also, the layout seemed broken and the edit icon was missing.
=> Fix KB comment UI

js/modules/SearchTokenizer/SearchInput.js
Search tokenizer was always given the user-specified options passed into the SearchInput JS class instead of the computed options (default + user-specified). This bug currently doesn't affect anything in the core as all required options are specified.
=> Use calculated options for tokenizer

src/MassiveAction.php, src/Ticket.php
When a category is deactivated, it still appeared in the update values of the massive actions, which made it possible to assign unavailable values.
| Fixed tickets | !23703
=> fix(massiveation): disabled categories was available

src/Inventory/Asset/NetworkEquipment.php, src/Inventory/Asset/NetworkPort.php, tests/functionnal/Glpi/Inventory/Assets/NetworkEquipment.php
| Fixed tickets | https://github.com/glpi-project/glpi-agent/issues/89 (3850 issue)
Currently when matching port to a stack index, the stack index is deducted from its name : https://github.com/glpi-project/glpi/blob/f4ce8bae01b691f0939cc82ddff128125289c002/src/Inventory/Asset/NetworkEquipment.php#L397
An alternative fix (tested) is to adapt the regex here to `/.+ -.+(\d)/` (in the orginal issue we had `mainname - Switch X` and so the "Switch" part didn't match the regex).
But i'm afraid we could have anything in the name of the stack, even no number at all, and so relying on this seems dangerous.
Another much more complex alternative could …
=> loose match ports to stack

src/Agent/Communication/AbstractRequest.php, src/Inventory/Conf.php
1. Having no limits may be dangerous.
2. Limits were applied only to manually imported files.
I did not trie to optimize memory usage, but I guess limit could be lowered with some work on it.
=> Set memory/execution time limits on inventory

src/Marketplace/Controller.php
I encountered the case where 128M of memory was not enough to extract a plugin archive.
=> Prevent memory issues on archives handling in marketplace

src/Inventory/Asset/Software.php, src/Software.php, tests/functionnal/Software.php
See comments in https://github.com/glpi-project/glpi-inventory-plugin/issues/86
I may be wrong, but current logic can result in having a defined `softwarecategories_id` on some softwares after statement have been prepared, resulting in having one more value than expected.
My proposal is to ensure that `softwarecategories_id` is always defined before statement preparation.
=> Ensure 'softwarecategories_id' is always set during inventory

css/includes/_includes.scss, css/includes/components/_networkport.scss, css/legacy/includes/_styles.scss, src/NetworkPort.php, src/Plugin/Hooks.php
A special commit to add:
- anchors on ports named with logical number
- target animation (when you get scrolled to a port via an anchor)
- a hook to display something above the port list 
The idea behind this is, in the incoming month create a plugin to display above the list a switch picture with ports, their status and being clickables 
Note, i moved the css relative to port in a dedicated file, no changes made apart the adition of the `:target `
=> add some hidden features to network ports display

install/install.php
If the connection to the DB failed under PHP 8.1, an exception is thrown instead of returning a `mysqli` object with `connect_error` set. This caused the exception to be shown during the install, but no back button or "user-friendly" error message would be shown as we expected.
=> Disable mysqli exceptions during install for PHP 8.1

js/modules/SearchTokenizer/SearchInput.js
This had no noticeable effect to functionality but would show an error in the console indicating `node.lastChild` was null if you backspaced inside an empty tag/token.
=> Fix error when backspacing in empty token

js/modules/SearchTokenizer/SearchInput.js
If there are a lot of filters used in the Kanban, they can overflow the input box since it isn't a real text box. The scroll behavior for the overflow has to be added.
=> Fix SearchInput overflow

src/Search.php
Followup of #11113, keep same search option as numbers search (= is / is not) for new "mio" search types.
See last comment of !23616.
| Fixed tickets | !23616
=> Search engine: restore "is"/"is not" for mio searches

tests/DbTestCase.php, tests/functionnal/Search.php
The method used to fetch all existing lasses was still searching in `inc` directory, so many tests were not done anymore.
=> Fix Rule/Search/Transfer tests

templates/components/itilobject/linked_tickets.html.twig
Hide the Add button when the fields for adding a ticket link is already showing since clicking it again would clear the fields. Adding multiple items at once is not currently supported.
=> Hide add button when ticket link started

src/Search.php
Error occurs when ```Search``` use ```having``` (from memory size for example)  and  ```contain``` clauses
```Order By``` statement is preceded by ```AND```
see !23616
| Fixed tickets | !23616
=> fix(search): do not compute link (and / or) if statement is having

src/Agent.php
Prevent ```NOTICE``` when GLPI try to request agent (```/now```)
```
[2022-04-05 11:45:52] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined variable: response in /home/stanislas/Teclib/dev/GLPI/master/src/Agent.php at line 627
Backtrace :
src/Agent.php:665                                  Agent->requestAgent()
ajax/agent.php:54                                  Agent->requestInventory()
```
=> fix(requestAgent): fix undefined variable

src/Console/Marketplace/DownloadCommand.php, src/Console/Marketplace/InfoCommand.php, src/Console/Marketplace/SearchCommand.php, src/Marketplace/Controller.php
Adds the following commands that utilize the Marketplace feature:
- `marketplace:search` - Accepts a term and returns any available plugin with that term in its key, name or description(s). If no term is specified, all available plugins are listed. The result is shown in a table with the key, name, and short description (Best match for their current language).
- `marketplace:info` - Accepts a plugin's key and returns the full information about the plugin provided by the Marketplace API.
- `marketplace:download` - Accepts one or more comma-separated plugin keys and downloads the latest compatible versions. This never …
=> Marketplace CLI commands

src/Features/Inventoriable.php
Fix:
```
PHP Warning (2): Undefined array key "autoupdatesystems_id" in /var/www/html/glpi/10.0.git/src/Features/Inventoriable.php at line 76
```
I guessed as `RefusedEquipment` doesn't have `autoupdatesystems_id` field, it still should have the xml link displayed
=> fix a warning when displaying refused equipment

front/displaypreference.form.php, src/CommonGLPI.php, src/Search.php, templates/components/search/controls.html.twig
Fixes issue displaying display preferences modal.
Fixes issue adding search criteria.
The first issue was caused by a properly formatted namespaced class name like `Glpi\Socket` having its only `\` stripped out in the `CommonGLPI::showTabsContent` method. Also, the itemtype didn't seem to be properly escaped for the iframe src.
The second issue wasn't clear with the cause. In the JS code generated for the button event listeners, it looks like a properly formatted namespaced class name like `Glp\Socket` would have been in the POST payload but Chrome's dev tools showed that the slash was removed before it was actually sent …
=> Namespaced class fixes

src/Search.php
At least with using them in jQuery queries, the backslash needs to be escaped with another slash. As long as we do not need to use it to identify the original class, it is best to just remove the slashes from the class names when they are used in element IDs/queries.
These changes should hopefully allow the rest of the search UI to work properly with namespaced itemtypes, I missed some things with my last PR.
=> Remove slashes from Search element IDs

inc/dropdown.class.php, inc/log.class.php
| Fixed tickets | !23704
Since #8818, result of `getTreeValueCompleteName()` conforms to handling of `<` and `>` special chars in GLPI (they are expected to be always encoded in HTML entities).
With this PR, we ensure that entries related to `completename` in `glpi_logs` table are also conforming to this rule.
=> Fix encoding of completename in logs

tests/imap/MailCollector.php
Follows #11213.
Usage of `$this->output()` catches the output and prevent it to be displayed in test results. We could test that it contains expected messages, but test will not fail if output contains something else than expected errors. As error messages are containing line number and path of file related to error, using `$this->output()->isIdenticalTo()` is not a solution.
So here I just added a check to ensure that output contains the same number of lines than the expected error count.
=> Clean output of imap tests

composer.lock
`webmozart/glob` 4.5.0 has drop requirement of unmaintained `webmozart/path-util`. Updating it will prevent having a warning on this when dependencies are installed.
=> Drop unmaintained webmozart/path-util dev dependency

.github/actions/init_build.sh
PSR-4 autoload on empty namespace has been removed in #10715 .
=> Put back strictness on composer config validation

src/Html.php
Current licence is lgpl2 and soon mit, none can enforce the display of the "ad".
The branding is really annoying and before 10, we never displayed it.
Suggestion is done we can add a specific page to mentions our usage of opensource libraries maybe
=> remove annoying branding

templates/layout/parts/profile_selector.html.twig
On every page, there are 2 warnings in the browser console stating "mergeStatusColumns is not yet implemented." from JSTree. The implementation of this feature in the newer grid extension was replaced with this warning 3 years ago so I don't know that it will be added anytime soon. For now, I explicitly set the option to false.
Also, for some reason, the `mergeStatusColumns`option has to be declared under the new `grid` property even though it existed in the older `table` extension. This is the only option I found that needs declared there. Just in case this is a bug that gets fixed later, I set the option to false in both …
=> Fix JSTree not implemented warning

src/Dashboard/Widget.php
`Search::showList()` method now returns controls and pager. This is a quick and dirty fix. A more appropriate fix would be to review the way params are passed to display method.
Before:
After:
=> Fix search result dashboard widget

css/includes/components/_gantt.scss
| Fixed tickets | #11296
Fix issue with extra linebreaks
=> Fix gantt tooltip linebreaks

ajax/timeline.php
| Fixed tickets | #11208
Changing the state of a task using the checkbox doesn't set the `users_id_editor` field so it won't show the Last Update by in the item header until someone edits the form normally. After that, the field remains set so the header will update properly when changing the state with the checkbox.
=> Fix missing last update when using todo checkbox in timeline

src/Certificate.php, src/CommonDBTM.php, src/Domain.php
When a certificate is expired and generates an alert, if the expiry date is updated afterwards, the alert is no longer sent (as it is considered as already sent).
Same behaviour with domains.
| Fixed tickets | !23755
=> fix(certificate/domain): delete alert after date_expiration update

install/install.php, templates/install/step3.html.twig
Since b1e199cdfc529d0eb5b662b9a7abe2061bdacd17, when DB connection checks fails during step 2 of update process, user is redirected to install process but he probably won't notice.
As the install process drops all tables before recreating them, all existing data will be erased.
=> Prevent unwanted switching from update to install

config/_config_db.php, install/install.php, src/Console/Database/UpdateCommand.php, src/DBConnection.php, src/Update.php, templates/install/update.invalid_database.html.twig
| Fixed tickets | #11239
While investigation on #11239, I figured out that handling of errors on update was not really user friendly.
1. When user was not selecting a database, a `Can't create the database connection file, please verify file permissions.` message was display. Besides of having an irrelevant message, user was redirected to first step of installation process, and had to redo all steps. Now, a proper message will be shown and user will proposed to go to previous step.
2. When current version of selected database was not found, an exception was trigerred (see #11239) in following steps. Thus, as configuration file was created, …
=> Enhance errors handling on update

src/Console/Marketplace/AbstractMarketplaceCommand.php, src/Console/Marketplace/DownloadCommand.php, src/Console/Marketplace/InfoCommand.php, src/Console/Marketplace/SearchCommand.php
Add interact prompt for plugin suggestions when none are specified in the Marketplace CLI commands.
I also tried adding tab autocompletion which was added in Symfony Console 5.4 but I never got it to work properly.
=> Add interact prompt for marketplace commands

src/Application/View/Extension/PhpExtension.php, templates/components/itilobject/fields/global_validation.html.twig
`gettext` does not like the usage of a function named `static`. Indeed, compile template contains `$context["can_create"] = has_profile_right(static(($context["validation"] ?? null), "rightname"), ($context["create_right_val"] ?? null));`, and following error is triggered: `Parse error: syntax error, unexpected token "(", expecting ":" in /tmp/glpi-locales-GGXTLYli/templates/components/itilobject/fields/global_validation.html.twig on line 86`.
Renaming the function fixes this issue.
=> Rename static Twig function to fix locales extract

src/Html.php
Previously, the links had the plugin's web directory prefixed automatically but since the UI rework, this is not the case anymore.
=> Fix menu links from helpdesk_menu_entry hook

js/dashboard.js
Most of the time, when animation finishes, numbers in dashboard are wrong. It occurs for me on Brave so probably on other browser too. My change ensure numbers are valid at the end of the animation.
If I remember, the bug was already there in 9.5.
=> Fix dashboard animated number ending with wrong values

templates/components/itilobject/selfservice.html.twig
| Fixed tickets | internal ref !23728
When a self-service user create a ticket, if he is **not delegatee** for its groups, no requester will be set in the resulting ticket
=> no requester when a ticket created by self-service

src/AuthLDAP.php
When creating a new LDAP directory in GLPI, a SQL warning shows at the bottom of the form stating:
```
SQL: SELECT COUNT(*) AS cpt FROM `glpi_users` WHERE `auths_id` = '' AND  NOT (`sync_field` IS NULL)
Warnings: 
1292: Truncated incorrect DOUBLE value: ''
```
`AuthLDAP::isSyncFieldUsed` should return false and not query the DB if this is a new item. The return type for the `getID` field isn't enforced as an integer and in this case, it is an empty string.
The first commit addresses the specific SQL warning. The second adds a check that will return `-1` from `getID` if the value is an empty …
=> Fix truncated DOUBLE warning for new LDAP server

install/migrations/update_9.5.x_to_10.0.0/slm.php
| Fixed tickets | #11331
`glpi_slas.calendars_id` will not exist if GLPI has been initialized on a 9.1.x version.
Indeed, field was not present in `glpi-empty.sql` file, but was present in 0.90.x->9.1.0 migration.
It has been added in `glpi-empty.sql` file in GLPI 9.2.0 (see commit ebd8c6f097fd0461e4f9840221224cbb5e89a7a1).
=> Add missing glpi_slas.calendars_id field

CHANGELOG.md, src/MailCollector.php, src/Toolbox.php, tests/functionnal/Toolbox.php
MailCollector is now handling email encoding using a clean logic that is based on email headers. This hacky code is no longer needed.
=> Remove obsolete hacky encoding fallback in collector

ajax/central.php, src/Central.php
| Fixed tickets | #11332
The group tab in central was looking for the wrong property to determine if the list widget should show data for groups or not.
=> Fix group central view

src/Dashboard/Provider.php
I have the following tickets: 
Filtering on the "Root" category will only find the first ticket:
And, when clicking on the widget to open the search page, the criteria only filter the tickets directly in the root category:
Since categories are a hierarchical structure, users might expect this kind of filter to show any tickets **under** the root category.
I've modified this filter to make it work as "under X category" instead of "equals X category".
The second ticket is now detected correctly:
And the search criteria has been updated: 
| Fixed tickets | !23842
=> Dashboard filters: under category

composer.json, composer.lock
| Fixed tickets | #11347
`laminas/laminas-servicemanager` 3.10.x has no compatibility issue with `ext/psr`.
=> Prevent incompatibility with ext-psr

src/CommonITILObject.php
| Fixed tickets | !23870 (partially)
See https://github.com/glpi-project/glpi/pull/11147/files#diff-f3f1bceed6f8cfef1bf2ac3e185202f061d1e65efb41329ce10ac866d4be2916R6864
I guess that this entry should not be proposed, as clicking it opens a blank form
=> Hide 'Add document' button in timeline

templates/components/itilobject/timeline/form_followup.html.twig
=> in followup form, content is not marked as required when needed

src/CommonITILObject.php
| Fixed tickets | #11341
Do not try retrieving timeline items for new ITIL Objects. I cannot think of when this would be needed. When creating from a template with predefined items, they didn't show in the new item form and weren't handled here anyways. Doing anything except immediately returning an empty array seems to just waste time with uneeded SQL queries and leads to potentially "invalid" queries because sometime new items use an empty string for the ID even though that field is numeric in the DB.
=> Do not try retrieving timeline items for new items

.eslintrc.json, js/fileupload.js
See comments on #11360 for discussion on raising the version in the linter from ES 6 to ES 12. This would allow many modern features of JavaScript. The features are supported on all desktop browsers that GLPI supports and most features are supported on their mobile equivalents.
=> Bump ECMA version to 2021 (ES12)

templates/components/itilobject/fields/priority_matrix.html.twig
| Fixed tickets | May fix #11379
Incorrect twig variable name causes an error when the impact field is mandatory.
=> Fix mandatory impact field

install/empty_data.php, install/migrations/update_10.0.x_to_10.1.0/slm.php, src/SLM.php, src/Ticket.php, templates/components/itilobject/service_levels.html.twig, tests/functionnal/Ticket.php
| Fixed tickets | #3595 
Adds a new SLM right for assigning/changing SLA and OLA fields on ITILObjects. This doesn't take priority over the standard UPDATE right for those items.
=> Add new right for assigning service levels

css/includes/components/itilobject/_footer.scss, css/includes/components/itilobject/_layout.scss, templates/components/itilobject/fields_panel.html.twig, templates/components/itilobject/timeline/timeline.html.twig
| Fixed tickets | internal ref !23893
Fix mainly issue with sticky bottom with firefox mobile (cf [mozilla-mobile/fenix#](https://github.com/mozilla-mobile/fenix/issues/19217)) -> moved to a fixed position 
+ some minor issues (position of left elements in timeline, layout switcher displayed in sm view)
=> fix some firefox mobile issues with timeline

templates/components/itilobject/actors/field.html.twig
The control doesn't work well in creation process, the actor is not added, and the data in the original form are lost
=> don't display 'assign to me' button on new ticket form

lib/bundles/tinymce.js, package-lock.json, package.json, src/Html.php
- `tabfocus` plugin was bundled but not used.
- `colorpicker` and `textcolor` were empty stub plugins since TinyMCE 5.0.
- `paste` plugin is now integrated into TinyMCE core.
- `styleselect` menu item has been renamed to `styles`
- `paste_data_images` is now `true` by default.
=> Upgrade TinyMCE to 6.x

src/CommonDBTM.php
| Fixed tickets | #11466
Use correct environment variable for the picture path. In default configurations, this was still able to work because `GLPI_DOC_DIR` was set to `GLPI_VAR_DIR` and the picture URL here used `GLPI_DOC_DIR` with `_pictures` appended. The correct thing to use here is `GLPI_PICTURE_DIR`. The pictures already exist in the correct location and this only affected the retrieval and only if the document directory was changed to be something other than the var directory.
=> Use correct root for picture URLs

src/ITILTemplate.php
| Fixed tickets | !23923
Some plugins like Releases have their class names with odd capitalization like "PluginReleasesReleasetemplate" instead of "PluginReleasesReleaseTemplate" or just "ReleaseTemplate" with a namespace (not really supported until now). The previous replacement was case-sensitive, so it would return the template class itself as the ITIL Object class instead of "PluginReleasesRelease".
=> Fix finding ITIL Object class from template

src/CommonDropdown.php
When deleting a dropdown type that must be replaced like Entity, the first message in the form says "You can also replace all uses of this dropdown by another". Use of "can also" is confusing when the first section (to remove references to the dropdown item) does not show in this case.
This PR changes the message to "You must replace all uses of this dropdown by another." when the replacement is required.
=> Fix confusing Entity dropdown replacement message

src/KnowbaseItem.php
With Formcereator, viewing KB in the service catalog : 
```
glpisqllog.ERROR: DBmysql::query() in /home/bugier/public_html/glpi-100a/src/DBmysql.php line 368
SQL: SELECT COUNT(*) AS cpt FROM `glpi_knowbaseitems` LEFT JOIN `glpi_knowbaseitems_users` ON (`glpi_knowbaseitems_users`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN `glpi_groups_knowbaseitems` ON (`glpi_groups_knowbaseitems`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN `glpi_knowbaseitems_profiles` ON (`glpi_knowbaseitems_profiles`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN `glpi_entities_knowbaseitems` ON (`glpi_entities_knowbaseitems`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN `glpi_knowbaseitems_knowbaseitemcategories` ON …
```
=> fix bad sql query

src/CommonITILObject.php, src/RuleCommonITILObject.php
| Fixed tickets | !23911
Since the existing rule action for sending an approval to every user in a group already uses the key `groups_id_validate` the new action was added under `groups_id_validate_any` to avoid adding a breaking change and having to change rules during migration.
This also contains a bug fix where an invalid user validation could be added (ID 0).
=> Add rule action to send group approval

src/CommonITILObject.php
The `type` parameter of `CommonITILObject::getITILTemplateToUse` is supposed to be `INCIDENT` or `REQUEST` integers for Tickets or null otherwise, not the class name of the current object.
=> Fix Ticket template for type

css/includes/components/itilobject/_footer.scss
Fixed z-index for the ITIL footer on small screens. It was being overlapped by other elements like the buttons in the timeline forms, the TinyMCE toolbar for timeline items, etc.
=> Fix ITIL footer z-index on mobile

src/Rule.php
| Fixed tickets | !23912
`is_a` must be set allow strings and is not default unlike `is_subclass_of`. In some cases these checks seemed to work just fine without allowing strings but I think that is an undefined behavior because it was always using a class string as the object (`static::class`).
=> Fix ITIL Object Rule Detection

src/Ticket.php, templates/components/itilobject/fields_panel.html.twig
The contract value was not retrieved from the predefined fields of a ticket template.
| Fixed tickets | !23906
=> fix(ticket template): contract in predefined field

css/includes/pages/_search.scss, templates/components/search/table.html.twig
| Fixed tickets | #11492
Instead of the table scrolling horizontally when there are more columns than can be displayed at once, the parent card element was scrolling instead.
=> Fix search table horizontal scroll

templates/components/itilobject/timeline/form_task.html.twig
| Fixed tickets | #11501
`toadd` option was missing for task duration field so 8 hours was the max duration that could be set (Options included minutes up to 8 hours. The toadd option added the remaining hour-only values).
=> Restore max task duration to old value

src/Ajax.php
When a page reloads, the initially loaded tab is always the one that was last loaded before the page refresh rather than the one that was last switched to. Since tabs are almost always loaded once per page load, tab tracking wasn't working properly.
=> Fix tab tracking

install/empty_data.php, install/migrations/update_10.0.x_to_10.1.0/impersonate_right.php, src/Profile_User.php, src/Session.php, src/User.php, tests/functionnal/Session.php
Adds a new User right for impersonation.
The new permission only allows users whose current profile is higher or equally privileged as every profile of the other user. For example, a technician with this right could impersonation self-service users but not admins. This is mainly to avoid privilege escalation.
If user's have the update permission for the config right, then they can impersonate anyone which is the previous behavior.
=> Add separate right for impersonation

.eslintrc.json, js/modules/Search/Table.js, tests/js/Search/Table.test.js, tests/js/bootstrap.js
The biggest case I notice is with the short lifespans the CSRF tokens have by default and having auto-refresh of the ticket list enabled. If you leave the ticket list open for more than 2 hours, the refresh will fail and show "The action you have requested is not allowed." instead of the search results.
If the refresh fails, it seems better to fall back on a page reload after updating the search URL as the initial results are sent with the page request and not done async.
=> Handle AJAX search failure better

.eslintrc.json, js/RichText/ContentTemplatesParameters.js, js/RichText/UserMention.js, js/fileupload.js
`Promise` polyfill has been removed from TinyMCE in version 6.x. Using native ES6 `Promise` API is safe now.
=> Fix TinyMCE completion plugins

src/Console/Marketplace/DownloadCommand.php, src/Marketplace/Controller.php, src/Marketplace/View.php
I don't know if it's the best way to do it, but it avoids losing code... when you accidentally click on the "update" button of a cloned git plugin (with therefore a .git folder) for which we have a local branch.
=> feat(marketplace): disable download if plugin contains git directory

css/includes/pages/_search.scss, templates/components/search/table.html.twig
| Fixed tickets | #11520, #11492
relate to #11506
Moved again to responsive-md to trigger the horizontal scroll only on screens < medium size. Under this breakpoint we already remove sticky elements. This fixes the spacing bug when responsive and sticky are enabled at the time (like mentioned in #11520).
To fix #11492, i now set `width: fit-content` on intermediate containers to apply the background.
The last part for th (`min-width: max-content`) is to have a better reading for column (they take more space and the text is less compacted).
=> fix issues with responsive and sticky positioning

.eslintrc.json
As seen here
https://github.com/glpi-project/glpi/pull/11487
Bump ecmaversion to 7 for javascript ```async function```
=> Bump ecmaVersion 6 to 8

css/includes/pages/_search.scss
Follow #11521 
Last thing i need (try) to fix, is `.page-infos` div scrolling due to the `.justify-content-between` class of its parent.
It's annonying, but not blocking i think, i contained it at 250px left/right
@cconard96 Do you see any remaining bugs  ?
=> make search header/footer components sticking horinzontally

templates/layout/parts/saved_searches.html.twig
Related to #11229.
I did not find any core namespaced itemtype that can be used in saved searches feature in GLPI 10.0, but maybe some plugins are impacted by this.
=> Fix saved searches panel on namespaced itemtype

src/Search.php
PHP 8.1 starts throwing deprecations when you pass null as the subject of several string functions such as `preg_split`. The `Search::showItem` function does not enforce any type for the `value` parameter. Null values are now replaced with an empty string.
=> Do not pass null values to string functions

src/NotificationTarget.php, tests/functionnal/NotificationTarget.php
Before these changes, a plugin itemtype with a namespace would not be loaded correctly.
=> Notifications: handle plugin namespaces

src/Search.php
Alternative to #11500 .
1. Entities encoding on `RichText::getTextFromHtml()` result should be done only when data is meant to be displayed in an HTML page.
2. `>` separator should be sanitized when value corresponds to a dropdown `completename`.
=> Fix encoding issues in PDF export

src/Ticket.php
In PHP 8.1, passing null to `strtotime` is deprecated. If a date field is not set, it is null by default. The solution is to use `?? ''` as an invalid date string will return false still. The only change is that the argument must be a string.
=> Fix strtotime deprecation messages in Ticket stats timeline

src/Marketplace/Api/Plugins.php, src/Marketplace/View.php
Add improved error handling to try and avoid a blank page being shown when an API connection timeout occurs.
This also improves the usability of the installed plugins tab when the GLPI Network Services are not available by checking the status once and then relying on a static `offline_mode` variable in the View to determine what parts of the marketplace could be shown without trying to make extra API calls.
=> Improve offline marketplace handling

templates/layout/parts/page_header.html.twig, templates/layout/parts/user_header.html.twig
| Fixed tickets | #11426
The password reset form seems unique in that there is a user session but no active profile or entity. Parts of the simple header used are reliant on at least an active entity when they weren't before in GLPI 9.5 and older. This PR tries detecting when the user is logged in like this and show a similar interface as before (`Html::simpleHeader`).
For example when needing to reset the password:
Reference to previous `Html::simpleHeader` implementation:
https://github.com/glpi-project/glpi/blame/9.5/bugfixes/inc/html.class.php#L1844
=> Fix password reset form

src/CommonITILObject.php
The values of the predefined fields in the template were displayed instead of the values recorded in the ticket.
| Fixed tickets | !24947
Possibly related to PR #11421
=> fix(ticket): predefined field always loaded

js/dashboard.js
Set min ```font-size``` for ```big-number``` card
Useful for single  ```big-number``` cards
Before 
After
=> feat(dashboard label): set min font-size

src/CommonITILObject.php, src/Ticket.php
If a template was already computed and stored in the DB, try using it first when displaying an ITIL Object.
=> Try using predefined template for existing ITIL Objects

js/log_filters.js
In history tab of an asset, after enabling logs filtering, if we select a value in the "Field" column, the filter action triggered twice:
- at selection
- after the timer (normally dedicated to text inputs)
=> clear timer when select a dropdown in logs filter

src/Transfer.php
All changes made are in PHPDoc and regular comments only.
I did make a note about the default value of the `inittype` property being set to 0 by default when the property is used for itemtype class names. I think it is held over from a time when itemtypes were referenced by integers. I added the correct type in the PHPDoc but didn't want to make any code changes here. I also don't know if this property is ever used as I only found two cases it was used and it was only written to.
=> Fix/update Transfer engine PHPDoc

src/Config.php
| Fixed tickets | see !23984
Having whitespaces around registration key may produce following error.
```
[2022-05-12 09:29:21] glpiphplog.CRITICAL: *** Uncaught Exception InvalidArgumentException: "aaaaaa==^M
^M
" is not valid header value in /var/www/glpi/vendor/guzzlehttp/psr7/src/MessageTrait.php at line 263
Backtrace :
vendor/guzzlehttp/psr7/src/MessageTrait.php:209 GuzzleHttp\Psr7\Request->assertValue()
: GuzzleHttp\Psr7\Request->GuzzleHttp\Psr7\{closure}()
vendor/guzzlehttp/psr7/src/MessageTrait.php:212 array_map()
vendor/guzzlehttp/psr7/src/MessageTrait.php:174 GuzzleHttp\Psr7\Request->trimAndValidateHeaderValues() …
```
=> Automatically trim whitespaces around registration key

templates/layout/parts/page_header.html.twig
Follow #11512 which fixed ajax toasts but broked standard toasts
=> displayMessageAfterRedirect without ajax was broken

src/Unmanaged.php
The item type dropdown for Unmanaged convert massive action was using the internal class names as the display value for the item types instead of the localized name.
=> Fix convert unmanaged dropdown itemtype names

src/Html.php
Updated help link to go directly to the documentation page on the GLPI Project website instead of going through a redirect. I also changed this link and the link in the copyright message to use HTTPS.
=> Update help link to avoid redirect

src/Api/API.php, src/MassiveAction.php
`MassiveAction::getAllMassiveActions` can return false when an error occurs but this was missing from the PHPDoc return types. I added the missing return type and improved its handling in the API functions.
Related to #11404. This does not specifically address the issue (I cannot recreate) but this was noticed while I was looking into how the issue could have possibly happened.
=> Handle massive action method return better

src/CommonITILObject.php
The header fields were editable while the change is closed.
Same with the problems.
| Fixed tickets | !23978
=> fix(change): editable fields in closed status

src/Html.php
| Fixed tickets | #11584
Hide the button to add a ticket in the simplified interface when the user does not have permission to create tickets.
=> Hide self service add ticket button without permissions

src/CommonITILObject.php, src/Ticket.php, templates/components/itilobject/actors/field.html.twig, templates/components/itilobject/actors/main.html.twig
| Fixed tickets | #10570 
The template that shows actor fields uses the entity from the item (or empty item is case of a new ticket). When using the self service form to create a ticket, the entity information is not set in the item fields (It wasn't in old versions either). This shouldn't have mattered since the entity is instead passed into the self service template in the `params` variable and then into the `main` actor template as `entities_id`. However, since the `main` actor template and child `field` template only checked the item fields, it was using a null value.
The solution is to set `entities_id` to the value in the item fields …
=> Fix null entity in self service form

src/Console/Migration/UnsignedKeysCommand.php
| Fixed tickets | see #10534, #10556, #10566, #11345
We had some feedback related to unsigned int migration where users had error related to presence of negative values in foreign keys in GLPI core tables. For #10534, #10556, and #10566, these values were not inconsistent, and probably produced by a buggy code. For instance, using the `getId()` method after a failure of `getFromDB()` returns `-1`.
I propose, for GLPI core tables, to force replacement of negative values by the default one (or 0 if there is no default).
I keep this PR as a draft, as I want to make some more tests.
=> Force migration of -1 foreign keys values in GLPI core tables

src/Item_SoftwareVersion.php
| Fixed tickets | #11609
1. `vername` alias does not exists anymore, use `version` instead.
2. sorting on licence is not possible, as this data is fetched in an extra query.
=> Fix columns sorting on software installation tab

templates/components/itilobject/mainform_open.html.twig
It is possible to create a ticket from a project task :
When doing so, the ticket creation form is open with a the project task id stored as a  `GET` param:
In GLPI 9.5, this parameter was then converted to an hidden input:
It seems this code was forgotten when porting the forms to twig.
| Fixed tickets | !24018
=> Ticket: fix creation from project task

src/Planning.php, src/PlanningExternalEvent.php, src/Reminder.php
| Fixed tickets | internal ref !23870
- Avoid overflow of inputs
- better header integration
For this last, when we'll transform legacy form into twig template, the ajax double header is already managed
=> improve ajax display of legacy forms in planning

src/CommonITILObject.php
Found an error whentying to use requester group search option from self service
[2022-05-20 08:57:00] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Glpi\Toolbox\Sanitizer::isNsClassOrCallableIdentifier() must be of the type string, array given, called in /glpi-100a/src/DBmysql.php on line 1257 in /glpi-100a/src/Toolbox/Sanitizer.php at line 228
Backtrace :
src/DBmysql.php:1257                               Glpi\Toolbox\Sanitizer::isNsClassOrCallableIdentifier()
src/DBmysqlIterator.php:633                        DBmysql::quoteValue()
src/DBmysqlIterator.php:589                        DBmysqlIterator->analyseCriterionValue()
src/DBmysqlIterator.php:557                        DBmysqlIterator->analyseCriterion()
src/DBmysqlIterator.php:312 …
=> fix requester group search

css/legacy/includes/_styles.scss, inc/config.php
It would be useful to have a way to temporarily bypass updates when doing certain devs operation like `git bisect`.
There already is a specific `$_GET["donotcheckversion"]` parameter but it only works for the main request.
I think this parameter is only meant to force loading of css or locales through PHP even if the DB version doesn't match, it isn't intended to be used to actually bypass an update.
This proposal would allow to do so using a new option in the `local_define.php` file :
A banner would be added at the top of the page to make sure we don't forget to turn this option off when we no longer need it.
What do you think of this ?
It would be a new dev feature but I think integrating it in the bugfixes branch would be better as the sooner it is integrated, the more commits will be …
=> Bypass updates

src/CommonITILRecurrent.php
Increase the limit value of preliminary creation (7 days -> 14 days)
| Fixed tickets | !24039
=> feat(recurrent ticket): preliminary creation

src/Console/Database/CheckSchemaIntegrityCommand.php, src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php, src/Update.php, tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
Based on #11576 .
I had in mind to add detection of "unkown" tables in database (i.e. tables name `glpi_*` but not present in `glpi-empty.sql`), so I refactored a little the `checkCompleteSchema()` method proposed in #11576 . It was not a bg deal, but then I wanted to add tests coverage on this method (and on other non tested methods of the class), and, to do so, I had to rewrite the existing data provider in order to provide . Diff is huge, but is mainly due to grouping/reordering of test cases.
There is now 3 types of diff: altered table, missing table and unknown table.
Example:
When differences are found during update …
=> Check for database integrity after update

src/Api/API.php
A SQL join was trying to use `entities_id` column on the wrong table.
This was like this since the query was converted to use the iterator array format in 2018.
=> Fix with_contracts API option

src/Lock.php
Replace static itemtype array used for computer_item "locks" (Related items that are dynamic) with `directconnect_types` array.
=> Use directconnect_types array for computer_item locks

install/migrations/update_10.0.0_to_10.0.1/schema_fixes.php, install/migrations/update_9.5.x_to_10.0.0/cable.php
1. On DB initialized in GLPI 9.5.0 to 9.5.3 on MariaDB, `glpi_impactcontexts.positions` has a still default value, but it should not (see #8415).
2. On GLPI 10.0.0 migration, if `glpi_cables` table exists, the `glpi_states.is_visible_cable` field will not be created. It may happen on really edge case (I found this after reinstalling a GLPI 9.5.7 DB over a GLPI 10.0.0 DB, without dropping tables first).
=> Fix some migrations

src/MailCollector.php, tests/emails-tests/29.1-ticket-followup-above-header-and-under-footer-lines.eml, tests/emails-tests/29.2-ticket-followup-above-header-line.eml, tests/emails-tests/29.3-ticket-followup-under-footer-line.eml, tests/emails-tests/29.4-ticket-followup-above-header-line-without-footer-line.eml, tests/emails-tests/29.5-ticket-followup-under-footer-line-without-header-line.eml, tests/emails-tests/29.6-ticket-followup-under-header-line-without-footer-line.eml, tests/emails-tests/29.7-ticket-followup-above-footer-line-without-header-line.eml, tests/imap/MailCollector.php
| Fixed tickets | #10792 
With this proposal, when initial notification stripping logic leads to an empty followup, then the "non stripped" mail content will be used.
I opened this PR on master branch as it is changing the mail collector behaviour.
=> Prevent empty followups generated by mail collector; fixes #10792

src/ContentTemplates/Parameters/TicketParameters.php
If a class does not exists, a fatal error occurs.
```
[2022-05-25 09:04:49] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'PluginFormcreatorFormAnswer' not found in glpi-100a/src/ContentTemplates/Parameters/TicketParameters.php at line 151
Backtrace :
...tTemplates/Parameters/AbstractParameters.php:81 Glpi\ContentTemplates\Parameters\TicketParameters->defineValues()
src/ContentTemplates/TemplateManager.php:107       Glpi\ContentTemplates\Parameters\AbstractParameters->getValues()
src/AbstractITILChildTemplate.php:142              Glpi\ContentTemplates\TemplateManager::renderContentForCommonITIL()
ajax/task.php:87                                   AbstractITILChildTemplate->getRenderedContent()
```
Observed when adding a task from a template to a ticket, and the ticket is …
=> ignore non existent classes

src/Html.php, src/Printer.php, src/Printer_CartridgeInfo.php, src/Search.php, tests/functionnal/Search.php
| Fixed tickets | !23397
Add search options for toner percentages which are stored in `glpi_printers_cartridgeinfos` and gathered by inventory agents.
This required an addition to the search engine since the data is not stored in a structured schema (just property => value pairs) and the use of additionalfields (which isn't great because it seems like it will grab all properties for the printer for every search option) would would cause extra values to display. I had to add an `aggregate` property to search options and change how the specific value display gets handled so that multiple values can be combined to one displayed value.
=> Add cartridge level search options

src/Console/Marketplace/DownloadCommand.php, src/Marketplace/Controller.php
When downloading plugins from the marketplace (CLI or web) we are forced to use the latest version available for the current version of GLPI. Some plugins, like mine, follow semantic versioning though and there may be multiple versions supported for each GLPI version. There are times where someone may want to stay within the same minor version and only get bug fixes, but that is not currently possible with the marketplace.
This PR adds the ability to download specific versions of plugins using the `marketplace:download` CLI command.
This uses the existing `plugins` option but now you can now specify versions for each.
For …
=> Allow downloading specific versions of plugins

src/Search.php
Multiple class properties were undocumented including ones whose purpose is very difficult to understand just by their name and usage in the code. In fact, I still don't know what `SHORTSEP` and `LONGSEP` are specifically used for; just that they are used as separators in a GROUP_CONCAT.
Some other PHPDoc changes were made to improve type hinting of class strings and fixing incorrect information.
=> Update Search PHPDoc

CHANGELOG.md, inc/includes.php, src/Html.php, src/Plugin.php, src/Plugin/HookManager.php, src/Session.php
For security reasons, disabling CSRF checks should not be allowed. Also, plugins have to be compliant with CSRF checks since 0.84 version of GLPI (see 519db4b6cc754a82d7aa2a4bffc1c72cf780e295), so I guess checking compliance of plugins with CSRF checks is no longer needed.
=> Remove ability to disable CSRF checks

src/ITILTemplate.php, tests/functionnal/ITILTemplate.php
| Fixed tickets | #11555
Change preview tab names in Ticket templates to clarify that they are only previews. The other ITIL templates already name the tab "Preview".
=> Clarify template preview tab names

templates/components/itilobject/actors/field.html.twig
| Fixed tickets | #11687
See https://tools.ietf.org/id/draft-liman-tld-names-00.html#:~:text=A%20TLD%20label%20MUST%20be,or%20trailing%20periods%20(.).
TLD can contains from 2 to 63 chars.
Here is the current list of TLD: https://data.iana.org/TLD/tlds-alpha-by-domain.txt
=> Fix anonymous actor email address check

src/ReservationItem.php
| Fixed tickets | #11694
Form was receiving `0` value for each element that was not selected, and it was not handled correctly. When no element is selected, user is correctly redirected to items list due to following code:
https://github.com/glpi-project/glpi/blob/98cef2d8343554547fa3fb913c6ede49c4979375/front/reservation.form.php#L178-L183
=> Fix selected items in reservation form

src/DbUtils.php, tests/functionnal/DbUtils.php
| Fixed tickets | #11721
Since #9723, `mbstring` extension is optional as we embed the corresponding polyfill in GLPI package.
Before GLPI 10, `autoName` was using `preg_match` instead of `mb_ereg` (see 2a2b34e8bee57d9c061549d73ad1afabc10748ef). I do not remember why I choosed to switch to `mb_ereg`, but it does not really make sense as the regex pattern does not contains any multi-byte char, and as replacements done in method are not using multi-byte functions.
I put back usage of `preg_match` and add a test on multy-byte strings. I also check that we are not using any other non implemented function (list is here: …
=> Fix autoname when using mbstring polyfill

templates/components/form/header.html.twig
Some items have an empty entity header:
This is because we are trying to load the `entities_id` fields on items that don't have it but still support entities.
For example, items that extends `CommonDBChild` may not have an `entities_id` field but they still support entities if their parent item does:
The fix is to use the `getEntityID` method instead of reading the `entities_id` property.
This method will handle special cases like `CommonDBChild` and return the correct entity id.
After: 
=> Fix missing entity info

src/Features/Clonable.php, tests/functionnal/Computer.php
The previous patch didn't handle multiple relation items properly and was copying the first name to all other items.
=> Ammend #11708

src/Reminder.php
| Fixed tickets | Ref #10654
If a public reminder was created by the current user, it would never show on the public reminders central widget. Instead, it would only show on the personal reminders widget.
This PR allows those public reminders to appear in the public reminders widget.
It does not handle filtering those public reminders from the personal reminders list.
Another PR was made to handle which reminders are shown in each widget.
This PR targets 10.0.1 while the other targets 10.1.0 as it was more likely to cause issues (query changes).
=> Show public reminders by self on Central

templates/central/widget_tab.html.twig
| Fixed tickets | #11568
Switch from using jQuery remove method to masonry remove.
Switch from using a DOM event to trigger a layout update to calling the layout method directly.
=> Fix central widget layout after removing an item

src/Api/API.php, src/Api/APIRest.php, src/Api/APIXmlrpc.php
Instead of having to run `$this->initEndpoint()` for every endpoint expect `initSession` and `lostPassword`, it is now executed automatically unless the target resources is defined in  `API::getRessourcesAllowedWithoutSession()`.
Resources that may modify session data must also be defined in `API::getRessourcesWithSessionWrite()` as a specific flag must be set before running `$this->initEndpoint()`.
Also contains some CS fix (`elseif` + missaligned comments).
=> Force api init endpoint

src/PassiveDCEquipment.php
| Fixed tickets | #11779
Passive devices have templates but the class was missing the Cloneable trait so it was not working properly.
=> Fix Passive devices cloning

front/locale.php, inc/autoload.function.php
Recently, transifex updated plural rules for many languages (see https://docs.transifex.com/whats-new/all#section-may-2022).
Problem is that locales overrides (using #5907 feature or generated by `localeoverride` plugin) may use previous plural rules. In this case, translator component will trigger an exception, and GLPI will be unusable.
With proposed changes, exception will be catched and a log entry will be generated (see below). Thus, I do not understand why, but it seems that the base GLPI translations are still working, so only overrides are not taken into account.
```
==> files/_log/php-errors.log <==
[2022-06-02 …
```
=> Handle translator exceptions

templates/components/itilobject/footer.html.twig
As a self service user, create a ticket. Add a followup. When a ticket has a followup, the self-service user is no longer allowed to delete the ticket. However the delete button is visible. Clicking on it leads to an error message .
=> delete ticket button may show when no right to delete

src/Plugin.php
Plugins may want to be able to do a specific action when they are activate/deactivated, and there currently no simple way to do it.
=> Add plugin activate and deactivate hooks handling

src/Toolbox.php, tests/units/Glpi/RichText/RichText.php
| Fixed tickets | #11580
Looks like Microsoft Outlook 2016 produces inconsistent table declaration, with both `width="0"` attribute and `style="width:346.9pt;"` attribute: `<table class="Tabellenraster1" border="0" cellspacing="0" cellpadding="0" width="0" style="width:346.9pt;border-collapse:collapse;border:none">`.
By default, `htmlawed` transform deprecated attributes into, mainly, styles, and result was `style="width:346.9pt; width:0px;"` and expected width was overriden by 0.
IMHO, we should disable this transformation. It is not our responsability to handle the fact that source of ticket (email client, external app using API, ...) …
=> Prevent htmlawed to trasnform deprecated attributes into styles

src/TicketSatisfaction.php
Follows #11664.
1. Update of TicketSatisfaction is not always done using the base form. For instance, if an API call is made just to update the rate, or just the comment, we should do the comment emptyness check using also values from DB.
2. `entities_id` has nothing to do in input, as the `glpi_ticketsatisfactions` table does not contain this field. We should use the related ticket entity config.
=> Fix TicketSatisfaction input handling on update

src/Cartridge.php
Partially addresses performance issues reported in #11773.
I'm not sure why this wasn't already paginated as the consumable lists were already paginated.
=> Paginate cartridge lists

.github/workflows/close_stale_issues.yml
The auto-close issue workflow should not run on forks.
=> Do not run stale auto-close on forks

src/Html.php
| Fixed tickets | #11814
Missing global statement caused the help URL in the simplified interface to always be the default one.
=> Fix simplified interface help link

templates/components/itilobject/selfservice.html.twig
The `post_item` hook should be called just before the form buttons are displayed, not after.
=> Move post_item hook before self service buttons

src/User.php
| Fixed tickets | !23730
It may happen that you want to change the policy for managing "not found" (or deleted) users in LDAP directories, example from "DELETED_USER_DISABLE" to "DELETED_USER_DISABLEANDWITHDRAWDYNINFO".
Example steps:
- Policy set to "DELETED_USER_DISABLE"
- LDAP synchronization > disable users not found
- Change policy and put "DELETED_USER_DISABLEANDWITHDRAWDYNINFO"
- The second synchronization will not delete the profiles / groups of the users, even if I explicitly asked to do so.
=> fix(ldap): force delete policy to be applied

js/modules/Kanban/Kanban.js
The button used to add/choose columns in the Kanban was using a custom element tag because of a typo. This didn't seem to break anything for me in Chrome even though it did not have a matching closing tag. Also, the role attribute was misnamed. On button elements, the role attribute is not needed. At one point, I think this button was a different type of element so it would have been needed before for accessibility reasons.
=> Fix add column button tag and role

src/Dropdown.php, src/Project.php
| Fixed tickets | Ref #11802
Since tasks of projects with a finished state are hidden from the global Project Kanban, it seems better to hide them from the dropdown on the new task form as the creation of the task would work, but the new task would never show in the Kanban,
I had to add support for Left Joins in the `condition` option of `getDropdownValue` in order to support this. The commits should probably remain separate.
=> Hide finished projects when adding new task in Kanban

src/PlanningExternalEvent.php
The "Guests" field no longer allowed multiple users to be added.
| Fixed tickets | !24165
=> fix(planning): multiple guests

src/Inventory/Asset/Software.php
This is an issue I've found on fusioninventory, seems like it also exist in the native inventory.
Dictionaries support a "Category" action:
But there is no code to handle it as `$res_rule['softwarecategories_id']` is never used anywhere.
I'm not sure how this action ever worked as I can't find any code on fusion that handled this specific rule result value even in older version (but I'm told that the criteria was indeed working a couple version ago so if someone has more details on that... I've tried multiple older versions of glpi and/or fusion and I was never able to make it work).
Kinda related fix done by @cedric-anne for the "replay dictionaries rules"  action that also needed this value to be taken into account properly: https://github.com/glpi-project/glpi/pull/7961.
| Q …
=> Dictionaries: fix assign category action

inc/config.php, templates/layout/parts/page_header.html.twig, templates/layout/parts/page_header_empty.html.twig
The warning header when skipping/bypassing database updates breaks the entire `head` section because we are trying to add a `div` element in it instead of the body. The `head` gets ended immediately and the body starts with the banner div followed by the usual `head` content. In Chrome at least, some of the usual head content worked like CSS and JS links and the title, but the favicon was not working.
=> Fix HTML head when bypassing updates

js/common.js, src/Html.php, templates/components/search/table.html.twig
"Check all" in the footer had no effect (in the header it worked).
| Fixed tickets | !24170
=> fix(check all): on footer not work

templates/components/masonry_grid.html.twig
| Fixed tickets | #11688
Chrome and Firefox handle the `msnry` variable differently. Chrome treats it as a global and adds it to `window` while Firefox does not. Firefox handles it more like it was declared with `let`.
=> Fix masonry grids on Firefox

src/NotificationTarget.php
Formcreator associates PluginFormcreatorFormAnswer to tickets via a relation table. GLPI finds this object and blindly tries to read goups_id_tech, which does not exists in this object.
=> check existence of field before acessing it

css/includes/components/_kanban.scss, js/modules/Kanban/Kanban.js
Small cleanup of the message shown in drop-only columns in the Kanban such as the Closed column for ITIL Objects.
Removes list style, centers the message, and adds a small space between the top of the column and the message.
=> Cleanup ITIL Object Kanban closed column warning

src/ContentTemplates/Parameters/AssetParameters.php, src/ContentTemplates/Parameters/TicketParameters.php
When a plugin object is linked with a ticket, the templates of followups, tasks and solutions don't loading.
And we have php-errors
```
[2022-06-07 11:15:57] glpiphplog.WARNING:   *** PHP User Warning (512): PluginBadgesBadge is not allowed for this parameter type. in C:\wamp64\www\glpi\src\ContentTemplates\Parameters\AbstractParameters.php at line 77
Backtrace :
...tTemplates\Parameters\AbstractParameters.php:77 trigger_error()
...ntTemplates\Parameters\TicketParameters.php:158 Glpi\ContentTemplates\Parameters\AbstractParameters->getValues()
...tTemplates\Parameters\AbstractParameters.php:81 …
```
=> [GLPI 10.0 Bugfixes] Fix load Templates for Plugins

src/CommonTreeDropdown.php, src/Socket.php
| Fixed tickets | #11843
During the 10.0 migration, sockets are added using the standard `add` method. In the `post_addItem`, a history entry is added to the related location using the socket's `getNameID` method. This uses a user preference to determine if the ID should be shown in the name or not but there is no session during CLI migration.
In similar use cases, the ID is always forced so that the logged data is consistent and this should bypass the need for a user session.
=> Always use ID in socket location history

src/ChangeTemplate.php, tests/functionnal/ITILTemplate.php
Currently Time to Resolve field is available just Ticket Templates.
We received request to make it mandatory also for Changes. 
Also in TicketTemplates it is added in TicketTemplate::getExtraAllowedFields()
https://github.com/glpi-project/glpi/blob/0393d8e2cfe4e86bff22c3c648476e92988704da/src/TicketTemplate.php#L99
I would like to propose the same for Changes.
=> Add Time to resolve to Change Template

ajax/planning.php, js/planning.js, src/Planning.php
Right-clicking on an event allowed cloning/deleting without rights checking.
| Fixed tickets | !24196
=> fix(planning): context menu rights

src/Inventory/Asset/InventoryAsset.php, src/Inventory/Asset/Software.php, tests/functionnal/Glpi/Inventory/Assets/Software.php
Found by @Pieurre on a customer instance.
`entities_id_software` configuration setup in Entities (Asset tab) is not taken into account at all.
Also, we can't do this into `->prepare` method as the entity of the main asset is not set yet; So i moved into `->handle`
One last thing, at least for software (but its strange by the way), dictionary shouldn't set the entity.
It's a duplicate setup (Entity asset tab + Dictionary) so, just keep the more usual way.
~~- [ ] Tests may fails, we'll see~~ fixed
=> get the correct entity in conf when populating softwares

templates/components/form/header.html.twig
The "template name" input seems a bit out of place:
A simple solution would be to move it inside the header:
=> Templates: Fix name display

src/Toolbox.php, tests/functionnal/ITILFollowup.php, tests/functionnal/ITILSolution.php, tests/functionnal/KnowbaseItem.php, tests/functionnal/Ticket.php, tests/functionnal/Toolbox.php
| Fixed tickets | #11882
Due to a mistake in sanitizing process refactoring, quotes unescaped in `Toolbox::addFiles()`.
Fixed lines were using `Toolbox::unclean_cross_side_scripting_deep()` in GLPI 9.5.
=> Fix quotes handling in rich-text images replacement

src/Entity.php
1. Fix root entity handling in update process (`strategy` field was not set to `0`, so inheritance was still applied).
2. Fix inherited value display.
=> Fix 'Entity for software creation' field handling

inc/define.php
It seems like tinymce is not always loaded when using the self-service ticket's view.
After checking in `$CFG_GLPI['javascript']`, there was indeed no js lib defined for this page.
Sometimes the lib was still loaded because some ajax call on the page end up requiring it, so it might be a bit tricky to reproduce the issue.
I was however able to reproduce almost 100% of the time by doing:
- Switch to self service
- Click here 
- Go to any ticket with some followups
- Check your browser console
| Fixed tickets | !24220
=> Self-service: load tinymce on ticket page

front/helpdesk.faq.php, front/helpdesk.public.php, front/reservationitem.php, inc/define.php
Following our discussion in #11894, add missing breadcrumbs for all self-service main pages.
=> Self-service: add missing breadcrumbs

apirest.md, src/Api/API.php
There are some inconsistencies regarding the 'range' parameter of the API.
For example, let's search for ticket in the GLPI interface:
I've got 101 tickets in my database and 20 are shown on the first page.
Now if I run the same search on the API (which will use the same default page size as the search engine) I would expect to get 20 results too, right ?
Wrong, I get 21:
Headers show that the content range is 0-20:
Since ranges start at 0, it should be 0-19 in order to get a precise 20 results first page.
I've updated the `getItems` endpoint to use the correct default values.
I've also updated the examples values for this option in the documentation like `0-50` or `150-200` which doesn't make sense if the index start at 0 (it should be `0-49` and `150-199`)
For the `search` endpoint, it …
=> API: fix default ranges

src/CommonDBTM.php, src/Rule.php, src/RuleAsset.php, src/RuleCriteria.php, tests/functionnal/RuleAsset.php, tests/functionnal/RuleCriteria.php
This new criteria required quite a bit of code as there was no support for dates
| Fixed tickets | !23959
=> Asset rules: add last inventory update criteria

src/Dropdown.php, src/KnowbaseItem.php, src/KnowbaseItem_KnowbaseItemCategory.php, tests/DbTestCase.php, tests/functionnal/KnowbaseItem.php
I've found a couple issues regarding FAQ categories.
For more context, these issues seems related to the change allowing multiple categories : https://github.com/glpi-project/glpi/pull/9898 and https://github.com/glpi-project/glpi/pull/11372.
Creation form: 
- Input is way too small
- Inserting multiple values do not work, only one value is save
- Missing "+" button to add a new category (this is not related directly to categories - GLPI do not support the "+" button for "multiple" dropdown)
Edit form:
- The input to edit categories is missing (it was placed here in 9.5).
Creation form:
- Input now have the same size as the one below
- Inserting multiple values is now working as expected
- "+" button now available
Update form:
- Can edit categories
| ------------- | …
=> Faq: fix categories form

js/dashboard.js, src/Dashboard/Grid.php, templates/components/form/fields_macros.html.twig
Saving a dashboard card with transparency breaks the entire dashboard. The client sends the value as a rgba string instead of hex like the server expects and this is never checked. Errors thrown by the PHPColor library are not caught and break the entire dashboard.
This PR adds client-side conversion to ensure it sends the correct format.
PR is draft as I am looking to improve the reliability of the dashboard if there are issues with individual cards.
=> Fix saving cards with transparency

templates/components/form/fields_macros.html.twig
If `numberField` macro is called using `min: '', max:'', step: any'`, generated html will be
`<input type="number" min= max= step=any />`
which will be evaluated to
`<input type="number" min="max=" step="any" />`
Surrounding values with quotes will prevent this kind of issues.
=> Surround number input attributes values by quotes

src/RuleImportEntity.php
Add ```itemtype``` criteria
```itemtype``` value is always send to ```Rule``` engine
see: 
https://github.com/glpi-project/glpi/blob/691086765a58056a6a29e6504253b4770ed5daae/src/Inventory/Asset/MainAsset.php#L463-L465
=> feat(rule): add itemtype to RuleImportEntity

src/MailCollector.php
| Fixed tickets | #11941
A quick fix for #11941.
Adding an option to use the `Sender` header would probably be interesting, but, anyway, we have to properly handle emails that does not provide the mandatory `From` header.
=> Handle missing 'From' header in collected emails

src/Dropdown.php
Displaying a dropdown of computer triggers a warning:
```
[2022-06-20 14:44:21] glpiphplog.NOTICE:   *** PHP Deprecated function (8192): strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/glpi/10.0.git/src/Dropdown.php at line 3282
Backtrace :
ajax/getDropdownValue.php:50                       Dropdown::getDropdownValue()
```
This kind of display (computer's dropdown) is not very usual in GLPI and we missed it since, i think, a long time.
=> fix warning null value when call dropdown of computers

src/Inventory/Request.php
The is_netdiscovery statut was not passed to hooks.
This fix would have prevent the need of glpi-project/glpi-inventory-plugin#135
=> Set inventory isDiscovery status before calling hook

src/CommonGLPI.php
| Fixed tickets | #11606
In older versions, the ID as shown within the form itself at all times.
Instead of adding it back into the fields panel, it may be cleaner to just force the display of the ID within the header.
=> Force ID display for ITIL Object headers

src/Profile_User.php
Previously, you could only associate profiles with users from the user's form. This allows you to associate users from the profile form. This helps streamline adding static profile assignments after creating a new profile.
=> Associate Users from Profile form

src/ITILFollowup.php
When reopening a change, the status was set to "ASSIGNED" which is not a change status.
=> fix(change): invalid status when reopening change

src/CommonDBTM.php, src/Html.php, src/Session.php
When an access-related issue occurs and causes the script execution to stop, a generic error is given to the user (good for security to not give exact details to them) but more information isn't available anywhere on the server for debugging.
This PR adds an "access-errors.log" file to log additional information including the user ID, request URI, and a sanitized stack trace (no arguments) and an optional message that can be changed based on the context.
=> Add access error log

src/MassiveAction.php
In the ticket's massive actions, the list of locations was always empty.
| Fixed tickets | !24307
=> fix(massive action): update location empty

install/empty_data.php, install/migrations/update_10.0.1_to_10.0.2/native_inventory.php, src/Agent.php, src/Inventory/Conf.php, tests/functionnal/DbUtils.php
| Bug fix?      | yes (Fixed regression)
The agent cleanup options remain in the GLPI Inventory plugin, but they are not used by the plugin or by native inventory. The cleanup configuration was not re-added when the agent class was migrated.
=> Re-implement agent cleanup

src/Dropdown.php
It seems that the initial value of this dropdown is set using js, which will trigger `glpiUnsavedFormChanges  = true`.
This will trigger the "unsaved changes" warning on page exit every time, which we do not want to happen as no data was actually modified by the user.
```php
Html::jsSetDropdownValue($field_id, $params['default_itemtype']);
```
Note that you may not be able to reproduce this issue on a standard GLPI installation, as we do not use this dropdown on any page with the "unsaved changes" warning enabled (as far as I know).
However, some plugins or specific patches (or potential future developments) may add this dropdown and cause the issue described above.
| Deprecations? | …
=> Itemtype dropdown: do not impact glpiUnsavedFormChanges when setting initial value

templates/components/itilobject/fields_panel.html.twig
| Fixed tickets | #11993
The virtual `_contracts_id` fields is not present in the default fields array for Tickets, so its value does not get restored from the saved input into that array. It is only restored to and available from the `params` twig variable.
=> Fix restore of contract value during ticket creation

src/Agent.php, src/Inventory/Conf.php
The cron method was not sufficiently changed from the FusionInventory code and requires attribution.
I added a line to the file's header as well as a `copyright` tag on the problematic method itself so it is easy to know that it is the problematic method.
=> Fix license notice in Agent class

inc/dbmysql.class.php
On latest versions on MySQL 8.0, `SHOW CREATE TABLE` outputs `utf8mb3` instead of `utf8`.
=> Fix tests on MySQL 8.0

templates/components/form/fields_macros.html.twig, templates/components/photoswipe.html.twig
3 bugs fixed that prevented the lightbox from working properly on asset forms.
1. Attributes on the `img` elements were double quoted because the `raw` filter was not used
2. The pointer cursor was not showing when hovering over the images to show they could be clicked
3. The index option for the lightbox was always 0 because it was using the index of the `img` within the `figure` instead of the index of the `figure`. This caused the lightbox to always start on the first image regardless of which one was clicked.
=> Fix asset picture lightbox

templates/components/itilobject/timeline/form_task.html.twig
The 'date' field of a task was no longer editable in 10 whereas it was in 9.5, because it was no longer in the form.
| Fixed tickets | !24337
=> fix(form task): missing date

src/MassiveAction.php
Due to a copy/paste residue, the magic `MassiveAction::__set()` method was always forcing values to `null`.
=> Fix magic MassiveAction::__set() method

install/migrations/update_9.5.6_to_9.5.7.php
The 9.5.7 migration fixed some weird fusioninventory data from `glpi_items_operatingsystems` by changing some foreign keys from -1 to 0.
It has the unexpected effect of triggering a failed unicity constraint if there are both a -1 and 0 value for the `operatingsystems_id` field (the -1 is modified to 0 and we end up with two row with 0 -> unicity check fail)
We will fix this by removing this duplicated values before this "clean up" process.
First step is to identify the affected items, we will do so with the following request:
This query give us :
* The affected item (items_id + itemtype)
* The entry of the only valid value (which will always be the latest entry to be inserted,)
Then, for each results we run a delete query like so:
```sql
DELETE FROM glpi_items_operatingsystems
WHERE …
```
=> 9.5.7 migration: Remove duplicated items_os before adding unicity

src/Agent.php
Don't update agent type in db with unexpected one
but keep it for class instantiation
=> Fix agent itemtype updated with unexpected value

src/Search.php
When first criteria is a global rule,
if we want to remove it 
all search form is removed
Remove useless 'dot' 
which remains when we add criterion (global or not)
=> Fix global search

templates/components/form/header.html.twig
When the `is_recursive` checkbox was unchecked the value `0` was not sent and therefore the field could not be modified.
| Fixed tickets | !24361
=> fix: is_recursive

src/CommonITILTask.php
Following #12041, if the date was not filled in, a null date was recorded instead of the current date, as when the field is not present.
| Fixed tickets | !24337
=> fix(itiltask): empty date

src/Dropdown.php
Fix dropdown width with empty choice
Before 
After
| Fixed tickets | #12063
=> fix(ux): fix combox empty choice width

src/AuthLDAP.php, src/Html.php
| Fixed tickets | #12056
3 fixes:
1. The JS used to set the massive action inputs in the massive action modal used the `value` attribute of elements with a specific data attribute. This was not working for the select element to select the target entity. The `val` method needed to be used instead.
2. The recursive entity option was shown as a massive action checkbox which was not using the provided name and instead set it to the expected name as if it were the main checkbox used to select the items.
3. The recursive entity option was not passed in the massive actions. It seems like the `data-glpicore-ma-tags` has to be set to `common` …
=> Fix LDAP group import options

js/modules/Search/Table.js
| Fixed tickets | !24361
The fixed bug is clearly visible on Ticket list, you can try to order the "Last update" column.
As we remove the last order on the view, the ajax query return the default sort (and so we loop).
After multiple tries, i found this easy solution to track the number of columns already sorted, and if we are in the case with 1 column, we replace the order from nosort to 'ASC' (aka switch between ASC and DESC).
So with one colum sorted, we can't return anymore to an unsorted state and we can't trigger the load of the default sort of the backend.
=> avoid to return to default sort when we have only one column sorted

ajax/entitytreesons.php
When changing entities, the selection tree was sometimes incomplete: the parent entity of the one already active was missing, even though the user has the rights.
Conversely, the tree could display entities that the user does not have access to, but does not have access to the content.
In addition, the active entity was not highlighted.
| Fixed tickets | !24361
=> fix: change entity tree

src/Html.php
The content CSS paths for `base.css` and the current palette given to the TinyMCE instances did not match the path of the resources loaded and cached from regular page requests. This forced the browser to try and re-fetch those resources at least one extra time even if it was already cached.
The paths provided to TinyMCE already had a version parameter but TinyMCE was adding another one (did not replace it).
Additionally, the path for the palette was missing the `scss` extension even though it was present in the path when loading a page normally. This PR adds an option to get a SCSS/CSS link without a version and then rely …
=> Fix extra CSS fetching from TinyMCE

src/DbUtils.php
The current `is_glpi_class` check only allow for classes to be inside the `glpi` folder.
This is not always the case as plugins like `fields` or `genericobject` create classes in the `files/_plugins` folder, which can be outside the `glpi` folder.
| Fixed tickets | !24075 !24299
=> Fix is_glpi_class check

templates/dropdown_form.html.twig
`subitem` was probably due to a bad copy/paste, this variable is only used for timeline items in templates.
Result was that drodown was never showing the current value as selected.
=> Fix selected tech in ITILCategory form

src/Inventory/Asset/MainAsset.php
Network data are never created from discovery
=> fix(inventory): allow network managment on create

src/RichText/RichText.php
Changes suggested by @cedric-anne yersteday.
Before: 
After;
=> Fix autolink

src/Inventory/Asset/Device.php
Prevent SQL error for incorrect date value
```sql
[2022-07-06 09:40:54] glpisqllog.ERROR: DBmysql::query() in /dev/GLPI/10.0-bugfixes/src/DBmysql.php line 370
SQL: INSERT INTO `glpi_devicefirmwares` (`date`, `version`, `designation`, `devicefirmwaretypes_id`, `date_creation`, `date_mod`) VALUES ('2015-04-16T00:00:00Z', 'B200M4.2.2.4a.0.041620151912', ' BIOS', '1', '2022-07-06 09:40:54', '2022-07-06 09:40:54')
Error: Incorrect date value: '2015-04-16T00:00:00Z' for column 'date' at row 1
Backtrace :
```
Error encountered from ```ESX inventory``` with ```glpiinventory``` plugin
Maybe this fix need to be placed in ```glpi_project/inventory_format```
| …
=> fix(inventory): format date if needed

src/NotificationTarget.php
| Fixed tickets | #12136
The itemtype did not contain escaped slashes in my testing so stripslashes was not needed. Using the Sanitizer class seems to handle the itemtype properly if the slashes are escaped or not.
=> Fix updating recipients on NS itemtype notifications

CHANGELOG.md, inc/define.php, install/migrations/update_10.0.2_to_10.0.3.php, install/migrations/update_10.0.2_to_10.0.3/schema_fixes.php, install/migrations/update_9.5.x_to_10.0.0/native_inventory.php, install/mysql/glpi-10.0.3-empty.sql, src/Toolbox.php, src/Update.php, tests/functionnal/Update.php
1. During a migration to GLPI 10.0.2, we found that `glpi_refusedequipments.autoupdatesystems_id` was missing from DB. This GLPI instance was probably migrated to GLPI 10.0 from its alpha state.
2. Using `-dev`, even on bugfixes versions, will permit to ensure that `10.0.2->10.0.3` migration is always replayed when using the CLI update command, without having to use the `--force` option.
=> Fix missing 'glpi_refusedequipments.autoupdatesystems_id' key

src/CommonITILValidation.php, templates/components/itilobject/timeline/form_validation.html.twig
Some js code from the `from_validation.html.twig` template execute a scroll to the bottom of the page when the new validation form is opened:
However, it isn't restricted properly as this scroll effect also happens on the ticket timeline.
This happens because we load the validation form as it can also be shown directly in the timeline using this action:
IMO, this shouldn't happen as the js code is kinda run "by accident".
If we want to keep the scrolling behavior on the timeline, it should be implemented somewhere else properly and not be caused by some unrelated validation code.
=> Ticket validation: restrict auto scroll

src/Change.php, src/CommonITILObject.php, src/Problem.php, src/Ticket.php, tests/functionnal/ITILSolution.php
| Fixed tickets | #12120, #12131
The switch from `NEW` to `ASSIGNED` is now done on `post_addItem/post_updateItem` methods, based on new actors detected.
This existing call is not required anymore. Thus, as existing actors are always defined in `$input[*_assign]` when update is done from UI, the check was wrong as it was also considering already assigned actors as a new assignment.
=> Fix ASSIGNED status automatic computation

src/Project.php
The "No Status" column should always be sent to the Project Kanban.
=> Fix missing no status column

js/impact.js
The color of the label text in Impact Analysis always seem to be black which means that it is invisible when using the Midnight palette. This PR sets the node color to the `--tblr-body-color` CSS var value to let it adapt regardless of the palette used.
=> Fix impact labels in dark themes

src/CommonITILObject.php, tests/functionnal/ITILSolution.php
This PR avoid the need to reload tickets, change or problem to get ots final status after creation
see https://github.com/glpi-project/glpi/pull/12149
=> maintain sync between itil object and its state in DB

src/NetworkName.php, src/NetworkPort.php
From Asset list, GLPI display all IPAddress.
Management port (NetworkPortAggregate) are displayed too 
This PR exclude ```NetworkPortAggregate``` from list.
Before : 
After : 
=> fix(search): do not display managmement port from list (NetworkPortAggregate)

src/CommonITILObject.php
| Fixed tickets | !24027
See: https://github.com/glpi-project/glpi/issues/11858#issuecomment-1168514243
The `value_calculation` property may be an empty string which `??` would not have made `value` be used instead. The `?:` operator would be needed so that any time the `value_calculation` property is falsy (including empty strings), the `value` is used instead.
=> Fix display of allowed statuses for new ITIL Objects

src/NetworkPort.php
Fix ambigous column when trying to display ```IP``` and ```MAC```
Before : 
After : 
=> fix(search): prevent error for ambigous column

js/modules/Kanban/Kanban.js
Each time the team member modal was shown, a new click handler was added for the related card instead of replacing the existing handlers. This led to an issue where team members could be added to the wrong cards or a non-fatal issue where duplicate team members were added to the same card item.
=> Fix duplicate click handlers for Kanban team management

src/MailCollector.php, src/Toolbox.php, tests/emails-tests/33-html-with-unwanted-tags-inside-body.eml, tests/imap/MailCollector.php
| Fixed tickets | see #12184
Sometimes, collected email contains `<style>` in their body. If we do not remove them, they may be applied to the whole GLPI interface when corresponding ticket is displayed.
=> Clean unwanted tags in collected email

src/Ticket.php
On central interface, input is restored into `$this->input` on form reload (e.g. when changing category on new ticket form). With this PR, same behaviour will be applied to helpdesk interface.
This will be usefull for some plugins, that may want to be aware of `$this->input` on `pre/post_item_form`.
=> Restore $this->input on helpdesk form

src/Dashboard/Provider.php
Let's take the following dashboard:
Clicking on the card send you to the wrong search page (default search):
After fix, the links take you to the correct search:
This issue also indirectly impacted the advanced dashboard plugin, as it allow users to create cards from search results.
This "search results" cards would show the wrong data if the `myself` criteria was used, as they rely on the search options to apply the filter to their content.
| Fixed tickets | !24446
=> Dashboard: fix 'myself' search criteria in generated URLs

src/NetworkName.php, src/NetworkPort.php
revert fix for duplicate IP and MAC from ```Printer``` list
This behavior is not due to GLPI, but rather of the native inventory which add 
port management (```ǸetworkPortAggregate``` even if IP is known from list port IPs)
revert : 
https://github.com/glpi-project/glpi/pull/12176
https://github.com/glpi-project/glpi/pull/12172
https://github.com/glpi-project/glpi/pull/12171
See : https://github.com/glpi-project/glpi/pull/12197
=> revert(commit): revert fix for duplicate IP / MAC

src/Item_Ticket.php
Fix "My devices" dropdown.
Ex : 
All assets are in sub entity
When user create ticket from root entity and change it, page is reload on dropdown working fine (these assets are displayed).
But if you add item previously selected, dropdown is reload by ajax.
But loss entity scope, and asset list is empty
| Fixed tickets | !24434
=> fix(ticket): fix dropdown item ticket entity scope

src/CommonDBTM.php, src/Ticket.php, tests/functionnal/ProjectTask.php, tests/functionnal/TicketTask.php
Display ID of opened ticket for all ITIL Objects not just Tickets in Common code with forceid option.
| Fixed tickets | N.A
=> Force display of ID for all ITIL Objects in CommonDBTB without any specific message

src/MailCollector.php, tests/emails-tests/34-no-message-id-header.eml, tests/imap/MailCollector.php
RFC 2822 says in 3.6.4 that though optional, every message SHOULD have a "Message-ID:" field, but sometimes emails have not this field, a Laminas exception is raised in the collecting process and the whole emails queue stops getting imported into GLPI.
So the idea is to catch Laminas exception during mail collector action as it is already done for the Subject field.
The same issue can be observed in both 9.5 and 10 GLPI branches.
=> E-mails with no message-ids block retrieving by collector

src/Problem.php
getSpecificValueToDisplay and getSpecificValueToSelect does not contain any specifics for Problems
CommonITILObject is defining everything necessary
| Fixed tickets | #12217
=> Remove getSpecificValue from Problem

src/CommonITILObject.php
From ```CLI``` context, ```canViewItem``` does not allow follow-ups and tickets
Use ```bypass_rights``` only used from ```notification``` 
| Fixed tickets | #12205
=> fix(timelineitems): bypass right for canViewItem from CLI (notification)

src/CommonITILObject.php
Fix return value of isAllowedStatus in case status does not exist for given ITIL Object
| Fixed tickets | #11561
=> Correct isAllowedStatus return code for non-existent statuses

js/impact.js
Before: 
After: 
The removed code seems to be some obsolete icon changes, probably forgot to remove it.
=> Impact analysis: fix dirty workspace icon

composer.json, tests/emails-tests/35-message-with-some-invalid-headers.eml, tests/imap/MailCollector.php, tools/patches/laminas-mail-invalid-header-ignore.patch
1st commit is made to ensure that added test case triggers a failure (see https://github.com/glpi-project/glpi/runs/7407454092).
2nd commit fixes the issue, by patching laminas-mail to ignore invalid headers, instead of throwing an exception.
=> Ignore invalid mail headers in mail collector

install/migrations/update_9.5.x_to_10.0.0/pendingreason.php
Fixes following non blocking error during migration to 10.0.0.
```
SQL Error "1054": Unknown column 'is_global' in 'where clause' in query "SELECT * FROM `glpi_lockedfields` WHERE `itemtype` = 'Profile_User' AND ((`items_id` = '0' OR `is_global` = '1'))"
```
This error was due to usage of `User::add()`, which seemed to create a dynamic profile. The `is_dynamic` attribute presence on `Profile_User::add()` was trigerring a call to `Lockedfield::getLocks()` in `CommonDBTM::cleanLockedsOnAdd()`.
There is maybe something to enhance in `CommonDBTM` to prevent usage of `Lockedfield` logic on `Group_User`, `Profile_User` and …
=> Fix 'Support' system user migration

.github/dependabot.yml
It is releavant to prevent dependabot to increase version of production dependencies, as it will most of the time require a manual handling of BC-breaks, but this kind of problem is less likely to occur with dev dependencies.
So I propose to allow dependabot to open PR to increase dev dependencies versions.
=> Allow dependabot to increase version of dev dependencies

src/Console/Plugin/ActivateCommand.php, src/Console/Plugin/DeactivateCommand.php, src/Plugin.php
Translator service has no "deduplication" logic, so calling `Translator::addFile()` multiple times for the same file will result in loading a file multiple time. As translator overrides existing translations when it loads a file, it may also erase overrides made by plugins (e.g. `localeoverride`).
Plugin locales files are always loaded in `Plugin::getInformationsFromDirectory()`, but this method is indirectly used multiple times  in each request, and loading lang is often useless, for instance if method is used to check if plugin can be loaded (i.e. we can fetch informations, no matter the current locale is) or if method …
=> Prevent plugin langs to be reloaded multiple time

src/Toolbox/Sanitizer.php, tests/units/Glpi/Toolbox/Sanitizer.php
| Fixed tickets | #12184
We had 2 performances issues on Sanitizer logic.
1. During sanitize/unsanitize operations, string was parsed char by char using `for ($i = 0; $i < strlen($value); $i++) {`. For all these parsing operations, as we know which char we are searching for, using a `while (($i = strpos($value, $char, $i)) !== false) { ... $i++ }` loop is more efficient.
2. During unsanitize operation, a call to `substr_replace()` was made for every char to unescape. In #12184, the string to handle is 4.5MB length and is containing 120 000 escaped chars (60 000 `\r\n`), so with previous logic, we were doing 120 000 chars replacement on a …
=> Enhance sanitizer performances

src/ITILFollowup.php
ITIL objects can have multiple Solved statuses (Changes for example). Approbation form is displayed in any of those, so accept closure from those as well
=> Use isSolved() method for checking Solved status

.github/workflows/ci.yml, README.md, src/Config.php, src/System/Requirement/DbConfiguration.php, src/System/Requirement/DbEngine.php, tests/functionnal/Config.php, tests/units/Glpi/System/Requirement/DbConfiguration.php, tests/units/Glpi/System/Requirement/DbEngine.php
MySQL 5.7 is still supported until 10/2023, but has been released in 10/2015 and 8.0 is widely available now.
MariaDB 10.2 is not supported anymore.
| OS | Release date | MySQL version | MariaDB version |
| -------- | -------- | -------- | -------- |
| RHEL 8.3     | 10/2020     | 8.0     | 10.3     |
| RHEL 8.4     | 05/2021     | 8.0     | 10.5     |
| RHEL 8.5     | 11/2021     | 8.0     | 10.5     |
| RHEL 8.6     | 05/2022     | 8.0     | 10.5     |
| Debian Buster     | 07/2019     | 8.0 (using MySQL PPA)     | 10.3     |
| Debian Bullseye     | 08/2021     | 8.0 (using MySQL PPA)     | 10.5     |
| Ubuntu 20.04 LTS …
=> Drop support of MySQL 5.7 and MariaDB 10.2

src/Change.php, src/CommonITILObject.php, src/Problem.php, src/Ticket.php
When a new ticket is created, a notification is sent to actors. Its type is "New Ticket". If a rule closes (rejects) the ticket upon creation, this "New Ticket" notification template is still used. In a perfect world, there should be both New Ticket and Close Ticket notifications sent, but as actually this is not possible, Close Ticket notification seems to be more accurate.
=> Changing notification type for new tickets directly closed upon creation

src/Dashboard/Filter.php, src/Dashboard/Grid.php, src/Dashboard/Widget.php, src/Plugin/Hooks.php
While working on plugin dev training document, i noticed that dashboard hooks was still using direct text notation.
=> missing constants for dashboard hooks

src/ComputerAntivirus.php
| Fixed tickets | #12258
Currently, is/is not search types are broken with computer antiviruses because they do not have an entity field (SQL error) but the classes `isEntityAssign` returns true because their parent item type is assigned to entities.
Since antiviruses are only a child itemtype, I do not think it makes sense to have this search type at this time even if it had the `entities_id` field. There could be duplicate entries in the dropdown with different values where each selection only matched the antivirus of a single computer even if the names were exactly the same in other computers.
=> Allow only contains and not contains search for Antivirus name

src/Console/Build/CompileScssCommand.php
This attempts to fix a random issue where some FontAwesome icons are displayed as Unicode characters instead of icons. The compiled CSS seems to remain the same between times it works and times it does not. It seems to only really happen with icons specified in `::before` selectors. Those `content` property values are unicode characters like "" in the compiled CSS rather then the code representations like "\f100".
It seems like the browser randomly interprets the encoding of the CSS file wrong.
The charset directive needs to be the first element in the stylesheet for it to be valid, but I did not see anything on MDN that …
=> Ensure charset directive is first in compiled CSS

src/CommonITILObject.php
| Fixed tickets | #12188
I tried to fix #12188 with minimal code changes.
To have a consistent behaviour, `getDefaultValues()` should probably use `getDefaultActor`, and `getDefaultActor` should probably also handle default requester, but I am a bit affraid of potential side effects.
=> Apply default actors from CommonITILObject::getDefaultValues()

templates/components/itilobject/timeline/timeline.html.twig
| Fixed tickets | #12025
Restore hooks calls that were present in GLPI 9.5
https://github.com/glpi-project/glpi/blob/5da35e463619ba6174d9c1fee940c3f22282e08e/inc/commonitilobject.class.php#L7176-L7186
https://github.com/glpi-project/glpi/blob/5da35e463619ba6174d9c1fee940c3f22282e08e/inc/commonitilobject.class.php#L7591-L7593
A small difference with GLPI 9.5 behaviour is that `$options` is not anymore passed by reference. I am not sure it was really usefull, and I am not even sure reference was passed in the whole chain.
=> Restore pre/post_show_item hooks in timeline

src/NotificationTemplateTranslation.php
| Fixed tickets | #12259
If the translation language is empty (default translation), the form header has "Template translation - Template translation". The second occurance is supposed to be the language name, but the code defaulted to the class's type name instead of "Default translation".
=> Fix form header title for default notification translations

src/CommonDBTM.php
| Fixed tickets | #12300
Added check if the `menu` param of `displayFullPageForItem` is null and if so, sets its value to an empty array.
The parameter here and some other places called from within this function can accept a null value based on both PHPDoc types and typehints. I did not see any case where a null value would have been handled differently than an empty array. This fix is just a workaround to avoid issues with the value conflicting with the PHP typehints in the other functions.
If the null value doesn't have a different function than an empty array, maybe that can be deprecated and removed in a later version.
=> Add fix for null menu param

src/Reminder.php
| Fixed tickets | Ref #10654
Includes #11736
This PR handles de-duplicating the included reminders on the central lists.
Personal reminders will only include non-public reminders created by the user.
Public reminders will include public reminders regardless of who created them.
=> Improve central reminder list contents

install/migrations/update_10.0.x_to_10.1.0/native_inventory.php, src/Agent.php, src/Config.php, src/Inventory/Conf.php, src/Plugin/Hooks.php, tests/functionnal/Agent.php
| Fixed tickets | !23415
Separates the agent cleanup actions so that you have the option to cleanup the agent and change the status of the related item instead of choosing one action or the other.
This also adds integration with the uninstall plugin to allow applying an uninstall model to the related item during cleanup.
=> Separate agent clean actions and add uninstall integration

src/Ticket.php
Found while validating #11304. Recurrent ticket creation uses default values, and its triggers a deprecation warning here:
https://github.com/glpi-project/glpi/blob/03ca90d110be22c4a9f95e6db963ffbf3c49bb9a/src/CommonITILObject.php#L1466-L1478
=> Fix deprecation notice on recurrent ticket creation

src/CommonITILObject.php
The Kanban item card title should no longer be a link as clicking the title now opens a panel with information about the item. The ability to go to the full form was moved to the overflow menu previously. The link in the title is not currently functional anyway as the click handler prevents the default handler.
=> Kanban item title should not be a link anymore

src/Plugin.php
`Plugin:->isInstalled()` rely on `Plugin->isPluginLoaded()` which can't be trusted every page, for example every plugin are always loaded on `front/plugin.php` if their name are displayed: 
=> Plugin: fix 'isInstalled' check

src/RuleImportAsset.php
A `TOBECONFIGURED` plugin would have its rules loaded, but it should not.
=> Do not add rule of loaded but not active plugins

src/CommonGLPI.php
* Restore the "status icon" in tickets/changes/problems headers.
Before:
After: 
It seems like the status icon was removed from the header when migrating to the new UI.
I've had a few requests to restore it as it help identify quickly the ticket status.
| Fixed tickets | !24543
=> CommonITILs: restore status icon in header

src/RuleRightCollection.php, tests/functionnal/RuleRightCollection.php
| Fixed tickets | #12304
Some of the criteria for authorization rules are uppercase when every other rule criteria in GLPI are all lowercase. The `prepareInputDataForProcess` function for `RuleRight` only partially accounted for the uppercase criteria. At least temporarily to avoid other issues (not sure how else this method could be called), I added logic to the mentioned method to create a new array from the `params` array with all keys in lowercase. The result array keys are still in the correct case depending on how the criteria were declared.
=> Ignore criteria case for RuleRight

src/Search.php, src/Session.php
Total counter at top right sometimes wrong
1. I am doing a search with 1 result:
2. When opening the ticket in result the counter is wrong:
3. If I go back to the list and then back to the same ticket, the counter is correct:
| Fixed tickets | !24541
=> fix(search): counter sometimes wrong

css/includes/pages/_search.scss
We've had some feedback that links are hard to identify in the new UI.
For comparison, here are GLPI 9.5 search results:
And GLPI 10:
This is how to looks like if we increase the font weigth to 500 (one step above the 'default' font weight which is 400):
Same for 600 (two steps above):
And finally, 700 (= standard bold)
In my opinion, full bold (700) is too much.
I'm fine with either 500 and 600, which both gave a noticeable difference to the links and make them stand apart from the rest of the values.
I was leaning more to 500 at first (which is the value included in this PR) but now that I'm looking at all the images side by side I may pick 600 as the best.
| …
=> Search results: increase links font weight

src/CommonDropdown.php, src/Dropdown.php
Since GLPI 10.0, the link to the FAQ related to the category had disappeared in simplified interface.
| Fixed tickets | portal 6922
=> fix(ticket): category FAQ link missing

front/crontask.form.php, src/CronTask.php, src/Dropdown.php, templates/components/form/fields_macros.html.twig, templates/pages/setup/crontask/crontask.html.twig, templates/pages/setup/crontask/statistics.html.twig
Move automatic action (crontask) UI to twig templates.
Main form:
Statistics tab (just a table; nothing special):
=> Move crontask UI to twig templates

js/common.js
When filtering the status dropdown, the values that didn't match the filter are shown are shown as "undefined" instead of being hidden from the results.
Before:
After:
=> Status dropdown: fix undefined values

js/fileupload.js
Bug introduced in #12014, reproducible in Firefox, but not in Chrome.
=> Fix images pasting in firefox

css/includes/components/itilobject/_dates_timelines.scss
There is a centering problem with some items in the timeline
The fix adjusts the position of the exclamation mark
=> timeline : exclamation mark in circle is not centered

js/fileupload.js, src/CommonITILObject.php, src/CommonITILTask.php, src/CommonITILValidation.php, src/Document_Item.php, src/Html.php, src/ITILFollowup.php, src/ITILSolution.php, src/Item_Ticket.php, src/KnowbaseItem.php, src/Ticket.php, templates/components/itilobject/timeline/form_validation.html.twig, tests/functionnal/ITILFollowup.php, tests/functionnal/ITILSolution.php, tests/functionnal/KnowbaseItem.php, tests/functionnal/Ticket.php
| Fixed tickets | #12276
Name of field that contains uploaded files can be:
- `filename`, if richtext editor is initialized using `enable_fileupload: true` (file uploader can be used to attach documents),
- same as richtext editor name, if richtext editor is initialized using `enable_fileupload: false` (file uploader is hidden, and is used only when pasting images).
See https://github.com/glpi-project/glpi/blob/e91180444200389eb6612fe9834488632c9eb39d/src/Html.php#L5726-L5738
IMHO, both feature should be technically separated, as it is corresponding to 2 distinct features (pasting images in rich text VS attaching documents to an item), but it …
=> Fix handling of pasted images and uploaded files

src/Console/Build/CompileScssCommand.php
The `tools` folder doesn't exist in GLPI official releases.
Therefore,  `tools/HEADER` can't be fetched by the `build:compile_scss` command.
We must either:
*  Include this file in the releases
*  Have a fallback to an empty string when it's missing (which is the change proposed by this PR)
=> Console: fix build:compile_scss in production builds

src/CommonITILObject.php
Deleted actors were indexed to confusing indexes as value from previous loop was used.
=> Fix index key name for deleted actors

templates/components/itilobject/timeline/pending_reasons_messages.html.twig
Regarding this feature: 
The code was referencing the wrong variable, seems like some code get pasted too quickly when migrating to twig ;)
Btw, it's only a visual issue - it won't affect the actual automatic resolution of a ticket.
| Fixed tickets | !24642
=> Pending reasons: fix auto solve date display

templates/generic_show_form.html.twig, templates/pages/assets/software.html.twig
```softwares_id``` is duplicate from ```Software``` form
as it is, the "Child of" field does not work because GLPI checks that the 'update' input is true
1. is added by ```generic_show_form.html.twig``` because ```Sofware``` have a 1-1 relation to it self
2. is added by  ```software.html.twig``` because in this context ```softwares_id``` is use to know if a software is an add-on / update from another one
From GLPI 9.5 it is the second option that is used
| Fixed tickets | !24618
=> fix(twig): fix Software HTML form

src/Plugin/HookManager.php
=> HookManager: fix enableCSRF

src/Dashboard/Dashboard.php, tests/functionnal/Glpi/Dashboard/Dashboard.php
The rights were tested with all the user's profiles instead of the active profile, so the "Dashboard" tab could appear even if the active profile did not allow it.
| Fixed tickets | !24541
=> fix(dashboard): profil rights

src/Html.php
| Fixed tickets | #12189
Not sure it fixes #12189, as I have no Windows server to try to reproduce.
Value returned by `Html::getScssCompilePath()` is used to both operations on filesystem and usage in a URL.
- In filesystem operations, always using `/` is not a problem (actually path already contains a `/` as `Html::getScssCompileDir()` returns `GLPI_ROOT . '/css_compiled'`).
- In URL path, using `\` is not correct.
So solution is to always use `/` in SCSS file path.
I also added a replacement operation on `Html::script()` and `Html::csslink()` to automatically fix this kind of issues.
=> Fix handling of compiled SCSS files path

src/RuleTicket.php, src/RuleTicketCollection.php, tests/functionnal/RuleTicket.php
Add new criterias to rule ticket engine (like ```x-priority```)
- from
- subject
- reply-to
- to
- in-reply-to
| Fixed tickets | !24256
=> feat(rule ticket): add mail headers as criteria

src/User.php
Rules did not apply with an SSO login.
With the same user, the rule applied if you login with the local password, but it did not apply in SSO (_example provider: Google_)
| Fixed tickets | !24646
=> fix(rule right): rules not applied with SSO

src/Features/Clonable.php, src/Profile.php, src/ProfileRight.php, tests/functionnal/MassiveAction.php, tests/functionnal/Profile.php
Enable cloning for profiles. This will be useful for admins by letting them start from an existing profile rather than going through every tab and manually adding all the different rights they want.
=> Clone profiles

src/CommonDBRelation.php
This PR allows in a specific case to use inheritance between 2 classes reprensenting an itemtype.
It solves a bug in a case where a plugin enhances an other plugin.
=> PoC: allow inheritance in itemtype

apirest.md, src/Api/API.php, src/Api/APIRest.php, tests/bootstrap.php, tests/functionnal/Computer.php, tests/functionnal/DbUtils.php, tests/functionnal/Search.php, tests/web/APIRest.php
One issue with our API is that results are returned with encoded HTML:
It happens because we store HTML encoded data in the database (bad practice), but I don't see us changing that soon because of how much work would be involved.
What we can do now is decode the data before sending it in the API response.
Regarding the impact on existing code that use the API, I expect most code would already be decoding the content.
In this case, decoding a second time shouldn't break anything.
Is there some use case we should be worried about breaking with this change ?
| Fixed tickets | !24579
=> API: decode html

src/Config.php
From inventory context, ```$CFG_GLPI['inventory_frequency']``` is always set to ```DEFAULT_FREQUENCY``` because
GLPI only load  legacy configuration with ```core``` context
Fix agent expiration always set to 24 hours
| Fixed tickets | #12116
=> fix(core): load 'inventory' context to CFG_GLPI

src/Search.php
Why not to have interface of Search results to be same for all ITIL Objects (Ticket, Changes, Problems..)
=> ID in front for all ITIL Objects in Search results

src/Ticket.php
Currently BR receive also actors from $this->fields not accounting deleted actors on $input["_actors"]
Present new values instead (without deleted actors), utilizing "_deleted" keys which come from transformActorsInput()
| Fixed tickets | #11671
=> Do not present deleted actors to BR for Tickets

src/Inventory/Asset/MainAsset.php
Allows you to update only
- Last inventory update
- SNMP Credential
- Auto update system
for NetworkEquipement and from discoveries
| Fixed tickets | [#209](https://github.com/glpi-project/glpi-inventory-plugin/issues/209)
=> fix(inventory): only update SNMP, last update, autoupdatesystems from NetworkEquipement discoveries

templates/components/itilobject/timeline/form_document_item.html.twig
If a document has no file path, usually because it has a link to an external resource instead, the null file path would get passed to `document_size` which is not allowed. This section of the form in the timeline can be excluded completely if there is no file path.
=> Fix document size error for weblink doc

src/Inventory/Asset/MainAsset.php
Add is_dynamic key to prevent last_inventory_update to be locked
=> fix(discovery): add is_dynamic key to prevent last_inventory_update to be locked

src/PendingReasonCron.php
Automatic action does not convert template tags for pending reason
| Fixed tickets | !24688
=> fix(pendingreason): correctly render content from automatic actions

front/networkport.form.php, inc/define.php, src/Dashboard/Widget.php, src/NetworkPortMetrics.php
Correctly display NetworkPort metrics
- Fix load of chartist js library 
- Convert bytes to megabytes (dashboard label more readable)
| Fixed tickets | #12472
=> fix(networkport): correctly display metrics

src/NetworkName.php, src/Search.php, tests/functionnal/Search.php
If we sort the IP column
it results in an SQL warning about the ```inet_aton``` function.
```shell
SQL Warnings: 1411: Incorrect string value: 'glpidb.glpi_ipaddresses_937b8c393ea02752d06397f2628684f5.name' for function inet_aton
```
There are currently 2 ways to trigger this error
- Empty IP
- ```IPV6``` format (from ```name``` column)
Rather than using the ```inet_aton``` function that is only compatible with ```IPV4```, I suggest using the ```IPV6``` version  ```inet6_aton```.
Sort order seems OK with ```inet6_aton```
```sql
mysql> select id, name, inet6_aton(name) from glpi_ipaddresses where mainitems_id = 7 and mainitemtype = 'Computer' order by inet6_aton(`glpi_ipaddresses`.`name`) asc;
+-----+-------------------------+------------------------------------+
| id  | name …
```
=> Fix sql warning from ip order

templates/components/itilobject/actors/main.html.twig
The "assign to" field was editable, even without the "assign" right. However, the data was not saved.
| Fixed tickets | !24764
=> fix(ticket): assign to editable without assign right

src/CommonITILObject.php
Users that can view documents have access to these actions in the timeline even if they can't edit/delete documents:
These is caused by two incorrect conditions where `Document::canView()` is used instead of the respective `canEdit` and `canDelete` methods.
I think the developer who wrote this assumed that `canUpdateItem` and `canDeleteItem` would call these methods.
Maybe they should (in another PR) ? 
| Fixed tickets | !24772
=> Timeline: fix documents actions visibility

src/CommonDropdown.php
This code rely on detecting null values:
https://github.com/glpi-project/glpi/pull/12307 replaced the null value by an empty array, so we need to check with `empty` instead.
=> Breadcrumbs: fix for dropdowns

src/Search.php, tests/functionnal/Search.php
While designing a search option I found the new need to mention a linkfield in a nested ['beforejoin' array](https://glpi-developer-documentation.readthedocs.io/en/master/devapi/search.html#join-parameters).
Thre is no place in GLPI where such search option exists, and the search engine fails to build the JOIN chain with such context.
I found that 2 consecutive JOIN are broken because of a misnamed table alias. The inner linkfield is missing.
=> fix table alias naming in nested join

src/RichText/RichText.php, src/Search.php
| Fixed tickets | internal ref !24694
Initially, a work around for an issue with a big image (10MB) in a tooltip in tickets list crashing chrome (don't know why).
But i though always deferring loading of images in tickets contents (timeline mainly) could be a plus on performance, loading times, server load, etc.
=> lazy loading for tickets images

src/CommonITILObject.php
change from self::isAllowedStatus() to static::isAllowedStatus() to allow redefining in ITIL classes
Sorry for copy&paste bug, missed this in #12470
| Fixed tickets | #12469
=> Fix isAllowedStatus call in canMassiveAction()

templates/components/itilobject/actors/field.html.twig
| Fixed tickets | Partially addresses #12520 but doesn't resolve the bulk of the performance issue
Currently, the select2 inputs for the actor fields send AJAX requests after each character typed. This results in many unneeded requests, extra server processing time, and extra bandwidth usage. By using the `delay` option, the requests can be debounced. This PR sets the `delay` option to 250 which results in a single request being made 250ms after the user stops typing.
=> Debounce actor field AJAX requests

src/ReservationItem.php
If we try to do a reservation for a GenericObject object
SQL error appears
```shell
[2022-08-31 08:21:54] glpisqllog.ERROR: DBmysql::query() in /home/GLPI/10.0-bugfixes/src/DBmysql.php line 370
SQL: SELECT `glpi_reservationitems`.`id`, `glpi_plugin_genericobject_tests`.`name` FROM `glpi_plugin_genericobject_tests` INNER JOIN `glpi_reservationitems` ON (`glpi_reservationitems`.`items_id` = `glpi_plugin_genericobject_tests`.`id` AND `glpi_reservationitems`.`itemtype` = 'PluginGenericobjectTest') WHERE `glpi_reservationitems`.`is_active` = '1' AND `glpi_plugin_genericobject_tests`.`is_deleted` = '0' AND `glpi_plugin_genericobject_tests`.`is_template` = '0'
Error: Unknown column 'glpi_plugin_genericobject_tests.is_template' in 'where clause'
Backtrace : …
```
=> fix(reservation): check if is_template fields exist

src/SavedSearch.php, tests/functionnal/SavedSearch.php
Public saved searches were visible, even on a profile that did not have the right to see them.
| Fixed tickets | !24794
=> fix(savedsearch): public search visible without right

src/Toolbox.php, tests/functionnal/Toolbox.php
Related to #10945
Formcreator needs to create URL to documents with query parameters itemtype=xxxx&items_id=xxxx . (see https://github.com/pluginsGLPI/formcreator/pull/2907)
This PR avoids code duplication currently added in the above PR.
=> Allow any object in URL to a document

templates/components/itilobject/fields_panel.html.twig, templates/components/itilobject/service_levels.html.twig
If the template hides all the fields in "Service Levels", the area was visible in the ticket, but empty and therefore useless.
| Fixed tickets | !24541
=> fix(ticket): empty service levels

src/AuthLDAP.php, src/User.php
same as DELETED_USER_DISABLEANDWITHDRAWDYNINFO but without authorization removal
| Fixed tickets | https://discord.com/channels/402399026168725505/402416991849414656/1012380128451514428
Suggestion of @kabassanov
=> add new options for deleted users : disable and remove groups 

src/CommonITILObject.php, tests/functionnal/Ticket.php
Here `post-only` is part of the `Pro services` group and add a new followup to a pending ticket.
-> Ticket is still pending which is incorrect: the ticket must be "reopened" when a requester add a followup.
The issue comes from `needReopen` calling `isGroup` incorrectly (sending an array of groups id instead of a single group id).
These changes:
- Fix the incorrect method parameter sent in `needReopen`
- Enforce types in `isGroup` to prevent future issues
- Improve unit tests coverage
=> Ticket: fix reopen by requester group

js/modules/SearchTokenizer/SearchInput.js
| Fixed tickets | InfotelGLPI/tasklists#48
The tokenized/taggified search input was re-tokenizing the text content of the input instead of using the raw input from the individual tokens. This caused it to ignore any quoted text as the quotes were not put into the text value of the displayed tags.
This caused a filter of: `group:"Security Team"` to be interpreted as two tokens. The first being `group:Security` and a second plain-text token of `Team`.
This PR also ensures that the quotes show when editing the tag if they were present to avoid issues when re-parsing the text.
=> Fix handling of search input tokens with spaces

src/Api/API.php, tests/web/APIRest.php
| Fixed tickets | #number 
I did not open a ticket.
app-token was prohibited by CORS policy. 
(Angular does a preflight test, and this header is mandatory glpi-client typescript library )
I added it to the list of allowed headers.
I also put this header in test, and changed a Tab for spaces.
=> CORS must allow app-token header

src/CommonDBTM.php, src/CommonGLPI.php
| Fixed tickets | #11896
The options passed to `ObjectLock::manageObjectLock` did not contain the ID for Tickets at least so they were never used.
=> Fix object locks

templates/components/itilobject/actors/field.html.twig
If the template hides the requesting group, the requesters field is visible, because the template user can add users, but not groups: the desired behavior.
If this field already contains a group, it was displayed and the user could delete it.
_Same thing with the other actor fields (observers, assigned to) and in the opposite direction: visible group, hidden user._
| Fixed tickets | !24765
=> fix(ticket): hide added group when it is hiddenfield in template

src/Change_Problem.php, src/Change_Ticket.php, src/Problem_Ticket.php
Dropdowns shown for linking of Common ITIL objects together (Chnage_Ticket, Problem_Ticket, Change_Problem) display currently ID just for Ticket type.
Display it also for other type of linking as in larger deployments it can contain multiple items with same name.
=> Display ID in linking dropdown for Common ITIL objects

css/includes/_base.scss
In some cases, the browser may try making "smart" replacements while rendering certain characters which may not be wanted most of the time in GLPI. For example, `Windows 10 x86` has the `x` replaced with a multiplication sign because there are numbers on both sides of it.
Tabler only has a CSS rule `font-feature-settings: "liga" 0"` which disables ligatures (joining of letters). However, the Inter font family changed the multiplication sign replacement from being in the "liga" feature to the "calt" (contextual alternates) feature starting in version 3.12 (2020) so it doesn't apply.
Some other replacements that this would …
=> Disable contextual character replacements by default

src/Inventory/Asset/NetworkPort.php, tests/functionnal/Glpi/Inventory/Assets/NetworkPort.php
Actually ```NetworkPortMetric``` are never update / added after first import of ```NetworkPort```
| Fixed tickets | #12483
=> fix(inventory): update network port metrics

css/standalone/dashboard.scss, src/Search.php
Drag feature not work on mini dahsboard because ```$grid_rows``` is defined to ```1``` instead of ```2``` (from GLPI 9.5)
Need to fix ```height``` to prevent empty space between ```cell-add``` ```div``` (from ```grid-guide```)
| Fixed tickets | !24801
=> fix(dashboard): fix draggable item and grid-stack size

src/Ticket.php
Predefined field ```date``` (```opening date```) not working
Because of ```null``` default value and this check
https://github.com/glpi-project/glpi/blob/bbce75d025fd8379329c3f53410ef74fe6644c82/src/CommonITILObject.php#L513
| Fixed tickets | !24821
=> fix(tickettemplate): fix predefined date not working

src/Inventory/Asset/MainAsset.php, src/Inventory/Asset/Printer.php, tests/functionnal/Glpi/Inventory/Assets/Printer.php
allow networkport update from discovery only for printer
Usefull when printer changes IP
Only network information are deleted (is the goal)
other inforamtions , page counter, Sysdescr, serial number, model , manufacturer are still present .
| Fixed tickets | [#192](https://github.com/glpi-project/glpi-inventory-plugin/issues/192)
=> fix(discovery): allow networkport update from discovery only for printer

front/ticket.form.php, templates/components/itilobject/timeline/sub_documents.html.twig
Reverts #12517 and replace link by a form to ensure CSRF protection.
=> Secure document deletion in timeline

src/CommonITILObject.php, src/Ticket.php, templates/components/itilobject/selfservice.html.twig
| Fixed tickets | #12427
When a ticket template is used in the self-service ticket creation form, multiple options are not set properly from the default values.
This PR fixes that and also changes how the `entities_id` is referenced within the template to match the regular ITIL Object form.
=> Fix missing self service ticket form defaults

ajax/common.tabs.php, src/Html.php
Fix redirect from load / switch tab when session is expired
How to test : 
Log in to GLPI and go to  Central page
Open new GLPI tab go to  GLPI Computer list -> then logout
From Central page change tab.
| Fixed tickets | !24812
=> Fix redirect from load tab when session is expired

src/RuleImportAsset.php, tests/functionnal/Glpi/Inventory/Inventory.php
The import logs were duplicated with the update rules, as `rulepassed` also adds the logs.
=> fix(inventory): duplicated logs

src/Agent/Communication/AbstractRequest.php, tests/units/Glpi/Inventory/Request.php, tests/web/Glpi/Inventory/Request.php
Importing the following XML fails (expected) but GLPI doesn't show the error message: 
```xml
<SOFTWARES>
<ARCH>x86_64</ARCH>
<FROM>registry</FROM>
<GUID>GUID 01233456789 - 987654321</GUID>
<INSTALLDATE>23/02/2021</INSTALLDATE>
<NAME>Long software name</NAME>
<PUBLISHER>Publisher of this software</PUBLISHER>
<SYSTEM_CATEGORY>application</SYSTEM_CATEGORY>
<UNINSTALL_STRING>"C:\Program Files\Common Files\Publisher of this software\Uninstall\uninstall.exe" option1=value1 option2=value2 option3=value3 option4=value4 option5=value5 option6=value6 option7=value7 option8=value8 option9=value9 option10=value10</UNINSTALL_STRING>
<VERSION>12.0.13213389.432420033</VERSION>
</SOFTWARES>
```
Behind the scenes, this PHP error will be triggered:
```log
[2022-09-05 10:02:10] glpiphplog.WARNING:   *** …
```
=> Inventory: fix xml errors encoding

css/install.scss, src/Auth.php, src/Session.php, src/System/Requirement/SessionsSecurityConfiguration.php, src/System/RequirementsManager.php, tests/units/Glpi/System/Requirement/SessionsSecurityConfiguration.php
PHP directives can be used to secure session cookies, but forcing some values on GLPI side may cause a degraded experience for some users. Indeed, using `SameSite=Strict` result in not sending session cookies when acces to GLPI is made from another website. For instance, if a user is redirected from any website to GLPI, its session cookies will not be received by GLPI and will therefore be erased, and user will have to log-in again.
I propose to add a new optionnal "requirement" on installation process, in order to inform administrator about these PHP directives. With this, we would be able to removed hard-coded …
=> Delegate session cookies security to sysadmin

css/includes/_includes.scss, css/includes/components/chartist/_chartist.scss, src/Dashboard/Widget.php, src/PrinterLog.php
Page counters get a bit messy with big datasets:
Note the labels on the X axis which are unreadable, and the ones on the Y-axis are truncated (it's supposed to go from 0 to 35k in this example).
Proposed changes:
* Limit the dataset to 25 items, spread equally across the set
* Change the graph from bars to areas. 
This help by reducing the Y scale (areas graph seems to start the Y scale from the lowest value (here 15k) instead of 0 and are also easier to read in my opinion
* Rewrite Y axis label to use K or M prefix for big numbers
* Rewrite X axis label to remove the year (this graph will only show the last 365 dates so we can part with this data) and use the month name (more easily readable, especially on small screens if the labels get spread on multiples lines).
| …
=> Printers: fix printed pages graph for big datasets

src/RuleImportAsset.php, tests/functionnal/RuleImportAsset.php
The criterion "is empty" on the UUID was ignored during the execution of the rule.
The addition of the rule "Computer update (by serial + uuid is empty in GLPI)" fixes the case where the asset is created (manually) with a serial and no UUID, because before the default rules created a duplicate.
| Fixed tickets | !24715
=> fix(inventory): UUID is empty

css/palettes/darker.scss
| Fixed tickets | #12597
Before:
After:
This also fixes the color of the large title and smaller section titles within the asset forms.
=> Fix header fg color in darker

src/RuleImportAsset.php, tests/functionnal/Glpi/Inventory/Inventory.php, tests/functionnal/RuleImportAsset.php
Only for fresh install.
some rules name are wrong
```Device``` to ```Global``` if ```itemtype``` criteria is not a ```is``` condition (use to group s by itemtype)
```Perihperal``` to ```Device``` because ```Perihperal``` class have type name ```Device```
| Fixed tickets | #11950
=> fix(rule): fix rule name

install/empty_data.php, install/migrations/update_10.0.2_to_10.0.3/notifications.php, src/NotificationTargetCommonITILObject.php
Change default recipient for the "New group in assignees" ticket notification from "Group in charge of the hardware" to "Group in charge of the ticket". This matches up with the other notifications related to new actors.
=> Fix default recipients for assign group in ticket notification

src/Console/Database/UpdateCommand.php
Database schema checks on update were not skipped when forcing upgrade to be replayed (e.g. upgrading from `10.0.3-dev@xxx` to `10.0.3@xxx` using `--force` param).
=> Fix database schema check bypass condition

src/NotificationEventMailing.php, src/RichText/RichText.php
When the user copies/pastes the image from richtext and changes its size (smaller)
on display, the size is reworked by GLPI to match the size of the text area -> perfect
But when GLPI generates the notification, it takes into account the ```width``` and ```height``` in the ```img``` DOM
This PR allow GLPI to handle image size.
**EDIT**
The real issue is -> " the display size in timeline is not correct."
Images are always risize by GLPI even if user change it
| Fixed tickets | !24145
=> fix(timeline):  the img display size in timeline is not correct.

src/ITILSolution.php, tests/functionnal/ITILSolution.php
Actually applying a solution to a ticket means to change its status to SOLVED (if GLPI is not configured to immediately close the ticket) and wait for approval.
Sometimes, a kind of a strong reject could be required for some tickets, ignoring autoclosure state/delay defined for the entity.
This modification offers the possibility to close a ticket and apply a solution for it by rule (in this order). Other usages could be imagined with tickets solutions and other statuses, but I didn't find a way to inform ITILSolution objects about ticket status modifications...
=> Allow forcing closure when adding solution via rules

src/Inventory/Asset/NetworkPort.php
Static analysis is wrong. The array is populated from the `rulepassed` method, which is called by `processAllRules` call (we pass the `class` parameter).
=> Drop irrelevant comments

templates/components/itilobject/timeline/form_followup.html.twig, templates/components/itilobject/timeline/form_solution.html.twig, templates/components/itilobject/timeline/form_task.html.twig, templates/components/itilobject/timeline/form_validation.html.twig, templates/components/itilobject/timeline/main_description.html.twig, templates/components/itilobject/timeline/timeline.html.twig
All rich text content should be wrapped with the `rich-text-container` class.
It seems to be missing on the timeline.
I've found that the `read-only-content` content class was applied to every timeline items so I've added the `rich-text-container` next to it which should cover every rich text elements hopefully.
=> ITIL Timeline: restore rich-text-container class

CHANGELOG.md, src/CommonDBTM.php
Similar to CommonDBTM::pre_updateInDB()
A use case would  be the management of a complex data which is hard / useless to store il multiple fields. It could be JSON encoded in a single field of the DB, but for manipulation should be decoded. 
Combined with post_getFromDB and pre_updateInDb(), the new method pre_addInDB() could handle the JSON encode/decode process without hassle, maintaining in RAM the data as an array or an object, at developer's convenience.
=> give itemtype the ability to modify their data before add

css/includes/components/itilobject/_timeline.scss
=> fix width of timeline item when displayed within todo layout

css/includes/components/_richtext.scss, src/Html.php, src/RichText/RichText.php, stylelint.config.js, tests/units/Glpi/RichText/RichText.php
Links made with the TinyMCE's link plugin (right click -> link) will now target a new tab by default.
Links added with the autolink PHP lib will always be in a new tab.
As suggested by @cedric-anne, I've also added an icon to hint at this new behavior:
The icon could also be placed on the left, let me know which one is better:
| Fixed tickets | !24845
=> Richtext: open links in new tab by default

install/empty_data.php, install/migrations/update_10.0.2_to_10.0.3/inventory.php, src/Inventory/Conf.php, src/Inventory/Inventory.php, src/Migration.php, tests/units/Migration.php
Since GLPI 10.0, the inventory is native, but the management of the rights is much less precise than before, because it depends only on the right UPDATE on the general configuration.
This PR, adds 2 rights corresponding to the 2 tabs of the inventory menu:
| Fixed tickets | !24880
=> fix(inventory): rights check

src/CommonDBTM.php, src/Inventory/Asset/InventoryAsset.php, src/Inventory/Asset/MainAsset.php, src/Lockedfield.php, tests/functionnal/Lockedfield.php
Removing locked data in inventory preparation causes values not to be stored in locked fields table.
This PR removes that, but still prevents locked relations to be created.
=> Do not remove locked data in inventory prepare

src/LevelAgreementLevel.php
Increase the maximum value of the execution time to +/- 100 days (instead of 29)
| Fixed tickets | !24832
=> feat(escalation level): increase execution time

src/Dropdown.php, templates/components/itilobject/actors/field.html.twig
| Fixed tickets | #12520
Limit the results for the user search query to the `dropdown_max` config option instead of being unlimited to improve performance in cases where a lot of users could be matched.
=> Use dropdown limit option for actor fields

src/Inventory/Asset/Software.php, tests/functionnal/Glpi/Inventory/Assets/Software.php, tests/functionnal/Glpi/Inventory/Inventory.php
Handle software categories correctly
On first import ```softwarecategories_id``` are never handle exept if ```value``` has been modified or set by the rules engine
Add capability of ```inventory``` to update ```softwarecategories_id``` of ```Software``` if needed (useful for straighten up data data already imported)
=> Fix softwarecategories import update

src/CommonGLPI.php
Formcreator features are constantly growing. The questions design system becomes messy because there are too many settings. 
As dropping the modal to design a question is very likely a bad idea, I'm experimenting the use of tabs in a modal. See below:
This PR allows to not render the navigation header we can see in the top of the modal. Going back to a list of items is not relevant here and pollutes the modal.
=> Tabs in modals

src/DbUtils.php, templates/components/user/info_card.html.twig
A small feature that can go into the bf branch:
I've set the milestone to target 10.0.4 as it is not urgent, but It can be changed if you want it in 10.0.3.
Also, I've noted that the user picture seems distorted in this tooltip (unrelated to changes).
Maybe something you could look into before 10.0.3 is released ?
=> User tooltip: add phone2 if exist

src/Html.php
Disable the default option of tinymce "text_patterns"
[](https://www.tiny.cloud/docs/tinymce/6/content-behavior-options/#text_patterns)
| Fixed tickets | !24929
=> fix(tinymce): disable text_patterns

src/Ticket.php
When viewing the simplified interface preview in a ticket template, the `$options` array is not initialized so an error occurs when it tries passing a null value when an array is required.
=> Fix simplified ticket template preview

CHANGELOG.md, src/Search.php, src/Search/Input/QueryBuilder.php, src/Search/Output/PDFSearchOutput.php, src/Search/Provider/SQLProvider.php, src/Search/SearchEngine.php, src/Search/SearchOption.php
Some `Search` class legacy methods are not used by plugins and could so be removed.
I was not able to perform more cleaning quickly, as many moved methods are still used from the legacy `Search` class.
=> Clean legacy search class

.github/workflows/nightly_build.yml
The nightly build of the main branch has been failing because it was trying to use PHP 7.4, but the minimum for the main branch is now 8.0.
=> Fix nightly build of main branch

css/includes/components/itilobject/_layout.scss, templates/components/itilobject/fields_panel.html.twig, templates/components/itilobject/footer.html.twig, templates/components/itilobject/layout.html.twig, templates/components/itilobject/timeline/filter_timeline.html.twig
The previous breakpoint was `-md` (768px) or  `-sm` (576px) for some parts, and the right panel could not be displayed correctly (especially with left menu expanded)
I took the opportunity to quickly fix the secondary buttons in the footer (filter, todo, and collapse/expand)
Before: 
After:
Before:
After:
=> move breaking points of itil object layout

js/common.js, js/modules/Search/Table.js
| Fixed tickets | #12667
Two issues:
1. The fluid search feature was making the "Select all" checkbox shift-clickable. This didn't seem related to the reported issue.
2. The shift-click would work, but the selected checkbox would uncheck immediately afterwards. The only fix I found was to only check the boxes between the last checked and the the currently selected one (exclusive) and let the default event handling check the currently selected box.
This was tested in Chrome and Firefox.
=> Fix search checkbox shift click

src/Inventory/Asset/NetworkPort.php
| Fixed tickets | #12609
The main idea throwing an exception was to see when that case was reached, and try to fix it. Since it's been implemented, there were no case such a try was really valid.
So, maybe there is a logic issue when the original array is completed, but when that fails, there is never a real connection to be made - as far as I see.
If inventory results seems OK ignoring self wiring case; it's certainly ok.
=> No longer throw an exception; closes #12609

css/includes/components/itilobject/_timeline.scss
f573edca31b7c2289028681b71b64dd9d33c45fa : 
on large screen (1440p + ) the limitation of 700px (added on #12153) cause the right timeline items to be shifted:
before
after
=> fix right item width in timeline (with 2k+ screens)

phpstan.neon
PHPStan spawn as many processes as there are available threads on the machine. PHPStan uses almost about 1.5GB per thread, probably because GLPI code does not use strict type hinting, so PHPStan has to analyse really long execution chains to detect errors.
On my machine, when running the `tests/run_tests.sh` script, it spawns 8 processes, that are so using up to 12GB of memory and my system completely freezes, with a 50+ load average. I guess `docker` tries to use swap memory. Last time I tried to let PHPStan finishes its job, I had to reboot my machine after 3 hours because I was not even able to unlock my Ubuntu session. …
=> Limit max processes used by PHPStan

js/common.js
I've recently spotted that some uploaded files had their first letter truncated:
After some digging I found out that our `uniqid` function would return a 22 (~10% of the time) or 23 (~90% of the time) chars string, while our backend always expect a 23 chars string.
This is explained by this part of the `uniqid` function code, which may return random numbers of different sizes:
The new code ensure the random number will be at least `10000000`, thus always having the same size. 
=> Fix uploaded files names

ajax/dropdownAllItems.php
Make ID visible in dropdownAllItems in case it is CommonITILObject, it is now used in fields panel to link any to any ITIL object..
Without ID it will be quite a problem to match correct ticket in many cases..
=> Force ID to be visible for CommonITILObjects in dropdownAllItems

src/SavedSearch.php, tests/functionnal/SavedSearch.php
| Fixed tickets | #12690
SavedSearch_User relation class/table is only used to track the default searches for users and not which searches users have access to, so the condition in the JOIN clause doesn't make sense to me. Removing it fixes the visibility so users can only see their own private searches or, if they have the READ right, the public searches.
=> Fix saved search visiblity

src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php, tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
Even if it is not usual, it may happens that a coment is added on a table index. In this case, comment should be ignored during integrity checks, to prevent following kind of result:
```
Le schéma diffère pour la table "glpi_notifications_notificationtemplates".
--- Schéma de base de données attendu
+++ Schéma de base de données actuel
@@ @@
`notificationtemplates_id` int NOT NULL DEFAULT 0,
PRIMARY KEY (`id`),
UNIQUE KEY `unicity` (`notifications_id`,`mode`,`notificationtemplates_id`),
-  KEY `mode` (`mode`),
+  KEY `mode` (`mode`) COMMENT 'See Notification_NotificationTemplate::MODE_* constants',
KEY …
```
=> Ignore KEY comments during database integrity checks

src/User.php
Needs to use ldap_escape() std function to be sure that "all" chars in $user_dn are correctly escaped.
=> Use of native PHP function for escaping user_dn

css/includes/_base.scss, css/includes/components/_asset-form.scss, js/common.js, src/CommonDBTM.php, src/CommonGLPI.php, src/User.php, templates/components/form/header.html.twig, templates/components/form/header_content.html.twig, templates/generic_show_form.html.twig
| Fixed tickets | #11493
Visually moved the item type and name header back to the navigation header so that is would be visible in each tab of an asset form.
~Still working on the functionality of the massive action dropdown and child entity checkbox as they are no longer located within the main form and are therefore missing some required inputs. Some more testing with modals needs done too. Modals of at least dropdown itemtypes seem to work properly with showing the header inside the form rather than the navigation header.~
=> Move main asset header back to the nav header

.github/label-commenter-config.yml, .github/workflows/label-commenter.yml
We often waste valuable time unsuccessfully investigating issues because we do not have all the information requested. Automatically closing this kind of issues by just adding a `invalid` label mays seems a bit rude, but I am pretty sure it will be more efficient than politely asking for missing information. Also, the requester not providing the requested information is already disrespectful, so closing their ticket is probably a good way to reframe it.
I also added autoclose action when `support` and `feature suggestion` labels are added.
=> Autoclose issues by adding a label

src/Api/API.php, tests/web/APIRest.php
I've noticed this API call (adding a group to a ticket) was failing: 
It failed because the content of  `_actors` wasn't converted properly from stdobject to array.
Fix seems to be calling the `inputObjectToArray` instead of simply casting to array (like it's already done for the `createItem` process).
Not sure why our json is decoded as an object and then converted to an array later.
Maybe it would be simpler to decode it directly as an array ?   
If so it should probably be done in another PR (main) to be safe.
Second fix was regarding this warning:
```
[2022-09-21 10:11:06] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "errors" in /home/aclai/localhost/glpi/10.0-bugfixes/src/Api/API.php at line 2369
Backtrace :
src/Api/API.php:1990 …
```
=> API: fix update input and warnings

src/Config.php
Using `json_decode` permit to have a better handling of array and boolean values, and to know the exact value of each constant.
```diff
- GLPI_IDOR_EXPIRES: 7200
+ GLPI_IDOR_EXPIRES: "7200"
- GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
+ GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
- GLPI_SERVERSIDE_URL_ALLOWLIST: Array
+ GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
- GLPI_INSTALL_MODE: GIT
+ GLPI_INSTALL_MODE: "GIT"
- GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
+ GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
- GLPI_USER_AGENT_EXTRA_COMMENTS: 
+ GLPI_USER_AGENT_EXTRA_COMMENTS: ""
```
=> Fix array value handling in GLPI constants display

src/Dropdown.php, templates/components/itilobject/fields/global_validation.html.twig
| Fixed tickets | #12677
The global approval field in ITIL Objects was not aligned properly if it was supposed to be in the second column.
There was also an issue with the dropdown widths when they had icon buttons. This seemed to be from changing `w-100` class to `w-150` when icons were present which fixed the display in the search engine, but inside a form it caused the dropdown to overflow into the next column.
=> Fix global approval and dropdowns field display

src/NotificationTargetCommonITILObject.php
| Fixed tickets | #12727
`$supplier` variable, containing a `Supplier` instance, was erased by an `array`.
I renamed variables to prevent this kind of issues.
=> Fix notification error when supplier is added to ticket

src/ComputerAntivirus.php, templates/components/form/computerantivirus.html.twig, templates/generic_show_form.html.twig
Use twig for ```ComputerAntivirus``` (usefull for locked field)
I take this opportunity to : 
- add the "Lock" tab
- fix ```expiration_date``` to ```NULL``` if empty
- propage ```field_options``` for ```twig``` ```date_field``` (usefull for locked field icon / toolti)
Before : 
After : 
Need https://github.com/glpi-project/glpi/pull/12722 for ```is_dynamic``` generic field
=> Twig computer antivirus

templates/components/form/buttons.html.twig
- type may be submit (default) or button
- onclick attribute
TODO:
historical tab does not refresh when changing the count of items per page. It refreshes the tab of the item displayed under the modal.
Helps to improve UX in incoming tabs in modals of Formcreator. USed (for now) to show a "Apply" button which saves form data without closing the modal, and editing setings in several tabs without closing / reopening the question.
To satisfy this need, an additional button shall not be of type submit and shall trigger some JS code.
Example of this implementation
```php
if (!$this->isNewItem()) {
// Have an "apply" button if the item already exists in DB
$options['addbuttons'] = [
'apply' => [
'type' => 'button',
'text' => __('Apply', 'formcreator'),
'onclick' => …
```
=> more parameters for additional buttons in generic_form template

src/RuleImportAsset.php, tests/functionnal/Glpi/Inventory/Inventory.php
When importing a Phone, there were 2 issues: agent were linked to the correct itemtype, but items_id was always 0; and RuleMatchedLog was set to Unmanaged.
=> Fix phone import

front/notificationtemplatetranslation.form.php
In the translations of the notification templates. the link refers to: ".../front/notificationtemplateetranslation.php" (which does not exist) instead of ".../front/notificationtemplate.form.php?id=xx"
| Fixed tickets | !24997
=> fix(Notification Template Translation): list url 404

css/includes/components/itilobject/_timeline.scss
The current limit of 700px systematically truncates the date when scheduling a task.
By increasing this max, it allows to see the hours and minutes.
https://github.com/glpi-project/glpi/commit/b76e5b8c7f047cf197579c2f0db7402cc9da23a2
=> fix(timeline content): enlarge to avoid truncating the date

src/Plugin.php
As discussed with @cedric-anne and @orthagh, we want to avoid calling the `CHANGE_PROFILE` hook on plugin activation if there is no active session.
Before : 
After :
=> Fix session related warnings on plugin activation from cli

src/SavedSearch.php, tests/functionnal/SavedSearch.php
| Fixed tickets | #12756
The last fix (post-10.0.3) had fixed the issue of seeing other user's private searches in the list but only if the user didn't have the "config" UPDATE permission. This PR should only show public searches and your own private searches in the flyout list. If you have the "config" UPDATE permission, you can still see all the searches in the "Manage saved searches" search list.
=> Restore saved search visiblity from 10.0.2

src/Ticket_Contract.php
| Fixed tickets | #12632
As far as I understand, purpose of link between contract and ticket, introduced in #8947, is to be able to track tickets that have been processed under a given contract. The max number of items related to a contract should not, IMHO, have any impact on the number of tickets that can be created for this contract.
For instance, if my contract is limited to 15 assets (i.e. computers), users of these assets should be able to create as many tickets as they have problems with these assets.
=> Do not limit number of tickets linked to a contract

src/Appliance.php
| Fixed tickets | #12766
There is no `$_POST['entity_restrict'] ` sent. Removing the option will make the dropdown filtered on currently active entities.
=> Fix entity restriction in Add Appliance massive action

front/knowbaseitem.form.php, front/reminder.form.php, front/rssfeed.form.php
| Fixed tickets | #12765
`entities_id` is not present in form data when adding a user in KB, Reminder or RSS targets.
=> Fix warning during user visibility definition

src/Event.php
Some itemtypes are not searchable on the events log page:
Fixed by adding used itemtypes to the 'Source' search option.
Previous values are moved to a "Special" dropdown group, while itemtpes are in the new `Item` dropdown group:
| Fixed tickets | !25021
=> Events: search by itemtype

src/Event.php
Fix for #12770 :
* Avoid failure if no itemtype is found by `getItemtypeFromType()`
* Trigger warning on unsupported itemtype
* Add support for "solution"
=> Events: search by itemtype 2

src/System/Diagnostic/DatabaseSchemaConsistencyChecker.php
Checks the presence of the ```is_deleted``` column if the ```is_dynamic``` column is present
Exclude ```glpi_usermails``` and ```glpi_profiles_users``` tables
need : https://github.com/glpi-project/glpi/pull/12775
=> feat(core): check is_deleted column if table have is_dynamic

src/Printer_CartridgeInfo.php
=> feat(cartridge): better display

install/empty_data.php, install/migrations/update_10.0.3_to_10.0.4/inventory.php, src/Lockedfield.php, src/Profile.php
Add dedicated right for locked field (only ```CREATE``` (for global lock) and ```PURGE``` are needed)
=> feat(inventory): add dedicated right for locked field

src/CalDAV/Backend/Calendar.php
| Fixed tickets | #12753
1. `PURGE` right was not checked before deleting the item.
2. The `CommonDBTM::deleteFromDB()` method was used. I do not remember if it was intentional, but I think it would be better to use the `CommonDBTM::delete()` method instead.
=> Fix CalDAV object deletion handling

src/NetworkEquipment.php, src/Printer.php, src/SNMPCredential.php, templates/components/form/inventory_info.html.twig, templates/generic_show_form.html.twig
Move ```snmpcredentials_id``` dropdown to main form
Allow user to fill field when the object is created (or on update).
some users use this feature to no longer perform the network discovery task, but just the SNMP inventory on an IP range 
Compatible with ```locked_field```
Printer : 
NetworkEquipement : 
=> feat(inventory): move snmpcredentials_id to main form

src/Monitor.php
add missing ```UUID``` searh option for ```Monitor```
| Fixed tickets | !25059
=> fix(monitor): add missing UUID searh option

src/NotificationEventAbstract.php
Fixes error returned after PHPStan update (see #12823).
It seems to be a false positive, but, anyway, `$notprocessed` items are never used.
=> Fix PHPStan issue by removing dead code

src/CommonDBTM.php, src/Document.php
When an ITILObject was created by inserting an image that was already in use, but whose corresponding file had been deleted, the image was not reimported, because it was only checked if the document was already present in the database, but not if the file was available.
This PR checks the accessibility of the file to reimport it if it is missing.
| Fixed tickets | !24661
=> fix(document): check availability

templates/components/itilobject/timeline/form_followup.html.twig
Since 10.0, the 'source of followup' was no longer displayed directly in the followup, you had to edit it to see its value.
| Fixed tickets | !25076
=> fix(timeline ticket): display source of followup

src/Toolbox.php
Follows #12802 .
If there is nothing in buffer, and if `output_buffering="off"`, a warning was trigerred (`PHP Notice (8): ob_clean(): failed to delete buffer. No buffer to delete in /var/www/glpi/src/Toolbox.php at line 700`).
=> Fix warning on document send buffer cleaning

css/legacy/includes/_styles.scss, src/CommonDropdown.php, src/CommonGLPI.php, src/Dropdown.php, src/Item_Ticket.php
When the category is very large, the link to the FAQ was reduced and became almost invisible:
Before:
After:
| Fixed tickets | !25091
=> fix(ticket): FAQ link too small

src/AutoUpdateSystem.php, src/Features/Inventoriable.php, src/Inventory/Asset/MainAsset.php, src/Inventory/Asset/VirtualMachine.php
I've found some duplicated auto update systems:
Not sure how it happens, so I'm adding a simple check to ensure we don't create a system that already exists.
I've also added a constant for "GLPI Native Inventory".
| Fixed tickets | !25096
=> Prevent duplicates "GLPI Native Inventory" auto update systems

src/Transfer.php
Prevent warning
```
[2022-10-04 10:54:57] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "sockets_id" in /home/DEV/GLPI/10.0-bugfixes/src/Transfer.php at line 3835
Backtrace :
src/Transfer.php:1220                              Transfer->transferNetworkLink()
src/Transfer.php:265                               Transfer->transferItem()
```
=> fix(transfer): fix warning undefined array key

install/empty_data.php
During update, `0` value is set on all profiles that are not matching required rights. Forcing `0` value on install makes fresh installed data consistent with updated data, and fixes main branch `Profile::testClone()` test.
=> Fix default locked_field rights

install/migrations/update_10.0.3_to_10.0.4/inventory.php, install/mysql/glpi-10.0.4-empty.sql, src/Inventory/Asset/OperatingSystem.php, src/Item_OperatingSystem.php, templates/pages/assets/operatingsystem.html.twig, tests/functionnal/Glpi/Inventory/Assets/OperatingSystem.php
Add os installation date from inventory
| Fixed tickets | [#233](https://github.com/glpi-project/glpi-inventory-plugin/issues/233)
=> Add os installation date

src/Inventory/Asset/MainAsset.php
When ```transfer_strategy``` does not allow the automatic transfer
the inventory does not put the old ```entities_id``` to ```item``` -> so the ```item``` changes entity.
| Fixed tickets | !25031
=> fix(inventory): revert entities_id if auto transfer is not allowed

install/migrations/update_10.0.3_to_10.0.4/dashboard.php, install/mysql/glpi-10.0.4-empty.sql
| Fixed tickets | https://forum.glpi-project.org/viewtopic.php?id=285002
Some classes from plugins may have very long names especially if they are relational classes like "PluginGenericobjectVideoprojecteur_PluginGenericobjectVideoprojecteurModel". The card ID and gridstack ID fields for dashboard items are limited to 100 characters which is not enough for these cases.
This PR raises the character limit to 255 characters.
=> Fix storing dashboard cards with long IDs

src/Dropdown.php
Database Instance Category dropdown option was not showing in the Dropdowns page and if you went directly to the search page using the "i" icon next to the field in a Database Instance form, it would not have the correct breadcrumbs so adding was blocked from there.
=> Fix missing Database Instance Category dropdown option

src/State.php, tests/functionnal/State.php
Trying to rename a state (`front/state.form.php`) named `TEST` to `TÉST` will throw an error.
This is because we search for existing values using a standard SQL query, which is accent insensitive:
```sql
SELECT * FROM `glpi_states` WHERE `name` = 'TÉST' 
```
```
+----+------+
| id | name |
+----+------+
|  1 | TEST |
+----+------+
1 row in set (0.00 sec)
```
We must specify the collation to avoid this issue:
```sql
SELECT id, name FROM `glpi_states` WHERE `name` = 'TÉST' collate utf8mb4_bin;
```
```
Empty set (0.00 sec)
```
| Fixed tickets | !25023
=> Make isUnique check for state accent insensitive

src/CommonDBVisible.php
`glpi_groups_knowbaseitems.entities_id` used to be set as `-1` to indicate no entities restrictions.
This behavior was modified to use `NULL` + an explicit `no_entity_restriction` field in GLPI 10 (unsigned keys restrictions).
See the relevant migration :
It seems this code was not updated accordingly.
| Fixed tickets | !25051
=> Fix KB visibily when group restriction is set as 'no_entity_restriction'

css/includes/components/_select2.scss, css/palettes/_defaults.scss
Inputs requires a little more contrast and select2 missed text-muted color
Before:
After:
=> fix colors when an input is in disabled state

src/NotificationEventMailing.php
If ```height``` is not defined from ```img``` 
images are distorted in notifications
Try to compute ```height``` or ```width``` if need.
| Fixed tickets | !24988 (seel last follow up)
=> fix(notification): fix img size when height is null

install/migrations/update_10.0.3_to_10.0.4/computer.php, install/mysql/glpi-10.0.4-empty.sql, src/Computer.php, src/Inventory/Asset/MainAsset.php, templates/generic_show_form.html.twig, tests/functionnal/Glpi/Inventory/Assets/Computer.php, tests/functionnal/Glpi/Inventory/Inventory.php
Get ```last_boot``` date from ```operatingsystem``` available in the ```boot_time``` node
```json
"operatingsystem": {
"arch": "x86_64",
"boot_time": "2020-06-09 07:58:08",
"fqdn": "glpixps",
"full_name": "Fedora 31 (Workstation Edition)",
"hostid": "a8c07601",
"kernel_name": "linux",
"kernel_version": "5.6.15-200.fc31.x86_64",
"name": "Fedora",
"timezone": {
"name": "CEST",
"offset": "+0200"
},
"version": "31 (Workstation Edition)"
}
```
```xml
<OPERATINGSYSTEM>
<ARCH>64-bit</ARCH>
<BOOT_TIME>2019-09-26 11:24:17</BOOT_TIME>
<DNS_DOMAIN>glpi-dev</DNS_DOMAIN>
<FQDN>mkjghkghkj.glpi-project.dev</FQDN>
<FULL_NAME>Fedora 31 (Workstation Edition)</FULL_NAME>
<INSTALL_DATE>2015-07-02 11:57:03</INSTALL_DATE>
<KERNEL_NAME>MSWin32</KERNEL_NAME>
<KERNEL_VERSION>6.3.9600</KERNEL_VERSION> …
```
=> feat(inventory): manage computer last boot

src/Stat/Data/Sglobal/StatDataSatisfaction.php
Answered values were missing from the graph
| Fixed tickets | !25143
=> fix(stat): satisfaction survey - missing answered

inc/define.php, src/CommonDBChild.php, src/CommonDBRelation.php, src/Lock.php
Actually, GLPI displays only the locks of the current itemtype.
But some data are related to ```Ìtem_XXXX``` relationship who do not have  their own form (like Computer)
and GLPI allow user to update it directly from current itemtype
It is frustrating to see the lock in the ```OS``` tab but not in the ```Lock``` tab
Actually is see two relationship in this case :
- ```Item_OperatingSystem```
- ```Item_Disk```
So this PR :
- compute related ```lock``` (```Item_OperatingSystem``` and ```Item_Disk```) for current ```itemtype```
- display ```itemtype``` and ```value``` from ```glpi_lockedfield``` table
- add ```Item_OperatingSystem``` to ```$CFG_GLPI['inventory_lockable_objects']``` (missing)
- Fix ```Locked items```display (Software / license ```header``` / ```massiveAction``` display if …
=> fix(lock): Display all lock available 

src/Html.php
If a plugin calls `Profile::displayRightsChoiceMatrix()` with an empty matrix, it will produce warnings as some variables are declared only inside `foreach` loops.
See #12875.
=> Handle empty rights matrix

src/Console/Database/FixHtmlEncodingCommand.php
CLI tool to fix data having bad HTML encoding in database. 
Currently fixes double encoded items 
internal ref 24943
| Fixed tickets | internal: 24943
=> HTML encoding fix tool

css/standalone/dashboard.scss, js/dashboard.js
Replace #12880 and #12532
fixes:
=> small dashboard issues

src/Dashboard/Widget.php
fix regression added in #12476
intermediate `<div>` doesn't have correct height.
To note: this (and the bug in the previous pr) is completely fixed by #12591
=> fix height of dashboard charts in their cards

src/Console/Database/CheckSchemaIntegrityCommand.php, src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
1. Message was not correct (was `Checking database integrity of version "" is not supported.` and will now be `Checking database integrity of plugin "formcreator" is not supported.`.
2. A wong variable usage was breaking the feature for plugins (fixed by: `!empty($schema_version)` -> `!empty($schema_path)`).
3. Now it will be possible to run the command even on inactive plugins. Plugin is responsible to know which version of schema is actually installed.
=> Fix database integrity check on plugins

front/computervirtualmachine.form.php, front/item_disk.form.php, front/networkname.form.php, src/CommonDBTM.php, src/ComputerVirtualMachine.php, src/Item_Disk.php, src/Item_SoftwareVersion.php, src/NetworkName.php, tests/functionnal/Item_Disk.php
Fix ```purge``` / ```delete``` behavior from ```dynamic``` items. 
Ensure that this function is used :
```php
public function useDeletedToLockIfDynamic()
{
return false;
}
``` 
and be sure that ```item.form.php``` handle ```deleted``` action.
Ensure that this function is NOT used (this use case is handled by ```MassiveAction``` logic) :
```php
public function useDeletedToLockIfDynamic()
{
return false;
}
``` 
=> fix(inventory): do not purge dynamic item, lock it

src/Inventory/Asset/OperatingSystem.php
Prevent SQL error (for new asset manually / dynamically imported)
```sql
Note:  Data truncated for column 'install_date' at row 1
```
Convert ```datetime``` to ```date```
=> fix(inventory): convert datetime to date for os installation date

src/MassiveAction.php
| Fixed tickets | !25195
Regression from #10975 (https://github.com/glpi-project/glpi/pull/10975/files#diff-284b41ead4d268948c291846bcb61a98c51a0eebb76968e6d09a40b485909777L280) because the control:
```
if (!isset($this->remainings)) {
...
} 
```
has been removed.
For explanation, when a massive takes more time than `max_execution_time`, there is a mechanism to reload the page with an identifier to retrieve the current execution and continue to parse the items stored in `$remainings`.
Previously, as the property was not declared explicitly:
- it was not set at the first execution (before reloading)
- it was set after reloading (by …
=> fix infinite loop on massive actions

src/KnowbaseItem.php, tests/functionnal/KnowbaseItem.php
The FAQ / KB view does not seem to work properly.
You can see on the following images that the category tree indicate that some articles should be visible, however when you click on the category you find out that there is no valid articles:
The code handling this list was hard to read because it was handling two different cases (FAQ and KB) at the same time.
I've: 
* Split and moved the code around to have proper KB / FAQ "code paths" which are easier to read and understand.
* Added a great number of tests which should handle every possible KB configuration.
Regarding the specific error in the images above, I think the `is_faq => 1` condition was not properly applied for self-service users (it was thrown in an `OR` clause with other criteria that should only be used for the KB side, not …
=> Fix FAQ/KB

src/DBmysqlIterator.php
This would allow adding proper SQL mappings for the RSQL case-sensitive `=like=` filter added in the High-Level API.
https://github.com/glpi-project/glpi/blob/2ece3698fa2c015887ea4780b5a424b599aad56c/src/Api/HL/RSQLInput.php#L100-L112
=> Support case-sensitive LIKE queries

src/Search.php
"Type" fields were not translated in the search results, although a translation existed.
| Fixed tickets | !25100
=> fix(search): translation in search result

src/Dashboard/Grid.php
I've noticed that the `Dashboard\Grid\getAllDasboardCards` function was taking 4+ seconds of execution time on a production server.
The problems seem to come from calling `DBConnection::getReadConnection()` in `$add_filters_fct`, which is being executed in multiple double foreach loops.
This cause a lot of extra SQL requests if you are using replication :
Moving the variable outside the function allow to reduce the 4s of execution time to nearly 0s.
| Fixed tickets | !25025
=> Improve dashboard performances (replication)

templates/components/itilobject/timeline/form_followup.html.twig
!24785
Regression in #12684 (part of forcing waiting checkbox to true if ticket.status = WAITING). Fortunately not yet published in a release.
If needRopen() = true, we should not check the waiting checkbox
=> requester should be able to reopen

css/includes/components/_richtext.scss, src/RichText/RichText.php
In 9.5, the long follow-ups were not displayed entirely by default, there was a "read_mode" button to display everything.
This PR restores this feature.
| Fixed tickets | !25170
=> fix(timeline): restore the read_more button on long timeline items

src/Migration.php, tests/units/Migration.php
if an itemtype moves to a namespace, the table name does not change but the migration class fails in such case
From a internal discussion with @cedric-anne 
Solves a migration issue found in develop branch of Formcreator
=> fix itemtype migration

ajax/agent.php
Waiting for inventory response can block your session for a long time, especially if you are on a server with a proxy where each request will wait until the max timeout before failing.
Would this change be OK ?
I don't see any code that would impact the session after this line.
=> Do not block session with inventory request

src/Dashboard/Dashboard.php
When a user remained displayed on the dashboards and $_SESSION expired, each card added this message in `php-errors.log`:
```
glpiphplog.CRITICAL :   *** Uncaught Exception TypeError : array_intersect() : Argument #2 must be of type array, null given in .../src/Dashboard/Dashboard.php at line 481
Backtrace :
src/Dashboard/Dashboard.php:481 array_intersect()
src/Dashboard/Dashboard.php:155 Glpi\Dashboard\Dashboard::checkRights()
src/Dashboard/Dashboard.php:391 GlpiDashboard\Dashboard->canViewCurrent()
src/Dashboard/Grid.php:109 Glpi\Dashboard\Dashboard::getAll()
src/Dashboard/Grid.php:1547 Glpi\Dashboard\Grid::loadAllDashboards()
src/Html.php:1412 Glpi\Dashboard\Grid::getDefaultDashboardForMenu()
src/Html.php:1520 Html::getMenuInfos()
src/Html.php:1779 Html::generateMenuSession() …
```
=> fix(dashboard): session expiration

src/Inventory/Asset/InventoryNetworkPort.php
It appears that the agent does not always report the type of networkport from inventory file
```json
{
"description": "Intel(R) Ethernet Connection (13) I219-V",
"mac": "A0:29:19:37:5D:C1",
"pciid": "8086:15FC:0A20:1028",
"pnpdeviceid": "PCI\\VEN_8086&DEV_15FC&SUBSYS_0A201028&REV_20\\3&11583659&0&FE",
"status": "down",
"type": "ethernet", //missing node
"virtualdev": false
},
```
So GLPI adds a ```NetworkPort``` with ```instantiation_type``` to ```null``` (hard to do better without information :disappointed: )
But if the agent improves and finds a way to report this information, GLPI does not update the ```NetworkPort```.
It adds a new one because the  ```instantiation_type ``` is one of reconciliation keys.
I propose to remove ```instantiation_type ``` from reconciliation keys to allow …
=> feat(inventory): allow instantiation_type update

front/networkport.form.php, src/NetworkPort.php
Fix ```NetworkPort``` ```delete``` / ```purge```.
Use ```delete``` step because of ```is_deleted``` database column instead of directly ```purged```
| Fixed tickets | #12971
=> fix(networkport): fix delete / purge behavior

inc/define.php
Add ```Monitor``` to ```$CFG_GLPI['inventory_lockable_objects']```
Usefull to add global lock
=> fix(lockedfield): add missing monitor itemtype

src/Console/Migration/UnsignedKeysCommand.php
Error message in `glpi:migration:unsigned_keys` command is not clear. Some people are asking us what they are supposed to do, meaning they do not understand what the message is advicing for (see !25184).
=> Make unsigned keys migration errored result more clear

front/networkport.form.php, front/socket.form.php, src/Dropdown.php, src/Socket.php, templates/pages/assets/socket.html.twig
Permit to add several ```Socket``` from an item
Compared to the standard add form
```Position``` field is hidden (compute on add) and ```NetworkPort``` field is hidden too (useless here)
=> feat(socket): add several socket from item

src/Printer_CartridgeInfo.php
Fix Cartridge Info ```searchoption```
I don't known why, but this method try to deals with some ```key``` that not exist
- ```$remaining_field = "toner{$color}remaining";```
- ```$max_field = "toner{$color}max";```
- ```$used_field = "toner{$color}used";```
```glpi_printers_cartridgeinfos``` contain only the current level of cartridge (```value``` column)
```sql
+----+-------------+--------------+-------+---------------------+---------------------+
| id | printers_id | property     | value | date_mod            | date_creation       |
+----+-------------+--------------+-------+---------------------+---------------------+
|  2 |           2 | fuserkit     | 22    | 2022-10-14 10:29:30 | 2022-10-14 10:29:30 |
|  3 |           2 | tonerblack   | 52    | 2022-10-14 10:29:30 | 2022-10-14 …
```
=> fix(cartridge_info): fix and refactor code

front/commonitiltask.form.php, src/CommonITILTask.php, templates/components/itilobject/timeline/form_task.html.twig
To remove the planning of a task, it was necessary to remove the whole task and recreate it without planning.
| Fixed tickets | !25166
=> fix(task): unplan task

front/snmpcredential.form.php, front/snmpcredential.php, install/empty_data.php, install/migrations/update_10.0.3_to_10.0.4/inventory.php, src/Profile.php, src/SNMPCredential.php
Add dedicated right (```ALLSTANDARDRIGHT```) for ```SNMPCredential``` 
=> feat(inventory): add dedicated right for SNMP Credential

src/User.php
| Fixed tickets | #12898
1. `addslashes` may incorrectly deal with multibyte strings.
2. HTML special chars should also be encoded.
=> Fix SSO variables encoding issues

front/refusedequipment.form.php, front/refusedequipment.php, install/empty_data.php, install/migrations/update_10.0.3_to_10.0.4/inventory.php, src/Profile.php, src/RefusedEquipment.php
Add dedicated right (```READ```, ```UPDATE```, ```PURGE```) for ```SNMPCredential``` 
Fix ```refusedquipment.form.php``` to handle ```update```
The ```showForm``` doesn't seem to prohibite the update, but is it really useful to allow the update ?
=> feat(inventory): add dedicated right for RefusedEquipement

src/Printer_CartridgeInfo.php
Some ```Printer``` inventory file handle ```drum``` info
```xml
<CARTRIDGES>
<DRUMBLACK>22</DRUMBLACK>
<DRUMCYAN>22</DRUMCYAN>
<DRUMMAGENTA>22</DRUMMAGENTA>
<DRUMYELLOW>22</DRUMYELLOW>
<TONERBLACK>OK</TONERBLACK>
<TONERCYAN>OK</TONERCYAN>
<TONERMAGENTA>OK</TONERMAGENTA>
<TONERYELLOW>OK</TONERYELLOW>
<WASTETONER>OK</WASTETONER>
</CARTRIDGES>
```
Update ```Printer_CartridgeInfo``` to handle it from ```Printer``` list
With ```drum``` info ```toner``` key contain string (```OK```, ```WARNING``` etc ...)
Update function to return value if not numeric.
Use this fiel to test -> [9462.zip](https://github.com/glpi-project/glpi/files/9786144/9462.zip)
| Tests pass? …
=> feat(cartridge): add drum searchoption (like toner searchoption)

front/agent.form.php, front/agent.php, install/empty_data.php, install/migrations/update_10.0.3_to_10.0.4/inventory.php, src/Agent.php, src/Profile.php
Add dedicated right (```ALLSTANDARDRIGHT```) for ```Agent``` 
Except ```CREATE```
=> feat(inventory): add dedicated right for Agent

src/Search.php, tools/getsearchoptions.php
| Fixed tickets | #12948
This code seems very old (from the addition of Search engine: bb9c4790c424bc823b65b7e73d72091b684db3ef), obviously bad design and feature of returning a reference of searchoptions seems not used
=> Search::getOptions should not return var by reference

src/Search.php, src/Search/Input/QueryBuilder.php, src/Search/Output/AbstractSearchOutput.php, src/Search/Output/ExportSearchOutput.php, src/Search/Output/HTMLSearchOutput.php, src/Search/Output/MapSearchOutput.php, src/Search/Output/SYLKSearchOutput.php, src/Search/Provider/SQLProvider.php, src/Search/Provider/SearchProviderInterface.php, src/Search/SearchEngine.php
- Move logic for `Search::show` to new classes.
- Improved handling of Map HTML output by adding a new `prepareInputParams` method for search output classes. This allows forcing some criteria so the location fields are included in the Map view
- Added `showPreSearchDisplay` method for search output classes to handle showing widgets before the search input form such as the mini dashboard shown for the HTML output for Tickets
- Unified the method naming for displaying/outputting the results
- Moved the remaining method logic left in `Search`
=> Streamline Search::show logic

src/CommonITILObject.php, src/Search.php
Add entities as a new meta criteria for CommonITIL items:
| Fixed tickets | !25017
=> CommonITIL: add 'Entity' meta search criteria

css/includes/components/_select2.scss
Fix syntax that is illegal according to SCSS documentation.
See https://sass-lang.com/documentation/style-rules/parent-selector
=> Fix illegal SCSS syntax

src/Toolbox.php
| Fixed tickets | #13022
It seems that ``mb_convert_encoding`` handles more chars than ``iconv``.
=> Fix ISO-8859-1 document filename conversion

css/includes/components/_richtext.scss
When there was a table with many columns, the words in the cells were cut off, which was not readable.
Before:
After:
| Fixed tickets | !25297
=> fix(ticket): unreadable table when many columns

src/Planning.php
check ```PURGE``` instead of ```DELETE``` to allow users to ```delete``` external event
Because ```PlanningExternalEvent``` cannot be deleted (no ```is_deleted``` fields in database)
```sql
mysql> explain glpi_planningexternalevents;
+-----------------------------------+--------------+------+-----+---------+----------------+
| Field                             | Type         | Null | Key | Default | Extra          |
+-----------------------------------+--------------+------+-----+---------+----------------+
| id                                | int unsigned | NO   | PRI | NULL    | auto_increment |
| uuid                              | varchar(255) | YES  | UNI | NULL    |                |
| planningexternaleventtemplates_id | int unsigned | NO   | MUL | 0       |                |
| …
```
=> fix(right): check PURGE instead of DELETE
