glpi-project/glpi

src/Inventory/Asset/VirtualMachine.php
tests/fixtures/inventories/lxc-server-1.json
tests/functionnal/Glpi/Inventory/Inventory.php

Fix virtual machines RAM update, add tests; closes #12416

---

src/CommonTreeDropdown.php
src/Search.php
tests/functionnal/CommonTreeDropdown.php

Fix handling of null value in completename

---

src/Inventory/Asset/Cartridge.php
tests/functionnal/Glpi/Inventory/Assets/Cartridge.php

Fix cartridge info update; closes #12429

---

src/Inventory/Asset/Antivirus.php
src/Inventory/Asset/Bios.php
src/Inventory/Asset/DatabaseInstance.php
src/Inventory/Asset/Device.php
src/Inventory/Asset/InventoryAsset.php
src/Inventory/Asset/InventoryNetworkPort.php
src/Inventory/Asset/MainAsset.php
src/Inventory/Asset/Monitor.php
src/Inventory/Asset/OperatingSystem.php
src/Inventory/Asset/Peripheral.php
src/Inventory/Asset/Printer.php
src/Inventory/Asset/VirtualMachine.php
src/Inventory/Asset/Volume.php
tests/functionnal/Glpi/Inventory/Assets/Bios.php
tests/functionnal/Glpi/Inventory/Assets/Printer.php
tests/functionnal/Glpi/Inventory/Inventory.php

Try to fix numeric OS version ignored and all similar issues
Indent, typos

Change way links are handled

---

src/CommonDBTM.php
src/Html.php

Add more info for access errors from displayFullPage

---

src/NotificationTargetCommonITILObject.php

New labels for CommonITILObject notifications
- entity.registration_number => Administrative Number
- assigntousers.phone => Technician phone
- assigntousers.phone2 => Technician phone 2
- assigntousers.mobile => Technician mobile phone
- assigntousers.category => Technician category
- assigntousers.location => Technician location
- assigntousers.address => Technician address
- assigntousers.postcode => Technician postal code
- assigntousers.town => Technician city
- assigntousers => List of technicians

New tags for CommonITILObject

---

install/migrations/update_10.0.x_to_10.1.0/locations.php
install/mysql/glpi-10.1.0-empty.sql
src/CommonITILObject.php
src/DbUtils.php
src/Dropdown.php
src/Location.php
src/RuleTicket.php
tests/bootstrap.php
tests/functionnal/Dropdown.php
tests/functionnal/Software.php

Add a "Code" field in the locations: 
- displayable in the dropdown list (completename - code)
- displayable in the list of tickets
- usable in the business rules for tickets
Add an "Alias" field in the locations: 
- displayed instead of the 'completename' (dropdown list) if valued
- displayable in the ticket list.
| Fixed tickets | !24312

feat(location): add alias and code

---

src/NotificationTemplateTranslation.php
src/RichText/RichText.php
tests/units/Glpi/RichText/RichText.php

| Fixed tickets | #10930
Alternative to #12329.

Preserve tags case when text notification is built from html

---

templates/components/itilobject/timeline/timeline_item_header.html.twig
templates/components/itilobject/timeline/timeline_item_header_badges.html.twig

just had the case where i wanted to link a specific followup on our support (with 40 followups in the timeline).

add anchors to timeline

---

css/includes/components/_global-menu.scss

A few minor improvements to the collasped sidebar.
Before:
After: 
Side by side:
The issues that were bugging me with the sidebar were:
1\) Not enough top padding for the logo.
Now the padding match the padding used for the "non-collapsed" logo:
2\) The "go to menu" icon didn't match the size of the others icons.
It was even more noticeable if you swaped the icon for the same as the one below:
3\)  Not enough spacing between each menu:
It felt like the icons were accumulated at the top of the page.
They are now spaced a bit more evenly, matching the spacing of the "non-collapsed" menu.
4\) Can't read the active menu:
I don't think this one was intentional but it definitely needed to be fixed:
After fix:
I realize that some of these changes might be subjective, so let me know what you …

Collasped sidebar tweaks

---

src/Html.php

The PHPDoc and parameter name for this function was missleading.
It says the function expect the name of a `textarea` element, when it actually need its id.
Related: https://github.com/pluginsGLPI/news/pull/112

Html::initEditorSystem() Fix phpdoc and var name

---

src/Database.php
src/DatabaseInstance.php
src/Monitor.php
src/NetworkEquipment.php
src/NetworkName.php
src/NetworkPort.php
src/Peripheral.php
src/Phone.php
src/Printer.php
src/Unmanaged.php

Add missing Lock tab for item
| Fixed tickets | #11985

fix(asset): add missing Lock tab for item

---

src/CommonITILTask.php

Change tasks were displayed in table without proper data.
For future it should be probably rewritten in more generic way not referring to specific ITIL Types.. 
| Fixed tickets | #12480

Fix ChangeTask on Central view

---

src/NetworkPortInstantiation.php

Before
After
| Fixed tickets | #12484

fix(ui): btn render to be more understandable

---

templates/pages/login.html.twig

fix plugin hook display on login page

---

src/Session.php

The `Session::canImpersonate()` returns some error message even if the user isn't actually allowed to impersonate anyone (because he isn't an administrator and doesn't have the "impersonate" right).
You might even see some detailed message about specific case because such cases are treated before checking the user rights :
I think this message shouldn't be displayed if the user isn't allowed to impersonate anyone anyway.
He should have no knowledge of this button (and feature).

Impersonate: don't show icon to users without the correct rights

---

src/Dropdown.php

Fix dropdownFindNum for types without a name field

---

src/PendingReason.php

| Fixed tickets | https://discord.com/channels/402399026168725505/517977882824409088/1011665858898182154

add day options for pending reason auto followups

---

src/Inventory/Conf.php

Fix potential PHP notice

---

src/CommonDropdown.php

Fix entity replacement dropdown options

---

src/Database.php

Fix Database item deletion behavior

---

templates/components/itilobject/timeline/timeline.html.twig

When the ticket is in the closed state, the status of the ticket tasks was not displayed.
| Fixed tickets | !24685

fix(task): show status when ticket closed

---

src/CommonGLPI.php
templates/layout/parts/context_links.html.twig

Cannot access save searches lists from some plugins

---

src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php

I will update tests once texts will be validated.

Enhance readability of database diff

---

src/Domain.php

Hide domain record links if profile has none manageable

---

src/CommonITILObject.php

fix check for date field value
since new format of default value introduce by  -> https://github.com/glpi-project/glpi/pull/12568

fix(ticket): update check for date field

---

src/ComputerVirtualMachine.php

Fix tab title

---

src/DbUtils.php

On some edge cases, scanning `src` directory on each request may highly degrade performances.
With proposed PR, directory will be scanned only in debug mode, when value has not been found in cache (to be able to handle new classes in development environment).

Add persistent cache on DbUtils::fixItemtypeCase()

---

src/CommonITILObject.php

fix call to abstract method

---

src/Ticket.php

Handle _users_id_requester array format in delegatee rights checks

---

templates/pages/management/softwarelicense.html.twig

Keep withtemplate param after soft selection

---

.github/workflows/ci.yml

Run test suite on MariaDB 10.9

---

ajax/kanban.php
src/CommonITILObject.php

Try fixing handling of ITIL assign right in Kanban

---

js/modules/Kanban/Kanban.js
src/CommonITILObject.php

Fix ITIL Kanban under read-only profile

---

src/CommonDBTM.php
src/Inventory/Asset/MainAsset.php
src/Lockedfield.php
templates/components/form/fields_macros.html.twig
tests/functionnal/Lockedfield.php

Display last inventoried value for locked fields

---

src/Inventory/Asset/VirtualMachine.php
tests/functionnal/Glpi/Inventory/Assets/VirtualMachine.php
tests/functionnal/Glpi/Inventory/Inventory.php

Use rules to add computers as virtual machines

---

front/contract_supplier.form.php

Fix typo on contracts

---

src/SavedSearch.php
templates/layout/parts/saved_searches.html.twig

Don't load savesearches if their panel is not displayed

---

install/migrations/update_10.0.2_to_10.0.3/notifications.php

Fix notification default recipients migration

---

src/CommonITILObject.php

Fix fields from other ITIL objects during creation

---

install/migrations/update_10.0.2_to_10.0.3/notifications.php

| Fixed tickets | #12443 !24892
#10295 fixed partial sanitization of default notification templates, but many users migrating from GLPI 9.5.x are complaining about the fact that notifications for Changes and Problems are broken. Proposed change will fix existing notifications.

Fix partially sanitized notifications

---

src/CommonITILObject.php

Fix visibility for ITIL Kanban

---

src/CommonITILObject.php

In debug mode, the following error message appeared when doing "create a change from this ticket."

fix(change): undefine index is_change

---

front/itilsolution.form.php
templates/components/form/fields_macros.html.twig
templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/form_solution.html.twig
templates/components/itilobject/timeline/form_task.html.twig

Fix KB linking from Solution

---

src/HTMLTableGroup.php

Following a small mistake in last phpstan fixes PR.

Fix components display

---

install/migrations/update_10.0.2_to_10.0.3/notifications.php

| Fixed tickets | #12443 !24892
follows #12622
If user saved the notification template translation form that was containing a partially encoded HTML content, then some parts of the content will be twice encoded.

Fix double-encoded notification templates

---

CHANGELOG.md
inc/define.php
install/migrations/update_10.0.3_to_10.0.4.php
install/mysql/glpi-10.0.4-empty.sql
tests/functionnal/Update.php

Prepare 10.0.4

---

SECURITY.md

fix: update security policy

---

.tx/config

Switch to GLPI 10.1 transifex resource

---

src/Html.php

Prevent menu icon replacement by plugin subitems

---

src/Features/PlanningEvent.php

Fix new external event form

---

src/NetworkPort.php

| Fixed tickets | https://forum.glpi-project.org/viewtopic.php?id=284825
Network ports have no search page.

Hide NetworkPort list button

---

src/Console/Database/CheckSchemaIntegrityCommand.php
src/Console/Database/UpdateCommand.php
src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php

Conditions checked to validate that installed schema can be checked were different between `db:update` and `db:check`. Thus, presence of `install` directory was not handled correctly.
I moved the logic in `DatabaseSchemaIntegrityChecker` class, fix some edge cases, and add unit tests on it.

Handle removal of install directory in db:check command

---

src/Project.php

Fix Project Kanban for read-only profiles

---

front/login.php
src/Api/API.php
src/Auth.php
templates/pages/login_error.html.twig

Fix login error display

---

tools/build_glpi.sh

Drop useless inventory_format lib files from release archive

---

tests/GLPITestCase.php
tests/functionnal/Ticket.php
tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php

Add helper to test private/protected methods in test suite

---

src/Search.php

Fix name in user export

---

src/Agent.php

Fix stale agents status change; closes #12738

---

composer.lock

Update inventory format lib

---

src/Item_Ticket.php

Add columns status and location :
| Fixed tickets | !24970

feat(item ticket): add columns status and location

---

src/KnowbaseItem_Item.php

Fix possible undefined rand variable

---

install/migrations/update_10.0.3_to_10.0.4/inventory.php
install/mysql/glpi-10.0.4-empty.sql
tests/functionnal/Glpi/Inventory/Inventory.php

add missing is_deleted column
see : https://github.com/glpi-project/glpi/pull/12774

fix(schema): add missing is_deleted column

---

templates/components/form/item_device.html.twig

Fix ```Item_Device``` twig template (impossible to save or update)

fix(itemdevice): fix twig template

---

src/Auth.php
src/AuthLDAP.php
src/User.php

Fix usage of LDAP group conditions

---

src/Location.php

Check if ```itemtype``` ```isEntityAssign``` before adding ```getEntitiesRestrictCriteria```
| Fixed tickets | #12797

dix(location): check entity assign

---

src/CommonDBChild.php
src/NetworkName.php
src/RegisteredID.php
src/UserEmail.php
templates/components/form/networkname.html.twig

Use twig for ```NetworkName``` (usefull for ```locked field```)
Before : 
After : 

feat(core): use twig for Networkname

---

src/ComputerVirtualMachine.php
templates/components/form/computervirtualmachine.html.twig

Use ```twig``` template for ```ComputerVirtualMachine```

Twig ComputerVirtualMachine

---

src/AuthLDAP.php
src/ContentTemplates/Parameters/UserParameters.php
src/RuleCommonITILObject.php
src/User.php

Change user-facing Responsible text to Supervisor

---

src/Toolbox.php

Fix handling of output buffering clean in document sending

---

src/Console/Plugin/ListCommand.php

Add list plugin CLI command

---

templates/components/form/header.html.twig

Fix entity creation in modal

---

src/Inventory/Asset/InventoryAsset.php
tests/functionnal/Glpi/Inventory/Inventory.php

Fix manufacturer dictionary on inventory; closes #12811

---

src/SNMPCredential.php

Conflicts with SO added in #12369.

Change SNMPCredential SO ids

---

src/Search.php

Some fields were not translated in the search results, although a translation existed.
| Fixed tickets | !25100

fix(search): translation in search result

---

src/DatabaseInstance.php

| Fixed tickets | https://forum.glpi-project.org/viewtopic.php?id=284756

Add missing DB instance port and path fields

---

templates/components/form/fields_macros.html.twig

Saw this while working on dashboard
Before:
After:

force checkbox field to be center aligned

---

install/migrations/update_10.0.3_to_10.0.4/inventory.php
src/Item_OperatingSystem.php
templates/pages/assets/operatingsystem.html.twig

Some fix
- Define data format
- use hardcoded table name
See #12893

Fix os installation date

---

src/Application/View/Extension/DataHelpersExtension.php
src/Html.php
tests/units/Html.php

Add ability to preserve seconds in Html::convDatatime()

---

src/NotificationTemplate.php

Remove unwanted encoding in notification CSS

---

src/Agent.php
src/Inventory/Inventory.php
tests/functionnal/Agent.php
tests/functionnal/Glpi/Inventory/Inventory.php

Save agent port, if possible and if it run as service mode.

fix(inventory): save agent port if needed (service mode)

---

templates/components/form/header_content.html.twig
templates/generic_show_form.html.twig

Display is_dynamic info to form header

feat(inventory): display is_dynamic info to form header

---

src/Lock.php

Display more data from 'locked items' (link if possible, field if possible etc ..)

feat(inventory): display more data from 'locked items'

---

css/includes/components/_racks.scss
css/standalone/dashboard.scss

fix check of dashboard card

---

src/Lock.php

add additional info about ```locked fields``` and ```locked items```

feat(lock): add additional info

---

src/Lock.php

fix(ui): minor lock fix

---

src/CommonITILObject.php

Fix Ticket kanban with linked ticket steps

---

src/Inventory/Asset/Device.php
src/Item_DeviceBattery.php
src/Item_DeviceCamera.php
src/Item_DeviceControl.php
src/Item_DeviceDrive.php
src/Item_DeviceFirmware.php
src/Item_DeviceGraphicCard.php
src/Item_DeviceHardDrive.php
src/Item_DeviceMemory.php
src/Item_DeviceNetworkCard.php
src/Item_DevicePowerSupply.php
src/Item_DeviceProcessor.php
src/Item_DeviceSensor.php
src/Item_DeviceSimcard.php
src/Item_DeviceSoundCard.php
tests/functionnal/Glpi/Inventory/Assets/Battery.php
tests/functionnal/Glpi/Inventory/Assets/Device.php
tests/functionnal/Glpi/Inventory/Assets/Drive.php
tests/functionnal/Glpi/Inventory/Assets/Memory.php
tests/functionnal/Glpi/Inventory/Assets/NetworkCard.php

| BC breaks?    | maybe.
Alternative to #12853

Device inventory update

---

front/lockedfield.form.php
front/lockedfield.php
install/empty_data.php
install/migrations/update_10.0.3_to_10.0.4/inventory.php
src/Inventory/Inventory.php
src/Lockedfield.php
src/Profile.php

Use ```UPDATE``` for ```create``` and ```purge``` global lock
Use ```CREATE``` for ```read``` and ```create``` standard lock

fix(inventory): fix front right and add new right for global lock

---

src/Agent.php

* Fix duplicated endpoint (`$endpoint` is set twice: in `$option['base_url']` and as a parameter when calling `->request`. As seen together while debugging with @orthagh and @stonebuzz, this does not break anything as Guzzle is able to detect the "malpractice" and fix it by itself)
* Fix var names (address have two d in english)
* Remove unused variable `$cs = true;`

Fix agent endpoint

---

src/Profile.php

Add dedicated table for inventory right

feat(right): add dedicated table for inventory right

---

src/Reservation.php

| Fixed tickets | #12737
See explaination here: https://github.com/glpi-project/glpi/blob/537fa6db37be04170b546ee54d97bd6dbea6c1e1/src/Planning.php#L2408-L2433

Fix timezone offset on reservation calendar

---

js/fileupload.js

| Fixed tickets | #12961
During rich text images handling on server side, when base64 source of an image is huge and `pcre.backtrack_limit` PHP directive has a small value, images are not correctly replaced in rich text and produces following kind of data:
To prevent this, I propose to remove, in the hidden textarea related to rich text editor, the src attribute of every images that were handled by upload process.
Validated by uploading a 650kb image after applying following patch:
```diff
diff --git a/src/Toolbox.php b/src/Toolbox.php
index bf1c7b4d76..15fe761560 100644
--- a/src/Toolbox.php
+++ b/src/Toolbox.php
@@ -2668,6 +2668,7 @@ class …
```

Prevent issues with big images handling in right text

---

css/legacy/includes/_styles.scss

Fix kb display from itil categorie dropdown
Before : 
After : 
| Fixed tickets | !25284

fix(kb): fix kb display from itil categorie dropdown

---

src/ObjectLock.php

| Fixed tickets | #11896 #12762

Fix "locked by" message

---

inc/config.php
src/Console/Application.php

Message was not really clear for everyone. See #11551.

Change message related to DB update

---

src/Dropdown.php
templates/dropdown_form.html.twig

Fix the display of the icon
Before : 
After : 

fix(ui): fix the display of the icon

---

src/Inventory/Asset/InventoryAsset.php

Prevent SQL error when computer_item move frm an asset to another
```sql
[2022-10-24 10:06:25] glpiphplog.WARNING:   
*** PHP User Warning (512): getFromDBByCrit expects to get one result, 
2 found in query "SELECT `id` FROM `glpi_computers_items` 
WHERE `itemtype` = 'Monitor' AND `items_id` = '23061'".
in /var/www/html/glpi/src/CommonDBTM.php at line 396
Backtrace :
/var/www/html/glpi/src/CommonDBTM.php:396          trigger_error()
...glpi/src/Inventory/Asset/InventoryAsset.php:376 CommonDBTM->getFromDBByCrit()
...w/html/glpi/src/Inventory/Asset/Monitor.php:199 Glpi\Inventory\Asset\InventoryAsset->addOrMoveItem()
...html/glpi/src/Inventory/Asset/MainAsset.php:836 Glpi\Inventory\Asset\Monitor->handle()
...html/glpi/src/Inventory/Asset/MainAsset.php:756 …
```

fix(invntory): do not check for deleted computers_items

---

js/flatpickr_buttons_plugin.js

An HTML entity in button label
After the fix

HTML entity text in UI

---

src/Inventory/Inventory.php

Fix inventory properties override

---

src/DatabaseInstance.php

add missing 'version' column
| Fixed tickets | !25311

fix(databaseinstance): add missing 'version' column

---

templates/components/itilobject/actors/field.html.twig

| Fixed tickets | https://twitter.com/Loiseau2nuit/status/1575866276852793345
Follow #11794
Finally, i found a way to prevent popover to be hidden when mouse is over its content

fix hover/hide delay on actor popover

---

src/Search.php

Added Change type, and simplified tests

---

src/Dashboard/Filter.php
src/Dashboard/Grid.php
src/Dashboard/Provider.php

Add filters that were present in the `mreporting` plugin:
- Ticket types
- Statuses of items
| Fixed tickets | !24661

feat(dashboard): add filters

---

src/Lock.php
src/Lockedfield.php
tests/functionnal/MassiveAction.php
tests/web/APIRest.php

Add massive action to unlock locked field (global are not handled gere)
| Fixed tickets | !25387

feat(lockedfield): add massive action to unlock locked field

---

package-lock.json
package.json
webpack.config.js

Fix webpack build

---

src/Stat.php

Retrieved some issues fixed in #12591 and fixed IDE warnings.

Fix minor stat issues

---

js/common.js

Fix escapeMarkup JS for number input

---

src/System/Requirement/InstallationNotOverriden.php
src/System/RequirementsManager.php
tests/units/Glpi/System/Requirement/InstallationNotOverriden.php
tools/build_glpi.sh

add new Requirement checking overridden installations

---

src/Computer.php
src/Console/Database/FixHtmlEncodingCommand.php
src/Lock.php
templates/generic_show_form.html.twig

Fix typos / harmonize translations

---

.github/workflows/audit-dependencies.yml

Will check for security issues in dependencies every monday, and everytime a depencency is updated.
Have to be adapted to be executed also against 9.5 branch.

Audit dependencies

---

src/ITILSolution.php
src/PendingReasonCron.php

Prevent SQL error when user try to add solution massivley
| Fixed tickets | !25441

fix(itilsolution): sanitize content from twig renderer

---

src/Session.php

check entity of user with ancestors

---

inc/session.class.php

check entity of user is valid with ancestors

---

CHANGELOG.md
inc/define.php
install/migrations/update_10.0.4_to_10.0.5.php
install/mysql/glpi-10.0.5-empty.sql
tests/functionnal/Update.php

Ensure that nightly build will be clearly identified as a `-dev` version.

Switch to 10.0.5-dev

---

front/ruledictionnaryoperatingsystemedition.form.php
front/ruledictionnaryoperatingsystemedition.php
src/Rule.php
src/RuleCollection.php
src/RuleDictionnaryOperatingSystemEdition.php
src/RuleDictionnaryOperatingSystemEditionCollection.php

add missing OS Edition rule dictionnary

feat(dictionnary): add OS Edition rule dictionnary

---

css/includes/components/itilobject/_timeline.scss
templates/components/itilobject/timeline/timeline.html.twig

| Fixed tickets | #13179
Before:
After:

Fix validation answer colors

---

src/Html.php
templates/components/form/fields_macros.html.twig

Avoid some harmless browser console warnings

---

templates/components/photoswipe.html.twig

Fix photoswipe preview opening with multiple images

---

src/Transfer.php

Fix entity transfer for rules

---

inc/update.class.php

Fix update from GLPI >= 9.5.7

---

CHANGELOG.md
inc/define.php
install/migrations/update_10.0.5_to_10.0.6.php
install/mysql/glpi-10.0.6-empty.sql
tests/functionnal/Update.php

Switch to 10.0.6-dev

---

src/Search/Output/HTMLSearchOutput.php
src/Search/Output/MapSearchOutput.php
templates/components/search/display_data.html.twig
templates/components/search/map.html.twig

Use twig for map search view

---

src/Console/Database/UpdateCommand.php

| Fixed tickets | !25480
Adapt displayed DB version in update command to not display version hash when it is not required.
From a stable version to a stable version:
From a stable version to a dev version:
From a dev version to a stable version:
From a stable version that does not match expected hash:

Hide stable DB version sha on update command

---

src/Inventory/Asset/InventoryAsset.php

Fix global peripheral management

---

src/Update.php
tests/functionnal/Update.php

This should permit to not have to add new versions to update tests everytime GLPI version changed.

Execute Update tests on virtual file system

---

front/softwareversion.form.php
src/SoftwareVersion.php

Fix redirect after deleting software versions

---

src/Inventory/Asset/VirtualMachine.php

Set autoupdatesystems_id on VMs from main item

---

CHANGELOG.md
front/change_problem.form.php
front/change_ticket.form.php
front/commonitilobject_commonitilobject.form.php
front/problem_ticket.form.php
src/Application/View/Extension/ItemtypeExtension.php
src/Change_Problem.php
src/Change_Ticket.php
src/CommonITILObject_CommonITILObject.php
src/Problem_Ticket.php
src/ProjectTask_Ticket.php
templates/components/form/fields_macros.html.twig
templates/components/form/link_existing_or_new.html.twig

Port of #12903 for main branch. A new feature for this port is the ability to specify link types.

Standardize ITIL Link Tabs

---

ajax/commonitilsatisfaction.php
src/CommonITILSatisfaction.php

Increase inquest rate from ```5``` to ```10``` 

feat(inquest): increase rate

---

templates/components/search/controls.html.twig

Passing Sort and Order options to Export Buttons

---

src/Planning.php

Fix handling of URL params in external calendars

---

src/Application/View/Extension/PluginExtension.php
src/CommonDBTM.php
src/Html.php
src/Search/Input/QueryBuilder.php
src/Search/Output/AbstractSearchOutput.php
src/Search/Output/ExportSearchOutput.php
src/Search/Output/HTMLSearchOutput.php
src/Search/Output/MapSearchOutput.php
templates/components/search/query_builder/criteria.html.twig
templates/components/search/query_builder/criteria_group.html.twig
templates/components/search/query_builder/main.html.twig
templates/components/search/query_builder/metacriteria.html.twig
templates/components/search/query_builder/search_option.html.twig
templates/components/search/query_builder/search_option_value.html.twig

Move Search Query Builder UI to Twig

---

js/common.js
src/SNMPCredential.php
templates/components/form/fields_macros.html.twig
templates/components/form/item_device.html.twig

| Fixed tickets | Ref https://forum.glpi-project.org/viewtopic.php?id=285362
Password fields from the form field twig template were not having their value set. This broke the display of the simcard PIN/PUK fields for example.

Fix missing value in password fields

---

inc/define.php
index.php
src/System/Requirement/PhpVersion.php
tests/units/Glpi/System/Requirement/PhpVersion.php

Will be easier to understand (I guess).

Make PHP_MAX_VERSION inclusive

---

src/CommonDevice.php
src/DeviceMemory.php
src/Inventory/Asset/Memory.php
tests/functionnal/Glpi/Inventory/Assets/Memory.php

The import had been ignoring memory models.
| Bug fix?      | probably

feat(inventory): memory model import

---

composer.lock

Update inventory_format lib

---

css/standalone/dashboard.scss
src/Dashboard/Grid.php

When edit mode is toggled, change dashboard dropdown was not hidden.
Also, save button was broken

fix toggle edit mode

---

css/standalone/dashboard.scss
src/Dashboard/Grid.php

improve dashboard toggles state

---

install/migrations/update_9.2.0_to_9.2.1.php
src/Config.php
src/DBmysql.php
src/DBmysqlIterator.php
src/FQDNLabel.php
src/Inventory/Asset/Antivirus.php
src/Migration.php
src/QueryUnion.php
src/Toolbox/Sanitizer.php
tests/functionnal/Certificate.php
tests/functionnal/Glpi/Inventory/Assets/NetworkEquipment.php
tests/functionnal/ProjectTask.php
tests/units/DB.php
tests/units/DBmysqlIterator.php

Fix deletion of empty OS items in 9.2.1 migration

---

.gitignore
marketplace/remove.txt
plugins/remove.txt

Drop missed remove.txt files

---

composer.lock

feat(core): Update inventory format lib

---

install/migrations/update_9.4.0_to_9.4.1.php

Make migration to 9.4.1 replayable

---

src/RichText/RichText.php
tests/units/Glpi/RichText/RichText.php

Fix detection of rich text in emails

---

src/FQDNLabel.php

Replace usage of true/punycode by idn_to_ascii

---

css/includes/components/_richtext.scss

make borders of tinymce field similaire to form-control

---

src/MailCollector.php
tests/emails-tests/36-microsoft-specific-code.eml
tests/imap/MailCollector.php

| Fixed tickets | #13399
Was partially made here before GLPI 10.0:
https://github.com/glpi-project/glpi/blob/cb6d3eb053988066ad435dbf738fc8042ceffff2/inc/html.class.php#L69-L70

Clean Outlook conditionnal code and namespaced tags

---

front/logout.php
src/Auth.php

| Fixed tickets | #13381
Safe alternative to #13388 for GLPI 10.0.

Fix compatibility with phpCAS 1.6.0

---

.composer-require-checker.config.json
CHANGELOG.md
composer.json
composer.lock
front/logout.php
inc/autoload.function.php
phpstan.neon
src/Auth.php
src/Config.php
src/Toolbox.php

`phpCAS::client()` parameters changed in 1.6.0 version and this change has not been made to maintain backward compatibility.
`phpCAS` is using a `Apache 2.0` licence.

Bundle phpCAS library in GLPI

---

install/empty_data.php

Constant exists, so its value should be used here.

Use USER_SYSTEM constant value in fresh install

---

front/profile.form.php

| Bug fix?      | yes and no
| New feature?  | yes and no

feat: add Event log for Profile

---

src/Session.php

Fix `Session::isInventory()` check

---

install/empty_data.php
install/migrations/update_10.0.5_to_10.0.6/transfer.php
install/mysql/glpi-empty.sql
src/CommonDBTM.php
src/Transfer.php
tests/functionnal/Glpi/Inventory/Assets/Computer.php

Add transfer option to enable / disable locked fiel during process

feat(transfer): add transfer option to enable / disable locked fiel during process

---

src/Contract.php

Fix 7 day contract notice central card

---

templates/pages/setup/dropdowns_list.html.twig

Make dropdown fitler text translatable

---

src/PlanningRecall.php

Closed ticket, change or problem tasks were recalled
| Fixed tickets | !25640

fix(planning recall): do not recall closed ticket tasks

---

inc/define.php
src/Dashboard/Dashboard.php
src/Html.php

Fix: 
- `PHP Warning (2): Undefined array key "users_id" in src/Dashboard/Dashboard.php at line 563`

fix undefined array when using a custom dashboard

---

src/NetworkPort.php

Fix missing Connected To column

---

src/NetworkPort.php

SO is based on a virtual field

---

src/Agent/Communication/AbstractRequest.php
src/RuleMatchedLog.php

add missing ```Module``` column value

fix(RuleMatchLog): add missing column value

---

src/User.php

Fix warning during SSO authentication

---

src/Inventory/Asset/Software.php

Fix history on delete (from inventory)
Before : 
After : 

fix(software): fix history on delete (from inventory)

---

src/Reservation.php

| Fixed tickets | #12905
Reservation input errors message were displayed in the middle of the page then, almost instantly, user was redirected to the planning, without being able to read the message.

Fix reservation input errors display

---

src/CommonITILObject.php

Fix undefined array key in actors handling

---

src/ComputerVirtualMachine.php

List VMs from trashbin also

---

js/modules/Kanban/Kanban.js
src/CommonITILObject.php

https://glpi.userecho.com/communities/1/topics/2125-global-kanban-filter-by-categories

Add category filter for ITIL Kanban

---

src/NotificationEventMailing.php

| Fixed tickets | #13516
Skip inline images that no longer exist.
Handle any exceptions thrown for individual emails gracefully.

Handle email send PHP exceptions

---

src/Toolbox.php
tests/functionnal/Toolbox.php

Fix undefined array key in mio size formatting

---

ajax/visibility.php
install/migrations/update_10.0.x_to_10.1.0/knowbaseitem.php
install/mysql/glpi-empty.sql
src/CommonDBVisible.php

Addition of the entity on the articles of the KB, to have a partitioning like with the other objects of GLPI.
| Fixed tickets | !25522 + !24105

feat(knowbase): add entity on articles

---

src/Html.php

Fix select2 focus within dropdown menu

---

templates/pages/management/softwarelicense.html.twig

| Fixed tickets | #13597
Use dropdown so that the Unlimited value can be used.

Use dropdown for license count field

---

src/Api/API.php

Handle uid for meta criteria

---

src/Entity.php

Apply changes suggested in #13437.

Helpdesk config: preset contract can't be deleted or template

---

install/migrations/update_10.0.5_to_10.0.6/inventory.php

fix(update): PHP Warning: Undefined array key stale_agents_action

---

src/Plugin.php
tests/functionnal/Plugin.php

| Bug fix?      | sometimes
Until now, the `oldname` information of a plugin was only used to update information of a plugin entry when the old plugin was not anymore present on filesystem. It basically means that if filesystem contains the old plugin (named `myoldplugin`) and the new plugin (named `mynewplugin`), administrator was able to install/activate both.
With proposed changes, as long as there is a replacement plugin, the old one will have the status `REPLACED` and will not be installable/activable. From this state:
- if old plugin is removed from filesystem, it will be shown as `TOBECLEANED`;
- if replacement plugin is removed from …

Simplier handling of plugin replacement

---

src/Phone.php
src/Printer.php

Better handling of numeric attributes of devices

---

src/Plugin.php

Help keep the plugin list page from breaking when a plugin is broken.
For example, I had just added the barcode plugin to the plugins folder and went to the plugin page (not marketplace) to install it, but the plugin search results weren't loading because the plugin had a `require` statement for a composer autoload file (I hadn't installed composer dependencies yet) in its `init` function which is called in this page even though the plugin isn't activated (it was in TOUPDATE status because of an old version).
With this PR, the plugin list will load when errors are generated in a plugin's init function. If the plugin was …

Protect plugin list from broken plugins

---

js/modules/Kanban/Kanban.js

Fix moving Kanban cards into filtered out column

---

js/modules/Kanban/Kanban.js
src/Project.php

| Fixed tickets | Related: #13651
Relies on #13653

Project Kanban deleted filter

---

ajax/kanban.php
js/modules/Kanban/Kanban.js

| Fixed tickets | Related: #13651
Relies on #13653

Add missing Kanban item restore action

---

src/CommonDBTM.php
src/CommonITILObject.php
src/Project.php
tests/functionnal/Software.php

Add a new search criterion to filter tickets, changes, problems or assets by project.
| Fixed tickets | !26074

Search ITIL items and assets by project

---

src/Inventory/Asset/MainAsset.php
tests/functionnal/RuleImportEntity.php

| Fixed tickets | #13667
Replaces #13642

Fix location set from entity rules

---

src/Inventory/Asset/OperatingSystem.php

Fix Item_OperatingSystem deletion during inventory

---

src/Config.php

Seen from this 
https://github.com/glpi-project/glpi/pull/13602#discussion_r1061276234
Anyone should be able to define its preferable button layout, and it should also be configurable globally.

make option configurable globally

---

front/apiclient.form.php

For security reason is important to at least logs APIClient creation/update and purge.

fix(apiclient): logs event

---

src/Migration.php

https://github.com/glpi-project/glpi/actions/runs/3840531546/jobs/6539701872#step:9:98

Fix ambiguous glpi_displaypreferences.id column in SO migration

---

src/Project.php

SO added in #13680 is conflicting with SO added in #11138 in main branch.

Prevent SO 401 conflicts

---

src/Inventory/Asset/Software.php
tests/functionnal/Glpi/Inventory/Assets/Software.php
tests/functionnal/Glpi/Inventory/Inventory.php

Fix soft categories double import
Store ID not verbatim value
Fix tests
Try rework sys categories
Add test
Alternative to #13639

Prevent double manufacturer import

---

front/change_group.form.php
front/change_supplier.form.php
front/change_user.form.php
front/dropdown.php
front/group_problem.form.php
front/group_ticket.form.php
front/item_problem.form.php
front/item_project.form.php
front/item_ticket.form.php
front/itiltemplatefield.form.php
front/knowbaseitem_item.form.php
front/planningrecall.form.php
front/problem_supplier.form.php
front/problem_ticket.form.php
front/problem_user.form.php
front/projecttask_ticket.form.php
front/supplier_ticket.form.php
front/ticket_contract.form.php
front/ticket_ticket.form.php
front/ticket_user.form.php

fix(cs): removing superfluous space

---

install/migrations/update_10.0.5_to_10.0.6/simcard.php
install/mysql/glpi-empty.sql
templates/components/form/item_device.html.twig
tests/functionnal/Glpi/Inventory/Inventory.php

Add ```comment``` field for ```Item_DeviceSimcard```

feat(simcard): add 'comments' field

---

src/Html.php

The links to navigate from page to page (on the rules for example) are much too small to be used easily.
This PR improves that a bit.
Before
After

fix(css): more usable buttons for ajax pagination

---

src/NetworkEquipment.php
src/Printer.php

Add missing SNMP search option
| Fixed tickets | !26195

feat(network device): add missing SNMP search option

---

src/CommonDBTM.php
tests/functionnal/Location.php

| Fixed tickets | #13313
There is a quite huge change in this PR. Previousely, updateInDb was doing an update query for each updated field, separately. Now, all fields are updated at once.

Fix locations unicity

---

templates/layout/parts/head.html.twig

prevent search engine robots indexing glpi instances

---

README.md

We could do even better, but it's already better than the current links.

fix(readme): documentations links

---

install/empty_data.php
install/migrations/update_10.0.5_to_10.0.6/queuednotification.php

Fix default displaypreferences for QueuedNotification

---

templates/components/form/fields_macros.html.twig

Fix new financial tab

---

templates/components/form/fields_macros.html.twig
templates/components/itilobject/timeline/simple_form.html.twig

fix maxlength form field option

---

inc/define.php
install/migrations/update_10.0.5_to_10.0.6/appliance.php
install/mysql/glpi-empty.sql
src/Appliance.php

Add ```Appliance``` to ```Parc > Global Search```
| Fixed tickets | !25986

feat(AllAsset): add Appliance

---

src/Html.php
src/Lock.php

Extra raw HTML will be replaced when page will be converted to twig.

Drop deprecated methods usage

---

tests/emails-tests/39-link-in-content.eml
tests/imap/MailCollector.php

| Fixed tickets | #13625
Just adding a test for referenced ticket

Test link in message body

---

composer.json
composer.lock
src/System/Status/StatusChecker.php

Can be usefull to detect deprecations when dependencies are updated.

Detect usage of deprecated methods using PHPStan

---

src/DatabaseInstance.php

Add some infos
Before : 
After : 

feat(databaseinstance): add info from computer

---

ajax/actorinformation.php
src/CommonITILObject.php
templates/components/itilobject/actors/field.html.twig

| Fixed tickets | #13429
Add counter for following actors types:
- requester user,
- assigned user,
- assigned group,
- assigned supplier.

Add ticket count for all actors

---

package-lock.json

Upgrade luxon

---

src/Dashboard/Provider.php
src/DbUtils.php
src/Search.php
src/User.php

Fix myself values handling on PHP 7.4

---

src/Reservation.php
src/ReservationItem.php

Add reservation READ right on simplified interface

---

src/Features/TreeBrowse.php
src/Html.php
src/Knowbase.php

Fix knowbase browse view in some locales

---

.github/actions/init_initialize-9.5-db.sh
install/mysql/glpi-9.5.12-empty.sql
tests/glpi-9.5-data.sql

Handle 9.5.12 schema check

---

src/RuleCriteria.php
tests/functionnal/RuleCriteria.php

As proposed https://github.com/glpi-project/glpi/issues/13626#issuecomment-1352868549

Trigger error when rule criteria regexp is invalid

---

front/crontask.php

fix(crontask): unable to click execute button

---

install/empty_data.php
src/Marketplace/NotificationTargetController.php

feat(marketplace): add GLPI URL for checkpluginsupdate notif

---

js/glpi_dialog.js

Fix modal backdrop blocking

---

templates/generic_show_form.html.twig

Use itemtype name rather than a generic label

---

src/Document.php

Fix some typos.
| Fixed tickets | #12785

Do not expose FS path on front.

---

src/RuleCollection.php

Reflect functionality of skip rules in test

---

src/NotificationTargetCommonITILObject.php

Fix anonymous authors in Ticket notifications

---

js/modules/SearchTokenizer/SearchInput.js

Escape search input token term

---

src/Console/Plugin/UninstallCommand.php

Needed this for a script, I guess we could add it to our lists of commands.

Console: Uninstall plugin command

---

src/Log.php

| Fixed tickets | !26407 #7480

fix(infocom): history for dropdown values

---

src/Plugin.php

It's time to logs all important event on plugins! (install/uninstall/activate/disable)

feat(plugins): add event logs

---

src/Search.php
src/Socket.php
src/Software.php
src/State.php
src/System/Requirement/InstallationNotOverriden.php
src/Ticket.php
src/Ticket_Contract.php
src/Toolbox.php
src/Transfer.php
src/User.php

| Bug fix?      | probably
First batch of fixes. It represents about 30% of detected issues.
Each commit could be reviewed separately, and we can move some of them in dedicated PR if it requires some rework.

Fix issues detected by phpstan at level 1

---

src/Plugin.php

feat(plugins): event log, add user

---

src/KnowbaseItem.php

The search result only showed articles without a category.

fix(kb): missing article in search

---

src/AutoUpdateSystem.php
src/RuleImportEntity.php

Add missing source ```GLPI Native Inventory``` from ```RuleEntity```
| Fixed tickets | !26418

fix(RuleEntity) : add missing source 'GLPI Native Inventory'

---

src/APIClient.php

Hide useless header; fixes #13874

---

src/APIClient.php
src/Application/View/Extension/DataHelpersExtension.php
templates/pages/setup/apiclient.html.twig

Switch form view to twig

---

front/computervirtualmachine.form.php

Fix ```ComputervirtualMachine``` ```restore``` action.
| Fixed tickets | !25864

fix(VirtualMachine): fix restore action

---

src/Contract.php
src/Entity.php

Fix default contract selector criteria

---

front/ldap.import.php
src/AuthLDAP.php

fix(ldap): stripslashes for basedn and filter

---

src/Inventory/Asset/MainAsset.php
tests/functionnal/Glpi/Inventory/Assets/Printer.php

Try to fix ```Printer``` network port that are continuously deleted / created
| Fixed tickets | https://github.com/glpi-project/glpi-inventory-plugin/issues/295

[WIP] fix(inventory): fix printer network port continuously deleted / created

---

src/Dashboard/Widget.php

Oversight of #13775, sometimes widgets are displayed without a dashboard.
| Fixed tickets | #13882

Printers: fix "Page counters" graph

---

install/migrations/update_10.0.6_to_10.0.7.php

Add 10.0.7 migration file

---

front/helpdesk.public.php

Incorrect display of knowledge base on self-service home page

---

src/Change.php

fix(change): incorrect reopenable status

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

Use MariaDB 10.10 in test suite

---

src/RuleLocationCollection.php

- Order Location Rules by name rather than ID
- Add this rule collection to the breadcrumb trail

Update RuleLocationCollection.php - sort order and breadcrumb trail

---

src/Inventory/Asset/InventoryAsset.php

Fix SQL error
```SQL
PHP User Error (256): Out of range value for column 'manufacturers_id' at row 1 in /var/www/html/glpi/src/DBmysql.php at line 1969
```
| Fixed tickets | #13994

feat(software): prevent import 0 value as dropdown (globally)

---

inc/define.php
install/migrations/update_10.0.6_to_10.0.7/unmanageds.php
install/mysql/glpi-empty.sql
src/Unmanaged.php

Remove direct relation to domains on unmanageds

---

src/User.php
tests/functionnal/MassiveAction.php

New massive action on users:
| Fixed tickets | !24847

Massive actions: delete users' emails

---

src/Dashboard/Provider.php

Fix criterion generated by ticket type dashboard filter

---

src/Dropdown.php

Add hidden inputs for readonly entries; fixes #12156

---

src/CommonDBTM.php
tests/functionnal/CommonDBTM.php

Fix truncation of multibyte strings

---

src/Agent.php
tests/functionnal/Agent.php

Force core agent type creation when missing

---

package-lock.json
package.json

Follow #14040, 2 weeks later, around 150 icons added.
No rename nor suppression this time

Upgrade tabler-icons to v2.4

---

src/CommonItilObject_Item.php

fix(computer): impossible to list tickets

---

templates/layout/parts/page_header.html.twig

fix(menu): improper collapse button alignment

---

src/Inventory/Asset/Software.php
tests/functionnal/Glpi/Inventory/Assets/Software.php

Fix unbreakable space issues in soft name during inventory

---

front/tracking.injector.php

fix(helpdesk): incorrect redirect on mandatory fields error

---

src/Inventory/Asset/NetworkCard.php
tests/functionnal/Glpi/Inventory/Assets/Computer.php

Ensure only one networkcard is created per mac; closes #14085

---

templates/components/form/fields_macros.html.twig

fix(html): incorrect multiple option for file input

---

templates/components/logs.html.twig

fix(html): logs-filter-select-multiple

---

front/report.dynamic.php

Fix rights check when exporting from All Assets search

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

MariaDB 10.11 has been released last week.

Run tests on MariaDB 10.11

---

templates/components/form/networkname.html.twig

fix(template): use get_plural_number TwigFunction

---

front/networkport.form.php
src/CommonDBTM.php

Fix network port redirection when not authenticated

---

src/AuthLDAP.php

Need https://github.com/glpi-project/glpi/pull/14145 to work :)

feat(ldap): add OpenLDAP preconfiguration example

---

src/Link.php

Fix external links encoding

---

tests/run_tests.sh

feat(tests): run suites lint_[php/js/scss/twig]

---

composer.lock
tests/functionnal/Glpi/Inventory/Assets/Unmanaged.php

feat(inventory): bump inventory format

---

src/Inventory/Asset/NetworkEquipment.php
tests/functionnal/Glpi/Inventory/Assets/Computer.php
tests/functionnal/Glpi/Inventory/Assets/NetworkEquipment.php
tests/functionnal/Glpi/Inventory/Assets/Printer.php

Manage assettag from network device
https://github.com/glpi-project/inventory_format/pull/88

feat(inventory): manage assettag from network device

---

src/Inventory/Asset/NetworkEquipment.php

Issue seen on provided file for another issue (https://github.com/glpi-project/glpi-inventory-plugin/issues/318)

Switch name may be missing

---

front/login.php

Related forum post:
https://forum.glpi-project.org/viewtopic.php?id=286393

Send 401 code on failed web login

---

src/CronTaskLog.php
src/Rule.php
src/RuleAction.php
src/RuleAsset.php
src/RuleCriteria.php
templates/layout/parts/user_header.html.twig

fix(html): add some icons

---

front/event.php

fix(logs): event logs breadcrumbs

---

css/includes/_base.scss
front/central.php
src/Html.php

don't limit iframe when embedding dashboards

---

src/Inventory/Asset/Software.php
tests/functionnal/Glpi/Inventory/Assets/Software.php

Handle duplicated softwareversion in inventory file

---

src/AuthLDAP.php

Fix ```Search failed: Bad search filter(-7)``` error.

fix(openldap): default filter condition

---

tests/LDAP/AuthLdap.php

fix(openldap): add unit test preconfig

---

src/Html.php

Default target to "_top", fixes #12240

---

src/ITILFollowup.php
tests/functionnal/ITILSolution.php

Approving a solution didn't close the ticket
Validation logs before :
| Fixed tickets | !27027

fix(ticket): approving solution

---

CHANGELOG.md
composer.json
composer.lock
src/GLPI.php
src/Toolbox.php
tests/GLPITestCase.php
tests/src/Log/TestHandler.php
tests/units/Glpi/Application/ErrorHandler.php

Alternative to #14178 . Permits make GLPI methods signatures fully compliant with PSR-3.

Upgrade `monolog/monolog` to 3.3

---

src/Inventory/Inventory.php

Fix autoloader on non yet loaded types; closes #14273

---

src/Entity.php
tests/functionnal/Entity.php

Prevent removal of entities with children

---

src/ManualLink.php

Fix manual links encoding

---

src/Features/Inventoriable.php

Use JSON formet per default; closes #13891

---

css/includes/_base.scss
src/Change.php
src/CommonITILTask.php
src/Problem.php
src/Ticket.php

0 was not handled; fixes #13995

---

src/SoftwareLicense.php

add missing 'Number of installations' search option.
| Fixed tickets | !27169

feat(SoftwareLicense): add missing 'Number of installations' SO

---

composer.json
composer.lock
src/Auth.php
src/Toolbox/Sanitizer.php
tests/FrontBaseClass.php
tests/bootstrap.php
tests/web/Computer.php
tests/web/Ticket.php

Front tests

---

src/Features/Inventoriable.php

Fix most recent agent reconciliation during computer inventory

---

package-lock.json

Update `webpack` to get security fixes

---

front/stat.graph.php

fix stat graph date filters

---

js/common.js

Fix unclosed pre tags in copied system information

---

src/Search.php

Allow showing id for linked tickets in search

---

src/CommonITILObject.php

Do not load the full item just to be able to use item-level permission checks. Use hacks from Search class for visibility and ignore item-level update rights (will be re-checked on the server when an update is attempted).

Less expensive visibility checks for ITIL Kanban

---

inc/define.php
install/migrations/update_10.0.6_to_10.0.7/domains_items.php
install/mysql/glpi-empty.sql
src/Domain_Item.php
src/Inventory/Asset/MainAsset.php
src/Lock.php
tests/functionnal/Glpi/Inventory/Assets/Computer.php

Handle domains on inventory

---

src/CommonITILObject.php

Fix checks against ticket predefined contents

---

front/report.infocom.php

Fix rights checks on Infocom report

---

src/NotificationEventAbstract.php

Fix marketplace notifications

---

src/Central.php

Fix undefined array key; closes #14375

---

front/updatepassword.php

Fix ability to update own password when it expired

---

front/snmpcredential.form.php
src/GLPIKey.php
tests/FrontBaseClass.php
tests/functionnal/GLPIKey.php
tests/web/SNMPCredential.php

Fix SNMP credentials encoding issues

---

src/CleanSoftwareCron.php
tests/functionnal/CleanSoftwareCron.php

Fix max param for CleanSoftware

---

tests/emails-tests/40.1-empty-content-multipart.eml
tests/emails-tests/40.2-empty-content-html.eml
tests/emails-tests/40.3-empty-content-plaintext.eml
tests/imap/MailCollector.php

| Fixed tickets | see #14011
Just a test to ensure that collector is handling correctly empty emails.

Ensure collector is handling empty emails

---

src/System/RequirementsManager.php

Add `Phar` extension in marketplace optional requirements

---

src/System/Requirement/PhpSupportedVersion.php
src/System/RequirementsManager.php
tests/units/Glpi/System/Requirement/PhpSupportedVersion.php

On UI install/update process:
On `system:check_requirements` console command:

Suggest to use an officially supported PHP version

---

src/NotificationTargetCommonITILObject.php

Add missing TAG
```##ticket.solution.author##```
```##lang.ticket.solution.author##```
| Fixed tickets | !27372

feat(Notification): add missing solution author tag

---

src/CommonDBTM.php
tests/functional/User.php

| BC breaks?    | hope not...
| Fixed tickets | #14053

Try to reproduce on tests

---

src/ProjectTask.php

Keep existing conditions (users/groups limits so far); clsoes #13898

---

tests/functional/User.php

Prevent test suite to fail on skipped test

---

src/Dropdown.php

Fix PHP 8.1 warning on floating numbers dropdown

---

ajax/agent.php

fix: check agent rights to trigger status/inventory

---

templates/components/itilobject/actors/field.html.twig
templates/components/itilobject/actors/main.html.twig
templates/components/itilobject/selfservice.html.twig

Fix "assign to me" button availability

---

inc/relation.constant.php
install/migrations/update_10.0.6_to_10.0.7/wrong_fkey.php
install/mysql/glpi-empty.sql
src/Inventory/Asset/Camera.php
src/Item_DeviceCamera_ImageFormat.php
src/Item_DeviceCamera_ImageResolution.php

Fix bad named foreign key

---

ajax/actorinformation.php

- improve security (intval)
- add canView check to avoid reading unwanted data
- "simplify" code (I don't know if we can do more :D)

fix: actorinformation checks

---

src/AuthLDAP.php
tests/LDAP/AuthLdap.php

Fix LDAP directory creation

---

public/index.php

| Fixed tickets | see https://forum.glpi-project.org/viewtopic.php?id=286740

Fix shared hosting support in PHP router (using `.htaccess`)

---

src/CommonGLPI.php

Error message on database opening :
> Uncaught Exception Error: Class name must be a valid object or a string in /var/www/html/glpi/src/CommonGLPI.php at line 986
| Fixed tickets | !27572

fix(database): blank page

---

src/Api/API.php
src/DBmysqlIterator.php
src/Search/Provider/SQLProvider.php

Automatically decode data from DB in API and Search results

---

templates/components/form/inventory_info.html.twig

Fix `Last contact` label

---

install/migrations/update_10.0.7_to_10.0.8/rule_tickets.php
resources/Rules/RuleTicket.xml

In the rule "Ticket location from item", the second criterion was unavailable.
| Fixed tickets | !27685

fix(rule ticket): criterion Unavailable

---

src/NotificationTargetTicket.php

fix(notification): town not city

---

src/Inventory/Asset/InventoryAsset.php
src/Inventory/Asset/Software.php
tests/functional/Glpi/Inventory/Assets/Software.php

Cleanup special characters in software and manufacturers names

---

src/Socket.php

Fix php warnings for sockets without cables

---

src/Http/ProxyRouter.php
tests/units/Glpi/Http/ProxyRouter.php

Handle duplicate `/` in PHP router

---

js/notifications_ajax.js
src/NotificationAjax.php
tests/functional/NotificationAjax.php

Fix URLs in ajax notifications

---

src/Inventory/Asset/InventoryAsset.php
src/Inventory/Asset/Software.php
tests/functional/Glpi/Inventory/Assets/Software.php

Fix inventory manufacturer case; closes #14602

---

.gitignore

fix: ignore inc/downstream file on git repository

---

src/Inventory/Inventory.php

pretty print json file (very useful for reading)
Before :
```json
{"action":"inventory","content":{"accesslog":{"logdate":"2023-02-20 12:19:27"},"antivirus":[{"base_version":"26780 (20230220)","enabled":true,"expiration":"2023-08-17","name":"ESET Endpoint Security","uptodate":true,"version":"10.0.2034.0"},{"base_version":"1.369.975.0","company":"Microsoft Corporation","enabled":false,"guid":"{D68DDC3A-831F-4fae-9E44-DA132C1ACF46}","name":"Windows Defender","uptodate":true}],"batteries":[{"capacity":41990,"chemistry":"LION","date":"2017-08-02","manufacturer":"Samsung","name":"DELL CYMGM78","serial":"59555","voltage":11400}],"bios":{"bdate":"2021-06-11","bmanufacturer":"Dell Inc.","bversion":"1.5.0","mmanufacturer":"Dell Inc.","mmodel":"097N0Y","msn":"\/F8N5Y32\/CN129667970039\/","skunumber" …
```

feat(core): pretty print json file

---

src/Inventory/Asset/Software.php
tests/functional/Glpi/Inventory/Assets/Software.php

Fix same software different cases; closes #14658

---

src/Entity.php
tests/functional/Entity.php

Add explicit error when renaming entity to existing name

---

src/Inventory/Asset/MainAsset.php

Do not include domain relation when checking existance

---

templates/components/search/table.html.twig
tests/DbTestCase.php
tests/functional/Project.php

Small regression introduced in #14027
Before: 
After:
| Fixed tickets | !27894

Fix project states colors

---

src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php

| Fixed tickets | see !27886
When there is a difference in DB schema, people may use the diff generated by `db:check` command to generate an `ALTER TABLE` query. When diff is related to a foreign key field, not having the `unsigned` option in diff string may result in errors.
For instance, in case a value is greater that the limit of a signed integer, an out of range error will be trigerred:

Display expected sign option in DB diff

---

templates/pages/admin/inventory/agent.html.twig

The purpose of this PR is to avoid any confusion between tasks supported by GLPI Agent as seen on the agent's main tab and the content of the "Agent modules" tab.
Before:
After:

Fix meaning of supported tasks as it's reported by GLPI agent

---

src/Console/Migration/Utf8mb4Command.php
src/GLPINetwork.php
src/RuleDictionnarySoftwareCollection.php

Translated strings should not contains HTML tags.

Remove HTML tags from translated strings

---

templates/components/form/inventory_info.html.twig

Inventory agent is not supposed to return HTML.

Escape inventory agent answer

---

src/Api/HL/Controller/AbstractController.php
src/Api/HL/Controller/AssetController.php
src/Api/HL/Controller/ComponentController.php
src/Api/HL/Controller/ITILController.php
src/Api/HL/Controller/ManagementController.php
src/Api/HL/Controller/ProjectController.php
src/Api/HL/Doc/Schema.php
src/Api/HL/OpenAPIGenerator.php
src/Api/HL/Router.php
src/Api/HL/Search.php
tests/functional/Glpi/Api/HL/Controller/AssetController.php
tests/functional/Glpi/Api/HL/Controller/ComponentController.php
tests/functional/Glpi/Api/HL/Controller/ITILController.php
tests/functional/Glpi/Api/HL/Controller/ProjectController.php

Relies on #14437.
Adds at least basic support for:
- Consumables
- Software
- Software Versions
- Racks
- Enclosures
- PDUs
- Passive DC Equipment
- Cables
- Sockets
- Recurring Tickets
- Recurring Changes
- External Events
- Projects
- Project Tasks
Most changes are declarative (defining schemas and routes) and not new/changed logic.

Add some new API endpoints needed for Webhook feature

---

templates/pages/setup/oauthclient.html.twig

Set auth code as default grant type

---

src/Dashboard/Filter.php
src/Dashboard/Filters/AbstractFilter.php
src/Dashboard/Filters/DatesFilter.php
src/Dashboard/Filters/DatesModFilter.php
src/Dashboard/Filters/GroupTechFilter.php
src/Dashboard/Filters/ItilCategoryFilter.php
src/Dashboard/Filters/LocationFilter.php
src/Dashboard/Filters/ManufacturerFilter.php
src/Dashboard/Filters/RequestTypeFilter.php
src/Dashboard/Filters/StateFilter.php
src/Dashboard/Filters/TicketTypeFilter.php
src/Dashboard/Filters/UserTechFilter.php
src/Dashboard/Grid.php
src/Dashboard/Provider.php

Supersedes #14526.
First commit corresponds to squashed commits of #14526, rebased on current 10.0/bugfixes branch state.
Other commits are mainly code mutualization/simplification/optimization.
I tested compatibility with `advanceddashboard` plugin (the only one I found that can be impacted) and all is working as expected. As there is no BC-break, it can be merged on 10.0 version.

added hook for dashboard filter front

---

src/DatabaseInstance.php

Adapt display of deleted databases instances

---

front/planning.php

Fix rights management on ical/webcal endpoint

---

src/DBmysqlIterator.php

Add fetch fields on iterator

---

src/Plugin.php

| Fixed tickets | - 
Following pull request #14746, the style and placement of the uninstallation button has been modified.
The button is no longer the same color and is offset.
Actual :
Expected :

Fixed style and placement of plugin uninstall button

---

apirest.md

| Fixed tickets | !28142
Code documentation does not exist anymore.

Remove links to old code documentation

---

src/Infocom.php

Hey there,
When you are using datainjection this dropdown is important but missing. So this will fix it.
| Fixed tickets | 0

Add Business criticity search option

---

src/CommonITILObject.php

Send notification for rule based followup/tasks

---

install/empty_data.php
install/migrations/update_10.0.x_to_10.1.0/ticket.php
src/Search/Provider/SQLProvider.php
src/Ticket.php
tests/functional/Search.php
tests/functional/Ticket.php

Added a "View new tickets" right, visible only for central interface profiles.
This right allows to see tickets with "Incoming" status.
Currently we rely on another right (to assign tickets) which is not necessarily very intuitive.

Add "View new tickets" right

---

src/Toolbox.php

Add ability to retrieve cURL response info

---

src/GLPIMailer.php

Speed-up SMTP XOAuth2 authentication

---

inc/define.php
src/Consumable.php
src/User.php
templates/components/datatable.html.twig

Add consumable tab on users
Add massive actions on the "used items" and "managed items" tabs
| Fixed tickets | !27187

feat(user): add consumable tab

---

.github/ISSUE_TEMPLATE/bug_report.yml

Precision on bug reporting

---

src/CommonDBTM.php

…eld is present in the secondary table

Fix fields ambiguity in `CommonDBTM::canUnrecurs()`

---

src/Agent.php
src/CommonITILRecurrentCron.php
src/CommonITILTask.php
src/CommonITILValidation.php
src/Console/Task/UnlockCommand.php
src/CronTask.php
src/DBAL/QueryFunction.php
src/Features/PlanningEvent.php
src/KnowbaseItem.php
src/NotificationAjax.php
src/OAuth/AccessTokenRepository.php
src/OAuth/AuthCodeRepository.php
src/OlaLevel_Ticket.php
src/Planning.php
src/PlanningRecall.php
src/QueuedNotification.php
src/ReservationItem.php
src/SlaLevel_Ticket.php
src/SoftwareLicense.php
src/System/Status/StatusChecker.php
src/User.php
tests/functional/Glpi/DBAL/QueryFunction.php

More sql function replacements (3)

---

src/Api/HL/RSQLInput.php
src/Api/HL/Search.php
src/CommonITILTask.php
src/DBAL/QueryFunction.php
src/DbUtils.php
src/PlanningRecall.php
src/Project.php
src/ProjectTask.php
src/PurgeLogs.php
tests/functional/Glpi/DBAL/QueryFunction.php

More sql function replacements (2)

---

src/Inventory/Asset/Software.php
tests/functional/Glpi/Inventory/Assets/Software.php

Fix soft manufacturer with and without accents

---

src/Inventory/Asset/MainAsset.php
src/Inventory/Asset/Software.php
tests/functional/Glpi/Inventory/Assets/Software.php
tests/functional/Glpi/Inventory/Inventory.php

Add operating system as a software

---

src/AuthLDAP.php

Fix display of LDAP form when values contains quotes

---

src/Inventory/Asset/Software.php
tests/functional/Glpi/Inventory/Inventory.php

See https://github.com/glpi-project/glpi/pull/14801#issuecomment-1580944719

Use OS full name if present

---

src/NotificationTargetProjectTask.php

Wrong variable name; closes #14680

---

.github/workflows/nightly_build.yml

No longer build 9.5 nightly

---

src/Config.php
src/User.php

Reload current loggedin user config after its been updated

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

Check MariaDB 11.0 compatibility

---

js/modules/Debug/Debug.js
lib/bundles/codemirror.js
package-lock.json
package.json

Fix debug bar compatibility with CodeMirror 6.

fix debug bar cm6 compat

---

.github/workflows/coverage.yml

Run coverage test suite on PHP 8.2

---

src/Auth.php
src/AuthLDAP.php
src/RuleRightCollection.php
src/User.php
tests/LDAP/AuthLdap.php

1. I added many tests to see how generated logs looks, then I added some details on generated logs when it was useful, removed some useless details on other messages and harmonized them.
2. I removed error detail in authentication callback (can be used to do bruteforce authentication).

Enhance LDAP error logs

---

ajax/dropdownMassiveAction.php
src/Debug/Profile.php

Catch `\Throwable` instead of `\Exception`

---

src/Dashboard/Filters/AbstractFilter.php

fix(dashboard): JS uninterpreted

---

src/Ticket.php
tests/functional/RuleTicket.php

With a rule of this type that has an SLA criterion. If only the SLA is updated on the ticket, the rule applies, but if only the urgency is updated, the rule does not apply.
| Fixed tickets | !27501

fix(rule ticket): issue with SLA criteria

---

src/Console/Cache/ConfigureCommand.php
src/Console/Cache/SetNamespacePrefixCommand.php
src/Marketplace/Api/Plugins.php
src/Plugin.php

Fix PHPStan issues related to unused constructors/anonymous functions parameters

---

src/Api/APIRest.php
src/Api/APIXmlrpc.php
src/Auth.php
src/CommonGLPI.php
src/Computer.php
src/Console/Database/InstallCommand.php
src/DbUtils.php
src/Item_Cluster.php
src/Item_DeviceCamera_ImageFormat.php
src/Item_DeviceCamera_ImageResolution.php
src/Item_Enclosure.php
src/Item_Rack.php
src/NetworkEquipment.php
src/NetworkPort.php
src/NotificationTemplateTranslation.php
src/PassiveDCEquipment.php
src/Pdu_Plug.php
src/Peripheral.php
src/Phone.php
src/PlanningRecall.php
src/Printer.php

Fix `Method X::Y() invoked with N parameter, N required.` issues detected by PHPStan

---

src/CommonDBTM.php
src/CommonITILObject.php
src/Console/Plugin/AbstractPluginCommand.php
src/DbUtils.php
src/Debug/Profile.php
src/FieldUnicity.php
src/IPAddress.php
src/Infocom.php
src/Inventory/Asset/MainAsset.php
src/Item_Ticket.php
src/MailCollector.php

Fix PHPStan issues related to check on always/never nullable/falsy variables

---

install/install.php

Since  440adc38fe555fc9d58ba67be700fb0357256f96, installation of main branch is broken.
Maybe I can use $db var for doQuery usage ?

Fix install from UI

---

css/includes/_highcontrast.scss
templates/components/form/fields_macros.html.twig
templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/form_task.html.twig

Before:
After:
| Fixed tickets | !28401

fix: toggle's border with high contrast

---

src/User.php

This field no longer seems to be used and is a source of confusion.

Remove "Personal token" display

---

src/DisplayPreference.php

Add item type in front of item fields

---

src/Inventory/Asset/Monitor.php

Remove monitor type from inventory

---

locales/en_GB.po
locales/glpi.pot
templates/pages/management/softwarelicense.html.twig
tests/functional/Software.php

Fix software translation source

---

js/modules/Debug/Debug.js
locales/en_GB.po
locales/glpi.pot
src/CommonGLPI.php
src/Html.php

Fix some translation strings

---

src/CommonDBTM.php

Fix fields unicity checks

---

src/Agent.php

fix(inventory): UserAgent searchOption on computer

---

src/CommonITILObject.php

| Fixed tickets | !27844
Alternative to #14981 to use the dedicated method that is made prevent XSS issues.

Fix encoding issues in group actors

---

js/modules/Debug/Debug.js

Remove translations on debug bar

---

install/migrations/update_10.0.7_to_10.0.8/ram_field.php

Fix `ram` field update when values contains `MB` unit

---

.github/workflows/audit_dependencies.yml

Disable dependencies audit on 9.5 branch

---

tests/functional/CommonDBTM.php

Add basic field unicity test

---

src/AuthLDAP.php
src/User.php

Fix LDAP DN matching issues when DN contains `&`

---

css/includes/components/_debug-toolbar.scss
js/modules/Debug/Debug.js
templates/components/debug/debug_toolbar.html.twig

Some UI and UX suggestions for the debug bar
Before:
After;
I have a few other changes in mind but I'll split them in another PR to keep things readable.

Debug bar UX

---

src/Computer_Item.php
tests/functional/Glpi/Inventory/Assets/Computer.php

Same as https://github.com/glpi-project/glpi/pull/15002
but when the relation is purged

Fix purge relation

---

src/Dashboard/Provider.php

Fix dashboard links

---

index.php
src/Auth.php
templates/pages/login.html.twig

fix(login-page): add missing id and adapt label ref

---

src/Inventory/Asset/VirtualMachine.php

Hability to handle operating systems from virtual machines

---

src/PrinterLog.php
templates/components/printer_graph_buttons.html.twig
tests/functional/PrinterLog.php

| Fixed tickets | !25229
Improved the graph that displays the number of printed pages of a printer.
* Added a dropdown list to select the period to display (with the possibility to define a custom range)
* Added a dropdown list to select the desired format

Improvement of the printer graph

---

src/Rule.php
tests/functional/Rule.php

Fix extra escaping on rule clone

---

src/DeviceControl.php
src/DeviceDrive.php
src/DeviceHardDrive.php
src/Inventory/Conf.php
src/Item_Disk.php
src/NetworkPortConnectionLog.php
src/NetworkPortInstantiation.php
src/NetworkPortMetrics.php

Harmonize / update / add missing icon
Before : 
After
Before : 
After
Before : 
After : 

Harmonize / update / add missing icon

---

install/migrations/update_0.84.x_to_0.85.0.php

| Fixed tickets | !28461
In #6216 (GLPI 9.5), the `glpi_computers_softwareversions` was renamed to `glpi_items_softwareversions` and altered to handle linking licenses to something else than computers. Problem is that the 0.85 migration is using a method that have evolve to use this new structure instead of hardcoded table name / structure. As the new table / structure does not exists in GLPI < 0.85, migration fails.
Fixes following error:

Fix `glpi_softwarelicenses.is_valid` 0.85 migration

---

src/CommonITILRecurrent.php
tests/functional/CommonITILRecurrent.php

Preserve predefined status of recurrent ticket/change

---

src/Agent.php

Like https://github.com/glpi-project/glpi/pull/14990
for ```TAG```

fix(inventory): TAG searchOption on computer

---

css/includes/components/_debug-toolbar.scss
css/includes/components/itilobject/_footer.scss
js/modules/Debug/Debug.js
templates/components/debug/debug_toolbar.html.twig

make itil buttons visible above debug bar

---

CHANGELOG.md
src/PrinterLog.php
templates/components/printer_graph_buttons.html.twig

I was a bit late on #14779 review. Here are some code quality improvements.

Improve PrinterLog code quality

---

resources/Rules/RuleDictionnaryOperatingSystem.xml
tests/functional/Glpi/Inventory/Assets/OperatingSystem.php

Add Amazon Linux name support in Operating System rules

---

js/modules/Debug/Debug.js
src/Debug/Profiler.php
src/Debug/ProfilerSection.php
src/Search/Provider/SQLProvider.php
src/Search/SearchEngine.php

Add profiling to some sections of the search engine code. This could be useful as more and more DB/Search code gets changed to monitor the performance impact.
This PR also adds the ability to pause and resume a profiler section.

Profile search engine

---

src/User.php

Fix undefined warning when adding a new config at install

---

front/notificationajaxsetting.form.php
front/notificationmailingsetting.form.php

Log mails/browsers notifications config changes

---

install/migrations/update_10.0.7_to_10.0.8/ram_field.php

Fix `ram` field migration on MySQL 5.7

---

src/Dashboard/Grid.php

fix dashboard entity recursive param

---

src/Inventory/Asset/InventoryNetworkPort.php

Ensure built network name is valid; fixes #15152

---

src/Inventory/Asset/MainAsset.php

Prevent SQL error when ```RuleEntity``` refused asset on inventory
```rules_id``` is set in ```_ruleid``` instead of ```rules_id```
```
[2023-07-07 16:38:09] glpisqllog.ERROR: DBmysql::query() in /home/DEV/GLPI/10.0-bugfixes/src/DBmysql.php line 379
SQL: INSERT INTO `glpi_refusedequipments` (`name`, `itemtype`, `serial`, `ip`, `mac`, `uuid`, `rules_id`, `entities_id`, `autoupdatesystems_id`, `date_creation`, `date_mod`) VALUES ('203312PD120HK2G', 'Computer', '5CD120HK2G', '[\"10.33.23.58\"]', '[\"d4:1b:81:b3:3b:75\",\"b0:22:7a:f2:6a:48\",\"d6:1b:81:b3:3b:75\",\"f6:1b:81:b3:3b:75\",\"d4:1b:81:b3:3b:76\",\"d6:1b:81:b3:3b:75\",\"f6:1b:81:b3:3b:75\",\"46:35:00:00:00:36\",\"10:79:20:52:41:53\",\"12:76:20:52:41:53\",\"16:7b:20:52:41:53\",\"10:79:20:5', …
```

fix(inventory): fix missing rule ID From RuleEntity when add as RefeEquipement

---

.atoum.php
.stylelintrc.js
.webpack.config.js
composer.lock

Clean useless license headers in tests/build config files

---

src/DBmysql.php
src/Migration.php
src/NetworkPortMigration.php
tests/units/DB.php

Goal is to limit raw queries (from plugins mainly)

Add drop method to DB

---

src/Auth.php
src/AuthLDAP.php
tests/LDAP/AuthLdap.php

Prevent user to be marked as deleted when LDAP connection failed

---

install/update.php
src/Console/Database/UpdateCommand.php
src/Update.php

Exit with an error when schema is not consistent after update

---

src/DBmysql.php
tests/units/DB.php

Seen trying to replace https://github.com/glpi-project/glpi-inventory-plugin/blob/develop/install/update.php#L364

Add exist clause, improve phpdoc

---

js/dashboard.js

Backport of fix found while creating tests in #15176

Fix suffixes on nuumber dashboard cards

---

js/dashboard.js

Backport of fix found while creating tests in #15176

avoid potential js warn when saving dashboard rights

---

front/logout.php
src/Auth.php

Fix provided by #15204 was not correct.

Fix issue with phpCAS 1.3.6-1 debian package (2)

---

src/GLPI.php

Adapt PHP log level to environment type

---

install/migrations/update_10.0.x_to_10.1.0/ticket.php
install/mysql/glpi-empty.sql
src/Api/HL/Controller/ITILController.php
templates/components/itilobject/fields_panel.html.twig

Add field to tickets meant for tracking the request/incident in an external system.

Ticket external ID

---

src/ITILTemplatePredefinedField.php

Prevent invalid predefined associated item in template

---

src/Api/API.php

Fix parent ID assignation in REST API

---

src/CalDAV/Plugin/Browser.php

Always enable CalDAV debug interface on `development` env

---

src/CommonITILValidationCron.php
tests/functional/CommonITILValidationCron.php

Notifications were sent on all tickets with no status filtering (resolved or closed)
Feat: https://github.com/glpi-project/glpi/pull/11623
| Fixed tickets | !28109

fix(approval reminder): exclude solved tickets

---

templates/components/form/basic_inputs_macros.html.twig

See https://github.com/glpi-project/glpi/commit/7b54e07ac889f5bce826e24d9c7d7e45c69f1eb4#r121840507

Fix input macro additional attributes escaping

---

src/Api/HL/Controller/AssetController.php
tests/functional/Glpi/Api/HL/Controller/AssetController.php

Fix software version endpoints

---

front/form/form.form.php
front/form/form.php
inc/relation.constant.php
install/migrations/update_10.0.x_to_10.1.0/form.php
install/mysql/glpi-empty.sql
src/Form/AnswersSet.php
src/Form/Form.php
src/Form/Question.php
src/Form/Section.php
src/Html.php
src/Migration.php
templates/pages/admin/form_answers_list.html.twig
templates/pages/admin/form_editor.html.twig
tests/units/Html.php

General boilerplate code + database schema.

Forms: basic classes

---

ajax/search.php
front/defaultfilter.form.php
front/defaultfilter.php
install/migrations/update_10.0.x_to_10.1.0/criteriafilter.php
install/mysql/glpi-empty.sql
src/DefaultFilter.php
src/Dropdown.php
src/Profile.php
src/Search/CriteriaFilter.php
src/Search/Input/QueryBuilder.php
templates/components/search/controls.html.twig
templates/components/search/query_builder/main.html.twig
templates/generic_show_form.html.twig

Replace https://github.com/glpi-project/glpi/pull/13977
Addition of default search filters, applied in addition to user filters. This filter can be disabled by the user.
Settings in dropdowns:
| Fixed tickets | !24956

feat(search): additional default filter

---

install/empty_data.php

Add missing default delete domain rights

---

src/Project.php

Fix code comment

---

src/Rule.php
tests/functional/RuleDictionnarySoftware.php
tests/functional/RuleSoftwareCategory.php

show skip remaining rules only when multiple rules can run

---

src/NotificationTargetCommonITILObject.php

Fix mentioned typo

---

src/Dashboard/Dashboard.php

Fix dashboard delete rights

---

src/Project.php

Kanban inherit recursive flag for projects and tasks from parent project

---

.github/workflows/ci.yml
composer.json
inc/define.php
index.php
tools/patches/atoum-4.1.0...4.2.0.patch

PHP 8.3 support

---

src/Config.php
src/Search.php

Fix view rights checks on `Config` class

---

.github/workflows/ci.yml
tests/run_tests.sh

MySQL 8.1 support

---

.eslintrc.json
.vue.webpack.config.js
composer.lock
js/src/vue/app.js
package-lock.json
package.json
src/Html.php

Minimal code required to add Vue.js support split from #15274.

Add vuejs support

---

src/Dropdown.php

fix(user): error message in debug mode

---

src/CommonITILObject.php
tests/functional/Ticket.php

Fix ITIL actors count

---

src/RuleCollection.php
src/Transfer.php
templates/generic_show_form.html.twig
templates/pages/admin/transfer.html.twig
templates/pages/admin/transfer_list.html.twig

Also improve the UI of the transfer list.
Old UI Before Selecting Transfer Mode:
Old UI After Selecting Transfer Mode:
New UI Before Selecting Transfer Mode:
New UI After Selecting Transfer Mode:

Migrate transfer forms to Twig

---

front/printerlogcsv.php
src/Csv/PrinterLogCsvExport.php
src/PrinterLog.php
templates/components/printer_graph_buttons.html.twig

| Fixed tickets | !28627
Adds the ability to export printer consumption data from the graph. The export is done in CSV format, taking into account the chart parameters: interval and format.

Export printer graph data 

---

composer.json
tools/patches/php-markdown-php8-compat.patch

| Fixed tickets | #15412
There is already a bug report and a proposed PR in the library GitHub, but no activity from the maintainer for a while.

Fix deprecation notice for phpmarkdown lib

---

ajax/cable.php
src/Socket.php

Do not try to display rack position on non rackable eleements

---

src/Domain.php

Use same translation as in Appliance for SO label

---

src/Config.php
templates/pages/setup/general/management_setup.html.twig

convert management setup to twig (last of config ui)

---

src/ITILFollowup.php
tests/functional/ITILFollowup.php

The `CommonDBTM::can` method will avoid reloading the current item if possible: 
*`$this->getFromDB` is only called if the row isn't already loaded in `$this>fields`*
We must take advantage of this in the followups rights logic and avoid creating a brand new item when the parent item is already known and loaded.

ITILFollowup: prevent reloading parent item on right check

---

src/Config.php
src/DBConnection.php
templates/components/form/basic_inputs_macros.html.twig
templates/pages/setup/general/api_apiclients_section.html.twig
templates/pages/setup/general/api_setup.html.twig
templates/pages/setup/general/assets_setup.html.twig
templates/pages/setup/general/assistance_setup.html.twig
templates/pages/setup/general/dbreplica_setup.html.twig

Move some Config tabs to Twig (part 1)

---

front/rule.php
src/Application/View/Extension/PhpExtension.php
src/Rule.php
src/RuleCollection.php
src/RuleCriteria.php
templates/components/form/basic_inputs_macros.html.twig
templates/pages/admin/rules/backup_header.html.twig
templates/pages/admin/rules/collections_list.html.twig
templates/pages/admin/rules/engine_preview_criteria.html.twig
templates/pages/admin/rules/engine_preview_results.html.twig
templates/pages/admin/rules/engine_summary.html.twig
templates/pages/admin/rules/import.html.twig
templates/pages/admin/rules/import_preview.html.twig

move some rules ui to twig

---

src/Stat/Data/Graph/StatDataTicketAverageTime.php

Fix inverted titles in tickets stats

---

src/User.php

Ensure removing picture only in picture directory

---

src/Item_SoftwareLicense.php

fix group in item_softwarelicense list

---

ajax/updateTranslationValue.php
src/CommonDropdown.php
src/DropdownTranslation.php

Content translation didn't support richtext.
Before:
After:
| Fixed tickets | !29299

fix(translation): richtext

---

js/modules/Kanban/Kanban.js

Before:
After:
| Fixed tickets | #28851

Kanban: fix columns ordering in "Add column" list

---

src/Api/HL/Search.php
tests/functional/Glpi/Api/HL/Controller/AdministrationController.php
tests/functional/Glpi/Api/HL/Controller/ComponentController.php
tests/functional/Glpi/Api/HL/Controller/ProjectController.php

The initial implementation for the new API was missing entity/advanced visibility checks. This PR adds them.

[HLAPI] Entity and Visibility checks

---

front/printerlogcsv.php
src/Csv/PrinterLogCsvExportComparison.php
src/PrinterLog.php
templates/components/printer_graph_buttons.html.twig
tests/functional/PrinterLog.php

| Fixed tickets | !28627
Adds the ability to compare multiple printers.

Compare printers statistics on printer graph

---

src/Api/HL/Controller/AbstractController.php
src/Api/HL/Router.php
src/Api/HL/Search.php
tests/functional/Glpi/Api/HL/Controller/AssetController.php

If you want translations for a language besides your default, you can pass the `Accept-Language` header with the desired language.

[HLAPI] Dropdown translations

---

src/Entity.php
templates/components/form/fields_macros.html.twig
templates/pages/admin/entity/address.html.twig
templates/pages/admin/entity/advanced.html.twig
templates/pages/admin/entity/assets.html.twig
templates/pages/admin/entity/notifications.html.twig

Converted the following tabs to Twig:
- Address
- Advanced
- Assets
- Notifications
Other changes:
- Added ability to have form helpers in `largeTitle` and `smallTitle`

Start converting entity forms to twig

---

CHANGELOG.md
css/legacy/includes/_styles.scss
js/modules/Search/GenericView.js
src/SavedSearch.php
src/SavedSearch_Alert.php
templates/components/datatable.html.twig
templates/components/search/query_builder/main.html.twig
templates/pages/tools/savedsearch/alert.html.twig
templates/pages/tools/savedsearch/alert_list_notification.html.twig
templates/pages/tools/savedsearch/form.html.twig
templates/pages/tools/savedsearch/save_button.html.twig

Notable change:
- Saved search alert list is now paginated and sortable

Migrate savedsearch ui to twig

---

src/Features/Kanban.php

Follows #15404. Proposed fix was not working for some languages, for instance for `bg_BG` (`Kanban` is translated to `Табло`).

Fix Kanban switcher

---

js/common.js
src/CommonITILTask.php
src/Planning.php
templates/components/itilobject/timeline/form_task.html.twig

Add task state icon
| Fixed tickets | !28658

feat(ITILTask): add state icon

---

tests/units/Migration.php

Fix local tests; cleanup

---

src/AuthLDAP.php
src/User.php
tests/LDAP/AuthLdap.php
tests/LDAP/README.ldap
tests/LDAP/ldif/ldap-glpi.ldif

Fix issues with `&` char in LDAP sync operations

---

front/dictionnary.php

File has moved

---

src/Application/View/Extension/SessionExtension.php
src/Notification.php
src/NotificationEvent.php
src/NotificationTarget.php
src/NotificationTemplate.php
src/NotificationTemplateTranslation.php
src/Notification_NotificationTemplate.php
templates/components/form/basic_inputs_macros.html.twig
templates/pages/setup/notification/event_debug.html.twig
templates/pages/setup/notification/group_notifications.html.twig
templates/pages/setup/notification/notification.html.twig
templates/pages/setup/notification/notification_notificationtemplate.html.twig
templates/pages/setup/notification/recipients.html.twig
templates/pages/setup/notification/template.html.twig
templates/pages/setup/notification/template_notifications.html.twig
templates/pages/setup/notification/translation.html.twig
templates/pages/setup/notification/translation_debug.html.twig

migrate notifications ui to twig

---

src/Config.php
templates/components/form/basic_inputs_macros.html.twig
templates/components/user/password_security_checks.html.twig
templates/install/agree_unstable.html.twig
templates/pages/setup/general/logs_setup.html.twig
templates/pages/setup/general/performance.html.twig
templates/pages/setup/general/security_setup.html.twig
templates/password_form.html.twig

Move some Config tabs to Twig (part 3)

---

install/empty_data.php
install/migrations/update_9.5.x_to_10.0.0/notifications.php
tests/functional/Glpi/RichText/UserMention.php

Fix typo on user mentioned default notification

---

src/Inventory/Asset/VirtualMachine.php
tests/functional/Glpi/Inventory/Assets/VirtualMachine.php

Replace https://github.com/glpi-project/glpi/pull/15584
allow computers import even if some are refused
| Fixed tickets | #15581

fix(inventory): allow computers import even if some are refused

---

front/projecttask.form.php

add redirection to project on delete to prevent white page
add missing 'restore' action

fix(ProjectTask): add redirection to project on delete to prevent white page

---

css/includes/_base.scss

| Fixed tickets | #15606
Can be removed when Tabler is updated.

fix autofill color in webkit

---

src/CommonItilObject_Item.php
src/Dropdown.php
src/Html.php
src/NotificationTarget.php
src/RuleCollection.php
tests/functional/Dropdown.php

Follows the cleanup done in #14302. These occurrences were either missed during code cleanup or missed during subsequent merge operations.

Remove useless stripslashes operations

---

src/Inventory/Asset/NetworkPort.php
tests/functional/Glpi/Inventory/Assets/NetworkPort.php

Fix VLAN change, add test; closes #15618

---

README.md

fix(readme): add link for GLPI plugins documentation

---

src/Inventory/Inventory.php
tests/functional/Glpi/Inventory/Assets/VirtualMachine.php

Make sure VMs are removed if node is empty

---

front/document.send.php
src/Console/Diagnostic/CheckDocumentsIntegrityCommand.php
src/Console/Marketplace/InfoCommand.php

Use existing translations

---

src/System/Requirement/SafeDocumentRoot.php

Handle usage of `auto_prepend_file` configuration

---

src/KnowbaseItem.php
tests/functional/KnowbaseItem.php

Backport from https://github.com/glpi-project/glpi/pull/13455

fix(faq): visibility

---

src/Config.php
src/DBConnection.php
src/DBmysql.php
templates/pages/setup/general/dbreplica_setup.html.twig

Review DB replica tab

---

install/migrations/update_10.0.10_to_10.0.11/transfer.php
install/mysql/glpi-empty.sql
src/Transfer.php
tests/functional/Transfer.php

Add new location option to transfer
* Empty the location
* Preserve (default behavior and same as before)
| Fixed tickets | !29010

feat(Transfer): add new option for location field

---

src/CommonITILObject.php
src/DbUtils.php
src/RuleAction.php
src/RuleCommonITILObject.php
tests/functional/RuleTicket.php

Add the requester's manager to the ticket's actors via the ticket's business rules
| Fixed tickets | !29808

feat(ticket rules): add requester's manager

---

css/includes/components/_select2.scss
css/legacy/includes/_inputs.scss

fix more dark theme text colors

---

src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php

| Tests pass?   | I Hope
This is a very important fix 😆

fix: missing an R in the name of a function

---

src/Rule.php
tests/functional/Glpi/Inventory/Assets/VirtualMachine.php
tests/functional/Rule.php

| Bug fix?      | yes?
| Fixed tickets | #15658

Fix rule creation via api

---

install/migrations/update_10.0.10_to_10.0.11/duplicate_searchopt_fixes.php
src/Domain.php
src/Monitor.php
src/Peripheral.php
src/Phone.php
src/Printer.php
src/Project.php
src/Search.php

fix duplicate Computer search options

---

templates/pages/setup/general/dbreplica_setup.html.twig

Fixes following issue introduced in #15594:

Fix DB replica writable state badges

---

src/Inventory/Asset/Device.php
src/Inventory/Asset/InventoryAsset.php
tests/functional/Glpi/Inventory/Assets/Firmware.php

Prevent SQL warning when GLPI try to load ```LockedField``` from item
```shell
SQL: SELECT * FROM `glpi_lockedfields` WHERE `itemtype` = 'Item_DeviceFirmware' AND ((`items_id` = '' OR `is_global` = '1'))
Warnings: 
1292: Truncated incorrect DECIMAL value: ''
Backtrace :
src/DBmysqlIterator.php:112                        
src/DBmysql.php:1078                               DBmysqlIterator->execute()
src/Lockedfield.php:218                            DBmysql->request()
src/Lockedfield.php:158                            Lockedfield->getLocks()
src/Inventory/Asset/InventoryAsset.php:433         Lockedfield->getLockedNames()
src/Inventory/Asset/Device.php:175                 Glpi\Inventory\Asset\InventoryAsset->handleInput()
src/Inventory/Asset/MainAsset.php:937 …
```

fix(Inventory): prevent SQL warning on load lockedfields

---

tests/functional/Lockedfield.php

Fix locked fields tests

---

ajax/entitytreesons.php

On a GLPI instance that has many entities and where almost every user has its own entity tree, sharing a same cache key for all possible entity trees is not a good idea, as it can result in a huge cache file. Reading and deserializing this file would probably use many resources, and I think it is preferable to have more smaller files on the filesystem.
PS: impact on performances will be mitigated by #15792, but I still think it is a bad idea to use a single cache entry here.

Split entity selector cache entries

---

src/NotificationTargetReservation.php

Added Note field for reservation notification template

Added Note field for reservation notification template

---

src/CommonDBTM.php
src/Inventory/Asset/InventoryAsset.php
src/Inventory/Asset/MainAsset.php
tests/functional/Glpi/Inventory/Inventory.php

| Fixed tickets | !29764 #14609

Handle modified values from business rules during inventory

---

templates/pages/admin/inventory/upload_result.html.twig

JS back is enough and prevent this requirement

Using URL requires config to be set properly

---

front/reservation.form.php

Redirect after fail update of reservation; fixes #15825

---

CHANGELOG.md
ajax/notificationmailingsettings.php
front/notificationmailingsetting.form.php
src/GLPIMailer.php
src/MailCollector.php
src/NotificationEventMailing.php
src/NotificationMailing.php
templates/pages/setup/notification/mailing_setting.html.twig

This pull request addresses an issue related to the testing of email notifications via the "Send a test email to the administrator" functionality in the general notification configuration. Currently, when a test email fails to send, the error details are not displayed to the user. Instead, users need to enable the debug mode and check the mail-debug.log file to access this information, which is less than ideal.
To enhance the user experience, this modification ensures that error details are displayed directly via a session message, even when the debug mode is not enabled. This change only affects the "Test Email" feature and …

feat: Refactor SMTP test email functionality and add debug logs modal

---

ajax/stencil.php
css/standalone/stencil-editor.scss
front/stencil.form.php
install/migrations/update_10.0.x_to_10.1.0/stencil.php
install/mysql/glpi-empty.sql
js/stencil-editor.js
lib/bundles/cropper.js
package-lock.json
package.json
src/Features/ZonableModelPicture.php
src/NetworkEquipmentModelStencil.php
src/NetworkPort.php
src/Stencil.php
src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
templates/stencil/editor.html.twig
templates/stencil/parts/label.html.twig
templates/stencil/parts/port/popover.html.twig
templates/stencil/parts/port/status.html.twig
templates/stencil/parts/zones.html.twig
templates/stencil/view.html.twig
tests/functional/Search.php
tests/units/DB.php
tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php

This mechanism is intended to be reused, so I made sure that the development was generic.

Graphical slot definition for NetworkEquipmentModels

---

src/DeviceMemory.php
src/DeviceProcessor.php
src/Item_DeviceProcessor.php

Add unit on frequency for CPUs/Memory

---

js/modules/Kanban/Kanban.js
src/CommonITILObject.php

Fix ITIL Kanban column list

---

templates/components/form/basic_inputs_macros.html.twig
templates/components/form/fields_macros.html.twig
templates/pages/setup/crontask/crontask.html.twig

| Bug fix?      | ye
Replace #15817 (forgot to create a branch)
Since https://github.com/glpi-project/glpi/pull/14852
mailing_settings seems to be fixed
Difficult to say I didn't break anything

fix id attribute in macro field files

---

install/migrations/update_10.0.x_to_10.1.0/entity.php
install/mysql/glpi-empty.sql
src/Entity.php
src/NotificationTarget.php
src/NotificationTargetUser.php
src/User.php
templates/pages/admin/entity/notifications.html.twig
tests/functional/NotificationTarget.php
tests/functional/NotificationTargetTicket.php

Notifications url base

---

src/Ajax.php
templates/components/itilobject/timeline/timeline.html.twig
templates/components/itilobject/timeline/timeline_item_header.html.twig

Follows #15831, add a X shaking animation when auto-scrolling to an element in timeline

animate parent item when scrolling to hash

---

src/CommonITILObject.php
tests/functional/Ticket.php

fix timeline order with same creation date

---

ajax/telemetry.php

fix telemetry button during install

---

js/common.js
js/glpi_dialog.js
js/modules/Kanban/Kanban.js
src/Auth.php
src/CronTask.php
src/DomainRelation.php
src/MailCollector.php
src/RSSFeed.php
src/Toolbox.php
templates/components/form/buttons.html.twig
templates/components/form/fields_macros.html.twig
templates/components/messages_after_redirect_toasts.html.twig
templates/pages/login_error.html.twig
templates/pages/setup/authentication/other_ext_setup.html.twig
templates/pages/setup/authentication/sync.html.twig
templates/pages/setup/mailcollector/folder_list.html.twig
templates/pages/setup/mailcollector/results_title.html.twig
templates/pages/setup/mailcollector/server_config_fields.html.twig
templates/pages/setup/mailcollector/setup_form.html.twig

Migrate Auth, MailCollector and DomainRelation to twig

---

src/Agent/Communication/AbstractRequest.php
src/DBmysql.php
src/Inventory/Asset/MainAsset.php
src/Inventory/Asset/Software.php
src/Inventory/Conf.php
src/Inventory/Inventory.php
src/NotificationTarget.php
src/Toolbox/FrontEnd.php
src/Toolbox/MarkdownBuilder.php
src/Toolbox/Sanitizer.php
src/Toolbox/URL.php

Few CS fixes

---

src/Api/HL/Controller/ITILController.php

[HLAPI] Add request source for followups and tickets

---

.github/workflows/nightly_build.yml

Fixes the following deprecation:

Replace deprecated usage of `::set-output`

---

templates/components/search/displaypreference_config.html.twig

Fix display preference list JS

---

src/Search.php
tests/functional/Appliance.php

Add missing meta options for appliances

---

templates/components/infocom.html.twig

Change sink coef step

---

inc/based_config.php
src/RichText/RichText.php
stubs/glpi_constants.php

Move threshold setting for read more button
| Fixed tickets | !30376

feat: move read more setting

---

src/Console/Plugin/ActivateCommand.php
src/Console/Plugin/DeactivateCommand.php

`plugin:activate` -> `plugin:enable`
`plugin:deactivate` -> `plugin:disable`

Add aliases for plugin CLI commands

---

src/Entity.php

fix: incorrect check right entity inventory tab

---

front/stat.tracking.php

Fix ITIL stat pager count

---

CHANGELOG.md
src/CommonITILActor.php
src/CommonITILObject.php

More correct fix of #15900 for main branch to avoid bad SQL requests.

Strict types for getActors method

---

src/Api/HL/OpenAPIGenerator.php

Noticed issue in Servicedesk Brasil video reviewing GLPI 10.1 features where nonsensical endpoints were being shown in the documentation like `/Assistance/Task/{id}/Timeline/{subitem_type}`. Tasks do not in fact have their own timeline. This was caused by an incorrectly hardcoded placeholder name in the documentation generator. This PR resolves that issue, but also enables expanding paths with more than one placeholder that has a static set of values. That means that the timeline endpoints will now be correct and complete like `/Assistance/Ticket/{id}/Timeline/Followup` rather than show `{subitem_type}` placeholders.
This …

[HLAPI] Expand paths with multiple placeholders

---

js/src/vue/Debug/Toolbar.vue
js/src/vue/Debug/Widget/HTTPRequests.vue
js/src/vue/Debug/Widget/RequestSummary.vue
js/src/vue/Debug/Widget/RequestTimeline.vue

The initial development for the new debug bar had a network timeline graph feature (hidden by default but can be shown with 't' key on requests tab). When the debug bar was moved to Vue, this hidden feature was only partially migrated and was not functional anymore. This PR restores the functionality and fixes some minor lint issues.

Fix debug timeline view implementation

---

src/Inventory/Inventory.php
tests/functional/Glpi/Inventory/Assets/RemoteManagement.php

Like https://github.com/glpi-project/glpi/pull/15380
but for Remote managment
| Fixed tickets | !30576

Make sure Remote mgmt  are removed if node is empty

---

templates/components/itilobject/timeline/form_validation.html.twig

| Fixed tickets | !30578
This was the last place that didn't use `do call('Ajax::updateItemOnSelectEvent')`.

standardize updateItemOnSelectEvent

---

src/CommonDCModelDropdown.php
src/Computer.php
src/Enclosure.php
src/Monitor.php
src/NetworkEquipment.php
src/PDU.php
src/PassiveDCEquipment.php
src/Peripheral.php

add searchoptions for pictures in assets

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

Run CI on PHP 8.3

---

ajax/stencil.php
front/stencil.form.php
js/stencil-editor.js
src/NetworkEquipmentModelStencil.php
src/Stencil.php
templates/stencil/editor.html.twig

This pull request is a continuation of the UX improvements introduced in PR #15229, with a focus on enhancing the Stencil Editor by implementing AJAX for the "Add" and "Remove" buttons.
- Added keyboard shortcuts for faster interaction.
- Integrated AJAX for "Add" and "Remove" actions to improve user experience.
- Limited input values to prevent browser crashes.
- Updated code structure for the above changes.
- Set a maximum zone number to 128 for consistency.
- Validated input for the zone number.

ux(Stencil): Enhance UX for stencils

---

composer.lock
src/DbUtils.php
src/OlaLevelAction.php
src/OlaLevelCriteria.php
src/RuleAction.php
src/SlaLevelAction.php
src/SlaLevelCriteria.php

Update to latest phpstan

---

install/empty_data.php
install/migrations/update_10.0.x_to_10.1.0/notifications.php
src/PendingReasonCron.php

**Description:**
This pull request includes two fixes.
The first fix makes the notifications of pending reasons recursive.
The second fix adds slashes to escape fields, ensuring that special characters are properly handled.

fix(pending-reasons): make notifications recursive and escape fields

---

src/Api/Deprecated/CommonDeprecatedTrait.php
src/Config.php
src/DomainRecord.php
src/Features/PlanningEvent.php
src/Inventory/Inventory.php
src/Marketplace/Api/Plugins.php
src/MassiveAction.php
src/Notification.php
src/NotificationTarget.php
src/Notification_NotificationTemplate.php
src/OlaLevel.php
src/Peripheral.php
src/Phone.php
src/Printer.php
src/Profile.php
src/RequestType.php
src/Rule.php
src/RuleAction.php
src/RuleCollection.php
src/RuleImportComputer.php
src/RuleRightCollection.php
src/RuleSoftwareCategoryCollection.php
src/SavedSearch.php
src/SingletonRuleList.php
src/SlaLevel.php
src/Software.php
src/Timer.php

Bunch of phpdoc fixes

---

front/tickettask.form.php
src/CommonITILTask.php
tests/functional/CommonITILTask.php
tests/functional/Ticket.php

| Fixed tickets | !29551
This request associates a user or group with a ticket if they are assigned to a task linked to that ticket.
This is handled before calling commonitiltask.form.php in tickettask.form.php.

Association of a technician with a ticket if he is assigned a ticket task

---

js/modules/Kanban/Kanban.js

| Fixed tickets | !30745
The "Add column" button did not display anything.
The browser console displayed an error such as "column.id is undefined".

Fix(ticket kanban): Add column do nothing

---

src/Config.php

Having this information could make troubleshooting bug reports easier especially if hosting providers disable specific PHP functions without the user knowing.

Report blocked functions in system info

---

src/System/Requirement/PhpSupportedVersion.php
tests/units/Glpi/System/Requirement/PhpSupportedVersion.php

Try to make the PHP version security requirement more clear

---

css/includes/components/itilobject/_timeline.scss
templates/components/form/fields_macros.html.twig
templates/components/itilobject/answer.html.twig
templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/form_task_main_form.html.twig
templates/components/itilobject/timeline/timeline.html.twig
templates/components/itilobject/timeline/timeline_item_header.html.twig

+ a few things to fix new form alignement with existing timeline items

make timeline private state more clear

---

front/updatepassword.php

Fix login redirect to updatepassword

---

src/Search.php

| Fixed tickets | !30871
Prevent error message :
```
glpiphplog.CRITICAL:   *** Uncaught Exception DivisionByZeroError: Division by zero in .../src/Search.php at line 7128
```

fix:(search): division by zero

---

install/migrations/update_10.0.x_to_10.1.0/displaypreference.php
src/Application/View/TemplateRenderer.php
src/Printer_CartridgeInfo.php

| Fixed tickets | #13000 
This pull request addresses the design considerations discussed in issue #13000 regarding the badge color labels. The decision was made to keep the color label within the badge, as under normal usage there should be 4 badges, and these 4 badges are narrower than the minimum column width (due to the rather long column label). An aria-label with the color has also been added for accessibility.

refactor(Printer_CartridgeInfo): simplify cartridge information display

---

inc/db.function.php
src/CommonITILObject.php
src/CommonITILTask.php
src/DbUtils.php
src/Rule.php
src/SavedSearch.php
src/SavedSearch_Alert.php
src/Search.php
src/Session.php
src/Socket.php
src/Software.php
src/SoftwareLicense.php
src/SoftwareVersion.php
src/Stat.php
src/State.php
src/Ticket.php
src/TicketTemplate.php
src/Toolbox.php
src/User.php
src/UserEmail.php

phpstan fixes

---

src/Contract.php

Add locations SO to Contracts; closes #16231

---

front/pluginimage.send.php

Adds the possibility of specifying a subfolder in the image path
Need for https://github.com/pluginsGLPI/genericobject/pull/368

feat(Pluginimage): handle subfolder

---

src/DomainRelation.php
tests/functional/DomainRelation.php

Fix domain relation deletion

---

src/Lockedfield.php

Add comment field to global locks

---

src/Api/HL/Search.php

If a GLPI admin has a DB replica configured, the High-Level API's search code should use it when possible for performance reasons.

HL API search should use db read connection

---

src/Toolbox.php

remove useless code

---

src/NotificationTarget.php

| Fixed tickets | !30994
Prevent error message:
```
[2023-12-22 11:21:06] glpiphplog.CRITICAL: *** Uncaught Exception Error: Call to undefined method Glpi\Marketplace\Controller::maybeRecursive() in .../src/NotificationTarget.php at line 1753
Backtrace :
src/NotificationTarget.php:591 NotificationTarget->isTargetItemRecursive()
src/NotificationTarget.php:730 NotificationTarget->addToRecipientsList()
src/NotificationTarget.php:1251 NotificationTarget->addAdmin()
src/NotificationEventAbstract.php:98 NotificationTarget->addForTarget()
src/NotificationEvent.php:188 NotificationEventAbstract::raise()
src/Marketplace/Controller.php:350 …
```

fix(notification): undefined method maybeRecursive

---

src/Rule.php

fix rule preview for append actions

---

src/Planning.php

Improve handling of invalid planning filters

---

src/Dashboard/Provider.php

Limit ticket validation dashboard card to not old statuses

---

css/tabler.scss

Re-enable negative margin support

---

install/migrations/update_10.0.11_to_10.0.12/log_rights.php

Tests are failing on the bugfixes branch due to a faulty header.
| New feature?   no

Fix invalid header for log_rights.php

---

ajax/itilfollowup.php
ajax/task.php
inc/relation.constant.php
install/migrations/update_10.0.x_to_10.1.0/itilfollowuptemplates.php
install/migrations/update_10.0.x_to_10.1.0/tasktemplates.php
install/mysql/glpi-empty.sql
src/CommonITILTask.php
src/ITILFollowup.php
src/ITILFollowupTemplate.php
src/TaskTemplate.php
templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/form_task.html.twig

| Fixed tickets | !30468
This PR adds the ability to define a pending reason in a followup or task template.

feat: add pending reason for followup and task templates

---

src/ReservationItem.php
tests/functional/Reservation.php

fix entity restrict for reservable item dropdown

---

templates/components/itilobject/timeline/form_followup.html.twig

| Fixed tickets | !31203
Follow-up templates were not filtered by entity, as task or solution templates already are.

fix(followup): template visibility

---

src/AbstractITILChildTemplate.php
src/Blacklist.php
src/BlacklistedMailContent.php
src/CommonDCModelDropdown.php
src/CommonDeviceModel.php
src/CommonType.php
src/ITILCategory.php
src/ITILFollowupTemplate.php
src/ITILValidationTemplate.php
src/Location.php
src/Manufacturer.php
src/SolutionTemplate.php
src/State.php
src/TaskCategory.php
src/TaskTemplate.php
tests/functional/Dropdown.php

| Fixed tickets | #14770
With this PR, 57 of 120 dropdown classes will now be clonable and have the cloning feature tested for them.

Add some clonable dropdowns

---

src/MailCollector.php
src/Migration.php

fix(log): carriage return not interpreted

---

src/SoftwareLicense.php

```
glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "entities_id" in .../src/NotificationTargetSoftwareLicense.php at line 72
Backtrace :
src/NotificationTarget.php:1394                    NotificationTargetSoftwareLicense->addDataForTemplate()
src/NotificationTemplate.php:279                   NotificationTarget->getForTemplate()
src/NotificationEventAbstract.php:125              NotificationTemplate->getTemplateByLanguage()
src/NotificationEvent.php:187                      NotificationEventAbstract::raise()
src/NotificationEvent.php:244                      NotificationEvent::raiseEvent() …
```

fix(license): prevent warning in debug mode

---

css/includes/components/_documentation.scss
src/Api/HL/Controller/CoreController.php
src/Html.php

- Fix styles for documentation pages and better align them to the regular GLPI UI (bootstrap/tabler styles).
- Fix missing libraries for HL API documentation page.

Fix documentation UI

---

src/Ticket.php
tests/functional/SLM.php

| Fixed tickets | !31189
When the SLA of a ticket that had a waiting duration changed, this waiting duration was not taken into account when calculating the new resolution date.

fix(ticket): waiting duration when SLA changes

---

src/CommonITILObject.php
src/KnowbaseItem.php

| Fixed tickets | !31251
When you want to add a solution to a change using the button for fetching a solution from the knowledge base, this doesn't work and redirects you to the change statistics tab.
The same applies to problems. Tickets were already OK.

fix(change + problem): load solution from kb

---

src/Asset/Capacity/HasLinksCapacity.php
src/Link.php
tests/functional/Glpi/Asset/Capacity/HasLinksCapacity.php

Add Links capacity

---

front/change.form.php
front/problem.form.php

| New feature?  |/no
| Fixed tickets | !31251
On a change, when we added a solution and wanted to add it to the KB, the fields in the KB form were empty.
_Same with problems, Tickets OK_

fix(change + problem): add solution to kb

---

src/Asset/Capacity/HasCertificatesCapacity.php
tests/functional/Glpi/Asset/Capacity/HasCertificatesCapacity.php

Add Certificates capacity

---

install/migrations/update_10.0.x_to_10.1.0/antivirus.php

When migration has already been done, it cannot be replayed.

Fix antiviruses migration replay

---

src/Asset/Capacity/HasDomainsCapacity.php
tests/functional/Glpi/Asset/Capacity/HasDomainsCapacity.php

Add Domains capacity

---

js/dashboard.js

| Fixed tickets | !31342
When you want to add a filter and there isn't another one already, an error appears in the browser console and blocks the addition.

fix(dashboard): add filter

---

src/Asset/AssetDefinitionManager.php
src/Asset/AssetModel.php
src/Asset/Capacity/IsRackableCapacity.php
src/Item_Rack.php
src/Rack.php
tests/functional/Glpi/Asset/Capacity/IsRackableCapacity.php

Add Rackable Capacity

---

src/Appliance_Item.php
src/Asset/Capacity/HasAppliancesCapacity.php
tests/functional/Glpi/Asset/Capacity/HasAppliancesCapacity.php

Add Appliances Capacity

---

src/Asset/Capacity/HasAntivirusCapacity.php
tests/functional/Glpi/Asset/Capacity/HasAntivirusCapacity.php

Add antivirus capacity to generic assets

---

src/Document.php

| Fixed tickets | !31156
It seems that the current description is not explicit enough.

cleanorphans: more precise description

---

src/Asset/Capacity/HasRemoteManagementCapacity.php
tests/functional/Glpi/Asset/Capacity/HasRemoteManagementCapacity.php

Add remote management capacity

---

src/Console/Ldap/SynchronizeUsersCommand.php

Add Server Name To LDAP Sync

---

ajax/form/form_renderer.php
front/form/form.form.php
front/form/form.php
install/empty_data.php
install/migrations/update_10.0.x_to_10.1.0/form.php
src/Form/Form.php
src/Profile.php

Add basic rights for forms management. 

Forms: basic rights

---

js/modules/Dashboard/Dashboard.js

Seems OK in 10.0/bugfixes with the action and data properties separated.

fix dashboard in single request mode

---

src/DbUtils.php
templates/components/user/info_card.html.twig

| Fixed tickets | !31508
Add data on users registration numbers to their cards.

Feature/ Adding matricule to user tooltip card

---

src/Asset/Capacity/HasDatabaseInstanceCapacity.php
tests/functional/Glpi/Asset/Capacity/HasDatabaseInstanceCapacity.php

Add databaseinstance capacity

---

src/Computer_Item.php

Add Type To Computer_Item List
| Fixed tickets | #

Add Type To Computer_Item List

---

js/form_editor_controller.js
src/Form/QuestionType/QuestionTypeInterface.php
src/Form/QuestionType/QuestionTypeLongAnswer.php
src/Form/QuestionType/QuestionTypesLoader.php
templates/pages/admin/form/form_editor.html.twig
templates/pages/admin/form/form_question.html.twig

Add the "Long answer" response type and the possibility to change a question's type.

Forms : basic questions types

---

templates/components/form/rulematchedlogs.html.twig

fix(UI): add btn class to <a>

---

js/form_editor_controller.js
src/Form/Form.php
templates/pages/admin/form/form_editor.html.twig
templates/pages/admin/form/form_question.html.twig
templates/pages/admin/form/form_section.html.twig

Forms: basic section management

---

front/asset/assetdefinition.form.php
install/migrations/update_10.0.x_to_10.1.0/assets.php
src/Asset/AssetDefinition.php
src/Asset/AssetDefinitionManager.php
src/Profile.php
src/ProfileRight.php
tests/DbTestCase.php
tests/functional/Glpi/Asset/AssetDefinition.php
tests/functional/Glpi/Asset/Capacity/HasAntivirusCapacity.php
tests/functional/Glpi/Asset/Capacity/HasAppliancesCapacity.php
tests/functional/Glpi/Asset/Capacity/HasCertificatesCapacity.php
tests/functional/Glpi/Asset/Capacity/HasDatabaseInstanceCapacity.php
tests/functional/Glpi/Asset/Capacity/HasDomainsCapacity.php
tests/functional/Glpi/Asset/Capacity/HasNotepadCapacity.php
tests/functional/Glpi/Asset/Capacity/HasVolumesCapacity.php

Show custom asset rights in a new "Custom assets" section on the Asset tab in the Profile forms.

Add custom asset rights to profile form

---

src/Search.php
tests/functional/Search.php

Since https://github.com/glpi-project/glpi/pull/16433, `Test on PHP 8.3 using mariadb:10.2` fail
https://github.com/glpi-project/glpi/actions/runs/7831077372/job/21366577017

fix(test search): order by actor

---

front/asset/asset.form.php
install/migrations/update_10.0.x_to_10.1.0/assets.php
install/mysql/glpi-empty.sql

Custom asset templates

---

css/includes/components/form/_form-editor.scss
js/form_editor_controller.js
src/Form/Form.php
src/Form/Section.php
templates/pages/admin/form/form_question.html.twig

Allow questions to be reordered using drag and drop.

Forms: reorder questions 

---

css/includes/components/form/_form-editor.scss
js/form_editor_controller.js
templates/pages/admin/form/form_editor.html.twig
templates/pages/admin/form/form_question.html.twig
templates/pages/admin/form/form_section.html.twig
templates/pages/admin/form/move_section_modal.html.twig

Forms: reorder sections

---

tests/functional/Glpi/Asset/Capacity/HasDomainsCapacity.php

Add missing SO num in `HasDomainsCapacity` tests

---

templates/pages/login.html.twig

| Fixed tickets | #15258
Improve login page
**Before**
**After**

Small improvment login page

---

install/migrations/update_10.0.x_to_10.1.0/oauth.php
install/mysql/glpi-empty.sql
src/Api/HL/Controller/CoreController.php
src/Api/HL/RoutePath.php
src/OAuth/Client.php
src/OAuth/ClientRepository.php
src/OAuthClient.php
templates/components/form/fields_macros.html.twig
templates/pages/setup/oauthclient.html.twig
tests/bootstrap.php
tests/functional/Glpi/Api/HL/Controller/CoreController.php

Allow specifying the authorized redirect URIs for OAuth clients.

Allow specifying authorized OAuth redirect URIs

---

src/QueuedWebhook.php

| Fixed tickets | !31553
In some cases, the Guzzle client may throw a non-RequestException exception and therefore the `getResponse` method may not always be available.

Handle more Guzzle exceptions when sending Webhooks

---

src/Asset/Capacity/HasNetworkPortCapacity.php
src/IPAddress.php
tests/functional/Glpi/Asset/Capacity/HasNetworkPortCapacity.php

Capacity: Has network ports

---

tools/genapidoc.sh

There is certainly still better to do (and besides we no longer publish the generated doc), but at least the script works again locally with these modifications :D

fix(tools): genapi script

---

templates/components/form/basic_inputs_macros.html.twig
templates/pages/setup/oauthclient.html.twig

make client ID copyable in auth client

---

src/Controller/CommonAjaxController.php
src/Form/Form.php
tests/functional/Glpi/Controller/CommonAJAXController.php

Add unit tests for CommonAjaxController

---

src/Asset/Capacity/AbstractCapacity.php
src/Asset/Capacity/CapacityInterface.php
src/Asset/Capacity/HasHistoryCapacity.php
templates/pages/admin/assetdefinition/capacities.html.twig

Add a description to each capacity.

Add description for capacities (and muted texts in setup)

---

css/includes/_includes.scss
css/includes/components/form/_form-renderer.scss
front/form/form_renderer.php
js/form_editor_controller.js
js/form_renderer_controller.js
src/Form/Form.php
templates/pages/admin/form/form_editor.html.twig
templates/pages/form_renderer.html.twig
tests/functional/Glpi/Form/Renderer/FormRenderer.php

Replace the temporary "preview" modal by a proper dedicated page:

Improve form preview; Add tests for FormRenderer

---

src/Form/AnswersHandler/AnswersHandler.php
src/Form/AnswersSet.php
src/Form/Form.php
src/Form/Question.php
src/Form/QuestionType/QuestionTypeLongAnswer.php
src/Form/QuestionType/QuestionTypeShortAnswerEmail.php
src/Form/QuestionType/QuestionTypeShortAnswerNumber.php
src/Form/QuestionType/QuestionTypeShortAnswerText.php
src/Form/Section.php

Use final for most Form classes

---

js/form_editor_controller.js
src/Form/Form.php
tests/DbTestCase.php
tests/functional/Glpi/Form/Form.php

Need to be rebased once #16567 is merged as we reuse its FormBuilder component.
Simplified the question input format from `_questions[section_index][question_index]` to `_questions[question_index]` as having the section index here was not really used.

Add tests for Form 

---

src/Form/QuestionType/QuestionTypeCategory.php
src/Form/QuestionType/QuestionTypeInterface.php
src/Form/QuestionType/QuestionTypeLongAnswer.php
src/Form/QuestionType/QuestionTypeShortAnswer.php
src/Form/QuestionType/QuestionTypeShortAnswerEmail.php
src/Form/QuestionType/QuestionTypeShortAnswerNumber.php
src/Form/QuestionType/QuestionTypeShortAnswerText.php
src/Form/QuestionType/QuestionTypesManager.php
tests/functional/Glpi/Form/QuestionType/QuestionTypesManager.php

Add tests for QuestionTypeManager

---

src/Form/Question.php
src/Form/Section.php
tests/DbTestCase.php
tests/functional/Glpi/Form/Question.php
tests/functional/Glpi/Form/Section.php

Add tests for Question and Section

---

front/report.dynamic.php
front/stat.item.php
front/stat.location.php
front/stat.tracking.php
src/Api/HL/Controller/ReportController.php
src/Api/HL/GraphQLGenerator.php
src/Api/HL/OpenAPIGenerator.php
src/Api/HL/Router.php
src/Stat.php
tests/HLAPITestCase.php
tests/functional/Glpi/Api/HL/Controller/ReportController.php

Add endpoints to retrieve assistance statistics that match Assistance > Statistics in the web UI.
To accomplish this, some of the existing statistics code was cleaned and moved from the `front` files to the `Stat` class.

[HLAPI] Assistance Stats

---

src/Enclosure.php

Fix SO condition

---

js/src/vue/Debug/Widget/SQLRequests.vue

fix copying sql from debug bar

---

src/Asset/Capacity/HasVirtualMachineCapacity.php
src/ItemVirtualMachine.php
tests/functional/Glpi/Asset/Capacity/HasVirtualMachineCapacity.php

Add virtual machines capacity

---

inc/relation.constant.php
install/migrations/update_10.0.x_to_11.0.0/form.php
install/mysql/glpi-empty.sql
src/Form/AnswersHandler/AnswersHandler.php
src/Form/Destination/AnswersSet_FormDestinationItem.php
src/Form/Destination/FormDestinationInterface.php
src/Form/Destination/FormDestinationTicket.php
src/Form/Destination/Form_FormDestination.php
src/Form/Form.php
tests/DbTestCase.php
tests/functional/Glpi/Form/AnswersHandler/AnswersHandler.php
tests/functional/Glpi/Form/Destination/FormDestinationTicket.php
tests/src/FormBuilder.php

Add the foundation for form destinations, which are items created when a form is submitted.
The UI will be coded in a second PR, for now the feature is only accessible throught the tests cases.

Forms: form destinations

---

CHANGELOG.md
ajax/dashboard.php
install/empty_data.php
install/migrations/update_10.0.x_to_11.0.0/configs.php
install/migrations/update_9.4.x_to_9.5.0/dashboards.php
js/modules/Dashboard/Dashboard.js
src/Ajax.php
src/Dashboard/FakeProvider.php
src/Dashboard/Grid.php
src/Dashboard/Provider.php
src/Dashboard/Widget.php
templates/components/form/fields_macros.html.twig
templates/pages/setup/general/preferences_setup.html.twig
tests/src/Command/TestUpdatedDataCommand.php

Add placeholder dashboard(s) which show some fake data for a more attractive default dashboard.

Placeholder dashboards

---

src/ContractCost.php

Seems like a bad copy/paste from the old TicketCost class.

Fix ContractCost init from last

---

src/CronTask.php
src/DBAL/QueryFunction.php
tests/functional/Glpi/DBAL/QueryFunction.php

This was done during the UI migration (#16648) but split into its own PR for easier reviewing.

Replace some hardcoded SQL function calls in CronTask

---

src/DomainRecord.php
src/DomainRecordType.php
src/Domain_Item.php

First pass through Domain class before UI work. UI migrations will be a separate PR after this.

Domain class review/cleanup

---

src/DropdownTranslation.php

First pass through DropdownTranslation class before UI work. UI migrations will be a separate PR after this.

dropdowntranslation cleanup/review

---

src/FieldUnicity.php

First pass through FieldUnicity class before UI work. UI migrations will be a separate PR after this.

fieldunicity review/cleanup

---

src/Features/DCBreadcrumb.php
src/PDU_Rack.php
tests/units/Glpi/Features/Dcbreadcrumb.php

Fix DB breadcrumbs for PDU placed aside a rack

---

js/flatpickr_buttons_plugin.js

Fix "save" date picker button when the input is empty

---

CHANGELOG.md
src/Knowbase.php
src/KnowbaseItem.php
src/KnowbaseItemTranslation.php
src/KnowbaseItem_Comment.php
src/KnowbaseItem_Item.php
src/KnowbaseItem_KnowbaseItemCategory.php
src/KnowbaseItem_Revision.php

First pass through KB classes before UI work. UI migrations will be a separate PR after this.

KB cleanup/review

---

CHANGELOG.md
src/Impact.php

First pass through Impact class before UI work. UI migrations will be a separate PR after this.

Impact cleanup/review

---

src/Features/Clonable.php
tests/DbTestCase.php
tests/functional/Calendar.php
tests/functional/Project.php

| Fixed tickets | !31888
Example with a project. When a project is created from a template and the template has a task whose name contains "'", this task is missing in the new project, generating these errors:
```
glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/src/DBmysql.php line 370
SQL: INSERT INTO `glpi_projecttasks` (`uuid`, `name`, `content`, `comment`, `entities_id`, `is_recursive`, `projects_id`, `projecttasks_id`, `plan_start_date`, `plan_end_date`, `real_start_date`, `real_end_date`, `planned_duration`, `effective_duration`, `projectstates_id`, `projecttasktypes_id`, `users_id`, `percent_done`, …
```

fix(clone): special character

---

js/modules/Form/GeolocationField.js
src/MapGeolocation.php

Move non-heredoc text of the JS required for the geolocation field to a script file and modernize some of the syntax.

Move inline map field JS to module

---

front/asset/asset.form.php

Fix generic asset creation form display

---

src/ObjectLock.php

| Fixed tickets | #####
Hello , 
When I check the checkbox who have the id alertMe, the listener is never trigger, 
To solve this I move the echo at the end of the function and i change the eventListener

Fix ObjectLock

---

js/form_editor_controller.js

Fixed an issue that would cause questions to disappears from a form (their sections id was modified to an invalid value by mistake).
I've also added a small try/catch guardrail before the form is submitted as we should stop the update process if any errors occurs to prevent data loss.

Forms: fix failed question update
