glpi-project/glpi

inc/based_config.php
js/dashboard.js
src/Dashboard/Grid.php

I've been notified that dashboard performances are not great on heavy GLPI databases and I'm looking for potential solutions.
Here are the potential fixes I've found so far:
1\) Duplicated AJAX request
I've found that `getCardsAjax` was being called twice when loading/refreshing a dashboard
2\) Restore browser cache
Browser cache has been broken since #9370 as `POST` request can't be cached.
At that time, I'd propose to revert to a `GET` request (#9548) but it wasn't possible due to the request size and no solution was found at the time
Is it possible to find a solution for this now ?
I've heard of a new `QUERY` request type that allow cached content of unlimited size but I couldn't find anything regarding browser support (it is quite recent) so it probably isn't usable yet.
The obvious …

Improve dashboards performances

---

front/logout.php
src/Session.php

Previous version of ```front/logout.php``` destroy ```$_SESSION``` on top of page.
In this context ```CAS::logout``` can work (need to check some variables from  ```$_SESSION```
| Fixed tickets | Maybe fix #12874

Fix logout session destroy

---

src/Change.php

Update to use checkEntity(true)

Fix canViewItem() for recursive Changes

---

src/Search.php
tests/functionnal/Search.php

| Fixed tickets | #13044
Sanitizer uses different entites for `<` and `>` since GLPI 10.0.

Fix < and > search operators

---

src/NotificationTemplate.php

If a notification template has no html content it will generate the following error in the logs.
glpiphplog.WARNING:   *** PHP Warning (2): Undefined variable $signature_text in src/NotificationTemplate.php at line 325

Fix signature_text

---

src/CommonITILTask.php
src/Entity.php
src/Features/PlanningEvent.php
src/ProjectTask.php
src/Reminder.php

Display in the tooltip of an event its origin: entity + ticket (or other) with its ID.
Example:
| Fixed tickets | !25061

feat(planning): display event origin

---

src/DbUtils.php
src/Migration.php

| Fixed tickets | Ref: https://forum.glpi-project.org/viewtopic.php?id=285200
User reported getting the following warning when viewing the Planning Recall notification recipients tab:
```
PHP Warning (2): preg_grep(): Unknown modifier '$' in /var/www/glpi/src/DbUtils.php at line 313
Uncaught Exception TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /var/www/glpi/src/DbUtils.php at line 314
```
I was able to recreate the issue and the fix seems to be passing the delimiter parameter to the `preg_quote` calls in `DBUtils`. The fixes in the `Migration` class are not for this specific issue but should still …

Fix escaping issue with preg_quote calls

---

src/Plugin.php
src/Search.php

Cleaning some removed plugins may take a really long time as `CronTask::unregister()` will indirectly remove each entry of related `CronTaskLog` in a separated SQL query (removal is done using `CommonDBTM::delete()`).
If a plugin has been removed without being uninstalled first, there are probably a lot of stale data in DB, so removing or not just those related to crontask would change that much the amount of stale data in the database.
I also updated rendering of `itemtypename` search option type to display the raw value when class is not found. It can happen whn some plugins are deactivated/deleted.

Do not force plugin cron unregister on plugin clean

---

src/CommonGLPI.php
templates/components/itilobject/actors/field.html.twig
templates/components/itilobject/fields_panel.html.twig
templates/components/itilobject/selfservice.html.twig

restore input (in the case where a mandatory field is not filled in, for example) is broken.
```input``` is always empty when the page reloads.
It appears that ```saveInput()``` is called two times : 
- ```prepareInputForAdd($input)```  (seems legitimate)
- ```showTabsContent($options = [])``` from ```CommonGLPI``` 
From  ```CommonGLPI``` step,  ```$options``` saved by ```saveInput()```is always set like this 
```
Array
(
[id] => 0
)
```
:warning:  This change does not fix the problem with images that are not restored.
I dont know how to deal with it 

fix(core): prevent double saveInput

---

src/Search.php

When using metacriteria in a search, the title of some columns was wrong. _The data was OK_
Before:
After:
| Fixed tickets | !25240

fix(search): column name with metacriteria

---

composer.lock

Update inventory format lib
to use 
https://github.com/glpi-project/inventory_format/releases/tag/1.1.21
usefull for OS boot time date conversion
https://github.com/glpi-project/inventory_format/pull/82

Update inventory format lib

---

ajax/itilfollowup.php
templates/components/itilobject/timeline/form_followup.html.twig

If ```SELECT``` contain more than one ```options``` and if remotly sourced (AJAX)
When user choose a ```request template```, ```request type``` is not selected
Need to programmatically add new option with same ```id``` and ```text```

fix(requesttype): fix request type not selected when more than one

---

ajax/task.php
templates/components/itilobject/timeline/form_task.html.twig

If ```SELECT``` contain more than one ```options``` and if remotly sourced (AJAX)
When user choose a ```task template```, ```task type``` is not selected
Need to programmatically add new option with same ```id``` and ```text```

fix(taskcategorie): fix task type not selected when more than one

---

ajax/dropdownValidator.php
src/CommonITILValidation.php
templates/components/itilobject/fields/global_validation.html.twig

Extends #12504 
This PR allows the requester to create a validation request based on already defined requesters in the form.
Adding / removing requesters triggers a full page refresh, then the approbators dropdown is always up to date with requesters list.
Also fix a PHP warning
| Fixed tickets | internal 23396

set requester's supervisor as approbator on ticket creation

---

src/MassiveAction.php

Check if user can CREATE item to allow Clone massive action.
| Fixed tickets | #13105

fix(massiveaction) Show action Clone only if can CREATE

---

src/Inventory/Asset/MainAsset.php
src/Inventory/Conf.php
tests/functionnal/Glpi/Inventory/Assets/Computer.php

Add new option to avoid the change of ```states_id``` (when is set manually before inventory)

feat(inventory): add new option to not change asset states

---

src/NetworkPortMetrics.php

| Fixed tickets | #13092
Port error metric should not be treated like a number of bytes, it is the number of packets with errors.

Fix port error metric graph

---

src/RuleCommonITILObject.php

Add date field (Opening Date) to the rule BR criteria matching (I could imagine using this for simple round-robin assignment based on seconds)

Add Opening Date to Common BR Criteria

---

src/DBmysql.php

Sometimes, the `insertId` function returned 0 even though the record had been added to the database.
_Case with the `alert` plugin, whose ID column is in AUTO_INCREMENT (as it should be)._
| Fixed tickets | !25385

fix(core): insertId return 0

---

js/fileupload.js

| Fixed tickets | #12849
When pasting an image from MS Word or LibreOffice Writer, the images were being inserted with one of two formats for their source attributes (Seemed random which it was):
1. A `file://` URI pointing to the image in a temporary directory
2. A `blob:` URI that seemed to point to a broken image
Local file access is not allowed in at least Chrome and Firefox for security reasons. However, the raw clipboard data has 3 different data sources (plain text, HTML, and RTF). TinyMCE only uses HTML or plain text but the RTF source has the binary image contents in hexadecimal. We can extract that data and replace the broken image …

Improve image pasting from MS Word

---

src/Ticket.php

Fix input check.
```!isset($input['_contracts_id'])```  return always ```false``` because ```$input['_contracts_id']``` alays exist with ```0``` value
| Fixed tickets | !25407

fix(contract): fix input check

---

CHANGELOG.md
ajax/dropdownMassiveActionField.php
install/migrations/update_0.90.x_to_9.1.0.php
src/Api/API.php
src/CommonDBTM.php
src/Dashboard/Provider.php
src/DisplayPreference.php
src/DropdownTranslation.php
src/ITILTemplate.php
src/ITILTemplatePredefinedField.php
src/Lock.php
src/Lockedfield.php
src/Log.php
src/MassiveAction.php
src/Search.php
src/Search/Output/ExportSearchOutput.php
src/Search/Output/PDFSearchOutput.php
src/Search/Provider/SQLProvider.php
src/Search/SearchOption.php
tools/getsearchoptions.php

| Fixed tickets | - 
This also replaces calls to `Search::getOptions` with new `SearchOption::getOptionsByItemtype`.

Remove return by reference for getOptionsByItemtype

---

composer.json
composer.lock

Forcing PHP `8.0.0` in composer platform overrides prevent dependabot to propose some new versions of our dependencies. For instance, `symfony` 6.x requires PHP `>= 8.0.2` (see https://github.com/symfony/symfony/pull/41282).
Forcing version to `8.0.99` will permit to still ensure that composer checks requirement against a `8.0.x` version.

Update PHP version override in composer.json

---

src/User.php

User::getFriendlyNameFields() may fail if used in a SQL query where the column **name** is used in other tables.
Other columns are qualified with table name, then **name** should be also properly qualified.

more resilient query expression for user name

---

src/CommonDBTM.php
src/Domain.php
src/Link.php
tests/functionnal/Link.php

Signature change was introducing a BC-break resulting in a fatal error on some plugins, e.g.
```
PHP Compile Error (64): Declaration of PluginOcsinventoryngTeamviewer::generateLinkContents($link, CommonDBTM $item) must be compatible with CommonDBTM::generateLinkContents($link, CommonDBTM $item, bool $safe_url = true) in /var/www/glpi/marketplace/ocsinventoryng/inc/teamviewer.class.php at line 326
```

Rollback CommonDBTM::generateLinkContents() signature change

---

src/Inventory/Asset/Battery.php
src/Inventory/Asset/HardDrive.php
tests/functionnal/Glpi/Inventory/Assets/Battery.php

Prevent PHP warning
```shell
[2022-11-04 11:55:05] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "capacity" in /home/stanislas/TECLIB/DEV/GLPI/10.0-bugfixes/src/Inventory/Asset/Device.php at line 143
Backtrace :
src/Inventory/Asset/Drive.php:121                  Glpi\Inventory\Asset\Device->handle()
src/Inventory/Asset/MainAsset.php:862              Glpi\Inventory\Asset\Drive->handle()
src/Inventory/Asset/MainAsset.php:782              Glpi\Inventory\Asset\MainAsset->handleAssets()
src/RuleImportAsset.php:950                        Glpi\Inventory\Asset\MainAsset->rulepassed()
src/Rule.php:1522                                  RuleImportAsset->executeActions()
src/RuleCollection.php:1591                        Rule->process()
src/Inventory/Asset/MainAsset.php:564 …
```

fix(inventory): default value if value not exist in inventory

---

src/Item_OperatingSystem.php

| Fixed tickets | Ref https://forum.glpi-project.org/viewtopic.php?id=285282
The delete button was showing in the OS tab of an item even if the user didn't have permission to update that item.

Fix display of OS tab delete button

---

src/Search/SearchOption.php

In all cases except when a search option has specific search types, the Is Empty option is last. In that one different case, it is first which makes it the default which may not be very intuitive. For example, Ticket title defaulting to is empty instead of contains.

Move Is Empty search option to end of list

---

src/Inventory/Inventory.php

Prevent this warning when ```checkUnicity``` try to add ```Event``` from inventory session without (```$_SESSION["glpiname"]```)
```shell
[2022-11-04 14:42:56] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "glpiname" in /home/stanislas/TECLIB/DEV/GLPI/10.0-bugfixes/src/CommonDBTM.php at line 4522
Backtrace :
src/CommonDBTM.php:1601                            CommonDBTM->checkUnicity()
src/Inventory/Asset/MainAsset.php:779              CommonDBTM->update()
src/RuleImportAsset.php:950                        Glpi\Inventory\Asset\MainAsset->rulepassed()
src/Rule.php:1510                                  RuleImportAsset->executeActions()
src/RuleCollection.php:1591                        Rule->process()
src/Inventory/Asset/MainAsset.php:564 …
```

fix(inventory): prevent php warning when check unicity add event on uplicate

---

src/Dashboard/Widget.php

Before:
Two issues:
* Labels on the Y abscissa are truncated -> fixed by limiting the number of decimals
* Main graph label overlapping with the X abscissa labels. Weird because I don't see it happening in the images from my previous PR on a similar subject (#12529) -> fixed with some padding
After:
| Fixed tickets | !25485

Dashboards: fix labels overlaps

---

src/Planning.php
src/User.php

English is not a gendered language, so defaulting to using "his" when referring to an object or unknown person is not valid.

Remove invalid gendered language

---

src/Search.php

| Fixed tickets | #12994
Simplified interface profiles don't usually have access to dashboards, but the mini ticket dashboard still tries to load. Even though it seems to fail, the loading animations and other initial elements seem to stay present.

Do not try loading mini ticket dashboard for simplified interface

---

src/Socket.php

It would be meaningfull to show socket name instead socket ID in the Assets -> Computer Table

show-socket-name-instead-of-socket-ID-in-Assets->computer-Table

---

src/CommonGLPI.php

Fix RedirectList from CommonDBChild class
When use 
from 
CommonDBChild class, we are redirected to non existant pages
Examples : /front/computerantivirus.php, /front/item_disk.php & from pplugins too
Other problem (not fixed here) - from front/apiclient.form.php?id=1
-> try to redirect to http://localhost/glpi/front/apiclient.php?sort%5B0%5D=0&order%5B0%5D=ASC&criteria%5B0%5D%5Bfield%5D=view&criteria%5B0%5D%5Blink%5D=contains&criteria%5B0%5D%5Bvalue%5D=

Fix RedirectList from CommonDBChild class

---

src/Inventory/Asset/InventoryAsset.php

Actually native inventory try to load ```locked field``` for current handled item (```Computer``` or ```Peripheral``` or other)
But ```items_id``` is always the main asset ```ID```.
in certain circumstances some SQL error appears
```shell
SQL: UPDATE `glpi_peripherals` SET `manufacturers_id` = 'Realtek Semiconductor Corp.' WHERE `id` = '13886'
Error: Incorrect integer value: 'Realtek Semiconductor Corp.' for column `sicoval`.`glpi_peripherals`.`manufacturers_id` at row 1
```
Circumstance in my case : 
- A ```Computer``` with ```ID``` = 3297
- A ```Peripheral``` in trash bin with  ```ID``` = 3297 (and with``` manufacturers_id``` as ```locked field```)
the right ```Peripheral``` attached to ```Computer``` thrown SQL error because GLPI try to load ```locked field``` from "Peripheral" and ID …

fix(lockedfield): load right locked field siwtch itemtype

---

src/User.php

Sanitizer::unsanitize($filter) is not handled properly as it contains "& " at the begin of string and isHtmlEncoded in that case returns false so Sanitizer::unsanitize() does nothing. Either above lines should be written as ``$filter = "(&#38; `` or as proposed just group_condition should be unsanitized as propsoed in PR only this field probably could contain sanitized characters (I believe)...

Fix LDAP filter Sanitizer in ldap_get_user_groups

---

src/Document_Item.php
src/NotificationTemplateTranslation.php

In notification template translation, we can insert images in rich text, but images were not uploaded.
| Fixed tickets | !25497

fix(notification template translation): images not uploaded

---

src/Features/ParentStatus.php
src/PendingReasonCron.php

When pending reason create the first follow-up, pending status was lost and other follow-ups were not sent.
| Fixed tickets | !25499

fix(ticket): pending reason lost status

---

templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/form_task.html.twig

When updating a follow-up with a pending reason, the waiting status was removed.
This PR adds the toggling of the reason for waiting as to add (https://github.com/glpi-project/glpi/pull/12684)
| Fixed tickets | !25488

feat(ticket): remove pending status from follow-up/task update

---

src/CommonDBTM.php
tests/functionnal/CommonDBTM.php
tests/functionnal/Notification_NotificationTemplate.php

Update canPurgeItem() canUpdateItem() canDeleteItem() to call $this->checkEntity(true) by default, so count with recursive objects entity by default.
This is to allow recursive ITIL Objects to work (Changes, Problems), so all these rights are checked for active entity not on items entity, if item is recursive. 

Update can*Item checks to count with recursive items

---

templates/components/itilobject/fields_panel.html.twig
tests/bootstrap.php

Given the 3 following entities;
The location dropdown does not restrict the values correctly:
After fix:
| Fixed tickets | !25523

CommonITIL: restrict location dropdown to correct entity

---

.tx/config

After November 30, old Transifex Python client will no longer work as Transifex API 2.0 and 2.5 will not be available anymore.
To install the new client, remove the previously installed client, then run ``cd /usr/local/bin/ && curl --silent --location https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash``.
I just run the `tx migrate` command to get the config file updated, then tested to push/pull to confirm it works.

Migrate transifex config for new client

---

src/RuleCommonITILObject.php
src/RuleCriteria.php
tests/functionnal/Rule.php
tests/functionnal/RuleCommonITILObject.php

Add action to match on ```completename``` for :
- ```category```
- ```group assign```
- ```group observer```
- ```group requester```
| Fixed tickets | !23131

feat(rule): add action matching completename

---

src/Notification.php

The 'Allow response' field was added in GLPI 9.5 but the relevant search option was missing.
Having this search option is useful as it allow to edit it through massive actions.

Search notification by 'Allow response' field

---

CHANGELOG.md
src/DBmysqlIterator.php
src/QueryFunction.php
src/QuerySubQuery.php
src/Search.php
src/Search/Provider/SQLProvider.php
src/Search/SearchOption.php
tests/functionnal/QueryFunction.php
tests/functionnal/Search.php
tests/units/DBmysqlIterator.php

Replace the use of a raw SQL query with the array format.
Having at least the joins and where parts of the search in array form is needed for the new API. The new API doesn't use the search engine and uses the new array format but it still needs to use some of the default cases in the Search for visibility restrictions.

Replace raw SQL in Search Engine

---

CHANGELOG.md
src/CommonDBTM.php
src/CommonITILObject.php
src/QueuedNotification.php
tests/functionnal/QueuedNotification.php

Every queued notification has probably a distinct content, even when it is related to same item/action/recipient than another queued notification. Deduplication logic could can lead to the loss of important information, and this is the reason it has been disabled a long time ago on Ticket items.
For the same reason, I think that notification deduplication logic should disabled on all items.

Remove notification deduplication logic

---

src/ITILFollowup.php
src/Ticket.php

Follow-up notifications were not always generated.
For example, when the ticket is already pending and a follow-up is added, it did not generate a notification.
| Fixed tickets | !25494
#13043

fix(ticket): notifications not send

---

css/standalone/dashboard.scss

While fixing #12884 this afternoon, i noticed the widget icons were very big and a scroll was needed to display the palette selection.
So i suggest to reduce a little the list of widgets icons:
**Before:**
**After:**

reduce widgets list to display better vertically

---

src/RuleLocation.php
tests/functionnal/RuleLocation.php

Correctly handle ```regex_result``` case from ```RuleLocation```
Prevent SQL error 
```
[2022-11-16 10:20:01] glpisqllog.ERROR: DBmysql::query() in /home/stanislas/DEV/GLPI/10.0-bugfixes/src/DBmysql.php line 370
SQL: UPDATE `glpi_computers` SET `locations_id` = 'sub' WHERE `id` = '2'
Error: Incorrect integer value: 'sub' for column `10bugfixes_ruless`.`glpi_computers`.`locations_id` at row 1
Backtrace :
src/DBmysql.php:1439                               
src/CommonDBTM.php:675                             DBmysql->update()
src/CommonDBTM.php:1678                            CommonDBTM->updateInDB()
src/Inventory/Asset/MainAsset.php:781              CommonDBTM->update()
src/RuleImportAsset.php:950                        Glpi\Inventory\Asset\MainAsset->rulepassed() …
```

fix(RuleLocation): correctly handle regex case

---

src/User.php

Drop unused sql query when user ldap sync

Optimize User LDAP Sync

---

src/Inventory/Asset/Memory.php
tests/functionnal/Glpi/Inventory/Assets/Memory.php

I suggest making memory names more descriptive by adding memory frequency to memory "designation", so `DDR4 - SODIMM` becomes `DDR4 - 2133 - SODIMM`.

idea(inventory): better memory naming

---

src/Search/Provider/SQLProvider.php

Recent changes break Formcreator unit tests.
- When a plugin hook generates an empty fragment of SQL query (SELECT, WHERE). Hooks often add SQL depending on the itemtype. If itemtype does not patches anything, then the function returns an empty string
example 
```php
function plugin_formcreator_addDefaultSelect($itemtype) {
switch ($itemtype) {
case PluginFormcreatorIssue::class:
return "`glpi_plugin_formcreator_issues`.`itemtype`, ";
}
return "";
}
```
- When a search is done with the meta value 'mygroups', it may be resolved into an empty array, later used un a SQL IN statement. The search engine should ignore the clause in most cases.
| …

Fix empty cases search

---

.github/workflows/audit_dependencies.yml

1. An issue will be created if `npm audit` found vulnerabilities, and another one will be created if `composer audit` found vulnerabilities.
2. Job will not fail anymore when vulnerabilities are found. As issue is created, there is no need to trigger failure to notify about vulnerabilities.
3. Job execution time is improved by working directly with locked files, removing the requirement of installing dependencies.
I tested the job using commit https://github.com/cedric-anne/glpi/commit/d479f850ae7da36e42acddcb282c05872d285611, result was creation of 2 issues (https://github.com/cedric-anne/glpi/issues/395 and …

Create issue when dependencies audit fails

---

.gitignore
vendor/.htaccess

It will protect only apache servers that allows usage of `.htaccess` files, but, according to https://telemetry.glpi-project.org/, it may represent a large majority of GLPI installations.

Protect vendor directory using .htaccess

---

install/migrations/update_10.0.5_to_10.0.6/rule.php

Fix rule migration introduced by https://github.com/glpi-project/glpi/pull/13183
Actually, all rule criteria are moved.
This PR prevent this behavior

fix(update): do not update criteria for all rule

---

src/CommonDBTM.php
tests/functionnal/Glpi/Inventory/Assets/Computer.php

Fix locked field from transfer
Do not add ```locked field``` when inventory use transfer behavior

Fix locked field from transfer

---

templates/components/itilobject/timeline/form_task.html.twig

Given the following task (note the planning information at the bottom):
Going into edition, planning information are hidden:
After clicking the "Plan this task" button, 2 out of 3 values are incorrect:
Fix: the date are shown directly in edition (no need to reclick the "Plan this task" button) and the correct values are displayed:
| Fixed tickets | #25423

Fix planned task edition

---

src/Search/Input/QueryBuilder.php
templates/components/search/query_builder/main.html.twig

Allow to not submit a form of search criterias.
Needed for Formcreator: https://github.com/pluginsGLPI/formcreator/pull/3087
An other branch is available (in my environment) for 10.0/bugfixes (due to refactor of search engine)

optional search submit button

---

src/CommonITILObject.php
src/ITILSolution.php

In business rules for tickets, actions to change status and add solution template can be used in same rules but are not compatible.
The status change is done before the solution is added, and therefore the solution fails, because the ticket is already resolved.
In this case (when the status is forced) adding the template should not compute the status again.
| Fixed tickets | !25009

fix(ticket rule): action status + solution template

---

src/AuthLDAP.php

Fix Notice error on LDAP sync with active directory because this error create 20MB of log in phplog file

Prevent PHP notices when LDAP does not provide "modifytimestamp" field

---

src/CommonGLPI.php

When a ticket submission fails (e.g. missing mandatory fields), the user submitted data is lost (ticket title, description, ...).
I've found that this is due to a code change from GLPI 9.5 to GLPI 10.0.
The ticket form may be reloaded from different actions:
- Failed submission (missing mandatory fields)
- Important data change (entity, category, requester, ...)
The backend handle the saved input differently for these two cases and thus must be able to differentiate them.
To do this, it rely on `$options`:
- Failed submission -> `$option` will be empty
- Data change -> `$options` will contain the form data written by the user
With this in mind, the backend only need to check if  `$option` is empty to do the right decision.
This was broken in GLPI 10 because `$options` is no longer empty …

CommonITIL: fix restore input on failed submission

---

src/Computer.php

Check ```is_dynamic``` from ```$this->input``` 
instead of ```$input['is_dynamic']``` which contain reloaded data from DB

fix(lock): check from ->input instead of $input

---

install/migrations/update_10.0.5_to_10.0.6/inventory.php
tests/functionnal/Glpi/Inventory/Assets/Computer.php

Prevent PHP warning about ```entities_id_default```
Initialize conf to ```0``` default
```shell
[2022-11-22 08:29:09] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "entities_id_default" in /home/stanislas/TECLIB/DEV/GLPI/10.0-bugfixes/src/Inventory/Conf.php at line 971
Backtrace :
src/Inventory/Asset/MainAsset.php:532              Glpi\Inventory\Conf->__get()
src/Inventory/Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
src/Inventory/Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
src/Agent/Communication/AbstractRequest.php:332 …
```

fix(inventory): prevent PHP warning for 'entities_id_default'

---

src/CommonDBTM.php
src/NotificationTemplateTranslation.php
src/Toolbox.php

A link was systematically added on the images in the templates
Before:
After:
| Fixed tickets | !25497

fix(notification template translation): link was added on images

---

src/Lock.php

Prevent PHP error when trying to get ```ìtemtype``` ```items_id``` from locked field
```shell
[2022-11-22 09:44:18] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class "itemtype" not found in /home/TECLIB/DEV/GLPI/10.0-bugfixes/src/Lock.php at line 227
Backtrace :
src/Lock.php:804                                   Lock::showForItem()
src/CommonGLPI.php:689                             Lock::displayTabContentForItem()
ajax/common.tabs.php:116                           CommonGLPI::displayStandardTab()
```
Declaration of ```CommonDBRelation``` sides are sometimes reversed
Item_Software have
```php
$itemtype_1 = 'itemtype';
$items_id_1 = 'items_id';
$itemtype_2 = 'SoftwareVersion';
$items_id_2 = 'softwareversions_id';
```
Item_OperatingSystem have
```php
$itemtype_1 = 'OperatingSystem'; …
```

fix(lock): check itemtype / items_id before load locked field

---

src/Lock.php

From ```CommonDBTM``` object (```Monitor```, ```DatabaseInstance```)
GLPI load all object without restrict scope
```sql
SELECT  `glpi_lockedfields`.*
FROM `glpi_lockedfields`
LEFT JOIN `glpi_monitors`
ON (`glpi_lockedfields`.`items_id` = `glpi_monitors`.`id`)
WHERE ((`glpi_lockedfields`.`itemtype` = 'Monitor' AND `glpi_lockedfields`.`items_id` = glpi_monitors.id) OR (`glpi_lockedfields`.`itemtype` = 'Monitor' AND `glpi_lockedfields`.`is_global` = '1')))
```
This PR fix this by adding :
- ```LEFT JOIN``` with ```Computer_Item```
- ```WHERE``` on ```current item ID```
```sql
SELECT  `glpi_lockedfields`.*
FROM `glpi_lockedfields`
LEFT JOIN `glpi_monitors`
ON (`glpi_lockedfields`.`items_id` = `glpi_monitors`.`id`)
LEFT JOIN `glpi_computers_items`
ON (`glpi_computers_items`.`items_id` = …
```

fix(lockedfield): fix lockedfield load

---

install/empty_data.php
install/migrations/update_10.0.5_to_10.0.6/rule.php
install/migrations/update_9.5.x_to_10.0.0/native_inventory.php
src/Rules/RulesManager.php
src/Toolbox.php
src/Update.php

Using `initRules()` methods during update process may lead to issues in the future. Indeed, these methods are also used when reinitializing rules from rules admin UI and are expecting that database is up to date, and so calling them with a database not fully upgraded may cause failures, if database structure change in the future.
With proposed code, rules will be initialized after database migration, using the same logic that the one used in install process.

Initialize rules after DB migrations

---

src/RuleImportAsset.php

Removed hook call is invalid. Indeed, `ruleImportAsset_addGlobalCriteria` hook is call in `RuleImportAsset::getGlobalCriteria()` and current call is probably resulting in a bad copy/paste (maybe it something like `ruleImportAsset_addRules` should have been called instead).
I propose to remove this call. Fixing it does not seems valuable as noone asked for it.

Drop unexpected ruleImportAsset_addGlobalCriteria hook call

---

.github/ISSUE_TEMPLATE/bug_report.yml
CONTRIBUTING.md
SECURITY.md

Maybe adding a bold text with a :warning: would prevent some people to open public security issues.

Try to avoid public security issues

---

templates/components/itilobject/timeline/main_description.html.twig
templates/components/itilobject/timeline/timeline.html.twig

When copy/pasting content from the ticket timeline, some unwanted css is inserted into the editor: 
Generated HTML:
This is caused by an incorrect use of `span`.
| Fixed tickets | !25593

Fix copy/pasting content from Ticket description

---

src/Search/Provider/SQLProvider.php

SQLProvider breaks hook addDefaultSelect because plugins must add a final comma to fields list to ensure proper concatenation with other fields in the search engine.
This PR removes the final coma, if found.

sqlprovider backward compatibility

---

templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/form_task.html.twig
templates/components/itilobject/timeline/form_validation.html.twig

The purge button was displayed in the follow-up edit form on serf-service profiles when they do not have this right.
| Fixed tickets | !25658

fix(ticket): purge button visible even without PURGE right

---

CHANGELOG.md
composer.json
composer.lock
src/Config.php

`php-intl` is a required dependency, so we can use `idn_to_ascii` safely instead of using abandonned `true/punycode` package.

Drop unused true/punycode package

---

ajax/itilfollowup.php

| Fixed tickets | #13392
There is a partial failure in the AJAX request from trying to check entities_id field for request types when they do not have an entity field. In debug mode, it returns the SQL error as part of the JSON payload which breaks the loading of data from templates completely. When not in debug mode, it just doesn't load the request source information.

Fix followup template use

---

src/Inventory/Asset/Software.php
tests/functionnal/Glpi/Inventory/Assets/Software.php

Alternative to https://github.com/glpi-project/glpi/pull/13387
use ```sha1``` instead of ```Toolbox::slugify($string)``` that does not manage the language well 
like ```ភាសាខ្មែរ កញ្ចប់បទពិសោធន៍ផ្ទៃក្នុង```

fix(software): use sha1 instaed of slugify to build comparison key

---

composer.lock
tests/functionnal/Glpi/Inventory/Assets/NetworkEquipment.php

Bump ```inventory_format``` to correctly handle ```sysdescr``` for ```NetworkEquipment``` 
| Fixed tickets | #13382

Bump inventory format sysdescr

---

install/migrations/update_10.0.5_to_10.0.6/inventory.php

```entities_id_default``` is always reset to ```0``` when an update is processed.
use dedicated function.

fix(udpate): fix inventory conf always reset

---

install/migrations/update_9.5.1_to_9.5.2.php
src/Document_Item.php

| Fixed tickets | #13341
Migration to `9.5.2` was using the `CommonDBTM::add()` method to add `Document_Item` elements. Problem is that it triggers some routines that are not expected to be run in the middle of a migration, and that are, therefore, not able to handle this case.
We already had to fix an unexpected behaviour in #9018 and to use `_disablenotif` to ensure that no notification are sent, but #13341 reveals that the only solution is to use direct DB queries.

Fix KB related documents migration

---

js/impact.js

Add some spacing between icons and text in the Impact graph context menu.

Add space between icons and text in impact context menu items

---

inc/define.php
install/migrations/update_10.0.x_to_10.1.0/changesatisfactions.php
install/mysql/glpi-empty.sql
src/Change.php
src/ChangeSatisfaction.php
src/CommonITILSatisfaction.php
src/Search/Provider/SQLProvider.php
src/Stat.php
src/Ticket.php
src/TicketSatisfaction.php

A few issues on the satisfaction search options :
* It's missing from changes
* It does not show values above 5 stars (we can go to 10 with the new config)
* It disappears when reloading the search results
1\)  It's missing from changes
-> Added it to changes. 
They don't share the same searchoptions id as the original ids are sadly not available for changes.
Instead they match the ticket's ids + 200 (kinda hacky - any plan to drop number based search options ids in the future ?).
2\) It does not show values above 5 stars (we can go to 10 with the new config)
-> Rewrote `displaySatisfaction` to take into account entity config
3\) It disappears when reloading the search results
-> Rewrote `displaySatisfaction` to use javascript to trigger the rateit library.
The previous method (relying on …

Fix satisfaction search options

---

src/Update.php
tests/functionnal/Update.php

| Fixed tickets | see #13338
Initially made on #10780.
When a migration is done, `version` is stored in database only at the end of the process, so if a migration that contains many steps fails, launching the update process will try to re-run the whole migration, including already completed steps.
Our migrations are almost always replayable when you try to re-run a step that has previously failed, but they cannot handle the fact that a step for a future version has already been completed. Storing the corresponding `version` value after each step completion will make the migration restart aftr the latest completed step.
#13338 show multiple …

Save migration progress when it includes multiple versions

---

src/User.php
tests/functionnal/User.php

The behavior of the `ADDDATE` function in MySQL when the second argument doesn't start with `INTERVAL` is to treat it like a number of days. The `password_init_token_delay` config value however is stored as a number of seconds, not days.
Bug only affects main branch.

Fix password forget token validity

---

src/Change.php

error happened when the user has no update right on changes

fix php warning when user views a change 

---

templates/components/itilobject/timeline/form_validation.html.twig

When adding a validation to a change, the users dropdown is configured to filter users with ticket validation right (**validate_incident** or **validate_request**). A change validation supports only **validate** .
To reproduce
Create a blank profile, with standard interface. Give rights to access changes and change validation.
Create a new user and add it to the previous profile.
Create a change with GLPI, then try to add the new user as a validator of the change. The user is not available in the list.

fix bad right check on change validationn

---

src/Html.php

| Fixed tickets | #13422
Localize the month name for relative datetime strings.

Localize month name

---

src/Html.php

The calculation of the relative date was based on the time difference, which was not precise enough.
For example, it is the 29th at 10am and the item is dated the 27th at 5pm. It shows "Yesterday" when it should be "2 days ago".
Same case with the number of weeks, if the event is 8 days old, we would display "2 weeks ago" when "1 week ago" is more accurate.
| Fixed tickets | !25712

fix: improvement of relative date calculation

---

src/KnowbaseItem.php

All articles were listed in the root category and not only those without category.
The counter was already good.
| Fixed tickets | #13336

fix(knowbase): root category show all articles

---

src/Api/APIRest.php

It seems like before 9.5, it was possible to use a namespaced class with the API by using `%5C` (backslash). When the handling of deprecated itemtypes was added, the itemtype name was normalized using the short name rather than the full name as it was before.
This PR will always use the full class name, and then removes the `Glpi\Api\Deprecated` namespace prefix if needed. This even allows namespaced itemtypes to be deprecated. For example, if `Glpi\Event` gets deprecated, the deprecation class would be `Glpi\Api\Deprecated\Glpi\Event`.

Restore usability of NS classes in API

---

js/fileupload.js

When we create a new ticket and there are mandatory fields not filled in, when we validate the form, the page is reloaded, the ticket is not created (normal) but the images are broken :
| Fixed tickets | !25685

fix(ticket): image lost when mandatory field missing on submit

---

install/mysql/glpi-empty.sql

SET FOREIGN_KEY_CHECKS=1 should be at end of file

fix empty sql file

---

src/RichText/RichText.php

Stripping `http|https` protocol on autolink does not seems really usefull and can, in some case, be an unwanted behaviour. I propose to deactivate this behaviour.

Preserve URL protocol on autolink

---

src/MailCollector.php
tests/emails-tests/37-image-with-octet-stream-type.eml
tests/imap/MailCollector.php

| Fixed tickets | #13232
Some e-mail clients seems to use `Content-Type: application/octet-stream` for images embedded into email HTML contents. I propose to always fetch the mime type from the actual saved file.
We already rely on this when adding the document, see https://github.com/glpi-project/glpi/blob/10.0/bugfixes/src/Document.php#L1206-L1207

Fix handling of application/octet-stream images in emails

---

.github/dependabot.yml

Almost everytime a dependabot PR is merged, dependabot rebases all other PR to fix potential conflicts. It fills the CI queue and rerun many times the test suite for the same PR.
I propose to disable this auto-rebase. We will just have to add 2 comments when we are ready to merge a PR: `@dependabot rebase` then `@dependabot merge`. By doing this, dependabot will rebase the PR and merge it once CI will have pass.

Disable dependabot auto rebase

---

src/Config.php
src/Entity.php
src/NotificationEventMailing.php
src/NotificationMailingSetting.php
tests/functionnal/NotificationEventMailing.php

1. Entity administrator target was not using inheritence logic.
2. `getEmailSenderFromEntityOrConfig` was silently ignoring invalid email values, so, in some cases, people were not receiving notifications to administrator without understanding why. Adding an entry in logs may help to identify misconfigured addresses.

Fix administrator targets

---

src/Rules/RulesManager.php

Will prevent following fatal error when stored value is not a valid JSON array:
```
Uncaught Exception TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /var/www/html/glpi/10.1.git/src/Rules/RulesManager.php at line 68
```

Handle missing/corrupted "initialized_rules_collections" config

---

src/Item_Disk.php

Fix this warning for the "Volumes - Encryption status" search option.
This warning appears if computers have no defined volumes (and the search option is active).
> [2022-11-30 17:33:06] glpiphplog.WARNING:   *** PHP User Warning (512): Encryption status  does not exists! in /var/www/html/glpi/src/Item_Disk.php at line 588
Backtrace :
src/Item_Disk.php:588                              trigger_error()
src/Item_Disk.php:665                              Item_Disk::getEncryptionStatus()
src/Search.php:7528                                Item_Disk::getSpecificValueToDisplay()
src/Search.php:1690                                Search::giveItem()
src/Search.php:447                                 Search::constructData()
ajax/search.php:79                                 Search::getDatas()
| Q …

Fix encryption warning

---

src/KnowbaseItem.php
src/RichText/RichText.php

When viewing a long KB article, the article is cut off by a read more button that you need to click to show the rest of the text. Given that the full text is already all loaded at once, and the article is the only content in the main form, it should be OK to always show the full content.
Ref: https://forum.glpi-project.org/viewtopic.php?id=285616

Show full KB article at once

---

install/migrations/update_10.0.0_to_10.0.1/fixaction.php
install/migrations/update_10.0.5_to_10.0.6/rule.php

| Fixed tickets | #13295 
Previous migration pattern `/(.*)[,|\\/]/` was interpreted as `/(.*)[,|/]/` on MySQL side.
Technical explaination:
1. `$var = '\\/';` creates a variable `$var` that contains `\/` string. Indeed the first backslash is here considered as an escape char for the second backslash.
2. `'\/'` in a MySQL query values is interpreted as a `/` values, as the backslash is considered as considered as an escape char for the slash.
`$var = $DB->escape('/(.*)[,|\/]/')` is equivalent to `$var = '/(.*)[,|\\\\/]/'`.

Fix 'contact' rule criteria migration

---

src/DBmysqlIterator.php
src/Search/Provider/SQLProvider.php

Fixes parsing of join strings to handle table aliases and also gets the full join condition and coverts it to a QueryExpression instead of trying to parse it. Support for QueryExpression join conditions was added to the iterator.

Fix analysis of raw plugin joins

---

src/Agent.php
tests/functionnal/Agent.php

The ```RuleMatchedLog``` class contains code to display data from an ```Agent```
https://github.com/glpi-project/glpi/blob/94445120413835b2421af54d91d5c44c9f21d2a3/src/RuleMatchedLog.php#L286-L297
Add missing tab from ```Agent```
Useful to see what the agent brings up.

fix(RuleMatchLog): add missing tab from Agent

---

.github/workflows/bump_version_after_release.yml
src/System/Requirement/InstallationNotOverriden.php
tests/units/Glpi/System/Requirement/InstallationNotOverriden.php
tools/build_glpi.sh

See #13553.
When an administrator updates the GLPI code base using a file manager, during the step `Ensure the target directory is empty and extract files there.`, he browses the GLPI directory, selects all files and directories and deletes them. The problem is that in many cases file managers do not show hidden files by default, and therefore the `.version` directory will not be selectable and therefore will not be deleted.
Although this check is only performed on users who try the nightly build (the check was not present in the previous version), this is not the first user to experience this problem. IMHO many people use …

Prevent version files directory to be hidden in file managers

---

src/Search/Provider/SQLProvider.php

This PR should address backward compatibility with hooks still using plain text SQL fragments, while allowing plugins to use modern style

fix plain SQL from plugins handling

---

src/NetworkPort.php
tests/functionnal/Glpi/Inventory/Inventory.php

Actually, when we add a ```NetworkPort``` to a ```Computer``` (manually or from inventory)
GLPI does not log the information of the addition
Fix : https://github.com/glpi-project/glpi/issues/10604#issuecomment-1081642373

fix(networkport): add history on add NetworkPort

---

front/reservation.form.php

| Fixed tickets | #13536
Reservation `group` should only create when there is more than 1 date added at once.

Fix reservation repetition group value

---

src/Ticket.php

While working on another pull request for !23972, I thought I was going to need to edit the `Ticket::canViewItem()` method.
The original code with the big condition was a bit hard to read so I decided to split it into multiple parts.
In the end, I won't need to modify this method but I'm submitting the reorganized version so it can still be merged (if you agree that's it's easier to read 😉).

Reorganize Ticket::canViewItem()

---

templates/generic_show_form.html.twig

When editing a template, the name of the template (field: `template_name`) was not proposed and therefore not modifiable.
| Fixed tickets | !25758

fix(licence template): template name not editable

---

src/Features/Clonable.php
tests/functionnal/Project.php

If we have a project template with 2 tasks: A and B (B is a child of A).
When creating a project from this template, the father of task B' was task A of the template instead of task A' of the new project.
| Fixed tickets | !25528

fix(clone): relation ID not updated between cloned sub items

---

js/common.js
src/MapGeolocation.php

If you disable this setting on firefox (about:config), the "Location on map" fields doesn't work anymore.
| Fixed tickets | !25816

Fix "Location on map" when geo.enabled is disabled on firefox

---

src/Lock.php

From the "Locks" tab of a monitor, I can see the computer locked fields AND the locked fields of items linked to the computer:
@stonebuzz tell me that this is done on purpose (to make it easier to browse all locked fields from the parent computer) so no issues at this point.
However, the linked fields are still shown even if the relation is deleted:
They should be hidden in the case (the fields are irrelevant because the items are no longer linked).
| Fixed tickets | !25474

Hide locked fields for deleted relation

---

composer.lock
src/Console/AbstractCommand.php
src/Console/Migration/DynamicRowFormatCommand.php
src/Console/Migration/MyIsamToInnoDbCommand.php
src/Console/Migration/TimestampsCommand.php
src/Console/Migration/UnsignedKeysCommand.php
src/Console/Migration/Utf8mb4Command.php

1. Add a message to warn about migration execution time.
2. Always display currently migrated table/column next to progress bar. User will so be able to see more information about migration progress without having to use the `verbose` mode. Thus, only errors remains in command output, so it is easier to find valuable information in command output, even in verbose mode (see second image).

Enhance progress bars on migration commands

---

src/ReservationItem.php

| Tests pass?   | ?
| Fixed tickets | #GH-13548
This PR aims to fix #GH-13548 by simply changing the comparison operators used when comparing date range endpoints of existing reservations .

Fix reservations date range endpoints comparison in "free period search tool"

---

install/migrations/update_10.0.5_to_10.0.6/blacklist.php
src/Blacklist.php
src/Inventory/Asset/NetworkEquipment.php
tests/functionnal/Blacklist.php
tests/functionnal/Glpi/Inventory/Assets/Printer.php

Alternative to https://github.com/glpi-project/glpi/pull/13591
Exclude ```0.0.0.0``` from ``` management port```
| Fixed tickets | https://github.com/glpi-project/glpi/issues/13523#issuecomment-1347896226

fix(inventory): exclude 0.0.0.0 from management port

---

js/modules/SearchTokenizer/SearchInput.js

| Fixed tickets | #13593
Token data attribute was lost after handling term transformation from the autocomplete data which broke any Kanban filter that used auto-suggested terms (like the types for Project Kanban).
This PR also adds a check to prevent trying to transform empty input into a tag which could trigger unnecessary tokenization and result change checks.

Fix lost token info after autocomplete transform

---

ajax/savedsearch.php
js/modules/Search/GenericView.js
src/SavedSearch.php

| Fixed tickets | #13425
Modal loading was using a POST request but with all parameters located in URL query string. I moved parameters into POST body to prevent issues with URL length limits.

Fix saved search creation form when many criteria are used

---

src/Auth.php

Accounts from mail servers shows "LDAP directory: " under the authentication info block in their form instead of "Mail server: ".

Fix auth label for mail accounts

---

src/Session.php

When selecting the active entities, the title is the same if you display all or the 1st entity in tree structure.
Example with this structure:
If we choose "select all" or "entity1" in recursive, we display `Root entity > entity1 (tree structure)` 
Before (both case):
After ("select all" case):
After ("entity1" case):
| Fixed tickets | !25861

enhance the entity name when selecting all

---

src/Dashboard/Provider.php
tests/functionnal/Glpi/Dashboard/Provider.php

This widget:
Is not taking into account visibility criteria defined for the reminders.
| Fixed tickets | !25922

Dashboards: fix reminders visibility

---

css/includes/components/itilobject/_footer.scss
inc/define.php
install/empty_data.php
install/migrations/update_10.0.5_to_10.0.6/configs.php
install/mysql/glpi-empty.sql
src/CommonITILObject.php
src/Config.php
templates/components/itilobject/footer.html.twig
templates/components/itilobject/timeline/filter_timeline.html.twig

Add user pref option to split or not timeline action button.
Standard layout (```merged```)
New layout (```splitted```)
NB : do not hide buttons when form (```task```, ```followup```, ```solution``` ... ) are open

feat(timeline): add capability to change the layout of button

---

src/Html.php

| Fixed tickets | #13451
`common.js` is critical to load before the page content is fully loaded in case a user tries to interact with the page before it is done loading. In one case, when you try adding a search filter before the page is completely loaded, it hangs and then shows an access denied error within the search criteria box. Now, the filter is able to be added as soon as the button is visible.

Load common.js in header

---

src/Inventory/Asset/MainAsset.php
src/RuleImportAsset.php
tests/functionnal/RuleImportAsset.php

```TAG``` criterion can use ```PATTERN_FIND``` and ```PATTERN_IS_EMPTY```
But ```handleFieldsCriteria()``` does not manage this criterion.
This PR try to fix this.
| Fixed tickets | https://github.com/glpi-project/glpi-inventory-plugin/issues/256

fix(ruleimportasset): correctly handle condition for TAG criteria

---

src/Entity.php

| Fixed tickets | Related #13541
After creating a new entity, it is added to your active entitiies in the session variable as a workaround to prevent needing to log out and back in, but the multi-entity mode flag is not changed/enforced.

Enable multi-entity mode immediately after creating entity

---

src/Migration.php
tests/units/Migration.php

| Fixed tickets | #13076
During migration, if a search option is changed and if there is search options existing for both old and new SO key, an SQL error will be thrown and migration will be blocked.
This is an edge case than can happen:
- when multiple migrations are replayed (migration to v0.2 adds the old SO, migration to v0.3 change it to new SO, migration to v0.4 fails, then migration from v0.1 to v0.4 is replayed);
- when a specific patch or a plugin has previously defined in the past a SO that uses the key of the new SO.

Fix duplicate entry issues on migration

---

src/Inventory/Asset/InventoryNetworkPort.php
src/Inventory/Asset/Printer.php
tests/functionnal/Glpi/Inventory/Assets/Printer.php

Do not delete management port at each inventory
Because ```handleUpdate``` unset management network port after handle it (and ```handleDeletesManagementPorts``` thinks that there is no)
https://github.com/stonebuzz/glpi/blob/88d839ade9f0fc28c0fb6f51d252dd0ad78a0b9f/src/Inventory/Asset/InventoryNetworkPort.php#L370-L380
| Fixed tickets |https://github.com/glpi-project/glpi/issues/13609

fix(snmp): do not delete management port each time

---

src/Dropdown.php

When loading a task template with a user value, if the user is, for example, 20th in the list and the `Page size for dropdown (paging using scroll)` parameter is 10. The user's value was not changed.
| Fixed tickets | !25874

fix(task template): user missing when dropdown_max too small

---

src/DeviceBattery.php
src/DeviceGraphicCard.php
src/DeviceHardDrive.php
src/DeviceMemory.php
src/DeviceProcessor.php
src/DeviceSimcard.php
src/Item_DeviceGraphicCard.php
src/Item_DeviceHardDrive.php
src/Item_DeviceMemory.php
src/Item_DeviceProcessor.php
templates/components/form/item_device.html.twig

| Fixed tickets | partially #13633
Use `integer` search option `datatype` to be able to use `>` and `<` operators in search terms and `input type="number"` in form.

Better handling of numeric attributes of devices

---

src/CommonITILObject.php
src/NotificationTargetCommonITILObject.php
templates/components/itilobject/timeline/timeline.html.twig
tests/functionnal/Ticket.php

`getTimelineItems()` was returning entries with `type="Solution"` instead of entries with `type="ITILSolution"`. Result was that item passed to `pre|post_item_form` hooks was null, due to the fact that `get_item("Solution", XXX)` was not able to find the `Solution` class.

Fix ITILSolution timeline hooks

---

js/modules/Kanban/Kanban.js
src/Project.php

| Fixed tickets | #13651 
Deleted items shown in the Project Kanban were not showing a red background like they should have.

Fix styles for deleted Kanban items

---

composer.json
composer.lock

According to [release notes](https://github.com/tecnickcom/TCPDF/blob/main/CHANGELOG.TXT), some fixes were made for PHP 8.0/8.1. I propose to upgrade this package on 10.0/bugfixes.

Upgrade tecnickcom/tcpdf to ^6.6

---

src/Inventory/Asset/Device.php

Depending on existing data, some missing item devices may not be created.
It seems to me that the `equals` variable is not reseted correctly between iteration thus tagging some missing items as existing.
| Fixed tickets | #26029

Inventory: Fix item devices creation

---

src/Agent.php
src/Inventory/Conf.php
src/Plugin/Hooks.php
tests/functionnal/Agent.php

Partial backport of #12060.
It introduces a `stale_agent_config` hook that permit to a plugin to register more actions to execute when stale agents are found. See also https://github.com/pluginsGLPI/uninstall/pull/68 .

Add `stale_agent_config` hook

---

src/Appliance.php

Appliance are still displayed from search even if they are deleted (```is_deleted = 1```)
| Fixed tickets | !25244

fix(Appliance): do not display deleted appliance from search

---

.npmrc

On recent `npm` versions, installing dependencies triggers following error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: jquery.autogrow-textarea@0.4.1
npm ERR! Found: jquery@3.5.1
npm ERR! node_modules/jquery
npm ERR!   jquery@"^3.4.1" from the root project
npm ERR!   jquery@"^1.8 || 2 || 3" from gridstack@0.6.3
npm ERR!   node_modules/gridstack
npm ERR!     gridstack@"^0.6.0" from the root project
npm ERR!   7 more (jquery-migrate, jquery-prettytextdiff, jquery-ui, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer jquery@"2.x" from …
```

Fix peer dependencies resolution

---

.stylelintrc.js
css/legacy/includes/_styles.scss
js/Forms/FaIconSelector.js
src/ManualLink.php

`Font Awesome 5` font families are still valid, but I guess they will be removed someday.

Fix references to outdated FontAwesome version

---

src/NotificationTargetCronTask.php

Trying to add a translation to a notification on the "Automatic Action" itemtype will fail due to a case error on the class name:
| Fixed tickets | #26110

Fix adding translations on NotificationTargetCronTask

---

src/CommonITILObject.php
src/Ticket.php
tests/functionnal/Ticket.php

When cloning a ticket with tasks with durations, the created ticket had an automatic completed task, like this:
| Fixed tickets | !25928

fix(ticket): cloning, unexpected automatic task

---

templates/components/form/single-action.html.twig

The click event listeners for the single action menu were being used for an unrelated element that happened to have a "data-action" attribute (in a plugin). I added an ID to the dropdown and added it to the event listener selectors to avoid this issue.

Fix event binding for single action menu

---

src/Dropdown.php

Hi
Formcreator 2.14 contains a new feature which allows admins to define a filter for dropdowns, based on the search engine query builder. See https://github.com/pluginsGLPI/formcreator/pull/3087
I target to maintain compatibility of Formcreator 2.14 with GLPI 10.0 and 10.1, then this backports helps to provide the plugin's feature earlier.  Also it has been requested for years (and often) by customers and community.
```php
Computer::dropdown([
'condition' => [
'LEFT JOIN' => ...
'WHERE' => ...
]
]);
```

Backport joins dropdown filter

---

front/notification_notificationtemplate.form.php

404 error when you want to delete a template linked to a notification.
| Fixed tickets | !26091

fix(notification): 404 error after purge

---

src/RuleRightCollection.php

order rules rights by 'ranking' instead of 'name'
fixes #13666
| Fixed tickets | #13666

Rule Rights : fix order

---

src/Console/Ldap/SynchronizeUsersCommand.php

Currently during a synchronization of several directories, if one of them is in error, the script stops immediately: preventing the following servers from being synchronized.

fix(ldap): do not exit processing servers on error

---

src/Search.php

| Fixed tickets | #13731
Restore rendering behaviours of multiline plaintext, see https://github.com/glpi-project/glpi/blob/759597943b4bbc40e05b25b5645b5caa5f04e6c4/inc/search.class.php#L6349-L6354

Fix rendering of multiline plain text

---

src/CleanSoftwareCron.php

In some cases, an uninstalled software version was not deleted, because the link between the item and this version remained in the trash bin.
| Fixed tickets | !25983

fix(cleansoftware): some versions were not deleted

---

src/Inventory/Request.php

Return error ```400``` ```Bad Request``` if ```JSON does not validate``` 

feat(inventroy): distinct error code switch error

---

front/tracking.injector.php
src/Html.php

It's possible for a self-service profile to have the right to create tickets but not see them.
If they also have the 'go to item on creation' setting enabled, creating a ticket will send them to this page:
Which is confusing and may make them think that their ticket wasn't created correctly.
I've handled this case and hidden the 'tickets' menu if the user can't see them (current conditions to display it were a bit weird)
PS: I know its a cursed usecase, you can check the internal ref for more details.
| Fixed tickets | !26007

Self-service: better handling of users that can't see tickets

---

front/document.send.php

Inventory file download response had a one week duration `Expires` header, meaning that if it was already downloaded within last 7 days, browsers would not even try to contact server if user tries to download it again.
As file is subject to change quiet often and has a constant path, such header should not be added.

Remove cache headers on inventory files

---

src/Html.php
src/ProblemTemplate.php
tests/functionnal/ITILTemplate.php

Add the 3 following fields to problems' templates:
This allow the users to mark them as mandatory.
While testing the mandatory feature, I've noticed that the error message always mention the description field no matter what:
I've fixed it by making it use the closest label instead:
| Fixed tickets | !26099

Support more fields in problems template and fix mandatory field alert

---

ajax/projecttask.php
src/Application/View/Extension/DataHelpersExtension.php
src/ProjectTask.php
templates/pages/tools/project_task.html.twig

Viewing projects' tasks from the "Your planning" widget of the  "Personal view" tab of the home page is broken:
It seems to be outdated table based html that isn't really responsive and can't deal with the smaller available width.
I've migrated it to twig to fix the issue.
After fix:
And here the before/after from the project task main tab:
| Fixed tickets | !26056

Twig template for projects' tasks

---

templates/components/form/item_device.html.twig

```MSIN``` tooltip is displayed for other fields
This PR fix that
| Fixed tickets | !26194

fix(simcard): display helper only when is needed

---

index.php

| Fixed tickets | #13758 
Allowed PHP version has been updated in `inc/define.php` but not in `index.php`.
https://github.com/glpi-project/glpi/blob/0046d6d6b5d7fc509ca139c62d4c2e65d2ce4d50/inc/define.php#L51-L52
We did not detect it earlier as we are probably all using a pre-release version (that is considered as less than `8.2.0`). Using `-dev` suffixes in comparison will prevent PHP 8.3 pre-releases to be accepted. Test will be similar to the test done in requirements checking:
https://github.com/glpi-project/glpi/blob/0046d6d6b5d7fc509ca139c62d4c2e65d2ce4d50/src/System/Requirement/PhpVersion.php#L79-L84
Note that checks has been …

Allow PHP 8.2

---

composer.json
tests/emails-tests/38-email-address-too-long.eml
tests/imap/MailCollector.php
tools/patches/laminas-mail-address-no-length-check.patch

| Fixed tickets | !24408
`laminas-mail` uses default strictness of `Laminas\Validator\EmailAddress` validator, that is checking that addresses are respecting the length limitation defined in RFC 3696.
Problem is that this limitation does not seems to be respected, even by Microsoft, that is sometimes generating far too long addresses in some cases.
Patch will prevent following error:
```
glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Exception\InvalidArgumentException: The input exceeds the allowed length in /var/www/glpi/vendor/laminas/laminas-mail/src/Address.php at line 74
Backtrace : …
```

Prevent collector to fail on address that contains unexpected chars length

---

css/includes/_base.scss
front/rule.common.php
src/Entity.php
src/Rule.php
src/RuleCollection.php

When you have a large number of rules, it sometimes takes a long time to have to go through them to find in which rule a particular criterion/action has been added.
This PR therefore makes it possible to display them in the list, thus making it possible to do a search (ctrl+f).
I don't know which branch is better (bug fixes or main).
Before
After
Perhaps an improvement: rather than having the display forced into the code, we could imagine two "toggle" buttons next to the "Actions" button (with persistent in-session choice).

feat(rules): display criterias/actions on list

---

src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php

| Fixed tickets | #13665
Before GLPI 10.0.0, `COLLATE` property was not explicitely defined for `glpi_notimportedemails`, and charset was not the same as other tables.
Depending on SQL server configuration, user may be informed of differences that will be anyway fixed by migration to GLPI 10.0.0, see https://github.com/glpi-project/glpi/blob/ef7cb5eef44be55373352d62e29864c873751d4a/install/migrations/update_9.5.x_to_10.0.0/schema_fixes.php#L72-L82
I propose to exclude CHARSET/COLLATE properties of `glpi_notimportedemails` in schema check when installed schema is < 10.0.

Prevent CHARSET/COLLATE unexpected diff on glpi_notimportedemails table

---

src/CommonITILObject.php
src/CommonITILTask.php
src/Features/ParentStatus.php
src/ITILFollowup.php
src/Ticket.php
templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/form_task.html.twig
tests/functionnal/PendingReason.class.php

It is currently impossible to add a pending reason to a pending ticket:
After changes:
Note that if the ticket is pending AND already have a pending reason, the input will still not be shown to avoid overriding the active pending reason.
| Fixed tickets | !26069

Allow to add pending reasons when item is already pending

---

templates/components/itilobject/footer.html.twig
templates/components/itilobject/timeline/timeline.html.twig

When the Answer button is clicked (e.g. to add a follow-up) before the page is fully loaded, the button remains displayed
If you click Answer instead of Add to validate, the form disappears and so does the Answer button, so the follow-up is not recorded and is lost.

fix: timeline button visibility

---

src/Inventory/Asset/NetworkPort.php

When GLPI handle ```NetworkPort``` (from ```inventory``` process)
If ```ifname``` not exist or is empty, use ```ifdescr``` (if possible)
Before : 
After : 
| Fixed tickets | !26198

fix(inventory): use ifdescr if ifname is empty for NetworkPort

---

inc/define.php

Add missing ```PassiveDCEquipment``` (for ```is_visible_xxxx``` field)
Already present from database.
| Fixed tickets | !26268

fix(states): add missing type

---

src/Features/AssetImage.php

For example on http://glpi10bf.local/front/computermodel.form.php if you add an image in "Rack pictures" + an image in "Other pictures" at the same time, when adding the model you get a fatal error:
```
[2023-01-13 15:47:20] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key 0 in /home/francois/www/glpi-core/10.0-bugfixes/src/Features/AssetImage.php at line 115
Backtrace :
src/CommonDCModelDropdown.php:217                  CommonDCModelDropdown->managePictures()
src/CommonDBTM.php:1281                            CommonDCModelDropdown->prepareInputForAdd()
front/dropdown.common.form.php:62 …
```

fix(imageasset): array error on multiple pictures upload

---

src/Toolbox.php

| Fixed tickets | !26291
I think that it is not necessary to condition the aspect ratio preservation on the fact that the image is greater than the max size.
Hence, for users' images that are not of a "square" ratio, the image is distorted currently, and people don't like having a distorted head :D
Before
After

fix(picture): always keep ratio aspect

---

src/Reservation.php

1. Reservation of items from all entities were shown on reservation planning.
2. Reservation edit form was "blank" due to missing rights when corresponding item was located in a parent entity but visible due to recursive visibility.

Fix reservation entity restrictions

---

src/PlanningExternalEvent.php
src/Search.php

The schedule view restriction was not checked for external events, so the user always saw all external events.
| Fixed tickets | !26244

fix(external event): missing visibility restriction

---

src/Agent.php

* requesting an inventory, we can really have a 'Not allowed' status when agent don't trust server and inventory reports many addresses
* requestAgent() can return earlier when inventory reports many addresses
Actually, we catch all Guzzle exception to try other agent computed addresses. But indeed we should only try on connection failure like connection timeout or domain name resolving failure. Checking this [Guzzle exceptions documentation](https://github.com/guzzle/guzzle/blob/master/docs/quickstart.rst#exceptions), having `RequestException` exception type means we reached the agent and don't need to continue our tries. …

Don't try other agent addresses when we get a client exception

---

src/Features/PlanningEvent.php

The IDs of the guests were displayed in place of their names.
Before:
After:

fix(external event): guest display in the search

---

src/Console/Database/AbstractConfigureCommand.php
src/Console/Database/UpdateCommand.php
src/Console/Migration/TimestampsCommand.php

It is preferable to move the `php bin/console` string outside translations to ensure that ranslators will not alter it.

Protect `php bin/console` string in translations

---

js/dashboard.js
src/Dashboard/Filter.php
src/Dashboard/Grid.php
src/Dashboard/Widget.php

Part 2 of #12953.
On the home page, we have two tabs that will contain dashboards (Dashboard tab + All tab).
Switching between these two tabs will break dashboard rendering due to shared variables stored in a global `Dashboard` var.
I've offloaded the variables into a distinct class to solve the issue.
It's still not perfect:
* Switching to a second tab if the first is still loading will break rendering (no idea how to fix it without preventing tab change while dashboard are loading... or deleting the all tab for the home page 👀)
* Sometimes SVG content isn't rendered on the second tab. It happens randomly, no clue how to fix it.
| Fixed …

Fix dashboard on multiple tabs

---

src/Entity.php
templates/components/itilobject/fields_panel.html.twig

On ITILObject panel, the idea is to make the last displayed name for entities clickable.
Before (no HTML link)
After (last name entry with an HTML link)

feat(itilobject): display entity completename with last as HTML link

---

templates/components/form/inventory_info.html.twig

Display message when no agent has been linked, not all asset have a last_inventory_update

Fix inventory information display

---

ajax/planning.php
ajax/projecttask.php
src/Item_Devices.php
src/RichText/RichText.php
src/Search.php

Following error occurs on PHP 8.2 when trying to use a project task template:
```
*** PHP Deprecated function (8192): html_entity_decode(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/glpi/ajax/projecttask.php at line 62
Backtrace :
:                                                  html_entity_decode()
ajax/projecttask.php:62                            array_map()
```
I figured out that there are at some place, `html_entity_decode` was used to revert the HTML special chars encoding process of the sanitizer, and therefore should use corresponding methods of `Glpi\Toolbox\Sanitizer` …

Replace unexpected usages of html_entity_decode

---

css/includes/components/_debug-panel.scss
js/common.js
src/Application/View/Extension/DataHelpersExtension.php
src/Application/View/Extension/PhpExtension.php
src/Html.php
templates/debug_panel.html.twig
tests/units/Html.php

Originally, I just wanted a way to be able to sort the SQL requests table to quickly identify slow queries. For that, I converted the panel to Twig and added a simple JS method to make a regular HTML table with static content sortable.

Use twig for debug panel and make SQL table sortable

---

src/NotificationTarget.php

There was a piece of code related to a `##glpi.url##` tag in notifications but it was not working.
1. I moved tag registration to constructor, to ensure tag is registerd as soon as possible and is visible in `Available tags` list.
2. I fixed tag value definition.

Fix ##glpi.url## tag definition in notifications

---

src/Toolbox/Sanitizer.php
tests/units/Glpi/Toolbox/Sanitizer.php

Fix $db_escape value in Sanitizer::sanitize() recursive calls

---

src/RuleCollection.php

```SimpleXMLElement->asXML();``` seems to use  ```htmlentities``` 
XML ```Entity``` completename node becomes 
```xml
<entities_id>Entit&#xE9; racine &amp;#62; Sub</entities_id>
```
The import is in error because GLPI seek the correct entity without decode HTML entity
| Fixed tickets | !26386

fix(rule): decode htmlentities from entity completename

---

src/Project.php

Project template name is visible on creation in a special header:
But after creation this header is no longer displayed (since global changes made in GLPI 10.0.4) and thus we can't edit it anymore :
I've added the field at the top to fix this:
| Fixed tickets | !26272

ProjectTemplate: show/edit name after creation

---

js/glpi_dialog.js

It seems that #13831 was not a correct fix (see #13839), we should revert it.

Revert "fix backdrop blocking on planning page"

---

css/includes/components/_global-menu.scss

Fixes following z-index bug:
~~Introduced in commit a0c89108a87884e03fc05445175726196056c051, so bug is not part of latest release.~~ misread the date, maybe it was introduced by something else, or present from the begining.

Fix user menu z-index

---

js/Forms/FaIconSelector.js

| Fixed tickets | #13604 
When minified CSS is used, FontAwesome icons list in incomplete. This is due to the fact that icons are groupes into a unique selector, and are not matching the expected pattern.
```css
.fa-arrow-turn-right::before,.fa-mail-forward::before,.fa-share::before{content:""}
```

Handle FontAwesome icons aliases in icon selector

---

src/Profile.php
src/ProfileRight.php

```
Uncaught Exception TypeError: Unsupported operand types: string & int in /home/francois/www/glpi-core/10.0-bugfixes/src/Profile.php at line 3137
```
Before
After

fix(profile): searchopt by right

---

.composer-require-checker.config.json
.github/workflows/ci.yml
.github/workflows/nightly_build.yml
README.md
composer.json
composer.lock
inc/define.php
index.php
phpstan.neon
src/AuthLDAP.php
src/User.php
tests/LDAP/AuthLdap.php
tests/run_tests.sh
tests/units/Glpi/Application/ErrorHandler.php

Next GLPI major version will likely not be released before end of the year. At this date, PHP 8.1 have reached its EOL.
At this date, all major OS distributions will support PHP 8.1.
| OS               | Release date | PHP version |
| ---------------- | ------------ | ----------- |
| ~~RHEL 8.5~~         | ~~11/2021~~      | ~~7.4~~         |
| ~~RHEL 8.6/9.0~~     | ~~05/2022~~      | ~~8.0~~         |
| RHEL 8.7/9.1     | 11/2022      | 8.1         |
| ~~Debian Bullseye~~  | ~~08/2021~~      | ~~7.4~~         |
| Debian Bookworm  | mid 2023     | 8.1         |
| ~~Ubuntu 20.04~~     | ~~04/2020~~      | ~~7.4~~         | …

Drop support of PHP 8.0

---

templates/components/itilobject/selfservice.html.twig

| Fixed tickets | #13793
When self-service form was reloaded (on category change for instance), uploads were not restored.

Fix uploads on self-service ticket form reload

---

.github/workflows/audit_dependencies.yml
.github/workflows/bump_version_after_release.yml
.github/workflows/label-commenter.yml

1. Add missing permissions on `Bump version after release` action.
2. Move existing permissions to job level.

Fix Github actions permissions

---

src/RichText/RichText.php

The value of `text_maxsize` was too small
ref: https://github.com/glpi-project/glpi/pull/12949

increase text_maxsize

---

src/Profile.php

The right label was not specific enough, because the right only allows you to change your own password and not those of other users.
| Fixed tickets | !25947

improving the `password_update` right label

---

src/SavedSearch.php
tests/functionnal/SavedSearch.php

| Fixed tickets | #12857
1. Public saved searches were visible regardless of active entities.
2. "Entity" and "Child entities" search options were missing.

Fix public saved search visibility in sub entities

---

src/ProjectTaskTemplate.php

`As child of` column was always empty:
| Fixed tickets | !26479

fix(project task template): as child of was not visible

---

ajax/getUserPicture.php
css/includes/components/_kanban.scss
js/modules/Kanban/Kanban.js

| New feature?  |/no
While browsing kanban for answering an incoming change, i though stack of actors in kanban can be slightly improved:
**From**:
**To**:
PS: i didn't had the time to check, but global kanban in ticket doesn't save columns anymore on my instance. @cconard96 Do you have an idea ?

improve kanban actors stack

---

src/KnowbaseItem.php
src/KnowbaseItemCategory.php

Fix for `bugfix` only as discussed in https://github.com/glpi-project/glpi/pull/13455
| Fixed tickets | !25313 #12566

fix(FAQ): visibility as documented (before GLPI 10.1)

---

src/Entity.php
src/Group.php
src/User.php
tests/functionnal/Entity.php

Allows to distinguish between anonymising the user and anonymising the group:
| Fixed tickets | !24779

feat(entity): more anonymising options

---

js/planning.js

After 10.0.6, the planning widget have some rendering issue on chromium based browser (but it works fine on firefox):
It seems to be an indirect consequence of the switch to 2 columns layout.
On the previous layout, the issue still existed but wasn't noticed on bigger screens because with 3 columns the planning widget ended up perfectly at the end of a column, so there was no content underneath to mess up his it's rendering.
The issue is kinda hard to explain (I'm still not sure I really understand it) but the basis is that we have these ajax requests:
The data in rendered by request 1 & 2.
GLPI tell gridstack to recompute the grid after the request 3 is done.
On firefox 1 & 2 always end before 3.
On chromium based browsers, 2 always end **after** 3, which created our issue.
I did find …

Fix planning widget rendering

---

src/Notification_NotificationTemplate.php

noticed method parameter type mismatch warning in IDE, obviously typo in code comments:
marking as bugfix, though importance is minor
Affects nothing except for developer's comfort.

fix code comment typo

---

js/glpi_dialog.js
js/planning.js

Clicking on the hours/minutes/seconds inputs doesn't work on the planning page:
It's some kind of conflict with boostrap, setting `data-bs-focus` to `false` solve the issue.
| Fixed tickets | !25165

Planning: fix datepicker input focus

---

src/CommonDropdown.php
src/Inventory/Asset/InventoryAsset.php
src/Inventory/Asset/Software.php
tests/functionnal/Glpi/Inventory/Assets/Software.php

Prevent SQL error 
```sql
Incorrect integer value: 'Microsoft' for column glpi_softwares.manufacturers_id at row 1 in src\DBmysql.php at line 1969
```
1. To fix SQL : fix Bad use of ```$this->known_links``` from ```Software```, ```key``` are never  use ```md5```
2. this fix caused a problem with the management of the operating system of the software version 
```OperatingSystem``` is a ```CommonDropdown``` and ```InventoryAsset->handleLinks``` with ```Dropdown::importExternal``` return``` -1``` if name is ```0```
Because 
```CommonDropdown::importExternal``` check if ```strlen($value) == 0``` (true if this case)
then call ```CommonDropdown::importExternal``` which check if ```empty($value)``` (false if this case and return ```-1```)
| Bug fix? …

fix(inventory): prevent SQL error when handle manufacturer rule

---

src/Auth.php

| Fixed tickets | !26150
Allows administrators to select "EXTERNAL" authentication mode, even when there is no LDAP directory configured.
This does not change the behavior that follows this first dropdown choice, if LDAP directories are available he can always choose it in the next dropdown (auth mode = external + ldap), or leave it empty (auth mode = external).

fix(user): auth EXTERNAL mode even without LDAP

---

templates/components/itilobject/timeline/form_document_item.html.twig

As discussed : https://github.com/glpi-project/glpi/pull/13986
Display the filename instead of the document name in the timeline.
| Fixed tickets | !26561

fix(document): show filename in timeline

---

src/AuthLDAP.php

| Fixed tickets | see #13396
When `ldap_search()` fails, trying to parse results lead to following error:
```
PHP Warning (2): ldap_parse_result() expects parameter 2 to be resource, bool given in /var/www/html/src/AuthLDAP.php at line 1868
```
All the logic of user research being a big plate of spaghetti, it is difficult to implement a clear message on UI/console, but proposed change will probably make log messages clearer and could help to debug..

Handle LDAP serch errors

---

src/SavedSearch.php

fix(savedsearch): incorrect is_default query

---

src/Search/Input/QueryBuilder.php
templates/components/search/query_builder/criteria.html.twig

Toggle `is_deleted` or `as_map` did nothing on search page

fix(search): toggle is_deleted,as_map not working

---

install/migrations/update_10.0.6_to_10.0.7/ruleticket.php
src/RuleTicket.php
src/RuleTicketCollection.php
src/Ticket.php

`itilcategories_id_cn` and `itilcategories_id` seem redundant.
IMO, the category criterion should work as it does with locations or entity.
| Fixed tickets | !25374

fix(rule ticket): drop itilcategories_id_cn

---

src/System/Requirement/IntegerSize.php
src/System/RequirementsManager.php

See #13980. `ip2long` produces unexpected result on 32 bits OS (see https://www.php.net/manual/fr/function.ip2long.php#refsect1-function.ip2long-notes). It may be possible to fix this, but I am not sure it is worth the cost, especially if we have to maintain a 32 bits environment in our test suite just for this.
I think we could move this requirement from optional to mandatory in next GLPI major version, but we have to do some checks on Windows platforms first. Indeed, on [this thread](https://stackoverflow.com/a/27865372), someone says that PHP on Windows is always using 32 bits integers, but I do not know if it is a fact …

Add 64 bits integer support as optional requirement

---

src/Document.php
tests/functionnal/Document.php

The name of the document in the database loaded from a ticket was not determined in the same way:
- If the document was loaded directly (Action: `Add a document`), the ticket name was used
- If it is in a followup, the file name was used.
_IMO, users look at documents more from a ticket than from the document menu, so the name based on the source is less relevant than the original file._
| Fixed tickets | !26561

fix(document): entry name in database

---

resources/Rules/RuleDictionnaryOperatingSystem.xml
tests/functionnal/Glpi/Inventory/Assets/OperatingSystem.php

REGEX improvement for ```OS Name```
current REGEX
```/(SUSE|SunOS|Red Hat|CentOS|Ubuntu|Debian|Fedora|AlmaLinux|Oracle)(?:\D+|)([\d.]+) ?(?:\(?([\w ]+)\)?)?/```
Not work with ```OS Name``` without ```version``` and ```edition```
Like : ```Red Hat Enterprise Linux Server```
Update ```REGEX``` to 
```/(SUSE|SunOS|Red Hat|CentOS|Ubuntu|Debian|Fedora|AlmaLinux|Oracle)(?:\D+|)([\d.]*) ?(?:\(?([\w ]+)\)?)?/```

fix(OS Rules): improvement of the REGEX

---

src/CommonITILRecurrent.php

Reimplement clone feature for ```CommonITILRecurrent```
Best regards
| Fixed tickets | !26652

fix(CommonITILRecurrent): reimplement clone feature

---

src/User.php

Sometimes, authorizations assignment rules affect the same profile twice.
Case observed when creating a user authenticating via the Oauth plugin.
| Fixed tickets | !26332

fix: preventing double profile assignment

---

ajax/cable.php
src/Dropdown.php
src/Socket.php
templates/pages/assets/cable.html.twig

```Socket``` can only be linked to one ```Cable```
So we need to exclude all ```Socket``` already linked from ```dropdown```
| Fixed tickets | #13851

fix(Socket): Socket can only be linked to one Cable

---

src/CommonITILTask.php
src/Planning.php
templates/components/itilobject/timeline/form_task.html.twig

When editing a task on the planning, clicking the "save" button should save the content using AJAX and close the modal:
On GLPI 10, the form is POSTed instead and we are redirected to the parent ticket/change/problem page.
After inspecting the code, we do specify correctly that the form should be handled through AJAX:
Note the `'formoptions' => "id='edit_event_form$rand'",` above that must match the ID passed to `Html::ajaxForm()`.
This is needed as the ID will be used to bind to the submit event.
This `formoptions` is handled correctly in the `generic_show_form` template but not in the specific template for tasks (which create our issue).
Fixed in 695117262103f865f46e9b125a5c0f1c667540bc by handling the option the same way it is done in `generic_show_form.html.twig`
I've also noticed the …

Planning: fix task edition

---

src/SavedSearch.php
templates/components/search/table.html.twig

1.  Fix warning about ``undefined array key`` when GLPI try to display data
```table.html.twig``` reproduces the logic of the function ```Search::outputData``` when GLPI display column
```twig
{% for col in data['data']['cols'] %}
{% set colkey = col['itemtype'] ~ '_' ~ col['id'] %}
{# showItem function returns "<td ...>...</td>" #}
{{ showItem(0, row[colkey]['displayname'], 0, 0, call('Search::displayConfigItem', [itemtype, col['id'], row]))|raw }}
{% endfor %}
```
```php
foreach ($data['data']['cols'] as $col) {
$colkey = "{$col['itemtype']}_{$col['id']}";
if (!$col['meta']) {
echo self::showItem(
$data['display_type'],
$row[$colkey]['displayname'],
$item_num,
$row_num,
self::displayConfigItem(
$data['itemtype'],
$col['id'],
$row
)
);
} else { // META case
echo self::showItem( …
```

fix(savedsearch) : fix support of meta criteria

---

css/includes/_fonts.scss
package-lock.json
package.json
webpack.config.js

Based on the changelogs, no icon was removed and the icons that had been renamed don't seem to be used by GLPI or any of the plugins I have downloaded. There have been hundreds of new icons added since 1.68 and many of them are useful for a plugin I am working on.
If BC is still a concern, I guess CSS rules could be added so that the old names of any renamed icons that exist in 1.68 can still work.

Upgrade tabler icons to v2.2

---

src/Infocom.php
src/Search.php

Currently it is now possible to select future dates when wanting to see the warranty expiration dates of devices. This change helps to see which devices will need attention in the coming X time then.

Filtering on end warranty should also allow to search future dates

---

src/CommonITILObject.php
src/ITILFollowup.php

_Rights uniformisation for twig and massive actions to add tasks and followups_
The timeline buttons at the bottom of Ticket or Change are displayed at this condition :
{% if item.**isNotSolved**() and default_action_data != false %}  (components/itilobjects/footer.html.twig)
==> Only displayed if item is not solved
If the specified item is solved, no possibility to add a new followup by this way.
But, it is always possible via massive actions because the condition is  :
if (in_array($item->fields['status'], $item->**getClosedStatusArray**())){
This PR uniformise the condition : allow to add followup or task only if item is not closed and is not solved.
| Tests …

fix(Massive actions) add status check before adding tasks/followups

---

src/Change_Problem.php
src/Change_Ticket.php
src/Problem_Ticket.php

The dropdown to link a change to a ticket did not filter out resolved and closed statuses.
_Same thing between change/problem and problem/ticket_
Considering the `Ticket` < `Problem` < `Change` hierarchy, we can associate a closed element when going down the hierarchy, but not when going up.
Example: We can associate a closed ticket from a change, but we cannot associate a closed change from a ticket.
| Fixed tickets | !26630

fix(ticket): filtering the dropdown of changes

---

src/Inventory/Asset/VirtualMachine.php
tests/functionnal/Glpi/Inventory/Inventory.php

When a ```VirtualMachine``` is missing from inventory file.
GLPI ```purge``` ```ComputerVirtualMachine``` and ```delete``` ```Computer```
it creates frustration among users (```Computer``` deleted, no info from ```ESX```` (```Virtualization``` tab)
I propose to only ```delete``` ```ComputerVirtualMachine```, 
The ```ComputerVirtualMachine``` will still be visible from the ```ESX``` (```Computer```) but marked as deleted (the code is already available)

fix(inventory): do not purge ComputerVirtualMachine

---

front/notificationtemplatetranslation.form.php

Prevent this error message in debug mode : `PHP Warning (2): Undefined array key "notificationtemplates_id" in /home/teclib/Dev/GLPI/10.0-bugfixes/front/notificationtemplatetranslation.form.php at line 49`
_The error did not appear to have any functional impact_

fix(notification template): error message in debug

---

CHANGELOG.md
src/Rule.php
src/RuleAsset.php
src/RuleCollection.php
src/RuleCommonITILObject.php
src/RuleDictionnaryDropdown.php
src/RuleDictionnaryPrinter.php
src/RuleDictionnarySoftware.php
src/RuleImportAsset.php
src/RuleImportComputer.php
src/RuleImportEntity.php
src/RuleLocation.php
src/RuleMailCollector.php
src/RuleRight.php
src/RuleSoftwareCategory.php

It seems that `Rule::$can_sort` and `Rule::$orderby` properties are not working, or at least not on all contexts where they should. For instance, it seems that `RuleMailCollector` list is sorted and evaluated based on `ranking` field, while it is specified that it should be based on `name` field.
I propose to remove ability to override this, as it does not even seems to be used in plugins.
Now, all rule collections will be sortable and evaluated based on the way they are sorted.

Remove ability to change rules sortable state and sort field

---

templates/components/form/fields_macros.html.twig

A JavaScript error is thrown if the color in a Spectrum color input is set to null, causing the control to stop working properly.

Fix color field null value handling

---

src/Search.php

On Change list, validation status are not colorized like Ticket list.
This PR add colorization on Change list.

fix(Change) Add color for validation status in change list

---

src/Inventory/Asset/NetworkPort.php
src/NetworkPort.php
tests/functionnal/Glpi/Inventory/Assets/NetworkPort.php

Do not lock ```networkport```  when handle metrics
| Fixed tickets | #14063

fix(inventory): do not lock networkport when handle metrics

---

src/CommonDBTM.php
tests/functionnal/Glpi/RichText/UserMention.php

Edge case revealed by #12451 .

User mentions handling should be skipped when no fields were updated

---

templates/components/form/link_existing_or_new.html.twig

| Fixed tickets | #14065
The predetermined random value for form field IDs wasn't being reused in all fields so changing the AJAX dropdowns like when you change the Project in the Project Tasks tab of a Ticket wasn't working.

fix missed rand reuse for itil link tabs

---

src/Inventory/Asset/NetworkEquipment.php
src/Inventory/Asset/NetworkPort.php
tests/functionnal/Glpi/Inventory/Assets/NetworkEquipment.php

I have stacks of switches where network ports names have zeroes in the chassis-id part, e.g. `Gi0/1`, and Glpi currently can't have `$stack_id == 0`. We can try to parse `network_components` section to find out ports to stack members assignment.
Links to https://github.com/glpi-project/glpi-agent/pull/260

feat(inventory): improved port to stack member mapping

---

src/Inventory/Asset/VirtualMachine.php

Handle ```last_inventory_update``` for ```Computer``` linked to ```VirtualMachine```
| Fixed tickets | !26406

fix(inventory): set last inventory update date to related computer

---

src/HTMLTableSubHeader.php

Fix `PHP Deprecated function (8192): Creation of dynamic property HTMLTableSubHeader::$numberOfSubHeaders is deprecated in /var/www/webapps/glpi/src/HTMLTableGroup.php at line 177` on computers components tab with PHP 8.2.

Fix PHP 8.2 dynamic property creation warning

---

src/KnowbaseItem_Comment.php
src/Notepad.php
templates/components/user/picture.html.twig

I user upload thumbnail with transparent background
background color from users initial is still display.
Before : 
After : 
Fix ```KnownBaseItem_Comment``` comment and ```NotePad``` too.

fix(ui): fix thumbnail background color

---

src/NotificationTargetContract.php

Adding the tags `##contract.comment##` and `##contract.account##`
| Fixed tickets | !26795

fix(notification): missing tags for contracts

---

front/networkport.form.php

Fix missing 'restore' action from ```NetworkPort```
| Fixed tickets | !26491

fix(NetworkPort): fix 'restore' action

---

src/NetworkPort.php

The display of ```NetworkPort``` should not depend on the is_dynamic property of the parent asset, but it should depend on the is_dynamic property of the ```NetworkPort```  (a dynamic asset can have dynamic and non dynamic ```NetworkPort```
| Fixed tickets | !26491

fix(NetworkPort): fix display of delete non dynamic NetworkPort

---

src/Console/AbstractCommand.php
src/Console/Diagnostic/CheckDocumentsIntegrityCommand.php

I've had some issues with the `php bin/console glpi:diagnostic:check_documents_integrity` command as it would go over the allowed memory limit.
With a test database of 638015 documents, the command would reach around 141MB of memory.
After optimization, the command do not got over 20MB.

Memory optimization for glpi:diagnostic:check_documents_integrity

---

src/Inventory/Asset/InventoryNetworkPort.php
tests/functionnal/Glpi/Inventory/Assets/Computer.php

| Fixed tickets | #14087 
`NetworkName` are associated to `NetowkrPort`, but appart of some hardcoded names in some cases; no name was never provided, therefore display was `(id)` most of the time. This PR use slugified NetworkPort name.

Use port name as network name during inventory

---

src/Inventory/Asset/NetworkPort.php

```Printer``` ```Network``` are now managed as ```NetworkEquipement``` ```Network```
See : https://github.com/glpi-project/glpi/pull/13894
But this feature => https://github.com/glpi-project/glpi/pull/12197
need to be adapt
Fix too : FIX glpi-inventopry plugin TU https://github.com/glpi-project/glpi-inventory-plugin/actions/runs/4052704362/jobs/6972432429

fix(inventory): remove management port for Printer on netinventory

---

src/Features/ParentStatus.php

Some code that only trigger for self-service users was not strict enough.
The code is checking the status instead of calling `needReopen` which has additional checks.
| Fixed tickets | !26763

Stricter reopen rules for self-services users

---

src/System/Requirement/IntegerSize.php
src/System/RequirementsManager.php

As discussed previously, this requirement should be mandatory on next major GLPI version.

Make 64bits integers requirement mandatory

---

install/migrations/update_10.0.6_to_10.0.7/unmanageds.php
install/mysql/glpi-empty.sql

Fixes All Assets view as `users_id_tech` field is expected for all assets but was missing for Unmanaged which was added to this list in #13326.

Add users_id_tech for unmanaged devices

---

templates/components/form/fields_macros.html.twig

| Fixed tickets | !26857
Adding images in solution, followup or task templates is not supported. However, pasting images was not disabled due to the fact that argument was not correctly passed to the rich text editor initialization method.

Fix enable_images option handling in textarea fields

---

src/MailCollector.php

| Fixed tickets | see #14116
Collector is currently including errored and already seen emails in its processing limit. Problem with this is that if there is more errored/already seen emails than the retrieve limit, the mailgate automated task will do nothing except fetching same emails as in previous run, and will therefore be kind of stuck.
I propose to change parameter from `Number of emails to retrieve` to `Number of emails to process`, meaning that errored/already seen emails will not be counted in the defined limit.

Fix way to count processed emails in collector

---

src/Inventory/Asset/VirtualMachine.php
tests/functionnal/Glpi/Inventory/Assets/VirtualMachine.php

Actually ```inventory``` can manage handle ```Computer``` even if  ```uuid``` change
from this ```420904fe-6a92-95e8-13f9-a37fc3607c14``` to this ```fe040942-926a-e895-13f9-a37fc3607c14```
See ```ComputerVirtualMachine::getUUIDRestrictCriteria```
https://github.com/glpi-project/glpi/blob/40cf35f66efb3840e6b6fe426589526a2df37149/src/ComputerVirtualMachine.php#L368-L401
But, this behavior is not done for ```ComputerVirtualMachine``` it self.
The link between ```ESX``` and ```Computer``` is then deleted and recreated at each inventory if ```UUID``` changed.
This Pr fix this
| Fixed tickets | !26226

fix(inventory): manage UUID format changed

---

src/Html.php

| Fixed tickets | #14138
`str_contains` params were inverted.

Fix redirect URL parameters

---

src/CommonDBChild.php
src/CommonDBTM.php

to fix:
```
[2023-02-22 11:07:54] glpisqllog.WARNING: DBmysql::query() in /var/www/webapps/glpi/src/DBmysql.php line 404
SQL: SELECT * FROM `glpi_ipaddresses` WHERE `items_id` = '' AND `itemtype` = 'NetworkName' AND `is_deleted` = '0'
Warnings: 
1292: Truncated incorrect DECIMAL value: ''
Backtrace :
src/DBmysqlIterator.php:112                        
src/DBmysql.php:1056                               DBmysqlIterator->execute()
src/CommonDBChild.php:948                          DBmysql->request()
src/NetworkName.php:478                            CommonDBChild::showChildsForItemForm()
src/NetworkPort.php:1399 …
```

Fix error on network port form

---

src/Inventory/Asset/NetworkPort.php
tests/functionnal/Glpi/Inventory/Assets/NetworkEquipment.php

```RuleImportAsset``` (when trying to retrive asset from MAC) use ```logical_number``` from ```WHERE``` statement.
But from ```Unmanaged``` asset, ```NetworkPort``` created never use ```logical_number```.
So at each inventory, GLPI create new ```Unmanaged``` asset (same as before)$
this PR fix this
| Fixed tickets | !26747

fix(inventory): fixed bad handling of Unmanaged reconciliation from ruleImportAsset

---

src/AuthLDAP.php

Even if values are pre-configured in "preconfig", they are not taken into account when submit add form, the following lines are ignored:
https://github.com/glpi-project/glpi/blob/94fa6fe3d58e366bedbc8ddf222a10efc61d1236/src/AuthLDAP.php#L220-L223
This PR fixes that problem (and adds a few more fields).

fix(ldap): missing preconfig fields

---

install/empty_data.php
install/migrations/update_10.0.6_to_10.0.7/profils.php
src/Migration.php
src/RSSFeed.php
src/Reminder.php
tests/units/Migration.php

When a profile did not have access to `public reminders`, GLPI replaced the menu with `personal reminders`, so the menu was not removed completely.
This PR adds rights to hide menus completely
| Fixed tickets | !26786

fix: no rights for personal reminders and RSS feeds

---

index.php
templates/pages/2fa/macros.html.twig

The code is validated on the server side so having the code input labeled as required isn't needed. This fixes the issue with skipping the 2FA setup when in a grace period.

Fix skipping 2FA setup in grace period

---

templates/pages/2fa/macros.html.twig

Auto-submit when typing the 2FA code was incorrectly moved to the keydown event when I was improving the responsiveness of the field set, so autosubmit would not activate immediately after the last number was entered and would have required another key press.

Fix 2FA code autosubmit

---

src/RuleTicket.php
tests/functionnal/Rule.php
tests/functionnal/RuleTicket.php

Currently, it is required that there be criteria for the selection of the contract that applies to the particular tickets.
The objective is to be able to open a ticket and that by means of rules, there is a way to assign a contract to it given that the work orders represent different priority levels, for each contract that has been contracted by the final customer.
In some cases, such as this one, the end user should be able to select which contract he wants to use and immediately, this will represent the level of service that the ticket will take.
| Fixed tickets | 42

feat(ruleaction): Assign a contract to ticket through regular expression or direct selection

---

src/Notification.php

add missing saved search list from ```Notification```
| Fixed tickets | !26926

fix(ui): add missing saved search list from Notification

---

src/CommonDropdown.php

add missing saved search list from all ```dropdown``` item (like ```ITILCategory```)
| Fixed tickets | !26918

fix(core): add missing saved search for dropdown

---

src/AuthLDAP.php
tests/LDAP/AuthLdap.php

The LDAP `Ymdhis.0Z` timestamp format was not always converted, so the `valid from` and `valid to` fields were not always synchronized.
https://github.com/glpi-project/glpi/pull/14032
| Fixed tickets | 26853

fix(authldap): LDAP date value

---

templates/components/itilobject/footer.html.twig

User that aren't allowed to add followups still have the "answer" button in the ITIL timeline.
Rights:
Before:
Note that "answer" is shown but not "add task" despite the user rights indicating the opposite.
After:
| Fixed tickets | !26945

IITLTimeline: hide "answer" button if not allowed to add followups

---

tests/run_tests.sh

As a result of this change (https://github.com/glpi-project/glpi/pull/14159), if the "--all" option is used, the lint tests are run twice.

fix(run_tests): remove lint_X tests when --all option

---

css/legacy/includes/_impact.scss

Fix impact toolbar z-index
Before : 
After : 

fix(UI): fix impact toolbar z-index

---

src/CommonGLPI.php
templates/components/form/header_content.html.twig

Display missing object header from template
Before : 
After : 

fix(UI): Display missing object header from template

---

front/logviewer.php

- fix 404 error when deleting a log file
- fix 404 error when click on the breadcrumb entry "Log file" (so with an empty "filepath" )

fix(logs): 404 error on delete

---

front/notepad.form.php

Related post on the forum:
https://forum.glpi-project.org/viewtopic.php?id=286418
The note item link listed in Administration > Logs would always show a "Lost" error because the `notepad.form.php` front file never handled trying to get a note as they are always embedded in tabs of other items. This PR adds a redirect to the Notes tab of the parent item if you try to access the note via `notepad.form.php` without overriding the form URL which I think would break add, update and deletion.

fix link for notes in logs

---

src/Ajax.php
src/Toolbox.php

Example: on a computer template, by activating the "Management" tab, if you reload the page (after validation of the form) the page opens on the "Remote management" tab (which is the tab just before).
Same case with the other tabs, the reload is done on a previous tab.
The offset depends on the number of hidden tabs in the template.
| Fixed tickets | !27048

fix(template): wrong tab after page reloading

---

front/search.php

Sort items in the global search results by number of results
Before:
After:
| Fixed tickets | !26078

feat(global search): sort items by number of results

---

src/SoftwareLicense.php

When creating a license from template, linked items (as contract) were not copied on the created license.
| Fixed tickets | !27043

fix(license template): missing relations

---

CHANGELOG.md
src/Console/Application.php
src/Console/CommandLoader.php
src/Console/Plugin/ListCommand.php
tests/units/Glpi/Console/CommandLoader.php

Purpose of this PR is to:
1. ensure plugins commands are grouped in their own namespace (see image below);
2. prevent conflics between GLPI base commands, GLPI tools commands and plugins commands, each having their own reserved namespace.
EDIT: To be reviewed without whitespace changes.

Normalize console command namespaces

---

src/Report.php

Prevent SQL error when ```itemtype```  does not have the 'is_template' column
```Operating System``` query does not use restrictions on the entity
| Fixed tickets | #14257

fix(report): fix default report

---

src/Inventory/Asset/MainAsset.php
tests/functionnal/Glpi/Inventory/Assets/Computer.php

Like https://github.com/glpi-project/glpi/pull/12891
When ```transfer_strategy``` does not allow the automatic transfer
the inventory does not put the old entities_id to ```Agent``` -> so the ```Agent``` changes entity.
| Fixed tickets | !27014

fix(inventory): revert old entities_id for agent too

---

src/NotificationTargetChange.php
src/NotificationTargetTicket.php

```##ticket.urlvalidation##``` and ```##change.urlvalidation##``` generate a bad redirection
The approval or refusal is no longer done in the ```Validation``` tab but in the ```Timeline (main)``` tab
We need to generate this : 
```
http://127.0.0.1/GLPI/10.0-bugfixes/ajax/common.tabs.php?_target=/GLPI/10.0-bugfixes/front/ticket.form.php&_itemtype=Ticket&_glpi_tab=Ticket$main&id=1
```
instead of 
```
http://127.0.0.1/GLPI/10.0-bugfixes/ajax/common.tabs.php?_target=/GLPI/10.0-bugfixes/front/ticket.form.php&_itemtype=Ticket&_glpi_tab=TicketValidation$1&id=1
```
| Fixed tickets | !27061

fix(Approval): ##object.urlvalidation## return bad redirect

---

CHANGELOG.md
apirest.php
apixmlrpc.php
caldav.php
front/cron.php
inc/includes.php
index.php
install/install.php
src/Toolbox.php
status.php
tools/getsearchoptions.php

1. `HTTP_REFERER` value cannot be trusted, so checking it does not really enforce security.
2. There is now a CSRF token check on all POST request (except for API), so checking `HTTP_REFERER` seems not relevant anymore.
3. Default behaviour of browsers is to not send cookies on `POST` requests (`SameSite: Lax` policy on cookies), so result will be that GLPI will not be able to retrieve session and will therefore not be able to validate CSRF token, so request will anyway be invalidated. Thus, since GLPI 10.0.3 ((see #12302), we added a warning on install/update to indicate when `SameSite` session cookie policy is not at …

Do not check HTTP_REFERER value on POST requests

---

public/index.php
src/Central.php
src/Console/System/CheckRequirementsCommand.php
src/Http/ProxyRouter.php
src/System/Requirement/DataDirectoriesProtectedPath.php
src/System/Requirement/SafeDocumentRoot.php
src/System/RequirementsManager.php
tests/units/Glpi/Http/ProxyRouter.php
tests/units/Glpi/System/Requirement/DataDirectoriesProtectedPath.php

PHP router to expose only public directory

---

install/migrations/update_10.0.6_to_10.0.7/indexes.php
install/mysql/glpi-empty.sql
src/System/Diagnostic/DatabaseKeysChecker.php

For itemtypes using commontreedropdown items may show very slowly because of unoptimized SQL queries. 
This may happen with Formcreator, when a question is designed to show only a subtree of existing items, and when there are a thousand of items in the database.
Adding an index on level columns shows a speed gain of 50%.
internal ref !26669
| Fixed tickets | #

add key on level column for CommonTreeDropdowns

---

src/CommonITILActor.php
tests/bootstrap.php
tests/functionnal/Project.php
tests/functionnal/ProjectTask.php
tests/functionnal/Ticket.php

Check that the actor exists in the database before adding it to the ticket (change, problem).
_Case observed at a customer: the user with ID = 1 (not existing in the database) was added to all tickets created via the FormCreator plugin and when the Behaviors plugin is active._
| Fixed tickets | !26985

fix(ticket): check user exist before link

---

src/NotificationTargetTicket.php

In ticket notifications, some location fields were missing in the tags:
- Address
- Postal code
- Town
- State
- Country
| Fixed tickets | !26381

feat(notification template): add missing location tags

---

src/CommonDBTM.php
src/User.php
templates/components/form/single-action.html.twig
templates/components/search/table.html.twig

Even if  system user ```glpi-user``` can't be deleted from his form
```MassiveAction``` are available (with ```trashbin``` and ```purge```)
Add ```CommonDBTM``` function to prohibit massive action (```bulk``` or ```single```) if necessary

fix(core): globally prohibit massive action if necessary

---

src/CommonITILObject.php
src/Search.php
tests/functionnal/Search.php

I'm using the following set of data to demonstrate the issue:
We have four tickets, two of which have multiple groups.
The tickets with multiple groups are the one that are not going to behave correctly in the tests below.
After fix:
After fix:
After fix:
The search engine is joining the data like this (simplified) :
When we add the condition, we remove the rows that don't match the expected group:
Tickets 50 is incorrectly returned because one of his linked groups (Group 2) satisfy the condition (Group != Group 1).
This is logical when looking at the query, but it doesn't make sense for the users.
When the user ask GLPI "Give me all the tickets that don't have Group 1 as an observer", ticket 50 should not be part of the results because it has indeed group 1 as an observer (even if it …

Search engine: fix negative conditions on linked children

---

src/Http/ProxyRouter.php
tests/units/Glpi/Http/ProxyRouter.php

Prior to PHP 8.1.12, `woff` and `woff2` files mime was not properly returned, see https://github.com/php/php-src/issues/8805

Fix WOFF font proxify on PHP 7.4/8.0

---

tests/units/Glpi/Application/ErrorHandler.php

Looks like there is an issue in atoum mock generator on PHP 8.1. As we do not really use mock capability on this specific case, passing a real instance of `Monolog\Handler\TestHandler` is an acceptable quickfix.

Fix tests on PHP 8.1

---

src/Search.php

Loose comparison with 0 in PHP 7.4 is unsafe.
```
$ php -r 'var_dump("myself" == 0);'
bool(true)
```

Fix subquery search handling on PHP 7.4

---

src/Dashboard/Grid.php
src/Session.php

The `getAllDasboardCards` cache entry will contain translated content and thus must be cached independently for each languages.
A better solution would be to not include translated content in the `getAllDasboardCards`  function, but it would require a lot more changes and probably some breaking changes regarding plugins like Advanced Dashboards.
| Fixed tickets | !26769

Fix getAllDasboardCards cache

---

src/Transfer.php
tests/functionnal/Transfer.php

During a transfer, ```entities_id``` from ```SoftwareVersion``` is not updated with the destination entity.
This Pr fix this

fix(Transfer): fix entities_id not update for SoftwareVersion

---

src/Inventory/Asset/MainAsset.php
tests/functionnal/Glpi/Inventory/Assets/Computer.php

Following this PR https://github.com/glpi-project/glpi/pull/14254
I noticed that the software does not follow the entity of the computer when is transferred 
At each inventory ```SoftwareVersion```, ```Item_SoftwareVersion```, ```Software``` change entity
even if we have not authorized the transfer ( ```no change of entity```) from ```Entity```
```TU``` failed because i found another bug, ```SoftwareVersion``` does not change entity from a transfer.
```Item_SoftwareVersion``` and ```Software``` are correctly transferred
need : https://github.com/glpi-project/glpi/pull/14287
| Fixed tickets | !27105

fix(inventory): software are still transfer even if not allowwed

---

src/CommonITILObject.php

Kanban page fails completely if one of the defined columns does not contains any tickets.
>[2023-03-13 11:17:29] glpiphplog.WARNING:   *** PHP Warning (2): foreach() argument must be of type array|object, null given in /home/aclai/localhost/glpi/10.0-bugfixes/src/CommonITILObject.php at line 8853
Backtrace :
ajax/kanban.php:247                                CommonITILObject::getKanbanColumns()
| Fixed tickets | !26997

ITIL Kanban: Fix error for empties columns

---

ajax/entitytreesons.php

Ensure entity tree cache is recomputed when `root_doc` change

---

src/Auth.php

If a login session is resumed using the "remember me" cookie, the login method was being called and the new 2FA feature was trying to treat it like a real login even though the user was already logged in. This resulted in a redirect loop between the login page and the 2FA code request page.
This bug was introduced with the 2FA feature, 10.0 is not affected.

Fix infinite login loop

---

front/user.form.php
src/User.php

| Fixed tickets | !27147
Allow users with the UPDATEAUTHENT permission to disable 2FA for users. If 2FA is mandatory for the user, they will be prompted to set it up again the next time they log in. This PR adds this action next to the 2FA status in the user form and as a massive action.

allow disabling 2fa for other users from web

---

src/Search/Provider/SQLProvider.php
tests/functionnal/Search.php

`makeTextSearchValue()` method result is used either in raw queries via `DBmysql::quoteValue($search_val)` that is already escaping values, either in `DBmysql::request()` params, that are now automatically escaped.

Prevent searched text to be twice escaped

---

inc/define.php

Assistance > Statistics page tries using the rateit library but it is not included for these pages.

Fix missing rateit lib for stats

---

src/Project.php

| Fixed tickets | #13899
`Html::showCheckbox` adds a hidden input with the same name which caused the onclick selector to target the wrong input. The Project Task form doesn't have this issue (uses Twig template).

fix project auto percent toggle

---

src/Ticket.php

When a ticket was created from a project task, the title AND the description of the ticket were identical, in both fields, it was the title of the task.
| Fixed tickets | !27264

fix(ticket): wrong content when create from project task

---

src/Rule.php

| Fixed tickets | #14306
I'm not sure that this action should be available in the single action list since it relies on knowing where in the list the rule is currently, which you cannot see from the rule itself

Remove move action from single action list

---

src/KnowbaseItem_Comment.php
tests/functionnal/KnowbaseItem_Comment.php

| Fixed tickets | #14348
Visibility of the comments tab should depend on the comment right and not update rights.

fix kb comment tab visibility

---

install/migrations/update_10.0.6_to_10.0.7/softwarelicense.php
install/mysql/glpi-empty.sql
src/System/Diagnostic/DatabaseSchemaConsistencyChecker.php

SoftwareLicense is a CommonTreeDropdown class and there are two cache fields that are expected to be present for all those classes, but are missing here. A SQL error is thrown after purging a Software because of these missing fields.

add missing softwarelicense cache fields

---

src/CommonTreeDropdown.php

Moving an entity under root result in an invalid `sons_cache`.
This is caused by check done on IDs that rely on 0 meaning that the item doesn't have any parent, which is false for entities (0 = root entity's id).
If you are affected by this issue, clearing GLPI's cache then logging off/on should restore access to the "lost" entity (and applying the patch before moving another entity).
| Fixed tickets | !27259 #14095 #14179 #14180

Fix invalid cache after moving entity under root

---

src/Html.php

| Fixed tickets | #14161
The automatic upload of files seems to interfere with the `required` attribute on the file upload input. As a workaround, the required attribute is removed when a file is automatically uploaded. All cases that expects a mandatory file upload should verify it on the server side anyways (Tickets do if mandatory through a template), so it seems like a low risk to remove the client-side check after the first auto-upload.

Workaround for mandatory file upload check

---

js/dashboard.js

New cards added to a dashboard didn't use the existing filters until the page was refreshed.

Use filters for new dashboard cards

---

templates/layout/parts/profile_selector.html.twig

| Fixed tickets | #14317
Entity tree filtering was done at node level, meaning that child of matching entities were filtered, as they were not matching the search term themselves.
Filtering at branch level fixes this.
Before
After

Display whole matching branches on entity tree filtering

---

css/legacy/includes/_styles.scss

| Fixed tickets | #14184
Removed rule was initially made to keep the header displayed when full screen mode was active on rich text.
There are many problems with that:
- 105 latest pixels of the content are hidden and unreachable;
- it does not handle ability to choose page layout (header has not the same height when menu is on top or on sidebar);
- it does not handle responsiveness of layout;
- it does not handle custome CSS rules that can be made in entity configuration or by a plugin.
So, I propose to remove this rule, and let the fullscreen mode take all available space on the screen.

Fix full screen mode of rich text editor

---

src/System/Requirement/DataDirectoriesProtectedPath.php
src/System/Requirement/SafeDocumentRoot.php

Use correct directory separator on Windows env.
```diff
- Web server root directory should be `D:\Web\glpi/public` to ensure non-public files cannot be accessed.
+ Web server root directory should be `D:\Web\glpi\public` to ensure non-public files cannot be accessed.
```

Fix requirements messages on Windows env

---

src/KnowbaseItem_Revision.php

| Fixed tickets | #13786
KnowbaseItem_Revision was missing a right name so API access was impossible.

Fix missing KB revision right

---

front/report.dynamic.php

I found a bug that cannot export simcard (Item_DeviceSimcard) because Item_DeviceSimcard doesn't have $rightname and will be failed when exporting in report.dynamic.php
<pre>
$itemtype = $_GET['item_type'];
if ($itemtype === 'AllAssets') {
Session::checkCentralAccess();
} else {
<b>Session::checkRight($itemtype::$rightname, READ);</b>
}
</pre>

Fix: Cannot export item_devicetype (item_devicesimcard, etc...)

---

src/Group_User.php

New `Group_User` relations are not shown in GLPI history.
These history entries are handled automatically by `CommonDBRelation::post_addItem()` and the `Group_User` class was overriding the function without calling the parent method.
| Fixed tickets | !27336

Fix missing history entry when adding a user to a group

---

js/fileupload.js

This change is required to allow a user to add files to a file field which is rendered with pre-uploaded files.
This use case may happen in Formcreator when a validator validates answers containing a file question. This PR is required for https://github.com/pluginsGLPI/formcreator/pull/3226
The goal is to not start the uploads index from zero, but counts the existing inputs related to a file upload field instead.

drop global var for uploads indexation

---

js/common.js
src/Html.php
templates/components/search/table.html.twig

In the ticket items tab, the KB entries unfolded when selecting all for massive actions and conversely, folded when unchecking all.
_I think it's more general, when there is a checkbox in the table data, but I don't know any other case._
Before:
After:

fix(massive action): check all

---

css/includes/components/_select2.scss

When an actor's name is too long, it is truncated and the icons that follow are not visible.
Before:
After:
| Fixed tickets | !27445

fix(ticket): display of actor names too long

---

css/standalone/dashboard.scss

The dashboards have some css code to hide the extra dropdown buttons like "+" in the filter area.
It seems to be a bit too aggressive and in the case of dropdown built from `Dropdown::FromArray`, which do not have these buttons, will end up targeting the delete filter button instead ("trash" icon).
Setting the delete filter button display's style as important avoid this issue.
Note: we do not have any filter that use this kind of dropdown yet so the issue does not affect anyone at this moment (but it could be an issue for future filters).
| Fixed tickets | !27440

Fix dashboard fitler css conflict

---

src/Api/APIRest.php
tests/web/APIRest.php

I found a bug that when calling GLPI Request using application/x-www-form-urlencoded content, glpi throw critical error
This error orrcurs on PHP >= 8
```
*** Uncaught Exception Error: Attempt to assign property "id" on array in \glpi\src\Api\APIRest.php at line 324
Backtrace :
apirest.php:57                                     Glpi\Api\APIRest->call()
```

Fix parsing of `x-www-form-urlencoded` input in API

---

install/migrations/update_10.0.6_to_10.0.7/ticket_fix_internal_tto_escalation.php
install/mysql/glpi-empty.sql
src/LevelAgreement.php
src/Ticket.php
tests/DbTestCase.php
tests/functional/SLM.php

TTO/TTR for OLA are calculated from the date at which the OLA were added to the ticket.
However, their escalation dates are currently calculated incorrectly (using the ticket opening date instead).
Ticket created at 12:00:
OLA added at 12:25:
The TTO/TTR are correct:
The escalation dates are incorrect:
Fixed by storing the date at which the OLA were set (new `ola_tto_begin_date` field for TTO, the `ola_ttr_begin_date` field for TTR already existed) and using it in calculations.
| Fixed tickets | #27262

Fix OLA escalation date calculation

---

src/User.php

The `User::getSqlSearchResult()` could return list of all users when used with `$right='groups'` or `$right='delegate'` from helpdesk interface.
Indeed, in this case, if there is no matching user found in current user groups, the where clause on `users_id` will not b applied due to https://github.com/glpi-project/glpi/blob/66691c1b2f029ae103fb6f79f6d4a7d3b246c91e/src/User.php#L4071-L4073.
It only affects helpdesk interface, as current user is added to users list on central interface: https://github.com/glpi-project/glpi/blob/66691c1b2f029ae103fb6f79f6d4a7d3b246c91e/src/User.php#L4067-L4069
Bug was introduced when code was …

Fix user dropdown filtering on helpdesk interface

---

src/Console/Migration/TimestampsCommand.php

`migration:timestamps` command is responsible to migrate database data. When timezones usages cannot be enabled, command do not fail though.
Replace the error message
by a warning

Enhance unmet prerequisites message in `migration:timestamps` command

---

inc/define.php

Fix restore / purge lock for Domain_Item
```Domain_Item``` need to be set in ```$CFG_GLPI['inventory_lockable_objects'] ```
See ```glpi/front/lock.form.php```
https://github.com/glpi-project/glpi/blob/2b3f5440bd8d175d4eb5b0b70399607b4b36ecf0/front/lock.form.php#L47-L51

fix(inventory): fix restore / purge lock for Domain_Item

---

src/Api/API.php

| Fixed tickets | #14490 
IPNetwork at least uses some class properties that interfere with adding/updating multiple items using the same instance. For safety, I think the API should always use a new instance for each item being created/updated.

Fix bulk create and update of some items via api

---

css/legacy/includes/_styles.scss
src/CommonDropdown.php

On small screen resolutions, when you display the KB, its rendering is cut.
Before:
After:
| Fixed tickets | !27550

fix(ticket): improve KB display

---

src/Inventory/Asset/MainAsset.php

Like ```Software```, ```Domain``` must follow the asset entity

fix(Inventory): search Domain with asset entities_id

---

src/Search.php
tests/functional/Search.php

When we made a search with a text containing a backslash, GLPI never found a result
Before:
After : 
| Fixed tickets | !27408

fix(search): query search with backslash

---

inc/includes.php
src/Toolbox/Sanitizer.php
tests/units/Glpi/Toolbox/Sanitizer.php

Tab names that contains name space (e.g. `GlpiPlugin\MyPlugin\Config`) can't be used with the `forcetab` query parameter as `\` are converted into `\\` by our processing of `$_REQUEST`.
Fixed by using `$_UREQUEST` instead (but maybe doing an str_replace on `$_REQUEST` instead would be safer ?).

Fix forcetab parameter for namespaces

---

js/glpi_dialog.js

Toasts created by the `glpi_toast` javascript function are not identical to their `Session::addMessageAfterRedirect` PHP counterparts.
PHP toast:
JS toast:
JS toast after changes:

Fix JS toast style

---

src/CommonITILObject.php
templates/components/itilobject/timeline/timeline.html.twig
templates/components/itilobject/timeline/timeline_item_header.html.twig

The `item was already promoted` entry was only displayed when Ticket was editable and not closed. This condition does not make sense. Indeed, when an item was already promoted, we should display this information whenever the parent status is.
Thus, it was resulting in proposing the promotion of an item that was already promoted.
Before fix:
After fix:
I also reviewed the conditions to ensure that the `item was already promoted` entry is only visible for user that would have rights to promote the item if it was not already promoted.
Replace #14475

Fix promote button state/visibility

---

src/Config.php

| Fixed tickets | !27638
SMTP OAuth configuration was lost when any config form not related to SMTP was submitted.

Prevent SMTP OAuth config to be lost on config save

---

front/savedsearch.php

| Fixed tickets | #14529
`front/savedsearch.php` file was probably included by another front script in previous GLPI versions. This is no longer the case.
When accessing this page without an active session, it triggers an error. Checking session state fixes this.

Ensure user is logged when accessing saved searches

---

src/Log.php

Sometimes, log can contain an entry related to an itemtype that is no longer available. In my case, it was an entry containing `itemtype_link='PluginFieldsProfile#right'`, but the `fields` plugin was inactive.
Following error was triggered:
```
glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class "PluginFieldsProfile" not found in /var/www/glpi/src/Log.php at line 581
Backtrace :
src/Log.php:316                                    Log::getHistoryData()
src/Log.php:107                                    Log::showForItem()
src/CommonGLPI.php:689                             Log::displayTabContentForItem() …
```

Handle missing itemtype on log display

---

install/install.php
src/Console/Database/InstallCommand.php

Since PHP 8.1, `mysqli` errors are triggering errors instead of warnings (see https://php.watch/versions/8.1/mysqli-error-mode).
We already fixed some cases, but not all. For instance, creating a new DB from install process was not working anymore, due to following error:
```
glpiphplog.CRITICAL:   *** Uncaught Exception mysqli_sql_exception: Unknown database 'test' in /var/www/glpi/install/install.php at line 319
Backtrace :
install/install.php:319                            mysqli->select_db()
install/install.php:598                            step4()
```

Fix DB creation at install on PHP 8.1+

---

src/Dashboard/Widget.php
tests/units/Glpi/Dashboard/Widget.php

Prevent PHP warning
```
Warning: Undefined array key 26 in /mnt/diskhome/home///htdocs/src/Dashboard/Widget.php on line 419
Warning: Undefined array key 27 in /mnt/diskhome/home///htdocs/src/Dashboard/Widget.php on line 419
Warning: Undefined array key 28 in /mnt/diskhome/home///htdocs/src/Dashboard/Widget.php on line 419
Warning: Undefined array key 29 in /mnt/diskhome/home///htdocs/src/Dashboard/Widget.php on line 419
Warning: Undefined array key 30 in /mnt/diskhome/home///htdocs/src/Dashboard/Widget.php on line 419
```
Because ```multipleNumber``` can display can display as many lines as the user wants
but technically ```multipleNumber``` is limited to the number of characters in the alphabet (26)
| BC …

fix(Widget): prevent undefined array key from 'multipleNumber'

---

src/NotificationTargetContract.php

Forum post: https://forum.glpi-project.org/viewtopic.php?id=286792
There is no `account_number` field for contracts. The field should be `accounting_number`

fix contract account num field for notification

---

src/CommonGLPI.php
templates/components/form/header_content.html.twig

Apart from the "Restore" or "Delete permanently" button, the fact that an item is deleted is not currently UI impactful.
This proposal to further highlight this deleted status (an add deletion date).
Ticket header
Computer header
User header

feat: add deleted status on items header

---

src/Telemetry.php

According to RFC2616, version in `Server` header is optional. In such case, previous regex was not matching and webserver engine was not sent in Telemetry reports.
With proposed change, we will be able to collect data from servers that does not expose their version. As no server should expose its version in production, for security reason, I guess it could permit to collect much more data than now.

Enhance webservers telemetry reporting rate

---

src/CommonDBTM.php
src/RuleAsset.php
tests/functional/Glpi/Inventory/Inventory.php

Add 'tag' as criteria to ```RuleAsset``` engine
Add 'otherserial' action (```regex_result```) to ```RuleAsset``` engine
| Fixed tickets | !27588

Add 'tag' and 'otherserial' to RuleAsset

---

src/CommonITILObject.php
tests/functional/Glpi/ContentTemplates/TemplateManager.php

Tickets actors information are missing when using this task template as a predefined field:
After fix:
The fix was simply moving the `handleXXXXTemplateInput()` functions after the `updateActors()` call to make sure we are working with the latest data.
| Fixed tickets | !27636

Fix missing ticket actors in content templates

---

src/DbUtils.php
tests/fixtures/another_test.php
tests/fixtures/namespace_a_b.php
tests/fixtures/pluginfoo_search_a_b_c_d_e_f_g_bar.php
tests/fixtures/pluginfoo_search_item_filter.php
tests/fixtures/test_a_b.php
tests/functional/DbUtils.php

Handle namespace + item_xxx in `getItemTypeForTable `.
Before this change, when trying to get the itemtype of a  `glpi_namespace1_namespace2_items_filters` table, GLPI would try to load the `Glpi\Namespace1\Namespace2\Item\Filter` itemtype.
This itemtype is incorect as in the case of CommonDBRelation, we must keep the last '_' separator.
The correct itemtype would be lpi\Namespace1\Namespace2\Item_Filter`.

Fix getItemTypeForTable when using namespace + item_xxx

---

js/modules/Kanban/Kanban.js

Kanban load each users pictures to display using **synchronous** ajax requests.
This is problematic when you have a lot of tickets with 100+ different user pictures to load.
There is a gif example in the internal ref where the page takes 55 seconds to load because of this, as each images must be loaded one by one while the execution of the page is paused.
@cconard96 Can you confirm that this change (setting the request as asynchronous) is safe ? I see a few more `async: false` parameters in the same file, can they be removed as well ?
An even better improvement would be to get the picture directly from the main `action=refresh` ajax request:
It seems we already have all information needed in this endpoint, this would help reduce the amount of ajax requests by loading all the data at once. …

Improve Kanban performances when loading user pictures

---

src/CommonITILObject.php

Since the closed column for ITIL Kanbans are "drop only", the `getKanbanColumns` method was exiting early with an empty array which results in the JS code not adding any new columns. This meant that to see the column after selecting it under "Add Column", you had to refresh the page.

Fix showing closed column ITIL kanban

---

js/modules/Kanban/Kanban.js

Kanban filters were not reapplied after adding a new column. Newly shown columns would be unfiltered until the next background refresh or the filters were changed. Now, the filters are immediately re-applied after the new column is shown.

Reapply filters after showing Kanban column

---

src/OlaLevel.php

In the OLA, the option `Time to own` or `Time to resolve` was missing, whereas they are proposed in the SLA
| Fixed tickets | !27667

fix(ola): missing value in dropdown

---

src/CommonITILCost.php

Actually ```actiontime``` for ```CommonITILCost``` is a maximum of 1 day
Increase days to 50.
replace ```addfirstminutes``` by ```toadd``` to prevent countdown by minute for each hour of each day
| Fixed tickets | !27218

feat(Cost): increase action time from CommonITILCost

---

ajax/savedsearch.php
css/includes/components/_saved-searches.scss
src/SavedSearch.php
templates/layout/parts/saved_searches.html.twig
templates/layout/parts/saved_searches_list.html.twig

In 9.5 it was possible to manually order the list of saved searches, which was not possible since 10.0.
Before:
After:
| Fixed tickets | !27549

feat(saved search): restore the ability to order the list

---

src/Entity.php

| Fixed tickets | #13892
Add search option for the default contract field for entities. This is for displaying the related column only and not for searching. Since this is based on two fields, I'm not sure searching can be supported and none of the others using a separate strategy column are currently searchable.

Add default contract search opt

---

src/Plugin.php

This only affects the main branch as the bug was introduced with the feature to control Marketplace availability. The wrong class was being used to get the URL so the button would redirect you to a non-existent URL `/front/marketplace/controller.php`.

fix marketplace link

---

src/MassiveAction.php

Fix this issue with the API trying to render some progress bars in its output:
| Fixed tickets | !27735

API: Do not render progress bars when executing massive actions

---

src/Entity.php

Cannot merge 10.0/bugfixes branche into main due to SO ID duplication:
> Duplicate key 71 (Default contract/Satisfaction survey configuration (Change)) in Entity searchOptions!
Update search option was introduced a week ago in aba538ecd08f87879689e2912ea4f5015abb36b2 and was not part of a release, so changing it should not require a migration.

Fix duplicated Entity search option ID

---

src/Http/ProxyRouter.php
tests/units/Glpi/Http/ProxyRouter.php

| Fixed tickets | https://forum.glpi-project.org/viewtopic.php?pid=501077 
`Content-Disposition: attachment;` forces browser to download the file instead of displaying it inline. It may be a problem for some files, like HTML files. I propose to remove this header, so browser will decide itself whether the file can be rendered inline of downloaded.
Unless I miss something, webservers are not defining this header in their response when serving static files, so removing it will get us closer to the default behavior of a webserver.

Do not force download of HTML files

---

inc/define.php

| Fixed tickets | #14607
`is_helpdesk_visible` field is attached to `DatabaseInstance` item, not to `Database` item.

Fix helpdesk visibility filter on databases

---

js/common.js

Logic error when searching for form button to lock.

fix finding form button to lock

---

src/KnowbaseItem_Item.php

| Fixed tickets | see #14600
On helpdesk interface, `Knowledge base` tab was containing an unfiltered list of KB items, including all KB items related to current item, including those that were not published in FAQ. Clicking on links of non visible items was leading to an empty page.

Fix count and content of KB items tab

---

ajax/getUserPicture.php
js/modules/Kanban/Kanban.js

https://github.com/glpi-project/glpi/pull/14525 was not enough to fix the internal ref issue.
Long story short, https://github.com/glpi-project/glpi/pull/14525 fixed the image picture cache that is built from the `cards` data returned by the `load_column_state` ajax request.
However, the `cards` entry returned in this request do not contain all displayed cards, it only contains cards that where moved in the kanban (thus saving their custom positions).
This mean that we may have 0 cards returned by this request, which make our cache far less useful.
To fix this specific point and improve the overall performances, I've applied the following fixes:
The kanban code is already able to display a fallback picture with the `generateUserBadge` function.
I've forced all users pictures to be …

Improve kanban performances 2

---

src/ComputerVirtualMachine.php

From a host, GLPI adds a CSS class for VMs that have been deleted.
do the same from ```Computer```  when it changes ESX  (the link to the first one is deleted and a new one is created)

feat(VirtualMachine): display deleted link when needed

---

src/Plugin.php

I've noticed a while ago that the performances cost of plugins seemed to be a bit too high.
I can't tell if it was an exponential scale or not but the more plugins you had the slower GLPI would get.
I've decided to take a quick look at it today and managed to cut the plugins initialization process time by half.
There may be more optimizations to be found but it's a good first step.
This was done by moving some repetitive code that would be run multiple time with the same input into class properties that are only loaded once.
To benchmark the performances on my side, I've enabled about 20 plugins and added the code below to time the `plugin::init()` function, which is called once per page or ajax request and will load all the plugins.
```diff
diff --git a/src/Plugin.php b/src/Plugin.php …
```

Improve plugins init performances

---

templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/form_task.html.twig
templates/components/itilobject/timeline/pending_reasons.html.twig

There is some issues with the display of pending reasons depending on your screen size and the pending reason name length.
Issue 1:
Issue 2:
After changes:
Disable wrapping for the pending reason + pending toggle div:
Enable wrapping for the parent container div + some row-gap padding:
| Fixed tickets | !27887

Fix pending reason wrapping

---

inc/based_config.php
src/Marketplace/Api/Plugins.php
src/Marketplace/Controller.php
src/Marketplace/View.php

1. Use the new `/marketplace` endpoint.
On marketplace server side, endoints were a bit reorganized. Old endpoints are still supported, but the sooner we use the new ones in GLPI, the sooner aliases could be removed on marketplace server side.
2. Fix check on required offers in marketplace
GLPI expect `required_offer` key to be `null` when there is no required offer for a given plugin. When value is an array, it consider that an higher offer is required and prevent plugin to be downloaded. It requires a specific piece of code on marketplace server side, and I would like to remove it in the future.
3. Ensure marketplace …

Misc marketplace updates/fixes

---

src/NetworkEquipment.php

UUID was not available in the search
| Fixed tickets | !27900

fix(network devices): add UUID in search

---

src/Entity.php

User that have no recursive access to the current entity can't create any new entity (as the new entity would become a child of the current entity, which they would not be able to see).
Currently users stills have access to the create button in this case, which lead them to an empty page:
These changes prevent the create button to be displayed for these users (this also cover the "add child" action in the "Entities" tab of an already existing entity).
| Fixed tickets | !27898

Do not show create button for entities if no recursion

---

src/DbUtils.php

When viewing a list of tickets, debug mode enabled, I may get several errors:
```PHP Deprecated function (8192): strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/glpi/src/DbUtils.php at line 1580```
I don't have access to backtrace, but the fix seems obvious.

fix deprecation warning (found in 10.0.7)

---

templates/components/search/table.html.twig

```checkbox```  from ```allasset (global)``` view is not available because
```item``` from ```allasset (global)``` view is ```null```
This PR handle this case
| Fixed tickets | #14684

fix(core): display checkbox for allasset view

---

src/Lockedfield.php

There is no READ flag in profiles for this right, so api return an ERROR_RIGHT_MISSING

permit to query Lockedfield with api

---

js/common.js
js/webkit_fix.js
src/Html.php
tests/js/bootstrap.mjs

| Fixed tickets | #13433
When using a browser running Webkit, the first time you open a select2 dropdown the auto width does not apply. This seems like a bug in the Webkit engine. This PR adds a workaround when it detects an AppleWebKit user agent to close and then reopen the dropdown when the user tries opening it the first time.
Since this only happens for WebKit, I had to test this using Cypress with the experimental Webkit support. You should be able to test this fix using this branch which includes this fix along with a Cypress + Webkit setup:
https://github.com/cconard96/glpi/tree/fix/13433
1. Start Cypress with `npm run test:e2e`
2. …

select2 dropdownAutowidth workaround for webkit

---

templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/form_task.html.twig

#14660 fix some overflow issue by using wrapping and work great on followup edition:
However it's not great for followup **creation** as we have a grouped input with the "Add" button in this case so wrapping is not ideal:
I've fixed it by preventing wrapping in this case, as we have enough space here to display the full form in one line:
Edition mode is still using the wrapped version.
@orthagh I didn't forget our discussion about shortening the form by hiding/restricting the followup frequency dropdowns, still something I want to do but maybe later as this solution was a lot simpler for now.
We've also had some complains that the form footer change height when toggling the pending reason button.
This is because select2 dropdowns are a bit higher than our buttons, so displaying/hiding the …

Fix pending reasons wrap 2

---

src/Ticket.php
tests/functional/RuleTicket.php

When you have a rule whose criterion is the assignment of a group "XXX", the rule is triggered when you change the "assigned" field. If the value contains the group "XXX", the action is applied, even if this group was already present before the current update.
IMHO, the rule should only apply at the time of adding the group and not if you add more actors afterwards.
| Fixed tickets | !27454

fix(rule ticket): triggering action on actor update

---

src/CommonITILObject.php
templates/components/form/link_existing_or_new.html.twig

When creating a change from a ticket, the category of the original ticket was not automatically included in the new change.
| Fixed tickets | !27779

fix: missing category when change created from ticket

---

templates/components/itilobject/timeline/form_document_item.html.twig

| Fixed tickets | #11849
As most of instance uses formcreator for self-service ticketing and I'm in favor of simplification for ui, I though hiding completly the field should be ok.
Ping @tsmr

completly hide headings field in self-service interface when adding a doc to an existing ticket

---

src/Document.php

Fix handling of null values for newer versions of PHP when viewing a document that has no file attached. Encountered error while troubleshooting uploading a document from the API when the document was created but no file was attached.

Fix null handling for docs without files

---

src/Computer.php
tests/functional/Computer.php

```ComputerAntivirus``` item (attached to template) are no longer propagate when Computer is added from template.
| Fixed tickets | !27980

fix(Computer): fix antivirus not propagate from template

---

src/Cartridge.php
src/DisplayPreference.php
src/Profile.php
tests/functional/Profile.php

| Fixed tickets | #14481
Only some permission changes in profiles are being logged in the historical data. Rights must have a search option for their changes to be logged. This PR adds a test to ensure a search option exists for at least the basic rights that are displayed as a checkbox matrix. Most of this PR is moving the rights arrays from each `showForm*` method into a single, separate method so they would be known by the test.

Ensure rights have search options to allow historical logging

---

src/Html.php

If placeholder contains a simple quote, javascript is broken.

Fix select2 placeholder escaping

---

src/Html.php

This change allows a new selection "End of month" and "End of year" (like "Beginning of month" and "Beginning of year" already exist).

Allow End of month/year for future date selections

---

src/DeviceGeneric.php

https://forum.glpi-project.org/viewtopic.php?id=287073
Given the nature of generic devices, the type could contain valuable information and it should be shown in the components tab for a computer.

Add type for generic devices in components tab

---

src/Cache/CacheManager.php
tests/units/Glpi/Cache/CacheManager.php

See https://forum.glpi-project.org/viewtopic.php?pid=501487
Not sur how it could happen except when cache configuration is manually changed, but when a `translations` entry is present in cache config, it triggers errors on every GLPI script execution, and this error is not really clear (it does not says that this cache context is not supposed to be configured).
Adding a dedicated message could help to understand the issue. Also, I put this message to `NOTICE` level, so, by default, it would not be added in logs except on debug mode.

Clarify cache manager warnings

---

tools/build_glpi.sh

1. There is no more `.htaccess` files, so we can simplify the hidden files cleaning.
2. Some files are not existing anymore, they can be removed from cleaning list.
3. As vendor directory is not in public scope anymore, cleaning it for security reasons is not required anymore (people may accidentally expose the whole GLPI sources files, but IMHO, we could not handle such case as it has too many implications), but maintaining the cleaning list is a pain (I used to check vendor packages regularly, but it takes too many time).
I keep cleaning of `glpi-project/inventory_format` as we need some files only for dev purpose, and …

Remove some cleaning operations from build script

---

src/SavedSearch.php

occurs when checking html encoding via CLI.
```
$ ./bin/console diagnostic:check_html_encoding
Command execution may take a long time and should not be interrupted.
PHP Warning (2): Undefined array key "glpiactive_entity" in /home/bugier/public_html/glpi-100a/src/SavedSearch.php at line 355
PHP Warning:  Undefined array key "glpiactive_entity" in /home/bugier/public_html/glpi-100a/src/SavedSearch.php on line 355
Scanning database for items to fix...
No item to fix.
```
```
Backtrace :
src/CommonDBTM.php:628                             SavedSearch->post_getEmpty()
src/CommonDBTM.php:3429                            CommonDBTM->getEmpty()
src/CommonDBTM.php:3845                            CommonDBTM->isField()
src/SavedSearch.php:194                            CommonDBTM->rawSearchOptions() …
```

fix php warning (undefined session var)

---

src/Console/Ldap/SynchronizeUsersCommand.php

| Fixed tickets | #14677
As stated in the code, this mode does not handle deleted users:
https://github.com/glpi-project/glpi/blob/aa15da313a064a7d9a92e182f4119aeebf80d473/src/Console/Ldap/SynchronizeUsersCommand.php#L192-L195

Clarify LDAP sync "only update" mode

---

src/NotificationEventMailing.php

The mail queue cron will fail if there is a broken image in a ticket.

Notifications: avoid divide by zero exception

---

apirest.md

The repeated "AND NOT" operator is changed to "OR NOT".

Fix typo in search items 'link' parameter

---

templates/components/search/controls.html.twig

Fix export link

---

templates/components/form/inventory_info.html.twig

Display missing ```Last inventory update``` 
Before : 
After : 
refactor UI to display the information in three columns
| Fixed tickets | [See comment](https://github.com/glpi-project/glpi/issues/14735#issuecomment-1559260525)

fix(inventory): display last inventory update if needed

---

src/Ajax.php

Proof of concept to utilize the tab content already loaded instead of forcibly getting the content of every tab again for the All tab. This should eliminate all issues with duplicate IDs and duplicate initialization of JavaScript components, and simplify the server-side handling of this tab. This also allows the user to start filling a form in a tab, and finish it in the All tab. The downside is that loading the All tab may take longer because the loading of previously unloaded tabs would be done in individual requests.
New functionality when the All tab is selected:
1. Load the content of every other tab without forcing a …

Rework All Tab

---

src/Reminder.php

https://glpi.userecho.com/communities/1/topics/2106-clone-reminders
Allow cloning of reminders. All content and visibility targets are copied. I didn't let it copy the planning recall as I assume it would be changed anyway in most cases.

Clone reminders

---

src/NotificationEventMailing.php

Notifications are broken on `main`: 
There is a duplicated "References" header added twice, I've removed one occurrence.
Also we add the headers with two different methods :
* `$mmail->AddCustomHeader`
* `$mail->getHeaders()->addTextHeader()`
Not sure which one is correct, I've kept `AddCustomHeader` to keep things identical.

Fix duplicated header in notifications

---

front/smtp_oauth2_callback.php

At this point of code, polyfills are not yet loaded, so `str_contains()` function is not available.

Fix SMTP OAuth callback on PHP 7.4

---

ajax/kanban.php
src/CommonITILObject.php

Following #14525 and #14599.
I've found another bottleneck that was slowing down the loading of the kanban page.
Each columns are loaded by an ajax request, which will find all the tickets of that column.
Then, for each tickets found, we load some extra data (actors and linked tickets).
This quickly become a costly operation as it require at least ~10 extra SQL requests for each ticket to load this extra data (so for 100 tickets, you run 1000 extra queries).
I've improved the performances massively by bulk loading all the extra data using a few SQL queries.
Then for each ticket we can just reach for the data in the preloaded arrays.
The small downside is that we use a bit more of memory but it seems reasonable (8mb for ~500 tickets).
If memory become a problem for massive databases (which …

Improve kanban performances 3

---

ajax/massiveaction.php
front/inventory.php
front/massiveaction.php
src/Agent.php
src/Auth.php
src/AuthLDAP.php
src/Dashboard/Grid.php
src/Html.php
src/Infocom.php
src/Inventory/Asset/Software.php
src/Inventory/Conf.php
src/Inventory/Inventory.php
src/MailCollector.php
src/NotificationEventMailing.php
src/SavedSearch.php
src/SavedSearch_Alert.php
src/System/Status/StatusChecker.php
src/Toolbox.php
src/Transfer.php
tests/web/APIRest.php
tests/web/APIXmlrpc.php

See #14756.
PHP internal errors are not extending `\Exception`, but `\Error`. Both of them are implementing the `\Throwable` interface. When code is made to cache any error, it should then catch  `\Throwable`.
Tree of classes that are extending `\Error` and will not be catched by `catch(\Exception $e)`:
```
Error
ArithmeticError
DivisionByZeroError
AssertionError
CompileError
ParseError
FiberError
TypeError
ArgumentCountError
UnhandledMatchError
ValueError
```

Catch `\Throwable` instead of `\Exception`

---

src/Marketplace/View.php
src/Plugin.php
templates/components/plugin_uninstall_modal.html.twig

Added a confirmation modal before uninstalling the plugin.
Both "plugins" and "marketplace" views have been taken into account.

Confirmation before uninstalling a plugin

---

src/Document.php
tests/functional/Document.php

Requests on `document.send.php` with invalid  `$_GET['itemtype']` will trigger an error:
```
[2023-05-23 13:13:53] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class "this_class_does_not_exist" not found in /var/www/glpi/src/Document.php at line 919
Backtrace :
src/Document.php:726                               Document->canViewFileFromItem()
front/document.send.php:55                         Document->canViewFile()
public/index.php:73                                require()
```

Document::canViewItem(): validate itemtype

---

src/GLPIMailer.php
src/MailCollector.php
src/NotificationEventMailing.php
tests/units/GLPIMailer.php

When trying to send a lot of emails on our support, we often get the following email message:
```
Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/TroubleshootingSMTP
server error: QUIT command failed Detail: Too many login attempts, please try again later
```
At first I thought that we were sending too many mails at once (thus hitting the rate limit of our provider) but the error message actually mention too much "login attempts", not too much mails.
After checking the code we are indeed login in to the STMP server once for each mail to send, which seems unnecessary.
I think we should be able to login once and then send all our mails.  
The solution seem simple for this branch as the component we use cleanly separate the transport layer.
It it however not the …

Do not login to STMP for each mail

---

src/CommonITILObject.php
templates/components/itilobject/timeline/timeline.html.twig

Icon prefixing log entries was missing since merge of #14592 
bug:
fixed:
ping @FragDev, for your #14698 pr you need to declare `is_content_safe` also for your new timeline entry

fix log entries icon

---

src/CommonITILObject.php
src/DBmysqlIterator.php
tests/units/DBmysqlIterator.php

Issue introduced in #14333: `Search::addDefaultWhere()`  is used without the needed `JOIN` clause, which lead to invalid SQL requests.
This affect any user who can't see all the tickets and thus will have some conditions on external tables (linked user, groups, validation, ...) returned by `Search::addDefaultWhere()`.
| Fixed tickets | !27631

Kanban: add missing join

---

src/ReservationItem.php

Prevent dirty case with GenericObject: the plugin code has been deleted directly, so the data is still in the database.

fix(reservation): class not found

---

src/ReservationItem.php

When the user wants to filter the list of reservable items,
```Dropdown``` returns the list of ```itemtype``` for the current entity, without taking into account the notion of recursion.
Consequently, from a sub-entity, the itemtypes are no longer displayed.
The list below takes this recursion into account
from ```root``` entity
from ```sub``` entity
| Fixed tickets | !28076

fix(Dropdown): retrieve item recursivly

---

src/NotificationEventMailing.php

| Fixed tickets | see https://forum.glpi-project.org/viewtopic.php?pid=501795
`QueuedNotification` entries that were created before upgrade to GLPI 10.0.8 would produce an error without proposed patch.
```
CommonITILObject::getMessageReferenceEvent(): Argument #1 ($event) must be of type string, null given, called in /var/www/glpi/src/NotificationEventMailing.php on line 135
````

Fix handling of notifications queued before upgrade to GLPI 10.0.8

---

src/Search.php

```
PHP Deprecated function (8192): trim(): Passing null to parameter #1 ($string) of type string is deprecated in lhome/ubuntu/Dev/GLPl/10.O-bugfixes/src/Search.php at line 6689
```
| Fixed tickets | !28185

fix(user): prevent error message

---

package-lock.json
package.json

Replaces #14836 to target 10.0/bugfixes branch.

build(deps): bump @tabler/icons-webfont from 2.17.0 to 2.21.0

---

src/MailCollector.php

Mailbox ```folder``` with  emphasised character (like ```collège_saint_vincent```) are thrown an error (from ```Gmail``` , at least that's the only case reported so far)
```
[2023-06-05 08:34:34] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Storage\Exception\RuntimeException: cannot change folder, maybe it does not exist in /home/stanislas/TECLIB/DEV/GLPI/10.0-bugfixes/vendor/laminas/laminas-mail/src/Storage/Imap.php at line 387
Backtrace :
...r/laminas/laminas-mail/src/Storage/Imap.php:228 Laminas\Mail\Storage\Imap->selectFolder()
src/Toolbox.php:2193                               Laminas\Mail\Storage\Imap->__construct()
src/MailCollector.php:1405                         Toolbox::getMailServerStorageInstance()
src/MailCollector.php:698 …
```

fix(Receveir): handle folder with emphasised character

---

src/CartridgeItem.php
src/Certificate.php
src/CommonITILValidationCron.php
src/ConsumableItem.php
src/CronTask.php
src/DBAL/QueryFunction.php
src/SavedSearch_Alert.php
src/User.php

According to MySQL docs, `CURRENT_TIMESTAMP()` is an alias of `NOW()`. All current uses of it can be replaced by a `DATE_SUB` function using `NOW()`.

Replace CURRENT_TIMESTAMP

---

src/CommonITILObject.php

When an ```ITIL Object``` is linked to another, title column on list is at end of table 
The title is a link and it's not easy to click on it
This PR : 
- Split  ```ID``` and ```Status``` column
- Move ```title``` to start
Before : 
After : 

feat(view): move title (link) to start

---

CHANGELOG.md
src/Auth.php
src/AuthLDAP.php
src/RuleRightCollection.php
src/System/Status/StatusChecker.php
src/User.php
tests/LDAP/AuthLdap.php

| Fixed tickets | #14556
Meant to replace #14356

Enhance LDAP errors handling

---

src/Log.php
src/Search/Provider/SQLProvider.php

After some research, it looks like the references to `glpi_auth_tables` have been dead since 2012 (45a340e63847cbda93e1f3cdfd5d8591a977e137) and they used to be for a non-existent "virtual" table.
There is no search option in the core that uses this non-existent table. The only references in plugins that I have found exist in `printercounters` and that is only because it looks like their `inc/search.class.php` is a copy of the Search engine in the core with some modifications added on top.

Drop glpi_auth_tables references

---

src/Plugin.php
tests/functional/Plugin.php

Since #14511, I figured out that, as long as one plugin is active, the `setup.php` file of all plugins are loaded on each GLPI page/script, even these corresponding to inactive plugins. This is not a new behaviour, but it is, IMHO, a bug. Indeed, unless on plugins administration pages, we should not load files from inactive plugins. For instance, on my development instance, I have dozens of inactive plugins in a custom directory I declared in `PLUGINS_DIRECTORIES` and some of them are generating errors because they expect to be in `plugins` directory (e.g. `PHP Warning (2): …

Prevent all plugins to be scanned everytime

---

css/includes/components/itilobject/_timeline.scss
inc/relation.constant.php
install/empty_data.php
install/migrations/update_10.0.x_to_10.1.0/itilautobumps.php
install/migrations/update_10.0.x_to_10.1.0/itilreminders.php
install/migrations/update_10.0.x_to_10.1.0/notifications.php
install/migrations/update_10.0.x_to_10.1.0/pendingreason.php
install/mysql/glpi-empty.sql
src/Central.php
src/CommonITILObject.php
src/ITILAutoBump.php
src/ITILReminder.php
src/ITILSolution.php
src/NotificationTargetCommonITILObject.php
src/PendingReason.php
src/PendingReasonCron.php
src/PendingReason_Item.php
templates/components/form/pending_reason_is_default.html.twig
templates/components/itilobject/timeline/filter_timeline.html.twig
templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/pending_reasons.html.twig
templates/components/itilobject/timeline/timeline.html.twig
templates/components/itilobject/timeline/timeline_item_header_badges.html.twig
templates/dropdown_form.html.twig
tests/functional/PendingReason.class.php

The main idea is to remove the reminder follow-up and introduce a new, more discreet element to replace them.
In addition, there are several minor changes.
**1. Rework of pending reasons**
* Use a new distinct type ITILAutoBump in ITIL objects timeline
* Add new table structure for glpi_itilautobumps
* Display information concisely in timeline format
* Add new filters and notification events
**2. Miscellaneous changes**
* Taking into account the calendar to avoid reminders on non-working days
* Define a default pending reason that is automatically pre-selected in follow-ups
* Resolution without follow-up

Rework of pending reasons

---

CHANGELOG.md
install/migrations/update_10.0.x_to_10.1.0/authldap.php
install/mysql/glpi-empty.sql
src/AuthLDAP.php
src/CommonDBTM.php
src/Document_Item.php
src/NotificationEventAbstract.php

There used to be an Entity tab for the AuthLDAP form, but it has been commented out since 2014 (859058b22de6c356c891fb0f2d19ede63bd1493d). There are `entity_field` and `entity_condition` fields that are only used in the display of this "hidden" tab. They should be safe to finally remove completely now.
Two other very minor removals:
1. The unused $fkfield CommonDBTM property
2. Special handling in NotificationEventAbstract that was marked for removal in 9.5

Drop unused AuthLDAP entity code (and misc)

---

src/RichText/RichText.php

Fix bad handling for ```ol``` DOM 
| Fixed tickets | !28000

fix(RichText): Correct handling of DOM ol li

---

src/RuleAsset.php
src/RuleTicket.php

Fix bad label for asset rules and make the long label the same to keep them in the same column.

Fix and unify parent business right labels

---

templates/components/itilobject/actors/field.html.twig

| Fixed tickets | #14881
According to https://github.com/glpi-project/glpi/blob/10.0.7/src/Ticket.php#L4337, entities are only imported from requesters, not others actors.
So we should only reload form for ticket creator for requester (and avoid in some case long waiting page load)

only reload create ticket form for requester actors (not observer/tech)

---

src/Html.php

In Formcreator, we may have textarea fields with uploads enabled **and** without showing an area to drop files. 
With this context, if someone uploads a too big image (usually 2MB), the upload is rejected, but no feedback is provided to the user. The file seems uploaded successfully because it appears in the text area, and its name shows below it.
(test picture credit: a wallpaper picked [here](https://www.pexels.com/photo/reflection-of-mountain-on-lake-braies-1525041/) by Fancesco Ungaro) size : 5 MB.
With the patch, the upload failure becomes visible
| Fixed tickets | internal ref 28203

Ensure upload failure messages are always displayed

---

src/Profile_User.php
tests/functional/Profile_User.php
tests/functional/Transfer.php

When a profile is attached to a user account, it is defined by both entity and the profile itseilf. Actually, only this second part is logged to the user history and this information is meaningless without the entity environment it is attached to.
The proposd approach is probably not the best one and any other way to do this is welcome.

Log full profile information to user record on profile add or suppression

---

src/NotificationEventMailing.php

| Fixed tickets | see #14901
It is probably an edge case, but documents handling in notifications does not correctly handle missing documents in DB.
Whitespace changes should be ignored to make review easier.

Handled missing document entries in notifications

---

src/RichText/RichText.php

| Fixed tickets | !28020
Alternative to #14758.
`PhotoSwipe` is encoding special chars in images URLs. We need to ensure that "raw" URLs are passed to `PhotoSwipe` to prevent double encoding issues.

Fix image gallery

---

install/migrations/update_10.0.7_to_10.0.8/rule.php
src/Inventory/Asset/OperatingSystem.php
src/RuleDictionnaryOperatingSystem.php
src/RuleDictionnaryOperatingSystemArchitecture.php
src/RuleDictionnaryOperatingSystemEdition.php
src/RuleDictionnaryOperatingSystemServicePack.php
src/RuleDictionnaryOperatingSystemVersion.php

"Replay the dictionary rules" 
no longer works since https://github.com/glpi-project/glpi/commit/3c8c655d207d893dae07e3e854492580a27c9cd2
Because the feature use "generic" field name ```['name']```.
But 
- ```RuleDictionnaryOperatingSystemCollection```
- ```RuleDictionnaryOperatingSystemVersionCollection```
- ```RuleDictionnaryOperatingSystemServicePackCollection```
- ```RuleDictionnaryOperatingSystemEditionCollection```
have been updated so that the ```name``` key is no longer used, but instead ```os_name```, ```os_version_name``` etc ....
This PR revert this change to keep generic behavior
| Fixed tickets | !28216

fix(RuleDictionnary): keep main key 'name'

---

ajax/timeline.php

When changing status of a task in the timeline by checking its box, the status is changed even if update function hasn't changed it.
Example:  - update fails 
- plugin [hooks](https://glpi-developer-documentation.readthedocs.io/en/master/plugins/hooks.html) interrupts it (I'm using behaviors plugin to control that fields are filled). 
I propose to recall the status from DB after the update of the task to be sure of its value.

Task Status is changed when update fails in timeline

---

src/ReservationItem.php

| Q | A
| --- | ---
| Implemented tickets | [UserEcho 2149](https://glpi.userecho.com/communities/1/topics/2149-allow-filtering-by-location-when-looking-for-a-free-item-in-a-specific-period-reservation-tool)
This PR is to implement the suggested feature of being able to filter by location when searching for a free item to book.
I did not used a location dropdown that gives the user the ability to set "is", "is not", "under" or "not under" criteria and simply used a "under" (inclusive) operator.
The added code re-use existing location dropdown system and sub/child location fetching.
I hope the code style is compliant with GLPI's standards (we'll see what the CI think of it very soon).

Adding a location-based filter on reservation search tool

---

src/Problem.php

handle HTML from searchoption
- causes
- impacts
- Symptoms
before : 
after : 
| Fixed tickets | !28356

fix(Problem): handle HTML from searchoption

---

src/CommonITILObject.php
src/Dropdown.php
templates/components/itilobject/actors/field.html.twig
templates/components/itilobject/actors/main.html.twig

When a person does not receive a notification for a ticket, people usually check if the email address is set correctly in the corresponding actor's notification settings. In GLPI 10.0, the value of the `alternative_email` field of an actor is no longer forced with the default email of this actor. In this case, when the modal notification setting is opened, the field is empty (see screenshots below) and users think that is why their user did not receive notifications. This is not a correct statement, as their user will receive a notification on their default email.
To clarify this behaviour, I added a placeholder that …

Display actor default email as input placeholder

---

templates/pages/management/softwarelicense.html.twig

From GLPI 9.5
License form on update display software link instead of ```dropdown```
this PR implement same behavior on GLPI 10
this avoids the refresh problem when changing the selected dropdown item (works correctly on add)

fix(License Form): Display link on update instaed of dropdown

---

src/Api/HL/Controller/AdministrationController.php
src/Api/HL/Controller/AssetController.php
src/Api/HL/Controller/ComponentController.php
src/Api/HL/Controller/ITILController.php
src/Api/HL/Controller/ManagementController.php
src/Api/HL/Controller/ProjectController.php
src/Api/HL/Middleware/ResultFormatterMiddleware.php
src/Api/HL/OpenAPIGenerator.php
src/Api/HL/Router.php

Add simple response middleware for new API to optionally transform the JSON output into CSV or XML format to ease the integration of external systems.

Add simple API response formatter middleware

---

src/Domain.php

| Fixed tickets | #14938
The Domain table should be used instead of the entities table. Using the entity table results in it returning that entity's parent ID instead.

Fix table used for Domain entity ID search option

---

src/RuleCollection.php

In some cases, criteria patterns and action values can be blank in the exported XML. When it get decoded during import, it is treated as an empty array so a runtime error is thrown as it would have been an empty IN clause when creating the SQL.
Related forum post:
https://forum.glpi-project.org/viewtopic.php?id=287315
Sample dictionary rule with issue:
```xml
<rule>
<entities_id>Root Entity</entities_id>
<sub_type>RuleDictionnarySoftware</sub_type>
<ranking>1</ranking>
<name>Freeplane</name>
<description></description>
<match>AND</match>
<is_active>0</is_active>
<comment></comment>
<is_recursive>0</is_recursive> …
```

Prevent empty IN error during rule import

---

src/Api/HL/Controller/ManagementController.php
src/Document.php
src/Toolbox.php

Similar to the legacy API, sending a request to the `/Management/Document/{id}` endpoint with an `Accept` header of `application/octet-stream` will tell the server to respond with the file contents instead of the metadata.
Sending a HEAD request with the `Accept` header for downloading a document will respond with the correct headers but without the content.
`Toolbox::sendFile` was modified to accept a new parameter to allow the returning of a Response object rather than having the headers and content sent directly.

HL API Allow document download

---

src/Api/HL/Controller/ITILController.php
src/Api/HL/Controller/ManagementController.php
src/Api/HL/RSQLInput.php
src/Api/HL/RoutePath.php
src/Api/HL/Search.php
tests/functional/Glpi/Api/HL/Controller/ITILController.php

Needed for #14916 
New:
- Changes timeline item handling to use schemas like every other type.
- Expands the fields for the ITIL type schemas
Fixes:
- Improve RSQL filter handling to skip empty filters
- Remove 'Log" as a timeline item type (Makes more sense to globally handle history)
- Fix issue where each RSQL filter processed would overwrite the array of filters instead of appending (only the last filter would be saved)
- Improve reliability of `RoutePath::getRoutePathWithParameters` by ignoring any array or object parameters passed. These parameters are never valid for the URL so it makes no sense to try and replace …

Improve ITIL timeline API endpoints

---

src/Search.php

If additional columns are added for display through the front/user.php page, in particular Number of tickets as requester and Entities (Profile) or Profiles (Entity), displaying users with a lot of tickets increases significantly the amount of memory used in php and eventually goes over the max allowed memory limit (significantly = +/- 60Mio or more per user).
As additional bug, AJAX code fails and does not allow to increase the number of entries to display on the page. 
The reason is a per ticket concatenation of identical values  related to entities and profiles in the sql result.

Preventing php memory saturation from user.php page

---

css/includes/_highcontrast.scss

When high contrast is enabled, there is almost no difference between a checked or unchecked box
Before:
After:

fix: checkbox with high contrast

---

src/GLPIMailer.php

I've been trying for a while to understand why some notifications have a poor HTML rendering in Outlook.
- GLPI Notification template translation
```sql
+----+--------------------------+----------+---------+--------------+--------------------------+
| id | notificationtemplates_id | language | subject | content_text | content_html             |
+----+--------------------------+----------+---------+--------------+--------------------------+
| 35 |                       36 | fr_FR    | toto    | a            | &#60;p&#62;a&#60;/p&#62; |
+----+--------------------------+----------+---------+--------------+--------------------------+
```
- Generated notification
```sql
MariaDB [preprod]> select * from glpi_queuednotifications where id = 44659 \G
*************************** 1. row …
```

fix(notification): force `quoted-printable` encoding

---

ajax/priority.php
src/CommonITILObject.php
templates/components/itilobject/fields/priority_matrix.html.twig

Javascript error that trigger when you set impact as hidden in your ticket template and try to edit the urgency dropdown (or the opposite).

Fix priority JS error when using hidden impact/urgency

---

src/Rule.php
src/RuleCollection.php
tests/functional/RuleTicket.php

The rule engine may be executed multiple times for one action due to some post_addItem code.
For example, consider this backtrace:
One user action (ticket creation) resulted in 3 database operation (one add and two update) for the ticket object.
The issue is that the rule engine use some kind of cache so the first operation (add) load the rules defined for "on add", which are then reused for the 2nd and 3rd operation despite being updates.
The test case show a concrete example that can be easily reproduced (the test will fail if you remove the changes).
Also fixed some lint warnings.
| Fixed tickets | !28287

Prevent invalid rules to be executed

---

src/Html.php

If the user sends a file to GLPI and then tries to submit the form, 
The added element may be truncated (especially images) 
Nothing prevents the user from adding the element, even if the file has not been fully uploaded.
| Fixed tickets | !28447

fix(upload): prevent form submit during file upload

---

src/CommonITILObject.php

| Fixed tickets | see #14585
See #14585. For some unknown reason, a `Document_Item` entry may be linked to an unexisting document. I do not know if it is caused by a plugin, a bug in mail collector, or something else, but this case should be handled to prevent timeline to be broken.

Prevent orphan documents to break ITIL timeline

---

src/Calendar.php
src/LevelAgreement.php
tests/functional/SLM.php

| Fixed tickets | !28382
When SLA/OLA had a definition time in days (e.g. must be resolved within 5 business days), the wait time calculation was not excluding closing hours and holidays during its computation and its restitution.
The behaviour of `Calendar::getActiveTimeBetween()` when using `$work_in_days=true` parameter does not make really sense as it returns both active (business hours/days) and inactive (closing hours/days and holidays) time. I renamed it to make things clear, and I guess we could remove it in GLPI 10.1 as it is not used anymore (plugins are not using this param).

Fix SLA waiting time duration

---

src/Config.php

| Fixed tickets | see !28461
Fix a non blocking SQL error, introduced in GLPI 10.0.0 by #11085, that appears in CLI update from GLPI < 0.85.
Visible in our test suite:

Fix error during update from GLPI < 0.85

---

install/migrations/update_10.0.7_to_10.0.8/ram_field.php

Until #14965, `glpi_computervirtualmachines.ram` was not nullable. To be able to update `''` values to `null`, field must first be made nullable.
```
SQL Error "1048": Column 'ram' cannot be null in query "UPDATE `glpi_computervirtualmachines` SET `ram` = NULL WHERE `ram` = ''"
SQL Error "1366": Incorrect integer value: '' for column 'ram' at row 4 in query "ALTER TABLE `glpi_computervirtualmachines` CHANGE `ram` `ram` int unsigned DEFAULT NULL   "
```

Fix RAM field migration

---

src/Session.php
tests/units/Session.php

GLPI base its cookie name on the `glpi` folder path.
This mean two GLPI with identical server path will have the same cookie name, which is an issue if they are on the same domain as cookies must be unique per top level domain name (so `test.domain` and `prod.domain` can't use the same cookie names).
Fixed by using additional data from `$_SERVER['HTTP_HOST']` and `$_SERVER['HTTP_PORT']` to get unique cookies name depending on the full domain name and port.
The port part was requested by @cedric-anne as he told me it would solve some issues when using multiple docker instances.
Note : the `instance_uuid` field from GLPI's config would be even better but we can't access it from this function as `$DB` is not yet initialized.
| …

Fix non-unique cookie name for the same domain

---

src/CommonITILObject.php
src/Project.php

The name field wasn't being retrieved/used to calculate the display name for users so if they had no first name or real name, an empty string or just the ID was shown depending on the user preference for showing IDs. This PR fixes that an allows the username to show in this case, as was originally intended.

Fix missing names on Kanban for users with only usernames

---

templates/layout/parts/page_header.html.twig

```navbar-brand-autodark``` use when dark mode is enabled (with ```auror dark```, ```darker```, ```midnight``` css) alters the rendering of the logo added from the ```branding``` plugin.
because of ```autodark-image``` mixin call by ```navbar-brand-autodark```
```css
@mixin autodark-image {
filter: brightness(0) invert(1);
}
```
Before : 
After : 
| Fixed tickets | !28491

fix(css): fix logo with dark mode

---

src/Rule.php

It is probably not a valid rule, but if pattern is null, then an error is triggered.
```
*** Uncaught Exception TypeError: Argument 1 passed to Glpi\Toolbox\Sanitizer::getVerbatimValue() must be of the type string, null given, called in /srv/glpi/src/Rule.php on line 2335
```

Fix error when rule pattern is null

---

ajax/reservations.php
front/helpdesk.public.php
js/reservations.js
src/Html.php
src/Reservation.php
src/ReservationItem.php

| Fixed tickets | !28443
Added the ability to view reservations with the `READ` right.
Until now, the `ReservationItem::RESERVEANITEM` right was required to display reservations.
The `READ` right was already present but had no effect.

Fix "read" right for reservations

---

src/Html.php
src/Session.php

When a user changes their profile in GLPI, the current page is reloaded. However, the new active profile does not guarantee that the user has the necessary rights to view the page, which can result in a permissions error. This pull request aims to address this issue by redirecting the user to the homepage if they lack the required rights. If the user has the necessary rights, no changes are made.

Add redirection if user lacks rights to view the page upon profile change

---

js/common.js

At some point, the submit once feature for forms broke. It seems the common.js script is loaded before the body element ready so the event listener is not properly added. This issue was noticed by @kabassanov during the login process when a mobile browser was automatically filling the login details and submitting the form (unknown at the time) and he was also manually pressing the Sign In button. The automatic action was consuming the CSRF token, while the later manual action was cancelling the first and trying to re-submit with an then-invalid token.
This PR delays the event listener binding until after the DOM is ready …

Fix double form submission protection

---

inc/relation.constant.php
src/CommonDBTM.php
src/Item_OperatingSystem.php
src/OperatingSystem.php
src/RuleDictionnaryDropdownCollection.php
tests/functional/Glpi/Inventory/Assets/OperatingSystem.php

Bug found after https://github.com/glpi-project/glpi/pull/14897
bad relation declared from ```relation.constant.php```
```_glpi_items_operatingsystems``` instead of ```glpi_items_operatingsystems```
See other relation like 
```php
'glpi_operatingsystemservicepacks' => [
'glpi_items_operatingsystems' => 'operatingsystemservicepacks_id',
],
'glpi_operatingsystemversions' => [
'glpi_items_operatingsystems' => 'operatingsystemversions_id',
],
'glpi_operatingsystemkernels' => [
'glpi_operatingsystemkernelversions' => 'operatingsystemkernels_id',
],
'glpi_operatingsystemkernelversions' => [
'glpi_items_operatingsystems' => 'operatingsystemkernelversions_id',
],
```
and when an ```OperatingSystem``` is purged GLPI purged ```Item_OperatingSystem``` too.
Behavior not equal to …

fix(dictionnaryOS): fix repaly rule on existing data

---

src/DBmysql.php
tests/units/DB.php

Add support for `INSERT INTO ... SELECT` type of query.
Given the following query from the escalade plugin:
```php
$query_users = "INSERT INTO glpi_tickets_users
SELECT '' AS id, $newID as tickets_id, users_id, type, use_notification, alternative_email
FROM glpi_tickets_users
WHERE tickets_id = $tickets_id AND type != 2";
```
The current solution to replace this raw query would be to first make the `SELECT` query and then iterate the results and make individual `INSERT` queries for each result. Depending on the amount of data, this could be a performance issue.
This PR allows you to specify a `QuerySubQuery` in place of …

Support insert into select queries

---

front/reservation.form.php

When a reservation form is sent without a defined item, an error occurs.
Form :
or
Error

Fixed an error when sending a reservation form empty.

---

src/Inventory/Asset/OperatingSystem.php
tests/functional/Glpi/Inventory/Assets/Software.php

```operatingystems_id``` used by ```SoftwareVersion``` comes from ```\Glpi\Inventory\Asset\OperatingSystem->getId()```
But from ```OperatingSystem``` when an ```OS``` is handled, ```getId()```  return ID of link between ```Computer``` and ```OS```
```php
$this->operatingsystems_id =  $ios->fields['id'];
``` 
| Fixed tickets | !28498

fix(inventory): fix ID keep in memory (and use from SoftwareVersion)

---

src/Inventory/Asset/Software.php

```date_creation``` is not filled (for ```Software``` and ```SoftwareVersion```) during inventory step.
This Pr fix this.
| Fixed tickets | !28498

fix(inventory): set date creation when needed

---

js/modules/Debug/Debug.js
templates/components/debug/debug_toolbar.html.twig

The arrows are reversed to open or close the debug bar.
Before (when debug bar is collapsed) : 
After  (when debug bar is collapsed)  : 

fix(DebugBar): reverse arrows

---

src/CommonITILObject.php
tests/functional/NotificationTargetTicket.php

| Fixed tickets | #14102
The timeline items are ordered using their `date` field value. This field is editable for tasks, and it may result in unexpected order in timeline.
For instance, if user put a date in the future, here is the result:
Ordering items by `creation_date`, when this field exist, solves the issue.

Fix timeline items order

---

.webpack.config.js

When using compiled CSS files, there are requests being made to for `/css/lib/fontsource/inter/files/inter-all-*-normal.woff` files which are not present. The webpack config only copies the `woff2` font files and the "all" fonts are not available as woff2. These missing fonts are referenced in `/css/lib/fontsource/inter/scss/mixins.scss`.

fix missing inter-all fonts

---

src/Computer.php
tests/functional/Glpi/Inventory/Assets/Computer.php

To avoid updating a manual element into a dynamic one
```is_dynamic``` propagation need to be done switch related item (cf : ```Monitor```) and not from mainasset (cf : ```Computer```)
| Fixed tickets | !27194

fix(Computer): fix is_dynamic source

---

src/Ticket.php
tests/functional/Ticket.php

In the simplified interface, the summary showing the number of tickets for each status is incorrect.
The counters do not take into account tickets where the user is an observer, even though they appear in the list.
Summary with the number of tickets for each status. "Processing" is set to 0.
But if you click on "Processing", the list includes a ticket where the user is an observer.
| Fixed tickets | !28453

Fix ticket counter in simplified interface

---

src/IPNetwork.php

```$WHERE``` are computed with ```for``` statement
but actually ```$WHERE``` overwrites the previous value
This Pr fix this

fix(IPNetwork): fix WHERE clause from ITERATOR query

---

src/Api/HL/Controller/AdministrationController.php
src/Api/HL/Search.php
src/Toolbox.php
tests/GLPITestCase.php
tests/functional/Glpi/Api/HL/Controller/AdministrationController.php

Add `picture` download URL to User schema.
Add endpoints to get a user's picture as a binary response:
1. /User/me/Picture
2. /User/{id}/Picture
3. /User/username/{username}/Picture
Fixed:
- Retrieving a field that is mapped from itself (like transforming the internal picture path to the download URL)

Get user pictures from API

---

src/CommonITILObject.php
src/NotificationTargetCommonITILObject.php
tests/functional/NotificationTargetTicket.php

When a ```requester``` have 2 profiles
- ```self-service```
- ```tech``` (without see private followup)
Notification contain private followup
why ?
When ```NotificationTargetCommonITILObject``` call ``` $item->getTimelineItems($options);```
With this options
```
$options = [
'with_documents'    => false,
'with_logs'         => false,
'with_validations'  => false,
'expose_private'    => $show_private,
'bypass_rights'     => true,
'sort_by_date_desc' => true,
'is_self_service'   => $is_self_service,
];
```
```$show_private``` is ```false``` because it's computed according to the profiles that have the right to ``ITILFollowup::SEEPRIVATE``.
```$is_self_service``` is ```false```, because ```requester``` have one profile with ```interface``` = ```central``` (tech)
First option …

fix(Notification): prevent private item exposure from notification

---

css/includes/_base.scss
templates/components/form/basic_inputs_macros.html.twig
templates/components/form/fields_macros.html.twig

| Fixed tickets | [#14852](https://github.com/glpi-project/glpi/pull/14852)
Add a new twig macro to create a button.
To use it, simply enter its label, name and type. You can also add the button class and an icon.

move html inputs macros to a dedicated file

---

src/ITILCategory.php
tests/functional/ITILCategory.php

When categories were updated via a massive action, the code field was emptied.
| Fixed tickets | !28567

fix(category): code lost when updated by a massive action

---

src/Api/HL/Search.php

For joined data returned from the API, we need the unicode character `0x1D` to be used as the separator, not "0x1D" string.

Fix API search join character

---

src/Dashboard/Dashboard.php
src/Dashboard/Grid.php

Dashboard cards are cached depending on the card's options and the current entity.
The cache key should also take into account the current profile as different rights will lead to different results that should thus use an unique cache key.
Exemple using one super admin account + a technician account on the same entity.
The super admin can see all tickets (~1000) while the technician can only see 28.
If the super admin load the dashboard first, it will display 1k tickets for both users:
On the other hand, if the technician load the dashboard first, it will display 28 tickets for both users:
| Fixed tickets | !28420

Prevent dashboard cache collisions

---

src/Api/HL/Search.php

In the new API, when a property added within a join uses a property name different than the column name, the SQL column was not being properly calculated from the `x-field` property.
Not currently used by the core, but was used with the API integration of the VIP plugin:
https://github.com/pluginsGLPI/vip/pull/5

Fix column remap for joined properties

---

src/Search/Provider/SQLProvider.php

For some search plugin hooks, only an empty string would prevent adding an empty QueryExpression to the criteria, but null needs to be handled too.

fix handling search data from plugin hooks

---

ajax/knowbase.php
src/Knowbase.php

The tree state was not saved and was reset each time the page was reloaded. So it always came back to the root category.
_Does not concern `main` branch_
| Fixed tickets | !28580

fix(knowbase): save tree browser

---

src/CommonDBTM.php

When we try to purged a ```Computer```
GLPI try to clean all relation data ```CommonDBTM->cleanRelationData()```
When handle ```IPAddress``` this method redefine key because ```IPAddress``` relationship that does not respect naming conventions
```mainitemtype``` and ```mainitems_id``` are used instead of ```itemtype``` and ```items_id``` 
It's down when current purged object is ```IPAddress``` but not when the table concerned by purged is ```glpi_ipaddresses```
GLPI therefore generates this request
```sql
SELECT * FROM `glpi_ipaddresses` WHERE (COMPUTER_ID)
```
because of bad criteria
```php
Array
(
[FROM] => glpi_ipaddresses
[WHERE] => Array
(
[0] => COMPUTER_ID
)
)
```
which returns all IPs
in the rest of the purge process, GLPI loops over all the IPs
This PR fix this 
| Q             | …

fix(purge): prevent SQL query with 'true' on WHERE clause

---

front/css.php

On PHP 7.4, SCSS compilation was failing when no cache was present due to lack of memory.
It seems that memory required to compile SCSS file increased since we added this workaround in #10487.

Fix SCSS compilation failure on PHP 7.4

---

src/Application/ErrorHandler.php

When error handler tries to record an error trace, if the log file is not writable, it throw an exception that is not catched. Result is often the display of an empty 500 error page, without anything that could indicate that there is problem with log files permissions.
Also, depending on the `error_reporting` level, even a simple deprecation "error", that should not be blocking, could result in such a 500 error.
I propose to catch log operations error and, in such case, display an error message in the interface.
Here is an example of what would be shown by an error generated by the following patch:
```diff
diff --git …
```

Handle failure during error log operation

---

templates/pages/admin/inventory/agent.html.twig

| Fixed tickets | #15036
items_id wasn't being added to the form because of a typo and a blank string was present instead, so updates were failing as it tried to replace the items_id with a string in an int column.

fix agent form save

---

src/PrinterLog.php
tests/functional/PrinterLog.php

1. Filtering logic expect logs to be ordered by date, but default order in database is based on `id` and it can lead to unexpected results whn logs are not created in the expected order (this is the case in the test suite). I added the `ORDER => date ASC` to fix this.
2. The loop that adds logs in the past 21 days can create logs on 1 or 2 months, depending on the current date. This affects the "logs by month" results. To prevent issues with that, I added a log entry for the previous month to ensuire we always have the same count of months in log entries.

Fix printer log tests

---

css/includes/components/itilobject/_timeline.scss
templates/components/itilobject/timeline/sub_documents.html.twig

Issue visible in !26398#ITILFollowup_123123, when a lot of screenshots are attached to a followup in the timeline, no wrap is present and so width continues to grow. It increase also the length of parent followup and text may start to be unreadable (very long lines)

prevent sub documents to break timeline layout

---

src/RichText/RichText.php
src/Search.php
tests/units/Glpi/RichText/RichText.php

preserve  ```>```  (only needed for Entity ```completename``` (becasue of HTML use) other ```dropdown``` are not affected)
preserve line breaks (like GLPI 9.5 export)
See result : 
| Fixed tickets | !28620

fix(export): preserve line breaks and > from completename

---

css/includes/components/_debug-toolbar.scss
js/modules/Debug/Debug.js

Somes changes suggested by @cedric-anne regarding formatting :
* Round X.00 values
* Always use spaces before units
* mio -> MB
I've also replaced the HTML tables by [tabler's datagrids](https://tabler.io/docs/components/datagrid) + added some margins/padding + reduced titles to h2.
Server perf before:
Server perf after:
Client perf before:
Client perf after:

Debug bar formating + Use datagrid instead of html tables

---

src/Dropdown.php
tests/bootstrap.php
tests/functional/Dropdown.php

| Fixed tickets | part of !27844
`Search::makeTextSearchValue()` unsanitizes input, and changint it may have unexpected side effects. The problem with this is that a users that is searching for `>`, `<` or `&` values in dropdowns will not find matches, as these chars are, most of the time, encoded in DB.
To be sure to find all expected results, we have to search for both raw and encoded values.

Fix dropdown results when searching for `>`, `<` or `&` chars

---

src/Agent.php

Revert https://github.com/glpi-project/glpi/pull/15090
```TAG``` search already exists
```php
$tab[] = [
'id'         => 901,
'field'      => 'tag',
'name'       => __('Tag'),
'datatype'   => 'text',
] + $baseopts;
```

fix(inventory): remove duplicate TAG searchOption on computer

---

src/CommonDBTM.php
tests/functional/Glpi/Inventory/Assets/Computer.php

When inventory handle an asset for the first time (creation)
when GLPI ```cleanLockedsOnAdd```
if a global lock on ```entities_id``` exist for this ```itemtype```, this ```key``` ```entities_id``` is unset from ```$this->input``` 
and trigger a PHP warning during unicity check
```shell
[2023-07-03 11:46:15] glpiphplog.WARNING:   *** PHP User Warning (512): Missing entity ID! in /home/DEV/GLPI/10.0-bugfixes/src/CommonDBTM.php at line 4485
Backtrace :
src/CommonDBTM.php:4485                            trigger_error()
src/CommonDBTM.php:1322                            CommonDBTM->checkUnicity()
src/Inventory/Asset/MainAsset.php:697              CommonDBTM->add()
src/RuleImportAsset.php:988                        Glpi\Inventory\Asset\MainAsset->rulepassed()
src/Rule.php:1525 …
```

fix(inventory): prevent 'Missing Entity ID' warning

---

src/DisplayPreference.php
src/Search.php

Fix a small regression introduced in #14947 which trigger an exception for search options added by plugins.
As seen with @cedric-anne, the format used in `Search::&getOptions()` to store theses plugin search options was incorrect.
We've also added a safety check in the `nameOfGroupForItemInSearchopt` method to avoid failure even if the data's format is incorrect.

Fix plugin search options display

---

src/CommonITILObject.php
tests/functional/Ticket.php

Actors of a ```CommonITILObject``` object are not cloned

fix(CommonITILObject): clone actors

---

ajax/debug.php
src/Debug/Profile.php

Debug profiles were not cleaned up from the session because `session_write_close()` was call too early. The result was that the session data size was growing disproportionately.
I fixed it and renamed `\Glpi\Debug\Profile::load()` to `\Glpi\Debug\Profile::pull()` in order to have a name that clearly indicates that the data is removed from the session when recovered.

Fix cleaning of debug profiles stored in session

---

src/CommonDBTM.php
src/Profile.php
src/Session.php
tests/functional/Session.php

Now that rights are more organized in the Profile class, it is relatively easy to resolve a label from a module and right value.
Allows showing a right name for non-standard rights like "Add external" for Users.
Allows showing overridden rights like "See my ticket" instead of READ (same value).
Session is closed and the language is forced to "en_GB" to standardize new names in the log. This shouldn't be an issue though as the access errors are logged when a `check*` call fails which stops the request anyways. Before the method ends, the user's language is restored just to ensure the error displayed in the web UI is in the …

Use user-friendly permission labels in access-errors log

---

src/Search/FilterableTrait.php

This may not affect any filterable types currently in the main branch, but globally the ID search option for an itemtype may not even exist yet and if it does, it may not be option number 2. Followups for example have no ID search option yet as they were not meant to be searched as the primary itemtype. In the webhooks feature this option will need added, but ID 2 is already being used.
The criteria injection will need to manually search for the option number for the ID field. If it is missing, it will throw a warning to make debugging this kind of issue easier in the future.

CriteriaFilter - Handle non-standard ID option number

---

install/migrations/update_10.0.7_to_10.0.8/queuednotification.php
install/migrations/update_10.0.8_to_10.0.9.php
install/migrations/update_10.0.8_to_10.0.9/queuednotification.php

| Fixed tickets | #15133
Migration was not located in the correct directory (`10.0.6_to_10.0.7` -> `10.0.7_to_10.0.8`). People migrating from GLPI 10.0.7 will not have this field created. People migrating from a previous version will not have this issue.

Fix `glpi_queuednotifications`.`event` column creation

---

src/CommonITILObject.php
src/NotificationTargetCommonITILObject.php
tests/functional/NotificationTargetTicket.php
tests/functional/Ticket.php

| Fixed tickets | #15128
`CommonITILObject::getTimelineItems()` options used for notifications were a mess. I simplified them.

Fix private items display in timeline

---

src/Dashboard/Provider.php

| Fixed tickets | #15131
Despite its default empty value, `$itemtype` param of `Search::getDefaultCriteria()` method is not optional. When `Items seen` configuration is not `Yes (default criterion)`, calling `Search::getDefaultCriteria()` without a valid itemtype triggers an error.

Fix dashboard when "Items seen" search is not the default criteria

---

front/planning.php

| Fixed tickets | #14711 and !28706
c4075349e3eb0b98733fb5cc1c65460c5d83da4d and 422f73ea2e272260e68afd236f8ca09e8e17b5bf were made to prevent giving too many rights to the session generated during the iCal/WebCal export. Problem is that some items are requiring much more rights than the basic `READ` to be readable, see https://github.com/glpi-project/glpi/blob/6e3e752988792990f08be1a50670332250ea8f2b/src/Ticket.php#L250-L312
A simplier solution is to NOT send the session cookie to the browser. With this solution, it is not possible to steal the generated session.
Also, it fixes a small bug. Indeed, due to session creation/destruction, the …

Fix iCal/WebCal export

---

src/AuthLDAP.php

Regression introduced in GLPI 10.0.8 by https://github.com/glpi-project/glpi/pull/14561/files#diff-a2b8bab26c2a6fc2656bb8a9a4a03e5e9690fe475a326288d952bc4bd17c1547R3126-R3128

Fix LDAP authentication when `use_bind` is false

---

src/User.php

To avoid misunderstandings and data entry errors,
I suggest modifying the function to find users by their email address by performing a search using lower case letters.
From RFC 5321, section 2.3.11:
The standard mailbox naming convention is defined to be "local-part@domain"; contemporary usage permits a much broader set of applications than simple "user names". Consequently, and due to a long history of problems when intermediate hosts have attempted to optimize transport by modifying them, the local-part MUST be interpreted and assigned semantics only by the host specified in the domain part of the address.
So yes, the part before the "@" could be case-sensitive, since it is entirely under the control of the host system. In practice though, no widely used mail systems distinguish …

fix(core): use non sensitive case to find user

---

.github/actions/test_update-from-9.5.sh
.github/actions/test_update-from-older-version.sh
install/migrations/update_0.90.1_to_0.90.5.php
install/migrations/update_0.90.x_to_9.1.0.php
install/migrations/update_10.0.0_to_10.0.1.php
install/migrations/update_10.0.1_to_10.0.2.php
install/migrations/update_10.0.2_to_10.0.3.php
install/migrations/update_10.0.3_to_10.0.4.php
install/migrations/update_10.0.4_to_10.0.5.php
install/migrations/update_10.0.5_to_10.0.6/inventory.php
install/migrations/update_10.0.6_to_10.0.7/unmanageds.php
install/migrations/update_9.2.x_to_9.3.0.php
install/migrations/update_9.3.1_to_9.3.2.php
install/migrations/update_9.3.x_to_9.4.0.php
install/migrations/update_9.4.0_to_9.4.1.php
install/migrations/update_9.4.1_to_9.4.2.php
install/migrations/update_9.4.2_to_9.4.3.php
install/migrations/update_9.4.x_to_9.5.0.php
install/migrations/update_9.5.3_to_9.5.4.php
install/migrations/update_9.5.x_to_10.0.0.php
install/migrations/update_9.5.x_to_10.0.0/cache.php
install/migrations/update_9.5.x_to_10.0.0/knowbaseitem_knowbaseitemcategory.php
install/migrations/update_9.5.x_to_10.0.0/native_inventory.php
install/migrations/update_9.5.x_to_10.0.0/pendingreason.php

1. Make CI test fails on migration errors
See https://github.com/cedric-anne/glpi/actions/runs/5486306414/jobs/9996236529 for a failure example (I forced execution of a broken query).
2. In migrations, replace `DBmysql::insert()`, `DBmysql::update()` and `DBmysql::delete()` usages by `DBmysql::insertOrDie()`, `DBmysql::updateOrDie()` and `DBmysql::deleteOrDie()`. Most of other DB operations are using a `XXXorDie()` method.

Make CI test fails on migration errors

---

src/ManualLink.php
src/Search.php

| Fixed tickets | #15145
On `additionalfields`, when value was `NULL`, fallback value was containing an unexpected `Search::SHORTSEP`.
```diff
- "IFNULL(GROUP_CONTACT(...), '" . self::NULLVALUE . self::SHORTSEP . '")"
+ "IFNULL(GROUP_CONTACT(...), '" . self::NULLVALUE . '")"
```

Fix handling of null values in additional fields

---

src/Reservation.php
src/ReservationItem.php
tests/functional/Reservation.php

Small improvement to reservations; do not show itemtypes that have no valid reservable items.
| Fixed tickets | !28083

Filter reservable itemtype dropdowns

---

css/includes/components/_tabs.scss

Fixing a small detail on our tabs.
Before:
After:

Fix tabs borders

---

src/Search.php

in addition to
https://github.com/glpi-project/glpi/pull/15054
old HTML format 
```
&lt;p&gt;Bonjour&lt;/p&gt;&lt;p&gt;Suite aux tests Firefox 90 esr 32 bits, j'ai mis à jour mon poste avec Firefox 64 bits&lt;/p&gt;&lt;p&gt;Cordialement&lt;/p&gt;
```
is not handle correctly when performing a CSV export (also on a line)
Previous PR that adds ```preserve_line_breaks``` option can be kept

fix(export): preserve line breaks for 'old' HTML format

---

CHANGELOG.md
front/css.php
front/locale.php
inc/based_config.php
src/Application/View/Extension/FrontEndAssetsExtension.php
src/Application/View/TemplateRenderer.php
src/Dashboard/Grid.php
src/GLPI.php
src/Html.php
tests/bootstrap.php
tests/router.php

| Fixed tickets | #15109 
Purpose of this new `GLPI_ENVIRONMENT_TYPE` constant is to be able to adapt some code behaviours.
To enhance performances, following operations will be done only on `development` envs:
- auto reload of twig templates on each rendering (implies an additional file access to detect whether the template changed);
- menu regeneration on each request.
To improve responsiveness to changes during development, following behaviours will be disabled specifically on `development` envs (it was previously done on `debug` mode):
- `front/css.php` response cache headers will not be sent to browser;
- `front/locales.php` response …

Add `GLPI_ENVIRONMENT_TYPE` constant

---

front/logout.php
phpstan.neon
src/Auth.php

| Fixed tickets | !28776
`phpCAS::client()` signature changed in 1.6.0 version of `phpCAS`, in order to fix a security issue. Unfortunatelly, this signature change has been backported in the `1.3.6-1` version of the debian package, and checking only the version `phpCAS` to adpat the code is not anymore sufficient.
With proposed change, we will use the new signature if `phpCAS` version is >= 1.6.0 or if the `phpCAS::client()` method has more than 6 arguments.
Counting arguments will make this code work for all existing versions. On first version (0.7.0), there was only 5 arguments, then  starting on 1.3.0 version, there was 6 arguments. I …

Fix issue with phpCAS 1.3.6-1 debian package

---

src/CalDAV/Plugin/Browser.php

Access to caldav debug UI was checking the `use_mode` of the connected user (connected using basic auth). It mean that this debug UI was accessible only if user had the debug mode active on its latest GLPI session, and this condition was not explained anywhere.
As user is connected, instead of checking his `use_mode` in database, we can directly check that he is able to access the debug mode (possible when he has the `config::UPDATE` right.

Fix access check to caldav debug UI

---

install/migrations/update_10.0.7_to_10.0.8/ram_field.php

Fix `ram` field migration when value is >= 2^32

---

CHANGELOG.md
src/Console/Migration/AppliancesPluginToCoreCommand.php
src/Console/Migration/RacksPluginToCoreCommand.php
src/DBmysql.php
src/NotImportedEmail.php
tests/functional/Profile_User.php

`truncate()` and `truncateOrDie()` are inconsistent, the first rely on a `delete()` the second performs a real SQL `TRUNCATE`. 
Behaviour is not the same (truncate resets autoincrement while delete does not).
This has been changed in #10853; but I cannot find the main reason, expect a bug from a plugin.
In any case, if a delete is needed, we should not call a method named truncate. Maybe the `truncateOrDie()` method should be removed aswell. 
This way, we do not allow any `TRUNCATE` SQL in GLPI nor its plugins. SQL `TRUNCATE` are issued in plugins migration commands and tests only in GLPI core (so this does not seems a problem to use …

Deprecate `DBmysql::truncate()` and `DBmysql::truncateOrDie()` methods

---

src/Knowbase.php

The category was not loaded from the URL parameters, when it is present. The last category displayed was always loaded.
| Fixed tickets | !28580

fix(knowbase): load category from URL

---

src/Ticket.php
templates/components/itilobject/fields/status.html.twig
tests/DbTestCase.php
tests/RuleBuilder.php
tests/bootstrap.php
tests/functional/RuleTicket.php

Add missing hidden input for the `global_validation` field, which is needed for our rule engine to work properly on this field.
| Fixed tickets | !28778

Add missing hidden input for global_validation field

---

src/CommonDBTM.php

despite of
https://github.com/glpi-project/glpi/pull/15032
another problem (the same as before) appeared  with
https://github.com/glpi-project/glpi/pull/15032/commits/80eb0cad7faf97a64119427aa5760310c2f0255d
```$itemtype``` is just a 'string' here, and check with ```ìnstanceof``` return ```false```

fix(purge): better check

---

src/AuthLDAP.php

As far as I understand, the `ldap_bind()` operation is mandatory unless the `LDAPS bind` method is used (using a `tls_certfile`/`tls_keyfile`). Since #10186, the label/helper of the `use_bind` option indicates that it could be used `for non-anonymous binds`, but in fact, this option must also be active when anonymous bind has to be done.
See https://github.com/glpi-project/glpi/blob/b5c8cc574e6094643c4cd8c543e24d3fd36b3283/src/AuthLDAP.php#L3134-L3140

Fix LDAP `use_bind` option label

---

src/Api/HL/Controller/AbstractController.php
src/Api/HL/Controller/AdministrationController.php
src/Api/HL/Controller/AssetController.php
src/Api/HL/Controller/ComponentController.php
src/Api/HL/Controller/DropdownController.php
src/Api/HL/Controller/ITILController.php
src/Api/HL/Controller/ManagementController.php
src/Api/HL/Controller/ProjectController.php
src/Api/HL/OpenAPIGenerator.php
src/Api/HL/Router.php

When a schema has related data like an entity or user, typically only the ID, name and a few other fields are shown; just enough to identify it. By tracking which schema represents the full object, it can improve user understanding of the type and also enable improved functionality on the server side.
For example, a potential GraphQL wrapper. Currently, the GraphQL wrapper dynamically generates a new object type for every single joined property. This is not only inefficient and a mess for users, but doesn't allow one of the benefits of GraphQL by letting the user get more of the fields than are exposed by default in the …

[HLAPI] Object type partials

---

src/Html.php
src/Session.php
templates/display_and_die.html.twig

When the session expires and an action is attempted, the error message was too generic.
Before:
After:
| Fixed tickets | !28748

expired session message

---

src/Knowbase.php

The complete state of the tree (unfolded or not) was no longer recorded, as was the case in 9.5.
| Fixed tickets | !28580

fix(knowbase): tree persistence

---

tests/src/Command/TestUpdatedDataCommand.php

In #14974, a new `add_document` event will be available for ITIL objects notifications, and a new default notification will be added. During update process, we cannot be sure what is the correct template to use for this new notification, as the default `Ticket` template may have been deleted, or may not be the template that is expected to be used.
I propose to the checks that ensure that notifications are identical between an updated GLPI instance and a new fresh installation. It is not really a problem if new default notifications are not added during GLPI update, as administrator may recreate them easilly. Also, it is …

Allow updated notifications to be different from the default ones

---

tests/bootstrap.php
tests/functional/Item_OperatingSystem.php
tests/imap/MailCollector.php
tests/units/DBmysqlIterator.php
tests/units/Html.php

In our test suite, when an error is triggered:
1. the error is catched by atoum and make tests fail unless the `$this->error()` asserter is used to validate it exists;
2. the error is catched by the GLPI error handler and produce a log entry that make tests fail unless a `$this->has*LogRecord*()` asserter is used to validate it exists;
3. the error generates an output message.
The message pollutes the output, see image, and sometimes it confuses the developer that may think that the error has to be fixed.
A solution could be to catch the output using the `$this->output()` asserter, but it is redundant with the …

Disable errors output in test suites executed by atoum

---

src/Project.php

Blank page on project kanban after #15118.
I've compared the data returned by `Project::getAllKanbanColumns()` before and after the changes and found some differences in array keys.
Before #15118:
After #15118:
Using `uasort` to preserve keys seems to fix the issue.

Fix project kanban

---

src/CommonDBTM.php
src/CommonITILTask.php
src/DeviceCamera.php
src/Infocom.php
src/NetworkName.php
src/NetworkPort.php
src/ProjectTaskTemplate.php
src/QueuedNotification.php
src/TaskTemplate.php
tests/functional/Search.php

While working on #14875, I figured out that some search options were not correctly declared.
As I am not completely sure of the exact list that we are supposed to support, I decided to not add a warning yet, to prevent introducing warnings on legitimate usages in plugins in a bugfixes version, so I added a check in test suite to prevent future issues.
This check should be moved into the search class itself in GLPI 10.1.

Fix invalid search options datatypes

---

css/includes/components/_kanban.scss

| Fixed tickets | #15254
When using a rotate transform in CSS, it doesn't rotate the layout (width, height, margin, padding, etc). A long Kanban header like "Processing (Assigned)" would overlap the surrounding columns when collapsed and block the user from being able to interact with the buttons in the other columns to expand them.
An alternative could be to change the writing mode to `tb` and then manually "rotate" the margins and padding.

Avoid transform rotate when collapsing kanban cols

---

src/Dropdown.php

| Fixed tickets | #15256
The returned `more` parameter was being returned as `true` under the wrong conditions leading to the actor dropdown always thinking there was more to load. This caused it to repeatedly send back-to-back requests to `ajax/actors.php` and, if debug mode was enabled, that meant many debug profile sessions being created and fetched from the server in a second `ajax/debug.php` request each time.

Fix actor dropdown infinite loading

---

js/dashboard.js

The 'K' was duplicated since https://github.com/glpi-project/glpi/pull/15209.
I don't know if this suffix has any other use? In this case, it seems unnecessary

fix(dashboard): suffix

---

src/Dashboard/Grid.php
src/Plugin.php

While working on #15109, I figured out that some caching issues may happens due to the fact that cache entries thay may be affected by plugins are not cleaned/rebuild when a plugin is installed/updated/activated/deactivated/uninstalled.
Some examples:
- A plugin installation may register a new right, resulting in a stale `all_possible_rights` cache entry. For the same reason, deinstallation of a plugin may have the same effect.
- If a plugin add its own entries in `$CFG_GLPI['itemdevices']`, `$CFG_GLPI['device_types']` or `$CFG_GLPI['asset_types']`, or if the result of a `AbstractFilter::canBeApplied()` method of an …

Ensure cache is clear when a plugin is activated/deactivated

---

src/Budget.php

The line "Total remaining on the budget" was only displayed if you were in the budget entity. From the root entity, for example, you could access the object, but the line was hidden.
I don't understand the relevance of this filtering?
| Fixed tickets | !28711

fix(budget): Total remaining on the budget

---

src/Search.php
tests/GLPITestCase.php
tests/functional/Search.php

Add many tests using the `contains` search operator.
Aim to validate advanced usages described in https://glpi-user-documentation.readthedocs.io/fr/latest/first-steps/search.html?highlight=search#perform-an-advanced-search for all valid search options datatypes.
While adding tests, I figured out that some cases are not working as expected, but I did not fix them yet, I just added some `FIXME` comments in the `Search` class code. I propose to fix them in separated PRs, as all of them are not easy to fix.

Add tests on `contains` search operator

---

src/Search.php
tests/functional/Search.php

1. Fix SQL criteria applied when searching for numeric values.
2. Fix search form `is`/`is_not` inputs when min/max values are defined.
before:
after:

Fix handling of `integer` search option datatype

---

src/Search.php
tests/functional/Search.php

1. Support `-` sign in numeric searches (e.g. `> -15`).
2. Support floats in numeric searches (e.g. `>= 10.5`).

Enhance numeric search

---

src/Search.php
tests/functional/Search.php

1. Fix handling of `AND NOT` operator in date searches.
2. Support floats in date searches (e.g. `>= 10.5` -> `>= ADDDATE(NOW(), INTERVAL 10.5 MONTH)`).

Fix and enhance date search

---

src/SavedSearch.php

Some saved searches gave a 404 error when trying to load them.
For example, **Device Camera Models**, which tried to load the URL `front/devicecameramodel.php?itemtype=DeviceCameraModel` instead of `front/devicemodel.php?itemtype=DeviceCameraModel`
Same case with GenericObject plugin objects
| Fixed tickets | !28884

fix(saved search): 404 error

---

src/Search.php
tests/functional/Search.php

Before:
- "AND field contains NULL" -> `WHERE (field IS NULL OR field = '')`
- "AND NOT field contains NULL" -> `WHERE (field IS NOT NULL OR field = '')`
After:
- "AND field contains NULL" -> `WHERE (field IS NULL OR field = '')`
- "AND NOT field contains NULL" -> `WHERE (field IS NOT NULL AND field <> '')`

Fix "AND NOT null" search criteria

---

css/includes/components/_flatpickr.scss

The week number was not visible, as it was written in white on white.
Before:
After:
| Fixed tickets | !28914

fix(calendar input): week number not visible

---

src/Html.php
src/Item_Devices.php

| Fixed tickets | #15099
When looking at batteries from the DeviceBattery form on the Items tab, it was trying to get the capacity from the asset rather than the device so nothing was showing and a warning was thrown. From the asset form, it was displaying correctly.
This PR fixes it by always using the device rather than the peer (the opposite of whichever type you are looking at). It also makes the available information visible when the individual battery has a capacity set but the battery model does not. Finally, it improves the display of progress bars in general by allowing the text to overflow since it is set on the inner part of the …

Try fixing battery wear level display from device model form

---

css/includes/components/_richtext.scss
css/legacy/includes/_styles.scss

The content of the article was displayed without line breaks in the paragraphs, so there was always a vertical and horizontal scrollbar.
Before:
After:
| Fixed tickets | !28974

fix(ticket): FAQ article sliders

---

src/Group.php

Since 10.0, it was no longer possible to clone a group.
| Fixed tickets | !28979

fix(group): restore cloning

---

src/Profile.php
tests/functional/Profile.php

It is possible for a user to switch all his "super-admin" profiles to a simplified interface, with the effect of losing the ability to modify the other profiles.
To prevent this, the "Profile's interface" field is set to "read-only" if the profile is the last "super-admin" profile.

Prevent last super admin profile from changing interface

---

package-lock.json
package.json

#15312 backported on 10.0/bugfixes branch.

Bump @tabler/icons-webfont from 2.21.0 to 2.30.0

---

src/User.php

| Bug fix?      | yes and no 😄
| New feature?  | yes and no 😄
| Fixed tickets | !28961
It's possible to "Clean LDAP fields and force synchronisation" on "Synchronization" tab for each user, but not with a Massive Action.

feat(user): add clean LDAP fields massive action

---

src/ReservationItem.php

When we searched for a free item for a specific period, we found items of different types, but the itemtype dropdown was empty, which made it impossible to filter by this field.
After:
| Fixed tickets | !28083

fix(reservation): itemtype list empty

---

src/User.php

In the "used items" tab, if the user is linked to group ID = 0 (a group that doesn't exist), the result displayed all assets with no group entered in their file, because in this case the value of `groups_id = 0`.
Same in the "managed items" tab.
| Fixed tickets | !28923

fix(user): used items list

---

src/RichText/UserMention.php

In PHP 7.4 at least it seems like DOMDocument does not handle empty HTML content well.
From CLI:
Uncaught ValueError: DOMDocument::loadHTML(): Argument 1 ($source) must not be empty in php shell code:1
See https://github.com/glpi-project/glpi/actions/runs/5761634677/job/15619847811

handle empty content before domdocument creation

---

templates/components/form/header.html.twig

| Fixed tickets | #15001
In GLPI 9.5, the `entities_id` field was only present in form header when the corresponding item has this field in its database table. This PR reproduces this behaviour.
Problem here is that the `0` value was passed due to https://github.com/glpi-project/glpi/blob/afbf1f6b93d9b7006a593c53480a33e5c7fe392a/templates/components/form/header.html.twig#L41-L53 and then used by document attachement logic due to `else if (isset($input['entities_id']))` case in https://github.com/glpi-project/glpi/blob/afbf1f6b93d9b7006a593c53480a33e5c7fe392a/src/CommonDBTM.php#L5484-L5491. With proposed change, the default `$entities_id = …

Fix reminder documents entity

---

src/Config.php

When people manually copy and paste the system info into a GitHub issue, there is a possibility it will contain a `#` followed by a number which triggers GitHub's auto-linking. Usually this occurs with the `php_uname` output. There are a lot of unrelated issues now linked to issue 1 at least.
When people use the preferred method of clicking the button that says "Copy to clipboard" this isn't an issue because it is converted to several HTML details elements.

Prevent github autolink with copied system information

---

tests/bootstrap.php

Since #15233 , I figured out that there was no output when an exception occurs during test suite execution. This PR aims to fix it by deactivating GLPI error and exception handlers during test suite, in order to ensure that atoum will be able to catch all errors/exceptions.
Before:
After:
The error handler is itself tested in a dedicated test, see https://github.com/glpi-project/glpi/blob/020c4a9b5abc66679bd2e16fa63f53270296e905/tests/units/Glpi/Application/ErrorHandler.php.

Fix empty exception output on test suite

---

ajax/common.tabs.php
ajax/updatecurrenttab.php
src/Ajax.php

Remove unneeded calls to `Toolbox::getAvailablesTabs()` as they may be costly in performances.
In the case of tickets, this function will trigger the following chain : `Ticket::defineAllTabs()` -> `Ticket::addDefaultFormTab()` -> `Ticket::getTimelineItems()` -> lot of SQL requests to load the timeline content.
This was really bad because `Toolbox::getAvailablesTabs()` was called 4 times when opening the ticket page and once on each tab change (any tab change, even to an already loaded one).
Going back and forth on some tabs and you may end up calling it 10+ times, triggering huge amount of requests.
After the changes, `Toolbox::getAvailablesTabs()` is only called twice :
* Once when opening the timeline tab (load timeline content)
* Once when loading the ticket page (load tabs name with …

Avoid costly calls to Toolbox::getAvailableTabs()

---

src/CommonITILObject.php
tests/functional/Ticket.php

| Fixed tickets | !28943
The `getTimelineItems()` design is prone to mistakes. When `check_view_rights` option is `false`, we should not us the session to filter private items.

Fix private followups/tasks filtering in notifications

---

src/Dashboard/Grid.php

Prevent calling `loadAllDashboards` if the default dashboard can be found in GLPI's config (which will be the case 99.9% of the time).
This save around ~70 SQL queries on every page for any user that didn't override the default dashboards in their preferences.

Fix default dashboard computation

---

css/includes/components/_search_input.scss
src/Search/Input/QueryBuilder.php
src/Search/Provider/SQLProvider.php
tests/functional/Search.php
tests/units/Glpi/Search/Input/QueryBuilder.php

Checks the format entered with the "contains" search entry.
This informs the user that their input is incorrect while they are typing and does not execute the search query (which can be a significant resource saving in some cases).
Suggested warning, probably to be improved:
| Fixed tickets | !26543

feat(search): check field pattern

---

src/AuthLDAP.php

| Fixed tickets | !28885 !29035
Regression introduced in 10.0.8 (#14561).
First argument of `ldap_set_option` have to be `null` for `LDAP_OPT_X_TLS_CERTFILE`/`LDAP_OPT_X_TLS_KEYFILE`  to set it globally. I do not really understand why it does not work when setting it only for the current connection, but without this change, searching for LDAP users results in a `Insufficient access (50)` error.

Fix LDAP connection using certificate files

---

src/Dropdown.php

In a dropdown of locations (for example), in multi-entities, locations are grouped by entity, but these entities were sorted by ID and not by completename.
Entities ID:
Before:
After:
| Fixed tickets | !28931

fix(dropdown): sort by entity

---

src/CommonDBTM.php

When a document is added from the kb, it was created on the root entity, but not recursively.
| Fixed tickets | !28932

fix(document): recursivity when added from knowbase

---

src/Features/Clonable.php
tests/functional/User.php

When cloning a user, the new user's authorization entities did not match the original one.
Original user:
Clone before:
Clone after:

fix(user): authorization cloning

---

src/Calendar.php
src/CalendarSegment.php
src/LevelAgreement.php
src/LevelAgreementLevel.php
tests/functional/Calendar.php
tests/functional/CommonITILRecurrent.php
tests/functional/SLM.php

Escalation levels are not computed correctly.
I'm supposed to have a 10 day threshold for the escalation date but it end up being on the same date as the SLA:
| Fixed tickets | !28778

Fix escalation levels computation

---

src/Cartridge.php

The icon used for cartridge seems to no longer exist:
Suggested replacement:
Other possible choices:

Fix cartridge icon

---

src/CommonITILObject.php
src/NotificationTemplate.php
templates/components/itilobject/layout.html.twig
templates/components/itilobject/mainform_open.html.twig
templates/components/itilobject/service_levels.html.twig
templates/components/itilobject/timeline/form_task.html.twig

Fix call to undefined properties to avoid triggering the `__get` magic method that will be added in #15388.

Fix undefined properties

---

src/User.php

Cleans up some fields when cloning a user to avoid inconsistencies.

fix(user): clean input for cloning

---

src/Contract.php

| Fixed tickets | #15260
I do not see any reason that explains why these fields cannot be update by massive actions.

Allow massive update of contracts `periodicity`, `billing` and `renewal`

---

CHANGELOG.md
css/includes/pages/_search.scss
install/empty_data.php
install/migrations/update_10.0.x_to_10.1.0/consumable.php
src/Consumable.php
src/MassiveAction.php
src/Search/Input/QueryBuilder.php
src/Search/Output/HTMLSearchOutput.php
src/Search/Provider/SQLProvider.php
src/Search/SearchEngine.php
templates/components/search/controls.html.twig
templates/components/search/display_data.html.twig
templates/components/search/query_builder/main.html.twig
templates/components/search/table.html.twig
templates/pages/assets/consumable_list.html.twig

Rewrite the "Consumable" tab to use the search engine rendering.
The main goals with this change are to :
* Allow users to add custom columns to the results through display preferences
* Allow users to export data (e.g. CSV)
Before:
After:
The original layout of the page is conserved with two separate tables for unused and used items.
These changes required a few tweaks of the search engine to work properly:
* A new `no_search` parameter for `SearchEngine::show()` in order to display only search results (the search criteria section is hidden but still rendered as we need the criteria inputs defined in the page for results pagination to work properly)
* Add a rand to the `massform$itemtype` form to avoid conflicts when displaying multiple search results on the same page.
* Support a new …

Use search engine to display consumables

---

SECURITY.md

The end of support for GLPI 9.5 has been announced, and ended on 06/30/2023.

fix: remove 9.5 from security fixes

---

src/RuleCriteria.php
tests/functional/Rule.php

```RuleCriteria``` does not work when the value of the field contains a ```quote```
This field can be ```sanitized``` and then passed to the rules 
Ex : 
Create a ticket with title :  ```"Besoin d'un ordinateur"```
```RuleCretieria``` receive  ```"Besoin d\'un ordinateur"``` 
| Fixed tickets | #29251

fix(RuleCriteria): unsanitize field when try to match

---

src/Features/Kanban.php

Since the addition of icons to the form tabs, the Kanban switcher has been broken due to the way it checked for the Kanban tab ID.

Fix Kanban switcher

---

src/CommonDCModelDropdown.php
tests/functional/Item_Rack.php

| Fixed tickets | !29207
Modifying an asset's model (by increasing its height, width or depth) can lead to overlapping with other assets in the rack.
For example, if I increase the height of my network equipment model to 5, the display becomes inconsistent (we can no longer interact with the computer).

Equipment collision in rack due to model modification

---

src/Ticket.php

The counter in the "Created tickets" tab counted deleted tickets, whereas the contents of the tab exclude them.
Before (user has 1 deleted ticket):
After:
| Fixed tickets | !29315

fix(ticket): menu counter counted trash

---

src/Computer.php

This was a feature added for my team's use - I've opened this PR in case the wider community would benefit.
This allows users to search whether a computer is available for reservation or not:
Computers marked as unavailable will be marked as "No", computers marked as available will be marked as "Yes", and computers that are not authorized for reservation can be searched under "contains NULL"
One question I have is about the 'id' of the search option. I picked 81 at random, let me know if I have this wrong and if there's a better way to determine a search option's id number.

Computers: Add search option for reservations

---

src/ProjectTask.php
tests/functional/ProjectTask.php

| Fixed tickets | !28627
Currently, there are several inconsistencies in the execution of massive actions on project tasks.
Firstly, if a task is moved from one project to another, the sub-tasks of that task will not be moved to their new project.
Secondly, if a task is cloned, its associated sub-tasks will not be cloned.

fix(projecttask): Cloning and updating massive actions are now passed on to subtasks

---

src/Api/HL/OpenAPIGenerator.php

When an API path like `/Assistance/{itemtype}/` was expanded for the OpenAPI documentation to `/Assistance/Ticket/`, `/Assistance/Change/` and `/Assistance/Problem/`, the `itemtype` parameter was left in the documentation which is not necessary or valid.

HLAPI remove expanded route params

---

src/Api/HL/Controller/AssetController.php

Move the dynamic schema used for the results of the `/Assets/Global` endpoint to the schema array so it can be reused, show in the documentation as a schema, and be able to be used in route documentation.

[HLAPI] make commonasset a proper schema

---

js/src/vue/app.js

Add `defineAsyncComponent` on the `window.Vue` global so plugins can use it without needing to re-import it in their webpack entrypoints.
Add some logic to ensure components somehow loaded before the main Vue `app.js` is imported are preserved.
Set `window._vue` to the complete exports from the 'vue' library so it can be used in `externals` mappings in plugins.
Example option in a plugin's webpack:
```
externals: {
vue: 'window _vue'
}
```
Plugins can then import from 'vue' as done normally, and have it actually map to `window._vue` to prevent useless duplicate code in the bundle.
I wasn't able to find a way to get this to …

improve plugin support for vue

---

src/KnowbaseItemTranslation.php

Translations could no longer be modified with an error visible in debug mode:
| Fixed tickets | !29252

fix(knowbase): translations not editable

---

install/empty_data.php
src/Api/HL/Controller/AdministrationController.php
src/Api/HL/Controller/ITILController.php
src/Api/HL/Controller/ProjectController.php
src/Api/HL/Middleware/CRUDRequestMiddleware.php
src/Api/HL/Search.php
tests/functional/Glpi/Api/HL/Controller/AdministrationController.php
tests/functional/Glpi/Api/HL/Controller/ComponentController.php
tests/functional/Glpi/Api/HL/Controller/ITILController.php
tests/functional/Glpi/Api/HL/Controller/ManagementController.php

\| Q             | A
Add a new optional extension property `x-rights-conditions`  to the schema definitions to specify, by access type, a callable that returns additional SQL criteria needed for the current user in order to restrict the results.
For example, a user without the ability to see private followups should have those followups filtered out.
A user without the ability to see all project should only see the ones they are a manager for or are in the project team for.
This keeps itemtype-specific restrictions out of the API's search code from the start and allows plugins to remove or modify the restrictions using the …

HLAPI Item-level restrictions in schema

---

css/includes/components/_racks.scss

Don't know since when (only on main), but while checking #15514 , I saw that while dragging a rack element (same in rooms) the width of the item was very wrong. Seems to come from the extra css of gridstack:
https://github.com/gridstack/gridstack.js/blob/master/src/gridstack-extra.scss
But I think this doesn't change since years, and I suspect another change (relative position maybe ?)

fix racks and room gridstack item width when draggin

---

src/Api/HL/Controller/CoreController.php
src/Api/HL/OpenAPIGenerator.php
src/Api/HL/RoutePath.php
src/Api/HL/Router.php
tests/HLAPITestCase.php
tests/bootstrap.php
tests/functional/Glpi/Api/HL/Controller/AdministrationController.php
tests/functional/Glpi/Api/HL/Controller/CoreController.php

With the inclusion of the OAuth server component in GLPI now, we no longer need to support the less safe HTTP Basic authentication option. The `user_token` authentication also seems redundant now. Additionally, we can drop support for the `Session-Token` header. All of the OAuth authentication methods were stateless anyways and that is how it is usually expected to work with REST. A session would still be initialized, but it would only last for that single request.
The `GLPI-Profile`, `GLPI-Entity` and `GLPI-Entity-Recursive` headers were added along with the OAuth server feature and can be used to specify …

Drop non-OAuth authentication for new API

---

tests/functional/SLM.php

Forces ordering during query ensures that result is identical on both MariaDB and MySQL.

Fix SLM levels tests on mariadb

---

src/Dashboard/Grid.php

The cache key does not take current entities into account due to a typo that's probably here since the original implementation in GLPI 9.5.
| Fixed tickets | #15431

Fix dashboard browser cache hash

---

src/Toolbox.php

| Fixed tickets | !29238
Context, one glpi with several url (case multi-structure or load balancing, etc)
Since https://github.com/glpi-project/glpi/security/advisories/GHSA-gxv6-xq9q-37hg, we force `url_base` (instead `root_doc` previously) when a `?redirect=` is asked with a relative url. This to prevent a malicious redirection (ex `?redirect=/\/example.com`)
Issue is with the above context, a cookie expiration will destroy session, and move to login page with a redirect parameter.
After a successful login, we are redirected to the url defined in setup general, where in some valid cases, we want to keep the current `server_name` .
To …

try to keep the same url when a relative redirect is asked

---

templates/pages/setup/general/dbreplica_setup.html.twig

Since #15369 is not possible to update replica tab configuration (changes are not saved) because of a missing "_dbslave_status" hidden field.

main: unable to update replica config

---

front/item_rack.form.php
js/rack.js
src/Item_Rack.php

Currently, the entire rack item form, including tabs, are being displayed in the modal when adding an item to the rack. This causes an issue as the new tabs share the same ID as the panel on the page. Before the "All" tab was reworked, this didn't seem to be an issue, but now the tabs on the page are hidden when the modal is opened (and an error trying to redefine a function).
Since the modal will only ever be used for a new item, it makes sense to just show the form itself without the extra tab stuff. Currently, the only way to have multiple tabbed forms loaded at once would be to load the others in an iframe. Randomizing …

Show only the rack item form itself in modal

---

src/CommonITILObject.php
tests/functional/Ticket.php

While trying to fix a bug on `fields`  pugin, I figured out that dynamic properties defined on `CommonITILObject` are not anymore working since #15388.
For instance,
```php
$change = new Change();
$change->plugin_fields_data = [];
var_dump($change->plugin_fields_data);
```
will produce a `*** PHP User Warning (512): Unknown field: 'plugin_fields_data' in /var/www/glpi/src/CommonITILObject.php at line 221` error.
We should preserve current behaviour , to not affect plugins in a bugfixes version. Maybe we should deprecate dynamic property settings in GLPI 10.1.

Allow dynamic properties on `CommonITILObject`

---

src/Inventory/Asset/MainAsset.php
src/Inventory/Conf.php
tests/functional/Glpi/Inventory/Assets/Computer.php

| Fixed tickets | !28571
When main asset cannot be created, for instance if it is blocked by unicity rules, or if a plugin invalidates the input, inventory process is not stopped and generates many errors.
1. First commit fixes handling of exceptions that may occurs during manual import.
2. Second commit permits to exit the inventory process as soon as the main asset cannot be created. It only patches this particular case.
This PR focuses on main asset only, but this kind of issues could appear at many places in the inventory process. There is actually no way to fix this easilly with current code. Indeed, the `CommonDBTM::add/update/delete()` …

Stop inventory process when main asset cannot be created

---

src/Group.php

Prevent SQL error
```sql
SQL: SELECT `id` FROM `glpi_items_devicesimcards` WHERE `groups_id` IN ('1') AND `is_deleted` = '0' ORDER BY `` LIMIT 100
Error: Unknown column '' in 'order clause'
Backtrace :
src/DBmysqlIterator.php:112                        
src/DBmysql.php:1078                               DBmysqlIterator->execute()
src/Group.php:767                                  DBmysql->request()
src/Group.php:857                                  Group->getDataItems()
src/Group.php:167                                  Group->showItems()
src/CommonGLPI.php:691                             Group::displayTabContentForItem()
ajax/common.tabs.php:114                           CommonGLPI::displayStandardTab()
```
When we display item list from ```Group``` …

fix(Group): prevent SQL error when 'name' field not exist

---

src/Console/Maintenance/EnableMaintenanceModeCommand.php
templates/maintenance.html.twig

1. `maintenance:enable` command was failing when `--text` option was used with a text containing single quotes.
2. Rendering of `<`, `&` or `>` chars was not correct.

Fix maintenance text encoding issues

---

src/Application/View/Extension/FrontEndAssetsExtension.php
src/Html.php
tests/units/Glpi/Application/View/Extension/FrontEndAssetsExtension.php

When a quey string is present in a SCSS file added by a plugin using the `add_css` hook, the resulting CSS href is broken.

Allow query string in plugins CSS added by hooks

---

src/ProjectTask.php

Inline images from project task description were not converted into documents, and were stored as base64 images into DB.

Fix project tasks rich text images handling

---

package-lock.json
package.json

Bump @tabler/icons-webfont from 2.30.0 to 2.34.0

---

ajax/debug.php
js/src/vue/Debug/Toolbar.vue
js/src/vue/Debug/Widget/SearchOptions.vue
js/src/vue/Debug/WidgetButton.vue

Proposal to migrate search option viewer from `dev` plugin to new debug bar. This allows seeing an overview of all of the search options for an itemtype at runtime in one place regardless of how they are added (inheritance, directly in class, plugins, etc). Could be useful to identify available search option IDs too.
Relies on #15274

Search Option widget for Debug Bar

---

src/Api/APIRest.php

Description
Currently when a file is uploaded through Rest API the file name is threated as an array. Thereby the random generated string wont be attached to the filename and so the whole filename later will be threated as PREFIX. This leds to a uploaded file which is not chained to the created document.
Fix
My fix checks if $_FILES[]['name'] is an array or not. And if not handles the random name in a different way. I have not removed the legacy array part but I do think this can ever work because $_FILES[]['name'] will never be an array in my opinion.

Fix API upload handler

---

src/Item_Devices.php

```Item_DeviceXXX``` from ```Component``` form are visible (and editable) even if they are attach to another entity
Entity restriction is only added when item_DeviceXXX is linked to an asset.
PS : 
Even with this fix, using this URL is still possible 
```/front/item_devicesimcard.form.php?id=20```
I am unable to correct this point 
| Fixed tickets | !29354

fix(Item_DeviceXXX) restrict visibility even if not linked to an asset

---

src/CommonDBRelation.php
src/Document_Item.php
src/Notepad.php
templates/components/itilobject/fields_panel.html.twig
templates/components/notepad/form.html.twig

Enable rich text and files on notes (e.g. entity notes)
| Fixed tickets | !28208

feat(notes): enable richtext with files

---

js/fileupload.js

When a ticket is reopened, a follow-up is mandatory. If an attempt is made to save this empty follow-up, a warning is displayed and the follow-up is not created. In the case where the user uses the content of a template, the text modification was not detected, and the warning was displayed even though the content is not empty.
| Fixed tickets | !29302

fix(ticket): ticket reopening with template

---

templates/components/form/fields_macros.html.twig

Since #14852, file upload was partially broken. Images were correctly added as document, but rich text was not update to replace base64 source by href to created document.

Fix images upload

---

src/RichText/RichText.php
tests/units/Glpi/RichText/RichText.php

| Fixed tickets | #15113
When GLPI document root is changed, all images URLs stored in rich text content are broken. We could probably use the change of `base_url` config as a trigger to update rich text contents, but it would probably result in a too long update procedure on large databases, so would not be a good idea.
I propose to fix paths on rich text rendering.

Fix images URLs when document root has change

---

src/Inventory/Asset/Simcard.php
src/Item_DeviceSimcard.php
tests/functional/Glpi/Inventory/Inventory.php

Try to fix https://github.com/glpi-project/glpi/issues/15435
The reconciliation (to know whether to add or update the SIM card) is done on the ```serial``` / ```msin``` field which (in the latest versions of Android due to Google restrictions) are empty.
So GLPI deletes the SIM card and adds a new one at each inventory.
This first draft consists of basing the reconciliation on the link (```imtes_id```, ```itemtype```, ```is_dynamic```) to the asset
This work if asset have only one SIM card.
But  could cause problems if the asset has several simcards.
It may be necessary to generate a ```UUID``` to be used as the serial number (from ```android-inventory-library```).
| Deprecations? | …

fix(inventory): fix inventory / GLPI mapping

---

src/Features/TreeBrowse.php
tests/functional/TreeBrowse.php

When an article belongs to several categories and you filter on the category in the search, in the tree you have the counter on the categories excluded by the filter, but no result when you open the category.
Before:
After:

fix(knowbase): search article with multi categories

---

templates/components/itilobject/timeline/timeline.html.twig
templates/components/itilobject/timeline/timeline_item_header.html.twig
templates/components/itilobject/timeline/timeline_item_header_badges.html.twig
templates/components/user/info_card.html.twig
templates/components/user/link_with_tooltip.html.twig
templates/components/user/picture.html.twig

Timeline performances: reuse already loaded user objects when possible

---

src/CommonDCModelDropdown.php

Follows #15448.
Unless I miss something, PHP filtering will try to apply the same filter already applied by the `WHERE` clause.

Simplify `CommonDCModelDropdown::getItemsRackForModel()`

---

templates/components/form/basic_inputs_macros.html.twig

Issue noticed with the client secret field for OAuth Clients. When a password field has no ID specified, the JS for the disclose and copy buttons is not valid. This PR forces the generation of an ID if none is specified and the options for disclosable or copyable are set to true.

force id attribute when disclosable or copyable

---

install/migrations/update_10.0.9_to_10.0.10/mailcollector.php
install/mysql/glpi-empty.sql
src/MailCollector.php
tests/imap/MailCollector.php

| Fixed tickets | !29267
On a GLPI instance with 225 mail collectors, all connected to an Azure mail server with OAuth authentication, collect job fails everytime around the 100th collector processed. This is probably due to a connection rate limitation on Azure side, but IMAP error is not really clear and it is hard to be sure of that. Anyway, processing more than 100 collectors at once is probably not a good idea, for performances reasons.
The goal of current PR is to add some rotation on collect job, and limit to 100 collectors processing on each job run.

Add rotation on mail collectors

---

src/Ticket.php

When the profile does not have the "See my ticket" right, the global view counters were wrong.
| Fixed tickets | !29477

fix(central): global view ticket counters

---

src/TicketSatisfaction.php

Follows #15478.
An update on something else than `satisfaction` or `comment` should probably ignored too. For instance, updating the `type` filed from API/plugin/whatever should not trigger a `replysatisfaction` notification.

Better check for `replysatisfaction` notification sending

---

locales/en_GB.po
locales/glpi.pot
src/Dashboard/Filters/AbstractFilter.php
src/DropdownTranslation.php
tests/units/DB.php
tests/units/Glpi/RichText/RichText.php

Due to https://savannah.gnu.org/bugs/?func=detailitem&item_id=62158, we should not indent heredoc ending marker.
I regenerated POT file. Missed translation (`src/DropdownTranslation.php:573`) was also present in other files, so it was still present in POT file.

Remove indentation of heredoc closing tags

---

composer.json
composer.lock
resources/api_doc.MD
src/Api/HL/Controller/AssetController.php
src/Api/HL/Controller/GraphQLController.php
src/Api/HL/GraphQL.php
src/Api/HL/GraphQLGenerator.php
src/Api/HL/Router.php
src/Api/HL/Search.php
src/Config.php
tests/functional/Glpi/Api/HL/Controller/GraphQLController.php

Generic wrapper for the new API allowing access with GraphQL queries.
For when the REST API doesn't return what you want in a single response, you want less information in the response, or you just want to torture your database server.
Supports RSQL filters just like the base API.
```graphql
query {
Ticket(limit: 1, filter: "name=ilike=test") {
id
name
status {
id
name
}
}
}
```
Normally, the `product_number` property for the printer models array in the CartridgeItem type is not accessible in the REST API, only the `id` and `name`, and `comment`. However, there was a recent schema flag `x-full-schema` added which adds a …

GraphQL wrapper

---

src/Api/HL/Controller/AbstractController.php
src/Api/HL/Controller/AdministrationController.php
src/Api/HL/Controller/AssetController.php
src/Api/HL/Controller/ComponentController.php
src/Api/HL/Controller/CoreController.php
src/Api/HL/Controller/ITILController.php
src/Api/HL/Controller/ManagementController.php
src/Api/HL/Controller/ProjectController.php
src/Api/HL/OpenAPIGenerator.php

Changes should affect Swagger UI documentation only.
- Added valid parameters for search endpoints (RSQL query, start, and limit)
- When a component schema has no description but has an itemtype associated, the fallback description is the itemtype's name
- GLPI-Entity, GLPI-Entity-Recursive and GLPI-Profile headers available in Swagger UI as parameters
- Added missing parameters and responses to route docs
- Added Accept-Langauge header parameter for every endpoint along with some examples for quick testing and to show the user the required format. Examples can be selected to pre-fill the value, but can also be entered …

HLAPI Expand endpoint docs

---

templates/components/form/fields_macros.html.twig

The "label_class" and "input_class" options could not be defined when the function was called, as they were systematically overwritten in the macro.
| Fixed tickets | !26302

fix: horizontalField set class

---

composer.json
composer.lock
src/Config.php
src/Html.php
src/UI/Theme.php

`str_replace(GLPI_ROOT, '', $path);` won't work if `GLPI_THEMES` is outside `GLPI_ROOT`.
| Fixed tickets | !28015

Fix relative path for themes stored outside of GLPI_ROOT + cache on last update

---

src/Auth.php

Avoid this deprecation warning:
> PHP Deprecated function (8192): strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/glpi/src/Auth.php at line 1515
Since the `sync_field` allow null values, we should fallback to an empty string to avoid sending invalid parameters to `strlen()`.

Avoid deprecated warning when sync_field is null

---

install/migrations/update_10.0.9_to_10.0.10/groups.php

Before #15017, some fields were not properly encoded when groups were imported from LDAP. These fields encoding have to be fixed to prevent issues during LDAP sync.
For instance, a group in DB with `ldap_group_dn=R&D` will not be found anymore as now we are searching for the encoded value `ldap_group_dn=R&#38;D`

Fix encoding of groups fields fetched from LDAP

---

install/migrations/update_10.0.9_to_10.0.10/ldap_fields.php

Follows #15622 .
Before #15017, some fields were not properly encoded when groups were imported from LDAP. These fields encoding have to be fixed to prevent issues during LDAP sync.
For instance, a user in DB with `user_dn=CN=TEST,OU=R&D,DC=glpi` will not be found anymore as now we are searching for the encoded value `user_dn=CN=TEST,OU=R&#38;D,DC=glpi`.

Fix encoding of users fields fetched from LDAP

---

templates/components/itilobject/fields_panel.html.twig

Replace #15450 .
I do not know why and if it is correct, but `$params['entities_id']` passed to `components/itilobject/layout.html.twig` correspond to the active entity, while `$entities_id` corresponds to the ticket entity.
This `entities_id` variable is already used to retrict actors fields.

Fix entity restriction in ticket item add form

---

install/migrations/update_10.0.10_to_10.0.11/pendingreason.php
install/mysql/glpi-empty.sql
src/Features/ParentStatus.php
src/PendingReason_Item.php
tests/functional/PendingReason.class.php

When modifying a ```ITILfollowup```, if the ```PendingReason``` is removed, the status of the parent element is set to ```ASSIGN```
But this status does not exist for changes (for example)
Here, I propose to save the parent's previous status (```Ticket```, ```Change```, ```Problem```) so that it can be restored if the user removes the  ```PendingReason```.
| Fixed tickets | !29347

fix(PendingReason): restore previous status

---

package-lock.json

Fix bad computation of the week number for all date fields using ```flatpickr```
Today (28/09/2023) We are in week 39, not 38
Before (with flatpickr to 4.6.11) : 
After  (with flatpickr to 4.6.13) : 
See : 
Fixed by
https://github.com/flatpickr/flatpickr/commit/b0ac85233140dc672dc564ce692dcf4d3dbfb540
https://github.com/flatpickr/flatpickr/commit/42723a251f5c1c206f189ea49892620e374a5ec1
| Fixed tickets | !29751

fix(Datetime): fix number of week

---

src/Rule.php
tests/functional/Rule.php

Add search option to be able to filter rules by subtype using RestAPI.
I just don't know hopw to choose the ID of this searchOption :/

Add `sub_type` search option to rules

---

css/includes/components/_richtext.scss

fix long content overflox
Before : 
After : 
| Fixed tickets | !29702

fix(ui): fix long content overflow

---

src/LevelAgreement.php

increase maximum time for ```SLA``` / ```OLA```
| Fixed tickets | !29781

feat(SLA / OLA): increase maximum time

---

src/Html.php

- Display main menu entries befores submenu entries ("Assets", before "Assets > Computers").
- Also add default dashboards entries

fix(fuzzy): main entries before subentries and dashboards

---

src/RuleCriteria.php
tests/functional/RuleCriteria.php

Since 10.0.10, this case no longer works when there are carriage returns in a `/(.*)/`, whereas it did in 10.0.9:
Criteria:
Description code:
```
<div>CATEGORIE : POSTE DE TRAVAIL</div>
<div>Catégorie secondaire : Dysfonctionnement-panne</div>
<div>---</div>
<div>DESCRIPTION :
<p>cambrai</p>
<br>Il s'agit d'un matériel neuf</div>
<div>---</div>
<div>Site de rattachement : Autres sites - Cambrai  </div>
<div>:</div>
<div> </div>
<div>---</div>
<div>Fin de la saisie - merci d'avoir utilisé notre plate-forme ; nos équipes vous répondront dans les meilleurs délais. </div>
<div>Information technique (réservée aux intervenants helpdesk) : Vers Qui Escalader</div>
<div> </div>
```
| …

fix(rule criteria): regex match with carriage return

---

templates/components/itilobject/fields/status.html.twig
templates/components/itilobject/timeline/pending_reasons_messages.html.twig

GLPI used to display the pending reason below the status field in the "main tickets details" section back in the official backport of the feature for GLPI 9.5.
This was lost when migrating to the new interface on the `main` branch.
Users that had beneficiated from the 9.5 backport are missing this feature and request that we correct it.
I think it's a good idea as it avoid scanning through the timeline to find the active pending reason (which may not be on the last followup).
With that in mind, displaying this information clearly under the status field seems good to me.
| Fixed tickets | !29772

Display pending reason in tickets details

---

src/AuthLDAP.php
src/User.php

| Fixed tickets | !29585
I do not know why we did not had a bug on it before. Maybe something changed, or maybe noone ever detect it (the restore feature is recent).
Problem is simple: a user was previously imported from LDAP into GLPI and then was removed from the LDAP.
On even synchronization, `$user['is_deleted']` was false, so the `User::manageDeletedUserInLdap();` method was called.
On odd synchronization, `$user['is_deleted']` was true, so the `User::manageRestoredUserInLdap();` method was called.
I added some conditions to prevent this to happen.

Fix LDAP delete/restore conditions

---

src/Config.php

| Fixed tickets | #15637
Usage of the `$.text()` function was stripping HTML tags, like `<img>`.

Fix display of icons in system information tab

---

src/Api/API.php
src/Search.php

| Fixed tickets | #15593
Standardize search option group entries as being an array with the label in a "name" property. When getting the search options from the legacy API, this wasn't consistent.

fix group formats in API listSearchOptions

---

src/Ticket.php
tests/emails-tests/41-image-src-with-no-quote.eml
tests/functional/Ticket.php
tests/imap/MailCollector.php

| Fixed tickets | #15578
Lack of quotes in embedded images (e.g. `<img src=cid:xxx>`) was not handled by the mail collector.

Fix handling of unquoted images src in mail collector

---

templates/components/itilobject/timeline/pending_reasons_messages.html.twig

Followup for https://github.com/glpi-project/glpi/pull/15696, improve display for long labels.
Before:
After:
| Fixed tickets | !29772

Display pending reason in tickets details 2

---

src/CommonDBTM.php
src/Console/Maintenance/EnableMaintenanceModeCommand.php
src/DBmysql.php

| Fixed tickets | #15543 (maybe)
The only way I was able to recreate the issue from #15543 was if I had the maintenance mode text set to something before running the CLI command to enable maintenance mode and I didn't specify any new text.
I added two fixes which both independently handle that case.
First, the `$input->hasOption('text')` is always true because it only checks if the option is defined rather than if the user specified a value for it. So, even if the user doesn't add `--text` to the command, it is still true. A null check was added as well. If the user wants to override the text already set and show nothing, they can specify an …

fix enable maintenance cli

---

src/Html.php
src/PlanningExternalEvent.php
src/User.php

Prevent 2 errors message on planningexternalevent form
`PHP Deprecated function (8192): strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/glpi/src/PlanningExternalEvent.php at line 160`
`Uncaught Exception ValueError: array_combine(): Argument #1 ($keys) and argument #2 ($values) must have the same number of elements in /var/www/glpi/src/Html.php at line 4816`

fix(planning external event): prevent errors

---

tests/GLPITestCase.php

Getting the root entity while writing tests is frustrating because you have to remember its exact name (`_test_root_entity`).
Maybe my memory isn't so good because I'm never sure of the exact name and up searching for it in other files most of the time.
Adding a simple helper method to `GLPITestCase.php` allow memory-impaired developers to rely on code completion for futures tests ;)

Add helper method to access the tests root entity

---

src/CommonITILTask.php
src/ITILFollowup.php
src/PendingReason_Item.php
templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/pending_reasons.html.twig
tests/functional/PendingReason.class.php

Similarly to #15696, this was a feature from the 9.5 backport that was not integrated properly into GLPI 10.
I think @cedric-anne also suggested that we fix that a while ago but it didn't go anywhere at the time.
When adding a new followup to a ticket, it is possible to remove the `pending` status but we can't interact with the pending reasons: 
After changes:
| Fixed tickets | !29772

Allow pending reason edition from new fup/task form

---

src/CommonDBTM.php
src/Log.php
tests/functional/CommonDBTM.php

| Fixed tickets | see #15543 
When a value was update to `null`, it was actually not update because the `isset($this->fields[$field])` was returning false. Using `array_key_exists($field, $this->fields)` fixes this issue.
Issue was introduced in 5bab9bda02a60f3cd49dde9053c19b7ab501177d (10.0.6).

Fix handling of null values during updates

---

src/CommonITILTask.php

In "list" view, change tasks generated errors in logs and were not displayed.
Before:
After:
| Fixed tickets | !29851

fix(planning): error with change tasks

---

src/Change.php

handle HTML from searchoption
- analysis impact
- deployment impact
- checklmist
- backup plan
- control list
before : 
after : 
| Fixed tickets | !29904

fix(Change): handle HTML from searchoption

---

src/MailCollector.php

| Tests pass?   | I hope
Mailbox hierarchy delimiter can be "/" or "." (it depend on server NAMESPACE configuration).
So I propose to use "globalName" (which already contains the full path of folder constructed by Laminas lib with the correct server delimiter), instead of using "localName" and construct the path on GLPI side.
This only affect "preselection" feature in collector UI configuration form.

fix: imap folders globalname

---

install/migrations/update_10.0.9_to_10.0.10/ldap_fields.php

```
PHP Error (1): Allowed memory size of 1073741824 bytes exhausted (tried to allocate 8192 bytes) in
.../src/DBmysql.php at line 570
```
| Fixed tickets | !29888

fix(migration 10.0.9 to 10.0.10): PHP Error Allowed memory size

---

src/CommonDBTM.php
tests/functional/CommonDBTM.php

Alternative to #15709.
When trying to see how to add a test case for #15709, I figured out that a call to `CommonDBTM::updateInDB()` passing a field key that does not actually exists is not supposed to happen. Indeed, `$this->updates` should contains only keys that are existing in `$this->fields` due to the following code: https://github.com/glpi-project/glpi/blob/b46d23510c9a5edb3d85e689d9e8508e2a91ed2f/src/CommonDBTM.php#L1651-L1652
So, if `$this->updates` contains an entry that does not correspond to a valid key in `$this->fields`, it means that `pre_updateInDB()` method of the corresponding item probably does something …

Trigger a warning when an updatable field does not exist

---

install/migrations/update_10.0.9_to_10.0.10/ldap_fields.php

Follows #15733.
Fixes `` SQL Error "1139": Got error 'repetition-operator operand invalid' from regexp in query "SELECT `glpi_users`.`id`, `glpi_users`.`user_dn`, `glpi_users`.`sync_field` FROM `glpi_users` WHERE `authtype` = '3' AND ((`user_dn` REGEXP '(<|>|(&(?!#?[a-z0-9]+;)))' OR `sync_field` REGEXP '(<|>|(&(?!#?[a-z0-9]+;)))'))" ``.

Fix migration on MySQL 5.7

---

src/Planning.php

On the planning screen, when you wanted to add all the users in a group, the group dropdown filtered to display only those groups that could have tasks, whereas it wasn't the group you were adding, but just its members.
| Fixed tickets | !29922

fix(planning): All users of a group restriction

---

src/Inventory/Asset/NetworkPort.php
tests/functional/Glpi/Inventory/Assets/NetworkEquipment.php

When an ```asset``` is updated throught networkport connection 
(ex with : ```Update only mac address (mac on switch port)```) 
```xml
<PORT>
<CONNECTIONS>
<CONNECTION>
<MAC>00:0b:84:09:c1:5e</MAC> //this asset (handle as unmanaged in this case)
</CONNECTION>
</CONNECTIONS>
<IFDESCR>GigabitEthernet1/0/1</IFDESCR>
<IFINERRORS>0</IFINERRORS>
<IFINOCTETS>19636462</IFINOCTETS>
<IFINTERNALSTATUS>1</IFINTERNALSTATUS>
</PORT>
```
```RuleMatchedLog``` are added only on ```create``` step 
Add missing ```RuleMatchedLog``` on ```update``` step
| Fixed tickets | !29945

fix(Inventory): add ruleMatchedLog on update too

---

src/Inventory/Asset/MainAsset.php
tests/functional/Glpi/Inventory/Assets/Computer.php

Currently, when a domain disappears from the inventory file
it is only deleted (and visible in the "Lock" tab)
It should be purged immediately
| Fixed tickets | !29950

fix(Inventory): purge useless Domain instead of delete it

---

src/Config.php
src/Dashboard/Grid.php

Restores the ability for users to disable the mini dashboard at the top of the ticket page. Previously, users could leave the value empty to hide the mini dashboard. However, PR #15382 changed this mechanism, using the empty value to default to the general configuration. This PR introduces a new 'Disabled' option for the 'Default for tickets (mini dashboard)' setting in user preferences, reinstating the ability for users to hide the mini dashboard if desired.

fix: Adds a "disabled" option to the dashboard preferences for tickets

---

src/Dashboard/Provider.php
tests/units/Glpi/Dashboard/Provider.php

| Fixed tickets | #15708 
Problem of association between data and labels on the "Tickets by SLA status and by technician group" graph.

fix(dashboard): Data error on "tickets by agreement status and technician group" graph

---

templates/components/form/header_content.html.twig

Fix header not displaying root entity name

---

templates/components/itilobject/footer.html.twig

See https://github.com/glpi-project/glpi/pull/15725
Moves the save button to 1st, to allow saving via the enter key.
Previously, when a text input was validated via the enter key, the ticket was deleted, as it was the 1st submit of the form.
Before:
After:

reorder save button
