CHANGELOG.md, ajax/displaypreference.php, css/includes/_includes.scss, css/includes/components/_kanban.scss, css/includes/components/_sortable.scss, css/legacy/includes/_styles.scss, front/displaypreference.form.php, inc/define.php, src/Ajax.php, src/CommonGLPI.php, src/Config.php, src/DisplayPreference.php, src/Html.php, src/MassiveAction.php, src/Plugin/Hooks.php, src/Toolbox.php, templates/components/search/controls.html.twig, templates/components/search/displaypreference_config.html.twig, templates/components/search/displaypreference_list.html.twig, templates/components/search/displaypreference_modal.html.twig, tests/functional/Config.php
Notable changes/improvements:
- AJAX actions now use the itemtype, user, and num instead of the ID for ordering and removal.
- Closing the modal will now attempt to trigger the `refreshResults` method for the fluid search view and only reload the full page when a fluid search view cannot be found (or finds multiple) or an error occurs.
- De-duplicated code between global and personal config forms
- Options are now orderable by drag and drop instead of one... at... a... time... up and down controls. Adding and removing options now doesn't trigger a reload of the iframe either. Activating and deactivating personal preferences …
=> Display preferences UX improvements

src/Html.php
Avoid seeing these kind of warnings everywhere in my code because of invalid PHPdoc ;)
=> Fix invalid PHPdoc

src/Api/HL/Middleware/InternalAuthMiddleware.php, src/Webhook.php
Session-based authentication is no longer supported with the new API, but the webhook feature was still trying to use it to authenticate when directly interfacing with the API.
To handle such cases of GLPI accessing its own API internally, I've added a new Auth middleware that isn't loaded by default which "authenticates" the API request as long as a user is logged into the session. This bypasses the default OAuth authentication feature in the API.
=> use internal auth for webhook api access

install/migrations/update_10.0.10_to_10.0.11/fix_document_item_index.php, install/mysql/glpi-empty.sql
The `timeline_position` column of `Document_Item` is sometimes used as part of a `WHERE` clause and thus must be indexed.
Example:
=> Add missing 'timeline_position' index to Document_Item

inc/config.php, install/install.php, src/Console/Application.php, src/Console/Cache/ConfigureCommand.php, src/Console/Cache/SetNamespacePrefixCommand.php, src/Console/Command/ConfigurationCommandInterface.php, src/Console/Database/EnableTimezonesCommand.php, src/Console/Database/InstallCommand.php, src/Console/Database/UpdateCommand.php, src/Console/Migration/MigrateAllCommand.php, src/Console/Migration/MyIsamToInnoDbCommand.php, src/Console/Migration/TimestampsCommand.php, src/Console/Migration/UnsignedKeysCommand.php, src/Console/Migration/Utf8mb4Command.php, src/Console/Security/ChangekeyCommand.php, src/System/Variables.php, src/Toolbox/Filesystem.php, templates/install/step1.html.twig, tests/units/Glpi/Toolbox/Filesystem.php
| Fixed tickets | #14030 !29985
For the moment, `GLPI_CONFIG_DIR` write access is considered as a mandatory requirement, but, for security reasons, one should be able to remove the write access to configuration files once GLPI has been installed/configured.
1. Remove `GLPI_CONFIG_DIR` write access from mandatory requirements
2. Checks that `config_db.php` and `glpicrypt.key` files can be written during installation process. On UI, it is done during the requirements checks.
3. Check config files can be written on CLI commands that requires it.
=> Remove `GLPI_CONFIG_DIR` write access from mandatory requirements

src/CommonDBTM.php, src/CommonDropdown.php, src/Console/Rules/ReplayDictionnaryRulesCommand.php, src/Dropdown.php, src/Profile.php, src/RuleCollection.php, src/RuleDictionnaryComputerModelCollection.php, src/RuleDictionnaryComputerTypeCollection.php, src/RuleDictionnaryMonitorModelCollection.php, src/RuleDictionnaryMonitorTypeCollection.php, src/RuleDictionnaryNetworkEquipmentModelCollection.php, src/RuleDictionnaryNetworkEquipmentTypeCollection.php, src/RuleDictionnaryOperatingSystemArchitectureCollection.php, src/RuleDictionnaryOperatingSystemCollection.php, src/RuleDictionnaryOperatingSystemEditionCollection.php, src/RuleDictionnaryOperatingSystemServicePackCollection.php, src/RuleDictionnaryOperatingSystemVersionCollection.php, src/RuleDictionnaryPeripheralModelCollection.php, src/RuleDictionnaryPeripheralTypeCollection.php, src/RuleDictionnaryPhoneModelCollection.php, src/RuleDictionnaryPhoneTypeCollection.php, src/RuleDictionnaryPrinter.php, src/RuleDictionnaryPrinterCollection.php, src/RuleDictionnaryPrinterModelCollection.php, src/RuleDictionnaryPrinterTypeCollection.php, src/RuleDictionnarySoftware.php, src/RuleDictionnarySoftwareCollection.php, src/Software.php
See #15795
I've just fixed in comments and translations. Files, classes and methods names remains unchanged (this would be a very huge job to change properly all of that).
=> Fix typo in dictionary

templates/layout/parts/global_search_form.html.twig, templates/layout/parts/page_header.html.twig
When global search bar is disable (in setup > general), the header and breadcrumbs move.
I keep the div empty to get flex working correctly.
Before:
After:
=> don't break header layout when global search is disabled

src/Cache/CacheManager.php, tests/bootstrap.php
| Fixed tickets | see !30032
I spend a few hours trying to understand why the filesystem of a customer was saturated by temporary file cache entries. The root cause was that a sub directory of the translations cache directory was owned by the `root` user, but file entry writing failure was not triggering any error/warning.
To get warnings, the logger must be defined on the cache adapter.
Warnings will look like this:
```
glpiphplog.WARNING: Failed to save key "{key}" of type array: fopen(/var/www/glpi/files/_cache/core/739e585a1908): Failed to open stream: Permission denied {"key":"0d74920f7b4ea661e0670b6c28ffda3a7c2eb869","exception":"[object] …
```
=> Add warnings on cache issues

install/migrations/update_10.0.2_to_10.0.3/notifications.php
| Fixed tickets | https://forum.glpi-project.org/viewtopic.php?pid=505474
Fixes following error:
```
glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Glpi\Toolbox\Sanitizer::decodeHtmlSpecialChars() must be of the type string, null given, called>
Backtrace :
...s/update_10.0.2_to_10.0.3/notifications.php:100 Glpi\Toolbox\Sanitizer::decodeHtmlSpecialChars()
install/migrations/update_10.0.2_to_10.0.3.php:59  require()
src/Update.php:260                                 update1002to1003()
src/Console/Database/UpdateCommand.php:212         Update->doUpdates()
vendor/symfony/console/Command/Command.php:298 …
```
=> Fix error on 10.0.2 -> 10.0.3 migration

src/Dashboard/Widget.php
Loading the central page with a search results card causes the search criteria saved in the session to be replaced with the criteria used by the dashboard. The search parameters should not be saved to the session at all.
=> Fix dashboards overwriting session search criteria

src/System/Requirement/SessionsSecurityConfiguration.php, tests/units/Glpi/System/Requirement/SessionsSecurityConfiguration.php
| Fixed tickets | !30084
When requirements are checked on CLI context, the used PHP configuration file may often be different than the one that will be used in web context. For most requirements, it is not an issue. Either they are not strictly related to PHP configuration, either fatal errors will be triggered if they are not met on web context (e.g. a missing extension will propably result in fatal errors).
For the session cookie configuration check, it may be an issue. Indeed, we should not explicitely say that `Sessions configuration is secured.` if we cannot be sure that it is really the case on web context. I propose to always show …
=> Do not trust session cookie configuration on CLI context

src/Inventory/Asset/MainAsset.php, src/RuleImportAsset.php, templates/pages/admin/inventory/upload_result.html.twig, tests/functional/Glpi/Inventory/Inventory.php
```RuleAction``` ```import denied (no log)``` should not add the asset to ```RefusedEquipment```
```RuleAction``` ```Refused import -> assign -> yes``` should add the asset to ```RefusedEquipment``` (currently the case)
This PR fix ```import denied (no log)``` action
Fix form for importing inventory files (massively)
| Fixed tickets | !29952
=> fix(Rule): do not import as refused equipement if rule denied with  no log

src/System/Requirement/DataDirectoriesProtectedPath.php, tests/units/Glpi/System/Requirement/DataDirectoriesProtectedPath.php
| Fixed tickets | !30035
When a GLPI data directory name was starting with the name of the GLPI directory itself, this directory was considered as unsecured.
For instance, when `GLPI_ROOT_DIR=/var/www/glpi` and `GLPI_VAR_DIR=/var/www/glpi_files`.
=> Fix data directories safeness check

.github/workflows/ci.yml, README.md, src/Config.php, src/System/Requirement/DbEngine.php, tests/functional/Config.php, tests/functional/Search.php, tests/units/Glpi/System/Requirement/DbConfiguration.php, tests/units/Glpi/System/Requirement/DbEngine.php
Tests are failing on the `main` branch due to usage of a JSON DB field (introduced in #15229). We could probably fix them, as it is probably just an issue only in the DB check logic, but I am not sure it is worth the effort.
The MariaDB 10.3 EOL is already passed (05/2023).
The MariaDB 10.4 EOL will arrive soon (06/2024).
The MariaDB default version on main Linux distributions is now 10.5 at least:
| OS | Release date | MySQL version | MariaDB version |
| -------- | -------- | -------- | -------- |
| RHEL 8.5     | 11/2021     | 8.0     | 10.5     |
| RHEL 8.6/9.0     | 05/2022     | 8.0     | 10.5     |
| RHEL 8.7/9.1 …
=> Drop support of MariaDB < 10.5

src/Security/PermissionManager.php
MFA has a huge performance impact even when not enabled.
---
The main issue is fixed by my first commit ec903d06e5eede8aa2fbf0a1e69bd94035f630ee.
The SQL request was faulty and returned a lot more results than expected, which is very bad as we are performing costly operation on these results later in the function.
Before changes, the request would return duplicated results:
After fixing the query, we get the expected results:
This small change fix the main issue and reduce the `getAllEntities()` function execution time from 10s to 0.002s on a GLPI with around 8000 entries in `glpi_profiles_users`.
---
The second commit 766c6f23914a25c221303e05414fe895db351cb4 follow the recommandation found [here](https://github.com/kalessil/phpinspectionsea/blob/master/docs/performance.md#slow-array-funct …
=> Fix MFA performances

front/css.php, src/Application/View/Extension/FrontEndAssetsExtension.php, src/Html.php
This Pull Request aims to improve the way custom themes are handled in the front/css.php file. Currently, when loading the relative path of the user's theme via front/css.php, it inadvertently exposes sensitive server structure information, which is undesirable.
To address this issue, this modification proposes the addition of a specific parameter is_custom_theme in front/css.php requests. When is_custom_theme is set to 1, GLPI will recognize that the request pertains to a custom theme and will load the theme directly from the correct directory, without exposing internal server paths. This enhancement enhances security by …
=> Enhancing Custom Theme Handling in front/css.php

src/Planning.php
Fix warning message on ticket search
`Deprecated: htmlspecialchars(): Passing null to parameter (Sstring) of type string is deprecated in /mnt/data/glpi/src/Planning.php on line 263`
| Fixed tickets | !30152
=> fix(search): deprecated htmlspecialchars

js/fileupload.js
| Fixed tickets | #15636
After some reverse engeneering, I figured out that there was an undocumented `internal` option that could be passed to `mceInsertClipboardContent` command. Passing this option with the `true` values disable some filtering operations that seems to be the cause of the issue here.
I was not able to identify exactly what is the issue here, and if it is a bug from TinyMCE or an expected behaviour. I will probably open an issue on their repository later.
To reproduce :
- create a solution template that contains a table with a background color;
- create a ticket and add a solution based on this template;
- check whether the …
=> Prevent TinyMCE to remove styles when content is pasted from a template

src/DBmysql.php, src/DBmysqlIterator.php, tests/units/DBmysqlIterator.php
| BC breaks?    | kind of
I'm almost sure this has not been handled in main.
I've always considered that was an mistake; fortunately this is not widely used in core code. Depreciation is not strict, unless constant is set (like in test suite).
=> Deprecate (non strict) usage of raw SQL in iterator

composer.lock
| Fixed tickets | !29546 !29492 !30032
There was a bug in symfony/cache that was resulting in a lack of cleaning cache temporary files. This caused disk space to fill up with thousands of files in the `files/_cache` directory. This bug was present only if the target path of the cache file was not writable.
It has been fixed in the latest symfony/cache version (see https://github.com/symfony/symfony/pull/52105).
=> Prevent cache dir to be filled by temporary files

src/CommonITILTask.php, tests/functional/TicketTask.php
| Fixed tickets | #15650
This Pull Request addresses an issue in the `CommonITILTask` class where the manually edited task duration was not replacing the planned duration. 
The changes in this PR ensure that the task duration and the planned duration are bi-directionally linked. This means that if the `actiontime` (task duration) is manually set, it will compute and update the end date accordingly. Conversely, if the `actiontime` is not set, it will compute it based on the difference between the start and end times.
This fix is crucial as it allows the actual time spent on a task to be accurately reflected, even if it differs from the …
=> Fix Task Duration Update Behavior in CommonITILTask

src/CommonDBTM.php, src/DbUtils.php, tests/functional/DbUtils.php
Currently, when a class overrides `CommonDBTM::getTable()` to force usage of a specific table, this override is not reflected in `getTableForItemType()` results. It does not seems to produce issues for now because overrides are not used for assets yet, but there are lots of usages of `getTableForItemType()` that would fail if someones push into `$CFG_GLPI['xxx_types']` a class that overrides the `CommonDBTM::getTable()` method. For instance, in #15729 , I figured out that many pieces of code were failing.
Replacing all usages of `getTableForItemType()` by `$itemtype::getTable()` is not really an option, at least in a short …
=> `getTableForItemType()` must support `CommonDBTM::getTable()` overrides

SECURITY.md
As now, huntr specialize only in AI/ML stuff.
I added github advisory possibility as it's opened since a few month for reporters
=> remove huntr from security channels

front/tracking.injector.php
Correction of a bug that prevented the creation of ticket in helpdesk interface.
When a user tried to create a ticket from the helpdesk interface, the creation failed and ended up with a white screen.
In the logs, we could see the following error:
```
[2023-11-02 09:59:16] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: json_decode(): Argument #1 ($json) must be of type string, array given in /home/glpi/main/front/tracking.injector.php at line 78
Backtrace :
front/tracking.injector.php:78                     json_decode()
public/index.php:82                                require()
```
A redundancy in the class …
=> Fix helpdesk ticket creation

.gitignore
In main branch, as it will be mandatory to use `/public` as  GLPI root directory, we removed `.htaccess` files. A side effect of this was that the `config` dir was not containing any versionned file and therefore was no more part of the repository. Adding a `.gitkeep` file will fix that.
I also simplified the `.gitignore` file that was containing way too much instructions related to config files.
=> Ensure `config` dir is included in release archive

src/NotificationTarget.php, src/NotificationTargetChange.php, src/NotificationTargetTicket.php, src/Toolbox.php, tests/functional/NotificationTargetTicket.php
To resume the following PR https://github.com/glpi-project/glpi/pull/14428
which continued the work of  https://github.com/glpi-project/glpi/pull/14256
and since https://github.com/glpi-project/glpi/pull/15831
The idea would be (via HTML anchors) to position the user directly on the validation form (which concerns him) in the time line.
you can use this URL (must be adapted to your GLPI url) to test
jsut  replace ```#ID_TICKET#``` and ```#ID_VALIDATION#```
```
/index.php?redirect=ticket_#ID_TICKET#_Ticket%24main%23TicketValidation_#ID_VALIDATION#
```
=> feat(Approval): use anchor to point directly to the form in the timeline

src/CommonITILObject.php
A change on the bugfix branch changed the code related to getting validation timeline items so `$validation` was now an object rather than an array of data.
=> fix validation timeline item retrieval

ajax/webhook.php, js/modules/Monaco/MonacoEditor.js, src/Webhook.php
| Fixed tickets | !29810
There was a request to be able to send the related ticket's external ID inside a webhook payload for a followup. Originally, I tried to find a way to implement this at the API level, but handling polymorphic relations (a followup may belong to multiple types) proved toomessy and it really isn't needed for the API itself, just edge-cases in webhooks.
Instead, the existing array of supported types in the webhook feature is used to determine if an item type like Followup has parent types. When the webhook body is calculated, it will resolve the correct parent type and gather the related data with "parent_item" prefixes …
=> Parent item data in webhooks

src/Api/HL/RSQL/Lexer.php
Bad use of `empty()` was seeing an RSQL filter value of '0' as if it were a missing value.
=> Fix 0 being read as missing rsql value

src/Dropdown.php
Readonly Dropdown with width set in parameters were not applied because html attributes were concatenated
`<span class="form-control" readonlystyle="width: 100%">XXXXXXXXXXXXXX</span>`
becomes :
`<span class="form-control" readonly style="width: 100%">XXXXXXXXXXXXXX</span>`
=> Fix readonly dropdown with defined width

src/System/Requirement/PhpSupportedVersion.php, tests/units/Glpi/System/Requirement/PhpSupportedVersion.php
I guess we will release GLPI 10.0.11 after the PHP 8.0 security support end date.
=> Discourage usage of PHP 8.0

src/Search/SearchEngine.php, tests/functional/ITILFollowup.php, tests/functional/TicketTask.php
| Fixed tickets | !29810
Add meta options for timeline types like followups to be able to search fields of the parent type (tickets, changes, problems). Timeline types are usually not searchable, so this can really only be used in the API or the criteria filter feature in webhooks.
=> Add parent meta options for timeline types

templates/components/itilobject/actors/field.html.twig
Jquery's ready wrapper do not work as expected in our AJAX fetched content.
The documentation state the following:
> The .ready() method offers a way to run JavaScript code as soon as the page's Document Object Model (DOM) becomes safe to manipulate. This will often be a good time to perform tasks that are needed before the user views or interacts with the page, for example to add event handlers and initialize plugins. When multiple functions are added via successive calls to this method, they run when the DOM is ready in the order in which they are added. As of jQuery 3.0, jQuery ensures that an exception occuring in one handler does not prevent subsequently added handlers from executing.
>
>Most browsers [provide similar functionality](https://caniuse.com/#search=DOMContentLoaded) in …
=> Do not use jquery.ready when rendering actors

src/Console/Build/GenerateCodeBaselineCommand.php, src/Console/Build/GenerateCodeManifestCommand.php, src/Console/Diagnostic/CheckSourceCodeIntegrityCommand.php, src/System/Diagnostic/SourceCodeIntegrityChecker.php, tests/functional/Glpi/System/Diagnostic/SourceCodeIntegrityChecker.php, tools/build_glpi.sh
- `bin/console diagnostic:source_code_integrity --baseline` - (Re-)Generate the baseline file manifest in the `version/X.Y.Z` file based on the current files. This is what is used when building the release archive.
- `bin/console diagnostic:source_code_integrity` - Display a summary of differences between the baseline file manifest and the current files. This is just a table of relative paths and the status (missing, added, or altered). Specific differences are not displayed.
-  `bin/console diagnostic:source_code_integrity --diff` - Outputs a diff of changes between the release archive and the current files. Does not work …
=> Files integrity check

templates/components/dropdown/limit.html.twig
When you customize the number of "Results to display by page" with "70" for example, which is not one of the original values proposed, the limit applied is indeed 70, but the dropdown displays 5.
Settings:
Before:
After:
=> fix(search): limit dropdown

src/CommonITILActor.php, src/CommonITILObject.php
A new install of GLPI 10.0.10 generates a "Truncated incorrect DECIMAL value: ''" SQL warning when viewing the new ticket form as it tries calling `CommonITILActor::getActors` with an empty string as the ID.
=> fix incorrect decimal sql warning on new ticket form

src/RichText/UserMention.php, tests/functional/Glpi/RichText/UserMention.php
Prevent  error when ```UserMention``` can't convert ```HTML``` to ```XML``` without thrown error from ```try / catch``` (but just by returning ```null``` or ```false```)
_@return SimpleXMLElement|null — a SimpleXMLElement or FALSE on failure._
```shell
[2023-10-26 06:01:31] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function xpath() on null in /mnt/data/glpi/src/RichText/UserMention.php at line 207
Backtrace :
src/RichText/UserMention.php:91                    Glpi\RichText\UserMention::getUserIdsFromUserMentions()
src/CommonDBTM.php:1538                            Glpi\RichText\UserMention::handleUserMentions()
src/CommonDBTM.php:1324                            CommonDBTM->post_addItem()
src/CronTask.php:375                               CommonDBTM->add() …
```
=> fix(UserMention): fix fatal error on null

src/Config.php, tests/functional/Config.php
Historical tab was empty
| Fixed tickets | !30358
=> fix(config): historical tab empty

css/includes/components/_richtext.scss
Attempts to correct the scrollbar that appeared following https://github.com/glpi-project/glpi/pull/15640
=> fix(ticket): followup display

src/RuleCommonITILObjectCollection.php
Use of `self` instead of `static` meant it was checking the default right for rule collections which is `config` rather than the specific rights for ITIL rules like `rule_ticket`.
=> fix itil rule right checks

src/Ticket.php, tests/functional/RuleTicket.php
Add missing data for ```Default profile``` criterion from rules ticket (on add and on update)
| Fixed tickets | !30117
=> fix(RuleTicket): fix default profiles criterion

install/migrations/update_10.0.10_to_10.0.11/lockedfield.php, src/Lockedfield.php
A global lock on the entites_id field is/will be problematic in several contexts:
- Deleting an entity
- Automatic transfer of assets (via rules) 
- etc ...
Lock management must not interfere with internal GLPI processes
| Fixed tickets | !30301
=> Prevent bad behavior with global  entities_id lock

src/Search.php
Improve search engine optimisation by using `UNION ALL`  instead of `UNION` on queries targeting `union_search_type` pages (e.g. `AllAssets`).
`UNION` is slower because it perform a `DISTINCT` operation on results, which should not be needed here since each query target a different itemtype (duplicated rows should thus be impossible).
Simple benchmark for the `AllAssets` page on a 300k assets database hosted on a questionable mariadb 11.1 docker container:
* `UNION`: ~20 seconds
* `UNION ALL`  ~ 14 seconds
| Fixed tickets | !29967
=> Search engine: use "UNION ALL" for union_search_type

src/Session.php
Allow us to benefit from IDE auto completion when trying to get this value rather than trying to guess the correct key name from memory.
=> Add helper function to read glpi_currenttime

js/common.js
| Fixed tickets | #12152
Corrected display of dates in reminder lists. 
For example, previously, if the item creation date was 2023-10-28 23:59:59.000 and the current date was 2023-10-30 07:00:00.000, the label displayed was not 2 days ago but yesterday.
This pull request changes the way days are counted, retaining only the date without the time. It also adds week and month management.
=> Fix incorrect display in reminder list label

src/Inventory/Asset/Drive.php, tests/functional/Glpi/Inventory/Assets/Drive.php
```interface``` value from inventory file 
```json
"storages": [
{
"description": "PCI Slot 8 : Bus 85 : Device 0 : Function 0 : Adapter 1",
"disksize": 488386,
"firmware": "HPS1NFAV",
"interface": "NVME",   <--- HERE
"model": "SAMSUNG MZVLQ512HBLU-00BH1",
"name": "PhysicalDisk0",
"serial": "9856_84F3_5641_9874.",
"type": "SSD"
}
],
```
is not used from native inventory (actuelly ```type``` is used)
```php
$mapping = [
'name'         => 'designation',
'type'    => 'interfacetypes_id',
'manufacturer' => 'manufacturers_id',
];
```
| Fixed tickets | !29959
=> fix(Inventory): use the right field for 'interface'

src/Cable.php, src/CartridgeItem.php, src/Certificate.php, src/Cluster.php, src/CommonDBTM.php, src/Computer.php, src/ConsumableItem.php, src/DatabaseInstance.php, src/Enclosure.php, src/ITILCategory.php, src/Monitor.php, src/NetworkEquipment.php, src/NotificationTargetReservation.php, src/PDU.php, src/PassiveDCEquipment.php, src/Peripheral.php, src/Phone.php, src/Printer.php, src/Rack.php, src/ReservationItem.php, src/RuleAsset.php, src/RuleImportEntity.php, src/Search.php, templates/generic_show_form.html.twig
The label "Technician in charge of the hardware" is a generic text, but it's not suitable for software. Same thing for the group.
Perhaps replace with "Technician in charge of the asset" or just "Technician in charge"?
Before:
After:
| Fixed tickets | !30281
=> fix(assets): input label

src/CronTask.php
Prevent useless HTTP request if there are no web cron tasks enabled (which should always be the case in production).
=> Do not call front/cron.php if no web tasks are enabled

src/NetworkName.php
If current user have no right on ```internet``` 
it cannot add / update IP addresses, 
but from ```NetworkName``` form ```IP Addresses``` label is displayed
which leads to confusion, see #15990
| Fixed tickets | #15990
=> fix(NetworkName): fix form with insufficient rights

src/Inventory/Asset/Drive.php, tests/functional/Glpi/Inventory/Assets/Drive.php
This reverts commit 02e72ce8007a8b46d31b41e5be6d154bdb02e5f6.
Because ```Drive``` use ```type``` for ```interfacetypes_id```
```php
public function prepare(): array
{
$mapping = [
'name'         => 'designation',
'type'         => 'interfacetypes_id',  <---- HERE
'manufacturer' => 'manufacturers_id',
];
$hdd = [];
foreach ($this->data as $k => &$val) {
if ($this->isDrive($val)) { // it's cd-rom / dvd
foreach ($mapping as $origin => $dest) {
if (property_exists($val, $origin)) {
$val->$dest = $val->$origin;
}
}
if (property_exists($val, 'description')) {
$val->designation = $val->description;
}
$val->is_dynamic = 1;
} else { // it's harddisk
$hdd[] = $val;
unset($this->data[$k]);
}
}
if (count($hdd)) {
$this->harddrives = new HardDrive($this->item, $hdd);
$prep_hdds = …
```
=> Revert "fix(Inventory): use the right field for 'interface' (#15989)"

src/NotificationTarget.php, tests/functional/NotificationTarget.php
When you not allow response on glpi notifications, the sender is replaced by getNoReplyEmailSender() but not the address used for response
=> Fix getReplyTo when not allow response

templates/components/itilobject/timeline/timeline_item_header_badges.html.twig
| Fixed tickets | #15892
When a user has their date format preference as MM-DD-YYYY, invalid date errors are shown when viewing a ticket's timeline. This is because Log items in the timeline are retrieved with `Log::getHistoryData` which already formats the date. In the template for the timeline item header badges, it tries converting it a second time which doesn't work. For now, the workaround is to show the date as-is for log entries.
I guess in GLPI 10.1 this workaround can be removed and the `Log::getHistoryData` method changed to return the raw date (and fix everything else that may use it).
=> Fix invalid date format error for ticket history in timeline

src/Log.php, tests/LDAP/AuthLdap.php, tests/functional/Agent.php, tests/functional/Appliance.php, tests/functional/Config.php, tests/functional/Document.php, tests/functional/OperatingSystem.php, tests/functional/OperatingSystemArchitecture.php, tests/functional/OperatingSystemEdition.php, tests/functional/OperatingSystemKernel.php, tests/functional/OperatingSystemKernelVersion.php
There is now a new right : 
But this right is not used for display tab
=> Add Log Right To getTabNameForItem

src/Central.php, src/System/Requirement/SafeDocumentRoot.php
The warning message about root directory configuration was displayed on all profiles, whereas other such messages are filtered so that they are only visible to admins.
| Fixed tickets | !30455
=> fix(central): warning displayed on all profiles

.github/actions/test_update-from-9.5.sh, .github/actions/test_update-from-older-version.sh, src/Console/Database/UpdateCommand.php
When DB update produces an unexpected result, CI does not provide any usefull information, see https://github.com/glpi-project/glpi/actions/runs/6812882059/job/18526239897?pr=15931
The `--skip-db-checks` option only skips checks done before performing the update. I consider we could use it also to disable checks that are done after the update. I added a comment message to invite people to run the `db:check` command.
Before:
After:
=> Enhance CI results when updated DB is not consistent

css/install.scss, css/legacy/includes/_styles.scss, src/Central.php, src/Console/System/CheckRequirementsCommand.php, src/System/Requirement/AbstractRequirement.php, src/System/Requirement/DataDirectoriesProtectedPath.php, src/System/Requirement/PhpSupportedVersion.php, src/System/Requirement/RequirementInterface.php, src/System/Requirement/SafeDocumentRoot.php, src/System/Requirement/SessionsSecurityConfiguration.php, templates/install/blocks/requirements_table.html.twig
As we recently see by checking the telemetry data, there are still lots of people that are using PHP 7.4. Highlighting the security requirements and adding a message about it on central page may encourage people to fullfill them.
Before:
After:
=> Highlight security requirements

inc/define.php
for example, i wanna add storage Fujitsu DX100 and it have power supply, but now i cannot add it
=> add 'Peripheral' to $CFG_GLPI["itemdevicepowersupply_types"]

install/empty_data.php, tests/functional/RuleCommonITILObject.php
From fresh install, user ```tech``` only have this rights for ```problem``` scope
```Problem::READMY | Problem::READALL | READNOTE | UPDATENOTE```
So a unit test that update problem with user 'tech' failed
https://github.com/glpi-project/glpi/blob/6e3f5405cca9ca1eea0ec3c5c00417b2c7d79e63/tests/functional/RuleCommonITILObject.php#L2773-L2775
=> Fix default rights on Problem for tech user

src/Ajax.php
Due to a mistake during merge of 10.0/bugfixes branch into main, the `update_current_tab` param of `loadTabContents` function dissapeared and it results in the following error:
```
Uncaught ReferenceError: update_current_tab is not defined
at loadTabContents
```
It does not seems usefull to reintroduce it, as no call to this function is redefining it. It was introduced in e0c3219131dd748f1d2e45a08618cfb72a6c3adb but was not actually used.
=> Drop useless `update_current_tab` param usage

front/databaseinstance.form.php
| Fixed tickets | !30426
This pull request solves the problem of the missing breadcrumb trail on `/front/databaseinstance.form.php` by adding an `Html::header` in `databaseinstance.form.php` file.
=> Fix no breadcrumb in db instance

composer.json
The weekly audit workflow would fail in composer 2.7 without this change. See following image
With this change, abandoned packages are still reported, but exit code of the command is 0 (success).
=> Prevent composer 2.7 audit to fail due to abandoned packages

src/Ticket.php
| Fixed tickets | !30441
This pull request allow the association of an item with a ticket when a profile doesn't have the ticket creation right. before this PR, a user without ticket creation rights has to navigate to the left tab to add an item, which is inconvenient. Now, the "Elements" section is present in the right-hand panel.
=> Fix associate items to ticket permission mistake

src/Search.php
Percentage of resolution time does not exclude waiting time. I think that the pending should freeze this evolution, so its value should be similar just before the pending and just after the exit of pending.
| Fixed tickets | !30259
=> fix(ticket): percentage of resolution time

front/stat.tracking.php
Data passed to `ajax/report.dynamic.php` was all combined as the value for `itemtype` instead of separated due to `Html::printPager` expecting each parameter to be separated by `&amp;` not `&`.
=> Fix stat export

src/Change.php, src/Features/ParentStatus.php, tests/functional/Change.php
| Fixed tickets | #15700
The status Applied for objects of type Change was not defined in the list of statuses allowing the reopening of a CommonITILObject, which prevented GLPI from updating its status, which therefore remained Applied (SOLVED).
=> Fix change status after refused solution

src/Inventory/Asset/MainAsset.php
When a ```discovery``` is performed on ```update``` (when asset is already inventoried with SNMP for example)
There is no ```RuleMatchedLog``` attached to it
=> fix(Inventory): add missing RuleMatchedLog from Discovery (on update)

src/MailCollector.php, src/NotificationEventMailing.php, src/NotificationMailing.php
The `&` in the notification settings was displayed as `&#38;` in received mails.
| Fixed tickets | !30570
=> fix(email notification): html entity decode

resources/Rules/RuleImportAsset.xml, tests/functional/Glpi/Inventory/Inventory.php
Since https://github.com/glpi-project/glpi/pull/15748
```import denied (no log) ``` no longer adds ```RefusedEquipement``` -> perfect
on the other hand, we should keep the default import denied with log.
The user can then decide to completely refuse the import without logging.
_it's frustrating to start the inventory and not have any information _
ATM I just modified the XMls dataset 
from : 
```xml
<ruleaction>
<action_type>assign</action_type>  // assign
<field>_inventory</field>          // inventory link
<value>2</value>                   // import denied (no log)
</ruleaction>
```
to :
```xml
<ruleaction>
<action_type>assign</action_type>  // assign
<field>_ignore_import</field>      // refuse import action
<value>1</value>                   // yes
</ruleaction>
```
I'm still …
=> fix(RuleImportAsset): use ignore_import instead of import denied no log from dataset

src/Item_Ticket.php, src/Ticket.php
| Fixed tickets | #15960
When a ticket is closed, massive actions and checkboxes are no longer displayed. In addition, the ability to "change" the priority of a closed ticket and to add an item to it has been removed.
**Before**
**After**
=> Fix possibility to delete assets in Closed tickets

src/Inventory/Asset/MainAsset.php, tests/functional/Glpi/Inventory/Assets/Computer.php
Originally on ```usionInventory``` plugin, the ```oscomment``` field sent in the ```RuleLocation```was retrieved from the hardware ```descritpion -> description```  node
```php
if (isset($array['HARDWARE']['DESCRIPTION'])) {
$a_inventory['fusioninventorycomputer']['oscomment'] = $array['HARDWARE']['DESCRIPTION'];
}
```
This PR retrive and add missing input before call ```RuleLocation```
| Fixed tickets | !30563
=> fix(Inventory): add missing 'oscomment' value for RuleLocation

src/Entity.php
On the root entity, when "Model for automatic entity transfer on inventories" was defined once, it was no longer possible to remove it, as the "No automatic transfer" option was only displayed on child entities. 
Since https://github.com/glpi-project/glpi/pull/14247
| Fixed tickets | !30475
=> fix(entity): mishandling of the entity transfer option

src/NetworkPort_NetworkPort.php
| Fixed tickets | !30599
Prevent this warning message:
```
glpiphplog.WARNING:   *** PHP User Warning (512): getFromDBByCrit expects to get one result, 23 found in query "SELECT `id` FROM `glpi_networkports_networkports` WHERE (`glpi_networkports_networkports`.`networkports_id_1` = '9967539' OR `glpi_networkports_networkports`.`networkports_id_2` = '9967539')". in www\glpi\src\CommonDBTM.php at line 391
Backtrace :
src\CommonDBTM.php:391                             trigger_error()
src\NetworkPort_NetworkPort.php:62                 CommonDBTM->getFromDBByCrit()
src\NetworkPort_NetworkPort.php:186 …
```
=> fix(network port): warning message in log

src/Http/ProxyRouter.php, tests/units/Glpi/Http/ProxyRouter.php
| Fixed tickets | #16035 !29545 !30449
1. When the URL contains encoded chars (e.g. `/apirest.php/GlpiPlugin%5CNamespace%5CUnexemple/`), the resulting `$_SERVER['PATH_INFO']` should correspond to the decoded char (i.e. `/GlpiPlugin\Namespace\Unexemple/`). This is how it works when file is directly served by a web server (validated on Apache), so we should reproduce the same behaviour in our PHP router.
2. When the URL contains multiple dots, it is not safe to rely on a regex to extract a possible filename (see screenshot below). I replace this by a `while` loop that will analyze all possible filenames until it found a valid one.
=> Fix PathInfo parsing in PHP router

templates/components/itilobject/timeline/pending_reasons.html.twig
This PR addresses an issue in the `pending_reasons.html.twig` file where a change on the dropdown is triggered on load to initialize the component. This was marking the form as modified, causing a confirmation prompt to appear when attempting to leave or reload the page, disrupting the user experience.
- Added a line of JavaScript to reset the `glpiUnsavedFormChanges` variable to `false` after the dropdown change is triggered. This prevents the form from being incorrectly marked as modified when the page loads.
=> fix(pending-reasons): prevent false form modification alert

src/Inventory/Asset/NetworkPort.php, tests/functional/Glpi/Inventory/Assets/NetworkEquipment.php
Like #14143 
```RuleImportAsset``` (when trying to retrive asset from ```ifdescr```) use ```ifdescr``` from ```WHERE``` statement.
But from ```Unmanaged``` asset (and converted unmanaged), ```NetworkPort``` created never use ```ifdescr```.
So at each inventory, GLPI create new ```Unmanaged``` asset (same as before)
this PR fix this
| Fixed tickets | !30363
=> fix(inventory): fixed bad handling of Unmanaged reconciliation fromuleImportAsset (by ifdescr)

src/IPNetwork.php, src/Inventory/Asset/InventoryNetworkPort.php
When an ```IPNetwork``` already exist in GLPI (for the destination entity)
a message is displayed
From the GLPI interface the message is useful but during the native inventory process, it's rather disturbing to get this error message (especially in red)
| Fixed tickets | !30610
=> fix(IPNetwork): Don't display unicity check result from native inventory process

src/DropdownTranslation.php, tests/functional/Dropdown.php, tests/functional/DropdownTranslation.php, tests/functional/NotificationTargetTicket.php
| Fixed tickets | #15801
Alternative to #15837.
1. `DropdownTranslation::getTranslatedValue()` will not return the untranslated value unless it is passed as 5th param. Previous code was sometimes generating a complename that was not containing all expected parts.
2. `DropdownTranslation::getTranslatedValue()` was using the `$_SESSION['glpi_dropdowntranslations']` variable to check whether the field had translations, but the session variable is containing the list of translated fields for the current session language, so the check was not correct when the `$language` param was not matching the session language.
=> Fix completename translated value

src/Item_OperatingSystem.php
This search option may return multiple results and should thus use `GROUP CONCAT` to prevent duplicated results.
=> Fix "Operating system name" search option

templates/pages/setup/general/general_setup.html.twig
This pull request addresses an issue where some checkboxes in the general configuration were not visible due to a width of 0px. This was caused by the `inline_field_options` applying the CSS property `w-auto`, which is inconsistent as most other checkboxes use `field_options`.
- Changed the options used for the 'Use locks', 'Default state of checkbox', and 'Display source dropdown on login page' checkboxes from `inline_field_options` to `field_options` to ensure consistent visibility across all checkboxes in the general configuration.
=> fix: checkbox visibility in general settings

src/PendingReason_Item.php, templates/components/itilobject/timeline/form_followup.html.twig, templates/components/itilobject/timeline/form_task.html.twig, templates/components/itilobject/timeline/pending_reasons.html.twig
| Fixed tickets | #15951
This pull request addresses a bug and an inconsistency in the display of the 'pending reason' for tasks or follow-ups that are not the last item in the timeline. Previously, the system allowed graphically setting a 'pending reason' for any task or follow-up, regardless of its position in the timeline. This led to a SQL error when the system tried to insert a NULL 'pendingreasons_id' into the 'glpi_pendingreasons_items' table.
The changes introduced in this pull request add a new method `canDisplayPendingReasonForItem` in the `PendingReason_Item` class. This method checks if a 'pending reason' can be displayed for a …
=> Fix Pending Reason display condition for non-last timeline items

templates/components/itilobject/timeline/pending_reasons.html.twig
**Description**
This PR provides an additional fix to the issue in the `pending_reasons.html.twig` file where a change on the dropdown is triggered on load to initialize the component. The previous PR (#16072) partially addressed this issue. However, the form was still being marked as modified, causing a confirmation prompt to appear when attempting to leave or reload the page, disrupting the user experience.
=> fix(pending-reasons): additional fix to prevent false form modification on alert

src/CommonDBTM.php, tests/functional/CommonDBTM.php
| Fixed tickets | !30569
In a plugin that stores namespaced itemtypes in an `itemtype` field, this field is considered changed everytime the corresponding form is submitted.
This is due to a combination of concurrent logics:
- comparison is done using the $input value (expected to be sanitized) VS the escaped $fields value, see https://github.com/glpi-project/glpi/blob/d4a8ae89aef14572f8922af70d23fcdd5b82ebfa/src/CommonDBTM.php#L1660
- itemtypes are not sanitized, see https://github.com/glpi-project/glpi/blob/d4a8ae89aef14572f8922af70d23fcdd5b82ebfa/src/Toolbox/Sanitizer.php#L76-L80
With this logic, `$this->input[$key]` value is …
=> Prevent namespaced itemtype to be falsely considered as changed

src/Calendar.php, src/CommonITILRecurrent.php, tests/functional/CommonITILRecurrent.php
If a recurrent ticket's start date was outside its defined calendar some calculation were not done properly.
The fix is not easy to explain, IMO you should mainly look at the new test cases and make sure you agree with their expected results.
| Fixed tickets | !30651
=> Fix recurrent ticket computation when start_date is outside of calendar

src/DatabaseInstance.php
In the database instance view, some items associated with database instances are listed as associated but cannot be found in the database. This problem generates an undefined "name" field error.
Here the error : `PHP Warning (2): Undefined array key "name" in /var/www/glpi/src/DatabaseInstance.php at line 486`
=> Fix associated items not found in DB instances

install/install.php
Fix bad replacement in install script. This `$link` variable is a `mysqli` object, not `DBmysql`. There was one other instance of a bad replacement that was previously fixed in this file.
=> Fix broken install script

src/Ticket.php
| Fixed tickets | !30498
Different results between the satisfaction survey table in the personal view and the filter assigned to it in the view of tickets awaiting satisfaction survey.
The problem is a mistake between the two queries which are supposed to return the same result.
=> Fix satisfaction survey link criteria

install/install.php
When installing GLPI, the user is shown a "Database created" message immediately after the empty database is created (or nothing if an existing one was selected). At that time, the tables are still being created and the default data being added, but it isn't clear to the user. This PR adds a message just before the table creation process starts.
=> enhance db create msg during install

CHANGELOG.md, src/Csv/LogCsvExport.php, src/Log.php, src/NotificationTargetCommonITILObject.php, src/NotificationTargetProject.php, src/NotificationTargetProjectTask.php, templates/components/itilobject/timeline/timeline_item_header_badges.html.twig, templates/components/logs.html.twig, tests/functional/Log.php
More correct fix of #15901. This removes the automatic formatting of dates in the `Log::getHistoryData` and moves the formatting to the point where the dates are actually shown.
=> Do not format dates in getHistoricalData

src/CommonITILObject.php
| Fixed tickets | !30496
Filtering tickets by category in the global kanban was not working. 
Searching by category was done via a text comparison, but a ticket's category was defined by its ID.
Changed the definition of the categorory field so that it now corresponds to the category name.
=>  Fix category filter in tickets Kanban

js/modules/Monaco/MonacoEditor.js, src/Webhook.php, templates/components/form/fields_macros.html.twig, templates/pages/setup/webhook/webhook.html.twig, templates/pages/setup/webhook/webhook_headers.html.twig
Currently, the URL, custom headers, and payload are all processed as twig templates. However, only the payload editor was actually using Monaco. The custom header value inputs were using a basic autocomplete which didn't make sense if you wanted more than just a single item property on its own. The URL field didn't have any autocomplete, so it wasn't obvious that it could accept twig tags.
This PR adds:
1. A helper function that returns a set of editor options that lets you configure an editor to mimic a `text` input with a single line.
2. A workaround for the global registration of completion items per language which …
=> Monaco editors for webhook url and headers

src/CommonITILObject.php, src/CommonITILSatisfaction.php, templates/components/itilobject/itilsatisfaction.html.twig
| Fixed tickets | #16009
When the response time has expired, the message Satisfaction survey expired is displayed. If the user has added a note before the time limit expires, the note is visible, otherwise the message No response has been given is displayed.
**Response gived**
**No response gived**
Verification used to be done in CommonItilObject, which called CommonItilSatisfaction or displayed the error message. Now, whether or not the message is displayed is managed on the twig page of satisfactions.
=> Add the possibility to see the result of satisfaction survey once expired

src/NotificationTarget.php, tests/functional/Notification.php
The notification system does not behave correctly with recursive items.
Lets assume we have a contract on the root entity with children entities enabled.
A user with an authorization on a sub entity can see the contract but won't receive any notifications.
You can see this example in details in the added test case, which is failing without the other changes.
| Fixed tickets | !29820
=> Fix notification entity restriction

src/NotificationTemplate.php, tests/functional/NotificationTemplate.php
| Fixed tickets | #15607
Added a piece of code already present in GLPI to NotificationTemplate's process() function to convert links relative to a domain into absolute links.
**Before**
**After**
=> Fix reference url computer error

.github/actions/init_build.sh, .github/workflows/ci.yml
1. Do not check platform requirements on PHP 8.3. Checks were already ignored on PHP 8.2, because some of our dependencies are not marked as compatible with PHP > 8.1, even if they are probably compatible. We cannot update them because new versions are not compatible with PHP 7.4. E.g. `friendsoftwig/twigcs` v6.3 has support of PHP 8.3 but no support of PHP 7.4.
2. Use PHP 8.3 instead of PHP 8.2 for checks done on PRs.
3. Remove MySQL and MariaDB recent releases that are not marked as LTS. They are producing a new release every 3 months and it will take too much time to update our ci matrix so often. Moreover, these non LTS …
=> Review CI PHP/SQL versions matrix

src/Plugin.php
| Fixed tickets | #16075
The  `plugin_xxx_deactivate` hook was almost never executed as corresponding plugin `hook.php` file was not loaded.
=> Fix `plugin_xxx_deactivate` hook execution

lib/bundles/base.js
`gettext.js` tries to replace `%x` by extra args.
- `__('Created by %1$s on %2$s')` will return `Created by undefined$s on undefined$s`
- `__('Created by %1$s on %2$s', 'glpi', 'me', '2023/12/07')` will return `Created by me$s on 2023/12/07$s`
With proposed patch, `%x$y` will be protected by an extra `%` (e.g. `%%x$y`), so the translation component could be used as expected: `__('Created by %1$s on %2$s').replace('%1$s', 'me').replace('%1$s', '2023/12/07')`.
=> Fix handling of `%x$y` in JS translations

install/migrations/update_10.0.10_to_10.0.11/states.php, install/mysql/glpi-empty.sql, src/Unmanaged.php
Alternatively, `Unmanaged` entry may be removed from `$CFG_GLPI['state_types']`; dunno what the best solution is.
=> Unmanaged is present in CFG_GLPI['state_types'] but missing in database

src/RefusedEquipment.php
In addition of https://github.com/glpi-project/glpi/pull/15604
Even if the column is updated in the database, GLPI continues to display a warning because 
GLPI compares the data length with the type of the corresponding ```search option``` with ```CommonDBTM->FilterValues```
Is it possible to add it to the 10.0.11 release?
=> fix(SearchOption): change type for IP and MAC

src/Inventory/Asset/Unmanaged.php, tests/functional/Glpi/Inventory/Assets/Unmanaged.php
The status of an ```Unmaneged``` device is calculated even before knowing whether a device already exists with the MAC address (i.e. converted).  
In addition, the ```checkConf``` function did not retrieve the ```states_id_default```, so this was always equal to ```0```
this Pr fix this
| Fixed tickets | !30564
=> fix(Unmanaged): do not empty status of the converted asset, when it's brought up from discovery

src/User.php
| Fixed tickets | !30769
Alternative to #16172.
1. On CLI context, the `_email` input key should be allowed to permit emails to be synchronized with LDAP during execution of `ldap:sync` command.
2. Previous logic was checking `$protected_input_keys > 0`, but as `$protected_input_keys` was an array, condition was probaly always `true`. I fixed that.
=> Allow LDAP sync command to sync emails

src/HTMLTableEntity.php
Prevent warning message:
```
PHP Deprecated function (8192): str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in .../src/HTMLTableEntity.php at line 187
```
=> fix(inventory): prevent warning message

src/AuthLDAP.php
On 10.0.11 it's impossible to update "Advanced information" for an LDAP server if "TLS" files options are empty.
=> fix(ldap): do not check TLS files if empty

js/dashboard.js
Toggling fullscreen mode on a dashboard would not work on accounts when there were no filters shown/the user didn't have access to filters. When it would try to enable fullscreen, it tried to force edit mode to be disabled. When it did that, `sortable` was called for the filter container element and was failing since there were no elements under that container.
=> Fix dashboard fullscreen toggle

templates/components/search/query_builder/criteria_group.html.twig
Since #15861, but after check it was present before merge (probably due to a previous redesign of search), when adding a metaciteria within a group, it's sub part doesn't show:
This was due to usage of square brackets in the id, that is forbidden (browser mays autofix them, but jquery no)
=> id attributes cannot contains square brackets

src/Search.php, src/Toolbox/DataExport.php
| Fixed tickets | !30871
When exporting to CSV, some empty data appeared with &nbsp;
Example with the User > Computer Emails column:
=> fix:(export): &nbsp; in CSV

src/Change.php, src/Problem.php
| Fixed tickets | #13908
Opening date was not in the defaults array for Change or Problem, so when the predefined value was loaded, it was made a hidden value instead of changing the value in the displayed field.
=> Fix hidden predefined dates for changes and problems

src/Dropdown.php, src/Reservation.php
| Fixed tickets | #16074
By default, a timestamp dropdown will automatically increase the `max` parameter to match the current `value` if it is higher than the specified `max` and fill in the values between the `min` and `max` based on the `step`. This causes a lot of client-side and network performance issues when the step is too small or the value is too big. For example, a reservation set for 60 days would cause over 17,000 options to be added to the dropdown assuming a `time_step` of 5 minutes.
I don't know if there is a legitimate case for expanding the generated options range like this, but to avoid breaking something I added a new …
=> Improve reminder duration dropdown performance

src/Rule.php
| Fixed tickets | Related to #14543
When a criteria has only a single value possible like "Exists" or "Not exists", a hidden input is added with a value of 1 rather than showing a dropdown. In test mode however, it shows a dropdown of options as well as adding the hidden input. Both values are sent to the server, and since the hidden field is after the displayed one, its value overrides the selection. In this case, the hidden field is not needed.
=> Do not add duplicate hidden field input in rule test mode

src/QueuedNotification.php
Fix to use **getPendings** on QueueNotification in the same time of create a message to notify
Example: There are a plugin from TICGAL(Golden Partner) called MFA that send an email with OTP (one time password) by GLPI notifications and the function **forceSendFor** to process the queue, but the queue is not processed because getPendings filter are '<' and in the moment of **forceSendFor** is called the time is '=' of time registered, so the filter must be '<='
=> Fix to use getPendings on QueueNotification 

install/migrations/update_10.0.11_to_10.0.12.php, install/migrations/update_10.0.11_to_10.0.12/duplicate_searchopt_fixes.php, src/ObjectLock.php, tests/functional/Search.php
Prevent warning message when locks are enabled in `Setup > General`:
```
PHP User Warning (512): Duplicate keys found in search options for item type Computer: 205, 206 in .../src/Search.php at line 8282
```
=> fix(object lock): duplicate keys in search options

src/System/Requirement/AbstractRequirement.php, src/System/Requirement/DataDirectoriesProtectedPath.php, src/System/Requirement/DbConfiguration.php, src/System/Requirement/DbEngine.php, src/System/Requirement/DbTimezones.php, src/System/Requirement/DirectoriesWriteAccess.php, src/System/Requirement/DirectoryWriteAccess.php, src/System/Requirement/Extension.php, src/System/Requirement/ExtensionConstant.php, src/System/Requirement/ExtensionGroup.php, src/System/Requirement/InstallationNotOverriden.php, src/System/Requirement/IntegerSize.php, src/System/Requirement/LogsWriteAccess.php, src/System/Requirement/MemoryLimit.php, src/System/Requirement/PhpSupportedVersion.php, src/System/Requirement/PhpVersion.php, src/System/Requirement/ProtectedWebAccess.php, src/System/Requirement/SafeDocumentRoot.php, src/System/Requirement/SeLinux.php, src/System/Requirement/SessionsConfiguration.php, src/System/Requirement/SessionsSecurityConfiguration.php, src/System/RequirementsList.php
| Fixed tickets | !30887
The `Glpi\System\Requirement\AbstractRequirement` has a bad design that results in executing checks when the `isOptional()` and/or the `isOutOfContext()` methods are used. For instance, when executing the `ldap:sync` command, if the `marketplace` directory is not writable (being writable is not a mandatory requirement), an error occurs (`PHP Warning (2): mkdir(): Permission denied in /var/www/glpi/src/Toolbox.php at line 1222`).
I changed default values for `$optional`/`$recommended_for_security`/`$out_of_context` to null and adds a constructor, with previous default values, that can be used to define them easilly. …
=> Prevent useless optional/out of context requirement checks

js/glpi_dialog.js, js/planning.js
| Fixed tickets | #13534
Two changes:
1. When the last visible modal is closed, all backdrops are forcibly removed.
2. When opening the planning modal, the calendar becomes unselectable for half of a second to prevent extra clicks from opening more modals.
=> Prevent planning modal duplicates

src/User.php
Due to the user's ID being a string in the input array and being used in a strict comparison with the logged in user's ID which should always be an integer in the session data, users were not able to update their own "protected" fields such as API token, emails, etc unless the `currentUserHaveMoreRightThan` check also passes. My database must have some bad/orphaned data related to rights as a user with a self-service and technician profile was unable to change these fields, but was able to with an admin profile. Regardless, a user should be able to change their own fields.
=> Fix users not able to update own protected fields

src/Inventory/Asset/InventoryNetworkPort.php, src/NetworkPort.php, tests/functional/Glpi/Inventory/Assets/NetworkPort.php
When ```NetworkPort```  ```ifalias``` field is updated from equipment (with SNMP)
GLPI's native inventory does not update the field from the inventory file
I took advantage of this PR to add the field to the ```NetworkPort``` form display.
| Fixed tickets | https://github.com/glpi-project/glpi-agent/discussions/558#discussioncomment-7912719
=> fix(NetworkPort): update 'ifalias' if needed

package.json
Latest tabler version requires, at least, node 18.x. I propose to upgrade minimal requirement to 20.x (the latest LTS). It will affect only developpers or people that want to build GLPI dependencies.
=> Upgrade node/npm requirement to latest LTS

install/migrations/update_10.0.11_to_10.0.12/user.php, install/mysql/glpi-empty.sql, src/User.php, tests/LDAP/AuthLdap.php, tests/functional/User.php
| Fixed tickets | !30554
**Description:**
This PR introduces a new field `user_dn_hash` in the `glpi_users` table. This field is a virtual field that is generated by hashing the `user_dn` field. This change is aimed at improving the performance of queries that involve the `user_dn` field by using the hashed value instead.
**Changes:**
1. Added `ext-hash` to the required PHP extensions in `composer.json` and `composer.lock` to avoid soft dependency issues.
2. Created a new migration file `user.php` in `install/migrations/update_10.0.10_to_10.0.11/` to add the `user_dn_hash` field and its index to the `glpi_users` table.
3. Updated …
=> feat: Add user_dn_hash field to improve User::getFromDBbyDn performance

src/Inventory/Conf.php
Add missing icon for agent stale action
reuses icon from 'default status' option
=> Fix(ui): add missing icon for agent stale action

src/Html.php
| Fixed tickets | !30976
For the progress bar in a Rack's statistics box, the basic text color was white, except that if the bar is empty and the person is on a white background, the text is not visible. So I set a light color for the background of the empty bar and a dark color for the text.
Darker
PremiumRed
Teclib
=> Set the color of a rack's weight and consumption

src/Ticket.php, tests/functional/Ticket.php
This PR introduces a new 'Age' search option for tickets. This option is not usable for searching but only displayable in the results. The 'Age' is calculated as the time difference between the ticket's date and the current time. If a calendar is associated with the ticket, it calculates the active time between the ticket's date and the current time.
- Added 'Age' search option to tickets.
- Updated `getSpecificValueToDisplay` method to handle the new 'Age' field.
- Added `ageSearchOptionDataProvider` method to provide data for testing the 'Age' option.
- Added `testAgeSearchOption` method to test the 'Age' option.
=> feat(search-option): add ticket age search option

css/includes/components/_search_input.scss, js/common.js, js/modules/Search/Table.js, src/Search/Input/QueryBuilder.php, templates/components/itilobject/mainform_open.html.twig, templates/components/search/controls.html.twig
Issue come from multiple pr (last was #14875)
but invalid states from inputs (required, check pattern, etc) were ugly or absent.
I leverage bootstrap [validation component](https://getbootstrap.com/docs/5.1/forms/validation/) to get proper style.
In most case, I didn't find a case where the `:valid` css rule was pertinent to keep. And so I tried to remove it properly (we lost focus style after validation).
One last point, on firefox, escaped char in regex pattern, when it should not be escaped, triggers an error (and failed completely the check), example : `\-` -> `-`.
=> better style for invalid states

js/dashboard.js
Avoid `async: false` in the dashboard's script.
=> Dashboards: prevent synchronous XMLHttpRequest on the main thread

src/KnowbaseItem.php
| Fixed tickets | #16243
When getting the data for the KB recent and popular lists, all columns in the `glpi_knowbaseitems` table was being retrieved, including the full article content, even though only the id, name and is_faq was being used. Restricting the columns being returned from the DB should noticeably improve performance if the articles had long content.
=> Improve KB recent/popular list by not getting unused article content

src/User.php
I've found some invalid language values in a production database:
The empty strings are unexpected (empty value should be NULL) and not handled correctly by GLPI.
Since I do not know where these invalide values came from, I can only make sure GLPI handle them better by falling back to the default language from the general config.
This is done by adding a safety check to the `computePreferences` methods.
Ironically, this method doesn't seem to be called on the personal preferences page so it needed its own individual safety check to display the proper fallback value.
| Fixed tickets | !31053
=> Fallback to default language if user preferences are invalid

js/modules/SearchTokenizer/SearchInput.js, js/src/vue/Debug/Widget/HTTPRequests.vue, js/src/vue/Kanban/Column.vue
The new version of Tabler changed the default styles of badges and the default text color is `--tblr-secondary`. For badges with `bg-secondary` this makes the text invisible.
=> Fix some badge text color

src/ITILTemplate.php
The field dropdowns within ticket templates say that the associate items field is only available in the standard interface. This is not correct. The code that lists the fields available in the simplified interface looks like it wasn't updated since the change to how associated items were stored in the DB and still refers to the "items_id" field in the ticket table. Since 0.90, more than one item could be associated with a ticket and this field was moved to a new table to allow linking multiple items to the same ticket.
=> Fix associated items label in template dropdown

src/ComputerAntivirus.php
| Fixed tickets | #16246
Change antivirus search options to use HAVING statements to try matching the expected behavior.
=> Improve behavior of antivirus search options

templates/components/itilobject/actors/field.html.twig
| Fixed tickets | !30913
On the native ticket creation form, in the simplified interface, the watcher was not taken into account.
So even if you filled it in, the created ticket didn't have it.
In the browser console, there was this error:
=> fix(ticket): watcher ignored on self-service form

src/MailCollector.php, tests/emails-tests/42-missing-content-type.eml, tests/imap/MailCollector.php
In some cases, an email may be sent to the GLPI mail receiver with no Content-Type header. Currently, we skip message parts that have no Content-Type, so an email with this header missing completely will result in a ticket being created with no content. I found no RFC that says this is a required header. Instead, I found multiple RFC including RFC 2045 that say the default Content-Type of `text/plain` is assumed when the header is missing.
=> Fix mail import with missing Content Type header

src/Item_Rack.php, src/PDU_Rack.php
Issue:
Showing the form for Item_Rack (items in a rack) performs 2 full scans of the `glpi_items_racks` table, a full scan of the `glpi_items_enclosures` table and a full scan of the `glpi_pdus_racks` table. In every case, it also requests every column from those tables.
Solution:
The 2 scans of the `glpi_items_racks` table have been combined. All full table requests have also been limited to only return the data we use.
=> Improve SQL performance in item_rack form

install/migrations/update_10.0.x_to_10.1.0/text_cols.php, install/migrations/update_10.0.x_to_10.1.0/webhook.php, install/mysql/glpi-empty.sql
| Fixed tickets | #12698
Some text columns in the database are likely to benefit from having the a larger text datatype. Specifically, the content columns for notification templates (queued notification table already had them set to longtext), webhook payload, and the kanban view state data.
=> Increase some text column lengths

CHANGELOG.md, install/migrations/update_10.0.11_to_10.0.12/log_rights.php, src/Central.php, src/Event.php, src/Profile.php
| Bug fix?      | -
| Fixed tickets | #16285
~Need to check/update tests and check plugins.~
This change should probably be highlighted in the release notes in case administrators don't check profiles after the update tells them permissions have changed.
With this PR, `logs` will refer to Historical data (`glpi_logs`) only while `system_logs` will refer to the system events/logs (`glpi_events`).
=> Split historical and log rights

src/SoftwareLicense.php
Fix the following fatal error when executing the `software` automatic action:
```
[2024-01-04 05:32:56] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "is_recursive" in /mnt/diskhome/home/teclib/htdocs/src/CommonDBTM.php at line 3202
Backtrace :
src/NotificationTarget.php:1757                    CommonDBTM->isRecursive()
src/NotificationTarget.php:591                     NotificationTarget->isTargetItemRecursive()
src/NotificationTarget.php:730                     NotificationTarget->addToRecipientsList()
src/NotificationTarget.php:1251                    NotificationTarget->addAdmin()
src/NotificationEventAbstract.php:98               NotificationTarget->addForTarget()
src/NotificationEvent.php:188                      NotificationEventAbstract::raise() …
```
=> Implement isRecursive for SoftwareLicense

js/modules/Monaco/MonacoEditor.js, js/src/vue/Debug/Toolbar.vue, js/src/vue/Debug/Widget/Globals.vue, js/src/vue/Debug/Widget/HTTPRequests.vue, js/src/vue/Debug/Widget/SQLRequests.vue, lib/bundles/codemirror.js, package-lock.json, package.json, src/Html.php
In the debug bar, Codemirror was used for syntax highlighting of SQL queries and to show globals data as JSON with highlighting and folding. Unfortunately Codemirror 6 made it complicated to simply apply syntax highlighting to some text without using a full editor, and it also struggles with simple code folding (You have to view the entire section for it to be loaded and able to be folded).
Monaco has neither weakness and doesn't require 4 extra dependencies just to accomplish standalone syntax highlighting.
=> Replace Codemirror with Monaco in debug bar

src/Budget.php
Before:
After: 
| Fixed tickets | !31063
=> Budget: Add "is" and "is not" search type for "Value" SO

ajax/webhook.php, src/Webhook.php, templates/pages/setup/webhook/webhook.html.twig
When the showing a new webhook form, an error was thrown when it tried to get the Monaco suggestions because the itemtype was not yet set. This PR adds a null check for this and also reloads the suggestions when the itemtype dropdown is changed.
=> Fix monaco suggestions in new webhook form

CHANGELOG.md, inc/autoload.function.php, install/empty_data.php, install/migrations/update_10.0.x_to_10.1.0/configs.php, src/Api/API.php, src/Api/HL/Router.php, src/Config.php, src/Migration.php, tests/units/Migration.php
Since the documentation and endpoint links were added for the new API, the legacy API URL was made read-only. This PR fully drops the ability to change the legacy API URL. As noted in #14509, users can accomplish this within their web server configuration instead. Now, the legacy API URL will always be `/api.php/v1`. The old endpoint `/apirest.php` still works. The `api.php` script will simply hand all of the data off to the `apirest.php` script when version 1 is specified.
=> Remove configurable API url

src/Search/SearchOption.php
Following discussion in #16328.
It seems the `decimal` SO type was involuntarily omitted from the `getActionsFor` method.
Loose search (ignore decimal)
Precise searches:
=> Support standard SO operators for "decimal" SO

.github/dependabot.yml
Alternative to #16156 .
In #16156, the proposal will result in a unique PR containing an update of all dependencies. I think it is not a good idea as sometimes we may want to exclude some libs update. For instance, we currently blocked the `fullcalendar` libs update and in the past we ignored some `gridstack` versions as it required many manual changes.
I propose to only use the following grouping (all other libraries will be updated into separate PRs):
- one group for all npm dev dependencies (most of the time, we accept all of them as soon as the CI checks are OK)
- one group for all composer dev dependencies (most of the …
=> Group some dependabot updates

package.json
Node 16.x is not maintained anymore (see https://nodejs.org/en/about/previous-releases) and some package maintainers already removed support of it. We cannot upgrade some of our build dependencies, see https://github.com/glpi-project/glpi/actions/runs/7473091177/job/20336579990?pr=16338 .
We use it only to build our dependencies, so changing this requirement will only impact developers. The 18.12 LTS version was released on Oct 25, 2022. I guess most of GLPI developers have already this version, or an higher one, installed on their machine.
=> Upgrade node/npm requirement to 18.12 LTS

index.php, templates/pages/login.html.twig
| Fixed tickets | #16010
In some cases, AJAX requests may be made automatically which perform a login check. If the session expired, the user would be automatically redirected to the login page which has CSRF protection. If the user was away from GLPI, but still had it open, and this happens, the CSRF token on the login page may have already expired. When they tried logging back in, they would get yet another error message that their session wasn't valid.
With these changes, when a `redirectToLogin` is performed, the error(s) are shown on a different screen with a button to "Log in again" than the login form. The idea is that GLPI can sit on …
=> Reduce chance of CSRF token expiration on login page when session auto-expires

front/login.php, src/Console/Application.php, src/Session.php, src/System/Requirement/DirectoryWriteAccess.php, src/System/Status/StatusChecker.php, src/Update.php
If PHP is configured to use "redis" for example as the session save handler instead of the default of "files", the `is_writable` checks on GLPI_SESSION_DIR shouldn't be required and can be skipped. This PR also makes sure that the Status Checker returns a message along with an OK status for the session directory check to explain that the "files" handler is not being used.
=> Skip checking GLPI_SESSION_DIR if not using "files" save handler

src/Infocom.php
| Fixed tickets | #11773
Replaces multiple calls to `Ajax::createIframeModalWindow` with the insertion of a single generic modal element and dynamically changing the iframe source depending on which infocom display link button is clicked. This performance improvement is most noticeable when the list limit is set higher than 25. Previously, it was hurting client-side performance as it tried to append and initialize tens of modals.
=> Significant performance improvement for lists with infocom links

.github/actions/lint_php-lint.sh
Recently, on `main` branch, PHPStan checks on PHP 8.1 are sometimes crashing because the memory limit is reached.
```
+ vendor/bin/phpstan analyze --ansi --memory-limit=2G --no-interaction --no-progress
Run code static analysis
Note: Using configuration file /var/glpi/phpstan.neon.
-- -------------------------------------------------------------------------- 
Error                                                                     
-- -------------------------------------------------------------------------- 
Child process error: PHPStan process crashed because it                   
reached configured PHP memory limit: 2G …
```
=> Increase a bit the memory limit allowed to PHPStan

src/Auth.php
when GLPI is not installed at the webserver's root phpcas receives an incorrect value for `service_base_url`, leading to a bad redirection after authentication. `path` and following data must be removed from `url_base` configuration value
=> Fix CAS authentication service_base_url

front/helpdesk.public.php, src/Central.php, src/User.php, tests/functional/User.php
When impersonating a user who has never had their password changed, and when the password expiration policy is set, the warning on the user's homepage says the password will expire in 1970. It also shows a debug error because 'password_last_update' is null and passing null to strtotime is deprecated. This PR prevents passing null to strtotime and also changes the message to "Your password has expired." when the expiration date has passed.
=> Enhance password expiration message

src/SavedSearch.php, templates/layout/parts/saved_searches_list.html.twig
Try to avoid a situation where a single bad saved search could prevent the list of searches from being shown.
~~Also adds the ability to remove saved searches directly from the list.~~
=> Improved handling of broken saved searches

CHANGELOG.md, src/Auth.php, src/RuleRight.php, tests/units/RuleRight.php
Add a new "Deny login" action to the authorization rules. This can allow the import/existence of users within GLPI and the assignment of entities, while at the same time denying their ability to log into GLPI. In some cases, you may want certain types of users to be active within GLPI so they can be assigned to assets or delegated as a requester on a ticket, but not let them login themselves. If you manually created the account, you could randomize the password. However, for external authentication sources like LDAP, that wasn't an option.
=> Add deny login action to authorization rules

js/src/vue/Debug/Toolbar.vue
The Monaco `colorize` method doesn't handle newlines well enough for the jQuery `parseHtml` method. It replaces the newlines with an ending `<span>` tag which doesn't match anything. Then, the jQuery method returns only the HTML before that point. This was most noticeable for search engine queries which contain newlines within the SELECT clause.
=> fix SQL display in debug bar

src/DBmysqlIterator.php, src/Dropdown.php, src/Ticket_Ticket.php, templates/components/itilobject/fields_panel.html.twig, templates/components/itilobject/linked_tickets.html.twig, tests/functional/Ticket.php, tests/functional/Ticket_Ticket.php, tests/units/DBmysqlIterator.php
| Fixed tickets | #14110
Ticket dropdowns now apply the same SQL conditions as the search engine to restrict results to the user's current permissions (unless they have permission to see all tickets). The linked ticket list also now only shows the tickets the user has access to view.
Finally, the linked ticket list template was adjusted to avoid having to call `Ticket_Ticket::getLinkedTicketsTo` once for the counter and then again for the actual list.
Also added the ability to use a QueryExpression as the value for a join's `ON`/`FKEY`. This was needed to conditionally join the ticket table on tickets_id_1 or tickets_id_2 (whichever field …
=> Apply profile restrictions to linked tickets display

src/IPAddress.php
Replace use of HTMLTable* classes to display the list of IP Addresses on the IP Addresses tab of IP Networks with a Twig datatable.
Before:
After:
The "Automatic Inventory" column *was* possible to show using the HTMLTable methods but it was hidden behind an option which was never set anywhere. The old HTMLTable methods were left in place as they were used in at least one other location for another table. That other table wasn't migrated yet as it relies on special grouping/rowspan behavior which is not possible in the datatable template yet.
=> IP Address list to twig datatable

src/DbUtils.php, tests/functional/DbUtils.php
| Fixed tickets | #15752
Issue:
When entities are restructured, the ancestor values in the GLPI_CACHE are only regenerated for the specific entity IDs, but there can remain old cached data for multiple IDs. When `getAncestorsOf` is called with an array as `$items_id`, the cache key was calculated as `ancestors_cache_$table . '_' . md5(implode('|', $items_id))`. These keys wouldn't be regenerated at all unless they were missing completely from the cache.
So, if EntityA and EntityB are created and something calls `getAncestorsOf` with the ID of both entities in an array, a combined cache entry is created. If you change the parent entity of …
=> Do not cache ancestors for multiple IDs together

src/AuthLDAP.php, src/User.php
| Fixed tickets | !31097
When the connection to LDAP is lost during synchronization, synchronization continues, treating the users as deleted.
=> fix(LDAP sync): connection lost

src/AuthLDAP.php
| Fixed tickets | !30554
During LDAP mass synchronization, the `LDAP\Connection` object is cached to be able to reuse the same connection for every synchronized user reading operation. The longer the synchronization, the higher the probability of losing the connection between each operation.
Before reusing the connection, executing an unfiltered read operation can be made to ensure that it does not fail with an error.
On my local machine, a synchronization of 900 users takes almost the same time with and without this patch.
=> Check LDAP connection state during user synchronization

src/CommonITILObject.php, src/Dropdown.php
| Fixed tickets | !31117
When the user only has read-only access to changes or problems, the fields were not read-only, so he could modify the values, and click on the save or delete buttons. 
_Pressing these buttons displayed a message saying that the user was not authorized to do so._
=> fix(change + problem): adding readonly on fields when ITIL object is not editable

CHANGELOG.md, src/Appliance_Item.php, src/Appliance_Item_Relation.php, src/DCRoom.php, src/Item_Cluster.php, src/Item_DeviceCamera_ImageFormat.php, src/Item_DeviceCamera_ImageResolution.php, src/Item_Disk.php, src/Item_Enclosure.php, src/Item_Rack.php, src/PDU_Rack.php, src/Pdu_Plug.php
Replacing a few more sublists with Twig datatables.
Changes besides UI:
- Add missing "Side" column for rack item list
- Change "Free percentage" progress bar to "Used percentage". Having a progress bar that indicates how free a disk is is the opposite of the typical visuals shown on a computer relating to disk space.
- Separate code for displaying the rack item list and graph views to improve readability
A  pass will be done later to work on any form that may be present above the sublists.
=> More sublists to twig datatables

src/Auth.php
| Fixed tickets | #15262
When logging in through the API with a user_token instead of a username/password, the authentication code was trying to connect to every active LDAP server even if the user was not from an LDAP. When the user is from an LDAP and has an `auths_id` set, then only that one server is checked. When `auths_id` is 0 or missing, it checks every server. This code should first check the `authtype` before anything else related to LDAP.
=> Skip unneeded LDAP auth checks

src/Item_DeviceSimcard.php
| Fixed tickets | !31204
It was the same type name for DeviceSimcard and Item_DevideSimcard. This made it difficult to distinguish them, for example, in the Fields plugin.
=> feat(simcard): distinguish between components and component elements

.github/actions/init_initialize-ldap-fixtures.sh, .github/actions/test_tests-functional.sh, .github/actions/test_tests-units.sh, tests/run_tests.sh
GLPI tests (specifically PHP code tests) can take a very long time to run. My previous answer for that was to manually edit the `test_tests-functional.sh` file locally to restrict tests to a specific directory or file. While that worked, it could be quicker if the docker containers didn't have to get recreated every time `tests/run_tests.sh` is run.
This PR adds a new "interactive" mode to the `run_tests.sh` script which can be activated with the `--interactive` flag. In interactive mode, all containers are started immediately and then it asks the user to enter one of several commands:
- test: Run the currently selected …
=> Interactive local test env

src/KnowbaseItem.php
```
[2024-01-18 09:12:04] glpisqllog.ERROR: DBmysql::doQuery() in .../src/DBmysql.php line 403
SQL: SELECT DISTINCT `glpi_knowbaseitems`.`id`, `glpi_knowbaseitems`.`name`, `glpi_knowbaseitems`.`is_faq`, `glpi_knowbaseitemtranslations`.`name` AS `transname`, `glpi_knowbaseitemtranslations`.`answer` AS `transanswer` FROM `glpi_knowbaseitems` LEFT JOIN `glpi_knowbaseitems_users` ON (`glpi_knowbaseitems_users`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN `glpi_groups_knowbaseitems` ON (`glpi_groups_knowbaseitems`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN …
```
=> fix(knowbase): prevent sql error

src/Html.php
The required library, CodeMirror, wasn't being loaded on the global search page because it is one without a sector set. This PR forces the on-demand JS to be evaluated when in debug mode even when the sector, item, and option params are all unset to ensure the requirements for the debug bar can be loaded.
=> Fix debug bar on global search page

src/CommonITILObject.php, src/User.php, templates/components/itilobject/actors/main.html.twig, tests/functional/Ticket.php
| Fixed tickets | !30499
In the current version 10.0.10 of the application, when the requester of a ticket is an (anonymous) email address, it is currently impossible to disable email tracking for this address. This issue results in automatic reactivation of email tracking after the ticket has been saved, making the deactivation feature ineffective.
This limitation can be particularly troublesome in cases where users wish to specifically disable e-mail tracking for requestor e-mail addresses. Currently, this action does not have the desired effect and the tracking bell remains active, resulting in an unnecessary overload of notifications for …
=> Anonymous ticket actor notifications cannot be enabled/disabled

src/Computer.php, src/DCRoom.php, src/Enclosure.php, src/Monitor.php, src/NetworkEquipment.php, src/PDU.php, src/PassiveDCEquipment.php, src/Peripheral.php, tests/functional/Search.php
same as https://github.com/glpi-project/glpi/pull/16390
but more generic:
1. use of ```rawSearchOptionsToAdd```.
2. call from ```Computer```, ```Monitor```, ```NetworkEquipment```, ```Peripheral```, ```Enclosure```, ```PDU```, ```PassiveDCEquipment```.
=> fix(DCRoom): add missing search option

install/migrations/update_10.0.x_to_10.1.0/databaseinstance.php, install/mysql/glpi-empty.sql, src/DatabaseInstance.php
As discussed in #16364, the `size` field for DatabaseInstance seems unused and just a copy-paste from Database.
=> drop size field for database instances

src/CommonDBRelation.php, src/Profile_User.php, src/User.php, templates/components/datatable.html.twig, templates/pages/admin/add_profile_authorization.html.twig
Migrates the forms to assign a profile to a user or a user to a profile to twig.
Migrates the list of profile assignments for a user to the twig datatable template.
Didn't migrate the view of users associated with a profile. I think this is the only case where we have a folder view for sub-items. Do we want to keep it, change it to a datatable, or change it in some other way?
=> Profile assignment twig migration

templates/components/form/fields_macros.html.twig
| Fixed tickets | !31313
Context: GLPI in English - browser in French
In the dashboards, when changing the color of a tile, the cancel/validate buttons remain in French, even though GLPI is in English.
=> fix: translation in color palettes

src/PrinterLog.php
| Fixed tickets | #16321 
the array_sum instead of $value > 0 allows you to keep the right number of points per line
before:
after:
=> Fix printer counters history chart

css/includes/components/_buttons-group.scss, css/includes/components/_select2.scss, src/CalendarSegment.php, src/Calendar_Holiday.php, src/DatabaseInstance.php, templates/components/datatable.html.twig, templates/components/form/basic_inputs_macros.html.twig, templates/pages/management/databaseinstance.html.twig, templates/pages/setup/calendar_holiday.html.twig, templates/pages/setup/calendarsegment.html.twig
=> Calendar dropdown and Database Instance Twig UI

CHANGELOG.md, front/socket.form.php, src/Dropdown.php, src/Socket.php, templates/pages/assets/socket.html.twig, templates/pages/assets/socket_networkport.html.twig, templates/pages/assets/socket_short_form.html.twig
Moved Socket-related UI to Twig templates.
Redesigned the form shown on the Sockets tab of Locations. Instead of two forms being shown at the same time, one for adding a single socket and another for adding multiple, there is now only a single form which can switch modes using a slider. For multi-add mode, I also added placeholder text for the two name textboxes to make it clearer to the user how the names are built.
=> Socket Twig UI

src/Search/Input/QueryBuilder.php, templates/components/search/query_builder/metacriteria.html.twig
Namespaced itemtypes were not handled properly within the meta criteria template. Meta criteria controls would break on any namespaced itemtype.
=> Fix namespace handling for metacriteria controls

src/DbUtils.php, tests/fixtures/pluginfoo_item_filter.php, tests/functional/DbUtils.php
Same as  https://github.com/glpi-project/glpi/pull/14566
But handle single level namespace + CommonDBRelation from Plugin context
Ex : 
```php
GlpiPlugin\\Foo\\Relation_Item
```
=> Fix getItemTypeForTable when using relation table

tools/genapidoc.sh
It looks like the owner of ApiGen let the domain expire some time before September 18th last year based on snapshots on the Wayback Machine and at some point someone else bought the domain and it now hosts a sketchy "gambling?" page. We probably shouldn't keep a link to this domain anymore. The project itself doesn't seem completely dead and the GitHub repo doesn't seem compromised, so if we need to keep a link, we could use that. Otherwise, maybe we should remove the link completely, or remove/change the script to use something else.
=> Replace APIGen link in tool script

js/src/vue/Debug/Widget/HTTPRequests.vue
It was impossible to scroll the request list or sub-widgets like the profiler separately. Scrolling in either panel would scroll the entire content area due to a missing height property on one of the divs between the scrollable containers and the element with the non-percentage height.
=> Fix scrolling in requests debug widget

CHANGELOG.md, js/modules/Form/WebIconSelector.js, src/Asset/AssetDefinition.php, src/Dropdown.php, src/ManualLink.php, templates/components/form/fields_macros.html.twig, templates/pages/admin/assetdefinition/main.html.twig, tests/js/bootstrap.mjs, tests/js/modules/Form/WebIconSelector.test.js
- Add WebIconSelector JS module/class based on `FaIconSelector.js` which can handle both Tabler and FontAwesome icons but defaults to only Tabler icons. FaIconSelector is now deprecated but remains as it was so non-module code can still import it and use the global set on `window`.
- Finished `icon` search option to show the web icon selector in the search criteria.
- Added reminder to replace the FaIconSelector usage by ManualLink when the form is moved to twig.
=> Add icon selector and search for asset definition

ajax/common_ajax_controller.php, css/includes/components/_asset-form.scss, css/includes/components/_content-editable-inputs.scss, js/common.js, js/common_ajax_controller.js, src/CommonDBTM.php, src/CommonGLPI.php, src/Controller/CommonAjaxController.php, src/Controller/CommonAjaxControllerAllowedClassesList.php, src/Controller/CommonAjaxControllerWhitelist.php, src/Controller/RequestException.php, src/Html.php, src/Session.php, templates/components/form/header_content.html.twig, templates/pages/admin/form/form_editor.html.twig, tests/functional/Computer.php
Allow update on Forms through AJAX.
This is an important feature because Forms will be complex items to configure and thus we want to avoid any page reload while dealing with them (which would make the user lose its curent "context" on the page).
Rather than implement the feature specifically for Forms, a generic `CommonAJAXController` controller has been created that will be able to handle AJAX updates on any `CommonDBTM` items.
This "ajax update" feature will only be enabled for Forms at this moment but could be easily enabled on others items later if we want to.
=> Forms: AJAX controller

front/form/form.form.php, install/migrations/update_10.0.x_to_10.1.0/form.php, install/mysql/glpi-empty.sql, js/common_ajax_controller.js, js/form_editor_controller.js, src/Search/Provider/SQLProvider.php, templates/pages/admin/form/form_editor.html.twig
The creation step is a bit redundant for complex objets like forms as we can't handle child items (sections and questions) that make up the most part of our form.
To avoid that, we use the `is_draft` flag:
* When going to the form creation page, a form is created with `is_draft = true` and the user is redirected to the form update page.
* The page still appears like the classic creation form with the "Add" action at the end of the toolbar.
* On the first update, we set `is_draft = false` and replace the "Add" button by the "Update" button.
* Items with `is_draft = true` are not shown in the form list and will be deleted after 7 days.
This may seems like a trivial change but it really streamline the UX of the form creation process and allow to fully use the AJAX controller even for a new …
=> Forms: draft status

js/planning.js
The planning page will fail if the default view is unknown to fullcalendar.
For example, the https://github.com/pluginsGLPI/advancedplanning plugin add a new "Timeline week" view, which users may select.
If the plugin is disabled later on, users that were using this view are stuck with an error on the callendar page (which become unusable).
To fix this, I've added a fallback to the default view.
This is done using a "fake" calendar initialisation in a try/catch block (an invalid view will trigger the catch block, which will revert to the default view before we initialize the real calendar).
It would be cleaner if we could check if a view exist by using an official FullCalendar method but i didn't find anything useful for this purpose in their documentation.
| …
=> Prevent FullCalendar failure when default view is invalid

composer.json, composer.lock, tests/GLPITestCase.php
Our tests extends `atoum\atoum` which doesn't seem to exist.
I suppose there is some black magic somewhere (as our tests obviously works) but it isn't known to VSCode which does not recognize any atoum method.
Using the correct `atoum` import fix the issue on VSCode and does not impact our tests.
This is the import used in the official documentation (https://atoum.readthedocs.io/en/latest/first_test.html#first-tests).
| New feature?  | on
=> Use `atoum/stubs`

CHANGELOG.md, src/Budget.php, src/CommonITILCost.php, src/ProjectTask.php, templates/components/datatable.html.twig, templates/components/form/basic_inputs_macros.html.twig, templates/pages/management/budget.html.twig, templates/pages/management/cost.html.twig
- Migrate budget/cost UI to twig
- Refactor SQL queries for items/entities related to a budget
- Budget "Main" tab now shows negative values for "Total remaining in the budget" in parentheses instead of with a negative sign to align with typical accounting practices.
- Added flag to allow hiding the pager in datatables
- Fixed handling of a clearable `date` field.
- Added ability to specify a super-header and footers for datatables
- Some minor code cleanup/PHPDoc fixes
=> Review budget and cost UI

install/migrations/update_10.0.x_to_10.1.0/profiles.php, install/mysql/glpi-empty.sql, src/Migration.php, src/Profile.php, src/ProfileRight.php, src/Session.php, tests/functional/ProfileRight.php, tests/functional/Search.php, tests/functional/Session.php, tests/units/Migration.php
**Description:**
This PR introduces a dynamic rights management system, primarily through the addition of a new field `last_rights_update` in the `glpi_profiles` table. This field is used to track the last update of the rights associated with a profile. Whenever a right is added, updated, or deleted, this field is updated with the current timestamp. This allows us to easily identify when a profile's rights were last modified and reload them "on the fly" when necessary.
**Changes:**
1. Added `last_rights_update` field to `glpi_profiles` table in `profiles.php` migration file and `glpi-empty.sql` file.
2. Updated …
=> Automatically reload updated rights

src/WifiNetwork.php
Add "be" WiFi card version to hard-coded list to support new/upcoming WiFi 7 devices.
=> Add WiFi 7 version

src/Datacenter.php, src/Rack.php, tests/functional/Search.php
- Add Datacenter search option to Racks
- Add Datacenter search option for items in `Datacenter::rawSearchOptionsToAdd()`, excluding racks and server rooms (they have separate search options for datacenters).
- Add test case
So now you can search rackable items, racks, and server rooms by which DataCenter they are assigned to.
| Fixed tickets | #16415
=> fix(DataCenter): add missing search option

src/Search.php, tests/functional/Search.php
| Fixed tickets | !31353
For ticket searches, when sorting users by requester, the result did not take anonymous users into account.
_The same applies to other types of actor and to changes and problems._
=> fix(search): order by actor

js/src/vue/Debug/Widget/Globals.vue, js/src/vue/Debug/Widget/Profiler.vue, js/src/vue/Debug/Widget/ProfilerTable.vue
Changing the selected HTTP request in the debug toolbar wasn't triggering an update of the globals and profiler sub-widgets.
=> Fix missing reactive behaviors in debug toolbar

src/CommonITILObject.php, src/LevelAgreement.php, src/Ticket.php
| Fixed tickets | https://github.com/glpi-project/glpi/issues/16466 #16498
```
glpiphplog.CRITICAL: *** Uncaught Exception TypeError: Unsupported operand types: int + string in .../src/LevelAgreement.php at line 855
Backtrace :
src/Ticket.php:449 LevelAgreement->computeDate()
src/Ticket.php:1428 Ticket->getDatasToAddSLA()
src/Ticket.php:2027 Ticket->slaAffect()
src/CommonDBTM.php:1297 Ticket->prepareInputForAdd()
front/ticket.form.php:80 CommonDBTM->add()
```
=> fix: prevent unsupported operand types int + string

src/Item_Ticket.php, src/Ticket.php
| Fixed tickets | !31506
This PR addresses an issue where linked items section were not visible in the right-hand panel of a ticket when it was closed.
The non-display of the section was introduced by PR #16056 to prevent items from being added or deleted once the ticket has been closed.
Here the behavior has been modified so that when the ticket is closed, only the list of linked objects is displayed, as shown in the screenshot below.
=> fix: make the items section visible in the right-hand panel of the ticket when it is closed

src/Profile.php
Not sure if the label should say "tickets, changes and problems" or "ITIL items".
IMO, ITIL items is too vague and users might not know what it means, especially since we have an `ITIL objects` category on the same page which does not target the same items at all:
If we want to use "ITIL items" for the right then this section should probably be renamed to avoid confusion.
=> Fix label for the "associable item to..." right

CHANGELOG.md, js/fileupload.js, js/modules/ITIL/Timeline/DocumentForm.js, js/modules/Screenshot/Screenshot.js, src/Application/View/Extension/DocumentExtension.php, templates/components/itilobject/timeline/form_document_item.html.twig, tests/js/modules/Screenshot/Screenshot.test.js
Integration of `screenshot` plugin. Unlike the plugin where the screenshot and recording buttons were separate timeline actions, these buttons now exist within the document item timeline form. That also means users can attach any number of screenshots, recordings, or uploaded files and they all get processed at once. Screenshots and recordings both have previews shown within the form and they can be removed by clicking the "x" on the preview or within the file upload control.
This feature only works within "secure contexts". Typically that means you connect over HTTPS or are connecting to `localhost`. If your browser …
=> Add screen capture feature

css/includes/_base.scss, lib/bundles/base.js, package-lock.json, package.json, templates/layout/parts/profile_selector.html.twig
While working on the Cypress POC, the CI actions started failing with NPM complaining about tarball data being corrupted for this dependency and bad cache permissions. This library hasn't been updated in 2 years, but more worryingly, the maintainer hasn't been active on GitHub in the same amount of time. For the one specific feature we use it for (entity selector list), we should be able to use a simple custom solution as a replacement.
This alternative creates a small scrollable area along the right side of the list to make it look like the entity list is scrollable even though it uses DOM recycling (only adds the visible …
=> remove plain-scrollbar dependency

src/Asset/Asset.php, src/Asset/AssetDefinitionManager.php, src/Asset/Capacity/AbstractCapacity.php, src/Asset/Capacity/CapacityInterface.php, src/Asset/Capacity/HasAntivirusCapacity.php, src/Asset/Capacity/HasContractsCapacity.php, src/Asset/Capacity/HasDocumentsCapacity.php, src/Asset/Capacity/HasInfocomCapacity.php, src/Asset/Capacity/HasKnowbaseCapacity.php, src/Asset/Capacity/HasNotepadCapacity.php, src/Asset/Capacity/HasOperatingSystemCapacity.php, src/Asset/Capacity/HasRemoteManagementCapacity.php, src/Asset/Capacity/HasVolumesCapacity.php, tests/functional/Glpi/Asset/Capacity/HasAntivirusCapacity.php, tests/functional/Glpi/Asset/Capacity/HasContractsCapacity.php, tests/functional/Glpi/Asset/Capacity/HasDocumentsCapacity.php, tests/functional/Glpi/Asset/Capacity/HasInfocomCapacity.php, tests/functional/Glpi/Asset/Capacity/HasKnowbaseCapacity.php, tests/functional/Glpi/Asset/Capacity/HasNotepadCapacity.php, tests/functional/Glpi/Asset/Capacity/HasOperatingSystemCapacity.php, tests/functional/Glpi/Asset/Capacity/HasRemoteManagementCapacity.php, tests/functional/Glpi/Asset/Capacity/HasVolumesCapacity.php
=> Custom asset cloning

src/NotificationTargetCertificate.php
This PR allows the use of "certificate.type" in the notifications. This field can be used for instance to keep the PKI name.
=> allow use of certificate type in notification

src/Reminder.php, tests/functional/Reminder.php
| Fixed tickets | !31521 #13650
When the target of the note is a profile or group on the recursive root entity. The note was visible from the `Root entity` or a child, but not from the `Root entity (tree structure)`.
OK:
Not OK:
=> fix(reminder): not visible on root entity with tree structure

CHANGELOG.md, ajax/webhook.php, front/commonitiltask.form.php, front/commonitilvalidation.form.php, src/ChangeTask.php, src/CommonITILTask.php, src/CommonITILValidation.php, src/Document_Item.php, src/Features/PlanningEvent.php, src/ITILFollowup.php, src/ITILSolution.php, src/Planning.php, src/ProblemTask.php, src/RichText/UserMention.php, src/Search/SearchEngine.php, src/TicketTask.php, src/Webhook.php
| Fixed tickets | #13904
Original reported issue was that documents attached to solutions were not visible to technicians with the "See my ticket" permission missing even though they instead had "See all" permission. While working on this fix, I found that the `canView` method for Followups, Tasks and Solutions all seemed inconsistent.
Changes in this PR:
- Followups and Tasks `canView` now checks permission to see public or private followups first. If that check fails, access is denied. Simply having the ability to view one of the parent types is no longer enough for the global check.
- Followups, Tasks and Solutions `canView` now checks …
=> Rework canView global checks for ITIL sub-items

src/Change_Item.php, src/CommonItilObject_Item.php, src/Item_Problem.php, src/Ticket.php
As discussed in #16432, extends the visibility condition of the ITIL tabs to all assets (instead of just generic assets).
As a reminder, the tabs are now only shown if:
* The current profile is allowed to link the given asset to ITIL items
* (OR) There are already linked ITIL items for the given asset
=> Hide ITIL tabs if empty

src/Appliance.php, src/Asset/AssetDefinitionManager.php, src/Cable.php, src/Certificate.php, src/Cluster.php, src/Computer.php, src/DCRoom.php, src/Database.php, src/DatabaseInstance.php, src/Domain.php, src/DomainRecord.php, src/Enclosure.php, src/Item_Ticket.php, src/Monitor.php, src/NetworkEquipment.php, src/PDU.php, src/PassiveDCEquipment.php, src/Peripheral.php, src/Phone.php, src/Printer.php, src/Rack.php, src/Software.php, src/SoftwareLicense.php, src/Ticket.php, tests/functional/Glpi/Asset/AssetDefinitionManager.php
Need #16518 to be merged first.
Use the correct `Item_Ticket` tab when needed, to be consistent with usage of the `Item_Problem`  and `Change_Item` tabs.
=> Fix item ticket tabs

src/Asset/AssetDefinition.php, src/Asset/AssetDefinitionManager.php, templates/pages/admin/assetdefinition/main.html.twig, tests/functional/Glpi/Asset/AssetDefinition.php
With this proposal, we will prevent administrator to use the system names that we would probably use when the assets from the corresponding classes will be transfered in the generic asset system.
Some of them will likely not be transfered, like `Unmanaged`, but I guess it is still preferable to prevent this system name to be used, at least to prevent any ambiguity with the GLPI native itemtype.
=> Prevent admin to use some reserved words as asset system name

src/Dashboard/Grid.php, src/Debug/Profiler.php
Use the current PHP request duration as the execution time on the dashboard cards in debug mode.
=> Enhance accuracy of debug mode dashboard card timings

src/Webhook.php, tests/functional/Webhook.php
| Fixed tickets | !31553
Information about parent items (The ticket for example when the webhook is for a followup) was only being retrieved when building the webhook body content, but not when the URL or header values were being processed by Twig.
=> Fix missing parent item data for webhook headers and url

templates/layout/parts/profile_selector.html.twig
Follows #16520. While reviewing #16373, I saw that this variable declaration was missing.
=> Add missing JS var declaration in profile selector

src/Api/HL/Controller/CoreController.php, src/Api/HL/RoutePath.php
Two bugs found when testing Authorization Code authentication within Swagger UI:
- Infinite redirect loop on /authorize endpoint caused by bad handling of cookie authentication. Custom logic was removed and replaced with the newer CookieAuthMiddleware.
- Swagger's redirect URI was resulting in a server error because it does not have any documentation attribute and it was trying to use the documentation to fill in any missing parameters with the default values (if they existed).
=> Fix OAuth authcode flow

install/migrations/update_10.0.x_to_10.1.0/form.php, install/mysql/glpi-empty.sql, js/form_editor_controller.js, src/Form/AnswersHandler/AnswersHandler.php, src/Form/AnswersSet.php, src/Form/Form.php, src/Form/Question.php, src/Form/QuestionType/QuestionTypeCategory.php, src/Form/QuestionType/QuestionTypeInterface.php, src/Form/QuestionType/QuestionTypeLongAnswer.php, src/Form/QuestionType/QuestionTypeShortAnswer.php, src/Form/QuestionType/QuestionTypeShortAnswerEmail.php, src/Form/QuestionType/QuestionTypeShortAnswerNumber.php, src/Form/QuestionType/QuestionTypeShortAnswerText.php, src/Form/QuestionType/QuestionTypesManager.php, templates/pages/admin/form/display_answers.html.twig, templates/pages/admin/form/form_editor.html.twig, templates/pages/admin/form/form_question.html.twig, templates/pages/form_renderer.html.twig
Split questions types into separate categories.
This avoid showing too many options at once for the users.
Initially, I thought that we were going to save the `type` and `subtype` into the database but it is not very useful in the end as only the "sub type" interest us and we can compute the parent category from it.
Thus, I've removed the `subtype` column.
=> Forms: questions categories

src/Config.php
| Fixed tickets | https://forum.glpi-project.org/viewtopic.php?id=289307
Force the menu to regenerate for the current session when the "Devices displayed in menu" option is changed. While this doesn't affect other users and they still have to log out and back in, it gives the person who made the change immediate feedback to know the effect of their change.
=> Refresh menu when devices in menu changed

CHANGELOG.md, inc/define.php, inc/includes.php, src/Api/API.php, src/Console/Application.php, src/DBmysql.php, src/Debug/Profile.php, src/Debug/Profiler.php, src/MassiveAction.php, src/Timer.php, src/Toolbox.php, tests/functional/Search.php, tests/functional/Update.php, tests/router.php
=> Drop old debug globals and configs

src/Ticket.php, tests/DbTestCase.php, tests/functional/Ticket.php
| Fixed tickets | #14707
When generating surveys, the max close date of the ticket is stored during a loop, the code updates the parent entity maxdate but never the code never update the current/child entity.
=> Fix satisfaction survey max close date saving when configuration is not inherited

js/src/vue/Debug/Toolbar.vue, js/src/vue/Debug/Widget/RequestSummary.vue, js/src/vue/Debug/Widget/SQLRequests.vue, src/Debug/Profile.php
1. Fixes the following error:
```
glpiphplog.NOTICE:   *** PHP Deprecated function (8192): Implicit conversion from float 0.762939453125 to int loses precision in /var/www/glpi/src/Debug/Profile.php at line 143
Backtrace :
src/DBmysql.php:438                                Glpi\Debug\Profile->addSQLQueryData()
src/DBmysqlIterator.php:119                        DBmysql->doQuery()
src/DBmysql.php:1091                               DBmysqlIterator->execute()
src/Session.php:999                                DBmysql->request()
src/Session.php:1107                               Session::checkValidSessionId() …
```
=> Fix SQL timings in debug bar

tests/HLAPITestCase.php
The default failure information atoum shows is not always useful or accurate in certain cases.
If you have a test class with an abstract parent which has a test method in it and that test fails, it reports the test failed in the child class on line 0.
If you call a method outside the test class which then in turn performs the assertions, the file/class/line reported is the last line in the backtrace from the test class rather than where the assertion was called.
I don't have confidence in a global fix for this but since the HL API tests have helper classes than act like pseudo-assertions, it makes sense to intercept the …
=> Improve HL API test failure messages

src/User.php, tests/DbTestCase.php, tests/LDAP/AuthLdap.php, tests/RuleBuilder.php, tests/functional/RuleCommonITILObject.php, tests/functional/SLM.php
same as https://github.com/glpi-project/glpi/pull/16548 but for main
The "groups" criteria for authorizations rules is not processed correctly for LDAP users.
Small improvement added to the unit test ```RuleBuilder``` to manages the ```subtype```, rather than the ```CreateRule``` function.
| Fixed tickets | !31311
=> Fix(RuleRight): Take db groups into account for rights rules on LDAusers

inc/define.php
Opening Setup > General > General tab displays a warning and an error in the console saying that tinyMCE is not defined and the login text option is shown as a regular textarea instead of a richtext editor.
=> fix missing tinymce in general setup

src/Api/HL/Controller/ITILController.php, src/Api/HL/OpenAPIGenerator.php, src/Api/HL/RoutePath.php, tests/functional/Glpi/Api/HL/OpenAPIGenerator.php
When path parameters like `{itemtype}` were expanded (for example to Ticket, Change and Problem), the parameters were still incorrectly shown.
=> [HLAPI] Remove expanded path parameters from OpenAPI doc

src/Api/HL/OpenAPIGenerator.php
Some parameters had the 'required' property set to a string ('true' or 'false') in the OpenAPI doc which always evaluates as true because the OpenAPI spec expects this to be a boolean and Swagger evaluates the value as one. This made parameters like `filter'`, `start` and `limit` required in Swagger UI.
=> [HLAPI] Fix some parameters incorrectly shown as required

src/Application/View/Extension/DocumentExtension.php
| Fixed tickets | !31632
The icon of a document in the timeline is not always identical to the icon of the same document in the documents menu. Especially with docx or xlsx.
Documents menu:
Timeline Before:
Timeline After:
=> fix(document): icon in timeline

src/Form/AnswersHandler/AnswersHandler.php, src/Form/QuestionType/QuestionTypesManager.php
These variables should have been protected as the instance is accessed using the dedicated `getInstance()` method.
=> Fix singleton property visibility

ajax/common.tabs.php, src/CommonGLPI.php
When you add a value to a dropdown, it raises a warning:
_In this example, it's a dropdown of the Fields plugin_
```
glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "_target" in .../ajax/common.tabs.php at line 56
Backtrace :
public/index.php:82                                require()
glpiphplog.NOTICE:   *** PHP Deprecated function (8192): str_ends_with(): Passing null to parameter #1 ($haystack) of type string is deprecated in .../ajax/common.tabs.php at line 56
Backtrace :
ajax/common.tabs.php:56                            str_ends_with()
public/index.php:82                                require()
```
=> fix(dropdown): prevent warning on add form

src/RuleMailCollector.php, tests/functional/RuleMailcollector.php
add capability to manage ```ExternalID``` from ```RuleMailColletor```
| Fixed tickets | !31246
=> feat(RuleMailColletor): add capability to manage 'ExternalID'

src/NotificationTargetTicket.php, tests/bootstrap.php, tests/functional/NotificationTargetTicket.php
add missing ```##ticket.externalid##``` TAG
| Fixed tickets | !31246
=> Fix(NotificationTargetTicket): add missing ##ticket.externalid## TAG

CHANGELOG.md, src/Api/HL/Controller/CoreController.php, src/Api/HL/Router.php, src/Console/System/CheckStatusCommand.php, src/System/Status/StatusChecker.php, status.php, tests/functional/Glpi/System/Status/StatusChecker.php
- Forces requests to `status.php` to be directed through the new API
- Drops old pain-text output format
By having all HTTP access to the status checker going through the new API we can have it use any potential new restrictions we may add to the new API like rate limiting, IP restrictions, OAuth scopes, etc.
=> Use HL API to handle status.php calls and drop plain-text output

.webpack.config.js, lib/bundles/base.js, package-lock.json, package.json
`jquery-ui-widget` was loaded twice because it is unexpectedly loaded by the `jquery.fancytree` package. I disabled the `jquery.fancytree/dist/modules/jquery.fancytree.ui-deps.js` file inclusion using the `WebPack` `null-loader`, and added required widgets in our bundle file.
=> Remove duplicated imports of jQuery UI

src/Search/Provider/SQLProvider.php, tests/functional/Glpi/Search/Provider/SQLProvider.php
Only affects `main` as bug was introduced while the search code was being refactored. The handling of `item_item` type search options was the same as `item_item_revert`.
10.0 handling can be found here for reference:
https://github.com/glpi-project/glpi/blob/a040236888d5e0eeb0707058be3bcbfe6953346c/src/Search.php#L6082-L6100
=> Fix item_item search options

src/RichText/RichText.php
Prevent warning message:
```
glpiphplog.NOTICE:   *** PHP Deprecated function (8192): strlen(): Passing null to parameter #1 ($string) of type string is deprecated in .../src/RichText/RichText.php at line 298
Backtrace :
src/RichText/RichText.php:298                      strlen()
src/ProjectTask.php:1158                           Glpi\RichText\RichText::getEnhancedHtml()
src/ProjectTask.php:1234                           ProjectTask::showFor()
src/CommonGLPI.php:694                             ProjectTask::displayTabContentForItem()
ajax/common.tabs.php:120                           CommonGLPI::displayStandardTab() …
```
=> fix(project): warning on null content

src/Search.php, src/Search/SearchEngine.php, src/Search/SearchOption.php, tests/functional/KnowbaseItem.php, tests/functional/Search.php
| Fixed tickets | !31553
The search engine makes some assumptions about search option IDs that is correct in *most* cases, but not all (like Followups). Rather than mess with changing search option IDs, the better solution is to replace all cases where we use hard-coded search option IDs to refer to a specific option.
For example, it assumes that ID 1 is always present and always the name field. In followups, this is the content field. Having the content field shown by default is very resource intensive. Worse, the default sort is always ID 1 which means the search query suddenly becomes much less performant as it has to scan the entire table. …
=> Do not refer to search options by ID literals

src/Api/API.php, tests/APIBaseClass.php
| Fixed tickets | #16259
Many libraries used to produce object oriented API connectors does not like to have a different behaviours for the same endpoint.
With the proposed modification, `_networkports` will always have the same behaviour whether there are existing ports or not.
Without existing ports:
```json
"_networkports": {
"NetworkPortEthernet": [],
"NetworkPortWifi": [],
"NetworkPortAggregate": [],
"NetworkPortAlias": [],
"NetworkPortDialup": [],
"NetworkPortLocal": [],
"NetworkPortFiberchannel": []
}
```
With existing ports:
```json
"_networkports": {
"NetworkPortEthernet": [
{
"netport_id": 15,
...
}
],
"NetworkPortWifi": [], …
```
=> Ensure `_networkports` result in API to be consistent with expected schema

src/CommonITILCost.php
| Fixed tickets | !31520
If a cost has already been charged to a budget for a ticket, the next time the ticket is added, the previously used budget is filled in by default in the addition form, without checking whether this budget has been deleted. _This allowed a deleted budget to continue to be charged. When the dropdown was unfolded, the deleted value was not listed._
=> fix(ticket): deleted budget

.github/actions/teardown_containers-cleanup.sh, .github/workflows/audit_dependencies.yml, .github/workflows/ci.yml, .github/workflows/coverage.yml, tests/run_tests.sh
The self hosted Github Action runner is not used anymore as it is far from being reliable (not enough system resources to be able to run GLPI test suite completely and in an acceptable delay). As we do not use it anymore, we can remove corresponding scripts.
=> Remove self hosted Github Action runner support

src/Group.php, templates/components/itilobject/timeline/form_task.html.twig
| Fixed tickets | #16560
When using the simplified interface, task groups are not visible.
Now the name is visible.
**Basic interface :** 
_Group name and link_
**Simplified interface :** 
_Just group name_
=> Fixed display of group name in simplified interface

install/empty_data.php
| Fixed tickets | see #15930
By default, the planning recall notification is sent only to the requester. People complains that the notification is not sent to the tech/group in charge. I think we could add these target to the default targets.
=> Add tech/group as default planning reminder notification target

src/CommonITILObject.php, src/Ticket.php, tests/functional/Ticket.php
| Fixed tickets | #16381
When the ticket was created with a closed status and a technician, the technician was not inserted into the database.
`line 9800 in CommonITILObject::transformActorsInput`
So I added a simple check to see if the item is a new item, otherwise the behavior remains the same as before.
=> Fixed ticket creation with closed status to exclude technician

js/glpi_dialog.js, src/Asset/AssetDefinition.php, templates/pages/admin/assetdefinition/main.html.twig
Replace use of the default confirmation dialog with one that says how many assets use the definition and would be deleted as a result of deleting the definition. If the definition is active, it shows a link to the asset search page so you can see what would be deleted. If the definition is inactive, they wouldn't have permission to view the search page so it simply says all assets using the definition will be deleted too.
Also changed the `glpi_confirm` function to allow specifying a callback to run when the modal is closed.
=> Improve asset definition deletion

src/Features/Inventoriable.php
Allow the inventory file to be downloaded only if the item is dynamic.
The condition concerning the update source makes no sense
A plugin could inject its json / xml and decide on the update source (```!= Glpi Native Inventory```)
Internal need with (cloud inventory plugin)
=> Fix(Inventory): allow to download inventory file only if is_dynamic

css/includes/components/_flatpickr.scss
=> Fix date picker border radius

src/System/RequirementsManager.php
| Fixed tickets | see #16694
The `symfony/polyfill-mbstring` components only provides a partial implementation of the native `mbstring` extension. It will permit, for instance, to be able to correctly display the GLPI console (see #8331), but it will not be able to convert chars to the `UTF7-IMAP` encoding required by the mail collector. I propose to make this extension mandatory in future GLPI versions.
Related error:
```
glpiphplog.WARNING:   *** PHP Warning (2): iconv(): Wrong encoding, conversion from "UTF-8" to "UTF7-IMAP//IGNORE" is not allowed in /var/www/html/glpi/vendor/symfony/polyfill-mbstring/Mbstring.php at line 116
Backtrace : …
```
=> Make `mbstring` extension mandatory

CHANGELOG.md, src/Document.php, src/Document_Item.php
Not exhaustive:
- Drop unused `Document::uploadDocument()`
- PHPDoc fixes
- Some minor DB query optimizations
- Use self/static for static calls
- Use `::class` instead of `getType` and hard-coded class names
=> Cleanup document code

js/modules/ObjectLock.js, src/ObjectLock.php, templates/layout/parts/objectlock_message.html.twig, tests/js/modules/ObjectLock.test.js
For ObjectLock:
- Migrate UI to Twig and cleanup
- Migrate inline scripts to dedicated ESM module
- PHPDoc cleanup
- Jest tests
Some behavior changes:
- When auto-lock disabled and another user had the item locked, it was simply showing it was "Read-only" with a button to request it to be unlocked. Now, it clearly shows the Locked by someone else message.
- When auto-lock disabled and the item is not locked, it now shows the user is currently in Read-only mode and gives them a button to "Edit" the item.
Screenshots Before -> After (Note that the message still shows under the navigation header. This was fixed after the …
=> ObjectLock feature/UI review

src/Group.php
New recursive feature for groups added overrides for `post_addItem` and `post_updateItem` but calls the the parent methods were missing which meant the caches were not being managed at all. Adding a new child group would not invalidate the relevant caches.
=> Fix group cache invalidation

CHANGELOG.md, src/DropdownTranslation.php
Followup to the previous cleanup PR. After searching every tagged version of GLPI from 0.20 until now, this method is only ever declared and not used. I don't see any plugins using it either (although I don't have all of them downloaded locally).
=> drop DropdownTranslation::getTranslationByName

css/includes/components/form/_form-editor.scss, js/form_editor_controller.js, templates/pages/admin/form/form_editor.html.twig, templates/pages/admin/form/form_question.html.twig, templates/pages/admin/form/form_section.html.twig, templates/pages/admin/form/form_toolbar.html.twig
Add a "floating toolbar" to the form editor.
This toolbar is shown for the active item and allow to insert a new question or section.
Its design and position might change in futures PR as we discuss UX later on.
Others changes:
* Renamed the `data-active-status` attribute to `[data-glpi-form-editor-active-status-indicator]` (to keep things consistant)
* Replaced the `.active` class by a `[data-glpi-form-editor-active]` data attribute (to prevent conflicts as others components may use the same `.active` class, which may impact our selectors)
* Question drag and drop handle is only shown when hovering the question itself (new `[data-glpi-form-editor-question-details]` attribute instead of `[data-glpi-form-editor-question]` which now also contain the toolbar).
* `#handleEditorAction` now …
=> Forms: floating toolbar

js/form_editor_controller.js, templates/pages/admin/form/form_editor.html.twig, templates/pages/admin/form/form_question.html.twig, templates/pages/admin/form/form_section.html.twig
Suggested by @orthagh:
* When opening a form, focus its name if it has no question
* When adding a question or section, focus its name
=> Forms: focus input

tests/functional/Glpi/Form/QuestionType/QuestionTypesManager.php
Force `testGetTypesForCategoryProvider` to use all available categories.
=> Forms: make sure tests fails if new categories content is not tested

js/form_editor_controller.js, src/Form/Form.php, src/Form/Question.php, src/Form/Section.php, templates/pages/admin/form/form_section.html.twig, tests/functional/Glpi/Form/Form.php
Enable history for forms.
Needed some specific code to take questions update into account as they are an indirect relation (Form -> Section -> Question) and our framework only manage related logs for direct relation.
=> Forms: history

css/includes/components/form/_form-editor.scss, js/form_editor_controller.js, templates/pages/admin/form/form_question.html.twig, templates/pages/admin/form/form_section.html.twig
Allow sections to be collapsed.
Collapsed:
Non-collapsed:
=> Forms: collaspe sections

src/Ajax.php
Seems like a recent break (something to E2E test once that is ready I guess) as I only noticed it now, but I don't know which change could have broken it. The previous code only recognized some of the parameters in the URL and seemed to be an encoding issue. The options in the encoded `formoptions` parameter were recognized, which the non-encoded ones were not. This was the only solution I found that worked properly.
=> Fix tab changes not persisting

src/Search.php, tests/functional/Search.php
| Fixed tickets | !31814
When we search for `&` in the contents of a ticket, the result returns all HTML entities, so more than expected.
=> fix(search): contains &

templates/components/itilobject/actors/field.html.twig
Fix a typo in a variable name introduced in #16064. It prevented existing actors to be loaded in ticket form.
=> Fix existing actors loading

js/form_editor_controller.js, templates/pages/admin/form/form_editor.html.twig
Suggested by @orthagh.
Before:
After:
=> Forms: display all actions labels

install/migrations/update_10.0.x_to_11.0.0/oauth.php, install/mysql/glpi-empty.sql, src/Api/HL/Middleware/IPRestrictionRequestMiddleware.php, src/Api/HL/Router.php, src/OAuthClient.php, templates/pages/setup/oauthclient.html.twig, tests/functional/Glpi/Api/HL/Middleware/IPRestrictionRequestMiddleware.php, tests/functional/OAuthClient.php
This was possible with the legacy API Clients, but wasn't added during the initial implementation of OAuth or the new API.
While API Clients have three fields `Pv4 address range start`, `IPv4 address range end` and `IPv6 address`, OAuth clients have a single `Allowed IPs` field which accepts a comma-separated list of individual IPv4/IPv6 addresses or ranges in CIDR notation. If the allowed IPs field is left blank, it is treated as there being no IP restrictions for the client.
=> OAuth Client IP Restrictions

src/ReservationItem.php
Fix SQL error when ```is_recursive``` column not exist
```sql
SQL: SELECT COUNT(*) AS total FROM `glpi_plugin_genericobject_scannerportables` INNER JOIN `glpi_reservationitems` ON (`glpi_reservationitems`.`items_id` = `glpi_plugin_genericobject_scannerportables`.`id` AND `glpi_reservationitems`.`itemtype` = 'PluginGenericobjectScannerportable') WHERE `glpi_reservationitems`.`is_active` = '1' AND `glpi_plugin_genericobject_scannerportables`.`is_deleted` = '0' AND ((`glpi_plugin_genericobject_scannerportables`.`entities_id` IN ('1') OR (`glpi_plugin_genericobject_scannerportables`.`is_recursive` = '1' AND `glpi_plugin_genericobject_scannerportables`.`entities_id` IN ('0'))))
Error: Unknown column 'glpi_plugin_genericobject_scannerportables.is_recursive' in 'where clause'
```
| Q …
=> Fix(ReservationItem): Fix SQL error when 'is_recursive' column not exist

src/Api/HL/Controller/AdministrationController.php, src/Api/HL/Middleware/OAuthRequestMiddleware.php, src/Api/HL/OpenAPIGenerator.php, src/Api/HL/Router.php, src/OAuth/ScopeRepository.php, src/OAuth/Server.php, src/OAuthClient.php, templates/pages/oauth/authorize.html.twig, templates/pages/setup/oauthclient.html.twig, tests/functional/Glpi/Api/HL/Controller/AdministrationController.php
Adds very basic OAuth scopes support:
- `email`: Access to the user's own default email address
- `user`: Access to the user's information
- `status`: Access to the status endpoints (Does not apply when accessed via the CLI commands)
- `inventory`: Access to submit inventory from an agent (Not implemented yet). Will eventually be used for authentication between the GLPI Agent and GLPI.
- `api`: Access to the API (All other endpoints not handled by their own scope)
The scopes are added into the OpenAPI documentation so the Swagger authentication UI has new options:
The authorization page in GLPI has been updated to show …
=> Basic OAuth scopes implementation

CHANGELOG.md, css/includes/_base.scss, front/group.php, front/user.php, src/Group.php, src/User.php
To avoid double scrollbar on these search pages, the buttons that were above the search have been moved to the top of the page. This also helps keep the UI consistent with other pages.
Even after moving the buttons, there was still a double scrollbar but without any clear reason so I made a small adjustment to the content-margin CSS variable to compensate.
There are two other pages with display alerts/messages above the search which also give the double scrollbar issue, but the fix is more complex so it will be done in another PR.
=> Remove buttons above user and group search

src/Asset/AssetDefinition.php, src/Search/SearchOption.php, tests/units/Glpi/Search/SearchOption.php
Assign search option IDs for capacities based on the capacity class name to ensure each capacity keeps the same ID regardless of the order they are defined.
=> Dynamic asset capacity search option ids

js/form_editor_controller.js
Not sure why this is missing, I remember adding it a while ago.
Maybe delete by mistake at some point.
This enable the question drag and drop features on newly created form sections.
=> Enable sortable on new form sections

js/form_editor_controller.js
Sortable does not allow empty lists to accept dragged items which mean we couldn't drag a question into an empty section.
Fixed by adding a "fake" empty div with a 1px height at the end of empty sections.
=> Allow questions to be dragged into empty sections

js/form_editor_controller.js
Previously, the "active" form item was highlighted until the user clicked on another form item.
Clicking outside the form did nothing, which is unexpected as most UX items are usually no longer "active" when you click outside of them.
=> Drop focus when the user click outside the form

ajax/form/answer.php, front/form/destination/formdestination.form.php, inc/relation.constant.php, install/migrations/update_10.0.x_to_11.0.0/form.php, install/mysql/glpi-empty.sql, js/form_renderer_controller.js, src/Form/AnswersHandler/AnswersHandler.php, src/Form/AnswersSet.php, src/Form/Destination/AbstractFormDestinationType.php, src/Form/Destination/AnswersSet_FormDestinationItem.php, src/Form/Destination/FormDestination.php, src/Form/Destination/FormDestinationInterface.php, src/Form/Destination/FormDestinationTicket.php, src/Form/Form.php, src/Html.php, src/Ticket.php, templates/pages/admin/form/form_destination.html.twig, tests/functional/Glpi/Form/AnswersSet.php, tests/functional/Glpi/Form/Destination/FormDestination.php, tests/functional/Glpi/Form/Destination/FormDestinationTicket.php, tests/src/Form/Destination/AbstractFormDestinationType.php, tests/src/FormBuilder.php, tests/src/FormTesterTrait.php
Followup to #16613, allow forms destination to be configurated from the interface using a new "Items to create" tab.
I don't think we need to discuss about the UI/UX of this tab yet as it does not have a lot of content.
It will be better to discuss it after more options are implemented.
The created tickets are listed on the answers page:
=> Forms: configure destinations from the interface

src/Inventory/Asset/Device.php, tests/functional/Glpi/Inventory/Assets/Bios.php, tests/functional/Glpi/Inventory/Inventory.php
Same as https://github.com/glpi-project/glpi/pull/16222 but for ```Item_Device``` 
I'm leaving it in draft form until I can see what impact it will have on the TUs for logs.
| Fixed tickets | !31950
=> Fix(Inventory) add history on Item_Devices add / update / delete when Mainasset already exist

src/Form/AnswersHandler/AnswersHandler.php, src/Form/Section.php, tests/functional/Glpi/Form/AnswersHandler/AnswersHandler.php, tests/functional/Glpi/Form/Section.php
The form editor currently "crashes" when an invalid question type is supplied.
This is not good because it might be a valid scenario (e.g. a type is defined by a plugin which was later disabled).
Thus it is better to simply ignore the question in this case.
=> Ignore invalid questions types in the form editor

src/Application/View/Extension/DataHelpersExtension.php, src/CronTask.php, templates/components/datatable.html.twig, templates/pages/setup/crontask/crontask.html.twig
- Twig migration for crontask logs list.
- Minor code cleanup.
CronTasks use the ext-pcntl extension to handle when the CLI script is terminated early (not a regular script exit). However, it isn't enabled in PHP by default and it also isn't available in Windows. So, I think the majority of GLPI installations are not using this functionality.
Is there an alternative way to handle this?
=> Crontask datatable twig migration

js/form_editor_controller.js
When a question/section is moved, we need to reinitialize its tinymce instance.
It was however failing in some cases and I didn't know why.
It turns out it was just some config conflitcs, I forgot that javascript use references for object by default.
=> Fix tinymce config conflicts in the form editor

js/modules/Monaco/MonacoEditor.js, src/ContentTemplates/TemplateManager.php, src/Webhook.php, tests/abstracts/AbstractITILChildTemplate.php, tests/units/Glpi/ContentTemplates/TemplateManager.php
Monaco's support for Twig doesn't include any information about the default environment, possibly because it can change (although it doesn't explain why keywords are missing). This PR at least adds some of the more common, available by default, keywords, functions, filters, etc to the list.
Obviously, this is still no replacement for user's reading the Twig documentation, but may give some hints to them that they do indeed have access to a default Twig environment and have some idea of what is available to them.
=> Monaco show basic suggestions for Twig env

templates/components/form/basic_inputs_macros.html.twig
Checkbox IDs attributes are double escaped due to how they are added. We only add the ID attribute if one was specified.
`{{ options.id != null ? 'id="' ~ options.id ~ '"' : '' }}`
This escapes "options.id" and then escapes the entire attribute again which results in something like `id=""agree_unstable""`.
=> Fix double escape on checkboxes with IDs

js/planning.js
| Fixed tickets | !32081
Corrected the appearance of tasks each time the page is loaded. It is no longer necessary to refresh manually with the button. 
**Before**
**After**
=> Fix default view of planning list

css/standalone/chartist.scss
| Fixed tickets | !32051
Resolved a display bug on pie and donut diagrams in the dashboard.
Before:
After:
=> Fix Chartist Pie unfilled colors

css/includes/components/_content-editable-inputs.scss, js/form_editor_controller.js, templates/pages/admin/form/form_editor.html.twig, templates/pages/admin/form/form_question.html.twig, templates/pages/admin/form/form_section.html.twig
Some margins where not ideal after recent changes.
\+ fixed an annoying scrolling issue.
Before:
After:
=> Improve form editors margins

src/Document.php, src/Toolbox.php, tests/functional/Toolbox.php
Currently, there are some TODO comments saying that certain functions or code blocks should be deprecated in a future version. Sometimes, these are missed before that version is released. So, we should allow adding `Toolbox::deprecated` immediately while targeting that future version for when the messages should start being logged.
=> Support planned deprecations

src/NotificationAjaxSetting.php, src/NotificationEventAbstract.php, src/NotificationEventInterface.php, src/NotificationTemplateTranslation.php, src/Notification_NotificationTemplate.php, src/QueuedNotification.php, templates/pages/setup/notification/translation.html.twig
UI migrations to twig to come in another PR.
- Cleanup/modernization of some notification code
- Some sanitization done in places that won't be migrated to Twig/used in Twig now but are output as raw values
- Fix for already used template translation languages showing up in the language dropdown for a new translation (missing since 9.5.6)
=> Review and clean some notification code

install/migrations/update_10.0.14_to_10.0.15.php, install/migrations/update_10.0.14_to_10.0.15/user.php, src/User.php, tests/functional/User.php
| Fixed tickets | #16725
When it has been introduced in #16096 `user_dn_hash` was computed based on `user_dn` values stored in DB, and these values are sanitized. The problem is that it is compared with a non-sanitized values, at least in the LDAP synchronization command.
For instance,
`md5('user=me,dc=R&#38;D,dc=glpi-project,dc=org')`
does not match
`md5('user=me,dc=R&D,dc=glpi-project,dc=org')`
=> Fix `user_dn_hash` reconciliation when user DN contains special chars

src/CommonTreeDropdown.php, src/Location.php, templates/components/datatable.html.twig
- Migrate CommonTreeDropdown tab that shows child items to Twig
- Added ability to use massive actions
- Migrate Items list for Locations to Twig
- Datatable template changes
- Ability to have an HTML super_header
- Ability to disable sorting per-column (already done in other PRs)
- Ability to disable filtering per-column
- Ability to have a different formatter for the filter than the column values
=> Location Twig UI

CHANGELOG.md, inc/db.function.php, src/DbUtils.php, src/Lock.php
- `Lock::getLocksQueryInfosByItemType()` is only used in the Lock class. It was made private.
- Fix static method calls.
- Increase strictness of datatype comparisons.
- Replacement of implicit joins (multiple tables in FROM) with explicit joins. Not likely to affect performance, but implicit joins aren't supported by some DBMS and may be more confusing for some people to read.
- PHPDoc improvements/fixes
- Performance improvements:
- De-duplicate getting some table names.
- Replacing preg_match with str_starts_with when only checking if a string starts with another.
- Reduce number of queries in case where a first query is …
=> Review and clean Lock class

src/CommonITILObject.php, src/Search/Provider/SQLProvider.php
The conversion of request criteria arrays to SQL can only handle a single extra element in the join array for additional criteria. Any extra conditions have to be inside that third element or else they are ignored.
=> Fix merging of join conditions in search engine

js/form_editor_controller.js, templates/pages/admin/form/form_question.html.twig
Add the ability to duplicate questions and fixes the section duplication action that was not working properly in some cases.
=> Forms: duplicate questions

templates/components/search/query_builder/main.html.twig
Missing border and bottom spacing
before: 
after:
=> fix legacy display for search form (missing border and spacing)

inc/based_config.php
Since #16763, the default value was `['{GLPI_MARKETPLACE_DIR}', '/var/www/glpi/plugins']` due to bad handling of inheritence defaults for array values.
=> Fix `PLUGINS_DIRECTORIES` default value

src/NetworkEquipment.php
| Fixed tickets | !31937
Avoids SQL errors when the item is connected to several other items via network ports.
```
glpisqllog.WARNING: DBmysql::doQuery() in /home/ubuntu/Dev/GLPI/10.0-bugfixes/src/DBmysql.php line 443
SQL: SELECT COUNT(*) AS cpt FROM `glpi_computers` WHERE `id` = '19,21' AND  NOT (`entities_id` IN ('0'))
Warnings: 
1292: Truncated incorrect DOUBLE value: '19,21'
Backtrace :
src/DBmysqlIterator.php:112                        DBmysql->doQuery()
src/DBmysql.php:1109                               DBmysqlIterator->execute()
src/DbUtils.php:524                                DBmysql->request() …
```
=> fix(network port): prevent sql error message

src/Dropdown.php, src/Session.php, tests/functional/Session.php
The dropdown fields displayed by the `generic_show_form` template are always passing `item.fields['entities_id']` to restrict dropdown entities, even for items that does not have this field (e.g. `Socket`). See https://github.com/glpi-project/glpi/blob/eb40b431374bde303d958f7af4cfa8724d17de85/templates/generic_show_form.html.twig#L156-L166
It triggers a deprecation log on PHP >= 8.1.
=> Fix deprecation on dropdown fields with a `null` entity restrict

js/planning.js
| Fixed tickets | !32146
In some cases, the personal view planing overlapped with the public reminders.
Before:
After:
=> fix(personal view): planning display

src/NetworkPort.php, tests/functional/NetworkPort.php
| Fixed tickets | !31937
Following https://github.com/glpi-project/glpi/pull/16738, we get an error on ports that have no correspondence in the Fields plugin tables, for example, when the port existed before the fields added by the plugin were created.
```
glpiphplog.NOTICE:   *** PHP Deprecated function (8192): htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/glpi/src/Html.php at line 2502
Backtrace :
src/Html.php:2502                                  htmlspecialchars()
src/NetworkPort.php:1018                           Html::getMassiveActionCheckBox()
src/NetworkPort.php:905 …
```
=> fix(network port): error message

src/Api/HL/Controller/AbstractController.php, src/Api/HL/Controller/AdministrationController.php, src/Api/HL/Controller/AssetController.php, src/Api/HL/Controller/ComponentController.php, src/Api/HL/Controller/ITILController.php, src/Api/HL/Controller/ManagementController.php, src/Api/HL/Controller/ProjectController.php, src/Api/HL/Controller/RuleController.php, src/Api/HL/Search.php, tests/HLAPITestCase.php, tests/functional/Glpi/Api/HL/Controller/AdministrationController.php
I think this is the last major feature that was missing from the new API search engine in comparison to the legacy API/web search.
The way sorting is handled in the new API is through a `sort` query parameter in the form of `property:direction`. Multi-sort works by simply providing a comma-separated list of sorts. The sort direction can be excluded to have it default to "ASC".
=> [HLAPI] Sorting

src/Api/HL/Controller/AssetController.php, src/Api/HL/Controller/ManagementController.php, tests/functional/Glpi/Api/HL/Controller/AssetController.php
`/{itemtype}/{id}/Infocom` endpoint allows getting infocom data for a specific asset.
Like other GET endpoints, the user can optionally format the response as CSV or XML using the `Accept` header.
=> [HLAPI] Get infocom information for assets

CHANGELOG.md, front/group_user.form.php, front/user.form.php, src/CommonTreeDropdown.php, src/Group.php, src/Group_User.php, templates/components/datatable.html.twig, templates/pages/admin/group_user.html.twig, tests/functional/Group_User.php
Move UI relating to items belonging to/managed by groups, users in a group, and groups assigned to a user to twig.
Still need to re-add filter support to the lists. Will require some changes to how filters are handled in the datatables template.
List of users in a group (Before):
List of users in a group (After):
List of groups for a user (Before):
List of groups for a user (After):
=> Groups UI Twig

src/Lock.php, templates/components/datatable.html.twig
Relies on #16796.
- Migrate the lists on an asset's Locks tab to Twig
- New datatable template features
- Ability to hide regular column headers to accommodate nested datatables (each nested table has its own columns and the parent table only has one column containing the subtables).
- Ability to toggle massive action checkboxes per-row
- Ability to change the table class used for styling (table-hover, table-sm, etc)
=> Lock Twig UI

front/form/destination/formdestination.form.php, install/migrations/update_10.0.x_to_11.0.0/form.php, install/mysql/glpi-empty.sql, src/Form/AnswersHandler/AnswersHandler.php, src/Form/Destination/AbstractCommonITILFormDestination.php, src/Form/Destination/CommonITILField/CommonITILFieldInterface.php, src/Form/Destination/CommonITILField/ContentField.php, src/Form/Destination/CommonITILField/TitleField.php, src/Form/Destination/ConfigFieldInterface.php, src/Form/Destination/FormDestination.php, src/Form/Destination/FormDestinationTypeManager.php, templates/pages/admin/form/form_destination.html.twig, templates/pages/admin/form/form_destination_commonitil_config.html.twig, tests/functional/Glpi/Form/AnswersSet.php, tests/functional/Glpi/Form/Destination/FormDestination.php, tests/functional/Glpi/Form/Destination/FormDestinationChange.php, tests/functional/Glpi/Form/Destination/FormDestinationProblem.php, tests/functional/Glpi/Form/Destination/FormDestinationTicket.php, tests/functional/Glpi/Form/Form.php, tests/src/Form/Destination/AbstractFormDestinationType.php, tests/src/FormBuilder.php, tests/src/FormTesterTrait.php
Add basic configuration for forms destination:
Once merged, the next steps are:
- Enable dynamic values based on the users answers.
- Add some kind of "auto" mode that auto compute these dynamic values (e.g. the ticket content will list all available questions/answers when in auto mode). The goal is that 99% of the users can just let "auto" everywhere and get a perfectly working form, leaving manual configuration for the 1% power users.
- Support all fields (will need the relevant question types to be added first, e.g. it is not possible to properly add the ticket type (request/incident) field config before the "request type" question type is added to forms).
The UI is not final but you can start making UI/UX suggestion if you want.
| Bug fix? …
=> Form destinations: basic configuration

templates/components/search/query_builder/main.html.twig
Remove a duplicated border + an unnecessary internal margin.
Before:
After:
=> Fix search UI

src/GLPIMailer.php, src/Mail/SMTP/OAuthTokenProvider.php
| Fixed tickets | !31976
When connecting against the Microsoft SMTP server, the granted access token may (always?) contain a new refresh token. In this case, the refresh token has been itself refreshed. In this case, the previous token will expire 90 days later. To prevent this expiration to block the Oauth authentication, we have to replace the previously known refresh token by the new one.
=> Always store updated SMTP Oauth refresh token

.github/actions/init_containers-start.sh, .github/actions/init_initialize-0.80-db.sh, .github/actions/init_initialize-9.5-db.sh, .github/actions/init_initialize-imap-fixtures.sh, .github/actions/init_initialize-ldap-fixtures.sh, .github/actions/init_show-versions.sh, .github/workflows/ci.yml, .github/workflows/coverage.yml, tests/run_tests.sh
The `docker-compose` command is no more available on latest docker versions. It has been replaced by the `docker compose` command.
=> Replace usage of obsolete `docker-compose` method

src/NotificationTargetProjectTask.php
| Fixed tickets | !32275
The old labeling suggested that users and groups linked to the project would be notified when a task was created or updated. In the new code, users or groups linked to the task are notified, which is more logical.
**Before**
**After**
=> Change notifications task labels

src/Project.php, src/ProjectTask.php
This pull request addresses issues with the search criteria and state handling in the Project class, which were introduced in the initial implementation of feature #16709.
- The search criteria now correctly differentiates between User and Group item types
- The search criteria now also takes into account the state of the project. Previously, finished projects were included in the search results.
- Add search options on users/groups/suppliers/contact for project tasks
=> Fix project search criteria and state handling in personnal and group dashboard

src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php, tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
We do not know really what it happens, but on one of our GLPI cloud instance, some tables return an unexpected length of `250` on some indexes on their `SHOW CREATE TABLE` command. Removing an recreating the index without specifying any length does not change anything.
It blocks the update script as the `db:check` commands considers that the DB schema is not correct.
```
Le schéma diffère pour la table "glpi_authldaps".
--- Schéma de base de données attendu
+++ Schéma de base de données actuel
@@ @@
KEY `is_active` (`is_active`),
KEY `is_default` (`is_default`),
KEY `name` (`name`),
-  KEY `sync_field` (`sync_field`)
+ …
```
=> Prevent DB check to fail on unexpected 250 index length

src/ProjectTask.php, tests/functional/ProjectTask.php
Corrects a problem initiated by PR #16718, the purpose of which was to automatically set the actual date of a project task. However, when the `real_start_date` field was set to an empty string (when saving the form with an empty date, for example), the automatic date setting no longer worked, since the field was not `null`.
=> fix: resolve issue with auto-setting real start and end dates in ProjectTask

src/Config.php, src/Profile.php, templates/pages/setup/general/general_setup.html.twig, tests/DbTestCase.php, tests/functional/Config.php, tests/functional/Profile.php
Some users ran into trouble when they modified the `Read-Only` profile to be restricted to the simplified interface.
This create major issues with the locking mechanism (as this profile is the default `Profile to be used when locking items` on a fresh install).
Trying to open a locked item will then log out the user because GLPI try to load a self-service profile while being on a central restricted page (e.g. a computer):
---
To prevent this, I've added two restrictions:
* The current "Profile to be used when locking items" can't be set to use the simplified interface.
* In the general configuration, simplified interface profiles can't be set as the "Profile to be used when locking items".
| BC breaks? …
=> Prevent invalid lock config

src/Computer_Item.php
| Fixed tickets | !32398
Fixed error in sql query for computer with sub-entities option enabled .
=> Fix SQL Warning Truncated linked to computer connection

tests/cypress.config.js, tests/cypress/e2e/selfservice_tickets.cy.js, tests/cypress/support/commands.js
- Enables experimental "Cypress Studio" which lets you generate test code by interacting with the browser inside Cypress. May be helpful for devs that aren't very familiar with Cypress yet or aren't comfortable with JavaScript.
https://docs.cypress.io/guides/references/cypress-studio
Tests:
- The dropdowns on the new ticket form which get their results through AJAX requests can all be opened and have their results loaded properly.
- Ticket can be created.
- The "OK" checkmark image and a toast notification are shown after the ticket is submitted.
- The ticket form loads by clicking the link in the notification.
- The …
=> Add some self-service ticket e2e tests

src/Entity.php
```
glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "tickettemplates_strategy" in .../src/Entity.php at line 3750
Backtrace :
src/CommonDBTM.php:4944                            Entity::getSpecificValueToDisplay()
src/Log.php:722                                    CommonDBTM->getValueToDisplay()
src/Log.php:325                                    Log::getHistoryData()
src/Log.php:110                                    Log::showForItem()
src/CommonGLPI.php:694                             Log::displayTabContentForItem()
ajax/common.tabs.php:120                           CommonGLPI::displayStandardTab() …
```
=> fix(entity): prevent warning on history tab

css/includes/_palette_dark.scss
| Fixed tickets | !32421
The user icon text was unreadable if the background was light. I had modified the _avatars.scss file but it doesn't do push so I did this via the _palette_dark.scss file.
=> Fix user icon text color in dark theme

CHANGELOG.md, src/Auth.php, src/AuthLDAP.php, src/AuthLdapReplicate.php, src/AuthMail.php
No substantial changes given how complex this code is.
Changes mostly consist of:
- PHPDoc fixes
- Removing redundant `isset` when followed by `empty` checks
- Adding `public` to consts (the default visibility)
- Replacing some lines with the shorter ?? version
- Replacing $this->getTable with static::getTable
- Deprecate Auth::getErr as a TODO note specified
=> Clean Auth Code

templates/pages/login.html.twig
Based on forum post:
https://forum.glpi-project.org/viewtopic.php?id=289797
The forgot password feature only works for local accounts, but the link on the login page is always shown. This PR makes it shown only when the local source is selected, or when the login source dropdown isn't shown at all.
=> show forgot password link only for local accounts

src/Inventory/Asset/Software.php, src/Software.php, tests/functional/Glpi/Inventory/Assets/Software.php
| Fixed tickets | #16036
Since there is often (always?) a system category ("Unspecified") defined in inventory file, rules to assign a category to a software are not run from inventory.
=> Handle software category rules from inventory

CHANGELOG.md, src/CommonITILObject.php, src/Itil_Project.php, src/Project.php, src/ProjectTask.php, tests/functional/Entity.php
Migrations for the project-related UI are proving to be more work than originally intended so I am splitting the work over multiple PRs. The "Itil items" tab for projects relied on `CommonITILObject::commonListHeader` and `CommonITILObject::showShort` to display the lists. Both methods echo raw HTML. To allow these lists to be shown with the datatable template like almost every other list, two replacement methods were added. The original methods are now deprecated. There are other places that use the old methods in the core and they will be migrated in future PRs. The old methods are used in at least one plugin (Releases). …
=> Project UI Migration (Part 1)

js/reservations.js, src/Reservation.php
| Fixed tickets | #15929
The `now` indicator in the reservations calendar was not displayed at the correct position. I reused the same logic as we already use in the planning calendar.
=> Fix "now" indicator in reservation calendar

src/Planning.php
While working on the planning UI migrations, I realized this form had duplicated entries for a user and was also showing SQL errors. Not sure when it broke, but this particular line hasn't changed in 8 years. Took a while for me to find where this form could be displayed (There is a calendar icon button next to the "Period" field when planning a task). Maybe it isn't used very often.
Before:
After:
=> Fix planning availability form

src/Asset/Capacity/HasSoftwaresCapacity.php, tests/functional/Glpi/Asset/Capacity/HasAntivirusCapacity.php, tests/functional/Glpi/Asset/Capacity/HasAppliancesCapacity.php, tests/functional/Glpi/Asset/Capacity/HasCertificatesCapacity.php, tests/functional/Glpi/Asset/Capacity/HasContractsCapacity.php, tests/functional/Glpi/Asset/Capacity/HasDatabaseInstanceCapacity.php, tests/functional/Glpi/Asset/Capacity/HasDocumentsCapacity.php, tests/functional/Glpi/Asset/Capacity/HasDomainsCapacity.php, tests/functional/Glpi/Asset/Capacity/HasHistoryCapacity.php, tests/functional/Glpi/Asset/Capacity/HasInfocomCapacity.php, tests/functional/Glpi/Asset/Capacity/HasKnowbaseCapacity.php, tests/functional/Glpi/Asset/Capacity/HasLinksCapacity.php, tests/functional/Glpi/Asset/Capacity/HasNetworkPortCapacity.php, tests/functional/Glpi/Asset/Capacity/HasNotepadCapacity.php, tests/functional/Glpi/Asset/Capacity/HasOperatingSystemCapacity.php, tests/functional/Glpi/Asset/Capacity/HasPeripheralAssetsCapacity.php, tests/functional/Glpi/Asset/Capacity/HasRemoteManagementCapacity.php, tests/functional/Glpi/Asset/Capacity/HasSoftwaresCapacity.php, tests/functional/Glpi/Asset/Capacity/HasVirtualMachineCapacity.php, tests/functional/Glpi/Asset/Capacity/HasVolumesCapacity.php, tests/functional/Glpi/Asset/Capacity/IsRackableCapacity.php, tests/functional/Glpi/Asset/Capacity/IsReservableCapacity.php, tests/src/Asset/CapacityUsageTestTrait.php
=> Capacity: Has softwares

src/Asset/AssetDefinition.php
1. The counters were displayed even when the `show_count_on_tabs` was set to `false`.
2. The profiles tab counter was counting profiles with no rights. Now it only counts profiles with at least one right (right value > 0).
=> Fix counters on asset definition tabs

src/Database.php
=> fix: typo in databaseinstance search function

.github/actions/init_build.sh, .github/workflows/ci.yml, phpstan.neon, src/User.php
PHPStan relies on the required PHP version found in the `composer.json` to adapt its behaviour. It means that some error will not be found until we change our requirements, see errors that had to be fixed in #16943 .
By forcing the PHP requirement and the `config.platform.php` entry of the `composer.json` file to match the effective PHP version tested by our lint tasks, we may detect errors earlier.
=> Rely on tested PHP version for PHP lint checks

src/Ajax.php
| Fixed tickets | #16963
This fixes a JS error preventing to display any page. 
This reintroduce for some cases original issue (see #16703), but anyway, proposed fix was probably not working when configuration URL is incorrect. Since we never ask user to properly configure that URL (and it does not seems really mandatory elsewhere); I'm not sure the original fix was correct.
=> Fix JS error when configuration URL is blank

src/Contract.php, src/Infocom.php, tests/functional/Contract.php
| Fixed tickets | https://github.com/glpi-project/glpi/issues/16890
Since https://github.com/glpi-project/glpi/pull/16719, in the search view, the renewal value was not taken into account, and the expiry date of contracts without tacit renewal was wrong.
=> fix(contract): expiration date in search

src/Html.php
Prevents a "missing license key" message to be shown in the javascript console.
See https://www.tiny.cloud/docs/tinymce/latest/license-key/#use-tinymce-with-the-gplv2-license
=> Add missing TinyMCE license key

composer.lock
| Fixed tickets |  #16970
According to the changelog, we should not be subject to unexpected side effects: https://github.com/tecnickcom/TCPDF/compare/6.7.4...6.7.5
=> Bump `tecnickcom/tcpdf` from 6.7.4 to 6.7.5

templates/components/form/basic_inputs_macros.html.twig, templates/components/form/fields_macros.html.twig, templates/pages/assistance/stats/title.html.twig
Labels for fields should only contain sanitized text content. As far as I know, there is only one intended case where HTML content was passed as a label for a field. In that case, I don't think it resulted in valid HTML. According to MDN, only phrasing content and the labelable element being labelled is allowed inside a `<label>`. The `<h*>` elements do not fall into either category. I've replaced this usage with the ability to specify some extra classes for the label and adding the `fs-3` class to adjust the text size to match that of a `<h3>` without the semantic change. …
=> No HTML in field labels

front/stat.global.php, front/stat.graph.php, src/Search/Output/AbstractSearchOutput.php, src/Search/Output/HTMLSearchOutput.php, src/Stat.php, templates/pages/assistance/stats/title.html.twig
The Stat display seems to have a legitimate reason to have a (pseudo)search output display instead of using `datatable` due to it being exportable. So, rather than migrate it to Twig, the focus was on changing uses of the old `Search` class methods to using the new `Search/*` classes and making sure values were being sanitized when needed.
Some redundant code was simplified as well.
The graph icon image used in the link to display a graph for a specific line was replaced with a webfont icon and added a title for the link.
=> More Stat code cleanup + UI work

js/src/vue/Debug/Widget/SQLRequests.vue
Broken since 69e0dee8de0c0df139b42dbfa1a8997888c2af95. The commit broke the highlighting HTML by sanitizing the query after the highlighting elements were added, and forced it to display a wall of gray HTML content instead of the nice, colorful SQL query.
In fact, the escaping of a SQL query here seems unneeded as Monaco is smart enough to properly sanitize the text it is given to colorize. As a test, I tried forcing all the queries to be `<button>test</button>` and with my changes, that content was shown as-is rather than inserting a button HTML element.
=> Remove bad HTML sanitization

css/includes/_base.scss
At some point, a blue outline became visible inside the single-line Monaco editors (like the URL field in the webhook form). This outline seems to be present in the regular editor too, but isn't visible. This PR simply removes the outline globally.
=> remove outline visible for single line monaco editors

templates/components/checkbox_matrix.html.twig
Prevent profile right matrix tables from overflowing outside the tab pane. Each matrix section will now have a horizontal scrollbar when needed to handle the extra content.
=> Prevent profile right matrix overflow

src/Migration.php, tests/units/Migration.php
| Fixed tickets | !32139
Updates the search option number in the `XXXtemplatehiddenfields`, `XXXtemplatemandatoryfields` and `templatepredefinedfields` tables when the itemtype concerned is a CommonITILObject
=> fix(migration): update template fields

src/Mail/SMTP/OauthConfig.php
The SSL certificate verification was disabled on SMTP Oauth connection only when a proxy was configured.
Having this option was not intentionnal (it was copied/pasted from the OauthIMAP plugin implementation, problably also copied/pasted from somewhere else).
There is no reason to not check certificates when a connection is made through proxies. There are many usages in GLPI an plugins that are using the Guzzle client with the same proxy configuration and all of them are not disabling the SSL verification.
=> Verify OauthSMTP SSL certificates when proxy is used

ajax/form/answer.php, src/Form/EndUserInputNameProvider.php, src/Form/Question.php, src/Form/QuestionType/AbstractQuestionTypeActors.php, src/Form/QuestionType/AbstractQuestionTypeShortAnswer.php, src/Form/QuestionType/QuestionTypeDateTime.php, src/Form/QuestionType/QuestionTypeLongText.php, src/Form/QuestionType/QuestionTypeUrgency.php, tests/functional/Glpi/Form/EndUserInputNameProvider.php
A method has been added to centralize the input names of the question types on the final form interface. The format has also been modified so that the answers to the questions are no longer stored in a single attribute. This is similar to the way FormCreator works, and simplifies the path for the upcoming arrival of the `File` question type.
=> refactor(forms): centralize end user input name

CHANGELOG.md, src/Html.php, src/Item_SoftwareVersion.php, src/Software.php, src/SoftwareLicense.php, src/SoftwareVersion.php, templates/components/datatable.html.twig
Based on #16912.
There are a lot of lists, so this work will be split into two PRs.
=> Software Twig UI 1

composer.json, composer.lock
Using a 64 bits version of PHP is now mandatory (see #14133).
Since composer 2.6, it is possible to add it as a requirement (see https://github.com/composer/composer/pull/11334).
=> Add PHP 64 bits requirement in `composer.json`

CHANGELOG.md, public/index.php, src/Http/ProxyRouter.php
Adds a redirect from the well-known ([RFC 5785](https://datatracker.ietf.org/doc/html/rfc5785)) change-password URI `.well-known/change-password` to `front/updatepassword.php`. This URI is often utilized by password managers. This is completely handled within the ProxyRouter.
=> Support Well-known change-password URI

.webpack.config.js, css/includes/_base.scss, css/includes/_palette_dark.scss, src/Api/API.php
Companion PR to #17059. If both PRs are approved, we should have nothing left using PrismJS in the core and it could be removed.
The trade-off in this PR is that Apache and NGINX config examples at the end of the documentation have no language support. In both cases, it is custom syntax.
For the Apache config, everything is commented out anyways so syntax highlighting doesn't really matter. We could trick it into highlighting by choosing any language with a `#` comment character.
For NGINX, the example as written looks mostly good if highlighted as GraphQL, but may look wrong to anyone that actually knows NGINX configs (not …
=> Use Monaco for legacy API examples

.github/dependabot.yml
It is preferable to use the same major version for all the `symfony` components we use. Since some of the libraries we use are not compatible with `symfony` 7.x, dependabot is proposing an update to 7.x only for some components, for instance:
To prevent this, I propose to explicitely ignore versions >= 7.x for now.
=> Prevent `symfony` components to be updated to 7.x version

src/Asset/AssetDefinition.php
Fix this :
```shell
[2024-05-06 14:10:20] glpiphplog.WARNING:   *** PHP User Warning (512): Invalid `translations` value (``). in /home/stanislas/TECLIB/DEV/GLPI/main/src/Asset/AssetDefinition.php at line 1002
Backtrace :
src/Asset/AssetDefinition.php:1002                 trigger_error()
src/Asset/AssetDefinition.php:654                  Glpi\Asset\AssetDefinition->getDecodedTranslationsField()
src/Asset/AssetDefinition.php:82                   Glpi\Asset\AssetDefinition->getTranslatedName()
src/CommonDBTM.php:5948                            Glpi\Asset\AssetDefinition->computeFriendlyName()
src/CommonDBTM.php:3690                            CommonDBTM->getFriendlyName()
src/CommonGLPI.php:1225                            CommonDBTM->getName() …
```
=> Fix(AssetDefinition): prevent PHP warning about missing translation on create

install/migrations/update_10.0.x_to_11.0.0/event.php, src/DbUtils.php, tests/functional/Transfer.php
There are many pieces of GLPI code that are using something like `$itemtype::getTypeName()` or `new $itemtype()` without previously normalizing the `$itemtype` value using the `getItemForItemtype()` method. The remaining `Event` itemtypes values in the database, are probably unsupported since a long time ago.
Anyway, I think the best solution here is to fix values from DB in order to remove the runtime transformation from `Event` to `Glpi\Event`.
=> Drop support of old `Event` class name

templates/components/itilobject/selfservice.html.twig, templates/components/itilobject/timeline/timeline.html.twig, templates/components/user/link_with_tooltip.html.twig
| Fixed tickets | !32593
Linked to this Pull request : #16974 
The tooltips were only displayed in the item list and not when we went to the item page. This pull request adds this functionality.
**Ticket page**
**Computer page**
=> (Feature) Adding user tooltip to internal item view

install/empty_data.php
To ease API testing (especially API requests), we can set the most often used profile (super admin) as the default profile for the e2e tests.
=> Set default profile for e2e_tests user

inc/includes.php, src/Toolbox/URL.php, tests/cypress/e2e/tabs.cy.js, tests/units/Glpi/Toolbox/URL.php
Trying to access a specific tab using the `forcetab` parameters on namespaced items does not work.
For example, `/front/form/form.form.php?id=50&forcetab=Glpi\Form\Destination\FormDestination$1` won't work, while `/front/computer.form.php?id=1&forcetab=Item_Line$1` works perfectly.
The issue isn't the namespace in the forcetab parameter (`Glpi\Form\Destination\FormDestination`, which is handled correctly) but instead the file path `/front/form/form.form.php` which is not interpreted correctly by our regex.
See:
The regex detect the correct `computer` itemtype when there are no namespace.
For the namespaced `form` itemtype, the regex return only `form` which is an incomplete type. 
To fix this, I've modified the regex this way:
Now we detect correctly `form/form`, which is easy to turn …
=> Fix forcetab parameter on namespaced items

CHANGELOG.md, css/legacy/includes/_styles.scss, front/change_supplier.form.php, front/change_user.form.php, front/problem_supplier.form.php, front/problem_user.form.php, front/supplier_ticket.form.php, front/ticket_user.form.php, inc/config.php, src/CommonDBTM.php, src/CommonDevice.php, src/CommonITILActor.php, src/Html.php, tests/units/Html.php
=> CommonDBTM, CommonITILActor, HTML class UI + Drop unused code

src/Form/QuestionType/QuestionTypeCategory.php, src/Form/QuestionType/QuestionTypeRequestType.php, tests/units/Glpi/Form/AnswersSet.php, tests/units/Glpi/Form/QuestionType/QuestionTypesManager.php
Added `Request Type` categories and related sub-question type : `Request Type`
=> feat(forms): Adding request type category and related question type

src/Group_User.php
Change made in #17034 was not correct. Indeed, the `NOT` clause was outside the condition entry. I tried to fix it, by moving it, with the following patch, but it resulted with a fatal error.
```diff
diff --git a/src/Group_User.php b/src/Group_User.php
index 385ad547c4..96a423d1da 100644
--- a/src/Group_User.php
+++ b/src/Group_User.php
@@ -205,7 +205,9 @@ class Group_User extends CommonDBRelation
'condition' => [
'is_usergroup' => 1,
] + getEntitiesRestrictCriteria(Group::getTable(), '', '', true)
-            ] + ['NOT' => self::getListForItemParams($user)];
+                  + ['NOT' => …
```
=> Fix user group dropdown condition

src/Form/AnswersHandler/AnswersHandler.php, src/Form/Question.php, src/Form/QuestionType/AbstractQuestionType.php, src/Form/QuestionType/AbstractQuestionTypeActors.php, src/Form/QuestionType/QuestionTypeCategory.php, src/Form/QuestionType/QuestionTypeDateTime.php, src/Form/QuestionType/QuestionTypeFile.php, src/Form/QuestionType/QuestionTypeInterface.php, tests/units/Glpi/Form/AnswersSet.php, tests/units/Glpi/Form/QuestionType/QuestionTypesManager.php
Added `File` category and related sub-question type : `File`
=> feat(forms): Adding file category and related sub question type

js/common_ajax_controller.js, src/Ajax.php, tests/cypress/e2e/ajax_controller.cy.js
Improve the AJAX controller by removing cached tabs when an object is updated.
GLPI tabs are loaded once when clicked and then are kept in cache.
This is good for "standard" forms, however it is not ideal for items updated by the AJAX controller.
Indeed, as the AJAX controller can update an item without forcing a page reload, this mean any cached tab data is kept and will thus no longer be accurate until the user manually refresh the page.
To counter this, we just need to clear the cached content after an AJAX update is done.
In the following demo, you can see the history being updated in "real time" thanks to these changes:
=> Force tab reload after an ajax update

CHANGELOG.md, ajax/networkname.php, src/CommonDBChild.php, src/NetworkName.php, src/NetworkPort.php, src/NetworkPortAggregate.php, src/NetworkPortAlias.php, src/NetworkPortConnectionLog.php, src/NetworkPortDialup.php, src/NetworkPortEthernet.php, src/NetworkPortFiberchannel.php, src/NetworkPortInstantiation.php, src/NetworkPortMetrics.php, src/NetworkPortMigration.php, src/NetworkPortType.php, src/NetworkPortWifi.php, src/NetworkPort_NetworkPort.php, src/NetworkPort_Vlan.php, src/Vlan.php, templates/components/form/networkname.html.twig, templates/pages/assets/networkport/form.html.twig, templates/pages/assets/networkport/networkname_short.html.twig
Notable UX Changes:
- List of network ports in a VLAN form now shows the NetworkPort link in a breadcrumb manner (MyServer > eth0 where MyServer is a link to the computer and eth0 is a link to the port).
- The Network Name section of a port was reworked. The link labeled "Network name" which took you to the network name item is now removed. The network name itself now shows the text field which allows freeform entry along with 2 grouped buttons (same style as dropdowns). The first button either takes you to the network name if one is linked, or to the search page. The second button allows you to dissociate the network name.
=> Network Port Twig UI

css/includes/components/form/_form-editor.scss, js/form_editor_controller.js, js/form_question_selectable.js, src/Form/Form.php, src/Form/Question.php, src/Form/QuestionType/AbstractQuestionType.php, src/Form/QuestionType/AbstractQuestionTypeSelectable.php, src/Form/QuestionType/QuestionTypeCategory.php, src/Form/QuestionType/QuestionTypeCheckbox.php, src/Form/QuestionType/QuestionTypeInterface.php, src/Form/QuestionType/QuestionTypeRadio.php, templates/pages/admin/form/form_editor.html.twig, tests/units/Glpi/Form/AnswersSet.php, tests/units/Glpi/Form/Form.php, tests/units/Glpi/Form/QuestionType/QuestionTypesManager.php, tests/units/Glpi/Form/Renderer/FormRenderer.php
Added `Radio` and `Checkbox` categories and related sub-question type : `Radio` and `Checkbox`
=> feat(forms): Adding radio and checkbox categories and related sub question type

src/Manufacturer.php, src/RegisteredID.php, templates/dropdown_form.html.twig
HTML in labels is no longer supported. This PR moves the button for adding another ID to the field itself in the same way that was done for devices in #17027.
=> Fix manufacturer registered ids field label

src/RichText/RichText.php, tests/units/Glpi/RichText/RichText.php
Since migration from `htmlawed` to `symfony/html-sanitizer`, user mentions were not refreshed properly on display.
=> Fix user mentions handling in rich text sanitizer

src/Asset/Asset_PeripheralAsset.php, src/CommonDBRelation.php
- Use sanitized translation functions for text going to `addMessageAfterRedirect` as this method could be used to display HTML content too.
- Prefer `::class` over `getType()`
- PHPDoc fixes
- Migrate connections UI to Twig
=> Custom Asset Twig/Sanitization

src/Inventory/Asset/InventoryAsset.php, src/Inventory/Asset/MainAsset.php, src/RuleAsset.php, tests/functional/Glpi/Inventory/Inventory.php
| Fixed tickets | !32435
Add new options in rules to manage user reconciliation.
=> User inventory rule

src/Asset/Asset_PeripheralAsset.php
+ inversion of ```name``` and ```itemtype``` columns
=> Feat(ui): display icons in peripheral list for an item

src/Html.php
| Fixed tickets | !32846
When copying text with layout (colors, size, bold, etc.). Depending on the browser, not everything was included.
For example, when copying from MS Word to GLPI, the color was pasted in Firefox, but not in Chrome.
=> fix(richtext): text color pasting

src/Api/HL/Controller/ReportController.php, src/Api/HL/Doc/Route.php, src/Search/Output/Spreadsheet.php, src/Stat.php
Requires #17010.
Unlike the different export formats enabled by the ResultFormatterMiddleware, these endpoints don't export the API response as a different format. Instead, it uses the exact same export logic as the web UI but returns the file content as the response body with the possible PDF, XLSX, CSV and ODS formats. These endpoints always export all results and the PDF orientation is always landscape.
Users may utilize these endpoints to get reports on a schedule.
=> [HLAPI] Allow exporting ITIL stats to pdf, csv, xlsx, and ods

ajax/form/form_tags.php, css/includes/components/_richtext.scss, js/RichText/FormTags.js, src/Form/Destination/CommonITILField/ContentField.php, src/Html.php, src/RichText/RichText.php, templates/components/form/basic_inputs_macros.html.twig, tests/cypress/e2e/form_tags.cy.js, tests/units/Glpi/RichText/RichText.php
Minimum code to implements form tags.
Form tags are "variables" that will be interpreted when a ticket is created.
It will thus mainly be used to insert the form answers into the created ticket description.
I've chosen the `#` prefix to trigger autocomplete as it is close to the format that was used by formcreator (`##TAG##`).
No real tags are supplied for now, real content will be provided by the next iterations (questions, answers, ...).
=> Add basic support for form tags

inc/define.php, src/CommonDBTM.php, templates/components/form/header_content.html.twig
Since https://github.com/glpi-project/glpi/pull/11968
An error occurs when trying to display an asset (assigned to the root entity and recursively) from a sub-entity
=> Fix(Core): fix TWIG template error

inc/db.function.php, src/Config.php, src/DbUtils.php, src/Dropdown.php, src/Profile.php, tests/cypress/e2e/general_config.cy.js, tests/cypress/support/commands.js, tests/functional/Glpi/Asset/AssetDefinitionManager.php
When a multiple-select dropdown has no options selected, no form data is sent to GLPI so that field is ignored. This made it impossible to handle removing all selections from a dropdown unless the missing field was treated specially as if it were an empty selection. That special handling is not correct though as partial updates via the API(s) are possible and failing to specify a multiselect field in an API update request should not delete the value.
The fix adds a hidden input with the same name just before the select element in the DOM. If the browser decides to send the data for the select, the hidden input is ignored. …
=> Fix missing form data when multi-select empty

CHANGELOG.md, src/Rule.php, src/RuleCollection.php, src/RuleDictionnarySoftware.php, tests/functional/Rule.php
Based on #17029. Twig UI migrations focused on the rules list. There will be at least one other PR for rule UI.
=> More Rules Twig UI

js/RichText/FormTags.js, src/Form/Destination/CommonITILField/ContentField.php, src/Form/Tag/FormTagsManager.php, src/Form/Tag/Tag.php, src/RichText/RichText.php, tests/cypress/e2e/form_tags.cy.js, tests/units/Glpi/Form/Destination/FormDestinationTicket.php, tests/units/Glpi/Form/Tag/FormTagsManager.php, tests/units/Glpi/Form/Tag/Tag.php, tests/units/Glpi/RichText/RichText.php
* Add a new `FormTagManager` class that will serve as a facade for tag related operations.
* A value can now be defined for a tag, it will be directly inserted into the content after the form is submitted (see exemple at the end)
* Moved tag html generation to the backend. This is better for tests as they can access the actual html implementation by calling `(new Tag(xxx))->html` instead of manually generating the `<span ....>` raw content.
This also mean that we are 100% sure that the content used for the tests is the real content that will be rendered on the htmlpage.
---
Tag value exemple, using this form configuration:
Created ticket:
| …
=> Forms: add tag manager class; insert tag content into the generated tickets

CHANGELOG.md, src/Cartridge.php, src/CartridgeItem.php, src/Consumable.php, src/ConsumableItem.php, src/Infocom.php, src/Printer_CartridgeInfo.php, templates/components/datatable.html.twig, templates/components/search/controls.html.twig, templates/pages/assets/cartridge.html.twig, templates/pages/assets/consumable_list.html.twig
Twig UI and cleanup of Cartridge and Consumable code.
=> Cartridge and Consumable Twig UI

templates/components/dropdown/limit.html.twig, templates/components/pager.html.twig, templates/pages/admin/events_list.html.twig
Passing href from pager to limit dropdown was broken because of a non-replaced placeholder.
Passing href to limit directly required manually putting a `?` or `&` at the end of the URL.
=> Fix pager and limit for non-form pages

css/legacy/includes/_styles.scss
| Fixed tickets | !32950
In `Assistance` -> `Problems` and `Notes` tab
If the user's name is too long, this disturbs the content of the note.
Before : 
After :
=> Fix incorrect positioning of note content in problem notes

src/Central.php, src/Dashboard/Dashboard.php, templates/layout/parts/menu.html.twig, templates/pages/setup/general/preferences_setup.html.twig
Add missing icon
Replace all ```ti ti-dashboard``` by ```getIcon()``` function
=> Feat(UI): add missing icon fron Central page

src/Form/Destination/FormDestination.php, templates/pages/admin/form/form_destination.html.twig
The `Delete` and `Update item` actions are now hidden when the user does not have the right to update the form.
With update right :
Without :
=> feat(forms): check update right to show form destination actions

src/Inventory/Asset/NetworkEquipment.php, tests/fixtures/inventories/stacked_switch_name.xml, tests/functional/Glpi/Inventory/Inventory.php
Stacked switches got a name with the "description" (model) field added, all switches the same(!), which gives several issues in managing them, and has apparently no logic.
It seems that this was just a wrong copy-paste from the previous code line. Corrected with _$stack_number  as a commonly used naming scheme.
| Fixed tickets | no ticket
=> Update NetworkEquipment.php - Stacked switch Name with ID

jsconfig.json, templates/pages/admin/form/form_question.html.twig, templates/pages/admin/form/form_toolbar.html.twig, tests/cypress/e2e/form/form_editor.cy.js, tests/cypress/support/commands/form.d.ts, tests/cypress/support/commands/form.js
Test the creation of questions from the form editor user interface.
I've added some common boilerplate code related to form creation into new cypress commands (will retrofit existing tests later).
These commands have their own file to avoid polluting the general `command.js` file.
=> Form: add e2e tests handling question creation

src/CronTask.php, src/Form/QuestionType/AbstractQuestionTypeSelectable.php, src/Form/QuestionType/AbstractQuestionTypeShortAnswer.php, src/Form/QuestionType/QuestionTypeDateTime.php, src/KnowbaseItem.php, templates/components/form/basic_inputs_macros.html.twig, templates/components/form/fields_macros.html.twig, templates/components/itilobject/itilsatisfaction.html.twig, templates/components/search/controls.html.twig, templates/components/search/query_builder/search_option_value.html.twig, templates/pages/admin/assetdefinition/capacities.html.twig, templates/pages/admin/form/form_editor.html.twig, templates/pages/admin/form/form_question.html.twig, templates/pages/admin/form/form_section.html.twig, templates/pages/setup/general/performance.html.twig, templates/pages/setup/general/systeminfo_table.html.twig, templates/pages/tools/savedsearch/save_button.html.twig, templates/stencil/editor.html.twig, templates/stencil/parts/zones.html.twig
I asked myself if it was mandatory to use the specific `html_attr` strategy to escape values that were printed in HTML attributes. It seems that only HTML special chars (`"`, `>` and `<`) must be encoded into HTML entities to protect the value as long as the attribute value is surrounded by quotes. Encoding special chars is the default Twig strategy, so we can safely remove the specific `|e('html_attr')` escaping filter.
=> Remove useless specific escaping

css/includes/components/_asset-form.scss
=> Fix asset form header alignment on small screens

.composer-require-checker.config.json, CHANGELOG.md, bin/console, composer.json, front/cron.php
A source of far too many forum posts, issue reports, etc where people end up with broken GLPI file permissions.
The most common case is when an administrator sets up a cron job for the GLPI automatic actions and simply adds the entry to the system's crontab rather than the web server user's crontab (or specifying the web server user in the system crontab entry).
This PR attempts to detect when the cron script and the GLPI CLI are run as root. If the root user is detected, execution will stop before any file ownership can be ruined.
This uses the `posix` extension which is included with PHP and enabled by default (except on …
=> Detect and block Cron and CLI running as Root user

templates/pages/admin/log_viewer.html.twig
=> Fix(LogViewer): Fix CSS

ajax/common.tabs.php
| Fixed tickets | https://github.com/glpi-project/glpi/pull/17156#issuecomment-2122824070
`full_page_tab` parameter is not anymore used. The corresponding code can be removed.
=> Drop dead code related to `full_page_tab` handling

js/RichText/FormTags.js, src/Form/Destination/AbstractCommonITILFormDestination.php, src/Form/Destination/CommonITILField/ContentField.php, src/Form/Destination/CommonITILField/TitleField.php, src/Form/Destination/ConfigFieldInterface.php, src/Form/Destination/FormDestinationInterface.php, src/Form/Tag/AnswerTagProvider.php, src/Form/Tag/FormTagsManager.php, src/Form/Tag/QuestionTagProvider.php, src/Form/Tag/Tag.php, src/Form/Tag/TagProviderInterface.php, src/RichText/RichText.php, templates/components/form/basic_inputs_macros.html.twig, templates/pages/admin/form/form_destination.html.twig, templates/pages/admin/form/form_destination_commonitil_config.html.twig, tests/cypress/e2e/form_tags.cy.js, tests/src/Form/Destination/AbstractFormDestinationType.php, tests/src/FormTesterTrait.php, tests/units/Glpi/Form/Destination/FormDestinationTicket.php, tests/units/Glpi/Form/Tag/AnswerTagProvider.php, tests/units/Glpi/Form/Tag/FormTagsManager.php, tests/units/Glpi/Form/Tag/QuestionTagProvider.php, tests/units/Glpi/Form/Tag/Tag.php, tests/units/Glpi/RichText/RichText.php
Add real providers, allowing tags to reuse questions labels and the form's answers.
=> Add form tag providers

src/CommonITILTask.php, src/Document_Item.php, src/ITILFollowup.php, src/Ticket.php, tests/functional/Ticket.php
| Fixed tickets | !32514
When merging a **C**hild **ticket C** into a **P**arent **ticket P**, the following issues were observed:
1. **Merging Process:**
- The content of **ticket C** is successfully added to **ticket P**.
- The status of **ticket C** is set to "deleted".
2. **Post-Merge Responses:**
- Responses posted to **ticket C** (now merged and deleted) are correctly added and visible.
- Responses sent to **ticket C** are not added to **ticket P**. Instead, they remain visible in **ticket C**, which is no longer tracked due to its deleted status. However, they should be present in the parent ticket.
To solve this problem, a post-add …
=> Fix merged ticket responses not being added to parent ticket

templates/layout/parts/context_links.html.twig
Display vertical divider only when contextual button are displayed
Before : 
After : 
=> Fix(Breadcrumb): Display vertical divider only if needed

templates/pages/admin/form/form_toolbar.html.twig
While transforming some invalid `label` tags into `button`, I forgot the default button type is `submit` which cause form editor changes to be accidentally saved when clicking on these buttons.
=> Add correct type to form toolbar buttons

src/Plugin/Hooks.php
Missing constant in Hooks class
=> fix missing hook constant CONFIG_PAGE

src/Ajax.php
Opening an item tab using the middle click lead to a broken "raw" page:
This is because our tabs `href` properties are the ajax endpoinst that will fetch the data.
So, opening the link in a new tab will only fetch the tab content and nothing else.
This is easy to fix as we have no requirement to use this url directly in the `href` property.
We can use a valid `href` and move the ajax endpoints URL into dedicated data attributes.
2E tests can't be added to validate this as cypress does not support multiple browsers tabs.
I'm doing this changes in main because the `href` property may possibly be parsed by some plugins which would break with this change.
If you think this possible issue is too "far fetched", I can move the PR to target the bugfix branch instead.
| …
=> Allow tab content to be opened using middle click

.github/workflows/ci.yml
As discussed in our weekly meeting.
=> Separate E2E tests into a dedicated CI env.

templates/pages/admin/inventory/agent.html.twig
Abandon ```generic_show_form.html.twig``` to allow read only on native fields such as ```name``` or ```agenttypes_id```.
Before : 
After : 
=> Fix(Agent): fix CSS and readonly input

src/Contract.php
| Fixed tickets | https://github.com/glpi-project/glpi/issues/17169
Fix the first 3 links to contracts in the global view by using the end date instead of the expiry date:
=> fix(contract): Global View links

ajax/form/form_tags.php, js/RichText/FormTags.js, src/Form/Tag/AnswerTagProvider.php, src/Form/Tag/FormTagsManager.php, tests/cypress/e2e/form_tags.cy.js, tests/units/Glpi/Form/Tag/FormTagsManager.php
Allow form tags to be filtered according to what the user typed.
Exemples:
=> Filter forms tags

src/Search.php, tests/functional/ITILFollowup.php
ITILFollowups do not have any entities restrictions in their `addDefaultWhere` method.
This mean that any "listing" using the `addDefaultWhere` method may return data from inaccessible entities (for exemple: an API request on `GET /ITIlFollowup`).
I suspect this issue happens on all `CommonDBChild` and `CommonDBRelation` items.
I am planning on fixing it for all timeline related items (in separate PR) as they impact directly the unread messages plugin.
I do not plan to fix all the others types as it would require a lot more work and the need to maintain new itemtypes in the future which is not acceptable.
It would be better to fix this everywhere with some mutual code but it doesn't seem possible without an important rewrite of the `addDefaultWhere` and `addDefaultJoin` methods that can't …
=> Fix followups entities restriction

src/Form/Tag/FormTagsManager.php, tests/units/Glpi/Form/Tag/FormTagsManager.php
Small followup to #17175, we do not want the search to be case sensitive.
=> Make tags filtering case insensitive

src/Form/Tag/AnswerTagProvider.php, src/Form/Tag/QuestionTagProvider.php, src/Form/Tag/Tag.php, src/RichText/RichText.php, tests/units/Glpi/Form/Tag/AnswerTagProvider.php, tests/units/Glpi/Form/Tag/FormTagsManager.php, tests/units/Glpi/Form/Tag/QuestionTagProvider.php, tests/units/Glpi/Form/Tag/Tag.php, tests/units/Glpi/RichText/RichText.php
Add accent colors to help distinguish different types of tags.
=> Add accent colors to form tags

src/Ticket.php
| Fixed tickets | !33018
In the personal view, the number of tickets being processed differs from the number of results that appear when you click on the filter.
In this example we are supposed to have 6 tickets in process
But in reality, the filter only takes into account tickets in "Progressing (assigned)" status. However, some users apply rules that assign "New" status to certain tickets, even if technicians are assigned to them. In our case, therefore, we only have 4 tickets in the results.
One possibility is to modify the filter criteria in this way:
=> Fix ticket processing criterias in the personal view

inc/config.php, index.php, install/install.php, install/update.php, src/Auth.php, src/Session.php, src/System/Requirement/SessionsSecurityConfiguration.php, templates/layout/page_card_notlogged.html.twig, templates/pages/https_only.html.twig, tests/units/Glpi/System/Requirement/SessionsSecurityConfiguration.php
When the `session.cookie_secure` is configured to `true` bug GLPI is accessed on HTTP context, the session is created without any warning, but the corresponding cookie is not sent to the response. It triggers, for instance, the following behaviours:
- When an administrator accesses to the install page, the `Select your language` step is displayed. When the administrator submit it, nothing happens and the same step is displayed again.
- When a user access GLPI, the login form is correctly displayed. However, when the user submits it, the following error is displayed: `The action you have requested is not allowed.`.
Since we …
=> Redirect user to HTTPS context when session is not allowed on HTTP

CHANGELOG.md, front/authldap.form.php, js/common.js, js/src/vue/Kanban/Column.vue, src/AuthLDAP.php, src/User.php, templates/pages/setup/ldap/adv_info.html.twig, templates/pages/setup/ldap/filter.html.twig, templates/pages/setup/ldap/form.html.twig, templates/pages/setup/ldap/group_config.html.twig
See changelog for intended changes/removals/fixes.
=> Auth Twig UI (Part 1)

CHANGELOG.md, src/NotificationAjaxSetting.php, templates/components/form/basic_inputs_macros.html.twig, templates/pages/assistance/planning/external_event.html.twig, templates/pages/setup/general/preferences_setup.html.twig, templates/pages/setup/ldap/form.html.twig, templates/pages/setup/notification/ajax_setting.html.twig
We do not really use this feature and it is prone to security issues.
I had to make the following changes:
- In the `Enable notifications` field helper, I replaced usage of `<ul>`/`</li>` by the `•`. The rendering is pretty similar. I do not know it it may be a problem for the accessibility of the text. We could eventually remove the bullet points.
- In the `Validity period of notifications` (for AJAX notification), I replaced a link to a crontask form by the name of the crontask. Anyway, the link was nearly impossible to access, as the tooltip dissapear as long as you loose the focus on the tooltip icon (this happens when …
=> Remove support of HTML code in fields helpers

src/Group_User.php
| Fixed tickets | !33023
In a group, an admin cannot add users to entities to which he has no access (which is normal), but he could delete them. There was no user entity check on massive actions.
=> fix(group): delete users

src/CommonTreeDropdown.php, tests/functional/Glpi/Inventory/Inventory.php
| Fixed tickets | https://github.com/glpi-project/glpi-inventory-plugin/issues/513 (and maybe #17106)
=> Fix import location hierarchy

src/CommonDBConnexity.php
| Fixed tickets | !33193
When the item cannot be deleted, with the `is_deleted` column, the test was always false, making the update impossible. Case with `infocom`.
=> fix: add maybeDeleted to check

api.php, apirest.php, caldav.php, inc/config.php, inc/define.php, inc/includes.php, index.php
These declarations are currently optional because these scripts are included/executed in the global scope, but it may change in a near future, for instance in #17213.
Adding the `global` declaration for these global variables should anyway have no impact on the code execution, and may help IDE / code analysis tools to detect issues.
=> Add missing global declarations

tests/functional/Config.php
Everytime we must change the list of our composer dependencies, if we forgot to update the `Config::getLibraries()` return value, the tests fails with an output that does not really help. For instance:
```
=> tests\units\Config::testGetLibraries():
In file /var/www/glpi/tests/functional/Config.php on line 196, array() failed: array(62) is not identical to array(63)
-Expected
+Actual
@@ -1 +1 @@
-array(63) {
+array(62) {
@@ -93 +93 @@
-  string(24) "symfony/framework-bundle"
+  string(22) "symfony/html-sanitizer"
@@ -95 +95 @@
-  string(22) "symfony/html-sanitizer"
+  string(23) "symfony/http-foundation"
@@ -97 +97 @@
- …
```
=> Enhance dependencies checks result

src/SoftwareLicense.php
| Fixed tickets | !33225
Creation date search option was missing from Software Licenses.
=> Add missing search option (Creation date) for Software Licenses

composer.json, composer.lock
Dev dependencies are updated by dependabot only on the 10.0/bugfixes branch. Some of them can be upgraded to newer versions due on the main branch due to requirements that are not fulfilled on the 10.0/bugfixes branch.
=> Upgrade PHP dev dependencies

inc/db.function.php, src/CommonDropdown.php, src/DBConnection.php, src/DbUtils.php, src/DropdownTranslation.php, src/FieldUnicity.php, src/Fieldblacklist.php, src/IPNetwork.php, src/Infocom.php, src/KnowbaseItemTranslation.php, src/PlanningRecall.php, src/ProjectTask.php, src/ReminderTranslation.php, src/ReservationItem.php, src/RuleCollection.php, src/SavedSearch_Alert.php, src/Session.php, src/Socket.php, src/SoftwareVersion.php
When I tried to update some plugins to phpstan 5, I got errors related to incorrect return types and parameters.
=> Fix return and param type

.github/actions/docker-compose-app.yml, .github/actions/docker-compose-services.yml
Since we use the compose utility directly embed in docker (see #16884), we use the V2 version of the compose utility (see https://docs.docker.com/compose/intro/history/#compose-file-format-versioning). The `version` property of compose files is useless in this version. Moreover, in recent versions, it triggers warnings each time the `docker compose` command is used, and it pollutes logs.
Example of logs pollution I get when executing the test suite on my machine:
=> Remove obsolete docker compose file version

src/Toolbox.php
| Fixed tickets | #17024
Since #15772, in the installation step, the db config file is included to check whether it contains an empty config file. See
https://github.com/glpi-project/glpi/blob/039d7305a140013811233a934e33f6d62830d4d7/install/install.php#L540-L543
Side effect of this is that, when the `Toolbox::createSchema()` method is call after the new config is store in the file, the `include_once` has no effect. As the `include_once` was here only to ensure that the `DB` class is not declared twice (this would result in a fatal error), we can replace the `once` logic by a check on `DB` class existence.
To reproduce the issue:
- …
=> Fix install process when it starts with an empty config file

front/item_cluster.form.php, src/Item_Cluster.php
Change the form for Item_Cluster items to be inline in the cluster items list tab rather than a separate page.
=> Move Item_Cluster form inline with list

templates/pages/admin/form/form_comment.html.twig, templates/pages/admin/form/form_question.html.twig
Currently, the duplicate action button for a comment or question is always visible, even when the question or comment is out of focus.
This PR hides the button when the element is not in focus.
=> feat: hide duplicate action when comment and question is not focused

CHANGELOG.md, ajax/dashboard.php, api.php, apirest.php, src/CronTask.php, src/GLPI.php, src/Glpi/Application/ErrorHandler.php, src/Glpi/Console/Application.php, src/Glpi/ContentTemplates/TemplateManager.php, src/Glpi/Dashboard/Grid.php, src/MailCollector.php, src/Toolbox.php, tests/GLPITestCase.php, tests/units/Glpi/Application/ErrorHandler.php
| Fixed tickets | see #15109 
1) On `development` environment, error messages will now be output even when debug mode is not active. Purpose of this change is to ensure that developer see these errors, even when he has not the debug mode active (when using CLI, API, simplified interface, ...).
2) On `production` environment, debug and info messages will no longer be output in debug mode. These messages are not meant to be used by end users. For instance, it will prevent end users to consider usage of deprecated function/methods as bugs.
=> Adapt error output to environment

tests/fixtures/inventories/softwares/02-test_software_with_special_chars_with_version.json, tests/fixtures/inventories/softwares/03-test_software_with_special_chars_and_without_version.json, tests/fixtures/inventories/softwares/04-test_software_with_special_chars_and_with_version_and_os.json, tests/fixtures/inventories/softwares/05-test_software_with_special_chars_and_without_version_and_os.json
Two issues here:
* Tests always look for a computer named "pc_test", see https://github.com/glpi-project/glpi/blob/10.0/bugfixes/tests/functional/Glpi/Inventory/Assets/Software.php#L799
* Test expect one software (see https://github.com/glpi-project/glpi/blob/10.0/bugfixes/tests/functional/Glpi/Inventory/Assets/Software.php#L832) but if there is an operating system, we got two.
=> Fix software tests fixtures

bin/console, src/Glpi/Console/Application.php, tests/README.md, tests/bootstrap.php
Since #16373, the GLPI installation will add additional data when `GLPI_ENVIRONMENT_TYPE == 'testing'`. It means that executing `bin/console db:update --config-dir=./tests/config` is not anymore populating the database with the data expected in the test suite. The correct way to do is now to rely on the `GLPI_ENVIRONMENT_TYPE` env variable, for instance by executing `GLPI_ENVIRONMENT_TYPE=testing bin/console db:update`.
The current PR add a `--env` option to be able to define the `GLPI_ENVIRONMENT_TYPE` environment variable.
=> Add support of the `--env` option in the console

templates/pages/setup/webhook/webhook_security.html.twig
Before this fix, it was impossible to click on the "Client Secret" field in the Security tab of a Webhook.
=> fix(webhook): onfocus for clientsecret field

src/RuleCollection.php
| Fixed tickets | !33283
In the list of rules, there is the right number of corresponding rules. 
if I click on the form for one of my rules, the correct number of rules is displayed on the page counter (1/2)
but if I return to the previous page and go back to the rules as before, the page counter doubles.
=> Fix duplicated items for rules pages counter

src/Html.php
#17074 had only fixed clearing multi-select dropdowns when they were created by `Dropdown::showFromArray`. Dropdowns for an itemtype were being created by `Html::select` which didn't have the fix added.
=> Fix more missing empty multiselect dropdown values

src/DbUtils.php, src/Html.php
1. Remove some usages of `Session::DEBUG_MODE` that are not really necessary.
2. Replace some other usages by a check on `GLPI_ENVIRONMENT_TYPE`.
=> Clean some usages of the `Session::DEBUG_MODE`

CHANGELOG.md, src/Glpi/Api/API.php, src/Glpi/Api/APIRest.php
This piece of code is related to the usage of a `?debug=2` parameter in the Rest API. It is not documented, and when trying to use it, it fails with the following error:
```
glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: count(): Argument #1 ($value) must be of type Countable|array, Glpi\Api\APIRest given in /var/www/glpi/src/Html.php at line 3959
Backtrace :
src/Glpi/Api/API.php:2388                          Html::printCleanArray()
src/Glpi/Api/APIRest.php:145                       Glpi\Api\API->showDebug()
apirest.php:67                                     Glpi\Api\APIRest->call()
public/index.php:83 …
```
=> Remove buggy undocumented `debug=2` support in Rest API

templates/components/itilobject/timeline/form_solution.html.twig
| Fixed tickets | !33306
The button linked to the knowledge base solution was visible in the bulk actions form, whereas it is impossible to add a knowledge base solution to several tickets simultaneously. (This button has now been removed from the massive actions form on the tickets page).
**Before**
**After**
=> Fix visibility of Knowbase button (Search solution)

src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php, src/Glpi/Form/Destination/CommonITILField/ContentField.php, src/Glpi/Form/Destination/CommonITILField/TitleField.php, src/Glpi/Form/Destination/ConfigFieldInterface.php, tests/functional/Glpi/Form/Destination/CommonITILField/ContentField.php, tests/functional/Glpi/Form/Destination/CommonITILField/TitleField.php, tests/functional/Glpi/Form/Destination/FormDestinationTicket.php, tests/src/Form/Destination/AbstractFormDestinationType.php
There is a stupid value wrapping using arrays which make destination config looks like this:
```php
[
'title' => ['value' => 'my ticket title'],
'content' => ['value' => 'my ticket content'],
]
```
This was built that way to support more complex values but I am not sure it will ever be needed.
With that in mind, it make sense to simplify it like this:
```php
[
'title' => 'my ticket title',
'content' => 'my ticket content',
]
```
| Bug fix?      |  no
=> Simplify the way form destinations fields are handled

src/Glpi/Search/Output/HTMLSearchOutput.php, src/Glpi/Search/Output/MapSearchOutput.php, src/Glpi/Search/Provider/SQLProvider.php, templates/components/search/controls.html.twig, templates/components/search/display_data.html.twig, templates/components/search/table.html.twig
Currently when a SQL error occurs during a search, the SQL error is output to the page even when not in debug mode/dev environment. In this case, the controls are also completely missing.
With this PR, the SQL error is hidden unless in debug mode. It also lets the controls be displayed so that the criteria or displayed columns can be adjusted.
=> Improve handling of search errors

src/Ajax.php, src/Html.php
1. The dropdown `on_change` and `placeholder` options were encoded to JSON and then surrounded by simple quotes, resulting in unexpected quotes surrounding, e.g. `'"reloadTab()"'` instead of `"reloadTab()"`.
2. The `reloadTab()` logic was broken since #17156.
=> Fix notification template translation preview

CHANGELOG.md, src/NotificationTemplateTranslation.php, templates/pages/setup/notification/translation_debug.html.twig
The notification template translation preview is currently only available when the debug mode is active, inside the debug tab. I think it make sense to move it in a dedicated tab that can be accessed to any user that has the right to display the corresponding `NotificationTemplateTranslation` item form.
While testing, I figured out that the preview is actually not really relevant on some cases. Indeed, to have a relevant preview, some events requires specific data added by specific pieces of code, for instance: https://github.com/glpi-project/glpi/blob/be75f36dead7cad36a707657ef8d80696c8db6b1/src/NotificationTargetContract. …
=> Make the notification template preview available outside debug mode

src/Rule.php, src/RuleLocation.php, tests/functional/RuleLocation.php
When testing a location rule 
If action concern ```regex_result``` assignation
GLPI import ```location``` even if we are in rule test context
This PR prevent this without impacting the test result
NB : ```importExternal``` is only called from ```RuleLocation``` (other rule are free)
| Fixed tickets | !33250
=> Fix(Rule): do not import locations in preview mode

CHANGELOG.md, src/User.php
User LDAP information are only available when the debug mode is active as they are located in the debug tab.
I propose to move them into a dedicated tab, and to give access to it as long as the current user has the `Read user authentication, synchronization method and 2FA` right.
I just rework a bit the view to have an acceptable rendering, but I guess some more improvements could be done. I have no time for this, and I consider it is still better than the previous rendering and can still be merged.
Before:
After:
=> Show user LDAP information on a dedicated tab

src/NotificationTarget.php, tests/functional/NotificationEventAjax.php, tests/functional/NotificationTarget.php, tests/functional/NotificationTargetSavedSearch_Alert.php
| Fixed tickets | !33345
The link sent in a notification to a user of type "GLPI internal database" contains the parameter noAUTO=1 which stops automatic authentication, but this does not seem to be relevant.
=> fix(notification): noAUTO=1

src/Glpi/Agent/Communication/AbstractRequest.php, src/Glpi/Agent/Communication/Headers/Common.php, src/Glpi/Api/HL/Controller/CoreController.php, src/Glpi/Inventory/Conf.php, src/Glpi/OAuth/AccessTokenRepository.php, tests/functional/Glpi/Api/HL/Controller/CoreController.php
Adds ability to require OAuth Client Credentials authentication between agent and GLPI for inventory submission.
I guess there is already basic authentication support, but I can't see how that is possible (where is it handled?).
This was tested only so far as to check if I get an error regarding the missing token or an error regarding the XML.Needs changes on the agent side.
The agent will need to request a token through the new API using the client_credentials grant type while requesting the "inventory" scope (/api.php/token), and then send an Authorization Bearer header with the auth token when submitting inventory.
=> Support client credentials oauth for inventory

src/Glpi/Api/HL/Search.php, tests/functional/Glpi/Api/HL/Controller/AssetController.php
When creating an item through the API, the current entity (determined by GLPI-Entity header) should be used if the entity ID is not explicitly specified in the parameters.
=> [HLAPI] Use active entity as default during item creation

inc/based_config.php
As documented in https://www.php.net/manual/en/function.date-default-timezone-set.php:
> Instead of using this function to set the default timezone in your script, you can also use the INI setting [date.timezone](https://www.php.net/manual/en/datetime.configuration.php#ini.date.timezone) to set the default timezone.
This hack was made to handle empty values of the `date.timezone` configuration, but since PHP 8.2 (the minimum PHP version for GLPI 11.0), an empty value will emit a warning (see https://www.php.net/manual/en/datetime.configuration.php).
IMHO, due to this warning, administrators will fix their PHP configuration …
=> Remove default timezone hack

CHANGELOG.md, inc/based_config.php
I did not find any reference to this variable in any of the plugins that are listed on the plugin catalog.
=> Remove unused `$CFG_GLPI_PLUGINS` global variable

js/impact.js
It will be interesting to use only on object to create a compound like that for example :
=> Impact : Permit use only one asset to create a compound

tests/InventoryTestCase.php, tests/functional/Glpi/Inventory/Inventory.php
`UnifiedArchive::archiveFiles()` is deprecated.
=> fix php83/unifiedarchive

CHANGELOG.md, ajax/marketplace.php, inc/includes.php, js/marketplace.js, src/Glpi/Marketplace/Controller.php, src/Plugin.php
In #8019, we introduced a hack to prevent an issue when trying to download, from the marketplace, a new version of an active plugin. The idea was to prevent this plugin from being loaded, to prevent a `Cannot redeclare plugin_version_XXX()` error that was caused by a double loading of the `setup.php` file (a first time before the code source replacement, and a second time after the download process).
This logic was a hack, and it is a pain to make it compatible with a centralized Kernel (job started in #17278). I propose to split the operation into 2 requests:
- the first request suspends the plugin execution;
- the second …
=> Remove the `$PLUGINS_EXCLUDED` global variable hack

src/CronTaskLog.php
Missing right name was making the read permission check in the legacy API fail. I made it use the same right name as CronTask.
=> Fix CronTaskLog access in legacy API

src/AllAssets.php, src/Html.php
| Fixed tickets | !33468
The Advenced dashboard plugin uses a `getIcon()` function on certain classes for saved searches, for example. However, for a saved search that concerns all assets, we need the `getIcon()` function of the AllAssets class, but it doesn't exist.
=> Add missing 'getIcon()' function to the AllAssets class

templates/components/form/fields_macros.html.twig, templates/components/itilobject/actors/field.html.twig, templates/components/itilobject/actors/main.html.twig, tests/cypress/e2e/selfservice_tickets.cy.js
Allow arbitrary HTML content to be inserted after inputs labels in our forms (only for the "vertical field" layout).
For example:
```twig
{% set content %}
<div class='ms-auto'>test</div>
{% endset %}
{{ fields.textField(
input_name,
value,
label,
{
insert_content_after_label: content
},
) }}
```
For extra context, this is needed for a new helpdesk forms related feature that I'm working on this week.
=> Allow content to be inserted after inputs labels

CHANGELOG.md, inc/based_config.php, src/Plugin.php
This variable is not used by GLPI.
I did not find any usage in plugins that would be affected by this removal. Indeed, the following snippets will still work:
```php
// a simple declaration
global $LANG;
$LANG['pluginkey']['xxx'] = 'value';
```
```php
// will anyway trigger a warning if the corresponding entry is not defined
global $LANG
echo $LANG['pluginkey']['xxx'];
```
```php
// a safe usage
global $LANG;
if (isset($LANG['genericobject'][$class][0])) {
return $LANG['genericobject'][$class][0];
}
```
=> Remove unused `$LANG` global variable

.github/workflows/coverage-schedule.yml, .github/workflows/coverage.yml
The code coverage workflow is scheduled from the default branch (10.0/bugfixes), but executed with the code from the `main` branch. It causes issues, as the workflow configuration can be incompatible with the target branch.
The current PR will fix this, as iit will permit to use the workflow configuration of the tested branch.
=> Ensure the coverage workflow uses the config from its own branch

dependency_injection/legacyConfigProviders.php, dependency_injection/services.php, src/Glpi/Http/Firewall.php, src/Glpi/Http/FirewallInterface.php, src/Glpi/Http/FirewallListener.php, src/Glpi/Kernel/Kernel.php, tests/functional/Glpi/Http/Firewall.php
1) Fixes the following error that appears only when the Kernel is instanciated with the `debug:true` parameter:
```
The "Glpi\Http\Firewall" service is synthetic, it needs to be set at boot time before it can be used.
```
2) Fixes the hardcoded strategies for legacy URLs that were not correctly applied when GLPI is located behing an Apache alias (e.g. http://host/glpi/index.php). I added some tests for these.
For now, I propose to fallback to `$CFG_GLPI['root_doc']` at runtime when the `$âth_prefix` value is not passed in the construcor. Later, we will improve this part by getting this value directly from a dedicated …
=> Fix firewall service instanciation and fix hardcoded strategies

bin/console, front/cron.php, public/index.php, src/Glpi/Application/ResourcesChecker.php
They were removed in #17278. I put these checks back, moving the code into a testable class. We may add tests later, when `phpunit` will be available in the main branch.
=> Put back dependencies/locales checks on GLPI bootstraping

src/Glpi/Search/Input/QueryBuilder.php, tests/functional/Search.php
In #16607, the search engine was changed to default to using the `id` search option for the default sort rather than whichever option had ID 1 (usually is the ID, but it is the content for followups). There was one place still defaulting to 1 for the sort instead of 0, so it wasn't being automatically determined and the default sort for followups was still the content.
=> Fix default sort search option

ajax/task.php
| Fixed tickets | #0
When use task template without define a users_id_tech, the loaded template blank the users_id_tech field.
=> Fix Default Tech With Task Template

src/Glpi/Search/Output/AbstractSearchOutput.php, src/Glpi/Search/Output/HTMLSearchOutput.php, src/Glpi/Search/SearchEngine.php, templates/components/search/criteria_filter.html.twig, templates/components/search/criteria_filter_actions.html.twig, templates/components/search/table.html.twig, tests/cypress/e2e/search/filterable.cy.js, tests/functional/Search.php
(Requested by @orthagh).
Filters on webhook/notifications are hard to manage on big databases due to potential slow search queries that are executed when previewing the filter results.
A quick image to remind you what this feature look like:
The first issue is that saving a filter also update the preview; thus forcing execution of a potential slow query.
Now, the preview is no longer updated when a filter is saved.
It is instead hidden (thus avoiding displaying preview information that may be outdated), if the user want to confirm the results again he is free to manually click the preview button and check the results.
The second issue is that an useless preview search query is executed when the page is loaded.
This was not meant to be this way and is just a side effect of using the search …
=> Improve FilterableTrait performances

install/migrations/update_10.0.15_to_10.0.16/config.php, src/Config.php, src/NotificationMailingSetting.php, tests/functional/Config.php
| Fixed tickets | !33354
SMTP logs have been moved to a dedicated tab on the e-mail notification side (as this is where SMTP-related options can be set). This avoids filling the general conf logs.
=> (Fix) Move smtp logs in NotificationMailingSetting

src/CommonITILObject.php, src/CommonITILTask.php, src/Glpi/Features/ParentStatus.php, tests/functional/TicketTask.php
| Fixed tickets | !32381
When a task is de-scheduled, the ticket status remains In progress (Scheduled) instead of being changed back to In progress (Assigned).
=> Fix update ticket status when ticket task is de-scheduled

src/Cluster.php, src/CommonDBTM.php, templates/generic_show_form.html.twig, tests/functional/Cluster.php
| Fixed tickets | !33477
In Computer and NetworkDevice, we can't see that it's part of a cluster when registering it as a tab (like all the other elements in "Management" such as DB instances, Appliances etc.).
**Before**
**After**
=> Fix cluster item tab in Computer & NetworkEquipment page

src/TicketTemplate.php, src/TicketTemplateMandatoryField.php, tests/functional/ITILTemplate.php
Add missing ```type``` field only for ```Ticket template``` 
It is excluded from ```MandatoryField``` because ```type``` has no empty option a default value is necessarily used
| Fixed tickets | !33298
=> Fix(TicketTemplate): add missing 'type' field

.github/workflows/ci.yml
This CI configuration should permit to process all subsequent tests even when a step fails, and still have a global failure when any step fails.
=> Process subsequent tests even on failure

front/central.php, src/Html.php
When dashboard is embedded 
browser tab ```title``` is missing
| Fixed tickets | #33588
=> Fix(Dashbaord): add missing browser tab title when dashboard embedded

apirest.md, src/Api/API.php, tests/web/APIRest.php
| Fixed tickets | !33486
Using the searchText parameter with a non-existent key returns a status of 200 with an empty playload. This should return another status with details of the error.
Request :
Response:
=> Add error status & debug for unknown column with searchText param

js/form_editor_controller.js, templates/pages/admin/form/form_comment.html.twig, templates/pages/admin/form/form_editor.html.twig, templates/pages/admin/form/form_section.html.twig, tests/cypress.config.js, tests/cypress/e2e/form/form_preview.cy.js
This PR solves the problem of the form preview not correctly reflecting the current state of the form in the editor due to unsaved changes. To achieve this, the preview button now saves the form before displaying it, and its text dynamically changes to “Save and Preview” if unsaved changes are detected.
=> feat(forms): add unsaved changes tracking and save-and-preview functionality to form editor

src/Glpi/Search/CriteriaFilter.php
| Fixed tickets | !33503
Applies on all Filter tabs (currently notifications and webhooks)
=> count criteria on filter tab

src/Ticket.php
| Fixed tickets | #17422
The addition of validations to the ticket common criteria made the status column ambiguous for the new ticket list which is shown when the "Show new tickets on the home page" preference is enabled.
=> Fix ambiguous status column in query

src/Session.php
| Fixed tickets | #17353
Ensures the impersonate button doesn't show in any user form, including your own, when you don't have permission to impersonate users.
=> Hide impersonate button for self when permission missing

tests/cypress.config.js, tests/cypress/e2e/form/form_preview.cy.js
Previous PR added a global retries for each failed E2E tests, which I think is not ideal as the "retry" feature is meant to help with external components that may fail (like an external API) and we have none yet.
The small changes I've made seems to be enough to prevent random failure (tests worked 10 times in a row yesterday when before it would fail 50% of the time).
=> Fix flaky tests

js/planning.js
| Fixed tickets | !33543
We create an external event with repetition over 3 days, for example. You end up with 3 elements in the schedule.
If you extend the first element and choose to modify the whole series, everything works fine, but if you extend the 2nd or 3rd, all the previous elements will be deleted.
=> Planning - Fix external events resizing issue

inc/based_config.php, src/Glpi/Application/ResourcesChecker.php
Already done in #17213 . Tests will be added later (with PHPUnit).
The main change is that in staging and production environments, the check will no longer be done, unless there is an existing `.git` directory. On these environments, unless the install is made by a git clone/checkout, there is no reason that these resources are out-of-sync. It will probably improve performances (maybe some ms less).
=> Move the dependencies/locales state check in a dedicated class

src/Glpi/Marketplace/View.php
| Fixed tickets | !32713
Fixed PR : #17148
The modal was only supposed to appear for plugin updates, but in plugin Marketplace mode, the modal would also appear when plugins were installed.
=> Fix modal appear for plugin installation

phpunit/bootstrap.php
Fixes the following warning:
```
Warning: Constant GLPI_ROOT already defined in /var/www/glpi/phpunit/bootstrap.php on line 46
```
`GLPI_ROOT` is defined during the autoload.
`GLPI_SERVERSIDE_URL_ALLOWLIST` default for testing environment is already defined by `Glpi\Application\ConfigurationConstants::computeConstants()`
=> Remove constants definition from PHPUnit bootstrap

js/impact.js
`__()` alredy escapes strings. See other meu options that are using the same logic.
=> Fix impact edit button escaping

CHANGELOG.md, phpunit/functional/AutoloadTest.php, src/Plugin.php, src/autoload/legacy-autoloader.php, tests/fixtures/plugins/tester/inc/mylegacyclass.class.php, tests/fixtures/plugins/tester/src/MyPsr4Class.php, tests/fixtures/plugins/tester/src/PluginTesterMyPseudoPsr4Class.php
Revert changes made in #17233 for autoloading plugins. It introduces redundancy in classpaths that is not necessary.
=> Revert plugins PSR-4 autoloader changes

phpunit/functional/Glpi/Inventory/Assets/VirtualMachine.php, src/Inventory/Asset/VirtualMachine.php
```Default status``` from inventory configuration is not used when GLPI creates/updates the virtual machine computer
if the ```Create computer for virtual machines``` option is enabled.
| Fixed tickets | !33628
=> Fix(Inventory): uses the default status for computers created for VMs

tests/bootstrap.php
`InventoryTestCase.php` has been moved to the `phpunit` folder.
We are still trying to include it from the atoum bootstrap file, which make all tests fails on my end (not sure why it does not trigger any error on the CI ?).
```
Error PHP WARNING in /localhost/glpi/main/tests/bootstrap.php on line 88:
include_once(/localhost/glpi/main/tests/InventoryTestCase.php): Failed to open stream: No such file or directory
```
=> Remove reference to moved file

src/Glpi/Marketplace/View.php, src/Plugin.php, src/RuleCollection.php, templates/components/danger_modal.html.twig
| Fixed tickets | !33542
Rules reset button changed to danger style.
Original neutral modal replaced by danger modal.
Button displayed only if user is on root entity and has configuration modification rights.
=> feat(rules): update reset rules modal and restrict button display

.github/actions/test_tests-phpunit.sh, tests/README.md, tests/run_tests.sh
I added the `phpunit` test suite support to the test runner script.
I also remove references to the obsolete `docker-compose` and change default DB image to `mariadb:10.11` to harmonize default test env with the `main` branch.
=> Add PHPUnit test suite to the test runner script

CHANGELOG.md, src/CommonDevice.php, src/Entity.php
These methods are not used anywhere.
=> Drop `CommonDevice::title()` and `Entity::title()` methods

src/Glpi/Api/HL/Controller/ManagementController.php, tests/functional/Glpi/Api/HL/Controller/ManagementController.php
The ability to download document contents was accidentally removed when the route declarations in the controller were being de-duplicated. This adds it back with better OpenAPI documentation and also adds a test to check the endpoint exists so it doesn't get accidentally removed again. Not sure there is a good way to mock a file upload to actually test the download.
=> [HLAPI] Read document download

src/Migration.php, tests/functional/Migration.php
Fix bug introduced by https://github.com/glpi-project/glpi/pull/16966
Encountered during an update of the `fields` plugin with a migration of `searchoption` IDs
All tables concerning templates use the column `num` instead of `field` (to save the number of the searchoption -> the field).
Ex with `Ticket` (but same for `Change` and `Problem`)
```sql
MariaDB [10bugfixes]> explain glpi_tickettemplatehiddenfields;
+--------------------+------------------+------+-----+---------+----------------+
| Field              | Type             | Null | Key | Default | Extra          |
+--------------------+------------------+------+-----+---------+----------------+
| id                 | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| tickettemplates_id | int(10) unsigned | NO   | MUL | 0 …
```
=> Fix(Migration): fix bad column name

.github/actions/test_tests-phpunit.sh, phpunit/bootstrap.php
"Expected" warnings are still being processed by PHP native handler, which display them.
It is only a visual issue on this branch, but on the `main` branch it makes the tests fails (due to process isolation being enabled, not sure why).
Note that this is the second time I get warnings that do not exist on the CI report (see #17455), there might be something wrong with it (I have confirmed with other developers that they have the same issue so it does not come from my setup).
Also the fallback for GLPI_CONFIG_DIR is wrong, it looks for a config file in the `phpunit` folder instead of `tests/config`.
This later part is a `10.0-bugfixes` only issue, it does not exist on `main`.
| …
=> Fix phpunit warnings and wrong config dir

.webpack.config.js, css/includes/_tabler_compat.scss, install/install.php, install/update.php, lib/bundles/tabler.scss, src/Html.php, templates/layout/page_card_notlogged.html.twig
Currently, we copy the Tabler, Bootstrap, Fontsource, and Tabler icons styles/fonts to `css/lib` and compile the bootstrap/tabler styles using the scssphp compiler. This PR moves this compilation to webpack since we shouldn't be changing anything with it now that it has been separated from the core GLPI styles and palettes.
The only bootstrap scss file still copied to `css/lib` is used by `css/includes/_tabler_compat.scss` to make some Tabler/Bootstrap variables/functions available in the core GLPI styles.
=> Move tabler/bootstrap scss compile to webpack

.github/actions/test_install.sh, .github/actions/test_update-from-9.5.sh, .github/actions/test_update-from-older-version.sh, src/Glpi/Console/Database/AbstractConfigureCommand.php
I found this while testing a new PR last Friday and I wanted to see new installations state.
The comment associated with the empty string value is very strange, it does the inverse of what it said
=> ask for password if no value passed to database:install cli command

ajax/uemailUpdate.php, src/CommonDBTM.php, src/Glpi/Api/HL/Middleware/DebugResponseMiddleware.php, src/Html.php, src/autoload/i18n.php, tests/functional/Glpi/RichText/RichText.php
There is no need to encode more chars than thosse encode by `htmlspecialchars()`.
=> Replace `htmlentities()` usages by `htmlspecialchars()`

CHANGELOG.md, phpunit/functional/HtmlTest.php, src/CommonITILTask.php, src/Dropdown.php, src/Glpi/CalDAV/Traits/VobjectConverterTrait.php, src/Glpi/Marketplace/View.php, src/Glpi/RichText/RichText.php, src/Glpi/Search/Provider/SQLProvider.php, src/Html.php, src/Item_RemoteManagement.php, src/NotificationTemplate.php, src/Plugin.php, src/ProjectTask.php, src/RuleCollection.php, src/UserEmail.php
These methods were initialy made to encode/decode entities in arrays, for instance to encode an array as it was done by the autosanitize logic, or to decode an item fields retrieved from the database.
Deprecating them will force people to either use the `htmlspeciachars` function in the HTML strinc concatenation context, either remove its usage that is no longer necessary due to removal of the autosanitize logic. It is exacly what I had to done in the GLPI code, and it permits me to see that we still had some pieces of code that were manually encoding/escaping stuffs that should not be encoded/escaped anymore.
=> Deprecate `Html::entities_deep()` and `Html::entity_decode_deep()`

src/Rule.php
Remove useless `search` entry
There is simply no search filter here or for the rules in general.
Apply on : 
- ```rule_ldap```
- ```rule_import```
-  ```rule_location```
-  ```rule_ticket```
-  ```rule_softwarecategories```
-  ```rule_mailcollector```
| Fixed tickets | #17500
=> Fix(Rule): remove useless 'search' entry

tests/cypress/support/commands.js
I wanted to run cypress on my local computer, but my system is in French.
So I can't pass the login test.
=> disable language detection from browser when running tests

phpunit.xml.dist, phpunit/GLPITestCase.php, phpunit/functional/AutoloadTest.php, phpunit/functional/Glpi/Inventory/InventoryTest.php, tests/src/autoload/functions.php
Disable tests isolations for PHPUnit.
There was 3 main issues:
* The `loadDataset()` script was outputting text, which meant that all tests that required authentification would fail because of the "headers already sent" state.
Fixed by deleting the output from the script as it is not very useful anyway. It can probably be re-added if the script is wrapped into another PHP process to prevent triggering headers inside the PHPUnit process.
* Shared static values like `Log::$use_queue`.
Inventory code would change this value which would make all assertions on logs by others tests fails.
Fixed by disabling the queue after each tests.
* Shared global config.
Fixed by restoring the default configuration after each tests.
With these change, only two tests needed the specific "run in separate …
=> Disable PHPUnit tests isolation

tests/cypress/e2e/form/form_preview.cy.js
Tests from the `form_preview` suite still fails from time to time for unknown reasons.
I suspect is able to click super fast on the `save` button while the ajax controller code is not yet loaded but I can't prove or fix it at this time.
=> Add retries to a specific flaky test suite

js/form_editor_controller.js
The form editor toolbar is only displayed when the form details, a section or a questions is focused.
This is confusing because if the user click away and break the focus there are no toolbar.
I've fixed this by making the focus always fall back to the forms details.
=> Make sure form editor toolbar is always displayed

phpunit/functional/Glpi/Form/AccessControl/ControlType/AllowListTest.php, phpunit/functional/Glpi/Form/AccessControl/ControlType/DirectAccessTest.php, phpunit/functional/Glpi/Form/AccessControl/FormAccessControlManagerTest.php, src/Glpi/Form/AccessControl/AccessVote.php, src/Glpi/Form/AccessControl/ControlType/AllowList.php, src/Glpi/Form/AccessControl/ControlType/ControlTypeInterface.php, src/Glpi/Form/AccessControl/ControlType/DirectAccess.php, src/Glpi/Form/AccessControl/FormAccessControlManager.php
Discussed lengthy internally with @cedric-anne, replacement for https://github.com/glpi-project/glpi/pull/17117.
TLDR: We redefine the default behavior for our forms access controls policies while allowing future plugins to do things differently. No interface changes and no new configuration options.
----
As a reminder we have two possible policies:
* Allow specific users/groups/profiles
* Allow direct token access
Before this PR, enabling both these criteria would lead to an AND condition (user must have valid token AND be whitelisted) which is not intuitive for users because the names specify "Allow xxx" and not "Restrict xxx".
Thus, this has been changed to an OR condition.
Internally, we use a voting system with 3 choices (grant, abstain, deny).
Our default policies only use the …
=> Form access control votes

front/form/access_control.form.php, phpunit/functional/Glpi/Form/AccessControl/ControlType/AllowListTest.php, phpunit/functional/Glpi/Form/AccessControl/ControlType/DirectAccessTest.php, phpunit/functional/Glpi/Form/AccessControl/FormAccessControlManagerTest.php, phpunit/functional/Glpi/Form/AccessControl/FormAccessControlTest.php, src/Glpi/Form/AccessControl/ControlType/AllowList.php, src/Glpi/Form/AccessControl/ControlType/ControlTypeInterface.php, src/Glpi/Form/AccessControl/ControlType/DirectAccess.php, src/Glpi/Form/AccessControl/FormAccessControl.php, src/Glpi/Form/AccessControl/FormAccessControlManager.php, src/Html.php, templates/pages/admin/form/access_control.html.twig, templates/pages/admin/form/access_control/allow_list.html.twig, templates/pages/admin/form/access_control/direct_access.html.twig, tests/cypress/e2e/form/access_control.cy.js
Common code refactoring extracted from #17117.
This improve:
* Handling access control warnings. Previously computation were done directly in the twig template. Now the FormAccessManager compute the warning by itself and only send their text content to the template.
* Access policies html form. It was previously one form per policies that were sent one by one using ajax. Now merged into a simple form.
=> Code refactoring from #17117

inc/config.php
Using SKIP_UPDATES forces the use mode in the session to normal mode and because the session is saved after that, it is impossible to be in debug mode.
=> Fix SKIP_UPDATES blocking debug mode

src/Html.php
The `scss()` method was used for this CSS instead of the `css()` method. I also reorder the files to ensure that the GLPI theme is loaded after the base CSS.
Fixes the following error:
```
[2024-07-18 14:16:34] glpiphplog.WARNING:   *** PHP User Warning (512): Requested file /var/www/glpi/public/lib/tabler.css.scss does not exists. in /var/www/glpi/src/Html.php at line 6361
Backtrace :
src/Html.php:6361                                  trigger_error()
front/css.php:61                                   Html::compileScss()
...Glpi/Controller/LegacyFileLoadController.php:57 require() …
```
=> Fix loading of tabler CSS by TinyMCE editor

src/ITILFollowup.php
When the requester validates the solution, the comment is added as a follow-up.
But the parent (Ticket) is closed before this action.
This can be seen in the ticket history
This PR reverses the action order
| Fixed tickets | !33833
=> Fix(LifeCycle): ITILObject must be closed after the follow-up has been added (when validates solution)

src/ProjectTask.php
In some cases, the `teammember_list` may be an empty string.
=> Fix handling of project task team members after add

front/locale.php
From 371kb to 326kb for en_GB. Having pretty JSON formatting is just a waste of bytes. There is the option to format the JSON in the browser's developer tools (at least in Chrome) if anyone really needs it.
=> Reduce locale json size

src/Debug/Profile.php
Debug data seems unavailable for dashboard card requests. When troubleshooting the issue, I saw that the shutdown function which saves the debug data would have been registered every time the current debug profile was got. I moved it to the constructor instead of the static getter and that seemed to also resolve the debug data availability issue.
=> Improve availability of debug profiles in ajax requests

templates/components/user/info_card.html.twig
| Fixed tickets | !33820
Backport of #16974, because the login appeared in 9.5 in the tooltip
=> fix(user): restores login in user's tooltip

src/ProjectTaskTemplate.php, templates/dropdown_form.html.twig
| Fixed tickets | !33651
In some forms, the rich text editor for descriptions is limited in size by the other inputs. This fix allows you to increase its size as much as possible to improve the user experience.
Before : 
After :
=> Fix Tiny description input size

js/dynamic_dropdown_controller.js, phpunit/functional/Glpi/Form/Destination/CommonITILField/RequestTypeFieldTest.php, src/Glpi/Form/AnswersSet.php, src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php, src/Glpi/Form/Destination/AbstractConfigField.php, src/Glpi/Form/Destination/CommonITILField/RequestTypeField.php, src/Glpi/Form/Destination/FormDestinationTicket.php, src/Glpi/Form/Form.php, src/Glpi/Form/QuestionType/QuestionTypeRequestType.php, templates/components/form/fields_macros.html.twig, templates/components/itilobject/fields_panel.html.twig, templates/pages/admin/form/form_destination.html.twig, templates/pages/admin/form/form_destination_commonitil_config.html.twig, templates/pages/form_renderer.html.twig, tests/cypress/e2e/form/destination_config_fields/request_type.cy.js, tests/cypress/support/commands/select2.d.ts, tests/cypress/support/commands/select2.js, tests/cypress/support/e2e.js
Possible configurations:
"Specific value" and "Answer from a specific question" both display a secondary select to let the user pick the chosen type/question:
=> Forms destinations: add "request type" configuration

js/form_editor_controller.js, js/form_editor_converted_extracted_default_value.js, src/Glpi/Form/Form.php, src/Glpi/Form/QuestionType/AbstractQuestionType.php, src/Glpi/Form/QuestionType/AbstractQuestionTypeShortAnswer.php, src/Glpi/Form/QuestionType/QuestionTypeInterface.php, src/Glpi/Form/QuestionType/QuestionTypeLongText.php, templates/pages/admin/form/form_editor.html.twig, templates/pages/admin/form/form_question.html.twig, tests/cypress/e2e/form/form_convert_default_values.cy.js, tests/cypress/support/commands.js
Added a mechanism for converting default values when changing question types.
=> feat(forms): Convert default values when question type change

phpunit/functional/Glpi/Form/AccessControl/ControlType/AllowListTest.php, src/AbstractRightsDropdown.php, src/Glpi/Form/AccessControl/ControlType/AllowList.php, src/Glpi/Form/AccessControl/ControlType/AllowListDropdown.php, src/Html.php, templates/pages/admin/form/access_control/allow_list.html.twig, tests/cypress/e2e/form/access_control.cy.js
Add a dedicated option that easily allow administrators to enable a form for all users.
=> Form allow list: Add "All users" option

phpunit/functional/LocationTest.php, src/CommonTreeDropdown.php, tests/functional/CommonTreeDropdown.php
| Fixed tickets | #17514
It restores the behaviour that was present in GLPI 9.5 and in earlier versions. In these versions, it was possible to not surround the tree separator by spaces, for instance `Country>City>Address` should be splittedn into 3 locations.
=> Fix handling of separator in dropdown import

src/Infocom.php
| Fixed tickets | !33876
Software can be associated with a supplier via the infocom, but in the items tab of the supplier file, software was excluded.
=> fix(supplier): list softwares

CHANGELOG.md, ajax/updatecurrenttab.php, src/Glpi/Config/LegacyConfigurators/StandardIncludes.php, src/Glpi/Http/ExceptionListener.php, src/Glpi/Http/LegacyRouterListener.php, src/Glpi/Http/ListenersPriority.php
The computation of the debug bar base URL is broken in legacy scripts because Symfony relies on `$_SERVER` variables that are overriden by GLPI. There is no need to override them anymore. Only a few plugins will be impacted, and fixing the corresponding legacy scripts will not be too difficult (they need to rely on `REQUEST_URI`).
=> Fix Symfony base URL computation

phpunit/functional/Glpi/Form/Destination/CommonITILField/ContentFieldTest.php, phpunit/functional/Glpi/Form/Tag/AnswerTagProviderTest.php, phpunit/functional/Glpi/Form/Tag/FormTagProviderTest.php, phpunit/functional/Glpi/Form/Tag/FormTagsManagerTest.php, phpunit/functional/Glpi/Form/Tag/QuestionTagProviderTest.php, phpunit/functional/Glpi/Form/Tag/SectionTagProviderTest.php, phpunit/functional/Glpi/Form/Tag/TagTest.php, src/Glpi/Form/Tag/AnswerTagProvider.php, src/Glpi/Form/Tag/FormTagProvider.php, src/Glpi/Form/Tag/QuestionTagProvider.php, src/Glpi/Form/Tag/SectionTagProvider.php, src/Glpi/Form/Tag/Tag.php, src/Glpi/Form/Tag/TagProviderInterface.php, tests/functional/Glpi/RichText/RichText.php
Remove color constructor parameter, call method from provider instead.
=> chore(forms): Add tag color method in tag providers

ajax/treebrowse.php
Avoid this error message in the browse mode display (with PHP 8.3):
```
glpiphplog.WARNING:   *** PHP Warning (2): http_response_code(): Cannot set response code - headers already sent (output started at /home/ubuntu/Dev/GLPI/main/vendor/twig/twig/src/Template.php:328) in /home/ubuntu/Dev/GLPI/main/ajax/treebrowse.php at line 76
Backtrace :
ajax/treebrowse.php:76                             http_response_code()
...Glpi/Controller/LegacyFileLoadController.php:57 require()
vendor/symfony/http-kernel/HttpKernel.php:101      Glpi\Controller\LegacyFileLoadController->Glpi\Controller\{closure}() …
```
=> fix browse view

phpunit/functional/ToolboxTest.php, src/Toolbox.php
| Fixed tickets | !33829
In the content of a ticket, for example, when you add a link to an image. In the final rendering, the original link is not visible. The URL on the image is that of the document in GLPI.
=> fix: avoids creating a link within a link with img

src/DeviceProcessor.php
In the computers list, computer.php, there is no possibility of showing the number of CPUs. If CPUs have the same name (as in nearly all computers) this is not visible anyhow in the list (while number of cores and threads can be displayed already). This would be important for various tasks and invoicing.
The translation of 'Processors number' is already present in GLPI, used for VMs.
=> Adding 'Processors number' in the computers overview list

templates/components/itilobject/service_levels.html.twig
| Fixed tickets | !33875
The SLA / OLA did not appear when it was applied via a ticket template.
**Before**
**After**
=> Fix service levels display

js/form_editor_controller.js, phpunit/functional/Glpi/Form/AccessControl/ControlType/DirectAccessTest.php, src/Glpi/Form/AccessControl/ControlType/AllowList.php, src/Glpi/Form/AccessControl/ControlType/ControlTypeInterface.php, src/Glpi/Form/AccessControl/ControlType/DirectAccess.php, src/Glpi/Form/AccessControl/FormAccessControlManager.php, src/Glpi/Form/Form.php, src/Glpi/Form/Question.php, src/Glpi/Form/QuestionType/AbstractQuestionType.php, src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php, src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php, src/Glpi/Form/QuestionType/AbstractQuestionTypeShortAnswer.php, src/Glpi/Form/QuestionType/QuestionTypeDateTime.php, src/Glpi/Form/QuestionType/QuestionTypeFile.php, src/Glpi/Form/QuestionType/QuestionTypeInterface.php, src/Glpi/Form/QuestionType/QuestionTypeLongText.php, src/Glpi/Form/QuestionType/QuestionTypeRequestType.php, src/Glpi/Form/QuestionType/QuestionTypeUrgency.php, src/Glpi/Form/Renderer/FormRenderer.php, templates/layout/parts/user_header.html.twig, templates/pages/admin/form/access_control/direct_access.html.twig, templates/pages/admin/form/form_editor.html.twig, templates/pages/admin/form/form_question.html.twig, templates/pages/form_renderer.html.twig, tests/cypress/e2e/form/access_policies/direct_access.cy.js, tests/cypress/support/commands.js
The DirectAccess policy allow anonymous users to access a form.
This is dangerous because we don't want anonymous users to access specific features that could reveal database information like items dropdowns (for now only the actors type would be "dangerous").
=> feat(forms): Blacklist dangerous questions types for anonymous forms

src/Glpi/Api/HL/Controller/DropdownController.php
| New feature? | no
For proper stability/versioning, we should use a static list of state types instead of the CFG_GLPI array. This PR also handles the conversion of class names to visibility property names. As seen when testing GraphQL locally previously when there is a custom asset defined, the GraphQL schema being generated was invalid because the slashes from the class name were being kept in property names.
If plugins add new state types, they should use the `REDEFINE_API_SCHEMAS` hook to add the new visibility properties to the schema.
=> [HLAPI] Use static list of state types

templates/components/form/fields_macros.html.twig
Found while testing #17462.
The `for` attribute of the label was incorrect (e.g. `dropdown_myprop[]1246579875`) and different from the `<select>` id (e.g. `dropdown_myprop__1246579875`) that is generated by:
https://github.com/glpi-project/glpi/blob/6edfb3d336b824d1d6005b44c53b68e9dc51ebe0/src/Dropdown.php#L227
=> Fix dropdown fields label when name contains `[]` chars

ajax/impact.php, js/impact.js, src/Glpi/Plugin/Hooks.php, src/Impact.php
Add a new hook to enable changing the icon of an item in the impact anlysis.
=> New hook : enable choosing the icon of an item in impact analysis

css/includes/components/form/_form-editor.scss, js/modules/DynamicDropdownController.js, js/modules/Forms/DestinationAutoConfigController.js, js/modules/Forms/EditorController.js, js/modules/Forms/EditorConvertedExtractedDefaultValue.js, js/modules/Forms/QuestionDropdown.js, js/modules/Forms/QuestionSelectable.js, js/modules/Forms/RendererController.js, src/Glpi/Form/Form.php, src/Glpi/Form/QuestionType/AbstractQuestionType.php, src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php, src/Glpi/Form/QuestionType/AbstractQuestionTypeShortAnswer.php, src/Glpi/Form/QuestionType/QuestionTypeDropdown.php, src/Glpi/Form/QuestionType/QuestionTypeInterface.php, src/Glpi/Form/QuestionType/QuestionTypeLongText.php, src/Glpi/Form/Renderer/FormRenderer.php, templates/pages/admin/form/form_destination.html.twig, templates/pages/admin/form/form_destination_commonitil_config.html.twig, templates/pages/admin/form/form_editor.html.twig, templates/pages/form_renderer.html.twig
The Forms feature JS should be modularized and avoid adding even more to the `window` object. It makes it easier to move to a built script later rather than importing many smaller JS files.
Right now, it some cases the `QuestionSelectable.js` script can be imported twice because of the import in `QuestionDropdown.js` and the dynamic import for specific question types. Something I don't have time to spend more time on is making sure the JS files for specific question types are always loaded through imports in the EditorController and have them work without having to initialize new instances from inline scripts. That would …
=> Modularize Forms JS Code

src/Html.php, tests/cypress/e2e/form/form_convert_default_values.cy.js
It seems like the `autoresize_bottom_margin: 0` option completely disabled tinymce resizing.
Using 1px instead works fine.
Before:
After:
=> Fix tinymce autoresize in forms

phpunit/functional/PrinterTest.php, src/CommonDBTM.php, src/Features/Clonable.php, src/Infocom.php
| Fixed tickets | !34062
When a printer is created from a template with infocoms, and date calculation rules have been activated on the entity. The asset's infocoms are missing.
=> fix(clone): no date calculation

css/includes/components/form/_form-editor.scss, templates/pages/admin/form/form_question.html.twig
No idea why this only happens on chrome, I had to inject a `display: flex` instruction into a specific select2 span for it to work.
Super hacky but I don't understand the issue at all, probably some chrome / select2 conflict.
Before:
After:
=> Forms: fix weird chrome only rendering issue

src/LevelAgreementLevel.php, tests/functional/SLM.php
| Fixed tickets | !34117
The Export option is inherited from the options applied to GLPI rules, but is not relevant in the case of an escalation level.
The current export is not functional and is not designed to support escalation levels.
=> fix(SLA): remove 'Export' option for escalation levels

src/CommonDBChild.php, src/LevelAgreement.php, src/Rule.php, tests/bootstrap.php, tests/functional/SLM.php
| Fixed tickets | !34117
When an SLA or OLA is cloned, the escalation levels linked to it are not cloned in turn.
=> fix(SLA): escalation levels are now cloned when the related SLA is cloned

src/Notification_NotificationTemplate.php, templates/pages/setup/notification/notification_notificationtemplate.html.twig
Currently, when a notification template is added to a notification, a right error is displayed and the notification template has not been added to the notification.
=> fix(notif): adding 'notifications_id' field in notification_notificationtemplate form

phpunit/functional/Glpi/Form/Tag/TagTest.php, src/Glpi/Form/Tag/Tag.php
Tags accent colors were a good idea but the first iteration is too flashy and colorful.
I propose a second more "moderate" version.
Before:
After:
=> Make forms tags accent colors less flashy

phpunit/functional/Glpi/Form/Destination/CommonITILField/RequestTypeFieldTest.php, src/Glpi/Form/Destination/AbstractConfigField.php, src/Glpi/Form/Destination/CommonITILField/ContentField.php, src/Glpi/Form/Destination/CommonITILField/RequestTypeField.php, src/Glpi/Form/Destination/CommonITILField/TitleField.php, tests/src/Form/Destination/AbstractFormDestinationType.php
Suggested by @cedric-anne, avoid using specific keys name and use classes instead.
This reduce the risk on key conflicts if we allow plugins to define their own fields.
=> Forms destination: Use class name for config to avoid conflicts

phpunit/functional/Glpi/Inventory/Assets/AntivirusTest.php, src/Inventory/Asset/Antivirus.php, src/Inventory/Asset/MainAsset.php, src/Inventory/Inventory.php
Ensure no antivirus from full inventory removes all known antiviruses
| Fixed tickets | #17598
=> Handle antivirus updates from partial inventory

src/CommonITILTask.php
Seems to make more sense to have the UI restrict drag/edit based on the task's `canUpdateItem` rather than checking `canUpdateITILItem`.
=> Planning task editable flag based on task not parent

src/Planning.php, tests/functional/Planning.php
| Bug fix?      | -
Remove ticket-specific check and replace with calls to `canUpdate` and `canUpdateItem` to handle more cases in a generic way.
=> Improve planning time update checks

src/Dropdown.php
In #17074, an hidden input was added prior to multiple dropdown to be sure that an empty value is sent when no dropdown value is selected. It permits to do simple checks like `if (!empty($input[$field])) { ... }` and to simplify the handling of multiple dropdowns.
The side effect is that, when the form is redisplayed based on the saved raw input, the `values` param is an empty string, instead of an empty array, and the following error occurs:
```
Twig Error (Twig\Error\RuntimeError): "An exception has been thrown during the rendering of a template ("array_diff(): Argument #2 must be of type array, string given")." in …
```
=> Fix groups input rendering error when unicity check fails

src/Csv/CsvResponse.php, tests/functional/Glpi/Csv/CsvResponse.php
Passing a non empty string for the escape char in CSV operations is deprecated in PHP 8.4 (see https://github.com/php/php-src/pull/15365) and output the following message: `fgetcsv(): Passing a non-empty string to the $escape parameter is deprecated since 8.4`.
As documented in https://www.php.net/manual/fr/function.fgetcsv.php, using `\` for the `$escape` parameter value is pretty useless. Thus, as in GLPI we already replace the `"` char by two single quotes `''` (in `Search::csv_clean()`), values will never contain the enclosure char and so any escaping logic is useless.
=> Fix deprecation on CSV export in PHP 8.4

phpunit/functional/Glpi/Toolbox/DataExportTest.php, src/Toolbox/DataExport.php
| Fixed tickets | #17417
Usage of `trim` is not compatible with multibyte chars. Indeed, a `trim($str, "\xC2\xA0")` will remove any `\xC2` and `\xA0` chars even if only one of them is present. Using `preg_replace` fixes this issue.
=> Fix spacing chars trim in data export

ajax/comments.php, templates/components/group/info_card.html.twig, templates/components/itilobject/actors/field.html.twig
| Fixed tickets | !33820
In 9.5, on tickets, groups had a tooltip allowing the complete name and comment to be displayed, but this was no longer present on 10.0.
Before:
After:
=> fix(ticket): restores group's tooltip

install/empty_data.php, install/migrations/update_10.0.16_to_10.0.17.php, install/migrations/update_10.0.16_to_10.0.17/entities.php, phpunit/functional/EntityTest.php, src/Entity.php
| Fixed tickets | #17648
The `custom_css_code` field is a textfield and therefore has no default value. The `Entity::getUsedConfig()` does not correctly handle the `null` value found in the root entity. As I am not sure to correctly handle the side effects of a change related to this on this method, I propose to fix the value in DB.
=> Fix default custom CSS value for root entity

resources/api_doc.MD, src/Glpi/Api/HL/Controller/AbstractController.php, src/Glpi/Api/HL/Controller/AdministrationController.php, src/Glpi/Api/HL/Controller/AssetController.php, src/Glpi/Api/HL/Controller/ComponentController.php, src/Glpi/Api/HL/Controller/CoreController.php, src/Glpi/Api/HL/Controller/DropdownController.php, src/Glpi/Api/HL/Controller/GraphQLController.php, src/Glpi/Api/HL/Controller/ITILController.php, src/Glpi/Api/HL/Controller/ManagementController.php, src/Glpi/Api/HL/Controller/ProjectController.php, src/Glpi/Api/HL/Controller/ReportController.php, src/Glpi/Api/HL/Controller/RuleController.php, src/Glpi/Api/HL/Doc/Schema.php, src/Glpi/Api/HL/Doc/SchemaReference.php, src/Glpi/Api/HL/GraphQL.php, src/Glpi/Api/HL/GraphQLGenerator.php, src/Glpi/Api/HL/OpenAPIGenerator.php, src/Glpi/Api/HL/RoutePath.php, src/Glpi/Api/HL/RouteVersion.php, src/Glpi/Api/HL/Router.php, src/Glpi/Controller/ApiController.php, src/Webhook.php, tests/HLAPITestCase.php, tests/functional/Glpi/Api/HL/Controller/ComponentController.php, tests/functional/Glpi/Api/HL/OpenAPIGenerator.php, tests/functional/Glpi/Api/HL/Router.php
This was an important feature that drove the creation of a new API. The initial PR for it already planned to handle specifying the version in the URL (or default to the current version). However, it currently just handles redirecting v1 to the legacy API. Beyond that, the version is removed from the URL and not handled.
This PR will add the framework for versioning HLAPI routes and schemas and handling the generation of the OpenAPI documentation for the requested version. I've put this off for a while but makes sense to add this functionality now before anything needs to be done for the next API version.
The current plan: …
=> Plan HLAPI versioning

src/CommonITILObject.php
| Fixed tickets | !33234
Related ticket : 33234
The customer wants to sort the "Support > Tickets" view by user category
=> Add user category search option (Requester, Observer, Technician)

CHANGELOG.md, src/Dropdown.php
| Fixed tickets | #16877
When the search text is numeric, it now only matches the beginning of the IDs rather than anywhere in the IDs. Should enable use of the index for that field now.
Changed a comparison to strict and removed redundant `is_numeric` check.
=> Improve perf searching ids in dropdowns

src/Item_Devices.php
harmonize location search option 
Actually, For ```CommonDevice``` assets, GLPI only display location name from related search option.
Ex : ```SimCard```
Related search option into device list
Now, GLPI use ```completename``` (like `Ticket` for example)
NB : Takes into account the following option
| Fixed tickets | !34181
=> Fix(Device): harmonize location search option

apirest.md, src/MassiveAction.php, tests/web/APIRest.php
`add_transfer_list` massive action cannot be used from the API.
This action adds the items to the transfer list.
But the `transferer` action cannot be triggered via the API, so you need to go to this page
The information is added to the session used by the API, which is different from the user session (even if it's the same user used by the API and to connect to GLPI).
maybe it should be done on `main` branch
=> fix(APIRest): remove not functional massive action

src/Group_User.php
Since https://github.com/glpi-project/glpi/pull/11928
Users from another entity can be seen  
Let's imagine the `root entity` with two children Entity A and `Entity B`
A group named `Security` in the `root entity` and `recursive`.
All admins in `entity A` and `entity B` see the group (OK)
The Admin in `entity A` adds a user from `entity A` to the group
The admin in `entity B` sees the user in `entity A` (NOK)
This PR fix this and corrects the user count in the tab, taking account of the entity restriction
| Fixed tickets | !34146
=> Fix(Group): fix user visibilty

phpunit/functional/TicketTest.php, src/CommonITILObject.php
| Fixed tickets | !34145
When creating a ticket via the API with the status set to "closed" and providing resolution and closure dates, these dates were systematically ignored.
I believe we should calculate these dates when they are missing or inconsistent, such as when they are earlier than the ticket's opening date, and also ensure that the resolution date is not after the closure date.
=> fix(ticket): solvedate and closedate on creation

src/Phone.php
Add missing ```Agent``` ```searchoption``` to ```Phone```
| Fixed tickets | !34295
=> Fix(Phone): add missing Agent search option

.composer-require-checker.config.json, .phpstan-baseline.php, phpstan.neon, src/User.php
See https://phpstan.org/user-guide/baseline
There are still some PHPStan level 2 errors in the 10.0/bugfixes branch also many errors on level 3 and 4, but fixing them may not be as simple as expected and it could result in introduction of new bugs.
Anyway, we can still activate the PHPStan level 4 checks by referencing the remaining errors in the auto-generated baseline. This would permit to force future code changes to be compliant with this new level.
After this would be merged in the main branch, it would still be possible (and recommended) to address these errors in the main branch, but it could be done later.
=> Activate PHPStan level 4 for future code changes

CHANGELOG.md, src/CartridgeItem.php, src/NotificationSetting.php, src/RuleDictionnaryDropdownCollection.php, src/Transfer.php
| Bug fix?      | Maybe
Done before support for generic assets is ensured/added. Not the rewrite it needs, but still a substantial refactor/cleanup. At the very least, it should make the entire entity transfer process more understandable since I don't think any current developer has a full understanding of this code. I also found some potential bugs which still need verified/fixed but were marked in the code with "FIXME" comments. I haven't looked at test coverage yet either.
- The code in the `simulateTransfer` method was split into several methods based on the related itemtype.
- Many methods were made private
Still a lot that could be …
=> Refactor and review transfer code

CHANGELOG.md, phpunit/functional/TransferTest.php, src/Transfer.php
I have every tagged version of GLPI cloned locally and I found no version where the `cleanSoftwares` method was actually called, so the "If software are no longer used" option was always ignored/treated as Preserve which was the default option. This PR adds a call to the method and adds a test.
=> Implement clean_software transfer option

src/NotificationTargetProjectTask.php
| Fixed tickets | !34162
In the ‘New project task’ notification settings, if you add the recipient ‘Project team group without supervisor’, the notifications are not sent.
=> Fix project task recipients

src/LevelAgreementLevel.php, src/SlaLevel.php
- It fixes !34326
Prevents cloning a `SlaLevel`.
In an `SLA`, it's not possible to have more than one `SlaLevel` with the same `execution_time`.
https://github.com/glpi-project/glpi/blob/5cd323a0b48d056feca915a64df1149ecd750d16/src/SlaLevel.php#L106-L113
The `clone` action overrides this constraint
=> Fix(SlaLevel): prevent 'clone' action

.phpstan-baseline.php, src/CommonGLPI.php, src/Glpi/Form/AccessControl/FormAccessControl.php, src/Glpi/Form/AnswersSet.php, src/Glpi/Form/Destination/AbstractFormDestinationType.php, src/Glpi/Form/Destination/FormDestination.php, src/Glpi/Search/CriteriaFilter.php
Fix phpdoc of the `getTabNameForItem()` method, which did not take into account that `string[]` is also a valid return type.
Here is an example of the return value being used an array:
This removes 49 errors from the baseline file.
=> Fix phpdoc return hint of getTabNameForItem() and bad implementations

src/Ticket.php
- It fixes !34329
Check if the category is accessible to the ticket's entity during creation
=> Fix(ticket): check category / entity validity

phpunit/functional/Glpi/Form/Destination/CommonITILField/UrgencyFieldTest.php, src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php, src/Glpi/Form/Destination/CommonITILField/UrgencyField.php, src/Glpi/Form/Destination/CommonITILField/UrgencyFieldConfig.php, src/Glpi/Form/Destination/CommonITILField/UrgencyFieldStrategy.php, src/Glpi/Form/QuestionType/QuestionTypeUrgency.php, templates/components/itilobject/fields/priority_matrix.html.twig, templates/pages/admin/form/itil_config_fields/urgency.html.twig, tests/cypress/e2e/form/destination_config_fields/urgency.cy.js
Credit to @ccailly, we both ended up working on this feature by accident so I've merged both work into one (there was good things to keep on both sides).
Note that I've noticed this does not take into account that urgency levels can be disabled in the general config (the urgency question type also missed this "feature").
I've added it to the backlog and will fix it in another PR (I'll probably add a proper Urgency backed enum because we don't even have constants for urgency values right now).
=>  feat(forms): Forms destinations - config urgency

phpunit/functional/TransferTest.php, src/Transfer.php
Links between ITIL objects and suppliers were not properly handled because their transfer was happening before the actual ITIL object changed entities and the entity checks done in `CommonDBRelation::canRelationItem()` were failing as a result in some cases.
=> Fix transfering ITIL supplier links

src/Transfer.php
Remove the addition of `-1` IDs in the transfer arrays seemingly just to prevent empty IN SQL clauses from being created.
=> Clean empty in clause handling in transfer feature

.phpstan-baseline.php, phpunit/functional/Glpi/Form/Export/FormSerializerTest.php, src/Glpi/Controller/Form/Import/Step1IndexController.php, src/Glpi/Controller/Form/Import/Step2PreviewController.php, src/Glpi/Controller/Form/Import/Step3ExecuteController.php, src/Glpi/Form/Export/Context/DatabaseMapper.php, src/Glpi/Form/Export/Result/ImportResultPreview.php, src/Glpi/Form/Export/Serializer/FormSerializer.php, src/Glpi/Form/Form.php, templates/layout/parts/context_links.html.twig, templates/pages/admin/form/import/step1_index.html.twig, templates/pages/admin/form/import/step2_preview.html.twig, templates/pages/admin/form/import/step3_execute.html.twig, tests/cypress/e2e/form/serializer/import.cy.js, tests/fixtures/export-of-2-forms.json
Minimal import UI.
Step 1:
Step 2:
Step 3:
Note that the second step isn't very interesting right now as it display something very similar to the third step.
This is temporary, in the future it will allow the user to pick replacements for missing items.
=>  feat(forms) : Import form basic UI

phpunit/functional/Glpi/Form/Export/FormSerializerTest.php, src/Glpi/Controller/Form/Import/Step2PreviewController.php, src/Glpi/Controller/Form/Import/Step3ExecuteController.php, src/Glpi/Form/Export/Context/DatabaseMapper.php, src/Glpi/Form/Export/Serializer/FormSerializer.php, src/Session.php
The form import process try to match items using their names.
It should be restricted to the current entity to make sure the user don't see data that he isn't allowed to see.
=> Form import: map only items visible in the current entity

phpunit/functional/Glpi/Form/QuestionType/QuestionTypeAssigneeTest.php, phpunit/functional/Glpi/Form/QuestionType/QuestionTypeCheckboxTest.php, phpunit/functional/Glpi/Form/QuestionType/QuestionTypeDateTimeTest.php, phpunit/functional/Glpi/Form/QuestionType/QuestionTypeDropdownTest.php, phpunit/functional/Glpi/Form/QuestionType/QuestionTypeEmailTest.php, phpunit/functional/Glpi/Form/QuestionType/QuestionTypeItemDropdownTest.php, phpunit/functional/Glpi/Form/QuestionType/QuestionTypeLongTextTest.php, phpunit/functional/Glpi/Form/QuestionType/QuestionTypeNumberTest.php, phpunit/functional/Glpi/Form/QuestionType/QuestionTypeObserverTest.php, phpunit/functional/Glpi/Form/QuestionType/QuestionTypeRadioTest.php, phpunit/functional/Glpi/Form/QuestionType/QuestionTypeRequestTypeTest.php, phpunit/functional/Glpi/Form/QuestionType/QuestionTypeRequesterTest.php, phpunit/functional/Glpi/Form/QuestionType/QuestionTypeShortTextTest.php, phpunit/functional/Glpi/Form/QuestionType/QuestionTypeUrgencyTest.php, src/Glpi/Form/Answer.php, src/Glpi/Form/QuestionType/AbstractQuestionType.php, src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php, src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php, src/Glpi/Form/QuestionType/AbstractQuestionTypeShortAnswer.php, src/Glpi/Form/QuestionType/QuestionTypeDateTime.php, src/Glpi/Form/QuestionType/QuestionTypeFile.php, src/Glpi/Form/QuestionType/QuestionTypeInterface.php, src/Glpi/Form/QuestionType/QuestionTypeItem.php, src/Glpi/Form/QuestionType/QuestionTypeLongText.php, src/Glpi/Form/QuestionType/QuestionTypeRequestType.php, src/Glpi/Form/QuestionType/QuestionTypeUrgency.php, src/Glpi/Form/Tag/AnswerTagProvider.php, tests/cypress/e2e/form/question_types/selectables.cy.js, tests/src/FormTesterTrait.php
Update `AnswerTagProvider` to return the formatted answer instead of the raw answer. This change improves the display of answers by formatting them based on their type. The `getFormattedAnswer()` method has been added to the `Answer` class, which formats the raw answer using the corresponding QuestionType's `formatRawAnswer()` method.
=> feat(forms): use an answer formatted by the question type to handle other types than string

install/migrations/update_10.0.x_to_11.0.0/form.php, install/mysql/glpi-empty.sql, templates/pages/admin/form/service_catalog_tab.html.twig, templates/pages/self-service/service_catalog.html.twig, tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js, tests/cypress/e2e/form/service_catalog/service_catalog_tab.cy.js
Create proper 'description' field that will be displayed in the service catalog.
Config:
=> Add description to service catalog

bin/console, src/Glpi/Application/ConfigurationConstants.php, src/Glpi/Kernel/Kernel.php
Using the `--env` parameter of the console inside an environment that was also defining the `GLPI_ENVIRONMENT_TYPE` in its environment variables was resulting in a `Warning: Constant GLPI_ENVIRONMENT_TYPE already defined` error.
=> Init `GLPI_ENVIRONMENT_TYPE` in the `ConfigurationConstants` service

CHANGELOG.md, inc/relation.constant.php, src/CommonDevice.php, src/Computer.php, src/Config.php, src/Glpi/Asset/Capacity/HasDevicesCapacity.php, src/Glpi/Dashboard/FakeProvider.php, src/Glpi/Dashboard/Grid.php, src/Item_Devices.php, src/Plugin.php, src/autoload/CFG_GLPI.php, tests/functional/Glpi/Asset/Capacity/HasDevicesCapacity.php
A `Components` capacity is added and permits to attach any component type to the asset. In a second time, I think it would be interesting to give the ability to configure the list of allowed component types. It would require to specify how we should handle the capacities configuration (in a dedicated tab, in a modal, ...).
=> Components capacity

css/includes/_base.scss
It fixes #17808
Bases the background color on `bg-surface` rather than `bg-surface-dark` and forces the text color to be the regular body color.
=> Fix pre element colors

phpunit/functional/Item_DevicesTest.php, src/Item_Devices.php, tests/functional/Glpi/Asset/Capacity/HasDevicesCapacity.php
Follows #17839 and required for #17807.
An asset class that is not present in `$CFG_GLPI['itemdevices_types']` was listed in the affinities with the devices having a `*` in their affinities list. This was not correct.
The proposed change ensure that `Item_Devices::getItemAffinities()` will always return an empty list for asset classes that are not supposed to have devices.
=> Fix filtering of devices affinities

inc/includes.php, src/Session.php, tests/functional/Session.php
- It fixes !34304 + !34305
When an entity changes its parent, the elements associated with that entity remain visible and accessible in ongoing sessions, even if the new hierarchy no longer grants the user access to the moved entity.
=> Fix: reload session entities in case of modification

phpunit/GLPITestCase.php, src/Glpi/Asset/AssetDefinitionManager.php
Once loaded, the asset definitions are stored in the `definitions_data` property of the `AssetDefinitionManager` singleton instance. This property acts as a cache and interfers with the other tests. Unsetting the singleton instance shoudl fix this behaviour.
=> Clean asset definitions after each test

.phpstan-baseline.php, front/asset/asset.form.php, front/asset/ruledictionarymodel.form.php, front/asset/ruledictionarymodel.php, front/asset/ruledictionarytype.form.php, front/asset/ruledictionarytype.php, front/rule.common.form.php, phpunit/DbTestCase.php, phpunit/functional/Glpi/Asset/DictionaryTest.php, phpunit/functional/HtmlTest.php, src/Glpi/Api/HL/Controller/RuleController.php, src/Glpi/Asset/AssetDefinition.php, src/Glpi/Asset/AssetDefinitionManager.php, src/Glpi/Asset/RuleDictionaryModel.php, src/Glpi/Asset/RuleDictionaryModelCollection.php, src/Glpi/Asset/RuleDictionaryType.php, src/Glpi/Asset/RuleDictionaryTypeCollection.php, src/Rule.php, src/RuleCollection.php, src/RuleCommonITILObjectCollection.php, src/RuleDictionnaryDropdownCollection.php, tests/DbTestCase.php
=> Custom Asset Type and Model Dictionaries

src/Glpi/Plugin/Hooks.php, templates/components/itilobject/fields_panel.html.twig
Add new hook 
- `pre_item_accordion_section`
- `post_item_accordion_section`
an example of implementation has been made on the `example` plugin
https://github.com/pluginsGLPI/example/pull/62
=> Feat(Framework): Add new hook (pre/post_item_accordion_section)

phpunit/functional/HtmlTest.php, src/CommonITILTask.php, src/Glpi/Agent/Communication/AbstractRequest.php, src/Glpi/Search/Provider/SQLProvider.php, src/Html.php, src/KnowbaseItem.php
`Html::resume_text()` purpose is to truncate a text to be displayed in an HTML page. I propose to always encode special chars contained in the text to make it easier to use.
=> Make `Html::resume_text()` result safe

src/SavedSearch_User.php, src/Session.php, src/Software.php, src/Supplier.php
Few htmlspecialchar() missing, some typos (S* classes)
=> Few htmlspecialchar() missing, some typos

CHANGELOG.md, phpunit/functional/CommonDBTMTest.php, phpunit/functional/ComputerTest.php, phpunit/functional/Glpi/Form/FormTest.php, src/CommonDBTM.php, src/Glpi/Features/DCBreadcrumb.php, tests/functional/Glpi/ContentTemplates/Parameters/ChangeParameters.php, tests/functional/Glpi/ContentTemplates/Parameters/KnowbaseItemParameters.php, tests/functional/Glpi/ContentTemplates/Parameters/ProblemParameters.php, tests/functional/Glpi/ContentTemplates/Parameters/TicketParameters.php
1. Ensure that HTML special chars are correctly escaped in `CommonDBTM::getLink()` result.
2. Ensure that `CommonDBTM::getName()`/`CommonDBTM::getNameID()` result never contains HTML. It can be used outside of web view context and it is the responsibility of the caller to escape it.
=> Fix escaping handling in `CommonDBTM::getLink/getName/getNameID()`

phpunit/functional/KnowbaseItemTest.php, src/KnowbaseItem.php
- It fixes # (Ticket number : !34449)
- Fixing the ability to clone knowledge bases: this was available in 9.5 but was removed.
The function was already functional in 9.5, but only the cloning of linked items (target, Associated items and Documents) was missing.
=> Fix KnowbaseItem Clonability

src/DbUtils.php
That is a code smell, and in the future, `trim()` with a non-string argument might throw a warning or an error.
Backport of #17883 to v10
=> Fix invalid check in DbUtils

CHANGELOG.md, ajax/comments.php, front/stat.graph.php, src/Change.php, src/CommonDBTM.php, src/CommonITILObject.php, src/DbUtils.php, src/Document.php, src/Glpi/Features/PlanningEvent.php, src/Glpi/Search/Provider/SQLProvider.php, src/Item_SoftwareLicense.php, src/Item_SoftwareVersion.php, src/KnowbaseItem.php, src/NotificationTarget.php, src/ObjectLock.php, src/Problem.php, src/Profile_User.php, src/Project.php, src/Ticket.php, src/User.php, src/autoload/dbutils-aliases.php
Still a draft, tests may fail.
1. I splitted the `getUserName()` and `formatUserName()` methods to have one that retunrs a raw username (`getUserName()`/`formatUserName()`) and one that returns a HTML link (`getUserLink()`/`formatUserLink()`).
2. `getUserName()` had a `$link=2` parameter value that completely changed its behaviour to return the user inforcard + the user link + the link URL. I moved this info card generation into a `User::getInfoCard()` method.
=> Fix escaping handling in `formatUserName()` and `getUserName()`

src/Appliance.php, src/Appliance_Item.php, src/Appliance_Item_Relation.php, src/Entity.php, src/Html.php
Fixed possible encodings issues
=> Fixed possible encodings issues

src/DbUtils.php, src/DisplayPreference.php, src/DocumentType.php
=> Better HTML encoding for DbUtils, DisplayPreference and DocumentType

phpunit/functional/ToolboxTest.php, src/Toolbox.php
- It fixes !34379
- In the dashboard, the widget colours could not be in RGB format
=> Fix - RGB format for dashboard widget colours

phpunit/functional/Glpi/Form/AccessControl/FormAccessControlManagerTest.php, phpunit/functional/Glpi/Form/ServiceCatalog/ServiceCatalogManagerTest.php, src/Glpi/Controller/Form/RendererController.php, src/Glpi/Controller/Form/ServiceCatalogController.php, src/Glpi/Controller/Form/SubmitAnswerController.php, src/Glpi/Form/AccessControl/FormAccessControlManager.php, src/Glpi/Form/AccessControl/FormAccessParameters.php, src/Glpi/Form/ServiceCatalog/ServiceCatalogManager.php, tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js, tests/cypress/support/commands/form.js, tests/src/FormBuilder.php, tests/src/FormTesterTrait.php
Modify the `ServiceCatalogManager` service to filter the forms according to their access policies.
This is done by calling the existing `canAnswerForm()` method on each forms.
We could in theory do it directly in the main SQL query that fetches the forms to be more efficient but this would require more code and be less reliable.
Doing it this way should be fine as forms are a low volume item anyway. 
To ease testing, I've also removed a session check that was done inside the `FormAccessControlManager` service.
This check was used to bypass the forms access restrictions when a form is being previewed by an administrator.
This has been replaced by a dedicated `bypass_restriction` parameter in the `FormAccessParameters` object, which is applied directly into the controllers that needs it.
| …
=> Filter service catalog using access policies

src/DBmysql.php
Since the development of the following features :
- generic asset 
- forms
GLPI displays the following message (only if installed on `MariaDB`)
**`4 tables are using the deprecated utf8mb3 storage charset. Run the "php bin/console migration:utf8mb4" command to migrate them.`**
These two features use a new type of column that we haven't used before => `JSON`
- On `Mysql` it's “real” type 
- On `MariaDB` it's an alias to `longtext` `utf8mb4_bin`. See -> [Link](https://mariadb.com/kb/en/json-data-type/#:~:text=JSON%20is%20an%20alias%20for,performance%20is%20at%20least%20equivalent.)
See the `Collation` of the `zones` column :
- MySQL (`NULL`)
```sql
MySQL [main]> show full columns from glpi_stencils; …
```
=> Fix(Core): prevent warning about 'legitimate' utf8mb4_bin

phpunit/functional/Glpi/Form/Destination/CommonITILField/ITILCategoryFieldTest.php, src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php, src/Glpi/Form/Destination/CommonITILField/ITILCategoryField.php, src/Glpi/Form/Destination/CommonITILField/ITILCategoryFieldConfig.php, src/Glpi/Form/Destination/CommonITILField/ITILCategoryFieldStrategy.php, templates/pages/admin/form/itil_config_fields/itilcategory.html.twig, tests/cypress/e2e/form/destination_config_fields/itilcategory.cy.js, tests/cypress/e2e/form/form_destination.cy.js
"Specific ITIL Category" display a secondary select to let the user pick the chosen itil category :
"Answer from a specific question" display a secondary select to let the user pick the chosen question :
=> feat(forms): Add ITILCategory field configuration for form destination

css/legacy/includes/_planning.scss, js/planning.js
- It fixes !34475
Replace agendaEventMinHeight option, removed since FullCalendar v4.
=> Fix(planning): event min height

CHANGELOG.md, src/CommonGLPI.php
The `CommonGLPI::$type` property is not anymore used since a long time ago. There are still some occurences in the `glpiinventory` plugin (`if ($item->fields['type'] == $this->type) {`), but I guess it is related to something that does not work anymore.
=> Drop unused `CommonGLPI::$type`

phpunit/DbTestCase.php, phpunit/functional/Glpi/Form/AccessControl/ControlType/AllowListConfigTest.php, phpunit/functional/Glpi/Form/Export/FormSerializerAccessPoliciesTest.php, phpunit/functional/Glpi/Form/Export/FormSerializerTest.php, src/Glpi/Form/AccessControl/ControlType/AllowListConfig.php, src/Glpi/Form/AccessControl/FormAccessControl.php, src/Glpi/Form/Export/Context/ConfigWithForeignKeysInterface.php, src/Glpi/Form/Export/Context/DatabaseMapper.php, src/Glpi/Form/Export/Context/ForeignKey/ForeignKeyArrayHandler.php, src/Glpi/Form/Export/Context/ForeignKey/JsonConfigForeignKeyHandlerInterface.php, src/Glpi/Form/Export/Serializer/FormSerializer.php, src/Glpi/Form/Export/Specification/AccesControlPolicyContentSpecification.php, src/Glpi/Form/Export/Specification/FormContentSpecification.php, tests/src/FormTesterTrait.php
Replace #17679.
Export/import the access policies of a form.
There is one technical difficulty: each access policies has its own config (for example, the allow list keep track of multiple users, groups and profiles).
These configs can contain database ids, which is bad for the export (as we don't want any hardcoded ids into the exported json file).
Therefore, we need a solution to easily handle those without heavy configuration on the config side.
I've chosen the `ForeignKeysHandler` approach, which is a list of handler objects defined by each config class that will let the serializer know how to deal with the data.
=> Forms: export/import access policies

install/migrations/update_10.0.16_to_10.0.17/logs.php, src/MailCollector.php
It fixes #17770
The proposed change will prevent the mail collector to add history entries on every execution. These entries are polluting the history and are redundant with the `CronTaskLog` entries.
Altternative to #17772.
=> Do not add history entries when emails are collected

front/cron.php, src/CronTask.php, src/Session.php
| Fixed tickets | !33948
The ticket in question reported a problem with the sending of SLA reminders.
The notification was not being generated and fatal errors were interrupting the notification generation mechanism due to undefined variables (`glpiname` and `glpigroups` in this case).
Access rights to GLPI objects were blocking the notification filter system, which was unable to find the objects due to a lack of rights.
=> fix: Add all rights to cron and manage session values for CronTask

src/Plugin.php, src/Plugin/Hooks.php
I found an inconsistency in the plugin post install hook.
This is an error I did in a PR 2 years ago, but has not been noticed :(
https://github.com/glpi-project/glpi/pull/11361/files#diff-c346b1aeac8259782c74702eadfe1d7a240ee3ecea6020ad2addede93c635cabL800
When installing a plugin, the hook POST_PLUGIN_UNINSTALL is called instead of PLUGIN_HOOK_INSTALL
=> fix plugin post install hook

src/Glpi/Config/LegacyConfigurators/StandardIncludes.php, src/Glpi/Controller/IndexController.php, src/Glpi/Http/Firewall.php
It fixes #17911.
The checks related to the DB config file validity were made on the `index` controller, preventing it to redirect to the installation process. Also, since #17490, the firewall was blocking the installation UI. Both problems are fixed by this PR.
=> Fix bootstrap/firewall checks related to install UI

composer.json
Since #17784, `composer build` command compiles locales 2 times
=> fix double mo compilation on 'composer build' command

src/CommonITILValidation.php, templates/components/itilobject/validation.html.twig
- Switch the ITIL object approval page to TWIG (necessary for the ITIL object print preview to function correctly).
**Before**
**After**
=> Feat(Approval) Twig Update

.phpstan-baseline.php, CHANGELOG.md, js/modules/Screenshot/Screenshot.js, src/Glpi/Application/ConfigurationConstants.php, src/Glpi/Application/View/Extension/PluginExtension.php, src/Glpi/Http/LegacyAssetsListener.php, src/Glpi/Http/LegacyRouterListener.php, src/Glpi/Http/LegacyRouterTrait.php, src/Glpi/Marketplace/View.php, src/Html.php, src/Plugin.php, src/Report.php, src/Rule.php, src/RuleCollection.php, src/Stat.php, stubs/glpi_constants.php, tests/functional/Glpi/Http/LegacyAssetsListener.php, tests/functional/Glpi/Http/LegacyRouterListener.php
With the proposed changes, any URL path matching the `/plugins/{plugin_key}` pattern will reach the corresponding plugin resource (static file or PHP script), wherever the plugin is located (as long as it is in a directory listed in `PLUGINS_DIRECTORIES`).
It means that:
- there is no need to build URLs using the `Plugin::getWebDir()` method or the `GLPI_PLUGINS_PATH` javascript variable;
- the `GLPI_MARKETPLACE_DIR` could really be changed now, even for a path located ouside the GLPI root directory (until now, changing it was not really possible, as firewall and router checks were made using the hardcoded `(marketplace|plugins)` patterns).
=> Use `/plugins/` path prefix for all plugins resources

phpunit/functional/TicketTaskTest.php, src/CommonITILTask.php, src/Features/ParentStatus.php
- It fixes !34520
The ticket status was automatically set to 'Planned' when a scheduled task was added. However, when this task was marked as 'Done', the ticket status was not updated accordingly. This PR fixes the issue by ensuring the ticket status is consistently updated after the task is completed.
=> Fix(ticket): update ticket status when planned task is updated

front/central.php, front/helpdesk.public.php, install/install.php, phpunit/functional/HtmlTest.php, src/Html.php, src/MassiveAction.php, src/Session.php, src/Transfer.php
Even if it does not seems possible to exploit it, we already had several issues opened related to lack of filtering of the referer header value.
I propose to add some filtering on it, and to generate back URLs based on the `$CFG_GLPI['url_base']` config entry when the referer is considered as invalid/unsafe.
=> Prevent Referer spoofing

src/Glpi/Http/LegacyAssetsListener.php, src/Glpi/Http/LegacyDropdownRouteListener.php, src/Glpi/Http/LegacyRouterListener.php, src/Glpi/Http/ListenersPriority.php
Fixes #17781.
`Group` extends `CommonDropdown` but has its own custom `/front/group.php` script. The generic `DropdownController` should not be used in this case.
=> Do not forward to dropdown controller if a front script exists

.phpstan-baseline.php, src/Glpi/Kernel/Kernel.php
When the kernel is instanciated without the `debug: true` parameter, DI container cache freshness is not checked at runtime. See https://github.com/symfony/http-kernel/blob/c227b1a922703bfbc7c1d5b52c76d6beceb67753/Kernel.php#L413-L421
It causes issues on the `testing` environment, as a change in class/method signatures can make the cached container incompatible with the GLPI code and result in a fatal error.
Instanciating the kernel with the `debug: true` parameter in the `testing` environment will prevent this kind of issues.
=> Ensure that container cache is correctly refreshed on testing env

src/DBmysql.php
I think that SQL warnings are not properly stored when debug mode is enabled.
$SQL_TOTAL_REQUEST is incremented on each ->doQuery() execution only when debug mode is enabled, then i assume that $DEBUG_SQL['warnings'][$SQL_TOTAL_REQUEST] should be populated only when debug mode is enabled
=> fix sql debugger data collector

src/Dashboard/Grid.php
- It fixes !34581
Some filters, such as “ticket types”, did not apply to certain ticket cards.
=> Fix(Dashboard): filters not applied

src/Marketplace/View.php
Code exist to display a link to get plugin CHANGELOG
`View.php -> getPlugincard()`
```php
$changelog_url = Html::entities_deep($plugin['changelog_url'] ?? "");
$changelog_url = strlen($changelog_url)
? "<a href='{$changelog_url}' target='_blank' >
<i class='ti ti-news add_tooltip' title='" . __s("Changelog") . "'></i>
</a>"
: "";
``` 
But when the plugin is loaded from the API, we don't retrieve the url.
This involves modifying all plugins that do not have the XML node `<changelog_url>` in the `plugin.xml` file
need : https://github.com/glpi-project/plugins/pull/85
=> Fix(Marketplace): retrieve 'changelog_url' from API

src/CommonITILObject.php, src/Log.php
Fixes the encoding issues in the historical tab. Alternative to #17949.
As the `Log::getHistoryData()` returns text that contains some HTML tags (`<ins>` and `<del>`), I propose to ensure that fields values added to the returned string are espaded by the method itself.
=> Fix encoding issues in historical tab

phpunit/functional/Glpi/Form/Destination/CommonITILField/EntityFieldTest.php, src/Entity.php, src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php, src/Glpi/Form/Destination/CommonITILField/EntityField.php, src/Glpi/Form/Destination/CommonITILField/EntityFieldConfig.php, src/Glpi/Form/Destination/CommonITILField/EntityFieldStrategy.php, src/Glpi/Form/QuestionType/QuestionTypeItem.php, templates/layout/parts/profile_selector.html.twig, templates/pages/admin/form/itil_config_fields/entity.html.twig, tests/cypress/e2e/form/destination_config_fields/entity.cy.js
"Specific entity" display a secondary select to let the user pick the chosen Entity :
"Answer from a specific question" display a secondary select to let the user pick the chosen question :
=> feat(forms): Add Entity field configuration for form destination

phpunit/functional/Glpi/Form/Destination/CommonITILField/ITILFollowupFieldTest.php, src/Dropdown.php, src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php, src/Glpi/Form/Destination/CommonITILField/ITILFollowupField.php, src/Glpi/Form/Destination/CommonITILField/ITILFollowupFieldConfig.php, src/Glpi/Form/Destination/CommonITILField/ITILFollowupFieldStrategy.php, templates/pages/admin/form/itil_config_fields/itilfollowuptemplate.html.twig, tests/cypress/e2e/form/destination_config_fields/itilfollowup.cy.js
Adds the ability to define followups that will be added to ITIL form destination objects.
- No Followup
- Specific Followup templates
- Answer from specific questions
- Answer to last "Followup templates" question
- All answers to "Followup templates" questions
=> feat(forms): Add ITILFollowup field configuration for form destination

src/Dropdown.php
The translation wasn't being rendered ("Calendar" was being shown instead of "Calendário" in PT-BR).
=> Fix "Calendar" Dropdown translation

phpunit/functional/Glpi/Form/Destination/CommonITILField/RequestSourceFieldTest.php, src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php, src/Glpi/Form/Destination/CommonITILField/RequestSourceField.php, src/Glpi/Form/Destination/CommonITILField/RequestSourceFieldConfig.php, src/Glpi/Form/Destination/CommonITILField/RequestSourceFieldStrategy.php, templates/pages/admin/form/itil_config_fields/request_source.html.twig, tests/cypress/e2e/form/destination_config_fields/request_source.cy.js
"Specific request source" display a secondary select to let the user pick the chosen source :
=>  feat(forms): Add new configuration fields to forms destination - Request source

phpunit/functional/Glpi/Form/Destination/CommonITILField/ITILTaskFieldTest.php, src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php, src/Glpi/Form/Destination/CommonITILField/ITILTaskField.php, src/Glpi/Form/Destination/CommonITILField/ITILTaskFieldConfig.php, src/Glpi/Form/Destination/CommonITILField/ITILTaskFieldStrategy.php, templates/pages/admin/form/itil_config_fields/itiltasktemplate.html.twig, tests/cypress/e2e/form/destination_config_fields/itiltask.cy.js
Adds the ability to define tasks that will be added to ITIL form destination objects.
- No Task
- Specific Task templates
- Answer from specific questions
- Answer to last "Task templates" question
- All answers to "Task templates" questions
=> feat(forms): Add ITILTask field configuration for form destination

front/cron.php, src/Glpi/Config/LegacyConfigurators/SessionStart.php
Fixed issue #17961 
The use of `ini_set('session.use_cookies', 0);` cause warnings due to the fact that the session was already active.
The addition of tests would be relevant, but I can't see how to test this layer.
=> fix: Bad session handling for GLPI mode cron

src/Session.php
Since ef93b740eb68e418692149c9991f9fc556febe42.
If the query does not return any rows, we do not enter the case ```$row['count'] === 0``` (because of the trying to access array offset on null error), and therefore the session is not destroyed.
```
glpiphplog.WARNING:   *** PHP Warning (2): Trying to access array offset on null in /home/francois/www/glpi-core/main/htdocs/src/Session.php at line 1096
Backtrace :
src/Session.php:1173                               Session::checkValidSessionId()
src/Glpi/Http/Firewall.php:131                     Session::checkLoginUser()
...nt/ContainerITyWjcI/FirewallProxy683eb58.php:25 Glpi\Http\Firewall->applyStrategy()
src/Glpi/Http/FirewallStrategyListener.php:73      ContainerITyWjcI\FirewallProxy683eb58->applyStrategy() …
```
=> fix: invalid session if count doesn't exists

css/helpdesk_home.scss, phpunit/CommonDropdown.php, phpunit/functional/AgentTest.php, phpunit/functional/ApplianceTest.php, phpunit/functional/ConfigTest.php, phpunit/functional/DocumentTest.php, phpunit/functional/ImpactTest.php, phpunit/functional/Item_OperatingSystemTest.php, phpunit/functional/Item_SoftwareLicenseTest.php, phpunit/functional/Itil_ProjectTest.php, phpunit/functional/KnowbaseItem_CommentTest.php, phpunit/functional/KnowbaseItem_ItemTest.php, phpunit/functional/KnowbaseItem_RevisionTest.php, phpunit/functional/Notification_NotificationTemplateTest.php, phpunit/functional/OperatingSystemArchitectureTest.php, phpunit/functional/OperatingSystemEditionTest.php, phpunit/functional/OperatingSystemKernelTest.php, phpunit/functional/OperatingSystemKernelVersionTest.php, phpunit/functional/OperatingSystemTest.php, src/Ajax.php, src/CommonGLPI.php, src/Glpi/Controller/SelfService/HomeController.php, src/Glpi/SelfService/HomePageTabs.php, templates/pages/self-service/new_home.html.twig, tests/LDAP/AuthLdap.php, tests/cypress/e2e/self-service/home.cy.js
- Reuse GLPI's AJAX tabs
- Tweak display
- Add reminders and RSS feeds as default tabs (they were displayed on the old home page, we don't want to remove this feature)
- Display of the reminder and rss feed tables are not ideal, we probably need to tweak it but it is also used in some others parts of GLPI so it might be best to defer this to another PR
=> Homepage: add proper tabs

phpunit/functional/Glpi/Form/DefaultFormsManagerTest.php, phpunit/functional/Glpi/Form/ServiceCatalog/ServiceCatalogManagerTest.php, src/Glpi/Form/DefaultFormsManager.php, src/Glpi/Form/Destination/AbstractConfigField.php, src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php, src/Glpi/Form/Destination/CommonITILField/EntityField.php, src/Glpi/Form/Destination/CommonITILField/ITILCategoryField.php, src/Glpi/Form/Destination/CommonITILField/ITILCategoryFieldStrategy.php, src/Glpi/Form/Destination/CommonITILField/LocationField.php, src/Glpi/Form/Destination/CommonITILField/OLATTOField.php, src/Glpi/Form/Destination/CommonITILField/OLATTRField.php, src/Glpi/Form/Destination/CommonITILField/RequestSourceField.php, src/Glpi/Form/Destination/CommonITILField/SLATTOField.php, src/Glpi/Form/Destination/CommonITILField/SLATTRField.php, src/Glpi/Form/Destination/CommonITILField/TemplateField.php, src/Glpi/Form/Destination/ConfigFieldInterface.php, src/Toolbox.php, src/Update.php, tests/src/Command/TestUpdatedDataCommand.php, tests/src/FormTesterTrait.php
Add two default forms when installing GLPI or updating to GLPI 11.
The goal is to copy the "old" helpdesk form:
It is split into two Incident/Request forms which are almost identical.
Note that the "associated elements" question is missing because it isn't possible to implement it right now (we will work on that later) and that the picked "watchers" are also not applied into the ticket (not possible yet too).
The default forms themselves are subject to change later as we make the final adjustments before GLPI 11.
Right now, the goal is just to offer the same feature that in GLPI 10 but with two "real" forms.
=> Create default forms on installation or update

phpunit/functional/ITILTemplateTest.php, src/Change.php, src/Problem.php
- It fixes !34638
Some predefined fields from templates were not populated when creating a Problem or Change.
=> fix(ITIL template): predefined fields not set

src/Glpi/Api/HL/Router.php, tests/functional/Glpi/Api/HL/Controller/CoreController.php
Authenticating with the password OAuth flow lets you specify the client ID and secret in the request body or the Authorization header. The HLAPI router was seeing the header and trying to authenticate even though the only legitimate Authorization header would be a Bearer type. Ignoring basic auth lets the data get passed to the `/token` endpoint properly.
=> Ignore basic auth header in HLAPI

phpunit/functional/RuleAssetTest.php, src/RuleAsset.php
- It fixes !34660
Fixed the problem of not being able to use the result of a regular expression in comments during an inventory by adding the Assign a value from a regular expression parameter for comments.
=> Fix impossibility to use regex result in comments

.webpack.config.js
Fixes #17745.
The Catalan locale file is not named according to the corresponding iso code in the `flatpickr` dist archive, and therefore the component translations are not loaded correctly by GLPI in this language.
Using a specific copy instruction to fix the file name fixes this issue.
=> Fix Catalan locale in Flatpickr component

js/modules/Forms/QuestionItem.js, phpunit/GLPITestCase.php, phpunit/functional/CronTaskTest.php, phpunit/functional/Glpi/Form/AnswersSetTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/AssociatedItemsFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/EntityFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/ITILCategoryFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/LocationFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/ValidationFieldTest.php, phpunit/functional/Glpi/Form/FormTest.php, phpunit/functional/Glpi/Form/QuestionType/QuestionTypeItemDropdownTest.php, src/Dropdown.php, src/Glpi/Form/QuestionType/QuestionTypeItem.php
Store itemtype as extra data instead of default value for item question types.
=> refactor(forms): Store itemtype as extra data for item question types

src/Dropdown.php, src/Glpi/Form/DefaultFormsManager.php, src/Glpi/Form/QuestionType/QuestionTypeItemDropdown.php
This PR adds a parameter to bypass right checking in the `Dropdown::getStandardDropdownItemTypes` function.
Without this parameter, we encounter issues with right verification at times when we cannot log in.
For example, when adding a default form during database installation, this form includes a question that checks if the itemtype is valid. It is impossible to log in in this case, but the itemtype is still valid.
=> fix: Add parameter to bypass right checking in Dropdown::getStandardDropdownItemTypes

css/includes/components/_global-menu.scss, templates/layout/parts/menu.html.twig
The horizontal menu was broken on the helpdesk, I've fixed it by:
* Removing the useless tooltips
* Use the correct light colors
* Remove the floating yellow underline
Before: 
After:
=> Fix helpdesk menu

phpstan.neon.dist, src/Glpi/Controller/ApiController.php, src/Glpi/Controller/ApiRestController.php, src/Glpi/Controller/DropdownController.php, src/Glpi/Controller/DropdownFormController.php, src/Glpi/Controller/IndexController.php, src/Glpi/Controller/LegacyFileLoadController.php, src/Glpi/Controller/StatusController.php, src/Glpi/Http/HeaderlessStreamedResponse.php
Fixes #17940
Due to a PHP bug, the usage of `http_response_code()` is not working as expected on PHP-FPM as long as a `header('HTTP/X.X $status $text')` function call as been done. Many of our legacy scripts are using the  `http_response_code()` function and the `Symfony` base respons is calling the `header('HTTP/X.X $status $text')` function.
See https://bugs.php.net/bug.php?id=81451 and https://stackoverflow.com/a/69213593
As a quick fix, I propose to redefine our own `StreamedResponse` class and prevent it to send any headers (we do not use this feature anyway). All usages of the `http_response_code()` in our code will still have to be removed, but with this temporary solution, we can do it step by step, and we give some more time to plugins developpers to do it on their side.
=> Prevent streamed response of legacy scripts to send a status header

templates/components/datatable.html.twig
There are 2 occurences of `Entries to show:` and 1 occurence of `Entries to show: `. The ending space could probably be removed to use the same translatable string.
=> Mutualize translatable string

ajax/asset/customfield.php, ajax/central.php, ajax/commonitilsatisfaction.php, ajax/dashboard.php, ajax/debug.php, ajax/displaypreference.php, ajax/fuzzysearch.php, ajax/getFormQuestionActorsDropdownValue.php, ajax/impact.php, ajax/kanban.php, ajax/pendingreason.php, ajax/rack.php, ajax/search.php, ajax/timeline.php, ajax/treebrowse.php, ajax/webhook.php
Goals, in all `ajax/` files:
* Avoid using `http_response_code()` , and replace with proper exceptions or other kind of features
* Avoid using `exit/die`
=> Replace some exit/die/responses to exception in AJAX controllers

phpunit/GLPITestCase.php, phpunit/functional/TicketTest.php
Add a new helper method to avoid wasting time with `sleep()` during our tests.
=> Avoid using sleep() in tests

src/Session.php, src/User.php
- It fixes -
Add Full structure value in user settings:
=> Feat(user): add default entity value = Full structure

dependency_injection/services.php
Duplicating config has no impact anyway, but it's to avoid written redundancy
=> Remove useless deduplication of web profiler config

phpunit/functional/Glpi/Application/View/Extension/RoutingExtensionTest.php, src/Glpi/Application/View/Extension/RoutingExtension.php, src/Glpi/Config/LegacyConfigProviders.php
The current setup overrides `path` and `url` functions in Twig, and that causes two issues:
* First, the GLPI routing doesn't work the same way than Symfony, so when used with a Symfony route, it generates the wrong path (happens with Symfony's WebProfiler for example)
* Second, if Twig is in `strict` mode, errors are thrown whenever a route path is generated without parameters and the actual route requires parameters
=> Fix routing replacing Symfony's one in Twig 

phpunit/functional/Glpi/Form/Destination/CommonITILField/AssociatedItemsFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/ContentFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/EntityFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/ITILCategoryFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/ITILFollowupFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/ITILTaskFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/LocationFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/OLATTOFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/OLATTRFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/RequestSourceFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/RequestTypeFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/SLATTOFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/SLATTRFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/TemplateFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/TitleFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/UrgencyFieldTest.php, phpunit/functional/Glpi/Form/Destination/CommonITILField/ValidationFieldTest.php, src/Glpi/Form/Destination/AbstractConfigField.php, src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php, src/Glpi/Form/Destination/CommonITILField/EntityField.php, src/Glpi/Form/Destination/CommonITILField/ITILCategoryField.php, src/Glpi/Form/Destination/CommonITILField/LocationField.php, src/Glpi/Form/Destination/CommonITILField/OLATTOField.php, src/Glpi/Form/Destination/CommonITILField/OLATTRField.php, src/Glpi/Form/Destination/CommonITILField/RequestSourceField.php, src/Glpi/Form/Destination/CommonITILField/SLATTOField.php, src/Glpi/Form/Destination/CommonITILField/SLATTRField.php, src/Glpi/Form/Destination/CommonITILField/TemplateField.php
Remove specific `getKey` methods from form destination fields classes.
Use parent method to determine key.
=> refactor(forms): Remove redundant getKey() methods and use the default one

phpunit/GLPITestCase.php, phpunit/functional/DbUtilsTest.php, src/DbUtils.php, src/Glpi/Search/SearchOption.php
We are having github runner shortages so I am taking a (very quick) look on how we could reduce our tests run time.
This optimisation reduce the `SearchTest.php` execution from 18 minutes to 12 minutes on my dev env.
Note: this is a "bad" static cache that we would avoid in a perfect world.
However, it does the works for now and we already have similar caches for others search methods.
Before:
After (edited after new commits):
=> Improve search performances

install/migrations/update_10.0.x_to_11.0.0/form.php, install/mysql/glpi-empty.sql, phpunit/functional/Glpi/Form/DefaultFormsManagerTest.php, src/Glpi/Form/DefaultFormsManager.php, src/Glpi/Form/SelfService/FormTile.php, src/Glpi/Form/SelfService/TilesManager.php, templates/components/helpdesk_forms/forms_list.html.twig, templates/pages/admin/form/service_catalog_tab.html.twig, tests/cypress/e2e/form/service_catalog/service_catalog_tab.cy.js
Use our new illustrations instead of tabler icons in the service catalog.
Note that config is a raw text input, we will have to work on some kind of illustration selector.
This will be done in another PR as I suspect it will be a difficult task to get it right.
Service catalog:
Config:
=> Use illustrations for helpdesk forms instead of icons

src/Webhook.php, tests/functional/Webhook.php
Fixes issue when there are itemtypes that have no API schema associated causing invalid options to remain in the list and cause a PHP error when trying to access getTypeName on an invalid class. Issue noted when custom assets from the `asset_types` config list are added since there is no HLAPI support for them yet.
=> Fix webhook itemtype list when itemtype has no schema

src/Html.php
The automatic flush of the output at the end of the `Html::includeHeader()` method was done to permit to the browser to download the CSS/JS resources earlier, before the rest of the page content is computed. It was probably considered as a good idea when it has been done, but I am not sure it is still necessary to do this.
Indeed, for most of the pages, the computation of the content is pretty fast, and for the slow pages, as the JS/CSS resources are probably already in cache, trying to load them earlier will probably does not change much.
I propose to remove this behaviour as it is not compatible with the construction of a base `Symfony` response object and forces us to use streamed responses.
Also, it cannot prevent this output to be sent in the PHPUnit output, even using the …
=> Remove automatic flush of the header

ajax/dropdownRubDocument.php, src/Document.php
- It fixes !34700
The document dropdown failed to load with an initial value (either the default or a previously saved value). This issue occurs with the Fields plugin, which allows adding a document-type field that leverages the core's dropdown functionality.
=> fix(document): display stored value

phpunit/functional/RuleTest.php, src/RuleAction.php, src/RuleTicket.php
- It fixes !34685
In the business rules for tickets, it is possible to remove the SLA by assigning an empty value, but this does not remove the calculated date on the ticket. Just like in the interface, removing the SLA doesn't automatically delete the corresponding date (a confirmation message appears). I propose adding an action to also delete this date when the SLA is removed.
=> fix(rule ticket): delete SLA date

src/WifiNetwork.php
Not expected to be officially adopted until 2028. While I hope GLPI 11 is obsolete by then, there is no harm in adding the protocol version now as the IEEE designation shouldn't change.
Also fixed potential issue with the "Monitor" mode translation. It had been changed a few years ago to use the Monitor itemtype name (Computer displays) and that may be an issue with non-English locales. For consistency, I changed all WiFi card mode strings to use the "wifi_card_mode" context.
=> Add WiFi 8 version

dependency_injection/web_profiler.php
Now that session expirations are generating a redirection that can be intercepted by the Symfony profiler, it is a pain to have this feature enabled everytime. I think it is useful only for specific debugging and developers can activate it when they need it.
=> Do not intercept redirects on dev env

src/Ticket.php
Originally was just going to fix a typo `Beeing -> Being`, but the label still didn't match the form used with the other rights like "See assigned" so it was changed to "Be in charge" instead. So "User can Be in charge" not "User can Being in charge".
=> Fix ticket own right label

phpunit/functional/HtmlTest.php, src/Html.php
The strict validation of the referer introduced in #17938 prevents GLPI from working correctly when it is accessed with an URL that does not match the configured base URL. This could be a problem in many legitimate cases :
- a sysadmin is preparing a migration to a new server with a GLPI connected to the production database, but using the server IP to access it until the DNS switch;
- GLPI is accessible at a different address whether it is accessed by the company workers from the local network (`https://support/`) or by the customers (`http://company.tld/support/`).
We could not rely on the `Host` header to handle this, as its value could be changed too.
The initial problem was the fact that the referer value could contain some JS code instead of a valid URL. I propose to keep only that …
=> Less strict validation of the referer URL

tests/cypress/e2e/error_page.cy.js
The `error_page` test seems to fail often. I do not understand why, but I suspect a race condition between debug mode disabling and debug bar ajax callbacks.
Blocking requests to the `ajax/debug.php` endpoint could fix the issue.
=> Try to fix error page flaky test

templates/components/itilobject/fields_panel.html.twig
Hides the entity notes section of the info panel when there are no notes to display
Fixes #17855
=> Hide empty note section in ticket panel

src/Html.php
Since 10.0.6, all of the "extra" required libraries for dashboards were always being included even when `dashboard` wasn't in the array of requested libraries. In a non-archive release (so nothing minified) this saves approximately 800kb on non-dashboard pages. Most of the savings is from not importing `echarts`.
=> Remove unneeded dashboard JS imports

.github/actions/test_tests-phpunit.sh
This PR allows executing the PHPUnit script locally with commands like this:
```bash
docker compose exec app .github/actions/test_tests-phpunit.sh # add other args...
```
Mainly to be able to easily run a single test class/file/method/dataset.
=> [11.0] Fix minor issues in phpunit script

CHANGELOG.md, install/migrations/update_10.0.x_to_11.0.0/notifications.php, install/mysql/glpi-empty.sql, phpunit/functional/NotificationTargetTest.php, src/NotificationTarget.php, templates/pages/setup/notification/recipients.html.twig, tests/functional/NotificationTargetKnowbaseItem.php
Adds a new field to the Recipients tab of notifications to allow specifying exclusions. For example, the "New Ticket" notification may be configured to be sent to the ticket's requesters. However, there may be a specific group or profile that you don't want to be notified about this event. A real-life case is within an education environment where students report issues to a physical helpdesk. They may have user accounts within GLPI from LDAP and therefore also emails. Previously, you couldn't have the students added to the tickets as the requester for tracking purposes and also avoid sending them the emails when the staff …
=> Add recipient exclusions for notifications

src/Dashboard/Provider.php
- It fixes !34859
There was a discrepancy between the number displayed on a 'bigNumber' card and the number of results shown when clicking on the card, because the recursion of parent entities was not considered.
=> Fix (dashboard): entities restrict criteria on bigNumber card

src/Auth.php, src/Glpi/Api/HL/Controller/CoreController.php, src/Glpi/Api/HL/Middleware/CookieAuthMiddleware.php
=> Fix authorizationCode flow on HL API documentation

src/AuthLDAP.php, src/CommonGLPI.php, src/Glpi/Inventory/Conf.php, tests/functional/ValidatorSubstitute.php
Ensures that  `CommonGLPI::createTabEntry()` produces a safe HTML code.
=> Fix HTML escaping in `CommonGLPI::createTabEntry()`

src/Glpi/Exception/AuthenticationFailedException.php
The constructor signature was not correct.
It fixes the following error:
```
PHP Deprecated function (8192): Exception::__construct(): Passing null to parameter #2 ($code) of type int is deprecated in /var/www/glpi/src/Glpi/Exception/AuthenticationFailedException.php at line 45
```
=> Fix `AuthenticationFailedException` constructor

src/Glpi/Config/LegacyConfigurators/StandardIncludes.php
It fixes #18013.
In contrary to the update requirement checks, the maintenance mode checks must be done on all URLs, except CSS and locales that may be required to correctly display the "maintenance mode" page.
=> Fix maintenance mode checks on index page

src/Document.php
- It fixes !34821
The document fields could not be passed as readonly, the problem arose when a user wanted to pass a Fields field as readonly but this failed. And the field could still be modified.
=> Fix document fields readonly

front/central.php, front/helpdesk.public.php, phpunit/functional/EntityTest.php, src/Entity.php, src/Glpi/Controller/Session/ChangeEntityController.php, templates/layout/parts/profile_selector.html.twig, templates/layout/parts/profile_selector_form.html.twig, tests/cypress/e2e/entities_selector.cy.js, tests/cypress/support/commands.d.ts, tests/cypress/support/commands.js
Same as #18057 but for entities changes.
=> Add proper endpoint for entity selection

.phpstan-baseline.php, ajax/displaypreference.php, css/helpdesk_home.scss, install/empty_data.php, install/migrations/update_10.0.x_to_11.0.0.php, install/migrations/update_10.0.x_to_11.0.0/displaypreference.php, install/mysql/glpi-empty.sql, src/CommonDBTM.php, src/DBmysql.php, src/DisplayPreference.php, src/Glpi/Dashboard/Grid.php, src/Glpi/Search/SearchEngine.php, src/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php, src/Migration.php, src/Ticket.php, templates/components/search/displaypreference_config.html.twig, templates/components/search/displaypreference_modal.html.twig, tests/cypress/e2e/search/display_preferences.cy.js, tests/cypress/e2e/self-service/home.cy.js, tests/cypress/support/commands.js, tests/functional/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
- Allow specific display preferences to be configured for the `helpdesk` interface.
- This view is only added for itemtypes that define a `supportHelpdeskDisplayPreferences()` method that return `true` (so only ticket for now).
- There are no restrictions on the criteria that can be selected, despite some ticket's search criteria being disabled for the helpdesk interface (see `Ticket::rawSearchOption()`).
This is because:
* It is hard to filter the selectable criteria depending on the interface because of bad session management in the code.
We would need a proper service that accept a given interface and then return the available search options.
Instead, we have a direct call to `Session::getCurrentInterface()` deeply nested into the stack trace, which mean passing a specific interface …
=> Allow specific display preferences to be configured for the helpdesk

phpunit/functional/ProjectTest.php, src/Features/Clonable.php
Fixes #18123.
The `$override_input` parameter of the `clone()` method is used to inject specific input defined by the user when an item is created from a template. Most of the time, il will already be escaped automatically by the global sanitization logic.
`Sanitizer::sanitize()` is designed to prevent double escaping/encoding. I propose to use it instead of `Toolbox::addslashes_deep()` to fix the issue.
=> Prevent double escaping of multiline when cloning an item
