- js/form_editor_controller.js
- templates/pages/admin/form/form_section.html.twig
> Forms: add "Merge with previous section" action

- ajax/dropdownLocation.php
- src/DCRoom.php
- templates/generic_show_form.html.twig
- templates/pages/management/dcroom.html.twig
> DCRoom Twig

- CHANGELOG.md
- ajax/viewsubitem.php
- css/includes/_palette_dark.scss
- src/Planning.php
- src/PlanningRecall.php
- src/Reminder.php
- src/ReminderTranslation.php
- templates/central/lists/table.html.twig
- templates/components/form/basic_inputs_macros.html.twig
- templates/pages/setup/general/assistance_setup.html.twig
- templates/pages/tools/reminder.html.twig
- templates/pages/tools/reminder_planning.html.twig
- templates/pages/tools/reminder_translation.html.twig
- Move reminder, reminder planning, central tables, and reminder translation UI to twig
Other fixes included:
- Background of tooltips was too transparent in dark themes (issue on `main` only)
- Planning working days had the wrong value for Sunday (issue on `main` only)
> Reminder UI Review/Twig

- src/Contract.php
| Fixed tickets | !31880
Fixes the expiration date in the search to match the value in the contract
Example:
Before:
(End date = Expiration)
After:
> fix(contrat): expiration date in search

- js/form_editor_controller.js
- templates/pages/admin/form/form_editor.html.twig
> Forms: track unsaved changes

- ajax/central.php
- css/includes/pages/_search.scss
- src/Central.php
- src/Change.php
- src/CommonITILTask.php
- src/Problem.php
- src/Project.php
- src/ProjectTask.php
- src/Search/Provider/SQLProvider.php
- src/Ticket.php
- tests/functional/Project.php
- tests/functional/ProjectTask.php
| Q | A
| Bug fix?      | no 
| New feature?  | yes 
| BC breaks?    | no 
| Deprecations? | no 
| Tests pass?   | yes 
Two new summary tables have been added to the personal and group view, displaying information on the user's/group's unfinished projects and the current project tasks for which the user/group is assigned.
> Adding dashboard for project and projecttask in personal and groups view

- js/form_editor_controller.js
- src/Controller/CommonAjaxController.php
- src/Form/Form.php
- src/Html.php
- src/Session.php
- tests/functional/Session.php
> Forms: improve error detection + minor bugfixes

- js/modules/Kanban/Kanban.js
- src/CommonITILObject.php
> Fix category metadata in itil kanban cards

- src/FieldUnicity.php
> FieldUnicity Twig UI

- ajax/updateTranslationValue.php
- src/Application/View/Extension/DataHelpersExtension.php
- src/DropdownTranslation.php
- templates/pages/setup/dropdowntranslation.html.twig
> DropdownTranslation Twig UI

- inc/relation.constant.php
- install/migrations/update_10.0.x_to_11.0.0/form.php
- install/mysql/glpi-empty.sql
- src/Form/AnswersHandler/AnswersHandler.php
- src/Form/Destination/FormDestination.php
- src/Form/Form.php
- src/Form/Section.php
- tests/DbTestCase.php
- tests/functional/Glpi/Form/Form.php
- tests/src/FormTesterTrait.php
Handle cascade deletion of forms items (questions, sections, ...).
> Forms: cascade deletion and database simplification

- src/ConsumableItem.php
> fix(consumable item): restore cloning

- src/NetworkPort.php
| Fixed tickets | !31937
Columns from plugins could be added, but the column was not visible in the table.
> fix(network port): items to show

- src/Search.php
- tests/functional/Search.php
| Fixed tickets | !31814
The search for `&` in titles displayed too many results such as `>` or `<`:
> fix(search): contains &

- src/ProjectTask.php
- tests/functional/ProjectTask.php
The actual dates of project tasks are automatically initialized according to the percentage of sub-tasks performed.
Start date initialized when percentage exceeds 0% and end date when equal to 100%.
> Automatic evolution of project task dates

- src/GLPINetwork.php
- templates/pages/setup/general/glpinetwork_setup.html.twig
Move the GLPI Network configuration tab UI to Twig
> GLPINetwork config twig

- js/form_editor_controller.js
Clean up a few technical TODOs meant to improve code stability.
> Clean up a few technical TODOs

- src/Dropdown.php
| Fixed tickets | #16768, #16769
> Fix assign field when suppliers assign is available

- src/CommonITILObject.php
- src/Ticket.php
- tests/functional/Ticket.php
| Fixed tickets | #16773
This reverts commit 09406faa84a24a220da26021a63f8fc4bfe31352.
> Revert "Fixed ticket creation with closed status to exclude technician"

- src/Session.php
- tests/functional/Session.php
> Fix active entities filtering

- src/CommonITILObject.php
- src/Form/AnswersSet.php
- src/Form/Destination/AbstractCommonITILFormDestination.php
- src/Form/Destination/AbstractFormDestinationType.php
- src/Form/Destination/FormDestination.php
- src/Form/Destination/FormDestinationChange.php
- src/Form/Destination/FormDestinationInterface.php
- src/Form/Destination/FormDestinationProblem.php
- src/Form/Destination/FormDestinationTicket.php
- src/Form/Destination/FormDestinationTypeManager.php
- src/Ticket.php
- templates/pages/admin/form/form_destination.html.twig
- templates/pages/admin/form/form_destination_commonitil_config.html.twig
- tests/functional/Glpi/Form/Destination/FormDestinationChange.php
- tests/functional/Glpi/Form/Destination/FormDestinationProblem.php
- tests/functional/Glpi/Form/Destination/FormDestinationTicket.php
- tests/functional/Glpi/Form/Destination/FormDestinationTypeManager.php
- tests/src/Form/Destination/AbstractFormDestinationType.php
Add support for all CommonITIL "destination" types and prepare the ground for their future configuration.
Once again, reviews are only needed for the technical side IMO.
UX can be dealt with later as we still lack most features for this page.
> Forms: support `Change` and `Problem` destinations

- front/asset/asset.form.php
- src/Asset/Asset.php
- tests/units/Glpi/Features/AssignableAsset.php
> Add READ/UPDATE assigned rights to generic assets

- js/form_editor_controller.js
- templates/pages/admin/form/form_section.html.twig
Add a new "Duplicate section" action + better error handling.
> Forms: duplicate section

- src/CommonItilObject_Item.php
- src/DomainRecord.php
- src/DomainRecordType.php
- src/Domain_Item.php
- src/Dropdown.php
- templates/pages/management/domainrecord.html.twig
- templates/pages/management/domainrecordtype_helper.html.twig
> Domain Twig UI

- CHANGELOG.md
- src/Search.php
- src/Search/Provider/SQLProvider.php
> Fix dropdown translations on search results

- src/Stat.php
| Fixed tickets | #16679 
Introduced in 6cf265936c4f6edf7dea7c78b12e46d75b94d9b0
> Missing ID in generated link

- front/item_devicecamera.form.php
> Add missing device camera item form

- templates/components/form/link_existing_or_new.html.twig
> Fix translation

- inc/define.php
- install/empty_data.php
- install/migrations/update_10.0.x_to_11.0.0/user.php
- install/mysql/glpi-empty.sql
- js/modules/Search/ResultsView.js
- js/modules/Search/Table.js
- templates/components/pager.html.twig
- templates/components/search/controls.html.twig
- templates/components/search/display_data.html.twig
- templates/pages/setup/general/preferences_setup.html.twig
- tests/js/modules/Search/Table.test.js
Requester after an early internal review of 11.0 UI.
> add option to show pagination on top of search results

- src/Asset/AssetDefinition.php
> sort capacities by label

- src/Asset/Capacity/AbstractCapacity.php
- src/Asset/Capacity/CapacityInterface.php
- src/Asset/Capacity/HasAntivirusCapacity.php
- src/Asset/Capacity/HasAppliancesCapacity.php
- src/Asset/Capacity/HasCertificatesCapacity.php
- src/Asset/Capacity/HasContractsCapacity.php
- src/Asset/Capacity/HasDatabaseInstanceCapacity.php
- src/Asset/Capacity/HasDocumentsCapacity.php
- src/Asset/Capacity/HasDomainsCapacity.php
- src/Asset/Capacity/HasHistoryCapacity.php
- src/Asset/Capacity/HasInfocomCapacity.php
- src/Asset/Capacity/HasKnowbaseCapacity.php
- src/Asset/Capacity/HasLinksCapacity.php
- src/Asset/Capacity/HasNetworkPortCapacity.php
- src/Asset/Capacity/HasNotepadCapacity.php
- src/Asset/Capacity/HasOperatingSystemCapacity.php
- src/Asset/Capacity/HasRemoteManagementCapacity.php
- src/Asset/Capacity/HasVirtualMachineCapacity.php
- src/Asset/Capacity/HasVolumesCapacity.php
- src/Asset/Capacity/IsRackableCapacity.php
- src/Asset/Capacity/IsReservableCapacity.php
- src/ItemVirtualMachine.php
- src/Item_RemoteManagement.php
- src/OperatingSystem.php
- templates/pages/admin/assetdefinition/capacities.html.twig
- tests/functional/Item_OperatingSystem.php
- tests/functional/OperatingSystem.php
I also adapted a few icons from core classes
> add icons to capacities

- js/RichText/ContentTemplatesParameters.js
- js/RichText/UserMention.js
- package-lock.json
- package.json
- src/Html.php
| Fixed tickets | #16859
Existing BC breaks seems acceptable to me.
See release notes: https://www.tiny.cloud/docs/tinymce/latest/7.0-release-notes/
See migration guide: https://www.tiny.cloud/docs/tinymce/latest/migration-from-6x
> Upgrade `tinymce`

- CHANGELOG.md
- inc/db.function.php
- src/DbUtils.php
- src/NetworkAlias.php
- src/NetworkName.php
- src/NetworkPort.php
- src/NetworkPortConnectionLog.php
- src/NetworkPortEthernet.php
- src/NetworkPortMigration.php
- src/NetworkPortWifi.php
- src/NetworkPort_Vlan.php
First pass through network port classes before UI work. UI migrations will be a separate PR after this.
> Network port classes cleanup/review

- src/Search.php
- tests/functional/Search.php
> Fix sorting on users fields not using another table

- templates/layout/page_card_notlogged.html.twig
> Include fuzzy.js on non logged pages; closes #16758

- src/RSSFeed.php
> Fix wrong replacement; closes #16726

- src/RuleMailCollectorCollection.php
| Fixed tickets | !32409
Prevent this warning message:
```
glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "mailcollector" in .../src/RuleMailCollectorCollection.php at line 57
Backtrace :
src/RuleCollection.php:1766                        RuleMailCollectorCollection->prepareInputDataForProcess()
src/RuleCollection.php:1921                        RuleCollection->testAllRules()
front/rulesengine.test.php:82                      RuleCollection->showRulesEnginePreviewResultsForm()
public/index.php:82                                require()
glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "_users_id_requester" in …
```
> fix(rule engine): warning message

- CHANGELOG.md
- src/Document.php
- src/Document_Item.php
- src/Dropdown.php
- templates/pages/management/document.html.twig
- templates/pages/management/document_item.html.twig
- tests/functional/Dropdown.php
> Document forms and lists Twig

- src/Entity.php
| Fixed tickets | !32361
In the entity search, the Entity for software creation column did not display the same value as in the entity file.
> fix(entity): Entity for software creation

- css/includes/_palette_dark.scss
| Fixed tickets | !32421
#16917
> Update user icon text color in dark theme

- src/Item_SoftwareLicense.php
- src/Item_SoftwareVersion.php
- src/Software.php
- src/SoftwareLicense.php
- src/SoftwareVersion.php
Work done before the UI migrations related to Software.
> Clean Software Code

- src/CommonDBTM.php
- src/LevelAgreement.php
- src/OLA.php
- src/OlaLevel.php
- src/OlaLevel_Ticket.php
- src/SLA.php
- src/SLM.php
- src/SlaLevel.php
- src/SlaLevel_Ticket.php
Work done before the UI migrations related to SLA/OLA/SLM.
> Clean SLM code

- CHANGELOG.md
- src/Planning.php
- src/PlanningExternalEvent.php
- src/PlanningRecall.php
Work done before the UI migrations related to Planning.
> Clean Planning Code

- src/User.php
> Ensure process rules are not run twice; closes #16936

- src/Search.php
- tests/functional/Search.php
| Fixed tickets | !32550
Prevent SQL error, on search without group by
```
glpisqllog.ERROR: DBmysql::doQuery() in /home/ubuntu/Dev/GLPI/10.0-bugfixes/src/DBmysql.php line 403
SQL: SELECT DISTINCT `glpi_computers`.`id` AS id, 'glpi' AS currentuser,
`glpi_computers`.`entities_id`, `glpi_computers`.`is_recursive`,  `glpi_computers`.`name` AS `ITEM_Computer_1`,
`glpi_computers`.`id` AS `ITEM_Computer_1_id`,
`glpi_entities`.`completename` AS `ITEM_Computer_80`,  `glpi_manufacturers`.`name` AS `ITEM_Computer_23`,  `glpi_computermodels`.`name` AS `ITEM_Computer_40`,  `glpi_states`.`completename` AS `ITEM_Computer_31`, …
```
> fix(search): order by actor without join table

- src/NetworkPortType.php
- tests/functional/Glpi/Inventory/Assets/NetworkPort.php
> Fix and check instanciation type is properly set

- src/ITILCategory.php
- src/RefusedEquipment.php
- src/State.php
- src/Supplier.php
> Clean Misc code

- src/Profile.php
- tests/functional/Profile.php
> Clean Profile code

- CHANGELOG.md
- front/stat.graph.php
- src/Stat.php
- tests/functional/Glpi/Api/HL/Controller/ReportController.php
> Clean Stat code

- src/Application/View/Extension/DataHelpersExtension.php
- src/RSSFeed.php
- templates/pages/tools/rss_form.html.twig
Based on https://github.com/glpi-project/glpi/pull/16956
> RSSFeed Twig UI

- js/common.js
- js/form_editor_controller.js
- src/Dropdown.php
- src/Form/QuestionType/QuestionTypeCategory.php
- src/Form/QuestionType/QuestionTypeUrgency.php
- src/Html.php
- tests/functional/Glpi/Form/AnswersSet.php
- tests/functional/Glpi/Form/QuestionType/QuestionTypesManager.php
Added `Urgency` category and related sub-question type : `Urgency`
> feat(forms): Adding urgency category and related question type

- src/DBConnection.php
> Fix DB slave sync status check

- src/Application/View/Extension/DataHelpersExtension.php
- templates/pages/setup/general/glpinetwork_setup.html.twig
> feat: add subscription period dates

- src/Search.php
- tests/functional/Search.php
> Ensure value is numeric searching in validation status

- src/DbUtils.php
- templates/components/user/info_card.html.twig
> (Feature) Adding id to user tooltip card

- src/Form/QuestionType/AbstractQuestionType.php
- src/Form/QuestionType/AbstractQuestionTypeActors.php
- src/Form/QuestionType/AbstractQuestionTypeShortAnswer.php
- src/Form/QuestionType/QuestionTypeDateTime.php
- src/Form/QuestionType/QuestionTypeLongText.php
- src/Form/QuestionType/QuestionTypeUrgency.php
| Q | A
| ------------- | --- 
| Bug fix?      | no 
| New feature?  | no 
| BC breaks?    | no 
| Deprecations? | no 
| Tests pass?   | yes 
Addition of an abstract parent class for question types.
This class is used to define default behaviors for certain interface methods.
> chore: Adding a new abstract class as base class for form question types

- css/includes/components/_richtext.scss
| Fixed tickets | !32710
Before :
After :
> Fix the position of the tinymce editor resize button

- src/RuleImportEntity.php
Bug noticed during UI work on main.
> Fix missing import_item array property error

- src/Entity.php
- src/Features/Clonable.php
> Fix cloned entity tree cache

- front/domainrecord.form.php
> Prevent rawurlencode notice on domain records form

- src/DomainRecord.php
- src/Dropdown.php
- src/Group_User.php
> Pass request parameters instead of array of used IDs

- src/NetworkPortType.php
- tests/functional/NetworkPortType.php
> Set radiomac port type importable, and instance of wifi; closes #16981

- CHANGELOG.md
- src/Entity.php
- src/RuleAction.php
- tests/functional/Entity.php
Some non-UI work that was done while working on #17023.
> Clean Entity Code

- js/common.js
- src/Reservation.php
- src/ReservationItem.php
- src/Toolbox.php
- src/User.php
- templates/components/datatable.html.twig
- templates/components/form/buttons.html.twig
- templates/pages/tools/find_available_reservation.html.twig
| Bug fix?      |no
Based on #16954
Intended UI/UX changes:
- The "Find a free item in a specific period" form now shows a cancel button to bring back the "View calendar for all items" and "Find a free item in a specific period" buttons without needing to reload the page.
- Actions to prohibit reservations and make unavailable now show in `danger` styles
> Reservation Twig UI

- README.md
> Update PHP support in readme

- .github/workflows/ci.yml
> Test MySQL 8.4 LTS compatibility

- src/Ticket.php
| Fixed tickets | !32642
Add this option:
> feat(crontask): add limit option to purgeticket

- src/Html.php
- src/Stat.php
> Fix stats exports

- src/HTMLTableBase.php
- src/HTMLTableCell.php
- src/HTMLTableEntity.php
- src/HTMLTableGroup.php
- src/HTMLTableHeader.php
- src/HTMLTableMain.php
- src/HTMLTableRow.php
- src/HTMLTableSubHeader.php
- src/HTMLTableSuperHeader.php
- src/Migration.php
> HTML table and Migration Twig UI

- front/form/form.form.php
- templates/components/form/basic_inputs_macros.html.twig
- templates/pages/admin/form/form_editor.html.twig
- tests/cypress/e2e/form/form_editor.cy.js
First step into adding complete E2E testing to the form editor interface.
> Add E2E tests for form creation

- src/ProjectTask_Ticket.php
> Fix father task link

- css/install.scss
- install/install.php
Also sets the HTML document language to en_GB instead of `fr` since the text is always English.
> Fix install styles

- js/src/vue/Debug/Toolbar.vue
- js/src/vue/Debug/Widget/ClientPerformance.vue
- js/src/vue/Debug/Widget/HTTPRequests.vue
- js/src/vue/Debug/Widget/ProfilerTable.vue
- js/src/vue/Debug/Widget/SearchOptions.vue
- tests/cypress/e2e/DebugMode/debug_bar.cy.js
- tests/cypress/e2e/DebugMode/debug_mode.cy.js
- tests/cypress/support/commands.js
Add E2E tests that cover toggling debug mode and the functionality of the debug toolbar.
> Debug mode E2E tests

- CHANGELOG.md
- front/devices.php
- front/ldap.group.import.php
- front/lostpassword.php
- front/migrationcleaner.php
- front/plugin.php
- front/rule.backup.php
- front/rule.common.php
- front/rule.test.php
- front/rulesengine.test.php
- front/search.php
- front/tracking.injector.php
- front/transfer.action.php
- front/updatepassword.php
- src/Html.php
- src/Item_Devices.php
- src/Item_Rack.php
- src/MassiveAction.php
- src/Software.php
- src/User.php
- templates/forgotpassword.html.twig
- templates/password_form.html.twig
- templates/updatepassword.html.twig
- Converted and unified the UI of the various forgot/update/init password forms.
- Misc Twig/sanitization
> Password forms Twig UI + Misc

- src/QueryParam.php
> Constructor signature should not have changed in deprecated class

- .github/workflows/nightly_build.yml
Should fix main branch nightly build
> Rely on supported PHP version

- css/includes/components/form/_form-editor.scss
- templates/pages/admin/form/form_destination.html.twig
- tests/cypress/e2e/form/form_destination.cy.js
[Capture vidéo du 16-05-2024 10:21:38.webm](https://github.com/glpi-project/glpi/assets/42278610/eee534ae-dcf0-42e1-bbcb-2d80cc674f9f)
> feat(forms): Allow modification of destination form name

- js/common.js
The condition in this function was inverted and did not work as expected.
> Fix getUUID function

- tests/units/Glpi/Form/Form.php
> Improve testCleanDBonPurge tests

- src/CommonDevice.php
| Fixed tickets | https://glpi.userecho.com/communities/1/topics/2347-components-display-number-of-items
> Add search option for number of component items

- templates/pages/setup/setup_notifications.html.twig
> Fix(Notification): Fix CSS

- templates/pages/setup/mailcollector/server_config_fields.html.twig
Fix input overflow
Before : 
After : 
> Fix(Receiver): Fix connections option UI

- src/RSSFeed.php
> Fix(Central): fix RSSFeed href

- src/Group.php
> Fix LDAP groups import link

- inc/config.php
> Fix update page

- src/Api/HL/Controller/ITILController.php
Add missing user, duration, state and category properties.
> [HLAPI] Add more ITIL task properties

- src/Api/API.php
| Fixed tickets | !33104
Check that $value is an integer for expand_dropdowns as above for get_hateoas
> fix(API): expand_dropdowns with multiselect

- install/migrations/update_10.0.15_to_10.0.16/queuednotifications.php
- install/mysql/glpi-empty.sql
> fix(queuednotifications): add index

- src/Profile_User.php
> Handle missing profile_user fields

- .github/actions/docker-compose-app.yml
- .github/workflows/branch_build.yml
- .github/workflows/nightly_build.yml
Follows https://github.com/glpi-project/docker-images/pull/125
> Update CI mount target

- .devcontainer/.gitignore
- .devcontainer/conf/php/Dockerfile
- .devcontainer/conf/php/php-dev.ini
- .devcontainer/conf/php/xdebug.ini
- .devcontainer/docker-compose.override.yml.dist
- .devcontainer/docker-compose.yml
Import of the fixes from #17236
> Fix devcontainers setup

- .devcontainer/conf/php/Dockerfile
> Set the `GLPI_ENVIRONMENT_TYPE` env var in dev container

- templates/components/itilobject/fields_panel.html.twig
> Fix contract dropdown in ticket creation

- js/common.js
> Fix `setupAdaptDropdown` setValue binding

- .devcontainer/conf/php/php-dev.ini
> Fix xdebug loaded too many times in devcontainer

- .github/workflows/ci.yml
> Test MariaDB 11.4 LTS

- tests/functional/Glpi/Form/Destination/FormDestinationChange.php
- tests/functional/Glpi/Form/Destination/FormDestinationProblem.php
- tests/functional/Glpi/Form/Destination/FormDestinationTicket.php
- tests/src/Form/Destination/AbstractFormDestinationType.php
Merge some duplicated tests, will make maintaining them easier in the future.
> Merge identical destination tests

- tests/cypress/e2e/form/form_editor.cy.js
- tests/cypress/support/commands.js
Simpler alternative to #17014.
> Cache cypress session across specs

- src/Auth.php
- src/System/Requirement/SessionsSecurityConfiguration.php
- tests/functional/Glpi/System/Requirement/SessionsSecurityConfiguration.php
| Fixed tickets | #17312
Initially done in #17201 for the `main` branch.
> Fix session configuration directives handling

- CHANGELOG.md
- src/Rule.php
If we consider this information as valuable, we could move it in the main form. We could also drop it completely.
> Drop Rule debug tab

- CHANGELOG.md
- src/CommonGLPI.php
Follows #17293, #17297, #17311 and #17317.
> Drop debug tab

- CHANGELOG.md
- src/Rule.php
- src/RuleCommonITILObject.php
- src/RuleDictionnarySoftware.php
- src/RuleDictionnarySoftwareCollection.php
- src/RuleImportAsset.php
- src/RuleRight.php
- templates/components/form/buttons.html.twig
- templates/pages/admin/rules/form.html.twig
- templates/pages/admin/rules/preview_criteria.html.twig
- templates/pages/admin/rules/ruleright_form.html.twig
> More Rules UI Work

- src/Glpi/Api/HL/Controller/AssetController.php
- tests/functional/Glpi/Api/HL/Controller/AssetController.php
> Add endpoints for rack items

- src/CommonITILObject.php
> Display the author of each change in the ticket timeline

- front/item_plug.form.php
- inc/relation.constant.php
- install/migrations/update_10.0.x_to_11.0.0/plugs.php
- install/mysql/glpi-empty.sql
- src/Glpi/Api/Deprecated/Pdu_Plug.php
- src/Item_Plug.php
- src/PDU.php
- src/Pdu_Plug.php
- src/Plug.php
- src/autoload/CFG_GLPI.php
- tests/functional/Document.php
> Plugs genericity

- src/CommonITILObject.php
> Fix right check used for _canupdate ITIL flag

- src/CronTaskLog.php
https://github.com/glpi-project/glpi/pull/17350#pullrequestreview-2138743190
> Make CronTaskLog extend CommonDBChild

- src/Html.php
- tests/functional/Html.php
> Test was not correctly executed

- src/Inventory/Asset/MainAsset.php
- tests/functional/Glpi/Inventory/Inventory.php
| Fixed tickets | #17276
No idea why it was explicitly disabled.
> Add test, re-enable partial users

- tests/cypress/e2e/form/form_editor.cy.js
Add E2E test to confirm questions can be deleted.
I recommend reviewing with the "hide white space" option enabled to get a clearer view as I reorganized some lines to make the test case more readable.
> Form editor: test question deletion

- src/Html.php
- src/Plugin/Hooks.php
- templates/layout/parts/head.html.twig
New hooks for inserting header tags via plugins
> Allow plugins to add custom header tags

- src/Glpi/Asset/Capacity/HasPlugCapacity.php
- src/Item_Plug.php
- tests/functional/Glpi/Asset/Capacity/HasPlugCapacity.php
> Add plugs capacity

- src/Computer.php
- src/Glpi/Asset/Capacity/HasSocketCapacity.php
- src/Glpi/Search/SearchOption.php
- src/Glpi/Socket.php
- src/NetworkEquipment.php
- src/PassiveDCEquipment.php
- src/Peripheral.php
- src/Phone.php
- src/Printer.php
- templates/pages/assets/cable.html.twig
- tests/functional/Glpi/Asset/Capacity/HasSocketCapacity.php
> Add sockets capacity

- src/ItemAntivirus.php
- templates/components/form/item_antivirus_item.html.twig
I need it for the print preview functionality because some tables are in twig and others are not, which makes the preview display complicated to modify effectively.
**Before**
**After**
> (Enhancement) Antivirus item twig update

- src/CommonITILValidation.php
- src/Glpi/Search/Provider/SQLProvider.php
| Fixed tickets | !33216
A new search option has been added to display both the user with his link and the current status of his validation.
> Add status by users search option

- src/ItemVirtualMachine.php
- templates/components/form/item_virtualmachine.html.twig
I need it for the print preview functionality because some tables are in twig and others are not, which makes the preview display complicated to modify effectively.
**Before**
**After**
> (enhancement) ItemVirtualMachine twig update

- tests/bootstrap.php
Same as #17455 for 10.0/bf branch
> Remove reference to moved file

- tools/cachebench.php
- tools/fake_metrics.php
- tools/fk_generate.php
- tools/getsearchoptions.php
- tools/testmail.php
- tools/update_registered_ids.php
These scripts were not compatible with the new GLPI bootstraping logic.
> Fix dev tools scripts

- src/Glpi/Cache/CacheManager.php
- src/Glpi/Kernel/Kernel.php
> Use `GLPI_CACHE_DIR` and `GLPI_LOG_DIR` values for the Kernel dir definitions

- inc/define.php
| Fixed tickets | !33725
Adds the ability to link an application to a project:
> feat(project): add appliance

- dependency_injection/legacyConfigProviders.php
- src/DBConnection.php
- src/Glpi/Config/LegacyConfigurators/AssetsAutoloader.php
- src/Glpi/Config/LegacyConfigurators/AssetsBootstrap.php
- src/Glpi/Config/LegacyConfigurators/StandardIncludes.php
- src/Glpi/Console/Application.php
- templates/layout/parts/page_header.html.twig
- templates/layout/parts/page_header_empty.html.twig
> Fix `SKIP_UPDATES` behaviour

- src/Item_RemoteManagement.php
- templates/components/datatable.html.twig
- templates/components/form/item_remotemanagement_form.html.twig
- templates/components/form/item_remotemanagement_list.html.twig
> Item_Remotemanagement twig update

- ajax/timeline.php
> slight improvement to handling task state toggle ajax

- src/NetworkName.php
> Fix missing pager for networkname lists

- templates/components/form/basic_inputs_macros.html.twig
> fix double escape of field helper content

- src/ContentTemplates/Parameters/TicketParameters.php
- tests/functional/Glpi/ContentTemplates/Parameters/TicketParameters.php
> Fix KB ID in templates

- templates/components/form/basic_inputs_macros.html.twig
> remove border radius from color inputs

- templates/components/form/fields_macros.html.twig
> adjust largetitle spacing

- templates/components/itilobject/service_levels.html.twig
> Fix slm fields required marker

- src/Contract.php
> Fix central list for 7 and 30 contract notices

- src/NetworkPort.php
> Prevent exception on invalid network port relation

- src/Webhook.php
> Support PUT for outgoing webhooks

- .github/workflows/ci.yml
Replaces #17341.
With this configuration, the test matrix will now contain only the items that are actually processed. It means that the result list will not anymore contained skipped jobs.
> Do not show skipped versions in tests results

- js/src/vue/Kanban/Kanban.vue
> Refresh kanban after card deletion

- front/webhookcategory.form.php
- front/webhookcategory.php
- inc/relation.constant.php
- install/migrations/update_10.0.x_to_11.0.0/webhook.php
- install/mysql/glpi-empty.sql
- src/Dropdown.php
- src/Webhook.php
- src/WebhookCategory.php
- templates/pages/setup/webhook/webhook.html.twig
Add categories to help with organization for webhooks.
> Add webhook categories

- src/Glpi/Form/Destination/CommonITILField/ContentField.php
- src/Glpi/Form/Destination/CommonITILField/RequestTypeField.php
- src/Glpi/Form/Destination/CommonITILField/TitleField.php
- src/Glpi/Form/Destination/ConfigFieldInterface.php
- templates/pages/admin/form/form_destination_commonitil_config.html.twig
| Q | A 
| ------------- | --- 
| Bug fix?      | no 
| New feature?  | yes 
| BC breaks?    | no 
| Deprecations? | no 
| Tests pass?   | yes 
Add a weight system to sort configuration fields on destination forms
> feat(forms): Add weight property to config fields for form destinations

- src/Search.php
Add Number of changes into GetOptions Function
> Add Number of changes 

- phpunit/functional/Glpi/Inventory/Assets/VirtualMachineTest.php
- src/Inventory/Asset/VirtualMachine.php
> Update virtual machines comment; closes #17517

- src/Glpi/Form/Destination/AbstractConfigField.php
- src/Glpi/Form/Destination/CommonITILField/TitleField.php
- src/Glpi/Form/Destination/ConfigFieldInterface.php
- src/Glpi/Form/Destination/FormDestination.php
- src/Html.php
- templates/components/form/basic_inputs_macros.html.twig
- tests/cypress/e2e/form/destination_config_fields/title.cy.js
- tests/cypress/e2e/form/form_destination.cy.js
| Fixed 
Support for tags in the title field. The field is now a tinyMCE field with toolbar and status bar disabled.
HTML tags and line breaks are not allowed.
> feat(forms): Transform "title" field into a rich text in form destination

- src/CommonDBTM.php
- src/DbUtils.php
> Handle getTable for PHPUnit mocked objects

- templates/pages/admin/form/form_destination_commonitil_config.html.twig
> feat(forms): Add tooltip for auto config field in form destinations

- css/includes/components/_richtext.scss
- src/Glpi/Form/Destination/CommonITILField/ContentField.php
- src/Html.php
- templates/components/form/basic_inputs_macros.html.twig
The previous formatting used paragraphs for each question, which resulted in too great gap between lines in the destinations, for example with the ticket generated below.
|  | Form destination config | Generated ticket
|:-------------------------------------:|:-------------------------------------:|:-------------------------------------:|
| Before | ![](https://github.com/user-attachments/assets/8cda7087-8e1d-4289-bb04-5e2a685dbd97) | ![](https://github.com/user-attachments/assets/13ee2e2b-0c58-426b-9dbb-4fb7d8c7e7e4) |
| After | ![](https://github.com/user-attachments/assets/4fca1b6f-82e6-49d5-9331-96b830d758ce) | …
> ui(forms): Improve destination content format

- .webpack.config.js
- js/modules/Form/WebIconSelector.js
- lib/bundles/tablericons-definitions.js
- templates/components/form/fields_macros.html.twig
- templates/pages/setup/manuallink.html.twig
- tests/js/modules/Form/WebIconSelector.test.js
It seems to be make wonders ^^
I wanted to add collections (with outgroup) for tabler icons, but the way icons are fetched (from the CSS file), I don't see any way to add this. But anyway, for the performance, it's already a good step in comparison of existing dropdown
> paginate local data when displaying icons selector, fix #17522

- src/Ajax.php
> Fix null instead of string; closes #17646

- tests/src/FormTesterTrait.php
This is a test helper method added in #17638.
Since the original PR won't be merged before 2 or 3 weeks, I've extracted the method to be able to use it in others PRs.
> Extract sendFormAndGetCreatedTicket

- src/Glpi/Controller/ErrorController.php
Now, whenever you throw an exception that implements `Symfony\Component\HttpKernel\Exception\HttpExceptionInterface`, the HTTP status code is used as an HTTP response code.
As of today, this applies to all these exceptions from the `Symfony\Component\HttpKernel\Exception` Symfony namespace:
- 400: `Symfony\Component\HttpKernel\Exception\BadRequestHttpException.php`
- 401: `Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException.php`
- 403: `Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException.php`
- 404: `Symfony\Component\HttpKernel\Exception\NotFoundHttpException.php`
- 405: `Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException.php`
- 406: `Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException.php`
- 409: …
> [11.0] Fix http error code not taken in account.

- src/AbstractITILChildTemplate.php
- src/ITILSolution.php
- tests/functional/ITILSolution.php
> Fix adding solution with empty content

- .github/workflows/ci.yml
- .vue.webpack.config.js
- js/src/vue/Debug/Widget/Profiler.vue
- js/src/vue/Debug/Widget/ProfilerTable.vue
- js/src/vue/Debug/Widget/SQLRequests.vue
- js/src/vue/Kanban/TeamBadgeProvider.js
- js/src/vue/app.js
| Fixed tickets | #17533
Use a custom `__webpack_chunk_load__` function to resolve chunk paths using `CFG_GLPI.root_doc` in order to support GLPI installations in subfolders.
> Fix Vue webpack chunk loading in subfolders

- src/Glpi/Asset/Asset.php
- src/Glpi/Asset/AssetDefinitionManager.php
- tests/functional/Glpi/Asset/Asset.php
- tests/functional/Glpi/Asset/AssetDefinition.php
- tests/functional/Glpi/Asset/AssetDefinitionManager.php
- tests/functional/Glpi/Asset/Capacity/HasContractsCapacity.php
- tests/functional/Glpi/Asset/Capacity/HasHistoryCapacity.php
- tests/functional/Glpi/Asset/Capacity/HasOperatingSystemCapacity.php
- tests/functional/Glpi/Asset/Capacity/IsRackableCapacity.php
> Custom Asset Field Unicity

- src/AuthLDAP.php
- src/CronTask.php
- src/Lock.php
- src/MailCollector.php
- src/NotificationTarget.php
- src/Profile.php
- src/ProfileRight.php
- src/RequestType.php
- src/Socket.php
- src/Ticket.php
- src/User.php
> fix: use getTable instead of direct table name

- ajax/dropdownAllItems.php
- js/common.js
- js/modules/Forms/QuestionItem.js
- phpunit/functional/Glpi/Form/AnswersSetTest.php
- phpunit/functional/Glpi/Form/QuestionType/QuestionTypesManagerTest.php
- src/Dropdown.php
- src/Glpi/Form/QuestionType/QuestionTypeCategory.php
- src/Glpi/Form/QuestionType/QuestionTypeItem.php
- src/Glpi/Form/QuestionType/QuestionTypeItemDropdown.php
- src/Html.php
- src/autoload/CFG_GLPI.php
- tests/cypress/e2e/form/question_types/item.cy.js
- tests/src/FormBuilder.php
- tests/src/FormTesterTrait.php
Added `Item` category and related sub-question type : `GLPI Objects` and `Dropdown`
[Capture vidéo du 04-07-2024 11:03:04.webm](https://github.com/glpi-project/glpi/assets/42278610/d20398c2-2035-457d-8da2-f22712913bee)
> feat(forms): Adding item category and related sub question type

- ajax/search.php
- ajax/treebrowse.php
- src/Features/TreeBrowse.php
| Fixed tickets | !300072
In tree view mode, column sorting did not work.
On documents, for example:
> fix(treebrowse): sorting operation

- phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
- src/Glpi/Form/Export/Serializer/FormSerializer.php
- src/Glpi/Form/Export/Specification/SectionContentSpecification.php
- tests/src/FormTesterTrait.php
Export/Import form sections (name, description and rank).
> Forms: export/import sections

- front/reservationitem.form.php
| Fixed tickets | https://github.com/glpi-project/glpi/pull/17712#pullrequestreview-2254526701
`backToStock` seems useless
> Fix(ReservationItem): backToStock is useless

- src/Glpi/Asset/AssetDefinition.php
- tests/functional/Glpi/Asset/Capacity/HasContractsCapacity.php
- tests/functional/Glpi/Asset/Capacity/HasOperatingSystemCapacity.php
> Custom Asset Default Display Preferences

- src/Change.php
- src/CommonItilObject_Item.php
- src/Problem.php
- src/Ticket.php
Fix tables of changes and problems for an item so that they are similar to the table of tickets for an item and compatible with the print preview functionality.
**Before**
**After**
> Fix tables of changes and problems

- src/CommonDBChild.php
- src/CommonDBTM.php
- src/Dropdown.php
- src/IPAddress.php
- src/Impact.php
- src/Item_Rack.php
- src/KnowbaseItem_Revision.php
- src/MassiveAction.php
- src/NetworkAlias.php
- src/NotificationEventAbstract.php
- src/NotificationTargetCommonITILObject.php
- src/PlanningRecall.php
- src/Plugin.php
- src/Report.php
> Feat: PHPstan 2

- phpunit/functional/Glpi/Inventory/Assets/MonitorTest.php
- src/Inventory/Asset/Monitor.php
| Fixed tickets | #17721 (maybe)
> Remove monitors when inventory node is empty; add tests

- templates/components/logs.html.twig
Add the check on display_history attribute before printing the line
> Fix plugins log entries filtering

- src/Glpi/Controller/DropdownFormController.php
> Fix unexpected exception in dropdown form

- .phpstan-baseline.php
- ajax/agent.php
- ajax/central.php
- ajax/comments.php
- ajax/commonitilobject_item.php
- ajax/dropdownItilActors.php
- ajax/dropdownTrackingDeviceType.php
- ajax/form/answer.php
- ajax/impact.php
- ajax/itilfollowup.php
- ajax/searchoptionvalue.php
- ajax/task.php
- src/Dropdown.php
- src/Glpi/Http/Response.php
You can check individual commits for an easier review.
> PHPStan: fix baseline issues for ajax/* files

- js/modules/Forms/EditorController.js
- templates/pages/admin/form/form_comment.html.twig
- templates/pages/admin/form/form_editor.html.twig
- templates/pages/admin/form/form_question.html.twig
- templates/pages/admin/form/form_section.html.twig
- templates/pages/admin/form/move_section_modal.html.twig
- tests/cypress/e2e/form/form_editor.cy.js
- tests/cypress/e2e/form/form_preview.cy.js
- tests/cypress/support/commands.d.ts
- tests/cypress/support/commands.js
- tests/cypress/support/commands/form.d.ts
- tests/cypress/support/commands/form.js
- tests/cypress/support/commands/select2.d.ts
A lot of tests added to cover more features of the form editor.
Had a lot of trouble testing drag and drop related features... current solution is honestly not that great but at least it is tested.
I am not sure we can do better at this time but feel free to improve it if you can :)
Separated in multiple commits to avoid opening 10 PRs.
> Add more form editors e2e tests

- phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
- src/Glpi/Form/Export/Serializer/FormSerializer.php
- src/Session.php
- tests/cypress/e2e/form/serializer/export.cy.js
Changes suggested by @cedric-anne:
> Forms: improve export filenames

- phpunit/functional/Glpi/Form/Destination/CommonITILField/TemplateFieldTest.php
- src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
- src/Glpi/Form/Destination/CommonITILField/RequestTypeField.php
- src/Glpi/Form/Destination/CommonITILField/TemplateField.php
- src/Glpi/Form/Destination/CommonITILField/TemplateFieldConfig.php
- src/Glpi/Form/Destination/CommonITILField/TemplateFieldStrategy.php
- tests/cypress/e2e/form/destination_config_fields/template.cy.js
"Specific template" display a secondary select to let the user pick the chosen template :
> feat(forms): Add Template field configuration for form destination

- templates/pages/setup/general/security_setup.html.twig
- a little visual improvement to make this page more understandable.
**before**
**after**
> feat: ui review of setup security tab

- phpunit/functional/Glpi/Form/Destination/CommonITILField/SLATTOFieldTest.php
- phpunit/functional/Glpi/Form/Destination/CommonITILField/SLATTRFieldTest.php
- src/Dropdown.php
- src/Glpi/Form/Destination/CommonITILField/SLAField.php
- src/Glpi/Form/Destination/CommonITILField/SLAFieldConfig.php
- src/Glpi/Form/Destination/CommonITILField/SLAFieldStrategy.php
- src/Glpi/Form/Destination/CommonITILField/SLATTOField.php
- src/Glpi/Form/Destination/CommonITILField/SLATTRField.php
- templates/components/itilobject/fields_panel.html.twig
- templates/pages/admin/form/itil_config_fields/sla.html.twig
- tests/cypress/e2e/form/destination_config_fields/sla_tto.cy.js
- tests/cypress/e2e/form/destination_config_fields/sla_ttr.cy.js
"Specific SLA" display a secondary select to let the user pick the chosen SLA :
> feat(forms): Add SLA field configuration for form destination

- templates/pages/setup/general/preferences_setup.html.twig
> Fix theme and layout select2 templates

- tests/cypress/e2e/form/destination_config_fields/request_type.cy.js
- tests/cypress/e2e/form/destination_config_fields/sla_tto.cy.js
- tests/cypress/e2e/form/destination_config_fields/sla_ttr.cy.js
- tests/cypress/e2e/form/destination_config_fields/template.cy.js
- tests/cypress/e2e/form/destination_config_fields/urgency.cy.js
- tests/cypress/support/commands.d.ts
- tests/cypress/support/commands.js
Fix problems in E2E Cypress tests on form destination configuration fields.
> fix(forms): Fix tests for destination fields and enhance alert management

- install/migrations/update_10.0.x_to_11.0.0/form.php
- install/mysql/glpi-empty.sql
- src/Glpi/Form/Form.php
- src/Glpi/Form/ServiceCatalog/ServiceCatalog.php
- templates/pages/admin/form/service_catalog_tab.html.twig
- templates/pages/self-service/service_catalog.html.twig
- tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
- tests/cypress/e2e/form/service_catalog/service_catalog_tab.cy.js
- tests/cypress/support/commands/form.js
Note: UI will be reviewed later, we focus on features for now.
Config is done in a new tab:
> Add icons to service catalog

- tests/cypress/e2e/form/destination_config_fields/content.cy.js
- tests/cypress/e2e/form/destination_config_fields/sla_tto.cy.js
- tests/cypress/e2e/form/destination_config_fields/sla_ttr.cy.js
- tests/cypress/e2e/form/destination_config_fields/template.cy.js
- tests/cypress/e2e/form/destination_config_fields/title.cy.js
Fix problems in E2E Cypress tests for SLA destination configuration fields.
> fix(forms): Fix form destination fields cypress tests

- src/Group.php
| Fixed tickets | !34220
**Before**
**After**
> Fix Used and Managed Items total count badge

- phpunit/DbTestCase.php
- phpunit/functional/SearchTest.php
- src/CommonITILSatisfaction.php
- src/Glpi/Search/Provider/SQLProvider.php
- src/Ticket.php
| Fixed tickets | !33982
The link to the search did not take into account “Duration of survey” defined on the entity.
> fix(central): satisfaction survey link criteria

- install/migrations/update_10.0.16_to_10.0.17/rule_tickets.php
- phpunit/functional/RuleTicketTest.php
- src/RuleTicket.php
- It fixes !34355
- The "Writer" criterion did not work on ticket rules.
> Fix(rule ticket): User_id_recipient criterion

- src/CommonDBTM.php
Prevents XSS in comments tooltips. Problem is present only in the `main` branch.
> Fix HTML escaping in comment tooltips

- src/Glpi/Form/Destination/CommonITILField/TitleField.php
Fixed title field destination prepareInput
> fix(forms): Fixed title field destination prepareInput

- src/User.php
- src/UserEmail.php
Ensure htmlspecialchars is used for echo in U* classes
> Ensure htmlspecialchars is used for echo in U* classes

- src/Database.php
- src/DatabaseInstance.php
- src/Datacenter.php
> Better HTML encoding for Database, DatabaseInstance and Datacenter

- phpunit/functional/Glpi/Inventory/Assets/Environment.php
- phpunit/functional/Glpi/Inventory/Assets/Process.php
- src/Glpi/Asset/Capacity/HasEnvironmentsCapacity.php
- src/Glpi/Asset/Capacity/HasProcessCapacity.php
- tests/functional/Glpi/Asset/Capacity/HasEnvironmentsCapacity.php
- tests/functional/Glpi/Asset/Capacity/HasProcessCapacity.php
Adds Environment and Process capacities.
> Add process and environment capacities

- src/Html.php
- Removes an unnecessary dash (at the beginning of a comment line) which my IDE doesn't like :D
> fix: removes an unnecessary dash

- src/Ticket.php
- src/Ticket_Ticket.php
- src/Toolbox.php
- src/ValidatorSubstitute.php
Classes T* and V*
Few typos
Fix possible encodings issues
> Fix possible encodings issues

- src/Domain.php
- src/Dropdown.php
> Better HTML encoding for Domain and Dropdown

- .phpstan-baseline.php
- src/Rack.php
- src/RefusedEquipment.php
- src/RegisteredID.php
- src/Reservation.php
- src/RuleAction.php
- src/RuleRightParameter.php
- stubs/glpi_constants.php
> Fix possible encodings issues 

- src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
- src/Html.php
- tests/cypress/e2e/form/question_types/actors.cy.js
The default value was not saved when multiple actors were not authorized.
This behavior was due to the hidden input of the multiple dropdown overwriting the value of the single dropdown.
> fix(forms): Fixed retention of default value for question type actors

- phpunit/functional/Glpi/Form/Destination/CommonITILField/UrgencyFieldTest.php
- phpunit/functional/Glpi/Form/QuestionType/QuestionTypeUrgencyTest.php
- src/Glpi/Form/Destination/CommonITILField/UrgencyField.php
- src/Glpi/Form/QuestionType/QuestionTypeUrgency.php
Urgency level configuration taken into account.
- In “Urgency” type questions: Filtering options available according to general configuration.
- In the “Urgency” form destination field: Option filtering available according to general configuration
> feat(forms): Take into account the fact that urgency levels can disabled

- tests/cypress/e2e/xss.cy.js
> Minimal E2E XSS test

- src/Html.php
Fixed some encodings issues in `Html.php`
> fix: Fixed some encodings issues in Html.php

- src/Glpi/Features/Inventoriable.php
Fix possible encoding issues on inventoriable trait
> Fix possible encoding issues on inventoriable trait

- src/IPNetwork_Vlan.php
- src/ITILCategory.php
- src/ITILFollowup.php
- src/Impact.php
- src/Infocom.php
- src/Item_Devices.php
- src/Item_Disk.php
- src/Item_Enclosure.php
- src/Item_Line.php
- src/Item_OperatingSystem.php
- src/Item_Plug.php
- src/Item_Project.php
- src/Item_Rack.php
- src/Item_SoftwareLicense.php
- src/Item_SoftwareVersion.php
- src/Itil_Project.php
> Better HTML encoding for I* classes

- src/PDU_Rack.php
- src/Plugin.php
- src/Problem.php
- src/Profile.php
- src/Profile_User.php
- src/Project.php
- src/ProjectCost.php
- src/ProjectTask.php
- tests/functional/Plugin.php
XSS escaping for src/P*.php classes
\+ a few clean (\n)
> check P* escaping

- composer.json
Fixes a typo in classes namespace.
> Fix case typo in tests autoloader

- templates/pages/setup/general/api_setup.html.twig
From #17847
Any specific reason that should be in the confirm/warning messages?
> Discourage legacy API usage

- src/Glpi/Dashboard/Filter.php
- src/Glpi/Dashboard/Filters/GroupRequesterFilter.php
- This PR add Requester Group Filter On Dashboard
> Add Requester Group Filter On Dashboard

- .phpstan-baseline.php
- phpunit/functional/Glpi/Form/Tag/CommentDescriptionTagProviderTest.php
- phpunit/functional/Glpi/Form/Tag/CommentTitleTagProviderTest.php
- phpunit/functional/Glpi/Form/Tag/FormTagsManagerTest.php
- src/Glpi/Form/Destination/CommonITILField/ContentField.php
- src/Glpi/Form/Section.php
- src/Glpi/Form/Tag/CommentDescriptionTagProvider.php
- src/Glpi/Form/Tag/CommentTitleTagProvider.php
- src/Glpi/Form/Tag/FormTagsManager.php
- tests/cypress/e2e/form/form_tags.cy.js
> feat(forms): Adding comment tags for form destinations

- phpunit/functional/Glpi/Form/Destination/CommonITILField/LocationFieldTest.php
- src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
- src/Glpi/Form/Destination/CommonITILField/LocationField.php
- src/Glpi/Form/Destination/CommonITILField/LocationFieldConfig.php
- src/Glpi/Form/Destination/CommonITILField/LocationFieldStrategy.php
- templates/pages/admin/form/itil_config_fields/location.html.twig
- tests/cypress/e2e/form/destination_config_fields/location.cy.js
"Specific Location" display a secondary select to let the user pick the chosen location :
"Answer from a specific question" display a secondary select to let the user pick the chosen question :
> feat(forms): Add Location field configuration for form destination

- js/modules/Forms/SelfServiceController.js
- phpunit/functional/Glpi/Form/ServiceCatalog/ServiceCatalogManagerTest.php
- phpunit/functional/Glpi/FuzzyMatcher/FuzzyMatcherTest.php
- src/Glpi/Controller/Form/FormListController.php
- src/Glpi/Form/ServiceCatalog/ServiceCatalogManager.php
- src/Glpi/FuzzyMatcher/FuzzyMatcher.php
- src/Glpi/FuzzyMatcher/FuzzyMatcherStrategyInterface.php
- src/Glpi/FuzzyMatcher/PartialMatchStrategy.php
- templates/components/helpdesk_forms/forms_list.html.twig
- tests/cypress/e2e/form/access_policies/access_control.cy.js
- tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
- tests/src/FormBuilder.php
- tests/src/FormTesterTrait.php
As always, do not pay attention to the UI as we will work on that later.
Alexandre requested some kind of fuzzy matching for this feature.
I've implemented it into a dedicated `FuzzyMatcher` class that can be reused into the future.
The exact parameters of the fuzzy matching are delegated to a strategy class in case we need some flexibility on this.
> Filter service catalog using a text search

- ajax/dropdownTrackingDeviceType.php
- css/includes/_includes.scss
- css/includes/components/form/_form-destination.scss
- js/modules/Forms/FieldDestinationAssociatedItem.js
- phpunit/functional/Glpi/Form/Destination/CommonITILField/AssociatedItemsFieldTest.php
- phpunit/functional/Glpi/Form/Tag/AnswerTagProviderTest.php
- src/CommonItilObject_Item.php
- src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
- src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php
- src/Glpi/Form/Destination/CommonITILField/AssociatedItemsFieldConfig.php
- src/Glpi/Form/Destination/CommonITILField/AssociatedItemsFieldStrategy.php
- src/Glpi/Form/QuestionType/QuestionTypeItem.php
- templates/components/form/fields_macros.html.twig
- templates/pages/admin/form/itil_config_fields/associated_items.html.twig
- tests/cypress/e2e/form/destination_config_fields/associated_items.cy.js
"Specific items" display a secondary select to let the user pick some items :
"Answer from specific questions" display a secondary select to let the user pick some questions :
> feat(forms): Add Associated Items field configuration for form destination

- src/User.php
> Fix undefined entry

- src/CommonGLPI.php
> Fix possible encoding issue

- templates/components/datatable.html.twig
- templates/components/logs.html.twig
- templates/components/pager.html.twig
- templates/pages/admin/events_list.html.twig
- templates/pages/admin/log_viewer.html.twig
Remove `raw` usages in log viewer template
>  Remove `raw` usages in log viewer template

- js/modules/Forms/RendererController.js
- templates/pages/form_renderer.html.twig
> fix(forms): Fixed the E2E test by adding the default “disabled” attribute to wait for JS init

- phpunit/functional/Glpi/Form/SelfService/TilesManagerTest.php
- src/Glpi/Controller/SelfService/HomeController.php
- src/Glpi/Form/SelfService/FormTile.php
- src/Glpi/Form/SelfService/Tile.php
- src/Glpi/Form/SelfService/TileInterface.php
- src/Glpi/Form/SelfService/TilesManager.php
- templates/pages/self-service/new_home.html.twig
- tests/cypress/e2e/self-service/home.cy.js
Technical stuff to prepare future user customization of the home page tiles.
> Home page: tiles manager

- phpunit/functional/Glpi/Form/Destination/CommonITILField/ValidationFieldTest.php
- src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
- src/Glpi/Form/Destination/CommonITILField/ValidationField.php
- src/Glpi/Form/Destination/CommonITILField/ValidationFieldConfig.php
- src/Glpi/Form/Destination/CommonITILField/ValidationFieldStrategy.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
- src/User.php
- templates/pages/admin/form/itil_config_fields/validation.html.twig
- tests/cypress/e2e/form/destination_config_fields/validation.cy.js
"Specific actors" display a secondary select to let the user pick some actors :
"Answer from specific questions" display a secondary select to let the user pick some questions :
> feat(forms): Add Validation field configuration for form destination

- templates/components/search/displaypreference_config.html.twig
Fix text not being vertically centered in the display preferences modal.
Before:
After:
You'll need good eyes to see it ;)
> Fix display preferences alignment

- src/Config.php
- It fixes !33699
Continuation of https://github.com/glpi-project/glpi/pull/17836
Enhance text to make it more precise.
> Fix(Inventory): text enhancement

- bin/console
- phpstan.neon
Create link to standard phpstan config file if not present
> Create link to standard phpstan config file if not present

- src/Glpi/Console/CommandLoader.php
Prefixing all Symfony commands with `symfony:` allows Symfony's `CommandLoader` to be used.
The only drawback is that commands that are registered automatically in DI via auto-configuration will also have this prefix, but for now it's not the case in any GLPI command, so it's safe.
> Add Symfony commands to the stack, and prefixed them with "symfony:"

- js/fileupload.js
- src/Html.php
Prevent XSS on the file upload feature (problem present only on the main branch).
> Fix escaping on file upload feature

- ajax/comments.php
- ajax/common.tabs.php
- ajax/dashboard.php
- ajax/debug.php
- ajax/dropdownConnect.php
- ajax/dropdownMassiveAction.php
- ajax/dropdownMassiveActionField.php
- ajax/dropdownMassiveActionOs.php
- ajax/itilfollowup.php
- ajax/itillayout.php
- ajax/itilvalidation.php
- ajax/kblink.php
- ajax/knowbase.php
- ajax/marketplace.php
- ajax/massiveaction.php
- ajax/planning.php
- ajax/reservations.php
- ajax/ruleaction.php
- ajax/search.php
- ajax/solution.php
- ajax/task.php
- ajax/ticketiteminformation.php
- ajax/timeline.php
- ajax/viewsubitem.php
- ajax/webhook.php
- front/impactcsv.php
> Replace exit/die statements in ajax with "return" instead

- src/Glpi/Exception/Access/InvalidCsrfException.php
That's remnants of the old code that wasn't using Symfony's Request object.
> Fix wrong check in InvalidCsrfException

- src/DatabaseInstance.php
- It fixes !34742
Add missing database instance Search options : Path and Itemtype
> Fix Database Instance SearchOption

- phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
- src/Glpi/Form/Export/Serializer/FormSerializer.php
- src/Glpi/Form/Export/Specification/CommentContentSpecification.php
- tests/src/FormTesterTrait.php
Adds export and import of comments (name, description, rank and section rank)
> feat(forms): Add export and import functionality for comments

- .phpstan-baseline.php
- src/Glpi/Form/Question.php
- src/Glpi/Form/QuestionType/AbstractQuestionType.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
- src/Glpi/Form/QuestionType/QuestionTypeActorsConfig.php
- src/Glpi/Form/QuestionType/QuestionTypeDateTime.php
- src/Glpi/Form/QuestionType/QuestionTypeDateTimeConfig.php
- src/Glpi/Form/QuestionType/QuestionTypeDropdown.php
- src/Glpi/Form/QuestionType/QuestionTypeDropdownConfig.php
- src/Glpi/Form/QuestionType/QuestionTypeInterface.php
- src/Glpi/Form/QuestionType/QuestionTypeItem.php
- src/Glpi/Form/QuestionType/QuestionTypeItemConfig.php
- src/Glpi/Form/QuestionType/QuestionTypeSelectableConfig.php
Wraps question type extra-data as serializable config classes.
This work is required to be able to export and import form questions.
> refactor(forms): Wraps question type extra-data as serializable config classes

- src/Glpi/Form/AccessControl/ControlType/AllowListDropdown.php
Added criteria to exclude the GLPI system user from the search.
The system user is already excluded from the users count, but is not excluded from the search when the link is clicked.
> feat(forms): Exclude system-user from allow list count user link

- src/Change.php
- src/Ticket.php
- Patch for ticket !34712.
- Add "Number of changes" to the display preferences for the tickets.
> Add "Number of changes" to the display preferences for the tickets

- src/Ticket.php
- It fixes !34780
Correction of the execution of rules using priorities. These were not validated if the user did not have the right to modify the priority. 
*For example, for the rule :*
**Priority:** Medium
**Technician:** Group 1
If the priority is already set to medium and the technician group becomes group 1, if the user does not have the right to update the priority, the rule is not validated.
> Fix Ticket Priority Rule execution

- phpunit/functional/Glpi/Form/Destination/CommonITILField/AssigneeFieldTest.php
- phpunit/functional/Glpi/Form/Destination/CommonITILField/ObserverFieldTest.php
- phpunit/functional/Glpi/Form/Destination/CommonITILField/RequesterFieldTest.php
- src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
- src/Glpi/Form/Destination/CommonITILField/AssigneeField.php
- src/Glpi/Form/Destination/CommonITILField/ITILActorField.php
- src/Glpi/Form/Destination/CommonITILField/ITILActorFieldConfig.php
- src/Glpi/Form/Destination/CommonITILField/ITILActorFieldStrategy.php
- src/Glpi/Form/Destination/CommonITILField/ObserverField.php
- src/Glpi/Form/Destination/CommonITILField/RequesterField.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
- templates/pages/admin/form/itil_config_fields/itilactor.html.twig
- tests/cypress/e2e/form/destination_config_fields/assignee.cy.js
- tests/cypress/e2e/form/destination_config_fields/observer.cy.js
- tests/cypress/e2e/form/destination_config_fields/requester.cy.js
> feat(forms): Add ITIL Actors configurations for form destination

- front/central.php
- front/helpdesk.public.php
- src/Glpi/Controller/ChangeProfileController.php
- src/Glpi/Controller/Session/ChangeProfileController.php
- templates/layout/parts/profile_selector.html.twig
- tests/cypress/e2e/session.cy.js
- tests/cypress/support/commands.js
I am going to delete the legacy `front/helpdesk.public.php` file soon as it is replaced by the new home page.
However, this page define some logic related to profiles changes so it needs to be migrated into a proper endpoint before it can be deleted.
> Add proper endpoint to change the current profile

- phpunit/functional/Glpi/Inventory/InventoryTest.php
- src/Inventory/Asset/InventoryNetworkPort.php
- src/Inventory/Asset/MainAsset.php
- src/Inventory/Asset/Printer.php
Fix partial network ports inventory
closes #18062
> Fix partial network ports inventory

- src/CommonITILObject.php
> Fix categorization of ITIL type search options

- css/legacy/includes/_styles.scss
Colors were not matching in dark themes. UI can be checked from ticket list when there are multiple actors of the same type (comments icon).
> Fix qtip titlebar colors

- js/src/vue/Debug/Toolbar.vue
> Try to fix handling incomplete debug profile

- src/ITILFollowup.php
> Raise add followup notification last

- templates/components/form/basic_inputs_macros.html.twig
- templates/components/form/fields_macros.html.twig
Fix template mark since labels can no longer contain HTML directly.
> Fix template mark in labels

- src/Change.php
- src/Problem.php
- Ticket !34712
- Add Problem - Change search options
> Add Problem - Change search options

- phpunit/functional/TicketCostTest.php
- src/Item_Ticket.php
- src/TicketCost.php
- It fixes !34818
- If a cost belonging to a ticket or a new item is added/modified/removed. The TCO of the park objects is not updated. The TCO remained equal to the value of the "value" field.
> fix(TCO): TCO was not updated

- tools/build_glpi.sh
1. Move the "user generated files" cleaning after the execution of the `bin/console build:generate_code_manifest` command. This command is generating cache files that must be cleaned.
2. Remove useless dev files/directories.
3. Remove `vue` components sources.
> Clean release archive

- phpunit/functional/Glpi/Form/AnswersSetTest.php
- phpunit/functional/Glpi/Form/Destination/CommonITILField/AssociatedItemsFieldTest.php
- phpunit/functional/Glpi/Form/QuestionType/QuestionTypeUserDeviceTest.php
- phpunit/functional/Glpi/Form/QuestionType/QuestionTypesManagerTest.php
- src/CommonItilObject_Item.php
- src/Glpi/Form/AnswersSet.php
- src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php
- src/Glpi/Form/Destination/CommonITILField/AssociatedItemsFieldStrategy.php
- src/Glpi/Form/QuestionType/AbstractQuestionType.php
- src/Glpi/Form/QuestionType/QuestionTypeItemDropdown.php
- src/Glpi/Form/QuestionType/QuestionTypeUserDevice.php
- src/Glpi/Form/QuestionType/QuestionTypeUserDevicesConfig.php
- src/Glpi/Form/QuestionType/QuestionTypesManager.php
- templates/pages/form_renderer.html.twig
- tests/cypress/e2e/form/destination_config_fields/associated_items.cy.js
- tests/cypress/e2e/form/question_types/actors.cy.js
- tests/cypress/e2e/form/question_types/user_device.cy.js
Added `User Devices` sub question type
The question may or may not authorize several assets.
The question can also be used as a source for `Associated Items` with the form's destination source.
> feat(forms): Adding User Device sub question type

- src/MailCollector.php
- tests/emails-tests/43-korean-encoding-issue.eml
- tests/imap/MailCollector.php
Handle not known encoding for mail content, fix for #18127
> Handle ks_c_5601-1987 charset in mail collector

- inc/relation.constant.php
- phpunit/functional/Glpi/Inventory/InventoryTest.php
- src/CommonDBTM.php
It fixes #17019.
With the proposed change, when a computer is deleted, the database instances attached to this item are deleted too.
> Delete DatabaseInstance when the corresponding item is deleted

- phpunit/functional/Glpi/Helpdesk/DefaultDataManagerTest.php
- phpunit/functional/Glpi/Helpdesk/Tile/TilesManagerTest.php
- src/Glpi/Controller/SelfService/HomeController.php
- src/Glpi/Helpdesk/DefaultDataManager.php
- src/Glpi/Helpdesk/Tile/FormTile.php
- src/Glpi/Helpdesk/Tile/Tile.php
- src/Glpi/Helpdesk/Tile/TileInterface.php
- src/Glpi/Helpdesk/Tile/TilesManager.php
- src/Toolbox.php
- src/Update.php
Small chore needed as we will soon be able to configure the tiles that are displayed on the new home page, with a few default tiles added during GLPI's installation.
I've also moved the helpdesk related files into the correct namespace.
> Rename DefaultFormsManager to DefaultDataManager

- phpunit/functional/SearchTest.php
- src/Search.php
> Fix sub queries negation for `notcontains` searches

- ajax/debug.php
> Drop unneeded exception

- src/NetworkPort.php
- src/NetworkPortConnectionLog.php
Fix wrong call, an array is expected.
> Fix wrong method call

- src/CommonDBTM.php
- src/Log.php
> Handle null values, fixes #18173

- phpunit/functional/DropdownTest.php
- phpunit/functional/NotificationTargetTicketTest.php
- src/Dropdown.php
No idea what is the exact path to reproduce this, but it seems that there are calls to `Dropdown::getDropdownComments()` for items that does not have a `comment` field.
Here is the corresponding warning I found in my logs:
```
glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "comment" in /var/www/glpi/src/Dropdown.php at line 804
Backtrace :
src/Dropdown.php:196                               Dropdown::getDropdownComments()
src/CommonDBTM.php:4177                            Dropdown::show()
...ication/View/Extension/ItemtypeExtension.php:98 CommonDBTM::dropdown()
...es/e9/e9fca707121fa64b648d53b6206d8526.php:2143 Glpi\Application\View\Extension\ItemtypeExtension->getItemtypeDropdown()
.../twig/twig/src/Extension/CoreExtension.php:1919 …
```
> Fix warning from unexpected calls to `Dropdown::getDropdownComments()`

- src/Computer.php
- src/ComputerVirtualMachine.php
- Ticket !34174
-  Add search options in Computer for ComputerVirtualMachine to retrieve VM by Computer UUID with REST API
> Add new SearchOptions Computer

- src/Glpi/Controller/WellKnownController.php
- src/Glpi/Http/LegacyRouterListener.php
- tests/functional/Glpi/Http/LegacyRouterListener.php
Just a small refactoring to use a proper way to handle this specific URL.
> Move `/.well-known/change-password` handling in a dedicated controller

- .phpstan-baseline.php
- src/CommonDBChild.php
- src/CommonDBConnexity.php
- src/CommonDBRelation.php
- src/CommonDBTM.php
- src/CommonDBVisible.php
- src/CommonDCModelDropdown.php
- src/CommonDropdown.php
- src/CommonGLPI.php
- src/CommonITILObject.php
- src/CommonITILRecurrent.php
- src/CommonITILTask.php
- src/CommonITILValidation.php
- src/CommonItilObject_Item.php
Missing escaping, fix some typos
> Missing escaping, fix some typos

- src/CommonITILRecurrent.php
This code often lead to confusion, see #18219 and #18220.
New version is not perfect (the whole function is quite complicated and will stay that way unless it is fully rewritten) but hopefully it is a bit clearer.
> Simplify computeNextCreationDate

- install/install.php
Regression introduced in https://github.com/glpi-project/glpi/pull/18151/commits/be96238a5d0b53148cf32a6ff7ece4d4ffa98157
> Fix new DB creation in UI install process

- composer.lock
```
+-------------------+----------------------------------------------------------------------------------+
| Package           | symfony/http-client                                                              |
| Severity          | low                                                                              |
| CVE               | CVE-2024-50342                                                                   |
| Title             | CVE-2024-50342: Internal address and port enumeration allowed by                 |
|                   | NoPrivateNetworkHttpClient                                                       |
| URL               | https://symfony.com/cve-2024-50342                                               |
| Affected versions | …
```
> Update dependencies to get latest security fixes

- phpunit/functional/TicketTest.php
- src/Ticket.php
- It fixes #18240
Ticket category no longer saved when at a lower level entity
> fix(ticket): category no longer saved when at a lower level entity

- .phpstan-baseline.php
- src/Glpi/Search/CriteriaFilter.php
- src/Glpi/Search/FilterableInterface.php
- src/Glpi/Search/Input/QueryBuilder.php
- src/Glpi/Search/Output/HTMLSearchOutput.php
- src/Glpi/Search/Provider/SQLProvider.php
- src/Glpi/Search/SearchEngine.php
- src/Glpi/Search/SearchOption.php
- src/Glpi/Security/TOTPManager.php
- src/Glpi/System/Diagnostic/DatabaseKeysChecker.php
- src/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
- src/Glpi/System/Requirement/InstallationNotOverriden.php
- src/Glpi/System/RequirementsManager.php
- src/Glpi/Toolbox/Filesystem.php
- src/Glpi/Toolbox/Sanitizer.php
- src/Glpi/Toolbox/VersionParser.php
- src/Glpi/UI/ThemeManager.php
Spotted while looking for html escaping issues
> Fix some typos

- src/Glpi/Controller/Form/Import/Step2PreviewController.php
- src/Glpi/Controller/Form/Import/Step4ExecuteController.php
- templates/pages/admin/form/import/step2_preview.html.twig
- templates/pages/admin/form/import/step3_resolve_issues.html.twig
- tests/cypress/e2e/form/serializer/import.cy.js
- tests/fixtures/export-of-2-forms.json
Correction of the issues resolve system when importing a form.
Commit 797589190599f8eb49009b261be55342ba0f1e71, whose purpose was to sanitize input names, was a little too aggressive for the functionality and removed spaces in the names of objects to be resolved, which was causing anomalies.
I took advantage of the situation to split the information into several inputs, so that the object name could no longer be used as a key in the input name.
> fix(forms): Fixed import E2E tests

- phpunit/functional/TicketTest.php
- src/CommonDBTM.php
- It fixes !35054
The purgeticket crontask failed to delete satisfaction surveys associated with the purged ticket, logging the following warning:
```
glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "tickets_id" in .../src/CommonDBTM.php at line 2045
Backtrace :
src/CommonDBTM.php:4675                            CommonDBTM->delete()
src/Ticket.php:1013                                CommonDBTM->deleteByCriteria()
src/CommonDBTM.php:792                             Ticket->cleanDBonPurge()
src/CommonDBTM.php:2100                            CommonDBTM->deleteFromDB()
src/Ticket.php:6090                                CommonDBTM->delete()
src/CronTask.php:1027                              Ticket::cronPurgeTicket() …
```
> fix(purgeticket): purge also ticket satisfaction

- src/ITILCategory.php
- It fixes !35088
The new SO Number of Change overwrites an existing SO with id 98
> Fix number of changes id

- tools/build_glpi.sh
These files should not be present in the release archive.
> 10.0/clean release archive

- phpunit/functional/Glpi/Helpdesk/DefaultDataManagerTest.php
- src/Glpi/Helpdesk/DefaultDataManager.php
Added missing `UserDevices` question type for default incident and request forms.
Added a destination field for `Observers` to define ticket observers from the `Watchers` question.
> feat(forms): Adding missing questions and destination configs for default forms

- CHANGELOG.md
- src/AuthLDAP.php
- src/AuthLdapReplicate.php
- src/AuthMail.php
- src/Toolbox.php
- templates/pages/setup/authentication/ldap_replicate.html.twig
- templates/pages/setup/authentication/mail.html.twig
- templates/pages/setup/mailcollector/server_config_fields.html.twig
> AuthMail and AuthLdapReplicate Twig UI

- .phpstan-baseline.php
- CHANGELOG.md
- ajax/comments.php
- ajax/priority.php
- phpunit/functional/HtmlTest.php
- src/Ajax.php
- src/Certificate_Item.php
- src/CommonDBChild.php
- src/Dropdown.php
- src/Glpi/Dashboard/Grid.php
- src/Glpi/Features/Inventoriable.php
- src/Glpi/Features/TreeBrowse.php
- src/Glpi/Marketplace/View.php
- src/Html.php
- src/Impact.php
- src/Infocom.php
- src/MassiveAction.php
- src/Profile.php
- src/ReservationItem.php
- src/User.php
- src/UserEmail.php
- src/Webhook.php
I fixed some issues reported by Psalm.
> Fix some escaping issues

- phpunit/functional/Glpi/Inventory/Assets/VirtualMachineTest.php
- src/Glpi/Inventory/Asset/VirtualMachine.php
- It fixes !34616 and !32800
Addition of the operating system and ip in the information retrieved from the vCenter API by the agent
> Add VM OS and IP Inventory

- src/Glpi/Http/Firewall.php
> [11.0] Fix firewall preventing access to the profiler in dev

- src/Glpi/Log/LegacyGlobalLogger.php
> Disable HTTP exceptions logs to errors and keep them in access

- js/common.js
- src/Session.php
- Replace part of #18077
- With the removal of the demo mode, remove the remains of language selector for login page
- Snyk.io will be pleased. It detects (wrongly) this code as a source of XSS.
> remove leftovers of obsolete #3934

- src/ProjectTask.php
- It fixes !34335
add "task team" column in "project tasks" tab
> feat(project): add task team column in project tasks tab

- src/CommonGLPI.php
It may fix some issues reported by Snyk.
> Use strict types in form URL generation

- src/Project.php
> Fix project task real end search option not groupped

- src/Ticket.php
- It fixes !34335
Add search option : Project task
> feat(ticket): add search option = project task

- src/Item_SoftwareLicense.php
A licence may not be attached to a user. In this case, we should not try to format a data that not exists. It fixes #18356.
> Fix licence items tab

- src/Glpi/Application/View/Extension/DataHelpersExtension.php
- src/Html.php
- templates/pages/setup/general/performance.html.twig
This provides a simple way to display static progress bars from a twig template.
> Progress bar Twig helper

- composer.json
- composer.lock
Update twig to allow us to use new functions like [enum()](https://twig.symfony.com/doc/3.x/functions/enum.html).
> Update twig to version 3.15

- src/CommonGLPI.php
- src/CommonITILObject.php
- templates/components/form/header_content.html.twig
> Remove duplicate ID in form header content

- css/includes/_base.scss
> Do not change accordion btn zindex on hover or focus

- src/Toolbox.php
I do not think there is a huge impact, this is mainly to make security analysis happy.
> Lower permissions on directory

- css/includes/components/_log_viewer.scss
- css/includes/components/_richtext.scss
- css/includes/components/_saved-searches.scss
- css/legacy/includes/_impact.scss
- css/legacy/includes/_planning.scss
- css/legacy/includes/_styles.scss
- add fallback for font-family
- remove strange/unknown properties
- remove duplicated properties
- improper usage
- For a few, completely remove the classes as they don't seem to be used. It was reported as sonarcloud on various issues like the above points.
> a few fixes for improving css reliability

- ajax/getAbstractRightDropdownValue.php
- ajax/getFormQuestionActorsDropdownValue.php
- phpunit/functional/Glpi/Form/AnswersSetTest.php
- phpunit/functional/Glpi/Form/Destination/CommonITILField/AssigneeFieldTest.php
- phpunit/functional/Glpi/Form/Destination/CommonITILField/ObserverFieldTest.php
- phpunit/functional/Glpi/Form/Destination/CommonITILField/RequesterFieldTest.php
- phpunit/functional/Glpi/Form/Destination/CommonITILField/ValidationFieldTest.php
- phpunit/functional/Glpi/Form/QuestionType/QuestionTypeAssigneeTest.php
- phpunit/functional/Glpi/Form/QuestionType/QuestionTypeObserverTest.php
- phpunit/functional/Glpi/Form/QuestionType/QuestionTypeRequesterTest.php
- phpunit/src/Glpi/Form/QuestionType/AbstractQuestionTypeActorsTest.php
- src/AbstractRightsDropdown.php
- src/Glpi/Form/AccessControl/ControlType/AllowListDropdown.php
- src/Glpi/Form/Dropdown/FormActorsDropdown.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
- src/Glpi/Form/QuestionType/QuestionTypeAssignee.php
- src/Glpi/Form/QuestionType/QuestionTypeObserver.php
- src/Glpi/Form/QuestionType/QuestionTypeRequester.php
- src/ProjectTaskTeamDropdown.php
- src/ShareDashboardDropdown.php
- tests/cypress/e2e/form/destination_config_fields/assignee.cy.js
- tests/cypress/e2e/form/question_types/actors.cy.js
- tests/src/FormTesterTrait.php
Added additional checks on data validation sent in response to a form.
Verification of objects submitted according to user configuration and rights.
Number of objects checked according to question configuration.
> feat(forms): Add more checks to validate answers for actor question types

- phpunit/functional/DBmysqlIteratorTest.php
- src/DBmysqlIterator.php
- src/Html.php
> Migrate tests to phpunit

- phpunit/functional/DBmysqlIteratorTest.php
- src/DBmysql.php
> Migrate tests main

- js/src/vue/Debug/Widget/ProfilerTable.vue
- src/Glpi/Asset/AssetDefinitionManager.php
- src/Glpi/Config/LegacyConfigurators/CleanPHPSelfParam.php
- src/Glpi/Config/LegacyConfigurators/ConfigRest.php
- src/Glpi/Config/LegacyConfigurators/CustomObjectsAutoloader.php
- src/Glpi/Config/LegacyConfigurators/CustomObjectsBootstrap.php
- src/Glpi/Config/LegacyConfigurators/InitializePlugins.php
- src/Glpi/Config/LegacyConfigurators/SessionConfig.php
- src/Glpi/Debug/Profiler.php
Add GLPI profiler sections for some Symfony config providers and custom asset capacity bootstrapping.
> Add some profiler sections

- install/install.php
There is a typo in the doctype.
> Fix HTML doctype in install page

- templates/pages/setup/authentication/mail.html.twig
- templates/pages/setup/mailcollector/server_config_fields.html.twig
- templates/pages/setup/mailcollector/setup_form.html.twig
UI tuning to have a more understandable interface.
> feat(mailcollector): review UI setup form

- js/common_ajax_controller.js
- tests/cypress/e2e/search/display_preferences.cy.js
Fix an incorrect call to `handleFeedbackMessages()`, the error message was not wrapped correctly (see the method code below).
> Fix form editor error reporting

- phpunit/functional/Glpi/UI/IllustrationManagerTest.php
I've forgot to put the correct variables after copying the code, see comment here: https://github.com/glpi-project/glpi/pull/18420#discussion_r1865366551.
Draft because one of the icon fails the checks, waiting for a new to be provided to me.
> Fix illustration manager tests

- src/RuleTicket.php
- It fixes !35385
Allowing the same actions to all 3 types of groups
> feat(rule ticket): standardization of actions on groups

- src/Plugin/Hooks.php
These constants are used in the `example` plugin, see https://github.com/pluginsGLPI/example/pull/76
> Add missing hook constant

- phpunit/CsvTestCase.php
- phpunit/bootstrap.php
- phpunit/functional/Glpi/CalDAV/ServerTest.php
- phpunit/functional/Glpi/Csv/CsvResponseTest.php
- phpunit/functional/Glpi/Csv/LogCsvExportTest.php
- phpunit/functional/Glpi/Csv/PlanningCsvTest.php
- phpunit/functional/Glpi/Dashboard/DashboardTest.php
- phpunit/functional/Glpi/Dashboard/ProviderTest.php
- phpunit/functional/Glpi/Dashboard/WidgetTest.php
- phpunit/functional/Glpi/Features/ClonableTest.php
- phpunit/functional/Glpi/Features/DCBreadcrumbTest.php
- src/Csv/CsvResponse.php
- src/Csv/ExportToCsvInterface.php
- src/Csv/LogCsvExport.php
- tests/bootstrap.php
> Migrate glpi tests

- phpunit/DbTestCase.php
- phpunit/GLPITestCase.php
- src/Glpi/Asset/AssetDefinitionManager.php
- src/Glpi/Dropdown/DropdownDefinitionManager.php
This will prevent to execute multiple regex when the tested class is not even located in the expected namespace.
> Enhance custom objects autoloader performances

- src/Glpi/Asset/Capacity/HasProjectsCapacity.php
- src/Glpi/Asset/Capacity/IsProjectAssetCapacity.php
- tests/functional/Glpi/Asset/Capacity/IsProjectAssetCapacity.php
- It fixes #18450
- Add project management to custom assets
- mostly copypasta but I didn't seen any error
> Assets: Add project capacity

- js/impact.js
Change CSS variable reference. Old variable no longer exists.
> Fix impact graph grid color

- src/BarcodeManager.php
Item with id = 0 doesn't need to display a qrcode
> item must have a positive id to display a qrcode

- src/Html.php
- src/Search.php
> fix(massiveactions): disable when selection too large

- src/Glpi/Asset/Capacity/IsInventoriableCapacity.php
- src/Glpi/Search/SearchEngine.php
- src/Rule.php
- src/RuleImportAsset.php
- src/RuleImportAssetCollection.php
- src/autoload/CFG_GLPI.php
> No longer rely on state registered types to list rules

- phpunit/functional/Glpi/Asset/CustomFieldDefinitionTest.php
- src/Glpi/Asset/CustomFieldType/DateTimeType.php
- src/Glpi/Asset/CustomFieldType/DateType.php
> Fix error formatting values for custom date fields

- src/MassiveAction.php
- src/Unmanaged.php
- templates/components/form/header_content.html.twig
- templates/components/itilobject/layout.html.twig
Add way to distinguish if massive actions are run from a single item context or not.
https://github.com/glpi-project/glpi/pull/18377#pullrequestreview-2458154169
> Distinguish single massive actions

- phpunit/functional/TransferTest.php
- src/CommonDevice.php
- src/Transfer.php
Activate transfer on generic assets
> Transfer generic assets

- src/CommonDevice.php
- src/Transfer.php
> Fix devices transfer

- front/contract_item.form.php
- inc/relation.constant.php
- install/migrations/update_10.0.x_to_11.0.0/contract_user.php
- install/mysql/glpi-empty.sql
- phpunit/functional/ContractTest.php
- src/Contract_Item.php
- src/Contract_User.php
- src/User.php
- src/autoload/CFG_GLPI.php
- It fixes !34567
Adding the relationship of Contracts to Users
Linked with : #18335
> Add User itemtype to Contracts linked items

- .phpstan-baseline.php
- dependency_injection/legacyConfigProviders.php
- src/Config.php
- src/Glpi/Config/LegacyConfigurators/InitializeDbConnection.php
- src/Glpi/Config/LegacyConfigurators/LoadLegacyConfiguration.php
- src/Glpi/Config/LegacyConfigurators/StandardIncludes.php
- src/Glpi/Console/Application.php
The purpose of this PR is to extract the DB connection initialization and the configuration loading from the complex `StandardIncludes` class. It should permit to ease the work started in #18497.
> Refactor DB connection init and configuration loading

- src/Item_Devices.php
> Missing Location search options in item_devices

- CHANGELOG.md
- install/install.php
- install/update.php
- src/Glpi/Config/LegacyConfigurators/SessionStart.php
- src/Glpi/Controller/IndexController.php
- src/Glpi/Debug/Profile.php
- src/Session.php
- src/Update.php
- tests/functional/Update.php
While reviewing #18497, I figured out the session initialization was not anymore done in the CLI context of the `/front/cron.php`.
I reviewed the corresponding configuration class to fix this. I also remove the duplciated session initialization in the install/update process.
> Fix session initialization

- composer.json
- composer.lock
- src/Config.php
- src/Glpi/Dashboard/Widget.php
- src/Stat.php
Fixes #18412
This library is abandoned and wasn't strictly needed.
> Remove Laminas JSON library

- phpunit/functional/RuleTicketTest.php
- src/Ticket.php
Bug was reported on the forum. The link between the ticket and project was added to the table for `Item_Project` which is for assets rather than `Itil_Project` which is for tickets/changes/problems.
> Fix assigning projects in ticket rules

- phpunit/abstracts/CommonITILSatisfaction.php
- phpunit/functional/ChangeSatisfactionTest.php
- phpunit/functional/ClusterTest.php
- phpunit/functional/CommonITILObject_CommonITILObjectTest.php
- phpunit/functional/DeviceHardDriveTest.php
- phpunit/functional/DeviceHardDriveTypeTest.php
- phpunit/functional/Item_LineTest.php
- phpunit/functional/NotificationTargetKnowbaseItemTest.php
- phpunit/functional/OAuthClientTest.php
- phpunit/functional/ProfileRightTest.php
- phpunit/functional/TicketSatisfactionTest.php
- phpunit/functional/ValidatorSubstituteTest.php
- phpunit/functional/WebhookTest.php
Migrations to phpunit (tests that only exists on main).
> Migrations to phpunit

- phpunit/HLAPITestCase.php
- phpunit/bootstrap.php
- phpunit/functional/Glpi/Api/HL/Controller/AdministrationControllerTest.php
- phpunit/functional/Glpi/Api/HL/Controller/AssetControllerTest.php
- phpunit/functional/Glpi/Api/HL/Controller/ComponentControllerTest.php
- phpunit/functional/Glpi/Api/HL/Controller/CoreControllerTest.php
- phpunit/functional/Glpi/Api/HL/Controller/GraphQLControllerTest.php
- phpunit/functional/Glpi/Api/HL/Controller/ITILControllerTest.php
- phpunit/functional/Glpi/Api/HL/Controller/ManagementControllerTest.php
- phpunit/functional/Glpi/Api/HL/Controller/ProjectControllerTest.php
- phpunit/functional/Glpi/Api/HL/Controller/ReportControllerTest.php
- phpunit/functional/Glpi/Api/HL/Controller/RuleControllerTest.php
- phpunit/functional/Glpi/Api/HL/Doc/SchemaTest.php
- phpunit/functional/Glpi/Api/HL/Middleware/IPRestrictionRequestMiddlewareTest.php
- phpunit/functional/Glpi/Api/HL/OpenAPIGeneratorTest.php
- phpunit/functional/Glpi/Api/HL/RSQL/LexerTest.php
- phpunit/functional/Glpi/Api/HL/RSQL/ParserTest.php
- phpunit/functional/Glpi/Api/HL/RouterTest.php
- src/Glpi/Api/HL/Router.php
- src/Toolbox.php
Migrates High-Level API tests to PHPUnit.
> Migrate HLAPI tests to phpunit

- src/Glpi/Config/LegacyConfigurators/StandardIncludes.php
- src/Glpi/Console/Application.php
- src/Glpi/Controller/MaintenanceController.php
- src/Glpi/Http/Listener/CheckMaintenanceListener.php
- src/Glpi/Kernel/ListenersPriority.php
> Move maintenance check to a controller and console event

- src/Transfer.php
> fix(transfer): add initForm, close #18507

- src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
- tests/cypress/e2e/form/question_types/actors.cy.js
Fixed a problem that prevented forms containing empty "Actors" type questions from being sent, which authorized several actors at the same time.
> fix(forms): Issue with sending forms with empty multiple actors questions

- install/empty_data.php
- phpunit/functional/NotificationTargetKnowbaseItemTest.php
- phpunit/functional/NotificationTargetTest.php
- src/NotificationTargetKnowbaseItem.php
Adds default in notifications that did not own by administrator as recipient.
> feat(notification): Adds the administrator as a recipient

- css/includes/components/itilobject/_timeline.scss
- tests/cypress/e2e/ITILObject/ticket_form.cy.js
> Hide pending reason reminders in TODO list view

- phpunit/functional/TicketTest.php
- src/CommonITILObject.php
Fixes #13601
This is only a visual bug and it had no effect on the actual actors added since duplicates are already handled during `prepareInputForAdd` for CommonITILActor.
> Deduplicate actors from templates

- composer.json
- composer.lock
> Upgrade `tecnickcom/tcpdf` to get latest security fixes

- src/NotificationTemplate.php
> HTML 5 doctype and headers for notifications

- phpunit/imap/MailCollectorTest.php
- src/MailCollector.php
- It fixes !35444
Texts including HTML tags, for example a specific link, were not filtered and therefore remained in the ticket.
> fix(mail collector): blacklisted mail content

- src/CommonDBTM.php
- src/Ticket.php
> Apply some defaults to Ticket from other items on initial load only

- templates/components/datatable.html.twig
- templates/components/itilobject/timeline/pending_reasons_messages.html.twig
- templates/pages/admin/inventory/agent.html.twig
> Use existing Twig functions/filters instead of static methods calls

- css/includes/components/_global-menu.scss
> left menu collapsed unusable - fix #17930

- css/includes/_base.scss
> bootstrap tooltip colors - fix #18679

- tests/cypress/e2e/search/display_preferences.cy.js
> Fix e2e tests again

- phpunit/DbTestCase.php
- phpunit/functional/Glpi/Controller/CommonAJAXControllerTest.php
- phpunit/functional/Glpi/Dropdown/DropdownDefinitionManagerTest.php
- phpunit/functional/Glpi/Dropdown/DropdownDefinitionTest.php
- phpunit/functional/Glpi/Dropdown/DropdownTest.php
- phpunit/functional/Glpi/Search/Input/QueryBuilderTest.php
- phpunit/functional/Glpi/Search/Provider/SQLProviderTest.php
- phpunit/functional/Glpi/Search/SearchOptionTest.php
- phpunit/functional/Glpi/Session/SessionInfoTest.php
- tests/DbTestCase.php
This is the latest bunch of tests that are present only on main branch.
> Migrate more tests to phpunit

- src/Glpi/Console/Database/ConfigureCommand.php
- [x ] I have read the CONTRIBUTING document.
better documentation on console cli : update description to database:configure console command
> update description to database:configure console command

- tests/bootstrap.php
removed include of moved files in atoum bootstrap file which cause atoum test to fail when bootstrap file used.
> [tests] removed include of moved files in atoum bootstrap file

- css/helpdesk_home.scss
Search banner background was not visible
> fix: search-banner background

- .github/actions/test_tests-cache.sh
- phpunit/functional/Calendar_HolidayTest.php
- phpunit/functional/DbUtilsTest.php
- phpunit/functional/EntityTest.php
> fix cache tests test: Update test launch script and PHP attribute in cache tests

- .github/actions/test_tests-cache.sh
- phpunit/functional/Calendar_HolidayTest.php
- phpunit/functional/DbUtilsTest.php
- phpunit/functional/EntityTest.php
> fix cache tests test: Update test launch script and docbloc tag in cache tests

- .phpstan-baseline.php
- src/Html.php
- templates/components/form/viewsubitem.html.twig
Some URLs were not prefixed by the GLPI root path.
> Fix missing URLs prefixes

- css/includes/components/form/_form-editor.scss
- templates/pages/admin/form/form_editor.html.twig
Fixed a bug on the form destination edit page that prevented scrolling once the accordion had been unrolled.
> fix(forms): Resolve scrolling issue in form destinations

- src/Cartridge.php
> Fix adding cartridges

- templates/components/form/buttons.html.twig
- templates/generic_show_form.html.twig
> Reduce spacing in form footers

- src/Glpi/Controller/ErrorController.php
This may help to identify issues.
> Display previous exceptions traces in error page

- .phpstan-baseline.php
- src/Ajax.php
- src/CommonGLPI.php
- Linked to this PR https://github.com/pluginsGLPI/fields/pull/911
> Fix of incorrect typing of method parameters

- src/Glpi/Form/AccessControl/ControlType/DirectAccess.php
Unlikely to be exploited but easy to fix.
> Prevent timing attacks on helpdesk form tokens

- phpunit/DbTestCase.php
- src/CommonDBTM.php
- src/QueryExpression.php
- src/QueryParam.php
- src/QuerySubQuery.php
- src/QueryUnion.php
> Improve DbTestCase::checkInput() message + documentation improvements

- css/includes/components/_utils.scss
- js/modules/Helpdesk/HelpdeskConfigController.js
- src/Glpi/Controller/Config/Helpdesk/AddTileController.php
- src/Glpi/Controller/Config/Helpdesk/DeleteTileController.php
- src/Glpi/Controller/Config/Helpdesk/SetTilesOrderController.php
- src/Glpi/Controller/Config/Helpdesk/ShowAddTileFormController.php
- src/Glpi/Controller/Config/Helpdesk/ShowEditTileFormController.php
- src/Glpi/Controller/Config/Helpdesk/UpdateTileController.php
- src/Glpi/Helpdesk/Tile/ExternalPageTile.php
- src/Glpi/Helpdesk/Tile/FormTile.php
- src/Glpi/Helpdesk/Tile/GlpiPageTile.php
- src/Glpi/Helpdesk/Tile/TileInterface.php
- src/Glpi/Helpdesk/Tile/TilesManager.php
- templates/pages/admin/external_page_tile_config_fields.html.twig
- templates/pages/admin/form_tile_config_fields.html.twig
- templates/pages/admin/glpi_page_tile_config_fields.html.twig
- templates/pages/admin/helpdesk_home_config.html.twig
- templates/pages/admin/helpdesk_home_config_add_tile_form.html.twig
- templates/pages/admin/helpdesk_home_config_edit_tile_form.html.twig
- templates/pages/admin/helpdesk_home_config_tiles.html.twig
- templates/pages/helpdesk/index.html.twig
- tests/cypress/e2e/self-service/home_config.cy.js
Followup to #18682.
Two more actions are added:
*  Edit a tile details
*  Add a new tile
Edit a tile details:
Add a new tile:
> Configure helpdesk home per profile 2/2

- phpunit/functional/Glpi/Form/CategoryTest.php
- src/CommonDBTM.php
- src/CommonTreeDropdown.php
- src/Glpi/Form/Category.php
- src/Glpi/Form/Form.php
This help seeing all the forms associated to a given category.
> Add "forms" tabs to service catalog categories

- css/includes/components/itilobject/_layout.scss
- phpunit/functional/TicketTest.php
- src/Ticket.php
- templates/components/itilobject/footer.html.twig
- templates/components/itilobject/layout.html.twig
- templates/components/itilobject/timeline/filter_timeline.html.twig
- templates/components/itilobject/timeline/timeline.html.twig
- templates/layout/parts/page_header.html.twig
Simplify the ticket page on the helpdesk, as it was done by formcreator "simplified interface" mode.
We will also offer an advanced mode with more details displayed (off by default) but it will be done later as we need to discuss what we include in it.
Before:
After:
> Simplify ticket page on helpdesk

- src/MassiveAction.php
- src/Plugin/Hooks.php
> add missing constant for 'use_massive_action' hook

- src/ReservationItem.php
As can exist multiple reservations (not only one), show the tab name on plural.
> Show Reservation tab on plural

- src/Application/View/Extension/FrontEndAssetsExtension.php
- src/Html.php
After this PR:
Notice that now it shows "Buscando" ("Searching" in pt-BR) instead. The translation is provided by [select2](https://select2.org/i18n) and already embedded on page by ``inc/Html.php`` file.
> Translate select2 dropdowns

- templates/pages/admin/assetdefinition/capacities.html.twig
Filter the list of capacities with a top input
> input to filter capacities

- js/dashboard.js
It fixes a regression present since merge of #18842 
As the mini dashboard in the tickets list doesn't have filters, the resizeSelect function fails.
> fix broken mini dashboard on tickets list

- templates/pages/admin/assetdefinition/capacities.html.twig
> redesign capacities list

- phpunit/functional/TicketTest.php
- templates/components/itilobject/footer.html.twig
Fix #18908, this button should never be visible on the central interface.
> Fix cancel ticket button on central

- composer.lock
- phpunit/functional/Glpi/Inventory/InventoryTest.php
Inventory library now allows additional properties; a test checking that has been added
> Update glpi inventory library, add test

- composer.lock
- phpunit/functional/Glpi/Inventory/InventoryTest.php
- src/Glpi/Inventory/Inventory.php
Same as https://github.com/glpi-project/glpi/pull/18957, for main
>  Update glpi inventory library, add test

- .github/actions/test_update-from-9.5.sh
- .github/actions/test_update-from-older-version.sh
- tests/src/Command/TestUpdatedDataCommand.php
> Fix unexpected warnings in TestUpdatedDataCommand

- css/install.scss
> Fix radio elements color in install process

- phpunit/DbTestCase.php
- src/CommonDBTM.php
- tests/src/autoload/functions.php
> Some docbloc fixes

- css/includes/components/form/_form-renderer.scss
- js/modules/Forms/Condition/Engine.js
- js/modules/Forms/EditorController.js
- js/modules/Forms/RendererController.js
- phpunit/functional/Glpi/Form/ConditionalVisibility/EngineTest.php
- src/Glpi/Controller/Form/ConditionalVisibility/EditorController.php
- src/Glpi/Controller/Form/ConditionalVisibility/EngineController.php
- src/Glpi/Controller/Form/RendererController.php
- src/Glpi/Form/ConditionalVisiblity/ConditionData.php
- src/Glpi/Form/ConditionalVisiblity/ConditionnableInterface.php
- src/Glpi/Form/ConditionalVisiblity/ConditionnableTrait.php
- src/Glpi/Form/ConditionalVisiblity/Engine.php
- src/Glpi/Form/ConditionalVisiblity/EngineInput.php
- src/Glpi/Form/ConditionalVisiblity/EngineOutput.php
- src/Glpi/Form/ConditionalVisiblity/LogicOperator.php
- src/Glpi/Form/ConditionalVisiblity/ValueOperator.php
- src/Glpi/Form/ConditionalVisiblity/VisibilityStrategy.php
- src/Glpi/Form/QuestionType/QuestionTypeLongText.php
- src/Html.php
- templates/pages/admin/form/conditional_visibility_dropdown.html.twig
- templates/pages/admin/form/conditional_visibility_editor.html.twig
- templates/pages/admin/form/form_question.html.twig
- templates/pages/form_renderer.html.twig
- tests/cypress/e2e/form/editor/conditions.cy.js
- tests/src/FormBuilder.php
- tests/src/FormTesterTrait.php
Apply visibility conditions to forms (= hide/show some part of the helpdesk form depending on the answers).
Conditions are applied correctly to comments and questions.
Sections are not handled yet, I'll complete it in another PR as this one is getting a bit too big and there a few specific cases that I need to handle.
> Apply conditions to forms

- templates/pages/management/domainrecord.html.twig
Domain records, like assets, can have multiple groups now
> Group field for domain records needs to be multiselect

- src/Glpi/Plugin/Hooks.php
- src/Html.php
> replace menu_toadd hook by a constant

- src/Item_Enclosure.php
> Fix item enclosure list massive actions

- phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
- src/Glpi/Form/ConditionalVisiblity/ConditionData.php
- src/Glpi/Form/Export/Context/ForeignKey/QuestionForeignKeyHandler.php
- src/Glpi/Form/Export/Serializer/FormSerializer.php
- src/Glpi/Form/Export/Specification/ConditionDataSpecification.php
- tests/fixtures/export-of-2-forms.json
Add export and import functionality for question conditions
> feat(forms): Add export and import functionality for question conditions

- src/UserEmail.php
- It fixes !36346
- Fix rights check for emails when adding user
- Follows https://github.com/glpi-project/glpi/pull/18441
> Can add emails on user creation

- css/includes/components/_utils.scss
- js/modules/Forms/Condition/Engine.js
- js/modules/Forms/RendererController.js
- phpunit/functional/Glpi/Form/ConditionalVisibility/EngineTest.php
- src/Glpi/Controller/Form/ConditionalVisibility/EngineController.php
- src/Glpi/Form/ConditionalVisiblity/Engine.php
- src/Glpi/Form/ConditionalVisiblity/EngineOutput.php
- templates/pages/form_renderer.html.twig
- tests/cypress/e2e/form/editor/conditions.cy.js
> Apply conditions to sections

- install/empty_data.php
- install/migrations/update_10.0.x_to_11.0.0/softwares.php
- phpunit/functional/PurgeSoftwareCronTest.php
- src/Glpi/Console/Assets/PurgeSoftwareCommand.php
- src/PurgeSoftwareCron.php
- src/PurgeSoftwareTask.php
- src/Software.php
- It fixes !34964
Add assets:purgesoftware action
> Feat - assets:purgesoftware

- .phpstan-baseline.php
- src/ProjectTask.php
Migrate project task planning and sublists to Twig to use standardized UI design
> Migrate ProjectTask planning and sublists to Twig

- ajax/visibility.php
- src/CommonDBVisible.php
- templates/components/add_visibility_target.html.twig
Migrate visibility tabs to Twig to use standardized UI design
> Migrate visibility targets UI to Twig

- .phpstan-baseline.php
- src/Certificate_Item.php
- templates/components/form/fields_macros.html.twig
Migrate certificate item tabs to Twig to use standardized UI design
> Migrate Certificate item tabs to Twig

- .phpstan-baseline.php
- CHANGELOG.md
- phpunit/functional/EntityTest.php
- src/CommonITILObject.php
- src/Itil_Project.php
- src/Project.php
- templates/components/form/basic_inputs_macros.html.twig
- templates/components/form/fields_macros.html.twig
- templates/generic_show_form.html.twig
- templates/pages/tools/project.html.twig
Migrate project form and sublists to Twig to use standardized UI design
Project Sublist (old on top):
Project Form Before:
Project Form After:
> Migrate Projects to Twig

- src/Glpi/Inventory/Conf.php
With new UI, it is more clear; and it prevents having to list all rules related to inventory in configuration
> Link to global rules from inventory

- front/olalevel.form.php
- front/rule.common.form.php
- front/slalevel.form.php
These actions are not used anymore.
> Drop dead code from `Rule` front scripts

- src/Glpi/Form/AccessControl/ControlType/AllowListDropdown.php
Suggested by @orthagh, the following link has been improved to be clearer:
Before:
After (grouped criteria + user login instead of ids):
> Improve allow list search link

- src/Contact.php
VCard button was showing only when creating Contacts. This PR removes the button for new Contacts and makes it show for existing Contacts.
> Fix contact vcard button

- phpunit/functional/Glpi/Migration/AbstractPluginMigrationTest.php
- phpunit/functional/Glpi/Progress/ConsoleProgressIndicatorTest.php
- src/Glpi/Console/Traits/PluginMigrationTrait.php
- src/Glpi/Migration/AbstractPluginMigration.php
- src/Glpi/Migration/PluginMigrationResult.php
- src/Glpi/Progress/ConsoleProgressIndicator.php
- Move progress feedback messages below the progress bar.
- Add missing spacing between icons and texts in command result output.
- Do not update items when the plugin item is outdated.
- Do not update items when there is actually no value change.
- Never output a message in both progress indicator and result.
- Add a method to validate DB fields existence.
> Enhance the plugin migration framework

- phpunit/functional/Glpi/Inventory/Assets/OperatingSystemTest.php
- phpunit/functional/Glpi/Inventory/Assets/SoftwareTest.php
- phpunit/functional/LockedfieldTest.php
- src/CommonDBTM.php
- src/Inventory/Asset/InventoryAsset.php
> Fix inventory error when item_os has been locked

- src/Glpi/Form/QuestionType/QuestionTypeDateTime.php
- tests/cypress/e2e/form/question_types/date_and_time.cy.js
Corrected options for `Date and Time` type questions.
> fix(forms): Fixed behavior of Date and Time question type options

- install/migrations/update_10.0.x_to_11.0.0/form.php
- install/mysql/glpi-empty.sql
- phpunit/functional/Glpi/Form/ServiceCatalog/ServiceCatalogManagerTest.php
- src/Glpi/Form/Category.php
- src/Glpi/Form/Form.php
- src/Glpi/Form/ServiceCatalog/ServiceCatalogItemInterface.php
- src/Glpi/Form/ServiceCatalog/ServiceCatalogManager.php
- templates/pages/admin/form/service_catalog_tab.html.twig
- tests/src/FormBuilder.php
- tests/src/FormTesterTrait.php
Added the possibility of pinning certain forms in the service catalog.
I'm not totally satisfied with the integration of the Yes/No dropdown to modify the pinning status.
> feat(forms): Add pinned status to forms and update sorting logic

- phpunit/functional/Glpi/Form/ConditionalVisibility/EditorManagerTest.php
- phpunit/functional/Glpi/Form/ConditionalVisibility/EngineTest.php
- src/CommonDBTM.php
- src/Glpi/Form/ConditionalVisiblity/EditorManager.php
- src/Glpi/Form/ConditionalVisiblity/Engine.php
- src/Glpi/Form/ConditionalVisiblity/InputTemplateKey.php
- src/Glpi/Form/ConditionalVisiblity/NumberConditionTrait.php
- src/Glpi/Form/ConditionalVisiblity/StringConditionTrait.php
- src/Glpi/Form/ConditionalVisiblity/ValueOperator.php
- src/Glpi/Form/QuestionType/QuestionTypeEmail.php
- src/Glpi/Form/QuestionType/QuestionTypeShortText.php
- templates/pages/admin/form/conditional_visibility_editor.html.twig
- tests/cypress/e2e/form/editor/conditions.cy.js
Support conditions on questions that expect a number value.
> Forms: support conditions on numeric values

- src/Contact_Supplier.php
- templates/pages/management/contact_supplier.html.twig
Migrate Contact_Supplier tabs to Twig to use standardized UI design
> Migrate contact supplier tabs to Twig

- src/Item_Line.php
- templates/pages/management/item_line.html.twig
Migrate Item_Line tabs to Twig to use standardized UI design
> Migrate Line tabs to Twig

- src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
- src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php
- src/Glpi/Form/Destination/CommonITILField/Category.php
- src/Glpi/Form/Destination/CommonITILField/ContentField.php
- src/Glpi/Form/Destination/CommonITILField/EntityField.php
- src/Glpi/Form/Destination/CommonITILField/ITILActorField.php
- src/Glpi/Form/Destination/CommonITILField/ITILCategoryField.php
- src/Glpi/Form/Destination/CommonITILField/ITILFollowupField.php
- src/Glpi/Form/Destination/CommonITILField/ITILTaskField.php
- src/Glpi/Form/Destination/CommonITILField/LocationField.php
- src/Glpi/Form/Destination/CommonITILField/OLATTOField.php
- src/Glpi/Form/Destination/CommonITILField/ObserverField.php
- src/Glpi/Form/Destination/CommonITILField/RequestSourceField.php
- src/Glpi/Form/Destination/CommonITILField/RequestTypeField.php
- src/Glpi/Form/Destination/CommonITILField/RequesterField.php
- src/Glpi/Form/Destination/CommonITILField/SLATTOField.php
- src/Glpi/Form/Destination/CommonITILField/SLMField.php
- src/Glpi/Form/Destination/CommonITILField/TemplateField.php
- src/Glpi/Form/Destination/CommonITILField/TitleField.php
- src/Glpi/Form/Destination/CommonITILField/UrgencyField.php
- src/Glpi/Form/Destination/CommonITILField/ValidationField.php
- src/Glpi/Form/Destination/DestinationFieldInterface.php
- src/Glpi/Form/Destination/FormDestinationTicket.php
- templates/pages/admin/form/form_destination_commonitil_config.html.twig
Improve the display of the form destination configuration:
* Group item by categories with label + icon
* Order categories
* Update fields weight to sort them logically inside their own categories
There are still others improvements that I have in mind but it will be done in another PR
I recommend disabling white space changes while consulting the diff for the changed twig file.
> Improve destination configuration

- phpunit/functional/Glpi/Inventory/Assets/UnmanagedTest.php
- src/Inventory/Inventory.php
> Check configuration before handling main item

- js/modules/Forms/ServiceCatalogController.js
- phpunit/functional/Glpi/Form/ServiceCatalog/ServiceCatalogManagerTest.php
- src/Glpi/Controller/Helpdesk/SearchController.php
- src/Glpi/Controller/ServiceCatalog/ItemsController.php
- src/Glpi/Form/Category.php
- src/Glpi/Form/ServiceCatalog/ItemRequest.php
- src/Glpi/Form/ServiceCatalog/ServiceCatalogManager.php
- templates/components/helpdesk_forms/service_catalog_items.html.twig
- templates/components/helpdesk_forms/service_catalog_nested_item.html.twig
- templates/pages/helpdesk/search.html.twig
- templates/pages/self-service/service_catalog.html.twig
- tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
Added a pagination system to the service catalog.
I've noticed a few problems with the pagination style.
The contrast between “disabled” elements and the background is almost non-existent.
Currently, the forms in a category, displayed from the parent category, are not paginated.
In my opinion, it would be interesting to hide a part of the forms and add a button redirecting to the category, or hide a part that can be revealed by a collapse.
#18899 Must be merged first.
> feat(forms): Add pagination system for service catalog

- src/CalendarSegment.php
- tests/cypress/e2e/Setup/Dropdowns/calendar.cy.js
Fixes #19060.
- Adds missing data which prevented the form element from being added.
- Add icon for the Time Ranges tab
- Remove unneeded form header
> Fix Calendar Time Range Form

- templates/components/search/displaypreference_config.html.twig
- tests/cypress/e2e/search/display_preferences.cy.js
> Fix hiding used options in display preference dropdown

- templates/pages/admin/customobjects/translations.html.twig
> Force initialization of tooltips in custom asset translations tab

- css/includes/components/_process-chart.scss
`auto` is not a valid value for `text-wrap`.
> Fix rule list text wrapping

- src/Profile.php
Fixes #19091. Only applies to `main` as far as I can tell.
> Fix saving managed domain record types

- .devcontainer/docker-compose.yaml
- .docker/README.md
- .docker/app/Dockerfile
- docker-compose.yaml
To be able to use the different versions added by https://github.com/glpi-project/docker-images/pull/138.
> Add ability to customize PHP version in the docker env

- install/migrations/update_10.0.x_to_11.0.0/form.php
- install/mysql/glpi-empty.sql
- js/modules/Forms/ConditionEditorController.js
- src/Glpi/Form/Comment.php
- src/Glpi/Form/Condition/ConditionnableTrait.php
- src/Glpi/Form/Condition/CreationStrategy.php
- src/Glpi/Form/Condition/FormData.php
- src/Glpi/Form/Destination/FormDestination.php
- src/Glpi/Form/Form.php
- src/Glpi/Form/Question.php
- src/Glpi/Form/Section.php
- templates/pages/admin/form/condition_configuration.html.twig
- templates/pages/admin/form/conditional_visibility_dropdown.html.twig
- templates/pages/admin/form/destination_visibility_conditions_configuration.html.twig
- templates/pages/admin/form/form_destination.html.twig
- tests/cypress/e2e/ajax_controller.cy.js
- tests/cypress/e2e/form/editor/conditions.cy.js
Add the condition editors for the form destinations feature.
Conditions can be configured but they are not yet applied, it will be done in a second PR.
> Add conditions to form destinations

- phpunit/functional/Glpi/Form/Tag/TagTest.php
- src/Glpi/Form/Tag/Tag.php
- tests/cypress/e2e/form/form_tags.cy.js
Suggested by @orthagh, this helps user discover the "#" autocomplete prefix.
Before:
After:
> Display form tags prefix

- phpunit/functional/LockedfieldTest.php
- src/Lockedfield.php
- It fixes !36656
The page for adding global locks was not displayed and generated this error in the logs:
```
glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Lockedfield::canAccessItemEntity(): Argument #2 ($items_id) must be of type int, string given, called in .../src/Lockedfield.php on line 74 in .../src/Lockedfield.php at line 105
Backtrace :
src/Lockedfield.php:74                             Lockedfield->canAccessItemEntity()
src/CommonDBTM.php:2954                            Lockedfield->canCreateItem()
ajax/common.tabs.php:93                            CommonDBTM->can()
public/index.php:82                                require()
```
> fix(locked field): error to add global lock

- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Console/Migration/AbstractPluginMigrationCommand.php
- src/Glpi/Console/Migration/FormCreatorPluginToCoreCommand.php
- src/Glpi/Form/Migration/FormMigration.php
- tests/glpi-formcreator-migration-data.sql
Implement form access type migration
> feat(forms): Implement form access type migration

- resources/api_doc.MD
- Add information about scopes now that they have been implemented.
- Explain "Client Credentials" grant which isn't usable for most API endpoints.
- Mention the name of the parameter that accepts the RSQL filters.
> Update HLAPI Getting Started Documentation

- src/KnowbaseItemTranslation.php
> Missing html close tag

- js/modules/Forms/QuestionDateTime.js
- src/Glpi/Form/QuestionType/QuestionTypeDateTime.php
- tests/cypress/e2e/form/question_types/date_and_time.cy.js
Conversion of date values for datetime questions.
Values are now preserved when going from a date to a date + time for example.
I took the opportunity to remove the inline javascript code from the PHP file and migrate it to a dedicated JS file.
> feat(forms): Handle default value conversions for datetime question type

- css/includes/components/form/_form-editor.scss
- phpunit/functional/Glpi/Form/Condition/ConditionHandler/DateConditionHandlerTest.php
- phpunit/functional/Glpi/Form/Condition/ConditionHandler/DateTimeConditionHandlerTest.php
- phpunit/functional/Glpi/Form/Condition/ConditionHandler/NumberConditionHandlerTest.php
- phpunit/functional/Glpi/Form/Condition/ConditionHandler/RichTextConditionHandlerTest.php
- phpunit/functional/Glpi/Form/Condition/ConditionHandler/StringConditionHandlerTest.php
- phpunit/functional/Glpi/Form/Condition/ConditionHandler/TimeConditionHandlerTest.php
- phpunit/functional/Glpi/Form/Condition/ConditionHandler/UrgencyConditionHandlerTest.php
- src/Glpi/Form/Condition/ConditionHandler/NumberConditionHandler.php
- src/Glpi/Form/Condition/ConditionHandler/UrgencyConditionHandler.php
- src/Glpi/Form/QuestionType/QuestionTypeUrgency.php
- src/Glpi/Urgency.php
- templates/pages/admin/form/conditional_visibility_editor.html.twig
- tests/cypress/e2e/form/editor/conditions.cy.js
> Helpdesk forms: add support for conditions on urgency questions

- phpunit/functional/Glpi/Form/Condition/ConditionHandler/RequestTypeConditionHandlerTest.php
- src/Glpi/Form/Condition/ConditionHandler/RequestTypeConditionHandler.php
- src/Glpi/Form/QuestionType/QuestionTypeRequestType.php
- templates/pages/admin/form/conditional_visibility_editor.html.twig
- tests/cypress/e2e/form/editor/conditions.cy.js
> Helpdesk forms: add support for conditions on request type questions

- src/Document_Item.php
Seen in PR https://github.com/glpi-project/glpi/pull/19120
Corrects the display of associated items
_The document is linked to several ticket solutions_
Before:
After:
> fix(document): associated items link

- templates/pages/admin/form/import/step3_resolve_issues.html.twig
This seems to have been commited by mistake in #18276.
> Remove console.log debug statement

- phpunit/functional/Glpi/Migration/AbstractPluginMigrationTest.php
- src/Glpi/Migration/AbstractPluginMigration.php
From #19033.
1) The `AbstractPluginMigration::copyItems()` can be used to copy items found using the given criteria, after applying some replacements.
```php
$this->copyItems(
FieldUnicity::class,
where: ['itemtype' => 'PluginMyPluginAsset'],
replacements: [
[
'field' => 'itemtype',
'from'  => 'PluginMyPluginAsset',
'to'    => $asset_definition->getAssetClassName(),
]
]
);
```
2) The `AbstractPluginMigration::copyPolymorphicConnexityItems()` can be used to copy all `CommonDBRelation` and all `CommonDBChild` attached to the source item and attach them to the target item.
```php
$this->copyPolymorphicConnexityItems(
'PluginMyPluginAsset',
$plugin_asset_id,
$imported_asset::class,
$imported_asset->getID()
);
```
> Add a function to ease the copy of related items in plugins migration

- css/legacy/includes/_planning.scss
- js/planning.js
- It fixes !36063
Fix minor issue : 
- The appointment tooltip currently appears exactly where the mouse pointer enters the appointment. In busy schedules, this behavior is inconvenient and reduces overall visibility.
- The minimum height for an appointment is set to 13px (for instance, a 5-minute appointment lasting less than 30 minutes). This configuration allocates approximately 10-12px for the resize handle and 1px for the area that opens the appointment form.
Before : 
After : 
1 - row size have been increase
2 - The minimum size of an appointment too
Tooltip are display to bottom right corner
> Fix(Planning): improve UX

- src/CalendarSegment.php
> Only allow purge action for calendar time ranges

- package-lock.json
> Update dependencies to get latests vulnerabilities fixes

- install/migrations/update_10.0.x_to_11.0.0/networkportmigrations.php
Failed when testing migration from a customer database
> drop glpi_networkportmigrations only if presents

- templates/pages/admin/user/user.html.twig
> move user form buttons back into form

- phpunit/functional/LogTest.php
- src/CommonDBTM.php
- src/Log.php
Fix two issues with form history.
1) Do not display json values
2) Make sure "Add the item" is always the first value.
> Fix form logs

- src/Glpi/Controller/Knowbase/KnowbaseItemController.php
- templates/components/itilobject/timeline/form_followup.html.twig
- templates/components/itilobject/timeline/form_solution.html.twig
- templates/components/itilobject/timeline/knowledge_item.html.twig
- templates/pages/tools/search_knowbaseitem.html.twig
- tests/cypress/e2e/ITILObject/ticket_form.cy.js
- It fixes !36633
- This RP adds the ability to use a knowledge base article to create a follow up in the same way as solutions
> feat: add knowlegde for followup

- .phpstan-baseline.php
- ajax/comments.php
- src/Ajax.php
- src/Dropdown.php
- src/Html.php
phpdoc fixes + clean phpstan baseline related entries
> Minor phpdoc issues found from a plugin phpstan compliance

- templates/components/search/displaypreference_list.html.twig
- tests/cypress/e2e/Setup/General/displaypreference_list.cy.js
Following #19207
- filter was broken at merge due to late display changes. I moved to a dedicated class distinct from display one to avoid that in the future
- prevent [Enter] key in filter to submit massive action form
> fix filter in search result display and prevent submit on Enter

- js/modules/Helpdesk/HelpdeskConfigController.js
- src/Glpi/Controller/Config/Helpdesk/DeleteTileController.php
- src/Glpi/Helpdesk/Tile/TilesManager.php
- templates/components/form/fields_macros.html.twig
- templates/components/illustration/icon_picker_modal.html.twig
- templates/pages/admin/external_page_tile_config_fields.html.twig
- templates/pages/admin/glpi_page_tile_config_fields.html.twig
- templates/pages/admin/helpdesk_home_config.html.twig
- templates/pages/admin/helpdesk_home_config_add_tile_form.html.twig
- templates/pages/admin/helpdesk_home_config_edit_tile_form.html.twig
- templates/pages/admin/helpdesk_home_config_tiles.html.twig
- tests/cypress/e2e/self-service/home_config.cy.js
Rework the helpdesk home page tiles configuration using an offcanvas panel.
Add a tile:
Edit a tile:
Delete a tile:
Reorder tiles:
> Rework home tile configuration UX

- css/includes/components/_illustration-picker.scss
- css/includes/components/_tabs.scss
- css/legacy/includes/_styles.scss
- dependency_injection/services.php
- js/modules/IllustrationPicker/Controller.js
- src/Glpi/Controller/UI/Illustration/CustomIllustrationController.php
- src/Glpi/Controller/UI/Illustration/UploadController.php
- src/Glpi/UI/IllustrationManager.php
- templates/components/form/fields_macros.html.twig
- templates/components/illustration/custom_icon.html.twig
- templates/components/illustration/icon_picker_modal.html.twig
- templates/pages/admin/form/service_catalog_tab.html.twig
- tests/cypress/e2e/illustration_picker.cy.js
Allow users to upload a custom image in the illustration picker.
I've also had to fix the styles after the latest tabler update... it was small details but there are probably issues elsewhere too.
> Upload custom illustrations

- templates/components/form/basic_inputs_macros.html.twig
- templates/components/form/fields_macros.html.twig
- templates/components/pager.html.twig
- templates/pages/tools/item_project.html.twig
- templates/pages/tools/kb/knowbaseitem_item.html.twig
It fixes some typo in variabels/method names detected in #18685.
> Fix misc bugs

- phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
- src/Glpi/Form/Comment.php
- src/Glpi/Form/Export/Context/DatabaseMapper.php
- src/Glpi/Form/Export/Context/ForeignKey/CommentForeignKeyHandler.php
- src/Glpi/Form/Export/Context/ForeignKey/SectionForeignKeyHandler.php
- src/Glpi/Form/Export/Serializer/FormSerializer.php
- src/Glpi/Form/Export/Specification/FormContentSpecification.php
- src/Glpi/Form/Export/Specification/TranslationContentSpecification.php
- src/Glpi/Form/FormTranslation.php
- src/Glpi/Form/Section.php
Adds export and import of form translations
> feat(forms): Add export and import functionality for translations

- css/standalone/dashboard.scss
- src/Html.php
- templates/components/form/basic_inputs_macros.html.twig
> Fix dashboard date filter clear button

- src/Glpi/Asset/Asset.php
> Add custom field search option category

- css/includes/components/form/_form-destination.scss
- templates/pages/admin/form/form_destination.html.twig
- templates/pages/admin/form/form_destination_commonitil_config.html.twig
Fixed a few minor issues concerning the form destination interface and its behavior.
- Multiple id issues that prevented accordions from working properly: when one accordion was open and another was opened, the first one didn't close.
- Removal of the mechanism that dynamically calculated input width.
> fix(forms): Make some UI/UX fixes for destinations : accordion & remove dynamic input

- phpunit/DbTestCase.php
- phpunit/LDAP/AuthLdapTest.php
- phpunit/functional/DbUtilsTest.php
- src/CommonDBTM.php
- src/CommonDropdown.php
- src/Migration.php
- tests/src/autoload/functions.php
- **fix bad typehint**
- **test docblock + explicit error if field provided in checkInput is not present in created object**
- **src docblocks**
> docblock fixes

- src/Glpi/Migration/GenericobjectPluginMigration.php
I tried to import the `genericobject` from a database that contained some kind of demo data. In this database, there are multiple assets having the same name in he same entity and created at the exact same time. These 3 properties were used as reconciliation criteria and it results in an unexpected behaviour. Indeed, the first asset was imported, then the second was merged with the first one, and so on. If both have `CommonDBChild` that are expected to be unique, it also results in an error (either at the PHP level, or with SQL unicity keys).
The idea behind the reconciliation logic was to be able to replay the migration in case of a failure, but as long as the migration is now executed inside a transaction, there is no reason to re-execute it.
I removed the reconciliation logic for the …
> Do not try to reconciliate `genericobject` assets during import

- src/Glpi/Application/View/Extension/I18nExtension.php
- src/Glpi/Application/View/TemplateRenderer.php
This revert the technical changes of #19257 (first commit) while keeping the various fixes (second commit).
We discovered some issues due to this change that can't be fixed yet :
* Some macros call translations, which create fatal errors if they are included by an inline template
* Cache issues
> Partiel revert of #19257

- src/ProjectTask.php
https://github.com/user-attachments/assets/1ece391f-a067-45ef-a16f-ac91efd0abe1
redirect to _not found item_ page
see attached video
> fix url to add a task in project

- phpunit/functional/Glpi/Features/DCBreadcrumbTest.php
- phpunit/functional/TransferTest.php
- src/DCRoom.php
- src/Rack.php
> dcroom  number of rows and columns must be a positive integer

- front/form/form.form.php
Solves two issues reported in #19284:
* Check the "is_recursive" checkbox.
* Always go to main tab
> Form creation tweaks

- js/modules/IllustrationPicker/Controller.js
- tests/cypress/e2e/illustration_picker.cy.js
Autofocus icon picker search bar when the modal is opened.
> Autofocus icon picker search bar

- .phpstan-baseline.php
- inc/relation.constant.php
- install/migrations/update_10.0.x_to_11.0.0/printerlog.php
- install/mysql/glpi-empty.sql
- phpunit/functional/Glpi/Asset/Capacity/IsInventoriableCapacityTest.php
- phpunit/functional/Glpi/Inventory/Assets/PrinterTest.php
- phpunit/functional/PrinterLogTest.php
- src/Glpi/Asset/AssetDefinitionManager.php
- src/Glpi/Asset/Capacity/AbstractCapacity.php
- src/Glpi/Asset/Capacity/CapacityInterface.php
- src/Glpi/Asset/Capacity/IsInventoriableCapacity.php
- src/Glpi/Inventory/MainAsset/Printer.php
- src/PrinterLog.php
- src/autoload/CFG_GLPI.php
> Add a printer type we can rely on for PrinterLog

- css/includes/components/_utils.scss
- templates/components/helpdesk_forms/service_catalog_item.html.twig
- tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
-> Only UI related changes.
Add specific style for pinned forms.
> Add specific style for pinned forms

- src/Glpi/Plugin/Hooks.php
- src/Plugin.php
- src/RuleImportEntity.php
> Add missing hooks names constants (#19343)

- src/NotificationTarget.php
In admin > Setup > Notification : edit a notification, go to 'recipients' tab, click "update".
Then a php error is triggered, see screenshot.
> fix update notification recipient

- css/includes/components/_illustration-picker.scss
- css/includes/components/_utils.scss
- src/Glpi/Form/Form.php
- templates/components/form/fields_macros.html.twig
- templates/components/helpdesk_forms/service_catalog_nested_item.html.twig
- templates/layout/parts/context_links.html.twig
- templates/pages/admin/external_page_tile_config_fields.html.twig
- templates/pages/admin/form/service_catalog_tab.html.twig
- templates/pages/admin/glpi_page_tile_config_fields.html.twig
> Small forms tweaks

- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Form/Migration/FormMigration.php
Handle orphan sections and questions during migration.
Adding new tests for these scenarios and modifying the migration logic to handle them appropriately.
> fix(forms-migration): add error handling for orphan sections and questions during migration

- src/Glpi/Kernel/Kernel.php
It fixes #19379.
When both the cache dir and the log dir are not writable, the GLPI administrator has currently no indication about the reason that prevent GLPI to run, unless on dev/testing env.
In this case, as the Symfony kernel cannot be booted, it is not possible to display the proper GLPI error page. As this issue is only supposed to happen during the installation, a clear message on a blank page is probably sufficient for the GLPI administrator.
> Add a clear error message when Symfony container cannot be built

- phpunit/functional/Glpi/Form/Condition/EngineTest.php
- phpunit/functional/Glpi/Form/Destination/CommonITILField/AssociatedItemsFieldTest.php
- phpunit/src/Glpi/Form/QuestionType/AbstractQuestionTypeActorsTest.php
- src/Glpi/Form/Condition/Engine.php
- src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
- templates/pages/admin/form/condition_handler_templates/dropdown_multiple.html.twig
- tests/src/FormBuilder.php
This pull request includes several changes to improve error handling and data validation in the form processing logic. The most important changes involve adding checks to prevent undefined index errors, validating foreign keys and IDs, and handling default values in template rendering.
Error handling and data validation improvements:
* [`src/Glpi/Form/Condition/Engine.php`](diffhunk://#diff-c52196072adccc6e6a28e0f16e9b76851b6da4117831ec0c4cfd5ccef10388e1R186-R192): Added a check to ensure `extra_data` is not null before attempting to decode and process it.
* [`src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php`](diffhunk://#diff-7094c0f22e8cda09c90d971ae1cdc421e131b04b91586afbbd0700eb2cf17337R229-R234): Added a check to skip …
> fix(forms): Fixed a few php errors triggered when using forms

- phpunit/functional/SearchTest.php
- src/Glpi/Search/Provider/SQLProvider.php
- It fixes !37045
When you try to perform an is empty search on the name of an item, it fails and returns the complete list.
> Fix is empty search option for name

- src/Ticket.php
- It fixes !37241
add missing ExternalId search option
> Fix(Ticket): add missing ExternalId search option

- src/Rule.php
To follow GLPI 11 tooltip style.
After this PR:
> Add tooltip style for rule action addition

- css/includes/components/form/_form-destination.scss
- js/common.js
- js/modules/Forms/DestinationConditionController.js
- templates/pages/admin/form/form_destination.html.twig
-> Can't really be tested as this is chrome specific and our e2e tests run on electron.
Fix #19360.
> Prevent form destination accordion from closing when typing

- src/Profile.php
> fix setup tab icon in simplified profile form

- templates/components/itilobject/footer.html.twig
> Fix itil form button order

- css/includes/components/form/_form-editor-horizontal-layout.scss
- src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
Apply some UI fixes to improve horizontal layout
Before :
Now :
> fix(forms): Improved UI for horizontal layout elements

- src/NotificationTarget.php
> fix missing group and profile options for notification recipients

- js/modules/Forms/ServiceCatalogController.js
> fix(forms): Service Catalog "Sort by" Icon displayed outside of dropdown

- phpunit/bootstrap.php
- src/Glpi/Application/SystemConfigurator.php
- src/Toolbox.php
- stubs/glpi_constants.php
- tests/bootstrap.php
E2E env should be configured the same as PHPUnit env.
> Use `GLPI_STRICT_DEPRECATED=true` in E2E tests

- css/includes/components/itilobject/_dates_timelines.scss
> fix: Adjust icon placement in timeline for ticket statistics

- src/Glpi/Form/Destination/CommonITILField/TemplateField.php
- templates/pages/admin/form/itil_config_fields/entity.html.twig
- templates/pages/admin/form/itil_config_fields/itilcategory.html.twig
- templates/pages/admin/form/itil_config_fields/itilfollowuptemplate.html.twig
- templates/pages/admin/form/itil_config_fields/itiltasktemplate.html.twig
- templates/pages/admin/form/itil_config_fields/location.html.twig
- templates/pages/admin/form/itil_config_fields/request_source.html.twig
- templates/pages/admin/form/itil_config_fields/request_type.html.twig
- templates/pages/admin/form/itil_config_fields/slm.html.twig
- templates/pages/admin/form/itil_config_fields/template.html.twig
- templates/pages/admin/form/itil_config_fields/urgency.html.twig
- templates/pages/admin/form/itil_config_fields/validation.html.twig
Since #18574, the system for displaying destination fields has been modified and no longer requires you to manage whether or not to display a field as soon as the page is generated.
This task is now performed in JS when the page is loaded.
This PR removes dead code inherited from the old system.
> refactor(forms): Remove old back-end conditional class rendering for display conditions

- src/PrinterLog.php
> Ensure only integers columns are used in array_sum

- js/modules/IllustrationPicker/Controller.js
- src/Glpi/Form/Category.php
- src/Glpi/Search/Provider/SQLProvider.php
- src/autoload/CFG_GLPI.php
- templates/dropdown_form.html.twig
- tests/cypress/e2e/form/form_category.cy.js
It fixes #19461 
Fixed several bugs related to form categories:
- SQL error when displaying forms in a category
- TinyMCE was not provided on pages and prevented the initialization of rich text zones
- The contents of illustration selector tabs were no longer displayed if the aprent tab was changed despite their active status.
> fix(forms): Many fixes related to form categories

- src/Glpi/Controller/AbstractController.php
- src/Glpi/Controller/IndexController.php
- src/User.php
- templates/components/form/fields_macros.html.twig
- templates/components/itilobject/timeline/simple_form.html.twig
- templates/pages/setup/notification/ajax_setting.html.twig
> Various Twig fixes

- phpunit/functional/RuleRightTest.php
- src/Rule.php
- src/RuleAction.php
- src/RuleRight.php
- It fixes !37377
It was not possible to assign the value ‘Full structure’ to the default entity from the user rules.
> fix(user rule): set Full structure as default entity

- src/Item_SoftwareLicense.php
- It fixes !37394
The user's location was not displayed.
_I've also removed the entity value, as it's not relevant (it was displayed in the group column)._
Before:
After:
> fix(licence): user's location display

- css/standalone/marketplace.scss
> Fix sort dropdown heights in marketplace

- front/setup.templates.php
- phpunit/functional/HtmlTest.php
- src/Html.php
- tests/fixtures/plugins/tester/setup.php
> fix sector for template pages

- composer.lock
- It fixes !37417
`composer update thenetworg/oauth2-azure firebase/php-jwt` to prevent this error message:
```
glpiphplog.CRITICAL:   *** Uncaught Exception Error: Firebase\JWT\JWT::decode(): Argument #3 ($headers) cannot be passed by reference in .../vendor/thenetworg/oauth2-azure/src/Token/AccessToken.php at line 30
Backtrace :
...networg/oauth2-azure/src/Provider/Azure.php:471 TheNetworg\OAuth2\Client\Token\AccessToken->__construct()
...h2-client/src/Provider/AbstractProvider.php:653 TheNetworg\OAuth2\Client\Provider\Azure->createAccessToken()
...networg/oauth2-azure/src/Provider/Azure.php:120 League\OAuth2\Client\Provider\AbstractProvider->getAccessToken()
vendor/phpmailer/phpmailer/src/OAuth.php:115 …
```
> Fix(mailgate): error message with M365

- src/Glpi/Application/View/TemplateRenderer.php
- src/Glpi/Console/Application.php
1. Do not override `use_log_in_files` config when executing the console. This is not necessary and prevent the configuration entry to be applied.
2.  Always use the Twig debug mode in dev env. This may provide us a better execution context when issues happens.
> Adapt some debug mode usages

- phpunit/functional/ITILTemplateTest.php
- src/CommonITILObject.php
- templates/components/itilobject/footer.html.twig
- It fixes !37318
If a ticket has mandatory fields that have not been filled in (for example if it has been created via a collector), it is possible to resolve the ticket by adding a solution.
This PR adds a check on the mandatory fields, and if they are incomplete, an alert icon is displayed and the add solution button is hidden.
> Feat(ITIL object): check mandatory fields for solution

- src/DeviceSimcard.php
Replaced the sim-card icon with tabler icon, this fixes the problem of text shift in the menu.
BEFORE
AFTER
> fix: simcard tabler icon

- css/includes/components/_buttons-group.scss
- templates/components/itilobject/footer.html.twig
https://github.com/glpi-project/glpi/pull/19443#issuecomment-2821226916
> Move ITIL action button to middle and fix reversed btn-group borders

- phpunit/functional/Glpi/RichText/RichTextTest.php
- src/Glpi/RichText/RichText.php
> Allow `class` attribute to be used in rich text

- phpunit/GLPITestCase.php
- tests/GLPITestCase.php
1. Permit to call this method without having to specify any args.
2. Remove it from the atoum context.
> Enhance `callPrivateConstructor()` test helper method

- src/Contract_Supplier.php
Missing button name prevented the linking of Contracts <-> Suppliers.
> Fix contract_supplier link forms

- .phpstan-baseline.php
- phpunit/functional/Glpi/System/Diagnostic/SourceCodeIntegrityCheckerTest.php
- src/Glpi/System/Diagnostic/SourceCodeIntegrityChecker.php
> Handle missing files/directories while generating the code manifest

- front/cron.php
While working on #19510, I figured out that the cron script required some fixes.
- move "root" execution warning before Kernel boot
- exit with an error code (1) when the crontasks cannot be executed
- remove the `chdir()` call (it should not be necessary)
- do not execute any CLI related logic in the web context
> Cron script fixes

- templates/pages/admin/user/user.html.twig
> Do not check external auth on user creation

- src/User.php
- templates/pages/admin/user/user.html.twig
- tests/cypress/e2e/Admin/user.cy.js
> Prevent enter key in password modal from submitting form

- js/modules/Forms/ConditionEditorController.js
- src/Glpi/Form/Form.php
- templates/pages/admin/form/form_destination_actions.html.twig
Fix #19548 and related issues on others pages.
These failures are not detected by our e2e test suite because GLPI is served directly in `localhost:80`.
We could change the CI docker file to have GLPI's in `locahost/glpi` instead (I'll try to do it later in another PR).
> Fix relative paths

- src/Glpi/Log/AccessLogHandler.php
- src/Glpi/Log/ErrorLogHandler.php
> Filter access log to log only `AccessDeniedHttpException`

- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Form/Condition/ConditionHandler/SingleChoiceFromValuesConditionHandler.php
- src/Glpi/Form/Condition/FormData.php
- src/Glpi/Form/Migration/ConditionHandlerDataConverterInterface.php
- src/Glpi/Form/Migration/FormMigration.php
- templates/pages/admin/form/destination_visibility_conditions_configuration.html.twig
- tests/glpi-formcreator-migration-data.sql
- It fixes #19489
Support migration of conditions on questions, tickets and destinations.
> feat(forms): Migrate form conditions

- front/cron.php
Inclusion of `/front/_check_webserver_config.php` as been added by a script in all `/front` files, but the `/front/cron.php` script can also be executed in a CLI context.
> Fix cron CLI execution

- phpunit/bootstrap.php
- tests/bootstrap.php
This may prevent unexpected failures when tests are executed on a machine having outdated dependencies/locales
> Ensure tests are executed with up-to-date dependencies

- phpunit/abstracts/AbstractPlanningEvent.php
- src/Glpi/Features/PlanningEvent.php
> Some entries expect to be an array, not an empty string

- templates/pages/setup/mailcollector/server_config_fields.html.twig
Fix #19542.
Force to use the full width as this columns is very long + add flex-wrap in case the viewport is too small.
Before:
After:
> Fix collector options wrap

- src/Glpi/Application/SystemConfigurator.php
- src/Glpi/Form/Condition/ConditionData.php
- templates/components/checkbox_matrix.html.twig
- templates/components/illustration/icon.svg.twig
- templates/components/itilobject/actors/field.html.twig
- templates/components/itilobject/actors/main.html.twig
- templates/layout/parts/head.html.twig
- templates/pages/admin/customobjects/profiles.html.twig
- templates/pages/admin/form/condition_handler_templates/input.html.twig
- templates/pages/admin/form/conditional_visibility_editor.html.twig
- templates/pages/admin/helpdesk_home_config_tiles.html.twig
- templates/pages/form_renderer.html.twig
Can be reviewed per commit.
Setting `glpi_currenttime` is not mandatory, this prevents many entries in log during e2e tests.
> Fix Twig templates

- src/Profile.php
> Fix 2fa profile setting in simplified interface profiles

- css/includes/components/form/_form-renderer.scss
- install/migrations/update_10.0.x_to_11.0.0/group_user.php
- install/mysql/glpi-empty.sql
- js/modules/Forms/RendererController.js
- phpunit/functional/Glpi/Form/AnswersSetTest.php
- phpunit/functional/Group_UserTest.php
- src/Glpi/Controller/Form/DelegationController.php
- src/Glpi/Controller/Form/SubmitAnswerController.php
- src/Glpi/Form/AnswersHandler/AnswersHandler.php
- src/Glpi/Form/AnswersSet.php
- src/Glpi/Form/DelegationData.php
- src/Glpi/Form/Destination/CommonITILField/ITILActorField.php
- src/Glpi/Form/Destination/CommonITILField/ITILActorFieldStrategy.php
- src/Glpi/Form/EndUserInputNameProvider.php
- src/Group.php
- src/Group_User.php
- src/Ticket.php
- src/User.php
- templates/components/helpdesk_forms/delegation_alert.html.twig
- templates/pages/admin/group_user.html.twig
- templates/pages/form_renderer.html.twig
- tests/cypress/e2e/form/form_delegation.cy.js
- tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
Add a delegation system for forms
> feat(forms): Form Delegation

- .vue.webpack.config.js
Handle cases where cache-busting may be required for Vue chunks. The main entrypoint is already versioned.
Fixes #19652
> Add hash to vue chunk name

- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yaml
- .vue.webpack.config.js
- docker-compose.yaml
- js/src/vue/app.js
- package-lock.json
- package.json
Enable hot-reloading of Vue components for quicker and more seamless development.
There are now 3 different "build" commands for Vue:
- `build:vue`: Compile Vue files once. You must refresh the browser to see changes.
- `watch:vue`: Watch for changes to the Vue files and recompile changes. You must refresh the browser to see changes.
- `serve:vue`: Starts webpack dev server, watching for changes and recompiles, and notifies a client-side script (added by webpack) to reload the changed chunks. Most changes can be seen instantly in the browser.
> Add HMR support for Vue

- phpunit/functional/DropdownTest.php
- src/Dropdown.php
- It fixes !37629
Fix operator during comparison
> fix(dropdown): fix the search by ID

- phpunit/functional/Glpi/Api/HL/Controller/AssetControllerTest.php
- phpunit/functional/Glpi/Migration/GenericobjectPluginMigrationTest.php
- phpunit/functional/HtmlTest.php
- src/Glpi/Asset/Asset.php
- src/Glpi/Search/Provider/SQLProvider.php
- tests/src/autoload/functions.php
Attempt to fix search engine SQL errors seen in #16452 which are unrelated to the new API but are instead only now being seen after adding a custom asset definition to the test data.
> Fix search SQL issues with custom assets

- composer-dependency-analyser.php
- composer.json
- composer.lock
- src/Glpi/Application/Environment.php
- src/Glpi/Application/View/TemplateRenderer.php
- templates/components/helpdesk_forms/delegation_alert.html.twig
- templates/components/itilobject/timeline/form_validation.html.twig
For TEST and DEVELOPMENT environments
> Enable Twig strict variables

- src/ITILTemplateField.php
> Fix associated items predefined fields rendering

- .github/workflows/ci.yml
Sometimes, the E2E test suite timeout is reached, due to many tests retries. Since it can happen multiple times a day now, I propose to increase the timeout.
> Increase E2E test suite timeout

- css/includes/components/form/_form-editor.scss
- templates/pages/admin/form/conditional_visibility_dropdown.html.twig
Small UI changes to handle cases where the labels are very long.
Fix #19704.
> Improve handling of long text in conditions

- css/includes/components/form/_form-renderer.scss
- js/modules/Forms/RendererController.js
- phpunit/functional/Glpi/Form/AnswersHandler/AnswersHandlerTest.php
- src/Glpi/Controller/Form/ValidateAnswerController.php
- src/Glpi/Form/AnswersHandler/AnswersHandler.php
- src/Glpi/Form/ValidationResult.php
- tests/cypress/e2e/form/form_rendering.cy.js
- tests/cypress/e2e/form/question_types/item.cy.js
Server-side validation of mandatory questions and display of messages indicating uncompleted mandatory questions.
This system is a first step before adding conditions on question validity (min, max, regex, ...).
> feat(forms): Server side validation for mandatory questions

- phpunit/functional/ITILTemplateTest.php
- src/ITILCategory.php
- src/ITILTemplate.php
- src/ITILTemplateHiddenField.php
- src/ITILTemplateMandatoryField.php
- src/ITILTemplatePredefinedField.php
- src/ITILTemplateReadonlyField.php
Open to alternative suggestions, some are not easy to pick.
Before:
After:
> Add missing icons for template view

- .phpstan-baseline.php
- src/Profile.php
- templates/pages/admin/profile/admin.html.twig
- templates/pages/admin/profile/base_tab.html.twig
- templates/pages/admin/profile/form.html.twig
- templates/pages/admin/profile/legend.html.twig
Part 1 of X for migrating Profile UI to Twig (split from #19147)
> Profile Twig UI Part 1

- src/Profile.php
- templates/pages/admin/profile/lifecycle.html.twig
- templates/pages/admin/profile/lifecycle_simple.html.twig
- templates/pages/admin/profile/management.html.twig
- templates/pages/admin/profile/tools.html.twig
- templates/pages/admin/profile/tools_simple.html.twig
Part 3 of X for migrating Profile UI to Twig (split from [#19147](https://github.com/glpi-project/glpi/issues/19147))
> Profile Twig UI Part 3 (Lifecycle, Management and Tools)

- package-lock.json
- package.json
- src/Auth.php
- src/Glpi/Security/TOTPManager.php
- templates/pages/2fa/2fa_request.html.twig
- templates/pages/2fa/macros.html.twig
- tests/cypress.config.js
- tests/cypress/e2e/session.cy.js
It fixes #19719
Support for `redirect` parameter after connection with 2FA
> fix: handle redirect param after 2FA login

- phpunit/functional/TicketTest.php
- templates/components/form/basic_inputs_macros.html.twig
- templates/components/form/fields_macros.html.twig
- templates/components/itilobject/timeline/simple_form.html.twig
This form was failing to load due to some missing twig variables:
> Fix ticket title/description edition

- src/Change_Ticket.php
- src/Problem_Ticket.php
- templates/components/itilobject/timeline/form_solution.html.twig
- tests/cypress/e2e/ITILObject/massive_actions.cy.js
Fix #19564.
Not sure why but the original code is looking for a `tickets_id` field on a `Ticket` object.
My theory is that at some point in the past `$item` was a `Change_Ticket/Problem_Ticket` item and it was changed by some unrelated PR to a `Ticket`, breaking this code.
Added a test to avoid it breaking again in the future.
> Fix solve ticket massive action

- phpunit/functional/MassiveActionTest.php
- src/Lock.php
> fix permission check for unlock fields action

- ajax/dropdownTrackingDeviceType.php
- composer.lock
- src/Item_SoftwareLicense.php
- src/KnowbaseItem.php
- src/KnowbaseItem_Comment.php
- src/Migration.php
- src/NotificationMailingSetting.php
- src/Reservation.php
- src/RuleCollection.php
- src/Search.php
Fix new gettext version warnings (on 10.0 branch)
> Fix gettext extraction

- js/common_ajax_controller.js
- js/modules/Dashboard/Dashboard.js
- js/planning.js
- phpunit/functional/Glpi/System/Requirement/ExtensionClassTest.php
- phpunit/functional/Glpi/System/Requirement/ExtensionFunctionTest.php
- phpunit/functional/Glpi/System/Requirement/ExtensionTest.php
- src/CommonITILObject_CommonITILObject.php
- src/CommonItilObject_Item.php
- src/Entity.php
- src/Glpi/Marketplace/View.php
- src/Glpi/Migration/GenericobjectPluginMigration.php
- src/Glpi/System/Requirement/Extension.php
- src/Impact.php
- src/PendingReason.php
- templates/components/form/networkname.html.twig
- templates/components/plugin_update_modal.html.twig
- templates/components/printer_graph_buttons.html.twig
- templates/pages/admin/form/form_editor.html.twig
- templates/pages/assets/networkport/networkname_short.html.twig
> Few fix on translations

- css/includes/components/form/_form-editor-horizontal-layout.scss
- css/includes/components/form/_form-editor.scss
- templates/pages/admin/form/form_comment.html.twig
- templates/pages/admin/form/form_horizontal_block.html.twig
- templates/pages/admin/form/form_question.html.twig
- templates/pages/admin/form/form_toolbar.html.twig
Move the toolbar to the right of the form elements
> ui(forms): Move the toolbar to the right of the form elements

- Makefile
> Makefile: specify memory limit for phpstan

- templates/pages/setup/notification/mailing_setting.html.twig
This is a complement to this PR #19825 (I couldn't test the SMTP OAUTH, so I couldn't see that the "Force OAuth authentication update" box was also affected by the display error)
> fix(mailsetting): another field visibility

- phpunit/functional/TransferTest.php
- src/Document.php
Trying to reproduce #19790 (but I can't).
> Test on documents transfer

- phpunit/functional/DbUtilsTest.php
- phpunit/functional/SavedSearchTest.php
- src/DbUtils.php
Fix a SQL error when querying `apirest.php/Entity` on legacy api
> fix getItems with entity on legacy rest api

- .phpstan-baseline.php
- phpstan.neon.dist
- src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
- src/Notification_NotificationTemplate.php
- src/RuleDefineItemtype.php
Same as #19895 for the `main` branch.
> Mark PHPDoc as uncertain for PHPStan (main branch)

- css/includes/components/form/_form-editor.scss
- templates/pages/admin/form/form_editor.html.twig
- templates/pages/admin/form/form_section.html.twig
- templates/pages/admin/form/form_toolbar.html.twig
Following PR #19793, the section toolbar had not been moved and was still below the element.
This PR moves the toolbar to the right of the section elements.
> fix(forms): Fixed toolbar layout for sections

- src/autoload/CFG_GLPI.php
> Fix wrong class name

- css/includes/components/form/_form-editor-horizontal-layout.scss
- css/includes/components/form/_form-editor.scss
- templates/pages/admin/form/form_horizontal_block.html.twig
> fix(forms): Fixed horizontal layout max width 

- front/logviewer.php
> Fix download log file action

- src/Glpi/Api/API.php
Internal cloud team test GLPI 11, and Anthony found that the behavior of duplicate entity post has changed
Now an exception is triggered and a 500 error, where it was a 400 before.
Not sure the 400 is good, but we promise to keep the legacy API stable.
> intercept SQL error (replicate legacy api behavior)

- js/modules/Forms/EditorController.js
- js/modules/Forms/RendererController.js
- templates/pages/admin/form/form_section.html.twig
- templates/pages/form_renderer.html.twig
- tests/cypress/e2e/form/editor/conditions.cy.js
- tests/cypress/e2e/form/editor/editor.cy.js
Move the section name to the card label
> ui(forms): Move the section name to the card label

- src/Auth.php
- src/User.php
> Prevent using null

- phpunit/GLPITestCase.php
- phpunit/RuleBuilder.php
- src/Calendar.php
- src/CommonDBTM.php
- src/CommonDropdown.php
- src/CommonITILObject.php
- src/LevelAgreement.php
- tests/src/autoload/functions.php
various docblocks & small changes
> docbloc tinyfix

- .phpstan-baseline.php
- phpunit/functional/RuleDictionnaryPrinterModelCollectionTest.php
- phpunit/functional/RuleDictionnaryPrinterModelTest.php
- src/CommonDBTM.php
- src/CommonDropdown.php
- src/MassiveAction.php
- src/RuleDictionnaryDropdownCollection.php
- src/RuleDictionnarySoftwareCollection.php
- src/Software.php
closes #18987
To be reviewed per commit; first one only fix CS, phpdoc and typos; while seocnd one fix the issues and add tests.
> Fix printer model dictionary replay 

- phpunit/imap/MailCollectorTest.php
- src/MailCollector.php
- tests/emails-tests/44-hebrew-encoding-issue.eml
> Fix hebrew characters encoding from mail collector

- src/Glpi/Marketplace/View.php
- src/Plugin.php
- templates/pages/setup/marketplace/card.html.twig
> Fix multiple escaping issues in marketplace

- README.md
We do not have (yet) a clear and public lifecycle policy. I propose to remove the one present in the readme as it does not even match the actual policy we applied when latest major versions were released (we provided support for the previous version for a few months).
> Remove irrelevant lifecycle

- js/planning.js
- src/PlanningExternalEvent.php
- templates/pages/assistance/planning/external_event.html.twig
> Fix non defined variable in external event form

- src/KnowbaseItem_Revision.php
Backport user cache from v11
closes #19997
> Limit selected fields

- CHANGELOG.md
- phpunit/functional/DropdownTest.php
- src/Dropdown.php
> Hide inactive suppliers in actor list

- src/Supplier.php
Issue is in a `show` method, no tests possible.
> Wrong SQL column, fix #20030

- src/NetworkPortInstantiation.php
- templates/pages/management/domainrecord.html.twig
> Fix missing Twig vars in domain record and netport instantiation

- package-lock.json
- package.json
- phpunit/functional/Glpi/UI/IllustrationManagerTest.php
> update illustration to 0.6.0

- CHANGELOG.md
- phpunit/web/APIRestTest.php
- src/Api/APIRest.php
> Do not return all items in API when requesting id 0

- src/User.php
> Fix user item lists for itemtypes without otherserial

- src/Config.php
- src/DisplayPreference.php
- src/Preference.php
- src/ValidatorSubstitute.php
Add missing tab icons for:
- Authorized Substitutes
- Personal View
- Personalization
- Two-factor authentication (2FA)
> Add some missing tab icons on user settings page

- phpunit/functional/PDU_RackTest.php
- src/PDU_Rack.php
> Ensure a valid PDU and rack id are provided

- front/form/access_control.form.php
- front/smtp_oauth2_callback.php
- src/Glpi/Api/HL/GraphQL.php
- src/Glpi/Api/HL/GraphQLGenerator.php
- src/Glpi/Form/AccessControl/FormAccessControl.php
- src/Glpi/Form/AnswersHandler/AnswersHandler.php
- src/Glpi/Security/TOTPManager.php
- src/MailCollector.php
- src/Planning.php
- src/Plugin.php
This will permit to have the original exception stack trace, instead of having the stack trace of the `trigger_error()` call.
> Better logs for caught exceptions

- tools/generateformforeachillustrationscommand.class.php
> Fixed command tools:generate_forms_for_each_illustrations

- src/Glpi/Console/Database/UpdateCommand.php
Fix a small typo I saw in #19836.
> Fix typo in update error

- phpstan.neon
phpstan.neon should not be in versionning. It's aimed to be a personal override of phpstan.neon.dist.
It causes trouble because I had some changes in it.
> Remove phpstan neon

- src/Glpi/Agent/Communication/AbstractRequest.php
- src/Glpi/Inventory/Conf.php
> Prevent auth on inventory file  upload

- src/User.php
With the "amp;" the link doesn't work, so I removed it.
> fix: incorrect user external source link

- install/empty_data.php
- install/migrations/update_10.0.x_to_11.0.0/form.php
- install/mysql/glpi-empty.sql
- phpunit/functional/EntityTest.php
- src/Entity.php
- templates/pages/admin/helpdesk_home_config_for_entity.html.twig
- templates/pages/helpdesk/index.html.twig
- tests/cypress/e2e/self-service/home_config.cy.js
Allow the "How can we help you?" title found on the helpdesk home page to be customized.
Result:
> Custom helpdesk title

- templates/pages/management/item_line.html.twig
> fix hidden field name in item_line form

- phpunit/functional/Glpi/Form/Condition/EditorManagerTest.php
- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Form/Condition/ConditionHandler/ActorConditionHandler.php
- src/Glpi/Form/Condition/ConditionHandler/ConditionHandlerInterface.php
- src/Glpi/Form/Condition/ConditionHandler/DateAndTimeConditionHandler.php
- src/Glpi/Form/Condition/ConditionHandler/DateConditionHandler.php
- src/Glpi/Form/Condition/ConditionHandler/ItemAsTextConditionHandler.php
- src/Glpi/Form/Condition/ConditionHandler/ItemConditionHandler.php
- src/Glpi/Form/Condition/ConditionHandler/MultipleChoiceFromValuesConditionHandler.php
- src/Glpi/Form/Condition/ConditionHandler/NumberConditionHandler.php
- src/Glpi/Form/Condition/ConditionHandler/RequestTypeConditionHandler.php
- src/Glpi/Form/Condition/ConditionHandler/SingleChoiceFromValuesConditionHandler.php
- src/Glpi/Form/Condition/ConditionHandler/StringConditionHandler.php
- src/Glpi/Form/Condition/ConditionHandler/TimeConditionHandler.php
- src/Glpi/Form/Condition/ConditionHandler/UrgencyConditionHandler.php
- src/Glpi/Form/Condition/ConditionHandler/UserDevicesConditionHandler.php
- src/Glpi/Form/Condition/ConditionHandler/VisibilityConditionHandler.php
- src/Glpi/Form/Condition/ValueOperator.php
- src/Glpi/Form/Migration/FormMigration.php
- src/Glpi/Form/QuestionType/QuestionTypeDropdown.php
- src/Glpi/Form/QuestionType/QuestionTypeItemDropdown.php
- templates/pages/admin/form/conditional_validation_editor.html.twig
- templates/pages/admin/form/conditional_visibility_editor.html.twig
- It fixes #20094
Bug fixes for questions of type `QuestionTypeItemDropdown` and `QuestionTypeDropdown`.
Improved support for importing validation conditions.
> fix(forms-migration): Fixed issue with ItemDropdown questions and enchance validation conditions

- phpunit/functional/Item_SoftwareLicenseTest.php
- src/CommonGLPI.php
- src/Item_SoftwareLicense.php
- src/SoftwareLicense.php
- templates/pages/management/license_progressbar.html.twig
- templates/pages/management/softwarelicense.html.twig
- It fixes !36843
- Adds a license counter that tells the user how many licenses are left and how many have been allocated.
**Afftected Items Search Option:**
_Unlimited_
_Valid_
_Full_
_Overflow_
**Tab:**
_Unlimited_
_Valid_
_Full_
_Overflow_
**Form**
_Unlimited_
_Valid_
_Full_
_Overflow_
> feat(license/ui): Display available license count

- phpunit/functional/ValidatorSubstituteTest.php
- src/ValidatorSubstitute.php
- tests/cypress/e2e/Admin/user.cy.js
> fix removal of authorized substitutes

- templates/pages/form_renderer.html.twig
These actions contains links that unauthenticated users can't access so there is no point displaying them.
Before:
After:
> Forms: do not show post submit actions for unauthenticated users

- src/Group.php
- src/Group_User.php
- templates/components/datatable.html.twig
> fix datatable filter handling

- phpunit/functional/Glpi/Dashboard/GroupFilterTest.php
- src/Glpi/Dashboard/Filters/AbstractGroupFilter.php
- src/Glpi/Dashboard/Filters/GroupRequesterFilter.php
- src/Glpi/Dashboard/Filters/GroupTechFilter.php
Fixes #19983
Deduplicated code by moving logic to an `AbstractGroupFilter` class.
Added unit test for the group filters.
> Fix dashboard group filters for assets

- .phpstan-baseline.php
- front/form/access_control.form.php
> Fix minor phpstan issues for forms

- css/includes/components/form/_form-destination.scss
Quick fix for #20212.
I agree with the other point from the issue (not storing css classes in the DB), I may improve it in another PR but it isn't high priority ATM.
> Fix form tags dark theme rendering

- src/Glpi/Form/Migration/FormMigration.php
Fix a small mistake in #20255.
> Fix prerequisites for formcreator migration

- src/Glpi/Api/HL/Search.php
Fix HTTP status codes used for some API error responses.
Split from #19678
> [HLAPI] Improve HLAPI error responses

- src/Lockedfield.php
Should fix #19984, but this is an area I don't often work on or use.
> Fix group field locks for assets

- ajax/rack.php
- css/includes/components/_mini-tabs.scss
- src/Rack.php
- templates/pages/management/dcroom_racks.html.twig
- tests/cypress/e2e/Tools/dcroom.cy.js
Fixes #20124
Fixes other potential issues from loading a full tabbed form for racks in a modal by just showing the main form in the modal.
Replaces qTip tooltips with Bootstrap ones.
Migrates raw echos to Twig as well to improve readability and standardize the table/list view with other parts of GLPI.
> Fix multiple issues with DC room rack view

- src/Api/API.php
> Fix legacy API searchText with 0 value

- templates/components/datatable.html.twig
> smarter datatable pager support

- src/Update.php
Contains #19985.
When an update contains only bugfixes, we are not suppose to introduce BC-breaks (see https://glpi-developer-documentation.readthedocs.io/en/develop/sourcecode.html#backward-compatibility).
I therefore propose to resume the plugins execution when an update is a bugfixes update.
> Resume plugins execution after a bugfix update

- .phpstan-baseline.php
- install/install.php
- install/migrations/update_10.0.0_to_10.0.1.php
- install/migrations/update_10.0.1_to_10.0.2.php
- install/migrations/update_10.0.2_to_10.0.3.php
- install/migrations/update_10.0.3_to_10.0.4.php
- install/migrations/update_10.0.4_to_10.0.5.php
- install/migrations/update_10.0.x_to_11.0.0.php
- install/migrations/update_9.1.x_to_9.2.0.php
- install/migrations/update_9.5.1_to_9.5.2.php
- install/migrations/update_9.5.x_to_10.0.0.php
- install/migrations/update_9.5.x_to_10.0.0/itemtype_pictures.php
As changes on these scripts are likely to be refused, I made a dedicated PR.
> Fix PHPStan issues on install scripts

- .phpstan-baseline.php
- src/CommonDBRelation.php
- src/CommonDBTM.php
- src/CommonITILTask.php
- src/Domain.php
- src/DropdownTranslation.php
- src/Glpi/Api/API.php
- src/Glpi/Api/APIRest.php
- src/Glpi/Api/HL/Doc/Schema.php
- src/Glpi/Api/HL/Router.php
- src/Glpi/Asset/Asset_PeripheralAsset.php
- src/Glpi/Console/Migration/RacksPluginToCoreCommand.php
- src/Glpi/Features/PlanningEvent.php
- src/Glpi/Search/CriteriaFilter.php
- src/Glpi/Search/Provider/SQLProvider.php
- src/Glpi/System/Log/LogViewer.php
- src/Item_Environment.php
- src/MailCollector.php
- src/Reservation.php
- src/Search.php
- src/Session.php
- src/Telemetry.php
- src/ValidatorSubstitute.php
> Fix phpstan return.* errors

- src/NetworkPortInstantiation.php
> Fix issue setting networkport data on uninitialized array path

- Makefile
Mutualise 3 useful commands into the makefile.
> Add phpcsfixer + phpstan baseline commands to makefile

- .phpstan-baseline.php
- css/includes/components/form/_form-destination.scss
- install/migrations/update_10.0.x_to_11.0.0/form.php
- js/modules/Forms/FieldDestinationMultipleConfig.js
- phpunit/functional/Glpi/Form/Destination/CommonITILField/ValidationFieldTest.php
- phpunit/functional/Glpi/Form/Export/FormSerializerDestinationTest.php
- phpunit/functional/Glpi/Form/Migration/TargetsMigrationTest.php
- src/CommonITILObject.php
- src/Glpi/Form/Destination/AbstractConfigField.php
- src/Glpi/Form/Destination/CommonITILField/ValidationField.php
- src/Glpi/Form/Destination/CommonITILField/ValidationFieldConfig.php
- src/Glpi/Form/Destination/CommonITILField/ValidationFieldStrategy.php
- src/Glpi/Form/Destination/CommonITILField/ValidationFieldStrategyConfig.php
- templates/pages/admin/form/form_destination_commonitil_config.html.twig
- templates/pages/admin/form/itil_config_fields/validation.html.twig
- tests/cypress/e2e/form/destination_config_fields/validation.cy.js
Adds the ability to define multiple validations for a target.
Ability to use the same strategy multiple times.
Support for the validation step system.
> feat(forms-destination): Add support for reusable strategies

- CHANGELOG.md
- src/Html.php
- src/autoload/CFG_GLPI.php
> Load TinyMCE on every page

- src/Glpi/Asset/Asset.php
Honestly, I am not even sure it can be used, since it has the `nosearch: true` and `nodisplay: true` options, but it is present in almost all asset classes, so it seems legitimate to add it here too, see https://github.com/glpi-project/glpi/blob/e43cd69345751fecce8ebb05a7a6ba21e4b2fdfd/src/Computer.php#L635-L644
> Add `template_name` search option for custom assets

- phpunit/functional/Glpi/Helpdesk/DefaultDataManagerTest.php
- phpunit/functional/Glpi/Helpdesk/Tile/TilesManagerTest.php
- src/Glpi/Helpdesk/DefaultDataManager.php
- src/Glpi/Helpdesk/Tile/GlpiPageTile.php
Draft, waiting for a better icon for the "See your tickets" tile.
> Tweak default tiles

- CHANGELOG.md
- ajax/actorinformation.php
- ajax/comments.php
- ajax/dashboard.php
- ajax/dropdownAllItems.php
- ajax/dropdownItilActors.php
- js/modules/Dashboard/Dashboard.js
- js/modules/Forms/FieldDestinationAssociatedItem.js
- phpunit/functional/autoload/MiscFunctionsTest.php
- src/Ajax.php
- src/CommonGLPI.php
- src/Dropdown.php
- src/autoload/misc-functions.php
> Fix some HTML/JS escaping

- .phpstan-baseline.php
- front/stat.item.php
- front/stat.location.php
- front/stat.tracking.php
- src/Cartridge.php
- src/Glpi/Api/HL/Controller/ReportController.php
- src/Glpi/Dashboard/Provider.php
- src/Html.php
- src/Infocom.php
- src/Stat.php
Fix `Parameter of function Safe\mktime expects int|null, string given` errors.
> Fix bad usages of mktime reported by PHPstan

- ajax/dropdownMassiveActionField.php
- ajax/dropdownShowIPNetwork.php
- ajax/dropdownTrackingDeviceType.php
- ajax/getMapPoint.php
- ajax/mailcollector.php
- ajax/massiveaction.php
- ajax/priority.php
- ajax/resaperiod.php
- ajax/ruleaction.php
- ajax/rulecriteria.php
- ajax/selectUnaffectedOrNewItem_Device.php
- ajax/ticketiteminformation.php
- ajax/webhook.php
Follows #20386. I've reviewed all files from the `ajax` directory.
> Fix some HTML/JS escaping in AJAX endpoints

- .phpstan-baseline.php
- install/migrations/update_10.0.16_to_10.0.17/tree_dropdowns.php
- src/Cartridge.php
- src/CommonITILSatisfaction.php
- src/Glpi/Console/Database/InstallCommand.php
- src/Glpi/Console/Database/UpdateCommand.php
- src/Glpi/Console/Migration/AbstractPluginMigrationCommand.php
- src/Glpi/DependencyInjection/PluginContainer.php
- src/Glpi/Form/AnswersHandler/AnswersHandler.php
- src/Glpi/Form/Comment.php
- src/Glpi/Form/Question.php
- src/Glpi/Form/Section.php
- src/Glpi/Inventory/MainAsset/Itemtype.php
- src/Glpi/Search/Output/Ods.php
- src/HTMLTableCell.php
- src/HTMLTableEntity.php
- src/HTMLTableSuperHeader.php
- src/Html.php
- src/Item_Devices.php
- src/NetworkPort.php
- src/Stat.php
- src/Toolbox.php
Fix constructor related phpstan errors
> Fix constructor related phpstan errors

- tools/update_registered_ids.php
The previous link to SourceForge is invalid now. I am guessing the script isn't used very often or the URL broke recently. It still seems like it could be useful though and I may use it to populate data the next time I reset my dev DB.
> Update PCI IDs URL in tool script

- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Form/Migration/FormMigration.php
- It fixes #19894
Support for migrating the visibility conditions of the form submit button.
> fix(forms-migration): Handle submit button visibility conditions

- phpunit/functional/Glpi/Form/AccessControl/FormAccessControlTest.php
- src/DocumentType.php
- src/Glpi/Form/AccessControl/FormAccessControlManager.php
- src/Glpi/Form/BlockInterface.php
- src/Glpi/Form/Comment.php
- src/Glpi/Form/Form.php
- src/Glpi/Form/Question.php
- src/Glpi/Form/Section.php
- templates/pages/admin/form/form_editor.html.twig
- templates/pages/admin/form/form_horizontal_block.html.twig
- templates/pages/admin/form/form_section.html.twig
- tests/src/FormTesterTrait.php
Improve performances of the `Form::showForm()` method by adding various cache layers and avoiding loading the same data multiple times.
(Small) partial improvement for #20416.
> Improve Form::showForm() performances

- install/migrations/update_11.0.x_to_11.1.0.php
- install/mysql/glpi-11.0.0-empty.sql
- phpunit/functional/Glpi/System/Diagnostic/SourceCodeIntegrityCheckerTest.php
- src/autoload/constants.php
To be sure to differenciate people testing on the main branch with people testing on the 11.0/bugfixes branch.
> Bump `main` branch version to 11.1

- ajax/asset/assetdefinition.php
- ajax/dashboard.php
- ajax/getDropdownNumber.php
- ajax/getDropdownUsers.php
- ajax/getDropdownValue.php
- psalm.xml
- src/DBConnection.php
- src/Glpi/Api/APIRest.php
- src/Glpi/Error/ErrorDisplayHandler/CliDisplayHandler.php
- src/Problem.php
> Fix detected Psalm `TaintedHtml` issues

- front/link.send.php
- front/pluginimage.send.php
- psalm.xml
- src/UploadHandler.php
There is no real security issue here, but we should still prevent HTTP headers to be manipulated here.
> Fix detected Psalm `TaintedHeader` issues

- css/includes/_includes.scss
- css/includes/components/form/_item-translations.scss
- phpunit/functional/ConfigTest.php
- phpunit/functional/Glpi/Helpdesk/Translation/HelpdeskTranslationTest.php
- src/Config.php
- src/Entity.php
- src/Glpi/Controller/Form/Translation/AddNewFormTranslationController.php
- src/Glpi/Controller/Form/Translation/UpdateFormTranslationController.php
- src/Glpi/Controller/Helpdesk/Translation/AddNewHelpdeskTranslationController.php
- src/Glpi/Controller/Helpdesk/Translation/DeleteHelpdeskTranslationController.php
- src/Glpi/Controller/Helpdesk/Translation/UpdateHelpdeskTranslationController.php
- src/Glpi/Controller/Translation/AbstractTranslationController.php
- src/Glpi/Helpdesk/HelpdeskTranslation.php
- src/Glpi/Helpdesk/Tile/ExternalPageTile.php
- src/Glpi/Helpdesk/Tile/FormTile.php
- src/Glpi/Helpdesk/Tile/GlpiPageTile.php
- src/Glpi/Helpdesk/Tile/TileInterface.php
- src/Glpi/Helpdesk/Tile/TilesManager.php
- src/Glpi/ItemTranslation/ItemTranslation.php
- templates/components/datatable.html.twig
- templates/pages/admin/form/form_translation.html.twig
- templates/pages/admin/form/form_translations.html.twig
- templates/pages/admin/helpdesk_home_translation.html.twig
- templates/pages/admin/helpdesk_home_translations.html.twig
- templates/pages/helpdesk/index.html.twig
- tests/cypress/e2e/helpdesk/helpdesk_translation.cy.js
- tests/cypress/e2e/self-service/helpdesk_translation.cy.js
- It fixes #19797 
This PR adds the ability to translate Helpdesk elements (tiles and helpdesk custom title).
The system uses the same approach as for translating forms.
> feat(helpdesk): Implement helpdesk translation

- templates/pages/admin/transfer.html.twig
> fix comment field in transfer form

- src/ProjectCost.php
> Fix unexpected JS code output in project costs

- phpunit/abstracts/CommonITILRecurrentTest.php
- src/CommonITILRecurrent.php
Link recurrent items to their template.
Fix #20566.
> Link recurrent items to their template

- src/ReservationItem.php
- templates/pages/tools/find_available_reservation.html.twig
- tests/cypress/e2e/Tools/reservations.cy.js
> fix find available reservations form

- phpunit/functional/DropdownTest.php
- src/Dropdown.php
Reported in #20563 but not specific to reservations
> fix dropdownTimestamp minute padding

- src/RichText/RichText.php
- It fixes !38841
Fix this error message in `php-errors.log`
```
glpiphplog.NOTICE:   *** PHP Deprecated function (8192): preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/glpi/src/RichText/RichText.php at line 355
Backtrace :
src/RichText/RichText.php:355                      preg_replace()
src/RichText/RichText.php:273                      Glpi\RichText\RichText::fixImagesPath()
src/RichText/RichText.php:63                       Glpi\RichText\RichText::normalizeHtmlContent()
src/RichText/RichText.php:301                      Glpi\RichText\RichText::getSafeHtml()
...ion/View/Extension/DataHelpersExtension.php:230 Glpi\RichText\RichText::getEnhancedHtml() …
```
> Fix: PHP Deprecated function

- src/CommonItilObject_Item.php
- tests/cypress/e2e/ITILObject/ticket_form.cy.js
Bug from https://github.com/glpi-project/glpi/pull/20408 which incorrectly checks for CommonItilObject_Item instead of CommonITILObject.
> fix items tab for itilobjects again

- phpunit/bootstrap.php
- phpunit/functional/ChangeTaskTest.php
- phpunit/functional/CommonITILTaskTest.php
- phpunit/functional/CommonITILTaskTestCase.php
- phpunit/functional/ProblemTaskTest.php
- phpunit/functional/TicketTaskTest.php
- src/CommonITILTask.php
- templates/components/massive_action/add_task.html.twig
First, I've refactored the `CommonITILTaskTask` tests to make it easier to add new ones that cover the 3 possible child classes.
This is done in the first commit, which should be reviewed with white space changes disabled.
Now, for the actual issue, the "add a new task" massive action form was throwing a rendering error:
```
Twig\Error\RuntimeError: Key "content" does not exist as the sequence/mapping is empty in "components/itilobject/timeline/form_task_main_form.html.twig" at line 71.
```
The issue reside in the `showMassiveActionAddTaskForm()` method, which fail to init the `subitem` parameter correctly (thus making the `fields` property an empty array, leading to the error when trying to read the "content" key).
Initializing the object with `getEmpty()` fix this issue but reveal …
> Fix add task massive action form

- phpunit/functional/Glpi/Form/FormTest.php
- src/Glpi/Form/Form.php
Delete matching `Item_Ticket` relations when a form is deleted.
Fix #20617.
> Delete linked tickets items when a form is deleted

- templates/components/itilobject/timeline/form_document_item.html.twig
> fix missing recursive value in itil document form

- install/install.php
I reused the same string than the one used in the page title a few lines above.
> Fix untranslated string in install process

- src/Contact.php
- src/Glpi/Dashboard/Filters/AbstractFilter.php
- src/Glpi/Dashboard/Grid.php
- src/Glpi/Dashboard/Widget.php
- src/Glpi/Http/RedirectResponse.php
- src/MailCollector.php
- src/Toolbox.php
> Fix some escaping issues (5/x)

- src/Dropdown.php
- src/Html.php
- src/User.php
> UserDropdown can be required - fix #20425

- src/CommonItilObject_Item.php
- Add Item and Remove Item massive action forms had buttons which were missing an end tag, forcing the browser to guess where it should be
- Remove Item massive action was adding a duplicate itemtype select
> Fix add/remove item MA forms

- templates/pages/setup/general/preferences_setup.html.twig
Very big change in this PR, a push on transifex will be necessary so that we can translate.
> fix(locales): missing parenthesis

- templates/pages/form_renderer.html.twig
- tests/cypress/e2e/form/form_translation.cy.js
Fixed `form_translation` E2E Tests by processing `data-testid` instead of `aria-label`
> fix(tests): Fixed form_translation E2E Tests by processing data-testid instead of aria-label

- src/Glpi/Search/Provider/SQLProvider.php
> fix plugin join handling

- phpunit/functional/Glpi/Form/AccessControl/FormAccessControlTest.php
- phpunit/functional/Glpi/Form/FormTest.php
- src/Glpi/Form/AccessControl/FormAccessControl.php
- src/Glpi/Form/Destination/FormDestination.php
- src/Glpi/Form/FormTranslation.php
Update the names of form tab entries to support pluralization
> fix(forms): Update tab entry names to support pluralization

- templates/pages/admin/form/form_destination.html.twig
Small issue with the placement of the format function in the twig file, which meant that it was not detected when extracting locales for translation.
> fix(forms): Fixed locales issue with the label of the “Add” button on the form destination

- resources/api_doc.MD
Adds an example in the getting started documentation showing a query which requests information crossing schema boundaries.
> Add GraphQL example crossing schemas

- src/Inventory/Inventory.php
> Add missing saved searches list in inventory pages

- src/Glpi/Application/Environment.php
Following https://github.com/glpi-project/glpi/issues/20768
> Missing path in plugins directories conf

- src/LevelAgreement.php
> Fix SLM link in level agreements forms

- src/Domain_Item.php
- templates/pages/management/document_item.html.twig
Some occurences were missed in #20654.
> Fix `is_recursive` forms inputs values

- phpunit/abstracts/SortStrategyTestCase.php
- phpunit/functional/Glpi/Form/ServiceCatalog/HomeSearchManagerTest.php
- phpunit/functional/Glpi/Form/ServiceCatalog/ServiceCatalogManagerTest.php
- src/Glpi/Controller/Helpdesk/SearchController.php
- src/Glpi/Controller/ServiceCatalog/IndexController.php
- src/Glpi/Controller/ServiceCatalog/ItemsController.php
- src/Glpi/Form/ServiceCatalog/HomeSearchManager.php
- src/Glpi/Form/ServiceCatalog/ItemRequestContext.php
- src/Glpi/Form/ServiceCatalog/Provider/FormProvider.php
- src/Glpi/Form/ServiceCatalog/Provider/KnowbaseItemProvider.php
- src/Glpi/Form/ServiceCatalog/ServiceCatalogManager.php
- src/Glpi/Toolbox/SingletonTrait.php
- src/KnowbaseItem.php
- templates/pages/helpdesk/search.html.twig
- tests/fixtures/plugins/tester/setup.php
- tests/fixtures/plugins/tester/src/Form/ComputerForServiceCatalog.php
- tests/fixtures/plugins/tester/src/Form/ComputerProvider.php
As discussed in our meeting this week, we lack a few plugins hooks for some internal needs and want to integrate them even if we are already in RC.
These changes allow plugins to add items to:
- The service catalog
- The home page search bar results
It required a small refactoring which is isolating in a dedicated commit.
> Add missing helpdesk hooks

- css/includes/components/form/_form-renderer.scss
- src/Glpi/Form/QuestionType/AbstractQuestionType.php
- src/Glpi/Form/QuestionType/QuestionTypeInterface.php
- templates/pages/form_renderer.html.twig
Another internal need, we are adding some questions types from formcreator into a plugin and we need the ability to keep a question hidden (this is how it was done in formcreator for the "IP", "hostname" and "hidden" types).
> Allow questions to be hidden in the form renderer

- src/Auth.php
- src/Glpi/Controller/IndexController.php
- src/Glpi/Controller/Security/MFAController.php
- src/Glpi/Security/TOTPManager.php
- templates/pages/2fa/2fa_backup_codes.html.twig
- templates/pages/2fa/2fa_request.html.twig
- templates/pages/2fa/2fa_status.html.twig
- templates/pages/2fa/macros.html.twig
- tests/cypress/e2e/session.cy.js
Fixes #18259
Fixes #17592
Fixes #17917
I was troubleshooting the missing session variables again and manually added a call to the safe version of "session_write_close" noticed an exception which I hadn't seen before.
```
[2025-08-27 16:06:37] glpi.CRITICAL:   *** Uncaught PHP Exception Exception: "Serialization of 'LDAP\Connection' is not allowed" at session.php line 538
Backtrace :
...odingmachine/safe/generated/8.4/session.php:538 
...odingmachine/safe/generated/8.4/session.php:538 session_write_close()
./src/Auth.php:1088                                Safe\session_write_close()
./front/login.php:75                               Auth->login()
...Glpi/Controller/LegacyFileLoadController.php:63 require()
./vendor/symfony/http-kernel/HttpKernel.php:181 …
```
> Fix 2FA with LDAP users

- ajax/getUserPicture.php
- front/stat.location.php
- front/stat.tracking.php
- phpunit/functional/HtmlTest.php
- phpunit/functional/ToolboxTest.php
- src/Document.php
- src/DocumentType.php
- src/Document_Item.php
- src/DomainRecordType.php
- src/Domain_Item.php
- src/Dropdown.php
- src/Entity.php
- src/FieldUnicity.php
- src/GLPINetwork.php
- src/Glpi/Application/View/Extension/HtmlExtension.php
- src/Glpi/Application/View/TemplateRenderer.php
- src/HTMLTableCell.php
- src/HTMLTableEntity.php
- src/HTMLTableGroup.php
- src/HTMLTableHeader.php
- src/HTMLTableMain.php
- src/HTMLTableRow.php
- src/Html.php
- src/KnowbaseItem.php
- src/Project.php
- src/Stat.php
- templates/components/dropdown/limit.html.twig
- templates/components/form/basic_inputs_macros.html.twig
- templates/components/form/fields_macros.html.twig
- templates/components/printer_graph_buttons.html.twig
I reviewed classes from `DCRoom` to `HTML*`.
> Fix some escaping issues (10/x)

- front/change_problem.form.php
- front/document_item.form.php
- front/itil_project.form.php
- front/knowbaseitem.form.php
- front/knowbaseitem_item.form.php
- front/ticket_contract.form.php
- phpunit/functional/CommonDBRelationTest.php
- src/CommonDBRelation.php
- src/Glpi/Exception/ItemLinkException.php
- src/Ticket_Contract.php
Fix for #20747 among others, replaces #20822
> Check for required fields on dbrelations

- phpunit/functional/Glpi/Form/Condition/EditorManagerTest.php
- src/Glpi/Form/Section.php
- tests/cypress/e2e/form/editor/conditions.cy.js
We changed "Step" to "Section" a while ago but some occurrences were missed.
> Rename missed "step" occurences to sections

- src/ITILFollowup.php
- src/ITILSolution.php
- src/ITILTemplate.php
- src/ITILValidationTemplate.php
- src/Impact.php
- src/Infocom.php
- src/ItemVirtualMachine.php
- src/Item_Devices.php
- src/Item_Disk.php
- src/Item_OperatingSystem.php
- src/Item_Plug.php
- src/Item_Project.php
- src/Item_Rack.php
- src/Item_SoftwareLicense.php
- src/Item_SoftwareVersion.php
- src/KnowbaseItem.php
- src/KnowbaseItem_Revision.php
- src/LevelAgreement.php
- src/LevelAgreementLevel.php
- src/Link.php
- src/Lock.php
I reviewed classes from `I` to `L`.
> Fix some escaping issues (11/x)

- css/includes/_includes.scss
- css/includes/components/_text-selection.scss
On GLPI 11, the selection of texts is almost invisible (screenshot before, the text "SELECTION" is highlighted, yes!)
Before
After (like GLPI 10)
> fix: improve text selection readability

- src/Item_Disk.php
- src/Item_Process.php
> Fix disk size display

- src/Glpi/Api/HL/Controller/ITILController.php
Add user/editor user properties for followups, tasks, and solutions. Previously, only the user property for tasks was present.
> [HLAPI] Add missing user props for timeline schemas

- js/src/vue/Kanban/Column.vue
> restore kanban static column width

- js/modules/Forms/EditorController.js
- src/Glpi/Controller/Form/Condition/EditorController.php
- src/Glpi/Form/Comment.php
- src/Glpi/Form/Condition/UsedAsCriteriaInterface.php
- src/Glpi/Form/QuestionType/AbstractQuestionType.php
- src/Glpi/Form/Section.php
- templates/pages/admin/form/form_editor.html.twig
- templates/pages/admin/form/item_has_conditions_for_deletion_modal.html.twig
- templates/pages/admin/form/item_has_conditions_for_new_question_type_modal.html.twig
- templates/pages/admin/form/item_has_conditions_modal_base.html.twig
- tests/cypress/e2e/form/editor/conditions.cy.js
- tests/cypress/e2e/form/form_convert_default_values.cy.js
- tests/cypress/e2e/form/form_preview.cy.js
- tests/cypress/e2e/form/form_translation.cy.js
- tests/cypress/support/commands/form.js
Prevent the question type from being updated when it is used by conditions with unsupported value operators.
> feat(forms): prevent the question type from being updated when it is used by conditions

- src/ValidationStep.php
> Remove silent lenght requirement

- templates/pages/admin/profile/base_tab.html.twig
> Fix save button placement

- install/empty_data.php
- install/migrations/update_10.0.x_to_11.0.0/form.php
- phpunit/functional/EntityTest.php
- tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
- tests/cypress/support/commands.d.ts
Internal request, I've been told to disable the "expand_service_catalog" parameter by default.
> Tweak service catalog internal values

- js/common.js
- templates/components/itilobject/validation.html.twig
- tests/cypress/e2e/dropdown.cy.js
> ajaxdropdownjs fix

- src/Appliance_Item.php
- src/Link.php
- src/NetworkPort.php
- src/ReservationItem.php
- templates/components/form/item_remotemanagement_list.html.twig
- templates/components/form/viewsubitem.html.twig
- templates/components/infocom.html.twig
- templates/components/notepad/form.html.twig
> Rework link display

- src/Config.php
- templates/pages/setup/general/api_setup.html.twig
> Fix API config page

- src/Plugin.php
Some plugins may want to send an error response, do a redirection or even kill the current session during the call to their `init` function. To allow this, we must not catch the corresponding exceptions.
> Do not catch some specific exceptions during plugins init

- phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
- src/Glpi/Form/Question.php
- src/Glpi/Form/QuestionType/AbstractQuestionType.php
- src/Glpi/Form/QuestionType/QuestionTypeInterface.php
- src/Glpi/Form/QuestionType/QuestionTypeItemDropdown.php
This parameter may be used to reference an existing category:
It must be handled by the export/import process as a data requirement.
> Fix question type dropdown item export

- templates/pages/admin/profile/assistance.html.twig
> Fix SQL condition error

- src/Html.php
- It fixes #20454
- It also fix an issue where the field wasn't always displayed as required
> fix(core): Mandatory fields not enforced

- src/Glpi/Features/DCBreadcrumb.php
Fixes #21069
Issue recreated when PDU is "placed at rack side" in a rack.
> fix dc breadcrumb for side pdus

- templates/layout/parts/page_footer.html.twig
- **display speed**
- **missing translation tags in page_footer.html.twig.**
> fix translation2

- src/Glpi/Search/Provider/SQLProvider.php
> Fix entity badge rendering

- src/Glpi/Application/SystemConfigurator.php
It fixes #20632.
It seems that `ini_get()` operations may fail under obscure circumstances. For instance, a comment on the [PHP documentation](https://www.php.net/manual/en/function.ini-set.php#115747) says
> I have experienced on some systems that ini_set() will fail and return a false, when trying to set a setting that was set inside php.ini inside a per-host setting. Beware of this.
1. I removed the `ini_set()` operation when the current value matches the expected value.
2. Any error will be caught and logged. The error log will indicate that the value should be enforced directly in the PHP configuration. If the administrator do it, the `ini_set()` operation will not be required anymore and the error will dissapear.
3. The error will not be blocking anymore, as GLPI will probably be …
> Do not block GLPI execution when session ini set fails

- src/Glpi/Search/Input/QueryBuilder.php
- src/SavedSearch.php
> Prevent Html::redirect call when loading default Search

- src/Glpi/Form/Condition/Engine.php
- tests/cypress/e2e/form/editor/conditions.cy.js
- tests/functional/Glpi/Form/Condition/ConditionHandler/VisibilityConditionHandlerTest.php
- tests/functional/Glpi/Form/Condition/EngineTest.php
If all children of a form section are hidden due to conditions, the section itself should be considered as hidden too.
> Hide form sections with no visible children

- src/Glpi/Form/Form.php
- src/Glpi/Form/ServiceCatalog/ServiceCatalogLeafInterface.php
- templates/components/helpdesk_forms/service_catalog_item.html.twig
- templates/components/helpdesk_forms/service_catalog_nested_item.html.twig
> Use prefixed url in helpdesk view search

- src/KnowbaseItem_Revision.php
The link was malformed due to a missing quote.
> Fix KB revision restore feature

- src/Html.php
- templates/pages/admin/form/form_comment.html.twig
- templates/pages/admin/form/form_editor.html.twig
- templates/pages/admin/form/form_question.html.twig
- templates/pages/admin/form/form_section.html.twig
- templates/pages/form_renderer.html.twig
I've fixed some word breaks issues (no screenshots to showcase it because our internet suck and I can't upload anything...).
Also, I've added a maxlength to name inputs as it triggers an SQL error if the client send a name longer than the field length (255 chars).
It should probably by fixed globally on the backend (not just for form, something to do in the framework itself), I've added myself a TODO to look at it later.
> Form editor overflow

- src/AbstractRightsDropdown.php
- src/Glpi/Controller/Form/QuestionActorsDropdownController.php
- src/Glpi/Form/Dropdown/FormActorsDropdown.php
- tests/functional/Glpi/Controller/Form/QuestionActorsDropdownControllerTest.php
- tests/functional/Glpi/Form/Dropdown/FormActorsDropdownTest.php
Fix multiple issues with the helpdesk actors dropdown.
Fix #21243
> Fix helpdesk forms actors dropdowns

- src/Glpi/Api/HL/Middleware/InternalAuthMiddleware.php
More of a workaround to allow internal "authentication" to work when GLPI is running from external cron/CLI.
> Allow checking fake users in hlapi internal auth for external cron

- src/CommonITILValidation.php
- src/CronTask.php
- src/Html.php
- src/NotificationTarget.php
- src/Session.php
- tests/RuleBuilder.php
> Complete/fix some PHP doc

- js/modules/Forms/EditorController.js
- tests/cypress/e2e/form/editor/editor.cy.js
- tests/fixtures/forms/form-with-validation-2025-10-08.json
Validation constraints are technically coded as condition where the target is the question itself.
This would trigger false positive when trying to delete the question as we don't allow questions that are used by conditions to be deleted:
To prevent this, we must exclude the current item from the results of the `getItemConditionDependencies` method.
> Allow questions with validation constraint to be deleted
