- .phpstan-baseline.php
- src/Html.php
- [X ] I have read the CONTRIBUTING document.
- [X ] I have performed a self-review of my code.
Fix mindate & maxdate for showDateTimeField
In parameters of the function : 
'mintime'    => '',
'maxtime'    => '',
But in the check : it use !empty($p['min']) and not !empty($p['mindate']) - same for maxdate
> Fix mindate & maxdate for showDateTimeField

- phpunit/functional/Glpi/Form/Export/FormSerializerAccessPoliciesTest.php
- phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
- src/Glpi/Controller/Form/Import/Step2PreviewController.php
- src/Glpi/Controller/Form/Import/Step3ResolveIssuesController.php
- src/Glpi/Controller/Form/Import/Step4ExecuteController.php
- src/Glpi/Form/Export/Context/DatabaseMapper.php
- src/Glpi/Form/Export/Result/ImportResultIssues.php
- src/Glpi/Form/Export/Result/ImportResultPreview.php
- src/Glpi/Form/Export/Serializer/FormSerializer.php
- src/Glpi/Form/Export/Specification/FormContentSpecification.php
- templates/pages/admin/form/import/step1_index.html.twig
- templates/pages/admin/form/import/step2_preview.html.twig
- templates/pages/admin/form/import/step3_resolve_issues.html.twig
- templates/pages/admin/form/import/step4_execute.html.twig
- templates/pages/form_renderer.html.twig
- tests/cypress/e2e/form/serializer/import.cy.js
- tests/cypress/support/commands/select2.js
- tests/fixtures/export-of-2-forms.json
- tests/src/FormTesterTrait.php
- Add a new step when importing a form to reconcile objects not available on the GLPI where the form will be imported.
- Add an action to remove a form from the import list.
> feat(forms): Add a new step to the import process to solve requirements issues

- .github/actions/test_install.sh
- src/Glpi/Console/System/CheckRequirementsCommand.php
Fix #18150, introduced by #18017.
The code would trigger a fatal error when `$optional_db` is null because `DatabaseTablesEngine`'s constructor only accept a `DBmysql` object.
It is weird that PHPStan did not report it.
> Fix install requirements

- src/CommonGLPI.php
It fixes #18155.
Revert a small change introduced in #18052. This change was a mistake. Indeed, the `$type` here does not correspond to the `$option` param of the header that was handled in commit https://github.com/glpi-project/glpi/pull/18052/commits/65c732e9e9d52aeff6ce251b98901f3841dcc08d, but corresponds to the `$item` param of the header, that is always transform to lower case see https://github.com/glpi-project/glpi/blob/092903a04b549a525315bb4933dbd77a5f547acc/src/Html.php#L1634
> Fix ticket menu breadcrumbs

- src/Html.php
Automatically load custom palettes the same way core palettes are so they can be easily swapped based on root element attributes.
Example custom palette SCSS (mycustomtheme.scss):
```scss
:root[data-glpi-theme="mycustomtheme"] {
--tblr-primary-rgb: 142, 197, 71;
--tblr-secondary: #768363;
--tblr-secondary-fg: #fcfcfc;
--tblr-link-color-rgb: 69, 148, 54;
--glpi-mainmenu-bg: #459436;
--glpi-mainmenu-fg: #f4f6fa;
}
```
> Autoload custom palettes

- CHANGELOG.md
- src/Glpi/Asset/Capacity/IsInventoriableCapacity.php
- src/Glpi/Rules/RulesManager.php
- src/Rule.php
Follows #18011.
There were some `FIXME` tags on the `Rule::initRules()` method. I fixed them.
> Update `Rule::initRules()` signature

- CHANGELOG.md
- ajax/comments.php
- phpunit/functional/CableTest.php
- phpunit/functional/DropdownTest.php
- phpunit/functional/DropdownTranslationTest.php
- phpunit/functional/NotificationTargetTicketTest.php
- phpunit/functional/SearchTest.php
- src/CommonDBTM.php
- src/CommonDBVisible.php
- src/CommonItilObject_Item.php
- src/Contract_Item.php
- src/DbUtils.php
- src/Dropdown.php
- src/Glpi/Application/View/Extension/ItemtypeExtension.php
- src/Item_Devices.php
- src/NotificationTargetCommonITILObject.php
- src/Rule.php
- src/autoload/dbutils-aliases.php
- templates/components/dropdown/comments.html.twig
- tests/functional/Glpi/Api/HL/Controller/AssetController.php
I extracted the `comments` computation from the `Dropdown::getDropdownName()` method and move it into a `Dropdown::getDropdownComments()` in order to not have a mix between raw data and HTML encoded data in the same method result.
- `Dropdown::getDropdownName()` will now always return a raw value.
- `Dropdown::getDropdownComments()` will always return a safe HTML string.
> Refactor dropdown comments handling

- src/Html.php
- It fixes !34988
To avoid log overload, we suppress the InvalidArgumentException error.
Some non-standard clients, such as bots or simplified HTTP services, don’t always send the User-Agent header,
and privacy-focused browsers or extensions may also block it.
Additionally, server configurations like proxies or firewalls may remove this header for security reasons.
> Fix(Core): prevent log overload when HTTP user-agent is missing

- src/DisplayPreference.php
-> Not needed, there is already a test on this feature. It went unnoticed because we don't check if there are warning in logs after the E2E tests are executed and the test itself still worked as intented.
Fix #18177.
> Fix missing interface criteria when updating display preferences

- ajax/genericdate.php
- Here is a brief description of what this PR does:
AJAX-generated date fields are always of type datetime, an example is contracts that have a Start date field with datatype date.
This is because the POST receives false as a boolean but interprets it as a text string, so the check is always correct as it is always text.
The fix validates value as a boolean option.
> Genericdate always shows datetime fields

- install/migrations/update_10.0.16_to_10.0.17/users.php
- install/mysql/glpi-empty.sql
- src/CommonDBTM.php
- src/Session.php
- src/User.php
- It fixes !33072
Completely replace the 'root entity' with 'Full structure' for the user's default entity selection (feature: https://github.com/glpi-project/glpi/pull/17923). This is to handle the case where a user has multiple permissions for the same profile, including one for the root entity that is non-recursive.
> fix(user): default entity value = Full structure

- src/Glpi/Console/Application.php
When a user created a database manually, then uses the `bin/console db:configure` command to create the database configuration file, and then uses the `bin/console db:install` command, the following SQL error is triggerred: `` SQL Error "1146": Table 'glpi.glpi_configs' doesn't exist in query "SELECT * FROM `glpi_configs`" ``.
The proposed change fixed it.
> Fix console error on missing config table

- src/Glpi/Console/Database/UpdateCommand.php
-> not easily testable
Fix an issue reported by @cedric-anne where an user can try to update GLPI without a valid config file.
```
Uncaught Exception TypeError: Glpi\System\Requirement\DatabaseTablesEngine::__construct(): Argument #1 ($db)
must be of type DBmysql, null given, called in /var/www/glpi/src/Glpi/Console/Database/UpdateCommand.php 
on line 97 in /var/www/glpi/src/Glpi/System/Requirement/DatabaseTablesEngine.php at line 47
```
> Fix update without config file

- phpunit/functional/Glpi/Inventory/InventoryTest.php
- phpunit/functional/RuleImportAssetTest.php
- src/Glpi/Inventory/Asset/InventoryAsset.php
- src/Glpi/Inventory/Asset/VirtualMachine.php
- src/RuleImportAsset.php
Addition of a new ‘Virtualisation system’ criterion in the rules for importing and linking equipment (for Computers). (Ticket : !33353)
> (Feat) ‘Virtualisation system’ criterion in the rules

- CHANGELOG.md
- phpunit/functional/ComputerTest.php
- phpunit/functional/MassiveActionTest.php
- src/CommonDBTM.php
- src/Glpi/Features/Clonable.php
- src/MassiveAction.php
- src/ProfileRight.php
- tests/functional/Glpi/Features/Clonable.php
- tests/web/APIRest.php
Proper implementation of what was blocked in #17775 (v10.0.17) to prevent undefined behavior.
- Allow cloning templates -> new templates
- Allow creating a template from a single item
> Template Cloning

- install/install.php
- src/GLPIKey.php
- src/Glpi/Console/Database/InstallCommand.php
When a user created a database manually, then uses the `bin/console db:configure` command to create the database configuration file, and then uses the `bin/console db:install` command, the following SQL error are triggerred:
```
SQL Error "1146": Table 'glpi.glpi_mailcollectors' doesn't exist in query "SELECT `id`, `passwd` FROM `glpi_mailcollectors` WHERE ( NOT (`passwd` IS NULL))"
SQL Error "1146": Table 'glpi.glpi_oauthclients' doesn't exist in query "SELECT `id`, `secret` FROM `glpi_oauthclients` WHERE ( NOT (`secret` IS NULL))"
SQL Error "1146": Table 'glpi.glpi_snmpcredentials' doesn't exist in query "SELECT `id`, `auth_passphrase` FROM `glpi_snmpcredentials` WHERE ( NOT (`auth_passphrase` IS NULL))"
SQL Error "1146": Table 'glpi.glpi_snmpcredentials' doesn't exist in query "SELECT …
```
> Fix key generation when database has no tables yet

- ajax/criteria_filter.php
- ajax/stencil.php
- ajax/task.php
- src/Glpi/Controller/ApiController.php
- src/Glpi/Controller/StatusController.php
- src/QueuedWebhook.php
`Glpi\Http\Response::send()` uses the `http_response_code()` function. We have to remore its usages, when possible, to get a better compatibility with the Symfony framework.
> Remove some usages of `Glpi\Http\Response::send()`

- src/Glpi/Controller/ApiController.php
- src/Glpi/Controller/StatusController.php
Can't use `getContents` on response body stream if pointer is already at the end of the stream. Symfony was dropping the response body for all API requests.
> Fix response body from API

- phpunit/functional/SearchTest.php
- src/Search.php
A quick fix for #18251.
This reverts commit d80db3a6534bfeabe3e7406e8ceadd549e7366fb. The initial bug was less problematic by the regression introduced by this commit.
> Revert "Fix sub queries negation for `notcontains` searches"

- phpunit/functional/EntityTest.php
- src/CommonTreeDropdown.php
I found while trying to debug the test failure on `main` after the 10.0 merge that updating an entity name with nothing else in the update parameters would cause the entity's parent to be replaced with the root entity. This seems like it would be an issue with the API, but not the web interface. When renaming an entity (and presumably any tree dropdown), it was assumed that the parent ID field was always in the input array.
I'm not 100% confident in this fix because I don't completely understand what the original code was trying to accomplish. That is why this targets `main` currently.
> Prevent dropdown parent reassignment during partial updates

- phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
- src/Glpi/Form/Export/Context/ForeignKey/ForeignKeyHandler.php
- src/Glpi/Form/Export/Serializer/FormSerializer.php
- src/Glpi/Form/Export/Specification/AccesControlPolicyContentSpecification.php
- src/Glpi/Form/Export/Specification/ContentSpecificationInterface.php
- src/Glpi/Form/Export/Specification/FormContentSpecification.php
- src/Glpi/Form/Export/Specification/QuestionContentSpecification.php
- src/Glpi/Form/Question.php
- src/Glpi/Form/QuestionType/AbstractQuestionType.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
- src/Glpi/Form/QuestionType/QuestionTypeActorsDefaultValueConfig.php
- src/Glpi/Form/QuestionType/QuestionTypeActorsExtraDataConfig.php
- src/Glpi/Form/QuestionType/QuestionTypeDateTime.php
- src/Glpi/Form/QuestionType/QuestionTypeDateTimeExtraDataConfig.php
- src/Glpi/Form/QuestionType/QuestionTypeDropdown.php
- src/Glpi/Form/QuestionType/QuestionTypeDropdownExtraDataConfig.php
- src/Glpi/Form/QuestionType/QuestionTypeInterface.php
- src/Glpi/Form/QuestionType/QuestionTypeItem.php
- src/Glpi/Form/QuestionType/QuestionTypeItemDefaultValueConfig.php
- src/Glpi/Form/QuestionType/QuestionTypeItemExtraDataConfig.php
- src/Glpi/Form/QuestionType/QuestionTypeSelectableExtraDataConfig.php
- src/Glpi/Form/QuestionType/QuestionTypeUserDevice.php
- tests/cypress.config.js
- tests/src/FormTesterTrait.php
Adds export and import of questions
> feat(forms): Add export and import functionality for questions

- phpunit/functional/UserTest.php
- src/User.php
It fixes #18261.
From the search endpoint, the `User::unsetUndisclosedFields()` method will receive an array that does not cotnains the `id` of the user. In this case, we cannot be sure that the current user is allowed to view the `password_forget_token` field and therefore we must remove it.
> Fix warning on API ticket searches

- ajax/common.tabs.php
- templates/components/form/buttons.html.twig
- It fixes !35099
The “Delete permanently” button was no longer displayed on notification templates.
> fix(notification template): purge button missing

- templates/pages/login.html.twig
Session e2e tests have been broken since the latest 10.0 merge into main.
It seems to be because the `label` tag also contains some extra content (the "forgot password" link), thus the `getInputByLabel('Password')` call fails.
Not sure why it only happens since last merge (in fact it doesn't even happen on my local env running the same docker script...) but this change should hopefully fix it as I've moved the extra content outside the label.
> Fix session e2e tests

- js/glpi_dialog.js
- src/Glpi/Search/Input/QueryBuilder.php
- templates/components/dropdown/limit.html.twig
- templates/components/form/basic_inputs_macros.html.twig
- templates/components/form/fields_macros.html.twig
- templates/components/pager.html.twig
- templates/components/search/controls.html.twig
- templates/components/search/query_builder/search_option_value.html.twig
- templates/pages/assistance/planning/filters.html.twig
- templates/pages/assistance/planning/single_filter.html.twig
- tests/cypress/e2e/Planning/external_event.cy.js
- tests/cypress/e2e/Planning/planning_view.cy.js
- tests/cypress/e2e/page_layout.cy.js
- tests/cypress/e2e/search_engine.cy.js
- tests/cypress/support/cypress-axe.js
Fixed:
- Modals from `glpi_html_dialog` were missing a label
- Modals from `glpi_html_dialog` did not capture focus (could not tab through the inputs in the dialog without first clicking inside it)
- Modals from `glpi_html_dialog` had the wrong header level for the title
- The button next to date/datetime inputs had no label
- Automatically generated IDs from names may break labels because the name wasn't slugified
- Planning view button to add a new calendar had no label
- Planning view filter color inputs had no label
- Massive action checkboxes in search results had no label
- Search criteria value input had no label
- …
> Accessibility improvements

- phpunit/functional/Glpi/Helpdesk/HomePageTabsTest.php
- src/Glpi/Controller/Helpdesk/IndexController.php
- src/Glpi/Helpdesk/HomePageTabs.php
- src/RSSFeed.php
- src/Reminder.php
On the helpdesk home page, do not display the `Reminder` and `Rss feeds` tabs if they have no content.
> Do no show empty reminder/rss tabs on home page

- src/Glpi/Console/Application.php
The #17985 PR added the ability to run Symfony commands, however it misses this change for which the Symfony Kernel sometimes need to get the Kernel from the Application class, such as the `debug:router` command (which can be run as `symfony:debug:router` in GLPI)
> [11.0] Fix missing Kernel in Application class

- install/migrations/update_10.0.x_to_11.0.0/mailcollectors.php
- install/mysql/glpi-empty.sql
- src/MailCollector.php
- templates/pages/setup/mailcollector/setup_form.html.twig
- tests/emails-tests/44-multiple-to.eml
- tests/imap/MailCollector.php
- It fixes !34412
Currently, other addresses in the "TO" field of emails are automatically added as ticket observers. This PR introduces an option to enable or disable this behavior.
> feat(mail collector): add 'TO' as observer

- composer.lock
- package-lock.json
It fixes #18325 and #18326.
```
+-------------------+----------------------------------------------------------------------------------+
| Package           | symfony/http-client                                                              |
| Severity          | low                                                                              |
| CVE               | CVE-2024-50342                                                                   |
| Title             | CVE-2024-50342: Internal address and port enumeration allowed by                 |
|                   | NoPrivateNetworkHttpClient                                                       |
| URL               | https://symfony.com/cve-2024-50342                                               |
| Affected versions | …
```
> Update dependencies to get latest security fixes

- src/Glpi/Config/LegacyConfigurators/ConfigRest.php
On any page that can be accessed without a full session loaded (login page, FAQ, install, update, ...), the proposed change will save a useless cache entry access. Indeed, in this case, `isset($_SESSION['glpigroups'])` will be `false` so the `last_group_change` cache entry value will not be used.
> Optimize disk I/O when checking session groups validity

- templates/generic_show_form.html.twig
- It fixes !35244
Since https://github.com/glpi-project/glpi/commit/df3033e38ed05c05055ac5594098f540581021ec, the read-only “Is active” field has been displayed.
> fix(suppliers): is active

- src/Glpi/Api/API.php
- tests/web/APIRest.php
- It fixes !35017
Retrieve the network ports of connected devices. Previously, the API only provided information about the main device's network ports, not its connections. The added code uses `NetworkPort::getContact` to retrieve the connected port ID `netport_oppositecontactID`, allowing users to identify connected devices directly in the API response. This addition is visible when the `with_networkports` option is enabled in the request.
> Add the port ID connected to the requested port

- phpunit/functional/Glpi/SocketTest.php
- src/Socket.php
- templates/pages/assets/socket.html.twig
Fixes #18202
Sockets are supposed to be allowed to exist without being connected to an item, but it was trying to save an empty string to the `items_id` column. Default selection for "Item" was an empty string instead of 0.
Fix ensures that if the items_id field is an empty value, the itemtype and items_id values are not saved.
> Fix creating socket without item linked

- inc/based_config.php
This prevents "already defined constants" errors when `inc/downstream.php` file is configured. This file should not be used from tests.
> Do not include downstream file from tests

- front/inventory.php
I think it's better to return a 403 error rather than a classic 200 code (the current behavior), making it seem like everything is OK.
> fix: return 403 when inventory is disabled

- css/helpdesk_home.scss
- js/modules/Helpdesk/IndexController.js
- src/Glpi/Controller/Helpdesk/SearchController.php
- templates/pages/helpdesk/index.html.twig
- templates/pages/helpdesk/search.html.twig
- tests/cypress/e2e/self-service/home.cy.js
Allow user to search for forms and faq articles on home page.
> Search for forms and faq articles on home page

- src/Unmanaged.php
Fixes #18372 
One problem left: if we convert only one Unmanaged from the list, we'll be redirected to the new asset form instead of unmanaged list; I did not find how to know if we were called from the form or from the list.
> Redirect on new asset after unmanaged conversion

- templates/generic_show_form.html.twig
- It fixes !35334
A lock set on the sysdescr field is correctly recorded in the database and appears in the list of locks. 
However, in the object, the lock icon is not displayed next to the field.
> Fix(LockedField): display lock for 'sysdescr'

- inc/relation.constant.php
- install/migrations/update_10.0.x_to_11.0.0/form.php
- install/mysql/glpi-empty.sql
- phpunit/functional/Glpi/Helpdesk/DefaultDataManagerTest.php
- phpunit/functional/Glpi/Helpdesk/Tile/TilesManagerTest.php
- src/CommonDBTM.php
- src/Glpi/Controller/Helpdesk/IndexController.php
- src/Glpi/Helpdesk/DefaultDataManager.php
- src/Glpi/Helpdesk/Tile/ExternalPageTile.php
- src/Glpi/Helpdesk/Tile/FormTile.php
- src/Glpi/Helpdesk/Tile/GlpiPageTile.php
- src/Glpi/Helpdesk/Tile/Profile_Tile.php
- src/Glpi/Helpdesk/Tile/TileInterface.php
- src/Glpi/Helpdesk/Tile/TilesManager.php
- src/Glpi/Session/SessionInfo.php
- src/Session.php
- templates/pages/helpdesk/index.html.twig
Move the hardcoded tiles of the home page into the database.
Next step is allowing tiles to be added and removed from GLPI's UI.
While a tile is technically just a title + a description + an illustration + a link, there are 3 distinct types to ease configuration:
* `GlpiPageTile`: harcoded link to a GLPI page.
* `ExternalPageTile`: link to any page.
* `FormTile`: link to a form.
Having these dedicated types will make it easier for user to configure their own tiles later as it abstract the 'link' away from the user in most cases (e.g. no need to know the URL of the service catalog page to add a "ServiceCatalog" tile).
> Save home page tiles to database

- .github/workflows/ci.yml
- composer.json
- composer.lock
- phpunit/functional/TicketTest.php
- phpunit/functional/ToolboxTest.php
- public/index.php
- src/Consumable.php
- src/Glpi/Application/ErrorHandler.php
- src/Glpi/Asset/Asset_PeripheralAsset.php
- src/Glpi/DBAL/QueryFunction.php
- src/Glpi/Dashboard/FakeProvider.php
- src/Glpi/Features/State.php
- src/Glpi/Form/ServiceCatalog/ServiceCatalogManager.php
- src/Glpi/Marketplace/Controller.php
- src/Glpi/System/Log/LogParser.php
- src/IPAddress.php
- src/Line.php
- src/QueuedWebhook.php
- src/Reservation.php
- src/Toolbox.php
- src/autoload/constants.php
- tests/functional/DBmysqlIterator.php
- tests/functional/Glpi/Application/ErrorHandler.php
- tests/functional/Glpi/Http/LegacyAssetsListener.php
- tests/functional/Glpi/Http/LegacyRouterListener.php
- tests/src/FormTesterTrait.php
- tools/patches/apereo-phpcas-php84.patch
The following dependencies patches were proposed but are not yet all validated or released.
- https://github.com/apereo/phpCAS/pull/444
- https://github.com/atoum/atoum/pull/899
- https://github.com/atoum/stubs/pull/24
- https://github.com/thephpleague/event/pull/107
- https://github.com/thephpleague/oauth2-client/pull/1034
- https://github.com/thephpleague/oauth2-server/pull/1440
- https://github.com/sabre-io/dav/pull/1560
- https://github.com/sabre-io/vobject/pull/673
- https://github.com/swaggest/json-diff/pull/69
- https://github.com/swaggest/php-json-schema/pull/163
- https://github.com/symfony/symfony/pull/58169
- …
> PHP 8.4 compatibility

- phpunit/functional/SearchTest.php
- src/Glpi/Search/Provider/SQLProvider.php
Alternative to #18386.
The `Items seen` criteria should add a `WHERE` condition for a displayed field only when the searched term matches the expected pattern of the corresponding search option.
> Fix `AND NOT`/`OR NOT` `view` `contains` search filter

- src/Auth.php
- src/Glpi/Application/SystemConfigurator.php
- src/Glpi/System/Requirement/SessionsConfiguration.php
- src/Glpi/System/Requirement/SessionsSecurityConfiguration.php
- tests/functional/Glpi/System/Requirement/SessionsConfiguration.php
- tests/functional/Glpi/System/Requirement/SessionsSecurityConfiguration.php
We are now sure that the GLPI bootstrapping made in the `SystemConfigurator` class will be done prior to any core front/ajax script and any plugin file inclusion and therefore before any possibility that a session was manually started. We can therefore force some session configuration in order to simplify the configuration requirements.
> Force some session settings to ease the server configuration

- src/Glpi/Exception/Http/RedirectException.php
- src/Glpi/Exception/RedirectException.php
- src/Glpi/Http/AccessErrorListener.php
- src/Html.php
Converts "exit" into an exception that will be converted by a proper redirection by the existing exception listener in the project
> Don't use `exit` anymore for Html::redirect

- install/install.php
- install/update.php
- src/Html.php
- templates/layout/parts/head.html.twig
Required for #18296 .
The locales were not loaded on the JS side in the install/update process. Instead of implementing a custom piece of code, I reused the `layout/parts/head.html.twig` template that contains a call to `{{ locales_js() }}`.
It also replaces #18400.
> Fix loadings of JS locales on install/update pages

- dependency_injection/services.php
See https://github.com/glpi-project/glpi/pull/18296#discussion_r1861844945
Not sure it is necessary. There is no reference to this class in any service, so the DI will probably never try to instanciate it.
> Exclude `SessionProgress` from DI

- templates/pages/setup/webhook/webhooktest.html.twig
Very long ticket content, completely breaks the webhook preview display.
> fix(webhook): wrap long text in preview

- install/install.php
- src/Glpi/Controller/InstallController.php
I just realized that a security check was missing in #18296 .
> Add missing `is_installing` check

- src/Glpi/Asset/Asset_PeripheralAsset.php
I had an SQL error when loading the dropdown that allows you to connect an Asset from the "Connections" tab of a Peripheral, because "is_global" (onlyglobal) is not necessary in "showForPeripheral".
```
glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: MySQL query error: Unknown column 'glpi_computers.is_global' in 'where clause' (1054) in SQL query "SELECT DISTINCT `glpi_computers`.* FROM `glpi_computers` WHERE (1) AND `glpi_computers`.`is_deleted` = '0' AND `glpi_computers`.`is_template` = '0' AND `glpi_computers`.`is_global` = '1' AND ((`glpi_computers`.`entities_id` = '0' OR (`glpi_computers`.`is_recursive` = '1' AND `glpi_computers`.`entities_id` IN ('0')))) ORDER BY `glpi_computers`.`entities_id`, `glpi_computers`.`name` …
```
> fix(asset_peripheral): incorrect query and twig macro name

- src/Glpi/Controller/CommonAjaxController.php
This `catch` block is no longer needed as we now already have a global `catch` block inside GLPI's kernel that is doing a better job than this one.
> Remove CommonAjaxController error handler

- src/AuthMail.php
- templates/pages/setup/authentication/mail.html.twig
- templates/pages/setup/mailcollector/server_config_fields.html.twig
- templates/pages/setup/mailcollector/setup_form.html.twig
Based on #18409
The "Test" tab in the form to configure email authentication (/front/authmail.form.php?id=1), does not work anymore: the hidden field "imap_string" was no longer in the form.
I also removed this "imap_string" field from the MailCollector part, it is not useful.
> fix: authmail connection test form

- install/migrations/update_10.0.x_to_11.0.0/assets.php
- install/mysql/glpi-empty.sql
- phpunit/functional/Glpi/Asset/CustomFieldDefinitionTest.php
- src/Glpi/Asset/AssetDefinition.php
- src/Glpi/Asset/CustomFieldDefinition.php
- src/Glpi/CustomObject/AbstractDefinition.php
- templates/pages/admin/customobjects/translations.html.twig
- tests/cypress/e2e/Asset/asset_definition.cy.js
Allow translating custom field labels
> Custom field translations

- src/Change.php
- src/CommonItilObject_Item.php
- src/Problem.php
- src/Ticket.php
- templates/components/datatable.html.twig
- templates/components/form/item_itilobject_group.html.twig
- templates/components/form/item_itilobject_item_list.html.twig
Passage of the code for displaying the list of items linked to an Itil object in twig as requested on the PR: #17680
> Itilobject_item showListForitem twig update

- src/Dropdown.php
- src/User.php
- src/UserEmail.php
- It fixes !35356
`is_active` field cannot be updated by a user with a profile with fewer rights.
The field could be modified, a confirmation message said the user was updated without error, but the field was unchanged, suggesting a bug.
The PR sets the field to readonly (as well as any e-mails in the same situation).
> fix(user): can not update is_active field

- src/Glpi/Http/AccessErrorListener.php
- src/Glpi/Http/RedirectExceptionListener.php
`RedirectException` should always trigger a redirection, even for ajax requests. The `AccessErrorListener` is only handling excpetion for main and non-ajax requests, so I moved the logic into a dedicated listener that would handle `RedirectException` regardless the request context.
> Fix redirect exception handling

- src/CommonDBTM.php
- tests/functional/Migration.php
- It fixes !35208
In the webhook filters, when targeting ticket creations (e.g., "Technician assigned is Jon Doe"), the webhook is not triggered for a ticket that meets the valid conditions.
The issue lies in the fact that post_add elements (such as adding a user to the ticket) are processed only after the filtering criteria are evaluated to determine whether the webhook should be triggered.
> Fix tickets users added after webhook filter check

- front/ticket.form.php
- phpunit/functional/CommonITILValidationTest.php
- src/CommonITILObject.php
- src/CommonITILValidation.php
- src/Dashboard/Provider.php
- src/Ticket.php
- It fixes !35135
When the ticket is closed and there are validation requests waiting for a response, it is still possible to validate them, but this does not update the global status.
So I deactivated the possibility of accepting a validation request once the ticket has been closed.
**Before**
**After**
> Fix validationresponse ticket close

- .phpstan-baseline.php
- phpunit/DbTestCase.php
- phpunit/GLPITestCase.php
- src/Glpi/Asset/Asset.php
- src/Glpi/Asset/AssetDefinition.php
- src/Glpi/Asset/AssetDefinitionManager.php
- src/Glpi/Asset/AssetModel.php
- src/Glpi/Asset/AssetType.php
- src/Glpi/Asset/Capacity/AbstractCapacity.php
- src/Glpi/Asset/Capacity/CapacityInterface.php
- src/Glpi/Asset/Capacity/IsInventoriableCapacity.php
- src/Glpi/Asset/RuleDictionaryModel.php
- src/Glpi/Asset/RuleDictionaryModelCollection.php
- src/Glpi/Asset/RuleDictionaryType.php
- src/Glpi/Asset/RuleDictionaryTypeCollection.php
- src/Glpi/Config/LegacyConfigurators/CustomObjectsBootstrap.php
- src/Glpi/CustomObject/AbstractDefinition.php
- src/Glpi/CustomObject/AbstractDefinitionManager.php
- src/Glpi/Dropdown/Dropdown.php
- src/Glpi/Dropdown/DropdownDefinition.php
- src/Glpi/Dropdown/DropdownDefinitionManager.php
- tests/DbTestCase.php
- tests/functional/Glpi/Asset/AssetDefinition.php
- tests/functional/Glpi/Asset/AssetDefinitionManager.php
- tests/functional/Glpi/Dropdown/DropdownDefinition.php
- tests/functional/Glpi/Dropdown/DropdownDefinitionManager.php
It is based on #18306 and replaces it. It fixes #18304.
The purpose of this PR is to add a `CapacityInterface::onCapacityEnabled()` method that can be used to define a logic that has to be call only at the moment a capacity is enabled. For instance, the loading of the default import rules has to be done only once.
I had to review a bit the custom assets/dropdowns definition handling to be able to reload a definition at runtime. This was already done in the tests with some kind of hacky code, but now it is done in a more proper way, and this is no longer necessary to use the reflection API to do this.
I also added a call to `CapacityInterface::onCapacityDisabled()` in the `AssetDefinition::cleanDbOnPurge()`. It is probably unecessary for the most common cases, but it permits to be sure …
> Add the ability to implement a specific logic when a capacity is enabled

- .phpstan-baseline.php
- phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
- phpunit/functional/Glpi/Form/FormTest.php
- src/Glpi/Form/Export/Serializer/FormSerializer.php
- src/Glpi/Form/Form.php
- src/Glpi/Form/Section.php
- src/Glpi/Form/Tag/CommentDescriptionTagProvider.php
- src/Glpi/Form/Tag/CommentTitleTagProvider.php
- tests/src/FormTesterTrait.php
There was a `getComments` method added for forms a while ago, this is incorrect because there is already a method with the same name from `CommonDBTM`.
I've changed the name to `getFormComments` to avoid this issue.
> Fix incorrect method name

- js/modules/Dashboard/Dashboard.js
- tests/js/modules/Dashboard/Dashboard.test.js
GridStack 11 removed the ability to add widgets with HTML content directly and they also changed the signature for `GridStack.addWidget`. This PR fixes the usage of `GridStack.addWidget` and overrides the default `GridStack.renderCB` to assign the content to the innerHTML again instead of innerText.
Fixes #18462
> Fix adding dashbaord cards HTML content

- .github/workflows/ci.yml
To prevent tests to run for too long, we'll be warned if a job is cancelled.
> Set 1 hour timeout for tests

- composer.json
- phpunit/functional/AutoloadTest.php
- src/autoload/legacy-autoloader.php
Since we now have all our namespaced classes located in the `src/Glpi` directory, we can safely rely on composer to use the `"": "src/"` fallback in order to load all our classes that have no namespace.
As we use the `"optimize-autoloader": true` option, the autoloading will be based on an optimized logic, using a classname<>filename mapping (generated automatically during `composer install/update` operations) that will, most of the time, be more efficient than our custom checks.
> Rely on composer to autoload all GLPI classes

- src/Glpi/Routing/PluginRoutesLoader.php
The plugins routes loader was trying to load routes from plugins that had no `src/Controller` directory. This was resulting in the following error:
```
The file "/var/www/glpi/plugins/xxx/src/Controller/" does not exist.
In /var/www/glpi/vendor/symfony/config/FileLocator.php(46)
#0 /var/www/glpi/vendor/symfony/routing/Loader/AttributeDirectoryLoader.php(31): Symfony\Component\Config\FileLocator->locate('/var/www/glpi/p...')
#1 /var/www/glpi/src/Glpi/Routing/PluginRoutesLoader.php(66): Symfony\Component\Routing\Loader\AttributeDirectoryLoader->load('/var/www/glpi/p...', 'attribute')
#2 /var/www/glpi/vendor/symfony/routing/Router.php(186): Glpi\Routing\PluginRoutesLoader->load('plugins_routes', NULL)
#3 /var/www/glpi/vendor/symfony/routing/Router.php(250): …
```
> Prevent plugins routes loader to fail if a plugin has no controllers

- src/Html.php
Since #18126, the HTTP path of JS files of the plugins differs from the filesystem path. There is currently a check done to ensure that the files targeted in the `add_javascript` hook exist, but it is broken.
I propose to remove this check. I do not see any reason to not add the script tag related to this file.
Also, we could consider that plugin developers may want to include a script that is served by a controller. In this case, it is a normal situation to not find the file on the filesystem.
> Do not check file existence in `add_javascript` hook

- src/Glpi/Asset/Capacity/AllowedInGlobalSearchCapacity.php
- tests/functional/Glpi/Asset/Capacity/AllowedInGlobalSearchCapacity.php
Add the ability to allow global searches for a generic asset definition.
> Add `Global search` capacity

- ajax/asset/assetdefinition.php
- install/migrations/update_10.0.x_to_11.0.0/assets.php
- install/migrations/update_10.0.x_to_11.0.0/dropdowns.php
- install/mysql/glpi-empty.sql
- js/src/vue/CustomObject/FieldPreview/FieldDisplay.vue
- phpunit/functional/Glpi/Asset/CustomFieldDefinitionTest.php
- src/Glpi/Asset/Asset.php
- src/Glpi/Asset/AssetDefinition.php
- src/Glpi/Asset/CustomFieldDefinition.php
- src/Glpi/CustomObject/AbstractDefinition.php
- templates/pages/admin/customobjects/main.html.twig
- templates/pages/assets/customfield.html.twig
- tests/functional/Glpi/Asset/Asset.php
- tests/functional/Glpi/Asset/AssetDefinition.php
- tests/functional/Glpi/Dropdown/DropdownDefinition.php
Adjust how Custom Assets and Custom Dropdowns have their system name / default label handled to match closer to what was done with Custom Fields.
> Review custom object system name and label

- src/Inventory/Request.php
During the exchange between the agent and the server, it was observed that the support for the **"inventory"** task is not included in the server's response, even though it is required for certain planned tasks such as **"esx"**, **"netdiscovery"**, **"netinventory"**, and **"remoteinventory"**. For example, the current response:
```json
{
"expiration": "4",
"status": "ok",
"tasks": {
"esx": {
"version": "1.4.0",
"server": "glpiinventory"
}
}
}
```
should also include the **"inventory"** task, as follows:
```json
{
"expiration": "4",
"status": "ok",
"tasks": {
"esx": {
"version": "1.4.0",
"server": "glpiinventory"
},
"inventory": {
"version": "10.0.17",
"server": "glpi"
}
}
}
```
This would …
> Fix add inventory task info

- .phpstan-baseline.php
- src/Glpi/Api/HL/Controller/AbstractController.php
- src/Glpi/Api/HL/Controller/AssetController.php
- src/Glpi/Api/HL/Controller/ComponentController.php
- src/Glpi/Api/HL/Controller/CoreController.php
- src/Glpi/Api/HL/Controller/ITILController.php
- src/Glpi/Api/HL/Controller/ManagementController.php
- src/Glpi/Api/HL/Controller/ProjectController.php
- src/Glpi/Api/HL/Controller/RuleController.php
- src/Glpi/Api/HL/Doc/Schema.php
- src/Glpi/Api/HL/OpenAPIGenerator.php
- src/Glpi/Api/HL/Route.php
- src/Glpi/Api/HL/RoutePath.php
- src/Glpi/Api/HL/Search.php
- tests/functional/Glpi/Api/HL/Controller/ComponentController.php
- tests/functional/Glpi/Api/HL/Controller/ManagementController.php
The OpenAPI schema has some validation issues according to the online Swagger editor. None of the validation issues actually seem to affect the Swagger UI display, but I guess some tools could have trouble parsing it. For example, the online Swagger editor doesn't seem able to generate clients based on the schema.
Fixes #18158
> Fix OpenAPI schema validation issues

- phpunit/functional/UserTest.php
- src/User.php
- It fixes !35356
Following https://github.com/glpi-project/glpi/pull/18441, the `is_active` field can still be modified by massive actions, a success message is displayed saying that the user has been modified, but the field was not modified in base. This PR is designed to display an error message while maintaining this security control.
> fix(user): can not update is_active field via massive action

- src/DBConnection.php
- src/Glpi/Config/LegacyConfigurators/StandardIncludes.php
- src/Glpi/System/Status/StatusChecker.php
The `$display` parameter of the `DBConnection::establishDBConnection()` method is never used. It could be removed to simplify future refactoring.
Seen while reviewing #18497.
> Remove unused parameter from `DBConnection::establishDBConnection()`

- install/empty_data.php
I don't know if other actions trigger this error, but when we go to "Setup > General > Search result display," select one or more checkboxes, then "Actions > Reset to default," we encounter this error.
```
glpiphplog.WARNING:   *** PHP Warning (2): foreach() argument must be of type array|object, true given in /home/francois/www/glpi-core/main/htdocs/install/empty_data.php at line 943
Backtrace :
install/empty_data.php:9322                        class@anonymous /home/francois/www/glpi-core/main/htdocs/install/empty_data.php:42$1->getEmptyData()
src/DisplayPreference.php:715                      require()
src/DisplayPreference.php:129                      DisplayPreference::resetToDefaultOptions()
src/MassiveAction.php:1462 …
```
> fix(empty_data): force include to not return true

- js/modules/Dashboard/Dashboard.js
- tests/js/modules/Dashboard/Dashboard.test.js
With the gridstack content rendering changes in version 11, the content refers to the `.gridstack-item-content` rather than `.gridstack-item`. The controls were being placed within the content and then overwritten when the card HTML was retrieved from the server.
> Fix missing controls after editing dashboard card

- .phpstan-baseline.php
- CHANGELOG.md
- ajax/savedsearch.php
- js/common.js
- js/modules/Search/Table.js
- phpunit/functional/SavedSearch_UserTest.php
- phpunit/functional/SearchTest.php
- src/Glpi/Search/Input/QueryBuilder.php
- src/Glpi/Search/SearchEngine.php
- src/Html.php
- src/SavedSearch.php
- tests/js/modules/Search/Table.test.js
| New feature?  | -
Adds a validation pass after the `QueryBuilder` is done building the search parameters array before it is sent to the data provider (`SQLProvider`). If a criterion refers to an invalid search option (typo in API request, missing plugin, bad saved search, etc), it is removed and a warning will be displayed to the user that states "Some search criteria were removed because they are invalid". Invalid sorts are silently discarded currently.
Since the legacy API uses the search engine as if it were a request from the web, but without the output, this PR adds validation to it too. Does not apply to High-Level API which doesn't …
> Validate search criteria

- src/Glpi/Asset/AssetDefinition.php
- src/Glpi/CustomObject/AbstractDefinition.php
- templates/pages/admin/customobjects/profiles.html.twig
- tests/cypress/e2e/Asset/asset_definition.cy.js
- tests/cypress/support/commands.js
- tests/functional/Glpi/Asset/AssetDefinition.php
> Add Custom Asset to ITIL Link Types from Definition

- .phpstan-baseline.php
- CHANGELOG.md
- install/update.php
- src/DBConnection.php
- src/DBmysql.php
Since PHP 8.2, the `MySQLi` extension always use the `mysqlnd` driver, see https://php.watch/versions/8.2/mysqli-libmysql-no-longer-supported. It is therefore not anymore required to check if the `MYSQLI_OPT_INT_AND_FLOAT_NATIVE` is defined, as it will be always defined.
> Remove useless mysqlnd driver compatibility check

- .phpstan-baseline.php
- phpstan.neon.dist
- src/Session.php
Based on PHPStan configuration change proposed in #18056.
Using a stub file to declare our dynamic constants was not the best solution as PHPStan was considering them to be always defined with a `null` value. The proper way to handle it is to use the `dynamicConstantNames` parameter.
The `stubs/glpi_constants.php` file may not be required anymore, unless it can be used to suppress IDEs errors. @orthagh @AdrienClairembault @trasher @cconard96, is this file still required for your IDEs?
> Fix handling of GLPI dynamic constants in PHPStan

- phpunit/functional/Glpi/Http/LegacyItemtypeRouteListenerTest.php
- phpunit/functional/Glpi/Http/RedirectLegacyRouteListenerTest.php
- src/Glpi/Http/Listener/AccessErrorListener.php
- src/Glpi/Http/Listener/FirewallStrategyListener.php
- src/Glpi/Http/Listener/LegacyAssetsListener.php
- src/Glpi/Http/Listener/LegacyItemtypeRouteListener.php
- src/Glpi/Http/Listener/LegacyPostRequestActionsListener.php
- src/Glpi/Http/Listener/LegacyRouterListener.php
- src/Glpi/Http/Listener/PluginsRouterListener.php
- src/Glpi/Http/Listener/RedirectExceptionListener.php
- src/Glpi/Http/Listener/RedirectLegacyRouteListener.php
- src/Glpi/Http/ListenersPriority.php
- src/Glpi/Kernel/Kernel.php
- tests/functional/Glpi/Http/Listener/LegacyAssetsListener.php
- tests/functional/Glpi/Http/Listener/LegacyRouterListener.php
This was messed up, between services and DTOs, so a sub-dir is easier to maintain
> Move HTTP listeners to a sub-namespace

- src/Item_Devices.php
> Missing Location search options in item_devices; closes #18529

- css/includes/_palette_dark.scss
The dark surface background color was calculated to be light in the dark theme base CSS which was causing tooltips to show a light background with light text.
> Fix dark theme tooltips bg

- .phpstan-baseline.php
- CHANGELOG.md
- install/install.php
- phpunit/functional/ConfigTest.php
- src/Config.php
- src/Glpi/Config/LegacyConfigurators/LoadLegacyConfiguration.php
- src/Glpi/Config/LegacyConfigurators/StandardIncludes.php
- src/Glpi/Console/Application.php
I refactored the  definition of the `$CFG_GLPI['root_doc']` configuration entry to :
1. in the web context, rely on the computation made by Symfony instead of our own logic;
2. move it in the `Config::loadLegacyConfiguration()` method to save a DB query when it has to be computed from the `url_base` configuration entry;
3. do it in a centralized method instead of doing it from 3 different places.
> Simplify `$CFG_GLPI['root_doc']` initialization

- CHANGELOG.md
- src/Glpi/Config/LegacyConfigurators/StandardIncludes.php
- src/Session.php
- tests/web/APIRest.php
1. Drop the `$_SESSION['glpiroot']` variable. The session cookie name is already generated using a hash of `$CFG_GLPI['root_doc']`. Therefore, the `$CFG_GLPI['root_doc'] != $_SESSION['glpiroot']` condition will always be `false`.
2. Drop useless call to `Toolbox::setDebugMode()`. Calling this method with no parameters has not any effect.
3. Drop unneeded initialization of `$_SESSION['glpilanguage']`. The same initialization is made in the `Session::loadLanguage()` method that will be anyway call a few lines later.
> Drop dead code executed during GLPI boot

- src/Glpi/Api/HL/Controller/AbstractController.php
- src/Glpi/Api/HL/Controller/AdministrationController.php
- src/Glpi/Api/HL/Controller/AssetController.php
- src/Glpi/Api/HL/Controller/ComponentController.php
- src/Glpi/Api/HL/RSQL/Error.php
- src/Glpi/Api/HL/RSQL/Parser.php
- src/Glpi/Api/HL/RSQL/Result.php
- src/Glpi/Api/HL/Search.php
- tests/functional/Glpi/Api/HL/RSQL/Parser.php
Instead of silently ignoring invalid RSQL filters, this PR causes a 400 response to be returned with details about the invalid filters. Previously, the search only errored from RSQL filters if the filter couldn't be tokenized.
The following cases are handled:
- Filter is on an unknown property
- Filter has an unknown operator
- Filter is for a mapped property (Since mappings are done after the query and there is nothing to reverse the mapping back to SQL criteria yet. For example, ticket status 1 is mapped to "New", but there isn't info to convert "New" to "_.status.id=1")
> [HLAPI] Fail search on invalid filters

- src/Session.php
- tests/functional/Session.php
A plugin I'm working on requires some actions to take place regardless of the current user's permissions and having a static property to indicate that right checks should be skipped seems like the best solution available at the moment.
> Add ability to bypass right checks

- phpunit/functional/Item_ProjectTest.php
- src/Appliance.php
- src/Certificate.php
- src/CommonDevice.php
- src/Computer.php
- src/DeviceCamera.php
- src/Html.php
- src/Item_Project.php
- src/Monitor.php
- src/NetworkEquipment.php
- src/Peripheral.php
- src/Phone.php
- src/Printer.php
- src/Project.php
- src/ProjectTask.php
- src/Software.php
- templates/components/datatable.html.twig
- templates/pages/tools/item_project.html.twig
- It fixes !35418
A “project” tab has been added to the objects page, featuring a dropdown with a button for linking a new project to the object, as well as a table of projects already associated with the object.
> Feat add project tab in asset

- .phpstan-baseline.php
- phpstan.neon.dist
- src/Glpi/Application/SystemConfigurator.php
- src/QueuedWebhook.php
- stubs/glpi_constants.php
- templates/pages/setup/webhook/queuedwebhook.html.twig
- templates/pages/setup/webhook/webhook.html.twig
Saving responses from webhooks isn't very useful except very rare cases where a service actually sends a response body and you want to view it for debug reasons. By default the ability to save webhook responses will be disabled except in development environments.
Need to make sure the `hookparser` plugin (also not useful for 90% of regular webhook use cases) can still access the responses regardless of this setting.
> Block saving webhook responses

- install/migrations/update_10.0.x_to_11.0.0/assets.php
- install/mysql/glpi-empty.sql
- src/Glpi/Asset/AssetDefinition.php
- src/Glpi/Asset/Capacity/HasImpactCapacity.php
- src/Glpi/Features/AssetImage.php
- src/Impact.php
- src/ImpactItem.php
- templates/pages/admin/customobjects/main.html.twig
- tests/functional/Glpi/Asset/Capacity/HasImpactCapacity.php
Adds ability to enabled impact graphs for custom asset types and specify the image to use in the graphs.
Also adds support for impact type pictures in the uploaded picture directory `files/_pictures` rather than just the `pics` folder or pictures provided through a PHP script.
> Add Impact Capacity

- .phpstan-baseline.php
- install/update.php
- phpstan.neon.dist
- src/DBConnection.php
- src/DBmysql.php
- src/Glpi/Application/View/Extension/FrontEndAssetsExtension.php
- src/Glpi/Console/AbstractCommand.php
- src/Glpi/Console/Application.php
- src/Glpi/System/Requirement/InstallationNotOverriden.php
- src/Plugin.php
- stubs/db_config_classes.php
This will permit to ensure that all usages of the `DB` and `DBSlave` classes are correctly detected as usages of the parent `DBmysql` class.
I also added a `|null` in the `@var` PHPDoc related to locations where the `global $DB` variable could be null (e.g. when installation is not yet done).
> Add stubs for DB config classes

- src/Domain_Item.php
- It fixes !35411
To remove a relationship between two items (e.g., Domain -> Computer), the system currently requires purge rights on the source item (Domain in this case). This behavior is problematic because granting purge rights not only allows the removal of relationships but also permits the deletion of items themselves. This creates a security concern when the intent is solely to manage relationships without affecting the items involved.
> Make Domain_Item purgeable with the delete right

- templates/pages/admin/form/access_control/direct_access.html.twig
- tests/cypress/e2e/form/access_policies/direct_access.cy.js
The configured token was lost each time the form was saved due to an input name property being incorrectly set.
You can see the issue here, the token value change every time the form is saved:
> Fix direct access token being regenerated accidentally

- phpunit/functional/TicketTest.php
- src/CommonITILObject.php
- src/ITILSubItemRights.php
- It fixes !34489
Added a new right so that I can see the private tasks assigned to my group even if I can't see the basic private tasks.
> Add new right : See private task assign to my group

- .phpstan-baseline.php
- phpunit/functional/Glpi/Inventory/Assets/ComputerTest.php
- phpunit/functional/Glpi/Inventory/Assets/NetworkEquipmentTest.php
- phpunit/functional/Glpi/Inventory/Assets/PrinterTest.php
- src/Glpi/Inventory/Asset/InventoryAsset.php
- src/Glpi/Inventory/Asset/InventoryNetworkPort.php
- src/Glpi/Inventory/Asset/NetworkPort.php
- src/Glpi/Inventory/Asset/Printer.php
- src/Glpi/Inventory/Inventory.php
- src/Glpi/Inventory/MainAsset/Computer.php
- src/Glpi/Inventory/MainAsset/GenericAsset.php
- src/Glpi/Inventory/MainAsset/MainAsset.php
- src/Glpi/Inventory/MainAsset/NetworkEquipment.php
- src/Glpi/Inventory/MainAsset/Phone.php
- src/Glpi/Inventory/MainAsset/Printer.php
- src/Glpi/Inventory/MainAsset/Unmanaged.php
- src/RuleImportAsset.php
- src/RuleImportAssetCollection.php
Main idea is to make distinction between simple asset and main assets (inventoriable ones).
Printer was a specific case because it can be either a MainAsset or a simple Asset. This is now handled from two distinct classes.
> Move MainAsset classes to their own directory

- js/modules/Dashboard/Dashboard.js
- tests/js/modules/Dashboard/Dashboard.test.js
Fix some dashboard options not working/not being saved.
Fixes #18545
As a note, at least some card types like multiple lines force the legend to show. Is this intended and the bug instead is that the option shows, or should it be an option for everything rather than forced?
> Fix dashboard options

- phpunit/functional/Group_UserTest.php
- src/Group_User.php
- src/User.php
- It fixes !35654
When you delete the link between a user and a group, if this group is the user's default group, it remains so even after the link has been deleted.
> Reset user default group when link between user and group is deleted

- src/Glpi/CustomObject/AbstractDefinition.php
- templates/pages/admin/customobjects/main.html.twig
Extracted from #18481.
1. The custom assets system name pattern does not accept underscores.
2. The regex was using `[A-Za-z]` ranges with the insensitive (`i`) flag, therefore, the `A-Z` uppercase range was useless.
> Fix custom asset system name pattern

- src/Glpi/Controller/Form/RendererController.php
- src/Glpi/Controller/Form/SubmitAnswerController.php
- src/Glpi/Form/AccessControl/FormAccessControlManager.php
- templates/pages/form_renderer.html.twig
- tests/cypress/e2e/form/access_policies/direct_access.cy.js
Two minor bugfixes for the forms feature.
1) Make sure only active forms can be answered.
2) The direct access token, which allow a form to be shared with a unique url like `http://localhost/Form/Render/526?token=xC4zlC6dOH6lCllLqjeMDMivmZNGPGx360AgIKWu`, needs to be included in the POSTed data when submitting answer as we obviously check it to make sure the user is allowed to answer the form.
> Make sure only active forms can be answered + include token in form

- css/includes/components/_utils.scss
- templates/layout/parts/page_header.html.twig
- templates/pages/helpdesk/index.html.twig
As a reminder, we changed the helpdesk UI a few month ago to force the "horizontal" layout and reduced the container for new pages like the home page or the service catalog:
This PR apply the same container to all the others helpdesk pages, for example here is the setting page before and after:
> Apply same container width for all helpdesk pages

- phpunit/functional/Glpi/Form/Destination/CommonITILField/EntityFieldTest.php
- src/Glpi/Form/Destination/CommonITILField/EntityField.php
- src/Glpi/Form/Destination/CommonITILField/EntityFieldStrategy.php
- tests/cypress/e2e/form/destination_config_fields/entity.cy.js
Added a new strategy `Active entity of the form filler` for `EntityField` form destination config.
This strategy retrieves the active entity of the user who filled in the form and applies it to the destination created.
> feat(forms): Add 'Active entity of the form filler' strategy for EntityField

- src/Glpi/Controller/ServiceCatalog/ItemsController.php
- templates/components/helpdesk_forms/service_catalog_items.html.twig
- templates/pages/self-service/service_catalog.html.twig
- tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
Show a message when a search do not return any results in the service catalog.
> Add an information message when the service catalog has no forms

- phpunit/functional/Glpi/Helpdesk/DefaultDataManagerTest.php
- src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php
- src/Glpi/Form/Destination/CommonITILField/ITILActorField.php
- src/Glpi/Form/Destination/CommonITILField/ValidationField.php
Some config fields were wrongly initialized, which prevented their default values from being applied properly.
This prevented some fields like the requester from being correctly set when using the default forms.
> Fix wrongly initiliazed destination config fields

- src/Glpi/Form/Category.php
- src/Glpi/Form/Form.php
- src/Glpi/UI/IllustrationManager.php
- src/autoload/CFG_GLPI.php
- templates/dropdown_form.html.twig
I forgot to apply the new `illustrationField` to the categories in #18565.
I've also added a new `$CFG_GLPI['default_illustration']` config entry to easily update the default illustration later on.
> Add illustration picker for service catalog categories

- phpunit/functional/SearchTest.php
- src/ITILCategory.php
Fixes #18333
These options use `count` datatype which results in an aggregate COUNT function being used so the criteria must use `HAVING`.
> Fix "Number of" search options for ITIL Categories

- css/includes/_base.scss
The `&` selector is not valid at root level. With `scssphp` v1.x, it is replaced by an empty value, making the resulting CSS valid, but with `scssphp` v2, it causes the following issue:
```
[ScssPhp\ScssPhp\Exception\SimpleSassException]               
Top-level selectors may not contain the parent selector "&".  
,                                                         
402 | &:-webkit-autofill {                                    
| ^                                                       
'                                                         
css/includes/_base.scss 402:1  root stylesheet        
```
> Fix invalid CSS selector

- front/change_supplier.form.php
- front/change_user.form.php
- front/displaypreference.form.php
- front/documenttype.list.php
- front/domainrecord.form.php
- front/group.form.php
- front/knowbaseitem.form.php
- front/massiveaction.php
- front/networkalias.form.php
- front/notification.tags.php
- front/problem_supplier.form.php
- front/problem_user.form.php
- front/project.form.php
- front/projecttask.form.php
- front/rule.test.php
- front/rulesengine.test.php
- front/supplier_ticket.form.php
- front/ticket_user.form.php
- src/Html.php
`Html::popHeader()`'s second argument `$url` is not used, but it was still receiving `$_SERVER['PHP_SELF']` in many places.
> Remove unused second argument when calling Html::popHeader

- .phpstan-baseline.php
- js/modules/Forms/RendererController.js
- phpunit/functional/Glpi/Helpdesk/DefaultDataManagerTest.php
- src/Glpi/Controller/Form/SubmitAnswerController.php
- src/Glpi/Form/AnswersHandler/AnswersHandler.php
- src/Glpi/Form/AnswersSet.php
- src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
- src/Glpi/Form/EndUserInputNameProvider.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
- tests/cypress/e2e/form/service_catalog/default_forms.cy.js
- tests/cypress/support/commands.js
Need #18601 to be merged first.
> Fix multiple issues while submitting helpdesk forms

- phpunit/functional/TicketTest.php
- src/CommonITILObject.php
- src/Ticket.php
Fixes #18016
When creating a ticket, the status field gets populated before actors are handled. Because of that, the `canAssign` check will fail because you aren't supposed to be able to assign technicians **after** the ticket is closed. The check now ignores the status if it is a new Ticket.
> Allow assigning users while creating a closed ticket

- dependency_injection/legacyConfigProviders.php
- src/Glpi/Http/Listener/SessionVariables.php
- src/Glpi/Kernel/ListenersPriority.php
- src/Session.php
- tests/functional/Session.php
> Make SessionConfig an http listener instead of just legacy provider

- src/Glpi/Config/LegacyConfigurators/ConfigRest.php
- src/Glpi/Http/Listener/SessionVariables.php
---
Note: when #18589 will be merged, this PR will have to remove "ConfigRest" too
> Extract session entities force loading out its own listener

- src/Glpi/Controller/NeedsUpdateController.php
1. Do not check require the user to be connected during the update process. This check was resulting in an infinite redirection loop when an update was required.
2. Remove useless unresolvable parameter. It fixes the following error: 
```Could not resolve argument $key of "Glpi\Controller\NeedsUpdateController::__invoke()", maybe you forgot to register the controller as a service or missed tagging it with the "controller.service_arguments"?```
> Fix update controller

- js/modules/Forms/RendererController.js
- src/Glpi/Controller/Form/RendererController.php
- templates/pages/form_renderer.html.twig
Add two possible actions after a form is successfully submitted:
* Go back to service catalog
* See my tickets
An other alternative would be to replace "See my tickets" by a direct link to the created ticket (and remove the success toast that currently serve that purpose).
We would have to think about the cases where multiple tickets might be created tho, in this case maybe a link to a search request that returns all the newly created ticket (id=x or id=y or ...) ?
What do you think @orthagh ?
> Display some actions after a form is submitted

- phpunit/functional/HtmlTest.php
- src/Glpi/Controller/Form/RendererController.php
- src/Glpi/Controller/ServiceCatalog/IndexController.php
- src/Glpi/Form/ServiceCatalog/ServiceCatalog.php
- src/Html.php
- tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
- tests/cypress/support/commands.d.ts
- tests/cypress/support/commands.js
Add a menu entry for the service catalog on the central interface and update the various controllers to make sure central user are allowed to use this page.
> Allow central users to use the service catalog

- front/documenttype.list.php
- src/Infocom.php
- src/KnowbaseItem.php
1. `target` param value seems to have no effect in the `Search::showList()` method.
2. `infocoms-show` is not referenced anywhere in the code, therefore the `!strpos($_SERVER['PHP_SELF'], "infocoms-show")` check is probably useless.
1. `target` param value seems to have no effect in the `KnowbaseItem::showList()` method.
> Remove useless usages of `$_SERVER['PHP_SELF']`

- js/modules/Forms/RendererController.js
Tests on main seems to be failing (we merged a lot of things at once recently, probably some unseen conflict).
It seems to come from the fact that the `tinymce` variable is now only defined if there is at least one editor on a page, unsure why.
> Fix failing tests

- templates/components/form/pictures.html.twig
- templates/generic_show_form.html.twig
Moves the asset QR code into the sidebar where asset pictures are shown and no longer shows the QR code field when creating new items.
Replaces #18494
Fixes #18493
Fixes #18670
Asset with model pictures:
Asset without model pictures:
> Move QR code to 3rd column

- .phpstan-baseline.php
- phpunit/functional/ToolboxTest.php
- src/Toolbox.php
The logic stays the same, code is just a bit cleaned up (early returns, merging `if` cascades, etc.).
The goal of this is to clean up all the calls to `Toolbox::manageRedirect()` (there are only 4 calls in the project itself, I don't know about plugins though) so that it no longer needs to throw an exception and instead just allows retrieving the URL to return a RedirectResponse.
> Extract URL checks from Toolbox::manageRedirect() to a new method

- src/Config.php
- src/Impact.php
This change permits to save either 1 or 3 queries when displaying any item form :
- 1 query, from `CommonGLPI::defineTabs() -> CommonGLPI::addImpactTab() -> Impact::isEnabled() -> Impact::getEnabledItemtypes()` (`src/CommonGLPI.php` line 392)
- 1 query when impact tab is registered, from `Impact::getTabNameForItem() -> Impact::isEnabled() -> Impact::getEnabledItemtypes()` (`src/Impact.php` line 97)
- 1 query when impact tab is registered, from `Impact::getTabNameForItem() -> Impact::getEnabledItemtypes()` (`src/Impact.php` line 129)
> Get enabled impact itemtypes from `$CFG_GLPI`

- phpunit/functional/PlanningTest.php
- src/Planning.php
Fixes #17385
I think this is mostly an issue with the Full Calendar library, but this PR will force the `allDay` flag to be true when an event starts at midnight and the duration is an entire day(s). Events that last all day (recurring or not) will now show up in the All Day section when appropriate.
> Force allDay planning flag when start at midnight and last entire day(s)

- CHANGELOG.md
- phpunit/functional/InfocomTest.php
- src/Infocom.php
Fixes #17408
If an item is deleted when the warranty expiration automatic action is run, there will not be a notification triggered for it. There will also not be an Alert created for it (unless the warranty has reached its expiration) so that if the item is restored, warranty alerts can be triggered.
> Do not trigger warranty alerts on deleted items

- CHANGELOG.md
- src/Glpi/Application/ErrorHandler.php
- src/Glpi/Application/View/TemplateRenderer.php
Exception that are not specifically caught are now resulting in a clean error page. It s no longuer necessary to catch Twig exception to prevent having a "blank error page". Also, the rendering will be more appropriate when the error prevent the whole page to be rendered.
Before:
After:
> Do not catch Twig exceptions anymore

- .phpstan-baseline.php
- CHANGELOG.md
- phpstan.neon.dist
- phpunit/GLPITestCase.php
- phpunit/functional/DBTest.php
- phpunit/functional/DBmysqlIteratorTest.php
- phpunit/functional/SearchTest.php
- src/DBmysql.php
- src/DBmysqlIterator.php
- src/GLPI.php
- src/Glpi/Application/ErrorHandler.php
- src/Toolbox.php
- stubs/glpi_constants.php
- tests/GLPITestCase.php
Since #18151, only SQL warnings and SQL debug information are logged in the `sql-errors.log`.
Having several handlers makes it more complicated to modify our error handling system to make it fully compliant with the Symfony error handling. Indeed, the Symfony system expects that only one error logger exists. It is still possible to have multiple log files, but this should be achieved using one logger with multiple handlers, instead of having multiple loggers with one handler for each, see https://symfony.com/doc/6.4/logging/channels_handlers.html.
I do not think it is really necessary to split our log files, so I propose to just trigger a PHP Warning when a query triggers SQL warnings, in order to make this error handled the same way as any other PHP error.
Also, I removed the `$debug` …
> Remove the specific SQL error logger

- src/Glpi/Dashboard/Grid.php
- src/Html.php
- tests/cypress/e2e/dashboards.cy.js
- tests/cypress/e2e/search/display_preferences.cy.js
On `main`, sometimes dashboards are not loading and the `GLPIDashboard` JS global is undefined at the time the constructor tries being called. Added bare-minimum E2E test to check that dashboards are loading on each of the 4 included dashboard locations.
> Fix dashboard class undefined

- src/Glpi/Agent/Communication/AbstractRequest.php
The  `ErrorHandler::handleError()` is not supposed to be called manually. It cannot be made `private` because it is used as a callback by `set_error_handler`.
> Use `trigger_error()` instead of a direct call to the error handler

- phpunit/functional/NotificationAjaxSettingTest.php
- phpunit/functional/NotificationMailingSettingTest.php
- phpunit/functional/NotificationSettingConfigTest.php
- src/NotificationAjaxSetting.php
- src/NotificationMailingSetting.php
- templates/pages/setup/setup_notifications.html.twig
Replace "followup" with "notification" in the notification settings labels to make them more accurate since they are related to the sending of notifications and not related to Followups.
> Replace followup with notification in some labels

- composer.json
I am not sure there is any use for the `test*` composer scripts anymore. The tests would probably always fail since they expect a clean GLPI installation. I left the code standards and lint scripts since they should still be OK to run outside of a container.
`tests/run_tests.php` should be used to run tests in a containerized environment.
> Remove test composer scripts

- .phpstan-baseline.php
- src/Glpi/Kernel/ListenersPriority.php
- src/Plugin.php
Prevent error message :
```
glpiphplog.CRITICAL: Uncaught Error: Call to a member function addTranslationFile() on null {"exception":"[object] (Error(code: 0): Call to a member function addTranslationFile() on null at .../src/Plugin.php:480)"} 
glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function addTranslationFile() on null in .../src/Plugin.php at line 480
Backtrace :
src/Plugin.php:1710                                Plugin::loadLang()
src/Plugin.php:557                                 Plugin->getInformationsFromDirectory()
src/Plugin.php:606                                 Plugin->getPluginInformation()
src/Plugin.php:545                                 Plugin->checkPluginState()
src/Plugin.php:294 …
```
> Fix plugin tranlations loading

- templates/components/itilobject/timeline/timeline.html.twig
If we want to use the pre_item_form hook for a validation request, GLPI does not pass the subitem to the Twig template during the timeline rendering.
If the subitem is not passed, the item is empty in the hook, making it impossible to use the data.
**Solution**: Add the subitem to the include of the item type template.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1208836526605807
> TicketValidation pre_item_form hook

- .phpstan-baseline.php
- install/migrations/update_10.0.x_to_11.0.0/form.php
This code was supposed to help developers work on different versions of the native forms feature without resetting their database too often.
In the end we still reset our databases all the time and this become more work to maintain when adding new feature so we should probably drop it now even if the database schema is not yet final for this feature.
> Drop temporary migration code

- phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
- src/Glpi/Form/Export/Serializer/FormSerializer.php
- src/Glpi/Form/Export/Specification/FormContentSpecification.php
- src/Glpi/Form/Export/Specification/SectionContentSpecification.php
- tests/fixtures/export-of-2-forms.json
Currently, form information relating to the service catalog is not exported and imported by the current system.
> feat(forms): Add export and import functionality for service catalog configuration

- src/DBmysql.php
Prevent this type of error with a PHPStan analysis at level 5 in plugins:
`Parameter #1 $tableorsql of method DBmysql::request() expects array<string>|QueryUnion|string, array<string, array<string, mixed>|string> given.`
> fix: PHPDoc for request()

- CHANGELOG.md
- ajax/timeline.php
- front/commonitiltask.form.php
- front/itilfollowup.form.php
- front/ticket.form.php
- src/CommonITILObject.php
- src/Glpi/Controller/Knowbase/KnowbaseItemController.php
- src/ITILSolution.php
- src/KnowbaseItem.php
- src/Ticket.php
- templates/components/itilobject/answer.html.twig
- templates/components/itilobject/footer.html.twig
- templates/components/itilobject/timeline/form_followup.html.twig
- templates/components/itilobject/timeline/form_solution.html.twig
- templates/components/itilobject/timeline/form_task_main_form.html.twig
- templates/components/pager.html.twig
- templates/pages/tools/search_solution.twig
- tests/cypress/e2e/ITILObject/ticket_form.cy.js
When using object locks, there was an opportunity for a technician to lose the lock on a ticket when searching for a solution because the process redirects out of the ticket for the solution search/selection part.
This PR moves the solution selection to a modal and allows adding the article content directly to the solution content without any redirects/page reloads.
Fixes #18490
> Streamline search for solution process

- ajax/dropdownAllItems.php
- js/modules/Forms/EditorController.js
- js/modules/Forms/QuestionItem.js
- src/Glpi/Form/QuestionType/AbstractQuestionType.php
- src/Glpi/Form/QuestionType/QuestionTypeInterface.php
- src/Glpi/Form/QuestionType/QuestionTypeItem.php
- templates/pages/admin/form/form_editor.html.twig
- templates/pages/admin/form/form_question.html.twig
- tests/cypress/e2e/form/destination_config_fields/itilcategory.cy.js
- tests/cypress/e2e/form/question_types/item.cy.js
The itemtype selection field for Item questions (Glpi Objects and Dropdowns) has been moved to the question type selection field, so that only the object selection field is in the default value area.
This arrangement is all the more logical as it is not possible to define an item type question without defining an itemtype; it will not be displayed in the final form. This new interface approach forces the user to select an itemtype by default.
PR #18354 introduces some interface modifications to the question type selection fields, notably by grouping them together. It will be important to do the same with this new field once the PR has been merged.
> feat(forms): Move the itemtype config field for QuestionTypeItem

- phpunit/functional/Glpi/Inventory/Assets/NetworkEquipmentTest.php
- src/Inventory/Asset/NetworkPort.php
- tests/fixtures/inventories/extreme_3650GTS.xml
- It fixes https://github.com/glpi-project/glpi-inventory-plugin/issues/591
The change makes the regex more flexible by allowing the switch number and port number to be extracted even if the network port name does not contain any text (ie: `Gi0/0/1`)  before the switch number. 
This is particularly useful in configurations where some ports are named only by their number (`1/1`, `2/3`, etc.) without a prefix (like Extreme Networks).
> fix(Inventory): correctly handle Extreme Networks stacked switch

- src/Html.php
htmlescape() which breaks urls, The '&' were replaced with html entities which breaks url parameters
- It fixes #18680
> fix broken tooltip when loading a ticket preview (ticket listing)

- src/NotificationEventMailing.php
Since the replacement of ```htmlawed```
the ```symfony``` component used to make HTML ```safe``` encodes ```=``` with ```&#61;```
```
<a href="/front/document.send.php?docid&#61;9122&amp;itemtype&#61;Ticket&amp;items_id&#61;38142" target="_blank" rel="noopener"><img src="/front/document.send.php?docid&#61;9122&amp;itemtype&#61;Ticket&amp;items_id&#61;38142" alt="d40c9e53-f37490bd-63ec57f1a8efc3.58665698" width="4032" /></a>
```
GLPI's notification system tries to convert relative URLs into absolute URLs via a ```reg_replace```
```php
foreach ($inline_docs as $docID => $filename) {
$current->fields['body_html'] = preg_replace(
[
'/src=["\'][^"\']*document\.send\.php\?docid=' . $docID . '(&[^"\']+)?["\']/',
'/href=["\'][^"\']*document\.send\.php\?docid=' . $docID . '(&[^"\']+)?["\']/',
],
[ …
```
> fix(Notification): fix conversion of relative URLs to aboslue URLs

- phpunit/functional/LockedfieldTest.php
- src/Lockedfield.php
GLPI does not respect the current user's permissions when deleting (purging) a `LockedField`.
This allows a `LockedField` linked to an object from another entity to be deleted.
I am also questioning the handling of `global` `LockedFields`.
Currently, anyone with the `UPDATE` permission can delete a global lock  (with or without this `PR`), regardless of the entity, as the `LockedField` object does not include an `entities_id`.
- It fixes !35279
> Fix(LockedField): prevent purge of lockedField without authorization on the linked object entity

- js/modules/Search/Table.js
- It fixes !35211
Perhaps an alternative to https://github.com/glpi-project/glpi/pull/18376. 
After further review, I believe the issue here is that the saved search system expects the user to execute a search based on their criteria at least once (to include them in the URL).
See `GenericView.js L102`
```js
const bs_modal = new bootstrap.Modal(modal.get(0), {show: false});
modal.on('show.bs.modal', () => {
const params = JSON.parse(modal.attr('data-params'));
params['url'] = window.location.pathname + window.location.search;
modal.find('.modal-body').load(CFG_GLPI.root_doc + '/ajax/savedsearch.php', params);
});
```
If the user does not execute a search at least once, the default search for the item type is used and saved in the database. …
> Fix(SavedSearch): Force user to validate criteria before saved search

- phpunit/functional/Glpi/Inventory/Assets/NetworkEquipmentTest.php
- src/Inventory/Asset/InventoryNetworkPort.php
- It fixes !35403
An asset can be added manually to GLPI with a `NetworkPortAggregate` for managing network ports.
Typically, assets are added through the SNMP discovery process, which creates a `NetworkPortAggregate` with `is_dynamic = 1`. However, in some cases, GLPI administrators may prefer to skip the discovery phase and directly perform an SNMP inventory.
GLPI supports this approach by allowing the manual addition of assets with dedicated `NetworkPortAggregate` entries, enabling compatibility with the SNMP inventory task.
Currently, during the SNMP inventory process, GLPI only compares and updates entries where `is_dynamic = 1`. This limitation prevents the system from updating manually added `NetworkPortAggregate` entries (`is_dynamic …
> Fix networkport inventory

- phpunit/functional/Glpi/Inventory/Assets/SoftwareTest.php
- src/Inventory/Asset/Software.php
- It fixes !35300
Currently, the software inventory does not take into account the `is_helpdesk_visible` option in GLPI's general configuration.
This option is now managed both during the creation of the software and when it is updated.
I took the opportunity in this PR to simplify the code with a dedicated function (We may have other cases to handle in the future)
> Fix(Inventory): take car of 'default_software_helpdesk_visible' from software inventory

- phpunit/functional/ProjectTaskTest.php
- src/ProjectTask.php
When a project is created from a template containing tasks with assigned actors,
the created project does contain the tasks, but they no longer have actors.
| Fixed tickets | !30072
> Fix(ProjectTask): keep PojectTaskTeam when use a template

- src/Webhook.php
- Bypass user permission checks when webhooks fetch data from the new API.
- ~~Abort the session in the `/front/cron.php` endpoint and then make all entities active. The session may need to be initialized, but I don't know a reason for it to ever be saved so `session_abort` makes sense even without the entity changes being done here.~~
> Fix webhook execution permissions in cron context

- phpunit/functional/PendingReasonTest.php
- src/NotificationTargetCommonITILObject.php
- src/PendingReasonCron.php
- src/PendingReason_Item.php
Fixes !34694
Add ITIL notification events for:
- Adding pending reason to ITIL item
- Removing pending reason from ITIL item
- ITIL item closed automatically from pending reason
The following event already existed:
- Automatic reminder
> Add pending reason notification events

- CHANGELOG.md
- phpunit/functional/TicketValidationTest.php
- src/CommonITILObject.php
- src/CommonITILValidation.php
- src/Ticket.php
While working on #17215, I noticed one place where the search result link for tickets waiting for approval filtered to unsolved tickets only. Some of the issue reported in the bug report was fixed in #18380 but there was still an inconsistency. Instead of hiding the ability to validate closed tickets only, it seems like it makes sense to also block validating solved tickets and changes. Once something is solved, all actions should be considered finished so approvals are expected to happen before that. Once solved, it is just waiting for user validation that the fix worked or validation from technicians in the case of an Observed change.
> Allow validating only unsolved ITIL

- templates/pages/tools/kb/knowbaseitem.html.twig
Prevent error message:
```
glpiphplog.INFO:   *** PHP User deprecated function (16384): Usage of `$link` parameter is deprecated. See `DbUtils::getUserName()`. in .../src/Toolbox.php at line 411
Backtrace :
src/Toolbox.php:411                                trigger_error()
src/autoload/dbutils-aliases.php:477               Toolbox::deprecated()
:                                                  getUserName()
.../Application/View/Extension/PhpExtension.php:91 call_user_func_array()
...tes/c7/c72b5b27661bd718f1e6bba6e8d1e266.php:135 Glpi\Application\View\Extension\PhpExtension->call()
vendor/twig/twig/src/Template.php:431              __TwigTemplate_3ff457c41796e09aa1e3b83ed2b25246->block_form_fields() …
```
> fix(knowbase): Usage of $link parameter is deprecated

- CHANGELOG.md
- phpunit/functional/UserTest.php
- src/User.php
Add a massive action which allows re-processing authorization assignment rules for users.
While these rules run when the user logs in, there are cases where you may want any changes to take effect immediately or cases where the user isn't allowed to log in at all (See Deny Login rule action).
I've seen people perform a workaround by messing with the user's authentication source/forcing a synchronization. Having a dedicated action would be safer and more intuitive.
> Add action to reapply Authorization Assignment Rules

- src/Glpi/Form/Question.php
- tests/cypress/e2e/form/form_editor_horizontal_layout.cy.js
- tests/cypress/support/commands/form.js
Fixed a bug that prevented you from effectively deleting a horizontal layout.
Currently, if you have a form with questions in a horizontal layout container, and you delete this layout then save and reload the form, you get this rendering:
> fix(forms): Cannot remove a horizontal layout

- src/Config.php
- templates/pages/setup/general/api_apiclients_section.html.twig
Hide the API Client config section in Setup > General > API tab if the legacy API is disabled and also change the section header to specify that these clients are for the legacy API only. Hopefully this helps reduce confusion with having two different APIs and different authentication methods.
> Enhance legacy api client config

- CHANGELOG.md
- phpunit/functional/ProjectTest.php
- src/Glpi/Search/Provider/SQLProvider.php
- src/Project.php
- src/ProjectTask.php
Remove hidden restriction when searching project tasks that only allowed assigned tasks to be visible. Now, it can show all tasks that the user has access to see.
The "My tasks" button shown on project pages now explicitly loads the search results with the task team criteria that used to be hidden.
This PR also means that the legacy API will now allow searching all project tasks, not just the assigned ones.
> Remove ProjectTask search restriction

- lib/bundles/gridstack.js
- src/Html.php
Reported by @Otijom 
It fixes
In main only, probably since the migration on [gridstack v8](https://github.com/gridstack/gridstack.js/blob/master/README.md#migrating-to-v8) (we are on v11 currently)
> CSS rules removed .grid-stack prefix for anything already gs based, 12 column (default) now uses .gs-12, extra.css is less than 1/4th it original size!, gs-min|max_w|h attribute no longer written (but read)
> include gridstack extra css

- js/modules/ProgressBar.js
- src/Glpi/Controller/ProgressController.php
The `/progress/check` endpoint is a read-only endpoint. It should use the `GET` method.
> Use GET method to read install progress

- src/NetworkPortMetrics.php
I noticed that the `CSS` applied to the `GLPI Dashboard` was not applied in the `NetworkPortMetric`, this PR fixes that
`GLPI Dashboard` :
`NetworkPortMetric` : 
`After` :
Don't worry about the data, I used the script `php tools/fake_metrics.php`.
> fix(NetowkrPortMetric): fix CSS

- phpunit/functional/RuleAssetTest.php
- src/CommonDBTM.php
- It fixes !35995
The rule engine doesn't seem to take the following rule into account when it's defined on a sub-entity.
When this rule is set on a root entity with recursion enabled, it's fine, but not when it's set only on a sub-entity.
> Fix non functional rule under sub entity

- js/modules/GlpiInstall.js
- js/modules/ObjectLock.js
- src/Glpi/Controller/ApiController.php
- src/Glpi/Controller/ApiRestController.php
- src/Glpi/Controller/IndexController.php
- src/Glpi/Controller/InventoryController.php
- src/Glpi/Http/Listener/CatchInventoryAgentRequestListener.php
- src/Glpi/Http/Listener/CheckCsrfListener.php
- src/Glpi/Kernel/ListenersPriority.php
- src/Glpi/Security/Attribute/DisableCsrfChecks.php
- tests/cypress/support/commands.js
GLPI has currently a distinct CSRF check logic for AJAX endpoint. Indeed, for these specific endpoints, a CSRF token can be consumed multiple times, see 93750ead9b827637198d17deb6391a7841ed3232
The propose change permits to consider that a request is an AJAX request when the `X-Requested-With: XMLHttpRequest` is used (it is commonly used as a flag to mark AJAX requests by the popular JS frameworks), instead of checking tha the request is made on a `/ajax/xxx` path.
The idea is to permit to use any URL pattern for AJAX endpoints.
> Enhance CSRF handling

- CHANGELOG.md
- front/item_device.common.form.php
- front/item_device.php
- front/knowbaseitem.php
- front/updatepassword.php
- src/CommonDBTM.php
- src/Glpi/Controller/LegacyFileLoadController.php
- src/Glpi/Http/Listener/AccessErrorListener.php
- src/Glpi/Http/Listener/LegacyPostRequestActionsListener.php
- src/Html.php
- src/Session.php
When a `AccessDeniedHttpException` is thrown, if the user is not authenticated, then it is automatically redirected to the login form. It permits to remove all manual calls to `Session::redirectIfNotLoggedIn()` and `Session::redirectToLogin()` and to reuse, for this behaviour, the redirection already existing in the `AccessErrorListener`.
> Simplify the redirection to login form related code

- phpunit/functional/Glpi/Http/FirewallTest.php
- src/Glpi/Http/Firewall.php
- src/Glpi/Http/LegacyRouterTrait.php
- tests/functional/Glpi/Http/Listener/LegacyRouterListener.php
In GLPI 11.0, a request to `/plugins/myplugin/myscript.php` should serve the `/plugins/myplugin/public/myscript.php` file and the default firewall strategy should be the same as any other legacy PHP script of the plugin.
This PR:
- fixes the default strategy applied to `/public/*.php` scripts,
- handles URLs explicitely containing the `/public` path, but triggers a deprecation indicating that `/public` should not be present in the URL (URL `/plugins/myplugin/public/myscript.php` shoudl be replaced by `/plugins/myplugin/myscript.php`).
> Fix routing of plugins public PHP scripts

- CHANGELOG.md
- src/Appliance.php
These two actions are never added to any itemtypes because `Appliance::getMassiveActionsForItemtype` isn't called from anywhere. Instead, `CommonDBTM` already adds the "Associate to an appliance" action to the itemtypes that can be linked to an Appliance.
> Remove unused appliance massive actions

- src/Dashboard/Grid.php
- It fixes !36055
A single quotation mark in the name truncated it in the edit field
Before:
After:
> fix(dashboard): name with quotes

- css/includes/components/_utils.scss
- js/modules/IllustrationPicker/Controller.js
- src/Ajax.php
- src/Glpi/Dashboard/Grid.php
- src/Impact.php
- templates/central/widget_tab.html.twig
- templates/components/form/inventory_info.html.twig
- templates/components/illustration/icon_picker_modal.html.twig
- templates/components/illustration/icon_picker_search_results.html.twig
- templates/components/itilobject/actors/field.html.twig
- templates/components/itilobject/timeline/timeline.html.twig
- templates/components/search/criteria_filter_actions.html.twig
- templates/layout/parts/saved_searches.html.twig
Remove uses of `fa-spin` and any FA icons used for spinning loading indicators with Tabler style loaders.
In general spinners are now spans with `spinner-border` classes. The only exception is in the inventory information section of an asset since they were rotating sync/refresh icons. For those, `fa-spin` was replaced with `icon-rotate` from Tabler.
> Standardize loading spinners

- .phpstan-baseline.php
- src/CommonDBTM.php
https://github.com/pluginsGLPI/uninstall/pull/130
Exemple from Uninstall plugin : 
Got this phpstan5 error :
> Fix CommonDBTM input const type to allow false value for phpstan

- .phpstan-baseline.php
- stubs/glpi_constants.php
While working on #18790, I had to add new errors in the PHPStan baseline due to default `null` values of our constants stubs.
1. They are often incompatible with the expected values. Using an expected value fixes issues like `Default value of the parameter #10 $config_dir (null) of method DBConnection::createMainConfig() is incompatible with type string.`.
2. Always using the same value make PHPStan unhappy when it finds a comparison operation based on the contant value. Using a random but still valid value fixes issues like `Strict comparison using !== between null and 'development' will always evaluate to true.`.
> Add meaningful/random default values for global constants stubs

- phpunit/functional/RuleTicketTest.php
- phpunit/functional/TicketTest.php
- src/CommonITILObject.php
- src/Features/ParentStatus.php
- It fixes !35867
When I have a rule that adds a follow-up template and changes the status, the status defined by my rule is overridden by the default status when a follow-up is added. This creates an inconsistency between the ticket created and the rule supposed to modify it.
> Fix parent status overhide with rule using followup template action and status

- CHANGELOG.md
- src/RuleMailCollector.php
Based on discussion in #18783 and on the forum, the labels for the From and To mail collector rule criteria could cause confusion as they reference the headers but they instead have always been just the actual email address part of the header. The optional name part, was never passed to the rule engine.
> Rename To and From mailcollector rule criteria

- .github/actions/test_tests-cache.sh
- .github/actions/test_tests-imap.sh
- .github/actions/test_tests-ldap.sh
- .github/actions/test_tests-phpunit.sh
- .github/workflows/coverage.yml
- .gitignore
- phpunit.xml.dist
IMHO, cache, IMAP and LDAP test suites should be considered as integration tests and should probably not be used to evaluate the code coverage. Indeed, they are not supposed to cover all use cases in all involved methods, and this should be done in the `phpunit/functional` test suite, using mocked connections instead of real remote services.
I also removed the code coverage in the remaining `atoum` tests, to be able to use `pcov` that is faster than `xdebug`.
> Limit code coverage to PHPUnit unit/functional tests

- CHANGELOG.md
- src/CommonITILObject.php
- src/Glpi/Plugin/Hooks.php
- src/Plugin.php
Fixes #18580.
Renames `show_in_timeline` plugin hook to `timeline_items` as this hook is not used to directly show anything in the timeline. Instead, it is used to modify the array of items in the timeline. The old hook name was causing confusion even among GLPI developers.
> Rename timeline items hook

- phpunit/abstracts/CommonITILRecurrentTest.php
The `testComputeNextCreationDate` test will often fail when executed at specific hours during the night (which often happens for @cconard96 as he is on a different timezone).
These changes makes the test deterministic and it should now always behave the same regardless of the current date (which is clearly something we want, if a specific date is problematic it should explicitly be added into the test suite and we should not have to wait for someone to trigger the CI at the right time to discover it).
Note: it does not fix the computation itself, someone else could look for it but it isn't high priority for now.
> Fix random failures on testComputeNextCreationDate

- src/Ajax.php
Same as #18830 but targeted to ``main`` branch and following @cconard96 advices.
When acessing the "Task executions" tab of GLPI Inventory plug-in, the spinner wasn't horizontally center aligned:
This fix attempts to horizontally aligns the AJAX spinner:
> Align AJAX tab loading spinner to center

- .github/workflows/ci.yml
Try to terminate E2E CI tests if they run for more than an hour.
Haven't solved the various issues that seem to be causing the 6 hour stalled E2E tests in #18577, but if this is going to be more common we should have some kind of reliable timeout set for the CI.
> Add timeout for E2E CI

- ajax/asset/assetdefinition.php
- ajax/asset/customfield.php
- js/src/vue/CustomObject/FieldPreview/Field.vue
- js/src/vue/CustomObject/FieldPreview/FieldDisplay.vue
- js/src/vue/CustomObject/FieldPreview/Sidebar.vue
- src/Glpi/Asset/AssetDefinition.php
- templates/pages/admin/assetdefinition/fields_display.html.twig
- templates/pages/assets/customfield.html.twig
- tests/cypress/e2e/Asset/custom_fields.cy.js
- tests/cypress/support/commands.js
> Custom asset field editor ux redesign

- js/planning.js
- src/CommonITILTask.php
- src/Glpi/Features/PlanningEvent.php
- src/Planning.php
- src/ProjectTask.php
- templates/pages/assistance/planning/single_filter.html.twig
Add a planning filter to display events/tasks that are done.
Basically replace the 'display_done_event' option, which currently is applied when using the month view, by a new filter that can be toggled.
> Add planning filter to filter done events

- js/modules/Helpdesk/HelpdeskConfigController.js
- src/Glpi/Controller/Config/Helpdesk/DeleteTileController.php
- src/Glpi/Controller/Config/Helpdesk/SetTilesOrderController.php
No longer needed after #18723.
> Remove /ajax prefix used in new form controllers

- inc/based_config.php
- phpunit/bootstrap.php
- phpunit/functional/ToolboxTest.php
- src/System/Status/StatusChecker.php
- tests/bootstrap.php
The `cas_host` configuration corresponds to the CAS server hostname. It must be prefixed by `https://` to build a valid URL.
It fixes #18346.
I cannot test against a real CAS server, so I cannot validate the rest of the status checking logic.
> Fix CAS server status check

- src/Html.php
When clicking on "Copy to clipboard" button when Debug mode is enabled, an error is thrown because the function "copyTextToClipboard" doesn't exist. I believe other UI parts apart of Debug mode also uses this functionality.
> Fix "Copy to clipboard"

- src/NotificationTarget.php
When plugins restrict notification tag to specific plugin's events it show a php warning
`glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "plugin_*****" in src/NotificationTarget.php at line 1474`
Using `getAllEvents()` insted of `getEvents()` prevent the warning and make it work fine
> Allow plugins to restrict their tags to specific events

- js/planning.js
- It fixes !30072
With Chrome or Edge, the planning widget in the personal view is displayed on top of the other elements. This is not the case with Firefox.
See: https://github.com/glpi-project/glpi/pull/17274
> fix(central): planning widget rendering

- .phpstan-baseline.php
- phpunit/functional/Glpi/Asset/AssetDefinitionManagerTest.php
- phpunit/functional/Glpi/Asset/AssetDefinitionTest.php
- phpunit/functional/Glpi/Dropdown/DropdownDefinitionManagerTest.php
- phpunit/functional/Glpi/Dropdown/DropdownDefinitionTest.php
- src/Glpi/Asset/AssetDefinitionManager.php
- src/Glpi/CustomObject/AbstractDefinition.php
- src/Glpi/Dropdown/DropdownDefinitionManager.php
- src/Glpi/Search/Provider/SQLProvider.php
- templates/pages/admin/customobjects/main.html.twig
People may want to use numbers in custom assets system names. Prior to GLPI 9.4, it was possible to use classnames with numbers in the search engine, for instance via the genericobject plugin. This possibility disappeared when the search engine was refactored, and we did not reverted this limitation because the issue was detected only after the GLPI 9.4.0 release (see https://github.com/glpi-project/glpi/pull/5495).
I think we could reintroduce the possibility to use numbers in itemtypes. The search engine has many test and some of them will probably fail if an unexpected side effect is introduced by this change.
> Allow numbers in custom objects system names

- js/dashboard.js
- src/Dashboard/Grid.php
Depending on the Dashboard width it overlaps the select dropdown arrow.
After this PR, the select width is based on selected option width, respecting "min-width" CSS attribute:
> Auto resize dashboard selector

- css/legacy/includes/_styles.scss
- js/clipboard.js
- src/Dashboard/Grid.php
- src/User.php
- templates/pages/setup/apiclient.html.twig
URL: https://glpi.example.com/front/user.form.php?id=1
After this PR:
This PR uses the ``input-group`` class of bootstrap as used on Data Picker inputs to position the "Copy to clipboard" button, as it seems a little misaligned. It works exactly as it is today, allowing copy by clicking into the input or copy button.
This PR keeps the current behavior/compatibility to plug-ins that may use the ``<div class="copy_to_clipboard_wrapper"></div>`` as it is today.
It adds a change effect similar to the "Copy to clipboard" on Debug, which changes the icon from "check" to the copy button again to user know it can copy the same information more than once if wanted.
- Here is a brief …
> Improvements to "Copy to Clipboard" wrapper

- .phpstan-baseline.php
- src/Document.php
- src/Glpi/Api/APIRest.php
The `Document::post_getFromDB()` code is only used by the legacy REST API. I try to remove all `exit/die` usages in the code executed from `ajax/front` endpoints. Moving it in the `APIRest` class helps to identify remaining occurences to fix.
> Move specific legacy API code in the legacy API class

- src/Entity.php
- It fixes !36172
Backport of https://github.com/glpi-project/glpi/pull/18900
Increase the maximum alert delay from 100 days to the equivalent of 1 year.
> Increase maximum alert delay (backport)

- templates/components/logs.html.twig
Export button was too squished to the left of the icon. "Entries to show" section under table to directly against the results instead of having the small vertical margins other pager sections have.
> Minor UI fixes on historical tab

- src/Glpi/Api/HL/RoutePath.php
- src/Glpi/Console/CommandLoader.php
I used a more defensive code to make PHPStan happy.
It fixes the following errors that are reported only on PHP 8.4:
```
------ ------------------------------------------------------------------- 
Line   src/Glpi/Api/HL/RoutePath.php                                      
------ ------------------------------------------------------------------- 
150    Property Glpi\Api\HL\RoutePath::$controller                        
(ReflectionClass<Glpi\Api\HL\Controller\AbstractController>|null)  
does not accept ReflectionClass<object>.                           
🪪  assign.propertyType                                            
------ ------------------------------------------------------------------- 
------ ---------------------------------------------------------------------- 
Line …
```
> Fix PHPStan errors reported on PHP 8.4

- src/Socket.php
- It fixes !36154
when updating to the latest version of Fields plugin :  
```
Error during database query: ALTER TABLE `glpi_plugin_fields_<table_name>` ADD `is_recursive` TINYINT NOT NULL DEFAULT '0' AFTER `entities_id` ,  
ADD INDEX `is_recursive` (`is_recursive`) - The error is Unknown column 'entities_id' in 'glpi_plugin_fields_<table_name>'.
```
Because `getItemForItemtype(“Glpi\Socket”)->maybeRecursive()` checks recursivity on the element returned by `getConnexityItem()` (Computer)
Complete this PR : https://github.com/glpi-project/glpi/pull/9710
> Override maybeRecursive() in Socket class for Fields plugin

- src/Search.php
- It fixes !36138
Fixed the absence of the TTO date in the TTO + SO progression when the ticket is pending. This was visible with the TTO option, but not with TTO + progress.
Now only the date is displayed (not the progress bar).
> Fix missing TTO date in TTO + progress SO when status is waiting

- src/Html.php
This was added in #18771 but it seems this file does not exist, which trigger a failed request on most pages.
> Remove ref to missing lib/gridstack-extra.css file

- src/NotificationTargetCommonITILObject.php
Related ticket : !35966 (@cedric-anne)
On a ticket, three actors reply to an email within the same minute (important). The follow-ups are correctly displayed in the ticket timeline
and recorded in the database.
```sql
MariaDB [10bugfixes]> select id, date_creation, date_mod, content from glpi_itilfollowups;
+----+---------------------+---------------------+------------+
| id | date_creation       | date_mod            | content    |
+----+---------------------+---------------------+------------+
| 90 | 2025-02-05 10:41:57 | 2025-02-05 10:41:57 | followup 1 |
| 91 | 2025-02-05 10:41:57 | 2025-02-05 10:41:57 | followup 2 |
| 92 | 2025-02-05 10:41:57 | 2025-02-05 10:41:57 | followup 3 | …
```
> Fix(Notification): Order by id ASC

- templates/pages/management/contract.html.twig
- It fixes !36245
Notice date wasn't correct when the contract was not renewed.
> Fix(contrat): notice date

- src/ItemVirtualMachine.php
Fixes the following error:
```
glpi.CRITICAL:   *** Uncaught PHP Exception TypeError: "array_key_exists(): Argument #2 ($array) must be of type array, int given" at CommonDBTM.php line 1488
Backtrace :
src/ItemVirtualMachine.php:210                     CommonDBTM->getLink()
src/ItemVirtualMachine.php:114                     ItemVirtualMachine::showForVirtualMachine()
src/CommonGLPI.php:681                             ItemVirtualMachine::displayTabContentForItem()
ajax/common.tabs.php:112                           CommonGLPI::displayStandardTab()
...Glpi/Controller/LegacyFileLoadController.php:59 require()
vendor/symfony/http-kernel/HttpKernel.php:101      Glpi\Controller\LegacyFileLoadController->Glpi\Controller\{closure}()
...ymfony/http-foundation/StreamedResponse.php:106 …
```
> Fix computer link on virtualization tab

- phpunit/abstracts/AbstractActorFieldTest.php
- phpunit/functional/Glpi/Form/Destination/CommonITILField/AssigneeFieldTest.php
- phpunit/functional/Glpi/Form/Destination/CommonITILField/ObserverFieldTest.php
- phpunit/functional/Glpi/Form/Destination/CommonITILField/RequesterFieldTest.php
- phpunit/src/Glpi/Form/Destination/CommonITILField/AbstractActorFieldTest.php
- src/Glpi/Form/Destination/CommonITILField/ITILActorField.php
- src/Glpi/Form/Destination/CommonITILField/ITILActorFieldStrategy.php
- templates/pages/admin/form/itil_config_fields/itilactor.html.twig
- tests/cypress/e2e/form/destination_config_fields/actors.cy.js
- tests/cypress/e2e/form/destination_config_fields/assignee.cy.js
- tests/cypress/e2e/form/destination_config_fields/observer.cy.js
- tests/cypress/e2e/form/destination_config_fields/requester.cy.js
Des stratégies implémentés dans FormCreator sont manquantes.
Ajout des stratégies : 
- Supervisor of the user who filled the form
- User from GLPI object answer
- Tech user from GLPI object answer
- Group from GLPI object answer
- Tech group from GLPI object answer
> feat(forms): Add new strategies for ITILActorField fields

- bin/console
- package.json
When we introduced `npm` to fetch our front-end dependencies, we were not able to recompute the `.package.hash` file automatically from a `npm` event because there was at this time no event triggered after the `package-lock.json` file update.
The probem is that we have to manually call `bin/console dependencies:install` after a `npm install {package}` operation to recompute this `.package.hash` file.
More recently, a `dependencies` event have been introduced.
> The dependencies script is run any time an npm command causes changes to the node_modules directory. It is run AFTER the changes have been applied and the package.json and package-lock.json files have been updated.
We can rely on it to be sure that the `.package.hash` is always up-to-date when new dependencies are installed.
> Recompute `.package.hash` when npm dependencies are changed

- src/NetworkPort.php
This PR removes the extra break on **Management port** section:
After this PR:
> Remove extra break on Management Port (Network Ports - Asset)

- src/RuleImportAsset.php
- Alternative to [#18921](https://github.com/glpi-project/glpi/pull/18921)
This PR enhances the **GLPI reconciliation engine** by integrating the `getUUIDRestrictCriteria()` method into **UUID-based matching rules**.  
Currently, **virtual machine processing** correctly identifies and associates computers using this method. However, the **reconciliation rules do not account for "mixed" UUIDs** in their queries, leading to inconsistencies.  
As a result, while the **native inventory** successfully links computers even when UUIDs are "mixed," the **reconciliation process fails to do so**.  
1️⃣ **Step 1: Importing an inventory file (Computer with Agent)**  
- The file contains `"uuid": "BC4C4D56-A9C6-6919-3FEE-FA0F3887B6A5"`.  
- GLPI correctly …
> Fix(inventory): 'uuid' criterion must be identical to what VirtualMachine does

- src/CommonDBTM.php
- src/Inventory/Asset/InventoryAsset.php
I still cannot explain why the existing `tests\units\Glpi\Inventory\InventoryTest::testOtherSerialFromTag()` test was passing and therefore I cannot be sure that the corresponding feature was buggy. Anyway, it should not have work with the current logic that is:
1. When the inventory is handled, the agent is created with the `itemtype=Computer` `items_id=0` properties.
2. The computer is then created with `CommonDBTM::add()`.
3. Before it is actually created in DB, the rules are processed in `CommonDBTM::assetBusinessRules()`.
4. At this point, `$this->getInventoryAgent()` can only return `null`, because the computer has not yet any ID, and therefore no agent can be linked to it. No agent tag can be added in `$input['_tag']` and the rule criteria cannot be evaluated.
With the proposed …
> Fix ONADD rules based on inventory agent tag

- src/Reservation.php
- It fixes !36205
The deletion notification does not work because `pre_deleteItem()` checks the `DELETE` right instead of the `PURGE` right.
The DELETE right does not exist on reservations
> Fix(Reservation): check for PURGE right instead of DELETE

- js/modules/Monaco/MonacoEditor.js
- js/src/vue/Debug/Widget/ThemeSwitcher.vue
If you have debug mode enabled and are using a dark theme, the Monaco editors such as the UI Customization editor were being shown in a light theme. This was because the `colorizeText` method used for syntax highlighting had to globally set the theme and it always set it to 'glpi' which is the custom light theme.
With this PR, `colorizeText` now creates a temporary element and then uses `colorizeElement` which can properly handle colorizing with a specific theme without messing with the themes of real editors.
I also added logic to handle switching the themes when using the theme switcher widget in the debug bar similar to how it handled switching TinyMCE styles.
> Fix monaco themes in debug mode

- phpunit/abstracts/RuleCommonITILObject.php
- phpunit/functional/Appliance_ItemTest.php
- phpunit/functional/Appliance_Item_RelationTest.php
- phpunit/functional/ComputerTest.php
- phpunit/functional/SearchTest.php
- src/CommonDBTM.php
- src/CommonDropdown.php
- src/CommonITILObject.php
- src/Glpi/Features/AssetImage.php
When the `CommonDBTM::isField()` method is used on a "non-hydrated" object, the `CommonDBTM::getEmpty()` is triggerred, calling itself the `CommonDBTM::post_getEmpty()` method and the `item_empty` hook.
One of the side-effect of this is that `$this->fields['entities_id']` field is automatically set with the `$_SESSION['glpiactive_entity']` value for any `CommonDBTM::add()` operation. For all items created from the generic GLPI form, it will not change much, as the `entities_id` will be overriden by the form input, but for all objects created from anywhere else, it could hide the fact that the information is missing in the input. For instance, the following commit fixes an issue that has not been detected earlier due to this default `entities_id` value: …
> Do not alter current object when fetching its search options

- phpunit/functional/Glpi/Inventory/InventoryTest.php
- src/Glpi/Inventory/Inventory.php
I've added methods/property to have control on that, not sure if it's necessary.
It will depend if we want to keep `additionalProperties` in schema. If we plan to remove them in the future (when v10 has died), we can just force flexible for the moment, and we're done.
> Allow extra nodes in inventory file

- phpunit/functional/DbUtilsTest.php
- phpunit/functional/Glpi/Inventory/Assets/NetworkPortTest.php
- src/Glpi/Dashboard/Dashboard.php
- tests/src/autoload/functions.php
The `getItemByTypeName()` function currently returns `false` if the required item cannot be loaded, but our tests code is actually not expecting this to happen. I think this function should throw and exception in this case, to be sure that the corresponding test will fail instantly when this happen.
> Throw exception when no item is found by `getItemByTypeName()`

- src/CommonTreeDropdown.php
- src/Location.php
- templates/components/itilobject/itilsatisfaction.html.twig
- templates/components/itilobject/timeline/form_document_item.html.twig
- templates/dropdown_form.html.twig
- templates/pages/admin/ldap.group_criteria.html.twig
- templates/pages/admin/ldap.user_criteria.html.twig
- templates/pages/assets/socket_short_form.html.twig
- templates/pages/management/domainrecord.html.twig
- templates/pages/management/domainrecordtype_helper.html.twig
- templates/pages/setup/externallink.html.twig
- templates/pages/setup/general/general_setup.html.twig
- templates/pages/setup/general/glpinetwork_setup.html.twig
- templates/pages/setup/general/security_setup.html.twig
- templates/pages/setup/general/systeminfo_form.html.twig
- templates/pages/setup/ldap/form.html.twig
- templates/pages/setup/ldap/group_config.html.twig
- templates/pages/setup/notification/queued_notification.html.twig
- templates/pages/tools/reminder.html.twig
- templates/pages/tools/reminder_translation.html.twig
- templates/pages/tools/rss_form.html.twig
The alignment of fields when using `full_width` was recently fixed but there were several cases where the sizes of labels and inputs was statically set to try fixing the alignment in individual use cases. These cases are no longer needed and in some cases were not producing the expected results.
> Review full_width with custom input sizes uses

- phpunit/functional/HtmlTest.php
- src/Ajax.php
- src/Html.php
Some variables in `Ajax::createIframeModalWindow()` were escaped using `htmlescape()` but were used in a JS context, resulting in an unexpected extra encoding.
> Fix AJAX modal url/id escaping

- templates/pages/form_renderer.html.twig
Replace invalid button "Go home" with "Go back to service catalog" when displayed on central interface
Helpdesk interface (current) :
Central interface :
> fix(forms): invalid `Go home` button on central interface

- js/modules/Form/GeolocationField.js
- src/CableStrand.php
- src/CartridgeItem_PrinterModel.php
- src/ITILCategory.php
- src/Item_Line.php
- src/Item_SoftwareLicense.php
- src/Item_SoftwareVersion.php
- src/KnowbaseItem.php
- src/NetworkAlias.php
- src/ProjectCost.php
- src/ProjectTask.php
- src/Search.php
- templates/components/datatable.html.twig
- templates/components/form/item_remotemanagement_list.html.twig
- templates/components/search/display_data.html.twig
- templates/components/search/displaypreference_list.html.twig
- templates/components/search/table.html.twig
- templates/layout/parts/profile_selector.html.twig
- templates/pages/form_renderer.html.twig
- templates/pages/setup/notification/group_notifications.html.twig
- templates/pages/tools/search_solution.twig
While working on other things I discovered some duplicated strings. This leads to an inconsistent user experience and probably adds some difficulty for the translators.
Changes:
- No item/result/data/item strings unified to simply "No results found" except in specific cases like the dashboard where "No data found" may make more sense or there was a more specific string like "No racks found".
- "Take me home" and "Go Home" unified to "Take me home" which existed first.
> Standardize some strings

- templates/components/notepad/form.html.twig
Makes note labels on the Notepad tabs more useful. The current format is the note's ID followed by a random number that is generated when the tab loads and shared between all notes. You end up with a list of notes like "#2084350", "#3084350", "#4084350". Refresh page and then the list is "#2345948", "#3345948", "#4345948".
New format: `#2 - 2025-02-16 19:02`, `#3 - 2025-02-16 19:02 (Last update on 2025-02-16 19:05)`
> Useful note labels

- src/Plugin.php
Some plugins may require the `Plugin::getWebDir()` to have the same behaviour as in GLPI 10.0 to continue to work as expected. For instance, the **OauthSSO** plugin uses this method to compute a callback URL that must be registered in the Oauth provider side. If we replace `/marketplace/oauthsso/...` by `/plugins/oauthsso/...`, it will break the authentication feature of the plugin.
Restoring the existing behaviour (as it was before #17929) is preferable to prevent this kind of issues.
The plugin will still have to find a solution to migrate to the new URL, but if we preserve this behaviour, it will be possible to do it later, and to implement a feature that would permit to ask to the GLPI administrator a confirmation that the Oauth provider …
> Restore the Plugin::getWebDir() behaviour

- phpunit/functional/Glpi/Migration/AbstractPluginMigrationTest.php
- phpunit/functional/Glpi/Progress/AbstractProgressIndicatorTest.php
- phpunit/functional/Glpi/Progress/ConsoleProgressIndicatorTest.php
- phpunit/functional/Glpi/Progress/StoredProgressIndicatorTest.php
- src/Glpi/Console/Traits/PluginMigrationTrait.php
- src/Glpi/Message/MessageType.php
- src/Glpi/Migration/AbstractPluginMigration.php
- src/Glpi/Migration/PluginMigrationResult.php
- src/Glpi/Progress/AbstractProgressIndicator.php
- src/Glpi/Progress/ConsoleProgressIndicator.php
- src/Glpi/Progress/StoredProgressIndicator.php
- src/Toolbox.php
The purpose of this "framework" is to ease the developement and the testing of the migration of plugins data into core tables. It will be used to handle the migration of the `formcreator` and the `genericobject` data in GLPI 11.0.
I propose to target a `11.0/plugin-migration-framework` branch. This will permit to parallelize work on both `formcreator` and `genericobject` migrations and keep the ability to refactor this framework easilly without polluting the main branch too many commits.
```php
// Migration class
class MyPluginMigration extends AbstractPluginMigration
{
protected function validatePrerequisites(): bool
{
return true;
}
protected function processMigration(): bool
{
$categories_iterator = $this->db->request(['FROM' => MyPluginCategory::getTable()]);
$items_iterator      = …
```
> Framework for migration of plugin data into core tables

- tests/cypress/e2e/form/editor/conditions.cy.js
There was a mistake in the `conditions are applied on questions` and `conditions are applied on comments` tests that went unnoticed due to some racing condition.
Indeed, the `"My question/comment that is visible if some criteria are met"` item should be hidden in the last step of the test as it is only visible if the answer is `Expected answer 1` and we have `Expected answer 2` in the final step.
The issue is that this assertion would work both way (not visible / is visible) due to how the tests are executed:
* When checking if the item is visible, the result is instantly true because the item is visible in the previous step of the test so the UI didn't have time to update yet.
* When checking if the item is not visible, cypress will see it is not true so it will wait a bit which give the …
> Fix mistake in conditions tests

- src/Api/API.php
- src/User.php
- It fixes !36290
- Change the message on reset to warn the user that if his email is matched to several users, GLPI will not send an email
> Change lost password message

- phpunit/functional/RuleMailCollectorTest.php
- src/RuleMailCollector.php
- src/RuleMailCollectorCollection.php
- It fixes !36253
When an email is quarantined by Microsoft and then released by an admin, GLPI considers it as an automated email and blocks it using the default rule:
This PR adds a criterion to the default rule to identify that an email has been released from quarantine by modifying the rule as follows:
However, since this criterion is specific to Microsoft, the default rule is not modified. Users must add it manually if needed.
> Feat(rule mail collector): add criterion for quarantine released

- CHANGELOG.md
- phpunit/functional/AuthTest.php
- src/Auth.php
- src/AuthMail.php
- src/RuleRight.php
- src/User.php
After some escaping fixes a few months ago, authentication sources with links (LDAP for example) were showing raw HTML on the user form instead of showing the link. I also noticed there was a `link` parameter for `Auth::getMethodName` which was ignored and at least for the last 13 years was not implemented. I've rewritten the method to take the `link` parameter into account and handle sanitization better.
> Fix escaping and unhandled param for Auth::getMethodName

- phpunit/functional/TelemetryTest.php
- phpunit/imap/MailCollectorTest.php
- src/MailCollector.php
- src/Toolbox.php
The server and server type need to be required fields for mail collectors. If the server is missing, a bunch of PHP warnings are encountered when loading the form. If the server type is missing, an exception is thrown when it tries connecting.
> Mail collector server and type should be required fields

- src/autoload/legacy-autoloader.php
The filter used to enhance the legacy autoloader performances was a bit aggressive. It was preventing files using the `GlpiPlugin\\` namespace to be loaded from the corresponding plugin `inc` directory.
> Fix autoload of non-PSR-4 namespaced plugin classes

- src/User.php
My GLPI instance doesn't support timezones =( So it's not displayed on Simplified UI, only a warning message is shown on Central UI, but as this warning isn't show to the user, it creates an odd situation where the missing Timezone field makes E-mail field overlaps:
This PR fixes this alignment by creating an empty TR (this approach is already taken by other parts of this same PHP function).
It also vertical align the "Emails" field on both UIs.
> Fix alignment of Email field and Dynamic rowspan

- src/Glpi/Inventory/Asset/DatabaseInstance.php
- src/Glpi/Inventory/Asset/Monitor.php
- src/Glpi/Inventory/Asset/Peripheral.php
- src/Glpi/Inventory/Asset/Printer.php
- src/Glpi/Inventory/MainAsset/MainAsset.php
- src/RuleImportAsset.php
GLPI Rules system output always contains a `_ruleid` entry with matching rule.
There is no need for an additional `rules_id` in the same output (it's specific to `RuleImportAsset`; it probably comes from original inventory migration) - that just adds confusion.
> Drop specific info already sent from GLPI framework

- phpunit/functional/DbUtilsTest.php
- src/DBmysqlIterator.php
- src/DbUtils.php
- src/Dropdown.php
- src/Profile.php
- It fixes !36401
When a user tries to modify the templates of a profile from an entity other than root, the list is empty because it must be done from the root entity, but this generates this error in the logs:
```
glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: Empty IN are not allowed in .../src/DBmysqlIterator.php at line 589
Backtrace :
src/DBmysqlIterator.php:560                        DBmysqlIterator->analyseCriterion()
src/DBmysqlIterator.php:315                        DBmysqlIterator->analyseCrit()
src/DBmysqlIterator.php:111                        DBmysqlIterator->buildQuery()
src/DBmysql.php:1105                               DBmysqlIterator->execute()
src/DbUtils.php:1074 …
```
> fix: Empty IN are not allowed

- src/MailCollector.php
Re-added the email headers that are missing since 10.0.18: Thread-Topic and Thread-Index
> Re-add the possibility to get Thread-Topic and Thread-Index from email header

- css/includes/components/_content-editable-inputs.scss
Fix some margin issues, it seems one specific CSS rule is no longer needed and has been having a negative impact on the UI.
Before (textarea is missing because of bad margins):
After:
> Forms: fix richtext editor margins

- src/CommonITILValidation.php
- It fixes #19036 
- Prevents division by zero.
I do not really understand why this issue is not already caught by tests suite. `TicketTest::testGlobalValidationUpdate()` seems to do the job; but `$total` in that case is always >= 1.
> Prevent division by zero; fixes #19036

- templates/components/itilobject/timeline/form_task.html.twig
This PR allows to remove the "Plan this task" button from the task form if the user does not have permission to assign the status "Planned" to the ticket
- It fixes !36489
> fix: hide Plan this task in task form for unauthorized users

- ajax/asset/assetdefinition.php
- js/src/vue/CustomObject/FieldPreview/FieldDisplay.vue
- src/Glpi/Asset/Asset.php
- src/Glpi/Asset/AssetDefinition.php
- src/Glpi/Asset/CustomFieldOption/ProfileRestrictOption.php
- src/Glpi/Asset/CustomFieldType/AbstractType.php
- src/Glpi/Asset/CustomFieldType/TypeInterface.php
- tests/cypress/e2e/Asset/custom_fields.cy.js
Change some options for custom fields to be based on the user's profile. For example, making the field readonly or hidden for certain profiles.
> Custom Field option profile restrictions

- js/modules/Forms/EditorConvertedExtractedSelectableDefaultValue.js
- js/modules/Forms/QuestionSelectable.js
- src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
- src/Glpi/Form/QuestionType/QuestionTypeDropdown.php
- templates/pages/admin/form/form_editor.html.twig
- tests/cypress/e2e/form/form_convert_default_values.cy.js
Improve the form editor by adding support for converting default values between selectable question types (radio, checkbox, dropdown).
Now when switching between these types, the selected options and their states are properly preserved, providing a better user experience when editing forms.
> feat(forms): Adding default value conversion between selectable question types

- phpunit/functional/Glpi/Form/Destination/CommonITILField/StatusFieldTest.php
- src/Glpi/Form/Destination/CommonITILField/StatusField.php
- src/Glpi/Form/Destination/FormDestinationTicket.php
This option allow to have a form destination that will create a ticket with the closed status.
This is useful when you have a form that do not require any treatment after submission (for example some kind of poll).
Note: formcreator does this by allowing forms to have 0 target, which we don't want.
We prefer to keep a ticket to have a "trace" of the answers, even if it is closed immediately .
> Forms: add an option to close a ticket on creation

- js/modules/Forms/EditorController.js
- src/Glpi/Controller/Form/RendererController.php
- src/Glpi/Form/Question.php
- src/Glpi/Form/QuestionType/AbstractQuestionType.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeShortAnswer.php
- src/Glpi/Form/QuestionType/QuestionTypeInterface.php
- src/Glpi/Form/QuestionType/QuestionTypeLongText.php
- src/Glpi/Form/QuestionType/QuestionTypeRequestType.php
- src/Glpi/Form/QuestionType/QuestionTypeUrgency.php
- templates/pages/admin/form/form_question.html.twig
- templates/pages/form_renderer.html.twig
- tests/cypress/e2e/form/form_rendering.cy.js
A feature that has often been requested and doesn't take much to add, preloading a form fields using GET parameters.
> Allow helpdesk forms fields to be preset using GET parameters

- front/asset/asset.form.php
- src/Glpi/Asset/Asset.php
1. To be able to use the trashbin on inventoriable assets, it is necessary to override the `useDeletedToLockIfDynamic` method.
2. The purge action was not working as expected.
> Fix generic assets trashbin feature

- ajax/dashboard.php
- front/central.php
- src/Dashboard/Grid.php
- It fixes !36463
The list of groups stored in `$_SESSION['glpigroups']` was systematically cleared when displaying a shared dashboard, causing the loss of access to elements shared via groups.
> fix(dashboard): groups lost in session

- phpunit/functional/ToolboxTest.php
- src/RichText/RichText.php
- src/Toolbox.php
It fixes !35308 and !36506
When an image is sent by email, it is possible to link it in order to redirect the user to another page. SharePoint uses this system which links to images. The problem is that if the user sends an image containing a redirect link, GLPI displays the image in the DOM but does not redirect the user to the associated link.
> Fix: Preserve Redirection Links for Images in Emails

- src/QueuedWebhook.php
Webhooks are sent inside an automatic action which may be triggered externally or under any user account. The `defineTabs` method in some cases relies on permission checks, notably CommonITILObject, which leads to PHP warnings and unexpected behavior. Instead of defining the tabs and checking them to see if a History tab exists, it should still be OK to simply check the `dohistory` property.
Part of !35208
> Do not call defineTabs from webhooks

- phpunit/functional/RuleAssetTest.php
- src/RuleAsset.php
- It fixes !36441
- This PR adds the ability to select in the assets rule engine, the name of the element in the criteria and actions.
> feat: Include asset name in rule engine processing

- phpunit/functional/TicketTest.php
- src/Ticket.php
The current behavior of `Ticket::getDefaultSearchRequest()` was a bit weird and caused an unexpected side effect for one of our client.
Indeed, it changes the default ticket criteria depending on whether or not the current user can see all the tickets.
It lead to confusion because two technicians will have different criteria if one of them is not allowed to see all tickets.
It feels more natural to tie this behavior to the used interface instead of a specific right.
This way all technicians have the same criteria.
Internal ref: !36367.
> Tweak tickets default request criteria

- src/Glpi/Search/Provider/SQLProvider.php
- Detected by @SebSept while working on #19048 
- in 10.0.18, where it works, the line is "1=0" to force a false condition (see https://github.com/glpi-project/glpi/blob/10.0.18/src/Search.php#L4424), and the current proposal resolves to true and so a lot of tickets appears without the right in session
- the bug probably started from #13072
Note: I'm note sure this is the best way to force a false SQL condition
> fix generated sql when Ticket::READMY is missing

- css/includes/components/itilobject/_timeline.scss
The todo list mode was expected to be compact. With some recent changes, a few div appear where they should not.
I didn't check the main branch, but let me know if dedicated work is required
Before:
After
Not the same picture, but you should see the changes
> todo list was broken

- src/Console/Database/InstallCommand.php
- It fixes #19080 (issue number, if applicable)
- The GLPI CLI command `bin/console db:install` will be able to support SSL enabled connection config on `config_db.php` when installing GLPI database.
n/a
As just following our company's OSS contribution rule, please allow to add copyright line.
> Fix CLI database install command to support ssl

- install/migrations/update_10.0.x_to_11.0.0/assets.php
- install/migrations/update_10.0.x_to_11.0.0/dropdowns.php
- install/mysql/glpi-empty.sql
- phpunit/functional/Glpi/Asset/AssetDefinitionTest.php
- phpunit/functional/Glpi/Asset/CustomFieldDefinitionTest.php
- phpunit/functional/Glpi/Dropdown/DropdownDefinitionTest.php
- src/Glpi/Asset/CustomFieldDefinition.php
- src/Glpi/CustomObject/AbstractDefinition.php
The proposed changes correspond to small enhancements that I had to implement to make the generic assets classes fully compatible with the generic migration system introduced in #18938 .
- Add missing `getNameField()` overrides and corresponding DB keys.
- Add default custom field lable based on the system name.
- Add an error message when custom field type of system name is going to be changed.
- Add missing `date_creation`/`date_mod` fields on `glpi_assets_customfielddefinitions` table.
- Remove obsolete dev migration.
> Small enhancements on custom objects

- js/src/vue/Kanban/Column.vue
Missing hidden fields like `projects_id` was causing the creation of items in non-global Kanbans to fail or occur without the correct parent association. As far as I know, it only affects the Vue rewrite of the Kanban, so not GLPI 10.
No tests added here as the Kanabn lacks any Jest (issues importing some of the JS needed) or E2E tests at the moment. I am working on them for a different PR.
> Fix missing hidden fields needed for bulk kanban adds

- css/includes/pages/_search.scss
Reduce vertical margins of `hr` elements which are used to separate items within the same cell from being 2x the page font size to 10px.
Before:
After:
> Reduce margin of hr elements in search results

- phpunit/functional/Glpi/Migration/AbstractPluginMigrationTest.php
- src/Glpi/Migration/AbstractPluginMigration.php
- src/Glpi/Migration/MigrationException.php
1) Use item friendly name in import messages.
2) Try to detect unchanged JSON fields.
While working on #19033, I figured out that some items were considered as different because `$input['translations']`  value was `[]` while the `$this->fields['translations']` value was is JSON representation `"[]"`. I added a small check to consider a field as unchanged when the input is an array and the decoded version of the value contained in `$this->fields` is identical.
3) Forward session messages to progress indicator.
Until now, when an item add/update operation failed, the result was a generic message (`An unexpected error occured.`), without any indication of what really happens. If the item hook methods are implemented as expected, a rejection of an add/update operation should result in adding …
> Enhance plugin migration framework (2)

- phpunit/functional/Glpi/Dashboard/DashboardTest.php
- src/Dashboard/Dashboard.php
- It fixes !36527
When two different users duplicated the same dashboard, they received identical keys for their copies, causing the second duplication to overwrite the first one in the database.
Modified the `cloneCurrent()` method in Dashboard.php to generate a unique key for each dashboard copy by incorporating a UUID, ensuring each duplicated dashboard receives a unique identifier regardless of the dashboard name.
> Fix duplicate dashboards that replace other copies

- src/Glpi/Http/Listener/PluginsRouterListener.php
- src/Glpi/Kernel/Kernel.php
- src/Glpi/Kernel/ListenersPriority.php
It fixes #19132.
When the plugin routing was implemented in #17641, some technical limitations forces us to add a "fake" route to detect plugins URLs and then handle them after the Symfony routing using a dedicated listener. The problem is that it conflicts with the way to detect the specific controllers in the `LegacyItemtypeRouteListener`, see https://github.com/glpi-project/glpi/blob/f4c1d9f285510e6f12e1bba28aec20ec79b1dca3/src/Glpi/Http/Listener/LegacyItemtypeRouteListener.php#L84-L90
Now we have reorganize the GLPI bootstraping to do it entirely after the kernel boot, we can remove this "fake" route and call the `PluginsRouterListener` earlier.
> Fix plugins generic URLs handling

- phpunit/functional/Glpi/Http/LegacyItemtypeRouteListenerTest.php
- src/Glpi/Http/Listener/LegacyItemtypeRouteListener.php
It fixes #18997.
`CommonDeviceModel` and `CommonDeviceType` URLs were not automatically forwarded to the generic controllers.
> Fix routing of devices models/types URLs

- js/modules/Forms/Condition/Engine.js
- src/Glpi/Controller/Form/Condition/EngineController.php
- src/Glpi/Controller/Form/QuestionActorsDropdownController.php
- src/Glpi/Controller/Form/RendererController.php
- src/Glpi/Controller/Form/SubmitAnswerController.php
- src/Glpi/Controller/Form/Utils/CanCheckAccessPolicies.php
- templates/pages/form_renderer.html.twig
- It fixes #19070
When allowing unauthenticated users to submit a form from a tokenized public URL, the Engine and SubmitAnswers routes returned HTTP 500 responses, making it impossible to actually submit a public form.
Only authenticated users could do it.
This PR fixes this behavior.
> Fix Form incorrect access control checks

- templates/components/datatable.html.twig
Add a formatter for yes no values such as is_active, is_recursive, etc.
> Add yesno formater in datatable.html.twig

- install/empty_data.php
- install/migrations/update_10.0.x_to_11.0.0/itilobject_templates.php
- install/mysql/glpi-empty.sql
- phpunit/functional/PendingReasonTest.php
- phpunit/functional/TicketTest.php
- src/Change.php
- src/CommonITILObject.php
- src/Problem.php
- src/Ticket.php
- templates/components/itilobject/fields_panel.html.twig
`Validation evolution` spec implementation, step 1 : `Pre-validation before arriving in the technicians’ queue`
[x] allow the usage of the `CommonITILObject::APPROVAL` status for tickets (not `ACCEPTED`/`REFUSED`)
[x] adapt "view new tickets" and "See All tickets" rights checks to take this status into account
[x] move "Approval" just below the status field in the right panel of ITIL objects
[x] hide this field when it is set to "Not subject to approval"
[x] check the automation of the rule engine (at least the possibility of sending an approval request)
> Allow usage of the `APPROVAL` status in tickets

- phpunit/functional/CommonITILValidationTest.php
- src/CommonITILValidation.php
- It fixes !36625
This PR fixes an issue where, after rejecting an approval request and submitting a new one, the approval status incorrectly remains `Rejected` instead of changing to `Waiting for approval`
> Fix - Validation status when requesting a new validation after reject

- phpunit/functional/Glpi/Asset/AssetDefinitionTest.php
- phpunit/functional/Glpi/Dropdown/DropdownDefinitionTest.php
- src/Glpi/Asset/AssetDefinition.php
- src/Glpi/CustomObject/AbstractDefinition.php
- src/Glpi/Dropdown/DropdownDefinition.php
To manually test #19033 , I sometimes have to delete the imported definition to and run the command to recreate them. I figured out that the dropdown concrete classes display preferences are not deleted when the corresponding dropdown definition is deleted. The result is that I had SQL errors when I reimported a dropdown definition with a previously used system name, due to DB unicity checks.
> Purge dropdown display preferences when a dropdown definition is purged

- front/lockedfield.form.php
While testing global locks, I found that if you have GLPI go to an item after creation you are directed to a locked field form which:
1. Isn't accessible in any other way except directly via URL.
2. Shows the incorrect field as the dropdown only shows fields which are left to be locked rather than using all lockable fields and a 'used' parameter.
3. Only shows the "Field" field and lets you change it here which probably isn't intended. I think it is intended that you need to delete/add locked fields rather than reassign existing ones.
The safest solution is to just redirect to the list.
> Do not show existing locked field forms

- front/ticket.form.php
- src/CommonITILObject.php
- src/Ticket.php
- It fixes !36483
- When a follow-up or a task is promoted to ticket, the content of the new ticket is not filled.
> fix: add ticket content from promoted followup

- .phpstan-baseline.php
- CHANGELOG.md
- js/fileupload.js
- src/CommonDBChild.php
- src/User.php
- src/UserEmail.php
- templates/components/form/header.html.twig
- templates/components/user/password_security_checks.html.twig
- templates/components/user/picture.html.twig
- templates/pages/admin/user/change_other_password.html.twig
- templates/pages/admin/user/user.html.twig
- templates/pages/admin/user/user_picture_field.html.twig
- tests/cypress/e2e/Admin/user.cy.js
This was going to just be a simple migration of the User forms to Twig, but the old layout looked worse when migrated as-is. In both the old and new, the form felt cluttered as well. The picture and password sections specifically felt messy.
Changes:
- Merge of regular User form and the "My user/My settings" user form into a single template, but still only showing certain fields on the My Settings page.
- New UI/UX for changing user pictures. The old display of having the picture, file upload and clear checkbox directly in the form took up a lot of room and didn't look right with the new form layout. Now, only the picture is shown. When you hover over the picture, you get a pointer and tooltip to indicate you can click to change the picture. This opens a modal that lets you go back to the …
> User forms UI twig and cleanup

- src/DropdownTranslation.php
Due to operator order (&& and ||), dropdown translations were showing search options that were not for the item's own table.
Fixes #19148
> Restrict dropdown translations to fields in item's own table

- js/modules/Forms/Condition/Engine.js
- phpunit/functional/Glpi/Form/AccessControl/ControlType/AllowListTest.php
- phpunit/functional/Glpi/Form/AccessControl/ControlType/DirectAccessTest.php
- src/Glpi/Controller/Form/RendererController.php
- src/Glpi/Controller/Form/Utils/CanCheckAccessPolicies.php
- src/Glpi/Form/AccessControl/ControlType/AllowList.php
- src/Glpi/Form/AccessControl/ControlType/ControlTypeInterface.php
- src/Glpi/Form/AccessControl/ControlType/DirectAccess.php
- src/Glpi/Form/AccessControl/FormAccessControlManager.php
- templates/pages/form_renderer.html.twig
As a reminder, this token allow a form to be accessed like this: `/Form/Render/{$id}?token={$token}`.
This works well when accessing a form but mean that any AJAX requested performed on the form page must also include this token to make sure the user is allowed to call it.
This is bad because it is hard to maintain (need to manually include the token everywhere) and non generic (the access policiy that deal with the token should not rely on external code that manually refer to its internal behavior).
The proposed solution is to store the submitted token in the session so it can easily be accessed by any ajax request using the session data.
This should not weaken the security as you still need the correct token to access the form in the first place.
> Helpdesk form: store direct access token in session once validated

- phpunit/functional/MassiveActionTest.php
- src/SavedSearch.php
- It fixes #36622
- The massive "Change visibility" action did not display the correct dropdown. It displayed the ability to change the saved search entity.
> fix: The massive action Change Visibility displayed the wrong dropdown

- src/Glpi/Kernel/Listener/SessionStart.php
Js file in the `/js` folder are not cached by the browser due to a session being started before the `LegacyAssetsListener` execution.
> Make sure js files outside of /lib are cached

- src/Search.php
- It fixes !36707
If a `Change` or `Problem` contains **anonymous actors** and you try to filter the list on them, an error appears and they don't appear in the search option results.
The problem stems from the fact that the search processing only targeted `Tickets` and not `Changes` and `Problems`.
> Fix filtering on anonymous users in changes

- composer-dependency-analyser.php
Can't lint the code locally since #19175 because of the following errors:
> Ignore composer dependency analyzer errors

- phpunit/functional/Glpi/Log/ErrorLogLineFormatterTest.php
- src/Glpi/Log/AbstractLogLineFormatter.php
The symfony exception handling logic automatically formats the message sent to the logger by appending the location of the error. However, it just contains the basename of the file, and it can be ambiguous. Also, If we want to manually log a caught error, we will have to manually append the error location to the message to be able to have it written in the log file.
I propose to preprend a line to the backtrace in the logs to be sure to always have the full location of the error.
```diff
[2025-03-13 07:30:34] glpi.CRITICAL:   *** Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("")." at index.html.twig line 39
Backtrace :
+  ./templates/pages/central/index.html.twig:39 …
```
> Enhance error traces in log

- phpunit/abstracts/AbstractDestinationFieldTest.php
- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- phpunit/functional/Glpi/Form/Migration/TargetsMigrationTest.php
- phpunit/functional/Glpi/Migration/AbstractPluginMigrationTest.php
- src/Glpi/Console/Migration/AbstractPluginMigrationCommand.php
- src/Glpi/Console/Migration/FormCreatorPluginToCoreCommand.php
- src/Glpi/Form/Migration/FormMigration.php
- src/Glpi/Migration/AbstractPluginMigration.php
This simplify the migration concrete class constructors.
> Make the logger instance optional for plugins migrations

- CHANGELOG.md
- src/Ticket.php
Fixes #19172
Only show unsolved/unclosed tickets in the dropdown for the Merge as Followup massive action. This is both for performance reasons and also logical since followups usually cannot be added to solved/closed tickets.
> Show only unsolved tickets for Merge as Followup

- src/Glpi/Api/APIRest.php
Due to the nature of multipart forms and the way that PHP handles them, during multi-part POST requests only the first uploaded file was attached to the created item. With this nested `foreach` it's possible now to upload multiple files at once and expect `manageUploadedFiles()` to handle them properly.
Tested on main and 10.0.17
> Add a nested foreach around $uresult

- templates/components/search/displaypreference_list.html.twig
- Rework the display of the "search result display" tab
- add a (un)select all button
- add a search input
Replace #18498
**Before**
**After**
> rework the "search result display" tab to be (a little bit) more usable

- css/includes/components/form/_form-editor.scss
- js/modules/Forms/EditorController.js
- templates/pages/admin/form/form_section.html.twig
- tests/cypress/e2e/form/editor/editor.cy.js
This pull request introduces changes to the form editor to display the number of elements in a section badge and updates the corresponding tests. The most important changes include adding CSS rules to hide the badge when the section is not collapsed, updating the section block count in the JS controller, and adding the badge to the template. Additionally, a new test case is added to verify the correct element count in the section badge.
> feat(forms): add a badge that displays the number of elements in a section when it is collapsed

- phpunit/functional/Glpi/Asset/AssetDefinitionManagerTest.php
- phpunit/functional/Glpi/Asset/AssetDefinitionTest.php
- phpunit/functional/Glpi/Dropdown/DropdownDefinitionManagerTest.php
- phpunit/functional/Glpi/Dropdown/DropdownDefinitionTest.php
- src/Glpi/Asset/CustomFieldDefinition.php
- src/Glpi/CustomObject/AbstractDefinition.php
- templates/pages/admin/customobjects/main.html.twig
- templates/pages/assets/customfield.html.twig
- tests/cypress/e2e/Asset/asset_definition.cy.js
It seems that generic object dropdown may contains underscore in their name, and custom fields names may contain numbers. To ease their migration in GLPI, we could allow underscores in the custom assets/dropdowns system names and numbers in custom fields system names.
> Allow undescores and numbers in custom objects system names

- phpunit/GLPITestCase.php
- phpunit/functional/CronTaskTest.php
- phpunit/functional/InfocomTest.php
- src/Glpi/Kernel/Listener/InitializePlugins.php
- tests/src/autoload/functions.php
The current workaround of installing the tester plugin through the `loadDataset()` method is not good because it is done after the kernel is booted.
Thus, the call to `$Plugin::init()` was already make and the plugin is not taken into account by GLPI.
This is fixed by installing the plugin directly during the `InitializePlugins` process.
> Make sure the tester plugin is loaded in our phpunit tests

- inc/define.php
- It fixes !
by working on https://github.com/pluginsGLPI/genericobject/pull/420
and missing related components
- `itemdevicedrive_types`
- `itemdevicecontrol_types`
I realised that the appropriate declarations were missing for registering a class (from `genericobject` in my case)  on these components
> Fix(ItemDevice): add missing declaration from define.php

- phpunit/GLPITestCase.php
- src/Glpi/CustomObject/AbstractDefinitionManager.php
- src/Glpi/Dropdown/DropdownDefinitionManager.php
In #19033 , I had issues with the custom objects autoloader that was not able to find the created custom classes. I figured out that the registered autoloader was the one instanciated during the GLPI boot, due to the usage of `$this` (`spl_autoload_register([$this, 'autoloadClass']);`). Due to this, the `AssetDefinitionManager::unsetInstance();` had no effect on the cached definitions used by the autoloader.
I fixed it by always using the current instance in the custom objects autoloader.
I also simplified how the cache is handled, by removing a useless nesting level in the `$definitions_data` property.
> Fix custom object autoloader cache in testing context

- src/Glpi/Asset/AssetDefinition.php
When deleting a custom asset definition, it is preferable to first remove the custom assets themselves and then remove the custom models and types. Indeed, if types or models are removed first, GLPI will, for each of them, check if they are used and update each custom asset that use them to remove the relation. As long as the custom assets are going to be removed, updating them is useless.
> Reduce custom asset definition deletion time

- js/planning.js
- It fixes !36792
The refresh button disappeared when a new event was opened.
> fix(planning): refresh button lost when opening an event

- src/Glpi/Error/ErrorDisplayHandler/HtmlErrorDisplayHandler.php
fix 
An alternative could be to set the z-index to 1000 according to the Bootstrap doc:
```
$zindex-dropdown:                   1000;
$zindex-sticky:                     1020;
$zindex-fixed:                      1030;
$zindex-modal-backdrop:             1040;
$zindex-offcanvas:                  1050;
$zindex-modal:                      1060;
$zindex-popover:                    1070;
$zindex-tooltip:                    1080;
```
> remove z-index on error alerts

- src/ITILSolution.php
- It fixes !36494
A technician could see the solution of a ticket but not the documents attached to that solution if they did not have the "See my ticket" permission.
> fix(ITILSolution): document not visible

- CHANGELOG.md
- install/migrations/update_10.0.x_to_11.0.0/user.php
- src/Migration.php
- src/User.php
- tests/functional/Migration.php
The "Picture" search option for users has been redundant since the initial GLPI 10 release as the user avatars are shown in the Login column. The "Picture" search option only showed the uploaded pictures, showed broken images when none existed, and used legacy CSS styles.
This PR also adds a helper to the Migration class to cleanly remove search options from various places in the database including display preferences, saved searches and ticket templates.
> Remove redundant user picture search option

- .phpstan-baseline.php
- phpunit/functional/MassiveActionTest.php
- src/SavedSearch.php
- It fixes !36776
-  To use the massive action "Unset default" to delete a saved default search, you had to have the right to update the GLPI configuration. However, choosing a saved search by default is an individual choice ( visible only to the user ). Checking for update permission on the configuration is not necessary in this case.
> fix: Fix rights verification for updating saved searches via massive action

- phpunit/functional/Glpi/Inventory/Assets/NetworkEquipmentTest.php
- src/Inventory/Asset/InventoryNetworkPort.php
- It fixes !36928
- Introduce by https://github.com/glpi-project/glpi/pull/18443
With the introduction of non-dynamic `NetworkPort` in `NetworkPort` management, those marked as non-dynamic and not switched to dynamic mode are removed during inventory.
> Fix(Inventory): keep manual NetworkPort if non dynamic

- css/includes/_base.scss
- css/includes/components/_fileupload.scss
- css/includes/components/_networkport.scss
- css/includes/components/_select2.scss
- css/legacy/includes/_impact.scss
- css/palettes/_auror_dark.scss
- css/palettes/_darker.scss
- css/palettes/_midnight.scss
- js/src/vue/Debug/Toolbar.vue
- lib/bundles/tablericons-definitions.js
- package-lock.json
- package.json
- src/Impact.php
- src/Telemetry.php
- templates/components/itilobject/itilsatisfaction.html.twig
- templates/components/pager.html.twig
Upgrade Tabler to v1.0.0 stable. This PR only includes fixes for issues noticed after the upgrade. It doesn't address any potential new features that could be utilized.
> Upgrade Tabler to v1.0.0 Stable

- src/PendingReason_Item.php
- templates/components/itilobject/timeline/pending_reasons_messages.html.twig
- It's fixes !36212
- This PR changes the style once the wait reasons are more active
Pending Reason Done
Pending Reason Active
> Changes the style of the reasons for waiting completed

- css/includes/components/_select2.scss
- css/includes/components/form/_form-editor.scss
Fix two small UI issues following tabler update.
1\) Disable state on dropdowns:
Before:
After:
2\) Conditions input height:
Before:
After:
> Fix styles for forms after tabler update

- phpunit/functional/Glpi/Form/Condition/ConditionHandler/StringConditionHandlerTest.php
- phpunit/functional/Glpi/Form/Condition/EditorManagerTest.php
- src/Glpi/Form/Condition/ConditionHandler/StringConditionHandler.php
- src/Glpi/Form/Condition/ValueOperator.php
@orthagh notified us that this was a feature of formcreator so we must keep it.
> Helpdesk forms: support regex on strings conditions

- phpunit/functional/ContractTest.php
- src/Contract.php
- It fixes !36679
In the case of express renewal, the expiry date was identical to the end date.
As a reminder, the end date corresponds to the initial date + the initial duration.
The expiry date must also take account of the renewal. _This is already OK for tacit renewal._
> Fix(Contract): Expiration date for express renewal

- src/Appliance_Item_Relation.php
- src/Domain_Item.php
- src/Glpi/Application/View/Extension/I18nExtension.php
- src/Glpi/Application/View/TemplateRenderer.php
- src/Glpi/Asset/CustomFieldOption/ProfileRestrictOption.php
- src/Glpi/Form/QuestionType/QuestionTypeDropdown.php
- src/Glpi/RichText/RichText.php
- src/Html.php
- src/Impact.php
- src/Item_Disk.php
- src/ObjectLock.php
- src/Planning.php
- src/SLM.php
- src/Telemetry.php
- templates/pages/assistance/planning/planning.html.twig
Usages of the translation function in inlined templates should be prohibited. Indeed, these translations will not be extracted as expected by `xgettext` and most of them will be missing in our string sources. Some of them were not detected during the code review, see https://github.com/glpi-project/glpi/blob/ab015d906c135191d2d59649fe1b1a3b0912cd01/src/Glpi/Form/QuestionType/AbstractQuestionTypeShortAnswer.php#L115
To prevent this, I propose to remove the `__()`, `_x()`, `_n()` and `_nx()` functions from the Twig environment used to render inlined templates, in order to trigger an error when some of them are used in this context.
Example of an error trace:
```
Unknown "__" function in "__string_template__c0d9752debc559c2a90bffb6ffb290b3" at line 3.
In …
```
> Trigger an error when an inline template contains a translatable string

- src/Glpi/Form/Form.php
- tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
Fixes #19279
Ensure form description translation fallback returns an empty string to avoid errors
> fix(forms): ensure form description translation fallback returns an empty string

- templates/pages/admin/user/user.html.twig
Fixes #19234
Fix ID set in the user form. Previously it was always set to the current user's ID even when the form wasn't the "My Settings" one which resulted in the wrong ID being used. For adding users, having the ID set would trigger the cloning feature and clone any data not specified in the form submission from the current user including profile assignments.
> Prevent triggering cloning feature when adding new user

- src/Plugin.php
Wrong icon used since changing from FA icon to Tabler
> Fix icon for plugin to enable

- src/Glpi/Form/QuestionType/AbstractQuestionTypeShortAnswer.php
- src/Glpi/Form/QuestionType/QuestionTypeShortText.php
- tests/cypress/e2e/form/form_translation.cy.js
Adding translation support for default values of short answer questions.
> feat(forms): add translation support for default values of short answer questions

- src/DisplayPreference.php
When using the "Reset to default" action in the new "Search result display" setup tab, 
If the selected itemtype has more than one interface, this generates an error "Update would change too many rows!".
> fix(displaypreference): add interface for reset option

- templates/pages/admin/form/access_control/allow_list.html.twig
There was a warning on this tab even if no modification were made due to a script triggering a change event on a dropdown when the tab is loaded.
> Prevent false positive "unsaved changed" warning on access control tab

- phpunit/functional/Glpi/Form/AccessControl/ControlType/AllowListTest.php
- phpunit/functional/Glpi/Form/AccessControl/ControlType/DirectAccessTest.php
- phpunit/functional/Glpi/Form/AccessControl/FormAccessControlManagerTest.php
- phpunit/functional/Glpi/Form/AccessControl/FormAccessControlTest.php
- phpunit/functional/Glpi/Form/Export/FormSerializerAccessPoliciesTest.php
- phpunit/functional/Glpi/Form/FormTest.php
- phpunit/functional/Glpi/Form/ServiceCatalog/ServiceCatalogManagerTest.php
- phpunit/functional/Glpi/Helpdesk/Tile/TilesManagerTest.php
- phpunit/functional/LogTest.php
- src/Glpi/Form/Export/Serializer/FormSerializer.php
- src/Glpi/Form/Form.php
- src/Glpi/Form/Migration/FormMigration.php
- src/Glpi/Helpdesk/DefaultDataManager.php
- tests/cypress/e2e/ajax_controller.cy.js
- tests/cypress/e2e/form/access_policies/access_control.cy.js
- tests/cypress/e2e/form/access_policies/direct_access.cy.js
- tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
- tests/src/FormBuilder.php
- tests/src/FormTesterTrait.php
-> Existing tests have been updated.
Forms are now created with the following default access policies:
It is possible to prevent this initialization using a special `_init_access_policies = false` input value.
This is mainly used for tests, and may be used by future plugins or API calls if needed.
The existing `_do_not_init_sections` input value was renamed to `_init_sections` to be consistant with this new parameter.
> Init form access policies on creation

- install/migrations/update_10.0.x_to_11.0.0/form.php
- install/mysql/glpi-empty.sql
- phpunit/functional/Glpi/Form/Destination/FormDestinationManagerTest.php
- phpunit/functional/Glpi/Form/Destination/FormDestinationTest.php
- phpunit/functional/Glpi/Form/Export/FormSerializerDestinationTest.php
- phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
- src/Glpi/Form/AnswersHandler/AnswersHandler.php
- src/Glpi/Form/Destination/FormDestination.php
- src/Glpi/Form/Destination/FormDestinationManager.php
- src/Glpi/Form/Export/Serializer/FormSerializer.php
- src/Glpi/Form/Export/Specification/DestinationContentSpecification.php
- src/Glpi/Form/Form.php
- src/Glpi/Form/Migration/FormMigration.php
- src/Glpi/Helpdesk/DefaultDataManager.php
- templates/pages/admin/form/form_destination.html.twig
- tests/cypress/e2e/form/editor/conditions.cy.js
- tests/src/FormBuilder.php
- tests/src/FormTesterTrait.php
As discussed with @orthagh:
* A form is still initialized with one ticket to create but it can now be removed or conditioned.
* If all items to create have been removed, a warning is shown.
* If all items to create are conditioned, a warning is shown.
Fix #19292.
> Remove mandatory destinations; show warning instead

- src/Html.php
- src/ProjectTask.php
- templates/components/datatable.html.twig
- Project tasks sublist massive action button class changed to secondary - fix #19008
> Project tasks sublist massive action button class changed to secondary - fix #19008

- phpunit/functional/TicketTest.php
- src/CommonITILObject.php
- It fixes !37145
- When a location is deleted and the user chooses to replace all objects assigned to that location with another one, the change takes place for tickets, except closed tickets.
Before replacement:
During replacement:
After replacement:
> fix(ticket): location of closed ticket isn't updated when replaced

- front/dropdown.common.form.php
Calling `loadDropdownForm` with something else than null will throw a depreciation message; default was wrong.
> Fix false depreciation message

- tests/cypress/e2e/maintenance.cy.js
The maintenance controller will handle all requests when GLPI is in maintenance mode.
However, due to the default firewall strategies changes in GLPI 11, the controller is only accessible for logged-in users.
This create a redirection loop for unauthenticated users (login page -> maintenance -> login page -> maintenance -> ...).
Fixed by adding the correct firewall strategy to the maintenance controller and adding a very small test that make sure the maintenance page is working for unauthenticated users.
> Fix maintenance redirection loop

- tools/build_glpi.sh
"composer-dependency-analyser.php" is not needed in the build.
> fix(build): remove composer-dependency-analyser

- phpunit/functional/UserTest.php
- src/User.php
- It fixes !37139 linked to !34567
The getFriendlyNameFields() function takes care of constructing a query expression to retrieve a user's name.
It works as follows: 
- If name and surname are filled in, a concatenation of the two is returned.
- If neither is filled in, the login is returned.
- If only one of the two is filled in, we return the login.
But we should return the first name if it's the only one filled in, and the same for the last name.
IMHO i consider this to be a bug fix, rather because :
- The current behavior is not intuitive and does not correspond to what one would expect from a user interface.
- The aim is to adjust existing conditional logic, not to add new functionality. …
> Fix - getFriendlyNameFields() query to return only first name if only one is defined

- src/Profile.php
-> Existing tests should cover it. 
I noticed that some simple phpunit cases were a bit too slow:
8s for some basics tests is way too much.
After investigations, I found that it was entirely caused by the profile creation process, which is executed like this in a few of the test cases:
```php
$profile = $this->createItem(Profile::class, [
'name' => 'Helpdesk profile',
'interface' => 'helpdesk',
]);
```
The `Profile::post_addItem()` process is the culprit as it triggers 1000+ SQL requests and iterate on 25000+ rows of data.
This is because this process need to initialize ~100 rows in the `glpi_profile_rights` table, which trigger a lot of "framework callback hell" as each row lead to some extra process (post_add/post_update/post_getempty callback, rights checks, cache being set and reset …
> Speed up profile creation

- phpunit/functional/RuleAssetTest.php
- src/RuleAsset.php
- It fixes !37215
With this rule:
Prevent this SQL error where user is not in any group:
> fix(business rule): first group of user without group

- phpunit/functional/Glpi/Form/AccessControl/FormAccessControlManagerTest.php
- src/Glpi/Form/AccessControl/ControlType/AllowList.php
- src/Glpi/Form/AccessControl/ControlType/ControlTypeInterface.php
- src/Glpi/Form/AccessControl/ControlType/DirectAccess.php
- src/Glpi/Form/AccessControl/FormAccessControlManager.php
- tests/cypress/e2e/form/form_plugins.cy.js
- tests/fixtures/plugins/tester/setup.php
- tests/fixtures/plugins/tester/src/Form/DayOfTheWeekPolicy.php
- tests/fixtures/plugins/tester/src/Form/DayOfTheWeekPolicyConfig.php
- tests/fixtures/plugins/tester/templates/day_of_the_week_policy.html.twig
* Allow plugins to define their own access policies.
* Refactor the `ControlTypeInterfame::getWarnings()` method to remove the `warnings` parameter.
> Forms: allow plugins to define custom access policies

- phpunit/functional/SearchTest.php
- src/Appliance.php
- src/Search.php
- Complete this PR : #13684
If the purpose of the search is to verify whether an item of type ‘itemtype1’ is related to an item of type ‘itemtype2’ (e.g: computer and application) and that this relationship is saved in a table via a pair (‘items_id’, ‘itemtype’), the target field in the relational table will not be `items_id` but `itemtype2_id`. This will result in an error, because the `itemtype2_id` does not exist. To resolve this issue, the name of the target field must be explicitly declared in order to correctly retrieve the ID of `itemtype'.
Default view:
Before
After:
In the example, I try to retrieve all tickets that do not contain a tag from the tag plugin.
This PR complements this PR: https://github.com/pluginsGLPI/tag/pull/230
> search option: fix negative conditions

- src/NetworkPort.php
closes #18845
Code was retrieved from FI plugin when migrating inventory to GLPI v10; but this particular part of code seem already dead in GLPI 0.85.
> Remove code that did not work for a while

- phpunit/functional/PasswordHistoryTest.php
- src/PasswordHistory.php
Fix calls to `PasswordHistory::updatePasswordHistory` with an empty value for the password. Having a missing password is normal for local users if the user is created without setting a password. As far as I can tell, it has never been required to set a password for a new user and although the checkbox to send an email to the user to set their password forces a random password, it doesn't seem to have any use because login attempts with an empty password are blocked in `Auth::validateLogin` anyways.
> Fix password history with empty previous password

- src/CommonDBChild.php
- src/UserEmail.php
- templates/pages/admin/user/user.html.twig
- tests/cypress/e2e/Admin/user.cy.js
Added missing CSRF field in user configuration and preferences.
Added an E2E test that verifies the addition of e-mails.
Improved accessibility on this point.
> fix: Adding missing CSRF tokens for users preferences page + enhance accessibility

- phpunit/functional/Glpi/Csv/PlanningCsvTest.php
Just a quick test for #11406. Success on main branch, and fail on 10.0 with the following:
```
GLPI dataset version 4.11 already loaded
PHPUnit 9.6.22 by Sebastian Bergmann and contributors.
..F                                                                 3 / 3 (100%)
Time: 00:00.847, Memory: 50.00 MB
There was 1 failure:
1) tests\units\Glpi\Csv\PlanningCsvTest::testGetFileContent
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
0 => Array (...)
1 => Array (
'actor' => '_test_user'
-        'title' => 'ticket \d\rtitle'
+        'title' => 'ticket d\r
+        title'
'itemtype' => 'Ticket task'
'items_id' => 17
'begindate' => '2024-10-09 06:37:36'
@@ @@
)
2 => Array (
'actor' => '_test_user'
-        'title' => 'ticket \d\rtitle'
+        'title' => 'ticket d\r …
```
> Test CSV export with a carriage return; closes #11406

- install/migrations/update_10.0.x_to_11.0.0/logs.php
- install/mysql/glpi-empty.sql
- phpunit/functional/ConfigTest.php
- phpunit/functional/LogTest.php
- src/Log.php
- It fixes https://github.com/glpi-project/glpi/pull/19140
Add two `new_id` and `old_id` columns to the `glpi_logs` table to optimize table searches
> Add old_id and new_id col in glpi_logs table

- phpunit/functional/CommonDBTMTest.php
- src/CommonDBTM.php
- It fixes !37274
When a template is updated, the uniqueness check is performed, whereas adding a new template does not trigger it.
> Prevent unicity from template on update

- src/Glpi/Application/View/Extension/FrontEndAssetsExtension.php
If the database configuration files exists but targets an empty database (no tables at all), the error page is not correctly displayed, because it generates a subsequent error while trying to get the `custom_css` configuration from the root entity.
I propose to add a check to prevent the error page to failed to be displayed propertly.
After:
Before:
> Fix error page display when database is corrupted

- phpunit/LDAP/AuthLdapTest.php
- src/User.php
- It fixes !36835
When a user is added to a group via an LDAP authorization rule, the group is not automatically removed if the user no longer meets the rule's criteria due to a change in LDAP attributes.
> Fix group not deleted for LDAP user

- css/includes/_includes.scss
- css/includes/components/form/_helpdesk-home-config-for-empty-entity.scss
- js/glpi_dialog.js
- js/modules/Helpdesk/HelpdeskConfigForEmptyEntityController.js
- phpunit/functional/Glpi/Helpdesk/DefaultDataManagerTest.php
- phpunit/functional/Glpi/Helpdesk/Tile/TilesManagerTest.php
- src/Entity.php
- src/Glpi/Controller/Config/Helpdesk/CopyParentEntityController.php
- src/Glpi/Helpdesk/DefaultDataManager.php
- src/Glpi/Helpdesk/Tile/TilesManager.php
- src/Glpi/Session/SessionInfo.php
- src/Profile.php
- src/Session.php
- templates/pages/admin/helpdesk_home_config.html.twig
- templates/pages/admin/helpdesk_home_config_for_empty_entity.html.twig
- templates/pages/admin/helpdesk_home_config_tiles.html.twig
- tests/cypress/e2e/self-service/home_config.cy.js
- tests/cypress/support/commands.js
Allow the helpdesk home page to be configured by entity.
The first commit is from #19321, which should be merged first (wait for it to be merged before reviewing).
Config on an entity;
Config on a profile:
On an entity that does not have any values, we should the parent values instead:
The two actions allow to define your own values for this entity (starting from an empty list of tiles or from a copy of the parent tiles).
> Helpdesk home page config for entities

- js/common.js
- js/modules/Forms/EditorController.js
- templates/components/itilobject/timeline/pending_reasons.html.twig
- templates/pages/admin/form/access_control/allow_list.html.twig
- templates/pages/admin/form/form_editor.html.twig
First commit fix the #19370 issue ("Save and preview" button didn't save the changes).
Note that there is no E2E tests on this feature as the preview open inside a new browser tab and cypress can't deal with that (will be possible with playwright tho).
Second commit improve the unsaved form state detection (which changes the "Preview" button into the "Save and preview" button).
This is done by watching for a specific custom event that we trigger when `window.glpiUnsavedFormChanges` is changed, instead of the original code which was watching for changes every 0.5s.
To make it possible `window.glpiUnsavedFormChanges` must no longer be interacted with directly, instead you should use the new `setHasUnsavedChanges()` method.
> Fix save and preview

- phpunit/functional/Glpi/Form/Destination/FormDestinationManagerTest.php
- src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
- src/Glpi/Form/Destination/FormDestinationChange.php
- src/Glpi/Form/Destination/FormDestinationManager.php
- src/Glpi/Form/Destination/FormDestinationProblem.php
- src/Glpi/Form/Destination/FormDestinationTicket.php
- templates/pages/admin/form/form_destination.html.twig
- templates/pages/admin/form/form_destination_actions.html.twig
- templates/pages/admin/form/form_destination_commonitil_config.html.twig
- tests/cypress/e2e/form/form_plugins.cy.js
- tests/fixtures/plugins/tester/setup.php
- tests/fixtures/plugins/tester/src/Form/ComputerDestination.php
- tests/fixtures/plugins/tester/templates/computer_destination.html.twig
- tests/src/Form/Destination/AbstractCommonITILFormDestinationType.php
Allow form destinations to be defined by plugins.
> Forms: allow plugins to define their own destinations types

- install/migrations/update_10.0.x_to_11.0.0/form.php
- install/mysql/glpi-empty.sql
- js/modules/Forms/ServiceCatalogController.js
- phpunit/abstracts/SortStrategyTestCase.php
- phpunit/functional/Glpi/Form/ServiceCatalog/ServiceCatalogManagerTest.php
- phpunit/functional/Glpi/Form/ServiceCatalog/SortStrategy/AlphabeticalSortTest.php
- phpunit/functional/Glpi/Form/ServiceCatalog/SortStrategy/PopularitySortTest.php
- phpunit/functional/Glpi/Form/ServiceCatalog/SortStrategy/ReverseAlphabeticalSortTest.php
- src/Glpi/Controller/ServiceCatalog/IndexController.php
- src/Glpi/Controller/ServiceCatalog/ItemsController.php
- src/Glpi/Form/AnswersHandler/AnswersHandler.php
- src/Glpi/Form/Category.php
- src/Glpi/Form/Form.php
- src/Glpi/Form/ServiceCatalog/ItemRequest.php
- src/Glpi/Form/ServiceCatalog/ServiceCatalogManager.php
- src/Glpi/Form/ServiceCatalog/SortStrategy/AbstractSortStrategy.php
- src/Glpi/Form/ServiceCatalog/SortStrategy/AlphabeticalSort.php
- src/Glpi/Form/ServiceCatalog/SortStrategy/PopularitySort.php
- src/Glpi/Form/ServiceCatalog/SortStrategy/ReverseAlphabeticalSort.php
- src/Glpi/Form/ServiceCatalog/SortStrategy/SortStrategyEnum.php
- src/Glpi/Form/ServiceCatalog/SortStrategy/SortStrategyFactory.php
- src/Glpi/Form/ServiceCatalog/SortStrategy/SortStrategyInterface.php
- templates/pages/self-service/service_catalog.html.twig
- tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
- tests/src/FormBuilder.php
- tests/src/FormTesterTrait.php
This pull request includes several changes to enhance the functionality of the GLPI forms and service catalog. The main updates involve adding a new field to track form usage and implementing a sorting strategy for service catalog items.
> Form service catalog items order enhancement

- phpunit/functional/Glpi/Asset/AssetModelTest.php
- phpunit/functional/Glpi/Asset/AssetTypeTest.php
- src/CommonDBTM.php
- src/CommonDropdown.php
This fixes 2 errors preventing the deletion of an asset model/type used in at least one asset.
First, an error preventing the replacement dropdown to be shown.
```
glpi.WARNING:   *** User Warning: Cannot instanciate "Glpi\Asset\AssetModel" as it is an abstract class. at DbUtils.php line 536
Backtrace :
./src/DbUtils.php:536                              
./src/autoload/dbutils-aliases.php:147             DbUtils->getItemForItemtype()
./src/Dropdown.php:113                             getItemForItemtype()
./src/CommonDropdown.php:660                       Dropdown::show()
.../Glpi/Controller/DropdownFormController.php:128 CommonDropdown->showDeleteConfirmForm()
...c/Glpi/Controller/DropdownFormController.php:67 Glpi\Controller\DropdownFormController::loadDropdownForm() …
```
> Fix deletion of a used asset model/type

- js/modules/Forms/FieldDestinationAssociatedItem.js
- src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php
-> Covered by existing tests.
The `associated_items.cy.js` is the most common test that randomly fails on the CI so I decided to take a look at it.
It turns out it is actually not the test that is flaky, but dropdowns inside GLPI that are not correctly initialized.
This is caused by some JS cause that use an UUID as a `rand` value:
The ajax response truncate it because `rand` is supposed to be an integer:
So `1a181201-df8c-4ae2-bfd2-d6e92a9d18dc` becomes `1` and as you can imagine this can quickly lead to conflicts as we add more and more dropdowns on the associated items config page.
This is fixed by my second commit.
The first commit fix a sorting issue that didn't affect the CI but was causing error locally if you were on MySQL (the CI is on MariaDB) due to some differences in how JSON …
> Fix associated_items.cy.js

- front/cron.php
- phpunit/bootstrap.php
- phpunit/functional/Glpi/Toolbox/VersionParserTest.php
- phpunit/functional/ImpactTest.php
- phpunit/imap/MailCollectorTest.php
- src/Glpi/Http/Listener/CheckIfUpdateNeededListener.php
- src/Glpi/Kernel/Listener/CustomObjectsAutoloaderRegistration.php
- src/Glpi/Kernel/Listener/InitializePlugins.php
- src/Glpi/Kernel/Listener/PostBootListenerTrait.php
- src/Glpi/Toolbox/VersionParser.php
- src/Plugin.php
- src/Update.php
- tests/bootstrap.php
It fixes #19250.
The checks based on `SKIP_UPDATES` in the post boot listeners were wrong. Indeed, they were considering a totaly empty DB as a available and it results in errors when trying to init plugins or load custome objects definitions.
I fixed this, and I changed a bit the `SKIP_UPDATES` behaviour. Now, it will not allow to skip the update when a new intermediate/major version is available. Indeed, it is probably a bad idea to allow skipping and intermediate/major update, as it often contains structural changes in the DB.
Now the behaviour changed, I wonder if we should not replace `defined('SKIP_UPDATES')`  checks by `GLPI_ENVIRONMENT === 'development'`, to be sure to be able to use this behaviour only in dev environment, and to be sure to have the same behaviour on all …
> Fix `SKIP_UPDATES` handling during GLPI boot

- install/update.php
During the update process, when the missing key file is missing, a specific page is displayed to propose ask the user what should be done (ignore and regenerate a new key, or wait for him to manually restore its key file and retry).
This form had no CSRF token, and submitting it was resulting in a 403 error.
> Fix missing CSRF in update process

- phpunit/functional/Glpi/Form/Translation/FormTranslationTest.php
- src/Glpi/Form/Section.php
- tests/src/FormBuilder.php
- tests/src/FormTesterTrait.php
It fixes #19369
Since it is now possible to define a horizontal layout for questions and comments on a form, the method used to retrieve elements has changed signature.
The method that retrieves elements for translation has not been modified accordingly.
> fix(forms): Fixed how translation handlers are retrieved to work with horizontal layout

- js/glpi_dialog.js
- tests/cypress/e2e/self-service/home_config.cy.js
Noticed with Forms that HTML content wasn't handled properly for JS toast messages when using it in an aria-label attribute. It wasn't escaped, but also the label is completely redundant and would be annoying for screen reader users. Change was added in #19355.
The way it was, as soon as the message appeared the screen reader would announce:
1. The message content
2. The message title
3. The close button
4. The message content
> Remove redundant aria label for JS toast messages

- css/includes/_base.scss
Deduct a few css variables for header in self-service portal
Important note, this relies on [css-relative-colors](https://caniuse.com/css-relative-colors) feature. It's widely supported but quite recent.
I didn't change the manually set variables in our theme, so in the default case, it's invisible.
The proposed change exists just for the few instances using a custom themes (and they will need to adapt anyway for GLPI 11).
So i though it was ok to use this css feature early.
Example with a customer theme (maybe not the best example ^^) without declaring manualy the variables.
> make a default gradient for helpdesk header

- phpunit/functional/LockedfieldTest.php
- src/CommonDBTM.php
- It fixes !37330
Currently,` Global Locks` on fields such as the computer `Name` incorrectly prevent agents from importing data even when creating new objects.
Real-world examples:
A `Computer` object is created by an agent, but the `Name` field remains empty because it is globally locked.
This behavior is inconsistent: `Global Locks` are meant to preserve existing manually entered data, but they should not block the initial population of fields during new object creation.
Proposed Solution
This PR adjusts the application logic so that` Global Locks`:
- Are enforced only for existing objects in GLPI.
- Do not block field values during the creation of new objects, even if a global lock is active on that field.
:information_source:  This first …
> Fix(Inventory): Do not handle lock on add

- src/RuleRightCollection.php
- It fixes !37278
When attempting to test the GLPI rule engine for the criterion `authentication type is AD directory`, an error is displayed. 
This error occurs because, at this point, we simply do not have the LDAP directory data to perform an `ldap_read` (although this data is correctly provided during the authentication phase). 
During engine tests, we merely want to test in the "context" of LDAP authentication, without the need to initiate an `ldap_read`.
After correcting this part, I encountered the following error,
stemming from two issues: an extra foreach loop relative to the data provided by the engine, 
``` 
Array
(
[0] => Array
(
[0] => 0 //entities_id
[1] => 1 //is_recursive
)
)
```
and incorrect display regarding recursivity, as …
> Fix(Ruleright): fix test engine

- src/Glpi/Controller/InstallController.php
- src/Glpi/Kernel/Listener/RequestListener/CheckDatabaseStatusListener.php
- templates/install/install.install_required.html.twig
In GLPI < 11.0, when the configuration file was missing, the following behaviours were applied:
- if the user go to the root URL (`/` or `/index.php`), it is redirected to the installation page;
- if the user go to any other URL, the `GLPI seems to not be configured properly.` error message is displayed.
In GLPI 11.0, the redirection from the root URL is no longer present, as we decided to remove it to have a common behaviour for all pages. Having an error page does not seems normal if the administrator is trying to start the installation process as [documented](https://glpi-install.readthedocs.io/en/latest/install/wizard.html), but it may be important to indicate that there is an issue with the installation file if GLPI is supposed to be already installed.
I propose to replace this error …
> Add a proper "install required" page

- phpunit/functional/LockedfieldTest.php
- src/CommonDBTM.php
- It fixes !37320
- If a field in an asset dynamic is locked and you want to replace its value, the value of the field was deleted instead of being replaced.
Location before replace
Replace
Location after replace
> fix(lockfield): replace dropdown value don't replace locked fields

- src/CronTask.php
- src/Glpi/Controller/IndexController.php
- templates/pages/login.html.twig
All the existing logic is still kept the same, same order of execution, etc.
But instead of relying on the old `Html::redirect` code, we return properly set `RedirectResponse`, and the TOTP part is still rendered in a `HeaderlessStreamedResponse` for consistency (and for it to still work, basically...).
The changes in the spaces and indentation are just here because now we can decrease the indentation level thanks to early returns, reduces cognitive load when reading the code 👌
Note: existing controllers still using `HeaderlessStreamedResponse` or `StreamedResponse` will need refactoring in order to be testable by #19093
> Simplify IndexController's handling to not break execution in testing

- templates/components/datatable.html.twig
- templates/components/dropdown/limit.html.twig
- templates/components/form/basic_inputs_macros.html.twig
- templates/components/form/buttons.html.twig
- templates/components/form/fields_macros.html.twig
- templates/components/form/header.html.twig
- templates/components/form/item_itilobject_item_list.html.twig
- templates/components/pager.html.twig
- templates/components/search/controls.html.twig
- templates/components/search/display_data.html.twig
- templates/components/search/query_builder/criteria.html.twig
- templates/components/search/query_builder/search_option.html.twig
- templates/components/user/picture.html.twig
- templates/generic_show_form.html.twig
- templates/layout/parts/menu.html.twig
- templates/pages/management/document_item.html.twig
Fixes to display main dashboard, computers list, computer form and (almost) all its standard tabs.
Goal is to quick fix several generic issues detected when enabling Twig strict variables. In case of doubt on one change, it can be reverted to be reviewed later.
> First buch of Twig templates fixes

- src/OAuthClient.php
- templates/pages/setup/oauthclient.html.twig
Fix probably copy/pasted variables
Following error is displayed when no scope is provided (`""` stored in database):
> Scopes is expected to be an array

- src/Html.php
- templates/components/itilobject/fields_panel.html.twig
- templates/components/notepad/form.html.twig
- tests/cypress/e2e/entity_notes.cy.js
- It fixes #19249
Display on tickets of linked documents to an entity's notes.
> fix: Missing attachments in entity notes

- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php
- src/Glpi/Form/Destination/CommonITILField/EntityField.php
- src/Glpi/Form/Destination/CommonITILField/ITILActorField.php
- src/Glpi/Form/Destination/CommonITILField/ITILCategoryField.php
- src/Glpi/Form/Destination/CommonITILField/LocationField.php
- src/Glpi/Form/Destination/CommonITILField/RequestTypeField.php
- src/Glpi/Form/Destination/CommonITILField/UrgencyField.php
- src/Glpi/Form/Destination/CommonITILField/ValidationField.php
- src/Glpi/Form/Migration/FormMigration.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
- src/Glpi/Migration/AbstractPluginMigration.php
Should fix #19362 
Improve form migration by handling null values for mapping and updating horizontal rank to match the new sorting system.
> fix(forms-migration): Add null handling for mapped items and update horizontal rank

- templates/components/datatable.html.twig
Introduced by change to revert `Rule` class changes while working on #19495
> row_massiveactions used before its declaration

- CHANGELOG.md
- front/cron.php
- front/massiveaction.php
- front/rule.common.php
- phpunit/functional/Glpi/Inventory/Assets/OperatingSystemTest.php
- src/Glpi/Controller/LegacyFileLoadController.php
- src/Glpi/Marketplace/View.php
- src/Glpi/Search/Output/Spreadsheet.php
- src/Html.php
- src/Item_Devices.php
- src/Item_Rack.php
- src/MassiveAction.php
- src/RuleCollection.php
- src/RuleDictionnaryDropdownCollection.php
- src/RuleDictionnaryPrinterCollection.php
- src/RuleDictionnarySoftwareCollection.php
- src/Software.php
- src/Toolbox.php
The proposed changes should permit to limit the usage of streamed responses to the endpoints that actually really require it.
These changes will also permit:
- to detect unexpected `flush()`/`ob_flush()`/`ob_clean()`/`ob_end_clean()` operations;
- to add the Symfony profiler in all GLPI pages, unless an `exit()`/`die()` instruction is used.
It is still possible to use a `flush()` operation to flush the current buffer to the browser, do some processing, and then redirect the request. It will not be detected as the redirection in a legacy script stops the execution before the output content is actually converted to a response. I had to use this for massive actions and rules replay progress bar, but both of them should be refactored later to use the new progress indicator system.
It should …
> Stream only specific responses

- phpunit/functional/Glpi/Http/FirewallTest.php
- src/Glpi/Controller/Plugin/LogoController.php
- src/Glpi/Http/Firewall.php
- src/Glpi/Marketplace/View.php
Replaces #18811.
In the marketplace view, when the plugin directory contains a `logo.png` file, it will be used to display the plugin logo instead of fetching it from the remote URL provided by the marketplace API.
1. This permit to display a logo for local plugins that are not available throught the marketplace.
2. This prevent requests to remote servers that can be an issue is securized contexts.
To prevent anyone to use the new controller to discover if a plugin is present on a GLPI instance, I introduced a new "admin access" firewall strategy. Plugins logos will be available only to GLPI administrators.
> Display plugin local logo files in the marketplace

- index.html
When the webserver document root is not configured properly, if someone tries to access the index path (e.g. `http://glpi.example.com/`), a default 404 error will be displayed.
I propose to add an `index.html` fallback page to be displayed in this case. This file name corresponds to a default value handled by [Apache](https://httpd.apache.org/docs/trunk/getting-started.html#content), [IIS](https://learn.microsoft.com/en-us/troubleshoot/developer/webapps/iis/www-modules-features/configure-default-document-iis) and [NGINX](https://nginx.org/en/docs/http/ngx_http_index_module.html).
If the webserver is correctly configured, accessing the `/index.html` path will result in a GLPI error page with a 404 status code.
> Display a dedicated page when webserver is misconfigured

- js/src/vue/Debug/Toolbar.vue
- js/src/vue/Debug/Widget/SQLRequests.vue
The Monaco library is supposed to only be loaded just-in-time and instead a smaller JS script gets loaded to expose some functions which in turn load the full library when called. In debug mode, the smaller MonacoEditor script is always included in debug mode which isn't an issue. The issue is that the debug toolbar immediately tries colorizing the SQL queries as soon as it loads and as soon as new AJAX requests are completed. If you aren't looking at the SQL requests in the debug bar, it is a wasted 2MB network transfer (if not using cache) on every page.
This PR moves the colorization logic to the SQL Requests widget. Now, the debug toolbar will only load the full library if you open the SQL requests widget or a widget that creates an editor (Globals tabs in HTTP Requests widget).
> Prevent immediate debug mode Monaco load

- install/empty_data.php
- install/migrations/update_10.0.x_to_11.0.0/form.php
- install/mysql/glpi-empty.sql
- js/modules/DynamicDropdownController.js
- phpunit/functional/EntityTest.php
- src/Entity.php
- src/Glpi/Application/View/Extension/IllustrationExtension.php
- src/Glpi/Controller/UI/Illustration/CustomSceneController.php
- src/Glpi/UI/IllustrationManager.php
- templates/components/illustration/custom_icon.html.twig
- templates/components/illustration/icon.svg.twig
- templates/pages/admin/helpdesk_home_custom_scene_config.html.twig
- templates/pages/helpdesk/index.html.twig
- tests/cypress/e2e/self-service/home_config.cy.js
Allow administrators to configure custom images for the helpdesk home page:
> Configure helpdesk home page illustration

- js/modules/Forms/Condition/Engine.js
- js/modules/Forms/RendererController.js
- tests/cypress/e2e/form/form_rendering.cy.js
- tests/cypress/support/commands/form.js
Fix #19490, make sure a form can't be submitted if mandatory questions are not filled.
This is only validated on the client, I'd like to add server side validation too but I'll do it another PR (or someone else, I'll add it to the backlog).
> Client side validation for mandatory questions

- phpunit/functional/RuleTicketTest.php
- phpunit/functional/SlaLevel_TicketTest.php
- src/CommonITILObject.php
- src/ITILFollowup.php
- It fixes !36815
From `Escalation Level` or from  `Ruleticket`
Although we have an action configured to disregard delay calculations `takeintoaccount_delay_stat => do_not_compute`, the 'itilfollowup_template' action still triggers the computation of the delay state.
The `post_addItem` method of the `ITILFollowup` class updates the last modification date of the parent item.
```php
// Check if stats should be computed after this change
$no_stat = isset($this->input['_do_not_compute_takeintoaccount']);
$parentitem = $this->input['_job'];
$parentitem->updateDateMod(
$this->input["items_id"],
$no_stat,
$this->input["users_id"]
);
```
However, the `prepareInputForAdd()` method never retrieves the `_do_not_compute_takeintoaccount` key, even when it …
> Fix(TicketRule): do not compute takeintoaccount if needed

- src/Glpi/Api/HL/Controller/AssetController.php
- src/Glpi/Api/HL/Controller/ITILController.php
- src/Glpi/Api/HL/Controller/ManagementController.php
- src/Glpi/Api/HL/Controller/ProjectController.php
One of the issues with the legacy API was not knowing what certain hard-coded integers meant for things like ticket status, priority, etc. The new API at least showed the possible values but OpenAPI doesn't support labels for enum values. This PR adds the information as a description for the properties.
A new PHPUnit test will enforce that all `enum` properties with the Integer type have a description.
> [HLAPI] Add descriptions for enums

- front/login.php
- src/Glpi/Controller/IndexController.php
- templates/pages/login.html.twig
Many years ago, the login field names were randomized for "security". This doesn't make any sense to me and I don't know of any security recommendations that say this should be done. Also, the login field IDs were always the same and so are the labels so this doesn't even obscure the fields (which isn't real security anyways). Anyone with competence (or AI for people with none) could figure out how to parse the HTML to get the field names.
Even if the original intention was valid for security, we have used CSRF tokens for a while now which probably cover whatever the original concern was.
> Simplify login field names

- phpunit/functional/SupplierTest.php
- src/Supplier.php
- It fixes !37406
- In GLPI version 9.5, it was possible to clone suppliers. This RP re-implements this functionality.
> fix(supplier): restore 'Clone' MA for supplier

- package-lock.json
- package.json
- phpunit/functional/Glpi/UI/IllustrationManagerTest.php
- Last (and probably final for this release) batch of icons
- extracted from the new website and adapted to our colors.
> update illustrations to 0.5.3

- src/Glpi/Controller/AbstractController.php
This is no longer necessary as the `flush()` operation that was present in the `Html::header()` method has been removed.
> Do not use output buffering when rendering a page

- phpunit/functional/ContactTest.php
- src/Contact.php
It fixes !37406
In GLPI version 9.5, it was possible to clone contact. This RP re-implements this functionality.
Complete : https://github.com/glpi-project/glpi/pull/19484
> fix(contact): restore 'Clone' MA for contact

- phpunit/functional/Document_ItemTest.php
- src/PDU.php
- src/autoload/CFG_GLPI.php
- It fixes !37442
add `component` to `PDUs`
Some code have already done not working (missing `CFG_GLPI` and `searchoption` declaration)
> Feat(PDU): add components to PDUs

- .phpstan-baseline.php
- composer.json
- composer.lock
- front/_check_webserver_config.php
- front/cron.php
- phpstan.neon.dist
- src/CommonITILObject.php
- src/CronTask.php
- src/Glpi/Application/ResourcesChecker.php
- src/Glpi/Http/Response.php
- src/Glpi/Kernel/Kernel.php
- src/MassiveAction.php
- tools/src/PHPStan/ForbidExitRule.php
- tools/src/PHPStan/ForbidHttpResponseCodeRule.php
This provides some rules to detect usages of PHP functions that can cause issues.
- I changed a bit the `Massive` actions code to use `return` instructions of to throw exceptions.
- I marked legitimate usages with a `phpstan-ignore` comment.
- Remaining usages were added to the baseline. The corresponding code should be refactored to use a `Symfony\Component\HttpFoundation\Response`.
> Add PHPStan rules to forbid some PHP functions

- phpunit/functional/LocationTest.php
- src/CommonTreeDropdown.php
Fix small mistake from #19556. Most classes do in fact use `__CLASS__` to add their own extra tabs, but `CommonTreeDropdown` is abstract and this was causing GLPI to try to get an item for an abstract itemtype:
```
[2025-04-28 18:02:16] glpi.WARNING:   *** User Warning: Cannot instanciate "CommonTreeDropdown" as it is an abstract class. at DbUtils.php line 537
```
The safest replacement for `$this::getType()` is `static::class` as it is the exact same functionality.
`$this::getType()` -> `static::class`
`$item::getType()` -> `$item::class`
> Fix tree dropdown tabs

- src/DeviceGraphicCard.php
- src/DeviceHardDrive.php
- src/DeviceMemory.php
- src/DeviceMotherboard.php
- src/DeviceNetworkCard.php
- src/DevicePci.php
- src/DevicePowerSupply.php
- src/DeviceProcessor.php
- src/DeviceSoundCard.php
- It fixes !37442
add mising 'serial' and 'otherserial' for  `rawSearchOptionsToAdd()` function when available from relation table
> Fix(Device): add missing 'serial' and 'otherserial' for  search option to add

- phpunit/functional/TicketTest.php
- src/Glpi/Search/SearchOption.php
- src/Ticket.php
The "Project task" search option should not be shown if the user doesn't have permission to read project tasks.
> Hide project task search option if no right to read

- src/Agent.php
Fixes #19479
I have no way to test, but I guess if GLPI gets a 500 level error with one agent address, it should still try the other ones.
> try other agent addresses on 5XX error response

- .phpstan-baseline.php
- phpunit/functional/ChangeTest.php
- src/Central.php
- src/Change.php
- It fixes !37495
Add missing _change to validate_ list from central personel view 
(like _ticket to validate_)
> Fix(change): add missing 'to_validate' list from central personal view

- templates/components/itilobject/actors/field.html.twig
- tests/cypress/e2e/ITILObject/ticket_form.cy.js
Fixes #19529
The select2 select and unselect event handler functions were changed to be arrow functions but the `onchange` code was still using `this`. This caused the generic form submission to never be called and instead, the default functionality of the browser was used which is to submit the form using the first submit button when the enter key is pressed.
> Fix enter key in requester field form submission

- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Form/Migration/FormMigration.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
- src/Glpi/Form/QuestionType/QuestionTypeUrgency.php
Removal of “useless” warning messages.
Added error handling for question imports.
Fixed default value conversion methods for selectables and urgency questions.
> fix(forms): Refactoring migration logic to skip orphan elements messages, and improve default value handling for some question types

- js/modules/Forms/EditorController.js
- src/Glpi/Form/Form.php
- templates/pages/admin/form/block_has_conditions_modal.html.twig
- templates/pages/admin/form/form_editor.html.twig
- templates/pages/admin/form/item_has_conditions_modal.html.twig
- templates/pages/admin/form/move_section_modal.html.twig
- tests/cypress/e2e/form/editor/conditions.cy.js
#19204 must be merged before
Prevent the deletion of a question, section or comment if it is used as a condition.
Add a modal to display which elements have conditions that use the element you wish to delete.
> feat(forms): prevent form elements deletion when they are used by conditions

- CHANGELOG.md
- src/DocumentType.php
- src/Dropdown.php
- templates/components/form/fields_macros.html.twig
Fixes #19585
This specific icon dropdown is only used to show icons from `/pics/icones` and even if another location was specified, the actual images always assumed to be served from the '/pics/icones` web URL. I changed the dropdown method to not have a configurable store path, fixed the path to point to the new location in the public folder, and cleaned up the error reporting.
> fix path used by icon dropdown

- templates/components/itilobject/timeline/pending_reasons_messages.html.twig
An unclosed `class` property was breaking the UI.
Introduced in 708bc3ab9f1ced877134c6bcc4b9025227639d6b, seems like a manual error during the merge to main (code in 10.0 is fine).
> Fix pending reason display (unclosed html property)

- tests/cypress/e2e/search/display_preferences.cy.js
Try to make the display_preferences e2e test less flaky
Also, please note that this test does not really benefits from the retries because once it fail the state is not recoverable for the next retry.
Having a way to reset the display preferences using the API would helps a lot here.
> Try to make the display_preferences e2e test less flaky

- src/Toolbox.php
The `getItemTypeFormUrl()` method relies on `getPhpDir()` to determine the plugin's location.
As a result, if the plugin is installed in the `marketplace` directory, all URLs generated for plugin-related item types will automatically use the `marketplace` path.
To avoid this behavior and ensure consistent URL paths, it is necessary to explicitly enforce the use of the `plugins` path for item types provided by plugins, regardless of their actual installation directory.
> Fix(url) force /plugins/ instead of /marketplace/ for plugin internurl

- .github/dependabot.yml
Some of our dev dependencies are outdated because they are currently upgraded using the `10.0/bugfixes` branch constraints (PHP 7.4 support).
I propose to have 2 parallel upgrade configurations:
- one for the current bugfixes branch, to get, at least, as most as bug fixes as possible on our dev dependencies;
- one for the `main` branch, to get the latest major versions.
Each configuration will not generate more than 2 PRs, as all the dev dependencies are in the same group.
There are already some minor conflicts in the dependencies lock files to solve everytime our dev dependencies are updated, so it will not be worse on this point.
> Allow dependabot to upgrade dev dependencies on `main` branch

- install/migrations/update_10.0.x_to_11.0.0/form.php
Fix: 
```
bin/console db:up -f -s -q -u
> An error occurred during the update. The error was: MySQL query error: Unknown column 'visibility_strategy' in 'glpi_forms_forms' (1054) in SQL query "ALTER TABLE `glpi_forms_forms` ADD `submit_button_conditions` JSON NOT NULL   AFTER `visibility_strategy` ".
```
> visibility_strategy has been renamed, fix upgrade

- CHANGELOG.md
- phpunit/functional/DomainRecordTest.php
- src/DomainRecord.php
It seems like having domain records not linked to a domain was an intentional design since there is even a UI feature to link unattached records to domains. However, domain records use a `CommonDBChild` class which by default requires they be attached to a parent item (domain). While you could create records without a domain (probably another bug, but I don't want to dive into that right now), you would not be able to view them because it would fail a permission check. When `canChildItem` can't find a parent item, it will return false if it must be attached.
> Fix viewing unattached domain records

- src/Rule.php
- src/RuleCollection.php
- It fixes !37587
display ranking from rule list
> feat(Rule): display ranking

- phpunit/functional/Glpi/Http/FirewallTest.php
- src/Glpi/Http/Firewall.php
Fix #19625.
The /front/initsession page was not available for users without sessions.
Note:  not sure why we have two different endpoints /front/initsession and /front/lostpassword when the do the exact same operation.
> Allow acces to /front/initpassword.php page without session

- phpunit/DbTestCase.php
- phpunit/LDAP/AuthLdapTest.php
- phpunit/functional/CommonDBTMTest.php
- phpunit/functional/RuleRightTest.php
Logging in cost a lot of test time, especially since most of the time we are not testing the login process itself but instead we just need a valid session for a given username.
I've changed the login session to do a "fake" logging that is much faster and added another `realLogin()` method that keep the original behavior for the few tests that actually do test the login feature.
With these changes:
On another unrelated PR for comparison:
> Mock login in tests

- phpunit/functional/Glpi/Asset/AssetDefinitionTest.php
- phpunit/functional/Glpi/Dropdown/DropdownDefinitionTest.php
- src/Dropdown.php
- src/Glpi/Asset/AssetDefinition.php
- src/Glpi/Asset/AssetDefinitionManager.php
- src/Glpi/CustomObject/AbstractDefinition.php
- src/Glpi/CustomObject/AbstractDefinitionManager.php
- src/Glpi/Dropdown/DropdownDefinitionManager.php
- templates/pages/admin/customobjects/main.html.twig
See #19658.
People may want to create custom dropdowns with names that ends with `Model` or `Type`. Allowing this does not seems to be a problem.
Allowing this for custom assets is also possible, but it requires to ensure it will not conflict with another definition, for instance, if you create a `CarModel` asset definition, it would conflict with a `Car` asset definition that automatically registers its `CarModel` asset model class. I have no time to do it for the moment, so I did not do this in the current PR.
> Allow custom dropdowns ending with Model or Type

- phpunit/bootstrap.php
- phpunit/functional/Glpi/Form/AnswersHandler/AnswersHandlerTest.php
Fix this error:
Note sure what file it is supposed to include but it does not exist (no references to `ApiBaseClass` in the code base).
And a non static method being called statically in one test file.
> Minor phpunit fixes

- src/Glpi/Form/Form.php
Fix #19654.
The url needs to be relative in this part of the code as the parts that render it call the `path` method on it:
> Fix form category link

- js/src/vue/Kanban/Kanban.vue
- js/src/vue/Kanban/KanbanApp.vue
- templates/components/kanban/kanban.html.twig
A quick UX win for the Kanban especially for larger global Kanbans and slow network connections. Currently, the Kanban is shown immediately before the extra needed data is loaded. The Kanban switcher dropdown is empty and an info message is shown saying there are no columns in the view. Then the switcher content loads, followed by the columns.
By wrapping the Kanban in another component using `<Suspense>` and moving the loading function calls to be top-level awaits in `<Kanban>`, we can show a loading indicator and then show the Kanban when it is fully ready.
> Wait for kanban to fully load before showing

- phpunit/functional/ProfileTest.php
- src/Profile.php
As noted in #14570, all profile rights should have a search option to ensure changes to them can be logged in the Profile's history. A check was added in the form of a test to ensure every right had a search option, but this didn't catch that custom asset rights were missing a search option because no custom asset definition existed in the test data.
> Add search options for custom asset rights

- src/Config.php
- src/PurgeLogs.php
- It fixes !37300
Fix Software purge
should remove entries where the `itemtype` matches one of the following: `Computer, Monitor, NetworkEquipment, Peripheral, Phone, or Printer`, as well as entries with `linked_action` **4** (`Log::HISTORY_INSTALL_SOFTWARE`) and **5** (`Log::HISTORY_UNINSTALL_SOFTWARE`).
However, some residual data remains in the database for `linked_action` types **17** (`Log::HISTORY_ADD_SUBITEM`), **18** (`Log::HISTORY_UPDATE_SUBITEM`), and **19** (`Log::HISTORY_DELETE_SUBITEM`).
For instance, at a client site, actions of type **4** and **5** are properly purged, but types **17**, **18**, and **19** remain in the database.
```sql
+----------+-------------------------------------------------------+---------------+---------- …
```
> Fix(Purgelog): fix Software purge

- phpunit/functional/Item_SoftwareLicenseTest.php
- phpunit/functional/SoftwareLicenseTest.php
- src/Item_SoftwareLicense.php
- src/SoftwareLicense.php
- src/SoftwareLicense_User.php
Linked to PR https://github.com/glpi-project/glpi/pull/18335
- It fixes !37405
The system correctly blocks the "Add" button when the "Number" field limit is reached. However, it is still possible to manually add items via "Actions > Add an item", which should not be allowed.
Users added through this path do not appear in the list but are counted in the "Affected items" counter.
> Fix - Massive user addition actions in Licenses

- phpunit/functional/ToolboxTest.php
- src/Toolbox.php
Fix #19634.
Url containing urlencoded values were marked as invalid by the `Toolbox::isValidWebUrl()` method.
The original regex was copied from Symfony: https://github.com/symfony/symfony/blob/7.3/src/Symfony/Component/Validator/Constraints/UrlValidator.php#L24.
It does not work for GLPI because we don't process it the same way.
Symfony use it in a `sprintf` call so it require the `%` char to be escaped as `%%`.
Since we do not call sprint on the value, the `%%` char is never replaced by `%` on our side which lead to a regex that can't detect url encoded values such as `%20` (it looks for `%%20` instead).
Fixed by replaced the `%%` occurrences by `%`.
In this future, it would be better to require the dependency and use it directly rather than manually copying its internal behavior (but I …
> Fix url validation with urlencoded chars

- ajax/comments.php
- templates/components/itilobject/actors/field.html.twig
- templates/components/supplier/info_card.html.twig
- It fixes !37627
The tooltip map of suppliers has disappeared with the switch to 10, although it was visible in 9.5 in the past.
**GLPI 9.5**
**GLPI 10 before**
**GLPI 10 after**
> Fix supplier tooltip card

- src/Glpi/OAuth/Server.php
I am reading the `OAuth\Server::generateKeys()` method for the #19673 issue and it suffer from too many nested conditions.
I've rewritten it with early return to make it easier to read and added calls to `openssl_error_string` to get clearer error messages (thanks @trasher for mentioning the method in the issue, I was not aware of its existence).
This does not fix the ongoing issue.
> Refactor OAuth\Server::generateKeys() for readability/debugging

- CHANGELOG.md
- phpstan.neon.dist
- src/CronTask.php
- src/DbUtils.php
- src/Glpi/Application/Environment.php
- src/Glpi/Application/SystemConfigurator.php
- src/Glpi/Console/Application.php
- src/Glpi/Console/CommandLoader.php
- src/Glpi/Console/Plugin/InstallCommand.php
- src/Glpi/Error/ErrorHandler.php
- src/Glpi/Http/Firewall.php
- src/Glpi/Kernel/Listener/ControllerListener/CheckCsrfListener.php
- src/Glpi/Kernel/Listener/PostBootListener/SessionStart.php
- src/Glpi/Kernel/Listener/RequestListener/FrontEndAssetsListener.php
- src/Glpi/Kernel/Listener/RequestListener/LegacyRouterListener.php
- src/Glpi/Log/AbstractLogHandler.php
- src/Glpi/Marketplace/Controller.php
- src/NotificationEventMailing.php
- src/NotificationMailing.php
- src/Plugin.php
- src/Session.php
- src/Toolbox.php
- src/Update.php
- src/autoload/constants.php
- src/autoload/legacy-autoloader.php
- stubs/glpi_constants.php
- templates/layout/parts/page_header.html.twig
- templates/layout/parts/page_header_empty.html.twig
1. Make the `GLPI_LOG_LVL` constant always defined and use it instead of having a `Environment::getLogLevel()` method.
2. Deprecate the `GLPI_FORCE_MAIL` constant. A mail catcher service is a better alternative than using a real SMTP server that may lead to unexpected message sending when the developer forgot to configure this constant.
3. Make the `SKIP_UPDATES` always defined (and rename it to `GLPI_SKIP_UPDATES` to follow the naming convention of our constants).
4. Make the `GLPI_SYSTEM_CRON` constant always defined.
5. Replace the `GLPI_KEEP_CSRF_TOKEN` constant by a safer implementation based on method params.
6. Rename the `PLUGINS_DIRECTORIES` to `GLPI_PLUGINS_DIRECTORIES` to follow the naming convention of our constants.
IMHO, we should also remove the `defined('TU_USER')` from …
> Clean constants handling

- templates/components/search/displaypreference_list.html.twig
A quick fix on an issue reported orally by @flegastelois; when you go on the "All" tab in Setup > General, the "Select All" button for the display preferences paragraph interferes with other parts of the page
The bug:
> limit selection of all checkbox for displaypreference to a sub div

- templates/pages/admin/form/condition_handler_templates/item_dropdown.html.twig
Following the strict declaration of variables in Twig templates initiated by #19667, a bug occurred when adding a new condition targeting questions of type `QuestionTypeItem`.
This fix should resolve the E2E test problems on the `conditions.cy.js` file.
> fix(forms): null twig template value in item condition handler

- src/Glpi/Controller/Session/ChangeProfileController.php
- src/Glpi/Kernel/Listener/ExceptionListener/AccessErrorListener.php
Same behavior as before but the `_redirected_from_profile_selector` flag is set in the query string instead of the session.
This make sure it can only be used for the next request and wont stay active for any further requests.
Fix #19630 (for main only).
> Improve error handling on profile redirection

- src/Dashboard/Grid.php
The label of this widget is incorrect, it targets the request sources of a ticket (email, phone, ...) not the request types (incident or request).
Fix #19698.
> Fix request sources dashboard label

- src/Profile.php
`SearchOption::generateAProbablyUniqueId()` has a high probability to generate redundant values. I tried to handle this in #16746, but it was not enough to achieve what I wanted to do, so it has never been finished.
Since this morning, and the merge of #19676, the test suite faile already multiple times with an error similar to:
```
1) tests\units\Glpi\Asset\Capacity\HasPlugCapacityTest::testCloneAsset
Unexpected entries in log in tests\units\Glpi\Asset\Capacity\HasPlugCapacityTest::GLPITestCase::tearDown:
Array
(
[0] => Array
(
[channel] => glpi
[level] => Warning
[message] => User Warning: Duplicate key `11552` (`Test01`/`wEQrMgqEhcFbJVEB`) in `Profile` search options. at CommonDBTM.php line 3924
```
Using 1000 + the definition ID will make ot stable over time and will ensure that the …
> Fix profiles rights uniqueness

- src/Ticket.php
- It fixes !37384
If a ticket template predefines a group as observer. In the simplified interface, the observer group is not filled in on the ticket creation form.
> Fix - Missing predefined group in helpdesk ticket form

- templates/pages/admin/inventory/upload_result.html.twig
Fixes a margin offset for buttons on the manual inventory import confirmation page.
Before 
After
> fix(inventory): margin ui import success

- src/ITILTemplateField.php
- src/ITILTemplatePredefinedField.php
-> Can't easily add a backend test as the method is not designed in a way that makes it testable and we already have too much e2e tests right now...
Some predefined fields like "associated assets" are supposed to "repeatable" (= can be defined multiple times).
This is no longer the case in GLPI 11 due to some refactoring that was done without keeping this feature.
I've found the original code from GLPI 10 and integrated it:
Fix #19682.
Before:
After:
> Fix repeatable predefined fields

- inc/define.php
- phpunit/functional/LockedfieldTest.php
- phpunit/functional/MassiveActionTest.php
- It fixes !37675
Dynamic objects that should have their fields locked were not in the list $CFG_GLPI['inventory_lockable_objects']
> Fix inventory_lockable_objects list

- install/empty_data.php
- phpunit/functional/ConfigTest.php
This field is only initialized when migrating from GLPI 10 to 11, we forgot to include it in the empty data for a clean install.
This lead to an exception when trying to render the security config form.
Introduced by: ba4c34277d25e5a1b753bc000ba1f394c64ad058.
> Fix missing default value on install for "non_reusable_passwords_count"

- install/empty_data.php
- phpunit/functional/Glpi/Api/HL/Controller/CoreControllerTest.php
- src/Glpi/Api/HL/Middleware/CookieAuthMiddleware.php
- src/Glpi/Api/HL/Middleware/IPRestrictionRequestMiddleware.php
- src/Glpi/Application/Environment.php
- src/Glpi/Kernel/Listener/PostBootListener/SessionStart.php
- tests/cypress/e2e/oauth_authcode.cy.js
- tests/src/Command/TestUpdatedDataCommand.php
Work to fix #18299 and maybe fix #19506.
Working to move authorization code test from PHPUnit (currently a partial/fake test) to Cypress.
> Try fixing authorization code redirect loop

- templates/pages/admin/external_page_tile_config_fields.html.twig
- tests/cypress/e2e/self-service/home_config.cy.js
- It fixes #19717
The name of the field used to define the external url did not match the base field.
Modification of a Cypress test to verify the configuration of an external tile after addition.
> fix(helpdesk): Rename 'link' to 'url' in external page tile configuration

- .phpstan-baseline.php
- CHANGELOG.md
- install/install.php
- install/update.php
- src/Glpi/Application/View/Extension/FrontEndAssetsExtension.php
- src/Html.php
- templates/layout/parts/head.html.twig
In the massive action process script, the GLPI footer is not displayed, as we only want to display a progress bar. The `CFG_GLPI` JS variable was therefore not defined and an error was triggered in the `vue/app.js` script that is executed on every page to register the path to every vue component.
I moved the definition of these variables in the `templates/layout/parts/head.html.twig` template that is used to display the HTML `<head>` section of every page.
> Move `CFG_GLPI` JS var definition in the HTML header

- phpunit/functional/ChangeTemplatePredefinedFieldTest.php
- phpunit/functional/ProblemTemplatePredefinedFieldTest.php
- phpunit/functional/TicketTemplatePredefinedFieldTest.php
- src/ITILTemplatePredefinedField.php
- tests/src/AbstractITILTemplatePredefinedFieldTest.php
Prevent adding an invalid associated items in the predefined fields (e.g. the itemtype was picker but the item was not selected).
Fix #19701.
> Prevent invalid associated item to be selected for predefined fields

- phpunit/functional/Glpi/Inventory/Assets/SoftwareTest.php
- src/Glpi/Inventory/Asset/Software.php
- It fixes !37653
Prevent `lockedfield` when inventory update `Item_SoftwareVersion` (date_install)
Introduced by https://github.com/glpi-project/glpi/pull/16598
> Fix(Inventory): prevent lock when inventory update Item_SoftwareVersion

- phpunit/functional/MassiveActionTest.php
- src/MassiveAction.php
- It fixes !37540
In `GLPI`, if a search option references a table different from the main object, the `MassiveAction` class will attempt (if the main item and the related item can be assigned to an `entity`) to load the related item to extract the entity (and the sub-entity if recursive) and compare it to the entity of the main item to "authorize" or deny the update.
However, the loading of the related item is performed via a `getFromDB()` (thus using the ID column) from the value of the modified field (=/).
Thus, when the field is text, the condition on the entity is never verified and update action is authorized.
But when the field is `numeric` (`dropdown` / `number` / `yes no`), the loading is erroneous.
For example, with `Yes` or `No`, …
> Fix(MassiveAction): fix item2 reconciliation

- templates/components/form/basic_inputs_macros.html.twig
- templates/components/itilobject/fields_panel.html.twig
- templates/components/itilobject/service_levels.html.twig
-> Would like to be the code that test this form is a mess and do not support readonly fields. Maybe later if I have time.
Some readonly fields were not applied correctly for itil templates:
- Request type
- Opening date
- SLA
Fix #19627.
> Fix readonly templates fields

- js/common.js
- src/NotificationTemplateTranslation.php
- src/Notification_NotificationTemplate.php
- tests/cypress/e2e/notifications.cy.js
Fixes #19522
Two issues:
1. The current language shouldn't be in the used array
2. An empty string placeholder breaks the display of the current option if the key of the current option is also an empty string. No need to add a blank placeholder in the Select2 config.
> Fix default notification translation selection

- src/Glpi/Application/View/Extension/FrontEndAssetsExtension.php
One of the few cases where `var` produced the desired effect, but `const` does not. We need to make sure these variables get added to the `window` as before so they can be accessed from within modules.
Modules can access these variables using `window.CFG_GLPI` or simply `CFG_GLPI` as before. With `const`, they were not accessible at all.
> Must declare CFG_GLPI in JS on the window

- src/Glpi/Kernel/Listener/PostBootListener/DisablePluginsOnVersionChange.php
- src/Glpi/Kernel/ListenersPriority.php
- src/Update.php
It fixes #19629.
Since now plugins are loaded during the GLPI boot sequence, they are now loaded prior to the initialization of the GLPI console, and it is therefore impossible to not load them for some specific commandas as it was done in GLPI 10.0. Indeed, it is nearly impossible to know what exact command will be executed during the kernel boot, as Symfony is able to match many identifiers for a same command, for instance the install command can be executed with `d:i`, `db:i`, `data:inst`, `database:install`, `db:install`, ... as long as there is no ambiguity between multiple commands.
Until now the plugins were deactivated by the update process itself, when it was actually executed. I propose to deactivate the plugins earlier, during the GLPI boot sequence, before they are actually …
> Unactivate all plugins once a mandatory update is detected

- phpunit/functional/SavedSearchTest.php
- src/SavedSearch.php
Prevent saved searches from being cloned as it does not work (probably not fully implemented).
Note that you can still clone and modify the search by loading it in the search results then using "Saved as new...".
Fix #19716
> Disable "clone" massive action for saved searches

- install/install.php
- phpunit/web/APIRestTest.php
- templates/pages/setup/general/api_setup.html.twig
- tests/README.md
- tests/src/autoload/functions.php
Tried to run the web suite locally and ran into the following issue:
* URL is hardcoded to use the `url_base_api`, which has been removed in GLPI 11.
* Documentation is no longer relevant.
I've removed the references to `url_base_api` and deleted the documentation as it is no longer relevant (router.php is no longer used on the CI and the example command won't work locally as the tests no longer target the given 8088 port AFAIK).
> Fix running web tests locally

- phpunit/functional/ITILTemplateTest.php
- src/CommonITILObject.php
- It fixes !37529
At the creation of an ITIL object, the category defined in the predefined field was not filled in.
> Fix(ITIL templates): category predefined field

- css/includes/components/form/_form-editor-horizontal-layout.scss
When you want to move a question/comment to a placeholder in a horizontal layout, the toolbar doesn't hide, leaving the UI unclear.
> fix(forms): hide toolbar when drag question placeholder is present

- src/Glpi/Search/Input/QueryBuilder.php
- templates/components/search/criteria_filter.html.twig
- templates/components/search/criteria_filter_actions.html.twig
- templates/components/search/query_builder/main.html.twig
Fixes #19724
There is only so much that can be done, without adding complexity or refactoring, because the criteria filter feature directly uses components of the main search engine and it wasn't really intended to be reused in that way. The criteria filter feature just changes the search button label.
This PR fixes the button group styles when there is only one button in the main query builder template, and add some spacing between the default buttons and the one added for the criteria filter UI.
I've also added a commit that forces non .btn-sm and .btn-secondary styles but it isn't a clean solution. If the default button CSS changes, this button won't match.
> Fix criteria filter button UI

- src/Toolbox.php
- It fixes !37529
When changing the category of an ITIL object, if a template with many predefined fields (including the category) is reloaded, the page crashes with a 414 error, leaving the loading animation displayed.
Browser console error:
> Fix(ITIL templates): 414 error with many predefined fields

- front/report.dynamic.php
- src/KnowbaseItem.php
- It fixes !37420
Incorrect export of knowledge base articles. For example, if I choose to export `All my articles`, the export will show `All published articles`. The problem is that the field containing the data to be displayed is not sent when the export is called.
> Fix - Consistency of exported knowledge base data

- phpunit/functional/MassiveActionTest.php
- phpunit/functional/SoftwareLicenseTest.php
- src/MassiveAction.php
- src/SoftwareLicense.php
- It fixes !37405
- Complete PR https://github.com/glpi-project/glpi/pull/19561
This pull request fixes a bug where the system correctly disabled the "Add" button when the limit defined in the "Number" field was reached, but still allowed users to bypass this restriction by using the menu:
"Actions > Add an item".
> Fix - Massive items addition actions in Licenses

- templates/pages/admin/log_viewer.html.twig
This variable does not exist in the macro.
> Fix unexpected variable in Twig macro

- src/Glpi/Form/BlockInterface.php
- src/Glpi/Form/Comment.php
- src/Glpi/Form/Question.php
- templates/pages/form_renderer.html.twig
- tests/cypress/e2e/form/form_rendering.cy.js
The label used for questions and comments when they don't have a defined title is the same : `Untitled question`.
Added a more personalized label for comments: `Untitled comment`.
> fix(forms): fixed untitled label for comment blocks

- src/Html.php
`Html::scss()` is used only for a few SCSS files. The path to compiled SCSS files was not correct, as it included the `/public` prefix that should not be used anymore. A similar replacement is already done for SCSS files paths generated in the Twig context : https://github.com/glpi-project/glpi/blob/2bc27a8359668996613c8f0fde9bfc9a34eaf0ab/src/Glpi/Application/View/Extension/FrontEndAssetsExtension.php#L129
> Fix SCSS compiled URL

- .phpstan-baseline.php
- phpunit/functional/Glpi/Inventory/Assets/SoftwareTest.php
- src/Inventory/Asset/Software.php
- tests/fixtures/inventories/software/01_computer_full_inventory_soft_and_os.json
- tests/fixtures/inventories/software/02_computer_full_inventory_soft_and_os.json
- tests/fixtures/inventories/software/03_computer_partial_inventory_with_os.json
- tests/fixtures/inventories/software/04_computer_full_inventory_with_os_without_soft.json
- tests/fixtures/inventories/software/05_computer_full_inventory_without_os_with_soft.json
Currently, when processing a new software entry in GLPI, the system checks whether the corresponding version already exists in the database. This verification is performed using a prepared SQL query built with the following criteria:
```php
$criteria = [
'SELECT' => ['id', 'name', 'arch', 'softwares_id', 'operatingsystems_id'],
'FROM'   => \SoftwareVersion::getTable(),
'WHERE'  => [
'entities_id'           => $this->entities_id,
'name'                  => new QueryParam(),
'arch'                  => new QueryParam(),
'softwares_id'          => new QueryParam(),
'operatingsystems_id'   => new QueryParam(),
],
];
```
The query parameters typically look like this:
```php
[
'version'      => $val->version,
'arch'         => $val->arch ?? '', …
```
> Fix(Inventory): prevent duplicate software version

- src/ITILFollowup.php
- It fixes !37813
This patch corrects a regression introduced by PR #17543 where follow-up notifications were sent before the status of the parent ticket was updated.
When a solution is approved via the Approvalbymail plugin, a follow-up is created and a notification is sent while the ticket is still in the "Resolved" state (status 5). Only then does the ticket change to "Closed" (status 6). As a result, the notification again includes the approval form, which is misleading and no longer relevant.
In ITILFollowup::post_addItem(), NotificationEvent::raiseEvent() is called before updateParentStatus().
Move the notification logic after the call to updateParentStatus() and …
> Fix (ITILFollowup) - Parent status update after notification

- .docker/app/Dockerfile
- Makefile
- docker-compose.yaml
Toggle xdebug on dev container using makefile.
Added as a volume to keep the config persistant when killing/rebuilding the containers.
> Toggle xdebug on docker using makefile

- templates/pages/helpdesk/search.html.twig
Search results on helpdesk homepage should not be forcing the results to use the dark text color as it makes the results unreadable in dark themes. The correct solution to fix the text color so it isn't the link color, is to use `text-body` to reset it to the body text color.
> Helpdesk search results should not use dark text

- phpunit/functional/CommonDBTMTest.php
- src/CommonDBTM.php
- It fixes !37801
In certain hierarchical classes, such as `IPNetwork`, the `completename` field is used to represent the full hierarchy as a text string. This field is often very long and typically stored as a `TEXT` or `MEDIUMTEXT` type in the database.
To enable converting the `completename` into a clickable link pointing to the related object, it is defined with the `itemlink` datatype. This type is used solely for visual rendering, particularly within the `CommonTreeDropdown` component.
However, when the `completename` field is updated, `CommonDBTM` and `FilterValues` apply a truncation mechanism to fields exceeding 255 characters when their datatype is `itemlink`. This can lead to data loss in certain edge cases (entity deleteion in my …
> Fix(CommonDBTM) Fix filtervalues method for completename used as itemlink (for display)

- src/ProjectTask.php
Tasks without parent task had a missing `<td>` in the project tasks tab:
Fix #19808.
> Fix missing column in project task datatable

- phpunit/functional/LogTest.php
- src/Log.php
Trimming of old and new value strings seems redundant included dead code. Seen while answering a question on the forum.
First, the values are trimmed to 180 characters. Then if the strings are over 255 characters (which they would never be), they are trimmed to 250.
We should only need to trim them to 255 characters which is the size of the columns in the database. In reality, I think the only thing gained by trimming on the PHP side is to reduce the amount of data sent over the network to the database in the case of extremely long content.
Functionally, the only change from this PR should be that old/new values for historical entries are now trimmed to 255 characters instead of 180.
> Simplify history values trimming

- src/NetworkPort.php
- It fixes !37769
When a hub is connected to a NetworkPort in GLPI, all unmanaged devices connected to that hub are displayed directly in the NetworkPort view.
All related equipment is displayed correctly, except for the one corresponding to the main object (in this case, the switch), which is excluded from the list (While this exclusion might be intentional, the information is available, so omitting it from the display seems unnecessary).
I now want to convert two unmanaged devices into clearly identified assets within GLPI.
- `RICOH COMPANY, LTD` → `Printer`
- `Apple, Inc.` → `Computer`
Once these unmanaged devices are converted, even though they remain physically connected to the hub, 
they no longer appear in the list of devices linked to …
> Fix(NetworkPort): display all items related to hub

- src/NetworkPort.php
* It fixes !37769
Follow-up to the PR  https://github.com/glpi-project/glpi/pull/19829
Prevent displaying the asset linked from the hub corresponding to the current asset.
In this example, I am looking at a network device, **FDB-HR-SW1**, where port **1/1/2** is connected to a hub. Naturally, this hub contains a port linked back to **FDB-HR-SW1**.
Displaying this connection is unnecessary and could lead to confusion or misunderstanding.
> Fix(NetworkPort): do not diplay current item network port link

- src/NotificationEvent.php
- src/QueuedNotification.php
When a notification mode added by a plugin is no longer available _typically because the plugin is disabled or uninstalled_
GLPI throws a runtime error during template rendering.
This was observed in the **QueuedNotification** list view, where some queued notifications used the `webhook` mode provided by the **CollaborativeTools** plugin, which was not active at the time.
```shell
[2025-05-28 12:04:30] glpi.CRITICAL:   *** Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Cannot access offset of type string on string")." at generic_list.html.twig line 38
Backtrace :
./templates/pages/generic_list.html.twig:38        
./vendor/twig/twig/src/Template.php:344 …
```
> Fix(Notification): prevent error when mode is not available

- phpunit/GLPITestCase.php
- phpunit/functional/SLMTest.php
- phpunit/src/Glpi/ITILTrait.php
- phpunit/src/Glpi/SLMTrait.php
- src/LevelAgreement.php
- src/OlaLevel_Ticket.php
- src/SlaLevel_Ticket.php
SlaLevel_Ticket and OlaLevel_Ticket.php function not dependent on SQL realtime. 
(replayForTicket(), cronOlaTicket(), cronSlaTicket())
+ add test : SLA TTR escalation level changes
I've had conflicting information about level escalation, so I wrote tests (while I'm changing something else on ola).
We can now be sure that both SLA and OLA (both TTR & TTO) have level escalation feature working).
More tests need to be written (noted with a @todo tag).
+ add test helpers (SLMTrait, ITILTrait)
- It fixes ability to perform Ola|SlaLevel tests
> Add SLA/OLA tests

- src/Glpi/Console/Database/UpdateCommand.php
- src/Glpi/Controller/InstallController.php
- src/Update.php
SQL errors are caught by the update process to visually indicates that the operation failed, but the result code of the update command was `0` in this case (only when the `--skip-db-checks` option is used, as in the CI).
Adding a boolean return value to `Update::doUpdate()` permit to adapt the command result code.
> Fix error code returned by the update command

- phpunit/DbTestCase.php
- phpunit/functional/Glpi/Asset/AssetDefinitionManagerTest.php
- src/Glpi/Asset/AssetDefinitionManager.php
- tests/fixtures/plugins/tester/src/Asset/Capacity/HasFooCapacity.php
- tests/fixtures/plugins/tester/src/Asset/Foo.php
This provides a method that can be used by plugins to register asset capacities from their setup function.
```php
AssetDefinitionManager::getInstance()->registerCapacity(new MyPluginCapacity());
```
> Allow plugins to register generic assets capacities

- src/Glpi/Controller/InstallController.php
The progress bar is not displayed as expected on PHP-FPM servers because there is an extra buffering system that prevents the flushed content to be received by the browser before the actuel end of the processing. Calling `fastcgi_finish_request()` should fix this.
I also added a call to `ignore_user_abort()` to prevent the process to be killed by the client.
> Fix install/update progress indicator on PHP-FPM servers

- composer.json
- composer.lock
@dependabot fails to do this upgrabe, because it tries to upgrade to the 12.x version.
See the log:
```
updater | 2025/06/01 11:11:47 INFO <job_1025189773> Checking if phpunit/phpunit 11.2.6 needs updating
proxy | 2025/06/01 11:11:47 [067] GET https://repo.packagist.org/p2/phpunit/phpunit.json
proxy | 2025/06/01 11:11:47 [067] 200 https://repo.packagist.org/p2/phpunit/phpunit.json
updater | 2025/06/01 11:11:47 INFO <job_1025189773> Latest version is 12.1.6
2025/06/01 11:11:47 INFO <job_1025189773> Adding dependencies as handled: (phpunit/phpunit).
...
updater | 2025/06/01 11:11:48 ERROR <job_1025189773> Your requirements could not be resolved to an installable set of packages.
Problem 1
- Root composer.json requires phpunit/phpunit >= 11.2.6, == 12.1.6 -> satisfiable by …
```
> Upgrade PHPUnit to ^11.5

- phpunit/functional/ChangeTest.php
- phpunit/functional/ProblemTest.php
- phpunit/functional/TicketTest.php
- src/Change.php
- src/CommonITILObject.php
- src/Ticket.php
- It fixes !37694
- If a user has the right to add follow-ups and add documents, the user cannot add documents to my changes, he should also have the right to update changes.
> fix(change): unable to add a document without change update rights

- phpunit/functional/LockedfieldTest.php
- src/Inventory/Asset/InventoryAsset.php
- src/Inventory/Asset/MainAsset.php
- It fixes !37931
Since the merge of [[PR #19426](https://github.com/glpi-project/glpi/pull/19426)](https://github.com/glpi-project/glpi/pull/19426), if a global locked field is created for dropdown fields an error is thrown by the GLPI Inventory module during asset import:
```shell
SQL: INSERT INTO `glpi_networkequipments` (`autoupdatesystems_id`, `last_inventory_update`, `is_deleted`, `name`, `ram`, `serial`, `uptime`, `sysdescr`, `networkequipmentmodels_id`, `networkequipmenttypes_id`, `manufacturers_id`, `is_dynamic`, `entities_id`, `states_id`, `date_creation`, `date_mod`) VALUES ('1', '2025-06-02 07:23:03', '0', 'FDB-HR-SW1', '3420', 'xxxxxxxx', '48 days, 22:50:03.23', 'Aruba JL677A 6100 24G CL4 4SFP+ Swch PL.10.13.1040', '2', …
```
> Fix(Inventory): prevent raw data when handle locked field on add

- phpunit/abstracts/RuleCommonITILObjectTest.php
- phpunit/functional/RuleTest.php
- src/CommonITILObject.php
This is needed for rule criteria to match an entity on update.
entities_id is added to 'changed' fields on CommonITILObject update.
This is needed for rule criteria to match an entity on update.
> entities_id is added to 'changed' fields on CommonITILObject update.

- templates/components/itilobject/fields_panel.html.twig
Fixes #19919. A bad default value was added in #19729 which made it show only the current entity except in Tickets which was the only case that specified `userentities`.
> Fix change and problem entity dropdown

- templates/pages/admin/form/form_destination.html.twig
- templates/pages/admin/form/form_destination_actions.html.twig
- tests/cypress/e2e/form/form_destination.cy.js
It fixes #19886
Add duplicate button for form destinations
> feat(forms): Add duplicate button for form destinations

- src/Database.php
- src/Impact.php
Fixes #19947
- Remove Impact Relation from clone relations for databases
- Disable Impact tab for templates
As far as I can tell, impact relations were never cloned even when a graph was defined in an asset template and an asset was created from that template. Further, no impact types have Impact Relations as a clone relation except Databases (added in #18554). This isn't the removal of a feature that never existed. This is removing an invalid relation and trying to prevent user confusion.
If we want to clone impact relations we likely need complex changes to support relationships where both sides are polymorphic, and also make all itemtypes that can be on an impact graph and cloned define Impact Relations as a relation to clone.
> Block impact in templates and cloning

- phpunit/web/Glpi/Inventory/RequestTest.php
- src/Glpi/Agent/Communication/AbstractRequest.php
PR #16727 does not work, the typo modification made before the merge (d23fe386f8667006705c34b9f2d23709dc732aee), prevents the oauth authentication feature from working on the inventory.
After discussion with @orthagh , we propose :
- to remove the part of code which prevents the oauth from working on the inventory
- to code a functional test
- and then to redo (in another PR) an adapted modification in the oauth inventory to put a functional code on the check of a non-existent user
> Add inventory oauth client_credentials tests

- phpunit/functional/TicketTest.php
- src/CommonITILObject.php
- It fixes !37860
- If the user executes a rule that applies a solution template during ticket creation, requesters receive a double notification that the ticket has been resolved.
> fix(notification): Only one notification is sent when a ticket is resolved on creation using a solution template rule

- src/Glpi/Form/QuestionType/QuestionTypeItemDropdown.php
- tests/cypress/e2e/form/question_types/dropdown_item.cy.js
- tests/cypress/support/commands/select2.js
- It fixes #19960
It is possible to define whether an ITIL category is visible or not on helpdesk interface.
This option was not taken into account by the `QuestioonTypeDropdownItem` question type and displayed hidden categories on self-service interface.
> fix(forms): Filter visible ITIL categories in helpdesk interface

- CHANGELOG.md
- install/empty_data.php
- phpunit/functional/ChangeTest.php
- src/Change.php
- src/CommonITILObject.php
- src/CommonITILValidation.php
- src/Glpi/Dashboard/FakeProvider.php
- src/Glpi/Dashboard/Provider.php
- src/Glpi/Form/Condition/ValidationStrategy.php
- src/Glpi/Form/Destination/CommonITILField/ValidationField.php
- src/Glpi/Form/Destination/CommonITILField/ValidationFieldStrategy.php
- src/Glpi/Helpdesk/DefaultDataManager.php
- src/ITILValidationTemplate.php
- src/ITILValidationTemplate_Target.php
- src/NotificationTargetChange.php
- src/NotificationTargetTicket.php
- src/RuleCommonITILObject.php
- src/Ticket.php
- src/TicketValidation.php
- src/ValidatorSubstitute.php
- templates/components/itilobject/fields/global_validation.html.twig
- templates/components/itilobject/timeline/filter_timeline.html.twig
- templates/components/itilobject/timeline/timeline.html.twig
- templates/components/itilobject/validationstep.html.twig
- templates/pages/admin/user.substitute.html.twig
- tests/cypress/e2e/form/destination_config_fields/validation.cy.js
- tests/src/Command/TestUpdatedDataCommand.php
The UI currently has both validation and approval, and other forms of these words, to refer to the same things. This PR standardizes it to be Approval which seems more correct in English. Internally, these are still referred to as validations.
https://forum.glpi-project.org/viewtopic.php?id=292619
> Replace Validation term with Approval

- phpunit/functional/TicketTest.php
- src/CommonITILObject.php
- It fixes !38049
When the option to view tickets from my groups is activated for a user who does not have a group, that user can no longer view tickets with a stain.
> Fix see task of my group option

- css/includes/_base.scss
- css/includes/_palette_dark.scss
- Fix input placeholder text color. Used to be hardcoded by Bootstrap to `#8a97ab` but is now linked to `--tblr-tertiary`.
- Fix webkit autofill styles again. Previous fix seems to have broken from a Chrome update.
- Remove box shadow for input group as it tends to extend past the actual contents in flexbox and doesn't look good with the border radius
- Fix input group text background color which was light in dark themes.
- Fix `.text-body` which is used for the search results in the helpdesk homepage being broken because it switched from `--tblr-body-color` to `--tblr-body-color-rgb` which wasn't overriden in the dark theme base css.
- Fix accordian button backgrounds extending past the rounded border of lists (dropdown type lists) causing the corners to appear invisible.
> Fix some dark theme styles

- .phpstan-baseline.php
- phpunit/functional/Glpi/Http/FirewallTest.php
- phpunit/functional/Glpi/Kernel/Listener/RequestListener/FrontEndAssetsListenerTest.php
- phpunit/functional/Glpi/Kernel/Listener/RequestListener/LegacyRouterListenerTest.php
- public/index.php
- src/Glpi/Http/Firewall.php
- src/Glpi/Http/RequestRouterTrait.php
- src/Glpi/Kernel/Listener/PostBootListener/SessionStart.php
- src/Glpi/Kernel/Listener/RequestListener/FrontEndAssetsListener.php
- src/Glpi/Kernel/Listener/RequestListener/LegacyRouterListener.php
It fixes #19948.
When the PHP built-in web server is used (`php -s 0:8080 public/index.php`), it handle all requests through the `public/index.php` file (as defined by the command line), even static files. For them, the `$_SERVER['SCRIPT_NAME']` contains the requested static file path instead of the `/public/index.php` value, and both GLPI and Symfony are not handling that properly.
The proposed patch permits to handle this pescial case and make GLPI compatible with the PHP built-in web server.
> Fix front-end routing with PHP built-in server

- phpunit/functional/ValidationStepTest.php
- phpunit/src/Glpi/ValidationStepTrait.php
- src/ValidationStep.php
- **Disallow deletion of used validation step.**
- **Do not show delete button on validation step that cannot be deleted**
- **add "default" search column for validationsteps**
- It fixes #19933
> improve multistep - no deletion of used ValidationSteps - fix #19933

- ajax/itilvalidation.php
- install/empty_data.php
- src/ITILValidationTemplate.php
- tests/cypress/e2e/ITILObject/ticket_form.cy.js
> Fix errors with validation templates when no approver set

- templates/pages/admin/transfer_list.html.twig
The array key for entity names was renamed a while ago but the reference was not changed in the twig template.
> Fix transfer list twig variable name

- .phpstan-baseline.php
- phpunit/functional/TicketTest.php
- src/Change.php
- src/CommonGLPI.php
- src/CommonITILObject.php
- src/Glpi/Features/Kanban.php
- src/Problem.php
- src/Ticket.php
CS
Typos
Use methods rather than string concat
Use class names instead of hardcoded strings
Add getTaskClassInstance
> Various CS fixes

- templates/components/photoswipe.html.twig
With recent Twig changes, this code was changed to default to `false` if the parameters were no explicitly specified, which resulted in nothing being printed in the generated JS code for two object values which is not valid.
> Fix photoswipe twig js boolean params

- css/includes/_palette_dark.scss
- templates/components/itilobject/timeline/form_document_item.html.twig
- Fixed issue where the "Upload from" section, where screen captures can be attached, always showed a horizontal scrollbar. You need to be connected in a secure context (HTTPS or localhost) to have the screen capture section show.
- Fixed issue where the text color was too dark in dark palettes in the form because it was never overridden in the base dark palette.
- Removed duplicate max filesize info message. This was originally done as part of #18990 but that PR wasn't accepted. The max upload size is already shown directly in the file input.
> Fix timeline document form UI issues

- phpunit/functional/Glpi/Form/FormTest.php
- src/Glpi/Form/Form.php
The "All" tab for forms is broken. It does load all of the tabs like it is supposed to, but the form editor always takes up the entire tab area and you are not allowed to scroll to see the other tabs. It seems best to just remove the All tab for forms.
> Remove all tab for forms

- .phpstan-baseline.php
- src/Glpi/Asset/AssetDefinition.php
In some cases, `helpdesk_item_type` for a profile may be null and this wasn't handled in a few places for custom assets so it was triggering a deprecation for `json_decode`.
This only really happens if you create a new profile and never set anything on the Assistance tab in the web UI and save it, which was my case. It is probably also possible to get to this state when using the API to configure profile rights.
> Handle null helpdesk types for custom assets

- phpunit/functional/Glpi/Kernel/Listener/RequestListener/LegacyItemtypeRouteListenerTest.php
- src/Glpi/Kernel/Listener/RequestListener/LegacyItemtypeRouteListener.php
- tests/fixtures/plugins/tester/src/Computer.php
**Prevent incorrect redirection when a plugin itemtype shares the same name as a native GLPI itemtype**
In the case of the `PluginCollaborativetoolsWebHook` itemtype, an issue arises when using the generic controller.
Specifically, the plugin’s `webhook.php` controller is mistakenly interpreted as GLPI’s native `webhook.php`, leading to an incorrect redirection or execution context.
This fix ensures that the correct controller is resolved when an itemtype provided by a plugin has the same class name or file name as a native GLPI component.
> Fix legacy itemtype router

- phpunit/functional/Glpi/Form/AccessControl/FormAccessControlManagerTest.php
- src/Glpi/Form/AccessControl/FormAccessControlManager.php
Currently, forms placed in the trash can be viewed by end users.
It is also possible to respond to this form.
This fix prevents end users from viewing and responding to the form while allowing the administrator to edit and preview it.
> fix(forms): Prevent access to deleted forms

- phpunit/functional/Glpi/Form/FormTest.php
- src/Glpi/Form/Form.php
- src/Glpi/Form/ServiceCatalog/Provider/FormProvider.php
- src/Glpi/Helpdesk/Tile/FormTile.php
- tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
- tests/cypress/e2e/self-service/home_config.cy.js
- It fixes #19926
Soft-deleted forms were still displayed in the service catalog and could also be displayed via tiles.
Tiles pointing to a completely deleted form returned an error.
> fix(forms): Exclude deleted forms froms service catalog and tiles display

- src/QuerySubQuery.php
Class QuerySubQuery had 2 arguments in GLPI 10; the 2nd was used to specify the alias of a subquery. The Retrocompatibility implementation does not contains that argument anymore, causing broken SQL queries 
This PR restores the missing argument and transmits it to the new implementation.
> Deprecated QuerySubQuery class misses alias argument

- phpunit/functional/Glpi/UI/IllustrationManagerTest.php
- tests/cypress/e2e/form/form_category.cy.js
- tests/cypress/e2e/illustration_picker.cy.js
Until there is a way to get results from 3rd party libs that do not change between versions; this almost just cause noise. see: #19397, #19544 and #20024.
> Drop tests that depends on 3rd party lib version

- src/Auth.php
- It fixes  #19913
- Better solution than  #20096 
I was finally able to understand what's going on.
* **GLPI**: Beta 6
* **OauthSSO plugin**: 1.11.0-beta5
1. The user authenticates with the identity provider.
2. The user is redirected back to the `OauthSSO` plugin, which fills in the user's information into the appropriate `SSO` fields.
3. A login attempt is made by `OauthSSO` using `Auth->login()` based on the SSO data.
4. GLPI correctly identifies the user but does **not** set `$this->user_present = true` (this issue is addressed in the related pull request).
5. Since `MFA` is enabled for the user, GLPI triggers the `MFA` process.
6. The user enters the verification code.
7. GLPI performs another call to `Auth->login()`.
8. At this point, …
> Fix(Auth): Fix External Auth + MFA + 'is_users_auto_add' -> false

- js/src/vue/Kanban/Kanban.vue
- tests/cypress/e2e/Kanban/kanban.cy.js
Fixes #20088
Moves the search input/filter initialization to be done after the Kanban component is mounted to ensure the source input element exists in the DOM at the time it tries to initialize the `SearchInput`.
> Fix initializing Kanban filter bar

- inc/define.php
- phpunit/functional/DocumentTest.php
- It fixes !38289
- Adds the Rack asset to the document dropdown
> fix(Document): include missing Rack in Document menu dropdown

- templates/pages/setup/general/glpinetwork_setup.html.twig
This is to help users who find the place to add their GLPI Network key, but then cannot find the Marketplace (because one day another admin answered "Never" in the popup when opening the plugins page).
> feat: setup option view for default marketplace

- Makefile
This parameter was missing, meaning the command would update the main DB instead of the test DB.
> Add missing '--env=testing' parameter to test-db-update command

- phpunit/LDAP/AuthLdapTest.php
- src/User.php
- It fixes !36835
Fix accidental deletion of dynamic groups added by something other than rules
> Fix wrong ldap group deletion

- phpunit/functional/Glpi/Inventory/Assets/MonitorTest.php
- src/Inventory/Asset/Monitor.php
- It fixes !38385
Add missing model to RuleImportAsset for Monitor
> Fix(Inventory): add missing model to RuleImportAsset for Monitor

- phpunit/functional/Glpi/Inventory/InventoryTest.php
- src/RuleImportAsset.php
- It fixes #37313
Fix PHP warning
A PHP warning is triggered during inventory when the `RuleImportAsset` rule executes the `RULE_ACTION_LINK_OR_NO_IMPORT` action:
```
[2025-06-30 13:56:55] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "action" in /home/stanislas/GLPI/10bugfixes/src/Inventory/Asset/MainAsset.php at line 594
Backtrace :
src/Inventory/Inventory.php:727                    Glpi\Inventory\Asset\MainAsset->handle()
src/Inventory/Inventory.php:358                    Glpi\Inventory\Inventory->handleItem()
src/Inventory/Request.php:381                      Glpi\Inventory\Inventory->doInventory()
src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory() …
```
> Fix(Inventory): fix output when actio n is RULE_ACTION_LINK_OR_NO_IMPORT

- templates/pages/assistance/planning/single_filter.html.twig
Fixes #20082
An invalid caldav url variable name was causing the group filter list of users to not be added to the DOM.
> fix expanding group planning filters

- phpunit/functional/Glpi/Api/HL/Middleware/DebugRequestMiddlewareTest.php
- src/Glpi/Api/HL/Middleware/DebugRequestMiddleware.php
Adds permission check for the debug mode request middleware.
Also fixes potential issue with using `getHeader` instead of `getHeaderLine`.
> Restrict HLAPI debug mode

- templates/pages/admin/profile/assistance_simple.html.twig
Fixes #19981
This config option for simplified interfaces was missing from the original PR. As noted in the issue, the "Restricted" option is complicated to support when considering the anonymization feature. So, for simplified interfaces I limited the configuration of user mentions to Disabled and Full. This limitation should still meet the original client's request.
> Add missing config for simplified interface mention right

- css/standalone/dashboard.scss
Invert widget type images when using a dark theme so they are visible.
Before             |  After
:-------------------------:|:-------------------------:
> Fix dashboard widget type images in dark mode

- .phpstan-baseline.php
- ajax/reservations.php
- front/reservation.form.php
- js/reservations.js
- src/Reservation.php
- templates/components/form/reservation.html.twig
- tests/cypress/e2e/Tools/reservations.cy.js
Fixes #19946. Loading duplicate JS and other resources cause the page scripts to break. This PR makes the modal load using the AJAX endpoint for both new and editing reservations in modals. Previously, only new reservations were loaded using the AJAX script.
> Change reservation modals to use ajax endpoint

- templates/pages/admin/form/access_control.html.twig
Replace #20062, do not reduce opacity of title + controls.
> Fix opacity concerns for form access controls

- templates/components/illustration/icon.svg.twig
When there is a custom illustration picked, the native illustration HTML is on the page but hidden and the title element is excluded. When you switch to a native illustration, the JS tries to update this missing element and it throws an error which prevents the preview from updating.
> fix illustration preview switching from custom to native

- phpunit/functional/Glpi/Http/FirewallTest.php
- phpunit/functional/Glpi/Http/SessionManagerTest.php
- src/Glpi/CalDAV/Backend/Auth.php
- src/Glpi/Dashboard/Grid.php
- src/Glpi/Http/Firewall.php
- src/Glpi/Http/SessionManager.php
- src/Glpi/Kernel/Listener/ControllerListener/FirewallStrategyListener.php
- src/Glpi/Kernel/Listener/PostBootListener/BootPlugins.php
- src/Glpi/Kernel/Listener/PostBootListener/CheckPluginsStates.php
- src/Glpi/Kernel/Listener/PostBootListener/InitializePlugins.php
- src/Glpi/Kernel/Listener/PostBootListener/ProfilerStart.php
- src/Glpi/Kernel/Listener/PostBootListener/SessionStart.php
- src/Glpi/Kernel/ListenersPriority.php
- src/Glpi/Marketplace/Controller.php
- src/Glpi/Marketplace/View.php
- src/Plugin.php
- src/Session.php
Some plugins are requiring to be able to use "stateless" endpoints. Stateless endpoints are already used in GLPI form machine-to-machine endpoints (API, CalDAV, ...), or for resources that can be publicly shared (embed dashboards, webcal, ...).
The problem is that the session was started prior to the plugins initialization, and some plugins are requiring this because they have to manipulate the session during their initialization. For instance the `localeoverride` plugin have to load its locale files according to the connected user locale, and this information is only available once the session is started.
I had to refactor a little the GLPI (post) boot sequence to add a new `plugin_xxx_boot()` hook that can be used to do some actions during the GLPI boot sequence, after the DB init and …
> Permit plugins to register stateless URLs

- phpunit/functional/Glpi/Form/Destination/CommonITILField/EntityFieldTest.php
- src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
- src/Glpi/Form/Destination/CommonITILField/EntityField.php
- src/Glpi/Form/Destination/CommonITILField/EntityFieldStrategy.php
- src/Glpi/Form/QuestionType/QuestionTypeLongText.php
For unauthenticated forms, disable the `enable_images` settings for textarea questions.
> Forms: prevent unauthenticated users from pasting images

- phpunit/functional/Glpi/Form/Destination/CommonITILField/SLATTOFieldTest.php
- src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
As often in GLPI's there are some rights checks that are misplaced in a low level method (`Ticket::prepareInputForAdd`):
This impact scripts that should not be subject to rights checks, leading to the linked issue.
Fixed by calling the `Session::callAsSystem` method, which is a temporary bypass until we can fix these rights issues correctly.
Fix #20229.
> Bypass rights when creating tickets from forms

- js/modules/ProgressIndicator.js
- phpunit/functional/Glpi/Progress/ProgressStorageTest.php
- phpunit/functional/Glpi/Progress/StoredProgressIndicatorTest.php
- src/Glpi/Controller/InstallController.php
- src/Glpi/Controller/Traits/AsyncOperationProgressControllerTrait.php
- src/Glpi/Kernel/Listener/ExceptionListener/ProgressErrorListener.php
- src/Glpi/Progress/AbstractProgressIndicator.php
- src/Glpi/Progress/ProgressStorage.php
- src/Glpi/Progress/StoredProgressIndicator.php
Non recoverable  and uncaught exceptions during the install/update process were previously handled on client side by considering that a failure happened if no update was done on the server side in the last 60 seconds. The problem is that the operation process may take more than 60 seconds for some specific queries.
I changed the logic to use a `KernelEvents::EXCEPTION` listener to mark unfinished operations as failed when the PHP process exits due to an error.
It closes #20184.
I also moved a reusable of code into a trait to permit to plugins to easilly use the progress indicator JS module.
> Handle install/update operations timeout on server side

- templates/pages/admin/form/form_destination.html.twig
Forced use of the dark color for text in several places in the form destination tab made the feature look broken and hid many of the options in dark themes. I don't see a reason not to use the default color.
Before:
Auror             |  Midnight
:-------------------------:|:-------------------------:
After:
Auror             |  Midnight
:-------------------------:|:-------------------------:
> Remove forced dark text color in form destinations

- src/DBmysql.php
- src/Glpi/Console/AbstractCommand.php
- src/Glpi/Console/Application.php
1. It prevent the DB connection to trigger warnings that will break the session initialization.
2. It prevent outputing the full stack trace in the console output when DB is not available.
Before 1:
Before 2:
After:
> Cleaner error handling on console when DB is unavailable

- phpunit/GLPITestCase.php
- phpunit/functional/Glpi/Asset/CustomFieldDefinitionTest.php
- src/Glpi/Api/HL/Controller/CustomAssetController.php
- src/Glpi/Asset/CustomFieldDefinition.php
- src/Glpi/CustomObject/AbstractDefinition.php
- src/Glpi/CustomObject/AbstractDefinitionManager.php
- src/Glpi/Kernel/Listener/PostBootListener/CustomObjectsBoot.php
- src/Glpi/Kernel/ListenersPriority.php
- src/Glpi/Migration/GenericobjectPluginMigration.php
- tests/src/autoload/functions.php
When a DB update is required, the custom objects autoloader is not registered and the definitions are not booted. However, the `AssetDefinitionManager::getDefinitions()` method returns all the definitions founds in the database, due to its "on demand" loading mechanism.
It can cause issues. For instance, when the plugins are deactivated when a DB update is required, `Plugin->unactivateAll()` is executed and indirectly tries to load the asset definitions (`Glpi\Event::log()` -> ` CommonDBTM->add()` -> `Webhook::raise()`  -> `Webhook::getAPIItemtypeData()` -> `Glpi\Api\HL\Controller\CustomAssetController::getCustomAssetTypes()` -> `Glpi\Asset\AssetDefinitionManager->getDefinitions()`), and then tries to call the `getTypeName()` method on corresponding classes, than cannot be loaded because …
> Prevent custom definitions to be loaded when DB is not up-to-date

- src/Glpi/Console/Traits/PluginMigrationTrait.php
When the migration fail, the "%d items created" message is displayed which is a lie since we rollback the changes in this case. 
It might mislead users, I've made sure we display a "Migration was aborted due to errors, all changes have been reverted" instead message in this case.
Also, some messages were not translated.
> Improve migration command

- src/Glpi/Event.php
- src/Plugin.php
As explained in #20246, changes made to plugins states during the GLPI boot are triggering `CommonDBTM` hooks before the end of the GLPI boot, and it may cause unexpected issues. Indeed, the logic behing business rules, unicity checks, webhooks, etc... can trigger execution of some pieces of code that are not expected to be executed during the GLPI boot.
For the plugins states updates, I propose to use `DBmysql::insert()`/`DBmysql::update()` for every operation made in the `Plugin::checkPluginState()` method.
Events logged when a plugin state change, are also triggering `CommonDBTM` hooks. I checked the GLPI code and all the code of all plugins from the plugin's catalog and I did not see any usage of the `add()`/`update()`/`delete()` methods on an `Event` object. The only method used to …
> Do not use `CommonDBTM` hooks on GLPI boot

- phpunit/functional/Glpi/SocketTest.php
- src/NetworkPortInstantiation.php
- It fixes !38472
When editing a `NetworkPortEthernet`, the displayed socket is retrieved through the `Socket` object, as it's the one maintaining the actual link:
```php
$socket = new Socket();
$value = 0;
if ($netport->getID() && $socket->getFromDBByCrit(['networkports_id' => $netport->getID()])) {
$value = $socket->getID();
}
```
However, when attempting to **remove** the linked socket (i.e. disconnect it), the operation silently fails. The socket is never actually disconnected, because the current code only handles socket **assignment** if a `sockets_id` is explicitly provided and greater than zero:
```php
if (isset($this->input['sockets_id']) && $this->input['sockets_id'] > 0) {
// Handle socket link
}
```
**What Works**
* Adding a new …
> Fix(NetworkPort): disconnect related socket id needed

- src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php
- src/Glpi/Form/Destination/CommonITILField/EntityField.php
- src/Glpi/Form/Destination/CommonITILField/ITILActorField.php
- src/Glpi/Form/Destination/CommonITILField/ITILCategoryField.php
- src/Glpi/Form/Destination/CommonITILField/LocationField.php
- src/Glpi/Form/Destination/CommonITILField/RequestTypeField.php
- src/Glpi/Form/Destination/CommonITILField/UrgencyField.php
- src/Glpi/Form/Destination/CommonITILField/ValidationField.php
Add extra context to some migration errors (the id of the question that we failed to found).
This will help us guide users that experience failures due to corrupted formcreator data without asking them for a database dump.
Before:
> The "Request type" destination field configuration of the form "DSIN-Signaler un Incident" cannot be imported : Question not found in a target form
After:
> The "Request type" destination field configuration of the form "DSIN-Signaler un Incident" cannot be imported : Question '165' not found in a target form
> Add more details to form migration failures

- src/Lockedfield.php
The `is_global` field for locked fields has no purpose in the form display and the value is always removed prior to showing the form anyways. In development env, this causes a Twig strict mode error. The form is only used to create new global locked fields it seems.
> Exclude is_global field from lock form

- phpunit/functional/TicketTest.php
- src/Entity.php
- src/Ticket.php
- templates/pages/admin/entity/survey_config.html.twig
| Fixed tickets | #12219
When a ticket's entity has the survey configuration inherited from a parent, the central list could see a duration of 0 (no limit) instead of the inherited value. This PR makes it retrieve the `inquest_config` value in the SQL and additionally the results with `inquest_config` set to be inherited. Then, for each result that has an inherited config the duration is resolved within PHP and the validity of the survey checked again.
> Fix ticket survey central list widget

- src/SoftwareLicense_User.php
- It fixes !38398
Fixed an issue where the counter badge for "Affected items" in software licenses was not properly updated when users were moved to trash.
When users linked to a software license were moved to trash (`is_deleted = 1`), the counter badge displayed next to "Affected items" was not updated accordingly. The list correctly showed only active users, but the counter included deleted users.
Modified the `countForLicense` method in `SoftwareLicense_User` class to exclude deleted users from the count by adding a JOIN condition with `User::getTable() . '.is_deleted' => 0`.
> Fix (SoftwareLicense_User) - Affected items counter for deleted users

- phpunit/HLAPITestCase.php
- phpunit/functional/Glpi/Api/HL/Controller/GraphQLControllerTest.php
- src/Glpi/Api/HL/GraphQL.php
- src/Glpi/Api/HL/Router.php
Split from https://github.com/glpi-project/glpi/pull/19678
- Implements GraphQL error responses when an error occurs during the search.
- Prevents expanding a schema when the user has no right to see the itemtype
Example:
A User can read tickets but not entities.
The ticket schema includes a partial schema for the `entity` property which includes the ID and name while the full schema includes some other fields like `comment`.
When the user makes a request like:
```graphql
query {
Ticket {
id
name
entity {
id
name
comment
}
}
}
```
The response schema will match the original request but the `comment` property will be null.
> [HLAPI] Handle GraphQL errors and schema expansion limitation

- phpstan.neon.dist
- src/Glpi/Application/SystemConfigurator.php
- src/QueuedWebhook.php
- src/Webhook.php
- stubs/glpi_constants.php
- templates/pages/setup/webhook/webhook_security.html.twig
Add GLPI configuration constant to allow globally requiring Challenge-Response authentication for outgoing webhooks.
Indents were fixed in the template file, so best reviewed with the ignore whitespace changes option.
> Add option to make webhook CRA globally required

- src/Item_Kanban.php
Changing PHP function usages to "Safe" implementations broke the loading of the Kanban because when the JS sends the `timestamp` of the last fetch, the `null` value is automatically converted to an empty string which makes the "Safe" `strtotime` throw an exception instead of returning false (implied 0) which would have made GLPI send the state data like it was expected to do.
The Kanban loading already had a E2E test, but it wasn't catching this even though it completely blocks the loading for me (Suspense component never resolves).
> Fix kanban state loading

- src/Profile.php
Since #14570, Simcard PIN/PUK permission was showing create and delete rights even though only read and update are valid.
> Fix sim pinpuk permission showing useless rights

- phpunit/functional/ImpactTest.php
- src/Impact.php
In some cases, an empty string is passed to the `withtemplate` parameter which causes the check that the item is not a template to fail because an empty string doesn't loosely equal 0.
https://forum.glpi-project.org/viewtopic.php?id=292775
> Fix impact tab in some cases

- .phpstan-baseline.php
- .phpstan-baseline.specific.php
- phpstan.neon.dist
This permit to detect invalid argument types passed to functions/methods. We will not fix these issues in GLPI 10.0, but activate this level in the `10.0/bugfixes` branch will help to prevent introducting new PHPStan issues in the `main` branch during merge operations.
> Activate PHPStan level 5

- phpunit/functional/Glpi/Form/Destination/CommonITILField/ValidationFieldTest.php
- src/Glpi/Form/Destination/CommonITILField/ValidationField.php
- src/Glpi/Form/Destination/CommonITILField/ValidationFieldConfig.php
- src/Glpi/Form/Destination/CommonITILField/ValidationFieldStrategy.php
- templates/pages/admin/form/itil_config_fields/validation.html.twig
- tests/cypress/e2e/form/destination_config_fields/validation.cy.js
Added a new strategy for the validation configuration field.
The `Specific Approval templates` strategy allows you to use approval templates that will be added to the target when it is created.
> feat(forms-destination): Add support for specific approval templates in validation field

- src/Entity.php
- It fixes !38481
The option `Replace the agent and group name with a customizable nickname` is ambiguous.
Currently, there is no option to specify a custom name for groups.
In fact, this option uses a generic name for groups.
```php
public static function getAnonymizedName(?int $entities_id = null): ?string
{
switch (Entity::getAnonymizeConfig($entities_id)) {
default:
case Entity::ANONYMIZE_DISABLED:
return null;
case Entity::ANONYMIZE_USE_GENERIC:
case Entity::ANONYMIZE_USE_NICKNAME: // Here
case Entity::ANONYMIZE_USE_GENERIC_GROUP:
return __("Helpdesk group");
}
}
```
> Fix(Anonymisation): clarify ambiguous option label

- install/empty_data.php
- install/migrations/update_10.0.x_to_11.0.0/configs.php
- install/migrations/update_10.0.x_to_11.0.0/entity.php
- install/migrations/update_9.1.x_to_9.2.0.php
- tests/src/Command/TestUpdatedDataCommand.php
This check will permit to ensure that there are the same configuration entries on a freshly installed DB and on an updated DB. Only the configuration entries names are checked, not values.
Here are the results from a test commit (b456ab2cea9cfca909ec4bb6c718c4eafead1d7e).
> Check configuration entries on updated database

- js/impact.js
When adding elements to a group in impact analysis A, then viewing impact analysis B that shares common elements, new elements appear overlapped instead of taking intelligent positions.
1. `getPresetLayout()` wasn't adding nodes without saved positions to `no_positions` array
2. `insertGraph()` was applying automatic repositioning even for nodes with saved positions, overriding user-defined layouts
- **getPresetLayout**: Add nodes without saved positions to `GLPIImpact.no_positions`
- **insertGraph**: Check if nodes have saved positions before applying automatic repositioning logic
- Preserve user-defined positions while ensuring new nodes get …
> Fix (ImpactAnalysis) - Resolve node overlap when adding elements to shared groups

- phpunit/DbTestCase.php
- phpunit/functional/DBTest.php
- phpunit/functional/Glpi/Migration/AbstractPluginMigrationTest.php
- src/DBmysql.php
- src/Glpi/Form/AnswersHandler/AnswersHandler.php
- src/Glpi/Form/Export/Serializer/FormSerializer.php
- src/Glpi/Form/Form.php
- src/Glpi/Inventory/Inventory.php
- src/Glpi/Migration/AbstractPluginMigration.php
- src/Group_User.php
- src/SavedSearch.php
- src/Ticket.php
- src/Transfer.php
- tests/functional/Glpi/System/Status/StatusChecker.php
A common issue with our tests suite is that the sql transactions that wrap the tests cases conflicts with the transaction from the source code as our DB only support running one transaction at a time.
While searching for answers, I checked what popular tools like doctrine were doing for this kind of issue and found the following:
To sum up, doctrine supports it using SQL savepoint when the begin transaction method is called from inside a transaction.
This result in a seamless experience for developers as they don't have to worry about the current transaction level and can just call the begin transaction method anywhere from the code.
While looking into it, I found that we already support save points but only manually.
This is not ideal as it require a lot of boilerplate each time it is …
> Nested transactions

- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Form/Destination/CommonITILField/ValidationField.php
- src/Glpi/Form/Migration/FormMigration.php
- src/Glpi/Migration/AbstractPluginMigration.php
* Do no import questions with an invalid type (a warning will be emitted)
* Handle already formatted values in `ValidationField::prepareInput()`
Fix #20249.
> Multiple form migrations fixes

- composer.json
- composer.lock
- src/Mail/SMTP/OauthProvider/Google.php
To get PHP 8.4 support, the `league/oauth2-client` library has been updated in #19053. Unfortunately, it was containing a bug (fixed the next day #19053 has been made).
The result of this bug is that the refresh token is not provided anymore by the Oauth authentication provider. Without this token, the authentication expires and the SMTP login fails.
It fixes #20331.
> Fix issues with SMTP/IMAP oauth refresh tokens

- phpunit/functional/ProfileTest.php
- src/Profile.php
- tests/functional/Session.php
Fixes #20007
This PR makes profiles sync rights with the custom asset definition when profiles are created/cloned, not just when they are updated.
> Fix custom asset permissions in cloned profiles

- templates/pages/setup/general/glpinetwork_setup.html.twig
It closes #18964.
Before (I altered the key to make it invalid on the screenshot):
After:
> Hide the GLPI-Network key behind a password field

- src/CommonITILObject.php
- [X ] I have read the CONTRIBUTING document.
- [X ] I have performed a self-review of my code.
When you use Technician anonymization for helpdesk interface, the others requesters & observers are also anonymized. But in fact, the self-service user can add observers on his ticket, so he can see the others users.
> Fix Anonymization For Requesters / Observers

- phpunit/functional/Glpi/Toolbox/DataExportTest.php
- src/Glpi/Toolbox/DataExport.php
It fixes #14476.
This changes was not done in the 10.0/bugfixes branch to be sure to not break existing scripts. However, I think the export format should be enhanced to make it easier to read for end-users, whereas automated scripts should use the API.
> Replace #LBBR# #LBHR# values in CSV/PDF/... exports

- phpunit/functional/NotificationTemplateTest.php
- src/NotificationEventAbstract.php
- src/NotificationTemplate.php
| Fixed tickets | #15875
Fix made in #9929 was working only for the main item of the notification, but all data fetched from database inside `NotificationTarget::getForTemplate()` / `NotificationTarget::addDataForTemplate()` methods was using the timezone of the currently connected user.
> Fix timezone handling in notifications

- templates/pages/admin/form/form_editor.html.twig
This pull request makes a small change to the `form_editor.html.twig` file to enhance the layout's behavior. Specifically, it adds a `data-fix-dropdown-flex` attribute to the `accordion-body` element to address potential issues with dropdown alignment in flexible layouts.
> fix(forms): Fixed incorrect display for the render layout selection option

- src/Html.php
- src/Ticket.php
It fixes the following error:
```
An error occurred
In ./vendor/thecodingmachine/safe/generated/Exceptions/DatetimeException.php(9)
#0 ./vendor/thecodingmachine/safe/generated/8.4/datetime.php(1228): Safe\Exceptions\DatetimeException::createFromPhpError()
#1 ./src/Ticket.php(5465): Safe\strtotime('')
#2 ./src/CommonITILObject.php(5564): Ticket->showStatsDates()
#3 ./src/Ticket.php(823): CommonITILObject->showStats()
#4 ./src/CommonGLPI.php(683): Ticket::displayTabContentForItem(Object(Ticket), '4', 0)
#5 ./ajax/common.tabs.php(111): CommonGLPI::displayStandardTab(Object(Ticket), 'Ticket$4', 0, Array)
#6 ./src/Glpi/Controller/LegacyFileLoadController.php(63): require('./a...')
#7 ./vendor/symfony/http-kernel/HttpKernel.php(181): Glpi\Controller\LegacyFileLoadController->__invoke(Object(Symf …
```
> Fix DateTime exceptions on ticket stats tab

- PluginsMakefile.mk
Add another makefile that plugins can reuse, making it easy for new GLPI dev to work with our docker compose setup.
Adding it in the core mean it is the same for all plugins and they don't need to implement these manually, they just need to write this:
```makefile
PLUGIN_DIR = collaborativetools
USE_COMPOSER = true
USE_NPM = false
include ../../PluginsMakefile.mk
```
> Plugins makefile

- src/Glpi/Api/HL/GraphQL.php
In some cases the HLAPI may return a 206 status for a GraphQL query and it was mistakenly treating it as an error response.
> [HLAPI] Restrict GraphQL errors to 300+ statuses

- composer.json
- composer.lock
This lib was required when GLPI PHPStan rules classes were embed in GLPI (see #19510). Now that they have been moved into a dedicated lib, it is not required anymore.
> Remove `nikic/php-parser` from dev requirements

- phpunit/functional/Glpi/Api/HL/Controller/AssetControllerTest.php
- src/Glpi/Api/HL/Search.php
Fixes #20017
A misidentification of joined properties was causing the search to skip grouping array property results and thus only returning a single result.
> [HLAPI] Fix array properties not returning all elements

- front/reservation.form.php
- phpunit/functional/ReservationTest.php
- src/Reservation.php
- It fixes !38626
Rollback a part of https://github.com/glpi-project/glpi/commit/b5f13320366e795a58cfc31add488fcedb9b8e20
🐛 **Problem**
Users with profiles configured in "simplified interface" (helpdesk mode) cannot create reservations even when they have the "Create" right (`RESERVEANITEM`) enabled for reservable items. The workaround was to temporarily switch to "standard interface", enable the right, then return to "simplified interface".
🔍 **Root Cause**
The issue was caused by hardcoded permission checks in front files instead of delegating to class methods that respect GLPI's permission architecture, specifically the `Reservation::canChildItem` method which grants all rights to users …
> Fix (Reservations) - Allow reservations in simplified interface with RESERVEANITEM right

- phpunit/web/APIRestTest.php
- src/Api/APIRest.php
- It fixes !38568
This error occurs because the code assumes `$this->parameters['input']` is always an object, but JSON can decode to either an object or an array depending on the input format.
Error : 
`[2025-07-28 08:24:07] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Attempt to assign property "id" on array in /home/romain/TECLIB/DEV/GLPI/glpi-10bf/src/Api/APIRest.php at line 344
Backtrace :
apirest.php:57                                     Glpi\Api\APIRest->call()
public/index.php:82                                require()`
The issue is specific to Entity updates due to the condition `($id == 0 && $itemtype == "Entity")` which allows Entity ID 0 to enter the ID assignment logic, …
> Fix (API) - Handle array input types in Entity PUT/PATCH requests

- js/modules/Forms/EditorController.js
- templates/pages/admin/form/form_question.html.twig
Similar to #20431 but for select2 instead of tinymce.
Each form questions have dropdowns (to select the question type) but they are not shown until a question is selected.
To speed up initial load, we can delay initializing the dropdowns of a question until it is selected.
Partial improvement for https://github.com/glpi-project/glpi/issues/20416.
> Lazy load form editor dropdowns

- CHANGELOG.md
- ajax/dropdownAllItems.php
- ajax/selectUnaffectedOrNewItem_Device.php
- src/Item_Devices.php
- templates/components/assets/link_existing_or_new_item_device.html.twig
Fixes #20491
Fixes #18713
Changes:
1. Dropdown label for individual components is no longer a dump of every single field in a confusing mess of hyphens, blank spaces, and unintelligible random numbers. Dropdown type fields (which would be IDs for things like locations) and fields that are set as "nodisplay" are not included (like PIN/PUK).
2. A helper was added to inform the user what the label pattern is. For example, SIM cards are `Serial number - Inventory number - MSIN`.
3. The SQL query for the dropdown values was changes so that null values are not excluded. This allows the labels to always conform to the pattern told to the user.
> Enhance component link UX

- css/palettes/midnight.scss
Partial revert of https://github.com/glpi-project/glpi/pull/16908 to fix several uses of muted text in Midnight including the breadcrumbs likes and some text in the debug bar. Since `$dark` is black and the main background color in this theme is also black, muted text is invisible.
> fix midnight theme muted color

- src/Glpi/Api/HL/Controller/AbstractController.php
- src/Glpi/Api/HL/Doc/SearchRoute.php
- src/Glpi/Api/HL/GraphQL.php
- src/Glpi/Api/HL/GraphQLGenerator.php
- src/Glpi/Api/HL/Search.php
- src/Glpi/Api/HL/Search/RecordSet.php
- src/Glpi/Api/HL/Search/SearchContext.php
- src/Glpi/Debug/Profiler.php
- Refactor search results into a RecordSet class and move hydration logic into the new class. This is to reduce complexity in the HLAPI Search class and isolate the logic for later optimization.
- Add some profiling to identify bottlenecks for later optimization
Currently, there are two notable performance bottlenecks for the HLAPI.
1. Building the GraphQL schema. This could be later improved by caching the schema or possibly with lazy type resolution.
2. Record hydration. The initial search only retrieves the top-level data for records. Then, it goes to a hydration set where the joined data is retrieved. This was done to allow more flexibility, and less complexity than we would get with a single SQL query. Depending on the number of results, and the number of joins, this could result in …
> [HLAPI] RecordSet refactor

- install/migrations/update_10.0.x_to_11.0.0/remindertranslations.php
- install/mysql/glpi-empty.sql
Typically, we have used 10 character length columns for storing language codes. For some reason, there are two exceptions currently:
1. Reminder translations which have existed since GLPI 9.5
2. Item Translations which were added for GLPI 11
Not every language code is 5 characters or less in our hard-coded languages. Currently, both of these limited columns would prevent adding translations for the Latin America Spanish language which has a code of `es_419`.
> Fix language column lengths

- psalm.xml
- src/Plugin.php
- src/autoload/legacy-autoloader.php
Existing includes were safe. I just added a check on the `$plugin_key` parameter of the `Plugin::includeHook()` method to be sure that it cannot be used to include a file outside the expected plugin directory tree.
> Fix detected Psalm `TaintedInclude` issues

- phpunit/functional/Glpi/Form/Translation/FormTranslationTest.php
- src/Glpi/Form/Comment.php
- src/Glpi/Form/Form.php
- src/Glpi/Form/Question.php
- src/Glpi/Form/Section.php
- It fixes #20495
Remove translations of form elements when deleting them.
> fix(forms): Delete form translations after parent item deleted

- css/includes/_base.scss
Latest Tabler updated added forced button animations and forces a minimum button width and height for all buttons which breaks our entity selector list at least. We shouldn't be using their animated buttons anyways, so this reverts the forced min sizes.
See https://github.com/tabler/tabler/pull/2401
> Remove forced min button sizes

- templates/layout/parts/profile_selector.html.twig
Long entity names could overflow the entity selector.
> fix overflow of long entity names in selector

- src/Certificate_Item.php
- Fix missing icon in Certificates tab for assets
- Fix hard-coded use of "2" as a plural count
> fix icon and plurals for certificate tab

- src/ItemVirtualMachine.php
The permission to update Computers should not be a blocker in viewing ItemVirtualMachine. This is also not related to the actual parent itemtype since this is a generic class now instead of ComputerVirtualMachine. The second commit changes the `canedit` check to check the ability to update the specific parent asset.
> Fix ItemVirtualMachine showForm rights

- src/Appliance_Item_Relation.php
Remove bottom margin from the appliance relation list (Appliances tab of an asset). This is more of an annoyance if there are no relations yet but the `ul` element is still present which leaves a large gap above the add button.
Fixed:
> remove margin from appliance relation list

- phpunit/functional/Glpi/Helpdesk/Translation/HelpdeskTranslationTest.php
- src/Entity.php
- src/Glpi/Helpdesk/HelpdeskTranslation.php
- src/Glpi/Helpdesk/Tile/ExternalPageTile.php
- src/Glpi/Helpdesk/Tile/FormTile.php
- src/Glpi/Helpdesk/Tile/GlpiPageTile.php
- src/Glpi/Helpdesk/Tile/TileInterface.php
- templates/pages/helpdesk/index.html.twig
Same as https://github.com/glpi-project/glpi/pull/20507 but for helpdesk translations.
I also took the opportunity to remove the "double translation" from the forms with `FormTile`.
> fix(forms): Delete helpdesk translations after parent item deleted

- src/SNMPCredential.php
- templates/components/form/snmpcredential.html.twig
- First it fixes triple-DES support as getEncryption() API wasn't reporting it for value "3". As far I can see this bug was still present in FusionInventory plugin.
- Secondly it adds definitions for new auth protocols (sha224, sha256, sha384 and sha512) and priv protocols (Cisco AES192 & AES256). The use of these protocols will actually requires to use current glpi-agent nightly build. It also requires Net::SNMP v6.0.1 perl library on the system, but this is the case for all recent linux distro and glpi-agent MacOS & Windows builds. These conditions may require a documentation update.
- Here is a brief description of what this PR does:
- `getEncryption()` method now returns "3DES" as expected for value "3" as it should
- Twig templates includes new values for new protocols and …
> Update SNMP v3 protocols definitions

- psalm.xml
- src/Glpi/System/Log/LogParser.php
- src/UploadHandler.php
I keep the `TaintedCallable` and `TaintedLdap` errors suppression config. These are pretty hard to handle with our current code and with the current Psalm limitations.
Anyway, the initial purpose was to detect potential XSS, and lots of issues were detected. Maybe there are false negatives, but we may improve the configuration later.
> Fix remaining legitimate Psalm issues

- templates/components/search/displaypreference_list.html.twig
Add breakpoints to display one/two/three/four items per line depending on screen size:
Hide long content behind text ellipsis:
Fix #20553
> Improve search config UI

- phpunit/functional/ChangeTest.php
- phpunit/functional/ProblemTest.php
- src/CommonITILObject.php
- src/Ticket.php
Fix a missing twig variable preventing a closed change or problem to be displayed.
After investigation, I saw that the missing variable was linked to some logic specific to the ticket but used in the parent itil object class.
I've improved it by moving the default behavior into a dedicated method than can then be overridden properly by the ticket class.
> Fix closed change rendering

- phpunit/functional/RuleTest.php
- src/CommonITILObject.php
- src/Rule.php
- src/RuleChange.php
- src/RuleCommonITILObject.php
- src/RuleProblem.php
- src/RuleTicket.php
When rules on changes and problems were added,  some calls to `Ticket::dropdownUrgency` were replaced by `CommonITILObject::dropdownUrgency` in the rules code (same for impact dropdowns).
This do not work because the `dropdownUrgency` depends on static variables that are redefined by the child classes like `Ticket` or `Change`.
Calling `dropdownUrgency` on `CommonITILObject` will thus always return a select with 0 options.
I've fixed the code by loading the correct child class before calling `dropdownUrgency` and made sure calling `CommonITILObject::dropdownUrgency` directly throw an error so we don't do it by mistake.
Fix #20546.
> Fix urgency and impact rule criteria

- front/item_enclosure.form.php
- src/Item_Enclosure.php
Before:
After:
As a side note, you might find the 'Add' and 'Template' menu suprising as they target the enclosure type, not the item enclosure type.
However, this is what we do for others similar types, see virtual machines on computers for example:
Fix #20531.
> Fix breadcrumbs and type name for enclosure items

- phpunit/functional/CommonDBTMTest.php
- src/DBConnection.php
`DBConnection` do not have a database table and thus has no reason to be a `CommonDBTM`.
Fix #20545.
Note: I did not test the exact scenario from the issue, but I see that the relevant code from the stack trace check explicitly the `CommonDBTM` type so there is no reason the issue should persist after this.
> Make DBConnection inherit CommonGLPI instead of CommonDBTM

- phpunit/web/APIRestTest.php
- src/Glpi/Api/API.php
A request for `Glpi\\CustomAsset\\Test01Asset` for example was returning assets of every definition because of the way the legacy API pieces together SQL criteria from the search engine.
Also affected `ItemTranslation` which I noticed while troubleshooting a different issue.
> Fix legacy API ignoring getSystemSQLCriteria

- src/Glpi/Dashboard/Widget.php
- src/PrinterLog.php
- tests/cypress/e2e/Asset/printer.cy.js
Fix missing scripts for the printer graph tab on printers and infocom reports.
This is caused by a bad practice, the code from the widgets class depends on some module that it doesn't load.
It works on the main dashboards page because we load the module there before loading the graphs in a separated ajax request, but it can't be replicated easily on the printer page because the graph and tab are in the same request and you can't make two independent scripts tags wait for each others.
I've fixed it by manually importing the module where it is needed.
This has no impact on the main dashboard page where the module was already loaded as browsers will only import modules once.
To review with whitespace change off, there are not much change but some code is wrapped in a anonymous methods so …
> Fix printer graphs and infocom report charts

- phpunit/functional/Glpi/Search/SearchOptionTest.php
- src/DisplayPreference.php
- src/Glpi/Search/SearchOption.php
Part of #20533
There was logic in both `DisplayPreference::getFixedColumns` and `SearchOption::getDefaultToView` to handle the columns always shown in search results. `SearchOption` was using newer, more flexible logic. I replaced uses of `DisplayPreference::getFixedColumns` with the newer method and fixed an issue with Ticket/Change/Problem IDs not being forced shown like was expected.
> deduplicate default search columns logic

- templates/pages/helpdesk/search.html.twig
We strip tags here because we don't want the html to be rendered, there isn't enough space.
Before:
After:
> Fix home search results displaying escaped html

- phpunit/DbTestCase.php
- phpunit/functional/Glpi/Helpdesk/Tile/TilesManagerTest.php
- src/Glpi/Helpdesk/Tile/FormTile.php
- src/Glpi/Helpdesk/Tile/GlpiPageTile.php
Rarely, self service user may not be allowed to see or create tickets.
These change take this into account when picking which tiles to display:
* Form tiles are hidden if the user can't create tickets
* Service catalog tile is hidden if the user can't create tickets
* "See my tickets" tiles is hidden if the user can't read tickets
> Filter home tiles on tickets rights

- js/impact.js
- src/Impact.php
- tests/js/bootstrap.mjs
- tests/js/impact.test.js
- tests/js/jest.config.js
Fixes #20528
Changes the search criteria used when clicking a badge in the impact graph so that the metacriteria for an asset's ID is used instead of the "Associated element" ID Ticket search option which is usually not meant to be searchable. If we cannot identify the correct metacriteria ID field, the previous behavior is used. If the metacriteria is not used, it shows a confusing criteria in the query builder "Items seen contains X" where X is the asset ID.
This PR also starts testing the Impact JS via Jest where there were no JS unit tests for this feature before.
> fix impact badge search criteria

- .github/workflows/ci.yml
E2E timeouts occasionally happen due to how slow the tests are and the fact they can all retry up to 3 times, so in some cases a bug may cause them to get cancelled for exceeding 90 minutes. In that case, the Cypress screenshots and GLPI logs were not being attached because a cancelled test isn't considered failed.
I think this will fix that, but I don't know how to reliably test it.
> try to add e2e artifiacts on cancellation too

- phpunit/HLAPITestCase.php
- phpunit/functional/Glpi/Api/HL/Controller/AdministrationControllerTest.php
- phpunit/functional/Glpi/Api/HL/Controller/CoreControllerTest.php
- phpunit/functional/Glpi/Api/HL/Controller/GraphQLControllerTest.php
- resources/api_doc.MD
- src/Glpi/Api/HL/Middleware/OAuthRequestMiddleware.php
- src/Glpi/OAuth/Server.php
- tests/src/autoload/functions.php
- Separates access to the GraphQL endpoint from the generic `api` OAuth scope. The GraphQL endpoint is a little more capable than the regular Rest API of causing the server to process a lot of data. I think it is better to split this into its own scope now to let GLPI admins decide who really needs access to it.
- Fixes scope checks from within the test environment as it was being detected as CLI and bypassing them.
- Adds scope tests.
> [HLAPI] Add GraphQL scope and fix scope checks

- phpunit/functional/NotificationAjaxSettingTest.php
- phpunit/functional/NotificationMailingSettingTest.php
- src/AuthMail.php
- src/CommonGLPI.php
- src/CommonITILRecurrent.php
- src/Config.php
- src/DisplayPreference.php
- src/DomainRecord.php
- src/Glpi/Inventory/Conf.php
- src/Knowbase.php
- src/KnowbaseItemTranslation.php
- src/Location.php
- src/NotificationSetting.php
- src/Planning.php
- src/ReservationItem.php
- src/RuleCollection.php
- src/RuleImportAssetCollection.php
- src/Software.php
`getTabNameForItem()` must return safe HTML. I did not found how to help Pslam to detect unescaped texts, so I just validate that every tab entry is created with `CommonDBTM::createTabEntry()`.
I added some icons that were missing.
> Fix tabs text escaping and add some missing icons

- phpunit/web/APIRestTest.php
- src/Glpi/Application/View/Extension/I18nExtension.php
- src/Glpi/Form/FormTranslation.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeShortAnswer.php
- src/Glpi/Form/QuestionType/QuestionTypeLongText.php
- src/Glpi/Helpdesk/HelpdeskTranslation.php
- src/Glpi/ItemTranslation/ItemTranslation.php
- templates/pages/form_renderer.html.twig
- templates/pages/helpdesk/index.html.twig
- tests/src/autoload/functions.php
Since `ItemTranslation` was designed to use a generic table for translations while also accessing that table through child classes `FormTranslation` and `HelpdeskTranslation`, there must be a `getSystemSQLCriteria` defined for each to limit relevant results. Also, since it was designed this way, the `ItemTranslation` class itself must be abstract so it isn't used directly.
> fix ItemTranslation not limiting sql criteria

- src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
Some js code related to the dropdown questiontype trigger a change event on initialization (probably to fix some rendering issues related to select2 if I recall correctly), thus marking the form as unsaved.
Fixed by correcting the state manually after this code is finished.
Fix #20663.
> Fix unsaved form state on load

- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Form/QuestionType/QuestionTypeItemDropdown.php
Fixed `convertExtraData` method in `QuestionTypeItemDropdown` to handle empty or non-string `values` fields.
> fix(forms-migration): Handle invalid DropdownItem configs

- src/Dropdown.php
- src/Supplier.php
Fix display of the extra dropdown links for Supplier dropdowns.
| Old Dark  | Old Light |
| ------------- | ------------- |
| <img width="374" height="56" alt="Selection_586" src="https://github.com/user-attachments/assets/9e8a6e75-9304-42e3-9cec-eeedda38d758" />  | <img width="603" height="54" alt="Selection_587" src="https://github.com/user-attachments/assets/84481e31-9ae4-4a35-8a45-1bbdc9a8866e" />  |
New:
> remove img usage in supplier links

- .php-cs-fixer.dist.php
- phpunit.xml.dist
- rector.php
Two of these caches (rector and php cs fixer) were stored in /tmp.
The issue is that if you run multiple dev instances on the same setup, the cache files will be identical for both.
I didn't run into the issue myself as I use docker so no conflicts are possible (/tmp is unique per GLPI instance) but it might be an issue for non-docker users.
I've moved them into `files/_cache` to avoid this, and also moved the phpunit cache there as it is currently polluting the root folder.
> Move dev cache files into files/_cache

- src/GLPIKey.php
- It fixes a wrong phpdoc throws (already catched in the method) and add a missing catch for base64_decode
> GLPIKey::decrypt: Fix invalid method throws and add missing catch for base64_decode

- src/Glpi/Api/HL/Middleware/DebugResponseMiddleware.php
Fixes #20520 (real issue in comment).
For requests that return no body, like DELETE requests, the middleware used to work properly and got an empty result from the JSON functions. Changes to use the "safe" wrappers caused it to break because an empty body wasn't recognized as valid JSON and therefore triggered an exception to be thrown.
> handle non-json responses in debug middleware

- phpunit/bootstrap.php
- tests/bootstrap.php
It will permit to use this bootstrap file for plugins tests.
> Use absolute path for console execution in tests bootstrap

- src/Agent.php
- src/Glpi/Marketplace/Api/Plugins.php
- src/Toolbox.php
- It removes a throws in the phpdoc that was never thrown (catched inside the glpi decrypt function)
- Also add the parameter default value to empty array @cedric-anne will this cause any issue since the method signature is changed ??
> Toolbox getGuzzleClient: Remove phpdoc throws that is never throws

- templates/pages/admin/user.substitute.html.twig
- tests/cypress/e2e/Admin/user.cy.js
The validation delegation feature allows you to designate one or more users who can validate a ticket on your behalf.
However, this was not what was reflected in the code — only users with the right to “create a validation request” were selectable.
This fix corrects it :)
> fix(delegators): incorrect rights for filtering users

- css/helpdesk_home.scss
- templates/pages/helpdesk/index.html.twig
The line height used for the helpdesk home page search title did not play well with long multi line text.
Before:
After:
> Fix homepage title line height

- templates/pages/admin/form/form_editor.html.twig
Pressing "enter" in the form editor would trigger the preview action instead of saving the form.
This was fixed by reordering the buttons to make sure the submit action is first, while keeping the same rendering by tweaking the flex direction.
Diff is mainly reordering the buttons in the code, no other hidden changes besides:
* Removing an orphan `</button>` tag
* Removing some outdated TODOs
> Fix form editor "Enter" behavior

- js/modules/Forms/RendererController.js
- tests/cypress/e2e/form/form_rendering.cy.js
Fixes TinyMCE content validation in forms by ensuring rich text editor content is properly saved before section validation. Includes improved test coverage for multi-section forms and mandatory field validation scenarios.
> fix(forms): improve TinyMCE content saving and validation handling

- install/empty_data.php
- install/migrations/update_10.0.x_to_11.0.0/mfa.php
- phpunit/functional/Glpi/Security/TOTPManagerTest.php
- src/Glpi/Security/TOTPManager.php
- templates/pages/2fa/2fa_request.html.twig
- templates/pages/2fa/macros.html.twig
- templates/pages/setup/general/security_setup.html.twig
- It fixes #20728 and #20757 
- This fixes correct a 2fa input text overlap on mobile and also add the possibility to set a suffix for the 2fa issuer in the Authenticator app
> Handle 2FA issuer suffix and fix 2FA display issue

- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Form/QuestionType/QuestionTypeItemDropdown.php
Formcreator plugin migration fails to properly handle negative show_tree_depth values. A value of -1 (meaning "show all levels") was incorrectly processed as a valid depth restriction.
> fix(forms-migration): handle negative tree depth values for dropdown item questions

- templates/pages/admin/form/import/step3_resolve_issues.html.twig
While checking out an issue related to this feature, I've noticed that some extra context in the "Resolve issue" step indicating clearly the target itemtype would be helpful.
Before:
After:
> Add extra context to form import issues

- css/includes/components/_documentation.scss
On "medium-ish" screen sizes, TOC of "getting started" HLAPI documentation overlaps the content.
I increased the size to 240px to match the TOC width and move the breakpoint on `xxl` where the issue disappears.
> fix TOC overflow on smaller screen sizes

- phpunit/functional/PluginTest.php
- src/Glpi/Application/Environment.php
- src/Plugin.php
- tests/fixtures/marketplace/myplugin/setup.php
- tests/functional/Plugin.php
In GLPI 11.0, moving the marketplace directory outside the GLPI root directory is now possible. Even if the method is deprecated, `Plugin::getWebDir()` should handle it to provide a valid URL path.
See https://github.com/glpi-project/docker-images/issues/197
> Fix `Plugin::getWebDir()` results with customized `GLPI_MARKETPLACE_DIR`

- src/CommonDBVisible.php
There is no opening `<table>` tag corresponding to this closing `</table>` tag.
> Remove unexpected `</table>` tag

- phpunit/functional/Glpi/Form/Export/FormSerializerAccessPoliciesTest.php
- phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
- src/Glpi/Form/AccessControl/ControlType/AllowList.php
- src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php
- src/Glpi/Form/Destination/CommonITILField/EntityField.php
- src/Glpi/Form/Destination/CommonITILField/ITILActorField.php
- src/Glpi/Form/Destination/CommonITILField/ITILCategoryField.php
- src/Glpi/Form/Destination/CommonITILField/ITILFollowupField.php
- src/Glpi/Form/Destination/CommonITILField/ITILTaskField.php
- src/Glpi/Form/Destination/CommonITILField/LinkedITILObjectsField.php
- src/Glpi/Form/Destination/CommonITILField/LocationField.php
- src/Glpi/Form/Destination/CommonITILField/SLMField.php
- src/Glpi/Form/Destination/CommonITILField/TemplateField.php
- src/Glpi/Form/Destination/CommonITILField/ValidationField.php
- src/Glpi/Form/Export/Context/DatabaseMapper.php
- src/Glpi/Form/Export/Serializer/FormSerializer.php
- src/Glpi/Form/Export/Specification/DataRequirementSpecification.php
- src/Glpi/Form/Export/Specification/FormContentSpecification.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
- src/Glpi/Form/QuestionType/QuestionTypeItem.php
- tests/fixtures/export-of-2-forms.json
When importing or exporting forms, we use the name of the required items (e.g. specific entities or categories).
This isn't ideal for `CommonTreeDropdown` items as they may have duplicated names, is it best to rely on the full completename to make sure we target the right item.
> Take completenames into acount in form export/import

- src/Glpi/Asset/AssetType.php
Search class could not be able to retrieve the concrete class when using `getItemTypeForTable()`
closes #20789
> Fix generic asset type search pages

- src/Glpi/Controller/Form/Import/Step3ResolveIssuesController.php
- templates/pages/admin/form/import/step3_resolve_issues.html.twig
First commit is form another PR, I'll rebase once it is merged.
When resolving issues on form import, the selected values are stored in temporary inputs like this:
There was a conflict on the array input used as new values would also be put at the start of the `replacements` array (so resolving issues on a form would erases resolved issues form another form).
I've fixed it by making sure we are always adding new values at the end of the array.
There was also an issue regarding types, the ids needs to be casted to int as they are stored as strings in $_POST.
> Form import: fix conflicts when resolving issues for multiple forms

- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Form/Migration/FormMigration.php
- It partially fixes #20205
Check whether the operator is supported by the question type when migrating conditions on questions.
Some operators are not supported by the new form integration.
Warning displayed if conditions are not imported.
> fix(migration): handle unsupported value operators in form migration conditions

- .gitignore
- tests/code-coverage/clover.xml
This should not have been added. This comes from the latest merge from the 10.0 branch; but the file do not exists on this one. Maybe just a mistake while merging?
I hope adding to `.gitignore` will prevent this issue in the future.
> Remove unexpected directory

- ajax/dropdownAllItems.php
```
[2025-08-28 09:58:10] glpi.NOTICE:   *** require() in ./ajax/dropdownAllItems.php line 86
Only strings can be json to decode! 
```
> Only call jsonDecode if used is not an array

- css/includes/_palette_dark.scss
It fixes #20725
Current PR make a global style for **all** dark palettes when displaying home and “service catalog” icons.
**darker**
**midnight**
**dark auror**
> better adaptive colors icons for dark palettes

- phpunit/functional/Glpi/Form/Condition/ConditionHandler/EmptyConditionHandlerTest.php
- phpunit/functional/Glpi/Form/Condition/EditorManagerTest.php
- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Form/AnswersHandler/AnswersHandler.php
- src/Glpi/Form/Condition/ConditionHandler/EmptyConditionHandler.php
- src/Glpi/Form/Condition/ValueOperator.php
- src/Glpi/Form/Migration/FormMigration.php
- src/Glpi/Form/QuestionType/AbstractQuestionType.php
- tests/cypress/e2e/form/editor/conditions.cy.js
Addition of two new value operators for visibility conditions.
These operators replace conditions using comparison operators with an empty value during migration.
These workarounds seem to be widely used by Formcreator users but will no longer be possible in the new form integration.
> feat(forms): Implement "Is empty/Is not empty" value operator

- templates/components/form/reservation.html.twig
Show repetition options as a full width field to avoid it being too small in the form.
PR in draft until the other part of the report can be verified/fixed.
> Adjust display of reservation repitition fields

- templates/pages/admin/form/access_control/direct_access.html.twig
If a form token leak, users might need to be able to refresh it:
Let me know if you prefer it done on main instead, but since it is kinda security related and low impact I thought it was OK to add to the RC.
> Allow form direct access token to be refreshed

- js/fileupload.js
- js/modules/Forms/Condition/Engine.js
- js/modules/Forms/RendererController.js
- tests/cypress/e2e/form/editor/conditions.cy.js
- #20823 must be merged before
Correction of the upload detection and upload deletion behavior of the condition engine and the JS rendering controller.
Currently, when you add a file to a `File` type question,  the addition is not detected to initiate a new calculation of visibility conditions, and when the form is submitted to the condition rendering engine, it does not detect the file.
> fix(forms): Detect changes made to the `File` question type when rendering the form

- css/helpdesk_home.scss
Small UI tweak to make sure the helpdesk scenes stays to the bottom of their container even if the title is longer than expected.
Before:
After:
> Make sure helpdesk scenes stick to the bottom

- phpunit/functional/Glpi/Form/Condition/ConditionDataTest.php
- src/Glpi/Form/Condition/ConditionData.php
- src/Glpi/Form/Condition/ConditionableTrait.php
It is possible to end up with "empty" conditions; if a visibility strategy is defined but no source item is defined, the default value (`0`) is sent.
This does not cause any problems for processing or displaying conditions, but it is problematic when exporting forms.
> fix(forms): Add validation logic to ConditionData to filter invalid conditions

- src/GLPIKey.php
Using `chr` with a value outside the 0-255 range is deprecated. I reproduced the logic automatically made by PHP, see https://www.php.net/manual/en/function.chr.php
> Values outside the valid range (0..255) will be bitwise and'ed with 255, which is equivalent to the following algorithm:
> ```php
> while ($bytevalue < 0) {
>     $bytevalue += 256;
> }
> $bytevalue %= 256;
> ```
This fixes the following issue:
```
Deprecated: chr(): Providing a value not in-between 0 and 255 is deprecated, this is because a byte value must be in the [0, 255] interval. The value used will be constrained using % 256 at GLPIKey.php line 485
#0 /var/www/glpi/src/GLPIKey.php(304): GLPIKey->decryptUsingLegacyKey('\x85X\xA3T\x8F\x9E\x90s\xA2\x0Fz\xE4\xCF\x8A\x88...')
#1 /var/www/glpi/src/GLPIKey.php(212): …
```
> Fix `chr(): Providing a value not in-between 0 and 255 is deprecated`

- front/report.dynamic.php
Since #11323, the KB list uses the generic implementation of the search engine. Therefore, the export feature should also use the generic implementation.
It fixes #20890.
> Fix KB export

- templates/components/form/fields_macros.html.twig
- templates/components/form/link_existing_or_new.html.twig
- templates/components/form/reservation.html.twig
- templates/generic_show_form.html.twig
- templates/pages/admin/form/question_type/item_dropdown/end_user_template.html.twig
Follows #20849.
The `label` parameter will never be used. I kept the ability to define options, for instance to define a specific `id`, or some data attributes values.
> Hidden fields have no label

- css/includes/_base.scss
- css/includes/components/_select2.scss
I saw this since months but didn't took the time to fix it.
It's subtle but a bit annoying
**Before**
**After**
There is also a double border between the select and the add button, but cannot tackle it for the moment
> neutralize a few annoying shadow (notably in healpdesk fields)

- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Form/Migration/FormMigration.php
- src/Glpi/Form/Migration/TypesConversionMapper.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeShortAnswer.php
- src/Glpi/Form/QuestionType/QuestionTypeDateTime.php
- src/Glpi/Form/QuestionType/QuestionTypeFile.php
- src/Glpi/Form/QuestionType/QuestionTypeItem.php
- src/Glpi/Form/QuestionType/QuestionTypeLongText.php
- src/Glpi/Form/QuestionType/QuestionTypeRequestType.php
- src/Glpi/Form/QuestionType/QuestionTypeUrgency.php
- tests/fixtures/plugins/tester/src/Form/QuestionTypeIpConverter.php
Since plugins are allowed to add new question types, it make sense to also allow them to integrate them into the form migration.
For example, a plugin that add the "Ip address" question type (a type from formcreator that we did not reuse in native forms) might want to make sure his new type is taken into account during the formcreator -> core migration.
> Allow plugins to hook into the form question types migration process

- tools/build_glpi.sh
I don't think this file is needed in a production environment?
> fix: remove PluginsMakefile from official build

- templates/components/infocom.html.twig
closes #20918
Seems the format has been lost during Twig conversion, in 9.5 those fields were displayed using `Html::formatNumber()` method
> Missed format on some values

- composer.json
The new composer patch block the composer install command if it is already applied:
> Fix already applied composer patch

- phpunit/functional/SoftwareLicenseTest.php
- src/SoftwareLicense.php
- templates/pages/management/license_progressbar.html.twig
- templates/pages/management/softwarelicense.html.twig
closes #20976
I did not find how to "use" a child licence; so maybe existing ones with a `number` field set to `0` can cause issues.
> Number of licence cannot be 0

- templates/pages/admin/form/form_comment.html.twig
We use "New question" and "New section" for questions and section but "Add a title..." for form comment:
I've renamed it to "New comment" to be consistent with questions and sections.
> Rename new form comment placeholder

- css/includes/components/form/_form-renderer.scss
- templates/pages/admin/form/form_question.html.twig
- templates/pages/form_renderer.html.twig
- tests/cypress/e2e/form/editor/conditions.cy.js
- tests/cypress/e2e/form/editor/validations.cy.js
I originally decided to put the description below the questions because this is a UI standard for small hints under a form field,
However a lot of formcreator users were using very long descriptions so it break the "small hint" effect that I was looking for.
With this in mind, it seems better to move the description above the question, like it was done on formcreator.
Before:
After:
Fix #20960 (and some internal complaints too).
> Put description above form sections

- src/Glpi/Dashboard/FakeProvider.php
The "Tickets status by month" graph was displayed with an invcerted chronological order. Similar `array_reverse` operations are present in the other dashboard graphs.
Before:
After:
> Fix "Tickets status by month" fake series order

- js/common.js
This is an edge case, but the fuzzy search was made on a an escaped text, so if the text was containing an HTML special char (`<`, `>` or `&`), searching for `&`, for instance, was outputing something like `R*&*amp;D`, and searching for `a` was outputing something like `R&*a*mp;D`.
Now, the escaping is made after the fuzzy search, so searching for `&` will output `R*&*D`.
> Fix escaping of array dropdown matches

- js/common.js
- js/modules/ObjectLock.js
- js/src/vue/Debug/Widget/ProfilerTable.vue
- js/src/vue/Debug/Widget/SQLRequests.vue
- js/src/vue/Kanban/Kanban.vue
- js/src/vue/Kanban/SearchInput.js
- templates/components/itilobject/actors/field.html.twig
- tests/js/modules/ObjectLock.test.js
While working on HTML escaping in the JS code context, I figured out that we still had a specific `escapeMarkupText()` function that escapes the text only if it contains `<` or `>`. This was doing the job in GLPI 10., when we had an autoescaping of almost everything, but it is not safe anymore in GLPI 11.0.
Also, we could directly use the `_.escape()` method from the `lodash` component, as we do in other pieces of our code.
> Replace `escapeMarkupText()` by `_.escape()`

- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Form/Condition/ConditionHandler/ItemConditionHandler.php
Prioritize using `completename` to retrieve a dropdown item rather than the name, avoiding results with multiple items; this causes the migration of formcreator forms to the new form system to crash.
> fix(migration): Use completename as a priority to retrieve dropdown item

- css/includes/components/_tinymce.scss
I don't know how to call it, but tinyce add some UI thing when the user click on readonly nodes:
I don't understand what is the purpose here but I doesn't look great and it is confusing (making it looks like the tag is duplicated) so I've removed it.
> Hide duplicated rich text tags UI thing

- js/src/vue/Debug/Widget/ProfilerTable.vue
- src/Glpi/Debug/Profiler.php
- tests/cypress/e2e/DebugMode/debug_bar.cy.js
Some profiler cleanup work while I was chasing an unusual performance issue with the cache initialization.
- Remove start and end timestamps as they do not have much use but were taking up a lot of horizontal space.
- Add auto-ended information which can be used to indicate a profiler section was not manually ended and therefore the timings for it may not be accurate as it was only ended at the end of the request. Under normal circumstances, only the "php_request" section can be expected to be auto-ended.
> improve profiler info in debug bar

- src/Glpi/Http/SessionManager.php
When `samesite=strict` is used for session cookies, the browser will send the cookies to GLPI only if the referer page is a GLPI page too. It means that when the Oauth provider redirects the user to the GLPI Oauth callback URL, the GLPI session cookie is not sent to the server.
To bypass this limitation, the `/front/smtp_oauth2_callback.php` endpoint will redirect to itself when its URL does not contain a specific flag. The browser will so reload the URL and pass the GLPI session cookie in the request headers. This require the `/front/smtp_oauth2_callback.php` endpoint to be loaded in stateless mode unless the `cookie_refresh` URL param is set, to be sure that it will not create a new session when the GLPI session cookie is not passed in the first request.
If fixes #20980.
> Fix SMTP Oauth2 callback compat with `samesite=strict` cookies

- src/Config.php
- src/Glpi/Api/HL/Router.php
- templates/pages/setup/general/api_setup.html.twig
Prevents 
```
Key "enable_hlapi" for sequence/mapping with keys "[...]" does not exist in "pages/setup/general/api_setup.html.twig" at line 41.
In ./templates/pages/setup/general/api_setup.html.twig(41)
```
After saving, the entry is added in the database.
> Prevent missing index in Twig file

- phpunit/functional/Glpi/Form/Destination/CommonITILField/AssociatedItemsFieldTest.php
- src/Glpi/Form/Destination/CommonITILField/AssociatedItemsFieldStrategy.php
Forms with assets questions were only added correctly to the destination ticket for english users.
This is because `CommonITILObject::getAllTypesForHelpdesk` return locales dependent values, we must check its keys instead to validate a given itemtype.
> Fix associated items from form not being set for non english users

- Makefile
- docker-compose.yaml
- tests/cypress/README.md
Allow cypress tests to run inside docker without any configuration, which will make it easier for newcomers to run them easily on their machine.
> Run cypress with docker

- phpunit/functional/Glpi/Form/Clone/FormCloneHelperTest.php
- src/Glpi/Form/Clone/FormCloneHelper.php
- src/Glpi/Form/Destination/CommonITILField/ContentField.php
- src/Glpi/Form/Destination/CommonITILField/TitleField.php
- src/Glpi/Form/Destination/HasFormTags.php
- src/Glpi/Form/Tag/AnswerTagProvider.php
- src/Glpi/Form/Tag/CommentDescriptionTagProvider.php
- src/Glpi/Form/Tag/CommentTitleTagProvider.php
- src/Glpi/Form/Tag/QuestionTagProvider.php
- src/Glpi/Form/Tag/SectionTagProvider.php
- src/Glpi/Form/Tag/TagWithIdValueInterface.php
Form tags can contains IDs references to its questions:
This need to be taken into account when cloning a form as we want the ID to match the newly cloned form parts, not the original form parts.
It will also need to be handled for the export/import feature, I'll do it in another PR once this one is merged.
> Take form tags into account when cloning

- templates/components/infocom.html.twig
This closes https://github.com/glpi-project/glpi/issues/21034, and reopen https://github.com/glpi-project/glpi/issues/20918 (which is just a display problem).
Same as #21120 - on 10.0/bugfixes branch.
> Revert "Missed format on some values"

- templates/components/search/display_data.html.twig
Seen on the Queries Log tab for webhooks. On initial load, the massive action checkboxes are hidden, but if the search results are refreshed the checkboxes appear. This was because the fluid search code was not preserving this parameter.
> Preserve showmassiveactions on search refresh

- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Form/Migration/FormMigration.php
Fixes #21146
I haven't used the plugin much but it sounds like all forms in the plugin were shown as a single page, so for consistency the migrated forms should all use the single page layout by default.
> Migrate forms as single page render layout

- phpunit/HLAPITestCase.php
- src/Glpi/Api/HL/Controller/AbstractController.php
- src/Glpi/Api/HL/Controller/AdministrationController.php
- src/Glpi/Api/HL/Controller/AssetController.php
- src/Glpi/Api/HL/Controller/ComponentController.php
- src/Glpi/Api/HL/Controller/CustomAssetController.php
- src/Glpi/Api/HL/Controller/DropdownController.php
- src/Glpi/Api/HL/Controller/ITILController.php
- src/Glpi/Api/HL/Controller/ManagementController.php
- src/Glpi/Api/HL/Controller/ProjectController.php
- src/Glpi/Api/HL/Controller/RuleController.php
- src/Glpi/Api/HL/Controller/SetupController.php
- src/Glpi/Api/HL/Doc/Schema.php
- src/Glpi/Api/HL/OpenAPIGenerator.php
- src/Glpi/Api/HL/ResourceAccessor.php
- src/Glpi/Api/HL/Search.php
- src/Glpi/Api/HL/Search/RecordSet.php
Fixes #21166
Use official schema feature for specifying properties that are read-only or write-only instead of extensions. This allows better compatibility, which can be seen in Swagger UI where it automatically hides the read-only properties from request bodies and write-only properties from response bodies.
Get User Response:
Create User Request Body:
Not that the password fields, which can only be written to, do not show as part of the response schema.
> [HLAPI] use readOnly and writeOnly

- front/tracking.injector.php
- It fixes !39426
When a self-service user created a ticket for themselves and had the option to delegate via their groups, the requester did not appear in the ticket that was created.
> Fix(ticket): missing requestor

- templates/pages/setup/webhook/payload_editor.html.twig
- tests/cypress/e2e/Setup/webhooks.cy.js
Fix what appears to be a race condition affecting the payload editor for webhooks. The Monaco editor initialization is started, but the container element is hidden before it can finish which causes the editor to have a 5px size instead of properly resizing to the parent.
This PR moves some logic after the editor creation promise resolves and also forces another editor layout when switching to the editor from the default payload.
> Fix monaco editor layout race condition

- composer.json
- src/CommonITILObject.php
- src/Dropdown.php
- src/Search.php
- templates/generic_show_form.html.twig
- tools/patches/symfony-string-php8.5-compat.patch
It fixes `Using null as an array offset is deprecated, use an empty string instead` deprecations triggered by the test suite.
> Fix PHP 8.5 deprecations

- phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
- src/Glpi/Form/Migration/FormMigration.php
Limits the categories migrated when migration has been restricted to certain forms.
> fix(forms-migration): Limit the import of form categories when the import is restricted to certain forms

- templates/components/illustration/custom_icon.html.twig
When using custom illustration with .png format in the service catalog, the image height follows the description on its side due to the parent set in display flex.
**Before:**
**After:**
> fix custom icons adapting to tile's description

- templates/components/illustration/custom_icon.html.twig
Due to the last tabler release (👋🏽 @cconard96 😬), a global style is applied on all img (`max-width: 100%`)
To note, for the moment, I made the change applied on the local part to avoid to manage issues now
**Before:**
**After:**
> fix sizing of icons on service-catalog

- js/RichText/UserMention.js
- js/cable.js
- js/common.js
- js/fileupload.js
- js/glpi_dialog.js
- js/impact.js
- js/planning.js
- js/rack.js
- js/reservations.js
- js/src/vue/CustomObject/FieldPreview/FieldDisplay.vue
- js/src/vue/Debug/Toolbar.vue
- js/src/vue/Debug/Widget/HTTPRequests.vue
- js/src/vue/Debug/Widget/SQLRequests.vue
- js/src/vue/Kanban/Kanban.vue
- js/src/vue/Kanban/SearchInput.js
- js/src/vue/Kanban/TeamBadgeProvider.js
- js/stencil-editor.js
- src/Glpi/Controller/GenericAjaxCrudController.php
- src/Html.php
- src/Item_Rack.php
- templates/components/search/displaypreference_config.html.twig
- templates/pages/setup/dropdowns_list.html.twig
- tests/functional/Glpi/Controller/GenericAjaxCrudControllerTest.php
> Enforce escaping in JS scripts (2/x)

- src/Glpi/Asset/CustomFieldType/DropdownType.php
- src/Glpi/DBAL/QueryFunction.php
- tests/functional/Glpi/Api/HL/Controller/CustomAssetControllerTest.php
- tests/functional/Glpi/Asset/CustomFieldDefinitionTest.php
- tests/functional/Glpi/Migration/GenericobjectPluginMigrationTest.php
- tests/src/autoload/functions.php
Fixes #21162
Fix condition for dropdown custom field search option joins when multiple selection are allowed.
Fix usage of `glpi_assets_assets` table instead of `REFTABLE` in join conditions.
Add dropdown custom fields (single and multiple) to test dataset for automatic search tests to take them into account.
> Fix dropdown custom field search options

- css/includes/components/form/_form-editor.scss
- js/modules/Forms/ItemAdvancedConfig.js
- src/Glpi/Form/QuestionType/QuestionTypeItem.php
- templates/pages/admin/form/question_type/item/advanced_configuration.html.twig
- templates/pages/admin/form/question_type/item_dropdown/advanced_configuration.html.twig
Added support for advanced configuration for all `CommonTreeDropdown` elements in `Item` questions.
Fixed a minor UI bug that broke the dropdown borders even when the button to display advanced options was hidden.
> fix(forms): Support for all CommonTreeDropdown for advanced configuration for Item questions

- src/Glpi/Application/ImportMapGenerator.php
The URLs contained in the importmap are corresponding to the full path of the JS files, including the GLPI root path. When this GLPI root path change, the cache should not be reused.
As it depends on the server configuration, we cannot know whenever we have to trigger the cache invalidation, so I propose to add the GLPI root path in the cache key to handle this.
> Invalidate the JS importmap cache when GLPI URL changes

- js/modules/Dashboard/Dashboard.js
- src/Glpi/Dashboard/Item.php
- [x,y,w,h] are not present anymore in gridstack items when equal to 0 (why ?) and so saving set the data to null in DB
probably fix #21239
> xywh attributes are missing when equals 0 on gridstack

- inc/define.php
- phpunit/functional/DropdownTest.php
Chilean Spanish language was missing from the dropdown because the MO file listed in the config was missing the extension. Since the file wasn't found, it was being excluded. A test was added to try to catch this kind of typo.
> Fix missing es_CL language

- src/Glpi/OAuth/RefreshTokenRepository.php
- tests/functional/Glpi/OAuth/RefreshTokenRepositoryTest.php
Yet another issue found while working on an app using GLPI OAuth where a SQL query tries selecting the `id` column in the refresh token table which does not exist. The `identifier` column is the primary key.
> [OAuth] Fix invalid column in refresh token revoke check

- src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
- src/Glpi/Form/Destination/FormDestinationManager.php
- tests/cypress/e2e/form/form_plugins.cy.js
- tests/fixtures/plugins/tester/setup.php
- tests/fixtures/plugins/tester/src/Form/ExternalIDField.php
- tests/fixtures/plugins/tester/src/Form/ExternalIDFieldConfig.php
- tests/fixtures/plugins/tester/src/Form/ExternalIDFieldStrategy.php
- tests/fixtures/plugins/tester/templates/external_id_config_field.html.twig
- tests/functional/Glpi/Form/Migration/TargetsMigrationTest.php
Allow plugins to define their own destination config fields
> feat(forms): Allow plugins to define their own destination config fields

- src/Glpi/Form/Dropdown/FormActorsDropdown.php
- src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
-> can't be tested with PHPUnit.
Filter actors questions, the logic was already there but the `right_for_users` parameter was not supplied.
I've also removed empty header results (e.g. no "groups" header in the dropdown if no groups were found).
Fix #21113.
> Filter actor questions in end users forms

- src/CommonITILTask.php
- tests/functional/CommonITILTaskTestCase.php
- Remove the forced behavior of auto assign tech in ticket from task, there are a lot of (justified) complaints in #21232
- The behavior will be implemented again in the incoming plugin moreoptions by @Lainow 
I did a manual revert, as the initial commit 74a22aa5039965341b5e34bbab1c868a2f3d1f9c start to be old and conflicting
> manualy revert #16033, fix #21232

- src/Glpi/Application/View/Extension/FrontEndAssetsExtension.php
Currently, the global JS variable `GLPI_PLUGINS_PATH` returns a list of paths for available plugins.
However, this list does not define keys for its values, which is problematic given that in previous versions we expected the key for each path to correspond to the name of the plugin.
This behavior is already present in the `getCoreVariablesForJavascript` method in `Html.php`.
> fix(plugins): Use array_combine to associate plugin keys with their paths

- src/Glpi/Form/AnswersHandler/AnswersHandler.php
- tests/functional/Glpi/Form/AnswersHandler/AnswersHandlerTest.php
Use the value returned by `transformConditionValueForComparisons` from `ConditionValueTransformerInterface` to correctly handle mandatory questions.
Currently, some questions are considered filled when they are not; for example, item type questions that use the value -1 to represent their empty value.
> fix(forms): Use ConditionValueTransformerInterface for complex mandatory answers

- CHANGELOG.md
- src/Ticket.php
Revert #19193
Ref support !39607
We have several customers reporting a regression in this feature for resolved and closed tickets.
In a typical use case:
- A ticket is resolved, and the solution validation notification is sent to the requester.
- A few days later, the automatic closure timer is triggered, the ticket is then closed.
- Finally, the requester replies with a message such as "Thank you!" (by email). This does not reopen the original ticket but instead creates a new one.
Customers were using the “Merge as Followups” feature to delete this new ticket and merge it as a follow-up to the closed ticket (without having to reopen the closed one).
This was, in my opinion, an important use case for the feature.
Regarding the original …
> revert show unsolved tickets in merge target dropdown

- js/modules/Forms/ServiceCatalogController.js
- src/CommonTreeDropdown.php
- src/Glpi/Controller/ServiceCatalog/ItemsController.php
- src/Glpi/Form/ServiceCatalog/Provider/CategoryProvider.php
- templates/components/helpdesk_forms/service_catalog_items.html.twig
- tests/functional/DropdownTest.php
- tests/functional/Glpi/Form/ServiceCatalog/Provider/CategoryProviderTest.php
Forms category are now visible in url and history so user can favorite a category page.
The breadcrumb structure is now returned by the backend and not anymore based on the browser history
> Add forms category in URLs

- src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
- tests/functional/Glpi/Form/Destination/CommonITILField/TemplateFieldTest.php
Adding a "NOW" predefined fields like this would lead to an SQL error when creating a ticket through an helpdesk form:
Fix #21267
> Fix forms failure when a template use the "NOW" value

- js/reservations.js
- src/Reservation.php
It fixes #21255.
1. The asset type localized name is now displayed instead of the asset class name.
2. The modal is now larger.
> Fix reservation modal display

- src/CommonITILObject.php
- tests/functional/TicketTest.php
It fixes #21229.
We should probably remove usages of the `"NULL"` strings in our whole codebase, but it is massively used and may have unexpected side effects, so I propose to just handle this specific case for the moment.
For information, these values are defined here: https://github.com/glpi-project/glpi/blob/077736c7c28b6dacfafcb7aa6d828f2ae43b90b6/src/CommonITILObject.php#L2301-L2310
Setting a `null` value instead of the `"NULL"` string would change the result of every following `isset()` test, and I am not really able to predict how the code will behave with this.
> Fix solve/close dates stats computations

- src/Glpi/Search/Provider/SQLProvider.php
- tests/functional/SearchTest.php
If fixes #21295.
In GLPI 10.0, numeric chars were not allowed in itemtype names (regex was `/ITEM(_(\w[^\d]+))?_(\d+)(_(.+))?/`). Now they are allowed, we have to use a lazy quantifier in the regex to not capture the search option num with the itemtype.
> Fix search results fields reconciliation
