tests/LDAP/AuthLdap.php
tests/LDAP/ldap_run.sh

add sso tests

---

inc/dbmysql.class.php
inc/dbmysqliterator.class.php
tests/units/DB.php
tests/units/DBmysqlIterator.php

Alias support in DBmysql; drop private quoteName in iterator
| Fixed tickets | #2327

Add aliases support on queries; closes #2327

---

inc/auth.class.php
index.php

remove auth icon from login when no additional available

---

inc/html.class.php

Added cache suffix for TinyMCE

---

inc/define.php

Fixed tiny_mce load (Close #3663)

---

composer.json
composer.lock
front/logout.php
inc/auth.class.php
inc/autoload.function.php
inc/config.class.php
inc/toolbox.class.php

remove phpcas lib

---

inc/mailcollector.class.php

Fixed author from mail on cron CLI (Close #2498)

---

tools/cleanhistory.php

Edit - changed grammar in a comment

---

inc/html.class.php
js/common.js

Factorize JS code

---

composer.json
composer.lock

Latest atoum, use dot report

---

inc/ajax.class.php

Do not consider aborted loads as errors

---

inc/ticket.class.php

Fixed line break display for content of ticket

---

inc/ticket.class.php

Fixed date displayed in timeline (Close #3722)

---

front/device.form.php
inc/commondropdown.class.php

Item type must be specified; handle posted itemtype

---

inc/config.class.php

No array tag expected in fordebug; fixes #3701

---

inc/search.class.php

Use iterator; escape value to fix #3750

---

inc/savedsearch.class.php

Added search in searches panel (Close #3136)

---

inc/html.class.php

Load analytics script if present

---

inc/state.class.php

Do not chek unicity if unicity fields did not change; fixes #3699

---

inc/ticket.class.php
tests/functionnal/Ticket.php

| Tests pass?   | 
| Fixed tickets | #3368

Category not replaced in closed tickets #3368

---

inc/ticket.class.php

Add document for helpdesk

---

inc/html.class.php
inc/search.class.php

Reword; fixes #3730

---

composer.json
composer.lock
inc/ipaddress.class.php
inc/state.class.php
tools/generate_bigdump.function.php
tools/generate_bigdump.php

| Fixed tickets | #939
Just fixed the logged warnings, maybe we have some part non functional anymore (i think about computers operating systems for example)

fix warnings in generate_bigdump

---

ajax/dropdownProjectTaskTicket.php
ajax/getDropdownValue.php
inc/project.class.php
inc/projecttask_ticket.class.php

Link a project task from the ticket fix #3665

---

inc/ticket.class.php

Keep files infos; fixes #3741

---

inc/search.class.php
tests/functionnal/Search.php

Fix dropdown translations; closes #3751

---

front/report.year.list.php
inc/define.php

Do not rely on contract_types from year reports; fixes #3781

---

inc/user.class.php

Check is array; fixes #3780

---

inc/search.class.php

Use dedicated method instead of concatenate strings

---

inc/dropdown.class.php

Not closed html element; fixes #3531

---

install/update_92_921.php

Check for the right field

---

inc/ticket.class.php

Do not add solution when ticket is solved
Do not show "Add" whan nothing is allowed
| Fixed tickets | #2761

Do not add document on closed tickets; fix #2761

---

install/mysql/glpi-empty.sql
install/update_92_93.php

Permit same license several times on same computer; fixes #3560

---

inc/computer.class.php

fix computer template - see #3798

---

inc/auth.class.php

Contains also some new constant for easier reading

display an error when ldap connection fails

---

ajax/dropdownTrackingDeviceType.php
inc/item_ticket.class.php

Make sure id is unique; fixes #3198

---

inc/massiveaction.class.php
inc/ticket.class.php

Restore rely on delete right, not purge; fixes #3165

---

ajax/timeline.php
inc/ticket.class.php

Fix task checkbox title on change; closes #3160

---

tests/units/DBmysqlIterator.php

| Fixed tickets | #2328
Just a new test for existing feature

Add a test on multiple joins; fixes #2328

---

inc/networkequipment.class.php

Replace deprecated each()

---

inc/session.class.php

Improve isCron check; fixes #3817

---

inc/change_ticket.class.php

Add ticket position on change the same as add problem/project

---

inc/user.class.php

Add email in user perso informations; fixes #2346

---

inc/item_ticket.class.php

Drop extra column; refs #3161

---

inc/ticket.class.php

Load entity from itemtype on ticket creation; fxes #2173

---

inc/levelagreement.class.php

Display comment in SLA tooltip; fxes #3321

---

inc/document.class.php

Take care of copy/pasted images in KB; fixes #3343

---

inc/ticket.class.php

Fix task creation from simplified interface; closes #2283

---

README.md

Fix prerequisites and install/update docs

---

tests/LDAP/README.md
tests/README.md

running in place of runing

---

inc/config.class.php
inc/purgelogs.class.php
install/mysql/glpi-empty.sql
install/update_92_93.php
tests/functionnal/Config.php

Reintregrate purgelogs plugin

---

inc/html.class.php

Factorize, log message if file has not been found; fixes #3843

---

inc/project.class.php

Check entities recursively; fixes #3848

---

inc/search.class.php

Fix bad search option

---

inc/budget.class.php
inc/certificate.class.php
inc/commonitiltask.class.php
inc/computer.class.php
inc/computerantivirus.class.php
inc/item_operatingsystem.class.php
inc/notepad.class.php
inc/software.class.php
inc/softwarelicense.class.php

Prefix som search options; closes #2681

---

css/styles.css
inc/ticket.class.php

Fix display; closes #3737

---

inc/slm.class.php

Add comment in search options; fixes #3846

---

inc/consumableitem.class.php

Add history for consumable items; fixes #3034

---

ajax/getKbRevision.php
inc/html.class.php

Fix multiple

---

inc/dbmysqliterator.class.php
install/install.php

Fix errors on last step of install wizard

---

inc/purgelogs.class.php

Drop old class references; fixes #3882

---

tools/generate_bigdump.function.php

Object has been renamed

---

front/stat.graph.php

use correct dates in stats > tickets (graph mode)

---

inc/search.class.php

| Fixed tickets | #3894
Crappy fix, a rewrite pr will follow for 9.3/bugfixes (don't cherry pick this one so)

add decomission date in Search::isInfocomOption

---

.circleci/config.yml
inc/config.class.php
inc/dbmysql.class.php
inc/toolbox.class.php
inc/update.class.php
tests/functionnal/Config.php

Add tests
Check db engine on update

Add check for db engine version

---

inc/search.class.php
tests/units/Search.php

| Fixed tickets | #3894
Cherry-pick on master

rewrite isInfocomOption, follows #3898

---

inc/define.php

Fix schema version

---

inc/knowbaseitem_comment.class.php

Check comment ACL on the right object; fixes #3901

---

inc/commonitiltask.class.php

fix #1776 planning in central

---

inc/config.class.php

Fix database checks display on upgrade screen

---

inc/user.class.php

Remove user picture along with user; fixes #3905

---

inc/savedsearch_alert.class.php

Multiple Problem with the cronSavedSearchesAlerts fix #3920

---

inc/define.php
inc/update.class.php
install/update_93_94.php
scripts/cliupdate.php

Bump version, add update script

---

inc/user.class.php
tests/functionnal/KnowbaseItem_Revision.php

use DB::delete() instead of raw queries

---

tools/generate_bigdump.php

Allow to pass user and password calling script; closes #3911

---

inc/config.class.php

Fix display on command line

---

install/update_922_923.php

Fix notification templates issues from 9.2 migration

---

front/backup.php

Not to be merged before 9.2.3 relase since its add new strings to translate.

Add warning message about internal backup

---

css/styles.css
inc/dropdown.class.php
inc/html.class.php
inc/log.class.php
js/log_filters.js
tests/functionnal/Log.php

Add log history filters

---

inc/config.php
inc/notificationeventmailing.class.php
inc/notificationmailing.class.php

Typos, refs #3945

---

ajax/getKbRevision.php

Fix "PHP Fatal error:  Call to undefined method Html::entity_decode() in $DOC/glpi/ajax/getKbRevision.php on line 54"
| BC breaks?    | 
| Deprecations? | 
| Tests pass?   | 

Fix undefined method

---

composer.json
composer.lock

Fix dependency version; closes #3931

---

inc/rack.class.php

Typo, refs #3945

---

inc/auth.class.php
inc/session.class.php
inc/user.class.php
index.php
js/common.js

Allows to select lang on login. Will be useful on demo.

Add language selector on login page

---

inc/knowbaseitem.class.php

Wrong variable used; fixes #3953

---

inc/group_user.class.php

fix assign group from a user - see #3778

---

inc/event.class.php
index.php
tools/checkfunction.php

Demo will be reset, this is no longer relevant

Drop countlogin

---

.circleci/config.yml
inc/toolbox.class.php

force image/svg+xml mime to be downloaded

---

inc/toolbox.class.php
tests/functionnal/Ticket.php

Fix escaping quote issue; closes #1264

---

inc/notificationeventmailing.class.php

Improve regexp; refs #3932

---

inc/define.php

add Line to global search

---

inc/location.class.php

Fix undefined index

---

README.md

Fix display of README

---

css/styles.css
inc/commonitilobject.class.php
inc/ticket.class.php
js/common.js

fix splitted button in timeline forms; fix #3938

---

css/style_install.css
inc/config.class.php
inc/toolbox.class.php
install/install.php

- Fix install which silently break
- Fix bad CSS & JS URL
Replace PR #3940 
Fix #3997

Fix installation

---

inc/control.class.php
inc/slm.class.php

Use getSearchURL() instead of hardcoded URL

---

front/dictionnary.php
inc/rulecollection.class.php

Replace hardcoded list with array from class

---

inc/config.class.php

Make defaut cache namespace unique to prvent multi instances issues

---

inc/tasktemplate.class.php

Enlarge default size for task template content field; closes #4021

---

inc/notificationtargetsavedsearch_alert.class.php

Deprecated method called

---

inc/savedsearch.class.php

Undefined variables; closes #4014

---

inc/dbmysql.class.php

Fix warning when fail to established DB connection; fixes #4027

---

inc/auth.class.php
inc/config.class.php
inc/notification.class.php
inc/ticket.class.php

Another bunch of hardcoded paths replacement

---

CHANGELOG.md

Add Select2 upgrade entry in changelog

---

inc/contract.class.php

| Fixed tickets | #2596
- Fix bad computation for the date of the first alert
- Disable contracts notification for deleted contracts (trashbin)
- Simplify coding logic
- Remove unused vars
Close #2596

Fix contract reminder notifications

---

css/styles.css

Fix extraline in dc room; closes #3988 (thanks to @orthagh)

---

inc/contract.class.php

Fixes #2596
Unused stuff
Refactor of coding logic - simplify
| Fixed tickets | #2596 
Same as https://github.com/glpi-project/glpi/pull/3877 for 9.2.

Don't run a cron on deleted contracts; thanks to @AnaelMobilia

---

inc/notificationeventmailing.class.php

Fix regexps; refs #3932

---

inc/commonitiltask.class.php
inc/dropdown.class.php
inc/html.class.php
inc/projecttask.class.php
inc/projecttasktemplate.class.php
tests/units/Html.php

| Fixed tickets | #3895 
Proposal for a more generic solution than 4003

programmaticaly set value for ajax dropdown

---

inc/define.php
inc/plugin.class.php
inc/transfer.class.php
scripts/add_creation_date.php

Fix remaning ComputerDisks references; closes #4036

---

.circleci/config.yml
inc/config.class.php
inc/update.class.php
install/update.php

Fix upgradenotices

---

css/styles.css
inc/commonitiltask.class.php
inc/html.class.php
inc/itilsolution.class.php
inc/projecttask.class.php
inc/reminder.class.php
inc/ticket.class.php
inc/ticketfollowup.class.php

Add ability to use lists in tickets texts; closes #3575

---

inc/dropdown.class.php
inc/user.class.php

Do not lower type name; fixes #4054

---

install/update.php
install/update_content.php

Prevent script to ba called directly

---

CHANGELOG.md
front/item_device.common.form.php
front/item_device.php
inc/commondevice.class.php
inc/item_devices.class.php
install/update_92_93.php

Add Item_Device* searchable lists

---

files/.htaccess
install/mysql/.htaccess
locales/.htaccess
scripts/.htaccess

Change htaccess for Apache 2.4

---

inc/planning.class.php

fix display planning for change task - see #4062

---

install/update.php
install/update_content.php

Better way to restrict content_update.pp direct access

---

install/mysql/glpi-empty.sql
tools/demo_data.sql

Demodata script

---

inc/rack.class.php

Non positionned racks were considered in; fixes #4068

---

inc/computer.class.php
inc/networkequipment.class.php
inc/printer.class.php

fix network label

---

inc/ticket.class.php
tools/demo_data.sql
tools/generate_bigdump.function.php

Solutions has changed

---

inc/notificationtargetprojecttask.class.php

Fix deprecated msg for NotificationTargetProjectTask::getTeamSuppliers()

---

inc/commonitilactor.class.php

Remove condition that seems useless

---

inc/define.php
inc/item_devices.class.php

Add missing conf; make mass actions on components check config

---

inc/consumableitem.class.php

Fix SQL date query; closes #3994

---

CHANGELOG.md
inc/dropdown.class.php

Deprecate showPrivatePublicSwitch

---

inc/commondropdown.class.php
tests/functionnal/CommonDropdown.php

Do not use locations id on item update; fixes #3584

---

inc/knowbaseitem_item.class.php
tests/functionnal/KnowbaseItem_Item.php

Viewing the "Knowledge base" tab without right fix #4007

---

inc/search.class.php

Take care of not for priority and impact; fixes #4095

---

inc/config.class.php

Do not check library if not present; fixes #4096

---

inc/certificate.class.php
inc/search.class.php

Display link for associated items in certificates; fixes #4044

---

inc/plugin.class.php
tests/functionnal/Plugin.php

Fix GLPI version check on plugin compatibility

---

front/backup.php

- Update XML dump to have date and version on filename
- Use the DB query builder

Clean backup

---

inc/ticket.class.php
tests/functionnal/Ticket.php

Fixes #4099

---

inc/auth.class.php
tests/functionnal/Auth.php

Move auth methods listing in its own method (no display)

---

tests/units/DB.php
tests/units/Migration.php

Add new unit tests

---

CHANGELOG.md

Add missing deprecated in 9.2+ changelog

---

css/styles.css

Fix focused style on form elements; fixes #4118

---

CHANGELOG.md

Fix 9.3 deprecated list in changelog

---

css/styles.css
inc/html.class.php
inc/search.class.php

| Fixed tickets | #1166
Replace #1210

Work on popups in sarch list

---

inc/knowbaseitem.class.php

| Fixed tickets | 0
Add Associated Documents To Knowbaseitem List

Add Associated Documents To Knowbaseitem List

---

inc/toolbox.class.php

| Fixed tickets | https://github.com/pluginsGLPI/genericobject/issues/179

Fix redirections when object url contains params

---

inc/plugin.class.php
tests/functionnal/Plugin.php

Fix compatibility check wordings

---

inc/auth.class.php
inc/planning.class.php
inc/user.class.php
tests/APIBaseClass.php
tests/functionnal/User.php
tests/web/APIRest.php

make User::getToken not static

---

ajax/getDropdownUsers.php
ajax/searchoptionvalue.php
inc/user.class.php

Fixes #1590
| Fixed tickets | #1590

Added an option (inactive_deleted) to get also inactive or deleted users from getSqlSearchResult()

---

install/update_92_93.php

Fix solutions migration

---

inc/commondbtm.class.php
inc/group_user.class.php

This prevents bugs and possible xss.

Ensure quotes are escaped in link title; drop unused code

---

inc/ticket.class.php

Use autolink on non converted html; closes #3907

---

front/ticket.form.php

Ensure data are escaped; fixes #4141

---

css/highcontrast.css
inc/change.class.php
inc/ticket.class.php

Fix high contrast border display

---

install/update_92_93.php

Rework solutions migration; closes #4146

---

inc/ajax.class.php

| Fixed tickets | #4171
Regression in c2f9b8302c8

fix jquery ajax call on savedsearch

---

scripts/checkdb.php

Logger was not initialized; closes #4169

---

inc/dbmysqliterator.class.php
tests/units/DBmysqlIterator.php

Fix regression on legacy queries detection introduced along with aliases support

Fix mode SQL query

---

inc/itilsolution.class.php
inc/ticket_ticket.class.php
tests/functionnal/ITILSolution.php

Fix undefined index
Add tests on solutions for duplicated tickets
Make sure there is no loop
Create new empty solution for add
| Fixed tickets | #4173

Fix solutions; closes #4173

---

apirest.md

Update apirest.md : Capitalize spelling of API

---

ajax/savedsearch.php
inc/search.class.php

Fix potential undefined index

---

inc/search.class.php

Check if link oprator is in list

---

inc/ticket.class.php

Fix search URL; closes #4166

---

composer.json
composer.lock
scripts/cliinstall.php

1/ prompt for password to avoid having it saved in history/log
For security extremists, like @kapouik ;)
This change mimics the `mysql` command behavior.
2/ as zend-console is added for previous, use a modern and robust Getopt instead of the old trivial implementation

Improve cliinstall

---

inc/dbmysql.class.php
scripts/cliinstall.php
scripts/cliupdate.php

Check db version on cli scripts; closes #4167

---

apirest.md

Capitalize keywords (JSON, URL, etc)
Minor spelling and grammar edits

Update apirest.md : Spelling and grammar fixes

---

scripts/innodb_migration.php

Add some infos running innodb migration script.

---

inc/update.class.php

Break update on unknown version

---

inc/itilsolution.class.php

permits to view itil solutions with api

---

inc/user.class.php
tests/LDAP/AuthLdap.php

Fix user modification date on email update

---

CHANGELOG.md
inc/commondbtm.class.php
inc/commonitilobject.class.php
inc/commonitiltask.class.php
inc/config.class.php
inc/document.class.php
inc/document_item.class.php
inc/html.class.php
inc/itilsolution.class.php
inc/knowbaseitem.class.php
inc/mailcollector.class.php
inc/ticket.class.php
inc/ticketfollowup.class.php
inc/toolbox.class.php
install/mysql/glpi-empty.sql
install/update_93_94.php
tests/functionnal/Ticket.php
tools/demo_data.sql

| BC breaks?    | well...
| Fixed tickets | #4138

Drop use_rich_text parameter, closes #4138

---

inc/ticket.class.php

we can update takeintoacccountstat without update on some cases

---

inc/commonitilobject.class.php
inc/commonitiltask.class.php
inc/search.class.php
inc/stat.class.php
inc/ticket.class.php

Improve a bit queries using an integer querying is_deleted

Explicit integer querying is_deleted

---

ajax/map.php
inc/search.class.php

Fix map on tickets

---

inc/commondbtm.class.php
inc/search.class.php

Do not display map control on items that cannot be located

---

inc/rulecollection.class.php

Ensure HTML entities are decoded; fixes #4248

---

CHANGELOG.md
inc/config.php
inc/define.php
inc/update.class.php

Will be merged on release day only.

Prepare release

---

.circleci/config.yml

Run CS checks on PHP 7.2 only

---

inc/central.class.php
inc/define.php

Change warnings on central

---

front/computer_softwareversion.form.php

To be marged after 9.3 release since it adds new strings.

Add error messages on software installations

---

inc/search.class.php

Select distinct itemtype.id; fixes #4154

---

inc/auth.class.php

Change login errors

---

inc/config.php
inc/session.class.php

Try to handle deprecated config parameters

---

inc/devicepci.class.php

Fix model dropdown in 'Other component' form; fixes #4259

---

inc/document_item.class.php

Ensure content is escaped; fix #4258

---

inc/notificationtargetcommonitilobject.class.php

Notifications for new solutions; fixes #4266

---

inc/define.php
inc/update.class.php
install/mysql/glpi-empty.sql
install/update_930_931.php

Change field type; closes #4242

---

inc/rack.class.php

| Fixed tickets | #4267 
There was code missing from the rack class's prepareInputForAdd. I've copied the code from the monitor class, and that seems to restore expected functionality.

Fix creation from rack template

---

inc/item_enclosure.class.php

Use translated values for display only, fixes #4283

---

inc/entity.class.php

Fix getscript call loading entities selector

---

inc/ticket.class.php

Solutions can be approved without UPDATE right; fixes #4282

---

inc/pdu_plug.class.php

Add missing id; fixes #4281

---

inc/central.class.php
inc/purgelogs.class.php

avoid checking mysql tables, it may cause insane table locks

---

inc/dbmysql.class.php
status.php

remove check for crashed tables also in status.php

---

CHANGELOG.md
inc/dbmysql.class.php

Drop deprecated method

---

inc/itilsolution.class.php

Do not display link in add popup; closes #4296

---

ajax/mailcollector.php
inc/mailcollector.class.php
inc/toolbox.class.php

i dit it very fastly, but i think it's a small feature/code

add folders list for mailcollector

---

inc/ticket.class.php

Fix potential issue on displayed user with other items in timeline

---

inc/config.class.php

Drop extra closing tab; replace hardcoded select with HTML method

---

inc/document.class.php

Fix wrongtable

---

front/contract_item.form.php

fix(CS) remove whitespaces on contract_item form

---

inc/cartridge.class.php

MA cartridge - see #4324

---

inc/auth.class.php
inc/authldap.class.php
inc/commondbtm.class.php
inc/toolbox.class.php

Fix calls of debug instead of error

---

inc/budget.class.php
inc/contract_item.class.php
inc/document.class.php
inc/document_item.class.php
inc/infocom.class.php
inc/supplier.class.php
inc/transfer.class.php

Part of https://github.com/glpi-project/glpi/pull/4326; more easy to review

Use iterator 1

---

inc/dbmysql.class.php
inc/projectcost.class.php
inc/projecttask.class.php
inc/projecttask_ticket.class.php
inc/projecttaskteam.class.php
inc/projectteam.class.php
inc/user.class.php
inc/useremail.class.php
tests/DbTestCase.php
tests/functionnal/User.php

Some simple iterator replacements

---

inc/commondbtm.class.php
inc/user.class.php
tests/LDAP/AuthLdap.php

Add a LDAP test with a huge dn

---

inc/document.class.php
inc/document_item.class.php
tests/functionnal/Document.php

Test Document

---

inc/dbmysqliterator.class.php
tests/units/DBmysqlIterator.php

Add ON alias for FKEY; closes #4348
Add RIGHT JOIN
Add support for COUNT, SUM, AVG, MIN and MAX in fields list; closes #4350
| Fixed tickets | #4348 #4350

Improve iterator

---

inc/commonitiltask.class.php
tests/functionnal/TicketTask.php

entity restrict task list on central, fix #4358

---

inc/config.class.php

Fix write logs checks; closes #4286

---

inc/auth.class.php
install/update_93_94.php

following feature request at : https://glpi.userecho.com/communities/1/topics/851-cas-3-support-and-automatic-e-mail-extraction
No new tests created as it would require a CAS server

Adding CAS version selection and automatic e-mail extraction if possible

---

inc/dbmysqliterator.class.php
tests/units/DBmysqlIterator.php

Add possibility to do same aggregation (COUNT, SUM), multiple times

---

CHANGELOG.md
inc/commonitilvalidation.class.php
inc/html.class.php

Deprecate Html::scriptStart() and Html::scriptEnd() usage

---

inc/search.class.php

Do not used list_limit when displaying map; closes #4374

---

inc/lineoperator.class.php

Check for mcc/mnc uniqueness and display error message; closes #4383

---

CHANGELOG.md
inc/html.class.php

Drop deprecated methods

---

inc/user.class.php

Fix table name

---

inc/commonitilobject.class.php
inc/itilsolution.class.php

Add ability to search on solutions statuses

---

inc/user.class.php

Fix user fetching from email address on mail collector; fixes #4414

---

CHANGELOG.md
inc/commondbtm.class.php

Mark unused constants as deprecated

---

inc/commonitilobject.class.php
inc/ticket.class.php

| Fixed tickets | https://github.com/glpi-project/glpi/issues/4414

Fix collector reject solution

---

CHANGELOG.md
inc/commondbtm.class.php

Drop deprecated constants

---

front/link.send.php

I did not try to see if it triggers a bug, but this code is definitly dead and could generate errors.

Remove query of undefined variable

---

inc/define.php

Use of new secure URL for telemetry.

Use new URI of telemetry (and use HTTPS)

---

inc/alert.class.php
inc/api.class.php
inc/apirest.class.php
inc/auth.class.php
inc/authldap.class.php
inc/autoload.function.php
inc/blacklist.class.php
inc/calendar.class.php
inc/cartridge.class.php
inc/cartridgeitem.class.php
inc/central.class.php
inc/certificate.class.php
inc/certificate_item.class.php
inc/change.class.php
inc/commondbchild.class.php

There is a lot that are still missing. Can be done in this PR or another.

[WIP] Add initialization for array and fix IDE 'Variable '$foo' is undefined warnings

---

tests/GLPITestCase.php
tests/bootstrap.php

Clean logs files only once at bootstrap; to prevent issues when mcn > 1

---

inc/commonitilvalidation.class.php

Validation request status notifications were computed but not displayed.

Fix visibility of validation request notification status

---

install/mysql/glpi-empty.sql

Wrong value in empty SQL

---

inc/commonitilobject.class.php

Factorize CommonITILObkect::countActiveObjects*

---

inc/search.class.php

don't show tasks from project template in 'my tasks' view

---

inc/commondbtm.class.php
inc/commonglpi.class.php

I tried to rewite PHPDoc to be clean and complete.
I had a lot of remarks on possible improvements, so I put them on TODOs to discuss about it.

Rewrite PHPDoc for CommonDBTM properties

---

inc/commondbconnexity.class.php
inc/commondbrelation.class.php
inc/commondbtm.class.php
inc/commondropdown.class.php
inc/commonglpi.class.php
inc/commonitilobject.class.php
inc/commonitiltask.class.php
inc/commonitilvalidation.class.php
inc/commontreedropdown.class.php
inc/computer_item.class.php
inc/config.class.php
inc/consumableitem.class.php
inc/contract.class.php

Following https://github.com/glpi-project/glpi/pull/4436

Add array init and fix 'Variable '$foo' is undefined IDE warnings

---

inc/commonitiltask.class.php

fix display of assets in planning items

---

inc/computer_item.class.php

Fix Computer_Item php error

---

inc/devicefirmware.class.php

Fix DeviceFirmware Import #4438

---

CHANGELOG.md

Fix missing entry in changelog and rename 9.3 to 9.3.0

---

CHANGELOG.md
inc/config.class.php
inc/plugin.class.php

Drop deprecated methods and reorder changelog

---

inc/commondbtm.class.php

Force attachement of inline images when not using rich text; fixes #4396

---

inc/dbmysqliterator.class.php
tests/functionnal/ComputerVirtualMachine.php
tests/functionnal/DbUtils.php
tests/units/DBmysqlIterator.php

| Fixed tickets | #4474, #4468

FIx virtual machines and null in iterator

---

inc/computer_softwareversion.class.php

Fix wrong queries; closes #4475

---

inc/transfer.class.php

PR #4471 was not good. Checked deeper and found this. For review, check the method Transfer::createSearchConditionUsingArray()

Fix transfer again

---

inc/dbmysqliterator.class.php
tests/units/DBmysqlIterator.php

closes #4443
| Fixed tickets | #4443

Add support for extra condition in foreign key

---

inc/knowbaseitem.class.php
inc/knowbaseitem_comment.class.php
inc/knowbaseitem_revision.class.php
install/mysql/glpi-empty.sql
tests/functionnal/KnowbaseItem_Comment.php
tests/functionnal/KnowbaseItem_Revision.php

self-service users should not be able to display revisions/comments tabs in faq

---

inc/project.class.php
inc/search.class.php

Fix color cell covering for project state; fixes #4380

---

inc/commonitilactor.class.php
inc/commonitilobject.class.php

Allow anonymous assignation of ITIl objects; closes #4447

---

inc/commondbvisible.class.php

Small issue found when testing visibility in kb
Before:
After:

KB: visibility concatenate and append the same string

---

inc/document.class.php
inc/knowbaseitem.class.php
tests/functionnal/Document.php

Fix document rights check; fixes #4236

---

inc/search.class.php

clean unreachable code

---

inc/group.class.php
inc/infocom.class.php

Fix deprecated call to countElementsInTable using string as condition

---

front/backup.php
inc/dbmysql.class.php
install/update_06_065.php
install/update_content.php

Fix table name reading from $DB->listTables() result

---

scripts/cliupdate.php

Fix updated version on forced 'cli update'

---

inc/toolbox.class.php
tests/functionnal/Ticket.php

| Fixed tickets | follow #3960; fix #1264

replace also &#39 char

---

inc/itilsolution.class.php
tests/functionnal/ITILSolution.php

prevent multiple solution to be posted on the same item

---

inc/ruleimportentity.class.php

| Fixed tickets | #4484 
Update rules for "assigning an item to an entity" adding actions "Child entities" & "groups_id_tech"

Update rules for OCS adding actions "Child entities" & "groups_id_tech"

---

inc/migration.class.php

Fix deprecated function

---

inc/config.class.php
index.php
install/mysql/glpi-empty.sql
install/update_930_931.php

| Fixed tickets | #4406, #4417

display/hide (new config variable) source on login page; fix 4406

---

inc/search.class.php

Variable may not be set; fixes #4546

---

inc/ticket.class.php

Reset user; fixes #4557

---

inc/problem_ticket.class.php

Fix undefined index; closes #4573

---

inc/commonitilobject.class.php

Get correct field; fix #4572

---

inc/transfer.class.php

Wrong iterator usage; fixes #4578

---

inc/auth.class.php
inc/toolbox.class.php

Do not use verbatim HTTP_X_FORWARDED_FOR header

---

inc/itilsolution.class.php

Switch to commondbchild; fix logs

---

inc/item_disk.class.php

Fix disk clone on computer clone

---

inc/define.php
tests/functionnal/Item_Rack.php

add data center itemtypes in fieldunicity

---

inc/dropdown.class.php

distinct kb items in dropdowns

---

inc/api.class.php

| Fixed tickets | #4580 
See: https://github.com/glpi-project/glpi/blob/9.3.0/inc/commondbtm.class.php#L1098-L1101

force api to have commonDBTM messages send after redirect

---

inc/projecttask_ticket.class.php

| Fixed tickets | #4596 
1. Do not displayed project with finished state.
2. Fix filter on finished state (id was hardcoded).
3. Do not display tasks from template or finished projects.

Fix project and project task visibility in ticket; fixes #4596

---

CHANGELOG.md
inc/autoload.function.php
tests/units/Autoload.php

Drop class alias Event

---

inc/user.class.php

An eeror was made on user items fetching when code was refactored to use iterator.

Fix fetching of user's items

---

front/projecttask.form.php

I do not even know how to access project task modal (maybe it is dead code), but I think it cannot be working without this fix.

Fix project task in modal context

---

ajax/comments.php
ajax/dropdownConnectNetworkPort.php
ajax/dropdownMassiveActionAddValidator.php
ajax/dropdownProjectTaskTicket.php
ajax/dropdownSoftwareLicense.php
ajax/dropdownValidator.php
ajax/getFileTag.php
ajax/searchmetarow.php
ajax/searchrow.php
ajax/ticketassigninformation.php
ajax/updatecurrenttab.php

1. Replace usage of uninitialized arrays
2. Remove unused variables

Clean ajax files

---

inc/user.class.php

1. Replace usage of uninitialized arrays
2. Fix IDE 'Variable '$foo' is undefined warnings
3. Remove unused variables
4. Fix type error due to bad format of docblocks
5. Remove useless docblock override
6. Enhance doc and add type hinting on arrays

Cleanup user class

---

inc/lock.class.php

| Fixed tickets | #4585 
1. `MassiveAction::itemDone()` was called using wrong `$itemtype`.
2. Operation was considered as a failure if no items had to be unlocked.
3. Error messages were not generated from a loaded object, so were not containing the link to the object concerned by the error.

Fix massive unlock action; fixes #4585

---

front/commonitilcost.form.php
front/commonitiltask.form.php
front/commonitilvalidation.form.php
front/document.form.php
front/dropdown.common.form.php
front/dropdown.common.php
front/item_device.common.form.php
front/lock.form.php
front/report.contract.list.php
front/report.infocom.conso.php
front/report.infocom.php
front/report.year.list.php
front/reservation.form.php
front/rule.common.form.php
front/rule.common.php
front/rule.test.php
front/rulesengine.test.php
front/savedsearch_alert.form.php
front/stat.global.php
front/tracking.injector.php
front/user.form.php

1. Remove unused vars
2. Add comments related to vars declared prior to an inclusion
3. Fix type hinting errors due to bad docblocks

Clean front files

---

inc/itilsolution.class.php
inc/ticketfollowup.class.php

Fixes truncation of links in ticket followups and solutions displayed on old "followups" tab.
Same fix was already applied to timeline https://github.com/glpi-project/glpi/commit/1fbe428d4c367f655146f0efcdc57b9c1ce3f152
Internal support Ref: 14892

Prevent truncation of links in followups and solutions

---

inc/api.class.php

api: detect parent in PUT query (avoid warnings and provide logs)

---

inc/relation.constant.php

Fix typo in peripheralmodel relation; fixes #4627

---

inc/ticket.class.php

Redirect to survey after ticket solution approval

---

inc/displaypreference.class.php

Replace raw SQL with dbiterator

---

inc/ajax.class.php
inc/api.class.php
inc/apirest.class.php
inc/apixmlrpc.class.php
inc/auth.class.php
inc/authldap.class.php
inc/authmail.class.php
inc/budget.class.php
inc/calendar.class.php
inc/calendar_holiday.class.php
inc/calendarsegment.class.php
inc/cartridgeitem.class.php
inc/cartridgeitem_printermodel.class.php
inc/central.class.php
inc/certificate.class.php
inc/certificate_item.class.php
inc/change.class.php
inc/change_item.class.php
inc/change_problem.class.php
inc/change_project.class.php
inc/change_ticket.class.php
inc/changetask.class.php
inc/commondbchild.class.php
inc/commondbconnexity.class.php
inc/commondbrelation.class.php
inc/commondbtm.class.php
inc/computer_item.class.php
inc/transfer.class.php

1. Remove unused vars
2. Remove errored overrided docblock to use parent doc
3. Add/fix type hinting in docblock to prevent errors on IDE
4. Add some type hinting on methods

Clean some classes code

---

inc/search.class.php

| Fixed tickets | https://forum.glpi-project.org/viewtopic.php?id=164598

show map without displaypref rights

---

inc/cartridge.class.php

1. Remove unused vars
2. Remove useless count query in showForCartridgeItem() function

Clean cartridge class

---

install/update_91_92.php

Document exact query required to add missing index on id_search_option

---

inc/cartridge.class.php

Replace remaining raw SQL in Cartidge class

---

front/pdu.form.php

Cannot create PDU template; closes #4647

---

inc/define.php
inc/item_enclosure.class.php
inc/item_rack.class.php
inc/update.class.php
install/update_931_932.php
scripts/cliupdate.php

Fix missing checks when adding items on DC elements; fixes #4648

---

inc/commondcmodeldropdown.class.php

add search options to CommonDCModelDropdown; fix #4654

---

front/enclosure.form.php
inc/enclosure.class.php

Fix creation of enclosure templates and enclosures from templates

---

.circleci/config.yml
inc/config.class.php
inc/document.class.php
inc/itilsolution.class.php
inc/notificationtemplate.class.php
inc/planning.class.php
inc/ruleimportentity.class.php
install/update_931_932.php
tests/functionnal/Document.php

Make CS fails block CI; fix CS

---

inc/api.class.php

API: add ITILSolution hateoas to itilobject

---

css/styles.css

fix(css): manage bottom in vsplit layout

---

.circleci/config.yml
composer.json

Replace composer calls with raw commands to prevent timeouts
Ensure memory limit is passed to atoum sub processes

Replace composer calls with raw commands to prevent timeouts

---

inc/user.class.php

| Fixed tickets | #4682 
Bug fix for Issue #4682 to 9.3/bugfix branch.

Bug fix for group_iterator db request for used/managed items

---

inc/user.class.php

| Fixed tickets | #4685 
Bug fix for Issue #4685 to 9.3/bugfix branch.

Bug fix for multiple groups for used/managed items

---

inc/ticket.class.php

missing tabs for empty ticket 

---

ajax/selectUnaffectedOrNewItem_Device.php
inc/calendar_holiday.class.php
inc/calendarsegment.class.php
inc/cartridgeitem.class.php
inc/certificate.class.php
inc/change_project.class.php
inc/commondbtm.class.php
inc/commondevice.class.php
inc/commonitilcost.class.php
inc/commonitilobject.class.php
inc/commontreedropdown.class.php
inc/computer.class.php
inc/computer_item.class.php
inc/computer_softwareversion.class.php
inc/computerantivirus.class.php
inc/consumableitem.class.php
inc/contract.class.php
inc/contract_item.class.php

Replace RAW SQL by new querying syntax

---

front/dropdown.php

Error PHP in front/dropdown.php fix #4698

---

inc/ticket.class.php

Fix typo in Ticket class

---

inc/dbmysqliterator.class.php
tests/units/DBmysqlIterator.php

Existing was ORDER and GROUPBY...

Add ORDERBY and GROUP capabilities

---

apirest.md

Fix doc; closes #3334

---

CHANGELOG.md
ajax/subvisibility.php
front/ipnetwork.form.php
front/migrationcleaner.php
inc/ipnetwork.class.php
inc/profile_user.class.php
inc/search.class.php
inc/session.class.php
inc/user.class.php

Fix PHPDoc, rename one method

---

apirest.php
apixmlrpc.php
inc/autoload.function.php
inc/based_config.php
inc/includes.php
install/install.php
install/update.php
install/update_content.php
scripts/checkdb.php
scripts/cliinstall.php
scripts/cliupdate.php

Load 3rd party libs earlier

---

inc/commonitilobject.class.php

| Fixed tickets | #4724 
Bug fix for Issue #4724 to 9.3/bugfix branch.

Bug fix for Using solution in Change log ERROR

---

inc/item_rack.class.php

Handle item rakc name; closes #4704

---

inc/reservation.class.php

Display user in reservation item; closes #4671

---

inc/levelagreement.class.php

Business rules for ticket with SLA criteria fix #4680

---

inc/rule.class.php

Allow "Major" selection in dropdown priority criteria in search option

Add major option in priority dropdown criteria

---

inc/html.class.php

This PR add  "minutes" (1 to 15) option to time search options (with hour, days, weeks etc)

add minutes option to time search option

---

CHANGELOG.md
inc/olalevel_ticket.class.php
inc/rule.class.php
inc/ruleimportcomputer.class.php
inc/ruleimportentity.class.php
inc/rulemailcollector.class.php
inc/ruleright.class.php
inc/ruleticket.class.php
inc/slalevel_ticket.class.php

Add the input parameters given to the rules to the action called after

feat(rule): add input to execute action

---

inc/knowbaseitem.class.php

fix pager url in public faq

---

inc/dbmysql.class.php
tests/functionnal/CommonDBTM.php

| Tests pass?   | not yet
This PR add a new method in dbmysql class, this method first try to perform an update on the object with specified parameters, if 0 row is modified by this update, then perform an insertOrDie on the object.
Need TU

Adding new method update or insert in dbmysql class

---

inc/computer_softwareversion.class.php

Match the count of the tab.
internal ref: 15015

display softwares in computer only for the current entity

---

inc/datacenter.class.php
inc/html.class.php
inc/project.class.php

fix breadcrumb sub item and force menu regeneration in debug mode

---

inc/enclosure.class.php
inc/item_enclosure.class.php

in split layout, adding an item to enclosure failed to get enclosure id

---

front/change.form.php
front/problem.form.php

When setting "Save and add to the knowledge base" to "yes" for Changes and Problems, KB item form is not displayed.
Fix is compatible with changes made in #4540 .

Fix display of KB creation from Change or Problem solution

---

inc/item_ticket.class.php

add 'my devices' label on items tab of tab

---

inc/enclosure.class.php
install/mysql/glpi-empty.sql
install/update_931_932.php

New feature?  | no
Internal ref 15093
Follow #4752

limit visibility of states for enclosures

---

scripts/migrations/racks_plugin.php

| Fixed tickets | None
Just a quick typo fix

Yet another typo

---

CHANGELOG.md
inc/commonitiltask.class.php
inc/itilsolution.class.php
inc/ticketfollowup.class.php

Deprecate methods already dropped in #4758 .

Deprecate ITIL methods that would be dropped in favor of timeline usage

---

inc/html.class.php

Problem with simplified interface help link fix #4776

---

.travis.yml

Add PHP 7.3 config

---

CHANGELOG.md
inc/autoload.function.php
inc/config.class.php
inc/crontask.class.php
inc/includes.php
inc/plugin.class.php
inc/search.class.php
inc/session.class.php

Drop direct usage of SESSION['glpi_plugins']

---

front/config.form.php
inc/commontreedropdown.class.php
inc/config.class.php
inc/dbutils.class.php
inc/entity.class.php
inc/session.class.php
inc/toolbox.class.php
tests/GLPITestCase.php

Use PSR-16 instead of Zend specific

---

inc/html.class.php

Display cache entries in debug panel

---

inc/define.php
inc/pdu.class.php
inc/state.class.php
install/mysql/glpi-empty.sql
install/update_931_932.php

| Fixed tickets | follow #4756
internal ref: 15093
In previous pr (#4756), i missed some relation arrays, fixed in this new one

limit visibility os states in pdu (+fix visibility in enclosure

---

inc/includes.php

fix loading on plugins

---

inc/project.class.php

| Fixed tickets | #2657 
Add total cost for project in search engine

Add total cost for project in search engine

---

CHANGELOG.md

Add changelog entry for JS function renaming

---

inc/search.class.php

| New feature?  | es/no
| Fixed tickets | #4809 

fix comments of a reservation - see #4809

---

inc/search.class.php

Add progress bar type in search

---

inc/knowbaseitem.class.php

review icons in kb list, faq should display only if published in multientities mode

---

inc/config.class.php
inc/preference.class.php
inc/profile.class.php
inc/user.class.php
install/mysql/glpi-empty.sql
install/update_93_94.php

closes #1062
| Fixed tickets | #1062
Allows locking of user personalizations to the defaults set by GLPI administrator.

Allow locking of personalizations

---

inc/commonitilactor.class.php
inc/mailcollector.class.php
inc/notimportedemail.class.php
inc/profile.class.php
inc/ticket.class.php
tests/functionnal/Profile.php
tests/functionnal/Ticket.php

| Fixed tickets | #2722
Internal ref: #14976

Check ticket/followup rights on mail collector

---

inc/itilsolution.class.php
tests/functionnal/ITILSolution.php

| Fixed tickets | 15156 (internal)

Adding a solution for problem or changes should not close them

---

inc/entity_reminder.class.php
inc/group_reminder.class.php
inc/profile_reminder.class.php
inc/reminder_user.class.php

Also swicth to iterator for all other similar methods
of Reminder related objects

Fix Entity_Reminder::getEntities

---

inc/dropdown.class.php
tests/functionnal/Dropdown.php

Rework limits for commontreedrodown with entities; fixes #4828

---

inc/itilsolution.class.php
tests/functionnal/ITILSolution.php

https://github.com/glpi-project/glpi/pull/4830 for master branch

Fix problemsolutionstatus master

---

inc/config.class.php

Cache fallback was not sending back PSR16 compliant class

---

inc/dbutils.class.php
tests/functionnal/DbUtils.php

PSR16 cache key must be 64 chars long maximum; fixes #4838

---

inc/deviceprocessor.class.php

add new searchoption for count of device processors

---

inc/api.class.php

Fix bug in api class and make function parseDropdowns realy recusive

---

inc/reservation.class.php

[9.1]fix reservation tab of an item - fixed #4870

---

inc/reservation.class.php

fix reservation tab of an item - fixed #4870

---

inc/ruleticket.class.php
install/mysql/glpi-empty.sql
install/update_93_94.php

| Fixed tickets | #4866, #4867

ticket rules: itilcategory criterion now permits to target completename

---

inc/config.class.php
tests/functionnal/Config.php

* split getLibraries out of showLibrariesInformation to be able to test it
* use composer name for all
* add test to ensure list match composer.json

refresh libraries list and add test to ensure none is missing

---

inc/commondbtm.class.php
inc/commonitilobject.class.php
inc/commontreedropdown.class.php
inc/computer.class.php
inc/computer_item.class.php
inc/computer_softwarelicense.class.php
inc/computer_softwareversion.class.php
inc/computerantivirus.class.php
inc/computervirtualmachine.class.php
inc/config.class.php
inc/consumable.class.php
inc/consumableitem.class.php
inc/contact.class.php
inc/contact_supplier.class.php
inc/contract.class.php
inc/contract_item.class.php
inc/contract_supplier.class.php
inc/contractcost.class.php
inc/crontask.class.php
inc/datacenter.class.php
inc/db.function.php
inc/dbconnection.class.php
inc/dbmysql.class.php
inc/dbutils.class.php

- Remove useless docblocks when defined in parent.
- Remove unused vars.
- Fix some docblock and types.

Clean some code.

---

CHANGELOG.md
inc/api.class.php
inc/budget.class.php
inc/notification.class.php
inc/notificationtarget.class.php
inc/notificationtargetcommonitilobject.class.php
inc/rulecollection.class.php
inc/session.class.php

A bunch or iterator replacements

Convert to iterator

---

inc/api.class.php

See https://github.com/glpi-project/glpi/pull/4878#discussion_r232705878

Fix LEFT JOIN condition; see #4878

---

inc/commonitilobject.class.php
inc/db.function.php
inc/dbutils.class.php
inc/stat.class.php
tests/functionnal/DbUtils.php

Deprecate get date request

---

inc/config.class.php
inc/mailcollector.class.php

| Fixed tickets | #4559 
Before:
After:

Fix windows encodings in mail collector; fixes #4559

---

inc/mailcollector.class.php

Fix stripping of initial mail in collector; fixes #4864

---

inc/pdu_plug.class.php

Do not add less than 1 plug in PDU; closes #4848

---

inc/commondbrelation.class.php

Auto detect recursivity; closes #4795

---

inc/ruleaction.class.php

Fix typo; closes #4755

---

inc/config.class.php

cleanup anoying debug info

---

ajax/map.php
inc/search.class.php

Fix search

---

inc/itilfollowup.class.php
tests/functionnal/ITILFollowup.php

Should be using the field value instead of the field name.

Fix ITILFollowup delete

---

inc/api.class.php

Fix API SQL typo

---

README.md

| Fixed tickets | #4304
Update the readme to match 9.3 min SQL version
Regards,
Anael

Min SQL version update

---

inc/commonitilvalidation.class.php
inc/dropdown.class.php
inc/group_user.class.php
inc/search.class.php
inc/user.class.php
tests/functionnal/Search.php

Rebased onto #4888 (ignore 1st commit until it reaches master).

Some more iterator conversions

---

inc/dropdowntranslation.class.php

fix display fields for translation - see #4912

---

inc/dbmysqliterator.class.php
inc/document_item.class.php
inc/queryunion.class.php
tests/units/DBmysqlIterator.php

| Fixed tickets | #4914 
Right now, I've implemented the capability and the tests; that's what I want to validate right now. `DocumentItem` changes are WIP and can be ignored right now :)

Add UNION to iterator; closes #4914

---

inc/search.class.php

Minor fixes/typos for new 'not contains' search option.

Fix not contains typos

---

inc/stat.class.php

One of the queries appears to have been converted to the iterator format, but the database call wasn't updated.

Fix statistics query

---

inc/dbutils.class.php
tests/functionnal/DbUtils.php

Fix auto name

---

inc/transfer.class.php

Transfer iterator

---

inc/change.class.php
inc/change_ticket.class.php
inc/commonitilobject.class.php
inc/item_ticket.class.php
inc/notificationtargetticket.class.php
inc/olalevel_ticket.class.php
inc/problem.class.php
inc/problem_ticket.class.php
inc/projecttask_ticket.class.php
inc/slalevel_ticket.class.php
inc/supplier_ticket.class.php
inc/ticket.class.php
inc/ticket_ticket.class.php
inc/tickettemplatepredefinedfield.class.php

Use iterator 4

---

inc/notificationtarget.class.php

Fix issues on notification groups fetching

---

inc/search.class.php

typo when retrieving searchoption

---

inc/search.class.php

show missing trash icon

---

inc/knowbaseitem_comment.class.php
tests/functionnal/KnowbaseItem_Comment.php

| Fixed tickets | internal ref 14689

missing icon for edit a kb's comment

---

inc/html.class.php

Fix select2 matcher; closes #4952

---

inc/mailcollector.class.php

| Fixed tickets | #4889 
Replaces #4890 .

Disable checks on collector if anonymous ticket/fup enabled; fixes #4889

---

inc/rulecollection.class.php

Fix SLA/OLA values in ticket rules export; fixes #4865

---

CHANGELOG.md

Add 9.3.3 changelog

---

.circleci/config.yml
inc/dbmysql.class.php
tests/functionnal/CommonDBTM.php

Insert or update

---

inc/queuednotification.class.php

send queue notification also when no mailing enabled

---

inc/infocom.class.php
inc/ticket_ticket.class.php
tests/LDAP/AuthLdap.php
tests/bootstrap.php
tests/functionnal/Computer.php
tests/functionnal/KnowbaseItem.php
tests/functionnal/KnowbaseItem_Revision.php
tests/functionnal/Log.php

Test dates

---

CHANGELOG.md
inc/commondbtm.class.php
tests/functionnal/CommonDBTM.php

Allow specify of creation and modification dates during add;closes #1731

---

inc/authldap.class.php
inc/ruleticket.class.php
inc/ticket.class.php
inc/user.class.php
install/mysql/glpi-empty.sql
install/update_93_94.php
tests/functionnal/AuthLdap.php
tests/functionnal/Rule.php

Feature [9.4] - Adding a responsible for a user see #4997

---

inc/knowbaseitem.class.php
inc/knowbaseitemtranslation.class.php

PO files has been updated using:
$ sed -e 's/ %id"/ %s"/g' -i locales/*.po
| Fixed tickets | #4990 
String must be extracted and sent to transifex once merged.

Fix string; closes #4990

---

inc/item_ticket.class.php

not similar as 9.1
| Fixed tickets | #4900, #4907

fix link in item ticket - #4900 and PR #4907

---

CHANGELOG.md
inc/authldap.class.php
inc/console/ldap/synchronizeuserscommand.class.php
inc/user.class.php
scripts/ldap_mass_sync.php

Move LDAP sync command to console

---

inc/html.class.php

Reload SCSS compilation if one of the source files has changed

---

inc/calendar.class.php
inc/ticket.class.php
tests/functionnal/Calendar.php
tests/functionnal/Ticket.php

autoclose cron now based on calendar open days

---

inc/ticketsatisfaction.class.php

add rightname to TicketSatisfaction to permits usage with api; fix #5014

---

front/knowbaseitemtranslation.form.php

permits to purge kb translations, fix #5025

---

inc/ajax.class.php

Fix JS when there is no anchor

---

inc/levelagreement.class.php
inc/ticket.class.php

| Fixed tickets | #4150 
Wip as i need to check SLA part

compute take into account stat on date creation

---

install/update_91_92.php
install/update_921_922.php
install/update_922_923.php
install/update_92_921.php
install/update_92_93.php
install/update_93_94.php

Some queries can't be re-factorized yet (not supported) : 
1) REPLACE or INSERT that get their values from another query.
```sql
REPLACE INTO `glpi_itilsolutions` (itemtype, items_id, date_creation, users_id, user_name, solutiontypes_id, content, status, date_approval)
SELECT
'Problem' AS itemtype,
problem.`id` AS items_id,
problem.`solvedate` AS date_creation,
IF(log.user_name REGEXP '[(][0-9]+[)]$', SUBSTRING_INDEX(SUBSTRING_INDEX(log.`user_name`, '(', -1), ')', 1), 0) AS users_id,
IF(log.user_name REGEXP '[(][0-9]+[)]$', NULL, log.`user_name`) AS user_name,
problem.`solutiontypes_id` AS solutiontypes_id,
problem.`solution` AS content,
(CASE
WHEN problem.status = 6 THEN 3   -- if CLOSED, ACCEPTED
WHEN problem.status = 5 THEN 2   -- if SOLVED, WAITING
WHEN problem.status = 8 THEN 2   -- …
```

Migration queries refactorization - update_93_94 to update_91_92

---

inc/console/application.class.php
inc/plugin.class.php

Prevent var override on plugin check state and force state check on console

---

inc/entity.class.php

fix count typo

---

inc/cartridgeitem.class.php
inc/certificate.class.php
inc/computer.class.php
inc/consumableitem.class.php
inc/enclosure.class.php
inc/line.class.php
inc/monitor.class.php
inc/networkequipment.class.php
inc/pdu.class.php
inc/peripheral.class.php
inc/phone.class.php
inc/printer.class.php
inc/project.class.php
inc/rack.class.php
inc/software.class.php
inc/softwarelicense.class.php
inc/softwareversion.class.php

Fix dropdown conditions

---

inc/item_ticket.class.php

| Fixed tickets | #5055 #5056 #5057

Fix SQL in item_ticket fixes #5055 fixes #5056 fixes #5057

---

inc/calendar_holiday.class.php
inc/change_ticket.class.php
inc/commonitilcost.class.php
inc/commonitilobject.class.php
inc/group_user.class.php
inc/location.class.php
inc/notificationtargetticket.class.php
inc/problem_ticket.class.php
inc/reservation.class.php
inc/user.class.php

Fix some SQL

---

inc/document_item.class.php

Fix undefined index in document_item for users fixes #5054

---

scripts/ldap_mass_sync.php

Reword; closes #5047

---

inc/reminder.class.php

Fix, closes #5051

---

inc/update.class.php

Update from 9.3.3; closes #5062

---

inc/dropdown.class.php

Drop depreciation

---

css/styles.scss

fix min-width in kb css; fix #5082

---

inc/ticket.class.php
inc/ticketsatisfaction.class.php

Fix ticket satisfaction form link; fixes #5079

---

inc/crontask.class.php
inc/dbmysqliterator.class.php
inc/knowbaseitem_revision.class.php
inc/migration.class.php
inc/rule.class.php
inc/ruledictionnarysoftwarecollection.class.php
inc/rulerightcollection.class.php
inc/session.class.php
inc/telemetry.class.php
inc/tickettemplatehiddenfield.class.php
inc/tickettemplatemandatoryfield.class.php
tests/functionnal/KnowbaseItem_Revision.php
tests/units/DBmysqlIterator.php

Use iterator 7

---

inc/transfer.class.php

Prevent empty IN; clsoes #5102

---

inc/console/ldap/synchronizeuserscommand.class.php

If command is called without parameters, it just runs sync with all active LDAP servers without any interaction. This is rude !

Add confirmation on LDAP sync command

---

inc/html.class.php
js/common.js

Handle diacritical marks in select2 matcher; fixes #4974

---

inc/dbmysqliterator.class.php
tests/units/DBmysqlIterator.php

Rework join subquery

---

.circleci/config.yml

Add PHP 7.3 support

---

inc/transfer.class.php

Fix empty INs in Transfer

---

inc/search.class.php

Fix global search, closes #5112

---

CHANGELOG.md
inc/api.class.php
inc/change.class.php
inc/commonitilobject.class.php
inc/problem.class.php
inc/ticket.class.php

Move getCommonSelect and getCommonLeftJoin to iterator

---

CHANGELOG.md
inc/migration.class.php
install/update_0782_080.php
install/update_0803_083.php
install/update_0831_084.php
install/update_083_0831.php
install/update_084_085.php
install/update_91_92.php
install/update_93_94.php

See https://github.com/glpi-project/glpi/pull/5124#discussion_r242056619

Deprecated raw condition on Migration::addField

---

inc/console/database/updatecommand.class.php
inc/define.php
inc/update.class.php
install/update_94_100.php

Bump version and add update script

---

inc/calendar.class.php
tests/bootstrap.php
tests/functionnal/Calendar.php

Migrate calendar

---

css/styles.scss
inc/knowbaseitem.class.php

Re-add FAQ border in popular/recent lists

---

inc/change.class.php
inc/search.class.php

Copypasta of the problem ones (just changed the id 63 to 68)

add change_items searchoptions to changes

---

install/update_085_0853.php

Not sure of the impact, but existing code seems not correct.

Fix cron limit update in 0.85.3 migration

---

install/update_0801_0803.php
install/update_0803_083.php
install/update_080_0801.php
install/update_0831_0833.php
install/update_0831_084.php
install/update_083_0831.php
install/update_0841_0843.php
install/update_0843_0844.php
install/update_0845_0846.php
install/update_084_0841.php
install/update_084_085.php
install/update_0853_0855.php
install/update_0855_090.php
install/update_085_0853.php
install/update_0901_0905.php
install/update_0905_91.php
install/update_090_0901.php
install/update_911_913.php
install/update_91_911.php
install/update_91_92.php
install/update_921_922.php
install/update_922_923.php
install/update_92_921.php
install/update_92_93.php
install/update_930_931.php
install/update_931_932.php
install/update_93_94.php

1. I removed lot of dead code.
2. I use the `Migration::updateDisplayPrefs()` method instead of duplicated code.
3. I fixed a potential bug in `update_0831_084.php`.
I will resolve conflicts with #5099, depending on which one is merged first.

10.0/clean migrations

---

inc/reminder.class.php

Fix private reminder list in central; fixes #5142

---

inc/commonitiltask.class.php
inc/consumable.class.php
inc/contract.class.php
inc/contractcost.class.php
inc/crontask.class.php
inc/crontasklog.class.php
inc/infocom.class.php
inc/knowbaseitem.class.php
inc/levelagreementlevel.class.php
inc/link.class.php
inc/problem.class.php
inc/projecttask.class.php
inc/ticket.class.php
inc/toolbox.class.php

Use iterator 10

---

install/update_0841_0843.php
install/update_0843_0844.php
install/update_0845_0846.php
install/update_084_0841.php
install/update_084_085.php
install/update_085_0853.php

 Migration queries refactorization - update_085_0853 to update_0841_0843

---

install/update_085_0853.php

Fix typo in update_085_0853.php

---

inc/item_ticket.class.php

Fix WHERE and ORDER criteria in Item_Ticket fixes #5174

---

inc/define.php

Add Data Center items into Global Search

---

inc/softwarelicense.class.php

Fix license view for software

---

CHANGELOG.md
inc/dbmysql.class.php
inc/notimportedemail.class.php

Only one instance of truncate usage in core, but several in plugins.

Add DB truncate method

---

inc/ticket.class.php

Respect hidden document field in ticket template fixes #3664

---

inc/commonitiltask.class.php

| Fixed tickets | #5032 
Do not show HTML tags in search.

Fix search display of tasks fixes #5032

---

inc/knowbaseitem.class.php

| Fixed tickets | #5084 
Show correct counts to reflect what is actually visible to user if they only have FAQ access.

Fix KB browse category counts fixes #5084

---

inc/crontask.class.php

warn user maintenance mode is enabled when trying to execute crontasks

---

inc/ajax.class.php

prevent bad js vars in generated html; fix #5175

---

inc/computervirtualmachine.class.php

Prevent potential issues on multiple results (see uuid hack in the query)

---

inc/change.class.php

permits to sort change's items searchoption

---

inc/ticket.class.php

confirm string not translated

---

inc/user.class.php

| Fixed tickets | #5214 
User's should be able to edit their password from user form if they are able to update their password in their preferences.

Fix user form consistency

---

inc/reservation.class.php

Only notify for deleted reservations that haven't ended yet

---

inc/savedsearch.class.php

Fix link when count is not displayed on tabs

---

inc/reminder.class.php

bad sql in reminder list

---

inc/define.php
inc/state.class.php

Add missing state_types and state search options

---

inc/report.class.php

Fix default report SQL

---

install/update_068_0681.php

fix old style constructor

---

inc/config.class.php
inc/notificationmailingsetting.class.php
inc/softwarelicense.class.php
inc/user.class.php

Fix Tr-Td display

---

inc/document_item.class.php

Fix sub documents query; closes #5241

---

inc/dbutils.class.php

Fix entity restrict criteria in cron mode; fixes #5117

---

install/update_0801_0803.php
install/update_0803_083.php
install/update_080_0801.php
install/update_0831_0833.php
install/update_0831_084.php
install/update_083_0831.php
install/update_084_0841.php

Migration queries refactorization - 084 to 080

---

inc/commonitiltask.class.php

Fix Display Ticket Task

---

inc/devicepci.class.php

Fix devicepci search option

---

inc/dbmysql.class.php
inc/dbmysqliterator.class.php
inc/transfer.class.php
tests/database/DBmysql.php
tests/functionnal/Item_Devicesimcard.php

Add join support to DB delete and update

---

inc/toolbox.class.php

Cleanup Toolbox class

---

.circleci/config.yml

Change CI workflow:
- run security checker first,
- run CS second (so CS issues may will appears even when tests are failing (they run on 7.3 only),
- run install before update

Rework workflow

---

inc/search.class.php

fix progressbar for sl fields

---

.circleci/config.yml
.stylelintrc
css/jquery-glpi.css
css/jstree-glpi.css
css/print.css
css/style_install.css
css/styles.scss
css/tab-scroller-menu.css
package-lock.json
package.json

Use stylelint to lint CSS

---

inc/purgelogs.class.php

Fix purge of plugins logs

---

CONTRIBUTING.md

Add link to readthedoc for contributing

---

install/update_0831_084.php
install/update_0843_0844.php

Fix bad usage of LIKE keyword in migrations

---

inc/contact.class.php
inc/location.class.php

Fix translation contexts; closes #5291

---

inc/commonitilobject.class.php

Wrong approval user ID on solutions; fixes #5301

---

inc/software.class.php
inc/softwareversion.class.php
inc/stat.class.php
inc/state.class.php
inc/supplier.class.php
inc/xml.class.php

Iterator conversions

---

inc/html.class.php

Escape JS, fix #5321

---

inc/migration.class.php
inc/rule.class.php

Fix usage of reserved rank keywork in MySQL8; fixes #5327

---

inc/html.class.php

Some more escaping

---

css/styles.scss
inc/commonitilobject.class.php
inc/commonitiltask.class.php
inc/html.class.php
inc/itilfollowup.class.php

Clean timeline ui

---

.circleci/config.yml

Adaptation of #5335 and #5341 for 9.4/bugfixes branch.

Optimize circleci jobs duration

---

.circleci/config.yml

Add cache on npm install in circleci

---

inc/ticket.class.php

Allow overriding fields from promoted followup

---

inc/commondbconnexity.class.php

Fix item relation - see #4850

---

.circleci/config.yml

Use custom docker images already containing system deps

---

.circleci/config.yml

- do not test PHP intermediate version on PR
- add tests on tags
- add nightly tests on all PHP versions
- add nightly tests on 9.4/bugfixes branch

Update circleci tests scheduling

---

.circleci/config.yml

- add cache on composer cache
- add fallback cache on vendor dir

Enhance cache on circleci

---

.travis.yml

Removed line are either not runned or already runned in CircleCI.

Remove obsolete script in travis config

---

inc/computer_softwarelicense.class.php
inc/softwarelicense.class.php
install/mysql/glpi-empty.sql
install/update_94_100.php

Allow assigning of licenses over assigned quota

---

css/styles.scss
inc/commonitilobject.class.php

fix rendering of timeline (ticket recall and document item)

---

inc/migration.class.php

Manage UNIQUE keys separately; closes #5359

---

src/Glpi/Application/Middleware/RequireJs.php
src/Glpi/Application/Middleware/TemplatesGlobals.php
src/Glpi/ConfigParams.php
src/Glpi/Controller/AbstractController.php
src/Glpi/Kernel.php
src/resources/services.yaml

Rename ambiguous Glpi\Config class

---

inc/console/application.class.php

DB, Cache and Session were init in console. This is useless as it is now done in kernel.

Remove useless global inits already done in Kernel

---

inc/auth.class.php

Avoid redirect to cas authentification to use rest api

bug using rest api if auth Cas is configured

---

inc/change.class.php
inc/problem.class.php

Get entity from ticket/problem when creating a change/problem

---

inc/user.class.php

Fix password forget token check; fixes #5386

---

inc/config.php
inc/toolbox.class.php
src/Glpi/DatabaseFactory.php

Handle old database configuration file migration from cli

---

inc/search.class.php

Bad variable, fixes #5394

---

inc/update.class.php

| Fixed tickets | https://github.com/glpi-project/glpi/issues/5362#issuecomment-462788722

Fix update from dev version, see #5362

---

inc/define.php
inc/profile.class.php
inc/update.class.php
install/update_940_941.php

this itemtype was missing a search option for ID
Signed-off-by: Thierry Bugier <tbugier@teclib.com>
| Fixed tickets | #5245 
Replace #5271

add search option for profile

---

.circleci/config.yml

Fix path of composer and npm cache on circleci

---

composer.json
inc/config.class.php
inc/toolbox.class.php
tests/units/Toolbox.php

Fix cyrillic characters in slugify; closes #2946

---

src/Glpi/Application/Middleware/Authentication.php
src/Glpi/Application/Middleware/Reload.php
src/Glpi/Application/Middleware/RequireJs.php
src/Glpi/Controller/Asset.php
src/Glpi/Controller/Main.php

Config variable do not exists; redirect when not logged

---

inc/item_devices.class.php

| Fixed tickets | #5365 
fixes #5365

Fix form title for Item_Devices

---

install/update_92_93.php

Take care to migrate solutions wichc contains only a type; closes #5312

---

tests/bootstrap.php

| Bug fix?      | kind of
| Tests pass?   | hope so!

Trying to clean directories seems a bad idea.

---

CHANGELOG.md
inc/commonitilobject.class.php

add new display hook timeline_actions

---

inc/projectteam.class.php

fiw project team - see #5430

---

inc/commonitilobject.class.php
inc/ticket.class.php

| Fixed tickets | #5435 and #5115

Itilsolution

---

install/update_0905_91.php

I do not have an old enough DB to test.

Fix ticket template fields migration

---

inc/item_devices.class.php

Fix list of documents related to device items

---

css/styles.scss

Fix nested arrays rendering in debug bar

---

inc/ticket.class.php

Fix immediate ticket autoclose; fixes #5279

---

front/plugin.php

Put back plugin catalog button; fixes #5454

---

inc/networkportinstantiation.class.php

Fix network ports display; fixes #5460 #5461

---

inc/lock.class.php

Fix lock rights checking; fixes #5458

---

index.php
install/install.php

Fuzzy lib is used for search feature in select2 dropdown.

Fix missing fuzzy lib on install and login

---

inc/html.class.php
js/common.js

Fix chevrons display in select2 rendering

---

inc/commondbtm.class.php
inc/item_disk.class.php
inc/mailcollector.class.php
templates/elements/input.twig
templates/elements/mailserver_config.twig
templates/elements/password.twig

Add mailserver configuration template
Add clear checkbox for passwords

Migrate collector UI

---

templates/elements/password.twig

Existing field was named _blank_passwd

---

inc/console/database/updatecommand.class.php

Fix last migration replay in update command

---

inc/transfer.class.php

Fix name of function

---

inc/user.class.php

Fix user add form in group users tab; fixes #5274

---

inc/transfer.class.php

Fix cartridges transfer; fixes #5497

---

inc/search.class.php

surround generated sql from view criteria by parenthesis; fix #5493

---

inc/location.class.php

Fix query; closes #5504

---

inc/location.class.php

Remove location fields from massive update action; fixes #5292

---

.circleci/config.yml

Fix circleci composer cache path and add epoch to vendor cache

---

inc/define.php
inc/update.class.php
install/update_93_94.php
install/update_940_941.php

Fix migration

---

inc/html.class.php

Prevent form and iframe in tinymce contents

---

inc/auth.class.php

Strict check

---

inc/update.class.php

Handle 9.4.1

---

ajax/dropdownItilActors.php

Fix group filtering on ITIL form; fixes #5522

---

inc/search.class.php

| Fixed tickets | #5311 
Replace #5318

fix order of group_concat in search

---

.circleci/config.yml
inc/central.class.php
inc/config.class.php
inc/console/database/updatecommand.class.php
inc/toolbox.class.php
install/update.php
install/update_0803_083.php
install/update_0831_084.php
install/update_084_085.php
install/update_085_0853.php
install/update_0905_91.php
install/update_91_92.php
install/update_92_921.php

No longer allow tables using myisam.

All tables must use InnoDB

---

src/Glpi/Kernel.php

Fix logger error when fail to init DB

---

CHANGELOG.md
front/plugin.php
inc/console/application.class.php
inc/includes.php
inc/plugin.class.php
src/Glpi/Kernel.php

Force reloading of active plugin list on each request

---

css/styles.scss

fix table overflow in timeline

---

css/glpi.scss
templates/elements/form.twig

Add dates in footer

---

css/styles.scss

disable pointer events on solution background images

---

inc/search.class.php

Fix joins in AllAssets view; fixes #5554

---

inc/plugin.class.php

| Fixed tickets | https://github.com/pluginsGLPI/order/issues/111

Prevent failure on itemtype migration

---

js/common.js
templates/elements/button.twig
templates/elements/checkbox.twig
templates/elements/delete.twig
templates/elements/form.twig
templates/elements/input.twig
templates/elements/purge.twig
templates/elements/select.twig
templates/elements/textarea.twig

Add delete, purge and restore buttons

---

inc/user.class.php

check cookie validity on glpi side

---

inc/user.class.php

Password token date was not removed

---

inc/olalevel_ticket.class.php
inc/purgelogs.class.php
inc/savedsearch.class.php
inc/slalevel_ticket.class.php
inc/telemetry.class.php
inc/ticket.class.php
inc/ticketrecurrent.class.php

Cron methods should return -1, 0 or 1 (see https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/crontask.class.php#L289).
This will just fix logged result on some cases.

Fix cron return codes

---

js/common.js

https for tiles retrieve from osm.org and so more speed with benefits of the http/2

https more secure and with HTTP/2

---

install/install.php

Fix bad merge; closes #5583

---

inc/ticket.class.php

| Fixed tickets | #5574 
Merge of #5576 into master was not complete. Modifications on "validation.rejected" query where not kept.

Fix refused tickets list; fixes #5574

---

front/mailcollector.form.php
inc/commondbtm.class.php
inc/commonglpi.class.php
src/Glpi/Controller/Asset.php
templates/edit_page.twig
templates/elements/form.twig
templates/elements/input.twig
templates/elements/select.twig

Do not display any form if user cannot edit asset

---

inc/commonitilobject.class.php

Display ITIL contents in classic/splitted view; closes #5582

---

inc/commonitiltask.class.php

Fix private tasks visibility in ITIL list; fixes #5587

---

inc/commonitilobject.class.php

Fix ITIL image path

---

inc/define.php

Bump version and year

---

front/document.send.php
inc/mailcollector.class.php
inc/user.class.php

| Fixed tickets | #5604 
Includes #5609 and fixes also the update process of user picture.

Fix user image upload and display; fixes #5604

---

inc/commonitilobject.class.php

Fix timeline buttons right checks; fixes #5628

---

inc/commondbtm.class.php
inc/dcbreadcrumb.class.php
templates/elements/dcbreadcrumb.twig

Add datacenter position element

---

inc/item_devices.class.php

Fix item_device form title

---

inc/knowbase.class.php

Fix search in KB tree; fixes #5618

---

css/glpi.scss
css/glpi/bootstrap.scss
css/glpi/layout.scss
inc/computerantivirus.class.php
package-lock.json
package.json
templates/edit_page.twig
templates/elements/form.twig
templates/elements/select.twig
templates/glpi_page.twig
webpack.config.js

bootstrap4 theme for dropdowns

---

CHANGELOG.md
inc/commondbtm.class.php
inc/migration.class.php
inc/software.class.php
install/update_0723_078.php

| Bug fix?      | yes/no (performances)
| Fixed tickets | #5657

Remove usage of cache for tables/fkey computed values; fixes #5657

---

CHANGELOG.md
inc/commondbtm.class.php
inc/migration.class.php

Fix 9.4/bugfixes merge

---

inc/plugin.class.php

Fix plugin locale reload after locale update; fixes #5662

---

inc/config.php

| New feature?  | /no
| Fixed tickets | #5684 
No complete https://github.com/glpi-project/glpi/issues/2863 check all dbversion value

fix migration - fixed #5684

---

inc/commondbrelation.class.php

fix synchonization - fixed #5660

---

inc/commondbrelation.class.php

fix synchronization - fixed #5660

---

inc/config.class.php
inc/log.class.php
tests/functionnal/Config.php

Add history on config

---

.circleci/config.yml
composer.json
composer.lock
front/document.send.php
inc/auth.class.php
inc/config.class.php
inc/document.class.php
inc/html.class.php
inc/ticket.class.php
inc/user.class.php
js/common.js
tests/functionnal/Document.php
tests/notanimage.jpg

| Fixed tickets | #5468 #5519 #5520 #5580 #5577 #5562 #5599
Backport of latest security patches on 9.3 branch.

Backport fixes

---

inc/ticket.class.php

fix survey - fixed #5686

---

inc/ticket.class.php

Needed for Ministries
| Fixed tickets | #5686
Done for 9.4: https://github.com/glpi-project/glpi/pull/5687

[9.3] fix survey - fixed #5686

---

inc/ticket.class.php

Commit was missing from last PR.
Avoids survey creation during merge

Do not close merged ticket

---

inc/cache/simplecache.class.php

See https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2789#issuecomment-474736011.
```
019-03-20 08:56:03] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 659
*** PHP User Warning(512): Cache footprint file "/usr/share/glpi/files/_cache/glpi_cache_db_9.4.1.1e6c9e72f63e2ff2eb817327ea4df352e.json" contents was invalid, it has been cleaned.
Backtrace :
:
inc/cache/simplecache.class.php:247 trigger_error()
inc/cache/simplecache.class.php:267 Glpi\Cache\SimpleCache->checkFootprintFileIntegrity()
inc/cache/simplecache.class.php:178 …
```

Make sure that footprint file reading respect file locking

---

inc/supplier.class.php
install/mysql/glpi-empty.sql
install/update_94_95.php

Add active status on suppliers

---

inc/notificationevent.class.php
inc/notificationeventabstract.class.php

[9.3] fix double notification - fixed #5702

---

inc/notificationevent.class.php
inc/notificationeventabstract.class.php

fix double notification - fixed #5702

---

inc/auth.class.php
inc/user.class.php

Prevent timezone set to null in session

---

composer.json

Prevents twig depreciation messages to be displayed. Proposal has been submitted upstream (https://github.com/slimphp/Twig-View/pull/104), waiting for merge and new release.

Locally apply proposed patch

---

inc/ajax.class.php
inc/change.class.php
inc/commonitilobject.class.php
inc/dcroom.class.php
inc/problem.class.php
inc/rack.class.php
inc/ticket.class.php

Change default tab on ITIL objects, racks and dc rooms

---

install/update_93_94.php

Drop old embed search options; closes #5658

---

inc/document.class.php
install/update_940_941.php
install/update_941_942.php

Fix bad usage of \d in MySQL regexp; fixes #5457

---

inc/document.class.php

Fix document tests

---

inc/toolbox.class.php

Fix redirect

---

index.php

Fix redirect when user have to log in

---

inc/knowbaseitem.class.php

| Fixed tickets | #5682 
Error was:
```
glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 177
SQL: SELECT `glpi_knowbaseitems_items`.* FROM `glpi_knowbaseitems_items`, `glpi_knowbaseitems` LEFT JOIN `glpi_knowbaseitems_users` ON (`glpi_knowbaseitems_users`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) WHERE `glpi_knowbaseitems_items`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id` AND (`glpi_knowbaseitems_items`.`knowbaseitems_id` = '3' AND (`glpi_knowbaseitems`.`is_faq` = '1' AND `glpi_entities_knowbaseitems`.`entities_id` = '0' AND `glpi_entities_knowbaseitems`.`is_recursive` = '1')) …
```

Fix public FAQ documents links; fixes #5682

---

.circleci/config.yml

Add MariaDB 10.4 and MySQL envs on CI

---

inc/plugin.class.php

Part of #5611 .
Active plugin list is stored on cache, and so is shared across multiple process and/or clients.
So, for a plugin that has been loaded in the init process, a change on its state done by another process/client may makes it considered as not active during the request execution, which can leads to errors.
Storing this list in a static property will prevent this.
Since #5694, the list is rebuild on each request, so storing it in the cache is, at least, useless, and at worse, counterproductive.

Make plugin active list stored on request scope instead of server scope

---

.circleci/config.yml
tests/units/Glpi/EventSubscriber/Item/ItemEventHookMapper.php

Add MySQL tests on tag/nightly builds and use -ram images

---

inc/console/database/updatecommand.class.php
inc/update.class.php

Fix update of dev version

---

inc/update.class.php

Even if they are never released

Handle update from possible 9.4.x releases numbers

---

front/document.send.php
inc/user.class.php

GLPI_PICTURES_DIR is NOT a sub-directory of GLPI_DOC_DIR

fix user pictures

---

inc/rule.class.php

Fixed output not working in rule actions

---

inc/plugin.class.php

Fix plugin tests

---

tests/functionnal/Search.php

Add tests on AND NOT meta criteria

---

.circleci/config.yml

Harmonize circleci config with master branch

---

inc/console/migration/buildmissingtimestampscommand.class.php
inc/console/migration/timestampscommand.class.php
inc/dbmysql.class.php
tests/units/Migration.php

Fix usage of INFORMATION_SCHEMA db on MySQL 8

---

inc/update.class.php

Handle update from possible 9.5.x releases numbers

---

inc/commondbrelation.class.php
inc/commondbtm.class.php
inc/problem.class.php
inc/search.class.php
inc/ticket.class.php
src/Glpi/Database/AbstractDatabase.php
src/Glpi/Database/MySql.php
tests/functionnal/Search.php
tests/units/Glpi/Database/MySql.php
tests/units/Migration.php

Various db

---

.circleci/config.yml
INSTALL.md

Update dev install doc and remove duplicated build step

---

inc/dbmysqliterator.class.php
tests/imap/MailCollector.php
tests/units/DBmysqlIterator.php

10 fix my8

---

inc/slalevel.class.php

| Fixed tickets | #5319 
Intenal id: 16780

Fix SLA level escalation; fixes #5319

---

inc/define.php

feat(core): ability to configure more CSRF options in local_define

---

inc/html.class.php
install/install.php
install/update.php
package-lock.json
package.json
webpack.config.js

Looks like styles from jquery-ui-dist lib are not correclty built.
With this change, they will be built from jquery-ui source files directly.

Build jQueryUI CSS from official repository files

---

inc/location.class.php

Fix location items list; fixes #5830

---

inc/search.class.php
inc/software.class.php
install/mysql/glpi-empty.sql
install/update_94_95.php

search softwares: fix bad performances

---

inc/software.class.php

| Fixed tickets | see #5833 
Bug introduced in 9.3 ( https://github.com/glpi-project/glpi/commit/3f39085a762f6e9ff2ef314d50e98dd0ae3ff645#diff-17af799339343190eb55774113e99760R1051 ).

Fix software regroupment; see #5833

---

inc/db.function.php
inc/dbutils.class.php
inc/migration.class.php
install/update_91_92.php
install/update_92_921.php
install/update_92_93.php
src/Glpi/Database/AbstractDatabase.php
tests/functionnal/DbUtils.php
tests/units/Glpi/Database/MySql.php

Primary and compound keys are handled; and this should be compatible with postgresql.

Replace isIndex

---

inc/dbmysql.class.php

Replace usage of 'columns.column_type' MySQL specific column

---

inc/stat.class.php

FIX #5796 - Statistic by ticket : solution type

---

inc/item_ticket.class.php

Fix filtering of used items in tickets items

---

front/report.location.list.php
front/report.netpoint.list.php
front/report.switch.list.php
inc/report.class.php
tests/units/DBmysqlIterator.php

Convert report to iterator

---

inc/commontreedropdown.class.php

Fix software category child list; fixes #5841

---

inc/ipaddress.class.php
tests/units/DBmysqlIterator.php

Fix network IP adresses list; fixes #5865

---

inc/knowbaseitem_item.class.php

Fix wrong query

---

inc/ticket.class.php

Fix '_date_creation_calendars_id' criteria on ticket update rules

---

inc/search.class.php
inc/ticket.class.php

Add a 'next escalation level' search option on tickets

---

inc/search.class.php
inc/ticket.class.php

 Filter TTO/TTR in next escalation depending on ticket state

---

templates/glpi_page.twig

Fix jQueryUI CSS path

---

inc/api.class.php

use closure to inspect criteria in api search item

---

inc/commonitilobject.class.php

display private icon on timeline also without edit right

---

composer.json
composer.lock

See https://github.com/leafo/scssphp/releases for changes.

Update leafo/scssphp to latest version
