glpi-project/glpi

inc/dbmysql.class.php, inc/dbmysqliterator.class.php, tests/units/Migration.php
| Fixed tickets | see #5273
Same as #5851 but for 9.5 branch.
Replaces #5891.
=> Add cache on tableExists

inc/dropdown.class.php
=> Add missing PDU type in dd list; fixes #5924

inc/commonitilobject.class.php, inc/dropdown.class.php, inc/ruleasset.class.php, inc/ruleticket.class.php, inc/search.class.php
=> Fix 'is_requester' condition

inc/html.class.php, tests/units/Html.php
=> Consider all zeros in datetime as null

inc/search.class.php
=> fix for PHP 7.4

inc/search.class.php
=> Fix display past delay in search engine - fixed #5943

front/css.php, front/find_num.php, inc/html.class.php, index.php, src/Glpi/Controller/Main.php, templates/glpi.twig, tools/compilescsscommand.class.php
=> Make CSS cacheable by browsers and proxies

inc/commonitilobject.class.php, inc/ruleticket.class.php
=> Observer group condition (9.4)

inc/search.class.php
=> Fix undefined index in reservations search; fixes #5929

CHANGELOG.md, ajax/entityCustomCssCode.php, css/styles.scss, inc/entity.class.php, inc/html.class.php, install/mysql/glpi-empty.sql, install/update_94_95.php, package-lock.json, package.json, webpack.config.js
Can be customized for each entity:
Can also be inherited from parent configuration:
=> Add ability to customize CSS into entity configuration

composer.json, composer.lock
https://github.com/leafo/scssphp/issues/649 has been solved.
=> Remove custom repository for leafo/scssphp

tests/functionnal/TicketRecurrent.php
=> Fix recurrent ticket tests

composer.json, composer.lock, inc/config.class.php
Was done in master branch in #5360
=> Remove useless lib paragonie/random_compat

INSTALL.md, inc/autoload.function.php, package-lock.json, package.json, webpack.config.js
=> Update application dependencies

inc/commonitilactor.class.php, inc/commonitilobject.class.php, inc/ruleaction.class.php, inc/ruleticket.class.php, inc/ticket.class.php, tests/functionnal/Rule.php, tests/functionnal/Ticket.php
Cherry-pick of #5883 into 9.4 branch.
=> Add a ticket business rule action to prevent take into account

inc/changetask.class.php, inc/problemtask.class.php, install/mysql/glpi-empty.sql, install/update_942_943.php
Internal ref 17062
Rights verification in changes/problems task seems strange
=> check task right when adding change/problem task

composer.json, composer.lock, inc/config.class.php, inc/html.class.php
See https://github.com/leafo/scssphp/issues/649#issuecomment-498909596
=> Use scssphp from scssphp fork

inc/ticket.class.php, tests/functionnal/Ticket.php
this occurs with Formcreator plugin
=> Fix location business rule when an array of requesters is given

inc/toolbox.class.php
=> Make sure logger errors are not fatal, but still logged

inc/html.class.php, index.php, install/update.php, lib/bundles/base.js, package-lock.json, src/Glpi/Application/Middleware/RequireJs.php, templates/glpi.twig, templates/glpi_page.twig, templates/list.twig, templates/login.twig, webpack.config.js
Following #5831 for master branch.
=> Bundle libraries to reduce CSS/JS requests

inc/enclosure.class.php
=> Fix column closed twice

inc/certificate.class.php
| Fixed tickets | 17237 (internal)
=> Exclude deleted and template certificates from cron

inc/ruleright.class.php
=> Make sure we work on an array; closes #6014

install/mysql/glpi-empty.sql, install/update_942_943.php
=> Add missing PurgeLog cron task; fixes #6020

apirest.md
| Fixed tickets | #5995 
Same fix as a790a8247d993c533e1db6912a8f459ca1fff7f1
=> Fix link to itemtype list; fixes #5995

front/cluster.form.php, front/cluster.php, front/clustertype.form.php, front/clustertype.php, front/item_cluster.form.php, inc/cluster.class.php, inc/clustertype.class.php, inc/commondbtm.class.php, inc/define.php, inc/dropdown.class.php, inc/html.class.php, inc/item_cluster.class.php, inc/profile.class.php, inc/relation.constant.php, inc/state.class.php, install/mysql/glpi-empty.sql, install/update_94_95.php, tests/functionnal/Item_Cluster.php, tests/units/Html.php
=> Add clusters

ajax/itilfollowup.php, front/itilfollowuptemplate.form.php, front/itilfollowuptemplate.php, inc/define.php, inc/dropdown.class.php, inc/itilfollowup.class.php, inc/itilfollowuptemplate.class.php, inc/relation.constant.php, install/mysql/glpi-empty.sql, install/update_94_95.php
=> add templates for followups

inc/commonitilobject.class.php
| Fixed tickets | #4015 (+ internal 17262)
=> Display requester identity in ITIL timeline; fixes #4015

inc/savedsearch.class.php
| Fixed tickets | 17196 (internal)
=> fix(savedsearch): remove is_private for change_entity massiveaction

inc/html.class.php, inc/stat.class.php
=> Fix duration statistics CSV export; fixes #6035

inc/computer_softwareversion.class.php
Fix bad CommonDBRelation declaration for items_id
Fix #5989 
| Fixed tickets | #5989
=> Fix API result for Computer_SoftwareVersion query

.circleci/config.yml
Splitting test suite into multiple command may help to create partial test suites.
Example: https://github.com/cedric-anne/glpi/commit/06cfb8e1ef6a0b7294c9600a520a249af39daeb0#diff-1d37e48f9ceff6d8030570cd36286a61
=> Split test suite into multiple commands

inc/ruleasset.class.php
fix #6040
Fix display dropdown users for assets rules engine
=> Fix display dropdown users for assets rules engine

inc/html.class.php
=> Prevent execution of javascript event on rich text

inc/html.class.php
=> Forbid javascript scheme

inc/glpinetwork.class.php
=> Missing translation

inc/location.class.php
=> Add address,postcode and town to search

inc/commondbtm.class.php, inc/computer.class.php, inc/datacenter.class.php, inc/dcbreadcrumb.class.php, inc/dcroom.class.php, inc/enclosure.class.php, inc/monitor.class.php, inc/networkequipment.class.php, inc/pdu.class.php, inc/peripheral.class.php, inc/rack.class.php
=> Add datacenter position search option

inc/log.class.php
=> avoid warning on missing user when displaying logs

inc/ruleticket.class.php, inc/ticket.class.php
|------------- | ---
Internal ref 17341
=> add item's state criteria in ticket's rules

inc/location.class.php
=> Fix location item list; fixes #6064

inc/contract.class.php
=> Fix initial duration in contracts alert; fixes #6004

inc/reminder.class.php
=> todo reminders in the past still should be visible when late

inc/dropdown.class.php
=> permits to search in dropdown also on displaywith options

inc/rulecollection.class.php
| Fixed tickets | Internal id: 15235
=> Fix rulecollection test when entities is part of criteria

inc/notificationtargetsavedsearch_alert.class.php
=> alerts for savedsearch was never send

inc/commonitilobject.class.php
=> add a space between actor icons

CHANGELOG.md, inc/commondbtm.class.php, inc/computer.class.php, inc/define.php, inc/item_operatingsystem.class.php, inc/monitor.class.php, inc/networkequipment.class.php, inc/peripheral.class.php, inc/phone.class.php, inc/printer.class.php
These items were already set for massive actions and to forward their entity, but missing the tab and search options.
=> Add OS links on Monitors, Peripherals, Phones and Printers

inc/user.class.php
| Fixed tickets | #6033 
Removed redundant root_doc.
=> Fix VCARD link in user form

inc/transfer.class.php
If an exception occurs at any point during a transfer, the whole process should be rolled back to avoid data loss.
=> Use DB transactions in transfer process

inc/ticket.class.php
Hi
I noticed many unused globals, I submit a cleanup
=> cleanup unused globals

front/document.send.php, inc/toolbox.class.php
=> Add expires headers on pictures to enhance cacheability

inc/transfer.class.php
Internal ref 17396
When trying to transfer entities, we have some errors:
**sql-errors.log**
```
[2019-07-15 14:12:54] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/9.4-git/inc/dbmysql.class.php line 188
SQL: SELECT `glpi_entities`.`id`, `glpi_entities`.`name`, `glpi_entities`.`completename` AS `locname`, `glpi_entities`.`id` AS `entID` FROM `glpi_entities` LEFT JOIN `glpi_entities` ON () WHERE `glpi_entities`.`id` IN ('89') ORDER BY `locname`, `glpi_entities`.`name`
Error: Not unique table/alias: 'glpi_entities'
Backtrace :
inc/dbmysqliterator.class.php:95                   
inc/dbmysql.class.php:580 …
```
=> alias entities when transfering entities (not unique table)

inc/dbmysql.class.php
Having a static variable for tables/fields cache can be a problem on edge cases (see https://circleci.com/gh/glpi-project/glpi/22729 ).
On normal case, as DB is not reinstanciated during a single request, it should have no impact on performances.
=> Make table and fields cache reset on new DB instanciation

inc/ticketrecurrent.class.php, tests/functionnal/TicketRecurrent.php
=> Fix recurrent ticket periodicity value check; fixes #6140

inc/document.class.php
=> Fix warning on doc upload when multiple duplicates exists; fixes #6145

tests/functionnal/Session.php
| Fixed tickets | test for #6136
=> Add test on Session::loadGroups()

inc/notificationeventmailing.class.php
=> Fix handling of documents URL parameters in notifications; fixes #6159

js/common.js
=> Fix search on dropdowns having entries with chevrons; fixes #6102

css/palettes/_aerialgreen.scss, css/palettes/_auror.scss, css/palettes/_automn.scss, css/palettes/_classic.scss, css/palettes/_clockworkorange.scss, css/palettes/_dark.scss, css/palettes/_darker.scss, css/palettes/_flood.scss, css/palettes/_greenflat.scss, css/palettes/_hipster.scss, css/palettes/_icecream.scss, css/palettes/_lightblue.scss, css/palettes/_premiumred.scss, css/palettes/_purplehaze.scss, css/palettes/_teclib.scss, css/palettes/_vintage.scss, css/styles.scss, inc/html.class.php, index.php
| Fixed tickets | partially fixes #5996 
Some simple enhancement for web accessibility on the global layout.
=> Enhance web accessibility

.github/FUNDING.yml
Hi, I would like to add sponsors buttons to our GitHub repository GLPI project
.github/FUNDING.yml shows the community how to support this project. Please see the [repository funding links documentation](https://help.github.com/articles/displaying-a-sponsor-button-in-your-repository) for more information on formatting and what is and isn't allowed in this file.
=> Sponsor buttons

tests/LDAP/AuthLdap.php, tests/LDAP/ldif/ldap-glpi.ldif
Not sure it will change anything, but I found this duplicated uid when trying to understand why tests were failing here https://travis-ci.org/glpi-project/glpi/builds/564038074.
=> Remove duplicate uid in LDAP fixtures

inc/mailcollector.class.php
=> Fix unrelevant linking to old ticket in collector; fixes #6179

css/palettes/_aerialgreen.scss, css/palettes/_auror.scss, css/palettes/_automn.scss, css/palettes/_classic.scss, css/palettes/_clockworkorange.scss, css/palettes/_dark.scss, css/palettes/_darker.scss, css/palettes/_flood.scss, css/palettes/_greenflat.scss, css/palettes/_hipster.scss, css/palettes/_icecream.scss, css/palettes/_lightblue.scss, css/palettes/_premiumred.scss, css/palettes/_purplehaze.scss, css/palettes/_teclib.scss, css/palettes/_vintage.scss, css/styles.scss, front/user.form.php, inc/html.class.php, inc/log.class.php, inc/session.class.php, inc/user.class.php
=> Add impersonate feature

inc/ruleright.class.php
| Fixed tickets | internal 17553
=> fix(ruleright): missing default group action assign

composer.json, composer.lock, front/authmail.php, front/mailcollector.php, front/setup.auth.php, inc/auth.class.php, inc/authmail.class.php, inc/config.class.php, inc/mailcollector.class.php, inc/plugin.class.php, inc/rulemailcollectorcollection.class.php, inc/toolbox.class.php, status.php, tests/emails-tests/02-unknown_user.eml, tests/emails-tests/05-empty-from.eml, tests/emails-tests/06-quoted-subject.eml, tests/emails-tests/07-quoted-rejected-subject.eml, tests/functionnal/Config.php, tests/imap/MailCollector.php
=> Use Zend Mail for collector

inc/ticket.class.php, tests/functionnal/CommonITILValidation.php
| Fixed tickets | internal 17575
Replaces https://github.com/glpi-project/glpi/pull/6194
=> Fix approval status

inc/budget.class.php
=> fix project costs in budget

inc/location.class.php
=> fix(location): add missing searchOptions

inc/itilfollowup.class.php, inc/search.class.php, inc/ticket.class.php, inc/tickettask.class.php
Internal ref : 16937.
Following #6150, this does the same but for TicketTask
=> Add defaultWhere for TicketTask

inc/search.class.php, inc/user.class.php
Search::addWhere() had to be modified for this searchOption to work.
This is an alternative to #6214.
=> Add responsible search option for user

CHANGELOG.md, inc/document.class.php, inc/entity.class.php, inc/ticket.class.php, install/mysql/glpi-empty.sql, install/update_94_95.php, tests/functionnal/Document.php, tests/functionnal/Ticket.php
=> Add cron to purge closed tickets

install/update_94_95.php
=> Fix rolling release update; fix #6256

.travis.yml, composer.json, composer.lock
=> Fix travis nighlty; add PHP 7.4

inc/item_ticket.class.php
=> Fix used items in tickets items tab

inc/api.class.php, inc/commonglpi.class.php, inc/commonitilvalidation.class.php, inc/dcroom.class.php, inc/document.class.php, inc/document_item.class.php, inc/dropdown.class.php, inc/entity.class.php, inc/massiveaction.class.php
Remove unused globals
| Fixed tickets | #
Joint a log from PHPCS with the extension sirbrillig/phpcs-variable-analysis
[cs_variables_check.log](https://github.com/glpi-project/glpi/files/3530167/cs_variables_check.log)
=> Cleanup unused vars

inc/item_rack.class.php, inc/rack.class.php
=> Missing rightname; fixes #6170

inc/knowbase.class.php, inc/knowbaseitem.class.php
=> Missing categories translations; closes #6113

inc/console/database/abstractconfigurecommand.class.php, inc/console/database/installcommand.class.php
Fix merge of #6286 into master
=> Fix installation command when using existing configuration

tools/HEADER, tools/modify_headers.pl
=> Update copyright default header and handle scss files

inc/computer_softwarelicense.class.php, inc/softwarelicense.class.php, install/mysql/glpi-empty.sql, install/update_94_95.php
| Fixed tickets | #1505 
Backport from master
=> Allow assigning of licenses over assigned quota; closes #1505

inc/define.php, inc/phone.class.php, install/mysql/glpi-empty.sql, install/update_94_95.php
=> Phone Storage

inc/transfer.class.php
=> Try to get rid of empty IN from transfer; closes #6243

css/styles.scss, inc/commondbrelation.class.php, inc/commondbtm.class.php, inc/commondropdown.class.php, inc/commonglpi.class.php, inc/commonitilobject.class.php, inc/commontreedropdown.class.php, inc/computer.class.php, inc/computer_item.class.php, inc/contract.class.php, inc/document.class.php, inc/group.class.php, inc/infocom.class.php, inc/itiltemplate.class.php, inc/knowbaseitem_item.class.php, inc/massiveaction.class.php, inc/monitor.class.php, inc/networkequipment.class.php, inc/peripheral.class.php, inc/phone.class.php, inc/printer.class.php, inc/rule.class.php, inc/software.class.php, inc/ticket.class.php, inc/user.class.php, js/common.js, tests/functionnal/MassiveAction.php, tests/functionnal/Rule.php
=> Add relevant massive actions on main form

inc/calendar.class.php, inc/ticketrecurrent.class.php
=> Fix ticket recurrent first occurrence computation

inc/commonitilobject.class.php
=> Do not display edit nor split/merge icon when ticket is closed

README.md
=> add new demo links

CHANGELOG.md, inc/ticket.class.php, install/mysql/glpi-empty.sql, install/update_94_95.php, tests/functionnal/Ticket.php
- Moved logic into a separate function
- Added ability to merge tasks and actors
- Added ability to change link type
- Added ability to specify if the process stop after a single failure, or if it tries merging all tickets and rollback individual ones that fail. Not exposed in UI but usable through API or plugins.
- Added tests for merging tickets
=> Multiple Ticket merge enhancements

inc/dropdown.class.php, inc/item_ticket.class.php, inc/networkport.class.php, inc/reservationitem.class.php, inc/ticket.class.php, inc/toolbox.class.php, inc/transfer.class.php, inc/user.class.php
=> Fix phpdoc, data**s**, unused variables, missing declarations, fix DISTINCT

inc/profile.class.php
=> FIx rights for ITIL templates

CHANGELOG.md, inc/migration.class.php, tests/units/Migration.php
=> Add itemtype migration method

inc/toolbox.class.php, install/empty_data.php, install/mysql/glpi-empty.sql, tests/APIBaseClass.php
=> Replace SQL inserts with PHP code and prepared statements

css/styles.scss
=> Fix font awesome's glyphs load

inc/notificationtargetticket.class.php, tests/functionnal/Search.php
=> Fix notices triggered on PHP 7.4

install/mysql/glpi-empty.sql, install/update_94_95.php
=> Fix glpi_documents_items.date_creation column type

inc/autoload.function.php, inc/dbmysql.class.php, inc/dbmysqliterator.class.php
Also drop US/UK wording on analyse.
=> Add DB::quote for future PDO compat

.circleci/config.yml, .github/workflows/ci.yml, .travis.yml, tests/bootstrap.php, tests/functionnal/NotificationMailing.php, tests/github_actions.config_db.php
Run full test suite in Github Action on push event. For now, it does almost same tests as what is done on CircleCI, but on a more compete matrix. PR for 9.5 branch will show some error we did not detect with CircleCI.
=> Run CI tests using Gihub actions

inc/commonitilobject.class.php, inc/entity.class.php, inc/profile.class.php, install/mysql/glpi-empty.sql, install/update_94_95.php, tests/functionnal/ITILSolution.php, tests/functionnal/ITILTemplate.php
=> Default template configuration for ITIL objects

inc/search.class.php, tests/functionnal/Search.php
regression in https://github.com/glpi-project/glpi/pull/6260
Let's be careful with this PR. It solves the issue in Formcreator : https://github.com/pluginsGLPI/formcreator/issues/1506
=> fix bad sql query

inc/dbmysqliterator.class.php, tests/units/DBmysqlIterator.php
=> Quote aliases

.circleci/config.yml, .github/workflows/ci.yml, .travis.yml, bin/console
1. Remove usage of `--optimize-autoloader` which is automatically set by composer.json config.
2. Replace the `--ci` option by more flexible `--composer-options`.
=> Refactor dependencies install options

inc/alert.class.php, inc/auth.class.php, inc/authldap.class.php, inc/authmail.class.php, inc/autoload.function.php, inc/blacklist.class.php, inc/calendar.class.php, inc/calendar_holiday.class.php, inc/calendarsegment.class.php, inc/cartridge.class.php
=> Update some PHPDoc

inc/crontask.class.php, inc/dbutils.class.php, inc/levelagreementlevel.class.php, inc/massiveaction.class.php, inc/notificationtarget.class.php, inc/reservation.class.php, inc/search.class.php, inc/ticket.class.php, inc/user.class.php
=> Fix some PHP warnings that may be bugs

inc/commondbrelation.class.php, tests/functionnal/Search.php
=> fix search options for CommonDBRelation itemtypes

front/planningcsv.php, inc/planning.class.php, inc/planningcsv.class.php, inc/planningevent.class.php, inc/reminder.class.php, tests/abstracts/AbstractPlanningEvent.php, tests/functionnal/PlanningCsv.php
=> CSV export for planning

inc/contract.class.php
=> fix contracts dropdown - fixed #6439

inc/change_ticket.class.php, inc/commonitilcost.class.php, inc/item_ticket.class.php, inc/itil_project.class.php, inc/knowbaseitem_item.class.php, inc/problem_ticket.class.php, inc/projecttask_ticket.class.php, inc/ticket.class.php
=> fix adding problem - see #5689

inc/change_ticket.class.php, inc/commonitilcost.class.php, inc/item_project.class.php, inc/item_ticket.class.php, inc/problem_ticket.class.php, inc/ticket.class.php
=> [9.1] fix bug with colsed items - see #5689

inc/change_ticket.class.php, inc/commonitilcost.class.php, inc/item_project.class.php, inc/item_ticket.class.php, inc/knowbaseitem_item.class.php, inc/problem_ticket.class.php, inc/projecttask_ticket.class.php, inc/ticket.class.php
=> [9.2] fix bug with closed items - see #5689

inc/change_ticket.class.php, inc/commonitilcost.class.php, inc/item_project.class.php, inc/item_ticket.class.php, inc/knowbaseitem_item.class.php, inc/problem_ticket.class.php, inc/projecttask_ticket.class.php, inc/ticket.class.php
=> fix bug with closed items - see #5689

inc/contract.class.php
=> [9.1] fix contracts dropdown - see #6439

inc/contract.class.php
=> [9.2] fix contracts dropdown - see #6439

inc/contract_item.class.php
=> fix link for project in a contract - fixes #4908

inc/contract_item.class.php
=> [9.1] fix link for item in a project - see #4908

inc/contract_item.class.php
=> [9.2] fix link for item in a project - see #4908

inc/commonitiltask.class.php
=> ticket massive action for adding task should have state field

.circleci/config.yml, .github/workflows/ci.yml, composer.json, composer.lock, install/mysql/glpi-empty.sql, install/update_084_085.php, install/update_91_92.php, install/update_94_95.php
Use correct DB for tests
Install db first
Move misplaced code, fix db index, fix empty
Type was not existing
Wrong default value
Fix GH actions
=> Fix database tests

inc/search.class.php, tests/functionnal/Search.php
=> Fix search engine on complex join; fixes #6397

inc/blacklist.class.php, inc/rule.class.php, inc/ruleasset.class.php, inc/ruleright.class.php, inc/ruleticket.class.php, inc/transfer.class.php, tests/functionnal/Rule.php
Backport #6001 and #6016 for 9.4
=> factorize maxActionsCount

inc/html.class.php, tests/units/Html.php
Cache freshness of SCSS files is currently only based on md5 of the root file. If any imported sub SCSS file is modified, cache is still considered as fresh. This PR fixes this.
This was not really a bug as it was only a problem for developpers.
=> Make SCSS file cache invalidated if any import changed

js/impact.js
Improve mouseover handling :
- Cursor in now default on edge
- Can't drag the graph when mouseovering an edge
=> [Impact] Improved mouseover handling

js/impact.js
=> [Impact] Go to on double click

css/impact.scss, inc/impact.class.php, js/impact.js
=>  [Impact] Fullscreen mode

inc/notificationeventmailing.class.php
Inspired by #3698. This PR was containing a refactoring commit that I choosed to ignore, so I get the first 3 commits and just do a small refactoring to limit the amount of changed code.
=> Attach documents to plain-text emails

inc/rule.class.php
=> Typo criteria/criterion

install/update_94_95.php
=> Fix 'refresh_views' config migration

inc/changetask.class.php, inc/commonitiltask.class.php, inc/planning.class.php, inc/planningcsv.class.php, inc/planningevent.class.php, inc/problemtask.class.php, inc/projecttask.class.php, inc/tickettask.class.php
Not a feature nor a fix, just a clean of this part
=> simplify management of planning groups (who_group, whogroup)

composer.json, composer.lock
=> Bump glpi-project/coding-standard from 0.7.1 to 0.7.2

inc/change.class.php, inc/problem.class.php
=> Use templates values when creating from a ticket

inc/change.class.php, inc/problem.class.php
=> Copy associated elements from ticket while copying

inc/changetask.class.php, inc/commonitiltask.class.php, inc/planning.class.php, inc/planningevent.class.php, inc/problemtask.class.php, inc/projecttask.class.php, inc/tickettask.class.php
=> Not planned tasks

css/styles.scss, inc/objectlock.class.php
Replace stalled read only #6395
=> New objectlock message look and style

inc/ticket.class.php
| Fixed tickets | #6402 
Alternative proposal to #6430 .
=> Do not display save button if ticket is locked; fixes #6402

inc/console/commandloader.class.php, tests/units/Glpi/Console/CommandLoader.php
1. Handle namespaced commands at root level.
2. Handle namespaced commands inside plugins.
=> Enhance command loader

ajax/impact.php, css/impact.scss, css/styles.scss, front/impact.php, front/impactcsv.php, front/impactitem.form.php, inc/ajax.class.php, inc/impact.class.php, inc/impactitem.class.php, js/impact.js, tests/units/Impact.php, tests/units/ImpactItem.php
=> [Impact] List view

inc/planning.class.php
=> Check if method exists

inc/planningexternalevent.class.php
=> fix application of rrules byday and bymonth fields from templates

inc/planning.class.php
=> Fix not planned issue with groups

inc/search.class.php
=> Fix missing actions in global criteria

js/planning.js
=> shorten vertical space usage in resource view

inc/event.class.php, inc/html.class.php, inc/project.class.php
=> [9.5] Multiple minor fixes

inc/event.class.php, inc/knowbaseitem.class.php, inc/log.class.php
| New feature?  | yes/
Maybe others parts of GLPI could be also set as readonly, let me know.
=> Use DB slave (if available) more often

CHANGELOG.md, inc/dbmysql.class.php
1. Fix changelog.
2. Remove deprecated tag that should not be here.
=> Fix changelog and PHPdoc

inc/profileright.class.php
| Fixed tickets | #6593 
Introduced by 2365e15ab55470024217ee51d0b4c6ca3a439fff
=> Fix statement exec in ProfileRight::fillProfileRights(); fixes #6593

inc/console/rules/replaydictionnaryrulescommand.class.php, scripts/compute_dictionnary.php
=> Move dictionnary rules replay command into bin/console

inc/console/rules/processsoftwarecategoryrulescommand.class.php, scripts/softcat_mass_compute.php
=> Move software category recompute command into bin/console

inc/ruleaction.class.php
Same as #6606 but for RuleAction.
Fix #6462.
=> Add missing $itemtype  for RuleAction

inc/html.class.php, js/fileupload.js, lib/bundles/file-type.js, package-lock.json, package.json
=> Fix handling of pasted images extension; fixes #6355

inc/ruleticket.class.php, tests/functionnal/RuleTicket.php
Thisd PR allow to rule engine to add solution on ticket  according to solution template defined in criteria
| Bug fix?      | no| New feature?  | yes
=> Add new criteria to rule ticket

inc/user.class.php
=> Fix case sensivity in LDAP sync of emails; fixes #6554

inc/caldav/traits/vobjectconvertertrait.class.php, inc/html.class.php, inc/objectlock.class.php, inc/planning.class.php, inc/planningevent.class.php, js/common.js, lib/bundles/base.js, package-lock.json, package.json, tests/abstracts/AbstractPlanningEvent.php, tests/functionnal/Planning.php, webpack.config.js
Aditionnaly, i fixed some issues with timezones (some events didn't change in the planning regarding the user timezone)
=> Date exceptions for recurrent events

ajax/impact.php, css/impact.scss, inc/impact.class.php, inc/toolbox.class.php, js/impact.js
Replace the toolbar by a new sidebar.
A lot of minors improvements, the main one being that we can now drag and drop assets directly into the graph.
| Tests pass?   | pending
=> Impact sidebar

inc/objectlock.class.php
=> Make object unlock works on Chrome 78 and Firefox 70

inc/planning.class.php, inc/planningexternalevent.class.php, js/planning.js
=> fix target user when adding event in resource view

inc/migration.class.php, tests/units/Migration.php
=> DATETIME should no longer be used

composer.lock, front/crontask.php, inc/apixmlrpc.class.php, inc/calendarsegment.class.php, inc/certificate_item.class.php, inc/commondbtm.class.php, inc/config.class.php, inc/contract.class.php, inc/infocom.class.php, inc/search.class.php, inc/user.class.php, install/update_0781_0782.php
Due to phpcs update from composer on continuous integration.
=> Update phpcs and fix new found issues

tests/functionnal/Slm.php
=> Fix SLM tests when run is on saturday

inc/knowbaseitem_item.class.php
=> Fix KBI tab for non CommonITILObject items

inc/mailcollector.class.php, install/mysql/glpi-empty.sql, install/update_943_945.php, install/update_94_95.php, tests/emails-tests/08-tech-and-cc.eml, tests/imap/MailCollector.php
This PR add new option to mail collector to add or not cc user as ticket observer 
=> Add new option to mail collector

inc/software.class.php, inc/softwarelicense.class.php
Internal support id: 18630
1) Number of installations was wrong due to malformed search options (`condition` was ignored as not defined in `joinparams`).
2) Remove templates from licences count and licences list.
=> Fix softwares installations and licences count

inc/html.class.php
Implementation of a time only field in HTML  class
=> Time (only) field 

inc/system/requirement/protectedwebaccess.class.php
This check was initialy done here: https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/toolbox.class.php#L1091
=> Fix protected web access test loop on install/update page

front/locale.php
=> Correctly serve locales to front even if an update is required

inc/dbmysql.class.php
=> Drop error muting

front/ticket.form.php, inc/commonitilobject.class.php
Internal support id: 18539
Replaces #6675
=> Fix rules evaluation on usage of 'add me as ...' feature

.dependabot/config.yml, tools/make_release.sh
It will be easier to propose/discuss about configuration update with this configuration file for dependabot.
I added a weekly check for security releases on top level dependencies for current release.
=> Add dependabot config

inc/rule.class.php, tests/functionnal/Rule.php
| Fixed tickets | #6491 
Cherry-pick of #6667 initially done on 9.5/bugfixes.
=> fix(rule): count from all actions not actions added by user; fixes #6491

inc/commonglpi.class.php
=> Fix actions in form header for CommonDBChild items; fixes #6488

tests/functionnal/TicketRecurrent.php
=> Fix TicketRecurrent test on monday afternoon

front/locale.php
Handle some error cases to try to find what can cause the issue #6679
1. Handle locale files read errors.
2. Force usage of binary mode while reading po file (to be sure that line feed are not translated).
3. Log error if mandatory headers are not set.
4. Handle extra whitespaces at end of lines (to prevent errors if po file has been altered)
=> Handle error cases and extra whitespaces on JSON locales

css/styles.scss, front/helpdesk.faq.php, front/knowbaseitem.form.php, inc/knowbaseitem.class.php
=> fix(knowbaseitem): incorrect FAQ links

inc/knowbaseitem.class.php
Follow #6770 .
We found with @flegastelois the title of the article was not translated in the pager.
=> translate title of kb item

inc/reservationitem.class.php
=> Fix reservation alert cron

inc/change.class.php, inc/commonitilobject.class.php, inc/htmltablecell.class.php, inc/itiltemplate.class.php, inc/itiltemplatepredefinedfield.class.php, inc/planning.class.php
=> Fix bad PHP symbols

composer.json, composer.lock, inc/config.class.php
Follows #6777 and replace #6779 .
=> Add missing zend/mime direct dependency to composer.json

tests/APIBaseClass.php, tests/functionnal/AuthLdap.php, tests/functionnal/SLM.php, tests/units/GLPI.php, tools/generate_bigdump.function.php
Follows #6774 to fix bad cases found while scanning tools and tests directories.
=> Fix classes case

inc/authldap.class.php, inc/authmail.class.php, inc/commondropdown.class.php, inc/config.class.php, inc/item_devices.class.php, inc/mailcollector.class.php, inc/notificationmailingsetting.class.php, inc/user.class.php
See https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#Preventing_autofilling_with_autocompletenew-password
=> Prevent autocomplete of password fields outside login context

inc/notificationtargetcertificate.class.php, inc/notificationtargetdomain.class.php, install/empty_data.php, install/update_94_95.php
I also fix missing data in update from 9.4 to 9.5.
=> Add tech and group in charge as possible targets for certificates/domains alerts

inc/ruledictionnaryprintercollection.class.php
Fix a regression introduced in e8999dbc1d1482c03dbf7860d4771d47e0df775f
=> Fix printer dictionnary rules replay

inc/commonitilobject.class.php, inc/db.function.php, inc/displaypreference.class.php, inc/document.class.php, inc/document_item.class.php, inc/domaintype.class.php, inc/dropdown.class.php, inc/dropdowntranslation.class.php, inc/entity.class.php, inc/entity_knowbaseitem.class.php, inc/entity_rssfeed.class.php, inc/event.class.php, inc/fieldblacklist.class.php, inc/fieldunicity.class.php, inc/fqdn.class.php, inc/fqdnlabel.class.php, inc/group_knowbaseitem.class.php, inc/group_reminder.class.php, inc/group_rssfeed.class.php, inc/html.class.php, inc/olalevel_ticket.class.php, inc/planningrecall.class.php, inc/queuednotification.class.php, inc/slalevel_ticket.class.php, inc/softwarelicense.class.php, inc/ticket.class.php, inc/ticketrecurrent.class.php
These PHPDoc errors pollutes my IDE with lots of red markers. This PR is just a quick fix to be able focus on real errors.
=> Fix some PHPDoc errors

tests/functionnal/Item_OperatingSystem.php
=> Fix MySQL8 tests

.circleci/config.yml, .github/workflows/ci.yml, inc/authldap.class.php
=> Run CI checks on all PHP versions when results may depend on it

inc/user.class.php, tests/functionnal/User.php
=> Prevent timezone unset on user update from massive actions

inc/change.class.php, inc/impact.class.php, inc/problem.class.php, inc/ticket.class.php, js/common.js, js/impact.js, lib/bundles/cytoscape.js, package-lock.json, package.json
Show a badge with the number of ongoing incidents for this asset.
The badge color match the highest priority among the incidents with some tweaks to ensure a decent level of contrast (default colors for the lowest priorities are too close to white to be directly used).
The badge can be clicked to access the ongoing incident list.
Show the number of ongoing incidents, problems and changes (if any).
Color match the highest priority level.
The cells can be clicked to access the ongoing incidents/problems/change list for the given asset.
=> Impact badges

.circleci/config.yml, .github/workflows/ci.yml, composer.json
This may help to detect problems with `composer.json`/`composer.lock` files.
For instance, changes in `composer.json` that were not applied:
Or warnings due to `composer.json` contents (see https://circleci.com/gh/glpi-project/glpi/33521 )
=> Add composer validation on CI linting

css/impact.scss, inc/impact.class.php, js/impact.js
Add undo/redo shortcuts and buttons.
=> Impact undo

inc/html.class.php
Fix change in 0c89b8a962b84ddef0ea4e011225391a2dee3905
submit button didn't have any value
=> set a value for submit button

install/update_94_95.php
As right rules can now be applied to local users (see #6794), default right rule that was present prior to GLPI 9.5 has to be updated to prevent all local account to get the default "Self Service" profile assignment.
=> Fix default right rule in migration

tests/functionnal/TicketRecurrent.php
- fix failure of tests on monday between 12am and 1pm
- fix failure of tests on last 7 days of month
=> Fix ticket recurrent tests

inc/commondbtm.class.php, tests/functionnal/CommonDBTM.php
=> Fix missing clean on KB related items deletion; fixes #6810

inc/infocom.class.php
=> Fix inconsistent not found error on inforcom activate; fixes #6819

inc/ruleticket.class.php, inc/ruleticketcollection.class.php
I don't know why (i'll ask past myself), but criterion added in #4868 didn't have any matching input...
=> missing input for ruleticket criterion added in 9e234d8

inc/html.class.php
=> JS methodw wait for text, not html; fixes #6862

inc/planning.class.php, js/planning.js, tests/functionnal/Planning.php
=> show ical import also on timeline view

inc/autoload.function.php
=> Fix API detection when using php-cgi; see #6780

inc/domainrecord.class.php
=> Improve domain records list

front/locale.php
=> Fix JS error on empty locale from plugin; fixes #6679

composer.json, composer.lock
=> Switch back to atoum stable release

front/domainrecord.form.php, inc/domainrecord.class.php
=> Add new record from domain

ajax/comments.php, inc/html.class.php, inc/planningevent.class.php, inc/planningexternalevent.class.php, inc/user.class.php
permits to have a multiple select with User::dropdown
=> manage multiple values in user dropdown

inc/profile.class.php
=> Move Domain rights config to management tab

inc/console/migration/domainsplugintocorecommand.class.php
=> Add Domains migration command

inc/planningevent.class.php
=> fix creation on external event (fatal on multiple users)

.travis.yml
=> Remove travis irc notifications

inc/console/database/abstractconfigurecommand.class.php, inc/console/database/installcommand.class.php
| Fixed tickets | #6919 
Same as #6921 but for 9.5/bugfixes branch.
=> Add ability to install DB unsing a socket connection; fixes #6919

CHANGELOG.md
I saw that some entries were missing when working on plugins upgrade.
I keep it as draft for the moment as I may find new ones within next few days.
=> Add missing entries in changelog

inc/entity.class.php, inc/search.class.php, inc/user.class.php, tests/functionnal/Search.php
=> Fix search query when using composite key on current item; fixes #6859

inc/lock.class.php
=> Fix wrong alias on join

inc/domainrecord.class.php, inc/profile.class.php, install/empty_data.php, install/mysql/glpi-empty.sql, install/update_94_95.php
=> Add rights to manage domain records limited to their types

inc/impact.class.php, inc/ticket.class.php
=> No impact analysis on helpdesk; fixes #6956

front/helpdesk.faq.php, front/user.form.php, inc/html.class.php
=> Add language selection on public FAQ

inc/dropdown.class.php
=> Add domains records types in dropdowns

inc/commonitilobject.class.php
=> fix display task - fixed #6970

ajax/entitytreesons.php, inc/commonitilobject.class.php
=> Issue 6974

inc/ticket.class.php
=> [93]fix display task - fixed #6970

ajax/entitytreesons.php, inc/ticket.class.php
=> 93 issue 6974

.circleci/config.yml, .gitignore, front/css.php, front/find_num.php, inc/html.class.php, index.php, tools/compilescsscommand.class.php, tools/make_release.sh
Backport of #5972, #5985, #5988, #6479, #6483 from 9.5/bugixes branch to make SCSS compiled on release process and highly cacheable.
=> Fix scss cacheability

inc/knowbaseitemcategory.class.php
=> Open KnowbaseItemCategory to self-service API users

inc/domainrecord.class.php
=> Ability to manage domainrecords without managing domain

inc/planningevent.class.php, inc/planningexternalevent.class.php, inc/planningexternaleventtemplate.class.php
=> add searchoptions to external events

composer.json, composer.lock
=> Use caret operator for atoum/atoum compatibility

inc/commondbtm.class.php, inc/console/migration/domainsplugintocorecommand.class.php, inc/domain.class.php, inc/domainrecord.class.php, tests/functionnal/Domain.php, tests/units/RuleRight.php
=> Fixes on domains and records

inc/domainrecord.class.php
=> Fix records status

inc/abstractquery.class.php, inc/html.class.php, inc/queryexpression.class.php, inc/queryparam.class.php
| Fixed tickets | #7021
Backport of #6548 for 9.4
=> Fix warning with objects in session

ajax/autocompletion.php, ajax/getDropdownConnect.php, ajax/getDropdownFindNum.php, ajax/getDropdownNetpoint.php, ajax/getDropdownNumber.php, ajax/getDropdownUsers.php, ajax/getDropdownValue.php
=> Use correct content-type for autocompletion url

tests/bootstrap.php
=> Use a transaction when boostraping data, usefull when bootstraping fails

inc/levelagreement.class.php
=> display sla/ola comment - fixed #7022

inc/levelagreement.class.php
=> [93] display sla/ola comment - fixed #7022

front/domainrecord.form.php, inc/domainrecord.class.php
Properly handle backcreated from popup,
Close popup reloads the records list
=> Fixes on domains records

inc/domainrecord.class.php
=> Order records by type and name

inc/softwareversion.class.php, tests/functionnal/SoftwareVersion.php
Fix the following error introduced by https://github.com/glpi-project/glpi/commit/2365e15ab55470024217ee51d0b4c6ca3a439ff :
I've also added a very simple test case to be sure it doesn't break again.
=> Fix incorrect sql migration

inc/commondbtm.class.php, inc/domainrecord.class.php
=> Fix rootdomaindisplay

inc/dashboard/grid.class.php
missing return.
Not tested (yet), my 9.5 env si currently broken
=> dashboard return cache

inc/html.class.php
To prevent any event (especially the space or enter keys) on the background
=> To force focus on the button

inc/networkport.class.php
=> Fix VM networks

inc/item_devices.class.php, inc/log.class.php, inc/migration.class.php, inc/rulecollection.class.php, tests/units/Migration.php
=> Various fixes

inc/domainrecord.class.php
=> Make records active per default

composer.json, composer.lock
=> Use new official repository for PHP Parallel Lint dev dependency

.github/workflows/ci.yml
1) Use Github docker repository for Github actions.
2) Use new version of checkout version (which may be faster according to changelog).
=> Use Github docker repository for Github actions

inc/commondbtm.class.php, inc/domain.class.php, inc/domainrecord.class.php, inc/itiltemplatepredefinedfield.class.php, inc/networkportinstantiation.class.php, tests/DbTestCase.php, tests/functionnal/Search.php, tests/functionnal/Transfer.php
Add tests on transfers, remove specific transfer on domains, fixes.
=> Domains transfer

inc/rule.class.php, inc/ruleaction.class.php, inc/ruleticket.class.php, inc/ticket.class.php, tests/functionnal/RuleTicket.php
Add new action to put default user group as group request of ticket
from rule ticket.
=> add action 'copy default from user' for group requester

inc/group_user.class.php
Follow #6978, it cool to have users in the dropdown, it's better to list them after effective addition
=> list users without rights in group page

inc/computervirtualmachine.class.php
=> Use same units on VM memory and memory component

inc/computer.class.php
=> Fix comments rwospan on computer; closes #7029

js/impact.js
The algorithm used to calculate the depth made a few mistakes in complicated cases.
Ex (node labels are set to display the calculated deph):
This was fixed by switching the the Dijkstra algorithm that is natively integrated in cytoscape.
The flags calculations (flags computes which part of the graph are impact, dependencies or both) were using the same logic so they have been switched to this new algorithm too.
After:
=> Impact - Use dijkstra for depth and flags calculations

front/passivedcequipment.form.php, front/passivedcequipment.php, front/passivedcequipmentmodel.form.php, front/passivedcequipmentmodel.php, front/passivedcequipmenttype.form.php, front/passivedcequipmenttype.php, inc/console/migration/racksplugintocorecommand.class.php, inc/define.php, inc/dropdown.class.php, inc/html.class.php, inc/passivedcequipment.class.php, inc/passivedcequipmentmodel.class.php, inc/passivedcequipmenttype.class.php, inc/relation.constant.php, inc/state.class.php, install/mysql/glpi-empty.sql, install/update_94_95.php, tests/functionnal/PassiveDCEquipment.php, tests/units/Html.php
Add passive equipement "matching" Other equipements from former rack plugin.
I tested manual adding / updating, not the migration script atm. Will do with customer data.
Address these suggestions:
- https://glpi.userecho.com/communities/1/topics/541-add-patch-panel-in-network-asses?comment_form_activate=true
- https://glpi.userecho.com/communities/1/topics/940-passive-painel-to-rack
=> Datacenter passive equipments

apirest.md
=> add a note for apache+fpm for api usage

inc/console/maintenance/disablemaintenancemodecommand.class.php, inc/console/maintenance/enablemaintenancemodecommand.class.php
=> More simple names

inc/mailcollector.class.php
=> Fix handling of inlined images in collectors; fixes #7136

inc/toolbox.class.php
=> Allow usage of audio and video tags in KB

inc/massiveaction.class.php
Allow GLPI to update infocom from plugin itemtype (ie: genericobject)
=> WIP :Allow infocom update for plugin itemtype

inc/pdu.class.php
| Fixed tickets | #7123
Note: not relevant on 9.5 branch; this is now handled more globally.
=> Fix creating PDU from template; closes #7123

inc/user.class.php
=> Fix sanitized value; closes #6900

inc/item_devices.class.php
=> Prevent access for non auth users; fixes #6798

inc/plugin.class.php
=> Permit plugins to overrides all _types from config; fixes #6938

inc/define.php
=> Missing links on simcards; fix #6296

inc/define.php, inc/location.class.php
Add all Item_Devices* to location_types; permit to display all located items, fix overrided variable
refs #7054
| Fixed tickets | #7054
=> Some item tab on location fixes

inc/planning.class.php
=> To fix tooltips that are not always shown

inc/commondbtm.class.php, inc/commonitiltask.class.php, inc/contact.class.php, inc/item_devices.class.php, inc/item_operatingsystem.class.php, inc/item_rack.class.php, inc/itilfollowup.class.php, inc/itiltemplatefield.class.php, inc/itiltemplatepredefinedfield.class.php, inc/notificationtarget.class.php, inc/notificationtemplatetranslation.class.php, inc/operatingsystemkernelversion.class.php, inc/profile_user.class.php, inc/ruleaction.class.php, inc/rulecriteria.class.php, inc/user.class.php, tests/functionnal/RuleCriteria.php
| Fixed tickets | #7134 
Bench made on #6858 shows that removing cache will not have a huge impact on performances. We may find another way to handle cache if users complains about performances.
=> Remove caching of friendly names; fixes #7134

inc/planning.class.php
=> Fix CalDAV URL; fixes #7178

inc/console/migration/domainsplugintocorecommand.class.php
=> Migrate suppliers_id from plugin

inc/ticket.class.php
=> Documents should not be displayed if hidden; fixes #7195

inc/appliance.class.php, inc/define.php, inc/impact.class.php, tests/functionnal/Appliance.php
=> Add Change And Impact Analysis For appliances

front/knowbaseitemtranslation.form.php, inc/knowbaseitem.class.php
Fix https://github.com/glpi-project/glpi/issues/7092
| Fixed tickets | #7092
=> Fix SQL Errors on display Knowbase

ajax/impact.php
Secure the json payload to avoid SQL injections.
=> Escape impact json payload

css/styles.scss, inc/commonitilobject.class.php
An old ticket :P https://github.com/glpi-project/glpi/issues/1159
| Fixed tickets | #1159
& hover
=> Ticket Tasks Enhancement

inc/knowbaseitem.class.php, tests/functionnal/KnowbaseItem_Revision.php
possible fix for #6961
| Fixed tickets | #6961
=> Data not escaped; improve tests

tests/APIBaseClass.php
=> Fix APIXmlrpc::testUndisclosedField() test

inc/massiveaction.class.php, tests/functionnal/MassiveAction.php
Internal ref: 17299.
Add two new massive actions :
* Amend comment
* Add note
=> Amend comment / Add note massive actions

css/styles.scss
| Fixed tickets | not reported
Before:
After:
=> Add top margin to timeline buttons

inc/computervirtualmachine.class.php
=> Add to display VM "comment" field, and add search by this field

inc/change.class.php, inc/impact.class.php, inc/problem.class.php, inc/ticket.class.php
=> Fix ImpactAnalysis count ItilObjects & titles

front/dcroom.form.php, inc/console/database/updatecommand.class.php, inc/define.php, inc/update.class.php, install/update_946_947.php
Event type should be 'dcrooms' not 'serverroms'. Causes missing Source in log list and broken ID column link.
=> Fix Server Room events

css/styles.scss, inc/html.class.php, js/kanban.js
The source of a card drag was the Kanban column body instead of the column itself, while the target was the column. This caused the new column counter to update correctly, while the original column would not update.
=> Fix Kanban counters and add form

inc/html.class.php
| Fixed tickets | Follow #6933
=> fix helpdesk menu entry hook when used with marketplace plugin

inc/marketplace/api/plugins.class.php
| Fixed tickets | follow #6933
=> sort plugins without checking case in marketplace

inc/knowbaseitem.class.php
Fix Knowbase visibility for self-service (Forgotten array)
| Fixed tickets | None
=> Fix Knowbase visibility for self-service

inc/commonitilobject.class.php
Fix Form Validation for timeline Ticket
Without correction : 
| Fixed tickets | None
=> Fix Form Validation for timeline Ticket

tools/make_release.sh
=> Ensure files created from cli commmands calls are dropped in release

inc/search.class.php
=> Global asset search; fixes #7286

inc/impact.class.php
=> Fix KnowBase In ImpactAnalysis

css/styles.scss, js/planning.js, tests/LDAP/AuthLdap.php
| Fixed tickets | #7285
& fix CSS for empty list on "planning view" :
=> Fix Planning Color Change & CSS

tools/build_glpi.sh
Follows #7292 + removal of an `exit` that should not be here.
=> Remove cache and log generated during release process

.github/workflows/ci.yml
=> Add min supported version to CI matrix; fixes #7293

README.md
=> Replace CI badge

inc/appliance.class.php, inc/define.php, tests/LDAP/AuthLdap.php
=> Link Appliances To Knowbase Articles

inc/mailcollector.class.php, install/mysql/glpi-empty.sql, install/update_94_95.php, tests/imap/MailCollector.php
| BC breaks?    | yes/no
| Deprecations? | yes/no
=> Drop imap kerberos

.circleci/config.yml, .github/workflows/ci.yml, composer.json
I accidentally apply CS fixes to all my plugins :)
=> Ignore marketplace in CS tasks

ajax/kanban.php, css/palettes/_darker.scss, css/styles.scss, inc/project.class.php, js/kanban.js
Also in commit:
Fix minor height different with columns without a header color (No Status column)
=> Bulk add items from Kanban

inc/dashboard/widget.class.php
| Fixed tickets | #7354, follow #7356
=> remove reverseData params as its behaviors is very strange, fix #7354

inc/commonitilobject.class.php
=> Fix notice; closes #7274

inc/authldap.class.php
=> Some fields were duplicated; fixes #7316

inc/domain.class.php, inc/group.class.php, inc/item_operatingsystem.class.php, inc/user.class.php
domain
group
user
operating system
=> Fix display form for multiple classes

inc/commondbrelation.class.php
=> Fix bad query in document associated item count; fixes #7357

inc/console/database/installcommand.class.php, inc/toolbox.class.php
=> Fix --reconfigure param behavior in install command

inc/commonitiltask.class.php, inc/define.php, inc/itilfollowup.class.php, inc/planningexternalevent.class.php, inc/projecttask.class.php, inc/projecttasktemplate.class.php, inc/tasktemplate.class.php, install/update_94_95.php
=> Add rich text to itsm and project's tasks (and their templates)

inc/budget.class.php, inc/consumableitem.class.php, inc/enclosure.class.php, inc/knowbaseitem_item.class.php, inc/softwarelicense.class.php, inc/user.class.php
=> Fix More Display (tr / td)

inc/networkname.class.php
=> Fix query; closes #7376

ajax/kanban.php
At least the AJAX code file needs tests made.
=> Fix Kanban compat with Feature/traits #7296

inc/networkname.class.php
=> Fix wrong query, closes #7376

inc/networkequipment.class.php
| New feature?  | /no
| Fixed tickets | #7376
=> Fix Form Network Equipment

inc/commonitilvalidation.class.php
```
PHP Notice:  Undefined index: global_validation in /var/www/webapps/glpi/inc/commonitilvalidation.class.php on line 1497
PHP Stack trace:
PHP   1. {main}() /var/www/webapps/glpi/ajax/common.tabs.php:0
PHP   2. CommonGLPI::displayStandardTab() /var/www/webapps/glpi/ajax/common.tabs.php:92
PHP   3. Problem->showForm() /var/www/webapps/glpi/inc/commonglpi.class.php:627
PHP   4. CommonITILValidation::alertValidation() /var/www/webapps/glpi/inc/problem.class.php:1303
```
=> Fix notice

.travis.yml, inc/dbmysqliterator.class.php, tests/units/DBmysqlIterator.php
=> Trigger error, COUNT(DISTINCT *) wont work

tools/locale/extract_template.sh
=> Search for translations in subdirectories as well

inc/change.class.php, inc/commonitilobject.class.php, inc/itiltemplate.class.php, inc/problem.class.php, inc/ticket.class.php
=> Do not try to create missing objects

inc/ruleimportcomputer.class.php
=> Rule import computer fix

css/dashboard.scss
Fix scrolling on mobile device
=> permits to scroll with touch events on responsive dashboard

inc/change.class.php, inc/commonitilobject.class.php, inc/problem.class.php, inc/ticket.class.php
Quite same as #7408, with factorization.
=> Factorize checks and add impact tab on Change and Problem

inc/marketplace/view.class.php
=> Call to non existing translation domain

css/styles.scss, inc/computer_item.class.php, inc/item_softwareversion.class.php
=> align list to left

inc/marketplace/view.class.php
=> fix title in marketplace with translations (apos issue)

inc/auth.class.php
=> gracefuly fails ldap connections for final user

inc/define.php
=> Allow passive DC items to be attributed to tickets

inc/reservationitem.class.php
=> fix sql error, simcard name field in reservation

inc/search.class.php
=> Fix missing call to _addLeftJoin hook; fixes #7436

inc/dropdown.class.php
=> Fix selected 'toadd' value in timestamp dropdown; fixes #6948

inc/networkportinstantiation.class.php
| Fixed tickets | #7421
closes #7421 
The abstraction seems logical but the way tabs are handled will need reviewed/reworked first.
=> Revert NetworkPortInstantiation abstraction

inc/ticket.class.php
=> Fix helpdesk form when using a template; fixes #6988

.atoum.php, .circleci/config.yml
Do not remove git dir on circle builds
=> Enable code coverage, upload to scrutinizer

inc/rule.class.php
=> Permit to set ranking on rule creation (useful for UT)

inc/define.php, inc/monitor.class.php, inc/networkequipment.class.php, inc/peripheral.class.php, inc/printer.class.php
I think it is safe to say any item that can have an OS, may also have the ability to have software (or individually licensed features).
=> Make software types the same as for OS

js/impact.js
=> Fix links to ITIL items inside plugin item impact tab; fixes #7301

inc/commondbrelation.class.php, inc/commondbtm.class.php, inc/commonitiltask.class.php, inc/devicesimcard.class.php, inc/item_operatingsystem.class.php, inc/knowbaseitem.class.php, inc/levelagreementlevel.class.php, inc/networkport.class.php, inc/networkportethernet.class.php, inc/networkportfiberchannel.class.php, inc/networkportwifi.class.php, inc/notificationevent.class.php, inc/olalevelaction.class.php, inc/olalevelcriteria.class.php, inc/purgelogs.class.php, inc/rulecriteria.class.php, inc/search.class.php, inc/slalevelaction.class.php, inc/slalevelcriteria.class.php, tests/functionnal/Search.php
=> Fix search options 3 and 4 of CommonDBRelation; fixes #7440

inc/itiltemplate.class.php
=> ITILTemplate is abstract, use static to access called class

.circleci/config.yml, composer.json, composer.lock
=> Use composer to fetch scrutinizer/ocular

README.md, inc/system/requirementsmanager.class.php
=> Fix requirements in readme

inc/appliance.class.php, inc/define.php, inc/domain.class.php, inc/dropdown.class.php, inc/item_devicesimcard.class.php, inc/item_ticket.class.php, install/mysql/glpi-empty.sql, install/update_94_95.php, install/update_94_95/appliances.php
| Fixed tickets | #7417
In addition of issue mentionned in #7417, i found global dropdown also failed.
Due to missing `is_helpdesk_visible` and `name` fields
=> fix warnings/errors when linking simcards to itilobjects

inc/dbmysql.class.php, inc/toolbox.class.php
=> Prevent proxy timeout on installation; fixes #7425

inc/config.class.php, inc/toolbox.class.php, tests/units/Toolbox.php
=> Check URL in configuration; fixes #7437

.circleci/config.yml, inc/config.class.php
=> Check if API configuration URL is valid as well, refs #7437

inc/glpinetwork.class.php, inc/toolbox.class.php
| Fixed tickets | #7411 
Display a warning with original cURL error message to help user understand why its registration key is not validated.
=> Add some informations when GLPI network is not reacheable; fixes #7411

inc/marketplace/view.class.php
=> Missing esacping on string

inc/marketplace/view.class.php
=> Escaping, wrong gettext domain

inc/plugin.class.php
=> Fix warning on plugin menu; fixes #7482

inc/networkport_vlan.class.php
| Fixed tickets | https://github.com/glpi-project/glpi/pull/7427#issuecomment-645721703
=> align vlan list

inc/supplier.class.php
=> Fix empty TD in Supplier showform

js/marketplace.js
=> fix refresh on installed tab in marketplace

front/marketplace.download.php, inc/marketplace/api/plugins.class.php, inc/marketplace/controller.class.php, inc/marketplace/view.class.php
=> Fix download of plugins archive from GLPI Network

inc/console/abstractcommand.class.php, inc/console/application.class.php, inc/console/command/glpicommandinterface.class.php, inc/console/database/installcommand.class.php, inc/console/database/updatecommand.class.php, inc/console/system/checkrequirementscommand.class.php
=> Check mandatory core requirements on all commands

inc/ruleasset.class.php
| Fixed tickets | internal !20226
=> fix assign group in ruleasset

css/styles.scss
=> Fix timeline timestamps truncated overflow; fixes #7291

apirest.md
| Fixed tickets | #7266 
Cherry-picked from @cconard96 commit a28c2c5f9c11bf5b599c6e8a6a0e2a88a5b9a7f4.
=> Fix Get all items API documentation; fixes #7266

inc/document_item.class.php, install/mysql/glpi-empty.sql, install/update_94_95.php
=> Fix 'Duplicated document item relation' error on migration; fixes #7430

inc/application/errorhandler.class.php
Since we defined an exception handler and a shutdown function, PHP was not anymore exiting with the 255 code.
I detected on as a `Call to a member function xxx() on null` on install command was exiting with a 0 code, and test suite was not failing at the right place.
=> Fix exit code on exception/fatal error

inc/contractcost.class.php
=> Fix bad call; closes #7504

css/styles.scss
| Fixed tickets | issue wasn't reported
Before:
Alter:
=> Change ticket processing page to display comment content below user info on small phones

inc/ruleright.class.php, inc/ruleticket.class.php
=> Fix business rules conditions using deprecated notation; fixes #7507

.dependabot/config.yml
Only security updates on 9.5 branch and all updates/upgrades on master.
=> Change branches in dependabot strategies

inc/change.class.php, inc/problem.class.php
closes #6785
| Bug fix?      | yes (depends who you ask)
| Fixed tickets | #6785 
When creating changes or problems from a ticket, the category should be checked to make sure it is applicable. If not, blank the field.
=> Enforce category restrictions

inc/console/plugin/installcommand.class.php
=> Includes marketplace plugins in install command list; fixes #7579

inc/based_config.php
=> remove rc versions from marketplace

inc/dashboard/provider.class.php
=> Fix Simcard URL in dashboards; fixes #7547

inc/html.class.php
=> Fix lightbox z-index in vertical split mode; fixes #7580

front/change.form.php, front/problem.form.php
=> Fix add me as observer on Changes and Problems; fixes #7591

inc/config.class.php, inc/glpinetwork.class.php, install/update_94_95.php
=> Encrypt GLPI Network registration key

inc/commonitilactor.class.php
=> Fix missing alternative_email in actor update form; fixes #7596

tools/build_glpi.sh
=> Remove Webpack config from release

lib/bundles/fullcalendar.js
=> import correctly rrule lib, and fix reccurent event display

CHANGELOG.md
=> Add missing releases in changelog

inc/search.class.php
| Fixed tickets | #7612 
Verified no regression on previous Global search issue.
=> Fix map search view

install/update.php, install/update_94_95.php
=> Fix access to undefined configuration during update process; fixes #7626

install/update_94_95.php
These instructions were present twice in update.
=> Remove duplicated update instructions

inc/change_item.class.php, inc/item_problem.class.php
=> Fix wrong count; closes #7603

js/planning.js
=> Use UTC for planning date selection; see #7623

ajax/dropdownConnectNetworkPort.php
=> Fix network interfaces connection form; fixes #7617

inc/calendar.class.php, inc/calendar_holiday.class.php, inc/calendarsegment.class.php, inc/commondbchild.class.php, inc/commondbconnexity.class.php, inc/commondbrelation.class.php, inc/contract.class.php, inc/contract_item.class.php, inc/contract_supplier.class.php, inc/contractcost.class.php, inc/features/clonable.class.php, inc/projectcost.class.php, inc/projecttask.class.php, tests/functionnal/Computer.php, tests/functionnal/Itil_Project.php
Remove all overrides (thanks to @cedric-anne!)
Get from existing data
Add a method to retrieve field name
=> Factorize clone requests; add some tests

CHANGELOG.md, inc/console/database/updatecommand.class.php, inc/update.class.php, install/update_95_xx.php
Contains #7609, wait for it to be merged on master.
=> Add next major release placeholder

.circleci/config.yml, .github/workflows/ci.yml
=> Back to mariadb 10.3, there is something wrong with 10.5 and 10.4

inc/glpikey.class.php
=> Update registration key on security key change; see #7645

inc/toolbox.class.php, tests/units/Toolbox.php
=> Wrong invalid URL check; closes #7642

README.md
=> Drop IE from supported browser list

inc/appliancetype.class.php
=> Fix undefined 'externalid' on appliance type creation; fixes #7662

css/_highcontrast.scss, css/jquery-glpi.css
| Fixed tickets | internal ref: 20297
=> fix border and width of selected tab on google chrome

inc/mailcollector.class.php
=> Fix erronous mail collector rejected email reason

css/styles.scss, inc/commonitilobject.class.php, inc/commonitiltask.class.php, inc/event.class.php, inc/problem.class.php, inc/ticket.class.php
=> review all alignment of central tabs

inc/item_devices.class.php
=> prevent undefined index in item_devices

inc/define.php
=> Add domains to global search

inc/glpinetwork.class.php
| Fixed tickets | see #7645
1) Add some logs when registration API returned errored responses, to be able to get some useful informations on error trace.
2) Prevent following error by returning empty data if `registration/offers` response is invalid:
```
[2020-07-09 12:59:30] glpiphplog.CRITICAL: *** Uncaught Exception TypeError: Return value of GLPINetwork::getOffers() must be of the type array, null returned in /home/newsurf9/glpidemo1/inc/glpinetwork.class.php at line 295
Backtrace :
inc/marketplace/controller.class.php:315 GLPINetwork::getOffers()
inc/marketplace/view.class.php:769 Glpi\Marketplace\Controller->getRequiredOffers() …
```
=> Add error log on errored responses from registration API; see #7645

inc/config.class.php
=> Do not expose registration key in API config endpoint

inc/itilfollowup.class.php
Internal ref: 20304.
Use `canReopen` function and make condition more readable.
=> Fix reopen check

inc/plugin.class.php
=> Fix path for plugin local locales

inc/computer_softwareversion.class.php
=> Fix comments

inc/search.class.php
=> Condition may be an array; fixes #7696

inc/commondbtm.class.php, inc/enclosure.class.php, inc/pdu.class.php, inc/rule.class.php, inc/rulecollection.class.php, inc/softwarelicense.class.php, tests/functionnal/Rule.php
=> Fix rules clone; closes #7655

install/update.php
=> Fix update called via install process

inc/infocom.class.php
=> Fix typo; closes #7710

inc/marketplace/view.class.php
=> Display installed list on marketplace, even in offline mode; fixes #7714

inc/commonitiltask.class.php, tests/functionnal/PlanningCsv.php, tests/functionnal/ProjectTask.php, tests/functionnal/TicketTask.php
=> Prevent creation of a task having an empty content; fixes #7737

inc/projecttask.class.php
=> decode Html before display it in project task tootlip

inc/crontask.class.php, tests/functionnal/CronTask.php
Reverted criteria to what it was before switching to iterator. Added new CronTask test class.
=> Fix CronTask unregister

inc/appliance.class.php
=> Fix "link to appliance" massive action; fixes #7726

js/kanban.js
Switched some forms to simple divs since they don't act correctly as forms. They had no action on them so hitting enter in them would submit the form but actually refresh the page instead. Doesn't make sense to me to keep them as forms since they are never supposed to refresh the page. The Kanban is meant to be a realtime collaborative tool.
Fixed issue using length property on an Object. This caused team member icons to not be loaded at all on cards in some cases.
=> Some Kanban fixes

inc/session.class.php, inc/user.class.php
=> Do not show impersonate button for new user

inc/dropdown.class.php
=> Fix 'display' param of yes/no checkboxes

.github/ISSUE_TEMPLATE/config.yml
=> explore new options for issue templates

inc/log.class.php
=> Display Historical tab on items templates

inc/impact.class.php
=> New icons for impact UI

inc/project.class.php
| Fixed tickets | #7704 
fixes #7704
=> Pass entity and recursive fields to Kanban forms

inc/api/api.class.php, inc/cartridgeitem.class.php, inc/commonitilobject.class.php, inc/commonitiltask.class.php, inc/commontreedropdown.class.php, inc/consumableitem.class.php, inc/group.class.php, inc/itilfollowup.class.php, inc/networkname.class.php, inc/networkport.class.php, inc/printer.class.php, inc/profile.class.php, inc/project.class.php, inc/search.class.php, inc/software.class.php, inc/softwarelicense.class.php, inc/ticket.class.php, inc/user.class.php
=> Drop SQL conditions

inc/commondbtm.class.php, inc/dbutils.class.php, inc/item_devices.class.php, inc/item_disk.class.php, inc/item_operatingsystem.class.php, inc/item_softwareversion.class.php
To be checked per commit:
- few casts in commondbtm,
- handle namespaces in `getTableForItemType`,
- few logic/view separation (so it can be used in unit tests without any copy/paste of a huge iterator).
=> Various changes

inc/commonitiltask.class.php, inc/domain.class.php, inc/ticket.class.php
=> Fix search option conditions; see #6010

inc/commondbtm.class.php, inc/impact.class.php, inc/user.class.php
Use friendly names in graph view, list view and asset search.
| Fixed tickets | #7729
=> Use friendly names in impact analysis; fix #7729

CHANGELOG.md, inc/update.class.php, tests/functionnal/Update.php
=> Remove unused constants declared by update process

inc/search.class.php
Fix issue introduced in #7456.
| Fixed tickets | #7752
=> Fix global asset search; fix #7752

inc/define.php, inc/domain.class.php
=> Link domains and certificates; closes #7770

inc/define.php, inc/html.class.php
* Fix "Photoswipe is undefined" error
* Fix url encoding issue in JS code
=> Fix inline images

inc/dashboard/provider.class.php
=> Fix top tech assigned card link

inc/config.class.php, inc/glpinetwork.class.php, inc/marketplace/view.class.php
=> Do not translate confusing contraction

inc/commondbtm.class.php, inc/savedsearch.class.php
=> Fix ability to create saved search

inc/console/database/updatecommand.class.php, inc/glpikey.class.php, inc/toolbox.class.php, inc/update.class.php, install/update.php, tests/units/GLPIKey.php
| Bug fix?      | not directly
| Fixed tickets | #7746
For UI update:
For CLI update:
not done yet
=> Check presence of security key file on update; fixes #7746

inc/commonitilobject.class.php, inc/profile.class.php
| Fixed tickets | #7877 
Follows #7768.
=> Fix dropdown conditions declaration; fixes #7877

ajax/domainrecord_data_form.php, inc/domainrecord.class.php, inc/domainrecordtype.class.php, install/mysql/glpi-empty.sql, install/update_94_95.php, install/update_95_xx/domains.php
=> Add an helper form for domain record data

inc/ticket.class.php
| Fixed tickets | #7766 
#7451 only fixed first observer form, but problem was still existing when wanting to add more actors.
=> Fix helpdesk ticket observer form; fixes #7766

inc/html.class.php
=> Do not show browser notifications when impersonating; fixes #7882

inc/item_softwareversion.class.php
=> Fixed #7890 - display software's installation

inc/commondbrelation.class.php, inc/itiltemplatefield.class.php, inc/plugin.class.php, tests/functionnal/Appliance_Item.php, tests/functionnal/Document_Item.php
=> Fix clone massive action targeting

inc/dashboard/grid.class.php, inc/define.php
=> Fix usage of dashboard user preferences; fixes #7924

inc/autoload.function.php
| Fixed tickets | internal ref 20579
=> check if called url is the one setup for api

inc/contact.class.php, inc/user.class.php
Add title for both User and Contact vCards.
Add timezone for User vCard.
Add plugin hook for plugins to add additional fields to vCards such as IM contact information.
=> Add title, timezone, and plugin hook for vCards

inc/group_user.class.php
=> Fix list of groups that can be associated to a user; fixes #7942

inc/mailcollector.class.php, install/mysql/glpi-empty.sql, install/update_951_952.php, tests/imap/MailCollector.php
Prevent loop when message is read but when it's impossible to move or delete it
due to mailbox problem (ie: full)
=> Do not import mail already seen

inc/computer.class.php, inc/dropdown.class.php, inc/htmltablecell.class.php, inc/item_kanban.class.php, inc/plugin.class.php, inc/session.class.php, inc/ticket.class.php, inc/ticketsatisfaction.class.php, inc/toolbox.class.php, inc/user.class.php
Change strtotime("now") to time().
Move some function calls out of for loop condition.
Merge a str_replace call when it doesn't affect readability of code.
Replace array_push with $array[] when pushing a single item.
=> Some performance fixes

inc/rule.class.php, tests/functionnal/Rule.php
=> Fix rules ranking

inc/ruledictionnarysoftwarecollection.class.php
=> Fix assign new software category on rules replay; fixes #7950

inc/commonitiltask.class.php
=> Fix documents attachement on ITIL task update; fixes #7948

inc/cluster.class.php, inc/computer.class.php, inc/console/migration/racksplugintocorecommand.class.php, inc/dashboard/provider.class.php, inc/define.php, inc/event.class.php, inc/item_disk.class.php, inc/lock.class.php, inc/monitor.class.php, inc/networkequipment.class.php, inc/peripheral.class.php, inc/phone.class.php, inc/printer.class.php, inc/ruleimportcomputer.class.php
=> Fix typos on _s, missing uses and classes case

inc/transfer.class.php
=> Fix software transfer; fixes #7864

inc/console/migration/racksplugintocorecommand.class.php, inc/domain.class.php
=> Search on domains is_active field

inc/item_softwareversion.class.php
=> Fix softwares installations list; fixes #7979

composer.json, composer.lock, css/styles.scss, front/log/export.php, inc/config.class.php, inc/log.class.php, js/log_filters.js, tests/functionnal/Log.php
Add the possibility to export logs to CSV + slight UI change.
Log filters are taken into account for the export.
Before: 
After:
CSV result:
=> Export logs to CSV

inc/calendar.class.php, tests/functionnal/Calendar.php
=> Improve performance of dates computation (OLA / SLA); see #7959

.circleci/config.yml, .composer-require-checker.config.json, .github/workflows/ci.yml, composer.json, composer.lock, inc/config.class.php
Before #7969 , reports looked like this:
=> Add checks for bad symbols and missing dependencies

inc/cache/simplecache.class.php, tests/units/Glpi/Cache/SimpleCache.php
This PR handle the case where footprint file exists, is writable, but not readable.
Fixed error (see https://github.com/glpi-project/glpi/issues/7989#issuecomment-697369905) :
```
[2020-09-23 14:06:31] glpiphplog.NOTICE:   *** PHP Notice (8): file_get_contents(): read of 8192 bytes failed with errno=13 Permission denied in C:\inetpub\wwwroot\glpi\inc\cache\simplecache.class.php at line 285
Backtrace :
inc\cache\simplecache.class.php:285                file_get_contents()
inc\cache\simplecache.class.php:72                 Glpi\Cache\SimpleCache->checkFootprintFileIntegrity()
inc\config.class.php:3315 …
```
=> Handle missing read rights on cache footprint file

inc/notificationtargetcommonitilobject.class.php
=> Fix #7980 Bug : Notification template block post_addItem of ticket

inc/commondbchild.class.php, tests/functionnal/RuleSoftwareCategory.php
=> Rule clonage exception; fixes #7974

ajax/marketplace.php, inc/includes.php, inc/marketplace/controller.class.php, inc/plugin.class.php
| Fixed tickets | #7831, #7939
=> Fix download of already installed plugin; fixes #7939 and #7831

inc/domainrecord.class.php
=> Check on display name, not the one in db

inc/marketplace/api/plugins.class.php
=> Replace usage of deprecated Guzzle\Psr7 functions

inc/savedsearch.class.php
=> Add search option on saved searches privacy; closes #7936

inc/projecttask_ticket.class.php
=> Avoid empty IN conditions; fixes #7740

.circleci/config.yml, composer.json, composer.lock
Coverage on scrutinizer was sent, but has never worked on the other side for GLPI project; I never have answer to my question on their support.
Also, coverage upload sometimes causes tests runs to fail because of tmeout on their api.
=> Drop scrutinizer code coverage

inc/user.class.php
=> Add Default Value For User Dropdown

.github/workflows/ci.yml, .github/workflows/nightly_build.yml
Linked to https://github.com/glpi-project/docker-images/pull/32
=> Use ghcr.io Github registry for Github Actions

css/styles.scss, inc/ticket.class.php, tests/functionnal/MassiveAction.php
Internal ref: 18423, 19662.
New massive action to link multiple tickets to a problem.
New massive action to resolve multiple tickets.
=> Massive Action: link multiple tickets to a problem

inc/commondbtm.class.php
=> Fix phpdoc for CommonDbtm::getById()

front/item_disk.form.php
=> Do not rely on post value; fixes #8092

inc/domainrecord.class.php, inc/domainrecordtype.class.php
=> Add a placeholder in helpers for CNAMEs, make text input larger

composer.lock, inc/application/errorhandler.class.php, inc/autoload.function.php, inc/commondbtm.class.php, inc/entity.class.php, inc/html.class.php, inc/profile.class.php, inc/project.class.php, inc/system/requirement/protectedwebaccess.class.php, tests/functionnal/CommonDropdown.php, tests/functionnal/Group_User.php, tests/functionnal/Search.php, tests/units/Glpi/Application/ErrorHandler.php
Fixes from #8051 but without including patch of atoum as code has not been validated yet.
=> Fix some PHP 8 issues

inc/html.class.php, inc/item_devicebattery.class.php, inc/item_devices.class.php, install/mysql/glpi-empty.sql, install/update_95_xx.php, install/update_95_xx/devicebattery.php
Support missing wear for battery component 
- Depends on an update on the Inventory protocol
- needs clarification about current capacity reported by the Agent. It looks like the reported value is the last max capacity reported by BMS and is processed as the design max capacity. To be confirmed.
=> Battery wear support

inc/state.class.php
=> Fix method call; closes #8095

inc/rulecriteria.class.php, tests/functionnal/RuleCriteria.php
=> Handle multiple matchs from rules expressions

.github/actions/check_services_health.sh, .github/workflows/ci.yml
=> Make CI services healthcheck more robust

.htaccess
=> Minor typo fixes

inc/console/application.class.php, inc/console/commandloader.class.php, tests/units/Glpi/Console/CommandLoader.php
Prevent disabled plugin's command to be loaded.
=> Do not load commands of disabled plugins

.github/workflows/ci.yml
See https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
=> Enable manual run of test suite

front/savedsearch.form.php
=> Fixes #8143 bug on purge saved search

inc/commonitilobject.class.php, inc/impact.class.php, inc/ticket.class.php
I think I properly updated all uses of getLinkedItems to a CommonITILObject
| Fixed tickets | #8114
=> Fix itemcount in Ticket

inc/config.class.php, inc/console/config/setcommand.class.php
=> Add config:set command

inc/appliance_item.class.php
=> Fixed #8141

inc/system/requirementslist.class.php
=> Out of context requirements cannot be missing; fixes #8149

inc/migration.class.php, inc/toolbox.class.php
=> Fix migration output in very verbose mode (-vv)

css/dashboard.scss, inc/dashboard/grid.class.php, inc/dashboard/widget.class.php, js/dashboard.js
| Fixed tickets | replace #8147, internal !20871, #8110
=> fix dashboards (overlapping with search bar, cache issue on language, bars graph hidden on chrome)

inc/levelagreement.class.php, tests/functionnal/SLM.php
=> feat(sla): add month duration

inc/log.class.php
=> fixed #8164

inc/dashboard/widget.class.php
=> fix also line/area charts with chrome (broken animation)

inc/marketplace/view.class.php
=> Check plugins prerequisites on marketplace view

inc/ticket.class.php, tests/functionnal/ProjectTask.php, tests/functionnal/TicketTask.php
When a ticket is created by GLPI, message displayed inform that the ticket is create and it's treatment is in progress.
But the ticket is in progress when technician are assigned to ticket not when is incoming
| Fixed tickets | internal 20971
=> fix(translate): ticket has been registered but not yet processed

package-lock.json, package.json, webpack.config.js
1. Adapt options (remove values when same as default, set value when mandatory).
2. Add polyfills (resolve.fallbacks) that are not included anymore by default.
=> Upgrade to webpack 5.0

inc/commondbchild.class.php, inc/consumable.class.php, tests/functionnal/Cartridge.php, tests/functionnal/Consumable.php
=> Fix inheritance of consumable financial information

front/savedsearch.form.php
| New feature?  | 
| Fixed tickets | #8143
=> [9.4] Fixes #8143 bug on purge saved search

inc/glpinetwork.class.php
Reported in:
https://forum.glpi-project.org/viewtopic.php?id=279763
=> Fix undefined var in marketplace unavailable message

inc/html.class.php
=> fix autogrow on textarea

inc/appliance.class.php
Sounds like I've missed some parts of #7290 on Appliances rewrite
=> Re-add missed parts of #7290

inc/certificate.class.php
=> Fix wrong field name

inc/appliance.class.php
=> Handle appliances link massive action; internal 21015

inc/domainrecord.class.php
=> Fix TTL type in massive actions

inc/commondbchild.class.php
=> Enhance cloning exception message; see #8218

.github/workflows/nightly_build.yml
See warnings on https://github.com/glpi-project/glpi/actions/runs/352953999
=> Replace usage of deprecated set-env in Github Actions

inc/knowbaseitem.class.php
=> Limit document visibility in KB Browse view

inc/html.class.php
Bug introduced by 984ae321eca4cf516a0f07a205d5e39c12fc2edf.
Before:
After:
=> Fix dropdown display when selected value is part of toadd

.github/workflows/ci.yml
=> Add Percona DB server on CI matrix

inc/networkport_vlan.class.php, inc/vlan.class.php
=> Add ports lists on vlan

css/palettes/_darker.scss, inc/html.class.php
| Fixed tickets | #8261
| Before | After |
|---|---|
| ![Screenshot from 2020-11-13 20-31-21](https://user-images.githubusercontent.com/17678637/99137320-0327f700-25f8-11eb-8a8b-a6097834558f.png) | ![Screenshot from 2020-11-13 20-32-06](https://user-images.githubusercontent.com/17678637/99137321-0e7b2280-25f8-11eb-9dda-16c4e7695fed.png) |
| ![Screenshot from 2020-11-13 20-50-16](https://user-images.githubusercontent.com/17678637/99137330-1fc42f00-25f8-11eb-870f-af0933be2990.png) | ![Screenshot from 2020-11-13 20-50-45](https://user-images.githubusercontent.com/17678637/99137336-2d79b480-25f8-11eb-970a-0b5d5f23fab3.png) |
| ![Screenshot from …
=> Fix some dashboard, tab, select and input colors

inc/budget.class.php
=> Fix consumables in budget items list

inc/contract.class.php
=> Increase max items per contract

inc/appliance.class.php, inc/certificate.class.php, inc/define.php
I think that it can make sense for "web appliance"to have relations between certificates and domains.
I am not sure if it is the right way to publish a modification.
=> add relations between certificates, domains and appliances.

inc/console/database/updatecommand.class.php, inc/define.php, inc/group.class.php, inc/item_ticket.class.php, inc/location.class.php, inc/rulemailcollector.class.php, inc/rulemailcollectorcollection.class.php, inc/ruleright.class.php, inc/rulerightcollection.class.php, inc/ruleticket.class.php, inc/state.class.php, inc/ticket.class.php, inc/update.class.php, install/empty_data.php, install/update_952_953.php, tests/DbTestCase.php, tests/functionnal/Rule.php, tests/functionnal/Search.php
=> Fix 'under'/'not under' conditions of rule criteria; fixes #8235

inc/mailcollector.class.php, inc/notificationtargetcommonitilobject.class.php
| Fixed tickets | #8275 
1. Fix handling of empty "private profiles" in ticket notification.
2. Fix handling of blacklisted emails in mail collector (requester is not set when email is blacklisted).
=> Fix ticket debug; fixes #8275

.github/workflows/ci.yml
It may be hard to know which exact version of PHP and/or MySQL is used in CI checks. This new step can help to easilly find this information.
=> Show system components versions on CI checks

inc/features/planningevent.class.php, inc/planning.class.php
=> Fix fetching of group events; fixes #8185

ajax/mailcollector.php, front/authldap.form.php, front/config.form.php, front/mailcollector.form.php, inc/authldap.class.php, inc/mailcollector.class.php, tests/functionnal/AuthLdap.php
=> Prevent passwords to be altered by sanitize logic; fixes #8188

composer.lock, tests/APIBaseClass.php, tests/functionnal/Knowbase.php, tests/web/APIRest.php
=> Fix tests for atoum 4

.github/workflows/ci.yml, bin/console, composer.lock
=> Switch to composer 2.x

.atoum.php, composer.json, composer.lock, tests/APIBaseClass.php, tests/GLPITestCase.php, tests/functionnal/Computer.php, tests/functionnal/Domain.php, tests/functionnal/MassiveAction.php, tests/functionnal/Transfer.php, tests/imap/MailCollector.php, tests/web/Telemetry.php, tools/genphpcov.sh
=> Switch to atoum/atoum stable 4.x releases

tests/functionnal/Search.php
=> Remove MariaDB performances issues workaround in tests

tests/functionnal/Reminder.php
=> Re-enable reminders tests

css/jquery-glpi.css
=> fix marketplace titles in bold

tests/functionnal/Dropdown.php
=> try to fix dropdown tests

inc/commondropdown.class.php, inc/dropdown.class.php
=> Few minor changes/improvements

.github/workflows/ci.yml
=> Use self-hosted Github Actions runner on glpi-network repository

inc/mailcollector.class.php
=> Prevent object to be sanitized; closes #8345

.composer-require-checker.config.json
=> Fix require checker

.composer-require-checker.config.json, composer.json, tests/web/APIXmlrpc.php, tools/sodium_compat-php8-compat.patch
=> FIX PHP8 tests

inc/console/application.class.php
=> Prevent console error when DB not configured; fixes #8332

package-lock.json, package.json, webpack.config.js
Fixes following error introduced recently in master due to Webpack v5 changes.
=> Fix images pasting in rich text

apirest.php, apixmlrpc.php
=> Init loggers and error handlers on API

inc/glpimailer.class.php
=> Don't auto-enable SMTP TLS

inc/search.class.php
=> Fix User "Number of tickets as ..." search column

inc/dashboard/provider.class.php
=> Fix Top Ticket Assignee Groups dashboard card

inc/savedsearch.class.php
=> Fix typo in saved searches edition

inc/dashboard/widget.class.php
=> Fix bar size

inc/application/errorhandler.class.php, inc/dbmysql.class.php, inc/toolbox.class.php, tests/functionnal/MassiveAction.php
Exemple of failures: https://github.com/glpi-project/glpi/runs/1557404465?check_suite_focus=true
Successfull run on MySQL 8.0: https://github.com/glpi-project/glpi/runs/1562881501?check_suite_focus=true
=> Log SQL warnings

css/styles.scss, inc/change.class.php, inc/commonitilobject.class.php, inc/commonitilvalidation.class.php, inc/itilsolution.class.php
=> Add "Refused" and "Cancelled" status for changes

.github/workflows/ci.yml, inc/config.class.php, tests/GLPITestCase.php, tests/enable-apcu.ini, tests/functionnal/DbUtils.php, tests/functionnal/Entity.php
=> Remove cache logic specific to test suite

front/recurrentchange.form.php, front/recurrentchange.php, inc/commonitilrecurrent.class.php, inc/commonitilrecurrentcron.class.php, inc/html.class.php, inc/profile.class.php, inc/recurrentchange.class.php, install/mysql/glpi-empty.sql, install/update_95_xx/recurrentchange.php, tests/bootstrap.php, tests/functionnal/CommonITILRecurrent.php, tests/functionnal/RecurrentChange.php, tests/units/Html.php
Add recurrent changes.
Diff is not as big as it looks, most of it is code moving from TicketRecurrent to the new CommonITILRecurrent parent.
| Internal ref | !20911
=> Recurrent changes

install/update_95_xx.php, tests/functionnal/Transfer.php
=> Very minor changes

inc/knowbaseitem.class.php
| Fixed tickets | part of #8385
=> Fix KB item assocated documents list

inc/marketplace/api/plugins.class.php
| Fixed tickets | !21108
When `GLPI_MARKETPLACE_PRERELEASES` is set to false (default), plugins with only unstable versions are shown but no action is proposed.
I propose to hide these plugins from the list.
=> Hide plugins with no installable version

.github/workflows/ci.yml
=> Show loaded extensions in CI env

composer.lock
=> Update laminas mail to fix some known issues, update monolog for php8 fix

install/empty_data.php
Bug only present on master with upcoming Recurrant Changes feature.
=> Fix missed recurrent ticket cron rename in empty data

inc/item_ticket.class.php
=> fix "Unknown column name" on glpi_items_devicesimcards

inc/html.class.php
=> Exclude object and embed from tinymce

install/mysql/glpi-empty.sql, tests/glpi-0.80-empty.sql, tools/checklicenceheadercommand.class.php, tools/demo_data.sql
1) Use a RecursiveFilterIterator to prevent parsing structure of excluded directories (now takes less than 1 seconds instead of 5 seconds).
2) Use `--` comments for SQL files.
=> Enhance licence headers check command

inc/dashboard/filter.class.php, inc/dashboard/provider.class.php
Add new filter 'my groups' to dashboard
| Fixed tickets | internal 21250
=> feat(dashaboard): new filter 'my groups'

js/planning.js
=> Fixed dialog position for planning page

inc/appliance.class.php, inc/define.php
| Fixed tickets | #8533
Add External links to Domains and Appliances.
Add Contracts to Domains.
=> Add missing types for Domains and Appliances

.github/workflows/ci.yml
Check was added only on CircleCI on #7941, but CircleCI is no more used.
=> Check for gettext warnings

inc/profile.class.php, tests/functionnal/Profile.php
| Fixed tickets | Internal ref !21361
=> keep only a subsert of ticket's rights when swithcing profile to selfservice

inc/console/migration/timestampscommand.class.php
Even if it is highly improbable that this has any impact in this specific case, joining `information_schema.tables` and `information_schema.columns` must have condition on both `table_name` and `table_schema` fields, in order to be sure that we retrieve the information from the expected database.
=> Fix timestamp migration table iterator

inc/search.class.php
=> Added add_default_join plugin hook

inc/console/database/installcommand.class.php, inc/console/migration/buildmissingtimestampscommand.class.php, inc/console/migration/timestampscommand.class.php, inc/dbmysql.class.php, inc/migration.class.php
`_` is a wildcard in MySQL LIKE, it should be escaped.
=> Fix filtering in table listing

inc/stat.class.php, inc/state.class.php
=> Fix missing is_deleted field on some tables

inc/commonitilobject.class.php
=> Fix sql total duration

inc/log.class.php
=> [9.4]fixed #8164

inc/entity.class.php, tests/functionnal/Entity.php
=> Fixed custom css from entity inheritables

.github/workflows/ci.yml
=> Update test matrix to mainly use PHP8

inc/auth.class.php
=> Fix for other-authentication in GLPI 9.5

inc/dropdown.class.php, tests/bootstrap.php, tests/functionnal/Dropdown.php
Show both Model name and Product Number for every Model in GLPI.
Allow model dropdowns lookup by Product number additional to Model name.
=> Show product_number in dropdown

.github/workflows/ci.yml
=> Do not test MySQL 8.0 twice

inc/appliance.class.php, inc/search.class.php
| Fixed tickets | !21039 !21242
=> Add appliances search options from item

inc/inventory/asset/virtualmachine.class.php, inc/inventory/conf.class.php, tests/fixtures/inventory/computer_2.json, tests/functionnal/Glpi/Inventory/Inventory.php
=> Add configuration option to create Computer asset from VMs

inc/massiveaction.class.php
=> Use number type for clone count field

inc/console/database/updatecommand.class.php, inc/dbmysql.class.php, inc/define.php, inc/profile.class.php, inc/update.class.php, install/update_953_954.php, tests/functionnal/Search.php
=> Fix unrelevant values in SO tests

inc/console/migration/dynamicrowformatcommand.class.php
If no migration is required, command outputs nothing. This is disturbing.
=> Add some output on 'glpi:migration:dynamic_row_format' command

front/rule.common.php, inc/inventory/asset/mainasset.class.php, inc/inventory/inventory.class.php
=> Various fix

tests/functionnal/Config.php, tests/functionnal/Update.php
Some tests are failing since yesterday; I guess something has changed on images (I do not reproduce locally, and last 9.5/bf build before this night cron was ok).
=> Fix failing tests

composer.json, composer.lock, inc/config.class.php, inc/mailcollector.class.php, inc/toolbox.class.php, tests/imap/MailCollector.php, tests/units/Toolbox.php
=> Use existing slug method not to rely on extra 3rd party lib

inc/impact.class.php, js/impact.js, templates/impact/edit_compound_modal.html.twig, templates/impact/ongoing_modal.html.twig
| Tests pass?   | no, not related to changes
=> Use bootstrap + twig for impact modals

inc/csv/logcsvexport.class.php, tests/units/Glpi/Csv/LogCsvExport.php
It also fix tests on master branch.
=> Use Toolbox::filename for CSV export filenames

.github/workflows/coverage.yml
=> Compute code coverage on master branch

CHANGELOG.md, inc/commonitilcost.class.php, inc/contract.class.php, inc/project.class.php, inc/search.class.php, tests/functionnal/Search.php
- Base available meta types on *_types configurations;
- Refactor Search::addMetaLeftJoin() to make it generic as possible;
- Fix some bugs.
Main problem now is that testing all these meta criteria takes time.
Here is the count of available meta criteria with this change:
| Itemtype               | Before   | After     |
|:---------------------- |:-------- |:--------- |
| **Total**              | **1270** | **19933** |
| Appliance              | -        | 786       |
| Budget                 | -        | 594       |
| Cartridge              | -        | 54        |
| CartridgeItem          | -        | 95        |
| …
=> Populate meta criteria in a generic way

inc/central.class.php, inc/system/requirementsmanager.class.php, inc/system/variables.class.php
Display "fiels" folder access check to central page
=> feat(core): add check for 'files' folder access

.github/workflows/ci.yml, .github/workflows/coverage.yml
=> Fix coverage and prevent scheduled jobs to be launched on tier repositories

inc/api/api.class.php, inc/auth.class.php, inc/dashboard/filter.class.php, inc/dashboard/grid.class.php, inc/dashboard/provider.class.php, inc/dashboard/widget.class.php, inc/marketplace/controller.class.php, inc/update.class.php
=> Do not use CommonGLPI on classes that do not require it

inc/rulemailcollectorcollection.class.php, tests/functionnal/RuleMailcollector.php
=> Fix mailcollector rules based on requester group; fixes #8340

inc/session.class.php
Thank @cedric-anne for the help.
This pr fixes this issue
=> fix adding new user planning due to a bad idor check

inc/itilfollowup.class.php
Add check to know if lifecycle allows change of status
| Fixed tickets | internal 21535
=> fix(lifecycle): check if reopening is allowed through lifecycle rights

front/contract_item.form.php
=> Fix bad translation

inc/appliance.class.php
=> fix(appliance): add location and manufacturer searchOptions

inc/computer_item.class.php
=> Use configuration types

install/mysql/glpi-empty.sql, tests/functionnal/RuleMailcollector.php
=> Remove integer display width on is_default_profile

inc/knowbaseitem_revision.class.php
=> fix(knowbase): missing escaped fields for revision translation

.github/actions/init_containers-start.sh
=> Install acl to fix CI jobs on ubuntu 20.04

install/empty_data.php, install/update_95_xx/native_inventory.php, tests/functionnal/DbUtils.php
=> Add missing crontask at install

inc/inventory/conf.class.php
=> Missing configuration for simcards inventory

inc/dashboard/grid.class.php
Fix undefined variable CFG GLPI on dashboard
| Fixed tickets | Internal 21689
=> fix(dashboard): fix undefined variable: CFG_GLPI

inc/ticket.class.php
=> Fix lost of referenced project task on form reload; fixes #8680

inc/software.class.php
| Fixed tickets | #8622 
Seems broken since 9.3 (see 3f39085a762f6e9ff2ef314d50e98dd0ae3ff645).
=> Fix undefined variable on software merging; fixes #8622

inc/itilfollowup.class.php
=> Fix ticket reopening from collector; fixes #8768

inc/notificationtargetcertificate.class.php
=> Fix certificate notification wording; fixes #8578

inc/search.class.php
=> Remove nometa filters only on meta context; fixes #8789

inc/dashboard/provider.class.php
=> Fix tickets counts in dashboard; fixes #8782

inc/session.class.php
Add log event when user impersonate another
| Fixed tickets | internal 21684
=> feat(impersonate): ad log event

inc/toolbox.class.php
Fix new function introduced in https://github.com/glpi-project/glpi/pull/8764/.
=> Fix Toolbox::getAvailablesTabs()

inc/appliance.class.php
=> Add search option on appliances user and group

inc/problem.class.php, inc/ticket.class.php
Add probelm searchoption to ticket
| Fixed tickets | internal 21707
=> feat(ticket): add problem searchoption

inc/impact.class.php
=> Fix Impact tab on ITIL objects; fixes #8837

inc/html.class.php, inc/toolbox.class.php, tests/units/Html.php, tests/units/Toolbox.php
=> Fix <email> transformation in rich text

css/palettes/_darker.scss, css/styles.scss, inc/change.class.php, inc/commondbchild.class.php, inc/commondbtm.class.php, inc/commonitilobject.class.php, inc/commonitiltask.class.php, inc/dropdown.class.php, inc/features/usermention.class.php, inc/html.class.php, inc/itilfollowup.class.php, inc/itilsolution.class.php, inc/notification.class.php, inc/notificationtargetcommonitilobject.class.php, inc/problem.class.php, inc/ticket.class.php, install/empty_data.php, install/update_95_xx.php, install/update_95_xx/notifications.php, js/RichText/UserMention.js, tests/functionnal/Glpi/Features/UserMention.php
Add ability to mention users in ITIL objects.
Remaining work to do:
=> Add ability to mention users in ITIL objects

inc/features/usermention.class.php, tests/functionnal/Glpi/Features/UserMention.php
=> Fix user mentions update notification on PHP 7.x

tools/locale/update_mo.pl
=> Make mo compile script callable from anywhere

inc/document_item.class.php, inc/knowbaseitem.class.php
=> Show docs on kb selfservice

tools/deleteorphanlogscommand.class.php
Add new command to delete orphan log (from glpi_logs)
=> feat(console): add command to delete orphan log (from glpi_logs)

ajax/ticketassigninformation.php, css/includes/_dark.scss, css/includes/components/_tabs.scss, css/includes/components/itilobject/_actors.scss, css/includes/components/itilobject/_footer.scss, css/includes/components/itilobject/_layout.scss, css/includes/components/itilobject/_timeline.scss, inc/application/view/extension/userextension.class.php, inc/commonitilobject.class.php, inc/html.class.php, inc/ticket.class.php, js/common.js, templates/anonymous_helpdesk.html.twig, templates/asset_form.html.twig, templates/components/form/fields_macros.html.twig, templates/components/itilobject/actors.html.twig, templates/components/itilobject/answer.html.twig, templates/components/itilobject/form_followup.html.twig, templates/components/itilobject/form_solution.html.twig, templates/components/itilobject/form_task.html.twig, templates/components/itilobject/form_validation.html.twig, templates/components/itilobject/linked_tickets.html.twig, templates/components/itilobject/main_description.html.twig, templates/components/itilobject/timeline.html.twig
=> Fix twig cs

inc/change.class.php, inc/commondbtm.class.php, inc/commonglpi.class.php, inc/problem.class.php, inc/ticket.class.php
restore values on update if needed
| Fixed tickets | internal 21623
=> fix(core): restore values on update if needed

inc/toolbox.class.php, tests/units/Toolbox.php
#8852 was not enough, some valid URL are still blocked.
| Fixed tickets | !21783
=> Fix URL validation 2

composer.lock, front/imageformat.form.php, front/imageformat.php, front/imageresolution.form.php, front/imageresolution.php, inc/computer_item.class.php, inc/define.php, inc/devicecamera.class.php, inc/devicecameramodel.class.php, inc/dropdown.class.php, inc/imageformat.class.php, inc/imageresolution.class.php, inc/inventory/asset/camera.class.php, inc/inventory/asset/device.class.php, inc/inventory/asset/sensor.class.php, inc/inventory/inventory.class.php, inc/item_devicecamera.class.php, inc/item_devicecamera_imageformat.class.php, inc/item_devicecamera_imageresolution.class.php, inc/relation.constant.php, inc/ruleimportasset.class.php, install/mysql/glpi-empty.sql, install/update_95_xx.php, install/update_95_xx/cameras.php, tests/fixtures/inventory/phone_1.json, tests/functionnal/Glpi/Inventory/Assets/Camera.php, tests/functionnal/Glpi/Inventory/Assets/Sensor.php, tests/functionnal/Glpi/Inventory/Inventory.php
Add camera component
Camera is defined by 
=> Add camera component

js/kanban.js
=> Fix create column action in Kanban

inc/lock.class.php
=> Fix lock tab

inc/application/view/extension/userextension.class.php, templates/components/itilobject/timeline.html.twig
Re-add anonymous agent feature in new timeline UI
=> Anonymous support agents in timeline

templates/components/itilobject/form_followup.html.twig, templates/components/itilobject/form_solution.html.twig, templates/components/itilobject/form_task.html.twig, templates/components/itilobject/form_validation.html.twig
=> [Modern UI] Add missing ID fields for timeline forms

inc/toolbox.class.php
=> HtmLawed: allow "notes" scheme

inc/itilfollowup.class.php
=> Fix user mentions feature on helpdesk followup form

inc/dbutils.class.php
This feature displays the user's default group in a user's tooltip
=> Add default group in user tooltip information

inc/inventory/asset/virtualmachine.class.php, tests/fixtures/inventory/computer_2_partial_vms.json, tests/functionnal/Glpi/Inventory/Inventory.php
=> Test partial inventory on VMs

ajax/rack.php, inc/item_rack.class.php, js/rack.js
=> Don't allow modifying racks without update right

inc/plugin.class.php
Add missing Clean massive action for plugins following #7917.
=> Add clean massive action for plugins

inc/domain.class.php
=> Not translated string; closes #8972

inc/savedsearch.class.php
=> Add missing encoding for savedsearch notif name
