glpi-project/glpi

inc/location.class.php
Internal ref: 19508
Fix ajax pager in Location > Elements.
The total count was using the size of the iterator results
-> total was always equals to the number of results returned 
-> only one page displayed with no pagination
I've fixed it by adding a second DB request that count the real total.
=> Fix location pager

front/change.form.php, front/problem.form.php, front/ticket.form.php, inc/api.class.php, inc/commonitilobject.class.php, inc/document.class.php, inc/notificationeventmailing.class.php, inc/notificationtargetcommonitilobject.class.php, inc/transfer.class.php, tests/functionnal/Ticket.php
| Fixed tickets | #7059
Due to #6598, document items of followup and tasks are not directly attached to parent ITIL item directly anymore.
Maybe some other features have to be fixed, for instance notifications related to ITIL items, list of items related to a document, ....
=> Fix handling of ITIL documents

inc/search.class.php
maybeRecursive can return true for CommonDBChild objects because of their parents; but is_recursive field maybe missing in the table.
Seen this working on future features, it does not seems to be throwed currently from core; but I'm not 100% sure, and plugins may certainly be impacted.
=> maybeRecursive can return true for CommonDBChild objects

inc/projecttask.class.php
Internal ref: 19597
Recursive project tasks are not visible from sub-entities.
=> Fix recursive project task visibility

ajax/mailcollector.php
Remove additional backslashes when getting folder list from Office365 shared mailboxes.
| Fixed tickets | #7136
=> Remove additional backslashes.

inc/notification.class.php, inc/notification_notificationtemplate.class.php
Add capability to 
- add template to a notification 
- remove all templates defined from notification
for add : check if template already defined
for add : check if notification itemtype is equal to selected template itemtype
For add : Add template to notification if it is possible.
| Fixed tickets | internal 19544
=> Rework massiveactions for add or delete template from notification

inc/search.class.php
Executing a search request on ITILFollowups gives 40+ warnings and incorrect results because of a group_concat on the content fields (each results are empty except the first which contains ALL the data in his content fields).
I've fixed it by adding a check on the itemtype so the group_concat clause is only added when the source of the search is a `CommonITILObject` and also improved the SQL readability.
=> API: fix search requests on ITILFollowup

inc/ruleticket.class.php
Follow #5932, it may help to disable more actions like linking items to ticket or adding documents.
Adding assignee still trigger compute of take into account delay stat.
=> add date_mod criterion in RuleTicket

inc/impact.class.php
Allow dynamic URL like "icon.php?id=6" to be used in the impact graph.
| Fixed tickets | #7091
=> Impact - allow dynamic URL; fixes #7091

inc/dbmysql.class.php, tests/units/DB.php
I have at least two issues with current sql parsing:
- when an error occurs, it outputs the whole SQL file, this is **huge**
- when the last line of the file (engine etc part of the last table), the script does not fail. Install is OK, but the lat table is not created.
=> Improve install script

js/common.js
The "submit" input was replaced by a button in 9.5 so we need to update this selector.
=> Fix CTRL+enter for textareas

inc/api.class.php
While working on a plugin I wondered whether or not SQL_CALC_FOUNDS_ROWS was better than a count request since I remember seeing it in our API.
I found out that [SQL_CALC_FOUND_ROWS is slower and deprecated from MySQLl 8 onward.](https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_found-rows) so I guess it would be good to replace it (that's the only place where we use it).
=> Replace SQL_CALC_FOUNDS_ROWS by count

js/common.js
With the Select2 search function, when we search term "gt" (to find Wellington for example) and if GLPI is configured to display the completename
Select2 escapes ">" and "<" when occurences is find and display ```&gt;``` on result set because templateResult underline matches on text
This PR fix this 
| Fixed tickets | internal 19509
=> Fix markup diplay when term match with html entity

composer.json, composer.lock, inc/system/requirementsmanager.class.php
1. Fix some inconsistency in requirements (obsolete, duplicates, ...).
2. Prevent installation of polyfills that corresponds to a PHP version or an extension that is defined as mandatory in requirements check.
See https://php.watch/articles/composer-replace-polyfills for an explanaition about using "replace" feature of composer.
=> Fix inconsistency in requires and prevent install of useless polyfills

inc/auth.class.php, inc/mail/protocol/protocolinterface.class.php, inc/mailcollector.class.php, inc/toolbox.class.php, tests/bootstrap.php, tests/fixtures/plugins/tester/setup.php, tests/functionnal/Telemetry.php, tests/units/Toolbox.php
| Fixed tickets | #6895
Imap Oauth implementation requires a secret/token exchange between GLPI and tier providers and this part may be specific for each of them.
I propose to add a new hook that will give ability to plugins to specify a new "protocol" (e.g. "Google IMAP XOauth2") and corresponding classes to use.
Remaining work to do:
=> Add new hook to give ability to handle more mail protocols

inc/change.class.php, inc/problem.class.php
internal ref : 19694
Change and problem forms are not editable anymore due to bad logical operator usage
=> fix canupdate detection in change|problem form

css/marketplace.scss
On "installed plugins" marketplace view, some buttons may not be clickable as they are overlapped by card footer.
Before:
After:
=> Fix not clickable buttons on installed plugins page

bin/console, package.json, tools/build_glpi.sh, tools/make_release.sh, webpack.config.js
There are also some improvements:
- dependencies install now outputs colors of composer output
- building script has been moved apart so it can be used directly on an extracted tarball retrieved from Github (will be usefull for nightly builds and internal archive build)
=> Make release process compatible with GPLI 9.5

css/styles.scss, inc/html.class.php, inc/profile.class.php
Internal ref: 19652.
After creating a new helpdesk profile, the life cycle tabs looks like everything is allowed:
After any update, the rights reset to the correct "default" state:
To fix this I've added a check in the prepareInputForAdd in order to initialize the life cycle correctly when creating a new helpdesk profile.
No modification needed for central profiles, they already work as expected.
On the previous screenshot, only 2 out of the 9 checkbox are clickable.
This is very confusing for the users as we give no UI feedback for read-only checkboxes.
After this change any read-only checkbox will display the "not-allowed" cursor when hovered:
| Tests pass?   | …
=> Fix default rights for self-service profiles

inc/rule.class.php
It's currently impossible to create or delete `Rule` object through the API as it use the `config` right name which only support `READ` and `UPDATE` rights :
=> Allow Rule creation and suppresion through API

inc/change.class.php, inc/commonitilobject.class.php, inc/problem.class.php, inc/ticket.class.php
Internal ref 19703
This prevent change of entity when editing changes/problems.
`$options` passed to `showFormHeader` contains a `entities_id` (set by `getDefaultValues`) key who force the change of entities of change/problem
Ticket doesn't have the issue because it had a custom header and doesn't rely on standard `showFormHeader` (it it was the case, Ticket would have the same issue as the `getDefaultValues` is also present.
I moved (and adapt a little)  the custom header of Ticket into a CommonItilObject::showFormHeader to share the same base code between the 3 itemtypes (and fix the issues)
The else part on the end prevent display hazard …
=> factorize showFormHeader for itil classes

.circleci/config.yml
This reverts commit 489cacc1b2231bd4d775938708db441602ef41c4.
=> Revert "Native sodium extension is broken on circle; disable it."

inc/search.class.php
Improve filter wording for numeric values and correct the behaviour of "not contains".
| Tests pass?   | ?
| Fixed tickets | #6917
=> Improve filter wording for numeric values and correct the behaviour of "not contains"

inc/commonitilobject.class.php, inc/ticket.class.php, tests/functionnal/Ticket.php
Internal ref: 19613.
Prevent `takeintoaccount_delay_stat` from being computed on update if the ticket status is still `INCOMING`.
Currently, any update by a support agent on a ticket will trigger the `takeintoaccount_delay_stat` computation.
This can result in a ticket still in `INCOMING` status but already taken into account (the TTO will be displayed as still running but no progression bar is shown).
=> Do not compute takeintoaccount_delay_stat if ticket is new

.github/workflows/ci.yml
Test suite results: https://github.com/cedric-anne/glpi/runs/663538123?check_suite_focus=true
Image is built using MariaDB 10.5 beta2.
It may be merged later, I just wanted to check compatibility with this new version prior to GLPI 9.5 release.
=> Run test suite on MariaDB 10.5

.github/workflows/ci.yml
This configuration, once merged, should enable GithubAction CI test suite even for PR created from a fork repository.
=> Run Github CI job on any PR, even from a fork

inc/user.class.php, tests/LDAP/AuthLdap.php
Internal ref: 19550.
When synchronizing an user, the value used to search for his manager was escaped twice.
If the manager DN contained any escaped chars like `\` it would then never be found.
First escaping in `User::getFromLDAP()`  
```php
$val = Toolbox::addslashes_deep($val);
```
Second escaping in `User::getIdByField()`
```php
$iterator = $DB->request([
'SELECT' => 'id',
'FROM'   => self::getTable(),
'WHERE'  => [$field => addslashes($value)]
]);
```
I've removed the second escaping for this specific case and kept it as a default parameter for the function since it is used in others places that may need the escaping.
----
Concrete example:
Manager DN to search for: `cn=Clairembault\2C Adrien,cn=abcd,dc=nodomain`
-> `\2C` is an encoded coma here, the displayed CN in the LDAP is …
=> User synchro: remove double escaping for manager field

.gitignore, inc/toolbox.class.php, tests/units/Toolbox.php
Some passwords like the LDAP bind password are allowed to be blank and may not be encrypted in that case so the DB values are still null or empty. When trying to decrypt them, a sodium exception is raised. The null or empty string value can just be returned instead.
=> Fix sodium decrypt for blank values

inc/extravisibilitycriteria.class.php, inc/impact.class.php, inc/knowbaseitem.class.php, inc/project.class.php, inc/reminder.class.php, inc/rssfeed.class.php, inc/savedsearch.class.php, js/impact.js
New visibility restrictions:
Graph context menu (right click on node)
* Do not display "go to" contextual menu action for an item that the user is not allowed to read
Add assets panel
* Do not display itemtypes that the user is not allowed to read
* If an itemtype have a `getVisibilityCriteria` method, use it to only show items that match the defined criterias
=> Impact visibility restrictions

inc/impact.class.php
If a plugin is used into Analysis Impact & is not activated : 
```
[2020-05-15 06:53:36] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'PluginWebapplicationsWebapplication' not found in C:\wamp64\www\glpi95\inc\impact.class.php at line 1130
Backtrace :
inc\impact.class.php:1147                          Impact::buildGraphFromNode()
inc\impact.class.php:1052                          Impact::buildGraphFromNode()
inc\impact.class.php:154                           Impact::buildGraph()
inc\commonglpi.class.php:622                       Impact::displayTabContentForItem()
ajax\common.tabs.php:92 …
```
=> Fix for see AnalysisImpact without loaded plugin

inc/notification.class.php, inc/notificationevent.class.php, inc/notificationmailingsetting.class.php, inc/notificationtarget.class.php, inc/notificationtargetticket.class.php, install/empty_data.php, install/mysql/glpi-empty.sql, install/update_94_95.php
Internal ref: 17298.
* Add a new configuration option for notification to indicate whether or not they should allow a response ('allow_response' param).
* If a notification doesn't expect a response, the `"To answer by email, write above this line"` headers and footers won't be printed in the email
* Add a new general configuration for notifications (no reply address)
* If a notification doesn't expect a response AND a no reply address is configured, use it as the sender address for the notification.
=> No reply configuration for email notifications

inc/item_devicesimcard.class.php, inc/search.class.php
SQL request for reservation fail in 9.5:
It seems that a base request with a .name is used to make multiple union queries with str_replace without checking if the new table have a name field.
Using getNameField + adding a name field to item_simcards seems to fix it.
Maybe we should have a global unit test that check the validity of each getNameField ?
=> Fix reservations namefield

inc/commondbtm.class.php, inc/contract.class.php, inc/projectcost.class.php, inc/projecttask.class.php, tests/functionnal/CommonDBTM.php
Internal ref: 19597.
Situation:
Create a project template with a task in the `Root` entity + subentities.
Switch to a sub entity (`Root > A`).
Create a project using the previous template.
-> the project will be in `Root > A` entity
-> the task will be in `Root` entity
Fixed this by adding a new check in some cloneXXXX methods:
If the entity id of the cloned item is not allowed for the current user -> remplace it by the entity of its parent item.
So in our previous case (task) we can't see `Root` entity so we fall back to the parent (project) entity which is `Root > A`.
=> Fix template entity

ajax/planning.php, css/styles.scss, inc/planning.class.php, js/planning.js, tests/functionnal/Planning.php
internal ref 19826
Current UX for cloning event (maintain [Shift] key while draggin' event) is bugged and doesn't work all the time.
So i re-did with a simple context menu. It's also more discoverable.
All planning views i know (zimbra, google calendar) use context menu for "fast actions".
=> planning: redo clone events ux with a context menu

CHANGELOG.md, inc/define.php, inc/monitor.class.php
Some people use Monitors for any display device such as TVs and I have found a few monitors for digital signage purposes that can have a network port (Seems to be for email alerts, chaining, etc).
https://glpi.userecho.com/communities/1/topics/1816-network-ports-on-monitors
=> Network ports on Monitors

inc/config.class.php, tests/functionnal/Config.php
- Added support for hyphen in language ID;
- Added test for language ID with hyphen;
| Tests pass?   | **not tested**
| Fixed tickets | fixed #7302 
I tested the code and it works. I did not run the tests.
=> Wrong/default language when using 'Other authentication send in the HTTP request' - fixed #7302

inc/impact.class.php
Fix a (harmless) warning when running 9.5 update for the first time and the new impact conf does not exist yet. 
=> Fix warning during 9.5 update

inc/dashboard/grid.class.php
Debug information of dashboard cards were stored in cache, and so were served to all users, even thoose having not debug mode enabled.
=> Do not cache dashboard cards debug info

CHANGELOG.md, inc/console/system/checkstatuscommand.class.php, inc/system/status/statuschecker.class.php, status.php, tests/functionnal/Glpi/System/Status/StatusChecker.php
| Fixed tickets | #5922
Added ability to get JSON format for status endpoint in addition to the "legacy" plain-text format. Allows for providing more information to monitoring systems/scripts (I added the DB replication delay as an example).
To provide BC, the plain-text format is the default and is output in the same way it was before. Extra information like the replication delay is not shown.
Fixed #5922 while I was at it (I don't have an IMAP server anymore for dev. Someone will have to test this to be sure. Wasn't sure if it mattered if I used the host from the DB or connection string.).
I think eventually this endpoint should be added …
=> Enhance Status Endpoint

inc/mailcollector.class.php, inc/notificationevent.class.php, inc/notificationeventabstract.class.php, inc/notificationeventinterface.class.php, inc/notificationtarget.class.php, inc/notificationtargetcommonitilobject.class.php, inc/notificationtargetticket.class.php
Internal ref: 19947.
The setting 'notification_to_myself' allow a user to enable/disable notifications triggered by his own events.
However, this setting is ignored when actions are handled by the mailgate since the notification system need a connected user to check this setting.
This was fixed by allowing to specify an additional "emitter" parameter to the notification so it can use it instead of the current connected user (= use the sender of the email for mailgate).
This fix should be good enough for now, but if there is a notification remodel in the future it should maybe use a concrete notion of emitter/source and never rely on the current user.
| Tests pass? …
=> Fix 'notification_to_myself' setting for mailgate

inc/mailcollector.class.php
Internal ref: 20025.
The additional anonymous users in the TOs and CCs headers were never added even if ticket creation from anonymous users was enabled in the config.
=> Mailgate: fix anonymous observers

tools/build_glpi.sh, tools/make_release.sh
Fixes `readlink: unrecognized option: canonicalize`.
See https://github.com/cedric-anne/glpi/actions/runs/124676457 which contains a failing build on 9.5/bugfixes and a working build with current fix.
=> Fix build script on Alpine Linux

inc/console/database/installcommand.class.php, inc/toolbox.class.php
If a DB config file was already existing, it was loading by initial includes, and was not reloaded by `Toolbox::createSchema()` (it cannot be reloaded as it is a class definition).
Result is that DB was (re)installed using previously existing configuration when using --force param in db:install command, althought the config file was rewritten with new config values.
=> Fix behavior of --force param in install command

.github/workflows/nightly_build.yml
Build GLPI nightly directly from Github Actions, and using CI docker images which provides an environment compatible with GLPI (required at least to be able to install dependencies using composer, as we need some of them during the build process).
TODO:
=> Nightly build GLPI using Github Actions

inc/commonitilobject.class.php, inc/notificationtargetcommonitilobject.class.php, inc/search.class.php, inc/ticket.class.php
Following #7015.
Internal ref: 20024.
A little improvement of the "Anonymous helpdesk" feature.
Instead of checking the current entity of the user, we now check the entity of the ticket.
Example: 
We have two entities A and B (B being a sub-entity of A).
A -> Anonymous helpdesk **disabled**
B -> Anonymous helpdesk **enabled**
Before the change, a user on the A entity will be able to see the names of all the tech on any tickets from A or B.
After the change, this same user will still see the technicians' names for tickets on A but not for tickets on B.
=> Anonymous helpdesk: improve entity check

inc/mailcollector.class.php, inc/notificationevent.class.php, inc/notificationtarget.class.php
Following #7360.
One case was not covered by the previous changes: anonymous users.
Since they have no real account we must use:
- the global configuration settings for $notify_me
- theirs emais instead of theirs IDs when comparing with a potential email target
=> Fix 'notification_to_myself' setting for mailgate 2

inc/commonitilobject.class.php, inc/document_item.class.php
Fix a few bugs and missing cases on ticket timeline when anonymous helpdesk is enabled:
- Anonymize 'last edit by'  and the user link at the bottom right of tasks
- Handle better different timeline items (solution, followup, document and tasks).
=> Fix anonymous helpdesk timeline

inc/commonitilobject.class.php, js/common.js
| Fixed tickets | #7389
fixes #7389
Remove tracking on CommonITILObject create forms
- The migration of data is already handled here and the warning is useless when some fields cause the form to reload on purpose.
Fix issue with false data-track-changes. False values become empty not false so the wrong value was tested.
Drop redundant Select2 listener
- The select change event is already fired when using Select2. Event call order doesn't seem to matter here (change event should be fired after select2).
=> Fix ITILObject create form change tracking

inc/holiday.class.php
| Fixed tickets | #7227
On 9.5 branch, unit tests has been added on more objects. Holidays was explicitely excluded, activating it gives the issue in tests, current fix fixes it :)
=> Fix holiday transfer; closes #7227

package-lock.json, package.json, tools/RoboFile.php, webpack.config.js
| Fixed tickets | #7393
`consolidation/robo` JS minification task is based on `patchwork/jsqueeze` library which is not maintained since 4 years. It is incompatible with some new JS syntax, like `const {ReadableWebToNodeStream} = require('readable-web-to-node-stream');` used in `file-type` dependency. So I replaced it by `terser` minification library.
I also prevent creation of bundle from minified files (a dev problem only).
=> Fix JS minification issues; fixes #7393

inc/projecttaskteam.class.php
Internal ref: 20148.
Affecting a new member on a project task should trigger an update notification.
=> Fix missing notification when adding a member to a project task

inc/html.class.php
| Fixed tickets | #6953 
In ITIL timeline, method is used to display rich text outside a textarea (`echo Html::setRichTextContent('', $content, '', true);`). As `$name` is empty, it instanciate a phantom tinyMCE instance and plugs event on it, which leads to JS errors.
=> Do not create tinyMCE instance if no textarea is defined; fixes #6953

inc/api.class.php
=> Fix missing escaping in API search queries; fixes #7414

inc/planning.class.php
| Fixed tickets | #7284 
Dues to latests jQuery update, HTML was mixed up and this piece of JS code was not working as expected: https://github.com/glpi-project/glpi/blob/9.5/bugfixes/js/planning.js#L727
=> Fix planning filters; fixes #7284

.github/workflows/ci.yml
It is not possible to run tests on GH actions on branch other than master and */bugfixes. I propose to add branches prefixed with `feature/` we frequently use, and also with `fix/` for bugfixes (less important).
Goal is I can get GH actions running on my own fork when I push to a feature branch, without having to open a pull request.
=> Build for feature and fix branches

composer.json, composer.lock
Since #7429 , `patchwork/jsqueeze` is not used anymore.
=> Remove useless patchwork/jsqueeze lib

composer.json, composer.lock
`wapmorgan/unified-archive` 1.0.0 release is now available. This release is not so different from 0.2.0, but is officially ready for production.
=> Upgrade wapmorgan/unified-archive to version 1.0.0

inc/console/application.class.php
=> Prevent exception on install command if mysqli is missing; fixes #7473

inc/calendar.class.php, inc/commonitilobject.class.php, inc/levelagreement.class.php, inc/ticket.class.php
Internal id: 19766
Crontask `closeticket` wass running into an infinite loop if entity uses a calendar having no working day.
=> Prevent usage of calendars having no working days

inc/session.class.php
| Fixed tickets | #7399 
Languages loading fails into a fatal error if `intl` extension is missing. Problem is that languages may be load before requirements checks done on installation/update process.
This PR will prevent the fatal error to be thrown, but will still show user that requirement is missing :
=> Prevent fatal error on installation process; fixes #7399

inc/dropdown.class.php, tests/functionnal/Dropdown.php
| Fixed tickets | #6928 
This will enable searching on ids inside dropdowns (but only if ids are displayed).
Example:
=> Search inside displayed ids on dropdowns; closes #6928

inc/toolbox.class.php, tests/units/Toolbox.php
With #7476 and #7477, it is not possible anymore to define a port on base URLs. This PR fixes this.
=> Permit usage of port in base URL

inc/telemetry.class.php
This will prevent the "telemetry" cron task to stay stuck on "running" when there is a problem with telemetry server.
=> Prevent blocking of telemetry cron on cURL failure

inc/itilsolution.class.php, tests/functionnal/ITILSolution.php
Internal ref: 19662.
Items_id and itemtype were ignored after the first addition
This would try to add both solution to ticket 1 and thus fail:
```php
$solution = new ITILSolution();
$solution->add([
'itemtype' => 'Ticket',
'items_id' => 1,
'content' => "xxxxxx"
]);
$solution->add([
'itemtype' => 'Ticket',
'items_id' => 2,
'content' => "xxxxxx"
]);
```
=> Fix multiple solutions

tools/make_release.sh
Fix #7292, was merged into refactored 9.5 script, resulting in a cleaning inside the source directory instead of the target one.
#7307 does the cleaning job right.
=> Fix removal of source dir files in release script; see #7292 and #7307

install/update_94_95.php
This will prevent undefined index when accessing `$CFG_GLPI['glpinetwork_registration_key']` in case key has not already been set, even if there is no code doing this for the moment.
=> Add GLPI Network registration key config entry in update

front/event.php
The item should be Glpi\\Event (Logs) and not Log (Historical)
=> Fix wrong Event breadcrumbs

.circleci/config.yml, .github/workflows/ci.yml, composer.json
With previous pattern, any directory named `config`, `files`, `lib`, `marketplace`, ... was not checked, so classes inside `marketplace` namespace were not checked.
As `ignore` pattern uses absolute paths, the only way to be sure to exclude directories that are at the root of the project is to include `pwd` in exclusion pattern.
=> Fix ignore pattern of CS tasks

inc/dashboard/grid.class.php
fixes #7510 
| Fixed tickets | #7510 
Non-existent title column was causing the dashboards to always show the key. The title is stored in 'name' instead.
Something I wasn't sure of, was if the key is supposed to be regenerated when the title is saved/changed. If not, would it be better to make it unique? It looks like dashboards are global now, but if private dashboards get added or dashboards available to specific groups, there could be key/naming conflicts. For example, user 1 names a dashboard "My Dashboard" and user 2 tries to make a dashboard named "My Dashboard" as well. Both have the key "my-dashboard".
=> Fix displayed dashboard title

inc/change_problem.class.php, inc/change_ticket.class.php, inc/commonitilobject.class.php, inc/problem_ticket.class.php
Internal ref: 20255.
Standardize Ticket <-> Change <-> Problem relations.
A resolved or closed status on a object imply a read-only state.
This was already the case for some of these relations, now it's the same for all of them.
=> Do no display closed changes when linking to other itil objects

inc/knowbaseitem.class.php
Fix SQL errors on search solution into KB from ticket
```
[2020-07-03 10:45:06] glpisqllog.ERROR: DBmysql::query() in C:\wamp64\www\glpi\inc\dbmysql.class.php line 305
SQL: SELECT COUNT(*) AS cpt FROM `glpi_knowbaseitems` LEFT JOIN `glpi_knowbaseitems_users` ON (`glpi_knowbaseitems_users`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN `glpi_groups_knowbaseitems` ON (`glpi_groups_knowbaseitems`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN `glpi_knowbaseitems_profiles` ON (`glpi_knowbaseitems_profiles`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN …
```
=> Fix SQL errors on search solution into KB from ticket

inc/group.class.php
fixes #6967
| Fixed tickets | #6967 
Fix massive action form dropdown for moving group item members so that an item can only be moved into groups that allow items. There was an issue were any group that could be responsible for assets would be shown event if it could not contain items.
=> Fix group member move selections

inc/commonitilobject.class.php
| Fixed tickets | #7413 
When use getAllTypesForHelpdesk function on a plugin hook.php file, there are php warning for existence of $_SESSION["glpiactiveprofile"].
=> Avoid Plugin Error on use getAllTypesForHelpdesk function

front/problem_user.form.php
When updating a problem actor followup email, popup stay blank when clicking on submit button.
=> Fix form refresh after problem actor email update

inc/commondbtm.class.php, inc/dbutils.class.php, inc/search.class.php, tests/functionnal/Search.php
| Fixed tickets | #7514 
since 2ee3984be7b7374f7201a7a13a2273b953e7a408, calling `getTableForItem` will work in every case; `::getTable` requires an existing class.
Current fix is a partial revert of that commit.
Note: we would need unit tests on 'AllAsset' :-/
=> Fix global search; closes #7514

inc/commonitilactor.class.php
| Fixed tickets | #7596
#7600 was not a correct fix, as forcing `alternative_email` will result in not taking care of user default email update.
Keeping this value blank will result in having the email computed when notification is sent, which seems more logical to me.
With this PR, `prepareInputForUpdate` will act as `prepareInputForAdd`.
=> ITIL actor alternative email should not be forced; fixes #7596

.circleci/config.yml, .github/workflows/ci.yml
MariaDB 10.5 stable version has been released, so we should now run tests using it.
Also, it seems a bit overkill to test all supported DB versions. Testing on the lowest and the highest versions should be enough to detect main incompatibilities.
=> Test on MariaDB 10.5 and review DB matrix

inc/cartridgeitem.class.php, inc/commondbtm.class.php, inc/computer.class.php, inc/consumableitem.class.php, inc/enclosure.class.php, inc/monitor.class.php, inc/networkequipment.class.php, inc/pdu.class.php, inc/peripheral.class.php, inc/phone.class.php, inc/printer.class.php, inc/rack.class.php, inc/software.class.php
Internal ref: 20271.
Add missing 'is_recursive' search option to most assets (it was only set in printer, software and network equipment).
This search options is very useful for massive actions.
=> Add missing 'is_recursive' search option to assets

inc/crontasklog.class.php
| Fixed tickets | #7633
1. `$id` was not passed to delete params.
2. `rowCount` is not available on a delete operation.
=> Fix exception on logs crontask; fixes #7633

inc/toolbox.class.php
| Fixed tickets | #7645
It may happen that stored data in DB was crypted with another key than the current one. In this case, throwing an exception seems too much, as it may prevent to display the form that can be used to fix the stored value.
=> Do not throw an axception when sodium decrypt fails; see #7645

inc/mailcollector.class.php, tests/emails-tests/09-reply-to-tech.eml, tests/emails-tests/10-missing-content-transfer-encoding.eml, tests/imap/MailCollector.php
| Fixed tickets | #7643 , #7649 
- Prevent exception on addresses parsing; fixes #7643
- Correctly fetch additionnal headers that may be used in rules
- Fix exclusion of mailer-daemon/postmaster
- Prevent exception when "Content-Transfer-Encoding" is not set; fixes #7649
=> Fix mail parsing in collector

css/dashboard.scss
| Fixed tickets | internal ref 20297
Before:
After:
=> overflow with ellipis long texts on y axis in horizontal bars

inc/project.class.php, js/kanban.js
| Fixed tickets | #7608 
Fix issue where adding a second item (and possibly after waiting for a Kanban refresh) in the Kanban would open the new Project form instead of adding the item automatically. Issue was caused by the submit event listener not being set properly after the initial Kanban refresh.
=> Fix Kanban add item action

inc/commondbvisible.class.php
The itemtype + "s_id" is not always the foreign key. For plugins we are supposed to use 'plugins_myplugin_itemtypes_id' not 'mypluginitemtypes_id.
With this fix, plugin classes can now extend CommonDBVisible and use the visibility form.
Tested Knowledgebase to ensure that is still functioned.
=> Fix CommonDBVisible showVisibility for plugin types

inc/change.class.php, inc/commonitilobject.class.php, inc/problem.class.php
| Fixed tickets | #7635
In GLPI 9.5, `showFormHeader()` method has been overrided in `CommonITILObject`, but its usage outside main form was not taken into account.
Result is that Change/Problem Analysis/Plans forms, that are not defining the `template_preview` had no form HTML tag.
Quick fix is to call the base method in these forms.
=> Fix Change/Problem Analysis/Plans forms; fixes #7635

inc/networkport.class.php
| Fixed tickets | #7651 
Instead of showing "eth0" for example, show "eth0 on HQCoreSwitch". The parent item is shown as a field in the form, but I think it is intuitive to have it shown in the form header as well especially since it is visible regardless of which tab you are looking at.
=> Show parent device in form header for network ports

inc/search.class.php
| Fixed tickets | #7670
Replaced with a `<br>` for now, I don't really know what is expected here.
=> Replace carriage return in slk exports; closes #7670

inc/mailcollector.class.php, tests/emails-tests/11-missing-contenttype.eml, tests/imap/MailCollector.php
=> Handle missing contenttype in collected emails

inc/based_config.php, inc/dbconnection.class.php, inc/dbmysql.class.php, inc/system/requirement/mysqlimysqlnd.class.php, inc/system/requirementsmanager.class.php, tests/units/Glpi/System/Requirement/MysqliMysqlnd.php
| Fixed tickets | see #7675
Usage of `MYSQLI_OPT_INT_AND_FLOAT_NATIVE` seems now required, as we cannot ensure that everything works fine without this option.
`MYSQLI_OPT_INT_AND_FLOAT_NATIVE` option is only available when mysqli uses mysqlnd driver.
=> Ensure mysqlnd is the driver used by mysqli; see #7675

inc/mailcollector.class.php, tests/emails-tests/12-missing-to.eml, tests/imap/MailCollector.php
=> Handle missing 'to' email header

inc/mailcollector.class.php
Calling `Mailcollector::connect()` can throw many exception types (due to a problem connection problem, or due to an invalid encryption key). As GLPI does not handle correctly exception (i.e. it results in a blank page), we should catch all of them an display/log an error message.
=> Prevent exception on maillcollector connection

.circleci/config.yml, .eslintrc.json, .github/workflows/ci.yml, webpack.config.js
With IE support officially dropped, all remaining browsers support at least ECMAScript 2015 (ES6) which adds a ton of new features to JS.
I also added node support to fix an error in PHPStorm where it would not recognize 'require' in the webpack config.
=> Bump ECMAScript to 2015

inc/commonitiltask.class.php, tests/functionnal/TicketTask.php
=> [9.4] Prevent creation of a task having an empty content; fixes #7737

inc/api/api.class.php
=> Fix right error when using 'with_document' in API

inc/define.php, tests/bootstrap.php
| Fixed tickets | internal ref 20251
The current behavior is not understandable for users.
I suggest to have only VEVENT component (calendar one) and explain to advanced user they can have todo or memo in their client from glpi planning.
=> change default caldav components used by our caldav server

front/user.form.php
| Fixed tickets | #7735 
`name` field check is already done on `User::prepareInputForAdd()` method.
=> Fix error message when creating user with an empty name; fixes #7735

inc/toolbox.class.php
| Fixed tickets | #7751
This check is similar to the one used in footer (see https://github.com/glpi-project/glpi/blob/9.5/bugfixes/inc/html.class.php#L1760).
=> Check new version using GLPI_VERSION constant; fixes #7751

inc/itilfollowup.class.php
| Fixed tickets | https://forum.glpi-project.org/viewtopic.php?id=278917
sql error:
```log
SQL Error "1052": Column 'itemtype' in where clause is ambiguous in query "SELECT DISTINCT `glpi_itilfollowups`.`id` AS id, 'xxxx' AS currentuser, `glpi_itilfollowups`.`content` AS `ITEM_ITILFollowup_1`,   COUNT(DISTINCT `glpi_documents_items`.`id`) AS `ITEM_ITILFollowup_119`, `glpi_itilfollowups`.`itemtype` AS `ITEM_ITILFollowup_6` FROM `glpi_itilfollowups` LEFT JOIN `glpi_documents_items` ON (`glpi_itilfollowups`.`id` = `glpi_documents_items`.`items_id` AND `glpi_documents_items`.`itemtype` = 'ITILFollowup')  WHERE `glpi_itilfollowups`.`is_private` IN …
```
=> use a clear statement on itilfollowups SQL where

inc/glpikey.class.php
Call to `GLPIKey::getLegacyKey()` is deprecated and, in case of an installation, this call is useless as result will not be used.
=> Prevent deprecation notice on installation

inc/commondbtm.class.php
When using a template, the `add` method was not setting `$fields` property with created object values, so redirection to created object was based on template ID as fields were set by `$this->getFromDB($id_to_clone)`.
To reproduce:
1) Set "Go to created item after creation" to "yes".
2) Create a computer from a template.
-> You should be redirected to the created object (without this fix you are redirected to the template itself).
=> Fix redirect to item created from a template

inc/marketplace/api/plugins.class.php
=> Fix net::ERR_RESPONSE_HEADERS_TOO_BIG when downloading huge plugin

inc/mailcollector.class.php, tests/emails-tests/00-unicode-smileys.eml, tests/emails-tests/01-inline-images.eml, tests/emails-tests/13-koi8-r-encoded-body.eml, tests/emails-tests/14-windows-1251-encoded-body.eml, tests/emails-tests/15-image-with-no-content-disposition.eml, tests/emails-tests/16-no-subject.eml, tests/imap/MailCollector.php
| Fixed tickets | #7709, #7787, #7790 
For #7709, some fixes were made on GLPI 9.4 in #4844 to fix encoding issues. I tried to reproduced the same behavior.
I also refactored a little the test suite to make it easier to update.
=> Fix multiple collector issues; fixes #7709, #7787 and #7790

composer.json, composer.lock, inc/auth.class.php, inc/mail/protocol/protocolinterface.class.php, inc/mailcollector.class.php, tests/imap/Toolbox.php
| Fixed tickets | #7693 
laminas/mail 2.12 will add support of `novalidatecert` option.
Not yet released, will require to update composer files.
=> Fix usage of novalidatecert IMAP/POP3 param; fixes #7693

inc/rulecollection.class.php
feor resold resolved :
glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /home/dev_glpi/public_html/inc/toolbox.class.php line 683
*** PHP Warning(2): mysqli::query(): Empty query
Backtrace :
:
inc/dbmysql.class.php:181                          mysqli->query()
inc/rulecollection.class.php:773                   DBmysql->query()
=> correction Empty query in function deleteRuleOrder

inc/ruleright.class.php, inc/user.class.php, tests/LDAP/AuthLdap.php
Internal ref: 20162.
Add an new action for authorizations assignment rules that link a group to the user.
=> RuleRight: link specific group

inc/toolbox.class.php
While troubleshooting a document issue, I noticed one of the plugins I had installed added some data to the output buffer when it was initialized and thereby corrupted any sent files. It would be good for GLPI to handle clearing the output buffer before sending files. No headers or data should be buffered before the Toolbox::sendFile function.
=> Clear output buffer before sending files

inc/application/errorhandler.class.php
| Fixed tickets | #7823
Don't show debug messages (HTML elements) in API responses because it breaks response parsing.
=> Don't show debug messages in API responses

inc/transfer.class.php, tests/functionnal/Computer.php
| Fixed tickets | #7864
It seems that the `'NOT'` was unintentionally removed during a merge operation.
=> Fix transfer of items softwares; fixes #7864

inc/notificationtargetsavedsearch_alert.class.php
Internal ref: 20507.
Class case was incorrect, this had some unexpected effects like broken hooks for the collaborative tools plugin.
The plugin is iterating on `$CFG_GLPI['notificationtemplates_types']` and adding hooks for each items types.
In `$CFG_GLPI['notificationtemplates_types']`, the type is `SavedSearch_Alert` so the hook would be set to `NotificationTargetSavedSearch_Alert` and never work since the real class was `NotificationTargetsavedSearch_Alert`.
=> Fix class name case

inc/console/database/updatecommand.class.php, inc/define.php, inc/update.class.php, install/update_94_95.php, install/update_951_952.php
Inline image migration to glpi_documents_items was not working as expected, only the first image of each item was migrated.
This was cause by the use of preg_match (stop at first match) instead of preg_match_all.
These changes fix the migration process and move it to 9.5.2.
=> Fix inline images migration (Document_Item)

inc/toolbox.class.php, tests/units/Toolbox.php
| Fixed tickets | #7848 
I think `SodiumException: public nonce size should be SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES bytes` is mainly related to calls to `Toolbox::sodiumDecrypt()` method passing a values that has not be crypted using sodium functions.
If value is shorter than 24 bytes, the nonce will not matches  `SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES` length, and this an exception will be trigerred.
=> Prevent exception on sodium decrypt; fixes #7848

inc/glpikey.class.php
| Fixed tickets | #7848
#7782 introduces an error when a migrated field is `null`. `null` values migration is useless, as it is not crypted.
=> Fix migration of encrypted data; see #7848

inc/define.php, install/empty_data.php, install/update_951_952.php, tests/functionnal/DbUtils.php
| Fixed tickets | #7835 
1. `Domain::DomainsAlert` crontask was not registered.
2. `Domain` was not part of `$CFG_GLPI["notificationtemplates_types"]`.
=> Fix Domain alerts

inc/item_softwarelicense.class.php
| Fixed tickets | #7853 
`Dropdown::showItemTypes()` expects a list of itemtypes to build its key/values.
In english, it was almost working as many itemtypes has a label that equals classname (i.e. 'Computer::getTypeName(1) == "Computer"', 'Monitor::getTypeName(1) == "Monitor"'), but in other languages, list was empty as passed values were not corresponding to valid itemtypes.
=> Fix software license items form; fixes #7853

inc/notificationeventmailing.class.php
| Fixed tickets | #7840 
`CommonITILObject::getAssociatedDocumentsCriteria()` was checking for session rights before inclusion of followups and solutions documents in notifications. As notifications are handled by a crontask, we cannot rely on session.
I added the `$bypass_rights = true` parameter in order to include followups and solution documents without checking rights. Even if it looks like a security bypass, it only reproduces what was done in GLPI 9.4 when documents were directly attached to the ticket.
Alternative solution would be to be able to be able to know the user_id related to the notification beiing sent (it is not stored …
=> Include all ITIL objects related documents in notifications; fixes #7840

inc/caldav/traits/vobjectconvertertrait.class.php, inc/commonitiltask.class.php, inc/planningexternalevent.class.php, inc/projecttask.class.php, inc/reminder.class.php
| Fixed tickets | Internal id. 20251
When tasks as handled as VEVENT by CalDAV server, any update coming from CalDAV client was reseting their status to 0 (information).
=> Fix status update of tasks served as VEVENT on CalDAV

inc/mailcollector.class.php, tests/emails-tests/17-malformed-email.eml, tests/imap/MailCollector.php
Mails that trigger an exception will not block anymore the mailgate cron. They will be handled as `NotImportedEmail` with a `FAILED_OPERATION` status.
=> Prevent mail import failure to break collector

inc/link.class.php
| Fixed tickets | #7915 
`joinparam` conditions are still based on SQL string.
=> Fix external links search option; fixes #7915

css/dashboard.scss
This PR fix height of mini dashoard which overlaps ticket search form
Fix #7867 
| Fixed tickets | #7867
=> fix(ui): fix mini dashboard CSS

inc/ipnetwork.class.php
Internal ref: 20133.
`$network->getAddress()` and `$network->getNetmask()` can both return `false` on invalid values but the current code always expect success.
These changes avoid fatal errors if one of the above return `false`.
=> Add check for invalid address or netmask

inc/glpikey.class.php, inc/toolbox.class.php, tests/units/Toolbox.php
1. `E_USER_ERROR` error level result in script exiting (it is a fatal error).
With `E_USER_ERROR`:
With `E_USER_WARNING`:
2. Old key was not fetch before its replacement, so migration was corrupting all existing passwords.
=> Prevent failure of "glpi:security:change_key" command

inc/toolbox.class.php, tests/units/Toolbox.php
Calling `Toolbox::log();` with a `notice` level triggers a `RuntimeException` in unit test context.
Directly using `trigger_error` will output almost the same trace (thanks to the GLPI error handling refactored in 9.5), and would give ability to keep some tests on deprecated usages.
Tests that does not "catch" errors will still fails with this kind of message:
=> Add ability to test deprecations

js/log_filters.js
The jquery filter meant to catch `select2:unselecting` events was not working properly.
For example, when removing any filters from the "Users", "Fields" or "Update" dropdowns of the log page, options were "stuck" in the top left corner:
These changes fixes this by using DOM event delegation.
=> Fix js filter (select2:unselecting)

inc/ajax.class.php
With GLPI 9.5.1 and split layout,
When we diplayeds software from computer, if we change display (number of items), scroolbar is break.
this RP prevent this.
Explaination : 
```reloadtab``` function unbin scroll to prevent ifinite scroll to top, by using a DOM selector with attr ```[aria-expanded=true]```  which no longuer exist
```js
$('#tabs$rand .ui-tabs-panel[aria-expanded=true]').unbind('scroll');
```
HTML is constructed like this
```html
<div id="ui-id-27" aria-live="polite" aria-labelledby="ui-id-26" role="tabpanel" class="ui-tabs-panel ui-corner-bottom ui-widget-content" aria-hidden="false">
```
```aria-expanded=true``` need to be replaced by ```[aria-hidden=false]```
Best regards
| BC breaks? …
=> Fix scrollbar from softwares list on computer

inc/item_rack.class.php
| Fixed tickets | #7976
Checked for other broken icons using:
`grep -rni inc/ -e 'fa-' | grep -vE '(fas |fa |far |fab )'`
This was the only case I saw of an icon with a missing `fa`, `fas`, `far`, or `fab` class.
=> Fix missing icon; fixes #7976

inc/plugin.class.php
The arrays used for active and loaded plugins have default keys and not indexed by directory name or plugin ID. This causes plugins to stay loaded until the page refreshes and the DB is checked again.
It causes an issue when you call Plugin::uninstall followed by Plugin::isInstalled because it still shows as installed when it isn't.
=> Fix plugin unloading

js/common.js
| Fixed tickets | pluginsGLPI/formcreator#1944.
Fix for pluginsGLPI/formcreator#1944.
Form tracking was reimplemented as opt-in so the arbitrary limitation for only tracking under `#page .glpi_tabs` seems useless. It also broke tracking when outside tabs like with the Form Creator service catalog UI.
=> Remove arbitrary form change tracking limit

inc/ticket.class.php, tests/emails-tests/18-image-on-multiple-lines.eml, tests/imap/MailCollector.php
| Fixed tickets | #7964 
Sometimes, the img tag inside an email is splitted on multiple lines (see new eml file in tests), and in this case, image was not attached correctly to ticket.
Failure before fix : https://app.circleci.com/pipelines/github/glpi-project/glpi/5821/workflows/4d95aec6-f944-4809-9cce-fd56fb183156/jobs/47318
=> Fix mailcollector image when tag is splitted on multiple lines; fixes #7964

inc/auth.class.php
| Fixed tickets | #6498 
This is an alternative proposal to #7885. The idea is to get rid of the `$user_deleted_ldap` property which may be set without even knowing if user was existing at some moment in this LDAP server, and can be misinterpreted.
=> Prevent user to be deactivated if LDAP login fails; fixes #6498

inc/search.class.php
SLA/OLA fields have been renamed in #4960, so I guess #5272 fix was only working due to a missing rebase when it has been done.
=> Fix SLA/OLA progress bar; see #5272 and #4960

inc/rssfeed.class.php
Internal ref: 20213.
SQL queries fetching may return duplicates as the user may be in multiple groups, profiles, ...
Using distinct solve this issue.
=> Fix RSS feeds duplicates

inc/domainrecord.class.php
Configured manageable records types now allows removal without
setting right on Domain itself
| Fixed tickets | 20613 (internal)
=> Override canDelete, canPurge and canPurgeItem on DomainRecord

.circleci/config.yml
=> Do not run PHP 7.4 tests on GLPI 9.4

inc/commonitilvalidation.class.php, tests/units/CommonITILValidation.php
Internal ref: 20749.
Consider the following situation:
1) Minimum approval for a given ticket is 100%.
2) There is 10 validators.
If 1 validator refuses the approval, the ticket is still "pending for validation" despite not being able to be validated even if all the 9 remaining validators votes yes.
This is because we use a very simple formula for checking refusal:
`{refusal %} > {minimum_validation %}`
In this case, it translates to 10% > 100% which is false -> no action.
---
These changes implement the following formula:
`{refusal %} + {minimum_validation %} > 100%`
In the case above, it translates to (10% + 100%) > 100% which is true -> approval is denied.
| …
=> Fix validation refusal detection

package.json
`acorn` lib is not directly used and was only added to force a specific version. This is no longer required, so this lib can be removed from dev dependencies.
=> Remove undirectly used acorn from direct dependencies

inc/application/errorhandler.class.php, inc/change.class.php, inc/plugin.class.php, inc/search.class.php, inc/ticket.class.php
Fix PHPDoc for parameters in Plugin and Search classes. The plugin class fixes should reduce the number of IDE warnings for plugin devs.
Add documentation to plugin state constants.
Remove doc blocks for some overridden methods that don't add anything new to the documentation.
Fix variable type of `$last_fatal_trace` in ErrorHandler (This is assigned the value of Exception::getTraceAsString later. I couldn't see where it can be an array).
Fix some param docs in Ticket class.
=> Update Plugin, Search, and other PHPDoc

inc/notification_notificationtemplate.class.php
| Fixed tickets | #8067
I don't know why default `multiple` param for `Notification_NotificationTemplate::dropdownMode` was set to true.
All usages force this param to `false` except one, and this last doesn't work properly.
So i choose to remove the param
=> remove multiple param from queuenotification mode criteria, fix #8067

inc/html.class.php
I need to handle possible errors when running an AJAX request. Html::ajaxForm() is nice, but does not support all callbacks.
As this change is minor, I submit it for GLPI 9.5.x, but I'm ok to merge in 9.6 as it is simple to maintain a version embedded in a plugin.
=> error and complete callback support for ajaxform

front/tickettemplatepredefinedfield.form.php
Internal ref: 20838.
Associated items in ticket templates are broken because the selected item's id is not saved in DB:
The following code from glpi 9.4 was missing:
https://github.com/glpi-project/glpi/blob/9.4/bugfixes/front/tickettemplatepredefinedfield.form.php#L44
=> Fix associated elements in ticket template

inc/user.class.php
| Fixed tickets | #8081
SQL is case insensitive, so query may return a row with an item having a name in a different case than expected. As PHP array keys are case sensitive, accessing `$passwords[$data['name']]` will produce `*** PHP Warning (2): Undefined array key "TECH" in /var/www/glpi/inc/user.class.php at line 5129`.
=> Fix security checks when default username case changed; fixes #8081

inc/commondbtm.class.php
When a Domain is created in a sub-entity; if we switch to any parent entity and try to create a Record for this domain, current entity was used; instead of Domain one.
This depends on how we were called. If we're from an `ajax/common.tabs.php`  call, everything is fine. If we used (as when adding a domain record) an iframe; behavior is different.
=> Use entity id if present; to avoid difficult to undesrtand cases

inc/ticket.class.php
When we create a ticket with total duration, a task is created, but GLPI does not provide a description for this task, 
this results in an error after the creation of the ticket.
"You can't add a task without description".
| Fixed tickets | internal 20863
=> fix(core): add content to task for action_time

inc/commonitilobject.class.php
Internal ref: 20833.
If you put a dropdown (let's say category) as mandatory in your ticket template, you obviously can't create the ticket through the UI without specifying the category.
However, if you have an existing ticket without category, it can be updated without issues despite lacking this mandatory category value.
The comments in the code indicate that this was done to avoid impacting existing tickets: if you add a new mandatory field, you can still update your old tickets without having to comply to the new mandatory settings.
However this prevent an interesting use case: a user might want to set up mandatory fields for a **recurrent** ticket, forcing these fields to be set during the first update.
These changes allow this by removing ticket that were created but not yet …
=> Fix mandatory fields for recurrent ticket

.github/workflows/ci.yml
1) Add nightly test suite on all supported PHP/MariaDB/MySQL versions.
2) Add lint on minimal supported version (too early usage of new syntaxes).
3) Limit tests done on a PR to PHP 7.4 only (except for lint).
=> Add nightly build and update matrix

inc/ticket.class.php
Add 'done' status to task when is created from actiontime.
| Fixed tickets | 20863
=> fix(core): add done state to task from actiontime

inc/search.class.php
| Fixed tickets | internal ref !20635
When calling 131 searchoption (from ticket) with api, an fatal may occurs if the glpi_items_tickets contains an bad itemtype (disabled plugin for example)
```
[12-Oct-2020 13:05:13 UTC] [12-Oct-2020 13:05:13 UTC] PHP Fatal error:  Uncaught Error: Class 'PluginDomainDomain' not found in inc\search.class.php:5947
Stack trace:
#0 inc\search.class.php(1441): Search::giveItem('Ticket', 'Ticket_131', Array)
#1 inc\search.class.php(314): Search::constructData(Array)
#2 inc\api.class.php(1603): Search::getDatas('Ticket', Array, Array)
#3 inc\apirest.class.php(193): API->searchItems('Ticket', Array)
#4 …
```
=> avoid loading non existent class

inc/search.class.php
| Fixed tickets | internal ref !20635
Fix in #8099 seems not correct, as it checks `$val['itemtype']` instead of `$val['name']`.
=> Fix ticket items search results; see #8099

.github/workflows/ci.yml
Currently, when pushing on a branch that match `master|.*/bugfixes|feature/.*|fix/.*`, all PHP versions and MariaDB/MySQL versions are tested. On tier repositories that has Github Actions workers usage limitations (private forks), it may be a problem.
With this PR, only PHP 7.4/MariaDB 10.3 versions will be tested.
=> Limit CI build matrix on tier repositories

inc/log.class.php
=> History: fix display for deletion of a subitem

inc/entity.class.php, inc/location.class.php, tests/functionnal/Entity.php, tests/functionnal/Location.php
If you don't specify any geolocation data in Locations and Entities, this information is now copied from the parent automatically.
https://glpi.userecho.com/communities/1/topics/914-use-parent-geolocation-data-when-no-data-available
=> Inherit geolocation data

.github/actions/docker-compose-app.yml, .github/actions/docker-compose-services.yml, .github/workflows/ci.yml
1) Use `docker-compose` to start containers. This prevent containers to be initialized even when all job steps are skipped (we gain about 50 seconds for each of the 5 skipped jobs).
2) Add cache on dependencies and on PHPCS.
3) Cancel any running/queued workflow running for a given branch when a new commit is pushed on this branch.
Cancelling a job will trigger a notification for failed build, so if you consider it is a problem, we can remove this commit.
=> Optimize Github Actions run times

inc/html.class.php
| Bug fix?      | unsure
| New feature?  | unsure
Some of my developments use AJAX. When the request fails I want to show a error message by calling the JS function **displayAjaxMessageAfterRedirect** ( in HTML::displayAjaxMessageAfterRedirect() ). If the user tries again and the AJAX fails with a different error message, the 1st error message is displayed instead the 2nd.
This is because GLPI adds a div with the error message with an ID attribute, and when a 2nd AJAX request is handled the 2nd message is created in the DOM with the same ID. This is invalid to have several identical IDs in the DOM, and the JS which shows the error uses the 1st ID found.
Here is …
=> allow repeated ajax calls to show session messages

inc/autoload.function.php
Prevent `Warning: strpos(): Empty needle in /var/www/glpi/inc/autoload.function.php on line 63`.
=> Fix 'Warning: strpos(): Empty needle' on isApi()

inc/console/commandloader.class.php, tests/units/Glpi/Console/CommandLoader.php
With GLPI 9.5, plugins can be installed in multiple directories (defined in `PLUGINS_DIRECTORIES`), but console commands were only loaded from `plugins` directory.
=> Load plugin commands from all plugins directories

front/dashboard_assets.php, front/dashboard_helpdesk.php, inc/dashboard/grid.class.php
1\)  Fix shared dashboards
If an user : 
- doesn't have the right to see all dashboards
- can see one or more shared dashboards
- can't see the default dashboard for the given page 
Then he get an empty page instead of being able to see the few shared dashboards he is able to see.
Fixed in e5e6a44.
Before:
After:
2\) Redirect if no dashboards
When clicking on the "assets" or "assistance" menu, if you can't see any dashboards for this page then you get an almost empty page.
I think it would be better to redirect the user to a useful page instead.
Fixed in 368c753 (url used to redirect were the one used in 9.4 before we added dashboards).
Before:
After:
3\) Default dashboard set by profiles
No change done on this, only a suggestion.
Shouldn't this setting be defined in each profiles instead …
=> Fix shared dashboards + redirect

css/impact.scss, package-lock.json, package.json
=> Bump cytoscape-context-menus from 3.1.0 to 4.0.0

inc/commonitilvalidation.class.php
When transferring a computer, if it's linked to ticket containing validation request (TicketValidation), 
PHP notices appears.
Because ```CommonDBTM``` only passed  ```entities_id``` and ```_transfert``` keys  when ```forwardEntityInformations```
| Fixed tickets | internal 15923
=> fix(transfer): prevent PHP notice

.github/workflows/ci.yml, inc/search.class.php, tests/functionnal/Search.php
This PR add checks on MariaDB 10.4 and 10.5 in test suite.
I found that in MariaDB 10.4 and 10.5, usage of `LIKE '%x%'` is a performance killer, and, on our test suite, we have some queries built from a search query that uses a `LIKE '%f%'` on all existing metacriteria (e.g. `Search::testSearchAllMeta()` on `Computer` uses 39 LIKE, and I had to kkil the request on my machine after 15 minutes as it was still running).
To fix this, I modified the test suite in order to prevent usage on '%' in `LIKE` conditions.
=> Test on MariaDB 10.5

inc/commonitiltask.class.php, inc/problem.class.php, inc/ticket.class.php
1. For each list, the full query was done to get the total count, the a query with limits where done to only get displayed items. I remove this second query as we can use the first one to display elements.
2. If `$_SESSION['glpidisplay_count_on_home']` was equal to `0`, items were not displayed (`$number = 0;` was causing `if ($number) {}` to be evaluate as false).
=> Reduce query count on home page and fix full list display; see #6765

css/dashboard.scss, inc/dashboard/widget.class.php
Introduced by https://github.com/glpi-project/glpi/pull/8151.
Tickets dashboard titles are broken on latest 9.5/bugfixes:
This is caused by a font size increase (11px -> 2em in #8151).
To fix this I've allowed the line to use 100% of the available width and added a text-ellipsis in case the text may still be too long in some other languages (in this case the user can hover on the text to see the full title thanks to the new title attribute).
After (with example of a long title for the last one) : 
FYI the labels were much smaller in 9.5.1 (font size is em based, 
=> Fix ticket dashboards titles

inc/search.class.php
Fixes ability to search using `>` or `<` operators.
=> Fix disk 'Free percentage' search option

ajax/ticketsatisfaction.php
Internal ref: 20967.
For surveys, the `max_closedate` input doesn't display until it has a value (value is set to current date if `inquest_rate` is updated.
This is confusing since the user is unaware this option exist unless he modifies the `inquest_rate` parameter (see internal ref).
Before:
After:
=> Always display max_closedate for surveys

inc/ticket.class.php, tests/functionnal/SLM.php
1. During OLA affect, base date was set to `date('Y-m-d H:i:s')`, making it difficult to test. I switched to `$_SESSION['glpi_currenttime']`.
2. `internal_time_to_own` start reference date was not always same as `$ticket-field['date']` (due to point 1), now it should.
3. `internal_time_to_resolve` start reference date is `$ticket->fields['ola_ttr_begin_date']`, which was not always equal to `$ticket->fields['date']` or `$ticket->fields['date_mod']` (due to point 1), now it should.
=> Fix SML dates computation tests

inc/marketplace/view.class.php
Due to usage of double quotes, `$s` was evaluated an replaced by an empty string, triggering an error: `Uncaught Exception ValueError: Unknown format specifier " "`.
=> Fix locale string

inc/migration.class.php, inc/reservationitem.class.php, install/mysql/glpi-empty.sql, install/update_95_xx.php, install/update_95_xx/reservationitem.php
Internal ref: 19770.
Followup of #7318.
Items have 3 states regarding reservation:
*  reservable (= there is ONE entry in `glpi_reservations_items ` with is_active = 1)
*  reservable but not active (= there is ONE entry in `glpi_reservations_items` with is_active = 0)
*  not reservable (= no entry in glpi_reservations_items).
If for some reason there is multiple entry for one item in `glpi_reservations_items ` then reservations are broken for this item.
-> Adding a unique key to prevent this.
I've also dropped the is_deleted field as it never used (there is no trashbin for this itemtype).
=> Add unique for reservation items + drop is_deleted

inc/plugin.class.php
Bulk install, enable, disable, and uninstall actions on plugins
For proper functionality, #7978 is needed. Otherwise, the uninstall action shows a failure message even though it is successful.
=> Massive actions on Plugins

inc/rule.class.php, inc/ruleticket.class.php, tests/functionnal/RuleTicket.php
This PR allows you to add a requester group to the ticket from the list of requester groups based on a regex
Example : criterion
check if requester group have parenthesis
Example : Action -> if so, affect the result of a regular expression using the string #0
Best regards
=> feat(rule): add action for RuleTicket engine

inc/commondbrelation.class.php, inc/computer_item.class.php
Assuming we have the following Computer <=> Monitor connection: 
View from Computer:
View from Monitor:
As you can see, the "Automatic inventory" fields do not match.
The correct information is the one displayed from the monitor's view.
The computer's view is incorrect because it show the "Automatic inventory" state of the linked monitor (instead of the state of the **connection** between the two items).
Use `is_dynamic` field from the connection.
| Fixed tickets | !18575
=> Fix is_dynamic display for computer_item tab

inc/networkportinstantiation.class.php
| Fixed tickets | #8183
Revert back to using `self` on instance method. Using `$this` caused an infinite loop.
=> Fix network port form

inc/config.class.php, inc/glpikey.class.php, inc/log.class.php, tests/functionnal/Config.php, tests/units/Migration.php
1. An history entry is now created when adding or deleting a configuration value (not only on update).
2. Values are replaced by `********` when entry correspond to a secured config.
There is no need to update existing history as shown values are encrypted.
Example:
=> Enhance configuration history

css/styles.scss
Pasted rich text is not displayed correctly:
* Added a new css rule to force line returns.
After:
=> Fix pasted rich text

inc/html.class.php
Partially addresses #7858 but still no `Today` button.
This change allows you to tab into date and time fields and manually enter a date like you were able to before.
Since the actual field value doesn't update while you type, it is forcibly set after flatpickr closes.
=> Allow manually entering date and time

inc/search.class.php, tests/functionnal/Search.php
Enclosed aliases/columns names in backticks, allowing the use o special characters such as '\'.
| Fixed tickets | #8226
=> Fix addOrderBy function

inc/plugin.class.php
Add plugin hooks for the different stages of a plugin's lifecycle (install, enable, disable, uninstall, and clean).
Currently, other plugins are not told when the state of a plugin changes. This can cause issues if plugins build on top of others. For example, a plugin linking Problems to Alerts from the news plugin. We can hook into when an alert is deleted to cleanup records in the link table, but if the plugin is completely uninstalled, we need to know in order to truncate the table. Otherwise, if the News plugin is reinstalled, we will have stale data.
=> Add plugin lifecycle hooks

inc/itilsolution.class.php
| Fixed tickets | #8167 
On an empty `CommonDBChild` object, `$this->getEntityID()` returns `-1`, so all solutions templates and solutions types were proposed, even on entities that were not available.
=> Fix visibility filters in solution form; fixes #8167

inc/log.class.php
| Fixed tickets | pluginsGLPI/datainjection#211
Issue noticed in Computer historical tab when the item is created by the Data Injection plugin. One or more of the entries has `id_search_options` set to 0. The loose comparison here compares all search options including the group headings like "common". This specific value equals integer 0 if you don't use a strict comparison, so it would throw a notice because there wouldn't be any `table` or `field` values for it.
This issue was only present in 9.5 because previously, the `id_search_options` value was read as a string, which "common" != "0".
=> Fix bad comparison in log

inc/config.php, inc/session.class.php, install/install.php, tests/functionnal/Session.php
When accessing pages without being logged-in, displayed language will now be based on `Accept-Language` header, or fallback to default GLPI language if accepted languages are not available.
Impacted pages are:
- login, logout, and password reset pages,
- public FAQ,
- update page.
On second commit, I updated the language selection of installation process to use the preferred language by default.
=> Try to use browser accepted languages on unauthenticated pages

inc/html.class.php
The `required` class is only removed on keyup event.
Pasting data though the context menu (right click -> paste) doesn't trigger this event.
Added a new listener for the 'paste' event that, when triggered, remove the `required` class.
| Fixed tickets | !21051
=> TinyMCE: Fix paste with context menu

inc/mailcollector.class.php, tests/emails-tests/19-attachement-rfc5987-multiline.eml, tests/imap/MailCollector.php
| Fixed tickets | #8148
Requires https://github.com/laminas/laminas-mail/pull/108 to work correctly on short filenames (when filename in content-disposition is not splitted info mutilple lines). This part will be done in #8265 .
=> Handle RFC5987 format in Content-Disposition header; fixes #8148

inc/mailcollector.class.php, tests/emails-tests/09-reply-to-tech.eml, tests/emails-tests/21-monopart-html.eml, tests/imap/MailCollector.php
| Fixed tickets | #8263
`$this->body_is_html = true;` was not set to true for mono-part messages. Main result is that new lines were replaced by `<br />`.  In most of case, ticket content contained extra line break, but if these line breaks were at a bad place (e.g. beween `table` and `thead` HTML tags), resulting HTML was completely corrupted during htmlawed cleaning.
=> Fix import of mono-part HTML emails; fixes #8263

inc/dbmysql.class.php, inc/html.class.php
May help when troubleshooting performance related issues reported by GLPI users as well as some other development use cases given more information than just the total time a query takes. It could give more information to the GLPI developer such as how many entities are being fetched which may influence subsequent queries.
Beyond performance, this extra information can help a GLPI developer see how much an action affects the DB data from within GLPI.
This extra column indicates the number of rows fetched, updated, inserted, deleted, etc.
=> Show number of rows affected in SQL Requests debug

inc/item_devices.class.php, inc/plugin.class.php
Replaces #8276 and #8277.
Give ability for a plugin to defines a `xxx_types` entry in `$CFG_GLPI` (e.g. `pluginautomationdevice_types`). This can give access to item affinities logic for a new type of devices.
=> Handle definition of xxx_types config handled by a plugin

js/kanban.js
Store if the user is using a dark theme or not along with the badge colors. When preloading the badge cache, we check if they are still using that type. If not, we clear the badge color cache and force it to regen so we get matching colors (Not light blue on white or dark grey on black).
=> Regen Kanban badge colors when changing theme type

inc/ticket.class.php, tests/functionnal/RuleTicket.php
The following ticket rule doesn't work:
This is because `itilcategories_id_code` is missing from the `$input` var which is sent to the rule engine.
Add the missing value in the `prepareInputForAdd` / `prepareInputForUpdate` methods.
| Fixed tickets | !21062
=> Fix ticket rules for itilcategories_id_code

inc/stat.class.php
When generating statistics of tickets by location, you would get SQL errors due to a space between the table name and field, and then no space between the field and `AS`.
=> Fix bad spacing in SQL query

inc/mapgeolocation.class.php, js/common.js
Try to make it easier to assign geolocation data by defaulting the map view to the current location (Or as close as we can approximate) if the user allows us to use their location. If not, fall back on the previous defaults.
If we can get geolocation data, the map zoom level is adjusted based on the reported accuracy.
This only works over HTTPS or localhost. If those requirements don't apply to the user, they will see the original functionality.
Tested on a desktop (very-low accuracy) and a cell phone (high accuracy) and the zoom levels seemed appropriate.
=> Try using current location as map default

inc/console/system/cleancachecommand.class.php, inc/console/system/clearcachecommand.class.php
Add new command "clean cache"
```
dev  ~/dev/GLPI/9.5-bugfixes   add_clean_cache_command  php bin/console glpi:system:clean_cache        
cleaning cache done !!
dev  ~/dev/GLPI/9.5-bugfixes   add_clean_cache_command  
```
=> feat(console): add clean cache command

inc/ticket.class.php
| Fixed tickets | !21085
Replaces #8291 
`$options['_tickettemplate']` contains the previously used template.
If redefinig it with the new computed value, the `$options[$key] != $tt->getID()` test will always be evaluated to false.
`$options['_tickettemplate'] = $tt` was done only to pass this value to `showActorAddFormOnCreate` options.
=> Fix ticket template change on helpdesk form

inc/marketplace/api/plugins.class.php
Marketplace API may not send versions from higher to lower, so it is preferable to do a sort on GLPI side to be sure to expose the higher version.
Marketplace API could be updated too, to fix version displayed for users using GLPI < 9.5.3, but keep the sorting on GLPI side can't hurt.
=> Fix higher version fetching in plugins marketplace

inc/glpinetwork.class.php
This will permit to return a custom validation message from GLPI Network Services API.
For instance, message could be:
- `Your registration has expired.`,
- `Registration key format is invalid.`,
- ...
=> Handle registration key validation message returned by Services API

package-lock.json, package.json, webpack.config.js
| Fixed tickets | #8302 
Remove sourceMappingURL directives for all external libs that are included by a simple copy of the js script.
This will prevent these directives to conflict with the directives added by webpack compilation process.
=> Strip unusable sourcemaps from bundled libs; fixes #8302

inc/datacenter.class.php
When we try to sort computer list by datacenter position SQL error occurs
```sql
SQL Error "1054": Unknown column 'ITEM_Computer_178' in 'order clause' in query "SELECT DISTINCT `glpi_computers`.`id` AS id, 'glpi' AS currentuser, `glpi_computers`.`entities_id`, `glpi_computers`.`is_recursive`, `glpi_computers`.`name` AS `ITEM_Computer_1`, `glpi_computers`.`id` AS `ITEM_Computer_1_id`, `glpi_entities`.`completename` AS `ITEM_Computer_80`, `glpi_states`.`completename` AS `ITEM_Computer_31`, `glpi_manufacturers`.`name` AS `ITEM_Computer_23`, `glpi_computers`.`serial` AS `ITEM_Computer_5`, `glpi_computertypes`.`name` AS `ITEM_Computer_4`, `glpi_computermodels`.`name` AS `ITEM_Computer_40`, `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090`.`name` AS `ITEM_Computer_45`, …
```
=> fix(search): use no sort for virtual field

inc/search.class.php, tests/functionnal/Search.php
| Fixed tickets | !21081
This changes fixes the exact case from ticket !21081, but I am really not confident in it as I do not really understand all the consequences. Indeed, there are too many operations to many usages related to $LINK and $NOT variables, making code really hard to understand.
=> Fix AND NOT meta search

inc/commonitilobject.class.php, inc/html.class.php
| BC breaks?    | possibly
| Fixed tickets | Item 2 in #8321 
Add an optional parameter to specify classes for the gallery items
- The `timeline_img_preview` class which was previously applied every time was moved to only be added when creating the gallery for non-embedded images in the timeline
Add an optional `thumbnail_src` parameter to images. If not specified, the `src` parameter is used for both the main image and thumbnail.
- The forced `timeline` context for the thumbnail image was removed and is instead passed implicitly from the timeline code. This means that in other cases like embedding an image in a followup, the image can take up more space in the …
=> Fix img size when embedded in timeline items

inc/stat.class.php
Satisfaction survey stats is in error
In fact, I have two satisfaction surveys, one is waiting for an answer and the other is answered.
But the statistics show me that both have been answered.
```sql
+----+------------+------+---------------------+---------------------+--------------+---------+
| id | tickets_id | type | date_begin          | date_answered       | satisfaction | comment |
+----+------------+------+---------------------+---------------------+--------------+---------+
|  1 |         51 |    1 | 2020-11-23 08:04:21 | NULL                |         NULL | NULL    |
|  2 |         55 |    1 | 2020-11-23 13:04:33 | 2020-11-24 09:19:56 |            3 | sdfsdf  |
+----+------------+------+---------------------+---------------------+--------------+---------+
```
"NOT" key in WHERE …
=> split 'not' criteria

css/jquery-glpi.css
| Fixed tickets | !21096
Put back styles that were present in GLPI 9.4 (see https://github.com/glpi-project/glpi/blob/9.4/bugfixes/lib/jquery/css/smoothness/jquery-ui-1.10.4.custom.css#L785 ).
=> Fix font-family inside tabs

inc/vlan.class.php
While acronyms do not have plural form in French, this is not true in english; and maybe in other languages as well.
=> Add plural

composer.json, composer.lock
With both mbstring and intl missing, I got:
```
% php80 ./bin/console glpi:system:check_requirements
Session::loadLanguage() in /var/www/webapps/glpi/inc/session.class.php line 628
Missing required intl PHP extension Uncaught Exception Error: Call to undefined function Symfony\Component\Console\Helper\mb_detect_encoding() in /var/www/webapps/glpi/vendor/symfony/console/Helper/Helper.php at line 50
```
=> Readable error on missing mbstring

.github/workflows/ci.yml
Prevent execution of full jobs matrix a branch prefixed by `feature/`, `bugfix/` or `security/` is pushed on current repository.
Full matrix will only be executed:
- on push on master branch,
- on push on */bugfixes branch,
- on tag creation,
- on manual dispatch.
=> Execute full matrix only on master and bugfixes branches and tags

composer.json, composer.lock, inc/define.php, index.php
Some dependencies `guzzlehttp/guzzle` `symfony/*`, `league/csv` have PHP 7.2.5 as minimum requirement for their latest versions.
=> Update min PHP version from 7.2.0 to 7.2.5 and upgrade dependencies

ajax/savedsearch.php, css/styles.scss, inc/savedsearch.class.php, inc/search.class.php
Allow edition of saved searches.
To make it easier to notice that you are on a saved search, the "star" icon is now highlighted :
Clicking the "star" icon when you are already on a saved search allow you to update the search:
The 'Save as a new search" button allow you to copy the modified search to a new one instead of overriding the current one.
| Internal tickets | !21016
=> Edit saved searches

inc/mailcollector.class.php, inc/toolbox.class.php
Adds email real uniqueID management see: https://github.com/laminas/laminas-mail/blob/2.13.x/src/Storage/Imap.php that recommend to use UniqueId for email, and not the default counter
fixes #8345
| Fixed tickets | #8345
=> Prevents addslashes_deep and stripslashes_deep to corrupt Objects

CHANGELOG.md, apirest.php, apixmlrpc.php, inc/api/apixmlrpc.class.php, inc/config.class.php, inc/system/requirementsmanager.class.php, inc/toolbox.class.php
XML-RPC extension has been dropped from core PHP extensions in PHP 8.0 and Pecl package has no available releases yet.
Thus, even if I cannot be sure of that, I guess most of people are already using the REST API.
I tried to put a deprecation warning, but it breaks XML response when errors are displayed in output.
=> Deprecate usage of XML-RPC API

inc/html.class.php, inc/notificationtargetticket.class.php
Given this ticket:
The emails surrounded between< and >will be missing from the notification content:
Encoding these emails a second time before sending the notification seems to fix the issue.
After fix:
This fix feel kind of hacky, if someone want to spend time to find a better solution he is welcome to do so :)
Some thoughts on this:
* If you check the sources (tinymce) from the client you can cleary see that only the \<emails\> are encoded: 
* However in the database both the html tags and the \<emails\> are encoded:
* Either the \<emails\> should be double encoded in the database or the others tags should not be encoded at all (isn't encoding html in the database a bad practice anyway ?)
| BC breaks? …
=> Fix <emails> in notifications

inc/search.class.php, inc/session.class.php
Since 9.5.3 and the addition of security idor tokens, we added globally check for all search engine ajax call.
Maybe too globally.
When asking for a new global rule (blue part) and after selecting itemtype, the second part doesn't display due to an idor check (with ajax call contains action=display_criteria parameter).
Afaik, the original security issue was found for action=display_searchoption case.
i have no idea how to fix the ajax call because, it rely on a dynamic itemtype=__VALUE__ parameter (we validate itemtype with idor checks)
So i suggest to remove idor validation for the current problematic case.
=> don't validate idor token when displaying criteria

tools/build_glpi.sh
It may happen that an external lib has classes inside a directory named `test` that are not meant to be used in test suite (for instance, in Twig: https://github.com/twigphp/Twig/tree/3.x/src/Node/Expression/Test).
Without this cleaning process, archive goes from 44MB to 46MB (tested on feat/modern-ui branch).
Even if the archive weighs 2MB more, as we used the `--prefer-dist` option in `composer install` call, I consider that it is the responsibility of external lib maintainers to exclude these files from their packages, using [archive option of `composer.json`](https://getcomposer.org/doc/04-schema.md#archive).
=> Remove vendor cleaning in release process

install/update_95_xx.php, install/update_95_xx/devicebattery.php, install/update_95_xx/domains.php, install/update_95_xx/reservationitem.php, install/update_95_xx/softwares.php
1. Replace some `*::getTable()` to hardcoded table names to prevent unexpected migration result in case tables names changed in the future.
2. Move domain update to domain file.
3. Add missing file header.
=> Enhance 9.5 to x.x migrations

install/update_95_xx/domains.php
Should fix following error:
```
SQL: UPDATE `glpi_domainrecordtypes` SET `fields` = '[{"key":"target","label":"Target","placeholder":"sip.example.com.","is_fqdn":true}]' WHERE `name` = 'CNAME'
Error: Unknown column 'fields' in 'field list'
Backtrace :
inc/dbmysql.class.php:1060                         
install/update_95_xx.php:93                        DBmysql->update()
inc/update.class.php:379                           update95toXX()
inc/console/database/updatecommand.class.php:180   Update->doUpdates()
vendor/symfony/console/Command/Command.php:255     Glpi\Console\Database\UpdateCommand->execute() …
```
=> Fix domains update

tests/GLPITestCase.php, tests/LDAP/AuthLdap.php, tests/functionnal/AuthLdap.php, tests/functionnal/Cartridge.php, tests/functionnal/CommonITILValidation.php, tests/functionnal/Config.php, tests/functionnal/DbUtils.php, tests/functionnal/Entity.php, tests/functionnal/ITILSolution.php, tests/functionnal/ITILTemplate.php, tests/functionnal/Item_Cluster.php, tests/functionnal/Item_Rack.php, tests/functionnal/ProjectTask.php, tests/functionnal/Session.php, tests/functionnal/SoftwareLicense.php, tests/functionnal/Telemetry.php, tests/functionnal/Ticket.php, tests/functionnal/TicketRecurrent.php, tests/functionnal/TicketTask.php, tests/functionnal/Ticket_Ticket.php, tests/functionnal/User.php, tests/imap/MailCollector.php
The goal is to catch all redirection messages (warning and errors); and I've also added a method to make tests simpler.
=> Test "messageafterredirect"

inc/notificationeventmailing.class.php, inc/notificationtargetticket.class.php, inc/toolbox.class.php
Following #8330, \<emails\> were correctly escaped in the mail queue but were still not displayed when receiving the actual email.
I figured there must be yet another HTML decoding step taking place before sending the mail, found it in notificationeventmailing and removed it.
| Fixed tickets | !21113
=> Fix <emails> in notifications 2

tests/APIBaseClass.php, tests/GLPITestCase.php, tests/bootstrap.php, tests/functionnal/Certificate_Item.php, tests/functionnal/CommonDBTM.php, tests/functionnal/DbUtils.php, tests/functionnal/Dropdown.php, tests/functionnal/Glpi/Dashboard/Provider.php, tests/functionnal/Knowbase.php, tests/functionnal/Session.php
Test bootstraping was altering session to be able to create dataset without being logged, so tests were running with session variables that were not compliant to a normal state.
I had to keep this session altering for API tests (as some add/update/delete operations are done), but it should not be a problem as tested results are retrieved via HTTP requests.
By the way, I noticed that requests done during API tests cannot be encapsulated into a transaction (requests are done by separated processes), so when a test is failing on dev machine, the whole DB have to be reset to be sure to have a clean DB state.
=> Prevent tests dataset loading to alter session

front/config.form.php
#8283 fixes issues with special chars in core configuration fields. This PR extends this fix to all declared configuration fields, including thoose declared by plugins.
Plugin metabase is affected by this issue.
=> Prevent secured configs to be altered by sanitize logic; see #8283

inc/changetemplate.class.php, inc/problemtemplate.class.php, inc/tickettemplate.class.php
The clone function for ticket template
does not take into account relationships (hidden fields, predefined fields, mandatory fields).
| Fixed tickets | internal 21229
=> fix(clone): cloning relations too

inc/itilsolution.class.php
Fix cascade resolution for duplicate tickets
Actually, when linked tickets are manage, GLPI try to update status, but it's already done by parent ticket.
| Fixed tickets | Internal 21194
=> fix(linked_ticket): fix cascade resolution

tests/GLPITestCase.php, tests/functionnal/CommonDBTM.php
On a a feature branch of mine, a minor change has a side effect to enter a loop that relies on `$_SESSION['glpiactive_entity']`; even on already existing tests/classes that has not been changed (more than 80 tests are failing).
=> GLPI expects this to be set in various places

CHANGELOG.md, inc/monitor.class.php, inc/networkequipment.class.php, inc/peripheral.class.php, inc/phone.class.php, inc/printer.class.php, install/mysql/glpi-empty.sql, install/update_95_xx.php, install/update_95_xx/uuids.php, tests/functionnal/Monitor.php
For next major version, not 9.5.0.
Adds a UUID field to ~~phones~~ all OS-capable itemtypes. Needed for Jamf plugin mainly since I ended up using extra classes/tables to store that extra field for phones. This was critical for me to effectively match iPhones for merging in the same way I handle iPads which imported as computers.
iOS/iPadOS UUID is static, but Android also has "Settings.Secure.ANDROID_ID" which is set on first boot but changes upon a factory reset (still may be suitable as a UUID). There may be another static ID for Android or any other phone firmware/OS that other plugins/inventory agents can utilize for …
=> UUID for OS-capable Itemtypes

inc/savedsearch.class.php
| Fixed tickets | #8303
There was a duplicate `is_private` field shown for technicians who could create private searches and it was overriding the user's selection and setting it back to the default which is private.
This hidden input now only shows when the user cannot create a public search and therefore only has one `is_private` field in either case now.
=> Fix creation of public saved search

inc/ticket_ticket.class.php
| Fixed tickets | #8400
fixes #8400
Before selecting TicketA and doing the Link Tickets massive action and setting any link type like "Son Of" and TicketB, the result is TicketA is linked to TicketB with "Parent Of" instead. This PR fixes that link by switching around which tickets are considered number 1 and 2.
=> Fix reversed ticket links from massive action

ajax/dashboard.php
Due to the idor token mechanism, displaying filter need a write enabled session.
Previously, we locked the session to display dashboard's cards by ajax (to avoid sequential load)
This is only needed for this cards loading, not all ajax html calls
=> Some dashboard fillters can't load

inc/toolbox.class.php
Sometime, it may arrives glpi network services are down.
To avoid stucking on Setup > General > GLPI Network tab, i set connection timeout to 5s.
It lets the page responds in a max time of 10s (5s for checking services status, 5s foc checking key informations)
=> GLPI Network services timeout

inc/commonitilobject.class.php, inc/tickettask.class.php
| Fixed tickets | internal !21260
In some case, for example a private task created by a ticket template, self-service user may be the author of a private task and could see it.
I suggest to remove ability to see private task globally for all self-service profiles
=> self-service users should never see private tasks

.github/actions/check_services_health.sh, tools/build_glpi.sh, tools/modify_headers.pl
1. Prevent some directories to be parsed (`config`, `css_compiled`, `files`, `marketplace`, `node_modules`).
2. Check files formats in extension only, to prevent `.json` to match `.js` format.
3. Remove an empty space that caused shell scripts to be altered when running headers modification script.
=> Fix checked files in headers update script

tests/emails-tests/20-attachement-rfc5987-singleline.eml, tests/imap/MailCollector.php
| Fixed tickets | see #8148 
Follow #8161.
Test was failing before merge of https://github.com/laminas/laminas-mail/pull/108 (see https://github.com/glpi-project/glpi/runs/1395939719?check_suite_focus=true ), and now it is passing.
=> Handle RFC5987 format in Content-Disposition header (single line)

inc/commonitilobject.class.php, inc/dashboard/provider.class.php, inc/ticket.class.php
SQL query used by ticket late widget is not same as query from ticket search form (where clause)
SQL query for widget
```
SELECT * FROM `glpi_tickets` 
WHERE `glpi_tickets`.`is_deleted` = '0' 
AND `glpi_tickets`.`status` IN ('1', '2', '3', '4') 
AND (
`time_to_resolve` < NOW() 
OR `time_to_own` < NOW() 
OR `internal_time_to_own` < NOW() 
OR `internal_time_to_resolve` < NOW()
) 
GROUP BY `glpi_tickets`.`id`
```
SQL query from search form
```
IF(`glpi_tickets`.`time_to_resolve` IS NOT NULL
AND `glpi_tickets`.`status` <> 4 AND (`glpi_tickets`.`solvedate` > `glpi_tickets`.`time_to_resolve`
OR (`glpi_tickets`.`solvedate` IS NULL AND `glpi_tickets`.`time_to_resolve` < NOW())), 1, 0) = 1
IF(`glpi_tickets`.`internal_time_to_resolve` IS NOT NULL AND `glpi_tickets`.`status` <> 4
AND …
```
=> fix(dashboard): fix query criteria

ajax/entitytreesons.php
This change has no functionnal impact on 9.5 branch (problem was detected on debug mode on master branch due to displaying of SQL warnings).
SQL warning was `1292: Truncated incorrect DOUBLE value: '0r'`.
On line 58, root ID is suffixed by a `r`, and this `r` was not remove before sending SQL request. It was working only due to the fact that SQL forced casting to a number by truncating the `r`.
=> Fix entity tree expand

inc/mailcollector.class.php
Should prevent following issue:
```
PHP Notice (8): iconv(): Detected an illegal character in input string in /var/www/glpi/inc/mailcollector.class.php at line 2079
 Backtrace :
 inc/mailcollector.class.php:2079                   iconv()
 inc/mailcollector.class.php:1616                   MailCollector->getDecodedContent()
 inc/mailcollector.class.php:1516                   MailCollector->getRecursiveAttached()
 inc/mailcollector.class.php:1657                   MailCollector->getRecursiveAttached()
 inc/mailcollector.class.php:992                    MailCollector->getAttached()
 inc/mailcollector.class.php:754 …
```
=> Fix email attachement decoding logic

inc/auth.class.php
IMAP auth isn't working when you disable the "Display source dropdown on login page" option.
-> Bug introduced in https://github.com/glpi-project/glpi/pull/7954.
Seems to be a typo in the condition to me.
| Tests pass?   | pending
| Fixed tickets | !21205
=> Fix IMAP auth without login source dropdown

inc/console/abstractcommand.class.php, inc/console/application.class.php, inc/console/command/glpicommandinterface.class.php, inc/console/database/abstractconfigurecommand.class.php, inc/console/database/updatecommand.class.php, inc/console/maintenance/disablemaintenancemodecommand.class.php, inc/console/maintenance/enablemaintenancemodecommand.class.php, inc/console/system/clearcachecommand.class.php
Executing some commands before having an up-to-date DB may produce unexpected results. This PR will disallow execution of most of existing commands in this case, except for install, update, maintenance enable/disable and cache clear commands.
=> Prevent console commands to be executed if DB is not up-to-date

CHANGELOG.md, inc/dbmysql.class.php
Honestly, even if I did not tried to use/test it, I do not even understand why this option is present. All tables/columns are created with `utf8` charset, and all communications between web clients (browser, api clients, ...) are expected to use the `utf8` charset.
So using an alternative charset will, at best, require the mysqli driver to convert data from `utf8` to this alternate charset, and the the MySQL server will have to convert it back to `utf8`, and at worse, it will produce buggy behaviours.
I am preparing migration to `utf8mb4` charset for next major release, and handling this custom charset may be a thorn in the …
=> Deprecate alternative BD connection encoding

inc/console/migration/timestampscommand.class.php, inc/dbmysql.class.php
=> Timestamp migration should care only about glpi_% tables

composer.json
Composer note:
Before executing scripts, Composer's bin-dir is temporarily pushed on top of the PATH environment variable so that binaries of dependencies are directly accessible. In this example no matter if the phpunit binary is actually in vendor/bin/phpunit or bin/phpunit it will be found and executed.
https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands
=> Fixed compatibility of composer scripts on Windows

inc/commonglpi.class.php
The fields plugin use the `$_SESSION['glpi_tabs']` array to check whether or not it must load some additional fields.
If you login to GLPI, you start with the following `$_SESSION['glpi_tabs']` content:
```
Array
(
[central] => Central$0
)
```
If you then go, for example, to the ticket creation form then there will NOT be any additional fields added by the plugin.
These fields will only be displayed after you have loaded an individual ticket and thus got a 'ticket' key in your `$_SESSION['glpi_tabs']` like this:
```
Array
(
[central] => Central$0
[ticket]  => Ticket$main
)
```
This fix prevent this issue by initializing the current `$_SESSION['glpi_tabs']` itemtype when you go on a form page.
While this fix seems to be a good short term solution, maybe we could also open an issue on the …
=> Init active tab on display

inc/commonglpi.class.php
Revert #8509 as it does not fix the reported issue.
=> Revert #8509

js/planning.js
Url are broken for items with `editable => true` prop.
The js code try to use the ajaxurl even if it is undefined.
Fixed the condition to check the url properly.
=> Fix editable items in planning without ajaxurl

inc/commondbrelation.class.php, inc/session.class.php
Some items were hardcoded to be created on the default entity instead of the current one (Item_DeviceSimcard for example).
| Fixed tickets | !21363
=> Fix default entity in CommonDBRelation

.github/workflows/ci.yml, CHANGELOG.md, composer.lock, inc/central.class.php, inc/console/abstractcommand.class.php, inc/console/application.class.php, inc/console/database/abstractconfigurecommand.class.php, inc/console/database/installcommand.class.php, inc/console/exception/earlyexitexception.class.php, inc/console/migration/utf8mb4command.class.php, inc/dbconnection.class.php, inc/dbmysql.class.php, inc/mailcollector.class.php, inc/migration.class.php, inc/system/requirement/dbconfiguration.class.php, inc/toolbox.class.php, install/install.php, install/mysql/glpi-empty.sql, install/update.php, install/update_95_xx.php, tests/database/DBmysql.php, tests/units/DB.php, tests/units/DBConnection.php, tests/units/Glpi/System/Requirement/DbConfiguration.php, tests/units/Migration.php
Supports emoji, and, unless I am wrong, more Han ideographs.
Migration took only 15 minutes for a 1.5GB database on my developpement machine (which host DB on a HDD).
Remaining work TO DO:
=> Use utf8mb4 MySQL character set

inc/html.class.php
This pull request add a filter for input files when `onlyimages` is setted when you click and open the window dialog.
Example: 
Before:
After: `Custom files: *.gif, *.png, *.jpg, *.jpeg`
=> Improved input file when setted only images

inc/commondbrelation.class.php, inc/item_softwareversion.class.php
| Fixed tickets | #8421
fixes #8421
Moved list criteria to `getListForItemParams` which was previously unused and restricted it to non-deleted items only.
=> Don't count deleted software on install tab

inc/calendar.class.php, inc/calendar_holiday.class.php, inc/holiday.class.php, tests/functionnal/Calendar.php, tests/functionnal/Calendar_Holiday.php
| Fixed tickets | #7989 
Cache holidays for each calendar to prevent doing a SQL query for each `isHoliday` check. This may greatly improve performances when SLA/OLA are computed on high date ranges, or when many items are shown on the same page.
=> Cache holidays to improve SLA/OLA computations; fixes #7989

inc/inventory/asset/monitor.class.php
```
SQL: SELECT `glpi_monitors`.`id`, `glpi_computers_items`.`id` AS `link_id` FROM `glpi_computers_items` LEFT JOIN `glpi_monitors` ON (`glpi_monitors`.`id` = `glpi_computers_items`.`items_id`) WHERE `itemtype` = 'Monitor' AND `computers_id` = 'Computer' AND `entities_id` = '0' AND `glpi_computers_items`.`is_dynamic` = '1' AND `glpi_monitors`.`is_global` = '0'
Warnings: 
1292: Truncated incorrect DOUBLE value: 'Computer'
Backtrace :
/var/glpi/inc/dbmysqliterator.class.php:95         
/var/glpi/inc/dbmysql.class.php:806                DBmysqlIterator->execute() …
```
=> Fix monitor asset handling in inventory

inc/search.class.php, tests/functionnal/Search.php
Charset must match the one used in tables.
=> Fix charset used in search

inc/ticket.class.php
GLPI allows you to assign a group to a ticket and leave the status as new.
But the central page -> group view -> tickets to be processed 
does not take into account the new status
| Fixed tickets | internal 21256
=> fix(central): add incoming ticket too

inc/search.class.php
| Fixed tickets | #4107
I don't know exactly why it fails depending on the database you have.
In my case it was with 10.3.27-MariaDB-1:10.3.27+maria~stretch-log.
When I executed the SQL with that database the result was:
ITEM_Ticket_13 | ITEM_Ticket_13_itemtype
1507$#$4631$$##$$1891$#$4632 | Computer$#$4632$$##$$Monitor$#$4631
When it should be:
ITEM_Ticket_13 | ITEM_Ticket_13_itemtype
1507$#$4631$$##$$1891$#$4632 | Computer$#$4631$$##$$Monitor$#$4632
To avoid this I forced to also order by the id the field "ITEM_Ticket_13_itemtype"
=> Fix associated elements in ticket list

ajax/comments.php, inc/inventory/asset/mainasset.class.php, inc/inventory/inventory.class.php, inc/refusedequipment.class.php, inc/rulecollection.class.php
Only the first stacked entry had an itemtype correctly set and corresponding rules_id in refused logs; and only the last one had the inventory file.
For those equipments, there is currently no "stack" notion we could rely on, so inventory file is available for every stack part like it is an entire equipment.
=> Fix stacked refused equipments

css/styles.scss, inc/entity.class.php, inc/notification.class.php, inc/notificationtarget.class.php, tests/bootstrap.php, tests/functionnal/Entity.php, tests/functionnal/Notification.php, tests/functionnal/NotificationTarget.php
| Fixed tickets | maybe #6944, and internal ref !21352
The purpose of this pr is to make easier configuration for large entity tree
All fields in the notification tabs of entities are curently inheritable except mails and names (ex prefix or signatures are inheritable despite no inline documentation).
I took the opportunity to extends inline documentation for inheritance on missing fields (and remove \<font\> balise deprecated in 1999 😬 )
I still have a concern by the way, we may change existing malformed setup in existing instances.
And some may have emails changes (before if no value defined in the direct entity, the system took the global …
=> make notification email/name from entity inheritables

inc/rulecollection.class.php
Hope this fix sortable buttons missing/present when then should/not appears.
=> More reliable way to detect sortable/not sortable tab

inc/config.class.php, inc/document.class.php, inc/documenttype.class.php, inc/glpiuploadhandler.class.php, inc/html.class.php, inc/toolbox.class.php, install/empty_data.php, install/update_95_xx.php, install/update_95_xx/documents.php, js/fileupload.js, tests/functionnal/Config.php, tests/functionnal/DocumentType.php
| Fixed tickets | #8176 
While searching how to fix #8176 , I noticed multiple things:
1. `maxChunkSize` option can be used to split upload on multiple request when using `fileupload` jQuery plugin.
2. Uploading from file input was using `fileupload` jQuery plugin capabilities, but uploading from image pasting into rich text editor was not.
3. Upload using `drop` event was configured to be handled by `fileupload` jQuery plugin but was also manually handled.
So, after some iterations, I finally mutualize code and use `fileupload` jQuery plugin for all uploads, which permits to upload large files chunks by chunks.
~~In the end, there is no …
=> Handle upload of large files

CHANGELOG.md, inc/commondbtm.class.php, inc/commonitilobject.class.php, inc/queuednotification.class.php, tests/functionnal/NotificationEventAjax.php, tests/functionnal/QueuedNotification.php
Notifications related to ITIL objects are synchronously sent. This was done, if I remember right, to be sure that every notification be sent to recipients before deduplication process can drop some of them. Problem is that notification sending can crash, due to a too large memory usage, when documents attached to tickets are voluminous.
I propose to do it in another way. Instead of forcing synchronous send of notifications, we could just prevent the deduplication process to be runned.
=> Async sending of ITIL objects notifications

js/kanban.js
| Fixed tickets | #8581
Instead of resetting the background refresh timer when a user was actively making changes (to avoid disruptions), a new timer was being created resulting in multiple refreshes being stacked together.
=> Clear existing background refresh when delaying/resetting it

front/entity.form.php, inc/entity.class.php, tests/functionnal/Entity.php
| Fixed tickets | #8397 
Alternative proposal to #8576 .
The idea is to store raw input, and then :
- display it with encoded entities in entity form, to display what was really set (this was already done like that, but was so twice encoded);
- strip tags before using the value in the `<style>` header tag, in order to prevent security issue without encoding or removing `<`, `>`, `'` and `"`.
=> Handle chevrons and quotes in custom CSS; fixes #8397

inc/software.class.php, tests/functionnal/Software.php
Add new searchoption 'date install' to Software metacriteria
depends on #8596 
| Fixed tickets | internal 21362
=> feat(searchoption): add software date install to metacriteria

inc/unmanaged.class.php
Fixes warnings on SO tests.
This PR targets master as MySQL warnings are not showned on 9.5/bugfixes branch, but I guess first 2 commits should be applied to 9.5 branch.
```
=> tests\units\Search::testSearchOptions():
==> An exception has been thrown in file /var/glpi/tests/functionnal/Search.php on line 471:
==> RuntimeException: DBmysql::query() in /var/glpi/inc/dbmysql.class.php line 363
==>   *** MySQL query warnings:
==>   SQL: SELECT DISTINCT `glpi_entities_knowbaseitems`.`id` AS id, '_test_user' AS currentuser,
==>                         `glpi_entities_knowbaseitems`.`entities_id`, …
```
=> Fix search options tests

inc/html.class.php
In some cases, a textarea may be dosplayed with  a height of 0. This can occur in Formcreator, very likely when a textarea is hidden and displayed by javascript.
It appears that setting a minimum height to the textarea solves the issue. Internal ref: 21355
The minimal height set here is similar to the height usually observed in GLPI, i.e. a new ticket.
=> set minimal height for textarea

inc/item_devicebattery.class.php, tests/functionnal/Search.php
Part of #8610.
Fixes following errors:
```
=> tests\units\Search::testSearchAllMeta():
==> An exception has been thrown in file /var/glpi/tests/functionnal/Search.php on line 539:
==> RuntimeException: DBmysql::query() in /var/glpi/inc/dbmysql.class.php line 363
==>   *** MySQL query warnings:
==>   SQL: SELECT DISTINCT `glpi_computers`.`id` AS id, '_test_user' AS currentuser,
==>                         `glpi_computers`.`entities_id`, `glpi_computers`.`is_recursive`,  `glpi_computers`.`name` AS `ITEM_Computer_1`,
==>                         `glpi_computers`.`id` AS `ITEM_Computer_1_id`,
==> …
```
=> Fix SO tests on MySQL 5.6/5.7

.github/actions/check_services_health.sh, .github/actions/test_update_from_9.5.sh, .github/actions/test_update_from_older_version.sh, inc/console/migration/dynamicrowformatcommand.class.php, inc/console/migration/utf8mb4command.class.php, inc/networkport.class.php
Includes #8617 .
1. Add `-e` to test sh scripts to be sure that shell script will exit if any command fails (see Update tsts in https://github.com/glpi-project/glpi/runs/1791562875?check_suite_focus=true, some commands were failing but were not trigerring failure of the test suite).
2. Separate `ROW_FORMAT` migration into a dedicated command, to be able to launch it before trying to play migration from 9.5 to master using utf8mb4 charset. Without this, MySQL 5.6 / MariaDB 10.1 test suite will when migration will try to create an index on a `varchar(255)`.
3. Fix a wrong datatype on lastup SO (to prevent failure on MySQL …
=> Fix tests on MySQL 5.6/5.7 and MariaDB 10.1

CHANGELOG.md, inc/calendar.class.php, inc/commondbconnexity.class.php, inc/commondbtm.class.php, inc/commonitilobject.class.php, inc/features/clonable.class.php, inc/massiveaction.class.php, inc/networkport.class.php, inc/projecttask.class.php, inc/rule.class.php, inc/toolbox.class.php, inc/user.class.php, tests/functionnal/Calendar.php, tests/functionnal/Ticket.php, tests/units/Glpi/Features/Clonable.php, tests/units/Toolbox.php
- Move all clone related functions into Clonable trait. Currently they are in CommonDBTM, but not all child itemtypes can be cloned. For example, Plugins and Config cannot/should not be cloned.
- Limit clone massive action to Clonable itemtypes only.
- Add a utility function Toolbox::hasTrait to check if an itemtype or its parents has a specific trait.
- Add test for checking clone action for Clonable itemtypes and Toolbox::hasTrait test.
=> Complete Clonable trait

inc/html.class.php
RegEx in JS are not surrounding by quotes.
This option is not used in 9.5 so bug only affects master, but as code is present on 9.5, I fix it on 9.5/bugfixes branch.
=> Fix images upload validation

inc/notificationtargetsavedsearch_alert.class.php
If the 'private search alerts' event is inadvertently removed, it is no longer possible to select it.
| Fixed tickets | Internal 21447
=> fix(event): fix get event for savedsearch

inc/dashboard/provider.class.php
When you click on a point in the widget to search for tickets, the filters are not used.
| Fixed tickets | internal 21250
=> fix(dashboard): add saerch filter criteria for widget by year

inc/console/migration/appliancesplugintocorecommand.class.php
If option "Enable the financial and administrative information by default" is enabled
Appliance migration thrown error for infocom step
Because, infocom already exist with good itemtype (due to option)
This PR fix this problem
| Fixed tickets | internal 21322
=> fix(apppliance): prevent duplicated infocom creation

inc/console/database/checkcommand.class.php, inc/system/diagnostic/databasechecker.class.php, install/mysql/glpi-empty.sql, tests/units/Glpi/System/Diagnostic/DatabaseChecker.php
Some tables were not detected due to usage of `IF NOT EXISTS`.
I fixed some minor issues on these tables declaration, added missing `DROP TABLE` instructions, and removed these `IF NOT EXISTS`.
=> Fix CREATE TABLE detection in db:check command

inc/console/build/compilescsscommand.class.php
It may happen that someone want to rebuild compiled CSS after applying a patch. Using this command cannot hurt, so I guess we could promote it as an official command.
=> Promote glpi:build:compile_scss as an official command

.github/actions/init_show-versions.sh
Using a `grep db` on docker container list may return entries that are not related to the container having the name `db`.
Example:
1. It is safer to rely on the `name=db` filter.
2. The `-a` option is useless as we should test ionly running containers (not all).
3. The `-q` option removes the headers to be sure to have an empty string if no cotnainer matches given name.
Prevents this error:
=> Fix CI 'Show version' step

inc/line.class.php
Original problem :
When creating a line with location, the line takes the entity of the location unlike certificates, for example
The inheritance of the class "line" has changed from ```CommonDBTM``` to ```CommonDropDown``` (I don't know why)
This PR revert commit https://github.com/glpi-project/glpi/commit/8052033582dc58eb6f90b256db4c436d3104f4e7#diff-7d3f7c2f1bdbb4c5a110fffc4d89bd93fd223c1cdad4d0b9698aae74344cda83R41
| Fixed tickets | internal 21479
=> fix(core): use CommonDBTM instead of CommonDropdown

inc/api/api.class.php
through GLPI API, when searching for ```IPAddress``` itemtype,
```mainitems_id``` is always empty.
```json
[
{
"id": 508,
"entities_id": "Root entity",
"items_id": "",
"itemtype": "NetworkName",
"version": 4,
"name": "192.168.139.246",
"binary_0": 0,
"binary_1": 0,
"binary_2": 65535,
"binary_3": 3232271350,
"is_deleted": 0,
"is_dynamic": 0,
"mainitems_id": "",
"mainitemtype": "Computer"
}
]
```
This foreign key need a specific transformation to be "understood" by API
| Fixed tickets | Internal 21367
=> fix(api): manage mainitems_id foreignkey

.github/actions/test_install.sh, .github/actions/test_update-from-9.5.sh, .github/actions/test_update-from-older-version.sh, inc/console/database/checkschemacommand.class.php, inc/system/diagnostic/databasekeyschecker.class.php, inc/system/diagnostic/databaseschemachecker.class.php, install/mysql/glpi-empty.sql, install/update_95_xx/native_inventory.php, install/update_95_xx/schema_fixes.php, tests/units/Glpi/System/Diagnostic/DatabaseKeysChecker.php, tests/units/Glpi/System/Diagnostic/DatabaseSchemaChecker.php, tools/checkkeyscommand.class.php
While analysing performances issues on meta criteria tests, I noticed that some fields in database corresponding to "foreign keys" were not in tables index.
This PR introduces a system that detects missing keys, based on column names. This system is called on tests suite and triggers a failure when a missing key is found.
Exemple of failure:
At first, I thought about putting this command into glpi-project/tools, but it would need to implement a way to configure DB connection for these tools and also to add CI checks. Maybe it could be done later, when I would have time to do it.
=> Add a check on database keys

inc/system/status/statuschecker.class.php
The LDAP server status plain-text output was incorrectly using the status of DB replicas.
=> Fix LDAP server status check

.github/workflows/ci.yml, README.md, composer.json, composer.lock, inc/define.php, index.php
PHP 7.2 is not supported since November 30, and some packages (laminas for instance) already dropped support of PHP 7.2 in their composer.json file, meaning that dependabot will not inform us about new releases of these packages as they are considered as incompatible.
For information, here is the current version oh PHP in main linux distributions
| Distribution | Release date | PHP Version
| --------------- | ------------------ | -----------------
| RHEL 8.3 | October 29, 2020 | PHP 7.4
| Debian Buster | July 6, 2019 | PHP 7.3
| Ubuntu 20.04 | April 23, 2020 | PHP 7.4
| openSUSE Leap 15.2 | July 2, 2020 | PHP 7.4
=> Drop PHP 7.2 support

inc/project.class.php, js/kanban.js
First problem
The bulk and individual add form uses the same css class ```kanban-add-form```
and the javascript code that add only one task is triggered during bulk add
Second problem
add task or sub project project from kanban view, use current active entity, rather than the problem entity
| Fixed tickets | internal 21417
=> Fix kanban

.github/actions/docker-compose-app.yml, .github/actions/lint_php-lint.sh, .github/actions/test_tests-functionnal.sh, .github/actions/test_tests-imap.sh, .github/actions/test_tests-ldap.sh, .github/actions/test_tests-units.sh, .github/workflows/ci.yml, .github/workflows/coverage.yml
1. Fix composer.lock removal in CI. Was not working as `IGNORE_LOCK_FILES` env was not passed to app container.
2. Fix CI cache. Was not working du tu usage of relative path (`${{ github.workspace }}/../app_home`). I put back old value, but, as `${{ runner.temp }}` is not accessiblle in job env declaration, I had to move `APP_CONTAINER_HOME` env declaration in a job step.
3. Fix PHP lint script for execution on dev machine. Hardcoded path for cache file and in ignore pattern was preventing this script to be usable on dev machine.
4. Use unique env var for code coverage (`CODE_COVERAGE`), to simplify usage of test scripts …
=> Minor CI fixes

inc/dashboard/filter.class.php, inc/dropdown.class.php, inc/html.class.php
In commit 984ae321eca4cf516a0f07a205d5e39c12fc2edf, dropdown values were filtered to handle the case where we want to display a dropdown without preselecting a value and without displaying the empty value. It intoduced bugs on dropdown that needs to display values <= 0.
#8255 was a first fix, to handle values <= 0 that was part of `toadd` option, but a bug was still existing for numeric dropdown when the 0 value was the selected value (blank value was displayed).
This PR introduced ability to explicitely pass `null` as a dropdown value.
=> Fix dropdown using 0 as a concrete value; see #8681

inc/search.class.php, tests/functionnal/Search.php
| Fixed tickets | #8671 
#8311 introduced a bug when using the `AND NOT` operator outside meta context.
I reverted #8311 and added a test case related to !21081.
I do not even know if my test is correct (it reproduces the query obtained with #8311 patch), but I guess we should find a way to make it pass.
=> Fix NOT search; fixes #8671

inc/profile_user.class.php, inc/update.class.php, inc/user.class.php, install/mysql/glpi-empty.sql, install/update_953_954.php, tests/units/RuleRight.php
When users have only one dynamic profiles that match the default profile of GLPI, this profile should not be deleted by the right rules engine if no rules match this user.
Concrete example (!21527) :  
- An user is created through the API
- The default profile is auto affected as dyamic
- There is no right rules targeting this user
-> When this user log in, he should keep the current profile (currently the profile is removed and he can't login).
=> Do no delete default profiles if no rules were applied

front/planning.php, inc/session.class.php, inc/user.class.php
WebCal export isn't working due to rights checks added in ba0f81603e5677c34397397329837a4637012248.   
External tools call front/planning.php with no session so all rights check done in Planning::generateIcal() will never work.
Fixed it by loading the calendar owner session.
| Fixed tickets | !21503
=> Fix webcal export rights check

inc/commonitilobject.class.php
Hello,
There was a two single quotes to end the action attribute of the form HTML tag.
Delete one in order to keep HTML clean.
Thank you
Regards
Tomolimo
=> Deleted excess quote in generated HTML

front/softwarelicense.form.php
do not track changes on license add form
Because of software dropdown wich reload page
if user change some input before, browser say "this page is asking you to confirm that you want to leave - data you have entered may not be saved"
this PR prevent this (same behavior for ticket.form.php
| Fixed tickets | Internal 21586
=> fix(data-track-change): do not track on license add form

inc/user.class.php
During LDAP synchronization 
GLPI does not check if the user already has the group.
This Pr prevent this
=> fix(ldap_sync): check if link already exist before add

inc/central.class.php
As seen on #8693 , checking web access is so easy. We should remove this new check since we do not have a better solution.
=> Remove check on logs file web access; see #8693

css/styles.scss, inc/html.class.php
Since #8180 , image upload is broken on rich text editors that uses the option `enable_fileupload: false` (the default value). Indeed, pasting an image in rich text now uses the `fileupload` component, but this one was not initialized when `enable_fileupload` option was not `true`.
=> Fix image pasting in rich text

inc/inventory/inventory.class.php
Fix fatal error on front/crontask.php: 
```
[2021-02-25 11:23:50] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined method Glpi\Inventory\Inventory::getTypeName() in /home/adrie/localhost/gmaster/inc/search.class.php at line 6469
Backtrace :
inc/search.class.php:1448                          Search::giveItem()
inc/search.class.php:320                           Search::constructData()
inc/search.class.php:95                            Search::getDatas()
inc/search.class.php:80                            Search::showList()
front/crontask.php:62                              Search::show()
```
=> Add missing method to Inventory cron

inc/itilfollowup.class.php
PR https://github.com/glpi-project/glpi/pull/8668
introduce bug for self service
Which is not allowed to go from resolved to ongoing status
=> fix(reopen): do not check allowed status from self service

inc/search.class.php
PHP function declaration is case insensitive, so this change has potentially no impact. But maybe in a far future PHP will introduce case sensitivity in class / function names, so I prefer to fix it.
=> Fix plugin case in search hooks

inc/crontask.class.php
| Fixed tickets | #8701
During cronstask execution:
1. Active plugins are loaded.
2. A loop is done using `$crontask->getNeedToRun()` to get next task to execute (it fetches only tasks for core and ACTIVE plugins).
3. Task callable is executed.
So plugin should already be loaded, and there is no neet to load it again.
On case sensitive filesystems (almost all now), plugin is not reloaded as `Plugin::load()` is called with an plugin name using camel case (first letter is uppercased). Directory is not found, so nothing is done.
On case insensitive systems (FAT ?), plugin is reloaded, and it produces an error, see #8701.
=> Prevent plugin reload on crontask execution

inc/ticket.class.php
| Fixed tickets | #8710 
`Ticket::computeTakeIntoAccountDelayStat()` base its computation on result of `Ticket::getCalendar()` method.
Without this fix, used calendar is always the one configured in entity.
With this fix, used calendar will be the one defined in SLM. Indeed, `calendars_id` field of SLA/OLA objects is filled on `post_getFromDB` method, based on parent SLM `calendars_id` field. It seems like a hack to me, but is used like that at many places.
=> Fix 'take into account' delay using SLM calendar; fixes #8710

inc/commonitiltask.class.php, tests/functionnal/TicketTask.php
| Fixed tickets | #8407 
Currently, `CommonITILTask::getTaskList` must return a `DBmysqlIterator` instance even if there are no results or it is an invalid query. If group tickets are requested and the current user has no groups, we must return an "empty" iterator instead of false.
=> Fix invalid return for Central group view

inc/console/system/checkstatuscommand.class.php, inc/console/system/listservicecommand.class.php, inc/console/system/listservicescommand.class.php, inc/system/status/statuschecker.class.php, status.php, tests/functionnal/Glpi/System/Status/StatusChecker.php
As GLPI and plugins become more complex and reliant on external services/systems it becomes more likely that a configuration or connectivity issue (In GLPI or the external service) could partially or completely break GLPI or the plugins, and it becomes more necessary to monitor and alert on these issues.
The goal of this PR is to make it easier to monitor GLPI. In some monitoring software, it may be inconvenient to do that with the previous implementation because all status checks were done together and returned as a single result which is slow and inefficient if you only want to check one or two things. The goal is to …
=> Improved Status Checking

ajax/common.tabs.php
When a creation form is displayed, `ajax/common.tabs.php` is called with an empty value for `id` param, which was transformed into `0` by int casting. In case of entity creation form, this is a problem, as `0` is the id of the root entity.
=> Fix entity creation form

inc/massiveaction.class.php
Massive actions have icons that are displayed in item view:
But are not displayed in the search results view: 
This was not an issue since the `<i>` tags weren't rendered.
However since 553b3dd0fa96de0226eacb2c14e5e72fd3780e6f the tags are escaped and displayed in plain text:
To fix this I've added a call to strip_tags for the search results view.
| Fixed tickets | !21680
=> Remove massive actions icons from search results view

inc/search.class.php
| Fixed tickets | #8765 
```diff
LEFT JOIN `glpi_computers_items` AS `glpi_computers_items_Computer` ON (`glpi_computers_items_Computer`.`items_id` = `glpi_monitors`.`id` AND `glpi_computers_items_Computer`.`itemtype` = 'Monitor' AND `glpi_computers_items_Computer`.`is_deleted` = 0)
-LEFT JOIN `glpi_computers` ON (`glpi_computers_items_Computer`.`computers_id` = `glpi_monitors`.`id` )
+LEFT JOIN `glpi_computers` ON (`glpi_computers_items_Computer`.`computers_id` = `glpi_computers`.`id` )
```
=> Fix meta left join through *_items when target is main item; fixes #8765

inc/dashboard/provider.class.php, inc/ticket.class.php
| Fixed tickets | #8746
`+` operator on array ignore already existing keys.
1. `OR` key was already existing for profiles that does ot have read rights on all tickets (set in `Ticket::getCriteriaFromProfile()`). I encapsulate `OR` clauses in an array to prevent conflicting.
2. I remove usage of `+` operator as it was still not working due to presence of same numeric key in both arrays.
=> Fix ticket dashboard criteria; fixes #8746

inc/item_softwareversion.class.php
| Fixed tickets | #8670 
Entities restrict criteria were pushed outside the `WHERE` key. When criteria exists outside `WHERE` key, they are ignored during query building.
=> Fix software count on computer; fixes #8670

inc/autoload.function.php, tests/units/Autoload.php
| Fixed tickets | https://github.com/pluginsGLPI/genericobject/issues/290
Due to missing `^` and `$` in regex used in `isPluginItemType()`, `Glpi\Api\Deprecated\PluginGenericobjectTest` was considered as `{"plugin": "Genericobject", "class": "Test"}`, and API deprecation check was so loading the `PluginGenericobjectTest` which was also loaded by `genericobject` plugin.
=> Fix API errors on deprecation checks

inc/search.class.php
The search UI allow to expand or reduce search criteria like this:
However this setting is lost on reload which make it a lot less useful.
I propose to store it in the client and reapply it on load if needed.
| Fixed tickets | !21701
=> Store search criteria toggle state in client

inc/document.class.php
| Fixed tickets | #8795 
When trying to reproduce the initial issue, I ended up with a followup where image had no height property. No sure how it happens, but result is that `Document::getImage()` was called with a width but no height.
=> Fix notification when image has a missing width/height; fixes #8795

inc/dashboard/provider.class.php
| Fixed tickets | #8794 
I also replaced the only occurence of `DISTINCT COUNT` by `COUNT DISTINCT`.
=> Use SQL count to limit memory usage on dashboard; fixes #8794

inc/dashboard/provider.class.php
Allow ```getSearchFiltersCriteria``` to be call outside ```Provider``` 
Usefull for plugins (advancedashboard) who would like to manage the criteria on the dashboard
=> feat(dsahboard): change function visibility to be call by plugins

inc/project.class.php
| Fixed tickets | #8574 
1. Show only projects related to active entities in the Global Kanban.
2. Show only projects related to active entities in the Project switch of the Kanban view.
=> Fix projects visibility in Kanban; fixes #8574

css/palettes/_darker.scss, css/styles.scss, inc/notepad.class.php
| Fixed tickets | #8595
Fix issue where the box around the notes field could overflow the form area. Removing the static width fixes the issue.
Fixed button/icon colors in the form header like the user vCard and impersonate buttons.
Fixed issue where the timeline filter was nearly invisible unless you hovered over it.
Fixed the color of the box around the note field to better match the darker theme and not a light theme.
=> Fix some darker theme and general style issues

ajax/common.tabs.php, ajax/updatecurrenttab.php, inc/ajax.class.php, inc/toolbox.class.php
GLPI use two ajax endpoint to handle tab loading.
If the tab was not loaded yet:
- `ajax/updatecurrenttab.php` set the current tab id in the session
- `ajax/common.tabs.php` load the tab content
If the tab was already loaded:
- `ajax/updatecurrenttab.php` set the current tab id in the session
The 'not loaded' case can lead to non deterministic issues as the request are sent asynchronously and can complete in different orders.
One clear example of this is that if the second request is completed first then the fields plugin would consider the user to still be on the previous tab (since the session data is not yet updated) and return incorrect data.
---
To fix this, I've changed the logic to this:
If the tab was not loaded yet:
- `ajax/common.tabs.php` set the current tab id in the session …
=> Set tab number in session before loading content

inc/commonitilvalidation.class.php
If an approver changes their response, global approval status is not recalculated
| Fixed tickets | internal 21725
=> fix(validation: compute global status even if it is not waitting for approval

inc/dashboard/provider.class.php
Fix reset filter criteria
for BigNumber widget in mini dahsboard , criterias are not reset correctly
url before patch  =   &1=reset
url after patch =   &reset=reset
| Fixed tickets | internal 21739
=> fix(dashboard): fix reset criteria

CHANGELOG.md, inc/search.class.php
#8629 breaks meta search in plugins itemtypes that are extending GLPI core itemtypes.
This PR puts back previous behaviour on plugin itemtypes.
=> Fix meta criteria from plugin objects

inc/html.class.php
| Fixed tickets | #8799 
If id used in massive action checkbox contains quotes or square brackets, name attribute of the checkbox will be malformed. It may happen on LDAP users import.
=> Fix special chars handling in massive actions; fixes #8799

inc/features/clonable.class.php, inc/session.class.php, tests/functionnal/Project.php
| Fixed tickets | #8598
When creating an item from a template, clone process is used. In case cloned element is created in another entity, child elements must also be created in this entity.
=> Fix entities_id/is_recursive values of cloned childs; fixes #8598

tools/build_glpi.sh, tools/make_release.sh
While trying to build GLPI 9.5.x on PHP 8, I saw that failure of minification command (used version of Robo in 9.5 branch is not PHP 8 compliant), was not stopping the build process. Usage of `-e` flag should ensure that process is exit when a subcommand fails.
=> Ensure release process will exit on error

inc/change.class.php, inc/commonglpi.class.php, inc/problem.class.php, inc/ticket.class.php
1. Fix restoration of input on Change and Problem
When changing category on creation form, content and images were lost.
2. Fix images saving on Change and Problem update
During update, inline images were not transformed into documents
3. Fix missing ending `</div>` on readonly Ticket form
=> Fix multiple ITIL rich text issues

CHANGELOG.md, inc/change.class.php, inc/commonitilobject.class.php, inc/html.class.php, inc/problem.class.php, inc/ticket.class.php, inc/toolbox.class.php, tests/functionnal/Ticket.php
1. On ITIL forms, TinyMCE is already initialized by `Html::textarea()`, so using `Html::setRichTextContent()` was initializing it twice.
2. On ITIL timeline, timeline items (except main item description), were already transformed by `Toolbox::getHtmlToDisplay()`, so using `Html::setRichTextContent()` had no effect, except that an extra entity decoding was done by the second call to `Html::clean()`.
3. On ITIL timeline, usage of `Toolbox::getHtmlToDisplay()` was more appropriate as `Html::setRichTextContent()` for main item description.
4. `Toolbox::getHtmlToDisplay()` was doing a `Html::entity_decode_deep()` that should …
=> Remove useless usage of Html::setRichTextContent()

inc/toolbox.class.php, tests/units/Toolbox.php
New regex introduced in #7733 is a bit too strict: URL containing "?" are considered to be not valid (so any URL with a query string would be marked as invalid).
=> Fix URL validation

inc/html.class.php, js/common.js
Flatpickr use the selected locale to define the start of the weeks.
The issue is that the US and the UK share one "english" locale config but should have different start of week (US -> sunday, UK -> monday).
Only way to fix this is to set the `firstDayOfWeek` param manually for this specific case.
| Fixed tickets | !21789
=> Flatpickr: Set start of week to Monday for UK

inc/mailcollector.class.php
This is not really a bug fix nor a new feature.
Currently, when a user creates/updates a mail collector with a name that is not an email address, an error message is displayed (`Invalid email address`), but input is saved anyway.
During collect process, name is added to blacklisted emails even if it is not a valid email address.
I added a tooltip to explain how this name is used, and removed the error message during input saving.
=> Clarify mailcollector name function

inc/commonitilobject.class.php
I see lot of occurences of `Missing type for Ticket template!` in logs provided in issues, but as it is logged using `Toolbox::logError()`, the backtrace is not available.
Using `trigger_error()` will permit to have the full trace. I use `E_USER_WARNING` as it is not a blocking error according to code, and `E_USER_ERROR` level will trigger a fatal error.
Exemple of trace we would get (I triggered it on a valid case):
```
[2021-03-19 09:58:04] glpiphplog.WARNING:   *** PHP User Warning (512): Missing type for Ticket template! in /var/www/glpi/inc/commonitilobject.class.php at line 7934
Backtrace : …
```
=> Use trigger_error() to be able to get trace in logs

inc/api/api.class.php, inc/search.class.php
In entity search results, when a user have access to only a subset of entities, their ancestor are shown, regardless user rights.
Removing the `$is_recursive:true` fixes this.
Nota:
`getEntitiesRestrictRequest()` and `getEntitiesRestrictCriteria()` have a special case to handle the `$is_recursive` for `glpi_entities` table, which looks weird to me. I did not see any occurence that uses this in the code, except for the case fixed by this PR.
=> Do not show ancestors on entity search results

.github/workflows/ci.yml, README.md, inc/config.class.php, inc/console/migration/dynamicrowformatcommand.class.php, inc/system/requirement/dbconfiguration.class.php, inc/system/requirement/dbengine.class.php, tests/functionnal/Config.php, tests/units/Glpi/System/Diagnostic/DatabaseSchemaChecker.php, tests/units/Glpi/System/Requirement/DbConfiguration.php, tests/units/Glpi/System/Requirement/DbEngine.php
MySQL 5.6 active support ended on February 5, 2021.
MariaDB 10.1 active support ended on October 17, 2020.
=> Drop MySQL 5.6 and MariaDB 10.1 support

inc/crontask.class.php
Crontask scheduling is based on dates computed on MySQL side (`lastrun` is using `DATE_FORMAT(NOW(),\'%Y-%m-%d %H:%i:00\')` and is the compared to `NOW()`).
Using PHP side hour may result in having tasks marked as executed outside their run period due to timezone offset between PHP and MySQL.
Example:
- Current hour is 05:00:00 UTC,
- PHP TZ is UTC+4,
- MySQL TZ is UTC+2,
- Run period is 8 -> 17;
-> PHP hour is so 09:00:00, within the run period. Task is executed and `lastrun` is updated to 07:00:00 (the MySQL time), wich is outside the run period.
=> Fix timezone used for cron task execution hours

inc/ipaddress.class.php
| Fixed tickets | !21668
I do not know why IP addresses chunks were converted into float as rest of logic expect integers.
=> Fix IP address conversion from binary

inc/crontask.class.php, inc/crontasklog.class.php, inc/notificationtargetcrontask.class.php
Here is a simple solution to prevent cron tasks to be marked as running when an error occured. Recoverable errors will be catched and so the task execution will be considered as aborted.
Consequences are:
- task will be reexecuted on next scheduled date,
- scripts will not exit due to error, so following tasks on the loop will be executed.
A better solution would be to add the error trace in the `glpi_crontasklogs` table, but it would require to add a new field in DB, much new strings and some UI changes, so it cannot be done on a bugfixes branch.
I forced an error on mailgate, for the example.
Cron log:
```
2021-03-26 …
```
=> Handle errors on crontasks

inc/crontask.class.php, tests/functionnal/CronTask.php
Fixes following issues:
1. If a plugin has registered a cron task that uses namespaced itemtype, then this cron task will be always executed, whenever the plugin is disabled.
2. If a plugin has registered a cron task that uses namespaced itemtype, then this cron task will not be removed by `CronTask::unregister()`.
=> Fix handling of plugins namespaces on crontask

inc/console/plugin/activatecommand.class.php, inc/console/plugin/deactivatecommand.class.php, inc/console/plugin/installcommand.class.php
This will prevent ability to activate, from CLI command, an inactive plugin which have a version different from its last installed version.
To reproduce the bug:
- deactivate an active plugin using `bin/console plugin:deactivate` command
- update its code source
- reactivate it using `bin/console plugin:activate` command
Without this fix, plugin will be reactivated but its `install` hook will not be trigerred.
With this fix, activation will be blocked.
=> Ensure plugin state is up to date before activate/install it

inc/crontask.class.php, tests/units/CronTask.php
Add capability to ```cleantemp``` crontask to clean recursively ```_tmp``` directory (file and folder if needed)
Unit test added
=> feat(crontask): improve clean temp crontask

inc/notification.class.php
Before:
After:
| Fixed tickets | !21903
=> Add missing submit button for 'remove_all_template' massive action

inc/link.class.php, inc/search.class.php
Two data were wrong for external links:
* Tab count display
* Search results
The issue with links is that you need to load the links matching the entity of a given item, not the active entity from the session.
Tab count were easy to fix, I could apply the same code that was already working for the tab content.
Search results were a lot harder as I'm not sure it is possible to do it in the search options.
I've tried a few SQL request inserted in `$newtab['joinparams']['condition']` but I wasn't sure it would work for everything given that we have specific case for recursives items and/or users.
In the end I've done the work on the `Search::giveItem` method instead (the search options does not do anything).
This was we can call the trusted code that we already use for displaying the tab …
=> Fix external links

inc/search.class.php
`specific` display is not working in both cases:
1. item `name` is empty,
2. `name` field is not part of retrieved data.
For case 1, for instance, manual links having an empty name (which could be the most common case) are not displayed in search results.
This PR fixes this.
I target master branch as I am not really sure of all impacts.
=> Allow usage of specific display without a name

inc/search.class.php
related to #4219
All searches use SELECT DISTINCT, then the extra SQL query to count the results shall do it as well.
Issue found on the Formanswers tab on form itemtype, and the issues list on the service catalog. I think the bug is new, and appeared after creating search options with a subquery of the following form:
LEFT JOIN foo ON (foo.id = bar.foos_id AND (SELECT ... FROM ...))
Forcegroupby is enabled for those search options, and those search options are force-enabled for all searches on the itemtypes with a plugin_foo_addDefaultJoin() function
=> a search uses DISTINCT, counting its results shall contain it as well

inc/commonitilobject.class.php, inc/ticket.class.php, tests/functionnal/Ticket.php
1. `Ticket::canUserAddFollowups()` was doing a check based on `Session::getLoginUserID()` instead of `$user_id` passed in parameters.
2. Some checks were done with a strict check. I do not know it it was a problem on a normal usage, but I hade to do non strict checks to be able to add some tests.
=> Fix followups rights checks

inc/system/diagnostic/databaseschemachecker.class.php, tests/units/Glpi/System/Diagnostic/DatabaseSchemaChecker.php
Change made in [MySQL 8.0.24](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-24.html) (released last week) :
> Client applications and test suite plugins now report utf8mb3 rather than utf8 when writing character set names. (Bug #32164079, Bug #32164125)
=> Fix utf8 migration checks on MySQL 8.0

tests/units/Html.php
Following #8985, added some unit test for Html::getGenericDateTimeSearchItems.
The `maybefuture` option mentioned in #8985 is used as `with_future` in this function.
| Fixed tickets | /
=> Add unit tests for Html::getGenericDateTimeSearchItems

inc/commonitilobject.class.php, inc/itilfollowup.class.php, inc/ticket.class.php, tests/functionnal/Ticket.php
| Fixed tickets | !21953
Includes #8991, as it is mandatory to make new test case pass.
=> Give ability to tickets observers to add followups

inc/commonitilobject.class.php
Introduced in #8960, missing an `echo` statement after the change from `printf` to `sprintf`.
=> Add missing 'echo' statement

inc/mailcollector.class.php, tests/emails-tests/26-illegal-char-in-body.eml, tests/imap/MailCollector.php
| Fixed tickets | #8986
Sometimes, some chars in email body cannot be transliterated to UTF-8, and the whole body remains in base encoding.
In added test :
- expected result: `这是很坏的Minus – Blabla`
- result without proposed fix: `ÕâÊÇºÜ»µµÄMinus ¨C Blabla`
- result with proposed fix: `这是很坏的Minus C Blabla`
I do not know if problem is due to an illegal char (conversion issue in the client that sent the email) or to a char that is not supported by iconv. However, I guess it is better to have some wrong chars instead of having the whole body in a wrong charset.
=> Fix handling of illegal chars in collected emails; see #8986

inc/system/requirementsmanager.class.php
People who do not use CAS do not understand why it is a requirement, and people who want to use it will still be warned when lib cannot be loaded by GLPI in the CAS configuration form.
=> Drop phpCAS extension check on install

css/styles.scss
Revert fix margin for p tag in timeline solution as exposed in #8566
| Fixed tickets | #8566
=> Fix for #8566  - Revert fix margin for p tag in timeline solution

inc/document_item.class.php, install/update_951_952.php, tests/functionnal/Document_Item.php
Tickets modification date were all updated when "Building inline images" migration part was played.
=> Do not update tickets date on inline images fixing

inc/api/api.class.php, tests/APIBaseClass.php
The `API->messageRightError()` method currently use a 401 (Unauthorized) returns code.
401 should be used when users are trying to access resources whitout being loged in:
> The 401 (Unauthorized) status code indicates that the request has not
been applied because it lacks valid authentication credentials for
the target resource 
https://tools.ietf.org/html/rfc7235#section-3.1.
In this case our user is logged in but doesn't have enough rights so 403 is more appropriate:
> The 403 (Forbidden) status code indicates that the server understood
the request but refuses to authorize it
https://tools.ietf.org/html/rfc7231#section-6.5.3
| Fixed …
=> Use 403 for API errors on missing rights

tools/build_glpi.sh
Locales have to be compiled before running `build:compile_scss` command.
See https://github.com/glpi-project/docker-images/runs/2488466370?check_suite_focus=true
=> Fix nightly build

inc/mailcollector.class.php, inc/toolbox.class.php, tests/functionnal/ITILFollowup.php, tests/functionnal/ITILSolution.php, tests/functionnal/KnowbaseItem.php, tests/functionnal/Ticket.php, tests/imap/MailCollector.php, tests/units/Toolbox.php
| Fixed tickets | part of #140
Currently, `<` and `>` chars are not correctly handled in rich test due to the way `Toolbox::clean_cross_side_scripting_deep()` and `Toolbox::unclean_cross_side_scripting_deep()` are working.
A short example:
- user types `time <5ms` in TinyMCE, and submit its ticket;
- `content` received will be `<p>time &lt;5ms</p>`, which is correct;
- `Toolbox::sanitize()` transforms it to `&lt;p&gt;time &lt;5ms&lt;/p&gt;`, and starting to this point we cannot differenciate anymore what was a `<` and what was a `&lt;`;
- when value is displayed, `Toolbox::unclean_cross_side_scripting_deep()` transforms it into `<p>time …
=> Fix XSS clean/unclean process

inc/infocom.class.php
As discussed today in our meeting, use the correct data when searching for software infocom data.
| Fixed tickets | !22034
=> Use correct infocom data for softwares searchoptions

.github/workflows/branch_build.yml
Almost the same workflow as the nightly build, but:
- branch have to be selected manually,
- PHP version can be selected manually (as compatible PHP version it may depend on target branch).
=> Add on-demand branch build workflow

front/pdu_rack.form.php
URL to redirect to list is wrong from ```PDU_Rack``` form
Now URL redirec to Rack list
| Fixed tickets | internal 22058
=> fix(core): list to front/rack.php

inc/commonitilobject.class.php, inc/entity.class.php, inc/group.class.php, inc/notificationtargetcommonitilobject.class.php, inc/search.class.php, inc/ticket.class.php, inc/user.class.php, install/migrations/update_9.5.x_to_10.0.0/nicknames.php, install/mysql/glpi-empty.sql, tests/functionnal/Entity.php
Add a new entity config regarding anonymized helpdesk:
This setting allow tech user to define a nickname in their preferences.
If a nickname is defined for a given user, it will be used instead of his name in the self-service interface.
| Fixed tickets | !21776
=> Anonymized helpdesk: add nicknames

inc/savedsearch.class.php
When GLPI savedsearch parse URL, we ened to check if it from plugins or marketplace folder
| Fixed tickets | Internal 22080
=> fix(savedsearch): determine if path contains marketplace or plugins

inc/ticket.class.php, tests/functionnal/Entity.php
While testing a backport of #9060 I noticed that two fields were missing anonymization:
This PR add correct anonymization for these two fields and add this case to the functional tests.
| Fixed tickets | /
=> Add missing fields to anonymization process

ajax/solution.php, inc/html.class.php, inc/itilsolution.class.php, inc/ticket.class.php
1. When selecting a template, the whole `textarea` was replaced, so the TinyMCE instance was reinit and user mention feature was not working anymore. I reused a similar logic as for followup form to fix this.
2. When an inline image was present in solution added from massive action, some errors were triggered, du to the missing `enctype="multipart/form-data"`.
=> Fix multiple solution form issues

inc/rule.class.php, inc/ruleaction.class.php, inc/ruleticket.class.php, tests/functionnal/Rule.php, tests/functionnal/RuleTicket.php
Following #9052, let's also add the 'global_valdiation' field to the possibles actions.
| Fixed tickets | !21937
=> Ticket rules: add 'global_valdiation' action

inc/commondbtm.class.php, inc/commondropdown.class.php, inc/html.class.php, inc/itilfollowuptemplate.class.php, inc/solutiontemplate.class.php, inc/ticket.class.php
1. Fix display of rich text input in "update" massive action (for followup and solution templates for instance).
2. Disable images pasting in rich text in massive action context (GLPI uploaded images handling does ot permit to reuse multiple times the same uploaded image, as uploaded file is moved once the first document is created).
3. Fix uploaded images handling in CommonDropdown.
=> Fix images handling in dropdown and massive actions

inc/stat.class.php
The list of statistics from plugins is built with the key "plugins".  
refactor code to use ```Plugin::getWebDir```
| Fixed tickets | Internal 22080
=> fix(stat): get real web dir for plugin stats

inc/document_item.class.php
The "Associated items" tab of documents may contain duplicate lines.
This is because some items like followups or tasks are shown as their parent in this tab (since we need a link and we don't have link to this kind of item yet).
This means that if you have a document linked both to a followup and to its parent ticket then the ticket will be shown twice in the list: 
My suggestion is to add a type hint for followup, solutions and task so the users have a bit more information and are aware it isn't a duplicated line but two different links:
| Fixed tickets | !22093
=> Document: handle duplicate links in associated items tab

inc/planning.class.php
There is some timezone issues that affect the planning start date.
For example, if you tried to set a full day event on the first day on the week it would not display correctly:
As you can see on the image it works for the others days in this week view but if I switch to the "day" view it not longer works since the selected day is now at the start date of the view:
It seems the issue is that some dates sent from the client are in UTC while my server is in "Europe/Berlin".
The date received from the client are then casted to an "unix timestamp" with `strtotime` and compared with others dates retrieved by the server using it's own timestamp.
This is an issue as the "unix timestamp" format lose the timezone information so any calculation using dates with a different timestamp will be …
=> Fix planning timezone

inc/notificationeventmailing.class.php
| Fixed tickets | #9075
If `width` or `height` of an img tag is empty, an error is triggered on PHP8. Changing regex to prevent matching when width/height is empty fixes this issue. Also, there is no need to round anymore, as we only extract integer values.
=> Fix fetching of images width/height on notifications; fixes #9075

inc/wifinetwork.class.php
Add the options for 802.11ac and 802.11ax for the protocol version field on WiFi ports.
=> Add WiFi ac and ax versions

inc/notificationtemplate.class.php, inc/notificationtemplatetranslation.class.php
When GLPI try to find translations from notification template for user language (or default language),
if it not found, GLPI do not restore the default language.
To avoid mistake, add empty label ```Default translation```  instead of ```---``` to language dropdown of ```NotificationTemplateTranslation```
| Fixed tickets | !22101
=> fix(core): always restore default language

inc/contract.class.php, inc/infocom.class.php
Before: 
The contract end date appear in red (= expired) despite having an auto renewal policy.
The expired check in Contract::dropdown() doesn't seem to be better: it only take into account the tacit renewal policy if the contract has no duration defined (`'glpi_contracts.duration' => 0,`).
After:
| Fixed tickets | !21598
=> Contract: take renewal into account when checking validity

inc/dashboard/grid.class.php, inc/dashboard/provider.class.php
On the "Ticket summary" card that you can see above, the "To validate" column is filtered on the current logged in user.
This doesn't make sense as the other four columns only filter on status.
| Fixed tickets | !22124
=> Dashboard/TicketSummary: don't filter waiting_validation on current user

inc/ruleimportentity.class.php
Fixes following error:
```
glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: in_array(): Argument #2 ($haystack) must be of type array, string given in /var/www/glpi/inc/rule.class.php at line 1007
Backtrace :
inc/rule.class.php:1007                            in_array()
inc/rule.class.php:1058                            Rule->getTitleAction()
inc/rule.class.php:3185                            Rule->showActionsList()
inc/commonglpi.class.php:656                       Rule::displayTabContentForItem()
ajax/common.tabs.php:106                           CommonGLPI::displayStandardTab()
```
=> Fix entity import rule actions

inc/user.class.php
Users should always be able to update their nicknames, current check on rights was a mistake.
This fix target master and not 9.5/bf as it is a feature introduced in GLPI 10.
| Fixed tickets | !21776
=> Do not require rights to update nickname in user settings

ajax/pendingreason.php, css/styles.scss, front/pendingreason.form.php, front/pendingreason.php, inc/change.class.php, inc/commondbtm.class.php, inc/commonitilobject.class.php, inc/commonitiltask.class.php, inc/dropdown.class.php, inc/itilfollowup.class.php, inc/itilsolution.class.php, inc/pendingreason.class.php, inc/pendingreason_item.class.php, inc/pendingreasoncron.class.php, inc/problem.class.php, inc/profile.class.php, inc/ticket.class.php, inc/user.class.php, install/empty_data.php, install/migrations/update_9.5.x_to_10.0.0/pendingreason.php, install/mysql/glpi-empty.sql, tests/functionnal/PendingReason.class.php, tests/functionnal/Search.php, tests/functionnal/Ticket.php, tests/functionnal/Transfer.php
New dropdown:
You can define the following fields:
New right added for managing pending reasons:
When adding a new followup to a ticket, there is a new "pause" toggle:
Enabling this toggle will set the ticket status to pending and allow you to select a pending reason:
Selecting a reason will display two additional fields: the auto bump and resolve parameters.
Their values will be set to the data defined in the pending reason object but can be modified.
After submitting the previous form, information regarding the pending reason can be found in two places :
1) In the ticket details:
2) In the timeline
Auto bump and auto resolve are handled by a new task:
Followup and solutions are added using a new special user.
This user is added during the migration and can't be deleted.
Only a few …
=> Pending reasons

install/update_91_92.php
Migration from 9.1 to 9.2 adds the `dbversion` config and initializes it with GLPI_SCHEMA_VERSION. Problem is that if migration fails after this point, it will not be possible to replay it.
`9.1.3` was the latest value of `GLPI_SCHEMA_VERSION` in 9.1 version (see https://github.com/glpi-project/glpi/blob/9.1/bugfixes/config/define.php#L40 ).
=> Fix dbversion when migration from < 9.2 fails

css/marketplace.scss, inc/marketplace/api/plugins.class.php, inc/marketplace/controller.class.php, inc/marketplace/view.class.php
Displays plugins in discover page even if plugin is not available for their GLPI version. For instance, on current master branch, no plugins are available, so page is empty.
I put this change on 9.5/bugfixes branch, as I think it could be usefull to be able to promote future new plugins in GLPI 9.5 even if they are only compatible with a newer GLPI version.
=> Do not filter unavailable plugins in marketplace

inc/html.class.php, templates/layout/parts/page_footer.html.twig
While testing a plugin, I made a few commits to allow it to function with the new UI.
- Load Javascript files from plugins
- Support loading core and plugin JS files as modules
- Show 'Never' instead of the start of Unix time when passing a null value to `Html::time2str`
The plugin has a "Last check" field and was showing December 1969 when no checks had been done yet. It was previously using its own method for building relative time strings, but I switched it to use what was provided by GLPI.
=> [Modern UI] Some plugin compatibility

inc/ipaddress.class.php, tests/functionnal/IPAddress.php
Manage  IPV4 dotted-quoad format ::ffff:192.168.1.1 as a real IPV4
| Fixed tickets | #9138
=> feat(core): manage Ipv4 dotted-quoad

inc/dashboard/provider.class.php
When using at the same time the filters
- technician
- technician group
the resulting SQL query contains 2 tables with the same alias "gl".
I guess this is a code copy / paste problem, and despite these filter will unlikely used together, this PR prevents an empty / erroneous card.
=> Avoid conflicting sql aliases

inc/html.class.php
I don't full understand how it happened, but on a modern UI branch I tried logging out while the dashboard was still loading and it redirected me to the login screen with a dashboard AJAX URL set as the redirect. I guess in this edge case, the user should just get redirect to the home page since we cannot tell where they actually came from.
=> Don't redirect to AJAX URLs

inc/itilfollowup.class.php, tests/functionnal/ITILFollowup.php
Currently observers are not anonymized as we assume that they are supposed to be 'end users' and not technicians.
However this is not the only possible use-case, some people might put a mix of technicians and end-users in the observers part.
With these changes : 
- Observer with at least one 'central' profile -> anonymized 
- Other observers -> not anonymized
| Related tickets | !21776
=> Anonymize observers if they have at least one 'central' profile

inc/commonitilobject.class.php, inc/ticket.class.php, tests/functionnal/RuleTicket.php
Master TU are broken
Several elements are involved
- Always prepare user data for rule on update only if we have some changes on ticket
https://github.com/glpi-project/glpi/blob/65df212e2fb8faff3a214a38399a0a3468e56465/inc/ticket.class.php#L1111-L1135
- Capability to use regex to add groups with ```_additional_groups_requesters```
https://github.com/glpi-project/glpi/blob/65df212e2fb8faff3a214a38399a0a3468e56465/inc/ruleticket.class.php#L369-L379
Description :
- Create ```Ticket```
- RuleTicket  add groups to ```_additional_groups_requesters```
- On ``post_addItem``` process ```CommonItilObject ``` add  ```_additional_groups_requesters```  (```addAdditionalActors```)
- Then GLPI try to update ```date_mod``` from main item (```Ticket```)
```prepareInputForUpdate``` detect two key …
```
=> fix(rule): add _groups_id_of_requester to changes only if users change

inc/ticket.class.php
When we split a ticket (Entity A) while using another entity (Root entity) :
The newly created ticket will be in Root entity instead of Entity A:
This is because we don't specify any entity when splitting so GLPI just use the current entity which may differ from the one in the original ticket.
The fix is simply to pass the correct entity to the creation form.
After:
| Fixed tickets | !22234
=> Use correct entity when splitting tickets

CHANGELOG.md, inc/migration.class.php, inc/system/diagnostic/databaseschemachecker.class.php, install/migrations/update_9.5.x_to_10.0.0/impact.php, install/mysql/glpi-empty.sql, tests/units/Glpi/System/Diagnostic/DatabaseSchemaChecker.php, tests/units/Migration.php
Currently, the `positions` field in `glpi_impactcontexts` uses TEXT which can store around 16,383 4-byte characters and each item on the graph seems to take around 60 characters in the JSON (mostly from using 13 decimal places for each coordinate value), leaving room for around 270 items total. In large/complex environments, it may be desired to view more devices all in the same graph.
MEDIUMTEXT would support around 69,905 items in each graph.
=> Support larger impact graphs

inc/ruleright.class.php
You can add new actions for rule through plugins with the `plugin_XXXXX_getRuleActions` hook.
The `executeAction` method for `RuleRight` use only specifics switch/cases values so the extra fields were never taken into account.
To fix this I've added a generic default case.
=> Take extra fields into account when executing a RuleRight

front/user.form.php, inc/auth.class.php, inc/authldap.class.php, inc/user.class.php, tests/LDAP/AuthLdap.php
| Fixed tickets | internal ref !20695
ldap fields match:
- user.name -> sameaccountname
- user.sync_field -> guid
Scenario:
- A user was created in glpi with ldap entry: [sameaccountname = user1, guid = 1]
- The user was deleted from ldap ands kept in GLPI (for history)
- The user is recreated with the same login but another guid [sameaccountname = user1, guid = 2]
- The user cannot login because the glpi entry is locked on the previous sync_field value.
I propose a new action in synchronization tab to clear the sync_field (and force a sync) to fix the last step of the scenarion.
It requires a manual action because the purpose of sync_field …
=> add action button in user synchronization tab to clear ldap sync field

ajax/kanban.php, js/kanban.js
1. AJAX input sent using POST query is already present and sanitized in `$_REQUEST` lines 44 to 51 were useless (unless I am wrong).
2. As items creation input is based on a URL encoded form value, `Toolbox::clean_cross_side_scripting_deep()` had no effect and has to be done once params are extracted from `$_REQUEST['inputs']`.
This change is required to be able to apply #9101 .
=> Fix cleaning of items created from Kanban

inc/ruleticket.class.php, inc/ticket.class.php, tests/functionnal/Rule.php, tests/functionnal/RuleTicket.php
Add capability to aassign appliance from rule (on associated element)
Action : assign,  regex
| Fixed tickets | internal 21617
=> Rule action appliance

inc/notificationeventmailing.class.php
GLPI use `PHPMailer::addAttachment()` to add attachments to emails notifications .
The default encoding used by `PHPMailer::addAttachment()` is base64, this means that every attachments sent by GLPI is base64 encoded.
This is a problem for `message/rfc822 (.eml)` files as they are not allowed to be encoded in base64 according to [RFC2046](https://datatracker.ietf.org/doc/html/rfc2046):
>No encoding other than "7bit", "8bit", or "binary" is permitted for
the body of a "message/rfc822" entity.
| Fixed tickets | !22174
=> Fix encoding for "message/rfc822" attachments

status.php
I missed adding the ability to filter by service through the HTTP endpoint. Service names are the same as shown in the CLI by running the `system:service:list` command. I also added the ability to change the output format using a query parameter for when you cannot change the `Accept` header.
Sample calls:
/status.php?service=db
/status.php?service=db&format=plain
/status.php?service=db&format=json
=> Filter service and change format in HTTP Status endpoint

inc/plugin.class.php, inc/session.class.php
GLPI allow custom locales in `files/_locales`.
Locale for core are placed in `files/_locales/core` and for a given plugin in `files/_locales/given_plugin_name`.
The main issue with this system is that it only allows one folder per locale "namespace".
To improve this I've modified this behavior to look for `files/_locales/core`  AND `files/_locales/core_*`  files.
This means that two  `core_feature1` and a `core_feature2` folders can coexist and add their own locales without having to be merged in one folder.
=> Allow multiple custom locales files

tools/github-nightly-description.sh
Update the nightly description to have something like:
Date|Archive|Size
---|---|---
2021-06-17 00:11:20 UTC|[9.5-bugfixes.ae81ac8.tar.gz](9.5-bugfixes.ae81ac8.tar.gz)|45727045
=> Set build date in table for nightly builds

.eslintrc.json, .github/actions/init_containers-start.sh, .github/actions/init_initialize-imap-fixtures.sh, .github/actions/init_initialize-ldap-fixtures.sh, .github/actions/lint_php-lint.sh, .github/actions/test_install.sh, .github/actions/test_update-from-older-version.sh, .github/workflows/ci.yml, .gitignore, tests/README.md, tests/bootstrap.php, tests/config/.gitignore, tests/router.php, tests/run_tests.sh
Example with install test suite
TODO
=> Add scripts to locally run test suite on CI docker containers

inc/queuednotification.class.php
Since #9011, queued notifications are stored sanitized in DB (https://github.com/glpi-project/glpi/pull/9011/files#diff-6b16f570d485c16ee727417cde892f2f6ae2f43f7ee2ac370c5bdfe15c3beed8R159). Sending from massive actions was not updated to handle that. This PR fixes it.
=> Fix notifications encoding when sent from massive actions

inc/notepad.class.php
I cannot find the previous commit causing this issue, maybe a bad merge
=> remain of dockblock clean on notepad causes fail of notepad display

inc/dbmysqliterator.class.php
DB iterator allow criteria to be placed both inside or outside "WHERE" key. If criteria are present on both place, thoose in "WHERE" key will be ignored.
I propose to add a warning, in order to prevent potential issues.
=> Check for criteria conflicts (inside and outside "WHERE" key); see #8670

inc/transfer.class.php, tests/functionnal/Computer.php, tests/functionnal/Transfer.php
The 'keep_software' option wasn't working properly due to being conditioned by the existence of items in the `$this->noneedtobe_transfer['SoftwareVersion']` property.
This `noneedtobe_transfer` property keep track of software that don't need to be transferred as they need are already valid for the new entity (is_recursive).
It should have no impact on the transfer beside preventing a few software from moving, but currently it block the whole process if there is noting in the property.
Fix was simply to move the condition lower in the code so it only impact the `WHERE` clause of the SQL request that use it's content.
| Fixed tickets | !22301
=> Transfer: fix 'keep_software' option

inc/search.class.php, tests/functionnal/Toolbox.php
Since adding the multi-sort feature for the Search engine, the map view showed an array to string conversion warning. This properly handles converting the new sort/order arrays into query string parameters.
I also added tests for `Toolbox::append_parameters` since none existed.
=> Fix array to string warning and add append_params tests

front/contract_supplier.form.php
| Fixed tickets | #8521 
Display a better error message when trying to associate no contract with a supplier.
Same as #4308 but for this specific case that is handled in a different front file.
=> Add better error for unselected contract for suppliers

front/ticket.php
| Fixed tickets | #9006 
Only applies to 9.5.X since 10.0.0 implements an AJAX-based refresh for search lists.
Since the `manageRefresh` function already puts the refresh code inside `setInterval` instead of `setTimeout`, we just need to check if a modal is open and skip the current refresh period.
I only did this for the ticket list in case some other code relies on refreshing while a modal is open.
=> Suppress ticket list refresh when modal open

front/helpdesk.php
| Fixed tickets | #8510
If anonymous helpdesk is not enabled, redirect to the central page (which would redirect to the login if not logged in).
=> Don't display public ticket form if not enabled

inc/commondbtm.class.php, inc/computer.class.php, tests/functionnal/CommonDBTM.php, tests/functionnal/ITILSolution.php, tests/functionnal/ProjectTask.php, tests/functionnal/TicketTask.php, tests/units/Migration.php
`CommonDBTM::$fields` property may be inconsistent. When adding or updating such an object; `fields` property is populated from `input` property, which is sanitized. When loading from DB, the `fields` property is loaded verbatim (ie. not sanitized).
This can cause difficult to handle cases, with required extra decoding.
The change may seem huge; but I do not think this would break. Indeed, this change would just make any extra `stripslashes` (and others) useless; calling such methods on clean data should not be a big issue; there were only a few problems in core right now.
=> Fix fields consistency on add/update

inc/commonitiltask.class.php
Added missing _ in front of status
=> Fix PHP notice when changing ITIL status from task form

inc/ticket.class.php, tests/functionnal/Ticket.php
| Fixed tickets | #9193
When a collected mail contains both external and embedded images, some content was sometime stripped due to usage of a wildcard in regex.
=> Fix handling of images in mail collector; fixes #9193

inc/commonitilobject.class.php, tests/DbTestCase.php, tests/functionnal/Ticket.php
Validators aren't allowed to add followups to tickets.
It seems useful to allow them to add followups for the tickets they validate, in case they need to add some additional informations later.
Changes:
* Allow validator to add followups for tickets they validate (new function CommonITILObject::isValidator + tests)
* Improve readability of canAddFollowups conditions
* Add a new `createItems` function in tests to avoid writing the same boiler plate code every tests.
Side note as it isn't related to the PR changes but having to check "manually" if validation is enabled on an itemtype (`if (!$this instanceof Ticket && !$this instanceof Change)` and building "manually" the validation class (`$validation_class = static::class . "Validation";`) should IMO be done with more robust polymorphic …
=> Allow validators to add followups

inc/commonitilobject.class.php
The tickets stats are confusing for the users because the times are computed according to their custom calendar but are displayed as 24 hours days.
It seems best to avoid this issue by displayed the duration in hours so there is no possible misinterpretation for the user.
**Before:**
**After :**
| Fixed tickets | !22239
=> Do not display tickets stats in days

inc/user.class.php
On main tab for personal settings
=> Fixed missing empty choice string for timezone settings

inc/ruleticket.class.php
Follows #6907 .
Sometimes, the `appendto` field is the exact same as the field where assigned value is stored (see https://github.com/glpi-project/glpi/runs/3006356686?check_suite_focus=true).
I propose to limit cleaning to fiels prefixed by `_additional_`, which corresponds to additionnal actors set by `append` rules.
=> Fix "appendto" cleaning in assign rules

inc/savedsearch.class.php
Private searches do not take entities restriction into account when being loaded into the right side pannel.
This may be done on purpose to always show the private ones ? 
It seems a bad idea because it show inconsistent data between the side panel and the saved search management page (which take the correct entity settings into account).
For example let's take this saved search: 
It is a private search on root entity with no recursion.
-> If I switch to a subentity, I get this conflicting data:
The search is shown on the right panel but not on the main page.
To prevent this I've applied the entity restriction to the right panel.
After:
This time the data is consistent: 2 items on both sides.
| BC breaks? …
=> Restrict private saved seaches to current entities

inc/savedsearch.class.php, install/migrations/update_9.5.x_to_10.0.0/savedsearch.php, install/mysql/glpi-empty.sql
path can be derived from itemtype
Ths PR fixes problem when a plugin is moved between marketplace folder and plugins folder, and GLPI has a saved search in one of its itemtypes. After move of the plugin, the path becomes invalid.
=> remove path column from savedsearches

inc/console/ldap/synchronizeuserscommand.class.php
Unless I am wrong, when running the `AuthLDAP::ACTION_ALL` synchronization mode, users that are not returned by LDAP are considered as deleted on LDAP side. So, in theory, if users try to run this synchronization mode using date filtering, most of users will not be returned and will de beleted/deactivated/whaterver in GLPI, depending on configured deletion strategy.
=> Prevent usage of date filters on full LDAP sync

inc/commonitilobject.class.php
While doing some SLA/TTR tests for !22239 I came across an issue.
Let's take two ticket.
Both tickets are expected to be solve in 5 min (this is a very efficient support i guess).
One ticket is immediately resolved:
The other is immediately resolved and closed:
Stats seems OK for now on both tickets.
Let's wait 5+ mins and reopen both tickets:
Ticket 1:
Ticket 2:
The stats of the first ticket are still OK because the time spent as resolved was considered as "waiting time" so we are still good on our 5 min TTR.
The stats of the second tickets are KO because the time spent as closed was not added into the waiting time so the 5 min TTR is expired.
To fix this I've made sure the time spent as closed is added in the waiting time when the ticket is reopened.
| ------------- …
=> Ticket: Add time spent in closed status to waiting_duration when the ticket is reopened

inc/caldav/traits/vobjectconvertertrait.class.php, inc/commondbtm.class.php, inc/commonitiltask.class.php, inc/knowbaseitem.class.php, inc/notificationtemplate.class.php, inc/project.class.php, inc/projecttask.class.php, inc/search.class.php, inc/toolbox/dataexport.class.php, inc/toolbox/richtext.class.php, tests/units/Glpi/Toolbox/DataExport.php, tests/units/Glpi/Toolbox/RichText.php
1. Fix stripping of tooltips in exported data.
2. Remove inlined links from exported data. These links were not present in GLPI 9.5 and adding them seems not a good idea. Indeed, they are polluting data and are usually not really usefull (see below image).
=> Fix data export (CSV, SYLK)

inc/networkportinstantiation.class.php
Fix undefined index `locations_id` notice on Cluster network port form.
=> Fix undefined index locations_id

inc/dashboard/provider.class.php
- fix technician filtering
- SLA cards should show in priority statistics where SLA are not satisfied. To achieve this, this PR reverts the order of data when series are built.
Using array_unshift requires to update the way to detect empty series.
=> Improve tech filter sla card

js/modules/Search/Table.js
Needed for `dev` plugin which has a WIP feature that adds a new action to the Plugins search results.
Since the search results can update without a page reload, we need a way to notify that search result customizations need re-applied. In this case, it is used to know to re-add the custom actions.
=> Add search refresh event

css/includes/components/_pictures.scss, templates/components/form/fields_macros.html.twig, templates/components/itilobject/timeline/sub_documents.html.twig, templates/components/photoswipe.html.twig
Needed for screenshot plugin which has the ability to create and attach screen recordings directly from the ticket timeline. This will allow users and technicians to view these recordings directly from the timeline rather than forcing the user to download the video or having to open it in a new tab in order to view it.
Images and videos may be present in the same gallery.
Videos in the timeline have a placeholder "thumbnail" using `fas fa-video`. I don't think having a proper thumbnail will be possible without a library like `php-ffmpeg`.
This PR also has a fix for having multiple galleries on the same page. Each gallery …
=> [Modern UI] Video Lightbox

inc/glpi.class.php, inc/mailcollector.class.php, tests/GLPITestCase.php, tests/imap/MailCollector.php
`mailgate.log` contains just summary information of errors that can happen during mail collect.
Adding the full trace of exceptions in GLPI error log may help to invatigate on errors.
Example of exception log:
```
==> files/_log/php-errors.log <==
[2021-07-15 09:25:28] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Storage\Exception\InvalidArgumentException: Header with Name message_id or message_id not found in /var/www/glpi/vendor/laminas/laminas-mail/src/Storage/Part.php at line 307
Backtrace :
inc/mailcollector.class.php:1455                   Laminas\Mail\Storage\Part->getHeader() …
```
=> Log mailcollector exceptions

inc/agent/communication/abstractrequest.class.php
Fixes following issue.
```
glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to private method Glpi\Agent\Communication\AbstractRequest::setMode() from scope Glpi\Inventory\Request in /var/www/glpi/inc/inventory/request.class.php at line 93
Backtrace :
inc/inventory/request.class.php:71                 Glpi\Inventory\Request->prolog()
...ent/communication/abstractrequest.class.php:237 Glpi\Inventory\Request->handleQuery()
...ent/communication/abstractrequest.class.php:194 Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
front/inventory.php:54
```
=> Fix prolog request handling

inc/inventory/asset/drive.class.php, inc/inventory/asset/harddrive.class.php
Very little cleanup as `storages/serialnumber` has still been replaced in inventory_format specs by `storages/serial`.
=> Cleanup other obsolete inventory property

inc/blacklist.class.php
Fix the following error blocking inventory import:
```
[2021-07-21 15:30:33] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Cannot use object of type stdClass as array in /var/www/glpi/inc/blacklist.class.php at line 506
Backtrace :
inc/inventory/asset/inventoryasset.class.php:161   Blacklist->processBlackList()
inc/inventory/asset/mainasset.class.php:566        Glpi\Inventory\Asset\InventoryAsset->handleLinks()
inc/ruleimportasset.class.php:922                  Glpi\Inventory\Asset\MainAsset->rulepassed()
inc/rule.class.php:1437                            RuleImportAsset->executeActions() …
```
=> fix: inventory import fails on found blacklisted value in model fields

inc/devicefirmware.class.php
The date of firmware components is a release date, not an installation date.
=> Fix firmware component date label

inc/application/view/extension/htmlextension.class.php, inc/notificationmailing.class.php, templates/components/form/fields_macros.html.twig, templates/components/itilobject/selfservice.html.twig, templates/components/itilobject/timeline/form_followup.html.twig, templates/components/itilobject/timeline/form_solution.html.twig, templates/components/itilobject/timeline/form_task.html.twig, templates/components/itilobject/timeline/simple_form.html.twig, templates/dropdown_form.html.twig
Almost all values that are rendered in templates are either a runtime generated html (like a link or a tooltip) or a "sanitized" value (like an item field value). Both of them are so already "escaped" (in a Twig point of view) and must be printed with a `|raw` filter.
There is 2 problems with this.
First, it may happen that an item field value has been generated on runtime and is not "sanitized", so using the `|raw` filter may introduce a security issue.
Second, in the future, we may want to remove the sanitize process. If we use the `|raw` filter for both legitimate HTML and "sanitized" values, it will be hard to …
=> Handle display of itemtype fields values

inc/transfer.class.php
with the current code, if a network port is added to a new device type the networkport transfer actions won't work
| Tests pass?   | --
=> FIX: remove hardcoded configuration for network port transfert

inc/application/errorhandler.class.php, inc/application/view/extension/ajaxextension.class.php, inc/application/view/extension/alertextension.class.php, inc/application/view/extension/commonitilobjectextension.class.php, inc/application/view/extension/configextension.class.php, inc/application/view/extension/csrfextension.class.php, inc/application/view/extension/dbextension.class.php, inc/application/view/extension/documentextension.class.php, inc/application/view/extension/dropdownextension.class.php, inc/application/view/extension/entityextension.class.php, inc/application/view/extension/eventextension.class.php, inc/application/view/extension/frontendassetsextension.class.php, inc/application/view/extension/htmlextension.class.php, inc/application/view/extension/i18nextension.class.php, inc/application/view/extension/infocomextension.class.php, inc/application/view/extension/itemtypeextension.class.php, inc/application/view/extension/modelextension.class.php, inc/application/view/extension/numberformatextension.class.php, inc/application/view/extension/pluginextension.class.php, inc/application/view/extension/richtextextension.class.php, inc/application/view/extension/routingextension.class.php, inc/application/view/extension/searchextension.class.php, inc/application/view/extension/sessionextension.class.php, inc/application/view/extension/toolboxextension.class.php, inc/application/view/extension/userextension.class.php, inc/application/view/extension/validationextension.class.php, inc/html.class.php, templates/components/logs.html.twig, templates/layout/parts/global_search_form.html.twig
Multiple fixes for modern UI branch
Fixes:
- Plugin menu icon was not shown because the `fas` class was missing on the icon element
- The inclusion of some TInyMCE plugins was causing a JS console warning since they have been included in the TinyMCE core since 5.0 (3 years ago).
- Implementing ExtensionInterface on GLPI's Twig extensions is redundant because AbstractExtension already implements this interface.
- Use static closures when access to instance properties are not required to improve performance.
- Add/fix multiple parameter and return types
- Fixed ignored `entity_restrict` in …
=> [Modern UI] Muliple FIxes

ajax/itilfollowup.php, ajax/solution.php, ajax/task.php, inc/abstractitilchildtemplate.class.php, inc/contenttemplates/templatemanager.class.php, inc/itilsolution.class.php, inc/ticket.class.php
When adding #9291, we forgot a specific case: it is possible to solve a ticket using a template through the massive actions.
This is not supported by the initial PR because we render the template when it is loaded into the form but this is not possible for this case as we do not have a given item to use as parameter (instead we have multiples items and the template should be rendered differently for each of these items).
The proposed solution is, for this specific case, to not render the template in the form.
Instead, we do it in the `prepareInputForAdd` function.
Example:
1) Using massive actions:
2) Ticket 102:
3) Ticket 95: 
| Fixed …
=> Twig support in emplates: Fix massive actions

css/includes/_dark.scss, css/includes/_global-variables.scss, css/palettes/_auror_dark.scss, inc/dashboard/grid.class.php, inc/toolbox.class.php, lib/bundles/base.js, package-lock.json, package.json, templates/components/form/fields_macros.html.twig
small changes to permits usage of opacity for cards background in dashboards.
The change in `Toolbox::getFgColor` permits to match the general background by giving an `inherit` value, usefull for dark thme
=> permits to set transparent color in dashboard cards

ajax/kanban.php, css/includes/components/_kanban.scss, front/change.form.php, front/problem.form.php, front/ticket.form.php, inc/commonitilobject.class.php, inc/define.php, inc/item_kanban.class.php, inc/project.class.php, js/kanban.js
Expand supported Kanban types to include ITIL Objects to offer a new way to view service requests, changes, and problems.
Done:
- Drag and drop between columns to change status
- Built-in state saving for card ordering
- Show/hide columns based on the ITIL Object's statuses
To do:
~A quick warning if testing: There is currently no limit to the number of cards shown in the closed column so having a large number of closed items will cause performance issues.~
~Also, since this was initially done before the Modern UI work, it relies on jQuery dialogs as does the existing Kanban code to view the items in a Kanban. You won be …
=> ITIL Object Kanban Views

inc/html.class.php
Color palette are currently loaded before plugins css.
It is common for experienced user to create their own palettes thus making it possibly a "user defined style" (like editing css in the entities).
I think this kind of styles are best loaded last so they are no overwritten by any "programmer defined styles".
| Fixed tickets | !22428
=> Load palette after plugins

front/itilfollowup.form.php
When an item is re-open (like a ticket) it proposes a followup to input reason, but after post of the followup, it proposes again a followup creation.
| Fixed tickets | #
=> To prevent followup creation form after re-open of an item

package-lock.json, package.json, webpack.config.js
Since we use Webpack css-loader > 6.0.0, we can directly handle CSS assets with [asset modules configuration](https://webpack.js.org/guides/asset-modules/).
See css-loader changelog: https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#600-2021-07-14
=> Switch from file-loader to Webpack asset modules

inc/dropdown.class.php
$itemtype is used only in case of stat, all the other cases don't need params, without default it create a compatibility issue with reports plugin (and I guess other piece of code)
| Bug fix?      | yes (but on master)
=> retro compatibility

inc/agent/communication/abstractrequest.class.php
When JSON response contains sub array ```addEntry``` is broken
I proposed to directly set the response rather than processing it and redoing a array
=> fix(communication): do not rework response

inc/agent.class.php
Allow plugins to call ```requestAgent```
=> feat(agent): allow plugin to request agent

README.md
See https://mail.ow2.org/wws/arc/glpi-dev/2020-02/msg00000.html : packages will stay on 9.4 version.
As mentioned on the support lifecycle, 9.4 version is unmaintained by the GLPI team.
Thank's to Remi for the long time work in order to maintain theses packages !
=> Remove Remi's RPM source (unmaintained)

ajax/kanban.php, js/kanban.js
1. The delete action was not working, as form data was sent with an `application/json` content type instead of the default `application/x-www-form-urlencoded`.
2. add/bulk_add actions were not working anymore due to #8763. Indeed `&` char is now transformed, so parsed `inputs` were invalid (see below). Using the raw POST fixes this.
3. Having a `null` value on project/projecttask content may result in issues, for instance while this content is handled by `Glpi\Toolbox\RichText` methods which are not expecting to receive a null value. Defining `content` field with an empty string fixes this.
=> Fix kanban add/delete actions

inc/search.class.php
Before fix, the SQL request try to match the status constant (2) with an id:
After: 
| Fixed tickets | !22444
=> Fix search on changes validation's status 

inc/mailcollector.class.php, tests/emails-tests/27-autoreply.eml, tests/imap/MailCollector.php
| Fixed tickets | #9306 
When an e-mail is received from a mailer-daemon/postmaster address, header parsing is skipped, so default rule that is made to reject e-mail having a `Auto-Submitted: auto-replied` header cannot match, and e-mail is not refused.
Depending on GLPI configuration, it can lead to different results:
- if anonymous ticket creation is not allowed, ticket will be refused as sender address is empty (due to lack of headers parsing);
- if anonymous ticket creation is allowed, a ticket will be created, which should not happen, according to rules.
The removed piece of code is really old (introduced in commit …
=> Fix handling of mailer-daemon e-mails in collector; fixes #9306

.github/workflows/ci.yml, .github/workflows/nightly_build.yml, README.md, composer.json, composer.lock, inc/define.php, index.php, tests/run_tests.sh
Debian Bullseye has been released on 2021-08-14, and so all major Linux distibutions are proposing PHP 7.4 as their default PHP version.
Thus, PHP 7.3 active support has already ended and security support will end on december.
Dropping PHP 7.3 support will unblock updating of some dependencies. This is limited to `symfony/console` for now, but PHP 7.3 support dropping already started on some projects (laminas for instance).
Using PHP 7.4 will also permit to use, among others, [type hinting for classes properties](https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.core.typed-properties) and …
=> Drop PHP 7.3 support

front/report.infocom.php
| Tests pass?   | ??
The asset types in the report were ard coded, this change use the `infocom_types` as reference and then do the report for the one that does have a field called ticket_tco (name is misleading by the way, should be asset_tco)
=> Display infocom report for all `infocom_types` compatible items

inc/central.class.php, templates/central/widget_tab.html.twig
1. All cards are using the `lazy` type. `raw` and `table` types are not used.
2. `title` property is never set.
3. All cards have the same body class (`p-0`).
4. `_idor_token` is inside params, so `data-idor` is always empty, thus it was not used.
=> [Modern-UI] Simplify central cards code

inc/authldap.class.php
If you have multiple ldap sources, a user who fail his password may be considered as deleted from the ldap.
This is because `AuthLdap::tryLdapAuth()` keep only the state of the last ldap connection tested.
So if the user is found on the first ldap but not on the second one then it will be considered as missing from the ldap and trigger the `User::manageDeletedUserInLdap` policy :
To fix this `user_found` must be true if the user was found on any ldap, not just the last one.
| Fixed tickets | !22420
=> Fix $auth->user_found for multiple ldaps

front/report.contract.list.php
Report by contract was failling because of missing location_id in clusters, the change simply set the location complete name to  empty string
| Fixed tickets | None created
=> Fix: report by contract failing

inc/dbutils.class.php, inc/toolbox/sanitizer.class.php, tests/functionnal/DbUtils.php, tests/units/Glpi/Toolbox/Sanitizer.php
1) Fix sanitized string detection.
2) Ensure `autoName` is compatible with both old and new "XSS cleaning" process.
Bonus: `autoName` is now also compatible with non sanitized value, and will return a non sanitized value in this case.
=> Fix autoName with new XSS clean chars

inc/features/inventoriable.class.php
Better way to find agent linked to asset if if we have more than one agent linked
Returns the last agent that contacted GLPI
=> fix(inventoriable): better way to find agent

css/styles.scss, front/contenttemplates/documentation.php, inc/abstractitilchildtemplate.class.php, inc/contenttemplates/parameters/abstractparameters.class.php, inc/contenttemplates/parameters/assetparameters.class.php, inc/contenttemplates/parameters/commonitilobjectparameters.class.php, inc/contenttemplates/parameters/dropdownparameters.class.php, inc/contenttemplates/parameters/knowbaseitemparameters.class.php, inc/contenttemplates/parameters/levelagreementparameters.class.php, inc/contenttemplates/parameters/parameterstypes/abstractparametertype.class.php, inc/contenttemplates/parameters/parameterstypes/arrayparameter.class.php, inc/contenttemplates/parameters/parameterstypes/attributeparameter.class.php, inc/contenttemplates/parameters/parameterstypes/objectparameter.class.php, inc/contenttemplates/parameters/parameterstypes/parametertypeinterface.class.php, inc/contenttemplates/parameters/supplierparameters.class.php, inc/contenttemplates/parameters/templatesparametersinterface.class.php, inc/contenttemplates/parameters/ticketparameters.class.php, inc/contenttemplates/parameters/treedropdownparameters.class.php, inc/contenttemplates/parameters/userparameters.class.php, inc/contenttemplates/parameterspreset.class.php, inc/contenttemplates/templatedocumentation.class.php, inc/contenttemplates/templatemanager.class.php, inc/html.class.php, inc/ticket.class.php, inc/toolbox/markdownbuilder.class.php, tests/functionnal/Glpi/ContentTemplates/Parameters/AbstractParameters.php
Related: #9291, #9325.
Added an "in place" documentation for the twig templates variables, similar to what we use for the API
The first section of the documentation contain the exposed "root" variables in the current form.
The following sections contains the dependencies of these root variables.
For example if the root variable have a `TicketParameter` then we have a `Ticket` dependencies with all the ticket fields displayed.
Each dependency may have its own dependencies (the entity of the ticket, the category, ...) that will also be displayed in their own sections.
| Fixed tickets | !22419
=> Twig content templates in place documentation

CHANGELOG.md, inc/dbmysql.class.php, tests/units/DB.php
Support more complex transactions using savepoints (InnoDB feature).
See https://dev.mysql.com/doc/refman/5.6/en/savepoint.html
Added new `DBMysql::setSavepoint` method to add a savepoint within a transaction. The `force` parameter here can be set to true to start a transaction if one isn't started already.
The `DBMysql::rollBack` method was changed to allow a `name` parameter. If specified, it rolls back to the specified savepoint.
The mysqli extension only seems to be able to create and release (remove without rollback or commit) savepoints, but not rollback to them so it has to be done with a raw query.
=> DB Transaction Savepoints

inc/agent/communication/abstractrequest.class.php, inc/inventory/inventory.class.php, inc/inventory/request.class.php
Improve communication ```CONTACT``` and ```GET_PARAMS``` protocol
By default GLPI send this
```php
$response = [
'expiration'  => self::DEFAULT_FREQUENCY,
'status'     => 'ok'
];
```
improve ```CONTACT``` and allow the plugin to add information to the response (for database plugin for the moment)
```php
array (
'expiration' => 24,
'status' => 'ok',
'tasks' => 
array (
'inventory' => 
array (
'params' => 
array (
0 => 
array (
'category' => 'database',
'use' =>  //agent module
array (
0 => 'mysql',
1 => 'oracle',
),
'params_id' => 3, //object containing more info
),
),
),
),
)
```
Manage ```GET_PARAMS``` when agent need more information (and allow the plugin to add information to the response)
```php
array (
'expiration' => 24,
'status' => 'ok',
'credentials' => 
array (
0 => 
array (
'id' …
```
=> feat(inventory): improve comunication protocol

inc/notificationtemplatetranslation.class.php
=> fix(richtext): use richtext instead of textarea

inc/infocom.class.php
Prevent warning from infocom when ```Amortization duration``` is 0
| Fixed tickets | 21118
=> fix(infocom): prevent 'division by zero' warning

inc/databaseinstance.class.php, tests/functionnal/DatabaseInstance.php
Delete massive action is broken (GLPI display 'Purge' but item is only deleted and the next step 'purge' not working)
because of ```is_deleted``` and ```is_dynamic``` fields.
like computers,  ```DatabaseInstance``` need to return false when ```Massiveaction``` class check for ```useDeletedToLockIfDynamic```
=> fix(massiveaction): fix databaseinstance massive action

install/empty_data.php
To prevent an undefined index on `system_user` configuration entry (apparently missed in #8706)
=> Missing config entry at install

inc/planning.class.php
I found some invalid planning data on an instance:
It seems the code in `Planning::showSingleLinePlanningFilter()` expect a "type" key for each items, which you can see is missing for "user_22043" in the screenshot above.
This throw an exception and prevent the whole planning from loading as some mandatory code is never executed and we end up with null references.
These changes prevent the planning from failing to load in case of faulty data.
It would also be nice to fix the source that add this incorrect data but I was unable to find it (this data come directly from the database so it isn't easy to find its origin).
| Fixed tickets | !22513
=> Add safety check on planning data

inc/user.class.php
I've noticed a few weird values in the users dropdown: 
It turns out to be a side effect of the new 'Myself' search criteria and PHP weird type casting for loose comparisons:
This issue is only present on PHP 7 as [saner string to number comparisons](https://www.php.net/releases/8.0/en.php#saner-string-to-number-comparisons) were introduced in PHP 8.
=> Fix empty value for user dropdown

inc/commondbtm.class.php, inc/document.class.php, inc/toolbox.class.php, tests/functionnal/Document.php, tests/functionnal/Toolbox.php
To fix some issues in Formcreator I need to create target tickets or target changes with special handling of inline images (added in a textarea question). The best solution is to process them as file uploads aas if the target is created from regular UI.
To complete this purpose, I need to use some lines of code from the core, but want to avoid duplication.
PR in Formcreator: https://github.com/pluginsGLPI/formcreator/pull/2320/files
=> Split code of uploaded files handling methods

inc/entity.class.php
Minor correction as the bug doesn't affect usage, but we have a browser warning indicating usage of duplicates id in DOM
=> avoid duplicate id usage in dom for entity selector

templates/components/form/header.html.twig
=> fix overlap of template name field with header's ribbon

inc/abstractrightsdropdown.class.php
A deprecation warning generates invalid json for the dropdown.
=> fix profile / group / user dropdown

inc/abstractrightsdropdown.class.php, inc/html.class.php, inc/netpoint.class.php
Bad behavior of technician filter on dashboards : the filter allows multiple selection but should allow selection of one item only.
I think there is currently only one multiple selection ajax dropdown (the new abstract rights dropdown made by @AdrienClairembault ), but I may be wrong.
=> explicit multiple selection mode for ajax dropdowns

bin/console
Replaces #9489 as we do not want to switch to lockfile v2 since npm v7 is not yet available in node LTS bundles.
=> Preserve npm lockfile version during dependencies install

inc/search.class.php, tests/functionnal/Search.php
| Fixed tickets | !22385
More global solution than #9329 .
The generic JOIN logic tries to find a link between main item and meta item through either `{$from_type}_Item` and `{$to_type}_Item`  types. The problem was that both types may exist, and JOIN has to be made on the right one.
For example, when searching form a `Computer` that has a specific `OperatingSystem`, JOIN chain was `glpi_computers -> glpi_computers_items -> glpi_operatingsystems` instead of `glpi_computers -> glpi_items_operatingsystems -> glpi_operatingsystems`.
So I keep the original generic logic, but I added a check based on `$CFG_GLPI[*_types]` (the same one that is used …
=> Fix meta JOIN

inc/databaseinstance.class.php, inc/define.php
Meta search options are based on `*_types`. As items are linked to `DatabaseInstance`, corresponding config key has to be `databaseinstance_types`.
=> Fix meta search on database instances

css/includes/components/_global-menu.scss, templates/layout/parts/menu.html.twig
=> icons in menu label should have a spacing (was broken in horizontal menu)

inc/softwarelicense.class.php
Missing license status columns in software > license tab
=> fix add status column in software licence

inc/commonitilobject.class.php, inc/itilsolution.class.php, inc/notificationtargetcommonitilobject.class.php, inc/notificationtemplatetranslation.class.php, install/empty_data.php, tests/functionnal/NotificationEventAjax.php, tests/functionnal/NotificationTargetTicket.php
Add new tags to display timeline items (```Followup```, ```Task```, ```Solution```) (not private)
```##lang.timelineitems.author##``` ```##timelineitems.author##```
```##lang.timelineitems.description##``` ```##timelineitems.description##```
```##lang.timelineitems.date##``` ```##timelineitems.date##```
```##lang.timelineitems.position##``` ```##timelineitems.position##```
```##lang.timelineitems.type##``` ```##timelineitems.type##``` (internal ref ex: TicketTask (usefull for css class name))
```##lang.timelineitems.typename##``` ```##timelineitems.typename##``` (ex: Ticket task)
Compliant with ```##FOREACHtimelineitems##``` and ```##ENDFOREACHtimelineitems##```
```##timelineitems.position##``` and ```##timelineitems.type##``` is used  for CSS 
Example
| ------------- …
=> Add ##timeline## tag for notifications

inc/dbmysql.class.php
`DbMysql::areTimezonesAvailable()` is called in the database initialization process, thus for every page and AJAX request.
This means 10+ execution of `SELECT count(*) FROM mysql.time_zone_name` for each page of the application, see this example of executing a simple search request: 
It seems to scale up for each plugin installed since we add another ajax call to `locale.php` by installed plugin.
Despite the fast that this request is extremely fast, it seems to create performance issue in the related internal ref when there is a lot of users on the application.
I suspect the issue to be linked to the internal ref specific environment since we never had any feedback on this before (and I suspect this is not the only query that is executed for each page and ajax request so why would it be a …
=> Add cache for areTimezonesAvailable

inc/update.class.php
Since 9.4.0, update process forces the Telemetry task state to `WAITING` even if it was disabled (meaning user did not gave its consent to send Telemetry information).
=> Do not reset Telemetry task state if disabled

inc/notificationtargetplanningrecall.class.php
In Planning recall notifications is missing the 'group in charge of the task'
=> Added missing 'group in charge of the task'

inc/notificationtemplate.class.php, tests/functionnal/NotificationTemplate.php, tests/functionnal/NotificationTemplateTranslation.php
When cloning a notification template, the translations were not cloned.
Add 'clone' in copy name to distinguish both.
| Fixed tickets | !22623
=> FIX: clone notification template

inc/telemetry.class.php
On some edge cases, even if hostname can be resolved, request to the server may fail.
=> Prevent warning during server headers fetching (Telemetry); fixes #2856

inc/search.class.php, tests/functionnal/Search.php
Bug reported by @cedric-anne.
The search engine throw some warning when searching for a very specific query:
This seems to be introduced by c4c332dd1ace71bc7960d8b86e3a175f9c0d3b0d which override the `$searchopt` variable when a meta criteria is present.
This lead to undefined indexes as some part of the code tries to fetch fields from the original value of `$searchopt`.
The "override" from c4c332dd1ace71bc7960d8b86e3a175f9c0d3b0d  can't just be reverted because it seems to be needed for some search options to run (`testSearchAllMeta` will fail if removed).
Fix seems to be keeping the original `$searchopt` value for some calls and send the alternate `$meta_searchopt` to others.
| …
=> Search engine: Fix group criteria after meta criteria

inc/cartridge.class.php, inc/commondbchild.class.php, inc/consumable.class.php, inc/printer.class.php
| Fixed tickets | #8218
Fix I initially proposed on https://github.com/glpi-project/glpi/issues/8218#issuecomment-724065718
1. Cartridge is a CommonDBRelation
2. When a printer is cloned, its cartridge should not (and cannot) be cloned, as a cartridge cannot be on 2 distinct printers.
I targeted master branch, as changing extended class may have side effects.
=> Fix printer cloning/creation from template

inc/search.class.php
| Fixed tickets | #9566
Since #9131, some fields values are "formatted" as numbers if their value contains numerical chars.
I removed formating of `itemlink` and `boolean` SO as well as thoose which have no specific datatype.
=> Fix numbered values display in search results; fixes #9566

inc/ruleticket.class.php, install/migrations/update_9.5.x_to_10.0.0/ruleticketaction.php, tests/functionnal/RuleTicket.php
Currently the `itilfollowup_template` and `task_template` use the `assign` action type.
The `append` action type seems more logical (you "add" a followup to ticket) and allows multiple followups or task per rule.
| Fixed tickets | !22632
=> Change action_type for itilfollowup_template and task_template

front/event.php, js/modules/Search/Table.js, templates/components/logs.html.twig, templates/components/pager.html.twig, templates/components/search/display_data.html.twig, templates/pages/admin/events_list.html.twig
1. I put back href that was removed in #9058. `e.preventDefault();` set by search page AJAX logic will result in ignoring this.
2. From items log, the default `reloadTab()` logic is done.
3. From events list, as we are not in a tab context, href and its additionnal params must be explicitely passed to the template, as it was already done for the limit dropdown template include.
4. I moved the template file in a lower level, as it is not only related to the search feature.
=> [Modern UI] Fix pager in item log and events list

inc/plugin.class.php, inc/session.class.php
Introduced by 53bc94e2ba7b2ac959f15da06e975a850cc0f5c7.
The commit above assume the `_locales` folder always exist.
Despite the folder being a part of GLPI since 9.5.0, this is not always the case as users will copy their "outdated" `files` folder when upgrading from older versions.
| Fixed tickets | :22665
=> Check if _locales exist

tools/build_glpi.sh
| Fixed tickets | #9597 
Scripts are already executed by dependencies install on line 46.
=> Prevent scripts to be executed twice in build process; fixes #9597

inc/commondbtm.class.php
Like document upload form (from timeline)
docs / images paste or drop into richtext need to be no recursifs.
| Fixed tickets | !22626
=> fix(doc): no recusivity for upload doc from richtext

templates/dropdown_form.html.twig
1. Aditionnal fields code was duplicated outside the `{% for field in additional_fields %}` loop, certainly due to a bad merge.
2. Aditionnal fields were nos available for new items due to `item.fields['id'] != 0` condition, which, I guess, was unvoluntarly applied to all fields, instead of being only applied to `entities_id` field (i.e not parent entity selection when on root entity form).
=> [Modern-UI] Fix dropdown forms

inc/search.class.php
To reproduce:
1. create a Computer in root entity + child entities
2. go in a sub entity
3. display the computers list
-> the massive action checkbox should not be displayed, as item is not updatable when displayed outside its own entity context
Check was based on `item` variable, that was not passed to the template (`{% elseif item is instanceof('CommonDBTM') and item.maybeRecursive() and not has_access_to_entity(row['entities_id'])  %}`).
=> [Modern UI] Fix massive action box display checks

inc/commonitilobject.class.php, inc/notificationtargetcommonitilobject.class.php, tests/functionnal/Entity.php, tests/functionnal/NotificationTargetTicket.php
Fix visibility of private items for self-service profil.
Use ```getTimelineItems```  means the use of sessions to check rights
But from ```NotificationTargetCommonITILObject``` all target have no session (except the current user who triggers the notification)
We need to know if target is a self-service or not to restrict view for private items because 
```show_private``` is combinated to ```bypass_right```
This notion of ```is_self_service``` is introduce by 
https://github.com/glpi-project/glpi/pull/9060/files#diff-f2baa5b27a17ff7ea8035b11b6933f05a1ed3aa1ea898344284fd73d6dc4e9cfR673 
But is calculated only if anonymize option is enabled.
This PR 
- computes ```is_self_service``` even if anonymize is disabled
- add a check to use anonymize or not
- use ```is_self_service``` from …
=> fix(notification): fix private items from timeline

templates/layout/parts/breadcrumbs.html.twig, templates/layout/parts/context_links.html.twig
Currently working on my laptop, the top part was displayed on two lines.
Proposed changes when the screen is too small:
- elipsis on breadcrumb
- hide text of context links
=> Fix breadcrumb & context links responsive display

inc/ticket_ticket.class.php
Don't know why exactly i had the following error:
```
[2021-09-29 14:37:17] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Using $this when not in object context in /var/www/html/glpi/10.0-git/inc/ticket_ticket.class.php at line 339
Backtrace :
:                                                  Ticket_Ticket::countOpenChildren()
...cation/view/extension/phpextension.class.php:80 call_user_func_array()
...bac35cc376ccc6977f69fc992313d235126f6c3.php:155 Glpi\Application\View\Extension\PhpExtension->call()
vendor/twig/twig/src/Template.php:171              __TwigTemplate_42b0336306996afcc9d98b07ee026afdabf8649eaef03c258a51bb0f0a38e17e->bloc …
```
=> fix this usage

inc/dropdown.class.php, inc/html.class.php
This fixes two issues with the search input focus:
- The search box is no longer automatically focused when the select2 dropdown is opened. This seems to be a known issue but has not been fixed upstream.
https://github.com/select2/select2/issues/5993
As a workaround, we need to manually set the focus when the dropdown is opened. The user can still use the arrow keys to select an option when the search is focused.
- When the dropdown is in a Bootstrap modal, it is impossible to interact with the search box. The modal seems to change the focus to its close button instead. For this, we need to be able to specify the …
=> [Modern UI] Fix select2 search autofocus

inc/commondcmodeldropdown.class.php, templates/components/form/fields_macros.html.twig, templates/dropdown_form.html.twig
With changes of sql mode in #8424, we have now sql errors when trying to insert dc models (like pdu models). The integers fields are now with empty string values (on modern/ui only, master set 0 values)
So, in integer fields, we force 0 value (or min value) if an empty string is provided
@cconard96 we removed select2 dropdown for integer fields of dropdowns.
Do you see any issues with that ? We didn't see a case where a input[type=number] is not better.
=> avoid insert empty string in dc model integer fields

inc/html.class.php
Autofocus has to be made on `select2:open` event.
=> [Modern UI] Fix JS errors on autofocus

inc/commondbtm.class.php
I do not understand why some `CommonDBChild` have `is_recursive` fields, but in this case, creating a new item produces an error (see https://github.com/glpi-project/glpi/pull/9042#issuecomment-931112162 ). On 9.5 branch, it only produces a silented warning.
Another solution would be to completely drop `entities_id` and `is_recursive` files on `CommonDBChild` items, as, I guess, child items should always have the same entities restrictions as their parent.
=> Fix is_recursive in CommonDBChild creation form

inc/ticket_ticket.class.php, tests/functionnal/Ticket_Ticket.php
See failure on PHP 7.4 tests: https://github.com/glpi-project/glpi/runs/3787869898?check_suite_focus=true
=> Ticket_Ticket::countOpenChildren() is used statically

inc/cable.class.php
invert icon between ```Cable``` and ```Socket```
=> invert icons

composer.lock
I do not know why, but dependabot did not propose this update.
Changelog:
> 1.2.6 - 4 September 2021. Fixes a bug that arises when $config["deny_attribute"] has a data-* attribute with > 1 hyphen character
=> Update htmlawed/htmlawed to 1.2.6

inc/html.class.php
TinyMCE I18n doesn't provide English locale files anymore. Trying to load an English locale file (implicitly or as fallback) resulted in a request for the non-existing file which on my end took around 1 second. For English, we don't need to specify any of the language options.
=> Don't try to load TinyMCE English langs

inc/commondcmodeldropdown.class.php
The `product_number` field is included in the base CommonDropdown class and in CommonDCModelDropdown. This double inclusion was added in 9.3 with datacenter management but only causes a noticeable issue in 10.0 with having the form creating dynamically instead of statically.
=> Fix duplicate product_number field

inc/ajax.class.php
The createModalWindow function doesn't use width & height if you try to define it
=> Fix modal size

inc/knowbaseitem.class.php, tests/functionnal/KnowbaseItem.php
Some FAQ searches trigger an SQL error if they contains boolean search mode operators.
For example, this search:
Will trigger this error:
```sql
SELECT 
`glpi_knowbaseitems`.*, 
`glpi_knowbaseitemcategories`.`completename` AS `category`, 
COUNT(
`glpi_knowbaseitems_users`.`id`
) + COUNT(
`glpi_groups_knowbaseitems`.`id`
) + COUNT(
`glpi_knowbaseitems_profiles`.`id`
) + COUNT(
`glpi_entities_knowbaseitems`.`id`
) AS `visibility_count`, 
(
MATCH(
`glpi_knowbaseitems`.`name`, `glpi_knowbaseitems`.`answer`
) AGAINST(
'test* /* test* (* test3* )*' IN BOOLEAN MODE
)
) AS SCORE 
FROM 
`glpi_knowbaseitems` 
LEFT JOIN `glpi_knowbaseitems_users` ON (
`glpi_knowbaseitems_users`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`
) 
LEFT JOIN `glpi_groups_knowbaseitems` ON ( …
```
=> FAQ: Fix full text search with illegal chars

inc/commonitilobject.class.php, inc/plugin/hooks.class.php
If wanted, a plugin can add its informations on ticket timeline history
=> add timeline hook for plugins

inc/html.class.php
For Formcreator and its service catalog : need to redefine menu in self service to prevent direct ticket creation
=> allow plugins to redefine menus

inc/ajax.class.php
Changing "Display (number of items)" in softwares list in a computer form doesn't reload the the current tab
=> reload tab should force load of html

css/standalone/gridstack-grids.scss
Chartist graph fails to get a width as we don't force anymore 100% width for gridstack item when a responsive view is used.
=> force gristack item to be 100% width when responsive display

css/includes/pages/_search.scss
Follow #9854 (sticky search header), the background color was light in dark paletttes:
=> search sticky header should take its parent background color

css/includes/_base.scss, css/includes/components/_saved-searches.scss, templates/layout/parts/saved_searches.html.twig
fix 2 issues:
- Follow #9719, i found color of list separator to be too agressive (and border size too much).
- Also, maybe to recent tabler update, tabs in this panel lost its active color, i changed the main class of content for fixing that.
This last change may me think future tabler updates may broke components more than we want.
=> fix colors in savedsearches panel

inc/dashboard/widget.class.php
issue : card using a gradient palette doesn't have their color applied correctly after a refresh
cause :  `Widget::getCssGradientPalette()` uses a generated css prefixed by a parent id.
This id was generated by a rand.
So the cache worked but return a css targeting nothing.
I change the id of impacted card for something more predictable.
At the moment, i just changed cards using the mentionned function but i can extends to all cards if you prefer.
=> fix card palettes cache using random id

inc/socket.class.php
=> Replace usage of deprecated Html::autocompletionTextField()

templates/components/form/buttons.html.twig
One may want to use the form with `canedit=false` to hide the "Update" button. In this case, the CSRF token and the form ending tag must still be prevent, if `item.canEdit(item.fields['id'])` is evaluated to true.
See https://github.com/glpi-project/glpi/blob/9.5/bugfixes/inc/commondbtm.class.php#L2460
=> Fix missing CSRF token when canedit=false

inc/html.class.php
Due to the recent change of sticky control in search pages, the massiveactions modal fails to have a proper z-index stack.
Appending the modal to the body fix that.
I don't know why, in the first place, modal was applied to a container...
=> fix display of massiveaction modal (append to body)

install/migrations/update_0.84.x_to_0.85.0.php
Fixes following warning: `Deprecated: addslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/glpi/install/migrations/update_0.84.x_to_0.85.0.php on line 118`
=> Fix old migration warning on PHP 8.1

templates/layout/parts/menu.html.twig
Due to the fact i mainly use GLPI in en_GB, i didn't see french menu overflows:
**Before:**
**After:**
=> make texts wrap in side menu

inc/html.class.php, templates/layout/parts/page_header_empty.html.twig
Fix the `null` header, used to display pages that only requires a GLPI logo in their header.
Before:
After:
=> Fix Html::nullHeader()

templates/components/logs.html.twig
href with `<button>` doesn't work
=> fix csv export of logs

inc/api/apirest.class.php, inc/glpiuploadhandler.class.php, inc/html.class.php, js/common.js, js/fileupload.js, templates/components/form/fields_macros.html.twig, templates/components/itilobject/timeline/simple_form.html.twig
1. Fix a naming conflict between a rich text area and its file upload field. This naming conflict only appears when direct file upload is not allowed.
2. Fix textarea macro to correctly handle rich text without direct file upload enabled.
3. Enable multiple files upload at once in the upload dropzone (same behaviour as in GLPI 9.5).
4. Fix images prefix generation. Prefix generated on server side was ignored in "chunked upload" mode. This prefix has to be generated on client side.
5. Fix already uploaded files display on ITIL template reload (for instance, on category switch).
=> Fix multiple issues in file upload handling

templates/components/pager.html.twig
When clicking the `last` pager button it was going to the second to last page.
=> Fix pager rounding error

templates/components/pager.html.twig
The search results limit dropdown's onchange is handled by the new fluid search and should not cause a full page refresh anymore. Having it refresh the page and trigger the AJAX call leads to a race condition where it sometimes doesn't properly update the value.
=> Prevent full page refresh when changing limit

templates/components/itilobject/fields_panel.html.twig, templates/components/itilobject/timeline/form_followup.html.twig, templates/components/itilobject/timeline/form_solution.html.twig, templates/components/itilobject/timeline/form_task.html.twig, templates/components/itilobject/timeline/form_validation.html.twig
Without an actual form tab for ITILObjects, the `pre_item_form` and `post_item_form` hooks were never used in these items. This breaks compatibility at least with the Tags plugin. I added calls for these hooks at the start and end of the main accordion in the new sidebar.
=> Re-add item_form hooks support for ITILObjects

ajax/dropdownTrackingDeviceType.php, inc/item_ticket.class.php, inc/ticket.class.php, templates/components/itilobject/add_items.html.twig, templates/components/itilobject/fields_panel.html.twig
Re-implemented the previous code that let you select one or more items during ticket creation. Currently, you have to add all of the items one at a time after the ticket is created.
=> Re-add ability to add items on ticket creation

inc/knowbaseitem.class.php
If you access the Browser tab of the knowledge base, the articles are grouped by category.
In the list of articles if one of them is created in the parent entity it is not possible to see the documents assigned to the articles if the user is in a child entity even if the documents and the article have recursion enabled.
=> Fix recursive documents in knowbase

inc/plugin.class.php
#9180 wasn't working properly for plugins.
This issue is the `$mofile` variable being modified inside the loop, which affect negatively the next iteration.
=> Fix plugin locales loading from files/_locales

inc/dbmysql.class.php, inc/notificationeventabstract.class.php, inc/notificationtarget.class.php
I though notifications was already send with user set timezone, seems not.
As the item is loaded before iteration on each actor, i need to reload the object for concerned user (as timezone "translations" are managed by mysql)
internal ref !22951
=> ensure notifications are send with data for the correct user's timezone

.github/actions/test_update-from-9.5.sh, .github/actions/test_update-from-older-version.sh, CHANGELOG.md, inc/central.class.php, inc/config.class.php, inc/console/database/abstractconfigurecommand.class.php, inc/console/database/configurecommand.class.php, inc/console/database/enabletimezonescommand.class.php, inc/console/database/installcommand.class.php, inc/console/migration/dynamicrowformatcommand.class.php, inc/console/migration/myisamtoinnodbcommand.class.php, inc/console/migration/timestampscommand.class.php, inc/console/migration/utf8mb4command.class.php, inc/dbconnection.class.php, inc/dbmysql.class.php, inc/migration.class.php, inc/queryunion.class.php, inc/system/requirement/dbtimezones.class.php, inc/update.class.php, inc/user.class.php, install/install.php, tests/functionnal/CommonDBTM.php, tests/units/DB.php, tests/units/DBConnection.php, tests/units/Glpi/System/Requirement/DbTimezones.php
If we want to drop support of `MyISAM` tables, `datetime` fields and `utf8mb3` support in a next GLPI major version (11.0 ?), I think we should add warnings everytime these elements are used in a table create/alter query.
This PR introduces multiple changes.
1) The `use_utf8mb4` configuration flag is now set automatically on update and `db:configure` command usage. If no GLPI core tables is still using the `utf8mb3` charset, then this flag will be set to `true`. It will prevent issues with bad usage of a `--use-utf8mb4` flag.
2) A new `allow_myisam` configuration flag is now set automatically on update and `db:configure` …
=> Enhance deprecated database usages handling

inc/fqdnlabel.class.php, inc/ipaddress.class.php, inc/ipnetwork.class.php, inc/networkname.class.php, inc/networkport.class.php, install/migrations/update_9.5.x_to_10.0.0/networknames.php, install/mysql/glpi-empty.sql, tests/functionnal/NetworkName.php, tests/functionnal/NetworkPort.php
From dynamic or manual inventory, 
When we add an IPNetwork, 
GLPI add automatically IPaddress which correpond to IPNetwork -> OK
But from NetworkName (attached to the IPAddress), GLPI does not find the correct ```IPNetwork``` (automatically)
This PR solves several problems
From database ```glpi_networknames``` has no column ```ipnetworks_id``` (Strange, because we have its graphical representation)
If you select manually an ```IPNetwork``` from ```NetworkName```
some informations are added
But if you select empty choice, some warning are displayed
On ```NetworkName``` create / update, GLPI automatically adds the corresponding ```IPNetwork``` if it found
| Tests …
=> feat(networkname): find ipnetwork from IP for networkname

inc/cache/cachemanager.class.php, inc/console/cache/configurecommand.class.php, inc/console/cache/setnamespaceprefixcommand.class.php, tests/units/Glpi/Cache/CacheManager.php
Defining a namespace for each cache context may be a problem.
1. GLPI admin may not know every cache context used in its instance (some plugins may define their own context).
2. Some contexts may be added after cache configuration, for instance by a new GLPI version or a new plugin, and GLPI admin may not be aware of that.
3. If many plusgins defines their own context, defining a namespace for each context can be a pain.
Main purpose of cache namespace definition is to prevent conflicts between multiple GLPI instances using the same cache storage, so defining a specific namespace for each context is not really needed, we …
=> Use global cache namespace prefix

js/planning.js
On planning page, "refresh" button did nothing after changing the dates.
| Fixed tickets | !22964
=> fix(planning): refresh button

inc/features/clonable.class.php, tests/functionnal/Project.php
When cloning a project, the "Project Team" data was not copied correctly:
1 -> My "original" team with one group (id =1) and one user (id = 3).
2 -> The incorrect data over multiple clone tests, you can see the project id was used instead of the correct user/group ids.
3 -> One more clone test after fix -> OK.
Seem like the `override_input` variable used wasn't reinitialized for each itemtype so some data was overlapping when it shouldn't.
Here I guess `items_id` was set from one of the previous clone relation (`Document_Item` or `ProjectTask`).
I've also added a new test to check that projects are cloned correctly.
Before fix:
After fix:
|  Q             | A
| …
=> Fix project clone

inc/knowbaseitem.class.php, tests/functionnal/KnowbaseItem.php
Anchors for FAQ headers are broken:
Despite having 4 headers in my content I only have one anchor that I can hover.
As you can see in the bottom left corner, its URL also seems to be malformed as it contains extra chars (it should only contain the header name). 
It turns out one of the regex we use was too greedy and matched too much chars.
After fixing the regex:
I've also added a functional test to check if the headers are properly formed.
| Fixed tickets | !22988
=> Fix FAQ anchors

inc/search.class.php
Not all columns are concerned, so i picked some datatypes to fix wrapping, mainly numbers (for id) and dates
=> fix some columns (number, dates) wrapping in search pages

ajax/search.php, inc/session.class.php
The search AJAX calls Search::displayData which tries initializing the navigation header and replaces the list URL with the AJAX URL.
=> Do not set listurl to AJAX urls

.npmrc, package-lock.json, package.json
Node v16 is the latest LTS and embed npm v8.
=> Force usage of node v16 and npm v8 and update lockfile version

inc/cartridge.class.php, inc/consumable.class.php
Since #9683, `$iterator->next()` must be replaced by `$iterator->current()`.
=> Fix DBmysqlIterator usage

inc/search.class.php
Fix deprecated usage of `trim(null)`.
=> Fix PHP 8.1 deprecation warning on search hooks

inc/dbmysql.class.php
#9766 Changed ssl_set call from procedural style to object oriented. The parameters are different between the two versions as the mysqli parameter is no longer needed.
https://www.php.net/manual/en/mysqli.ssl-set.php
=> Fix DB ssl_set

inc/commonitiltask.class.php
When clicking on the counters next to "Problems tasks to do", the link would send user to "Tickets" section instead of "Problem" section. I noted this when I was adding "Changes" information on central screen.
I tested it and now the link is sending user to correct place. I did with a variable because in my instance I'm adding "Changes" info on central too. I would send a pull request for it too, but I've seen it was already implemented.
| Tests pass?   | don't know what that means
=> Central counter links fix

install/migrations/update_0.80.0_to_0.80.1.php, install/migrations/update_0.80.x_to_0.83.0.php, install/migrations/update_0.83.0_to_0.83.1.php, install/migrations/update_0.83.x_to_0.84.0.php, install/migrations/update_0.84.x_to_0.85.0.php, install/migrations/update_0.85.0_to_0.85.3.php, install/migrations/update_0.85.x_to_0.90.0.php, install/migrations/update_0.90.x_to_9.1.0.php, install/migrations/update_9.1.x_to_9.2.0.php, install/migrations/update_9.2.0_to_9.2.1.php, install/migrations/update_9.2.2_to_9.2.3.php, install/migrations/update_9.2.x_to_9.3.0.php, install/migrations/update_9.3.x_to_9.4.0.php, install/migrations/update_9.4.x_to_9.5.0.php, install/migrations/update_9.4.x_to_9.5.0/appliances.php
Integer display width is deprecated in MySQL 8.x and will probably be removed in a future major version.
We already remove its usage in GLPI 9.5.x->10.0.0 migrations and in `glpi-empty.sql` DB init script.
=> Remove usage of MySQL integer display width in migrations

front/css.php, inc/dashboard/widget.class.php, inc/html.class.php
On PHP 8.1, in debug mode, main scss compilation triggers PHP deprecation warnings, and compiled CSS syntax is invalid due as it contains these warnings messages.
I propose to disable error handler output to prevent this behaviour. Warnings will still be logged in errors log.
Triggered warnings:
```
glpiphplog.NOTICE:   *** PHP Deprecated function (8192): strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/glpi/vendor/scssphp/scssphp/src/SourceMap/SourceMapGenerator.php at line 350
Backtrace :
...cssphp/src/SourceMap/SourceMapGenerator.php:350 strpos() …
```
=> Prevent warnings to break CSS; replace deprecated usages

inc/change_problem.class.php, inc/change_ticket.class.php, inc/problem_ticket.class.php
It's not currently possible to link a closed ticket/change/problem to another ticket/change/problem:
As discussed, keeping this tab readonly on solved items can be troublesome for some use-case.
I've removed this restriction from `Change` <-> `Ticket` and `Ticket` <-> `Problem`.
`Change` <-> `Problem` didn't have this restriction so no changes needed here.
EDIT:
Second commit remove the "open items only" condition on Problems for the Ticket and Changes tabs.
| Fixed tickets | !23034
=> Link closed Ticket/Problems/Changes

inc/html.class.php, inc/plugin/hooks.class.php
Use case:
My "dev" plugin exposes some of the GLPI internals and provides some info useful for debugging and development. It would make sense to add some of this data in the existing debug info panel.
=> Add hook for custom debug tabs

templates/generic_show_form.html.twig
=> avoid dc breadcrumb to wrap icon and text

templates/pages/management/softwarelicense.html.twig
Software fieds was missing in the twig form
=> missing field in license form, creation was impossible

inc/rulecollection.class.php
The number of rules displayed in the pager doesn't match the results:
The count request is built using `getRuleListCriteria`.
This function support `inherited` and `childrens` params but they weren't being set when called from `getCollectionSize`.
| Fixed tickets | !23047
=> Fix rules count

js/modules/Kanban/Kanban.js
CSS variable is returned as a string, not a boolean.
=> Fix dark theme detection in Kanban

CHANGELOG.md, src/CommonDBTM.php, src/CommonGLPI.php, src/CommonGLPIInterface.php, src/DbUtils.php, tests/functionnal/DbUtils.php
We have some `new static()` in code, and some `new $itemtype()` also. If anyone overrides an itemtype constructor and defines some params in it, it will not work. Forcing lack of constructor arguments using an interface will prevent this kind of override.
See https://phpstan.org/blog/solving-phpstan-error-unsafe-usage-of-new-static
=> Ensure CommonGLPI constructor overrides have no params

inc/dashboard/grid.class.php
When we use, for example, the variable {{glpiID}} (=> GLPI user) in an advanceddashboard card, we sometimes get the result of another user. This happens when there are many simultaneous users.
| Fixed tickets | !23029
=> fix(dashboard): cache issue with advanceddashboard

inc/change_item.class.php, inc/item_problem.class.php
I've found the following warnings when viewing a computer:
```sh
[2021-12-09 10:15:59] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: id in /var/www/glpi/inc/commondbrelation.class.php at line 1577
Backtrace :
inc/commondbrelation.class.php:1785                CommonDBRelation::getListForItemParams()
inc/item_problem.class.php:250                     CommonDBRelation::countForItem()
inc/commonglpi.class.php:339                       Item_Problem->getTabNameForItem()
inc/computer.class.php:108                         CommonGLPI->addStandardTab()
inc/commonglpi.class.php:294                       Computer->defineTabs()
inc/commonglpi.class.php:859                       CommonGLPI->defineAllTabs()
inc/commonglpi.class.php:1230                      CommonGLPI->showTabsContent() …
```
=> Safety checks

templates/components/form/inventory_info.html.twig, templates/generic_show_form.html.twig
Use same block than GLPI inventory agent for plugins
=> Change Hook Inventory Information block location

src/RuleImportAsset.php, tests/functionnal/RuleImportAsset.php
When you want to Link a agent on an existing item or no import agent like this
The result is not send to $output without this check
=> Inventory - Fix Rule Asset Import Case

src/Agent/Communication/AbstractRequest.php, src/Agent/Communication/Headers/Common.php, tests/functionnal/Glpi/Agent/Communication/Headers/Common.php
=> Use legacy headers to prevent json format to be used for plugins tasks

inc/ticket.class.php
This rule was never executed on update, even if the category was modified: 
This is because the input contains a change for `itilcategories_id` while the rule field is defined as `itilcategories_id_cn`.
=> Fix rules depending on category completename

css/palettes/auror_dark.scss
Fix `WARNING: Found no color leading to 5:1 contrast ratio against...`
=> fix contrast ratio warning on auror dark

templates/components/form/fields_macros.html.twig, templates/components/logs.html.twig
slugify is here to prevent bad dom id (`filters[date]_rand` ), squares are forbidden in id
=> replace log's date filter by flatpickr

src/CommonDBTM.php
Fixes following issue
```
*** PHP Deprecated function (8192): preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /var/www/glpi/src/Html.php at line 3205
Backtrace :
src/Html.php:3205                                  preg_match()
src/CommonDBTM.php:4314                            Html::computeGenericDateTimeSearch()
src/Log.php:659                                    CommonDBTM->getValueToDisplay()
src/NotificationTargetCommonITILObject.php:1342    Log::getHistoryData()
src/NotificationTargetTicket.php:151               NotificationTargetCommonITILObject->getDataForObject() …
```
=> Fix PHP 8.1 deprecation errors on empty dates rendering

ajax/fileupload.php
There are some PHP 8.1 deprecation errors triggered in the file upload lib. In debug mode, it prevents to upload a file as javascript is not able to understand the response.
=> Prevent deprecations to break file upload JSON response

templates/components/infocom.html.twig
The hook don't display plugins informations on infocom.
Needs to change plugin existant hooks  : 
Example : 
```
diff --git a/inc/order_item.class.php b/inc/order_item.class.php
index 1569d09..18a0339 100644
--- a/inc/order_item.class.php
+++ b/inc/order_item.class.php
@@ -2005,7 +2005,8 @@ class PluginOrderOrder_Item extends CommonDBRelation {
}
-   public static function showForInfocom(CommonDBTM $item) {
+   public static function showForInfocom($params) {
+      $item = $params['item'];
$order_item = new self();
$order_item->showPluginFromItems(get_class($item), $item->getField('id'));
} 
```
=> Fix Infocom Hook display for plugins

src/Search.php
Honnestly, i don't know why tooltip are keeped after criteria removal, so i force the disposable when clicking on remove button
=> force disposal of tooltips when removing criteria in search form

inc/autoload.function.php, src/Report.php
1. Marketplace directory was not evaluated during autoload since #9704 .
2. Custome plugins reports were always pointing to `plugins` directory.
=> Fix plugins autoloader and reports

src/DomainRecord.php, src/DomainRecordType.php, src/User.php
#10095 had changed JS anonymous functions that were in PHP files to `public function` which is not valid JS.
=> Revert PSR-12 changes made to inline JS anon funcs

templates/components/form/header.html.twig
=> Align entities info

src/Marketplace/View.php
Download icon was using an alert icon instead of the download one. The download again button was using the FontAwesome icon still so I changed it to Tabler since that icon was already replaced other places.
=> Fix marketplace download icons

ajax/domainrecord_data_form.php
This was trying to include headers in an AJAX modal when they were already included for the page, which meant it tried loading the scripts twice and would fail/break.
=> Fix DomainRecord helper js errors

front/socketmodel.form.php, front/socketmodel.php, inc/define.php, src/Cable.php, src/Dropdown.php, src/Socket.php, src/SocketModel.php, templates/pages/assets/cable.html.twig, templates/pages/assets/socket.html.twig, tests/functionnal/Cable.php
Multiple places in the code expects an asset model class to be the fully qualified class of the asset followed by `Model`. For sockets, the `Socket` is in the Glpi namespace while the `SocketModel` is in the root so it cannot be automatically discovered.
=> SocketModel should use same namespace as Socket

src/Plugin.php
When a property with falsy value is passed to `Plugin::registerClass()` it should not trigger a warning.
```
[2021-12-15 10:11:27] glpiphplog.WARNING:   *** PHP User Warning (512): Unknown attributes "helpdesk_visible_types", "linkgroup_types", "linkuser_types", "linkgroup_tech_types", "linkuser_tech_types", "ticket_types", "infocom_types", "networkport_types", "reservation_types", "contract_types", "unicity_types", "location_types", "itemdevices_types" used in "PluginGenericobjectVoiture" class registration in /var/www/glpi/src/Plugin.php at line 1394
Backtrace :
src/Plugin.php:1394 …
```
=> Fix handling of falsy properties in Plugin::registerClass()

src/Ajax.php, templates/components/form/header.html.twig
Following #10098, a little fix + another improvement:
* Do not show item name on creation form
* Hide tab above creation form
Before:
After:
=> Fix headers for new items

src/KnowbaseItem.php
| Fixed tickets | #10172
The removal of the `right` property in #9898 broke the Profile dropdown in the KB visibility tab. I tested the category dropdown from the other commit and it still worked with the `right` property restored. I'm not quite sure why it was removed.
=> Fix KB profile visibility dropdown

templates/pages/login.html.twig
When a plugin (like alerts or branding) use the`display_onlogin` but don't display anything, login screen show an empty right column.
Before:
After:
=> fix empty display_onlogin hook displaying an empty  right column

templates/components/itilobject/timeline/form_task.html.twig
Prevent "Plan this task" button to overflow with small screen
=> prevent overflow of plan button when creating task

templates/dropdown_form.html.twig
Recurent Ticket and Change form display some date fields, and their flatpickr code is not working.
this form use `CommonDropdown::showForm`  and this last forward to `templates/dropdown_form.html.twig`.
The problem come from showForm pass global params to template, and this one use it in field option. Date field only fill id key  when not present. Currently the id key is already set (empty in new form) and so flatpick doesn't work.
I suggest to not use form params for fields options.
=> avoid using item.id when displaying date[time] field

src/Ajax.php
Horizontal tabs (like central or preferences) display both controls : tabpanel and tabselect
=> fix horizontal tabs responsive

src/Search.php
| Fixed tickets | #10099
The default tabler box shadow for the striped table rows was hiding the custom background colors set on the td elements.
=> Fix custom cell color in striped tables

tools/make_release.sh
GLPI_VERSION has not been updated in `inc/define.php` during GLPI 10.0.0-beta release process. This check will prevent this kind omission.
=> Prevent releasing a version without updating inc/define.php first

src/Ajax.php
issue with horizontal tabs after merging of 9b875a3de652885ea6de7624d79ae552a319a2ab
they should be displayed as flex (at least inline) not block
Before:
After:
=> hz tabs should be displayed as flex, not block

src/OLA.php, src/SLA.php
Class names are case sensitive and these references didn't match the class name exactly.
=> Fix SLA and OLA class references

src/Config.php
This occurs when timezone are available on the system but are not setup in GLPI (in config > general)
=> fix notice with timezone dropdown

composer.json
Local CS checks were specifically using the GLPI standard which caused it to ignore the `.phpcs.xml` config.
GLPI has switched to PSR-12 which was already set in the config.
This should align the results of the local CS checks with the CI checks now.
=> Fix standard used with local CS check

src/Rack.php
| Fixed tickets | #10179 
AJAX is POST by default which GLPI checks CSRF for, but this modal doesn't have a token. In previous versions it explicitly was a GET for the form contents. The retrieved form should still be submitted through a POST.
=> Use GET for ajax modal like previous versions

src/AuthLDAP.php, tests/LDAP/AuthLdap.php
=> use_bind should be set to yes by default; see #10135

inc/commonitilobject.class.php
When scheduled the creation of a recurring ticket with the option "Preliminary creation". The task opens with the actual creation date of the ticket. So task date was before ticket date.
| Fixed tickets | !23092
=> fix: task date before ticket creation date

src/Item_Devices.php
Looks like an error was introduced in UI refurbish, here (inc/item_devices.class.php line 1395) : https://github.com/glpi-project/glpi/commit/0aec396494ef38c781633f4abe6b07295014cd40#diff-fee44d53676e1f4f83896aa4ee32e3c6a885cfdca359cb684f1ee57c7c602479R1395
[Tue Dec 28 08:13:29 2021] PHP Notice:  Undefined index: name in /home/bugier/public_html/glpi-master/src/Item_Devices.php on line 1516
[Tue Dec 28 08:13:29 2021] PHP Stack trace:
[Tue Dec 28 08:13:29 2021] PHP   1. {main}() /ajax/common.tabs.php:0
[Tue Dec 28 08:13:29 2021] PHP   2. CommonGLPI::displayStandardTab($item = *uninitialized*, $tab = *uninitialized*, $withtemplate = *uninitialized*, $options = *uninitialized*) /ajax/common.tabs.php:107
[Tue Dec 28 08:13:29 2021] PHP   3. Item_DeviceSimcard->showForm($ID = *uninitialized*, …
=> fix php warning on device_simcard display

templates/components/form/fields_macros.html.twig, templates/components/itilobject/fields/status.html.twig
=> Fix status field alignement when readonly

templates/components/itilobject/selfservice.html.twig
Current self-service form has a huge left margin, I don't think it's on purpose.
Before:
After:
=> Fix self-service form display

front/tracking.injector.php
When using the helpdesk form to create tickets (simplified interface) and then doing something to trigger a page reload like changing the category, you would get the following error:
`Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\glpi\src\CommonITILObject.php on line 162`
The `_actors` parameter is a JSON string but is treated like an array.
When using the standard interface, this is an array as expected.
=> Fix bad actor format for helpdesk ticket form

src/KnowbaseItem.php
| Fixed tickets | #10239
Fix issue with missing knowledgebasecategories_id field in the KB search and browse view when dropdown translations are enabled.
=> Fix KB view

src/CommonGLPI.php
The KB item displayed by default was not the 1st in the list (which is sorted alphabetically), but the 1st ID
| Fixed tickets | !23109
=> feat(ticket): KB order for associated items

js/modules/Kanban/Kanban.js, src/CommonITILObject.php, src/Features/Kanban.php, src/Plugin/Hooks.php, src/Project.php
Add missing support for plugins to hook into the new Kanban filtering feature.
Two new PHP hooks were added:
- kanban_item_metadata: Used to inject metadata values into the displayed cards that will be used later for filtering
- kanban_filters: Add new filters for different item types
The JS-side event `kanban:filter` was changed to pass the kanban element selector in addition to the filters. This is not strictly needed for core Kanbans since they all use `#kanban` but this isn't a restriction for Kanban's added elsewhere.
=> Improve plugin support for Kanban

templates/generic_show_form.html.twig
Global management dropdown currently uses the config value for Monitor global management restrictions (unit vs global) instead of the specific one for the current item type.
=> Fix global management dropdown restrictions

tests/functionnal/Config.php
While working on user documentation I found that this config option wasn't tested. I added a test to verify it worked as intended.
=> Test auto-enable of infocom config option

src/DBConnection.php, tests/units/DBConnection.php
Working on user documentation, I found that the default SQL replica config that gets created when you enable it in the System tab uses the wrong class name.
The main DB config already defines the class `DB`. Looking at the code in GLPI, it looks like the replica config class is supposed to be `DBSlave`.
Without the change, the SQL Replica configuration tab fails to load because it tries autoloading `DB` twice.
=> Fix default SQL replica config

src/Application/ErrorHandler.php
No real purpose inside GLPI itself right now.
I've been experimenting with an end-to-end test framework and wanted to test that no alerts show when in debug mode (PHP warnings, etc).
In most cases just looking for `alert-danger` is enough, but it is nice to be able to tell the difference between debug alerts and application alerts especially if an application alert is expected, but not a debug alert.
=> Differentiate GLPI debug alerts

src/DeviceBattery.php, src/DeviceGraphicCard.php, src/DeviceHardDrive.php, src/DeviceMemory.php, src/DeviceProcessor.php, src/DeviceSimcard.php
Many components have fields that are `INT` in the DB but are presented as text fields in the UI.
This makes it very easy to accidentally try setting the fields to invalid values.
By default, if you didn't change the empty "number" text fields, it would fail because an empty string is not a valid integer.
=> Fix device number fields

src/Entity.php
Working on user documentation, I found that two of the notification configuration fields in the per-Entity config were confusing/wrong.
- Administrator reply-to email (if needed) - Confusingly doesn't use the same label as the global configuration
- Response address (if needed) - Not correct. This is a label for the Administrator reply-to email display name, not the email address itself
I replaced both labels with the ones from the global configuration.
=> Fix confusing Entity notification field labels

src/Search.php
| New feature?  | Back-end change only
Add some data attributes to the div surrounding the search criteria input to help identify if in JS.
The input field itself doesn't have any generalized identifier like a class and neither does the wrapper currently.
This is needed for the camerainput plugin to know where to inject the camera search button.
This would allow scanning a barcode as a data input method when searching.
=> Add data attribs to search criteria input

src/Ticket.php, templates/components/itilobject/selfservice.html.twig
I've found that, as a self service user, I can see the validation notice but the "Check it out" link redirect me to the current page:
This is because while I do have some tickets waiting for my validation (which trigger the notice to appear) I do not have the rights to validate tickets (which prevent the correct link from being set).
I've added an empty check on the link to prevent this (now the notice isn't show at all for my user).
A few others changes:
- `nb_tic_to_validate` -> `has_tickets_to_validate` since the var is actually a boolean and does not contains the numbers of tickets
- There **is** some tickets -> There **are** some tickets ("there is"  is for singular or uncountable items, "there are" for plural)
| New …
=> Fix validation notice for self-services

js/common.js, src/Html.php
Two fixes:
If you forgot a mandatory tinymce field (e.g. ticket's description) then you can never submit your form again:
-> Fixed by not triggering the "one time submit" code on failed tinymce validation.
Firefox seems to save the content of all textareas on a page and rewrite them on a soft reload.
This caused an unexpected issue:
If you refresh this page, the tinymce input is no longer required and you can submit an empty form:
The browse save the HTML content of the tinymce textarea, which for some reason contains `<p><br></p>` for an empty textarea.
So when you refresh the page, the `$('#$name').val() == ''` check that add the required tag fails as `val` contains `<p><br></p>`.
-> Fixed by stripping all html tags before checking if `val` is empty.
| ------------- …
=> Fix submit button for ticket forms

templates/components/form/fields_macros.html.twig
Using Twig to generate fields with alternate field_class and no_label, field_class is ignored.
Below the condition form for a section, in Formcreator. The 4 last fields should be on the same line, they use in order the following field_class
'field_class': 'col-12 col-sm-1',
'field_class': 'col-12 col-sm-5',
'field_class': 'col-12 col-sm-1',
'field_class': 'col-12 col-sm-5',
Sum of col-sm-xx is 12 and matches col-12. 
No_label is set for all these fields
Expected rendering, obtained with this patch
However, if full_widh is enabled, col-sm-xx is deleted as expected, but col-12 will be used instead of a col-xx defind in field_class. This pach does not addresses this case.
| …
=> fix field without label ignoring field class

templates/components/itilobject/footer.html.twig, templates/components/itilobject/timeline/form_followup.html.twig
Self-service users have access to too much information:
Also the 'btn-group' dropdown shouldn't be displayed if there is only one possible action
After changes:
=> Fix self-service followups actions

src/Html.php
Update an external event from calendar is partially break
If I click in the yellow (from submit button) -> update is OK
If I click on the label or on the icon (from submit button) -> update is KO
I think it's since the introduction of twig, where we added a ```<span>``` and ```<i>``` (for icon and label)
This Pr fix this
| Fixed tickets | internal 23111
=> fix(js): better way to get last clicked submit

src/AuthLDAP.php
| Fixed tickets | #10135
@cedric-anne opinion on this one would be required before merging i suppose
Original error was on `ldap_search` (but the `@` before https://github.com/glpi-project/glpi/blob/10.0.0-beta/src/AuthLDAP.php#L3329 hides completly the error for me, also in logs):
```
[2021-12-21 12:21:20] glpiphplog.WARNING:   *** PHP Warning (2): ldap_search(): Search: Bad search filter in /var/www/html/glpi/10.0-git/src/AuthLDAP.php at line 3331
Backtrace :
src/AuthLDAP.php:3331                              ldap_search()
src/AuthLDAP.php:2732                              AuthLDAP::searchUserDn()
src/AuthLDAP.php:352 …
```
=> do not send encoded html to ldap search; see #10135

front/locale.php, inc/config.php, inc/define.php, index.php, src/Console/Application.php, src/Console/Database/UpdateCommand.php, src/DbUtils.php, src/Html.php, src/Toolbox.php, src/Update.php
| Fixed tickets | #10132
1. When calling directly the root path of GLPI `/` or `/index.php`, if DB config file is missing and `/install/install.php` file has been removed, following page is displayed, instead of redirecting to a 404.
2. Page displayed when DB config file is missing during call to any front PHP file is now displayed properly. Also, the `Go to install` button will be displayed only if the install page is available.
~~3. When `/install/mysql/glpi-empty.sql` is missing, `GLPI_SCHEMA_VERSION` will be suffixed by `@unknown`. Checks done to ensure DB is up to date will trigger a warning in this case, but update page will not be …
=> Better handling of /install directory removal; see #10132

inc/itilsolution.class.php
'users_id_editor' value wasn't changed on solution update.
| Fixed tickets | !23128
=> fix(ticket): missing users_id_editor on solution update

src/ReservationItem.php
When using the simplified interface, the reservable items list has links to the Reservation tab for the items even when the user doesn't have access to view those item types so they get a blank page with `You don't have permission to perform this action.`.
It would probably be a better user experience if there weren't links there at all in this case.
=> Show name without link in reservation UI without item rights

css/includes/components/_asset-form.scss
| Fixed tickets | #10269
Fix top of form when embedded in iframe (Usually positioned properly because of .tab-content).
Without it, the top of the card header is cut off.
=> Fix form ribbon position in iframe

js/impact.js, src/Impact.php
This "status badge" count the number of ongoing incidents for an item:
With these changes, it also take into account ongoing problems.
| Fixed tickets | !23130
=> Add problems to impact "status" badge

src/Ajax.php
Following https://github.com/glpi-project/glpi/pull/10124.
The previous PR only targeted new items regarding this visual issue:
These one extend it to all items: no point to display tabs list if there is only one tab ( + it's overlapping the "ribbon" thing containing the icon).
=> Hide single tab

css/includes/components/_flatpickr.scss, css/palettes/_includes.scss, src/Html.php
Currently, the default dark flatpickr theme is only used if the current palette is `darker` and doesn't account for any of the other dark themes.
To resolve this, I changed it to include the default dark flatpickr theme all the time (may have a cleaner look than light), and then overrode all colors in a new includes so that they would match the current palette colors.
Samples (Auror, Premium Red, Dark Auror, Midnight):
=> Flatpickr theme support

templates/generic_show_form.html.twig
For some items you need to disable the form footer as you have no relevant dates or template to display, for example:
There seems to be an option "formfooter" that can be used to disable this footer but it's a bit weird to use.
`$options['formfooter'] = false;`  wont work, you need to set a "truthy" value to disable it because of the non strict check.
This is not very intuitive, you would not expect the footer to be disabled if you set formfooter to `true`.
These change allow the footer to be disabled with `$options['formfooter'] = false;` while still keeping the default behavior of showing the footer if the option is null (= not specified). …
=> Fix form footer option

templates/components/form/fields_macros.html.twig
Add support for [\<input type="email"\>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email).
=> Add emailField twig macro

package-lock.json, package.json, src/CommonITILObject.php, templates/components/itilobject/timeline/form_validation.html.twig
Main issue was comments from validations was still escaped when they should have been displayed.
This was due to a mix between escaped and non escaped html in the same content entry.
Another issue was the submission comments wasn't present anymore in form.
I took the opportunity to customize, a litte, displayed data and so i needed an update of tabler/icons
=> fix validations issues

front/pluginimage.send.php, inc/auth.class.php, inc/console/migration/unsignedkeyscommand.class.php, inc/dbmysql.class.php, inc/event.class.php, inc/networkportinstantiation.class.php, inc/session.class.php, install/update_956_957.php
Here is the first step of migration to unsigned integers for primary/foreign keys. Switching installation file to unsigned int is too impacting and would trigger too many conflicts to be done on 9.5 branch, but the migration command should be, IMHO, be available in 9.5 branch, as it will be usefull for people using behaviours plugin.
=> Add migration to use usigned int for primary/foreign keys; see #10262

src/Change.php, src/Problem.php, src/Ticket.php
While looking at a different issue, I noticed that in some cases the actors would disappear before I submit the final form.
To recreate:
1. Have category a mandatory field
2. Create ticket with actors and everything required except category
3. Try adding ticket and get error saying category is required and see actors are missing
This doesn't seem to happen when adding other actors or changing fields that cause the form to reload.
=> Restore actors after incomplete form reload

css/includes/components/_flatpickr.scss, js/flatpickr_buttons_plugin.js, src/Html.php, templates/components/form/fields_macros.html.twig
In the jQuery UI date picker, we had a button to automatically set the date/time to the current date.
Beyond setting the initial value to now, having the ability to update the date/time to the current one is useful in some cases like updating the last physical inventory.
I made a custom plugin for flatpickr to allow adding buttons, with a Now/Today button (label changes depending on if time is enabled) being the default.
Related stale issues: #7780, #7858
I've also seen some forum topics concerning the lack of the button.
Most recent was: https://forum.glpi-project.org/viewtopic.php?id=282697
=> Support buttons in datetime and add today/now button

src/RichText/UserMention.php, src/Session.php, src/Stat/Data/Location/StatDataLocation.php, src/Toolbox.php
1. `UserMention::getUserIdsFromUserMentions()` and `Toolbox::stripTags()` were still requiring an opt-in argument to handle unsanitization. This arg has been removed as `Sanitizer` is now able to handle it automatically.
2. IDOR token check was using `Toolbox::stripslashes_deep()`. I replaced it with `Sanitizer::getVerbatimValue()` as we may also face encoding issues with `<`, `>` or `&` chars.
=> Adjust some 'unsanitize' logic

ajax/massiveaction.php, js/common.js, src/Html.php
This JS script was indirectly included via the `CommonDBTM::showFormButtons()` in GLPI 9.5, but is not included anymore. ~~I propose to move it directly in `common.js` file, which should be included almost everywhere, and remove the related `CFG_GLPI` volative entry.~~
There is no need for such a script. Prepending the checkbox with an hidden input having the `0` value does the job.
=> Fix 'zero_on_empty' checkbox option

front/inventory.php, src/Agent/Communication/AbstractRequest.php, src/Inventory/Inventory.php, src/Inventory/Request.php, tests/units/Glpi/Inventory/Request.php, tests/web/Glpi/Inventory/Request.php
| Fixed tickets | partly #10162
It appeared glpi-agent and fusioninventory-agent can generate unexpected errors like "Uncaught Exception RuntimeException: Mode has not been set" in php-errors.log.
This was due to GET request generated by Collect, ESX & Deploy tasks requesting a config with the GET protocol.
First there was a typo preventing GLPI from setting the HTTP code on the response, so GLPI 10 was always returning 200 even on error.
The "Method not allowed" was configured to return a 400 HTTP code but this error should be returned as 405 and without content.
Also, in the case of GLPI-Agent communicating in json, the server would answer …
=> Update http protocol error and inventory error support

inc/toolbox.class.php
| Fixed tickets | #10109 
In some cases an image's resized height can be rounded down to zero which isn't valid (example image was 3px high by 449px wide).
Wrapping the division in `ceil` should make images at least 1px high.
=> Ensure resize image height is greater than zero

src/Ticket.php, templates/anonymous_helpdesk.html.twig
When trying to create a ticket using `helpdesk.public.php` you get redirected to a blank page and the ticket isn't created because the `add` parameter is missing in the POST.
=> Fix anonymous ticket creation

src/Console/Database/AbstractConfigureCommand.php, src/Console/Database/InstallCommand.php, src/GLPIKey.php
The `AbstractConfigureCommand::configureDatabase()` method can be used to create a configuration file that targets the database that will be created later by the `db:install` command. The call to `DBmysql::connect()` must be done after the creation of this new database.
=> Fix db:configure command when using a db that does not yet exists

src/Inventory/Request.php
This little PR to follow one @orthagh suggestion on #10316 and to avoid a possible deprecated notation in future PHP versions.
=> Update hooks params setup in getParams

src/DBmysql.php, tests/units/DB.php
On some plugins, the install SQL queries are using ``` CREATE TABLE IF NOT EXISTS `xxx` ``` queries. In this case, table name was incorrectly extracted and following warning was trigerred: ``` Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `IF`.`id`. ```
=> Fix table name in unsigned key usage warning

src/Inventory/Request.php, src/Plugin/Hooks.php
In this PR, we:
* add hooks support for all tasks supported by GLPI-Agent
* disable not supported tasks in contact answer so agent has not have to run them
* enable inventory and remoteinventory tasks by default
The purpose of this PR is to enhance the JSON protocol related to the CONTACT request. Actually, the server will answer GLPI-Agent to disable all its tasks but `inventory` one. Now, `remoteinventory` task is also enabled by default as this task is only setup on the agent side. Also, any plugin, like [GlpiInventory plugin](https://github.com/glpi-project/glpi-inventory-plugin), can tell GLPI to answer it can handle …
=> Json protocol contact support update

src/CommonITILObject.php
This fix ensure that hook.php from the plugin is loaded.
Fixes a feature of Formcreator.
=> timeline_actions hook must load hooks of plugins

src/Agent/Communication/AbstractRequest.php, tests/functionnal/Glpi/Inventory/Inventory.php, tests/web/Glpi/Inventory/Request.php
This PR permits to avoid a double json decoding of submitted content. It also introduces a malformed JSON error handled with a 400 HTTP error.
This also prevents to see a PHP warning exception inphp-errors.log when submitting a not compressed and malformed json with such a request:
```
LANG=C curl http://glpi-server/front/inventory.php -v -X POST -H "Content-Type: application/json"
```
Here was the found warning for such request:
```
[2022-01-11 12:20:04] glpiphplog.WARNING:   *** PHP Warning (2): First parameter must either be an object or the name of an existing class in …
```
=> Json protocol support update

src/TaskTemplate.php
State dropdown in the Task Template form was missing.
=> Fix state dropdown

install/migrations/update_9.5.x_to_10.0.0/cable.php, install/migrations/update_9.5.x_to_10.0.0/cameras.php, install/migrations/update_9.5.x_to_10.0.0/dashboard_filters.php, install/migrations/update_9.5.x_to_10.0.0/databases.php, install/migrations/update_9.5.x_to_10.0.0/entity.php, install/migrations/update_9.5.x_to_10.0.0/gantt.php, install/migrations/update_9.5.x_to_10.0.0/inventory_management.php, install/migrations/update_9.5.x_to_10.0.0/knowbaseitem_knowbaseitemcategory.php, install/migrations/update_9.5.x_to_10.0.0/manuallinks.php, install/migrations/update_9.5.x_to_10.0.0/native_inventory.php, install/migrations/update_9.5.x_to_10.0.0/networknames.php, install/migrations/update_9.5.x_to_10.0.0/pendingreason.php, install/migrations/update_9.5.x_to_10.0.0/recurrentchange.php, install/migrations/update_9.5.x_to_10.0.0/schema_fixes.php, install/migrations/update_9.5.x_to_10.0.0/ticket_contract.php, install/migrations/update_9.5.x_to_10.0.0/tickettask.php, src/DBConnection.php, src/Migration.php, tests/units/Migration.php
~~Includes #10315 .~~
Working on plugins, I figured out that we should only use `unsigned` primary/foreign key when migration has been done in core (which can be verified using the `$DB->allow_signed_key` flag). Indeed, it could prevent unconsistency between keys types.
I implemented something similar as what we have already done for utf8 VS utf8mb4 handling.
=> Use primary/foreign key default sign option in migrations

src/Application/ErrorHandler.php, src/Planning.php
| Fixed tickets | #10352
New `ErrorHandler` methods will permit to temporarly suspend the output, but messages will still be sent to the error log. This is a good alternative to usage of `@` operator.
=> Prevent external calendars issues to break planning; fixes #10352
