inc/dropdown.class.php
inc/group_user.class.php
inc/user.class.php

Complement to #6978
Do not display users without right from ticket (and other places)
Add new arg to have or not users without rights
| Fixed tickets | Internal 21872

fix(core): do not display users without rights

---

inc/certificate.class.php
inc/commonitiltask.class.php
inc/contract.class.php
inc/infocom.class.php

Allow future date on the following search criteria:
* Certificate:
* Expiration date
* Tasks:
* Begin date
* End date
* Contract:
* Start date
* End date
* Infocom:
* Decommission date
| Fixed tickets | !21923

Search / Future dates

---

inc/auth.class.php
inc/authldap.class.php
inc/authldapreplicate.class.php
install/migrations/update_9.5.x_to_10.0.0/ldaps.php
install/mysql/glpi-empty.sql
tests/LDAP/AuthLdap.php

Add new option from authldap (and authldapreplicate) form to define timeout 

feat(auth): add option to define timeout

---

.github/workflows/coverage.yml

Coverage is done on master branch, configuration file on default branch (9.5/bugfixes) has to be compatible with master branch scripts.

Fix coverage config

---

composer.lock
inc/inventory/inventory.class.php
inc/system/requirementsmanager.class.php

Update inventory lib

---

inc/notificationtargetchange.class.php
inc/notificationtargetticket.class.php

Fix two typos (an an -> an)

---

inc/ruledictionnarysoftwarecollection.class.php

Escape software name in rules; fixes #9004

---

inc/knowbaseitem.class.php

Improvement for #8847 : sort files by name

order files by name on kb

---

inc/rule.class.php
inc/ruleticket.class.php
tests/functionnal/RuleTicket.php

Add new 'validation' criteria to tickets rules

---

css/styles.scss
inc/dropdown.class.php
inc/html.class.php
inc/search.class.php
js/common.js
tests/functionnal/Search.php

Internal ref: 21809.
Useful to export search results (only the name column) and paste them somewhere else.

Copy names to clipboard

---

inc/console/commandloader.class.php

| Fixed tickets | https://github.com/pluginsGLPI/formcreator/issues/2236

Prevent console error when a plugin is installed twice

---

CHANGELOG.md
inc/commonitiltask.class.php

Deprecate unused CommonITILTask::showInObjectSumnary()

---

CHANGELOG.md
inc/change_ticket.class.php
inc/commonitilobject.class.php
inc/itilfollowup.class.php
inc/problem_ticket.class.php
inc/projecttask_ticket.class.php

Deprecate unused code

---

composer.lock
tests/fixtures/inventory/phone_1.json

Fix inventory schema

---

inc/define.php
inc/enclosure.class.php
inc/migration.class.php
inc/passivedcequipment.class.php
inc/pdu.class.php
inc/rack.class.php
inc/update.class.php
install/update_955_956.php
tests/units/Migration.php

| Fixed tickets | #9021
The Infocom tab exists for these items already but they aren't in the `infocom_types` array so they don't have the needed search options.

Add infocom search options to DC assets

---

.eslintrc.json
CHANGELOG.md
ajax/search.php
css/includes/pages/_search.scss
inc/html.class.php
inc/search.class.php
js/modules/Search/GenericView.js
js/modules/Search/ResultsView.js
js/modules/Search/Table.js
templates/components/dropdown/limit.html.twig
templates/components/search/display_data.html.twig
templates/components/search/pager.html.twig
templates/components/search/table.html.twig
templates/layout/parts/head.html.twig
tests/functionnal/Search.php

Create a more fluid searching experience.
Major changes:
- The column headers are now always visible when scrolling (Sticky headers)
- You can sort by more than one field at a time (Multi-column sorting)
- Search results update through AJAX requests instead of a full page reload
This should improve perceived performance when searching. It also fixes the issue where the automatic ticket list refresh could reload the full page while you are trying to change your search or perform massive actions.

Fluid Search Experience

---

inc/link.class.php

With the domain management feature, the handling of the [DOMAIN] tag in external links was removed but the array of accepted tags wasn't changed so it showed in the UI that it was valid, and it wasn't clear in the changelog that this tag was no longer supported.
This PR tries to re-add backwards compatibility to some degree by using the first linked domain's name.
I don't know the best way of supporting multiple domains going forward.

Try fix BC for external links with domains

---

inc/marketplace/controller.class.php

Replace deprecated usages from wapmorgan\UnifiedArchive

---

inc/dashboard/provider.class.php

Add missing solved state for ticket summary widget
| Fixed tickets | internal 22165

feat(dashboard): add missing solved state

---

inc/tasktemplate.class.php

Add missing SO for tasktemplate
Need for this-> https://github.com/pluginsGLPI/datainjection/pull/237
| Fixed tickets | Internal 22192

feat(core): add missing SO

---

inc/ticket.class.php
tests/functionnal/MassiveAction.php

Add massive action to link Tickets with a Project Task.

Link project task massive action

---

tests/DbTestCase.php

See https://github.com/glpi-project/glpi/pull/9147/files#diff-c58d39865d39c39278dd02e35cd98924bc956d9a0bcbb8ea50cd7d9ce957d719R816

Correctly handle slashes in functionnal tests checks

---

css/includes/_base.scss
inc/application/view/extension/dbextension.class.php
inc/application/view/extension/dropdownextension.class.php
inc/application/view/extension/htmlextension.class.php
inc/application/view/extension/itemtypeextension.class.php
inc/application/view/extension/modelextension.class.php
inc/application/view/extension/toolboxextension.class.php
inc/application/view/templaterenderer.class.php
inc/blacklist.class.php
inc/commondbchild.class.php
inc/commondcmodeldropdown.class.php
inc/commondevice.class.php
inc/commondropdown.class.php
inc/commonitilrecurrent.class.php
inc/domainrecordtype.class.php
inc/dropdown.class.php
inc/entity.class.php
inc/fieldblacklist.class.php
inc/fieldunicity.class.php
inc/location.class.php
inc/manufacturer.class.php
inc/operatingsystemkernelversion.class.php
inc/planningexternaleventtemplate.class.php
inc/projecttasktemplate.class.php
inc/tasktemplate.class.php
inc/vlan.class.php
inc/wifinetwork.class.php
templates/components/form/fields_macros.html.twig
templates/components/form/pictures.html.twig
templates/dropdown_form.html.twig

[Modern UI] Dropdown forms UI

---

inc/api/api.class.php

Add ITILObject actor HATEOAS classes

---

.github/workflows/nightly_build.yml
tools/github-nightly-description.sh

Add nightly builds publishing support

ci: nightly builds publishing

---

.github/workflows/nightly_build.yml

Add nightly build of master branch and enable manual build

---

.github/workflows/nightly_build.yml

Fix nightly cleaning

---

ajax/searchoptionvalue.php
inc/dashboard/filter.class.php
inc/dashboard/provider.class.php
inc/dbutils.class.php
inc/dropdown.class.php
inc/search.class.php
inc/user.class.php
tests/functionnal/Search.php

Add a new "Myself" search criteria:
It works the same as "My groups" but for the connected user.
| Fixed tickets | !22209

Add 'Myself' search criteria

---

css/includes/components/itilobject/_timeline.scss
inc/commonitilobject.class.php
templates/components/itilobject/timeline/form_document_item.html.twig
templates/components/itilobject/timeline/sub_documents.html.twig
templates/components/itilobject/timeline/timeline.html.twig

**from**
**to**
I open the pr separately, because i'm note sure about right management nor with the twig function extension (the design is ok i think)

sub documents

---

css/legacy/includes/_styles.scss
inc/dropdown.class.php
js/common.js
js/glpi_dialog.js
templates/components/messages_after_redirect_alerts.html.twig
templates/components/messages_after_redirect_toasts.html.twig
templates/components/search/controls.html.twig

UI adaptation/compatibility for https://github.com/glpi-project/glpi/pull/9022.

Modern UI / Copy names

---

tools/github-nightly-description.sh

Set a date when no git commit if found for an archive

Fix just build nightly date

---

tests/bin/test-updated-data
tests/bootstrap.php
tests/src/BootstrapUtils.php
tests/src/Toolbox.php

Fix tests var directories init

---

inc/session.class.php
tests/functionnal/Glpi/Inventory/Inventory.php
tests/units/Html.php

Fixes related to files generated during tests

---

inc/pdu_plug.class.php

Disable non working massiva actions; closes #9206

---

inc/ruleticket.class.php
tests/functionnal/RuleTicket.php

when assigning delete groups to add

---

inc/projecttask.class.php

Fix not planned project tasks populate

---

inc/config.class.php
install/empty_data.php
install/migrations/update_9.5.x_to_10.0.0/planning_work_days.php
js/planning.js

New configuration option:  
After:  
| Fixed tickets | !22107

Planning: add configuration for working days

---

inc/toolbox.class.php

Fix resizing of BMP images; fixes #5683

---

inc/commonitilobject.class.php
inc/ruleticket.class.php
tests/functionnal/Rule.php
tests/functionnal/RuleTicket.php

RuleTicket: Add followup from template

---

inc/glpinetwork.class.php
inc/marketplace/view.class.php

1. On registration key page:
2. On marketplace page:
3. Force informations refresh when displaying the registration key page.

Handle terminated subscriptions on marketplace

---

.github/actions/docker-compose-app.yml
.github/actions/init_install-dependencies.sh
.github/workflows/ci.yml
.github/workflows/coverage.yml

Use lockfiles on CI test suite

---

inc/marketplace/api/plugins.class.php
inc/marketplace/controller.class.php

Log plugin version when downloaded from marketplace

---

tests/functionnal/CommonDBTM.php

Give unit tests for CommonDBTM::getById()

add tests for getById

---

inc/dashboard/filter.class.php
install/migrations/update_9.5.x_to_10.0.0/dashboard_filters.php
install/mysql/glpi-empty.sql

Fix #9179 : different filters on the same dashboard depending on preference of each user.

fix dashboard filter

---

inc/cartridgeitem.class.php
inc/computer.class.php
inc/consumableitem.class.php
inc/monitor.class.php
inc/networkequipment.class.php
inc/peripheral.class.php
inc/phone.class.php
inc/printer.class.php
inc/software.class.php

Deleted redondant lines in rawSearchOptions()

---

inc/commonitilobject.class.php

Fix loading of TicketTemplate from settings; fixes #9013

---

inc/projecttask.class.php

When creating/updating milestones from another source than the UI form, planned/real dates may be not set.

Fix project milestones creation/update

---

inc/application/view/extension/documentextension.class.php
inc/commonitilobject.class.php
templates/components/itilobject/timeline/form_document_item.html.twig
templates/components/itilobject/timeline/sub_documents.html.twig
templates/components/itilobject/timeline/timeline.html.twig
templates/components/photoswipe.html.twig

Re-add thumbnails to timeline and re-add the ability to open images in a lightbox.

{Modern UI] Timeline images

---

.composer-require-checker.config.json
front/inventory.php
inc/agent/communication/abstractrequest.class.php
inc/agent/communication/headers/common.class.php
inc/inventory/inventory.class.php
inc/inventory/request.class.php
tests/functionnal/Glpi/Agent/Communication/Headers/Common.php
tests/web/Glpi/Inventory/Inventory.php

This is now present in the agent: https://github.com/glpi-project/glpi-agent/pull/16

Agent communication protocol

---

tests/functionnal/CommonDBTM.php

tests for CommonDBTM::getById() (branch master  only)

add tests to getById

---

templates/components/itilobject/timeline/form_task.html.twig

[Modern UI] Re-add planning button in task

---

inc/features/inventoriable.class.php
inc/inventory/asset/mainasset.class.php
inc/inventory/conf.class.php
inc/inventory/inventory.class.php
tests/functionnal/Glpi/Inventory/Inventory.php

Limit to 1000 files per directory for inventory files

---

install/empty_data.php
install/migrations/update_9.5.x_to_10.0.0/native_inventory.php

Default display for agents list

---

inc/inventory/asset/operatingsystem.class.php

This follows this [inventory_format PR](https://github.com/glpi-project/inventory_format/pull/52) and this [glpi-agent commit](https://github.com/glpi-project/glpi-agent/commit/00e7b27eb7fbd62b7f7a156eeeca704cebbbaa95).

Remove unused code on obsoleted properties

---

inc/savedsearch.class.php

Before:
After:
| Fixed tickets | !22341

Fix duplicated saved searched

---

inc/glpipdf.class.php

Static method must use default configuration

---

inc/dashboard/provider.class.php

Fix duplicated count in dashboards (#9134)

---

front/change.form.php
front/problem.form.php
front/ticket.form.php

Fix ITIL Kanban page titles

---

inc/search.class.php

Set values for the All criterion instead of an empty string, for tickets, problems and changes
fixes #9341
| Fixed tickets | #9341

Added values for 'All' criterion for ticket statuses

---

inc/console/application.class.php

Set glpiname from cli commands

---

inc/dropdown.class.php

In master branch, support for custom values was added, (key  toadd of options of Html::jsAjaxDropdown())
The added valuses are not taken into account in the count reported to the browser.

fix count of items on ajax users dropdown

---

.composer-require-checker.config.json
inc/authldap.class.php

Drop useless code (was used on PHP < 7.3)

---

inc/database.class.php

fix(database): add unit size

---

front/inventory.php
inc/features/inventoriable.class.php
inc/inventory/conf.class.php
inc/inventory/inventory.class.php
inc/ruleimportassetcollection.class.php

It fixes inventory download link and fix inventory getInventoryFileName() method usage as it still includes GLPI_INVENTORY_DIR.

Fix inventory download link

---

inc/ruleimportasset.class.php

Init rule for database inventory

feat(core): init rule for database inventory

---

front/report.infocom.conso.php

I made the code more generic and remove the hard coded config

Display other infocom report for all infocom_types compatible items 

---

inc/based_config.php
tests/bootstrap.php

Add ability to customize config dir used by tests

---

inc/dropdowntranslation.class.php

Fix issues preventing you from translating dropdowns using a namespaced class.

Support namespaced classes for dropdown translations

---

ajax/dashboard.php
inc/dashboard/grid.class.php
inc/dashboard/widget.class.php
js/dashboard.js

With debug mode on or off, loading the central dashboard (27 cards. Default + 1 plugin card) takes around 12 seconds. The GLPI and DB were both hosted on my laptop at the time so I expected it to be slow, but it seemed pretty bad in comparison to other parts of GLPI.
I profiled multiple portions of the code and found a few optimizations that could be made and got it down to about 3 seconds at most. I expect other users to see similar or better performance improvements.
On the client side, I saw that a synchronous request to get filter data was made for every card it tried to load that takes up to half a second each time. …

Dashboard load time improvements

---

inc/database.class.php
install/empty_data.php
install/migrations/update_9.5.x_to_10.0.0/databases.php

fix(database): missing raw search options

---

inc/search.class.php
templates/components/search/display_data.html.twig

Fix issues preventing the fluid search from working with namespaced itemtypes and some other issues with the search page.

Fix search pages for namespace itemtypes

---

inc/report.class.php

default report was not showing assets created by modules

feature: default report more generic

---

inc/search.class.php
templates/components/user/picture.html.twig

display avatars in user list

---

inc/ticket.class.php
install/migrations/update_9.5.x_to_10.0.0/tickettask.php
install/mysql/glpi-empty.sql
templates/components/itilobject/fields_panel.html.twig
templates/components/itilobject/linked_tickets.html.twig
templates/components/itilobject/mainform_open.html.twig
templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/form_task.html.twig
templates/components/itilobject/timeline/timeline.html.twig
templates/components/itilobject/timeline/timeline_item_header.html.twig

 Add task promotion to ticket

---

inc/authldap.class.php
inc/budget.class.php
inc/config.class.php
inc/rssfeed.class.php
inc/user.class.php
templates/asset_form.html.twig

Few input fixes

---

inc/entity.class.php
inc/html.class.php
inc/impact.class.php
inc/item_devices.class.php
inc/mailcollector.class.php
inc/toolbox.class.php
templates/components/form/fields_macros.html.twig

Feat/modern UI btngroups

---

inc/html.class.php
templates/components/form/fields_macros.html.twig

Fix date and date time selector display

---

front/ticket.php

remove duplicate minidashboard on tickets list

---

inc/agent.class.php
inc/unmanaged.class.php

Drop deprecated HTML align attribute

Fix itemtype dropdown values

---

templates/generic_show_form.html.twig

notices for contract expiration displayed raw html

---

inc/contract.class.php
templates/components/itilobject/fields_panel.html.twig

missing part of #8947 in feat/modern-ui

show contract field on new ticket form

---

inc/ticket_ticket.class.php
templates/components/itilobject/linked_tickets.html.twig
templates/components/itilobject/timeline/form_solution.html.twig

Fix ticket_ticket issues

---

inc/itilsolution.class.php

fix bad check on users_id field from itilsolution

fix(solution): fix missing users_id from DB

---

package-lock.json
package.json
templates/layout/parts/menu.html.twig

fix profile-selector and language selector issue
waiting for tabler to fix their issues

use npm-force-resolutions to upgrade bootstrap in tabler

---

css/legacy/includes/_styles.scss
inc/entity.class.php

use badges for inherited values (contrast was broken on dark themes)

---

inc/html.class.php

[Modern UI] Fix undefined evt

---

templates/components/form/modals_macros.html.twig

[Modern UI] Add ability to specify custom modal classes

---

inc/computer.class.php
inc/item_softwarelicense.class.php
inc/monitor.class.php
inc/networkequipment.class.php
inc/peripheral.class.php
inc/phone.class.php
inc/printer.class.php
inc/softwarelicense.class.php
tests/bootstrap.php
tests/functionnal/MassiveAction.php

Missing massive actions to link a license to an item (computer, monitor, network equipment, ...) and vice versa

fix massivaction license

---

inc/console/application.class.php
install/install.php

Ensure cache service is initialized prior to DB

---

front/change.form.php
front/problem.form.php
front/ticket.form.php
front/ticket_ticket.form.php
templates/components/itilobject/actors/assign_to_me.html.twig
templates/components/itilobject/actors/main.html.twig
templates/components/itilobject/layout.html.twig
templates/components/itilobject/linked_tickets.html.twig

Force POST method for some itil actions

---

css/palettes/__defaults.scss
css/palettes/_auror.scss
css/style_install.scss
front/css.php
inc/config.class.php
inc/config.php
inc/html.class.php
inc/telemetry.class.php
install/install.php
install/update.php
templates/components/alerts_macros.html.twig
templates/install/accept_license.html.twig
templates/install/choose_language.html.twig
templates/install/step0.html.twig
templates/install/step1.html.twig
templates/install/step2.html.twig
templates/install/step3.html.twig
templates/install/step6.html.twig
templates/install/step7.html.twig
templates/install/step8.html.twig
templates/install/update.html.twig

Initialy i started (it slipped a little :p) the work by wanted to fix the language selector (a select2 one) present at first page of install/update process and i found css styles was not loaded.
I added a var `$skip_db_check` in front/css.php to have scss compile feature available for installation (This is most important change), `includes.php` check this var before checking existence of DB.
And i moved most html parts of installation into twig templates.
I didn't touch a lot of update process (just the final page and buttton styles)
I found the following errors i didn't understant (yet) :
```
[2021-09-09 11:49:09] glpiphplog.DEBUG: …
```

move most of install html into twig templates and apply bootstrap styles

---

inc/console/database/installcommand.class.php
inc/console/database/updatecommand.class.php
inc/console/traits/telemetryactivationtrait.class.php
inc/console/traits/telemetryenablementtrait.class.php
inc/telemetry.class.php

Add ability to (en|dis)able Telemetry during install/update process

---

inc/commondbtm.class.php
tests/functionnal/Computer.php

Initially proposed in #9276 comments.

Enhance CommonDBTM::getFromDBByCrit() warning trace

---

package-lock.json
package.json

Use dev branch of @tabler/core

---

inc/transfer.class.php
install/empty_data.php
install/migrations/update_9.5.x_to_10.0.0/transfer.php
install/mysql/glpi-empty.sql
tests/functionnal/Transfer.php

FEATURE: During an entity transfer of an item (computer) the linked certificates were not managed.
FIX: During a transfer, links to contracts were removed.
| Fixed tickets | 21637

feature : transfer certificate in item

---

.github/workflows/close_stale_issues.yml

Automatically close stale issues

---

ajax/agent.php
ajax/gantt.php
ajax/kanban.php
ajax/reservations.php
inc/features/inventoriable.class.php

Apply latest security fixes to AJAX operations that have been introduced in master branch.

Ensure AJAX writing operations are using POST method

---

js/glpi_dialog.js

Added Success toast.
Added ability to customize the toast caption.
Added ability to specify the following toast options:
- Delay (How long it is visible)
- Animated - True if animated
- Animation - Class for the animation
- Animation Extra Classes - Extra classes to use for the animation such as a delay or speed class
Added type definition for the toast options for documentation and IDE autocomplete.

[Modern UI] More Toast Options

---

inc/commonitilobject.class.php
inc/notificationtargetcommonitilobject.class.php
tests/functionnal/NotificationTargetTicket.php

Fix timeline items order in notifications

---

front/ldap.php
inc/authldap.class.php
inc/dropdown.class.php
inc/html.class.php
templates/pages/admin/users_ldap.html.twig

Admin > Users > Ldap import was unreadable.
Replacing all html by twig templates should be better but too much time consuming atm.
I still replaced the index as it's a very easy part

fix ui of users ldap import

---

.github/workflows/ci.yml

Run tests on MariaDB 10.6

---

inc/authldap.class.php

| Fixed tickets | !22553
Alternative to #9522.

First try on known LDAP server(s) to speed-up login

---

inc/config.class.php

Add current language in system information

---

inc/software.class.php
tests/functionnal/Software.php

Add search option on softwareversion architecture

---

js/fileupload.js
templates/components/form/fields_macros.html.twig

[Modern UI] Fix image pasting in timeline forms

---

inc/user.class.php

This feature allow people to search user by registration_number in user dropdown

add possibility to search user by registration_number in user dropdown

---

css/styles.scss
inc/change.class.php

Manage change template from create form
Rework css / style
Display missing fields on create form
| Fixed tickets | Internal 22614

feat(change): use change template from create form

---

CHANGELOG.md
inc/change.class.php
inc/problem.class.php
templates/components/itilobject/fields_panel.html.twig

move changes|problems analysis and plans tabs to field panel

---

inc/auth.class.php
inc/commondbtm.class.php
inc/contract.class.php
inc/document.class.php
inc/dropdown.class.php
inc/item_ticket.class.php
inc/rule.class.php
inc/user.class.php
templates/components/form/fields_macros.html.twig
templates/components/itilobject/fields_panel.html.twig

Alternative solution for #9503.

[Modern UI] Hide some dropdowns if they are empty

---

inc/marketplace/view.class.php

marketplace: permits to download again a plugin in a 'clean' state

---

css/includes/_base.scss
inc/datacenter.class.php
inc/domain.class.php
inc/inventory/inventory.class.php
inc/plugin.class.php
inc/project.class.php
inc/ticket.class.php

fix context links display

---

front/change.form.php
front/commonitiltask.form.php
front/itilfollowup.form.php
front/problem.form.php
front/ticket.form.php
inc/knowbaseitem.class.php
templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/form_task.html.twig

Allows to create a kb from followup or task, as it already exists in solution.
Linked: https://github.com/glpi-project/glpi/pull/9593
| Fixed tickets | !22387

FEAT(modern-ui): create kb from fw or task

---

inc/ticket_ticket.class.php

Fix SQL escaping

---

front/cable.form.php
front/cable.php
front/socket.form.php
front/socket.php
inc/html.class.php
tests/units/Html.php

Move ```Cable``` entry to ```Assets```

Move cable entry to asset

---

css/includes/_base.scss
package.json
webpack.config.js

[Modern UI] Import tabler icons in main CSS

---

inc/entity.class.php

missing form-control in entity address form

---

composer.lock
front/inventory.php
inc/agent/communication/abstractrequest.class.php
inc/inventory/inventory.class.php
inc/inventory/request.class.php
inc/plugin/hooks.class.php
tests/functionnal/Glpi/Inventory/Assets/Battery.php
tests/units/Glpi/Inventory/Request.php

* add a hook to set extra information on prolog
* rework xml generation to use attributes on nodes
* add a hook for network discovery

Improve inventory

---

inc/commonitilobject.class.php

Fix getLegacyTimelineActionsHTML for plugins

---

inc/impact.class.php

Fix potential empty value

---

inc/entity.class.php
install/migrations/update_9.5.x_to_10.0.0/entity.php
install/mysql/glpi-empty.sql

Add administrative number field for entities and allow filtering it

Entity registration number

---

inc/define.php

Add appliances to global search

---

templates/components/itilobject/fields/status.html.twig

Fix status icon display on tickets

Fix status icon display on tickets

---

front/planningcsv.php

clean genical usage in planning csv export

---

composer.lock
inc/agent.class.php
inc/inventory/asset/networkequipment.class.php

Currently includes #9831 since this is not yet merged. See only last commit

Inventory: name and credentials

---

inc/html.class.php

fix date picker UI

---

ajax/updatecurrenttab.php

simplify code

---

css/install.scss
install/install.php

1) Licence field text color (inherited from container) was almost identical to field background.
2) When DB config file was not created, error message was displayed without HTML header/styles/...

Fix some install process display issues

---

inc/inventory/asset/cartridge.class.php
inc/inventory/asset/inventorynetworkport.class.php
inc/inventory/asset/printer.class.php
install/migrations/update_9.5.x_to_10.0.0/native_inventory.php
tests/functionnal/Glpi/Inventory/Assets/Printer.php

Few fixes for printers inventory

---

inc/savedsearch.class.php

Hide Alert of SaveSearch for self-service

Hide Alert of SaveSearch for self-service

---

inc/marketplace/view.class.php

suggest download again cleaned plugin only when version available

---

inc/inventory/asset/mainasset.class.php
inc/ruleimportasset.class.php

Many infromation were missing calling rules

---

composer.lock
install/migrations/update_9.5.x_to_10.0.0/native_inventory.php
install/mysql/glpi-empty.sql
tests/functionnal/Glpi/Inventory/Inventory.php

Missing autoupdatesystems_id on printers

---

inc/dashboard/widget.class.php

Following https://github.com/glpi-project/glpi/pull/9757

Missing cache_key parameter

---

css/standalone/dashboard.scss

fix z-index of dashboards tooltips

---

inc/agent/communication/abstractrequest.class.php
inc/inventory/request.class.php
inc/plugin/hooks.class.php
tests/units/Glpi/Inventory/Request.php

Add SNMP inventory hook

---

inc/agent/communication/abstractrequest.class.php
tests/units/Glpi/Inventory/Request.php

Add missing deflate compression; add tests

---

templates/components/form/buttons.html.twig

make trashbin button with warning style

---

css/includes/components/_global-menu.scss

fix z-index of user menu (overlap of sticky search headers)

---

templates/layout/parts/breadcrumbs.html.twig

prevent long breadcrumbs to push context links in responsive mode

---

css/includes/_base.scss

Follow d5354ba481a0d57c87ec0f832f83c238d10bae60
Style of button with .fa-stack need different styles for desktop or responsive.

fix fa-stack

---

front/crontask.php
front/dropdown.common.php
inc/commondropdown.class.php
inc/group.class.php
inc/mailcollector.class.php

There's still an issue with page height due to these titles but i'll fix that in another pr

make style of titles in search page with bootstrap

---

css/includes/components/_global-menu.scss

fix z-index of user menu also in vertical layout

---

inc/user.class.php

fix user initials

---

inc/rulecollection.class.php

Fix rule order change query; fixes #9888

---

css/includes/components/_saved-searches.scss

another z-index issue

---

templates/components/search/controls.html.twig

scroll to top when enabling 'toggle search filters'

---

inc/item_disk.class.php
inc/search.class.php

natural sorting of volume percent free

---

inc/entity.class.php
inc/inventory/asset/mainasset.class.php

Use entity configuration for automatic transfer

---

inc/contact.class.php
inc/supplier.class.php
install/migrations/update_9.5.x_to_10.0.0/contact.php
install/migrations/update_9.5.x_to_10.0.0/supplier.php
install/mysql/glpi-empty.sql
templates/generic_show_form.html.twig

Add administrative number field for supplier and contact

Supplier and contact add administrative number

---

templates/components/itilobject/fields/priority_matrix.html.twig

Fix a typo in variable name (missing `s`).

Fix priority matrix

---

inc/commondcmodeldropdown.class.php

Fix computer model pictures saving

---

inc/html.class.php
templates/layout/parts/page_header.html.twig

more subtle style for goto menu

---

templates/layout/parts/profile_selector.html.twig

The entity tree has a wrong dom id

bad dom id for entity tree

---

inc/agent.class.php
install/migrations/update_9.5.x_to_10.0.0/native_inventory.php
install/mysql/glpi-empty.sql

Add agent_base_url configuration in entities

---

inc/cable.class.php
inc/commondbtm.class.php
inc/console/ldap/synchronizeuserscommand.class.php
inc/contract_item.class.php
inc/dashboard/provider.class.php
inc/html.class.php
inc/pdu_rack.class.php
inc/projecttasktemplate.class.php
inc/ruleticket.class.php
inc/search.class.php
inc/toolbox.class.php
inc/transfer.class.php
inc/user.class.php

Fix missing breaks in switches

---

templates/install/blocks/requirements_table.html.twig

fix requirments icons

---

inc/search.class.php
js/common.js

fix height of search data when displayed as map

---

css/includes/components/_racks.scss
inc/pdu_rack.class.php
js/rack.js

Fixes for some rack issues:
- adding pdu was broken
- edit button on pdu was bottom of the page
- modal dialogs were very small
And i move some legacy code to dedicated file

Fix rack issues

---

inc/dropdown.class.php

fix quotes dispklying for dropdown add link

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
composer.json
composer.lock
inc/dbutils.class.php
inc/inventory/asset/volume.class.php

Switch test matrix to PHP 8.1

---

css/includes/pages/_search.scss

fix z-index of export dropdown in search header

---

inc/commondbtm.class.php
inc/gantt/item.class.php
inc/html.class.php
inc/rack.class.php
inc/reservationitem.class.php
inc/search.class.php

fix some php8.1 errors

---

inc/knowbaseitem.class.php
inc/reservationitem.class.php

remove lists icons on kb & reservations

---

tests/functionnal/Glpi/Inventory/Assets/Computer.php
tests/functionnal/Glpi/Inventory/Assets/Printer.php

There was a typo in glpi_current**t**ime

Fix inventory tests

---

inc/inventory/asset/networkcard.class.php
inc/inventory/conf.class.php
tests/functionnal/Glpi/Inventory/Assets/NetworkCard.php

Add inventory configuration for net cards and/or virtuals

---

inc/appliance.class.php
inc/certificate.class.php
inc/software.class.php
inc/softwarelicense.class.php
tests/functionnal/Software.php

Certificate data could not be displayed in appliances and software searches.
| Fixed tickets | !22982

fix: missing certificates datas

---

inc/infocom.class.php

php8.1 error on infocom

---

inc/auth.class.php
inc/authldap.class.php
inc/config.class.php
inc/console/ldap/synchronizeuserscommand.class.php
inc/session.class.php
inc/user.class.php
install/empty_data.php
install/migrations/update_9.5.x_to_10.0.0/configs.php
tests/LDAP/AuthLdap.php

Implement LDAP Restoration Process

---

inc/computer.class.php

computer icon should match other ti icons

---

css/includes/components/_global-menu.scss

fix spacing of menu icons in hz layout

---

templates/components/form/buttons.html.twig

align buttons to the right of the form

---

templates/layout/parts/context_links.html.twig

On a suggestion by Pascal, the add button, as it's a primary action, should more visible.

make add button more visible

---

inc/commonitilobject.class.php
inc/problem.class.php

Clean up some massives actions that shouldn't be available on "massive update" and do nothing:  
| Fixed tickets | !23034

Clean up ticket massive actions

---

inc/dashboard/widget.class.php
inc/html.class.php

Fix SCSS generation on Windows

---

css/includes/_base.scss
css/includes/_dark.scss
css/includes/_global-variables.scss
css/includes/components/_select2.scss
css/palettes/auror_dark.scss
package-lock.json
package.json
templates/components/form/buttons.html.twig
templates/layout/parts/global_search_form.html.twig

Opened as wip as buttons styles have changed, i need to do a pass on them.
@cconard96 could you do a pass on dark mode, there a lot of changes for this mode in this beta

upgrade tabler to beta-5

---

templates/layout/parts/saved_searches.html.twig

fix header of savedsearches panel

---

inc/html.class.php

Fix font-awesome icon for SimpleForm

---

js/modules/Search/Table.js

permits to use meta key (on mac) for multisort

---

inc/commonitilobject.class.php

Fix where for query kanban

---

css/standalone/dashboard.scss
inc/dashboard/grid.class.php

display glpi logo in fullscreen dashboard

---

inc/displaypreference.class.php

fix display of add button in display preferences modal

---

inc/inventory/asset/inventorynetworkport.class.php
inc/inventory/asset/mainasset.class.php
inc/inventory/asset/networkequipment.class.php
inc/inventory/asset/networkport.class.php
tests/functionnal/Glpi/Inventory/Assets/NetworkEquipment.php
tests/functionnal/Glpi/Inventory/Assets/Printer.php

Try to deal properly with management ports

---

inc/dashboard/provider.class.php

Fix Title Card Panel Display - Unresolv

---

src/KnowbaseItem.php

[GLPI 10] SQL-Errors on display knowbase

---

css/includes/components/_debug-panel.scss
src/Html.php

Fix debug tables in dark themes

---

src/NetworkPortType.php

Invalidate cache

---

src/Toolbox/Sanitizer.php

Optimize DB escape handling in Sanitizer

---

src/Rule.php

Check if class exists before instanciate it

---

src/CommonDBTM.php
templates/generic_show_form.html.twig

Hide asset image section when there are no images

---

js/dashboard.js

fix icon toggle when editing dashboard

---

src/CommonDBTM.php

Check model exist before instanciating

---

templates/layout/parts/context_links.html.twig

Fix Icons Context (with Gantt locale / kanban / setup)

Fix Icons Context

---

src/Features/AssetImage.php

@cconard96 24c275f91c47cdb835bbf5ff36da861020a80c40 commit is for removing the last entry in "other pictures" list.

Permits to remove last entry in other pictures list

---

ajax/unlockobject.php
src/Change.php
src/CronTask.php
src/Infocom.php
src/KnowbaseItem.php
src/Log.php
src/MailCollector.php
src/PlanningRecall.php
src/Plugin.php
src/Problem.php
src/RuleDictionnaryDropdownCollection.php
src/RuleDictionnarySoftwareCollection.php
src/RuleMailCollector.php
src/RuleRight.php
src/Ticket.php
src/Transfer.php
src/User.php
src/XML.php

Command used:
```
sed -E "s/}(( )?\/\/.*)/}/g" -i ajax/**/*.php front/**/*.php inc/**/*.php install/**/*.php lib/**/*.php scripts/**/*.php src/**/*.php tests/**/*.php
```

Useless comments

---

src/Search.php

fix 'Automatic conversion of false to array' when adding metacriteria

---

css/legacy/includes/_inputs.scss
css/legacy/includes/_styles.scss
css/palettes/_includes.scss

add style for legacy inputs

---

inc/includes.php
src/CommonGLPI.php

Force the selection of an entity and/or a profile in the URL
parameters:
- change_profile
- change_entity
| Fixed tickets | !21545

feat: select profile/entity in url

---

src/CommonITILTask.php

| Fixed tickets | (https://github.com/InfotelGLPI/mydashboard/issues/120)

Fix get Task List - add is_deleted criteria

---

src/FQDNLabel.php
src/NetworkPort.php

Fix undefined array key; closes #10062

---

src/Printer_CartridgeInfo.php

Fix double header

---

css/includes/components/_global-menu.scss

Before changes:
After changes:

Fix collapsed sidebar logo hitbox

---

templates/components/itilobject/fields_panel.html.twig
templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/form_solution.html.twig
templates/components/itilobject/timeline/form_task.html.twig
templates/components/itilobject/timeline/form_validation.html.twig

Fix BC breaks in itil child forms hooks

---

templates/pages/admin/events_list.html.twig

Fix invalid Event class namespace reference

---

src/ITILFollowupTemplate.php
templates/dropdown_form.html.twig

review dropdown form layout, and force content field to be full width

---

CHANGELOG.md
src/Html.php

Some missing entries I found while working on plugins.

Improve 10.0 changelog

---

src/CommonGLPI.php
src/Item_Ticket.php

When creating a ticket, see the KB articles of the associated items (as already exists with categories).
| Fixed tickets | !22617

feat(ticket creation): KB items of associated items

---

src/Dropdown.php
src/User.php

readonly option for dropdowns

---

src/Impact.php
src/MapGeolocation.php

remove unwanted public keyword on js functions

---

install/install.php
src/Application/View/TemplateRenderer.php
templates/components/form/inventory_info.html.twig

Do not instantiate cache if it's not writable

---

index.php

Try to detect agent calls

---

src/User.php

Avoid calling DateTime on null

---

css/install.scss

not focused inputs was white on white

force color of input in install

---

ajax/agent.php
src/Agent.php
templates/components/form/inventory_info.html.twig
tests/functionnal/Agent.php

Many fix
surround IPV6 with brackets for Guzzle_client request
fix ajax call response
use $_GET instead of $_POST fron ajax file

Fix remote ping inventory

---

locales/fr_FR.po
locales/ru_RU.po

pull locales (fix plural/singular issues on frfr)

---

css/includes/_base.scss
package-lock.json
package.json
src/CommonDevice.php
src/DeviceProcessor.php
src/RefusedEquipment.php

update tabler/icons and fix some minor icons issues

---

src/Features/PlanningEvent.php
src/PlanningExternalEvent.php

Seen here : https://youtu.be/Mvm9VSePzXE?t=2576
+ bonus php8.1 notice

fix overflow of field when adding external event in planning

---

css/includes/components/_global-menu.scss

fix z-index issues on responsive menu

---

templates/components/pager.html.twig

(include a re-indent, check pr witrhout spaces changes)

display pagination only when nb pages > 1

---

src/System/Requirement/DbEngine.php
templates/install/blocks/requirements_table.html.twig
tests/units/Glpi/System/Requirement/DbEngine.php

1. Show validation messages when a requirement is missing.
2. Add minimum required DB server version in validation message.

Show missing requirements errors

---

inc/define.php
install/empty_data.php
install/migrations/update_9.5.x_to_10.0.0/configs.php
install/mysql/glpi-empty.sql
src/CommonITILObject.php
src/Config.php
templates/components/itilobject/footer.html.twig
templates/components/itilobject/timeline/timeline.html.twig

Following today meeting with partners, some said they prefer to have new followups at the top of the timeline.

allow users to setup timeline order (natural or reverse)

---

install/empty_data.php
install/migrations/update_9.5.x_to_10.0.0/pendingreason.php
src/User.php
tests/functionnal/NotificationMailing.php
tests/functionnal/Reminder.php

| Fixed tickets | #10134
WIP, i need to check some part of pending reasons.

fix pending reasons

---

install/empty_data.php
install/migrations/update_9.5.x_to_10.0.0.php
install/migrations/update_9.5.x_to_10.0.0/cable.php
src/DbUtils.php
src/Search.php

| Fixed tickets | #10168 #10130

Fix Socket namespace handling

---

src/Rule.php
templates/layout/parts/context_links.html.twig

| Fixed tickets | #10155
After:

fix transfer list icon, fix #10155

---

src/Domain.php

| Fixed tickets | #10189 
These fields were rendered in the old form but weren't listed as additional fields, so they weren't shown when using the new templates.

Add missing domain fields

---

templates/components/form/buttons.html.twig

i got this purge button on Users:

show devices keep checkbox only on itemtypes with devices

---

css/includes/components/itilobject/_timeline.scss

If use hook for add actions on a existing ticket, there is a css problem for others buttons

Fix Css For Plugins Actions Into tickets

---

src/NotificationTarget.php

Add missing tags in "list of available tags"
| Fixed tickets | !23068

feat(notification template): list of available tags

---

ajax/dashboard.php

Allow display of dashboards in simplified interface
Related to : https://github.com/pluginsGLPI/formcreator/pull/2513

allow dashboards to show on self service

---

src/Search.php

Add Color for Expiration Date field for domains & certificates (on lists)

Add Color for Expiration Date field for domains & certificates

---

templates/pages/assets/cable.html.twig

Fix yet another SocketModel class reference

---

src/SavedSearch_Alert.php

Fix typo in SavedSearch alert cron error

---

src/PendingReasonCron.php

Fix minor typo in pending reasons error

---

src/AuthLDAP.php

| Fixed tickets | #10135
Allows you to avoid configuration errors?

feat(ldap): better UI for BIND option

---

composer.json
composer.lock

Switch back to wapmorgan/unified-archive stable releases

---

templates/layout/parts/profile_selector.html.twig

avoid striping tags when searching in entity tree

---

install/install.php
install/update.php
src/Html.php

Prevent recompilation of scss in install/update process

---

src/Inventory/Inventory.php

Improve inventory menu item rights checks

---

templates/components/form/header.html.twig
templates/components/form/single-action.html.twig

Avoid this issue where an item doesn't support entities:

Do not show entity in header if item doesn't support it

---

src/Html.php

Check the pr without whitespaces changes

don't display default dashboards in menu if user cannot see them

---

src/MailCollector.php
src/Toolbox.php

fixes:
- prevent scrollbars disappearing after selecting a folder
- clicks are now on the button, not just on the icon (easier to click)

fix dialogs present in mail collector

---

css/includes/components/_racks.scss

fix rack pictures not taking 100% height of their container; fix #10283

---

front/reservation.form.php
js/glpi_dialog.js

Intially, I was trying to add a messageAfterRedirect after submiting a reservation.
But i found a lot of issues with glpi_ajax_dialog (strangely, other usages of this function was not impacted)

add message after adding reservation

---

src/Item_Ticket.php

In a ticket, directly access the FAQ articles of the associated items
| Fixed tickets | !22617

feat(ticket): KB items of associated items

---

tests/functionnal/Unmanaged.php

Test unmanageds

---

src/Database.php
src/DatabaseInstance.php

| Fixed tickets | #10158
1st commit is just clean

forward child entity to database from instance

---

templates/components/itilobject/actors/field.html.twig

Required to get this commit https://github.com/pluginsGLPI/itilcategorygroups/pull/39/commits/ce50430bf5f0bf5126e5c00bde48a774240eb7d1 (from plugin itilcategorygroups) working.

complete FILTER_ACTORS hook with complete item

---

src/Migration.php
tests/units/Migration.php

Use unsigned int in 'autoincrement' field format migration

---

src/Unmanaged.php
tests/functionnal/Unmanaged.php

Test and fix Unmanaged conversion

---

src/DBmysql.php
tests/units/DB.php

It may be quiet hard to find which field is related to this warning. Having table+field name in warning may be usefull.

Enhance warning on signed integer usage in primary/foreign key

---

tests/bootstrap.php

Re-enable error handler output on test suite

---

src/Supplier.php

| Fixed tickets | https://forum.glpi-project.org/viewtopic.php?id=282739

feat(supplier): add is_active searchOption

---

inc/mailcollector.class.php
tests/functionnal/RuleTicket.php

| Fixed tickets | #10337
~Waiting for affected user to test and verify.~

Fix mail header rule criteria

---

src/Database.php

Needed at least for datainjection integration, but the entry could be needed for display

add instance searchoption in database list

---

templates/components/itilobject/add_items.html.twig

Show error when trying to add a blank item to ticket

---

README.md
inc/define.php
index.php
src/System/Requirement/PhpVersion.php
src/System/RequirementsManager.php
tests/units/Glpi/System/Requirement/PhpVersion.php

Same reason as glpi-project/doc-install#62

PHP version matrix in README and updated checker

---

src/NotificationEventMailing.php

| Fixed tickets | #9326 
Replace outdated PR #9656 .

Fix links in notifications to admins; fixes #9326

---

install/empty_data.php
install/migrations/update_9.5.x_to_10.0.0/entity.php

Fix default entity config strategy fields for root entity

---

css/includes/_includes.scss
css/includes/components/_asset-form.scss
css/includes/components/itilobject/_timeline.scss
css/includes/mixins/_badges_fixes.scss
package-lock.json
package.json

Update tabler to v1.0.0-beta6

---

src/Console/Database/AbstractConfigureCommand.php
src/Console/Database/ConfigureCommand.php
src/Console/Database/InstallCommand.php
src/Console/Database/UpdateCommand.php
src/Console/Ldap/SynchronizeUsersCommand.php
src/Console/Migration/AppliancesPluginToCoreCommand.php
src/Console/Migration/DomainsPluginToCoreCommand.php
src/Console/Migration/DynamicRowFormatCommand.php
src/Console/Migration/MyIsamToInnoDbCommand.php
src/Console/Migration/RacksPluginToCoreCommand.php
src/Console/Migration/TimestampsCommand.php
src/Console/Migration/UnsignedKeysCommand.php
src/Console/Migration/Utf8mb4Command.php
src/Console/Security/ChangekeyCommand.php
tools/deleteorphanlogscommand.class.php

1. Enhance migration commands:
- Add progress bars
- Update property flags even when errors occurs on some tables
2. Mutualize confirmation logic code

Enhance commands

---

front/massiveaction.php

| Fixed tickets | internal !23161

don't require central access to send massiveactions

---

css/standalone/dashboard.scss
js/dashboard.js

~~include #10373~~
Some minor issues i found while working with dashboard:
- data-gs-id doesn't exists anymore (since ?)
- when clearing a dropdown filter, undefined value was set in json and lost at stringify
- fixed  crappy style for date filter

Fix dashboard issues

---

inc/commonitilobject.class.php

a self service user is not allolwed to view user details
internal ref: 23225

fix unreachable URL in self service

---

src/CommonDBTM.php
src/Migration.php

A few minor improvements to https://github.com/glpi-project/glpi/pull/10288.

Multiple dropdown 2

---

inc/commonitilobject.class.php
inc/rule.class.php
inc/ruleticket.class.php

Fix add solution on ticket add rule

---

src/Toolbox/Sanitizer.php
tests/units/Glpi/Toolbox/Sanitizer.php

| Fixed tickets | #10390 
See comments in code for explainations.

Fix rendering of misencoded followups; fixes #10390

---

inc/commonitilobject.class.php

| Fixed tickets | !23090
| Related Forum | https://forum.glpi-project.org/viewtopic.php?id=282462

Cast to get 'NULL' > 0 === false for both PHP 7.4 and 8.0

---

src/Html.php
src/Plugin/Hooks.php

Add helpdesk_menu_entry_icon hook

---

ajax/dropdownTrackingDeviceType.php
templates/components/itilobject/add_items.html.twig

| Fixed tickets | Maybe #10073

Multiple fixes adding items to ITILObjects

---

templates/components/form/fields_macros.html.twig
templates/generic_show_form.html.twig

Fix size field for Monitors

---

inc/change.class.php
inc/commonitilobject.class.php
inc/problem.class.php
inc/ticket.class.php

Add missing file upload field

---

js/common.js
src/NetworkPort.php
src/RefusedEquipment.php

Replace remaining usages of $.dialog()

---

ajax/timeline.php
src/CommonITILObject.php
src/CommonITILValidation.php
templates/components/itilobject/answer.html.twig
templates/components/itilobject/timeline/form_validation.html.twig
templates/components/itilobject/timeline/timeline.html.twig

When trying to edit a validation answer, the request form was opened instead of the anwer form.

Fix validation answer edit form

---

js/modules/Kanban/Kanban.js

| Fixed tickets | #10431
Fix missing role parameter.

Fix removing ITILObject team member from side panel

---

js/dashboard.js

Do not reanimate dashboard counters on resize

---

.github/workflows/close_stale_issues.yml

Since we have identified an issue as a reproductible bug, we should not close it automatically.

Prevent issues with 'bug' label will not be marked as stale

---

inc/commondbtm.class.php
inc/computer_item.class.php

Related to #2548 but I cannot confirm that it is completely resolved yet.

Check canUnrecurs for Computer_Item opposite relation

---

src/Agent.php

| Fixed tickets | #10203
Avoid an exception when a request to an agent fails and return "Unknown" in that case.
```
[2022-01-27 11:36:59] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Return value of Agent::requestAgent() must be an instance of GuzzleHttp\Psr7\Response, null returned in /srv/glpi/src/Agent.php at line 619
Backtrace :
src/Agent.php:630                                  Agent->requestAgent()
ajax/agent.php:58                                  Agent->requestStatus()
```

Update GuzzleHttp client exception handling when requesting agents

---

css/includes/pages/_search.scss

remove little space on top of priority block

---

inc/commonitilobject.class.php

Introduced by ea42249f7c8e614a8f093e4a72fba1f570e62142.

Fix timeline warning

---

src/Inventory/Asset/Antivirus.php

Ensure antivirus is_acvtive has a correct value; fixes #10462

---

src/Dashboard/Widget.php

Fix undefined cache_key error on printer page counters

---

install/empty_data.php
install/migrations/update_9.4.x_to_9.5.0.php
install/migrations/update_9.5.x_to_10.0.0/entity.php
install/mysql/glpi-empty.sql
js/modules/Kanban/Kanban.js
src/Entity.php
src/User.php
templates/components/kanban/kanban.html.twig
templates/components/user/picture.html.twig

Allow disabling initials in Kanban

---

ajax/itillayout.php

Follow #10445, commit e20c0b25ab62df5e3cf76e0ff1f1d04ff6eb91be tested return in the wrong way

fix saving of itillayout

---

src/Agent/Communication/AbstractRequest.php

Fix handling of missing compression in inventory request

---

src/Html.php
templates/components/form/fields_macros.html.twig

displayed required mark on _documents_id

---

inc/define.php

Update GLPI_YEAR to 2022

---

front/css.php

Increase memory limit on SCSS comiplation; fixes #10485

---

src/User.php
templates/components/user/picture.html.twig
templates/layout/parts/user_header.html.twig

use same twig template everywhere for displaying user avatar; fix #10479

---

src/APIClient.php
src/Config.php

add an icon to APIClient; fix #10476

---

front/agent.form.php
src/Inventory/Inventory.php

remove link for adding manually agent, fix #10475

---

src/RichText/RichText.php

Fix RichText detection

---

templates/components/itilobject/actors/field.html.twig
templates/components/itilobject/actors/main.html.twig

Only show users that can be assigned in assign dropdown

---

ajax/cable.php

fix(condition): get socket without defined model

---

templates/pages/assets/socket.html.twig

Remove duplicate or useless input
Before
After

fix(socket): remove useless or duplicate input

---

src/Socket.php

Fix translations for wiring sides

fix(translation): fix translations

---

templates/components/itilobject/fields_panel.html.twig

filter itilcategories by entities; fix #10433

---

package-lock.json
package.json
src/Agent.php
src/Auth.php
src/AuthLDAP.php
src/AuthMail.php
src/ComputerAntivirus.php
src/Domain.php
src/DomainRecord.php
src/Inventory/Inventory.php
src/Item_Cluster.php
src/Item_Enclosure.php
src/Item_OperatingSystem.php
src/Item_Rack.php
src/Item_RemoteManagement.php
src/USBVendor.php
src/User.php
templates/pages/setup/authentication.html.twig

add some missing icons, fix #10518

---

ajax/timeline.php

Fix validation form in locked Tickets

---

src/Database.php

add SO to get the Computer where the database instance is installed

feat(database): add missing SO

---

front/dropdown.common.form.php

Forgot an edge case in my #10114.

Fix commondropdown headers

---

src/Html.php

Fix helpdesk dashboard link

---

src/Item_Kanban.php

| Fixed tickets | #10545
Removed logic to remove special "drop only" columns like "No status" from the saved state. This wasn't working before anyways and having the folded state saved is desired.
Added some safety checks for array element existence.
Added check to prevent moving cards in "drop only" columns. These columns don't have card data saved to the view state.

Fix Kanban warnings

---

front/dropdown.common.form.php

Fix dropdown creation

---

templates/components/itilobject/selfservice.html.twig

A user in a sub-entity will systematically see these tickets created in the root entity
| Fixed tickets | #23297

fix(selfservice): define entities_id

---

front/knowbaseitem.php

| Fixed tickets | #10533 
See with @AdrienClairembault, we revert the changes from #10114

fix kb display, fix #10533

---

css/standalone/dashboard.scss

hide superflu borders on ticket's summary widget in dashboard

---

src/CommonDBTM.php

Fix item name truncate

---

src/Search.php

Handle bad decimal pattern match

---

src/System/Requirement/SeLinux.php

Fix selinux command output

---

front/ticket.form.php

Undefined index; closes #10535

---

src/Search.php

| Fixed tickets | #8179 (maybe)

Fix OLA progress bar

---

src/CommonITILValidation.php

Fix TicketValidation

---

src/Html.php

Fix browser notifications; fixes #10612

---

templates/pages/assets/cable.html.twig

fix asset endpoint type dropdown

---

templates/components/itilobject/fields/priority_matrix.html.twig

Fix lowercase priority labels

---

src/Dashboard/Grid.php

Fix spelling error (private dashboards)

---

.github/dependabot.yml

See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot

Automatically check for Github Actions dependencies updates

---

inc/ticket.class.php

Backport delegatee check fix #10320

---

inc/define.php

Allow one application to be linked to another
| Fixed tickets | !23461

feat(appliance): link appliance to an other

---

src/AuthLDAP.php

Fix LDAP import when sync field is missing; fixes #10669

---

inc/notificationtargetcommonitilobject.class.php

Fix notification to followup author; fixes #10683

---

src/Rule.php

Fix rules criteria/actions encoding issues; fixes #10685

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

Switch CI from MariaDB 10.6 to MariaDB 10.7

---

templates/components/form/inventory_info.html.twig

Move Inventory Hook (not in {% if agent is not null %})

Move Inventory Hook (not in {% if agent is not null %})

---

src/Config.php

missing parenthesis

---

front/central.php

self-service cannot switch entity anymore

---

css/includes/components/_global-menu.scss

| Fixed tickets | #10592
Set z-index higher so that it can show over other elements when in "mobile" mode.

Fix navigation menu z-index

---

src/DisplayPreference.php
src/Html.php

Fix fas for fa-times-circle

---

front/massiveaction.php
src/Api/API.php
src/CommonDBTM.php
src/MassiveAction.php
src/QueuedNotification.php
tests/functionnal/Computer.php
tests/functionnal/Domain.php
tests/functionnal/Transfer.php
tests/web/APIRest.php

Should be reviewed commit by commit.

Fix handling of queued ajax notification

---

src/Console/AbstractCommand.php
src/Console/Migration/AbstractPluginToCoreCommand.php
src/Console/Migration/DatabasesPluginToCoreCommand.php

Add Database Plugin Migration Script
"glpi_plugin_databases_servertypes" & "glpi_plugin_databases_scripts" & "glpi_plugin_databases_scripttypes" cannot be migrated to core...

Add Database Plugin Migration Script

---

ajax/dropdownDelegationUsers.php
front/central.php
inc/db.function.php
src/DbUtils.php
src/Ticket.php
src/User.php
templates/components/itilobject/actors/field.html.twig
templates/components/itilobject/selfservice.html.twig

6a792bf65a87377ba0dd7c73971655fd8762b7be -> just small redesign, the current form was a little crappy
5bc1924b1a3aefa2f2cad5171463ca1f18bc6d35 -> fix an exception when starting a ticket with delegate feature
88ed9ab2ca181b99e53108706c789ff18c3aaefd -> mostly ux changes (hide of some parts, initial user loaded in dropdown)
685565e648043ed21a7e431c2c86565067e9cca9 -> #7015 induce a bug on all users dropdowns. when they are loaded with a value, anonymous user will be the value, but we are in a dropdown for user, so let's display the real username
177151a668d6bcb9308d1230ad0c64daf4c48c5f -> clean of old code and fix usage of entity parameter …

Fix selfservice issues

---

src/Update.php

#10783 introduced a warning on MySQL 5.7
```
3090: Changing sql mode 'NO_AUTO_CREATE_USER' is deprecated. It will be removed in a future release.
in query "SET SESSION sql_mode = ''"
```

Prevent warnings on sql mode change on MySQL 5.7

---

install/migrations/update_9.5.x_to_10.0.0/domains.php

Prevent domains creation date to be erased if already migrated

---

src/Ticket_Contract.php

Hide Ticket contract tab without right

---

src/Plugin.php

Fix PSR-4 loading in plugins

---

front/knowbaseitem.form.php

Fixed bad menu header for KB Item.

Fix KB item header

---

src/Entity.php
src/Features/Clonable.php
src/MassiveAction.php
src/NotificationTemplate.php
src/Rule.php
src/User.php
tests/functionnal/Appliance.php
tests/functionnal/Certificate.php
tests/functionnal/Computer.php
tests/functionnal/Entity.php
tests/functionnal/Monitor.php
tests/functionnal/NetworkPort.php
tests/functionnal/Project.php
tests/functionnal/Rule.php
tests/functionnal/RuleSoftwareCategory.php
tests/functionnal/Software.php
tests/functionnal/Ticket.php
tests/functionnal/User.php

Same as #10707 adapted to master branch.

Fix clone name uniqueness

---

ajax/savedsearch.php
inc/savedsearch.class.php

| Fixed tickets | #10009
Attempted backport of #10515

Backport saved search fix for special chars

---

src/RuleImportAsset.php

move import(serial+uuid) just after update(serial+uuid), fix #9741

---

templates/components/form/fields_macros.html.twig

permits to add extra html to textarea fields

---

templates/components/itilobject/timeline/main_description.html.twig
templates/components/itilobject/timeline/new_form.html.twig

fix overflow on main content also

---

src/Inventory/Inventory.php

Fix error on agent contact action

---

src/Computer.php
src/Enclosure.php
src/Monitor.php
src/NetworkEquipment.php
src/PDU.php
src/PassiveDCEquipment.php
src/Peripheral.php
src/Rack.php

Add ```Rack``` search option 
| Fixed tickets | !23459

feat(searchoption): add rack SO

---

src/AbstractITILChildTemplate.php

The content of the followups and tasks was not translated, although a translation exists.
| Fixed tickets | !23516
_I did another PR for bugfix : #10843_

fix: content translation

---

src/Api/API.php
src/Api/APIRest.php
src/Api/APIXmlrpc.php

Fixes following PHPStan issues:
```
------ ----------------------------------------------------------------------- 
Line   Api/API.php                                                            
------ ----------------------------------------------------------------------- 
210    Access to an undefined property Glpi\Api\API::$verb.                   
210    Access to an undefined property Glpi\Api\API::$verb.                   
214    Access to an undefined property Glpi\Api\API::$verb.                   
323    Result of static method Session::destroy() (void) is used.             
337    Access to an undefined property …
```

Fix PHPStan level 0 issues on API

---

front/ticket.form.php
templates/components/itilobject/timeline/form_document_item.html.twig

Fix document deletion from timeline

---

src/SolutionTemplate.php

Followup and Task templates are translatable, so I guess Solution templates should be translatable too.

Make SolutionTemplate translatable

---

templates/components/itilobject/actors/field.html.twig

Escape actors name in actors selection dropdown

---

src/CommonITILObject.php
src/Search.php
src/Ticket.php

| Fixed tickets | !23402
Alternative to #10586

Highlight TTO/TTR only when exceeded

---

src/MailCollector.php
tests/emails-tests/30-subject-with-special-char.eml
tests/imap/MailCollector.php

Fix collected ticket name encoding; fixes #10879

---

templates/layout/parts/goto_button.html.twig
templates/layout/parts/page_header.html.twig

| Fixed tickets | #10580
Contains also a fix for goto menu in vertical mode

try to have a good condensed menu in horizontal mode, fix #10580

---

inc/commonitilobject.class.php
tests/functionnal/Change.php

Remove duplicate actors in addAdditionalActors

---

ajax/dropdownMassiveAction.php
ajax/massiveaction.php
src/MassiveAction.php

Remove extra escaping for MA values

---

src/CommonGLPI.php

Id is not visible in the ticket view.

Add id in the ticket form

---

src/Inventory/Asset/Device.php
tests/functionnal/Glpi/Inventory/Inventory.php

Do not log item_device updating; closes #10880

---

src/Application/View/Extension/FrontEndAssetsExtension.php
src/Html.php
src/Plugin.php
src/System/Status/StatusChecker.php
templates/layout/page_card_notlogged.html.twig
templates/layout/parts/head.html.twig
templates/layout/parts/page_footer.html.twig

Fix version in plugins JS/CSS files URL

---

src/Rule.php

Hide transfer action for global rules

---

install/migrations/update_9.5.x_to_10.0.0/native_inventory.php
install/mysql/glpi-empty.sql
src/Computer.php
src/Phone.php
tests/functionnal/Glpi/Inventory/Inventory.php

Add missing last inventory date on computers; fixes #10918

---

src/SavedSearch.php

| Fixed tickets | #10924
This hack does not seems to be usefull anymore.

Fix saved search creation form; fixes #10924

---

install/migrations/update_9.5.x_to_10.0.0/databases.php
install/mysql/glpi-empty.sql
src/Database.php
src/Inventory/Asset/DatabaseInstance.php

Add missing ```is_dynamic``` field from ```Database```

fix(database): add missing is_dynamic field

---

src/CommonITILValidation.php
templates/components/itilobject/timeline/form_validation.html.twig

Before:
After (color of secondary buttons changed, new form at bottom):

try to clarify validation tab colors and placement

---

src/Dropdown.php
src/Search.php

| Fixed tickets | #10536 (Issue in comment)

Fix truncated double SQL warning

---

install/migrations/update_9.5.x_to_10.0.0/schema_fixes.php
src/NotificationEventAbstract.php
src/NotificationEventMailing.php

Prevent negative values in glpi_queuednotifications.items_id

---

composer.lock
locales/en_GB.po
locales/glpi.pot
templates/components/itilobject/timeline/form_validation.html.twig

| Fixed tickets | #10916 
Generated using https://github.com/glpi-project/tools/pull/46

Fix locales; fixes #10916

---

src/Html.php
src/Notepad.php

Notepad UI didn't account for missing user pictures and the delete icon was broken.
Before:
After:

Fix notepad UI

---

src/Ticket.php
templates/components/itilobject/mainform_open.html.twig

Fix predefined fields in selfservice

---

.phpcs.xml
src/Console/Config/SetCommand.php
src/Marketplace/Api/Plugins.php
src/Marketplace/Controller.php
src/Marketplace/NotificationTargetController.php
src/Marketplace/View.php
tests/fixtures/plugins/tester/setup.php

`marketplace` and `config` child directories of `src` were exceluded from PHP CS checks.

Fix phpcs excludes

---

templates/components/itilobject/timeline/main_description.html.twig

Fix ticket name encoding

---

tests/functionnal/Ticket.php

Fix ticket tests

---

install/migrations/update_9.5.x_to_10.0.0/databases.php
install/mysql/glpi-empty.sql
src/DatabaseInstance.php
src/State.php
templates/generic_show_form.html.twig

Reported on Forum: https://forum.glpi-project.org/viewtopic.php?id=283108
`is_visible_*` field for database instances was named for Database not Database Instance. The generic form was also set to always use the visibility criteria for computers and not the specific ones for the current item.

Fix state dropdown conditions

---

inc/ticket_ticket.class.php

GLPI 9.5.5
[2022-03-15 10:22:39] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: relid in \glpi\inc\transfer.class.php at line 2464
Backtrace :
inc\transfer.class.php:1078                        Transfer->transferTickets()
inc\transfer.class.php:214                         Transfer->transferItem()
front\transfer.action.php:46                       Transfer->moveItems()

Undefined index relid

---

src/CommonITILValidation.php

`request send to` -> `request sent to`.

Fix approval sent message grammer

---

src/Inventory/Asset/InventoryNetworkPort.php
tests/functionnal/Glpi/Inventory/Inventory.php

Fix IPNetwork inventory

---

install/migrations/update_9.5.x_to_10.0.0/native_inventory.php

Fix migration when there is no printerlogs/networkportmetrics

---

src/Inventory/Asset/NetworkPort.php
src/NetworkPort_NetworkPort.php

Fix networkport wiring unicity during inventory

---

src/CommonITILObject.php
templates/components/itilobject/fields/priority_matrix.html.twig

Show only priorities used in matrix on ticket creation

Fix Display Priority : Show only priorities used in matrix

---

src/CommonDBTM.php
src/NetworkPort.php
src/NetworkPortInstantiation.php

Try improve links display beetween equipments

---

src/NetworkPort.php

Remove unused NetworkPort:: dynamic property

---

src/Computer.php
src/Monitor.php
src/Peripheral.php
src/Phone.php
src/Printer.php

Add Four columns to computers list
[129] => Monitors / Number of monitors
[130] => Peripherals / Number of peripherals
[131] => Printers / Number of printers
[132] => Phones / Number of phones

Add Number Of Items SearchOptions

---

src/Search.php
src/Toolbox/DataExport.php
tests/units/Glpi/Toolbox/DataExport.php

Enhance CSV/SYLK export cleaning; fixes #11001

---

src/Inventory/Inventory.php
src/Inventory/Request.php

Use configuration for inventory frequency

---

src/Session.php

| New feature?  | o
| Fixed tickets | #11021

Add possible path; closes #11021

---

src/MassiveAction.php

Declare missing properties in MassiveAction

---

src/Item_SoftwareVersion.php

Minor fixes on software sublist

---

src/AbstractITILChildTemplate.php
src/Agent/Communication/AbstractRequest.php
src/CommonDropdown.php
src/CommonITILTask.php
src/CommonITILValidation.php
src/ITILFollowup.php
src/ITILSolution.php
src/Item_Cluster.php
src/Item_Enclosure.php
src/Item_OperatingSystem.php
src/Item_Rack.php
src/NetworkPort.php
src/NetworkPortMigration.php
src/Notification_NotificationTemplate.php
src/PDU_Rack.php
src/ProjectTeam.php
src/RSSFeed.php
src/Rack.php
src/Reservation.php
src/Rule.php
src/RuleAction.php
src/RuleCollection.php
src/RuleCriteria.php
src/RuleDictionnaryDropdownCollection.php
src/RuleDictionnaryPrinterCollection.php
src/RuleDictionnarySoftwareCollection.php
src/RuleImportAsset.php
src/RuleImportComputer.php
src/RuleImportEntity.php
src/RuleRight.php

Fix some PHPStan issues

---

src/Inventory/Asset/Software.php
src/Inventory/Asset/Volume.php
src/Item_Disk.php
tests/functionnal/Glpi/Inventory/Inventory.php

minor issues on inventory logs

---

ajax/reservable_items.php
ajax/reservations.php
js/reservations.js
src/Reservation.php

Fix reservation calendar for simplified interface; fixes #10421

---

js/log_filters.js

prevent submit of parent form when pressing Enter in log/software filters

---

css/includes/components/_racks.scss

regression on rack add icon with upgrade of fontawesome lib

---

src/CommonDBChild.php
src/Item_Disk.php
tests/functionnal/Glpi/Inventory/Inventory.php

don't log disk changes like freesize (and total for zfs)

---

src/Document.php

Fix an error in https://github.com/glpi-project/glpi/pull/10945

check access on wrong ID var

---

css/includes/components/itilobject/_timeline.scss
css/includes/mixins/_badges_fixes.scss

fix timeline badge height and alignment

---

src/CommonITILObject.php
tests/functionnal/RuleTicket.php

Fix actors added by rule on Ticket update

---

inc/caldav/backend/auth.class.php

Prevent usage of SSO systems on CalDAV auth; fixes #11091

---

js/planning.js
src/Planning.php
templates/central/widget_tab.html.twig
templates/components/masonry_grid.html.twig

relayout msnry when planning finished loading on central page

---

src/Application/View/Extension/DataHelpersExtension.php
templates/layout/parts/user_header.html.twig

fix ellipsis on entity completname in glpi header

---

src/Dropdown.php
src/User.php
templates/components/form/fields_macros.html.twig

Fixed while working on fields plugin.

Fix handling of readonly fields

---

inc/config.php
src/Config.php
src/Console/Application.php
src/ITILSolution.php
src/Toolbox.php

| Fixed tickets | #10614, #6458
- Ensure computation is based on realpath; fixes #10614
- Computation based on $CFG_GLPI['url_base'] on CLI context; fixes #6458

Fix $CFG_GLPI['root_doc'] computation

---

src/Toolbox/Sanitizer.php
tests/units/Glpi/Toolbox/Sanitizer.php

Prevent MassiveAction / callable identifier sanitizing

---

src/ProjectTask.php
tests/functionnal/Project.php

Fix auto-percent calculation when adding or deleting tasks

---

css/standalone/marketplace.scss
src/Marketplace/View.php

add changelog icon if plugin declares any

---

src/User.php

Fix css buton on hover (```vcard``` and ```impersonate```)
Before
After

fix(css): fix btn size on hover

---

inc/define.php

Add PassiveDCEquipment to global search types; closes #11008

---

src/Inventory/Asset/Software.php
tests/functionnal/Glpi/Inventory/Inventory.php

| Fixed tickets | #10605
I can't log addition in the `logSoftwares` method as i don't have some id at this point.

log softwares (un)installations into Software and SoftwareVersion objects

---

src/Agent/Communication/AbstractRequest.php
src/Inventory/Inventory.php
src/Inventory/Request.php
tests/InventoryTestCase.php
tests/functionnal/Agent.php
tests/functionnal/Glpi/Inventory/Assets/Computer.php
tests/functionnal/Glpi/Inventory/Assets/NetworkEquipment.php
tests/functionnal/Glpi/Inventory/Assets/Printer.php
tests/functionnal/Glpi/Inventory/Assets/Volume.php
tests/functionnal/Glpi/Inventory/Inventory.php
tests/functionnal/Unmanaged.php

Factorize calls
Prevent useless double JSON encoding; fix tests

Force partial mode on network discoveries

---

.github/workflows/nightly_build.yml

Add persistent paths to nightly builds

---

src/Agent/Communication/AbstractRequest.php
src/Inventory/Conf.php
src/Inventory/Inventory.php
src/Inventory/Request.php

Fix error messages when using import UI

---

src/Toolbox/DataExport.php
tests/units/Glpi/Toolbox/DataExport.php

Fix export encoding issues

---

src/Inventory/Asset/MainAsset.php
src/Inventory/Inventory.php
src/Inventory/Request.php

Fix discovery/inventory data removal

---

src/Inventory/Asset/InventoryNetworkPort.php
src/Inventory/Asset/NetworkPort.php
tests/functionnal/Glpi/Inventory/Assets/NetworkPort.php

import of port ips is on `ips` key not on `ipadress` key

---

.github/actions/test_tests-cache.sh
.github/actions/test_tests-functionnal.sh
.github/actions/test_tests-imap.sh
.github/actions/test_tests-ldap.sh
.github/actions/test_tests-units.sh
.github/actions/test_tests-web.sh
tests/functionnal/Config.php
tests/functionnal/Item_OperatingSystem.php
tests/functionnal/NotificationTarget.php
tests/functionnal/Rule.php
tests/functionnal/Ticket.php
tests/units/DBmysqlIterator.php
tests/units/Html.php
tests/units/Migration.php

Clean tests output

---

ajax/dropdownNotificationEvent.php
ajax/dropdownValidator.php
ajax/impact.php
ajax/ruleactionvalue.php
front/knowbaseitem.php
src/Auth.php
src/Event.php
src/Item_Ticket.php
src/Log.php
src/Search.php
src/Toolbox.php
tests/DbTestCase.php
tests/functionnal/Toolbox.php

There are still many usages of addslashes/stripslashes in codebase, and it may produce bug on edge cases (usage of namespaced itemtypes for instance). I fixed some of them.

Fix some buggy/useless usages of stripslashes

---

src/Inventory/Asset/Camera.php

Like ```DatabaseInstance``` Correctly manage Boolean value for ```flashunit``` key

Correctly manage boolean value for flashunit

---

ajax/dropdownMassiveActionAddActor.php
src/Supplier.php

Add supplier on add_actor massive action & Add is_active to post_getEmpty

Add supplier on add_actor massive action & is_active to post_getEmpty

---

src/RuleMatchedLog.php

display correctly colums for rulematchedlogs

---

src/Item_Rack.php

fix notice on rack

---

ajax/uemailUpdate.php

Min fix - Drop Div uemailUpdate.php

---

src/ChangeTemplate.php

Fix Recurrent Change Locale

---

src/RuleTicket.php

Add Writer to RuleTicket Criteria

---

templates/layout/page_card_notlogged.html.twig

Add a simple class on body index page for custom background

---

src/CommonTreeDropdown.php
src/DbUtils.php
src/Dropdown.php
src/Log.php
tests/functionnal/CommonTreeDropdown.php

Port of #11209 on master. Fixes are not strictly identical, du to sanitization process and UI rendering logic changes.

Fix completename encoding issues

---

templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/form_solution.html.twig
templates/components/itilobject/timeline/form_task.html.twig

fix links between KB and tickets

---

CHANGELOG.md
inc/define.php
install/migrations/update_10.0.x_to_10.1.0.php
tests/functionnal/Update.php

Prepare repository for 10.1.0 version migrations

---

templates/layout/parts/saved_searches.html.twig

Fix saved search panel filter

---

src/Socket.php

Fix check all for Socket massive action

---

src/CommonDropdown.php

Fix replacement dropdown select width

---

src/Socket.php

Missed a fix related to #11274 as I was looking for uses of the class name in HTML elements.

Fix missed element ID fix

---

src/DocumentType.php
src/Html.php

Fix duplicate element IDs on timeline

---

js/modules/Kanban/Kanban.js

Fix some type information in Kanban JSDoc and some minor grammar issues. No changes to code logic were made.

Fix JSDoc typedefs and grammer

---

templates/components/itilobject/service_levels.html.twig

When both parts of a SLM field are hidden, the label is still visible.
https://forum.glpi-project.org/viewtopic.php?id=283335

Fix hidden SLM fields

---

inc/define.php

Add missing location_types
| Fixed tickets | !23801

fix(location): add missing location_types

---

install/empty_data.php

Some rights replacements were missed in the last PR (not including the backup permissions which were left on purpose).

Replace rights with constants

---

css/includes/components/_richtext.scss
css/legacy/includes/_inputs.scss

Fix rendering of tables borders in rich text; fixes #11293

---

src/CommonITILObject.php

Fix permission check for ITIL Kanban

---

src/CommonITILObject.php

| Fixed tickets | #10961 #10912
Since #10647, `CommonITILObject::getTimelineItemtypes()` is used to define the template used to display timeline items, so all entries should be defined even when user has no rights to add/edit corresponding items, in order to display timeline items using the right template.

Fix display of timeline items; fixes #10961

---

src/ITILSolution.php

Handle file upload in Solutions

---

js/planning.js
src/Planning.php

Fix rights checks on planning view; fixes #10667

---

src/Application/View/Extension/FrontEndAssetsExtension.php
src/Html.php
src/Toolbox/FrontEnd.php
tests/units/Glpi/Toolbox/FrontEnd.php
tests/units/Html.php

Hide versions in front-end assets URL

---

templates/generic_show_form.html.twig

| Fixed tickets | #11266
https://forum.glpi-project.org/viewtopic.php?id=283107

Fix missing fields for supplier and contact

---

src/CommonITILObject.php
src/Ticket.php

Fix entity assigning in new ticket form

---

src/CommonDBTM.php
src/Item_OperatingSystem.php
templates/components/form/header.html.twig

don't show any header in os tab

---

src/CommonITILObject.php

retrieve mail actors when reloading new ticket form

---

js/dashboard.js
src/Config.php

don't refresh dashboard every '0' seconds

---

src/Central.php
src/DBmysql.php
src/Update.php

Exclude plugins from alerts related to utf8mb4/unsigned keys

---

src/GLPINetwork.php

fix(glpinetwork): service instead product

---

src/Search.php
src/User.php

| Fixed tickets | internal ref !23760

fix display of user's responsible column

---

src/CommonITILObject.php
src/Ticket.php
templates/components/itilobject/footer.html.twig
templates/components/itilobject/timeline/form_followup.html.twig
tests/functionnal/Ticket.php

| Fixed tickets | internal ref !23737

requester cannot reopen ticket with followup anymore

---

src/Console/Plugin/ActivateCommand.php
src/Console/Plugin/DeactivateCommand.php
src/Console/Plugin/InstallCommand.php

When installation/activation/deactivation of a plugin failed using dedicated CLI commands, result code is still `0` (success).

Fix plugin commands result codes on failure

---

src/CommonTreeDropdown.php
src/Entity.php

Fix root entity storage on PHP 7.4; closes #11322

---

composer.json
composer.lock
src/Config.php

Move symfony/css-selector in production dependencies

---

src/Plugin.php
src/Plugin/Hooks.php

I found some hooks without constant.

constants for more hooks

---

src/KnowbaseItem.php
tests/functionnal/KnowbaseItem.php

Re-add category dropdown to new KB item form

---

src/Reservation.php

| New feature?  | o
| Fixed tickets | #11373

Field no longer exists, closes #11373

---

src/Ajax.php

display tab spinner at a better position

---

css/legacy/includes/_styles.scss
src/CommonGLPI.php

Fix lockedfields display

---

src/CommonITILObject.php

| Fixed tickets | !23862
Due to #8496, when a ticket is created, "new actor" notifications will be sent in addition to the "new ticket" notification that already contains this information.
So if there is 3 observers, following notifications will be received:
- user1 receives 'new observer' notification (observers = user1)
- user1 receives 'new observer' notification (observers = user1, user2)
- user2 receives 'new observer' notification (observers = user1, user2)
- user1 receives 'new observer' notification (observers = user1, user2, user3)
- user2 receives 'new observer' notification (observers = user1, user2, user3)
- user3 receives 'new …

Do not send 'new actor' notifications on ticket creation

---

templates/components/itilobject/actors/field.html.twig

| Fixed tickets | #11384
required tag was not placed on select tag (on option tag) and a TODO reliquate was present
Also hidden var didn't called the good methods

fix mandatory actors

---

src/CommonITILObject.php

Add search option for ITIL template

---

ajax/dropdownTicketCategories.php
templates/components/itilobject/fields_panel.html.twig

reload category dropdown when ticket's type change

---

src/CommonITILObject.php

Fix status update on actors assign

---

src/CommonITILObject.php
templates/components/itilobject/service_levels.html.twig

| Fixed tickets | fixes #11410
Issue caused by bad refactor in #10886.

Fix predefined ITIL Object fields

---

front/dropdown.common.form.php

Fix device form pager

---

src/RuleAction.php

Fix missed dropdown_status for rules

---

templates/components/itilobject/timeline/form_task.html.twig

Fix task templates

---

lib/bundles/base.js
package-lock.json
package.json
templates/components/form/fields_macros.html.twig

replace jscolor by spectrum again

---

templates/components/form/fields_macros.html.twig
templates/pages/admin/inventory/upload_form.html.twig

fix inventory form

---

install/empty_data.php

| Fixed tickets | !23916
The automatic action for creating Change surveys was missing from the empty data file in the combined change improvements branch. It is properly registered only during an update.

Add missing Change Survey cron task

---

templates/components/user/link_with_tooltip.html.twig

Prevent issue when rendering link to invalid user; fixes #11496

---

src/Html.php

Add copy and paste to tinyMCE context menu

---

templates/components/itilobject/selfservice.html.twig

Add missing form hooks for self service form

---

front/planningexternalevent.form.php
src/PlanningExternalEvent.php
templates/components/form/buttons.html.twig

Allow to detach an instance from a series to create an independent event.
| Fixed tickets | !23868

feat(planning): detach instance from serie

---

package-lock.json
package.json

update @tabler/icon to 1.68

---

src/Project.php

Hide templates from Project Kanbans

---

css/standalone/dashboard.scss

display correctly dropdown'sicon in dashboard

---

css/includes/pages/_search.scss
css/legacy/includes/_responsive_fixes.scss
templates/components/search/table.html.twig

Follow #11521
Avoid empty space when not enough columns to fill

avoid to set width on responsive, min-width is better

---

src/Search.php
tests/functionnal/Search.php

Fix escaping; closes #11542

---

src/Inventory/Inventory.php

| Fixed tickets | #10356, #11405
Replace #11518

Fix inventory temp file not removed on import error

---

src/Socket.php

There is no networkport search list; closes #11535

---

src/RuleCommonITILObject.php

Allow multiple group approvals

---

front/lockedfield.form.php
install/migrations/update_10.0.0_to_10.0.1/lockedfields.php
install/mysql/glpi-empty.sql
src/CommonDBTM.php
src/Inventory/Inventory.php
src/Lockedfield.php
templates/pages/admin/inventory/lockedfield.html.twig
tests/functionnal/Lockedfield.php

Add global locks

---

CHANGELOG.md
ajax/displayMessageAfterRedirect.php
js/misc.js
src/Html.php
templates/components/messages_after_redirect_toasts.html.twig

| Fixed tickets | internal ref !23761
Fixed at least 2 issues:
- marketplace actions adding multiple (and superposed) `.toast-container`
- marketplace display the same message multiple time when repeating actions 
the last was probably due to the toast initialization was recalled on already existing toast.
I fixed by checking the `.show` class is not present and removing toast after hidden event

fix markeplace popups (toasts) issues

---

front/item_line.form.php
inc/define.php
inc/relation.constant.php
install/migrations/update_10.0.x_to_10.1.0/items_lines.php
install/mysql/glpi-empty.sql
src/CommonDBTM.php
src/Computer.php
src/Item_Line.php
src/Line.php
src/MassiveAction.php
src/NetworkEquipment.php
src/Peripheral.php
src/Phone.php
src/Printer.php
tests/bootstrap.php
tests/functionnal/Item_Line.php
tests/functionnal/MassiveAction.php
tests/web/APIRest.php

| Fixed tickets | !23460
Allow linking lines to items directly without needing a simcard.

Direct linking for Lines to Items

---

CHANGELOG.md
css/includes/_base.scss
inc/define.php
install/empty_data.php
install/migrations/update_10.0.x_to_10.1.0/configs.php
install/mysql/glpi-empty.sql
js/glpi_dialog.js
src/Config.php
templates/components/messages_after_redirect_toasts.html.twig

Add user preference to choose which corner the toast notifications show in.

Configurable toast location

---

css/includes/components/_mini-tabs.scss

fix mini switch using font awesome

---

templates/components/itilobject/fields_panel.html.twig

Add missing required mark for associated items

---

src/Plugin.php

Fix loading of plugin language not defined in $CFG_GLPI

---

src/Agent.php
src/Computer.php

add agent searchoptions into Computer

---

composer.json

Drop IRC link and use HTTPS protocol for all other links.

Update links in composer file

---

src/Inventory/Asset/Antivirus.php

Prevent SQL issue with PHP8; closes #11603

---

src/Inventory/Asset/Monitor.php
tests/functionnal/Glpi/Inventory/Assets/Monitor.php
tests/functionnal/Glpi/Inventory/Inventory.php

Handle monitors models and types; closes #11604

---

src/Agent.php

Fix Agent last_contact SO datatype

---

src/Rule.php
src/RuleAction.php
src/RuleCriteria.php

Fix encoding issues in rules actions/criteria form

---

src/Inventory/Asset/Monitor.php
tests/functionnal/Glpi/Inventory/Assets/Cartridge.php
tests/functionnal/Glpi/Inventory/Assets/Monitor.php

Ensure monitors are updated

---

install/empty_data.php
install/migrations/update_10.0.0_to_10.0.1/configs.php
src/Config.php

Inventory frequency

---

src/NotificationTemplateTranslation.php

Notifications: fix tag display for itemtype with namespace

---

src/Computer_Item.php

Prevent locking fields on contact autoupdate

---

src/Html.php
src/Lock.php

Fix lock form

---

src/Search.php

filter Reservation api request by entities

---

install/empty_data.php
install/migrations/update_10.0.0_to_10.0.1/fixaction.php

Improve first user regexp; closes #11565

---

src/Unmanaged.php

Fix delete/purge rights

---

install/empty_data.php
install/migrations/update_10.0.0_to_10.0.1/configs.php
src/Config.php
src/Inventory/Conf.php

Move inventory frequency conf to inventory conf

---

src/CommonITILObject.php
templates/components/itilobject/actors/field.html.twig

Fix use notification option during ITIL creation

---

src/Session.php
src/User.php

Follow #11634 (it also fix an issue with the true parameter on `Profile_User::getUserProfiles`)

display errors when impersonate is not possible

---

front/report.location.list.php
front/report.socket.list.php

Fix network report queries

---

src/Group.php

Fix undefined variable in Group class

---

README.md
css/install.scss
install/install.php
templates/install/accept_license.html.twig

1. Fix missing licence content.
2. Do not ask anymore to user if he accept or refuse the licence.
3. Enhance translation link styles.

Fix licence step in install

---

src/Features/Clonable.php

Do not suffix cloned relations from template

---

front/ticket.php
src/Plugin/Hooks.php
src/Search.php

Added a hook to the ticket list.
Required for [https://github.com/pluginsGLPI/news/pull/98](https://github.com/pluginsGLPI/news/pull/98)
| Fixed tickets | !23784

feat(ticket): add hook

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

Run tests on MariaDB 10.8

---

templates/components/masonry_grid.html.twig
templates/pages/self-service/home.html.twig

Do not add cards without content to the public helpdesk homepage.

Hide empty cards on self-service homepage

---

templates/components/itilobject/actors/field.html.twig

filter actors only when a requester is already set

---

inc/define.php
locales/es_EC.po

Add new language from transifex

---

src/CommonDBTM.php

clean saved input also when no updates done

---

package-lock.json
package.json
src/Html.php
webpack.config.js

Use v6 lang files, as we are now using TinyMCE v6 since #11430 .

Fix TinyMCE langs

---

src/CommonITILObject.php
tests/functionnal/Change.php
tests/functionnal/ITILSolution.php

Do not set assigned status on invalid itemtypes

---

src/RuleTicketCollection.php

Follow https://github.com/glpi-project/glpi/pull/11728#pullrequestreview-992679969

avoid duplication of actors

---

src/Console/Config/SetCommand.php
src/Inventory/Conf.php

Fix config:set command for inventory context

---

src/NotificationTargetSoftwareLicense.php

Adding a notification tag to have the licence entity
| Fixed tickets | !23886

fix(notification): tag license.entity

---

composer.lock

Update inventory lib; closes #11801

---

src/Alert.php
src/CommonITILValidationCron.php
src/Entity.php
src/NotificationTargetCommonITILObject.php
src/NotificationTargetTicket.php

- Adding intermediate values for the frequency
- Adding an event to distinguish from `validation` event
| Fixed tickets | !23424

feat(approval reminder): enhancement

---

front/softwarelicense.form.php
templates/pages/management/softwarelicense.html.twig

Fix software license form

---

js/modules/Kanban/Kanban.js

| Fixed tickets | #11802
Fix issue with select2 dropdown breaking after adding the first item with the form.
Fix display of the close button in the add item form.

Kanban add item form fixes

---

CHANGELOG.md
inc/define.php
install/migrations/update_10.0.1_to_10.0.2.php
install/mysql/glpi-10.0.2-empty.sql
tests/functionnal/Update.php

Prepare 10.0.2 update process

---

src/Inventory/Asset/Antivirus.php
src/Inventory/Asset/Camera.php
src/Inventory/Asset/Cartridge.php
src/Inventory/Asset/Device.php
src/Inventory/Asset/Drive.php
src/Inventory/Asset/InventoryAsset.php
src/Inventory/Asset/InventoryNetworkPort.php
src/Inventory/Asset/MainAsset.php
src/Inventory/Asset/Monitor.php
src/Inventory/Asset/NetworkEquipment.php
src/Inventory/Asset/NetworkPort.php
src/Inventory/Asset/Peripheral.php
src/Inventory/Asset/Printer.php
src/Inventory/Asset/RemoteManagement.php
src/Inventory/Asset/Software.php
src/Inventory/Asset/VirtualMachine.php
src/Inventory/Asset/Volume.php
src/Inventory/Conf.php
src/Inventory/Inventory.php
src/Inventory/Request.php

Fix multiple potential bugs found with the PHPStan static analysis tool and a review of the PHPDoc.
Summary of changes:
- The delete method of CommonDBTM should be called with a boolean for the force parameter even if it historically used an integer. The PHPDoc for the method properly typehints it as a boolean and internally, the method can handle it since it only checks the truthiness of the value.
- Fixed cases where the type in a PHPDoc block was not specific enough (InventoryAsset used but MainAsset methods used and always expected)
- Avoiding cases where variables may not be declared yet
- Missing method/property …

Fix multiple issues with Inventory code and PHPDoc

---

src/RuleCollection.php

| Fixed tickets | Ref #11860 (Reported issue seems to be the opposite of the current behavior?)

Fix rule test URL detection for plugins

---

front/planningexternalevent.form.php
src/PlanningExternalEvent.php

Detach instance: There was a right's inconsistency between displaying the button and executing the action.
| Fixed tickets | !24197

fix(planning): check right

---

src/Migration.php
tests/units/Migration.php

Fix itemtype renaming migration strings

---

src/CommonITILObject.php

Handle bad return for timeline_answer_actions hook

---

ajax/planningcheck.php
src/Planning.php
templates/components/itilobject/timeline/form_task.html.twig

Availability from a task (ticket, change, problem) was never displayed.
| Fixed tickets | !24166

fix(ticket task): availability not displayed

---

src/Lockedfield.php

Permit global lock on entities_id field; refs #11853

---

index.php
templates/pages/login.html.twig

```redirect``` from URL no longer work. 

fix(core): re add redirect from index.php

---

src/Item_SoftwareLicense.php

Fix software licence assigned elements list

---

src/Inventory/Asset/InventoryAsset.php
tests/functionnal/Glpi/Inventory/Assets/Monitor.php
tests/functionnal/Glpi/Inventory/Assets/Peripheral.php
tests/functionnal/Glpi/Inventory/Assets/Printer.php

Test global management on peripherals and monitors

---

css/includes/_base.scss
css/includes/_palette_dark.scss
templates/components/itilobject/actors/field.html.twig
templates/components/user/info_card.html.twig

Add user info tooltip to actor fields

---

src/RSSFeed.php

Fix RSS URL handling

---

src/Cartridge.php
src/Consumable.php

Fix alarm threshold value in notifications

---

src/MailCollector.php
tests/emails-tests/32-html-with-attributes-on-body.eml
tests/imap/MailCollector.php

Fix <body> parsing on collected emails

---

install/empty_data.php
install/migrations/update_9.5.x_to_10.0.0/recurrentchange.php

Caught by end to end tests (Cypress) during prototyping.

Add missing default recurring change rights

---

src/Printer.php
tests/functionnal/Glpi/Inventory/Assets/Cartridge.php

Remove cartridge info along with printer; closes #11951

---

src/CommonDBTM.php
src/Config.php
tests/functionnal/Glpi/Inventory/Assets/Monitor.php
tests/functionnal/Glpi/Inventory/Assets/Peripheral.php
tests/functionnal/Glpi/Inventory/Assets/Printer.php

Fix constant name

---

src/Domain.php
templates/generic_show_form.html.twig

Fix domain creation/registration dates search options

---

src/Lock.php

Show globals for current itemtype only; refs #11936

---

src/Api/API.php

Try fix tests

---

src/CommonDevice.php
src/Inventory/Asset/Device.php
tests/functionnal/Glpi/Inventory/Inventory.php

Prevent log on import

---

src/Blacklist.php
src/Inventory/Asset/MainAsset.php
tests/functionnal/Glpi/Inventory/Assets/Computer.php

Rely on mserial if serial is wrong

---

src/Auth.php
src/AuthLDAP.php
src/Contact.php
src/Entity.php
src/Supplier.php
src/User.php
templates/generic_show_form.html.twig

Fix registration_number locale for entity 

Fix registration_number locale for entity

---

src/NetworkEquipment.php
src/Phone.php
src/Printer.php

Add missing SO
usefull for https://github.com/glpi-project/glpi-inventory-plugin/pull/153

fix(so): add missing SO

---

src/CommonITILObject.php
src/Project.php

1. Only fetch required columns from the database
2. Do not fetch data for drop-only columns like the Closed status for ITIL Objects as no cards are displayed in those columns
3. When there are no columns that are being fetched, return nothing rather than querying all columns (statuses) and filtering the extra data out later
4. Use static closures when possible (micro-optimization done when reviewing Kanban-related code). This probably has no noticeable improvement on its own.

Improve Kanban performance

---

src/Reservation.php

Reservation popup for self-service display login of user - not his complete name

Fix Reservation User Name

---

src/Console/Database/CheckSchemaIntegrityCommand.php

plugins must provide a new function plugin_formcreator_getSchemaPath in setup.php
which returns null if the feature is not supported, or the path to the .sql file as a string
example 
```php
/**
* Get the path to the empty SQL schema file
*
* @return string|null
*/
function plugin_formcreator_getSchemaPath(): ?string {
return Plugin::getPhpDir('formcreator') . '/install/mysql/plugin_formcreator_empty.sql' ;
}
```
see https://github.com/pluginsGLPI/formcreator/pull/2854
Output on error in db integrity check of the plugin
```
bin/console glpi:database:check_schema_integrity -p formcreator
Table schema differs for table "glpi_plugin_formcreator_issues".
--- Original
+++ New
@@ @@
`is_recursive` tinyint NOT NULL DEFAULT 0,
`items_id` int NOT NULL DEFAULT 0,
`itemtype` varchar(255) NOT NULL …
```

allow plugins to check their DB integrity

---

src/Inventory/Asset/MainAsset.php

Reload item when update.
Usefull for -> https://github.com/glpi-project/glpi-inventory-plugin/pull/159

fix(inventory): reload updated item anyway

---

src/Group_User.php

Sometimes users in a group are not displayed because of entities restrictions: 
If you can see the group then you should also be able to see all its associated users in the "Users" tab.

Groups: fix user list (no entities restrictions)

---

src/CommonDBTM.php
src/CommonITILObject.php
templates/components/itilobject/fields/status.html.twig

Fix display of allowed statuses during creation

---

composer.lock

Locales lint is currently not executed. https://github.com/glpi-project/tools/pull/55 fixes this problem.

Fix locales lint test

---

src/DisplayPreference.php

The current display preferences form has a few issues: 
As you can see on this image, the columns show do not match (1 and 2).
The `ID` columns should be displayed at the top of table (2) as a fixed column (this case is specific to `CommonITILObject`).
There is another issue, despite `Entity` and `ID` being fixed columns, it is still possible to add them manually and move them arround (3).
Adding and moving these columns has no impact on the display (as they are fixed columns) and obviously shouldn't be possible.
After changes:
* `ID` is shown as the first column for tickets:
* `Entity` column can't be added
* `ID` column can't be added
| …

DisplayPrefs: Fix fixed columns

---

composer.lock
tests/functionnal/Agent.php
tests/functionnal/Glpi/Inventory/Inventory.php

Just to add tests. Will fail until updated inventory_format has been fixed

Check agent tag is correct in all cases

---

templates/components/form/header.html.twig

Preserve in_modal tracking in form submissions

---

src/Item_SoftwareVersion.php

Add pager to bottom of software installation list

---

src/Agent/Communication/AbstractRequest.php
tests/functionnal/Toolbox.php
tests/units/Glpi/Inventory/Request.php
tests/web/Glpi/Inventory/Inventory.php
tests/web/Glpi/Inventory/Request.php

Use new method to check for valid JSON

---

tests/js/Search/Table.test.js

Add test for #12058

---

src/Agent/Communication/AbstractRequest.php
tests/web/Glpi/Inventory/Request.php

Revert "Use new method to check for valid JSON (#12048)"

---

src/CommonITILObject.php
tests/functionnal/Ticket.php

| Fixed tickets | see https://github.com/glpi-project/glpi/issues/11671#issuecomment-1168599106

Fix auto-assign from category/item

---

ajax/central.php

Fix condition so also tasks are displayed on Central view
| Fixed tickets | #12124

Add CommonITILTask to central view

---

src/Stat/Data/Sglobal/StatDataTicketAverageTime.php
src/Stat/Data/Sglobal/StatDataTicketNumber.php

Fix Global Stats datas

---

templates/pages/login.html.twig

Fix "login to your account" not being centered on login page.

---

src/Item_RemoteManagement.php

Regarding to MeshCentral inventory https://github.com/glpi-project/glpi-agent/pull/163 and https://github.com/glpi-project/glpi-agent/issues/135 these changes are oriented to the inclusion of this type of inventory in the Item_RemoteManagment class. After this, it is expected that as part of the native and GLPI agent inventory, there will be a new type of Remote Managment ID that has a Meshcentral node.
> | Q             | A
> | ------------- | ---
> | Bug fix?      | no
> | New feature?  | yes
> | BC breaks?    | no
> | Deprecations? | no
> | Tests pass?   | yes
> | Fixed tickets | 
>

Adding MeshCentral capability.

---

src/CommonITILObject.php

Fix actors filtering on item creation

---

src/CommonITILObject.php
src/CommonITILValidation.php

| Fixed tickets | #12141
Alternative to #12154.

Fix global validation status update

---

src/NetworkPortInstantiation.php

Permit to select network card on all supported types

---

templates/layout/parts/page_header.html.twig

Hide global search if needed
| Fixed tickets | !!24393

feat(ui): hide global search if needed

---

src/RuleImportAsset.php

[GLPI 10 Bugfixes] Fix Rule SQL errors Import Asset

---

composer.lock
src/CommonDBTM.php
src/Inventory/Asset/Printer.php
templates/components/form/inventory_info.html.twig
tests/functionnal/Glpi/Inventory/Assets/Printer.php
tests/functionnal/Glpi/Inventory/Inventory.php

add snmp credential and last update for NetworkEquipement and Printer

feat(inventoriable): add snmp credential and last update for NetworkEquipement and Printer

---

inc/define.php

[GLPI 10.0 Bugfixes] Add Line To User & Group

---

src/Item_RemoteManagement.php

Created a pull request on GLPI-AGENT: https://github.com/glpi-project/glpi-agent/pull/179
Referenced request: https://github.com/glpi-project/glpi-agent/issues/35
| Fixed tickets | https://github.com/glpi-project/glpi-agent/issues/35

Add SupRemo in Remote management

---

composer.json
composer.lock

Upgrade friendsoftwig/twigcs to 6.0

---

css/includes/pages/_search.scss
src/Ticket.php

9.5: 
10:
After fix:
| Fixed tickets | !24335

Central views: add missing priority color on short ticket lists

---

src/Project.php

| Fixed tickets | #12193
Not sure if it should be considered as a bug or a missing feature.
I guess templates for any itemtype should propose this feature.

Handle autoname on projects

---

src/Central.php
templates/central/widget_tab.html.twig

fix(central): show central warnings only on first tab

---

src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php

Even if it is not a bug, for GLPI that have been firstly installed and/or updated to 9.5.0, 9.5.1, 9.5.2 or 9.5.3, and using MySQL as DB server, the database integrity check will detect following diff, due to the fact that MySQL does not accept default value on a TEXT field.
```
--- Original
+++ New
@@ @@
`max_depth` int NOT NULL DEFAULT 5,
`pan_x` float NOT NULL DEFAULT 0,
`pan_y` float NOT NULL DEFAULT 0,
-  `positions` text NOT NULL,
+  `positions` text NOT NULL DEFAULT '',
`show_depends` tinyint NOT NULL DEFAULT 1,
`show_impact` tinyint NOT NULL DEFAULT 1,
`zoom` float NOT NULL DEFAULT 0,
PRIMARY KEY (`id`)
)
```
This …

Fix unwanted glpi_impactcontexts.positions diff detection on MySQL

---

src/Notepad.php

Fix missing avatar image in notes

---

src/Session.php

Fix right value in access logs

---

templates/components/itilobject/answer.html.twig

Fix Load KB Article From Ticket Solution

---

templates/components/itilobject/timeline/form_solution.html.twig

When trying to add a solution, a null value is displayed so the form is submitted incorrectly by default:
Expected behavior shoul be defined with id as 0:

Solution type default should be 0 id.

---

src/User.php

Fix undefined name index in used item list

---

src/Planning.php
tests/functionnal/Planning.php

Fix planning colors for groups over 15 users

---

js/modules/Kanban/Kanban.js

Fix tooltip for team members with quote in name

---

ajax/marketplace.php
js/marketplace.js
src/Marketplace/Api/Plugins.php
src/Marketplace/View.php

Enforce types of request params in Marketplace ajax endpoint

---

src/Project.php

Enable rich text for Project descriptions

---

src/Session.php

| Fixed tickets | #12032
Before impersonating another user, preserve the current language, debug mode flag, profile and entity.
After impersonation, the language, debug mode flag, profile and entity will be restored.
This should make impersonation seem more seamless to the user.

Restore entity and profile after stopping impersonate

---

index.php
src/Auth.php
src/NotificationTarget.php
src/NotificationTargetCommonITILObject.php
src/NotificationTargetSavedSearch_Alert.php
tests/functionnal/NotificationTarget.php
tests/functionnal/NotificationTargetSavedSearch_Alert.php

| Fixed tickets | #12212
This should fix an issue with the encoding of the inner query parameters.

Fix saved search alert notification URL

---

src/Plugin.php

Follows #12288.
When a plugin has another plugin in its requirements, `Plugin::isActivated()` is called during `Plugin::checkPluginState()` execution, but as `Plugin::$activated_plugins` is not initialized yet, it always returns `false`. In this case, a DB query should be performed.

Fix plugin requirement check

---

templates/components/infocom.html.twig

Fix missing delivery number

---

src/CommonITILObject.php

Fix document date in timeline

---

src/NotificationMailing.php

Fix sender used in test notification

---

front/notificationmailingsetting.form.php

Fix handling of special chars in SMTP password

---

src/Features/PlanningEvent.php

Prevent invalid value for RRULE interval

---

CONTRIBUTING.md

Minor typo fixes in Contributing file

---

src/Item_RemoteManagement.php

I wrote some (really small) modifications to support [RustDesk](https://rustdesk.com), an open-source remote management software.
I prepared the PR for the agent also: https://github.com/glpi-project/glpi-agent/pull/193

Initial RustDesk support

---

front/config.form.php
front/notificationajaxsetting.form.php
front/notificationmailingsetting.form.php
src/Config.php
src/NotificationSettingConfig.php

| Fixed tickets | #12267
Replace #12270

Workaround for config record ID requirement

---

templates/components/form/fields_macros.html.twig
templates/components/itilobject/timeline/approbation_form.html.twig
templates/components/itilobject/timeline/form_followup.html.twig
templates/components/itilobject/timeline/form_solution.html.twig
templates/components/itilobject/timeline/form_task.html.twig
templates/components/itilobject/timeline/form_validation.html.twig
templates/components/itilobject/timeline/simple_form.html.twig

Fix entity restriction in user mentions feature
